### ISSUE TITLE
How to custom select / dropdownlist when add row data

### ISSUE THREAD

**Issue by theerat** [mbrn/material-table#1001]
how i can do it ? when i want to add row data, i can custom field to select and bind data array

thanks.

![image](https://user-images.githubusercontent.com/13750967/63237840-c3942300-c26d-11e9-8b93-d7095ebe4769.png)

**Comment by LouisJS** [comment]
You can find an example of simple select option on this [codesandbox](https://codesandbox.io/s/material-demo-dldgm)

**Comment by theerat** [comment]
thank you. i can do it
