### ISSUE TITLE
expandTreeForNodes optional on filtering/searching

### ISSUE THREAD

**Issue by simromm** [mbrn/material-table#1008]
**Is your feature request related to a problem? Please describe.**
The default behavior is to expanded  when child elements match which is great. 
But I would like to avoid  this expand on filtering/searching when child elements match.

**Describe the solution you'd like**
To have an option to control this expand  when  child elements match on filtering/searching.

**Describe alternatives you've considered**
None for now.

**Additional context**
None

**Comment by simromm** [comment]
Any update?

**Comment by rozwell** [comment]
Quick solution for those who would like to have control over the expansion:
`
parentChildData={(row, rows) => {
    row.tableData.isTreeExpanded = false; // overrides fixed behavior after filtering/searching in: https://github.com/mbrn/material-table/blob/a4659411489b1fb469096f92505b11a5f6157a6c/src/utils/data-manager.js#L856
    return rows.find(v => v.id === row.parent_id);
}}
`
