### ISSUE TITLE
Changing component state in editComponent handler

### ISSUE THREAD

**Issue by oreshkoandrei** [mbrn/material-table#1012]
Hi everyone. I want to change component state in edit component handler, but input value is not actually changes. I tried to execute setState in timeout and noticed, that changes i do disappear for some reason.

In fact, i want to remember last changed column name.

This is what my custom edit component looks like
![image](https://user-images.githubusercontent.com/24525691/63363025-8453f800-c37b-11e9-9af0-6743d6eda9c8.png)

**Comment by seanharr11** [comment]
I have a similar issue with the `EditComponent` (_in my case a `TextField`_) rendering once before input has been entered, and then again after the first keystroke in the `TextField`, causing the initial character to be wiped due the component being re-rendered.

**Comment by oreshkoandrei** [comment]
> I have a similar issue with the custom `EditComponent` (_in my case a `Downshift` component_) rendering once before input has been entered, and then again after the first keystroke in the `DownShift`, causing the initial character to be wiped due the component being re-rendered.

yeah, sounds similar
have you come up with any temporary solution for your problem though ?

**Comment by seanharr11** [comment]
> > I have a similar issue with the custom `EditComponent` (_in my case a `Downshift` component_) rendering once before input has been entered, and then again after the first keystroke in the `DownShift`, causing the initial character to be wiped due the component being re-rendered.
> 
> yeah, sounds similar
> have you come up with any temporary solution for your problem though ?

Negative - I am wondering if we can prevent the `EditComponent` from re-rendering via implementing `shouldComponentUpdate`, and checking to see if `props.index` has changed. The container `EditComponent` shouldn't be re-rendering.

Here's a visual of my specific problem: 
![downshift-material-table-error](https://user-images.githubusercontent.com/3341490/63439001-45658700-c3fb-11e9-92e6-a48e30875913.gif)

**Comment by seanharr11** [comment]
My problem turned out to be the following issue:
1. I had a component wrapping `MaterialTable` (_the `parent`_)
2. I was holding onto a `tableRef` using `useRef`
3. The `parent` component was re-rendering the first time that `editComponent` had data entered into it, forcing the `editComponent` itself to re-render.

My solution was to `memoize` the `editComponent` handler, and to drop the `tableRef`.

**Comment by oreshkoandrei** [comment]
In my case it seems like somehow related to Container overriding like here
          components={{
              Container: (props) => <div>{props.children}</div>,
          }}

If i delete it from my MaterialTable tag, it starts to work as expected

**Comment by MacGyver98** [comment]
Hi people!    I see this is closed, and now i'm suffering this issue. I could'n use state on editComponent.

I'm new on React and couldn't understand right the solutions offered here.  Maybe some of you give me an explanation for dummies.

Thanks in advance.

**Comment by redamsy** [comment]
i have the same issue, i am using editComponent and inside i have a component which sends http request, this leads to exiting the edit mode , can anyone help?? urgent

**Comment by foriinr** [comment]
A year later and I have now run into this issue.  Setting any state variable during the edit mode causes the the exiting of the edit mode.  If you go back to material table version 1.52.0 then it behaves as expected and quite nicely.  The issue with going back is there is validation missing (probably among other features).
