### ISSUE TITLE
How to programmatically collapse expanded row(s) with detailPanel enabled?

### ISSUE THREAD

**Issue by TheHalcyonSavant** [mbrn/material-table#1013]
I'd like to use material-table like an accordion, i.e. with enabled detailPanel, when the user expand one row the other ones should collapse.

I'd like to have a custom method, something like `rowData.tableData.collapse()`

I've checked all issues and source code, I couldn't find such a method.

Thanks

**Comment by Joeanca** [comment]
There is an option detailPanelType multi or single. It may be what you are looking for. [relevant documentation under options](https://material-table.com/#/docs/all-props)

**Comment by TheHalcyonSavant** [comment]
Thank you @Joeanca
