### ISSUE TITLE
Can a dropdown filtering be done seperately from the table .

### ISSUE THREAD

**Issue by gmumdzhiev** [mbrn/material-table#1016]
Hey guys i don't know if this is possible , but i would like to have the filtering with the dropdown on a seperate component outside of the table , but still to filter the current table . Is this thing possible ? And if it is can i have an example ? 
![tabledropdown](https://user-images.githubusercontent.com/32012354/63503994-df4b3380-c4d0-11e9-896c-0087c9c8e83a.jpg)

**Comment by airen29** [comment]
I would love to have that functionality also. It's missing so much.

For example, if I have a lookup for a row and want to choose only 3 or 5 possible options in the dropdown menu, that would be so nice.

**Comment by gmumdzhiev** [comment]
@airen29  Exactly the case that i want to build on .  This may work , but i'd haven't tested it yet : 
[https://stackoverflow.com/questions/57609155/material-table-is-there-a-way-to-seperate-filtering-from-the-table-react/57611274#57611274](url)

**Comment by airen29** [comment]
@gmumdzhiev I feel you.  

There should be an option to let developer choose different array (or map of the array) for the dropdown menu. It should not take automatically array from the `column`.   

For example. 

- I have a list of users.   
- I've a column name `Access`. 
- In the table I'll see all the users with all the Accesses - f.e. `Junior Developer`, `Tester`, `Manager`, `Accountant`, `Senior Developer`, etc... (you get it)
- Given that I'm a `Senior Developer` I can create only `Junior Developer` and a `Tester`. I cannot create a `Manager`, `Accountant` or another `Senior Developer`.
- Right now if I add a new row (that have a functionality to create a new user tied with current `onRowAdd` event), I can select any role that is already listen via `lookup` in given cell `Access`. I should not be able to do that but with current approach, there is no simple way how to achieve different `dropdown` menu's but only to use one provided by default `Access` column.

I hope it explains a lot and this functionality would be good. 

Let developer take care of mapping of the array or about the logic behind (like in lookup function that is connected to `Redux` state, etc..) but also let developer to choose what he wants to show in the `dropdown` separately of the things he wants to show in the table column itself :) 

Thanks a lot!

**Comment by Vitorbnc** [comment]
Hey! Any progress on this issue? Is filtering outside the table a planned feature?
