### ISSUE TITLE
grouping and selection do not work together

### ISSUE THREAD

**Issue by timeichfeld-msa** [mbrn/material-table#1017]
Behavior:
Check box does not appear in the GroupRow when options [ selection: true ] is set 

Expected:
when selecting the options [grouping: true, selection: true]  a checkbox should appear in the GroupRow to toggle all items in the group.

Actual:
no Checkbox is present in the GroupRow.

**Comment by pradeepravi-cse** [comment]
Facing the same issue

**Comment by zsolt-halo** [comment]
+1

**Comment by christanfoden** [comment]
yep
