### ISSUE TITLE
Is there a way to color a row based on value?

### ISSUE THREAD

**Issue by clevernyyyy** [mbrn/material-table#1019]
I'm looking to color rows of the table based on a value.  For example, if you consider a table in which rows "fail" or "pass" and want to color them red and green respectively.  How would I do that?

**Comment by clevernyyyy** [comment]
Figured it out, buried in the docs, not where I expected.  👍 
Closing issue.

```
      options={{
      	paging:false,
      	rowStyle: rowData => ({
      		backgroundColor: (rowData['valid'] === 'true' ? '#e4f9e4' : '#ffb9b9')
      	})
      }}
```

**Comment by Totalbug92** [comment]
> Figured it out, buried in the docs, not where I expected. 👍
> Closing issue.
> 
> ```
>       options={{
>       	paging:false,
>       	rowStyle: rowData => ({
>       		backgroundColor: (rowData['valid'] === 'true' ? '#e4f9e4' : '#ffb9b9')
>       	})
>       }}
> ```

Could you tell me where in the docs you found this ? :)
