### ISSUE TITLE
Weird stuff leaks into the DOM

### ISSUE THREAD

**Issue by jayarjo** [mbrn/material-table#1020]
Weird stuff leaks into the DOM. Screenshot:

![Screenshot from 2019-08-23 16-10-25](https://user-images.githubusercontent.com/150075/63591691-8a86e600-c5c0-11e9-917c-676f0dfea94c.png)

Also observable in the editable example on the site: https://material-table.com/#/docs/features/editable

**Comment by jayarjo** [comment]
I see you spread stuff from externals onto internals all over the place, this might be the reason. Maybe it makes sense to filter it down somehow.

**Comment by buszmen201** [comment]
can confirm, I don't think it should be injected that way :( 

![image](https://user-images.githubusercontent.com/29873044/64338784-de42f780-cfe2-11e9-8829-df83ed91a5b9.png)

**Comment by brendon1555** [comment]
I can take a look at this. I'll make a pull request with the cleanup.
