### ISSUE TITLE
Material logic - Invalid button action title 

### ISSUE THREAD

**Issue by FroggDev** [mbrn/material-table#1033]
Hi,

The titles of the actions button are set in the **span** instead of the **button** tag as it should be in materialize.

Expected
![2019-08-26 11_14_58-DevTools - myunip-dev uniprevoyance fr_sinistres_en_ligne_arret-de-travail - Ope](https://user-images.githubusercontent.com/3765812/63680049-0799a180-c7f3-11e9-9146-49c34ed6d305.png)

Actual result
![2019-08-26 11_15_33-DevTools - myunip-dev uniprevoyance fr_sinistres_en_ligne_arret-de-travail_histo](https://user-images.githubusercontent.com/3765812/63680082-197b4480-c7f3-11e9-81b6-6de6bd332642.png)

Thanks

**Comment by jayarjo** [comment]
@FroggDev as someone having an insight in this, could you please submit a PR?
