### ISSUE TITLE
How to change edit field value format if the type = "date"?

### ISSUE THREAD

**Issue by ElvisWong** [mbrn/material-table#1038]
I wish to display the date with the format like this "dd/MM/yyyy" instead of "MM.dd.yyyy", is there any way to do it for edit fileld with the type "date"?

**Comment by MathieuCh** [comment]
You could use the 'render' props on columns => 

```
{ 
    field: 'validated_at',
    title: 'Hi'
    type: 'date',
    render: rowData => moment(rowData.validated_at).format('DD/MM/YYYY')
}
```

**Comment by SpyrosPac** [comment]
I think the question was for editable field, the above is applying the format for data after being saved or when loaded.
To provide a format on edit field, the only way I figured was to use "editComponent" column property like this:
```
{
       title: "Date",
       field: "date",
       type: "date",
       editComponent: props => (
              <MuiPickersUtilsProvider utils={DateFnsUtils} 
                          locale={props.dateTimePickerLocalization}>
                     <DatePicker
                            format="dd/MM/yyyy"
                            value={props.value || null}
                            onChange={props.onChange}
                            clearable
                            InputProps={{
                                     style: {
                                          fontSize: 13,
                                     }
                            }}
                       />
                </MuiPickersUtilsProvider>
               )
},
```
Basically, I added the code from [m-table-edit-field.js](https://github.com/mbrn/material-table/blob/master/src/components/m-table-edit-field.js) into the "editComponent" and I changed the format.

**Comment by thelazydogsback** [comment]
It seems like whenever you use the date type for editing, something is coercing the rowData.myDate value to an ISO date string rather than keeping it a Date object.  Is there a way around this?

**Comment by GusMartins499** [comment]
> I think the question was for editable field, the above is applying the format for data after being saved or when loaded.
> To provide a format on edit field, the only way I figured was to use "editComponent" column property like this:
> 
> ```
> {
>        title: "Date",
>        field: "date",
>        type: "date",
>        editComponent: props => (
>               <MuiPickersUtilsProvider utils={DateFnsUtils} 
>                           locale={props.dateTimePickerLocalization}>
>                      <DatePicker
>                             format="dd/MM/yyyy"
>                             value={props.value || null}
>                             onChange={props.onChange}
>                             clearable
>                             InputProps={{
>                                      style: {
>                                           fontSize: 13,
>                                      }
>                             }}
>                        />
>                 </MuiPickersUtilsProvider>
>                )
> },
> ```
> 
> Basically, I added the code from [m-table-edit-field.js](https://github.com/mbrn/material-table/blob/master/src/components/m-table-edit-field.js) into the "editComponent" and I changed the format.

Hi, how do you call the function editComponent ?
