### ISSUE TITLE
Is there a way to sort the table remotely?

### ISSUE THREAD

**Issue by omnislashbr** [mbrn/material-table#1039]
I would like  to know if is there a way to sort the data by an event outside the table?

I couldn't find such a method.

Thanks

**Comment by punnadittr** [comment]
You can access `query.orderBy` object (containing column id & title) and `query.orderDirection` which are changed when clicking sorting header. 

You can use these two items to make a request to the server and have the server return the ordered result to you.

```
  data={query =>
        new Promise(resolve => {
          Axios.get('API_ENDPOINT', {
            params: {         
              sort_by: query.orderBy && query.orderBy.tableData.id,
              sort_direction: query.orderDirection,
            },
          }).then(response => {        
            resolve({
              data: response.data.data,       
            });
          });
        })
      }
```
