### ISSUE TITLE
Column with type numeric

### ISSUE THREAD

**Issue by vgk77** [mbrn/material-table#1044]
How to add realtime validation to the column with type numeric

**Comment by masbaehr** [comment]
You can always use "render" in the column definition to do things with data (e.g validating)

**Comment by jayarjo** [comment]
Or override the `editComponent` for the given column.

**Comment by jayarjo** [comment]
@vgk77 I encourage you to ask material-table related questions on StackOverflow, so that others could benefit from them as well.
