### ISSUE TITLE
The sort arrows are too big

### ISSUE THREAD

**Issue by Jak3b0** [mbrn/material-table#1051]
**Describe the bug**
When sorting a column, the sort arrow is too big and clipped

**To Reproduce**
1. Go to https://material-table.com/#/docs/features/sorting
2. Click on a column header
3. See error

**Expected behavior**
Smaller sort arrow

**Screenshots**
![image](https://user-images.githubusercontent.com/2845081/63967586-be07bb80-ca6b-11e9-84d9-ebf92f1d2c41.png)

**Comment by KasparasGud** [comment]
I added the following in the theme overrides:

``` overrides: {
    MuiIcon: {
      root: {
        fontSize: "1.4rem"  // <-- Or "1.3rem", "1.2rem" If you want a smaller icon
      }
    }
}

**Comment by Totalbug92** [comment]
For me this fixed it:
`.material-icons {
  inline-size: auto !important;
  line-height: inherit !important;
}`

**Comment by Totalbug92** [comment]
> icons={{
>         SortArrow: props => <ArrowUpwardIcon {...props} fontSize="small" />,
>       }}

I got an overload does not exist when using this code, had to do :
```
icons={{
   SortArrow: React.forwardRef((props, ref) => <ArrowUpward {...props} fontSize="small" ref={ref}/>)
}}
```

with import: import {ArrowUpward} from '@material-ui/icons'

**Comment by cargallo** [comment]
The @Totalbug92 solution works fine for typescript, but I think that this is a bug of the library and should be fixed. The project's styles do not have to affect the library behavior unless it is intentional
