### ISSUE TITLE
Default sort does not update when state variable updates

### ISSUE THREAD

**Issue by jakeleventhal** [mbrn/material-table#1055]
**Describe the bug**
Say I have a table with 2 columns, `A` and `B`. I have a state variable called `isA`. When `isA === true`, I want to have a default sort by `A`. Conversely, when `isA === false`, I want to have default sort by `B`.

My columns look like this:
```javascript
[
  { field: 'A', title: 'A', defaultSort: isA && 'asc'},
  { field: 'B', title: 'B', defaultSort: !isA && 'desc'},
]
```
My table uses server side paging. When I update the `isA` variable I run the following:
```javascript
await this.tableRef.current.onQueryChange();
```
When this is complete and the table reloads, the default sort does not get set; rather, the same sort is in place but no sort is shown in the column headers.

**To Reproduce**
Do as described above.

**Expected behavior**
The table should switch to the correct default sort when the table reloads.

**Comment by jakeleventhal** [comment]
this is not stale!

**Comment by jakeleventhal** [comment]
not stale

**Comment by anyamiletic** [comment]
@jakeleventhal have you tried to reset the sort in the ref? I had an issue with sort persisting which was causing the component to crash, this is what i did:
`
                tableRef.current.dataManager.orderBy = -1;
                tableRef.current.dataManager.orderDirection = "";
`
then when you supply the columns with sorting it applies the new values

**Comment by jakeleventhal** [comment]
not stale

**Comment by jakeleventhal** [comment]
not stale
