### ISSUE TITLE
Unable to get Actions working

### ISSUE THREAD

**Issue by margozzi** [mbrn/material-table#106]
**Describe the bug**
I am unable to get "actions" to work

**To Reproduce**
I have code like this that refuses to render an icon in an actions column.
I took the action config straight from your demo code.
Also, you can't view the demo code without using the copy to clipboard way.

<MaterialTable
        columns={[
          { title: 'Name', field: 'name' },
          { title: 'Enabled', field: 'is_enabled', type: 'boolean' },
          { title: 'Application Access', field: 'allow_application_access', type: 'boolean' },
          { title: 'Netowk Access', field: 'allow_network_access', type: 'boolean' },
        ]}
        data={this.state.data}
        title='Portals'
        options={this.state.tableOptions}
        actions={[
          {
            icon: 'account_circle',
            tooltip: 'Show User Info',
            onClick: (event, rowData) => {
              alert('You clicked user ' + rowData.name)
            },
          },
        ]}
      />

**Expected behavior**
I expect to see an icon in the table row

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Browser Chrome
 - Version 70.0.3538.110 (Official Build) (64-bit)

**Additional context**

**Comment by mbrn** [comment]
Hi @margozzi ,

What is this.state.tableOptions. If selection is true the actions will be rendered on the top right of table when you select at least one column. 

**Also, you can't view the demo code without using the copy to clipboard way.**
Docz have a bug. If you click 11th-12th line of code the complete code will be shown.

**Comment by mbrn** [comment]
One more thing: 

Did you add material icons to your html as it described in documentation?

**Comment by margozzi** [comment]
this.state = {
        data: [],
        tableOptions: {
          selection: true,
          columnsButton: true,
          exportButton: true,
        }
    };

Yes, selection was true. I never thought to select a row as all the examples showed the icons in the rows themselves.
I actually think I like the icons up in the header.

Thank you for the tip about the source code viewing.

The action icon is now showing up as you described. Thank you very much for the quick response!

**Comment by margozzi** [comment]
Yes, and everything is working after I select a row. Thanks again.

**Comment by mbrn** [comment]
If you want to an action to be shown without selection please add __isFreeAction:true__ to action definition. This action will work with no related selection.

**Comment by slevy85** [comment]
Hi,

Why not showing actions column and selection column at the same time ?
This would be useful because we can have actions that only apply to one row (edit, show details, etc.) and actions that applies to many (delete, move, etc).

What do you think ?

**Comment by mbrn** [comment]
Hi @slevy85,

This would be. But it will make action definitions very complex. So i decided to do not implement this. If you need this, you can add a column with render property of column.

**Comment by slevy85** [comment]
Yes you are right I can have a custom column actions, thank you.
