### ISSUE TITLE
Column width is too big when filtering is enabled

### ISSUE THREAD

**Issue by masbaehr** [mbrn/material-table#1060]
The table filter causes some columns to be a lot larger than intended. The filter input should never be longer (in characters) than the longest item in a column (maybe just a little longer)

![image](https://user-images.githubusercontent.com/38694044/64109264-5c06c900-cd7f-11e9-8b01-b86b5a59f23b.png)

Expected:

![image](https://user-images.githubusercontent.com/38694044/64109300-704ac600-cd7f-11e9-8786-a476284168f3.png)

**Comment by ckalas** [comment]
use the filterCellStyle prop when defining your columns, ie:               
   ```
  {
                           title: 'Product', field: 'product_group',
                       
                            cellStyle: {textAlign: 'center'},
                            filterCellStyle:{maxWidth:50}
                            
                    }
```
