### ISSUE TITLE
Lookup dropdown is positioned slightly to the bottom compared to normal filter

### ISSUE THREAD

**Issue by serendipity1004** [mbrn/material-table#1061]
https://material-table.com/#/docs/features/filtering

If you look at the bottom most example, the lookup column has slightly less padding at the bottom which positions the dropdown lower than default filters. Need to fix this as it looks very ugly. Meanwhile, is there a quick fix for it?

**Comment by BrunoYTanaka** [comment]
+1

**Comment by kthyer** [comment]
@serendipity1004 This was bugging me as well but I found a quick fix until there is an official fix for this.

For each column that has the dropdown filter add

`filterCellStyle: {
              paddingTop: 1
            }`

This fixed it on chrome and firefox for me.

**Comment by tobilarscheid** [comment]
thanks @kthyer - not perfect, but good enough as a workaround. unfortunately, this stops me from digging deeper into it and probably finding a proper fix ;-)

**Comment by janderson215** [comment]
Thanks for pointing us in the right direction for a quick fix, @kthyer. In Chrome, that actually leaves it one pixel lower than the filter inputs for me, so I believe a slight correction is in order:
`filterCellStyle: { paddingTop: 0 }`
