### ISSUE TITLE
onAddRow newData does not include false boolean check columns

### ISSUE THREAD

**Issue by Totalbug92** [mbrn/material-table#1064]
**Describe the bug**
When i console log a new row object it won't include a boolean type column if it is not checked(false).

**To Reproduce**
1. create a table with a type: 'boolean' column.
2. add a new row, do not check the boolean column.
3. console.log newData inside onAddRow. log will not include a "BooleanColumn: false"

**Expected behavior**
Expect the newData object to include a property with false data for a boolean type column.

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome 76.0.3809.100

**Comment by Totalbug92** [comment]
A fix that worked for me

Where payload is the body{} of the newObject

```
if (typeof payload === 'object') {
      this.props.kolonner.forEach(element => {
        if (element['type'] === 'boolean') {
          if (!payload.hasOwnProperty(String(element['field']))) payload[String(element['field'])] = false;
        }
      });
    }

```

**Comment by ldgmaia** [comment]
No offical solution for this issue?

**Comment by pierreleripoll** [comment]
Still no official solution ?
