### ISSUE TITLE
Need to export table data to pdf 

### ISSUE THREAD

**Issue by kunjeers** [mbrn/material-table#1065]
In there any way to export all table and/or searched data to pdf just like export to csv option.

Could you please help on this

**Comment by jayarjo** [comment]
There's no such functionality in `material-table` itself. But you can always create a custom action in the actions column or in the same menu as export to csv menu and attach custom export logic to it.

**Comment by jayarjo** [comment]
@kunjeers 

I encourage you to ask material-table related questions on StackOverflow, so that others could benefit from them as well.
