### ISSUE TITLE
Receive className prop on table itself?

### ISSUE THREAD

**Issue by ifndefdeadmau5** [mbrn/material-table#1068]
Currently I'm using `style` prop to styling table but why not just pass className in here

https://github.com/mbrn/material-table/blob/bab87b76db9318668c98fdf7a4d645b63c902c17/src/material-table.js#L473

and make it available via 3rd party styling solutions like `styled-components`

**Comment by jayarjo** [comment]
@mbrn I think the whole thing should be better adapted to Material UI best practices for that matter.

**Comment by ifndefdeadmau5** [comment]
@jayarjo would you mind if I send PR for this?
