### ISSUE TITLE
How i can change styling of the table ?

### ISSUE THREAD

**Issue by TITAN9389** [mbrn/material-table#107]
@mbrn this mui-tables looks good one, tried others before but i'm facing some issues,
i need to change the Rows background color , how i can access to that level deep ?
and how i can pass props to real MUI elements ? like giving TableRow hover props true ?

**Comment by mbrn** [comment]
Hi @TITAN9389,

You can add style for cells. But it doesn't have row styling yet. In next releases we will add. Also we can add props feature for mui elements. Why don't you fork the project and send your first PR to repo:)

https://mbrn.github.io/material-table/#/docz-examples-example-cell-styling

**Comment by mbrn** [comment]
Please try component customization : 

https://mbrn.github.io/material-table/#/docz-examples-10-example-component-overriding
