### ISSUE TITLE
Localization property renders as localization=[object Object] in HTML code

### ISSUE THREAD

**Issue by masbaehr** [mbrn/material-table#1075]
I noticed this: 

![image](https://user-images.githubusercontent.com/38694044/64423237-4c9cbe00-d0a6-11e9-91db-21931d502843.png)

Probably this was not intended right? The property should not render instead just used internally for i18n purpose

**Comment by jayarjo** [comment]
This might be somewhat related: https://github.com/mbrn/material-table/issues/1020

**Comment by brendon1555** [comment]
I can take a look at this
