### ISSUE TITLE
Warnings when using <Button> for free actions

### ISSUE THREAD

**Issue by LeJav** [mbrn/material-table#1080]
I want to use my own Button component for free actions.

Here is for instance the action section with standard Button:
```
                  actions={[
                    {
                      icon: ( () => (
                        <Button
                           variant="contained"                                                                                                                          
                            color="primary" >                                                                                                                            
                          <AddIcon />                                                                                                                                    
                         </Button>)),
                      tooltip: 'Add User',
                      isFreeAction: true,
                      onClick: (event) => alert("You want to add a new row")
                    }
                  ]}
```
This works, but generates warning in the browser console:
```
Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>.
...
```

How can I avoid these warnings?

Many thanks for your help.

**Comment by miguderp** [comment]
You should check the `components` prop where you can find `Action`.
By default it englobes your `icon` function inside another `<button />` so you'd need to override it in order to remove the default tag element.

Check the example from _Action Overriding Example_ at https://material-table.com/#/docs/features/component-overriding

**Comment by LeJav** [comment]
Many thanks for your answer, this is the solution I was looking for. I completely missed this documentation part.
