### ISSUE TITLE
Editing for a column field which is a group column

### ISSUE THREAD

**Issue by avkonst** [mbrn/material-table#1084]
**Is your feature request related to a problem? Please describe.**
When a table has got a grouping column, values of this column can not be edited unless grouping is removed.

**Describe the solution you'd like**
I would like two behaviors which are not mutually exclusive:

1) allow to drag and drop rows from a group to another group -> this would trigger `onRowUpdate` function with `newData` having new group field value
2) do not hide a column if it is used for grouping, this can be made configurable via table or column options.

**Describe alternatives you've considered**
I have overridden tablerow component to inject custom groupping row (for example, grouping by `Folder` column):
![image](https://user-images.githubusercontent.com/3971413/64483576-9f1ddc00-d258-11e9-9c51-20fdad7f1e54.png)

**Comment by mikelyndersOKCC** [comment]
Also having the same issue
