### ISSUE TITLE
Performance is very slow when selecting a row in a large table

### ISSUE THREAD

**Issue by shaibam** [mbrn/material-table#1085]
**Describe the bug**
I have a 240 row table with 6 columns.
when selecting a row, it takes as much as 1second for the check marker to appear.
When removing the styling checking the input using js, performance is well.

> $0.checked = true

**To Reproduce**
create a 240 row table with 6 columns, set 'selection' option to true. try selecting a row.

**Comment by popov-aa** [comment]
I have same problem with 30 rows count. 
I had developed simple table without this disadvantage. Everything, that need, it's use key of rows and columns and using of method shouldComponentUpdate.
My variant of row component:
`class Row extends React.Component {

    renderRowCheckCell = (row) => {
        const {isSelected} = this.props;
        return (
            <TableCell padding="checkbox">
                <Checkbox
                    checked={isSelected}
                />
            </TableCell>
        );
    }

    handleClick = (event, row) => {
        const {isSelected, onSelectionChange, selectableEnabled} = this.props;
        if (selectableEnabled) {
            onSelectionChange(row, !isSelected);
        }
    }

    shouldComponentUpdate(nextProps, nextState, nextContext) {
        const {selectableEnabled, isSelected, columns, row} = this.props;
        let shouldUpdate = false;
        if (nextProps.selectableEnabled !== selectableEnabled ||
            nextProps.isSelected !== isSelected ||
            nextProps.row !== row
        ) {
            shouldUpdate = true;
        }
        if (nextProps.columns.length !== columns.length) {
            shouldUpdate = true;
        }
        for (let i = 0; i < nextProps.length; ++i) {
            const column1 = nextProps.columns[i];
            const column2 = columns[i];
            if (column1.field !== column2.field) {
                shouldUpdate = true;
                break;
            }
        }
        return shouldUpdate;
    }

    render () {
        const {selectableEnabled, isSelected, columns, row} = this.props;
        console.log(`Row #${row.id} was rendered.`)
        return (
            <TableRow
                hover
                role="checkbox"
                tabIndex={-1}
                selected={isSelected}
                aria-checked={isSelected}
                onClick={event => this.handleClick(event, row)}
            >
                {
                    selectableEnabled ? this.renderRowCheckCell(row) : null
                }
                {
                    columns.map(({render, field, align}) => {
                        const value = render ?
                            render(row) :
                            row[field];
                        return (
                            <TableCell key={field} align={align}>
                                {value}
                            </TableCell>
                        );
                    })
                }
            </TableRow>
        );
    }
}
Row.propTypes = {
    selectableEnabled: PropTypes.bool.isRequired,
    isSelected: PropTypes.bool.isRequired,
    columns: PropTypes.array.isRequired,
    row: PropTypes.array.isRequired,
    onSelectionChange: PropTypes.func.isRequired
}`
When I select row, will rerender only it row.
Full module: https://pastebin.com/tUT3txEX

**Comment by ElenaMagda** [comment]
Hello! We are encountering this problem on our project as well. At first I thought that I was doing something wrong but I made a simple app using material-table selection https://codesandbox.io/embed/determined-goodall-0whe4?fontsize=14&hidenavigation=1&theme=dark and the performance is still slow.
Does anybody has any solution?

**Comment by chetanyakan** [comment]
Still facing this with about `100 rows` per page and `5 columns + 1 actions column`.

**Comment by gjergjk71** [comment]
Until fixed, sorry to say, this package is useless.

**Comment by RELNO** [comment]
Same here -- surprisingly, this happens in production and not on dev which is harder to catch.

**Comment by pra-richardg2-sportsbet** [comment]
Has this been fixed yet?

**Comment by RELNO** [comment]
Error persist 1.69.2. Issue should probably be reopened.

**Comment by kartiknaithani** [comment]
still facing the issue.

**Comment by AlexCiceu** [comment]
Should definitely be re-opened, facing the same issue with 36 rows.

**Comment by avirupdutta** [comment]
facing same issue with 25 rows and 6 cols

**Comment by vnylbscr** [comment]
the problem still continues. I currently have a table with 50 rows and it works like an oxcart when I click somewhere on the page.

**Comment by sm3sher** [comment]
Unuseable package with this problem. Looking for alternatives.

**Comment by anabeatrizzz** [comment]
@sm3sher did you find some good alternative?

**Comment by pra-richardg2-sportsbet** [comment]
Nah. Had to just keep the row numbers lowish with pagination.

**Comment by anabeatrizzz** [comment]
@pra-richardg2-sportsbet using your own pagination solution or using the built-in pagination feature?

**Comment by pra-richardg2-sportsbet** [comment]
Just the built in one

**Comment by navoditbharat** [comment]
still this issue persists

**Comment by nativecoderbb** [comment]
please fix this slow selection issue it is still there , our whole project noe depend on this

**Comment by amar-nath-das** [comment]
Please optimize the selection issue on larger page-size.

**Comment by navoditbharat** [comment]
Stopped using this table altogether

**Comment by KippWade** [comment]
Material-table/core is a fork of this project and is updated regularly.
