### ISSUE TITLE
RowData type does not include 'tableData' 

### ISSUE THREAD

**Issue by seanharr11** [mbrn/material-table#1086]
**Describe the bug**
In the typescript type definitions, `RowData` is passed as the generic prop to `MaterialTable`. In many contexts, not only does this type have the row data (current type definition), it also has the `tableData` (holds things like `path`, etc.)

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by Domino987** [comment]
That is because tableData is local and should only be used by material table itself. I don't think that you are supposed to access it at all. What do you need that for ?

**Comment by longsangstan** [comment]
@Domino987 

We don't need it.

The problem is when you use the custom render function for columns it will give you the wrong type (current type definition **& the tableData field**) :

```
{
          title: "MyData",
          render: (rowData) => (  // it returns MyData's type, but rowData includes tableData field as well which is extra and incorrect
            <span>
              {/* xxxxx */}
            </span>
          ),
        }
```
