### ISSUE TITLE
when RowAdd event on grouping table

### ISSUE THREAD

**Issue by devAceLim** [mbrn/material-table#1092]
Deer,

group by header field is not editable when inline RowAdd Event on grouping table. 
![asis](https://user-images.githubusercontent.com/11826640/64662438-77f72280-d483-11e9-8760-f4ed58ae744f.png)

So removed all group headers click delete button on chip then click add row button.
this is so uncomfortable.
![t](https://user-images.githubusercontent.com/11826640/64662440-788fb900-d483-11e9-909f-8309164f51ee.png)

I needs some feature.

- Automatically delete all group by fields after row add editable.

**Comment by sanathkumarx** [comment]
Facing the same issue. It would be nice if grouping was temporarily disabled onRowAdd since the columns which are grouped by will be empty value.
