### ISSUE TITLE
Identify if a row is in edit mode

### ISSUE THREAD

**Issue by marsh-d** [mbrn/material-table#1095]
Hi, 
I am overriding the render of one column in my material-table with a custom component.  This is working well.  I would now like to display a different component when the row is being edited.  Is it possible to determine whether a row is in read/edit mode?  

Thank you

https://material-table.com/#/docs/features/custom-column-rendering

**Comment by jayarjo** [comment]
@marsh-d have you found any solution to your problem?

**Comment by jayarjo** [comment]
This might be helpful: https://github.com/mbrn/material-table/issues/1131
