### ISSUE TITLE
Styles are overridden in the paginator

### ISSUE THREAD

**Issue by roseak** [mbrn/material-table#1099]
**Describe the bug**
When adding a basic table to my page, certain other Material UI elements on the page will override the paginator styles so that the number of rows to be displayed is weird and there's a scroll bar that appears, though it more comes off like the padding is off on the element.  I noticed this specifically with the <Toolbar /> component being on the page (the scroll appears), and with <TextField /> (the rows to be displayed gets messed up).  Would be great to stop that from happening.

**Screenshots**
<img width="310" alt="Screen Shot 2019-09-12 at 10 34 39 AM" src="https://user-images.githubusercontent.com/10897615/64807530-354c4d80-d54a-11e9-8255-d60d3f311414.png">

**Comment by mehuljariwala** [comment]
@roseak  Are you using Material ui for your project or different UI ?

**Comment by jayarjo** [comment]
@roseak it must be something specific to your environment, as it isn't usually a case.

**Comment by roseak** [comment]
Hey sorry, just saw this.  I'm using Material UI.  If I do the paginator on my own, it's fine.  It's just the one from Material Table.

**Comment by jayarjo** [comment]
@roseak this might be of some help: https://github.com/mbrn/material-table/issues/804. Solved a similar problem for me personally.
