### ISSUE TITLE
Delete multiple rows at once, table rendering old data plus new data

### ISSUE THREAD

**Issue by Pheelbert** [mbrn/material-table#1100]
Is it possible to delete multiple rows at once and have the table refresh correctly? The row edit feature (https://material-table.com/#/docs/features/editable) is not exactly what I'm looking for since it can only delete a single one at a time.

I tried changing the table's data and as soon as I remove an element it messes up the whole table (removes the element but adds a new duplicate of another element). I have read about tableRef and onQueryChange... Any idea how to do this using a functional component (using hooks)?

Here are the parts of the code that are relevant (not working at all even if I don't modify the data and only call "onQueryChange", image below code):
```
[...]

const tableRef = useRef(null);

function handleClick() {
    tableRef.current.onQueryChange();
}

[...]

<MaterialTable
            tableRef={tableRef}

[...]

options={{
                selection: true
            }}
            actions={[{
                    [...]
                    onClick: (event, data) => handleClick()
            }]}

[...]
```
![error_message](https://user-images.githubusercontent.com/5648665/64824474-1b316000-d588-11e9-9045-dc0b26054de9.png)

**Comment by oze4** [comment]
You should be able to do something like this:

**Live Demo:**
[![Edit react-material-table delete multiple rows](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-material-table-delete-multiple-rows-3fnzq?fontsize=14&module=%2Fsrc%2FAppTable.js)

**Code:**
```javascript
export default function AppTable() {
  const [data, setData] = useState(results);

  const handleDeleteRows = (event, rowData) => {
    let _data = [...data];
    rowData.forEach(rd => {
      _data = _data.filter(t => t.tableData.id !== rd.tableData.id);
    });
    setData(_data);
  };

  return (
    <MaterialTable
      title="Select row(s) to get the option to delete"
      columns={[
        {
          title: "Name",
          field: "name"
        },
        {
          title: "State",
          field: "state"
        },
        {
          title: "Account",
          field: "account"
        }
      ]}
      data={data}
      options={{
        selection: true,
        pageSize: 10
      }}
      icons={tableIcons}
      actions={[
        {
          icon: () => <Delete />,
          tooltip: "Delete Rows",
          onClick: handleDeleteRows
        }
      ]}
    />
  );
}
```
**Screenshot:**
![image](https://user-images.githubusercontent.com/21092343/64901249-c27fc700-d65c-11e9-925d-6f16c0ddfa49.png)

**Comment by Pheelbert** [comment]
Thank you so much @oze4! I didn't think of doing it this way and I was stuck with another issue which was resolved by passing the initial table data in the props. I'm so glad this works now.

**Comment by vcilano** [comment]
it's cool! Thank very much! It's really good
