### ISSUE TITLE
Editable table returns only strings

### ISSUE THREAD

**Issue by ericjansen1988** [mbrn/material-table#1102]
I have an editable material-table with some numeric columns:
```
  var columns = [{
    title: 'Naam',
    field: 'naam'
  },{
    title: 'Dag vd maand',
    field: 'dag',
    type: 'numeric'
  }, {
    title: 'Type',
    field: 'type'
  }, {
    title: 'Rekening',
    field: 'rekening'
  }]
```

When making the table editable, those edditted values are all strings. Is there any way to receive those values/variables as numbers? I store them as JSON so it would be nice to not have to convert every item to numeric. It is now displaying (console.log) as this:
{dag: "1"
naam: "Testrek"
rekening: "Algemeen"
type: "Rekening"}

**Comment by ericjansen1988** [comment]
I used the columns variable to check if name of the property is in the columns and if yes, if there is a field type set. If yes, parse this type.

Little cumbersome :)

**Comment by jayarjo** [comment]
You can also set a type on corresponding columns to `numeric`.

**Comment by g3n35i5** [comment]
I have the same problem right now. As far as I can tell, @ericjansen1988  has selected "numeric" as column type, so parsing the values does not seem to use the type from the column settings. I have the same problem when creating entries.

**Comment by g3n35i5** [comment]
I think #1450 is a related issue.
