### ISSUE TITLE
Switch search mode(remote or local data)

### ISSUE THREAD

**Issue by jerlockk** [mbrn/material-table#1103]
When activating the **remote query** the search is always carried out towards the server, I would like to have an option to have the remote query but with the search in the **local data**.

I usually use the remote search for pagination but the search to the server was not implemented, so I would like to keep the local search option.

**Comment by jayarjo** [comment]
I don't think this will be implemented. Consider adding search functionality to your remote handler. Searching locally doesn't sound as good idea anyway.

**Comment by Gardezi1** [comment]
I also need this functionality. Isn't there any way material-table could do it
