### ISSUE TITLE
row field input max length 

### ISSUE THREAD

**Issue by omriran** [mbrn/material-table#1104]
Hi,
Is there anyway to use the maxLength input attribute to limit the number of characters that are allowed to a specific field?

Thanks

**Comment by omriran** [comment]
Ok, so I'e figured out how to do this for all input fields by using:

components={{
                            EditField: props => (
                                <TextField
                                    inputProps={{maxLength: 24}}
                                />
                            ),
                        }}

but i'm not sure how to make this work on individual fields

**Comment by omriran** [comment]
For anyone who looks for it here is how I've achieve it. You will need to import TextField from material-ui

```
columns: [
                {
                    title: 'Title', field: 'title', editComponent: props => {
                        return (
                            <TextField
                                value={props.value}
                                placeholder={props.title}
                                inputProps={{ maxLength: 24 }}
                            />
                        )
                    }
                }
            ]
```

**Comment by sunil-sadasivan** [comment]
Wanted to update this thread. @omriran's solution worked for me only after including the onChange handler:

```
columns: [
                {
                    title: 'Title', field: 'title', editComponent: props => {
                        return (
                            <TextField
                                value={props.value}
                                inputProps={{ maxLength: 24 }}
                                onChange={(event) => {props.onChange(event.target.value)}
                            />
                        )
                    }
                }
            ]
```

**Comment by saunlani** [comment]
i'm storing my columns in a database table to keep my configuration as high level as possible and so far this has not presented any issue. however, i've found it to be difficult to assign a custom editComponent to a column.

using the method above, it is  simple to add an editComponent. however, my columns are assigned to a state object, which does not have visibility of the props in the material-table component.  anyone know how to pull this off?

thanks
