### ISSUE TITLE
How to make a field readonly (not the complete row)

### ISSUE THREAD

**Issue by raza2022** [mbrn/material-table#1105]
I want to make, only one field in whole row, as `readonly`, not the whole row, but didn't find the way to achieve it, it can be implemented in core API? as my search I found a `readOnly` flag under columns section, as described [here](https://material-table.com/#/docs/all-props) but even that flag not work for single fields and all fields remain editable in a row
below is my minimal code
****Note**: I tried both cases i.e `readOnly` and `readonly`**
```
import React from 'react';
import MaterialTable from 'material-table';

export default function MaterialTableDemo() {
    const [state, setState] = React.useState({
        columns: [
            { title: 'Name', field: 'name', readOnly: true },
            { title: 'Surname', field: 'surname', readOnly: true },
            { title: 'Birth Year', field: 'birthYear', type: 'numeric', readOnly: true },
            {
                title: 'Birth Place',
                field: 'birthCity',
                lookup: { 34: 'İstanbul', 63: 'Şanlıurfa' },
            },
        ],
        data: [
            { name: 'Mehmet', surname: 'Baran', birthYear: 1987, birthCity: 63 },
            {
                name: 'Zerya Betül',
                surname: 'Baran',
                birthYear: 2017,
                birthCity: 34,
            },
        ],
    });

    return (
        <MaterialTable
            title="Control Panel"
            columns={state.columns}
            data={state.data}
            editable={{
                onRowAdd: newData =>
                    new Promise(resolve => {
                        setTimeout(() => {
                            resolve();
                            const data = [...state.data];
                            data.push(newData);
                            setState({ ...state, data });
                        }, 600);
                    }),
                onRowUpdate: (newData, oldData) =>
                    new Promise(resolve => {
                        setTimeout(() => {
                            resolve();
                            const data = [...state.data];
                            data[data.indexOf(oldData)] = newData;
                            setState({ ...state, data });
                        }, 600);
                    }),
                onRowDelete: oldData =>
                    new Promise(resolve => {
                        setTimeout(() => {
                            resolve();
                            const data = [...state.data];
                            data.splice(data.indexOf(oldData), 1);
                            setState({ ...state, data });
                        }, 600);
                    }),
            }}
        />
    );
}
```

**Comment by Domino987** [comment]
Hi,
You can simply use the editable: never value for a column to prevent editing.
I'll provide a code example in a few minutes.

**Comment by Domino987** [comment]
Hi,
You can simply use the editable: never value for a column to prevent editing.
I'll provide a code example in a few minutes.

**Comment by Domino987** [comment]
Here is the editable example from the docs but name cannot be edited. Hope this helps:

    class Editable extends React.Component {
      constructor(props) {
        super(props);
        this.state = {
          columns: [
            { title: 'Name', field: 'name', editable:'never' },
            { title: 'Surname', field: 'surname', initialEditValue: 'initial edit value' },
            { title: 'Birth Year', field: 'birthYear', type: 'numeric' },
            {
              title: 'Birth Place',
              field: 'birthCity',
              lookup: { 34: 'İstanbul', 63: 'Şanlıurfa' },
            },
          ],
          data: [
            { name: 'Mehmet', surname: 'Baran', birthYear: 1987, birthCity: 63 },
            { name: 'Zerya Betül', surname: 'Baran', birthYear: 2017, birthCity: 34 },
          ]
        }
      }

      render() {
        return (
          <MaterialTable
            title="Editable Preview"
            columns={this.state.columns}
            data={this.state.data}
            editable={{
              onRowAdd: newData =>
                new Promise((resolve, reject) => {
                  setTimeout(() => {
                    {
                      const data = this.state.data;
                      data.push(newData);
                      this.setState({ data }, () => resolve());
                    }
                    resolve()
                  }, 1000)
                }),
              onRowUpdate: (newData, oldData) =>
                new Promise((resolve, reject) => {
                  setTimeout(() => {
                    {
                      const data = this.state.data;
                      const index = data.indexOf(oldData);
                      data[index] = newData;
                      this.setState({ data }, () => resolve());
                    }
                    resolve()
                  }, 1000)
                }),
              onRowDelete: oldData =>
                new Promise((resolve, reject) => {
                  setTimeout(() => {
                    {
                      let data = this.state.data;
                      const index = data.indexOf(oldData);
                      data.splice(index, 1);
                      this.setState({ data }, () => resolve());
                    }
                    resolve()
                  }, 1000)
                }),
            }}
          />
        )
      }
    }

**Comment by raza2022** [comment]
Thanks as I need the fields is not editable but admin can set value when add new fields so `onAdd` works perfect for me
```
{title: 'FirstName', field: 'firstName', editable: 'onAdd'}
```
