### ISSUE TITLE
Tablo içinde bulunan colums için alternatif yöntem

### ISSUE THREAD

**Issue by kadirsaymadi** [mbrn/material-table#1109]
Merhaba abi koda bakınca anlayacağını düşünüyorum fakat yinede yazayım
Böyle bir problemim var ben lookup ile çok güzel filtreleme yapıyorum fakat bazı durumlarda row data içindeki özelliği kullanmam gerekebiliyor böyle bir kullanım şansım var mı?
lookup ta render gibi çalışsın tüm çoluk çocuk mutlu mesut yaşasın :D
```
{
                    title: "Fatura Tipi", field: "type",
                    lookup: {
                        0: "Isınma Faturası",
                        1: "Su Tüketim Faturası",
                        2: "Sıcak Su Isıtma Faturası",
                        3: "Isı Kayıp Gideri Faturası",
                        4: rowData.title, // HATA VERİYOR
                        5: "Sıcak Su Tüketim Faturası",
                    },
                    render: rowData => {
                        // KENDİ BULDUGUM ALTERNATİF
                        let text = "";
                        if (rowData.type === 0) {
                            text = "Isınma Faturası";
                        } else if (rowData.type === 1) {
                            text = "Su Tüketim Faturası";
                        }
                        else if (rowData.type === 2) {
                            text = "Sıcak Su Isıtma Faturası";
                        }
                        else if (rowData.type === 3) {
                            text = "Isı Kayıp Gideri Faturası";
                        }
                        else if (rowData.type === 4) {
                            text = rowData.title;
                        }
                        else if (rowData.type === 5) {
                            text = "Sıcak Su Tüketim Faturası";
                        }
                        return (
                            text
                        );
                    }
                },
```

**Comment by emresimsk** [comment]
Merhaba yanlış anlamış olabilirim.
lookup da verdiğiniz objenin keylerine göre text değerlerini zaten yazıyor. Render'da bu işlemi yapmanıza gerek yok.

**Comment by kadirsaymadi** [comment]
Merhabalar.  Öncelikle soruma yanıt verdiğiniz için teşekkür ederim.
Lookup key değerine göre text yazıyor evet ama benim istediğim tam olarak
degil ben orada kategori filtresine benzer bir şey yapmak istiyorum

lookup: {
0: "test kategori",
1: "test 1 kategori"
}

yukarıdaki örnekte bir problem yok fakat şöyle bir şey olsa daha kullanışlı
olacak

lookup: (rowData) => {
    return {
            rowData.category._id: rowData.category.name
        }
}

tabi bunun dizi hali olması gerekiyor

benim kategori _id 'im 1 numara ama bunun adı görünecek ve bu kategoriler
yukarıdan filtrelenebilir olacak 1 numaralı kategoriyi seçince ona göre
liste gelecek dinamik bir şekilde bende lookup üzerinde istedigim gibi
fitre menüsünü oluşturacağım.

İlginiz için yinede teşekkür ederim

Emre Şimşek <notifications@github.com>, 25 Eyl 2019 Çar, 15:45 tarihinde
şunu yazdı:

**Comment by kadirsaymadi** [comment]
{
                    title: "Adı", field: "city.name",
                    lookup: { // lookup yerine alternatif filtrelemele
                        this.props.cities.map((city) => {
                            return { value: city._id, label: city.name }
                        })
                    }
                    render: rowData => {
                        return (
                            rowData.name
                        );
                    }
                },

 bu şekilde olsa mesela tadından yenmeyecek :)

**Comment by emresimsk** [comment]
Merhaba yine anladığım kadarıyla,
bu işlemi lookup ile değil de, editComponent kullanarak yapabilirsiniz diye düşünüyorum.
yardımcı olması için aşağıda örnek kod paylaştım umarım aradığınız şey budur.

```
       {
                    title: 'KDV Oranı', field: 'vatRate', editComponent: props => {
                        const vatRates = this.state.vatRates(x => x.id === props.rowData.id)
                        return (
                            <Select
                                value={props.value}
                                onChange={e => props.onChange(e.target.value)}
                            >{
                                    vatRates.map((item, i) =>
                                        <MenuItem value={item.value}>{item.label}</MenuItem>
                                    )
                                }

                            </Select>
                        )
                    }
                },
```

**Comment by jayarjo** [comment]
I encourage you to ask `material-table` related questions on StackOverflow, so that others could benefit from them as well (and in English please :)
