### ISSUE TITLE
Numeric Cell Header Alignment

### ISSUE THREAD

**Issue by KamalAman** [mbrn/material-table#1110]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when numeric column headers look different than all the other column headers

`m-table-edit-row` has the following code
```jsx
<TableCell
       key={columnDef.tableData.id}
       align={['numeric'].indexOf(columnDef.type) !== -1 ? "right" : "left"}
>
```

Is there are reason why this is the default functionality?

**Describe the solution you'd like**
Two things: 
1.  allow columns to specify `TableCellProps` and spread the `TableCellProps` onto the `TableCell` component so properties can be modified on the `TableCell` component
2. Allow columns to specify `alignment`

**Describe alternatives you've considered**
None are possible since material-table does not offer any way to target properties on the TableCell component

**Additional context**
![image](https://user-images.githubusercontent.com/2692357/65266790-bfb02680-dae1-11e9-913b-8ca1b3c43199.png)

**Comment by jayarjo** [comment]
Yes, it's kind of standard to format numbers like that.  If you do not like how it looks, do not use type number for the column and it will be formatted similar to other text columns.

I encourage you to ask material-table related questions on StackOverflow, so that others could benefit from them as well.

**Comment by Xzas22** [comment]
Setting the column type to numeric also changes the default sorting to be correct for numbers. Can we just override the "right align" part?

**Comment by Xzas22** [comment]
Also, the numeric align-right really messes with the style of grouping numeric columns
