### ISSUE TITLE
Option to make 'Add New' row always visible. 

### ISSUE THREAD

**Issue by vazra** [mbrn/material-table#1112]
**Is your feature request related to a problem? Please describe.**
I have some use cases where I want to show the 'add new' fields always visible by default. 
For 
Eg: If the table is given in a form to create a new list of items, in which user can enter data and it will be added to the datasource. 

**Describe the solution you'd like**
An option to make the 'add row' always visible. 

**Describe alternatives you've considered**
I don't use material-table in this case, in the use cases I mentioned, the primary use of the table is to add data, the user usually have to add approx. 20-30 rows at once, In that case its difficult click on the add new button each time.

**Comment by jayarjo** [comment]
You can always have a form for this outside of the table, styled and managed by you and simply update the data object that you feed to the `material-table`.
