### ISSUE TITLE
How to set debounce for search field? 

### ISSUE THREAD

**Issue by xfishernet** [mbrn/material-table#1114]
How to set debounce for search field?

**Comment by oze4** [comment]
You can use the `debounceInterval` attribute under the `options` property.. The default is `200` (in ms).

https://material-table.com/#/docs/all-props

![image](https://user-images.githubusercontent.com/21092343/65329062-554cc400-db7d-11e9-800e-57d0b1381581.png)

**Comment by jayarjo** [comment]
@xfishernet 

I encourage you to ask material-table related questions on StackOverflow, so that others could benefit from them as well.
