### ISSUE TITLE
Add dinamically object to lookup

### ISSUE THREAD

**Issue by SchafferCPqD** [mbrn/material-table#1115]
I need to select my lookup object based on row data. I'll pass activity value and use a different lookup object. I'll make an example:

my column config:
```
columns =  [
    { title: 'Activity', field: 'activity' },
    { title: 'Original', field: 'original', lookup: getLookup(activity) }
 ];
```

activity can be 0 or 1
original can be 0 or 1 also
then based on activity I wanna change original lookup

My lookup objects, I need to change the lookup based on value of activity
```
run = {
    0:'Fast',
    1:'Slow'
}
swim = {
    0:'Crawl',
    1:'Butterfly'
}
```

Function to get correct lookup:
```
const getLookup = (field) => {
    switch(field){
        case 0:
            return run;
        break;
        case 1:
            return swim;
        break;
    }
}
```

My data is:
```
data={[
    { activity: 0, original: 0  },
    { activity: 1, original: 0  },
    { activity: 0, original: 1  },
    { activity: 1, original: 1  },
]} 
```

I want for table result be like that:
```
+----------+-----------+
| Activity |  Original |
+----------+-----------+
|     0    |    Fast   |
+----------+-----------+
|     1    |   Crawl   |
+----------+-----------+
|     0    |    Slow   |
+----------+-----------+
|     1    | Butterfly |
+----------+-----------+
```

**Comment by Domino987** [comment]
Hi you can achieve that with the editComponent prop. Here is a [codepen](https://codesandbox.io/embed/material-ui-responsive-table-k2wgq?fontsize=14) for you.

**Comment by SchafferCPqD** [comment]
@Domino987 Nice solution for edit mode, but how can I achieve that on rendering?
Keeping it simple, I just want change field 'original' lookup based on 'activity' value. Here is a fork of your [codepen](https://codesandbox.io/embed/material-ui-responsive-table-t2bwl)

**Comment by Domino987** [comment]
Well it seems like it did not save the changes regarding the render prop. I had it in there. Let me check

**Comment by didopop3** [comment]
@Domino987 could you please elabarate a bit and where shoud i put the row render? Thanks

**Comment by emresimsk** [comment]
Hi you can try this,

columns =  [
    { title: 'Activity', field: 'activity' },
    { title: 'Original', field: 'original', editComponent: props => {
                        const arrayList = switch.........
                        return (
                            <Select
                                value={props.value}
                                onChange={e => props.onChange(e.target.value)}
                            >{
                                    arrayList.map((item, i) =>
                                        <MenuItem value={item.value}>{item.label}</MenuItem>
                                    )
                                }

                            </Select>
                        )
                    } }
 ];

**Comment by jayarjo** [comment]
@SchafferCPqD 

I encourage you to ask material-table related questions on StackOverflow, so that others could benefit from them as well. I will respond on StackOverflow, if you create a question and link it here.
