### ISSUE TITLE
Action Functions on key press

### ISSUE THREAD

**Issue by adrihle** [mbrn/material-table#1116]
Hey there

Im trying to looking for a some way to add like a onKeyPress listener that launch a editable actions from the table, instead on clicking on a icon, for a more faster performance, just for add a new row from a key like enter o any other.

Any idea about? thanks guys

**Comment by jayarjo** [comment]
I don't think we have a method to programmatically switch the row into editing mode, do we @mbrn? I think we should.

P.S. @adrihle may I ask - how are you related to your avatar?
