### ISSUE TITLE
initialEditValue does not support deep attributes

### ISSUE THREAD

**Issue by KamalAman** [mbrn/material-table#1117]
**Describe the bug**
Fields that are nested and have an initialEditValue cannot be edited.

**To Reproduce**
If you have the following column `{ field: 'a.b', initialEditValue: 'test', type: 'string' }` you are unable to edit the value. This is due to createRowData not using `setByString`

```
createRowData(){
    return this.props.columns.filter(column=>column.initialEditValue && column.field).reduce((prev,column)=>{
      prev[column.field]=column.initialEditValue;
      return prev;
    },{});
  }
```

**Expected behavior**
You should be able to edit a nested attribute

**Comment by drorElgabsi** [comment]
+1
