### ISSUE TITLE
Uncaught TypeError: Cannot read property 'droppableId' of null

### ISSUE THREAD

**Issue by pradeepravi-cse** [mbrn/material-table#1118]
**Describe the bug**

**To Reproduce**
1. Drag and Drop table header 

**Screenshots**
![image](https://user-images.githubusercontent.com/7976356/65371181-86f98400-dc7e-11e9-8ad1-5c0394dca6dd.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Browser [chrome ]
 - Version [76]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pradeepravi-cse** [comment]
@mbrn

**Comment by oze4** [comment]
I don't think this is an issue any longer.  I am not able to reproduce.
