### ISSUE TITLE
Search data in table on press enter

### ISSUE THREAD

**Issue by mqasim1990** [mbrn/material-table#1119]
Hi, how can i overwrite the search functionality in table instead of sending an API call on key press i want to send an API call on press Enter.
How can i do this ?

I am using **`debounceInterval: 2000`** but this is not enough can i overwrite this function to call on enter key ?

**Comment by twhetzel** [comment]
Also looking to start search on Enter keypress and looking for some examples on how to access the search field to do this.

**Comment by twhetzel** [comment]
I was not able to figure out to use the default search input field to initiate search on Enter so I added a separate TextField and used the option `toolbar: false,` to hide the toolbar (search input, title, etc.). I used `tableRef` following this post[1] to query the data with the text in the TextField. 

[1] https://github.com/mbrn/material-table/issues/383

**Comment by mqasim1990** [comment]
> I was not able to figure out to use the default search input field to initiate search on Enter so I added a separate TextField and used the option `toolbar: false,` to hide the toolbar (search input, title, etc.). I used `tableRef` following this post[1] to query the data with the text in the TextField.
> 
> [1] #383

Thanks @twhetzel can you please share the code here.

**Comment by jayarjo** [comment]
@mbrn another candidate for overriding - Search component.

**Comment by mqasim1990** [comment]
Found the solution and i think it's a best solution.
I have just overwrite the component and add input field in Material table header like below and it's work like a charm.
![image](https://user-images.githubusercontent.com/23281307/65907132-32bc7580-e3dd-11e9-9bd3-64eb11982b0b.png)

Just change the functionality of search field and pass `query.search` through another function.

**Comment by vireshshah** [comment]
@iqasim-com Can you please share sample code? Thank you!

**Comment by dr-martin** [comment]
> Found the solution and i think it's a best solution and this is exactly what i want . 👍 .
> I have just overwrite the component and add input field in Material table header like below and it's work like a charm.
> ![image](https://user-images.githubusercontent.com/23281307/65907132-32bc7580-e3dd-11e9-9bd3-64eb11982b0b.png)
> 
> Just used `display none` css property to hide default search field. **Hacky way but works.**
> 
> Just change the functionality of search field and pass `query.search` through another function on **press Enter** after type no need to use `**debounceInterval** `
> 
> Custom search field with remote data......
> ![image](https://user-images.githubusercontent.com/23281307/65907694-41575c80-e3de-11e9-92bf-d6c9fd65d898.png)

Works for me!, Thanks @iqasim-com!!

**Comment by MohammedSaberMohammed** [comment]
@dr-martin @iqasim-com could u please share ur code ?

**Comment by maliganesh2011** [comment]
@dr-martin  @iqasim-com  can you please share your code
