### ISSUE TITLE
Ordered List in Table

### ISSUE THREAD

**Issue by iamrenzx** [mbrn/material-table#1123]
Hi is it possible to get this output?

![image](https://user-images.githubusercontent.com/21088424/65404118-d324ff80-de09-11e9-9275-df773210f8ad.png)

**Comment by jayarjo** [comment]
You can override any given cell with your own custom Component implementing arbitrary logic. So - yes, possible.

**Comment by jayarjo** [comment]
I encourage you to ask material-table related questions on StackOverflow, so that others could benefit from them as well.
