### ISSUE TITLE
access data after search's been made

### ISSUE THREAD

**Issue by NikicaCh** [mbrn/material-table#1124]
How can I access the data after I do the search, for example how to get the sum of element's quantity from specific title(i search for) ?

**Comment by jayarjo** [comment]
@NikicaCh 

I encourage you to ask material-table related questions on StackOverflow, so that others could benefit from them as well. I will respond on StackOverflow, if you create a question and link it here.

**Comment by imjared** [comment]
@NikicaCh did you either figure this out or post it to stackoverflow? trying to do the same thing

**Comment by tylercaceres** [comment]
try looking at my post in #752 [My Workaround](https://github.com/mbrn/material-table/issues/752#issuecomment-564137746)
I used ref.
I know this isn't the solution you're looking for, but it did work for me.
(sorry for the bad formatting in the post too)

**Comment by JimiSweden** [comment]
I found this thread today and have now worked on and tested two working solutions that probably is what you want, so I thought I should share it =)

**Option 1** - listen for changes in MaterialTable.state.data with reference. (useRef, and UseEffect)
**Option 2** - built in MaterialTable.onSearchChange combined with reference to MaterialTable.state.data
**note, I have included 2 flavors of option 2.**

Thanks @tylercaceres for the example you provided, it didn't fit for me but gave me a hint on how to do it.

Code is found here: [MaterialTableGettingHoldOfRenderData.js](https://gist.github.com/JimiSweden/efa79ca1ff5dc1113ec93f96cd3e4440)
material-table example getting filtered data, the tables current view data, including 2 options and some other examples of actions/buttons, how to use SvgIcon from Material-UI
