### ISSUE TITLE
Provide ability to customize icon, checkedIcon and indeterminateIcon from Checkbox-API 

### ISSUE THREAD

**Issue by StefanJelner** [mbrn/material-table#1128]
At the moment it is not possible to change the 3 icon states (`icon`, `checkedIcon` and `indeterminateIcon` from Checkbox-API https://material-ui.com/api/checkbox/ ) for the checkboxes. I already had a look into the source code and as far as i understand the only possible solution would be to write custom header and row components, which is far out of scope for the requirement to make material-table completely stick to my styleguide.

So what i would really like to see are 3 new icon-keys. For example:
```
Checkbox: ReactElement
CheckboxChecked: ReactElement
CheckboxIndeterminate: ReactElement
```

Or a way to provide options to the Checkbox-components, which become used.

**Comment by jayarjo** [comment]
@mbrn this is what I'm talking about. So less config items, but more options to override to ones taste and needs.

**Comment by Domino987** [comment]
How would you like to style it ? @StefanJelner

**Comment by StefanJelner** [comment]
> 
> 
> How would you like to style it ? @StefanJelner

Since i would use `ReactElement`s, i could add my own BEM-style class names via `className` and then style it with CSS. Or did you mean something different?

```
Checkbox: <Foo className="bar__baz" />
```

**Comment by Domino987** [comment]
I think you could wrap your app or just the material table with your own Theme Provider from material-ui and override it all the components you need with that:
`const theme = createMuiTheme({
  overrides: {
    MuiCheckbox: {
      root: {
        color: '#fff' // This would make the border white
      }
    }
  }
});`

and wrap the table with:
`
        <MuiThemeProvider theme={theme}>
<MaterialTable>...</MaterialTable>
</MuiThemeProvider>`

Would that fir your use case?

**Comment by StefanJelner** [comment]
No. I can't. Because i use SVG-icons. If i use them as `background-image`, i cannot completely style them, because until now CSS is not capable of shadow-DOM. This is by the way the reason, why libraries, like Fontawesome 5 use Javascript to inject the SVG icons into the DOM.

The Themeprovider is only able to provide CSS-formatting. I want my own SVG-element in the DOM. the other icons can be provided this way, only the checkbox-icons are missing.

**Comment by StefanJelner** [comment]
I thought a little bit about this problem and had an idea:

What about everytime you use an element from material UI, you provide the ability to override your configuration.

You could provide a `prop` called `overrides` (or something like that). Inside this `override` one could make custom configurations. example:

```
<MaterialTable overrides={{ Checkbox: { foo: 'bar' }}} />
```

In your code, when you instantiate `Checkbox` you could add the overrides at the end, so your defaults become overridden by user configuration. example:

```
const conf = {
  checked: false
  , onChange: console.log
  , value: 'baz'
  , color: 'primary'
  , ...this.props.overrides.Checkbox
};

return (
  <Checkbox {...conf} />
);
```

If you do this with every element you use from material UI, the user would be able to override all these elements with custom settings, including also the icons used.
