### ISSUE TITLE
make component completely translatable

### ISSUE THREAD

**Issue by bohrsty** [mbrn/material-table#113]
**Is your feature request related to a problem? Please describe.**
I want to use the component in a translatable project (and even if it never will be translated, my projects default language is german)

**Describe the solution you'd like**
An object of translation strings as prop

**Additional context**
I tried to solve it my self and want to give it back upstream (if you like), pr follows...

**Comment by mbrn** [comment]
Why not?

Let us see your improvements.

**Comment by bohrsty** [comment]
see it in [pr114](https://github.com/mbrn/material-table/pull/114)

**Comment by mbrn** [comment]
I merged pr114 @bohrsty . Thank you for your contribution. It will be in next release after tests
