### ISSUE TITLE
Check if row is still in edit mode

### ISSUE THREAD

**Issue by tomcolaa** [mbrn/material-table#1131]
Hi,

I'm using the material table in a [material-ui Stepper](https://material-ui.com/components/steppers/) and the user tends to click on "next" button even though the table is still in edit mode. This results in a loss of data.

Can I somehow access the table information to check if the table/row is still in edit mode when the user clicks my "next" button

Thank you for any ideas and help.

Cheers,
Tom

StackOverflow Answer: https://stackoverflow.com/questions/58144937/check-if-a-material-table-row-is-still-in-edit-mode

**Comment by jayarjo** [comment]
@tomcolaa 

I encourage you to ask material-table related questions on StackOverflow, so that others could benefit from them as well. I will respond on StackOverflow, if you create a question and link it here.

**Comment by tomcolaa** [comment]
Hi @jayarjo,

sorry, you're right!
Here is the question: https://stackoverflow.com/questions/58144937/check-if-a-material-table-row-is-still-in-edit-mode

Thank you in advance!
Best Tom

**Comment by jayarjo** [comment]
I posted potential solution there.

**Comment by ShevaShen** [comment]
The solution above is not good enough. I saw someone made a PR. Hopefully it will get merged soon.
https://github.com/mbrn/material-table/pull/1184
