### ISSUE TITLE
Clear Filters Button

### ISSUE THREAD

**Issue by Edisonsan** [mbrn/material-table#1132]
There is some method actually to enable a clear filters button?
Must be near or download the ACTIONS header column, something licke CLEAR

**Comment by jayarjo** [comment]
No. There should be. But there's none. Potentially you could add one by overriding `TableFilterRow` component.

PS All caps is interpreted as shouting. So why do you shout at us?

**Comment by Edisonsan** [comment]
> No. There should be. But there's none. Potentially you could add one by overriding `TableFilterRow` component.
> 
> PS All caps is interpreted as shouting. So why do you shout at us?

My apologies; i did modify the title.

How i can use MTableFilterRow to clear the bottom, i try to forceUpload all the component table, reset the state, etc, but nothing works.

**Comment by ATLUSio** [comment]
There's no clear filters button, but if you can still clear filters using methods by accessing the tableRef object. For example:
```let self = this.tableRef.current; // get the tableRef
let query = self.state.query; // get the query obj
self.setState({
    ...self.dataManager.getRenderState(), // set the render state
    query: {
        ...query,
        filters: [] // set filters to nothing
    }
});
// you also need to update the filter value on the column by doing this:
for ( var item in this.tableRef.current.state.query.filters ) {
    let tableColumn = this.tableRef.current.state.query.filters[item].column
    this.tableRef.current.dataManager.changeFilterValue(tableColumn.tableData.id, null)
}```

I don't think this is really "recommended", though. Either way, this is how I do it.
