### ISSUE TITLE
EXTERNAL EXPORT OPTION

### ISSUE THREAD

**Issue by Edisonsan** [mbrn/material-table#1133]
There is some option to add a new dropdown export option like a EXCEL then use another library to generate the excel using the data filtered or result of search?

**Comment by jayarjo** [comment]
Yes: https://material-table.com/#/docs/features/export. Basically you can export whatever is currently visible in the table or do some monkey-patching and decide what gets exported yourself.

**Comment by Edisonsan** [comment]
![image](https://user-images.githubusercontent.com/4142615/65821894-d2290f00-e209-11e9-81cd-04a521e233ab.png)

I mean how to add a new option there, to Export as XLS or PDF using another component or function for that purpose.  I mean create an override as ToolBar override to create a new option to export external function with the filtered rows.

**Comment by jayarjo** [comment]
You can add custom actions: https://material-table.com/#/docs/features/actions. Check a Free Action Example specifically.

**Comment by kwasik-com** [comment]
> You can add custom actions: https://material-table.com/#/docs/features/actions. Check a Free Action Example specifically.

You Can Add External Button Not Inside Export's Button

**Comment by MrChe** [comment]
Bad News, Why not give the opportunity to add other buttons to an existing dropdown?

**Comment by ChanhLy** [comment]
The built in Export button only have one option but still show a dropdown, which could not be modified and set disableScrollLock to false. This needs more work.

**Comment by ervikashkumar** [comment]
> > You can add custom actions: https://material-table.com/#/docs/features/actions. Check a Free Action Example specifically.
> 
> You Can Add External Button Not Inside Export's Button

How can we get the filtered/sorted/searched data there in custom free action component?

**Comment by Jsalvat** [comment]
@ervikashkumar u can't atm and this is so sad XD

**Comment by iamshahraj** [comment]
Install following packages to get option for PDF:  npm install jspdf jspdf-autotable

**Comment by TamjidTayeb** [comment]
Has this feature been added yet? I am unable to add options to the export dropdown

**Comment by HugoBaspin** [comment]
Any news about the feature ? i would like to add some options to the export dropdown too
