### ISSUE TITLE
Allow simple toggle of sort between ASC and DESC

### ISSUE THREAD

**Issue by richpixel** [mbrn/material-table#1134]
**Is your feature request related to a problem? Please describe.**
Currently if I click the sort arrow on a column, it cycles through 3 states as opposed to toggling between asc and desc. The cycle is 'asc', '' (empty, which makes it sort using the first columen), and 'desc')

**Describe the solution you'd like**
I would like to be able to simply toggle between 'asc' and 'desc', which is what the standard material-ui table does.

Thanks a lot

**Comment by jayarjo** [comment]
There's a solution for this, so we need to merge @mbrn: https://github.com/mbrn/material-table/pull/997
