### ISSUE TITLE
Possible to make Table Row click animation?

### ISSUE THREAD

**Issue by 5PK** [mbrn/material-table#1135]
I would like the Table Row on click to have a Material Waves animation across the entire row. 

Does anyone know of the best way to achieve this?

**Comment by jayarjo** [comment]
@5PK 

I encourage you to ask material-table related questions on StackOverflow, so that others could benefit from them as well.

**Comment by 5PK** [comment]
Done: https://stackoverflow.com/questions/58158629/material-table-onrowclick-waves-animation-is-this-possible

Thanks!
