### ISSUE TITLE
Use remote data in functional components

### ISSUE THREAD

**Issue by danipralea** [mbrn/material-table#1139]
**Describe the bug**
I'm trying to implement the table with remote data fetching in a functional/stateless component

**To Reproduce**
1. Create a functional component
2. Try to implement the example (with `useState` hook instead) `const [tableRef, setTableRef] = useState(React.createRef());`
3. it crashes with error :     onGetClients(userAuthToken);

**Expected behavior**
Having the data fetched from server and displayed

**Screenshots**
<img width="546" alt="Screenshot 2019-09-29 21 45 00" src="https://user-images.githubusercontent.com/768893/65837628-768e7c80-e302-11e9-81ff-4b03c809cf54.png">

**Desktop (please complete the following information):**
 - OS: MAC OS
 - Browser: Chrome
 - Version: Version 77.0.3865.90 (Official Build) (64-bit)

**Comment by jayarjo** [comment]
@danipralea and why exactly you think that storing a component ref in a state is good idea?

**Comment by danipralea** [comment]
Because you're doing it in the docs?

**Comment by naudej** [comment]
@danipralea Do you perhaps have an example of a functional component that uses remote data, im very new to React and im only familiar with class components but the project im on only uses functional components. Please any assistance would be greatly appreciated .
