### ISSUE TITLE
Edit all rows in a table at once

### ISSUE THREAD

**Issue by mktanksley** [mbrn/material-table#1142]
**Is your feature request related to a problem? Please describe.**
When editing rows in the table, if you tab from one row to the next and select the next edit button your edits are not saved because you didn't click on the edit button. This makes sense but if you are making a lot of changes to the table and want to stick to tab navigation it can get a little annoying.

**Describe the solution you'd like**
I would like to be able to click one button to unlock all rows to editing at once. That way I can just edit the whole table by tabbing through instead of clicking the edit button for each row.

**Describe alternatives you've considered**
The alternative is I will need to either click edit  buttons for each individual row of the table, or use an upload button elsewhere on my project to make changes to the database when I have more than a few rows of data that need updating.

**Additional context**
Thank you for your consideration.

**Comment by jayarjo** [comment]
I think this question got some feedback at SO. Will close it here.
