### ISSUE TITLE
filtering with highlights

### ISSUE THREAD

**Issue by mstruensee** [mbrn/material-table#1144]
I am wanting to use react-highlight-words to highlight my custom rendered column cell, but I do not have access to the "term" ...

I tried setting it with useState, works but causes a re render, clearing filter value.
I tried setting it with redux action, same thing, works but causes re render, clearing filter value.

Is there anyway I can get the "term" inside of the "render" callback for my column?

EDIT: for now I cheated, set a class level variable inside of customFilterAndSearch and accessed it inside of render ... setting it at the class level allowed updates to happen without re-renders.

**Comment by jayarjo** [comment]
You could potentially store it in a ref with `useRef`. Or you could try to extract it from table state via a tableRef property. But I agree it should be more easily accessible through the table itself.

**Comment by jayarjo** [comment]
@mstruensee 

I encourage you to ask material-table related questions on StackOverflow, so that others could benefit from them as well.

**Comment by mstruensee** [comment]
I was thinking the same, thing ... adding "term" to the tableData that is on each row.
Thanks for the SO link!  Will start using that.  I will give the ref a try today and let you know how it goes.  

Thanks again for the suggestion.

**Comment by mstruensee** [comment]
ref works!

```
const tableRef = useRef()
const searchText = get(tableRef, "current.state.searchText") //inside each render ...
```

Thanks again!
