### ISSUE TITLE
How to remove the overlay loader

### ISSUE THREAD

**Issue by yashSangai** [mbrn/material-table#1148]
Great library.
Just want one help, how can I remove the overlay loader completely from the table? @mbrn

**Comment by jayarjo** [comment]
@yashSangai 

I encourage you to ask material-table related questions on StackOverflow, so that others could benefit from them as well. I will respond on StackOverflow, if you create a question and link it here.

**Comment by yashSangai** [comment]
@jayarjo Here it is
https://stackoverflow.com/questions/58213945/how-to-remove-the-overlay-loader-from-material-table
