### ISSUE TITLE
Validating the TextField when using inline editable

### ISSUE THREAD

**Issue by hungbang** [mbrn/material-table#1152]
I'm using material table with inline editing mode, and now I want to all of inline editing fields are required, if the user leaves the input is empty or something like that, material table should display error message and disable the buttons.

At the moment, I have to use the `editComponent` to override the input. is there anyway to I can do it by material table without overriding?

**Comment by jayarjo** [comment]
@hungbang 

I encourage you to ask material-table related questions on StackOverflow, so that others could benefit from them as well. I will respond on StackOverflow, if you create a question and link it here.

**Comment by hungbang** [comment]
@jayarjo I've added the question on the Stackoverflow, please take a look at here: 
https://stackoverflow.com/questions/58245987/validating-the-textfield-when-using-inline-editable
