### ISSUE TITLE
How To Render Custom Autocomplete Select in columns lookup field?

### ISSUE THREAD

**Issue by RamilMamedo** [mbrn/material-table#1155]
Default lookup field rendered Select element looks like this:

<img width="916" alt="Screen Shot 2019-10-04 at 12 31 19 PM" src="https://user-images.githubusercontent.com/38986496/66193145-0a659d00-e6a3-11e9-95b3-d706ef293b82.png">

I want to replace it with Autocomplete Select element **only on row add or edit** is this possible? 
<img width="1155" alt="Screen Shot 2019-10-04 at 12 31 39 PM" src="https://user-images.githubusercontent.com/38986496/66193187-1baea980-e6a3-11e9-9690-cf7f3e9ab8cd.png">

Thanks in evidence!

**Comment by hungbang** [comment]
Is there any update for this issue?

**Comment by flyingangel** [comment]
Try editComponent and create your own custom component

**Comment by RamilMamedo** [comment]
> Try editComponent and create your own custom component

Okay, will try it. Thank you

**Comment by hungbang** [comment]
@RamilMamedo 
This is what I did to render custom autocomplete select in material table : 
I was using the `react-select`.
`{
        title: 'Owner',
        field: 'owner',
        cellStyle: { fontSize: '1.3rem', minWidth: '300px' },
        render: rowData => {
          if (rowData && rowData.owner) {
            const ownerSplit = _.split(rowData.owner, '-');
            return ownerSplit[2];
          }
        },
        editComponent: props => (
          <FormControl
            className="mt-8 mb-16 text-13 min-w-320"
            fullWidth
            onBlur={this.autoSubmit}
          >
            <Async
              value={this.defaultValue(props)}
              loadOptions={this.promiseOptions}
              defaultOptions
              cacheOptions
              placeholder={'Search owner...'}
              onChange={e => {
                props.onChange(e.value);
              }}
              onBlur={this.autoSubmit}
            />
            {!props.rowData.owner && (
              <FormHelperText style={{ color: '#f44336' }}>
                Owner is required!
              </FormHelperText>
            )}
          </FormControl>
        )
      }`

**Comment by RamilMamedo** [comment]
> @RamilMamedo
> This is what I did to render custom autocomplete select in material table :
> I was using the `react-select`.
> ![image](https://user-images.githubusercontent.com/10163092/66280647-dc21d080-e8e1-11e9-8e7d-d5eb1a6df939.png)

I created custom autocomplete select but when adding new item, can't get autocomplete's value. 

<img width="1404" alt="Screen Shot 2019-10-07 at 12 56 43 PM" src="https://user-images.githubusercontent.com/38986496/66298034-f7043d00-e901-11e9-8355-723f1384c203.png">

**Comment by RamilMamedo** [comment]
Thank you! I handled this! 

![code](https://user-images.githubusercontent.com/38986496/66318482-71e24d80-e92c-11e9-9a5a-1e869e1d2fad.png)

**Comment by Raiishin** [comment]
Does anyone know how to replicate the autocomplete but on the searchbar? I can't seem to find it anywhere! Thanks so much !

**Comment by eilman** [comment]
Hello, I examined your question and solution. I have the same problem. I want to convert texfield to autocomplete textfield on add and edit functions of material table. I tried to apply your solution but I do not understand one thing.. Why did you set field to 'category.id' and where did "Categories" come from ? I would be happy if you answer these questions.. Thanks!

**Comment by AleOjeda** [comment]
Looking at the day the question was posted, I'm sure it's late. Btw, I hope this post helps anyone. 
'category.id' within the lookup function makes that 'category.id' is posted to the api and, at the front end it's showed the 'category.name'. I'm sure in the DB the table is 'category.id' || 'category.name'.
regarding the second question: 
"where did "Categories" come from?", the component must have a father and when this component is called, Categories is passed as a prop.
