### ISSUE TITLE
Can't change row's text color using rowStyle

### ISSUE THREAD

**Issue by saulojoab** [mbrn/material-table#1158]
**Describe the bug**
I am trying to style the row text color on the table. I managed to change the background color just fine, but for some reason, the text won't change colors at all.

**To Reproduce**
Create a table then use this as the option props:
```js
options={{
 rowStyle: {
   backgroundColor: '#334551', 
   color: 'white !important', // not working! i tried without the !important as well
 },
}}
```
The background color will change but the text color remains the same.

**Screenshots**
The row text is supposed to be white, but as you can see, it doesn't work.

![image](https://user-images.githubusercontent.com/37988252/66210011-27907080-e68f-11e9-9215-01b9dd42c7e4.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Opera
 - Version 63.0.3368.94

**Comment by jayarjo** [comment]
PRs are welcome.

**Comment by sshanzel** [comment]
I've found a way how to accommodate this, please let me know where do you prefer it to be specified. Is it at options for `rowStyle` or `cellStyle`?

**Comment by DustinRobison** [comment]
I created a PR for this so that table cells inherit a color by default

**Comment by sshanzel** [comment]
PR for `cellStyle` to actually take effect.
