### ISSUE TITLE
Better treeshaking and webpack bundle size for optional features / tooltips optional

### ISSUE THREAD

**Issue by StefanJelner** [mbrn/material-table#1161]
Recently i am spending a lot of time on optimizing the size of my bundle.

What i found out is, that even i do not use the drag&drop- and tooltip-Feature, `react-beautiful-dnd` and `popper.js` still become included in the webpack bundle, which means ~380KB useless code in my bundle.

1. It would be very nice if tooltips would be an optional feature
2. It would be very nice if tooltips and/or drag&drop are optional, the related libraries are not included into the webpack bundle, which means better treeshaking.

**Comment by jayarjo** [comment]
PRs are very welcome.
