### ISSUE TITLE
how to read columns headers after dragging using reactjs

### ISSUE THREAD

**Issue by PATTANPARVIN** [mbrn/material-table#1164]
how to get columns headers array while dragging occurred

**Comment by jayarjo** [comment]
@PATTANPARVIN 

I encourage you to ask material-table related questions on StackOverflow, so that others could benefit from them as well. I will respond on StackOverflow, if you create a question and link it here.

**Comment by PATTANPARVIN** [comment]
okay sure.

**Comment by PATTANPARVIN** [comment]
https://stackoverflow.com/questions/58297402/how-to-read-material-table-column-headers-array-while-dragging-occurred-using-re

**Comment by PATTANPARVIN** [comment]
@jayarjo 
can you plz find above link..
