### ISSUE TITLE
How to change default sorting icon on table header column ?

### ISSUE THREAD

**Issue by sekittipat** [mbrn/material-table#1165]
Can I change the default sorting icon on table header column ? ex. I want to change asc sorting icon to  ArrowDownward and desc sorting icon to ArrowUpward. I try to set SortArrow icons props on MaterialTable but its show on every table header columns even its not active sorting column. Please help. 

Example: active sorting column is User ID (asc)

Code: 
`<MaterialTable
...         
icons={{
            SortArrow: () => <ArrowDownwardIcon />
          }}`

Output: 
![image](https://user-images.githubusercontent.com/40179890/66303163-94706880-e924-11e9-81ba-8c8cdda1076a.png)

**Comment by jayarjo** [comment]
@sekittipat 

I encourage you to ask material-table related questions on StackOverflow, so that others could benefit from them as well. I will respond on StackOverflow, if you create a question and link it here.

**Comment by sekittipat** [comment]
@jayarjo 

Here is my question link on StackOverflow.
[https://stackoverflow.com/questions/58285674/how-to-change-default-sorting-icon-on-table-header-column-on-react-material-tabl](url)

**Comment by sekittipat** [comment]
@jayarjo 

Here is my question link on StackOverflow.
[https://stackoverflow.com/questions/58285674/how-to-change-default-sorting-icon-on-table-header-column-on-react-material-tabl](https://stackoverflow.com/questions/58285674/how-to-change-default-sorting-icon-on-table-header-column-on-react-material-tabl)

**Comment by Domino987** [comment]
Can we close this issue since it is answered?
