### ISSUE TITLE
Custom sort arrow not rotating 

### ISSUE THREAD

**Issue by unnikrishna** [mbrn/material-table#1167]
**Describe the bug**
I was trying to use custom icons in this table
`icons={{
          Search: SearchIcon,
          ResetSearch: ClearIcon,
          DetailPanel: DetailPanelIcon,
          Check: '',
          Filter: SortIcon,
          SortArrow: SortIcon,
        }}`

`const SortIcon = () => <Icon iconName="SortUp" className="ms-IconExample" />;`
![icon](https://user-images.githubusercontent.com/10768507/66465417-70389700-ea9e-11e9-9e2d-eb24003e5f84.PNG)

**Problem** 
So when i use custom icon for sort-arrow the following issues is what i encountered

1. it is showing by default,
2. When clicking for sorting the icon is not rotating

but when DetailPanel icon is working as expected

**Comment by jayarjo** [comment]
Even if you click multiple times?

**Comment by Domino987** [comment]
You have to wrap the icon with forward Ref like this as mentioned in the readme:
`Add: forwardRef((props, ref) => <AddBox {...props} ref={ref} />),`

**Comment by unnikrishna** [comment]
I have already tried this but still same issue is there

**Comment by Domino987** [comment]
Can you provide a codepen to reproduce it? It works fine for me with the forwardRef wrapper.

**Comment by unnikrishna** [comment]
https://codesandbox.io/s/material-table-with-grouped-rows-rf7k7
it just sample code for your reference

**Comment by Domino987** [comment]
You pass the props to MyIcon but MyIcon does not pass them to the span and are lost. Do it like this:
`const MyIcon = (props) => (
  <span {...props}>
    <ArrowUpwardIcon />
  </span>
);
`

**Comment by unnikrishna** [comment]
Great that helps, sorry from my side, i shouldn't have miss that, now it works like a charm thank you.

**Comment by Discartyptics** [comment]
Sort of related, but if anyone else is having this issue, also check to make sure your column sorting is lowercase, i.e. "asc" rather than "ASC".
