### ISSUE TITLE
Override checkbox icon filter / add row

### ISSUE THREAD

**Issue by Totalbug92** [mbrn/material-table#1169]
**Describe the bug**
When I override the Check and ThirdStateCheck with my own checkbox icons it doesn't apply to add / edit row and when the filter is enabled. 

Also for some reason, the Check icon override also applies to the confirmation button when adding/deleting/editing a row. 

**To Reproduce**
1. Create a column that has the type 'boolean'
2. Override the Check and ThirdStateCheck with your own icons
3. Try to edit, filter, add or delete a row

**Expected behavior**
I expect the checkbox overriding that I'm trying to do to apply to all checkboxes.
I also don't expect it to override the confirmation button when adding/deleting/editing a row, both of those buttons should probably have their own Icon override functionality. 

**Screenshots**
![image](https://user-images.githubusercontent.com/32250965/66489127-63706f00-eaaf-11e9-9a91-1b4b941c8379.png)

___

![image](https://user-images.githubusercontent.com/32250965/66489148-6cf9d700-eaaf-11e9-9599-ab3b1ab68dd7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 77.0.3865.90

**Comment by sshanzel** [comment]
Is it possible for you to provide a simple fiddle for this? I would really appreciate it!

**Comment by Totalbug92** [comment]
> I am able to actually modify the Icons you mentioned:
> ![image](https://user-images.githubusercontent.com/13744167/66983734-4bf63f00-f0ca-11e9-8e35-f7da61057a39.png)
> Is it possible for you to provide a simple fiddle for this? I would really appreciate it!

Maybe I didn't explain myself well enough. But you have the same error as I have 
![image](https://user-images.githubusercontent.com/32250965/66990881-5531dc80-f0c7-11e9-80fe-6fd3f5857379.png)

The pink checkmark should, in my opinion, look the same as the overridden check icons you have below. Or you should at least be able to override it yourself. Also try to check out how the icons look like when you try to add, edit or delete a row with these icons overridden. 

I'll try to make a JSFiddle when I have time, though tbh it's a tool I haven 0 experience in using.

**Comment by sshanzel** [comment]
Okay, will look into it. Thanks!

**Comment by AnhTuan-AiT** [comment]
Override <b>Header</b> by using <b>components</b> attribute  is the way to go:

```javascript
components = {
  Header: (props) => (
    <MTableHeader
      {...props}
      options={{
        ...props.options,
        headerSelectionProps: {
          ...props.options.headerSelectionProps,
          indeterminateIcon: <RemoveCircleIcon fontSize="small" />,
          icon: <RadioButtonUncheckedIcon fontSize="small" />,
          checkedIcon: <CheckCircleIcon fontSize="small" />,
        },
      }}
    />
  ),
};
```

Hope this help :))
