### ISSUE TITLE
Filtering just one column

### ISSUE THREAD

**Issue by hrafaelveloso** [mbrn/material-table#117]
**Describe the bug**
It is impossible to choose the filter in only one column. If you have the option `filtering: true` in the `options`, all the `columns` have the filter active, even if you put `filtering: false` in the `columns` where I do not want the filter to be active

**To Reproduce**
1. Add one `filtering : true` to one column;
2. Filter don't appear;
3. Add `filtering : true` to `<MaterialTable /> options`;
4. All filters appear in all `columns`. 

**Expected behavior**
Appear just one filter in one column.

**Screenshots**
![print1](https://user-images.githubusercontent.com/22391919/50008071-e2d60480-ffaa-11e8-9af4-a486aea80c02.png)

With these `columns` if I have `filtering: true` in the `options`, the filter appears in all columns. If you have `filtering: false` in the `options`, no filter appears. If you do not have the `filtering` option in the `options`, the filters do not appear either.

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser: Chrome
 - Version: 67.0.3396.99

**Comment by mbrn** [comment]
Hi @hrafaelveloso ,

Which version of material-table do you use?. Because i try it with latest and it works properly. 

can you check it again?

**Comment by hrafaelveloso** [comment]
Hi @mbrn, the version that I'm using is `1.7.0`

**Comment by mbrn** [comment]
This is strange. I tried it in docz and it works. 

![image](https://user-images.githubusercontent.com/7895451/50080861-1f4d6e80-01fe-11e9-97fc-479bf5fa7390.png)

**Comment by mbrn** [comment]
And I tried it in demo.js and it works again. Please run `npm ls material-table` in your project. And be sure it is 1.7.0

**Comment by mbrn** [comment]
I found the problem :). It is my mistake. It will be in next release. I added to release notes mistakenly.

https://github.com/mbrn/material-table/blob/v1.7.0/src/m-table-filter-row.js#L122

Sorry for this.

**Comment by hrafaelveloso** [comment]
No problem :) Waiting for next release then :+1:

**Comment by mbrn** [comment]
You can try 1.8.0 @hrafaelveloso :)
