### ISSUE TITLE
Is this repo dead?

### ISSUE THREAD

**Issue by oze4** [mbrn/material-table#1171]
I have noticed Pull Requests are not being merged/considered... the author is rather unresponsive.... just seeing lots of signs of a stagnant, dead repo..

Is this the case?

**Comment by ifndefdeadmau5** [comment]
I don't think so. There is even a merged PR in 3 days ago, looks like just there are too many issues & PR to handle.

**Comment by jayarjo** [comment]
@oze4 any particular PR in mind? Author is busy these days for sure. So doesn't have any time for implementing features or fixing bugs. But easy to follow, well argumented PRs are merged right away.

**Comment by jayarjo** [comment]
@oze4 in fact let me recommend you as a collaborator/contributor to the author. What do you think?

**Comment by oze4** [comment]
@jayarjo I'd be happy to help in any way I can. Especially if the author is quite busy these days. 

Happy to help.

**Comment by Domino987** [comment]
I would volunteer as well if @mbrn needs help!

**Comment by jayarjo** [comment]
@mbrn people are looking to help.

**Comment by jayarjo** [comment]
@Domino987 @oze4 can you guys have a look, if such change is justified: https://github.com/mbrn/material-table/pull/1201? I've got a vague idea of TypeScript typings for React :)

**Comment by oze4** [comment]
@jayarjo @Domino987 - same here, I am not very familiar with TypeScript typings..

**Comment by Domino987** [comment]
I am but it works on my machine so I asked him to share some code/error message. We will see.

**Comment by Domino987** [comment]
Ok #1201  can be approved. There was one case, where it did not work so this fixes that. @jayarjo
