### ISSUE TITLE
Wrong variant in button in m-table-stepped-pagination.js

### ISSUE THREAD

**Issue by jonasanx** [mbrn/material-table#1172]
I get the following error.

`Warning: Failed prop type: Invalid prop 'variant' of value 'default' supplied to 'ForwardRef(Button)', expected one of ["text","outlined","contained"].`

https://github.com/mbrn/material-table/blob/2dd0ca780abeda0b98445e986b9a39630aaca10e/src/components/m-table-stepped-pagination.js#L39

As explained in the error log, there's no a variant="default" option in the button component in `@material-ui/core ^4.5.0`  the available variants are: text, outlined and contained.

**Comment by jayarjo** [comment]
PRs are welcome!
