### ISSUE TITLE
Paging doesn't work on remote data

### ISSUE THREAD

**Issue by IcarusHU** [mbrn/material-table#1176]
I've added a remote data source to the data attribute, but I don't want paging to be handled by the server, but on the client side. However, after the data loads in, the rows shop up properly, even the row display changer is working, but the pager shows NaN/NaN of undefined and does not work. I tried the same code and structure with static data, this way the paging works perfectly.

On the second screen, you can see the data query structure, I deliberately omitted page and totalCount parameters, to have an automatic paging, but it doesn't work this way

![image](https://user-images.githubusercontent.com/7024470/66584709-e9f78000-eb85-11e9-958f-bd8e15b11714.png)

![image](https://user-images.githubusercontent.com/7024470/66584865-2dea8500-eb86-11e9-9a03-496731514ed5.png)

**Comment by jayarjo** [comment]
If you don't want material-table to query your server, fetch data yourself and feed it to it as if it was local.
