### ISSUE TITLE
Customize GroupRow when grouping by default

### ISSUE THREAD

**Issue by tebayoso** [mbrn/material-table#1179]
**Is your feature request related to a problem? Please describe.**
Not a problem, just wanting to add some functionality to the group table.

**Describe the solution you'd like**
When grouping in datatables, I will like an option to provide a custom render to the tablerow that's generated, because currently there's no way to get metadata in there. Amount of elements? 

**Describe alternatives you've considered**
I tryed the tree view, but it groups under a parent element, and I need to create a whole new class: Category row, inside the table.

**Additional context**
This is the element I want to customize.

![image](https://user-images.githubusercontent.com/881714/66650407-ece68500-ec06-11e9-9271-ccf005156816.png)

**Comment by zipzapp** [comment]
Hello, I have the same question as the OP here. Is there a recommended/build-in approach?
