### ISSUE TITLE
Header Checkbox: Styling to Work with Header Styling

### ISSUE THREAD

**Issue by chriszwickerocteris** [mbrn/material-table#1181]
## Problem

When styling the header row (e.g. with a dark background), the selection checkbox becomes hard to see. It would be good if it was possible to style it.

## Proposal

I believe the simplest option would be an additional prop that would allow to style the checkbox (e.g. `selectAllCheckboxProps`) in line with the existing `selectionProps`.

An alternative would be not to allow individual styling, but to use the header style's `color` attribute as the header checkbox' color.

I believe the best possible solution would be to combine the two:
* if the header is styled, use the header style's `color` attribute as the checkbox color by default
* allow overriding this default with an explicit `selectAllCheckboxProps` attribute.

**Comment by flyingangel** [comment]
When it comes to customization, the best is to use Component Overriding technique which allow the user to customize more things than just styles.
