### ISSUE TITLE
Update table data locally

### ISSUE THREAD

**Issue by Tighrine** [mbrn/material-table#1192]
I got an issue when I try to update the table data locally using an action that block or unblock a device. I got this issue: 
![image](https://user-images.githubusercontent.com/25404529/66738914-dd1da980-ee6f-11e9-8594-b6e726e13233.png)
 Here is my first data:

`const [data, setData] = React.useState({
        content: [
            { id: 1, osVersion: "IOS 10", udid: "AB456875DSDSS54545dsD", user: "User 1", status: true },
            { id: 2, osVersion: "Android 9", udid: "AB456875DSDSS54545dsD", user: "User 2", status: false },
            { id: 3, osVersion: "IOS 12", udid: "AB456875DSDSS54545dsD", user: "User 1", status: true },
            { id: 4, osVersion: "Android 8", udid: "AB456875DSDSS54545dsD", user: "User 1", status: false },
            { id: 5, osVersion: "Android 7", udid: "AB456875DSDSS54545dsD", user: "User 3", status: true },
            { id: 6, osVersion: "IOS 11", udid: "AB456875DSDSS54545dsD", user: "User 1", status: false },
            { id: 7, osVersion: "IOS 10", udid: "AB456875DSDSS54545dsD", user: "User 3", status: false }
        ]
    })`

**Comment by Tighrine** [comment]
I noticed that material-table add "tableData" field to my state

**Comment by Domino987** [comment]
Yes but this will be removed with #1174 , I hope.

**Comment by Domino987** [comment]
It fails because data looks like this :
{content: [...]} But it has to be [...].
So remove the content wrapper and you should be fine.

**Comment by Tighrine** [comment]
But I use it like this data.content so it is like this [...]

**Comment by Domino987** [comment]
Ah ok , than it should not fail. Can you reproduce that in a Sandbox?
