### ISSUE TITLE
Change default text in onRowDelete fuction

### ISSUE THREAD

**Issue by Nolandos** [mbrn/material-table#1194]
Hello,

Can I change default text for onRowDelete function ? 
<img width="735" alt="Bez tytułu" src="https://user-images.githubusercontent.com/44065286/66749897-54146b80-ee8b-11e9-8fa8-1ffabb7f11a8.png">
or text tooltip ?

**Comment by Domino987** [comment]
You can pass a [localisation object](https://material-table.com/#/docs/features/localization) to material table and override body.deleteTooltip for example.

**Comment by Nolandos** [comment]
@Domino987 Thank You !
