### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by Domino987** [mbrn/material-table#1196]
**Describe the solution you'd like**
I think to provide a better library, we should think about writing tests so that new commits don't break existing code. What do you guys think?  I you are on board, I would start wiritng some this week ?@mbrn , @jayarjo

**Comment by jayarjo** [comment]
Absolutely. There's a housekeeping PR that layed down the ground for such initiative. However I personally think that other PRs must be handled first or we'll get conflicts all around the code base.

Has been merged but then reverted: https://github.com/mbrn/material-table/pull/979
