### ISSUE TITLE
Select Parents instead of Children at Tree Data

### ISSUE THREAD

**Issue by Roseidon** [mbrn/material-table#1202]
I currently try to build a tree sructure guided by the "tree data example" and came to a use case not yet considered.

Normally, when you have unselected tree data
![Unselected](https://user-images.githubusercontent.com/19248263/66812882-056edc00-ef34-11e9-9dcb-f071da7fb532.png)
and you select an item (e.g. a), the tree selects all children of that item
![SelectChildren](https://user-images.githubusercontent.com/19248263/66812883-056edc00-ef34-11e9-82c0-f592cccc3208.png)
which is the most common use case for a tree.

But in my case, I would like to select all parents of a certain item (e.g. d).
![SelectParents](https://user-images.githubusercontent.com/19248263/66812884-056edc00-ef34-11e9-81c3-1eb08b5b67f0.png)

I imagine the solution as kind of a flag you can set in the table, and you can choose whether you want to select children or parents of an item, when selecting it.

**Comment by Domino987** [comment]
I would try to reduce the amount of props and would let you handle it with onSelectionChange. That would not be possible without a lot of work and manipulating the local data right now but with the next release, you will be able to do it like this:

     const [stateData, setData] = useState(data);

     const handleSelectChange = (rows, row) => setData(oldData => oldData.map(d => d.id === row.id ? { ...d, tableData: { ...row.tableData, checked: row.tableData.checked} } : d))

    <MaterialTable
          title="Basic Tree Data Preview"
          data={stateData}
          columns={columns}
          parentChildData={(row, rows) => rows.find(a => a.id === row.parentId)}
          onSelectionChange={handleSelectChange}
           options={{
                selection: true
           }}
        />
  `
