### ISSUE TITLE
when i set data table in a container, it exceeds container, how i fix this issue

### ISSUE THREAD

**Issue by indraneelpradhan** [mbrn/material-table#1203]
please help me how to fix this problm, its needed

**Comment by Domino987** [comment]
I encourage you to ask material-table related questions on StackOverflow, so that others could benefit from them as well. I will respond on StackOverflow, if you create a question and link it here.

**Comment by indraneelpradhan** [comment]
https://stackoverflow.com/questions/58410081/when-i-put-material-table-react-in-container-it-exceeds-than-container-size-h

**Comment by indraneelpradhan** [comment]
Please help me ? I need this, please
