### ISSUE TITLE
how to customize the fonts  in Material-table

### ISSUE THREAD

**Issue by ramyam07** [mbrn/material-table#1204]
Font is looking small in every component, please suggest me to increase the font size explicitly in groupbar and pagination

How to install MuiThemeProvider, i am trying this also but saying component is not availble

**Comment by Domino987** [comment]
I encourage you to ask material-table related questions on StackOverflow, so that others could benefit from them as well. I will respond on StackOverflow, if you create a question and link it here.

**Comment by ramyam07** [comment]
https://stackoverflow.com/questions/58400106/material-table-1204-how-to-customize-the-fonts-in-groupbar-pagination-in-rea
