### ISSUE TITLE
Pre-select/check table data

### ISSUE THREAD

**Issue by wboyle-erwin** [mbrn/material-table#121]
Looking at the selection example, I am not sure if there is a means to pre-select/check table data. Would you happen to have an example that demonstrates pre-selection?

**Comment by mbrn** [comment]
Hi @wboyle-erwin ,

Do you look something like this:

https://mbrn.github.io/material-table/#/docz-examples-05-example-selection

**Comment by wboyle-erwin** [comment]
Yes, I was looking at that example. However, the initial state of data is unselected. Is there an example where a row is preselected?

**Comment by mbrn** [comment]
Yes we will do it. This is duplicate issue of #96. So i am closing this. Please wait for next releases
