### ISSUE TITLE
CellStyle is not actually working

### ISSUE THREAD

**Issue by sshanzel** [mbrn/material-table#1213]
**Describe the bug**
Data placed in `options` for `cellStyle` is not actually being passed down to the cells.

**To Reproduce**
Apply any styling property to `cellStyle`. It won't reflect in any case. 

**Expected behavior**
Cell style should follow as the option provided

**Comment by sshanzel** [comment]
I already checked and forked the project. Will make a PR once someone declares this as a valid issue

**Comment by jayarjo** [comment]
@sshanzel please do.

**Comment by sshanzel** [comment]
@jayarjo i've actually created the PR (#1214) already but this issue wasn't verified yet back then, that's why it was closed for the meantime. Should i be creating another PR or we would reopen the referenced PR?
