### ISSUE TITLE
Where is the material-table documentation project?

### ISSUE THREAD

**Issue by South-Paw** [mbrn/material-table#1217]
Hi 👋,

I'd like to have a shot at contributing to the project's documentation and make some improvements to UX and the content.

However, I can't find a Github repository for it and there is no links to it on the site or from this project.

Could a maintainer please let me know where I can find it?

**Comment by flyingangel** [comment]
You need to search in the owner's github repository list : https://github.com/mbrn/material-table.com

**Comment by South-Paw** [comment]
Did have a search before I asked couldn't seem to find it. Thanks for linking 👍
