### ISSUE TITLE
Support draggable rows

### ISSUE THREAD

**Issue by rnielsen** [mbrn/material-table#1219]
**Is your feature request related to a problem? Please describe.**
It would be nice if material-table would support reordering rows by dragging them

**Describe the solution you'd like**
A new option to mark a table as row draggable and a callback to be notified when a row is dragged.

**Describe alternatives you've considered**
Is this possible to achieve by overriding components and using react-beautiful-dnd ?  If so, this would be fine but I think a built-in option would be cleaner.

**Comment by jayarjo** [comment]
Rows are typically sorted according to the corresponding column and order direction. I don't see how something like you suggest might be useful. Mind to describe the case?

**Comment by rnielsen** [comment]
Sure.   The use case is where the order of rows is important, such as a list of rules where the first rule is applied first.  The user would drag around the rules in the order that they like and this order would be persisted on the server - you would most likely disable the column sorting feature for this use case.  Usually when this feature is available a Drag Handle icon is added to the row.

Here's an example from another project: https://www.ag-grid.com/javascript-grid-row-dragging/

**Comment by mathiashoeld** [comment]
i would also like to see this feature. i'd like to test material tables for one of the projects i'm working on, but can't unless this feature is implemented.

**Comment by Satsh24** [comment]
I definitely need this feature. I'm using material-table and love it. I'm surprised they don/t draggable rows feature. I have a requirement for something like drag and drop rows. I've various options like overriding the MTableBody and MTableRow with react-beautiful-dnd but of no use.

**Comment by jayarjo** [comment]
PRs are welcome - never forget :P

**Comment by Nderim1** [comment]
I would also need this feature. Is there a workaround I can implement meanwhile?

**Comment by n-sviridenko** [comment]
+1

**Comment by josepichu** [comment]
+1 here.

**Comment by kslysz** [comment]
+1

**Comment by mrcesc0** [comment]
+1

**Comment by mrcesc0** [comment]
+1

**Comment by awmoreira** [comment]
+1

**Comment by Eugenelee** [comment]
+1

**Comment by JosielLima** [comment]
+1

**Comment by rogeliotg** [comment]
+1

**Comment by murilopf** [comment]
+1

**Comment by urkob** [comment]
+1

**Comment by vernonmanuela** [comment]
+1

**Comment by cadupedroni** [comment]
+1

**Comment by roger1618** [comment]
+1

**Comment by yinchen618** [comment]
+1 thans!!

**Comment by mzparacha** [comment]
+1

**Comment by Prasanna-ramesh** [comment]
+1

**Comment by kishanio** [comment]
+1

**Comment by diogosmendonca** [comment]
+1

**Comment by StefanJanuschke** [comment]
+1

**Comment by agustinbc** [comment]
+1

**Comment by Ardeshir81** [comment]
+1

**Comment by maolivieri** [comment]
+1

**Comment by aamirafridi** [comment]
It will be tricky in a tree structure

**Comment by vuk-niko** [comment]
Any news on this topic ? 
thanks

**Comment by martin-trajanovski** [comment]
+1

**Comment by ekremkenter** [comment]
+1

**Comment by Rymou** [comment]
+1

**Comment by rucsacman** [comment]
Overriding row component I was able to give drag support. Please check may be helping you as well

```
 components={{
                                        Row: props => (
                                            <MTableBodyRow {...props}
                                                draggable="true"
                                                onDragStart={(e) => {
                                                    console.log('onDragStart');
                                                    DrageState.row = props.data.tableData.id

                                                }}

                                                onDragEnter={e => {
                                                    e.preventDefault();
                                                    if( props.data.tableData.id != DrageState.row){
                                                        DrageState.dropIndex = props.data.tableData.id ;

                                                    }                                                  
                                                }}

                                                onDragEnd={(e) => {
                                                    console.log(`onDragEnd`);
                                                    if(DrageState.dropIndex != -1){
                                                        reodering({index: DrageState.row, dropIndex: DrageState.dropIndex})
                                                    }
                                                    DrageState.row = -1;
                                                    DrageState.dropIndex = -1;

                                                }}
                                            />

                                        )
                                    }
```

**Comment by piscespieces** [comment]
@rucsacman dude, it looks like a cool quick solution but I can't understand it. There are misspelling errors and stuff that get me confused.

**Comment by Lory1990** [comment]
+1

**Comment by rucsacman** [comment]
> @rucsacman dude, it looks like a cool quick solution but I can't understand it. There are misspelling errors and stuff that get me confused. What's DrageStatus ?

Hi Dude Yes it should be DragState
`const DrageState = {
    row: -1,            //current row
    dropIndex: -1 // drag target
};`

Sorry for the confused

**Comment by rafaelslug** [comment]
I have this error "'rendering' is not defined"

**Comment by dekelb** [comment]
I see that there are still comments about this feature request.

For everyone that is still looking for a solution - there was a PR opened with a complete implementation of that.
You can check #1995 (Draggable rows / rows reordering / drag & drop rows).

The PR was closed because the maintainer decided to close all "big" PRs and not merge them before a refactoring phase to the library (which is currently undergoing, but there is no ETA for when it will be done).

Maybe if more people will try and push it inside the maintainer will do so.

**Comment by yashaswinibprasad87** [comment]
> Overriding row component I was able to give drag support. Please check may be helping you as well
> 
> ```
>  components={{
>                                         Row: props => (
>                                             <MTableBodyRow {...props}
>                                                 draggable="true"
>                                                 onDragStart={(e) => {
>                                                     console.log('onDragStart');
>                                                     DrageState.row = props.data.tableData.id
> 
>                                                 }}
> 
>                                                 onDragEnter={e => {
>                                                     e.preventDefault();
>                                                     if( props.data.tableData.id != DrageState.row){
>                                                         DrageState.dropIndex = props.data.tableData.id ;
> 
>                                                     }                                                  
>                                                 }}
> 
>                                                 onDragEnd={(e) => {
>                                                     console.log(`onDragEnd`);
>                                                     if(DrageState.dropIndex != -1){
>                                                         reodering({index: DrageState.row, dropIndex: DrageState.dropIndex})
>                                                     }
>                                                     DrageState.row = -1;
>                                                     DrageState.dropIndex = -1;
> 
>                                                 }}
>                                             />
> 
>                                         )
>                                     }
> ```

Can someone help out with full example as its not clear to me

**Comment by yashaswinibprasad87** [comment]
> Overriding row component I was able to give drag support. Please check may be helping you as well
> 
> ```
>  components={{
>                                         Row: props => (
>                                             <MTableBodyRow {...props}
>                                                 draggable="true"
>                                                 onDragStart={(e) => {
>                                                     console.log('onDragStart');
>                                                     DrageState.row = props.data.tableData.id
> 
>                                                 }}
> 
>                                                 onDragEnter={e => {
>                                                     e.preventDefault();
>                                                     if( props.data.tableData.id != DrageState.row){
>                                                         DrageState.dropIndex = props.data.tableData.id ;
> 
>                                                     }                                                  
>                                                 }}
> 
>                                                 onDragEnd={(e) => {
>                                                     console.log(`onDragEnd`);
>                                                     if(DrageState.dropIndex != -1){
>                                                         reodering({index: DrageState.row, dropIndex: DrageState.dropIndex})
>                                                     }
>                                                     DrageState.row = -1;
>                                                     DrageState.dropIndex = -1;
> 
>                                                 }}
>                                             />
> 
>                                         )
>                                     }
> ```

Please help out with full example , am not able to achieve it

**Comment by yashaswinibprasad87** [comment]
> Overriding row component I was able to give drag support. Please check may be helping you as well
> 
> ```
>  components={{
>                                         Row: props => (
>                                             <MTableBodyRow {...props}
>                                                 draggable="true"
>                                                 onDragStart={(e) => {
>                                                     console.log('onDragStart');
>                                                     DrageState.row = props.data.tableData.id
> 
>                                                 }}
> 
>                                                 onDragEnter={e => {
>                                                     e.preventDefault();
>                                                     if( props.data.tableData.id != DrageState.row){
>                                                         DrageState.dropIndex = props.data.tableData.id ;
> 
>                                                     }                                                  
>                                                 }}
> 
>                                                 onDragEnd={(e) => {
>                                                     console.log(`onDragEnd`);
>                                                     if(DrageState.dropIndex != -1){
>                                                         reodering({index: DrageState.row, dropIndex: DrageState.dropIndex})
>                                                     }
>                                                     DrageState.row = -1;
>                                                     DrageState.dropIndex = -1;
> 
>                                                 }}
>                                             />
> 
>                                         )
>                                     }
> ```

Please provide with a full example as not able to achieve it

**Comment by yashaswinibprasad87** [comment]
@rucsacman  can u please provide full example as am not able to achieve it


> Overriding row component I was able to give drag support. Please check may be helping you as well
> 
> ```
>  components={{
>                                         Row: props => (
>                                             <MTableBodyRow {...props}
>                                                 draggable="true"
>                                                 onDragStart={(e) => {
>                                                     console.log('onDragStart');
>                                                     DrageState.row = props.data.tableData.id
> 
>                                                 }}
> 
>                                                 onDragEnter={e => {
>                                                     e.preventDefault();
>                                                     if( props.data.tableData.id != DrageState.row){
>                                                         DrageState.dropIndex = props.data.tableData.id ;
> 
>                                                     }                                                  
>                                                 }}
> 
>                                                 onDragEnd={(e) => {
>                                                     console.log(`onDragEnd`);
>                                                     if(DrageState.dropIndex != -1){
>                                                         reodering({index: DrageState.row, dropIndex: DrageState.dropIndex})
>                                                     }
>                                                     DrageState.row = -1;
>                                                     DrageState.dropIndex = -1;
> 
>                                                 }}
>                                             />
> 
>                                         )
>                                     }
> ```

**Comment by rucsacman** [comment]
> @rucsacman can u please provide full example as am not able to achieve it
> 
> > Overriding row component I was able to give drag support. Please check may be helping you as well
> > ```
> >  components={{
> >                                         Row: props => (
> >                                             <MTableBodyRow {...props}
> >                                                 draggable="true"
> >                                                 onDragStart={(e) => {
> >                                                     console.log('onDragStart');
> >                                                     DrageState.row = props.data.tableData.id
> > 
> >                                                 }}
> > 
> >                                                 onDragEnter={e => {
> >                                                     e.preventDefault();
> >                                                     if( props.data.tableData.id != DrageState.row){
> >                                                         DrageState.dropIndex = props.data.tableData.id ;
> > 
> >                                                     }                                                  
> >                                                 }}
> > 
> >                                                 onDragEnd={(e) => {
> >                                                     console.log(`onDragEnd`);
> >                                                     if(DrageState.dropIndex != -1){
> >                                                         reodering({index: DrageState.row, dropIndex: DrageState.dropIndex})
> >                                                     }
> >                                                     DrageState.row = -1;
> >                                                     DrageState.dropIndex = -1;
> > 
> >                                                 }}
> >                                             />
> > 
> >                                         )
> >                                     }
> > ```

```
const DrageState = {
    row: -1,
    dropIndex: -1 // drag target
};

```

```
<MaterialTable
            components={{
                Row: props => (
                    <MTableBodyRow {...props}
                        draggable="true"
                        onDragStart={(e) => {
                            console.log('onDragStart');
                            DrageState.row = props.data.tableData.id
                        }}
                        onDragEnter={e => {
                            e.preventDefault();
                            if( props.data.tableData.id !== DrageState.row){
                                DrageState.dropIndex = props.data.tableData.id ;
                            }                                                  
                        }}
                        onDragEnd={(e) => {
                            console.log(`onDragEnd`);
                            if(DrageState.dropIndex !== -1){
                                reOrderRow(DrageState.row, DrageState.dropIndex)
                            }
                            DrageState.row = -1;
                            DrageState.dropIndex = -1;
                        }}
                    />
                )
            }} // components
        />

```
```
//Reorder the table row
const offsetIndex = (from, to, arr = []) => {
    if (from < to) {
      let start = arr.slice(0, from),
        between = arr.slice(from + 1, to + 1),
        end = arr.slice(to + 1);
      return [...start, ...between, arr[from], ...end];
    }
    if (from > to) {
      let start = arr.slice(0, to),
        between = arr.slice(to, from),
        end = arr.slice(from + 1);
      return [...start, arr[from], ...between, ...end];
    }
    return arr;
  }
const reOrderRow = (from, to) =>{
	let newtableData = offsetIndex(from, to, tableData);
	//Update react state
	setTableData(newtableData);
}
   
```

**Comment by orhanhub** [comment]
Rucsacman unfortunately I could not get it done by the way you suggested, I think MTableBodyRow does not have onDragStart/onDragEnter/onDragEnd properties, so it did not work for me.

Nevertheless, using react-beautiful-dnd library and watching the demo here: 
https://egghead.io/lessons/react-persist-list-reordering-with-react-beautiful-dnd-using-the-ondragend-callback

I was able to combine material-table with react-beatiful-dnd as such:

```

import React from "react";
import ReactDOM from "react-dom";
import { DragDropContext, Droppable, Draggable } from "react-beautiful-dnd";
import MaterialTable, { MTableBody, MTableBodyRow } from "material-table";

export default function App() {
  const values = [
    { name: "one" },
    { name: "two" },
    { name: "three" },
    { name: "four" },
  ];

  const [myState, setMyState] = React.useState(values);

  const onDragEnd = (result) => {
    const { destination, source } = result;
    if (!destination) return;
    if (source.index !== destination.index) {
      let copyArray = [...myState];
      let temp = myState[source.index];
      copyArray.splice(source.index, 1);
      copyArray.splice(destination.index, 0, temp);
      setMyState(copyArray);
    }
  };

  return (
    <div style={{ maxWidth: "100%" }}>
      <MaterialTable
        columns={[{ title: "Numbers", field: "name" }]}
        data={myState}
        title=""
        components={{
          Body: (props) => (
            <div>
              <DragDropContext onDragEnd={onDragEnd}>
                <Droppable droppableId={"singleColumnDroppableAreaThusStaticInput"}>
                  {(provided) => (
                    <div ref={provided.innerRef}>
                      <MTableBody {...props} />
                      {provided.placeholder}
                    </div>
                  )}
                </Droppable>
              </DragDropContext>
            </div>
          ),
          Row: (props) => (
            <Draggable
              draggableId={props.data.tableData.id.toString()}
              index={props.data.tableData.id}
            >
              {(provided) => (
                <div
                  {...provided.draggableProps}
                  {...provided.dragHandleProps}
                  ref={provided.innerRef}
                >
                  <MTableBodyRow {...props} />
                </div>
              )}
            </Draggable>
          ),
        }}
      />
    </div>
  );
}

ReactDOM.render(<App />, document.getElementById("root"));
```

this works but I am getting a few warnings on the console. When grouped, these are:
1. I am inserting div's into table/tbody/tr's thus getting validateDOMNesting warnings
2. MTable is adding overflow auto into a div above the MTableBody, and react beautiul dnd is annoyed that there's a nested scroll that it cannot control, I haven't looked more into it, but looks like with the help of this community, this structure can be improved.

Thanks y'all

**Comment by yashaswinibprasad87** [comment]
> > @rucsacman can u please provide full example as am not able to achieve it
> > > Overriding row component I was able to give drag support. Please check may be helping you as well
> > > ```
> > >  components={{
> > >                                         Row: props => (
> > >                                             <MTableBodyRow {...props}
> > >                                                 draggable="true"
> > >                                                 onDragStart={(e) => {
> > >                                                     console.log('onDragStart');
> > >                                                     DrageState.row = props.data.tableData.id
> > > 
> > >                                                 }}
> > > 
> > >                                                 onDragEnter={e => {
> > >                                                     e.preventDefault();
> > >                                                     if( props.data.tableData.id != DrageState.row){
> > >                                                         DrageState.dropIndex = props.data.tableData.id ;
> > > 
> > >                                                     }                                                  
> > >                                                 }}
> > > 
> > >                                                 onDragEnd={(e) => {
> > >                                                     console.log(`onDragEnd`);
> > >                                                     if(DrageState.dropIndex != -1){
> > >                                                         reodering({index: DrageState.row, dropIndex: DrageState.dropIndex})
> > >                                                     }
> > >                                                     DrageState.row = -1;
> > >                                                     DrageState.dropIndex = -1;
> > > 
> > >                                                 }}
> > >                                             />
> > > 
> > >                                         )
> > >                                     }
> > > ```
> 
> ```
> const DrageState = {
>     row: -1,
>     dropIndex: -1 // drag target
> };
> ```
> 
> ```
> <MaterialTable
>             components={{
>                 Row: props => (
>                     <MTableBodyRow {...props}
>                         draggable="true"
>                         onDragStart={(e) => {
>                             console.log('onDragStart');
>                             DrageState.row = props.data.tableData.id
>                         }}
>                         onDragEnter={e => {
>                             e.preventDefault();
>                             if( props.data.tableData.id !== DrageState.row){
>                                 DrageState.dropIndex = props.data.tableData.id ;
>                             }                                                  
>                         }}
>                         onDragEnd={(e) => {
>                             console.log(`onDragEnd`);
>                             if(DrageState.dropIndex !== -1){
>                                 reOrderRow(DrageState.row, DrageState.dropIndex)
>                             }
>                             DrageState.row = -1;
>                             DrageState.dropIndex = -1;
>                         }}
>                     />
>                 )
>             }} // components
>         />
> ```
> 
> ```
> //Reorder the table row
> const offsetIndex = (from, to, arr = []) => {
>     if (from < to) {
>       let start = arr.slice(0, from),
>         between = arr.slice(from + 1, to + 1),
>         end = arr.slice(to + 1);
>       return [...start, ...between, arr[from], ...end];
>     }
>     if (from > to) {
>       let start = arr.slice(0, to),
>         between = arr.slice(to, from),
>         end = arr.slice(from + 1);
>       return [...start, arr[from], ...between, ...end];
>     }
>     return arr;
>   }
> const reOrderRow = (from, to) =>{
> 	let newtableData = offsetIndex(from, to, tableData);
> 	//Update react state
> 	setTableData(newtableData);
> }
>    
> ```

Thank you it worked for me🙂
Can we include an icon to each row next to/ before checkbox to indicate  to drag, 
As it was failing to include

Kindly help with it

**Comment by yashaswinibprasad87** [comment]
> Rucsacman unfortunately I could not get it done by the way you suggested, I think MTableBodyRow does not have onDragStart/onDragEnter/onDragEnd properties, so it did not work for me.
> 
> Nevertheless, using react-beautiful-dnd library and watching the demo here:
> https://egghead.io/lessons/react-persist-list-reordering-with-react-beautiful-dnd-using-the-ondragend-callback
> 
> I was able to combine material-table with react-beatiful-dnd as such:
> 
> ```
> 
> import React from "react";
> import ReactDOM from "react-dom";
> import { DragDropContext, Droppable, Draggable } from "react-beautiful-dnd";
> import MaterialTable, { MTableBody, MTableBodyRow } from "material-table";
> 
> export default function App() {
>   const values = [
>     { name: "one" },
>     { name: "two" },
>     { name: "three" },
>     { name: "four" },
>   ];
> 
>   const [myState, setMyState] = React.useState(values);
> 
>   const onDragEnd = (result) => {
>     const { destination, source } = result;
>     if (!destination) return;
>     if (source.index !== destination.index) {
>       let copyArray = [...myState];
>       let temp = myState[source.index];
>       copyArray.splice(source.index, 1);
>       copyArray.splice(destination.index, 0, temp);
>       setMyState(copyArray);
>     }
>   };
> 
>   return (
>     <div style={{ maxWidth: "100%" }}>
>       <MaterialTable
>         columns={[{ title: "Numbers", field: "name" }]}
>         data={myState}
>         title=""
>         components={{
>           Body: (props) => (
>             <div>
>               <DragDropContext onDragEnd={onDragEnd}>
>                 <Droppable droppableId={"singleColumnDroppableAreaThusStaticInput"}>
>                   {(provided) => (
>                     <div ref={provided.innerRef}>
>                       <MTableBody {...props} />
>                       {provided.placeholder}
>                     </div>
>                   )}
>                 </Droppable>
>               </DragDropContext>
>             </div>
>           ),
>           Row: (props) => (
>             <Draggable
>               draggableId={props.data.tableData.id.toString()}
>               index={props.data.tableData.id}
>             >
>               {(provided) => (
>                 <div
>                   {...provided.draggableProps}
>                   {...provided.dragHandleProps}
>                   ref={provided.innerRef}
>                 >
>                   <MTableBodyRow {...props} />
>                 </div>
>               )}
>             </Draggable>
>           ),
>         }}
>       />
>     </div>
>   );
> }
> 
> ReactDOM.render(<App />, document.getElementById("root"));
> ```
> 
> this works but I am getting a few warnings on the console. When grouped, these are:
> 
> 1. I am inserting div's into table/tbody/tr's thus getting validateDOMNesting warnings
> 2. MTable is adding overflow auto into a div above the MTableBody, and react beautiul dnd is annoyed that there's a nested scroll that it cannot control, I haven't looked more into it, but looks like with the help of this community, this structure can be improved.
> 
> Thanks y'all

Hope material-table internally react dnd, we need to explicitly import again
Which version of mat table you are using?
Try to re-implement with his solution

**Comment by orhanhub** [comment]
material-table internally imports react-dnd, it is one of its dependencies, and I am using the latest version of material-table, but somehow rucsacman's solution did not work for me. Can you post yours on github or somewhere, so I can look?
> Hope material-table internally react dnd, we need to explicitly import again
> Which version of mat table you are using?
> Try to re-implement with his solution

**Comment by Tate-Young** [comment]
暂时通过你这个方法完成了，不过说实话，交互方式有点丑哈哈。总之谢谢啦

**Comment by Tate-Young** [comment]
@rucsacman 

暂时通过你这个方法完成了，不过说实话，交互方式有点丑哈哈，不知道是不是我接入方式不对 😊。总之谢谢啦

**Comment by siddiq-rehman** [comment]
Could be helpful If there is a proper working code with the table and the react-beautiful-library.?

**Comment by rashmipyrumas** [comment]
Is it possible to pass 'ref' to <MTableBody/> instead of 'div' ?
It would be helpful if there is a proper working code with  material-table with react-beatiful-dnd.

**Comment by orhanhub** [comment]
Still cannot get it working with react beautiful and but here is the working solution based on @rucsacman's code above:

```

import React from "react";
import MaterialTable, { MTableBodyRow } from "material-table";

export default function Beautiful() {
  const values = [
    { name: "one" },
    { name: "two" },
    { name: "three" },
    { name: "four" },
  ];

  const [tableData, setTableData] = React.useState(values);

  const DrageState = {
    row: -1,
    dropIndex: -1, // drag target
  };

  const offsetIndex = (from, to, arr = []) => {
    if (from < to) {
      let start = arr.slice(0, from),
        between = arr.slice(from + 1, to + 1),
        end = arr.slice(to + 1);
      return [...start, ...between, arr[from], ...end];
    }
    if (from > to) {
      let start = arr.slice(0, to),
        between = arr.slice(to, from),
        end = arr.slice(from + 1);
      return [...start, arr[from], ...between, ...end];
    }
    return arr;
  };
  const reOrderRow = (from, to) => {
    let newtableData = offsetIndex(from, to, tableData);
    //Update react state
    setTableData(newtableData);
  };

  return (
    <MaterialTable
      columns={[{ title: "Numbers", field: "name" }]}
      data={tableData}
      title=""
      components={{
        Row: (props) => (
          <MTableBodyRow
            {...props}
            draggable="true"
            onDragStart={(e) => {
              console.log("onDragStart");
              DrageState.row = props.data.tableData.id;
            }}
            onDragEnter={(e) => {
              e.preventDefault();
              if (props.data.tableData.id !== DrageState.row) {
                DrageState.dropIndex = props.data.tableData.id;
              }
            }}
            onDragEnd={(e) => {
              console.log(`onDragEnd`);
              if (DrageState.dropIndex !== -1) {
                reOrderRow(DrageState.row, DrageState.dropIndex);
              }
              DrageState.row = -1;
              DrageState.dropIndex = -1;
            }}
          />
        ),
      }} // components
    />
  );
}

```

**Comment by shivarad** [comment]
is there a way to add a button to toolbar on dragging start?

**Comment by SrinivasSwaroop-Dev** [comment]
@rucsacman , I've tried the approach that's been suggested by you, it just works fine in read only rows scenario. However, when editable columns were introduced text field for example render unresponsive and are not editable at all. 
Please refer to the code sandbox below, the drag drop works fine but text fields are not editable.

[sandBox](https://codesandbox.io/s/great-feistel-r4pt0)

-TIA

**Comment by sachin-agarwal-by** [comment]
> @rucsacman , I've tried the approach that's been suggested by you, it just works fine in read only rows scenario. However, when editable columns were introduced text field for example render unresponsive and are not editable at all.
> Please refer to the code sandbox below, the drag drop works fine but text fields are not editable.
> 
> [sandBox](https://codesandbox.io/s/great-feistel-r4pt0)
> 
> -TIA

I am also facing same Issue.

**Comment by shivarad** [comment]
@rucsacman it works for me but unfortunately it doesnt work on touch devices! any update for working with touch device?

**Comment by omkarjadhav24** [comment]
I am using drag and drop solution which is refer from here ,  on drag row becoming transparent how 
to prevent this any idea

**Comment by pprathameshmore** [comment]
> @rucsacman , I've tried the approach that's been suggested by you, it just works fine in read only rows scenario. However, when editable columns were introduced text field for example render unresponsive and are not editable at all. Please refer to the code sandbox below, the drag drop works fine but text fields are not editable.
> 
> [sandBox](https://codesandbox.io/s/great-feistel-r4pt0)
> 
> -TIA

Yeah, I had the same issue. You can add drag and drop support to actions or any other read-only column.


```javascript

components={{
        Row: (props) => (
          <MTableBodyRow
            {...props}
            draggable="true"
            onDragStart={(e) => {
              console.log("onDragStart");
              DrageState.row = props.data.tableData.id;
            }}
            onDragEnter={(e) => {
              e.preventDefault();
              if (props.data.tableData.id !== DrageState.row) {
                DrageState.dropIndex = props.data.tableData.id;
              }
            }}
            onDragEnd={(e) => {
              console.log(`onDragEnd`);
              if (DrageState.dropIndex !== -1) {
                reOrderRow(DrageState.row, DrageState.dropIndex);
              }
              DrageState.row = -1;
              DrageState.dropIndex = -1;
            }}
          />
        ),
      }}
```
Component overriding causing issue.
