### ISSUE TITLE
Styling on material table

### ISSUE THREAD

**Issue by schatterjee-erwin** [mbrn/material-table#122]
Is there a way to remove the box shadow at the bottom of the table?

<img width="372" alt="page shadow" src="https://user-images.githubusercontent.com/27771746/50168443-719f9580-02b9-11e9-909b-5494aded06b2.PNG">

**Comment by mbrn** [comment]
I will add an option to remove paper component. So you can do this. I hope in this week it will be in new release. 

This is duplicate issue of #119 . So i am closing this.
