### ISSUE TITLE
Filter data in table on press enter

### ISSUE THREAD

**Issue by kwasik-com** [mbrn/material-table#1221]
I don't want to Override every Filter or create a new separate Filter!

**Comment by Totalbug92** [comment]
Not sure I completely understood your problem.
But If you want to enable the filtering row when you click Enter you could make the condition a variable and change it in an eventListener somewhere else?

```
<MaterialTable
...
options={{
   filtering: enableFilteringVariable // Default false
}}
/>

window.addEventListener('keypress', function (e) {
    if (e.keyCode !== 13) {
        enableFilteringVariable = !enableFilteringVariable ;
    }
}, false);
```

**Comment by kwasik-com** [comment]
No, the problem is that when i use remote data the filter uses a debounce interval & i don't want that, i want to filter data on enter not by itself...

**Comment by Qaimali** [comment]
> No, the problem is that when i use remote data the filter uses a debounce interval & i don't want that, i want to filter data on enter not by itself...

Kwasik-com you got the solution for searching on press enter

**Comment by zoran123456** [comment]
I also need this feature badly for server loaded data! I tried setting debounceInterval to 9999999 by default, and then setting it to 1 on ENTER pressed, however that does not work. Even manually triggering "materialtableRef.current.onQueryChange();" does not work.

Please help!!

**Comment by NikSkor** [comment]
In new versions, is it possible to start filtering only after typing text and pressing the Enter button?
