### ISSUE TITLE
showFirstLastPageButtons doesn't work for Stepped Pagination ??

### ISSUE THREAD

**Issue by kwasik-com** [mbrn/material-table#1222]

**Comment by jayarjo** [comment]
Hm... doesn't it, have an example?

**Comment by kwasik-com** [comment]
`class Test extends React.Component {
  render() {
    return (
      <MaterialTable
        title="Test"
        columns={[
          { title: 'Name', field: 'name' },
          { title: 'Surname', field: 'surname' },
          { title: 'Birth Year', field: 'birthYear', type: 'numeric' },
          {
            title: 'Birth Place',
            field: 'birthCity',
            lookup: { 34: 'İstanbul', 63: 'Şanlıurfa' },
          },
        ]}
        data={[
          { name: 'Mehmet', surname: 'Baran', birthYear: 1987, birthCity: 63 },
          { name: 'Zerya Betül', surname: 'Baran', birthYear: 2017, birthCity: 34 },
          { name: 'Zerya Betül', surname: 'Baran', birthYear: 2017, birthCity: 34 },
          { name: 'Zerya Betül', surname: 'Baran', birthYear: 2017, birthCity: 34 },
          { name: 'Zerya Betül', surname: 'Baran', birthYear: 2017, birthCity: 34 },
          { name: 'Zerya Betül', surname: 'Baran', birthYear: 2017, birthCity: 34 },
          { name: 'Zerya Betül', surname: 'Baran', birthYear: 2017, birthCity: 34 },
          { name: 'Zerya Betül', surname: 'Baran', birthYear: 2017, birthCity: 34 },
          { name: 'Zerya Betül', surname: 'Baran', birthYear: 2017, birthCity: 34 },
          { name: 'Zerya Betül', surname: 'Baran', birthYear: 2017, birthCity: 34 },
          { name: 'Zerya Betül', surname: 'Baran', birthYear: 2017, birthCity: 34 },
          { name: 'Zerya Betül', surname: 'Baran', birthYear: 2017, birthCity: 34 },
          { name: 'Zerya Betül', surname: 'Baran', birthYear: 2017, birthCity: 34 },
          { name: 'Zerya Betül', surname: 'Baran', birthYear: 2017, birthCity: 34 },
        ]}        
        options={{
          search: false,
          paginationType: "stepped",
          showFirstLastPage: true
        }}
      />
    )
  }
}`

![2](https://user-images.githubusercontent.com/56349436/67246052-b78b3400-f45d-11e9-9c21-08276ff3b969.png)

**Comment by jayarjo** [comment]
Screenshots are not helpful. Just saying. You should consider posting a [codesanbox](https://codesandbox.io/) instead in such cases.

**Comment by kwasik-com** [comment]
App: https://sh9uk.csb.app/
Code: https://codesandbox.io/s/wizardly-euler-sh9uk

**Comment by sshanzel** [comment]
I'll make the PR later, have finished the dev.
