### ISSUE TITLE
defaultSorting on column still active when sorting = false

### ISSUE THREAD

**Issue by frankforpresident** [mbrn/material-table#1223]
**Describe the bug**
When you provide sorting: false to options, defaultSort: 'desc' from a column is still applied. When reading the documentation this should not be the case.

"To make sorting available you must open sorting in options." and "sorting | boolean | true | Flag to activate or disable sorting feature of table"

**To Reproduce**
Install 1.52.0
render a default table with options={{ sorting: false }}
provide a column with defaultSort

**Expected behavior**
defaultSort is not applied on the data

**Actual behavior**
defaultSort is sorting the data.

**Comment by sshanzel** [comment]
When you apply `sorting: false` also on `column` props with `defaultSort`, it happens. Though this is fixed on the referenced PR

**Comment by sshanzel** [comment]
This has been fixed with the merging of referenced PR. Kindly close the issue if you are now satisfied with the fix. Thanks a lot for the report!

**Comment by mbrn** [comment]
> This has been fixed with the merging of referenced PR. Kindly close the issue if you are now satisfied with the fix. Thanks a lot for the report!

We can close the issue
