### ISSUE TITLE
Add an option to conditionally render a different value if data is undefined

### ISSUE THREAD

**Issue by jakeleventhal** [mbrn/material-table#123]
**Is your feature request related to a problem? Please describe.**
For the currency type, if the value is null or undefined, it makes sense in most scenarios that I can think of to display something like 'N/A' or nothing at all (preferably 'N/A') instead of $0.00. This could probably apply to most other types as well that have a default value in the case of null or undefined.
For example, if one column is 'Cost', it doesn't make sense to show that the cost is $0.00 if there is no data.

**Describe the solution you'd like**
Add an option to have a fallback cell render.

**Comment by mbrn** [comment]
Another good feature request @jakeleventhal :) Thanks

**Comment by yildirims** [comment]
Hi, I will work on this issue
