### ISSUE TITLE
How can I change styling of the Add new row tooltip ?

### ISSUE THREAD

**Issue by hungbang** [mbrn/material-table#1231]
As the question, I want to change styling of the Add new Row tooltip, specifically I want to set the tooltip fontSize a bit bigger. 

![image](https://user-images.githubusercontent.com/10163092/67144055-9af3ce00-f29c-11e9-8ca5-0979240c33c9.png)

Thank you in advance!

**Comment by jayarjo** [comment]
@hungbang I encourage you to ask material-table related questions on StackOverflow, so that others could benefit from them as well.
