### ISSUE TITLE
When using function for Action, re-renders fully add/remove custom component

### ISSUE THREAD

**Issue by rylandg** [mbrn/material-table#1235]
**Describe the bug**

When adding an action implemented with a function (as opposed to an icon), the DOM seemingly fully removes and re-inserts the action element for each re-render. This obviously effects performance in an unacceptable way, causing all rows to briefly flash on any search or just plain loading. 

**To Reproduce**

1. Create a table with actions
2. Add action that uses a custom component

```jsx
          (rowData: any): any => ({
            icon: () => <a href='google.com'><img src={img} /> </a>
            tooltip: 'Google link',
            onClick: (event: any, rowData: any) => {}
          }),
```

3. Search in Material table
4. See flickering of the image as it's continuously removed from the DOM

**Expected behavior**

The action only should re-render if the component changes. If you provide a function that returns an icon string (not a custom component), things behave correctly:

```jsx
          (rowData: any): any => {
              icon: 'fiber_new',
              tooltip: 'New updates!',
              iconProps: { color: 'secondary' },
              onClick: (event: any, rowData: any) => {},
            }
```

If I had to guess, it's something about this conditional in `m-table-action.js`

```jsx
          {typeof action.icon === "string" ? (
            <Icon {...action.iconProps}>{action.icon}</Icon>
          ) : (
              <action.icon
                {...action.iconProps}
                disabled={action.disabled}
              />
            )
          }
```

**Comment by kwiatkk1** [comment]
I've managed to reproduce and fix this. Looks like calling render prop directly as opposed to via jsx wrapper, causes no re-render.

**Comment by rylandg** [comment]
@kwiatkk1 awesome work. Thanks for figuring  this out, already implemented your fix in my fork!
