### ISSUE TITLE
How to change MuiTableCell padding ?

### ISSUE THREAD

**Issue by hungbang** [mbrn/material-table#1236]
![image](https://user-images.githubusercontent.com/10163092/67180506-0b692f00-f404-11e9-9155-cf9707d0c1a8.png)
I want to change MuiTableCell root padding as the image above

**Comment by Domino987** [comment]
You can override it using the style prop as mentioned in the [docs](https://material-table.com/#/docs/features/styling)

**Comment by jayarjo** [comment]
@hungbang I encourage you to ask material-table related questions on StackOverflow, so that others could benefit from them as well. I will respond on StackOverflow,
