### ISSUE TITLE
Warning: Failed prop type: "numeric" is deprecated for TableCell

### ISSUE THREAD

**Issue by rfrerebe** [mbrn/material-table#124]
**Describe the bug**
React warning about "numeric" being deprecated for TableCell
See : https://material-ui.com/api/table-cell/

**To Reproduce**
Open a Material-Table with React 16.6.0
Look at console

**Expected behavior**
No warning

**Additional context**
React 16.6.0

**Comment by mbrn** [comment]
This closed with #125
