### ISSUE TITLE
free action example from website docs does not display plus icon for new row

### ISSUE THREAD

**Issue by jdmairs** [mbrn/material-table#1245]
**Describe the bug**
The add or addbox icon does not display.

**To Reproduce**
Reference https://github.com/mbrn/material-table/issues/838#issue-469014346
for a link to a codepen example that is similar.

**Expected behavior**
See the Free Action example
https://material-table.com/#/docs/features/actions
![image](https://user-images.githubusercontent.com/5624808/67333231-36c84880-f4ee-11e9-9d84-d80daf917711.png)

**Screenshots**
<img width="346" alt="image" src="https://user-images.githubusercontent.com/5624808/67333090-fb2d7e80-f4ed-11e9-9969-b8c3628c782c.png">

**Comment by ChrisJVoss** [comment]
I had the same issue and ended up circumventing it by simply using the stylesheet

<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

I'd love to know how to do it with imported icons though.

**Comment by jdmairs** [comment]
Since it was only the Add and Delete icons that were missing wy work around was this:

import { Delete, Add } from '@material-ui/icons';
icon: () => (<Add />),

**Comment by jayarjo** [comment]
@jdmairs @ChrisJVoss doesn't a solution over here solve it for you: https://github.com/mbrn/material-table/issues/838?

**Comment by jdmairs** [comment]
that's the same solution I figured out and posted above
