### ISSUE TITLE
Localization property missing for placeholder for filters

### ISSUE THREAD

**Issue by mehradrishty** [mbrn/material-table#1246]
We can set the placeholder for filters using the property : filterPlaceholder. But the localization property for the same setting is missing. Can you please provide the localization ability for this placeholder as well. 

Thanks

**Comment by jayarjo** [comment]
PRs are welcome. Don't lose your chance to become contributor. No enhancement or bugfix is too small.

**Comment by sshanzel** [comment]
Does this mean all the filter boxes will have the same placeholder content if declared in `localization`? Pardon if i'm quite slow perceiving your issue. Thanks a lot!

If yes, i'll make the PR later. Thanks!
