### ISSUE TITLE
How to add a function call when the row is entering editing status. (question)

### ISSUE THREAD

**Issue by yinlitao** [mbrn/material-table#1248]
I like to do some changes on the row when the row is entering editing mode. Seems I couldn't find a easy way. The onRowUpdate is triggered when user clicking the save button. any suggestions?

**Comment by Joycewu31400** [comment]
> I like to do some changes on the row when the row is entering editing mode. Seems I couldn't find a easy way. The onRowUpdate is triggered when user clicking the save button. any suggestions?

Do you find  a way to solve the problem?

**Comment by triusis92** [comment]
Hi,

Ran into same issue except for onRowAdd. Does anyone have a solution for this ?

**Comment by thelazydogsback** [comment]
Yes, we need onBeforeAdd/Update/Delete() as well as onValidateAdd/Update()
