### ISSUE TITLE
Alphanumeric sort not working  

### ISSUE THREAD

**Issue by mohendren** [mbrn/material-table#1249]
Issue:

  Alphanumeric sort is not working properly. I had applied custom sort for this. though it is not consistent. After double click on the sort arrow, it is changing the records to descending order from ascending. 

data is in below format:

data = [
  { string_id: "D1" },
  { string_id: "D2" },
  { string_id: "D3" },
  { string_id: "D4" },
  { string_id: "D5" },
  { string_id: "D6" },
  { string_id: "D7" },
  { string_id: "D8" },
  { string_id: "D9" },
  { string_id: "D10" },
  { string_id: "D11" },
  { string_id: "D100" }
];

code sandbox link:- https://codesandbox.io/s/ecstatic-neumann-ut2ti

Thanks in advance

**Comment by mohendren** [comment]
Hi, 

I do not see any issue when the same code is implemented in browser console. But why does the  lag comes in picture with this . why it is not working in first click on the arrow.

**Comment by mbrn** [comment]
Please check again: 

![image](https://user-images.githubusercontent.com/7895451/67477294-76b03c80-f662-11e9-80dd-917905029ab2.png)

**Comment by mohendren** [comment]
Thanks for the explanation. But if the data is in  

data = [
{ string_id: "D1" },
{ string_id: "D2" },
{ string_id: "D3" },
{ string_id: "D10" },
{ string_id: "D5" },
{ string_id: "D6" },
{ string_id: "D7" },
{ string_id: "D8" },
{ string_id: "D9" },
{ string_id: "D11" },
{ string_id: "D100" }
];

this format, ascending order  is taking two steps, but descending order is working in first step itself. can you please check the sandbox link

Sorry I may be disturbing you
