### ISSUE TITLE
How to override on select all action?

### ISSUE THREAD

**Issue by friscote** [mbrn/material-table#1251]
Hi, I have some checkboxes in my material-table that are indeterminate and disabled. The functionality works well until I click on `Select All` checkbox. It selects records with indeterminate and disabled checkboxes too. I want to avoid that. I tried to use onSelectionChange trigger but this trigger doesn't overwrite the existing behaviour as records get selected/unselected independently of onSelectionChange functionality (I can console.log what records got selected, but state of the table changes somewhere else - don't know where). Not sure whether selecting records with disabled checkboxes is a bug, so writing a Help issue. Not sure also where I can find all possible attributes of selectionProps if I am missing any. I am using the latest material-table package and react.

**Comment by jayarjo** [comment]
I encourage you to ask material-table related questions on StackOverflow, so that others could benefit from them as well. I will respond on StackOverflow, if you create a question and link it here.
