### ISSUE TITLE
How can I notify the table of external row data change?

### ISSUE THREAD

**Issue by bennidi** [mbrn/material-table#1256]
I would like to use the data table to implement a master-detail view with a complex editor in the details panel.
I was hoping to find a callback that I can pass to the table to notify about specific row changes (for fast rerender). I can not use the `editable` prop because the inline-editing is not what I am looking for.
Is there any way to notify the table about a change in data without triggering a full redraw?

**Comment by sshanzel** [comment]
you are missing the point of React. It won't full redraw in the actual DOM, transaction time will only be based on how fast it processes the data, but it won't actually re-render every element in your DOM. You won't be able to update the table info without React to actually re-render it but only in Virtual DOM.

**Comment by sshanzel** [comment]
And React doesn't have a 2-way binding.

**Comment by bennidi** [comment]
I am aware of the concept of Virtual DOM. Just that the Virtual DOM can become quite big and computing the new Virtual DOM and diffing it against the old and patching the browser DOM can become time consuming.

It's the reason to exist for things like PureRenderMixin and libraries like Mobx or other state management libs. It is possible to optimize Virtual DOM generation by tracking the actual data changes on only re-rendering this very part of the Virtual DOM.

And this is what my question is about. Thanks for helping me point that out more clearly.

And this is what my question is about.

**Comment by sshanzel** [comment]
Hmmm. Since you mentioned it. Have you tried passing an observed object for your table data? This is cool, i was thinking pure React. Please let me know if you'll ever have anything about this, I became curious about it now. Lol.

**Comment by bennidi** [comment]
Passing an observed object will not help since the observer needs to be the
rendering component. This is why the state management libs provide HOCs or
other type of Function/Class decorators to leverage React.Component to be
aware of their observables.

Am So., 3. Nov. 2019 um 14:11 Uhr schrieb Hansel Solevilla <
notifications@github.com>:

**Comment by sshanzel** [comment]
Yeahh i figured it will rerender again so i had to remove what i said, it really has to come from the inside

**Comment by bennidi** [comment]
Good. So now we are all on the same page :-P

Am So., 3. Nov. 2019 um 17:01 Uhr schrieb Hansel Solevilla <
notifications@github.com>:

**Comment by sshanzel** [comment]
Hell yeah, lol. My mind is buzzed right now because of it :-D Please let us know if you have thought of something or anything :-P

**Comment by bennidi** [comment]
@mbrn What does the library author have to say to this?

**Comment by mbrn** [comment]
Hi @bennidi,

 I almost completed waiting PR's. Now i can work on issues. I will look at this case asap.

**Comment by bennidi** [comment]
Nice. I expect to become an enthusiastic user of this component. So you might as well try and include me in the process so I might be able to submit a PR.

**Comment by mbrn** [comment]
> Nice. I expect to become an enthusiastic user of this component. So you might as well try and include me in the process so I might be able to submit a PR.

Thanks @bennidi 

You can find a issue and then create a PR for it. It will be appreciated :)

**Comment by bennidi** [comment]
@mbrn I meant to submit a PR on this issue. If you could point me around the codebase and maybe suggest a way to implement the feature.

**Comment by mbrn** [comment]
Actually i don't have any offer about this problem. You may override Row component (see overriding components section on docs.)

**Comment by bennidi** [comment]
Aha. Yeah, that could work. Using an observable array and overwrite the row rendering with a observer. I will close this issue now and see what comes out of this idea. Maybe I can publish a gist of a mobx aware row-renderer. Thanks.

**Comment by cworf** [comment]
Id like to re-open this because I cant seem to get the table to show new updates on a mobx observable, my attempted solution before coming here was the same as @mbrn 's, to override the component with an observer, I have tried the following: 
```JSX
<MaterialTable
  columns={[
    { title: 'Product', field: 'item_number' },
    { title: 'Item Price', field: 'price', type: 'numeric' },
  ]}
  data={newOrderCart}
  title="Order Details"
  components={{
    Row: props => observer(<MTableRow {...props} />)
  }}
/>


```

**Comment by sshanzel** [comment]
Maybe you can provide a sandbox or something to enable people to help you out?

**Comment by cworf** [comment]
my pleasure, I have done up a simple todo app that illustrates what I have tried. expected functionality would be that every time a new todo is added, it gets added to the form, and as you can see, the ordered list updates however the table component does not,

My comment above was definitely the wrong way to use the observer HOC, after reading a bit more on mobx's github I was able to discover they included an actual `<Observer></Observer>` component that expects a child function that returns a component so 
`Cell: props => <Observer>() => <MTableCell {...props} /></Observer>` 
would be the correct way to wrap the rendered component

Sadly, this does not work still. my assumption is that there is yet another child component inside of `MTableCell` which renders the final observable data. and so here I am stuck

Im gonna go try one more thing before bed which is to render the cell with the actual table cell component from material-ui. if that works, ill let you know.

**Comment by sshanzel** [comment]
I don't think this would be possible from the outside. Since `material-table` has its data manager that processes the in which a new object reference will be created that will be in place of each cells, hence we will lose the reference to the observable.

**Comment by cworf** [comment]
Judging by the silence I'm guessing I've reached a dead end. Sadly I'll have to switch to react-table for this functionality. Bummer because I REALLY like this one. Can't win em all!

**Comment by lukeggchapman** [comment]
I think your problem is that the data you pass in mapped to a new array, which would change it from an observable to a plain array. There is a push to separate table data from passed in data which would also solve this issue.
#1371
