### ISSUE TITLE
When using a React.Element as title for columns, The editable placeholder renders as "Object"

### ISSUE THREAD

**Issue by masbaehr** [mbrn/material-table#1260]
When using a complex title instead of a simple string this happens:

Title is defined as:
title?: string | React.ReactElement<any>;

Exemplary code
```javascript
  columns={[
                
                { title: <div>Italiano (chiave)<img style={flagstyle} src='whatever.png'></img></div>, field: 'it' }
```

![image](https://user-images.githubusercontent.com/38694044/67631339-1a812e80-f895-11e9-9c76-2752c6a93605.png)
 
Warning: Failed prop type: Invalid prop `placeholder` of type `object` supplied to `ForwardRef(InputBase)`, expected `string`.
    in ForwardRef(InputBase) (created by WithStyles(ForwardRef(InputBase)))
    in WithStyles(ForwardRef(InputBase)) (created by ForwardRef(Input))
    in ForwardRef(Input) (created by WithStyles(ForwardRef(Input)))

**Comment by jonasanx** [comment]
I don't think the issue is on the title, I think it has to do with the data. My guess is that maybe instead of passing a string value, you're passing an object. What do you have on `columns`?

**Comment by masbaehr** [comment]
The issue is on the title, as i have tested to just type "whatever" then it renders correctly. Basically the title is used as a placeholder internally causing the error. However a ReactElement is allowed to be used as a title e.g. if you want to render something else other than a plain string. 
Maybe something called "editPlaceholder" would be a nicer way to solve the problem. Then you can specify something like "Type new value..."

**Comment by WinZip17** [comment]
This problem is not resolved? ReactElement in title is possible, but not in the crap placeholder. But for the placeholder, the value is taken from the title

**Comment by masbaehr** [comment]
Then the proper way to solve this would be to allow a ReactElement for _title_ and a String for "_titlePlaceholder_" ;)  The way it is now, is not correct and definitely buggy or at least error-prone

**Comment by masbaehr** [comment]
Suggestion for fixing this issue properly. I'm sorry for not providing a pull request but i don't have the proficiency to know if this is enough or not. But it should be a reasonable solution which should not break current implementation by providing additional functionality

In m-table-edit-field.js

Instead of :   
```javascript
 placeholder={this.props.columnDef.title} 
```

use:  
```javascript
 placeholder={(typeof this.props.columnDef.title !== 'string') ? this.props.columnDef.placeholder : this.props.columnDef.title}
```

And add a new "placeholder" property in columnDef which allows to set the placeholder in case when title is a complex ReactElement

Then in the column definition the following would be possible:

```javascript
    { title: <div>Key<MdiIcons.Key style={{marginLeft: 5, verticalAlign: "bottom", color: "gray"}}></MdiIcons.Key></div>, field: keyIso, placeholder: "Key" },
```
