### ISSUE TITLE
Disable automatically selecting children when parent is selected in tree

### ISSUE THREAD

**Issue by TheGoodSpinach** [mbrn/material-table#1269]
Currently, when working with tree data in a table, selecting a row will automatically select all children underneath it. 

Is it possible to disable this functionality, so selecting a row will not automatically select its children? And conversely, deselecting a row should not automatically deselect all it’s children.

**Comment by TheGoodSpinach** [comment]
Looks like this is solved by #1224

**Comment by Tobbe129** [comment]
Would really need this as well!
