### ISSUE TITLE
Wrong number of rows displayed when grouping is on with remote data

### ISSUE THREAD

**Issue by Clem-** [mbrn/material-table#1270]
**Describe the bug**
There is always additional empty rows displayed when grouping is on with remote data.
The row calculation for remote data table is based on number of fetched rows and not number of groups.

**To Reproduce**
[See CodeSandbox](https://codesandbox.io/embed/materialtable-grouping-rows-issue-zi1o0)

**Expected behavior**
As for local data table (see 2nd table of CodeSandbox), all 5 rows per page must be filled with grouped rows.

**Comment by Clem-** [comment]
In fact, this is more complicated than that because we downloaded just 5 data-rows, and would have to download more data-rows after they are grouped, in order to fill the empty table-rows.

**Comment by pixelass** [comment]
This is not related to grouping. If 5 rows are selected (in the rows-dropdown) it always renders 5 rows even if only 1 row is present.
