### ISSUE TITLE
Possibility to edit individual fields instead of the whole row

### ISSUE THREAD

**Issue by rootsher** [mbrn/material-table#1271]
I would like to edit single table cell instead click "edit action button" and edit whole row at the same time.

I propose to add an option that will allow you to click on the "edit" icon next to a given field - which will make the field editable.

**Comment by hrafaelveloso** [comment]
So instead of one clickable icon, you want X clickable icons? You can disable the fields that you dont want to be editable. I think that's not the best UI/UX...

**Comment by mosofsky** [comment]
I would also like to restrict editing to certain rows.  The UI/UX I can imagine is the field has a slightly different look so the user is enticed to mouse over it.  When the user mouses over the cell, controls for the cell appear, for instance an edit icon.
