### ISSUE TITLE
[Help wanted] onRowUpdate after update leaves row in editing state

### ISSUE THREAD

**Issue by mindaugasnakrosis** [mbrn/material-table#1273]
I update row with redux action, data updates but the row looks like it is still in `editable` state (icons `edit`, `delete` are still left).

Update function:

```
 onRowUpdate: updatedRow =>
     new Promise(resolve => {
           onRowUpdate(newData);
           resolve();
     });
```

`onRowUpdate` just updates the redux state that is being used in the table.

**Screenshot after updating a row:**
<img width="1010" alt="updated" src="https://user-images.githubusercontent.com/14983636/67962296-a1236c00-fc05-11e9-895c-854c4abef0f3.png">

Any ideas?

**Comment by Roseidon** [comment]
I encountered the same issue aswell (version 1.52.0).
Maybe we have the same problem?
Are you using class components or functional Components with hooks?

**Comment by Roseidon** [comment]
Is there some progress in this issue? This still occurs in version `1.54.1`

**Comment by Roseidon** [comment]
I solved the problem (accidentally ^^) by correcting my memoization in my component.

Do you use some sort of memoization? Maybe with `reselect` for Redux or a similar libary.
Maybe this is the source of your problem.

**Comment by ShaunLWM** [comment]
Having this problem as well. And not using any memoization :/
Data is updated, yet ```resolve()``` does nothing to the edited row.

**Comment by mindaugasnakrosis** [comment]
No memoization in my code.

**Comment by mindaugasnakrosis** [comment]
@ShaunLWM How did you fix it?
@Roseidon What memoization did you fix?

**Comment by ShaunLWM** [comment]
Nope. Didn't manage to fix it. It was working perfectly until I added some code and it stopped working.
Maybe you can switch to react-table or something. Sorry I can't be of help.

**Comment by Roseidon** [comment]
> @Roseidon What memoization did you fix?

As far as I remember, I memoized the wrong parameters, or had functions memoized and thus used a stale state. It was a while ago.
