### ISSUE TITLE
Demos are not working properly

### ISSUE THREAD

**Issue by TCM5** [mbrn/material-table#1275]
**Describe the bug**
All the demos present in this link [https://material-table.com/#/docs/features/editable](https://material-table.com/#/docs/features/editable) are not working on update action events.

**To Reproduce**
1. Go to [https://material-table.com/#/docs/features/editable](https://material-table.com/#/docs/features/editable)
2. Click on "edit action button"
3. Change the value to a new one and save
4. The updated table doesn't have the new value

**Expected behavior**
The new value should be visible after saving

**Desktop**
 - OS: Windows 10
 - Browser: firefox 
 - Version: 70.0

**Comment by TCM5** [comment]
tip: I guess **indexOf** is not making the job. It's returning allways -1

**Comment by VicenteQueiroz** [comment]
Exactly! Suddenly my tables stopped working and it was related to that. But I don't know what changed... I think `oldData` object didn't have the key `tableData`.  I use now **findIndex** instead to search for the index

**Comment by batsauto** [comment]
This is a duplicated of issue #1257 . A work around/answer is provided there.
