### ISSUE TITLE
Edit documentation

### ISSUE THREAD

**Issue by hrafaelveloso** [mbrn/material-table#1276]
**Is your feature request related to a problem? Please describe.**
This package is growing and there's a lot of new PRs merged in master, with some of them adding functionality to the package but that functionality isn't explained in the docs. 

**Describe the solution you'd like**
So, I propose that the documentation could be edited here in github aswell. For every edit we submit a PR. I know that's an increment in the number of PRs, but I think that @mbrn could just appoint someone of his trust to do that - accept and ignore PRs that are relatable to the docs.

I don't know if that's a good feature or not, but that's something that I've been thinking for some time.

**Comment by Justin2997** [comment]
I agree, that will make the documentation must clear for the futur. I will like to help on that, but for now  I can not modify the documentation. Let me know if you need help @mbrn
