### ISSUE TITLE
MaterialTable modifying column prop directly instead of making a copy

### ISSUE THREAD

**Issue by TheGoodSpinach** [mbrn/material-table#1277]
**Describe the bug**

Material Table currently modifies the column prop directly instead of making a copy first, which can cause unexpected side effects. For example, filtering a grid will save the filter state to the columns object, which will cause any future rendered grid that uses the same columns object to render with the same filter.

A similar issue was fixed in #1174 for the data prop; it needs to be extended to all props.

 

**To Reproduce**

https://codesandbox.io/s/mystifying-resonance-iom1z?fontsize=14

1. Type something into the filter cell in the first grid

2. Click the "Show Second Grid" button

3. Second grid renders with the same filter

 

**Expected behavior**

The column prop should not be modified directly by it's child, so that other tables can use a clean version as originally defined.

**Comment by raythree** [comment]
We experienced something that may be related, when using immer.js in our reducer and passing data to the table, we get an exception:

```
TypeError: Cannot add property tableData, object is not extensible
(anonymous function)
node_modules/material-table/dist/utils/data-manager.js:276
  273 | 
  274 | this.selectedCount = 0;
  275 | this.data = data.map(function (row, index) {
> 276 |   row.tableData = (0, _objectSpread2["default"])({}, row.tableData, {
      | ^  277 |     id: index
  278 |   });
  ```

**Comment by schen3** [comment]
I am facing the same, My solution is to modify column.tableData.filterValue 

`  useEffect(() => {
    columns.map(item => (item.tableData.filterValue = undefined));
  }, [columns]);`

Not sure this is a good solution, but it will reset filter after page redirect.

**Comment by lkostrowski** [comment]
This is seriously bad one...

I handle it by changing my columns to getter each time like this:

```const getNameColumn = (): Column<Account> => ({
	title: 'Name',
	render: ({ firstName, lastName }) => {
		return `${firstName} ${lastName}`;
	},
	customFilterAndSearch: nameSearchStrategy,
});```
