### ISSUE TITLE
Add a flag to a row's tableData to indicate if row is on current page

### ISSUE THREAD

**Issue by eoghanmccarthy** [mbrn/material-table#1280]
In most use cases in my experience and what I'm recently working on, when a user checks 'selects all', they are generally looking to get all items on the current page, not all pages. Similar to how selecting emails in Gmail, Outlook, etc. works.

I've tried manually to get this data through tableRef but this isn't reliable. It would be great if in the returned data from onSelectedChange, each selected item also had a boolean to indicate if it is on the current page. Something like:

```
tableData: {
    id: 0,
    selected: true,
    visible: true/false
}
```
Not sure if this possible but it would be an extremely useful feature.

Or, is it possible with the current api somehow?

**Comment by eoghanmccarthy** [comment]
Or maybe:
```
tableData: {
    id: 0,
    selected: true,
    currentPage: true/false
}
```

**Comment by creative-dev-lab** [comment]
@eoghanmccarthy I am facing the same problem with this.
Have you found any solution?

**Comment by eoghanmccarthy** [comment]
@creative-dev-lab No, unfortunately not. Seems it's an issue with table data being mutated. Such a great lightweight table package this, I hope I don't have to abandon it.

**Comment by creative-dev-lab** [comment]
It'd be much appreciated if you could share your solution whenever you find it!
Thanks, @eoghanmccarthy
