### ISSUE TITLE
Add require property in column field

### ISSUE THREAD

**Issue by chitgoks** [mbrn/material-table#1282]
It would be nice to have a require property so that if a user selects the check icon to add a row and the field is required, it will show a red border and some possible error message below it.

**Comment by sshanzel** [comment]
This is a nice feat. Once declared valid, i'll start working on this one.

**Comment by hyphaene** [comment]
Hi everyone,

Any news on this feature ?

I'd be glad to help if needed

**Comment by sshanzel** [comment]
Hi @hyphaene, unfortunately there wasn't any update on this issue yet for me to proceed on development.

**Comment by Michal-Sh** [comment]
Hi, 
I'd like to have it.
still no updates?

**Comment by sshanzel** [comment]
We shall call for @mbrn
