### ISSUE TITLE
Hello There

### ISSUE THREAD

**Issue by akayee** [mbrn/material-table#1286]
My css getting down with table

without your table
![image](https://user-images.githubusercontent.com/53110296/68085907-0d48de80-fe57-11e9-9549-40be40b5a58b.png)

with your table
![image](https://user-images.githubusercontent.com/53110296/68085911-2baeda00-fe57-11e9-86a2-cc9fbad98233.png)

and i wanna put £ on current balance row. Can u help me?

**Comment by hrafaelveloso** [comment]
So, you have a lot  of options that you can customize in material-table. That **ACCOUNTS** is tht title, and you now have a _search field_. That's the `options.toolbar`, if you set that to `false`, that disappears. 
In your columns you can do a _custom render_ of the field, for instance, to add £ in current balance you need to do something similar:

```js
{
    title: 'Current Balance',
    field: 'balance',
    render: rowData => `£ ${rowData.balance}`,
  },
```

**Comment by akayee** [comment]
Thanks for information but i have one more problem. If you could focus on sidebar you can see difference. This table changing my sidebar css. How can i fix that?

**Comment by akayee** [comment]
Again me. It is fixed. Dunnow how :) thx.

**Comment by hrafaelveloso** [comment]
I didn't saw that problem with the sidebar :smile:

**Comment by mbrn** [comment]
I think that problem resolved.
