### ISSUE TITLE
examples are gone....

### ISSUE THREAD

**Issue by hbinkle** [mbrn/material-table#1290]
Hi,
I'm searching for examples linked in some issues.
Especially this one: [https://mbrn.github.io/material-table/#/docz-examples-02-example-column-types#column-types-example](https://mbrn.github.io/material-table/#/docz-examples-02-example-column-types#column-types-example)
Where are the examples gone?

Greetings
Harald

**Comment by sshanzel** [comment]
You may also look here for the examples with regards to material-table: https://material-table.com/#/

**Comment by hbinkle** [comment]
Thanks, but there is no longer a column types example
