### ISSUE TITLE
doubleHorizontalScroll

### ISSUE THREAD

**Issue by kadirguloglu** [mbrn/material-table#1297]
Uzun bir tablo için çift scroll (doubleHorizontalScroll) özelliğini aktif ediyorum. Herhangi bir değişiklik yapmıyor.

![Ekran Alıntısı](https://user-images.githubusercontent.com/28136387/68298239-ee8e5600-00a9-11ea-8f3a-7eecff088fd4.PNG)
![Ekran Alıntısı1](https://user-images.githubusercontent.com/28136387/68298275-036ae980-00aa-11ea-81a9-d8601d318d58.PNG)
![Ekran Alıntısı](https://user-images.githubusercontent.com/28136387/68298324-1bdb0400-00aa-11ea-94a1-1207402449b2.PNG)

**Comment by hbinkle** [comment]
Settings `doubleHorizontalScroll: true` causes the space between column drop zone and header is shown, but there is no scrollbar which can be used.

**Comment by hbinkle** [comment]
here a sample sowing the option doubleHorizontalScroll does not work:
https://codesandbox.io/s/material-demo-ynctq?fontsize=14&hidenavigation=1&theme=dark
