### ISSUE TITLE
Checkbox in Actions field .

### ISSUE THREAD

**Issue by gmumdzhiev** [mbrn/material-table#1303]
Hey guys i want to thank you first for the great table that you have created . But i have some questions about the customization and i try to find a solution .
First is there a way to display the options Selection together with the actions Download ? 
Second can we switch the place of the checkbox to be next to the Download button in instead of the Delete button ? ( as shown on the image )

![table3](https://user-images.githubusercontent.com/32012354/68379769-ca388500-014e-11ea-88ee-f36d0c0df89a.jpg)

I will be very greatfull if someone can give me some examples or answers . Thank you again !

**Comment by mbrn** [comment]
Hi @gmumdzhiev ,

You can use version 1.54.0 positioning the actions on row even if selection is true. But MT does not have a options to move selection column to right.
