### ISSUE TITLE
Breaking change on how props.data is handled

### ISSUE THREAD

**Issue by jpmtrabbold** [mbrn/material-table#1304]
Hello guys,

This refers to this commit:
https://github.com/mbrn/material-table/commit/ae62214079fc85a5160627faf7eeca9c51f1ec84

I put a comment there, as follows:

With this change, this.data is not holding the original references to the original objects inside the array. In line 50, you are deconstructing row (...row), which also means that if it was a named object, it becomes just a plain js object. The problem with that is:

- this is a breaking change;
- whenever you pass back the row (for example, to onRowClick), any developer will expect that to be the exact object that he passed before (as it was before this commit), but now this is a completely different reference. In a whole project that I've been using material-table, I've been relying on the fact that the rowData passed back has the same reference as the objects I passed as props.data, and now all stopped working.

Was that supposed to be a breaking change, by design?

**Comment by mbrn** [comment]
Hi @jpmtrabbold ,

It seems a bug. But i will examine why this change pushed asap.

**Comment by pradej** [comment]
This also seems like the reason behind this issue: https://github.com/mbrn/material-table/issues/1283

**Comment by simonkaspersen** [comment]
After update to 1.5.3, expanding of row got cancelled and reset after i loaded details from redux for the clicked row. After downgrading to 1.5.2, it worked again.

**Comment by mbrn** [comment]
I asked reason of this change to @Domino987 . I think that we can revert this change.

**Comment by jpmtrabbold** [comment]
Thank you very much @mbrn, if that gets reverted back it will be much appreciated. I believe one good solution for both not mutating the data prop and also keeping a reference would be to data-manager have a separate array (this.data) with its items corresponding to the data prop items. Each  item would have two major properties:
- origin - untouched reference to the data prop;
- tableData - whatever stuff that you want to annotate the item with

pls let me know when any decision is made on this. Cheers

**Comment by sureshtidbit** [comment]
hey @mbrn have you find any solution and change code for that because on redux also when data change but material table is not re-rendering as per new props data
