### ISSUE TITLE
material table allows user to click on other rows to action column 

### ISSUE THREAD

**Issue by mohendren** [mbrn/material-table#1305]
When a row is in editable mode . material table allow user to click on other rows action buttons. thus it enables the row to the respective action.

https://material-table.com/#/docs/features/editable

click on the first row edit button.
then click on the next row edit button.

expected :- it should not allow user to click on other rows when a row is in editable mode

Please help to fix this issue

**Comment by mbrn** [comment]
Hi @mohendren ,

Thanks for feedback. I solved problem. It will on next release.

**Comment by mbrn** [comment]
This is done with 1.54.1

**Comment by mohendren** [comment]
Thank you!
