### ISSUE TITLE
onSelectionChange looses checkboxes seelcted if .setState() used

### ISSUE THREAD

**Issue by skitsanos** [mbrn/material-table#1307]
So in my case i needed to take an array of selected items and put them into my component state:

```jsx
 onSelectionChange={(selection, current) =>
                     {
                       _this.setState({selectedRows: selection});
                     }}
```

I can see in _tableRef.current_ that _tableData_ marked as checked, but i don't see any checkboxes checked anymore. if i don't do anything with state within this handler, everything works as expected.

Any hints on how to fix it?

**Comment by mbrn** [comment]
Hi @skitsanos ,

I solved the problem. It is related with new componentDidUpdate implementation. This problem will be with next release (probably tomorrow or weekend).

**Comment by skitsanos** [comment]
Tesekkur ederim Mehmet! can't wait :)

**Comment by mbrn** [comment]
This is done with 1.54.1

**Comment by roseak** [comment]
I just upgraded to 1.54.1 and it still seems to be a problem for me :/

**Comment by roseak** [comment]
Also having the same problem if using state with onAllSelected

**Comment by roseak** [comment]
It also changes it so that the selection is just the most current selection instead of including the other options that have also been checked.

**Comment by andrewmirs** [comment]
I'm having the same issue. Even with the latest update, as soon as I call setState, the table re-renders without displaying the selected table rows

**Comment by jasonvooo** [comment]
Any update for this bug? I am still experiencing this on `1.54.1`

**Comment by KPpuria** [comment]
i am still experiencing this issue

**Comment by eoghanmccarthy** [comment]
Does anyone know when this bug appeared? Is there a previous version where this isn't an issue?

**Comment by eoghanmccarthy** [comment]
It also happens when `options.selectionProps` is called.

**Comment by aniesshsethh** [comment]
Same Issue Here, any sort of setState, and the table looses it's value

**Comment by eoghanmccarthy** [comment]
@aniesshsethh I created my own checkboxes in a custom column and save the checked state in component state. It's not ideal but works.

**Comment by aniesshsethh** [comment]
I do not need for the checkboxes, but to maintain the number of rows shown. so if the user has selected 20, I want 20 selected

**Comment by Discartyptics** [comment]
I'm also still experiencing this issue.

**Comment by nocoli** [comment]
I am also experiencing this issue. When I call setState from my actions onclick event the table is re-rendered and I lose my selected rows

**Comment by watchsteve** [comment]
Still seeing this as well.

**Comment by Laferu** [comment]
Aqui também ainda está havendo isso
