### ISSUE TITLE
Breaking Changes in array of actions passed as props

### ISSUE THREAD

**Issue by BrenoVelasco** [mbrn/material-table#1309]
Good morning!
Updated material-table from v1.50.0 to v1.54.0 and it broke my piece of code which handles array of actions objects passed via props. It doesn't recognize my "rowData" param anymore.

```
actions={[
  rowData =>
    props.updateRow && {
    icon: 'edit',
    tooltip: props.updateRow.disabled(rowData) ? null : 'Editar Usuário',
    onClick: (event, rowData) => props.updateRow.function(rowData),
    disabled: props.updateRow.disabled(rowData),
  },
]}
```

**Expected behavior**
Being able to pass rowData to tooltip and disabled.

**Screenshots**
![Screenshot from 2019-11-08 15-28-37](https://user-images.githubusercontent.com/21113340/68501275-8754db00-023c-11ea-95d3-a5adb80c00b8.png)

**Desktop:**
 - OS: Ubuntu 18.04
 - Browser: Chrome

Thank you for your time =)

**Comment by mbrn** [comment]
This is done with 1.54.1

**Comment by BrenoVelasco** [comment]
Thank you very much!
