### ISSUE TITLE
Upgrading @material-ui/core to 4.6.0 breaks material-table

### ISSUE THREAD

**Issue by roseak** [mbrn/material-table#1310]
**Describe the bug**
After upgrading to 4.6.0 for @material-ui/core, material-table is breaking.  I believe it has something to do with importing styles/theming, but unclear.

Also on the same error but with createTypography.js and createMuiTheme.js instead of createPalette.js

```ERROR in /Users/[...]/node_modules/material-table/node_modules/@material-ui/core/styles/createPalette.js
Module not found: Error: Can't resolve 'deepmerge' in '/Users/[...]/node_modules/material-table/node_modules/@material-ui/core/styles'
 @ /Users/[...]/node_modules/material-table/node_modules/@material-ui/core/styles/createPalette.js 17:40-60
 @ /Users/[...]/node_modules/material-table/node_modules/@material-ui/core/styles/createMuiTheme.js
 @ /Users/[...]/node_modules/material-table/node_modules/@material-ui/core/styles/defaultTheme.js
 @ /Users/[...]/node_modules/material-table/node_modules/@material-ui/core/styles/withStyles.js
 @ /Users/[...]/node_modules/material-table/dist/index.js```

**Comment by jadbox** [comment]
Strange, I haven't seen this yet in my project with 4.6 core... maybe its a certain material-table feature that when enabled causes an issue with 4.6?

**Comment by roseak** [comment]
Not sure what the deal is, but it's only a problem in my files with material-table.  If I install deepmerge, the errors go away.  Maybe you have deepmerge already installed?

**Comment by jadbox** [comment]
Huh interesting, I do have deepmerge installed by virtue of another component using it.

`yarn list deepmerge`

```
yarn list v1.19.1
├─ deepmerge@2.2.1
└─ react-player@1.14.0
   └─ deepmerge@4.2.2
```

Seems like deepmerge should be added to material-table as a proper dep?

**Comment by roseak** [comment]
Has anything been done to fix this?
