### ISSUE TITLE
Filter by a range of data

### ISSUE THREAD

**Issue by jeffsupancic** [mbrn/material-table#1311]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add the ability to filter columns by a range.  For example a date between 2019-11-08 and 2019-11-30.

**Describe alternatives you've considered**
An alternative to implementing range filters would be allowing the developer to implement custom filter components instead of having to override the entire FilterRow.

**Comment by fazaal97** [comment]
Hey Do find a way to Range of date in Filter. I also looking a way to filter Date by Range
