### ISSUE TITLE
isEditable conditional is broken in version 1.54.1

### ISSUE THREAD

**Issue by bilix** [mbrn/material-table#1321]
**Describe the bug**
isEditable is not working in version 1.54.1. It works fine in version 1.54.0. If the condition is set to false, you can edit the row anyway.

**To Reproduce**
```
editable={{               
    isEditable: rowData => false,
    onRowUpdate: (newData, oldData) =>
        new Promise((resolve, reject) => {
            setTimeout(() => {
                {
                      /* const data = this.state.data;
                      const index = data.indexOf(oldData);
                      data[index] = newData;                
                      this.setState({ data }, () => resolve()); */
                 }
                 resolve();
                 }, 1000);
              }),
         }}
```

**Expected behavior**
The edit action button is disabled

**Comment by ogenodisho** [comment]
(This repo needs some unit tests)

**Comment by georgehazan** [comment]
I confirm. not only isEditable, but also isDeletable too

**Comment by thuryn** [comment]
I can confirm it also

**Comment by nathann282** [comment]
this issue is still in version 1.54.2

**Comment by jfocco-IUGO** [comment]
I can confirm it also, isEditable is not working yet...

**Comment by thelazydogsback** [comment]
Also running into this issue

**Comment by evblurbs** [comment]
Also experiencing this. I used `patch-package` module to apply the change for my project.  Thanks @benrawn for the fix.

**Comment by william13murphy** [comment]
I am still experiencing this issue in 1.57.2. Can anybody else confirm?

**Comment by LuisPinaSoares** [comment]
@william13murphy i do not confirm.
Just updated my version to 1.57.2 and its seems to be working

`          editable={{
            isEditable: rowData => selectedSubst.includes(rowData.id),
            onRowUpdate: (newData, oldData) => {},
          }}`

**Comment by william13murphy** [comment]
@LuisPinaSoares Thank you for your response. isEditable is working as intended!!

Thank you package managers/contributors for a wonderful library.
