### ISSUE TITLE
API data put and post with axios

### ISSUE THREAD

**Issue by p9614** [mbrn/material-table#1324]
I have the methods post, put and get that I call from my API with Axios, I want use the functions onRowAdd and onRowUpdated of Material-table to manipulate data but I have not succeeded. 
I only succeeded in recovering the data and displaying it in the table using useEffect and the prop data

This is my code to edit the data I get that error: PUT http: // localhost: xxxx / api / User / edit /? IdUser = 1 404 (Not Found)

To add a new row does not send me any errors but also does not add the data.

How  can I use the methods put and post to add and edit rows?

`import React, { useState, useEffect } from 'react';
import MaterialTable from 'material-table';
import  axios  from 'axios';

export default function UserTable() {

const url='/api/Users';

const [user, setUser]= useState({DataUser:[]});

 useEffect(()=>{
    const getUser=async()=>{
            const response =await axios.get(url);
            setUser(response.data);
    }
    getUser();
},[]);

  return (
    <MaterialTable
    title="Users"
    columns={[
      {title: 'IdUser',field: 'IdUser', type: 'numeric', hidden:'false'},
      {title: 'name',field: 'name'},
      { title: 'lastname', field: 'lastname' },
      { title: 'age', field: 'age', type: 'numeric' },
    ]}
    data={user.DataUser}
    options={{
      filtering: true
    }}
    editable={{
      onRowUpdate: (newData, oldData) =>
      new Promise(resolve => {
          setTimeout(() => {
          resolve();
          const data=[...user.DataUser];
          data[data.indexOf(oldData)] = newData;
          axios.put('api/User/edit/', newData,{
                  params: {
                    id:user.DataUser[0].IdUser
                  }
              })
              .then(res => console.log(res.DataUser));
              setUser({...user,data});
      }, 600);
  }),
  }}
  />
);
}`

**Comment by memredemir** [comment]
You can try putting your fetch to a method(like fetchData) and call that method like this:
`editable={{
onRowUpdate: (newData, oldData) =>
new Promise(resolve => {
setTimeout(() => {
resolve();
const data=[...user.DataUser];
data[data.indexOf(oldData)] = newData;
fetchData(data);
setUser({...user,data});
}, 600);
}),`
