### ISSUE TITLE
Functional Components (Hooks) - Editable options

### ISSUE THREAD

**Issue by mbv401920150** [mbrn/material-table#1325]
I'm checking the Editable option, but only has documentation related of React Components (Classes).
I need help to know how to apply the same feature with a Functional Component (Using Hooks)...

[https://material-table.com/#/docs/features/editable](https://material-table.com/#/docs/features/editable)

```
onRowUpdate: (newData, oldData) =>
	new Promise((resolve, reject) => {
	  setTimeout(() => {
		{
		  const data = this.state.data;
		  const index = data.indexOf(oldData);
		  data[index] = newData;
		  this.setState({ data }, () => resolve());
		}
		resolve()
	  }, 1000)
	}),
```

I cannot figure out how to update a state and execute the function `resolve()`.
Does somebody have the same problem?

Find the code right here
[https://codesandbox.io/s/materialtableui-b35v3](https://codesandbox.io/s/materialtableui-b35v3)

**Comment by mbv401920150** [comment]
It's valid or it's the best practice do the following?

**Comment by TroySchmidt** [comment]
It still isn't ideal.  I am trying to use useReducer hook and dispatch from the editable promises but it crashes.

**Comment by karanness86** [comment]
i used the code above that @mbv401920150 provided as an example to solve my onRowUpdate issue. Thank you so much.

**Comment by DanielFerszt** [comment]
Hi, I used the code you provided @mbv401920150 and it worked fine, but when I changed ir to receive data from props it stoped updating.
I edit a field, and data changes in the state and variables, but the table renders the old data. 
I only changed this:
```
const [gridData, setGridData] = useState({
    data: props.data,
    resolve: () => {},
    updatedAt: new Date()
  });
``` 
Originally I had a callback to a parent component that handles the data request and logic. That callback changed the state in the parent, that was then passed as props to the table. But I removed all of that, trying simply to take data from props, and then updating the state within the table component.

Any Ideas?

**Comment by ScottEAdams** [comment]
@DanielFerszt - add a key to the table that is randomly set to force the refresh:

`const [refreshKey, setRefreshKey] = useState(Math.random())`

```
useEffect(() => {
  gridData.resolve();
  setRefreshKey(Math.random())
  console.log("RESOLVE AT:", gridData.updatedAt);
}, [gridData]);
```

`<MaterialTable key={refreshKey}`

**Comment by DanielFerszt** [comment]
Thanks, I'll try that. I solved the issue by adding a second state for the columns and refreshing that with every edit too... That forced the table to refresh.

**Comment by TroySchmidt** [comment]
I have also set the tableRef and called onQueryChange to force a refresh as well on row edits.

**Comment by lgm-dev** [comment]
Hey,

Can you please guys @TroySchmidt  or @DanielFerszt provide a working exemple of your guys solution. I'm trying to move my project to react hooks and I'm not able to have my props containing the data of my table, passed down to that material-table. 

I tried the refreshed keys already trick, but didn't make any difference. 

```
    const [refreshKey, setRefreshKey] = useState(Math.random())
    const [gridData, setGridData] = useState({
  data: props.ingredients
  resolve: () => {}});

useEffect(() => {
  gridData.resolve();
  setRefreshKey(Math.random())

}, [gridData]);

```

**Comment by DanielFerszt** [comment]
Sure, here is a link to my question in stackOverflow where someone answered very well. He even explains a little more in the comments at my request.

[https://stackoverflow.com/questions/60935643/react-material-table-editing-from-props-using-hooks/60957646?noredirect=1#comment107850018_60957646](url)

Let me know it you need more help!
