### ISSUE TITLE
Actions `disabled` prop is not respect in 1.54.0 and 1.54.1

### ISSUE THREAD

**Issue by callmeberzerker** [mbrn/material-table#1326]
**Describe the bug**
The `disabled` prop is not respected on the `Action` object.

**To Reproduce**
1. Go to any of the examples for actions
2. Edit the action to have `disabled: true` prop
3. See that the action is not disabled

**Expected behavior**
`disabled` prop is respected.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 n/a

**Comment by mvitkin** [comment]
I am not able to reproduce this bug, neither in my local environment, nor in the examples for actions. Adding `disabled: true`, does seem to disable the buttons (I am no longer able to click on them).

Can you share an example where you see this occurring?

**Comment by IraSkyx** [comment]
I can reproduce this.

CodeSandbox : https://codesandbox.io/s/material-table-issue-with-disabled-4iioi

It seems to occur only when passing a function as action 
`rowData => ({
            icon: React.forwardRef((props, ref) => (
              <Check {...props} ref={ref} />
            )),
            disabled: true
          })`

Doesn't work in 1.54.1 

While : 
`{
            icon: React.forwardRef((props, ref) => (
              <Check {...props} ref={ref} />
            )),
            disabled: true
          }`

Does work even in 1.54.1

**Comment by msanmartin-cloudhesive** [comment]
Having the same issue with 1.54.1. I'm using the sample version from the documentation on Conditional Actions, which also doesn't seem to be working [Conditional Actions Example](https://material-table.com/#/docs/features/actions)

[CodeSandbox Example](https://codesandbox.io/s/optimistic-leavitt-vh3hc?fontsize=14)

Behavior is the same that @IraSkyx describes. It doesn't work when passing a function and when passing 'disable' prop in an object it works but affects every row

**Comment by Shurpop** [comment]
Hello!

After update from version 1.50.0 to 1.54.1 it doesn't work.

**Comment by Eplumecocq** [comment]
I also have the same issue in 1.54.1

**Comment by Tainan404** [comment]
I have the same bug when I use a function to actions.

https://codesandbox.io/s/react-example-zumc6?fontsize=14&hidenavigation=1&theme=dark

**Comment by dmytro-mavrosaus** [comment]
Could anybody merge this PR?

**Comment by yoniabrahamy** [comment]
I join @dmytro-mavrosaus request

**Comment by hikmert** [comment]
Hi,
Same issue with 1.54.1 and 1.54.2. I would appreciate if @dmytro-mavrosaus ' PR is merged.

**Comment by PeterJFerrarotto** [comment]
What's strange is that the `hidden` prop works just fine when using a function for an Action object.

**Comment by alexrt23** [comment]
Same issue v1.54.2.

**Comment by RegisParpex** [comment]
Do we have any news regarding a 1.54.3 containing this fix ?

**Comment by YunfanZH** [comment]
Ran into the same issue... with latest v1.54.2

**Comment by hikmert** [comment]
downgrading to v1.53.0 solved the issue for me.

**Comment by gabolucuy** [comment]
Any updates on this issue?

**Comment by callmeberzerker** [comment]
dont know why are we still waiting for this PR to be merged. :(

**Comment by kwiatopl** [comment]
Any update on this issue?

**Comment by callmeberzerker** [comment]
It seems this issue is fixed as of 1.57.2. Everyone affected upgrade to this version. I will close this issue. 🎉
