### ISSUE TITLE
Table Footer

### ISSUE THREAD

**Issue by X-3mal** [mbrn/material-table#1328]
**Is your feature request related to a problem? Please describe.**
Statistcs table. I cannot add "Total" footer row, except Overriding Body component

**Describe the solution you'd like**
Add option like "columns" with footer cells info (field, customReducer, customRender)

**Describe alternatives you've considered**
I solved it with
`components={{Body: props=><Fragment><MTableBody {...props} /><...my custom footer.../></Fragment>`

**Comment by ericjansen1988** [comment]
any news on this?

**Comment by radmonteiro** [comment]
We need this.
Something like https://material.angular.io/components/table/overview#footer-row

**Comment by Marouann** [comment]
Your alternative works very well, thanks a lot.
