### ISSUE TITLE
Search slow performance

### ISSUE THREAD

**Issue by Kraviecc** [mbrn/material-table#1334]
**Describe the bug**
When there is a page size of ~50 (or more) records, searching is very slow (the whole table rerenders when searchText state is changed)

**To Reproduce**
1. Prepare ~30 rows of data
2. Set pageSize to 50
3. Start typing in search box
4. Lags appear

**Expected behavior**
When a user is typing the search phrase, only the toolbar should rerender.

**Comment by MatiasManevi** [comment]
I'll add to this.

Since there is no backend pagination built in. Is it possible to implement virtualization for the not shown rows?

Having a table with 1.000.000 freezes the browser!
