### ISSUE TITLE
Allow to override MTableGroupbar styles

### ISSUE THREAD

**Issue by menreiki** [mbrn/material-table#1338]
MTableGroupbar's Toolbar doesn't take over styles as it's already done for MTableToolbar.

https://github.com/mbrn/material-table/blob/master/src/components/m-table-toolbar.js
https://github.com/mbrn/material-table/blob/master/src/components/m-table-groupbar.js

So it'd be possible to :

```javascript
components={{
	Groupbar: props => (
		<div>
			<MTableGroupbar classes={{root:"some_class"}} {...props} />
		</div>
	),
}}
```

**Comment by mbrn** [comment]
Hi @delikatessa 

I will implement this asap.
