### ISSUE TITLE
Sort doesn't support Date or Datetime data types

### ISSUE THREAD

**Issue by martindeanlund** [mbrn/material-table#134]
Despite setting a column as type "date" or "datetime" the column sorting applies comparisons based on simple alphanumeric comparisons as if the data was just of type "String."

1. ) Go to example column exhibit here:
https://mbrn.github.io/material-table/#/docz-examples-02-example-column-types#column-types-example
2.) Edit code
3.) Swap years of sample data rows
4.) Click for ascending sort

**Expected behavior**
Earliest year should display at the top of the sort, not the earliest month

**Comment by mbrn** [comment]
Hi @martindeanlund ,

You are right. I will resolve it asap.

**Comment by martindeanlund** [comment]
I think it might just be an issue with the example. I was able to sort correctly if the data provided is a proper JS Date and I use "dateTime" as the type for the column definitions, but I have to add Render arguments to convert back to a datestring for display purposes. I don't know if you want to support date strings as the data type and convert them to Date for sorting or support Date for the data type and convert to date Strings for rendering but either should work.

**Comment by mbrn** [comment]
I just look at example at docs now. I will look at code and test it with many cases. I may add support for string dates to be sorted properly. Thanks for giving detailed information

**Comment by mbrn** [comment]
No need improvement.

**Comment by estefrare** [comment]
A solution using [Moment.js](https://momentjs.com/): 
```
customSort = (a , b) => {
        return moment(moment(a[field], [formatDate]))
          .isBefore(moment(b[field], [formatDate])) 
            ? 1 
            : -1;
      };
```

**formatDate**: here you have to put what is the format of the string date _(ex: 'DD-MM-YYYY - hh:mm A')._

**Comment by ytcitsupport-jlin** [comment]
Is this issue been solved?
I got field with string date, the sort is still not working.

![Screenshot 2021-05-12 164026](https://user-images.githubusercontent.com/82171601/118057398-c3d92980-b340-11eb-8cd8-93e477c75725.png)
