### ISSUE TITLE
The placement of the filter row does not adhere to material design guidelines.

### ISSUE THREAD

**Issue by ogenodisho** [mbrn/material-table#1341]
According to the [material design guidelines on data tables](https://material.io/components/data-tables/#anatomy):

> Controls that manipulate how table data is displayed (such as pagination or filter chips) should be placed directly above or below a table.

![](https://storage.googleapis.com/spec-host-backup/mio-components%2Fassets%2F1s4W5twT0ThnL6pnchJmTdSY4uZIUDU00%2Fcomponents-datatables-filtertool.png)

Material table is currently not adhering to this guideline because the filter row is located inside the table below the header.

**Comment by mbrn** [comment]
Hi @ogenodisho 

This seems very good. I will implement this but now i want to focus on bugs.

**Comment by kirakik** [comment]
@mbrn I have an immediate need for this, I could work on this feature and open a PR?
