### ISSUE TITLE
Columna tipo Boolean

### ISSUE THREAD

**Issue by jfla1205** [mbrn/material-table#1344]
Al momento de agregar una celda de tipo boolean, esta no se muestra.

`class SimpleAction extends React.Component {
  render() {
    return (
      <MaterialTable
        title="Simple Action Preview"
        columns={[
          { title: 'Name', field: 'name' },
          { title: 'Surname', field: 'surname' },
          { title: 'Birth Year', field: 'birthYear', type: 'numeric' },
          {
            title: 'Birth Place',
            field: 'birthCity',
            lookup: { 34: 'İstanbul', 63: 'Şanlıurfa' },
          },
          { title: 'State', field: 'state'}
        ]}
        data={[
          { name: 'Mehmet', surname: 'Baran', birthYear: 1987, birthCity: 63, state: true },
          { name: 'Zerya Betül', surname: 'Baran', birthYear: 2017, birthCity: 34, state: false },
        ]}        
        actions={[
          {
            icon: 'save',
            tooltip: 'Save User',
            onClick: (event, rowData) => alert("You saved " + rowData.name)
          }
        ]}
      />
    )
  }
}
`

**Comment by mbrn** [comment]
Hi @jfla1205 ,

Actually i don't know your language :). I know Just english, kurdish and turkish. But google translate helped me:).

You can add type: 'boolean' to your column definition or add a custom render to it. 

```jsx
{ title: 'State', field: 'state', type: 'boolean' }
```
