### ISSUE TITLE
Array field

### ISSUE THREAD

**Issue by llermaly** [mbrn/material-table#1346]
**Describe the bug**
Array fields are showing as a string with no comma

ie: [1,2,3] renders as 123 instad of 1,2,3

**To Reproduce**
1. Select a column with array field
2. Render the table

**Expected behavior**
array as string separated with commas

Additional info:

I tried with this custom render method

        {
          title: "Cods. Comisión",
          field: "cod_comision",
          render: rowData => rowData.cod_comision.join()
        }
Throws this error when editing a field
rowData.cod_comision.join is not a function

But data shows good after a refresh

**Comment by mbrn** [comment]
Hi @llermaly 

I tested this code and it works. Can you test it again with latest version, please?

![image](https://user-images.githubusercontent.com/7895451/69183541-3c807080-0b24-11ea-824f-742aadcb65cf.png)

I am closing issue. You can reopen it if it requires.

**Comment by ricklevy21** [comment]
I am now experiencing this error as well. Happens when an edit is submitted to a field that has a custom render method.
