### ISSUE TITLE
Programmatically cancel action tooltip, Add leaveDelay Property like in Materials-UI

### ISSUE THREAD

**Issue by chitgoks** [mbrn/material-table#1347]
So i have an action button in the table, and i enabled the tooltip property so when the mouse hovers over it, the tooltip shows. 

for my use case scenario, i wish to ask if it is possible to get a reference to the tooltip so i can hide it before calling the code in the action's onClick().

o r... perhaps the leaveDelay property like in the materials-ui, there are some scenarios where the tooltip is still visible when i go to another page. setting a delay of 0 will automatically hide the tooltip

**Comment by mbrn** [comment]
Hi @chitgoks 

Try this code: 

```jsx
<MaterialTable
                  tableRef={this.tableRef}
                  columns={this.state.columns}
                  data={this.state.data}
                  title="Demo Title"
                  actions={[
                    rowData => ({
                      icon: 'save',
                      tooltip: rowData.name == "A1" ? 'Save User' : undefined,
                      onClick: (event, rowData) => alert("You saved " + rowData.name)
                    }),
                    {
                      icon: 'delete',
                      tooltip: 'Delete User',
                      onClick: (event, rowData) => confirm("You want to delete " + rowData.name)
                    }
                  ]}
                />
```

**Comment by chitgoks** [comment]
@mbrn  sorry, what does this code do?
