### ISSUE TITLE
Warning pops up with latest @material-ui/core

### ISSUE THREAD

**Issue by ifndefdeadmau5** [mbrn/material-table#1348]
**Describe the bug**
With `@material-ui/core` v4.6.0, below warning is shown
> Warning: Failed prop type: Invalid prop `color` of value `inherit` supplied to `ForwardRef(TextField)`, expected one of ["primary","secondary"].

**To Reproduce**
Install both `@material-ui/core` and `material-table` with latest version.

**Expected behavior**
Warning shouldn't be appear

This is because current version of material-ui's TextField only supports `["primary","secondary"]` while one in repository uses `color="inherit"` on TextField.

**Comment by mbrn** [comment]
Hi @ifndefdeadmau5 

This will be in next release. Thanks.

**Comment by adeelibr** [comment]
Just asking 😄 when will the next release happen? Also can I help in anyway to move this forward 😄

**Comment by jakub-bao** [comment]
same issue here.. 

![image](https://user-images.githubusercontent.com/47790868/70067514-62922000-15bc-11ea-9564-e59d73e2ec80.png)

**Comment by VictorGaiva** [comment]
Do you have the latest version of the module?

**Comment by jakub-bao** [comment]
@VictorGaiva correct.

**Comment by montydhanjal** [comment]
The latest version fixed this issue. Confirmed!
