### ISSUE TITLE
Adding Tree data feature

### ISSUE THREAD

**Issue by mbrn** [mbrn/material-table#135]
Adding Tree data feature for data has parent-child relationship. Something like this:

https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/tree-data/

**Comment by urirahimi** [comment]
Any idea when this may be done?

**Comment by mbrn** [comment]
Hi @urirahimi,

Unfortunately. Because it effects many place to be changed. So i need time to work on it and nowadays i am very busy.

**Comment by plummer-flex** [comment]
Doesn't `detailPanel` already cover this?

**Comment by mbrn** [comment]
Maybe but they need something like this:

https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/tree-data/

**Comment by plummer-flex** [comment]
Right, but it seems like a broken UX.  In the example provided, the child-rows are still rendered inline with the parent-rows.  This causes jumps and incomplete content to be loaded.

Doesn't mean something similar shouldn't/can't be done, but important to note usability when putting effort toward features.

**Comment by mbrn** [comment]
You are right. But sometimes we need something like this. So i think implement this by overriding the Row component.

**Comment by vijthang61** [comment]
any idea when we can expect this feature to be available.

**Comment by mbrn** [comment]
I will complete data grouping in this week. Then i will start to tree data. So in 2-3 weeks(max end of feb) this will be ready.

**Comment by vijthang61** [comment]
Can you let me know what do you mean by data grouping, that by itself looks like tree structure.

**Comment by mbrn** [comment]
Of course. 

This is tree data: Data has parent-child relations
https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/tree-data/

This is data grouping: 
https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/integrated-data-shaping/

**Comment by vijthang61** [comment]
When can we expect this to be merged?

**Comment by mbrn** [comment]
I will merge this until end of february. Now i am working on it.

**Comment by mbrn** [comment]
This is done with v1.19.0
