### ISSUE TITLE
Gets error after upgrading material-table from 1.40.1 to 1.50.0

### ISSUE THREAD

**Issue by hungbang** [mbrn/material-table#1352]
I got a problem after upgrading material-table in my application, everything looks okay, there is no console error log is thrown, but the web app could not load the page. I have debugged, all of the pages are working excluding the page that I used material-table, actually, I have no idea about it. These things below are my configures as well as the information from my app. I hope that there are people who have been seen this bug before. Thank you in advance.

I have added the question on Stackoverflow: 
https://stackoverflow.com/questions/58926340/got-error-when-upgrading-material-table-from-1-40-1-to-1-50-0

**Comment by mbrn** [comment]
Hi @hungbang ,

I checked your configuration. Can you try with latest version please? 1.54.1

**Comment by hungbang** [comment]
Thank you so much @mbrn, I tried to use `1.54.1` with material-UI `3.9.2`, but it seems 1.54.1 only works with `Material-UI v4`. 

If it is, I think I could not use the latest version of `material-table` since there are a lot of implementations in the current source code that using `material-UI v3`. So that to upgrade Material-UI v3 to Material-UI v4 would take a lot of time from my team. 

I want to upgrade material-UI to use the new improved code that you have released: `Make MTableEditRow's cells use cellStyle. Thanks to @PFayoux` (https://github.com/mbrn/material-table/releases/tag/v1.54.0), because I want to change the `padding` default of the `MuiTableCell-root ` both modes: View and edit.

**Comment by mbrn** [comment]
@hungbang 

You can use the Mui theme instead of cellStyle. Take a look at this

https://v3.material-ui.com/customization/themes/#customizing-all-instances-of-a-component-type
