### ISSUE TITLE
Arrow function on rowStyle resets page size

### ISSUE THREAD

**Issue by dhs43** [mbrn/material-table#1353]
**Description**
If you add an arrow function to access rowData, the table resets to default pageSize on click. This happens regardless of function contents--even if it's empty.

**To Reproduce**
This can most easily be seen in the material-table docs here:
https://material-table.com/#/docs/features/styling

On the `Selected Row Styling Example` if you change the pageSize and select a row, it will resize to the default.

This works fine:
```
options={{
    pageSize: 10,
    pageSizeOptions: [5, 10, 15],
    rowStyle: {
        // styling here
    },
}}
```

This resets to default pageSize onRowClick
```
options={{
    pageSize: 10,
    pageSizeOptions: [5, 10, 15],
    rowStyle: rowData => ({
        // styling based on rowData here
    }),
}}
```

**Expected behavior**
This should allow for styling based on rowData and should retain the user's pageSize selection even onRowClick.

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [Chrome 78]
 - Version [1.54.1]

**Comment by mbrn** [comment]
Hi @dhs43 ,

I solved problem. It is not about arrow funtion usage. It is about something require a render. 

It will be in next release. Thanks for issue.

**Comment by orestes22** [comment]
Hi, @mbrn  please, check #1644
