### ISSUE TITLE
Insert value into Checkbox . 

### ISSUE THREAD

**Issue by gmumdzhiev** [mbrn/material-table#1356]
Hey guys . I need your help . I don't know how to insert my value prop inside of my checkbox . Before my custom checkbox had a value of : 
` render: rowData =>
                                        <GreenCheckbox
                                            disabled={downloadedIDS && downloadedIDS.indexOf(rowData.documentId) >= 0 ? true : false}
                                            color='default'
                                            value={JSON.stringify({ documentId: rowData.documentId, documentNumber: rowData.documentNumber })}
                                            onClick={this.handleCheckboxClick} />` 
And it was working like supouse to be , but now i decided to use the integraded checkboxes . So how can i set the value prop ? Until now i have tried this , but it doesnt help :
`  options={{
                            
                                selection: true,
                                selectionProps: rowData => ({
                                    value: rowData => JSON.stringify({documentId: rowData.documendId, documentNumber: rowData.documentNumber}),
                                    onClick: (event , rowData) => this.handleCheckboxClick(event,rowData),
                                }),`

**Comment by mbrn** [comment]
Hi @gmumdzhiev ,

Can you try this:

```jsx
options={{

           selection: true,
          selectionProps: rowData => ({
              checked: rowData.name === "Mehmet",
              onClick: (event , rowData) => this.handleCheckboxClick(event,rowData),
          })
        }}
```

**Comment by gmumdzhiev** [comment]
@mbrn I dont understand from where i am supouse to take the `rowData.name` if i dont have it in my table ?

**Comment by mbrn** [comment]
rowData.name is my example. This means you should calculate checked value according to your rowData. Such as: 

checked: rowData.documentId > 10 ? true : false

**Comment by gmumdzhiev** [comment]
@mbrn  I have tried with : `checked: rowData.documentNumber === 'documentNumber'` , but still in my `handleCheckboxClick` function i don't see any data going inside of my object .

**Comment by mbrn** [comment]
Do you want to access value that you assing to select:

```jsx
options={{
          selection: true,
          selectionProps: rowData => ({
              checked: rowData.name === "Mehmet",
              value: rowData.surname,
              onClick: (event , rowData) => alert(event.target.value)
          })
        }}
```

**Comment by gmumdzhiev** [comment]
Sorry @mbrn  , but maybe i didn't explained the question correct . Before i had an custom checkbox from MUI that i have assigned a value to be equal to the documentId and documentNumber : 
`render: rowData =>
                                        <GreenCheckbox
                                            disabled={downloadedIDS && downloadedIDS.indexOf(rowData.documentId) >= 0 ? true : false}
                                            color='default'
                                            value={JSON.stringify({ documentId: rowData.documentId, documentNumber: rowData.documentNumber })}
                                            onClick={this.handleCheckboxClick} />`
And it was working properly . But now i switched to the material-table checkboxes . And in inside of the `selectionProps` i want to do the same with the `value`

**Comment by mbrn** [comment]
Okay,

What is problem with this?

```jsx
options={{
          selection: true,
          selectionProps: rowData => ({
              checked: rowData.name === "Mehmet",
              value: JSON.stringify({ documentId: rowData.documentId, documentNumber: rowData.documentNumber }),
              onClick: (event , rowData) => alert(event.target.value)
          })
        }}
```

**Comment by gmumdzhiev** [comment]
@mbrn  perfect , now it works !  Just another question how can i manipulate the button to select all of them . I mean how can i assign a fucntion specifcly to this button ?

**Comment by mbrn** [comment]
Actually you can't. You may want to hide it with setting options.showSelectAllCheckbox as false

**Comment by burcusozay** [comment]
> Do you want to access value that you assing to select:
> 
> ```js-jsx
> options={{
>           selection: true,
>           selectionProps: rowData => ({
>               checked: rowData.name === "Mehmet",
>               value: rowData.surname,
>               onClick: (event , rowData) => alert(event.target.value)
>           })
>         }}
> ```

Hi, 
I am trying to decrease value of the nRowSelected when I give a condition for checkbox checked. I mean there is 10 row on the table and one of the record is Mehmet but the others are not. And I checked the select all I want to table header text is "9 row is selected".

**Comment by ahmetcengiz06** [comment]
> Hi @gmumdzhiev ,
> 
> Can you try this:
> 
> ```js
> options={{
> 
>            selection: true,
>           selectionProps: rowData => ({
>               checked: rowData.name === "Mehmet",
>               onClick: (event , rowData) => this.handleCheckboxClick(event,rowData),
>           })
>         }}
> ```
 Hi, 
After I did this onSelectionChange method doesn't select anything. My problem is I have userIds  array when component did mount and I am trying to show selected in table when table initializing. My second question is this.handleCheckboxClick(event,rowData) what should do ?
