### ISSUE TITLE
Columns Button can't select/unselect columns properly 

### ISSUE THREAD

**Issue by SooSoo-El-Shreer** [mbrn/material-table#1357]
**Describe the bug**
In Material-Table there is an option for having columns button, if it is set to true you get a column that shows a dropdown that has all the columns that are displayed in the table.
clicking any of the checkboxes makes a column disappear/appear.
My issue is that am not able to click on the checkboxes properly.
I am using the following version
"material-table": "^1.51.0"
**To Reproduce**
1. create a table with multi columns
2. in the 'options' of the table add columnsButton: true
3. click on the columns button that is provided by the table
4. try clicking on a checkbox
5. checkbox is not clickable
**Expected behavior**
the checkbox should be clickable

**Screenshots**
![checkboxes](https://user-images.githubusercontent.com/42125554/69233224-3676a800-0b95-11ea-9d8b-4cbdcdc14ddb.png)
**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome Version 78.0.3904.97

**Additional context**

**Comment by mbrn** [comment]
Hi @SooSoo-El-Shreer 

I tried with latest version and it works. Can you upgrade to latest, please?

**Comment by mbrn** [comment]
I am closing the issue. You can reopen if it requires.

**Comment by SooSoo-El-Shreer** [comment]
Thanks a lot
it worked after updating to "material-table": "^1.54.1"
