### ISSUE TITLE
Is it possible to get rid of column headers

### ISSUE THREAD

**Issue by urirahimi** [mbrn/material-table#136]
Is it possible to get rid of the column headers?
<img width="930" alt="screen shot 2018-12-31 at 7 53 34 am" src="https://user-images.githubusercontent.com/19512370/50563384-35b0fb00-0cd1-11e9-8c49-d921d8365d85.png">

**Comment by urirahimi** [comment]
<img width="905" alt="screen shot 2018-12-31 at 7 41 41 am" src="https://user-images.githubusercontent.com/19512370/50563205-9e977380-0ccf-11e9-9874-51e618dbae6b.png">
<img width="843" alt="screen shot 2018-12-31 at 7 41 28 am" src="https://user-images.githubusercontent.com/19512370/50563206-9e977380-0ccf-11e9-8e4b-31da96b5e951.png">
would like to have those two columns fill the width entirely of the container and to get rid of the empty header

**Comment by mbrn** [comment]
I can add this feature for next release. 

But i can give a workaround:

1. set `paging` and `toolbar` to false in options
2. override Header components with null

```javascript
<MaterialTable
          columns={[
            { title: 'Adı', field: 'name' },
            { title: 'Soyadı', field: 'surname' },
            { title: 'Doğum Yılı', field: 'birthYear', type: 'numeric' },
            { title: 'Doğum Yeri', field: 'birthCity', lookup: { 34: 'İstanbul', 63: 'Şanlıurfa' } }
          ]}
          data={this.state.data}
          title="Demo Title"
          components={{
            Header: props => null
          }}
          options={{
            toolbar: false,
            paging: false
          }}
        />
```

**Comment by jakeleventhal** [comment]
Just curious, why is it that there are two sets of curly braces on options. I.e. why do you have to type `options: {{ paging: false }}` instead of just `options: { paging: false }`

**Comment by mbrn** [comment]
Because first brace for react props. Second one means options is a json object. So you cant give many props with one brace. It is same with style props of component:

```javascript
<div style={{color: 'red'}}>red text</div>
```
