### ISSUE TITLE
onRowClick and button click overlapping 

### ISSUE THREAD

**Issue by sridummy** [mbrn/material-table#1362]
```
<MaterialTable 
onRowClick={() => openRightDrawer()}
actions={[
{
icon:"Check",
tooltip:"Activate",
onClick: () => activateAccount()
}
]}
components={{
Action: props => <Button onClick={() => props.action.onClick()}>Activate</Button>
}}
/>
```

button onClick and onRowClick is getting overlapping if i click a button both actions are getting triggered. is there any workaround i did not find any issue related to this.

**Comment by mbrn** [comment]
Hi @sridummy ,

You should call event.stopPropagation()

```jsx
Action: props => <Button onClick={(event) => { 
props.action.onClick(); 
event.stopPropagation();
}>Activate</Button>
```

I am closing issue. You can reopen if it requires

**Comment by sridummy** [comment]
@mbrn Awesome thanks it worked!😃
