### ISSUE TITLE
customFilterAndSearch function is not working when table is getting remote data.

### ISSUE THREAD

**Issue by maitedev** [mbrn/material-table#1363]
My table is getting remote data. I am trying to use the customFilterAndSearch property: (value, rowData), to get the value that the user enters the filter. My idea is to store that Value as a search parameter and then pass it to the function that brings the data.

    const columns = [
                {
                    field: "type",
                    title: "Type",                            
                    customFilterAndSearch: (value, rowData) => { 
                        console.log(value);      //DOES NOT show any console value             
                }
            }
    ];
        const options = {            
            filtering: true,  
            pageSize: 3,
            pageSizeOptions: [50, 200, 500],
        };

     <MaterialTable             
                        columns={columns}           
                        data={async query => {               
                        const activeObject = this.props.activeObject
                        const searchParameters = JSON.stringify(this.props.searchParameters)
                        const response = await fetchListObjects(activeObject, query.page, query.pageSize, 
         searchParameters)
                            return response
                        }}
                    options={options}

**Comment by mbrn** [comment]
Hi @maitedev ,

You can't use customFilterAndSearch with remote data. You can filter your data on your promise. Material-table calls your promise with search and filtering parameters. You can use them on server side or front side. 

I am closing this issue. You can reopen if it requires.

**Comment by swastikpal08** [comment]
hi i am facing the same issue can yu please give me the example of your solution

**Comment by maitedev** [comment]
Hi @ swastikpal08, it's my pleasure to help you. We store the filters that the user uses, with Redux. When restoring the table view, we restore the filters used previously as follows:

`// Helper funtion
export const handleDefaultFilters = (storedFilters, columnField) => {
  if (storedFilters.length > 0) {
    let defaultFilter = null;
    for (let i = 0; i < storedFilters.length; i++) {        
      if (storedFilters[i].column.field === columnField) {
        defaultFilter = storedFilters[i].value;
        break;
      }
    }
    return defaultFilter;
  } else {
    return null;
  }
};`

// Table
`...
render() {
    const storedFilters = store.getState().globalSearch.tableFiltersOriginalFormat;
    const columns = [
    {
        field: "priority_id",
        title: "Priority",
        type: "string",   
        render: (rowData) => (rowData.priority ? rowData.priority.name : null),   
        defaultFilter: handleDefaultFilters(storedFilters, "priority_id"),
      }, `
