### ISSUE TITLE
Pagination : Local data

### ISSUE THREAD

**Issue by shkumesh** [mbrn/material-table#1366]
I need to change the default no of rows per page to 10,50 and all. How can I do that?

Also how can I export full table with local data?

![image](https://user-images.githubusercontent.com/48082518/69312175-3be6f780-0c54-11ea-9c5d-95ded2772517.png)

**Comment by Justin2997** [comment]
Hi !

You can add a options `pageSizeOptions` to your Table. 

```
<MaterialTable
        ......
        options={{
          pageSizeOptions: [10, 50, data.length],
        }}
.....
```

**Comment by shkumesh** [comment]
Thanks  ...

**Comment by Justin2997** [comment]
@shkumesh If that solve your problem please close the issues. Thanks

**Comment by shkumesh** [comment]
@Justin2997  rather than the number(data.length), is there a way to get the label "All"?

**Comment by Justin2997** [comment]
I don't know. You will have to test it.

You can find complet props here : https://material-table.com/#/docs/all-props
You can check this : 
![image](https://user-images.githubusercontent.com/9096155/69453056-1c71cc80-0d31-11ea-8474-4ec01bfc0fd9.png)

**Comment by shkumesh** [comment]
Thanks ...
