### ISSUE TITLE
Currency align

### ISSUE THREAD

**Issue by X-3mal** [mbrn/material-table#1369]
**Describe the bug**
Column {...type: 'currency'}
Header cell has left align Left, cells have align Right.

**Expected behavior**
Both header and cell should have the same align

**Screenshots**
Before fix: https://clip2net.com/s/44I0rXq
After fix: https://clip2net.com/s/44I0Gme

**Solution**
m-table-header.js :96
`align: ['numeric'].indexOf(columnDef.type) !== -1 ? "right" : "left",`
Add 'currency'
`align: ['numeric', 'currency'].indexOf(columnDef.type) !== -1 ? "right" : "left",`

**Comment by rustycoslett** [comment]
+1

**Comment by lfsando** [comment]
I'm having the same issue!

**Comment by HighlApp** [comment]
+1

**Comment by Motoxpro** [comment]
Hopefully I can get around to making a PR soon, but I have been doing this.

`columns={[{cellStyle: { textAlign: 'left' }, ...}]}`

**Comment by pajohns** [comment]
Furthermore the sort icon appears on the right as opposed to the left. These should be reversed when the alignment is changed to the right.
