### ISSUE TITLE
Search clears when updating state from a free action

### ISSUE THREAD

**Issue by adam-harwood** [mbrn/material-table#1373]
**Describe the bug**
If you have a some value present in the search, and a free action that calls setState, then clicking the action will clear out the value in the search field.

**To Reproduce**
1. Enter a value into the search field.
2. Click a free action that calls setState.
3. See that the value in the search field has now been cleared.

**Expected behavior**
I would expect the existing search value to remain.

**Desktop (please complete the following information):**
 Replicated on Ubuntu 18 Firefox 70, and Mac Chrome.

**Comment by JacobSMoller** [comment]
I am also experiencing this. 

It also resets pagination.

**Comment by LAXITKUMAR** [comment]
I am also facing the same issue. I resolved it by performing the setState operation in the parent component and just passing the callback function to the component that includes the material table.

**Comment by nocoli** [comment]
Facing a similar issue where if I call setState from the onclick event in my action it unselects all selected rows

**Comment by soundcraft** [comment]
I am writing code like [#152 ,](https://github.com/mbrn/material-table/issues/152) but I have a similar problem.
grouping resets when opening dialog...

**Comment by tonypee** [comment]
Setting the selection explicitly on the rows of 'data' is a fix  (where selection is the result stored which is returned from onSelectionChange)
```

// explicitly set selection on row, since material-table is buggy
// see https://github.com/mbrn/material-table/issues/96
function fixSelectionBug<T>(data: T[], selection: T[]) {
  return data.map(row => {
    // @ts-ignore
    row.tableData = {
      // @ts-ignore
      checked: selection && selection.find(r => r.uid === row.uid) !== undefined,
    };
    return row;
  });
}
```
