### ISSUE TITLE
Emptyvalue doesn't work on undefined values

### ISSUE THREAD

**Issue by jakeleventhal** [mbrn/material-table#138]
**Describe the bug**
When a value is supposed to render the `emptyValue` (i.e. when it is null) it only works if the value is null. If the value is undefined, it doesn't work properly

**To Reproduce**
Add data that is null instead of undefined.

**Expected behavior**
The empty value should be rendered if the dat is null, undefined, or an empty string

**Comment by yildirims** [comment]
Hi, 
I will work on this issue. 
Can you paste your sample code here

**Comment by mbrn** [comment]
This is done. It will be in v1.12.0
