### ISSUE TITLE
onClick prop when 'add' is clicked

### ISSUE THREAD

**Issue by triusis92** [mbrn/material-table#1380]
Hi,

I'm using the onRowAdd prop when adding a row to the table. I was wondering if there is something like onClick prop when when clicking the 'add' button initially as in not after inputting values and clicking save but just before the options are presented to do so?

I tried using onClick but it has no effect.

Code snippet below of what I'm trying to achieve:
`editable={{
                    onClick: ()=> {console.log('clicked')}, // nothing happens
                    onRowAdd: newData =>{
                      new Promise((resolve, reject) => {
                        setTimeout(() => {
                        etc...
`

UPDATE:

After digging through open issues and visiting these links:
https://github.com/mbrn/material-table/issues/1131
https://github.com/mbrn/material-table/pull/1184
https://stackoverflow.com/questions/58144937/check-if-a-material-table-row-is-still-in-edit-mode

Could not find a solution that I initially wanted. Found a workaround thats specific to my application though. Hopefully a solution for this gets released soon.

**Comment by rommelmamedov** [comment]
Any update on this? :)

**Comment by govinddk4444** [comment]
+1

**Comment by Jsalvat** [comment]
+1

**Comment by v1v2v3vv55** [comment]
Ah crap I also want to know this one since I want the new row that is generated by Add button appear on the top.
