### ISSUE TITLE
overriding default editing behaviour

### ISSUE THREAD

**Issue by nicdim** [mbrn/material-table#1382]
Hi there.
I found your component from a link on the material-ui site and amazed at all the extra functionality you have added above and beyond the basic table.

A particular application I am working on has a need for quick entry/editing of a cell in the table.

This would need a click on the cell text to start editing, i.e show an input textbox..  User can edit the text then use enter to submit and come out of edit mode, or use up/down arrows to submit then start editing on the next or previous rows.  Much like using Excel or google sheets.

Can you give a few pointers on how I would override the default behaviour to get to this?
Many thanks!!

**Comment by FlaviusBejan** [comment]
I'm not 100% sure if this would work, but have you experimented with the column "render" ?
"render" allows you to change the component that's drawn for each cell in that column.
You could put a component that catches your double click action and changes the sub-component (or component that's linked to the double click catching component) from view to edit mode.

**Comment by MichaelJC91** [comment]
@FlaviusBejan what prop or function do I need to call to put the row into edit mode?

**Comment by danielkrich** [comment]
This is relevant to me also. For now, it looks like there's only 1 way to go into edit mode and control it... @mbrn any idea?

**Comment by FlaviusBejan** [comment]
`
...
import { dateTimeEditorRenderer } from "../../renderers/DateTimeRenderer";
...
    tableRenderDate = rowData => {
        // Here you do what you want with the data from the row, but you need to return what you have in the respective column

        let currentDate = new Date();
        let dateObj = new Date(rowData.expiration_date);
        let formattedDate = ISODateToStringDate(rowData.expiration_date);

        // Do stuff, like check if the start date has passed the current date

        return (
            <Tooltip title="Data has expired" placement="bottom" TransitionComponent={Zoom}>
                <font color="red">{formattedDate}</font>
            </Tooltip>
        );
    };

    renderTable = () => {
        const columns = [
            {
                title: "Expiration Date",
                field: "expiration_date",
                type: "datetime",
                sorting: false,
                render: rowData => this.tableRenderDate(rowData),
                editComponent: props =>
                    dateTimeEditorRenderer({ onChange: value => props.onChange(value) }, props.value)
            }];
        let editable = {
            onRowAdd: this.onRowAdd,
            onRowUpdate: this.onRowUpdate(columns),
            onRowDelete: this.onRowDelete(columns)
        };
        return <WebsterTable columns={columns} data={this.props.data} editable={editable} />;
    };
...
`
`
...
class DateTimeEditorComponent extends React.Component {
    constructor(props) {
        super(props);

        this.state = {
            dateTime: props.dateTime
        };
    }

    static propTypes = {
        dateTime: PropTypes.string,
        onChange: PropTypes.func
    };

    static defaultProps = {
        dateTime: "",
        onChange: undefined
    };

    handleChange = value => {
        let { onChange } = this.props;

        this.setState(
            {
                dateTime: value.toISOString()
            },
            () => {
                if (onChange) {
                    onChange(value.toISOString());
                }
            }
        );
    };

    render() {
        let { dateField } = this.props.classes;
        let { dateTime } = this.state;

        return (
            <MuiPickersUtilsProvider utils={MomentUtils}>
                <DateTimePicker
                    className={dateField}
                    value={dateTime}
                    onChange={this.handleChange}
                    ampm={false}
                    showTodayButton
                />
            </MuiPickersUtilsProvider>
        );
    }
}
...
const DateTimeEditor = withStyles(styles, { withTheme: true })(DateTimeEditorComponent);
export const dateTimeEditorRenderer = (editorProps, value, row, column, rowIndex, columnIndex) => {
    return <DateTimeEditor {...editorProps} dateTime={value} />;
};
`
