### ISSUE TITLE
How to override style for tablerow

### ISSUE THREAD

**Issue by TimCodes** [mbrn/material-table#139]
how do i get rid of striped styling for table rows

**Comment by mbrn** [comment]
Unfortunately it does not have a feature about row styling. But i can add it. It would be usefull feature. 

If your requirement is urgent you can override Row completely. 
https://mbrn.github.io/material-table/#/docz-examples-10-example-component-overriding

**Comment by mbrn** [comment]
Hi @TimCodes ,

I added rowStyle feature to options. You can set a style object directly or return it with a function that takes rowData as parameter. 

Example:
```javascript
<MaterialTable
          columns={[
            { title: 'Adı', field: 'name' },
            { title: 'Soyadı', field: 'surname' },
            { title: 'Doğum Yılı', field: 'birthYear', type: 'numeric' },
            { title: 'Doğum Yeri', field: 'birthCity', lookup: { 34: 'İstanbul', 63: 'Şanlıurfa' } }
          ]}
          data={this.state.data}
          title="Demo Title"
          options={{   
            //rowStyle: { backgroundColor: 'green'},
            rowStyle: rowData => {
              if(rowData.name === "Mehmet") {
                return {backgroundColor: 'yellow'};
              }
              
              return {};
            }
          }}
        />
```

This will be in version 1.12.0

**Comment by gxwheel152** [comment]
I have the opposite problem --- rows are not striped, but I would like them to be. 
Is there an options such as ... 
row: {
    '&:nth-of-type(odd)': {
      backgroundColor: theme.palette.background.default,
    },

OR

  rowStyle: rowData => ({
    backgroundColor: **rowIndex** % 2 === 0 ? "#EEE" : "#FFF",
  }),

When I use the following, it seems to reference the original order of the data instead of the order of the rows as currently displayed :   
rowStyle: rowData => ({
    backgroundColor: rowData.tableData.id % 2 === 0 ? "#EEE" : "#FFF",
  }),

**Comment by mbrn** [comment]
Hi @gxwheel152 ,

I will add stripeRows to options asap.

**Comment by rxhl** [comment]
@mbrn How do we change the hover color for the rows?

**Comment by Ainnop** [comment]
@mbrn have you been finished stripeRows option? I have been waiting for that update for sometime now

**Comment by skitsanos** [comment]
> @mbrn How do we change the hover color for the rows?

You can do hover with css directly:
```css
tbody.MuiTableBody-root > tr:hover {
    background-color: #efefef;
}
```

**Comment by skitsanos** [comment]
And as for stripes:
```css
tbody.MuiTableBody-root >:nth-of-type(2n)
{
    background-color: #fafafa;
}
```

**Comment by ppitintern** [comment]
Hi, I want to add a backgroundColor fading out effect on newly added row, how can I achieve this?

**Comment by Jhenri-silva** [comment]
I think the row could receive an visual effect when father row expand, I have no idea how to implement that effect :(

**Comment by saeidalidadi** [comment]
This `rowStyle` does not change `actions` cell

**Comment by siddharth110** [comment]
> Hi, I want to add a backgroundColor fading out effect on newly added row, how can I achieve this? I tried this, but it didn't work.
> 
> ```
> rowStyle: ()=>{
>                         let color ='#FFF';
>                         setTimeout(function(){color='#EEE'},2000)
>                         return {backgroundColor: color}
>                         
>                     }
> ```

did you get an answer.

**Comment by GigSolucoes** [comment]
How can I change the padding in rowStyle?
