### ISSUE TITLE
Can't resolve 'date-fns/addDays

### ISSUE THREAD

**Issue by Mikaila94** [mbrn/material-table#1390]
I installed material-table with npm and got this error: "Can't resolve 'date-fns/addDays" when I tried to render the MaterialTable component. From your package.json, it seems like date-fns is a dependency, so I am not sure why this error occurs. The problem is solved by installing date-fns as a dependency in my project, but I shouldn't have to do this.  Can you look into this?

 - Mac OSX,  Latest version of Chrome

**Comment by acidoxee** [comment]
The same thing happens for me.

**Comment by imjared** [comment]
I'm not entirely sure but may be related to the underlying version of date-io and an issue that happened there?

https://github.com/dmtrKovalenko/date-io/issues/232

**Comment by hutber** [comment]
Also happening for me with latest version of material table: `    "material-table": "^1.54.2",`

**Comment by hutber** [comment]
Downgrade to version 1.53.0 then it will work for now.

**Comment by DominikEngel** [comment]
Is this still valid? I cannot reproduce it anymore?
Here is a [sandbox](https://codesandbox.io/s/gracious-cannon-eb7bs?file=/src/App.js) with a clean install.

**Comment by julianmcolina** [comment]
I received the same error using version `1.66.0`
