### ISSUE TITLE
Header and Pagination style

### ISSUE THREAD

**Issue by eniro** [mbrn/material-table#1398]
![Capture](https://user-images.githubusercontent.com/32244352/69861979-2308c280-12a2-11ea-86c7-3f3a7e29005d.PNG)

I am trying to make first and  second header fixed (or sticky) using MuiThemeProvider and createMuiTheme. Until now, I've managed to make pagination fixed to bottom like this:

```
const theme = createMuiTheme({
  overrides: {
    MuiTableCell: {
      root: {
        padding: "5px",
      }
    },
    MTableHeader:{
      header: {
      top: '0px',
      zIndex: '0px',
      position: 'sticky',
      backgroundColor: '#fff',
  }
},
    MuiTablePagination: {
      toolbar: {
        position: 'fixed',
        bottom: '0px',
        left: '0px',
        backgroundColor: '#E7E7E7'
      }
    }
  }
});
```

but it seems that I can not do the same thing for MTableHeader and MuiToolbar (second header). Also, I need to add padding-top to pagination, because the last row of the body is hidden. Anh help would be much appreciated.

**Comment by mahdin75** [comment]
I'm also using this library and want to make header and pagination bar fixed. Is it possible? how?

**Comment by mahdin75** [comment]
I found a solution [here](https://github.com/mbrn/material-table/issues/780#issuecomment-512876433).
