### ISSUE TITLE
Table extends page when many columns

### ISSUE THREAD

**Issue by jakeleventhal** [mbrn/material-table#140]
**Describe the bug**
When there are many columns, the table just stretches out the page instead of being contained by width of the page.

**To Reproduce**
Create a table with many columns in a structure as such
```
<Grid container spacing={16}>
    <Grid item xs={12}>
        <SomeHeaderComponent />
    </Grid>
    <Grid item xs={12}>
        <MyTable />
    </Grid>
</Grid>
```

**Expected behavior**
The table should have room to scroll within the table instead of expanding the page.

**Screenshots**
Notice how before the table renders, my loading component renders conditionally, and everything fits within the margins of the page. Then as soon as the table renders with many columns, the page gets stretched out.
![ezgif-1-5e0aeb6dcd0c](https://user-images.githubusercontent.com/15133828/50669772-08d44080-0f7c-11e9-9455-9b2444c7d98f.gif)

**Comment by mbrn** [comment]
Hi @jakeleventhal i could not reproduce the case. Did you use a div with width style to cover MaterialTable

**Comment by jakeleventhal** [comment]
Sorry, I took a while to get to this problem but it still persists. Here is [an example](https://codesandbox.io/s/p3p5v0z7q) of the issue. This is based off the Material UI Docs' example for using a persistent drawer. As you should be able to see, I added a bunch of columns to simulate my table and the page gets extended instead of allowing scrolling from within the table.

**Comment by mbrn** [comment]
Hi @jakeleventhal ,

material-table fill content available in parent. You should have a limited width parent that cover table. Such as: 
```html
<div style={{width:500}}>..........</div> 
```

or width should be `90vw`, '100%'. So i mean you should have a parent which has a width.

**Comment by jakeleventhal** [comment]
That doesn't seem to fix the problem, try messing with code sandbox i linked in my previous comment. It works if I hardcode a fixed pixel width (i.e. 500) but not if I want to have the table fit in a dynamically sized window

**Comment by mbrn** [comment]
Yes. Because one of the parent of material-table has not limit something percent or vw. You should add 100vw or 100% to body of your html. Can you try this?

**Comment by jakeleventhal** [comment]
I figured out the problem, but it is still not resolved. in the sandbox i linked ([here it is again](https://codesandbox.io/s/p3p5v0z7q)), if i add `style={{ width: '100%' }}` to the <main> tag on line 163, it works properly. However, if I add a material-ui <Grid container> around the table, it no longer works and stretches out again. How should this be resolved?

**Comment by mbrn** [comment]
Just add the width:'100%' to content class of demo component like this:

![image](https://user-images.githubusercontent.com/7895451/51234594-365aba00-197e-11e9-90ce-4f4ce306e2ca.png)

**Comment by jakeleventhal** [comment]
That doesn't fix the problem when I add a grid container around the material table.
[Check out this new sandbox](https://codesandbox.io/s/72kww5oqj) that I made where I added the `width: 100%` and the grid container.

If you remove the container prop on line 171, it doesn't fit in the page properly.

In my app and in many others I imagine, there will be a need for having a table inside a grid.

Moreover, even after removing the container prop, when opening the drawer on the side, the table slides off the end of the page

**Comment by mbrn** [comment]
Look at this.

https://codesandbox.io/s/9oxvlzv074

**Comment by jakeleventhal** [comment]
Thanks so much!

**Comment by Shaked** [comment]
> Look at this.
> 
> https://codesandbox.io/s/9oxvlzv074

Hey @mbrn, can you attach this example again?
