### ISSUE TITLE
Third click on sorting arrow is not setting the table to custom default sort

### ISSUE THREAD

**Issue by NattoV** [mbrn/material-table#1401]
I know the table is going to have the initial state when clicking three time on an sorting arrow, but Which is that initial state? I have setted a customSort as a default and it works when the table is rendered, but I completely lose the customSort when I do the third click.  Is there a way to resolve this? or is there a way to custom the "third click" event? Thanks in advance.

**Comment by gianlucamateo** [comment]
The initial state is whichever order you passed the rows to the table in.

**Comment by NattoV** [comment]
Thank you. I solve this by sorting the data before passing it to MaterialTable component, so the initial state has the default sorting I want.
