### ISSUE TITLE
Column lookup attribute and type attribute do not play well together

### ISSUE THREAD

**Issue by macyabbey** [mbrn/material-table#1402]
**Describe the bug**
A column configured with a "lookup" prop results in a string typed value in the submit data, regardless of the "type" attribute of the column.

**To Reproduce**
Configure a column with type "numeric". Give the column a type of "numeric".
Configure the table to be editable.
Inspect the data passed to the onRowAdd function.
Notice the type of the column is not numeric, it's a string.

**Expected behavior**
The type of the field's value should match the type of the column.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OS X
 - Browser: Chrome
 - Version Version 78.0.3904.108 

**Additional context**
This should be extended to all possible types.

Example code demonstrating the issue.

```

    let dogTypeLookup = {
        0: 'Golden Retriever',
        1: 'Labrador'
    };

    return (
        <MaterialTable
          options={{
            pageSize: 15
          }}
          columns={[
            { title: 'Dog type', field: 'dog_id', lookup: dogTypeLookup, type: 'numeric', readonly: true}
          ]}
          title=""
          editable={{
            onRowAdd: (data) => {
                //When selecting Golden Retriever

                //Actual Result
                //data.dog_id === 0 is false
                //data.dog_id === "0" is true

                //Expected Result
                //data.dog_id === 0 is true
                //data.dog_id === "0" is false
                return Promise.resolve(data.dog_id === parseInt(data.dog_id));
            }
          }}
        />
    );

```

**Comment by miktap** [comment]
Valid issue for other than lookup columns as well, see #1450
