### ISSUE TITLE
Add optional horizontal double scroll

### ISSUE THREAD

**Issue by martinvergara26** [mbrn/material-table#141]
**Is your feature request related to a problem? Please describe.**
When columns and rows amounts are large, you can't see the horizontal scrollbar until you reach the bottom. This is a common behaviour, but in my case it's a requirement to also have a scrollbar at the top of the table.

**Describe the solution you'd like**
```
const options = {
            :
            doubleHorizontalScroll: true
            :
        };
```
**What I've tried**
I've tried many workarounds to achieve this, but they are awful. 

**Suggestion**
Maybe [Double Scrollbar](https://www.npmjs.com/package/react-double-scrollbar) would be useful to accomplish these.

**Comment by mbrn** [comment]
Good idea @martinvergara26 . I think use react-custom-scrollbars instead of default scrollbar

**Comment by martinvergara26** [comment]
Thanks, looking forward to this feature!

**Comment by mbrn** [comment]
This is done. It will be in v1.12.0

**Comment by hbinkle** [comment]
> This is done. It will be in v1.12.0

does not work:
https://codesandbox.io/s/material-demo-ynctq?fontsize=14&hidenavigation=1&theme=dark

**Comment by AliTariq14** [comment]
@hbinkle  i also need a scroll bar at top, and this is not working ?

**Comment by LuisPerez94** [comment]
> This is done. It will be in v1.12.0

Something is wrong, it seems it does not work. 🤕

**Comment by srinivasmangipudi** [comment]
> @hbinkle i also need a scroll bar at top, and this is not working ?

Yes scrollbar at top is essential for mouse users. otherwise everytime you have to go to the bottom to scroll the table

**Comment by emylee9** [comment]
This still does not work.

**Comment by scleecb** [comment]
This does not work.

**Comment by mithusingh32** [comment]
I can verify is till does not work.

**Comment by alexdobsom** [comment]
does it work for you now? 🧐
