### ISSUE TITLE
Autocomplete for dropdown lookup? 

### ISSUE THREAD

**Issue by michaelrios28** [mbrn/material-table#1410]
Is there a way to use the new @materialui/lab/ **autocomplete** as the dropdown/ lookup?

**Comment by mattbho** [comment]
I render it as a custom component in one of my columns. You can definitely do that

**Comment by thelazydogsback** [comment]
@mattbho Do you have an example?
I'm having an getting this working -- ignoring styling for now, I have the following issues:
- got 2nd arg to onChange when using dropdown, but only null synthetic events for keys and blur
- When I call the editComponent.props.onchange with a new value, everything rerenders and focus leaves the table completely 
- After the onchange, the value has be updated internally, but no longer appears in the dropdown

My component looks like:

```
const DropdownEditor = (label:string, data:string[]) =>
                            (props: EditComponentProps<CatalogItemModel>) => {
    return ( 
        <Autocomplete 
            options={data}
            onChange={(_,newVal)=>props.onChange(newVal)}
            // onBlur={}
            renderInput={params => (
                <TextField 
                    {...params} label={label}  />
            )}/>
    )
}

```
and added:

`       ...     editComponent: DropdownEditor("label", data) `

**Comment by mattbho** [comment]
`{
      title: "Agent",
      field: "previous_agent",
      emptyValue: "New",
      cellStyle: {
        width: "300px"
      },
      editComponent: props => (
        <Autocomplete
          id="Agent Emails"
          size="small"
          options={workerEmails}
          getOptionLabel={option => option.email}
          renderInput={params => {
            return (
              <TextField
                {...params}
                variant="outlined"
                label={props.value}
                fullWidth
              />
            );
          }}
          onChange={e => props.onChange(e.target.innerText)}
        />
      )
    },`

**Comment by mattbho** [comment]
```{
      title: "Agent",
      field: "previous_agent",
      emptyValue: "New",
      cellStyle: {
        width: "300px"
      },
      editComponent: props => (
        <Autocomplete
          id="Agent Emails"
          size="small"
          options={workerEmails}
          getOptionLabel={option => option.email}
          renderInput={params => {
            return (
              <TextField
                {...params}
                variant="outlined"
                label={props.value}
                fullWidth
              />
            );
          }}
          onChange={e => props.onChange(e.target.innerText)}
        />
      )
    }```

**Comment by maurosbu** [comment]
@mbrn is it possible to replace Select element with Autocomplete one in lookup filter? Clearing selection in Select component is tedious. Thx.
