### ISSUE TITLE
How can get both text and value of lookup column?

### ISSUE THREAD

**Issue by tolgaaykurt** [mbrn/material-table#1412]
Hi,

How can i get both text and value of lookup column? Lookup gets only value of selected item. For example; 

{ 0:Istanbul, 2:Ankara, 3:Izmir }

If i select "Istanbul" on lookup then i get 0 value. But i need to both 0 and Istanbul.

Thanks.

**Comment by acsakshay** [comment]
Hi, I think this is not a bug but a query. I would recommend to use chat on Gitter or stackoverflow with tag [material-table] and any additional relevant tags :)

**Comment by tolgaaykurt** [comment]
Hi acsakshay,

Thanks for your care. This is not a bug. This is an question. I have send message to lobby after your recommended. I hope find a solution.

**Comment by acsakshay** [comment]
> Hi acsakshay,
> 
> Thanks for your care. This is not a bug. This is an question. I have send message to lobby after your recommended. I hope find a solution.

No Worries. The reason why I mentioned is that there were no labels and plus it just puts a toll on the guys. 

Fingers crossed, you find a solution there. Also, I would recommend posting it on StackOverflow with a small script that you are working. Usually it helps in providing you a faster resolution.
