### ISSUE TITLE
Add, update and delete methods in examples, not working

### ISSUE THREAD

**Issue by amarch** [mbrn/material-table#1413]
HI. I understand this issue has already been reported and relates to version update. Has it been fixed? If not, are there any workarounds or new methods to CRUD rows? Many thanks.

**Comment by guyla** [comment]
I just opened an issue about it

change `const data = this.state.data;` to `const data = Array.from(this.state.data);` that will do the trick. 

Guy

**Comment by amarch** [comment]
Worked like a charm. Thanks, Guy!

**Comment by derryberni** [comment]
wow awesome, thankyou is worked like charm.

@guyla can you explain what happend ? why we can't use
`const data = this.state.data;`

Thanks

**Comment by AugustoCalaca** [comment]
this occurs because of the `indexOf` isn't working as expected
a better solution is to use `oldData.tableData.id` to get the index of the row  

the docs are being updated

**Comment by techyrajeev** [comment]
Examples provided are incorrect

**Comment by phannack** [comment]
> I just opened an issue about it #1417
> 
> In the examples, change `const data = this.state.data;` to `const data = Array.from(this.state.data);` that will do the trick.
> 
> Guy

great
