### ISSUE TITLE
Failed prop type: Invalid prop `children` supplied to `ForwardRef(TableCell)`, expected a ReactNode.

### ISSUE THREAD

**Issue by OnkelTem** [mbrn/material-table#1414]
I started getting this warning and cannot nail down the rason.
I cannot provide you with an example because it's a complex component and I don't really know what raises the warning.
But here is the full error message cut at the point where MaterialTable starts. I really hope it can tell you something, because I myself don't have any idea:
```
index.js:1375 Warning: Failed prop type: Invalid prop `children` supplied to `ForwardRef(TableCell)`, expected a ReactNode.
    in ForwardRef(TableCell) (created by WithStyles(ForwardRef(TableCell)))
    in WithStyles(ForwardRef(TableCell)) (created by MTableCell)
    in MTableCell (created by MTableBodyRow)
    in tr (created by ForwardRef(TableRow))
    in ForwardRef(TableRow) (created by WithStyles(ForwardRef(TableRow)))
    in WithStyles(ForwardRef(TableRow)) (created by MTableBodyRow)
    in MTableBodyRow (created by MTableBody)
    in tbody (created by ForwardRef(TableBody))
    in ForwardRef(TableBody) (created by WithStyles(ForwardRef(TableBody)))
    in WithStyles(ForwardRef(TableBody)) (created by MTableBody)
    in MTableBody (created by Droppable)
    in table (created by ForwardRef(Table))
    in ForwardRef(Table) (created by WithStyles(ForwardRef(Table)))
    in WithStyles(ForwardRef(Table)) (created by Droppable)
    in div (created by Droppable)
    in div (created by Droppable)
    in Droppable (created by ConnectFunction)
    in ConnectFunction
    in ConnectFunction (created by MaterialTable)
    in div (created by ScrollBar)
    in ScrollBar (created by MaterialTable)
    in div (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (created by Container)
    in Container (created by MaterialTable)
    in Provider (created by App)
    in App (created by ErrorBoundary)
    in ErrorBoundary (created by DragDropContext)
    in DragDropContext (created by MaterialTable)
    in MaterialTable
   ...
```

P.S. There is [another issue](https://github.com/mbrn/material-table/issues/1074) with the same title in the issue queue, but it doesn't have any relation to my case (I don't use any "id" fields)

**Comment by codinglabsdev** [comment]
Hey, take a look at my comment in #1074 

Maybe your data has nested objects too.

**Comment by OnkelTem** [comment]
Sorry for not updating the issue in time.

_And here is why one should always provide a modicum of information about their specific case: after a while they don't remember the circumstances which has been raising the problem._ Just like in my case.

I believe I had exacly that problem as you described in the issue @codinglabsdev - an object where scalar was expected.

**Comment by raulrobi2018** [comment]
Hi OnkeTem!! I'm having the same problem. Can you tell me how you solved it?

**Comment by JoyMbugua** [comment]
I was having this problem because i was passing a boolean value direct from the backend. using toString() solved it for me

**Comment by indofiz** [comment]
> I was having this problem because i was passing a boolean value direct from the backend. using toString() solved it for me

Yes, thanks,

**Comment by alejandrogih** [comment]
thanks @w-mbugua it really worked for me
