### ISSUE TITLE
How to align data in a column?

### ISSUE THREAD

**Issue by OnkelTem** [mbrn/material-table#1415]
I want to align the contents of a column right, but I don't want to make this column "numeric" because it's not.
I tried obvious "align" property with "right" value, but it didn't work.

**Comment by hrafaelveloso** [comment]
In your columns definition, add the following:
```js
{
    title: <your column title>,
    field: <your column field>,
    cellStyle: {
        textAlign: "right"
    }
  }
```

**Comment by nicholaspollock** [comment]
> In your columns definition, add the following:
> 
> ```js
> {
>     title: <your column title>,
>     field: <your column field>,
>     cellStyle: {
>         textAlign: "right"
>     }
>   }
> ```

Im not able to fix the problem by using this.

**Comment by hrafaelveloso** [comment]
Can you provide some codesandbox with your issue?

**Comment by npollock-catalyte** [comment]
> Can you provide some codesandbox with your issue?
I fixxed it. As long as my edit and add form handle the currency I can just display it as a normal field with a custom render of a dollar sign

**Comment by sanojsilva** [comment]
> In your columns definition, add the following:
> 
> ```js
> {
>     title: <your column title>,
>     field: <your column field>,
>     cellStyle: {
>         textAlign: "right"
>     }
>   }
> ```

this works

**Comment by jackHedaya** [comment]
How can this be done on the action column?

**Comment by Domino987** [comment]
Check out the my merged PR: #1974

**Comment by chathuranga95** [comment]
In your columns definition, add the following:
```
{
    title: <your column title>,
    field: <your column field>,
    align: "right"
}
```

This will align column header and column data to right

**Comment by gurbraj** [comment]
hey @chathuranga95, thanks but that isn't working for me... 

any other ideas?

`"@material-table/core": "^4.3.0",`
