### ISSUE TITLE
Frozen header row

### ISSUE THREAD

**Issue by jakeleventhal** [mbrn/material-table#1418]
**Is your feature request related to a problem? Please describe.**
When scrolling down on a long table, the header is sometimes important to still see.

**Describe the solution you'd like**
There should be a way to freeze the header row at the top so that it is always visible in the table.

**Comment by jakeleventhal** [comment]
This solution should also apply to an arbitrary column. Here's an example of the “first column” freezing when you scroll to the side:
https://codesandbox.io/s/n766xny1o0

**Comment by jakeleventhal** [comment]
not stale

**Comment by jakeleventhal** [comment]
not stale

**Comment by jakeleventhal** [comment]
not stale

**Comment by lporteri2p** [comment]
@jakeleventhal the solution [here](https://github.com/mbrn/material-table/issues/709#issuecomment-512876617) works well.  Good luck!

**Comment by jakeleventhal** [comment]
not stale
