### ISSUE TITLE
hello guys I need summary row 

### ISSUE THREAD

**Issue by zilkenberg22** [mbrn/material-table#1419]
![summary_row](https://user-images.githubusercontent.com/33345651/70216731-1a6d2c00-177b-11ea-8028-7f636b0bfa77.png)
how to like total row 
I cant do it 
Help me Thanks

**Comment by zilkenberg22** [comment]
up

**Comment by tylercaceres** [comment]
#752 try looking at my comment and seeing if that works for you.

**Comment by zilkenberg22** [comment]
hi can u give me full example

**Comment by pabichw** [comment]
Well, might not be the best solution but I made my Total row by overriding `Pagination` component. I'm not going to need paging anyways and that rows stays nicely on the bottom so that's nice

**Comment by codenamethanos** [comment]
If someone needs a simple datatable with summary footer row this should work - https://github.com/codenamethanos/materialui-table 
Just 500 lines of code

**Comment by thedmeyer** [comment]
Any way to do with and keep the content of the summary row aligned with the columns?

**Comment by johnsintal** [comment]
Has anyone been able to successfully show a summary row like in the original poster's screenshot? Any help would be appreciated!

**Comment by janderson215** [comment]
> Has anyone been able to successfully show a summary row like in the original poster's screenshot? Any help would be appreciated!

This is what I'm doing it it's working pretty well. Sorting ignores the second MTableBody object :)
				`components={{
					Body: (props) => (
						<>
							<MTableBody {...props} />
							<MTableBody
								{...props}
								renderData={claimTypeHistory
									.filter((claimType) =>
										['TOTAL', 'TOTFAC', 'TOTPRO'].includes(claimType.claim_type)
									)
									.map((row, i) => ({ ...row, tableData: { id: i } }))}
								options={{
									rowStyle: (_, i) =>
										i === 0
											? { borderTop: 3, borderTopStyle: 'solid', paddingLeft: 4, paddingRight: 4 }
											: i % 2 === 0
											? { paddingLeft: 4, paddingRight: 4 }
											: { backgroundColor: colors.grey[200], paddingLeft: 4, paddingRight: 4 },
								}}
							/>
						</>
					),
				}}`

**Comment by elias-thok** [comment]
Thanks so much, this is exactly what I was looking for!
