### ISSUE TITLE
Not able to reduce height of rows below 53px

### ISSUE THREAD

**Issue by mrafivyr** [mbrn/material-table#1420]
Tried with cellStyle: {height:30} option to reduce height of all rows, but its not working when the value is less than 53px.

In my case am trying to have height as 30px, but its considering default value of 53px. Its working absolutely fine when height value is greater than 53px.

**Comment by janderson215** [comment]
@mrafivyr Try adjusting paddingTop and paddingBottom

**Comment by mrafivyr** [comment]
@janderson215 Thanks a lot for your inputs. It worked with padding option, i have updated below details in options section of Material table.

cellStyle: {height:30, paddingTop:0, paddingBottom:0}
