### ISSUE TITLE
How to add a callback function to the button of adding a row? 

### ISSUE THREAD

**Issue by kkateli** [mbrn/material-table#1427]
I used Material Table OnRowAdd to add new rows. I wonder how to create my own callback function so that I can control what to do after the plus button is clicked
<img width="51" alt="Screen Shot 2019-12-09 at 4 24 49 PM" src="https://user-images.githubusercontent.com/39331184/70404965-88c62d00-1aa0-11ea-99bb-0769cc0ce982.png">

**Comment by Solijons** [comment]
Were you able to solve this?
