### ISSUE TITLE
warnings in console when simply using the table

### ISSUE THREAD

**Issue by hbinkle** [mbrn/material-table#1430]
there are warning in the console when simply using the table.
```
Failed prop type: Invalid prop `color` of value `inherit` supplied to `ForwardRef(TextField)`
Failed prop type: Invalid prop `color` of value `inherit` supplied to `ForwardRef(FormControl)`
```

![image](https://user-images.githubusercontent.com/51942180/70441916-8f9b7280-1a95-11ea-8a92-021698058639.png)

https://codesandbox.io/s/material-demo-yvqym?fontsize=14&hidenavigation=1&theme=dark

**Comment by KerimG** [comment]
Just encountered the same issue.

**Comment by hutber** [comment]
I'm also having the same problems with version `1.53.0`
