### ISSUE TITLE
How can I have inline action with selection props to true ? 

### ISSUE THREAD

**Issue by Eplumecocq** [mbrn/material-table#1432]
Hi, 

I was wondering how to achieve inline action when the  `selection` props is set to `true`.

Actually, if `selection` props is set to `false`, any actions will be render inside the row.

I would like to be able to have some inline actions AND actions inside the toolbar triggered by selection.

Any help would be appreciated

**Comment by HongYu-Cupertino** [comment]
I encountered the same issue: i can't have both actions and selection feature at the same time. You can reproduce the issue by adding below in your simple action sample:
       options={{
          actionsColumnIndex: 1,
          selection: true
        }}

**Comment by Sqrtme** [comment]
https://github.com/mbrn/material-table/issues/1448
possible solution here

**Comment by Eplumecocq** [comment]
@Sqrtme Thanks a lot it works !
