### ISSUE TITLE
Grouping and Tree Data don't work together. 

### ISSUE THREAD

**Issue by sanichka96** [mbrn/material-table#1434]
Hi everyone!
I'm using material-table for my project, because it has two very important features wich I need: _Tree Data_ and _Grouping_.
When I use those features intependently of each other, each of them does work. But when I use noth of them at the same time, I'm facing some issues. 

Image 1: Tree Data works OK.
![tree](https://user-images.githubusercontent.com/18401192/70507451-ae991380-1b2c-11ea-8b48-db10bef16a26.PNG)

Image 2: After column 'Owner'  header was dragged - no owners' info is displayed: 
![group1](https://user-images.githubusercontent.com/18401192/70507675-223b2080-1b2d-11ea-9f71-f7eb5fb73132.PNG)

Image 3: After expanding groupped rows error appears: 
![log](https://user-images.githubusercontent.com/18401192/70507783-629a9e80-1b2d-11ea-813b-8798ad386c79.PNG)

Image 4: Error in file m-table-group-row.js:
![log1](https://user-images.githubusercontent.com/18401192/70508388-a641d800-1b2e-11ea-9aed-18cbb175b0be.PNG)

`this.props.groupData` is undefined.

**Expected behavior**: Grouping and Tree Data work together without errors. 

material-table version: **1.54.1**.

**Comment by Camsteack** [comment]
Any update on this issue ?

**Comment by ParticularPhil** [comment]
I'm having this issue as well. I'd like to use both grouping and trees and encountered exactly the issue @sanichka96 described.

**Comment by arjunvnd** [comment]
I'm also having the same issues when trying to use grouping and tree data.

**Comment by cbaker** [comment]
I'm kind of confused on how grouping & tree data would even work together?

**Comment by aescobar95** [comment]
Hi, @sanichka96, I have the same problem. Did you find any solution?

**Comment by sanichka96** [comment]
@aescobar95, no, I don't have such a requirement at work anymore, so I stopped trying to solve the problem. :(
