### ISSUE TITLE
Search is not working at Remote data code

### ISSUE THREAD

**Issue by PATTANPARVIN** [mbrn/material-table#1440]
Search is not working while calling rest call dynamically

**Comment by cbschuld** [comment]
I have search working fine with a dynamic REST (will GraphQL, but still remote) can you share a code snippet?

**Comment by szkiecin** [comment]
@cbschuld are you using onSearchChange with material-table 1.54.2 ?

**Comment by tuliocll** [comment]
i have the same issue, the documentation example not working too.
https://material-table.com/#/docs/features/remote-data

**Comment by gaurav-agarwal27** [comment]
@cbschuld can you share your implementation of remote search ?

**Comment by dattatrey93** [comment]
> i have the same issue, the documentation example not working too.
> https://material-table.com/#/docs/features/remote-data

facing same issue . have you got solution?

**Comment by therohitjha** [comment]
> Search is not working while calling rest call dynamically

simply first save your api data into variable instead of fetching directly from an api into MaterialTable data.
then add that variable data into materialTable data.
<img width="301" alt="Capture" src="https://user-images.githubusercontent.com/45750703/72609293-87fba300-394a-11ea-835b-65fe75936151.PNG">

**Comment by pjshu** [comment]
hello,I solve this problem use
`js
  function handlePagingQuery(query) {
    if(query.search){
      return new Promise(resolve => {
        axios.get(`${api}?search=${query.search}`).then(res => {
          resolve(res)
        })
      })
    }else{
       // fetch your initial data
    }
  
  }
  return (
    <MaterialTable
      data={handlePagingQuery}
    />
  );
`
hope this will help you

**Comment by e-hop** [comment]
i'm currently trying to achieve this but it didn't work for me. This is my code

```
      <MaterialTable        
        title="Refresh Data Preview"
        tableRef={tableRef}
        columns={[
          { title: 'Id', field: 'id' },
          { title: 'First Name', field: 'object_id' },
          { title: 'Last Name', field: 'last_name' },
        ]}
        data={query =>
          new Promise((resolve, reject) => {

            if(query.search){
                console.log(query.search)

                fetch( `${props.route}?filter=${query.search}` )
                .then(response => response.json())
                .then(result => {
                  console.log(result)
                  resolve({
                    data: result.data,
                    page: result.page - 1,
                    totalCount: result.total,
                  })
                })

              }else{

                let url = props.route
                url += '?per_page=' + query.pageSize
                url += '&page=' + (query.page + 1)
                fetch(url)
                  .then(response => response.json())
                  .then(result => {
                    console.log(result)
                    resolve({
                      data: result.data,
                      page: result.page - 1,
                      totalCount: result.total,
                    })
                  })
              }
```

            })
        }
        actions={[
          {
            icon: 'refresh',
            tooltip: 'Refresh Data',
            isFreeAction: true,
            onClick: () => tableRef.current && tableRef.current.onQueryChange(),
          }
        ]}
        options={{
            search: true
          }}
      />

**Comment by AravindTReddy** [comment]
> I have search working fine with a dynamic REST (actually GraphQL, but still remote) can you share a code snippet?

https://material-table.com/#/docs/features/remote-data This is the example from documentation where search doesn't work. 
how did you overcome the issue ? Thanks
