### ISSUE TITLE
Ability to fullWidth editable cell FormControl

### ISSUE THREAD

**Issue by zacheryph** [mbrn/material-table#1443]
**Is your feature request related to a problem? Please describe.**
I commonly add style `{whiteSpace: 'nowrap', width: '1%'}` to columns i want to shrink. This problem probably does not relate to that but I notice when a table is editable, text fields in wider columns (not shrunk) will not extend to fill the field.

**Describe the solution you'd like**
I know there is `editComponent` though I was wondering if there is or could be an easier way to update the FormControl props, or allow `fullWidth` to be a default possibly.

**Describe alternatives you've considered**
`editComponent` is the only current solution I am aware of

**Additional context**
![Screen Shot 2019-12-11 at 3 54 12 PM](https://user-images.githubusercontent.com/476/70663728-8f82aa80-1c2e-11ea-9e1d-77e6327466af.png)

**Comment by jvink** [comment]
Same issue here.
