### ISSUE TITLE
Add new row in editable mode when clicking on custom button or icon

### ISSUE THREAD

**Issue by anuj47billion** [mbrn/material-table#1445]
Hello All,
I need to add new row editable mode on click the custom icon which was created by actions props like

actions={[
                   {
                       icon: () => <FileCopyIcon />,
                       tooltip: 'Copy',
                       onClick: (event, rowData) => {
                            //Functionality
                       }
                   }
 ]}

IS there any possibity to do this?

**Comment by MeghaBambra** [comment]
I tried to achieve this by doing the following:

```
actions={[
                    {
                      icon: tableIcons.FileCopy,
                      tooltip: 'Copy',
                      onClick: (event, rowData) => {
                        tableRef.current.props.editable.onRowAdd(rowData)
                      },
                    },
                  ]}
```

However, ran into error of `Uncaught TypeError: Cannot read property 'editing' of undefined`

**Comment by thelazydogsback** [comment]
Running into the same question -- need to use the standard mat-ui floating add icon. (The circle with the plus sign.)
@MeghaBambra Did you figure this out?

**Comment by MeghaBambra** [comment]
So I got this working with the following: 
`
actions={[
                    {
                      icon: tableIcons.FileCopy,
                      tooltip: 'Copy',
                      onClick: (event, rowData) => {
                        const newData = {...rowData, uuid: uuid() }
                        tableRef.current.props.editable.onRowAdd(newData)
                      },
                    },
                  ]}
`
You cannot edit `rowData` as it was cause an error - guessing because its modifying existing data structure table is bound to. So i created a copy of it.

**Comment by didopop3** [comment]
anyupdates on this one?
