### ISSUE TITLE
Editable table returns only strings

### ISSUE THREAD

**Issue by miktap** [mbrn/material-table#1450]
**Describe the bug**
A column configured as type `numeric` is of type `string` in the `onRowAdd` function. 

**To Reproduce**
Give the column a type of `numeric`.
Configure the table to be editable.
Inspect the data passed to the `onRowAdd` function.
Notice the type of the column is not numeric, it's a string.

**Expected behavior**
The type of the field should be a `number`.

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser: Chrome
 - Version: 78.0.3904.108

**Additional context**
Example code:

```typescript
import React from 'react';
import MaterialTable, { Column } from 'material-table';

interface Row {
  age: number;
}

interface TableState {
  columns: Array<Column<Row>>;
  data: Row[];
}

export default function Demo() {
  const [state, setState] = React.useState<TableState>({
    columns: [
      { title: 'Age', field: 'age', type: 'numeric' },
    ],
    data: [
      { age: 63 },
    ]
  });

  return (
    <MaterialTable
      title='Editable Example'
      columns={state.columns}
      data={state.data}
      editable={{
        onRowAdd: newData =>
          new Promise(resolve => {
            console.log(typeof(newData.age)); // prints 'string'
            resolve();
          }),
      }}
    />
  );
}
```

**Comment by xaroth8088** [comment]
I'd request this be re-opened, as it's definitely a surprising result.

**Comment by sudaraka94** [comment]
I am also facing the same issue. The only solution is to convert the value while handling the result and it is hacky :/

**Comment by Domino987** [comment]
This is due to how react handles inputs. All inputs are string except if the type is number. The problem with that is, that you always have a number in the field, so an empty field is not possible. But this is a restriction by choice to have empty numeric field.
What would you expect to be returned for numeric empty fields? undefined, '', 0, maybe null?
Maybe we can think of a better approach.
