### ISSUE TITLE
Grouping by link

### ISSUE THREAD

**Issue by xStorm111** [mbrn/material-table#1455]
Hello, i'm trying to render a column as a "<|Link>" as you can see on the follow image:
![image](https://user-images.githubusercontent.com/22938156/71021248-d886a300-20f5-11ea-8e20-89ac70dd9c0d.png)
 but the option grouping is expecting a string.
![image](https://user-images.githubusercontent.com/22938156/71021300-f05e2700-20f5-11ea-87bc-bb2c93010716.png)

I'm using the following code:
![image](https://user-images.githubusercontent.com/22938156/71021402-31563b80-20f6-11ea-9c53-6fb36617c430.png)

Is there any way to fix this?

**Comment by anggar85** [comment]
Hi, I use you example to fix my problem.
I think you just need to remve "BrowserRouter"
![image](https://user-images.githubusercontent.com/20346779/75383989-38d25780-5892-11ea-8b0c-bfb23c06e73f.png)

**Comment by xStorm111** [comment]
Hello @anggar85 , first of all thanks for the reply. Infortunately i allready tried that and i had the same result..
i adapt like you said and still doesn't fix:
![image](https://user-images.githubusercontent.com/22938156/75444140-c37e8980-595a-11ea-9692-0a68211cd2df.png)

Preview:
![image](https://user-images.githubusercontent.com/22938156/75444263-07718e80-595b-11ea-8913-d7d1621a31ac.png)
