### ISSUE TITLE
Save Filters

### ISSUE THREAD

**Issue by lynnhardy** [mbrn/material-table#1458]
When I filter the columns, how can I save the filter? I don't want to have to filter again when I click into a different screen and then come back to my table.

**Comment by keif** [comment]
I did a simple tweak using storage. It's hacky AF but it worked for my needs until I can get around to adding it to the component itself. Something similar may help you out.

In my case, this was around the groupings, so, I created a "custom component" (just something to capture and update the data being passed in):
```
          Groupbar: props => {
            setGroupedByColumns(props)
            return <MTableGroupbar {...props} />
          }
```
This function did the magic:
```
  const setGroupedByColumns = ({ groupColumns }) => {
    //  save the passed in "grouped by" data
    const groupedByColumns = groupColumns.reduce((acc, curr) => [...acc, curr.field], [])

    if (!_.isEqual(tableSelections, groupedByColumns)) {
      dispatch({
        // generates "GROUPINGS_SELECTED"
        type: GROUPINGS_SELECTED,
        payload: groupedByColumns
      })
    }
  }
```

Again… hacky, but it worked for my current needs, and you may be able to figure out something similar.

**Comment by PierrickI3** [comment]
Hi @keif ,

Sorry for waking up an old issue.

trying to implement your option on my side. I save the grouped columns in local storage but when I refresh the page, I can see the group filter in the group bar however the grouping is not applied. 

Are you calling a specific Material Table function to make it aware of the group being applied?
