### ISSUE TITLE
Edit does not update table

### ISSUE THREAD

**Issue by gabbottron** [mbrn/material-table#1460]
**Describe the bug**
Edit does not actually show changes in the table. It doesn't even work on the example page: https://material-table.com/#/docs/features/editable

Attempt to edit a field and hit the check button and the table just reverts to original state. The behavior is the same in my example app despite the state changing.

**To Reproduce**
1. Go to https://material-table.com/#/docs/features/editable
2. Edit one of the fields
3. Hit check box
4. Observe table does not update.

**Expected behavior**
Table should update based on new data.

Is anyone else seeing this?

**Comment by guyla** [comment]
https://github.com/mbrn/material-table/issues/1417

**Comment by rizabek-mukanov** [comment]
> **Describe the bug**
> Edit does not actually show changes in the table. It doesn't even work on the example page: https://material-table.com/#/docs/features/editable
> 
> Attempt to edit a field and hit the check button and the table just reverts to original state. The behavior is the same in my example app despite the state changing.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to https://material-table.com/#/docs/features/editable
> 2. Edit one of the fields
> 3. Hit check box
> 4. Observe table does not update.
> 
> **Expected behavior**
> Table should update based on new data.
> 
> Is anyone else seeing this?

yeah, it doesn't work. 
Array.from(data) didn't work as well for me.

**Comment by BhushanDangore** [comment]
> **Describe the bug**
> Edit does not actually show changes in the table. It doesn't even work on the example page: https://material-table.com/#/docs/features/editable
> 
> Attempt to edit a field and hit the check button and the table just reverts to original state. The behavior is the same in my example app despite the state changing.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to https://material-table.com/#/docs/features/editable
> 2. Edit one of the fields
> 3. Hit check box
> 4. Observe table does not update.
> 
> **Expected behavior**
> Table should update based on new data.
> 
> Is anyone else seeing this?

It works with functional components with hook but it is not working with class based component.

**Comment by tengemakers** [comment]
> > **Describe the bug**
> > Edit does not actually show changes in the table. It doesn't even work on the example page: https://material-table.com/#/docs/features/editable
> > Attempt to edit a field and hit the check button and the table just reverts to original state. The behavior is the same in my example app despite the state changing.
> > **To Reproduce**
> > Steps to reproduce the behavior:
> > 
> > 1. Go to https://material-table.com/#/docs/features/editable
> > 2. Edit one of the fields
> > 3. Hit check box
> > 4. Observe table does not update.
> > 
> > **Expected behavior**
> > Table should update based on new data.
> > Is anyone else seeing this?
> 
> It works with functional components with hook but it is not working with class based component.

+ i can confirm this. 
@gabbottron, hope this will be hopeful.
I set my data like: `data={Array.from(tableData)}`
and onRowUpdate
`onRowUpdate: (newData, oldData) =>
              new Promise(resolve => {
                setTimeout(() => {
                  resolve();
                  const { sampleID, ...rest } = newData;
                  const data = Array.from(tableData);
                  data[data.indexOf(oldData)] = newData;
                  setTableData(() => data);
                  resolve();
                }, 700);
              }),`

**Comment by AugustoCalaca** [comment]
https://github.com/mbrn/material-table/issues/1413#issuecomment-572858590
