### ISSUE TITLE
Is it possible to hide instead of disable buttons with isEditable?

### ISSUE THREAD

**Issue by ryanjohndunne** [mbrn/material-table#1462]
Looking to hide the buttons when they aren't editable as they'll be replaced with action buttons.

**Comment by pain2theworld** [comment]
You can replace 'disabled' with 'hidden' or add it by modifying '/material-table/dist/material-table.js' onRowUpdate and onRowDelete.

**disabled: calculatedProps.editable.isEditable && !calculatedProps.editable.isEditable(rowData)**
