### ISSUE TITLE
How to make rows with two different background colors.

### ISSUE THREAD

**Issue by muqsithck** [mbrn/material-table#1463]
I need to change the background color of the table rows, with all even-numbered rows with one color and odd-numbered with another color. how to make it. ?

  options={{
                rowStyle: {
                    backgroundColor:  '#EEE',
                  }
            }}

**Comment by mattjford** [comment]
options={{
            rowStyle: rowData => ({
                backgroundColor: (rowData.tableData.id % 2) ? '#EEE' : '#FFF'
            })
          }}

**Comment by muqsithck** [comment]
@mattjford 

options={{
rowStyle: rowData => ({
backgroundColor: (rowData.tableData.id % 2) ? '#EEE' : '#FFF'
})
}}

It's working. But when we try to sort the table,  it goes wrong. Because of using tableData.id ,  Is there any option to get the row index value.?
