### ISSUE TITLE
customSort is not working

### ISSUE THREAD

**Issue by xStorm111** [mbrn/material-table#1465]
I receive a column from api that contains Dates + _number (example: "20/12/2019_1" as a string). The sort function will group counting data as a string and not as a Date column. Which means i need to do a customSort.
So i created a function to transform that string into a Date object, but when i return the value nothing happens...

columns:
![image](https://user-images.githubusercontent.com/22938156/71271089-0ca6d180-234b-11ea-9040-7afbac87722e.png)
my utils.js:
![image](https://user-images.githubusercontent.com/22938156/71271384-3829bc00-234b-11ea-8a1f-9f4fc68e0591.png)

I know my function is working correctly but i can't put customSort working...

**Comment by Domino987** [comment]
Since this is not an issue or bug, you should probably ask this on SO. Link me when you did and I will look into it.

**Comment by xStorm111** [comment]
Hello @Domino987 , first of all thanks for the reply.
My function is working as expected but somehow it's not working on customSort...

I did what you said, i created a SO post, i will leave the link below:
https://stackoverflow.com/questions/59643681/material-table-customsort-doesnt-work-with-dates
