### ISSUE TITLE
When using selction column filter is not applied

### ISSUE THREAD

**Issue by kfirshahar** [mbrn/material-table#1467]
**Describe the bug**
When defining a Material table with row selection and column filter, the filtering disappears when selecting rows, i.e. the rows which are displayed are no longer filtered by the column search field.
The problem does not happen when using global search field.

**Reproduce**
1. Define a Material table is it appears in the example in https://material-table.com/#/docs/features/filtering
2. Select a value for filtering on the column 'Name' for example 'meh'
3. Select a specific row (this example does not suport selection of rows so it needs to be enabled too)

**Expected behavior**
Only data records which are matching the filter should be seen in the table

**Actual behavior**
All data records are seen in the table, also those who do not match the filter

**Desktop (please complete the following information):**
Version 79.0.3945.88 (Official Build) (64-bit)
windows 7

**Comment by Abekonge** [comment]
I can confirm this behaviour

**Comment by VidushaZ** [comment]
Still no fix for this?

**Comment by hemanthvrm** [comment]
I am unable to find native options to persist filters after row selection...But found a workaround to achieve this --> my sandbox
[https://codesandbox.io/s/material-table-filter-selection-71ed5?file=/src/App.js](https://codesandbox.io/s/material-table-filter-selection-71ed5?file=/src/App.js)


```
const columns = [
  { title: "Name", field: "name", checked: true },
  { title: "Surname", field: "surname" },
  { title: "Birth Year", field: "birthYear", type: "numeric" },
  {
    title: "Birth Place",
    field: "birthCity",
    lookup: { 34: "İstanbul", 63: "Şanlıurfa" }
  }
];

const data = [
  {
    name: "Mehmet",
    surname: "Baran",
    birthYear: 1987,
    birthCity: 63
  },
  {
    name: "Zerya Betül",
    surname: "Baran",
    birthYear: 2017,
    birthCity: 34
  },
  {
    name: "Zerya Betül 2",
    surname: "Baran",
    birthYear: 2017,
    birthCity: 34
  },
  {
    name: "Zerya Betül 3",
    surname: "Baran",
    birthYear: 2017,
    birthCity: 63
  }
];

export const App = () => {
  const [selectedItems, setSelectedItems] = useState({
    initialLoad: true,
    rows: [],
    cloumns: []
  });
  return (
    <div className="App">
      <MaterialTable
        title="Basic Selection Preview"
        columns={selectedItems.initialLoad ? columns : selectedItems.columns}
        data={data}
        options={{
          selection: true,
          filtering: true
        }}
        onSelectionChange={(rows) =>
          setSelectedItems({
            ...selectedItems,
            data: rows,
            initialLoad: false,
            columns: selectedItems.initialLoad ? columns : selectedItems.columns
          })
        }
      />
    </div>
  );
}; 
```
