### ISSUE TITLE
Add ability to inline edit on rows without having to click edit button

### ISSUE THREAD

**Issue by jakeleventhal** [mbrn/material-table#1471]
**Is your feature request related to a problem? Please describe.**
It is difficult and annoying sometimes to click the edit button on a row to edit its contents. Many users on our software have complained about this and would like to just be able to click to edit a row

**Describe the solution you'd like**
Cells should be clickable - bringing up the edit component
[This](https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/editable-data) is a good example of what we are looking for functionality-wise. It would of course have to fit the Material theme

**Comment by tharun968** [comment]
Hello, Is there any update on this feature ? Do we have insight on this way to implement the edit on rows w/o edit button. I'm trying to customize it but didn't get any way. Please confirm.

**Comment by itsmeganesh-cse-iiit** [comment]
Same issue here, planning to customize the package with required functionality, will update the repo soon.

**Comment by dharmesh-r-patel** [comment]
Something looking

**Comment by Dobata7** [comment]
up

**Comment by MichaelJC91** [comment]
I would love this feature!

**Comment by jakeleventhal** [comment]
not stale!

**Comment by iamsaurabhgupt** [comment]
@mbrn we would also love to have this feature. 
Currently, edit is available only on row level. So, all selection options of a selector field are not visible. If this is editable on cell level, then the selector options changing and visibility would become drastically enhanced.

**Comment by mbrn** [comment]
I started to work on :)

**Comment by iamsaurabhgupt** [comment]
Awesome @mbrn . Would wait for this release.
You can have a look at [Datatable Editor](https://editor.datatables.net/) for building a similar functionality on React. 
If this gets built, then you would have taken it to another level altogether.
![image](https://user-images.githubusercontent.com/43205009/88219649-899e7e80-cc7f-11ea-8ec4-9659e730c3a8.png)

**Comment by mbrn** [comment]
Hi,

You can use the feature with the version 1.67.1

To see an example: https://material-table.com/#/docs/features/editable

Note: We can develop it more. This is first release about cell editing.

**Comment by iamsaurabhgupt** [comment]
@mbrn It it possible to remove that underline?
It's spoiling the aesthetics. 
Rest looks great.
Thanks a lot for the amazing work.
![image](https://user-images.githubusercontent.com/43205009/88506634-f86d3600-cff7-11ea-94b8-bd966fa75143.png)

**Comment by mbrn** [comment]
@iamsaurabhgupt 

Of course. I can do it configurable. 

Also i will add a cellEditable.type (select, all)
select: Current style of editing. Users should select cell to edit. 
all: All cells would be editable at the same time with a flag.

**Comment by iamsaurabhgupt** [comment]
@mbrn Yes, that seems wonderful.
Also, we tried to change the styling of selector like a chip. 
![image](https://user-images.githubusercontent.com/43205009/88507669-84805d00-cffa-11ea-80a7-9e5ac1a4f927.png)
But, the table was not accepting it. 
Is that something that's currently possible or it needs a fresh issue to be created?

**Comment by mbrn** [comment]
@iamsaurabhgupt 

You can override editComponent.

**Comment by iamsaurabhgupt** [comment]
@mbrn is there a documentation how to do it?
May be I am missing something.

**Comment by mbrn** [comment]
@iamsaurabhgupt 

https://material-table.com/#/docs/features/editable

does 3rd example solve your needs?

**Comment by enisit** [comment]
Hi @mbrn awesome work on cell edit feature. However, editComponent does not override default input with the cell editing feature.
I used row editing before this release and editComponent was working fine but since I installed the latest version (1.68.0) and switched to cell editing it does not work anymore. Row editing still works fine with the latest release. 

``` 
          { 
            title: 'Tags',
            field: 'tags',
            editComponent: (props) => {
              return (
                <ChipInput
                    value={props.value}
                    newChipKeyCodes={[188]}
                    newChipKeys={[',']}
                    placeholder="Enter comma separated values"
                    onAdd={tag => props.onChange([...props.value, tag])}
                    onDelete={(tag, index) => {
                      props.value.splice(index,1);
                      props.onChange([...props.value]);
                    }}
                />
              );
            },
            render: (rowData) => {
              return (
                <div>
                  {rowData.tags.map((tag) => {
                    return (
                      <Chip
                        key={tag}
                        label={tag}
                        className={classes.chip}
                      />
                    )
                  })}
                </div>
              );
            }
          }
```

**Comment by iamsaurabhgupt** [comment]
@mbrn Row editing allows disabling editing of selective fields. 
But, cell edit is not allowing to disable editing on some fields. We are not able to utilise this feature due to this gap.
![image](https://user-images.githubusercontent.com/43205009/90480923-97e09d00-e14e-11ea-84d6-5be0b5b22fdc.png)

**Comment by atishwarchand** [comment]
@iamsaurabhgupt can you help me with this question. 
https://github.com/mbrn/material-table/issues/2628

**Comment by khunspoonzi** [comment]
> @mbrn It it possible to remove that underline?
> It's spoiling the aesthetics.
> Rest looks great.
> Thanks a lot for the amazing work.
> ![image](https://user-images.githubusercontent.com/43205009/88506634-f86d3600-cff7-11ea-94b8-bd966fa75143.png)

Was there ever a resolution to this particular request? I too would like to remove the underline for a cleaner look.

**Comment by sh638073** [comment]
Is there a way to include dropdown part of the table column and populate the values for the drop down dynamically using an api response.? I see we can hardcode the dropdown values but i am not sure how to populated it dynamically. Please do help me on the same.
