### ISSUE TITLE
Support for array column type and export csv

### ISSUE THREAD

**Issue by keyvanm** [mbrn/material-table#1477]
**Is your feature request related to a problem? Please describe.**
One the fields I'd like to render is an array field. I currently render the column using a custom render method which works fine. The problem comes form the default export option. When I export it to csv, the array field gets exported with commas in it and no quotation around the value, which the csv interprets as a new column. 
As an example: 
```json
data = [
    { "id": 1, "tags": ["tag1", "tag2"] },
    { "id": 2, "tags": ["tag2",] },
]
```
In the export this comes out as
```csv
"id","tags"
"1",tag1,tag2
"2",tag2
```

For some reason all fields are wrapped with quotation except the array field which can use it the most.

**Describe the solution you'd like**
A quick fix would be to wrap all exported csv cells in quotations (including the array fields) so the csv can be interpreted properly.

Another solution is described in #1318 

In general adding support for array data columns would be nice!

**Describe alternatives you've considered**
An option is to override the `exportCsv` options but that would be too cumbersome for one column.

**Comment by keyvanm** [comment]
I did some inspecting around and ended up overriding export csv based on the `defaultExportCsv` function in https://github.com/mbrn/material-table/blob/8cda5e7b208799ecc440fa15de92ef852c11a88d/src/components/m-table-toolbar.js#L29

It seems like the critical junction for this feature is https://github.com/mbrn/material-table/blob/8cda5e7b208799ecc440fa15de92ef852c11a88d/src/components/m-table-toolbar.js#L38 where 
```js
columns.map(columnDef => {
    return this.props.getFieldValue(rowData, columnDef);
})
```
We could check if the value returned from `getFieldValue` is an array and do a join on it like so: 
```js
let value = this.props.getFieldValue(rowData, columnDef);
if (Array.isArray(value)) {
  value = value.join(",");
}
return value;
```

After looking into the implementation of `getFieldValue`, another option popped into my mind that could be interesting.
https://github.com/mbrn/material-table/blob/fecb998f2f03ddbc0c5746923f1c0824fa4fe1de/src/utils/data-manager.js#L406
`getFieldValue` allows overriding the value of a field using the `lookup` column option. If `lookup` could also be a function alongside a map, then the developer can define it to do the join in column options, or override the value of that field to their liking.

**Comment by mogilvie** [comment]
As a possible solution here and to #1808 and #1318 

For example, the row data is an object containing currentPay and pastPay. Where the data export should only return the current pay value.  
  
In the Column Definition, add a "customExport" function, similar to the existing "customSort", that returns the value you want fro the underlying data object.

```
{
  title: 'Net pay',
  field: 'netPay',
  customExport: rowData => rowData.netPay.current
}
```

Then in *m-tables-toolbar.js* line 84
```
var data = dataToExport.map(function (rowData) {
  return columns.map(function (columnDef) {

    // Add check on the customExport function below and return the result of that function.
    if(typeof columnDef.customExport === "function"){
      return columnDef.customExport(rowData);
    }

    return _this.props.getFieldValue(rowData, columnDef);
  });
});
```

This seems to be working for me at the moment. Although I am not sure if I am bypassing any important work from _this.props.getFieldValue

**Comment by tolgaduzenli** [comment]
I have same situation. Trying to export as CSV feature but last column of each row is list of object. (array)
Something like this; 
"rolePermissions":[
{"id":"8c1c6dc2-0e32-4afa-a0ee-dd6a677695e6",
"roleId":"dcc49fc9-6607-4e0b-991f-c18ffef62bcf",
"permissionId":"d207bd83-88a3-4371-abef-d611d028dd8b",
"permissionIsGrant":1,
"permission": {
  "id":"d207bd83-88a3-4371-abef-d611d028dd8b",
  "companyId":"b3535f27-a337-4c7a-94c6-639036a1b909",
  "permissionKey":"add_announcement",
  "permissionDescription":""
 }
}
]

I need to show permission.permissionKey in the excel file. 

Is this something I can with somehow by custom export function or is it too much complex?

**Comment by Cristy94** [comment]
I have the same issue, trying to export an array of pages a user visited, it breaks the CSV column alignment.

One solution could be to allow the passing of an optional, custom `exportFormat` function to each column.

So the column could have 

```
{
    title: 'Column name',
    exportFormat: (rowData) => rowData.pagesVisited.join(' ')
}
```
