### ISSUE TITLE
Columns labeled as 'numeric' have right align when used as a group label.

### ISSUE THREAD

**Issue by Siech0** [mbrn/material-table#1479]
**Describe the bug**
If you enable grouping on a table and you use a label marked with the type 'numeric' as the group by label, the group selection interface will be right aligned. (Likely due to how numeric columns themselves are right aligned.)

**To Reproduce**
1. Create a column with the field "type" set to "numeric"
2. Enable the option 'grouping' on the table
3. Choose the previously created "numeric" column as the grouping label
4. See that the group tabs are awkwardly on the right side of the table

**Expected behavior**
The group tabs should be aligned to the left, irrespective of the type of the column used to group by.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/7662568/71575024-4ef1b080-2ab9-11ea-8652-bf228d461f32.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version [e.g. 22]: 71.0

**Comment by thelazydogsback** [comment]
Just came across this as well.

**Comment by 8enSmith** [comment]
You can see this issue in the "Basic Grouping Example" [here](https://material-table.com/#/docs/features/grouping). View this example and group by "Birth Year" to see the issue described above.

**Comment by HighlApp** [comment]
Same here.
