### ISSUE TITLE
Increase the font in the Pagination component ...

### ISSUE THREAD

**Issue by anand-swaminathan** [mbrn/material-table#148]
I tried to use component overriding for Pagination as follows :
<MaterialTable
components={{
Pagination: props => (
<div style={{ backgroundColor: '#e8eaf5', fontSize: 14 }}>
<TablePagination {...props} />
),
}}

The intent was that the text "Rows per page" and the text "1-20 of 500" (for example) would be in font size of 14.  I could not get this to work. Is this doable ?

**Comment by aswamina** [comment]
This worked well. Thanks so much
