### ISSUE TITLE
CSS Glitch in Next js

### ISSUE THREAD

**Issue by derryberni** [mbrn/material-table#1482]
**Describe the bug**
When i'm try material-table in next js i found problem asset css like glitch when page load.

**To Reproduce**
1. Install next js project
2. create page example editable using material table
https://material-table.com/#/docs/features/editable

**Expected behavior**
asset and icon load without glitch

**Screenshots**
https://streamable.com/e3y23

**Package.json**
"dependencies": {
    "@material-ui/core": "^4.8.2",
    "material-table": "^1.54.2",
    "next": "^9.1.6",
    "react": "^16.12.0",
    "react-dom": "^16.12.0"
  }

**Example Code Repo**
https://github.com/derryberni/nextjs-material-table

Thankyou

**Comment by emarshah** [comment]
@derryberni its working fine for me in chrome? I have re-used your code, and seems there is no css glitch as you described.

**Screen Recording**
[https://streamable.com/hvogg](url)
