### ISSUE TITLE
TablePagination is out of range when deleting item

### ISSUE THREAD

**Issue by dinizime** [mbrn/material-table#1483]
**Describe the bug**
When using an editable table (as in https://material-table.com/#/docs/features/editable) and you have only one item in the last page and you delete that item you will get the following warning

`Warning: Failed prop type: Material-UI: the page prop of a TablePagination is out of range (0 to 0, but page is 1).`

**Expected behavior**
Automatically update the pagination values.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser  Chrome Version 79.0.3945.88 (Official Build) (64-bit)
- Material table version: 1.54.2

**Comment by juspeeh** [comment]
Facing same issue. Is there a way to manually update the page or other workarounds?

**Comment by Letrab** [comment]
Reopen?

**Comment by ale917k** [comment]
Same happening here, this ticket needs to be reopened
