### ISSUE TITLE
Editable problem: everything stays greyed

### ISSUE THREAD

**Issue by LeJav** [mbrn/material-table#1487]
In editable mode, when doing something else without saving/cancelling the changes, the fields stay greyed and disabled.
For instance, go at https://material-table.com/#/docs/features/editable
  - show "Editable Example"
  - click on edit icon for a row
  - hide "Editable Example"
  - show again "Editable Example"
All rows are disabled in grey.
Is it possible to avoid that? To force exit of edition mode?

**Comment by thelazydogsback** [comment]
See related #1496 . In <= v.1.54.0 all rows could sometimes gray out without user interaction when entering edit mode - not sure if it's some kind of race condition, but seems to be fixed in 1.54.2.

**Comment by LeJav** [comment]
I have the problem with 1.54.2.
You can test this issue very easily:
For instance, go at https://material-table.com/#/docs/features/editable
    show "Editable Example"
    click on edit icon for a row
    hide "Editable Example"
    show again "Editable Example"
    All rows are disabled in grey.

**Comment by JoseHerradez** [comment]
Happening for me still, even when routing and going back all the tables are looking like that

**Comment by yonihorwitz** [comment]
Any update or solution to this problem?

**Comment by AmrViernes** [comment]
The Same here hope to fix it really

**Comment by yurivangeffen** [comment]
Same when updating the parent component (which probably triggers a re-render).
