### ISSUE TITLE
add multiselect to lookup

### ISSUE THREAD

**Issue by hutber** [mbrn/material-table#1492]
With the below code I get a select menu (`lookup`). I would like to have a multiselect menu, so i can save more then one id, ideally an array.

# Current Select
[![enter image description here][1]][1]

# Implementation

    columns = [
      {
        title: 'Game Systems',
        field: 'gameSystemIds',
        type: 'numeric',
        lookup: {1: "40k", 2: "Fantasy"},
      },
    ]
    
    <Table
       columns={columns}
       data={allManufacturers}
    </>

Is it possible to use a multi select box?

  [1]: https://i.stack.imgur.com/xv9cl.png

**Comment by hutber** [comment]
This is possible with https://material-table.com/#/docs/features/component-overriding
and using:
`EditField`

Without going into any detail at all:

```javascript
export default function(props) {
  return (
    <MaterialTable
      components={{
        EditField: fieldProps => {
          const {
            columnDef: { lookup },
          } = fieldProps
          if (lookup) {
            console.info(fieldProps)
            return <AutoComplete {...fieldProps} />
          } else {
            return <MTableEditField {...{ ...fieldProps, value: fieldProps.value || '' }} />
          }
        },
      }}
      icons={tableIcons}
      {...props}
    />
  )
}
```

**Comment by techyrajeev** [comment]
I came here in search of 'adding multiselect to lookup'
@hutber issue is still open. is it not working or looking for other alternatives?

**Comment by hutber** [comment]
No, please close the issue as its working perfectly with my code above.
