### ISSUE TITLE
How to get hover event for a row

### ISSUE THREAD

**Issue by engelkes-finstreet** [mbrn/material-table#1501]
Is there a way to pass the hover event from a row down to a column. I would like to 

1. Show the edit and delete icons only on row hover 
2. Change the font color of some of the columns on row hover

![image](https://user-images.githubusercontent.com/36962022/71996795-15e5d880-323d-11ea-9011-9153cc9eb7d5.png)

I found some possibilities how to change the style for a row on hover but not for a specific column after the row was hovered.

Help is much appreciated. Thanks in advance!

**Comment by theMattCode** [comment]
See https://github.com/mbrn/material-table/issues/1178#issuecomment-573041748. Maybe that helps to get you started.

**Comment by Davst** [comment]
Also looking for a way to just change the row color on hover.

**Comment by theMattCode** [comment]
Simply put it in the block selected by : hover
