### ISSUE TITLE
How to make details panel searchable

### ISSUE THREAD

**Issue by nagireddygatla** [mbrn/material-table#1505]
I want to search details panel of material table, currently search is working only on column data, not sure if this feature is already there, custom implementation of this feature if anyone has done would also be useful. Thanks!

**Comment by nagireddygatla** [comment]
Found a way to have the details panel data in the column, and setting cellstyle to 0px, and the data is searchable now, but it is showing an empty space for some part of row. Is it possible to set hidden property to true and make it still searchable, when I set hidden property to true the column again becomes non-searchable.

**Comment by starkWebDev** [comment]
@nagireddygatla Im not sure if you already got this figured out, but you can flag a column as both "hidden" and "searchable", which should solve your problem!
