### ISSUE TITLE
Cannot set search box and add button to second line

### ISSUE THREAD

**Issue by vicradon** [mbrn/material-table#1513]
**Problem and Feature Request**
I can't style the table to fit mobile. I can't seem to find a way to put the search bar and add button on a different line.

**Possible Solution**
I would want a way to set an option to move the search bar and add button on a different line

**Alternatives I've considered**
I have tried using a stylesheet to write styles on the existing classes I copied from the dev tools. This action affected other components using that same class"

**Comment by ambr89** [comment]
Hi @Vicradon 
have you found any solution?

I would move add button in line with filters.

**Comment by Vicradon** [comment]
I haven't.
I don't get what you mean by, “in line with filters”

**Comment by kirillibrahim** [comment]
I want to move the search bar and add button on a different line or outside table contianer div to be above table.
