### ISSUE TITLE
How to enable row hovering?

### ISSUE THREAD

**Issue by Davst** [mbrn/material-table#1515]
Really liking this table, missing the material UI hover per row.. is there any way to use this feature with this table?

**Comment by phillhutt** [comment]
I was able to enable the hover feature by setting `onRowClick={true}` on the MaterialTable component.

**Comment by Davst** [comment]
This did add hover effects, but also makes the whole row look like it is linked (link pointer)

**Comment by ManishaW** [comment]
Add this line to your MaterialTable:
 `options={{ rowStyle: { "&:hover": { backgroundColor: "#0000000f" } }`

**Comment by InfinityKn** [comment]
I enable onRowClick and pass null to function
`onRowClick={() => null}`

**Comment by InfinityKn** [comment]
> I was able to enable the hover feature by setting `onRowClick={true}` on the MaterialTable component.

Try `onRowClick={() => null}`

**Comment by fragmyte** [comment]
I was trying for the same thing, please let me know if you got it working

Tried with - 

1. onRowClick={true}
2. onRowClick={() => null}
3. options={{ rowStyle: { "&:hover": { backgroundColor: "#0000000f" } }}}

Option 1 and 2 are making cursor type as pointer, and option 3 isn't working

**Comment by InfinityKn** [comment]
> I was trying for the same thing, please let me know if you got it working
> 
> Tried with -
> 
> 1. onRowClick={true}
> 2. onRowClick={() => null}
> 3. options={{ rowStyle: { "&:hover": { backgroundColor: "#0000000f" } }}}
> 
> Option 1 and 2 are making cursor type as pointer, and option 3 isn't working

I use only `onRowClick={()=>null}` to enable row hover 
this is example [https://codesandbox.io/embed/flamboyant-booth-4ghm4?fontsize=14&hidenavigation=1&theme=dark](url)

**Comment by fragmyte** [comment]
@InfinityKn that example isn't working. what i'm trying to say is 'onRowClick={()=>null}' gives hover functionality, but it makes the cursor as a pointer, which is not a good UX practice as row isn't clickable always.

**Comment by arthurtyukayev** [comment]
The only way that I was able to disable the pointer cursor while having a `onRowClick` handler was to use a plain old CSS file imported that overwrites the classes.

**Comment by PedrinhowVieira** [comment]
I'm trying to achieve the same as @fragmyte and @Davst ,  @arthurtyukayev can you share what you done to disable the pointer cursor?
