### ISSUE TITLE
Lookup On An Array Of Data

### ISSUE THREAD

**Issue by ETS-Nathaniel** [mbrn/material-table#1516]
I have a column that needs to render multiple pre-defined values that can be filtered using the lookup dropdown menu. Lookup will render a single item, but as soon as the data contains an array of lookups I end up with an empty table field. My current data looks like this:

`data={[
  {acct:'McDonalds'},
  {needs:[1,2,3]}
]}`

And then in my table

`column={[
  {title: 'Account', field: 'acct'}
  {title: 'Needs', field: 'needs',
    lookup: {
    1: 'Floor Cleaning',
    2: 'Window Washing',
    3: 'Trash Service',
    }
]}`

**Describe the solution you'd like**
It would be great to have a way to define multiple lookups and have them all render in the same row, so that for instance you could check 'Floor Cleaning' and 'Window Washing' and either
  1 - See the accounts that only require Floor Cleaning and Window Washing, or
  2 - Filter out all the accounts that DO NOT require both Floor Cleaning and Window Washing.
Either of these solutions would work fine for me, I have just been unable to figure out an effective way to implement this.

I did consider a solution that where the data is an array of strings, i.e.
`data={[
  {acct:'McDonalds'},
  {needs:['Floor Cleaning', 'Window Washing', 'Trash Service']}
]}`
then the filter is overridden with a drop-down that gives the options. I'm thinking I may be able to hack together a contains() filter but have had some trouble overriding just the filter for the needs column. If that is both more viable and simpler in the long run then help targeting that specific filter would also be appreciated.

**Comment by sperezm97** [comment]
This should be considere by the maintainers !
