### ISSUE TITLE
Filter placeholder text is misaligned for lookup filters

### ISSUE THREAD

**Issue by kthyer** [mbrn/material-table#1519]
**Describe the bug**
Filter placeholder text is misaligned for dropdown filters

**To Reproduce**
On version: 1.55.0 of material-table

1. Create a table with a normal filter and lookup filter
2. Add filter placeholder text
3. Note the filter placeholder text for lookup filter is misaligned 

**Expected behavior**
The lookup filter placeholder text should be aligned with the normal filter placeholder text

**Screenshots**
Chrome: 
![Screen Shot 2020-01-13 at 10 01 24 AM](https://user-images.githubusercontent.com/850356/72272823-4344d480-35f7-11ea-8dbc-2a430b7b46e0.png)

Firefox:
![Screen Shot 2020-01-13 at 11 26 37 AM](https://user-images.githubusercontent.com/850356/72273071-b3ebf100-35f7-11ea-9ebc-dba2a36f65c7.png)

**Desktop:**
 - OS: macOS 10.15.2

 - Browser Chrome
 - Version 79.0.3945.117 (Official Build) (64-bit)

- Browser Firefox
- Version 72.0.1 (64-bit)

**Comment by ZamenWolk** [comment]
Also tried to update to version 1.55 and noticed this. I would expect this to be caught before being shipped, so this is quite surprising to me and took me quite some time to find

**Comment by ingvaldlorentzen** [comment]
Anybody have a workaround for this, or can point me in the right direction for a fix?

Wouldn't mind making a PR for this, but not quite sure where to start.

**Comment by ingvaldlorentzen** [comment]
As you can see in the references I made a pull request that fixes this. 
Also I found a workaround that might be useful for others until the pull request is (hopefully) merged.

```js
const muiTheme = createMuiTheme({
    overrides: {
        MuiTableCell: {
            root: {
                '& .MuiInputLabel-formControl': {
                    marginTop: -16,
                },
            },
        },
    }
})
```
Ref: https://material-ui.com/customization/components/#global-theme-override
