### ISSUE TITLE
Make Filter row sticky under header 

### ISSUE THREAD

**Issue by schen3** [mbrn/material-table#1521]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when scroll to the end of the page, the filter is been scrolled up and could not see what has been filtered. 

**Describe the solution you'd like**
Make filter row sticky right under the header row.

**Comment by mackankowski** [comment]
@schen3  - try setting `filterRowStyle` in table's `options`:

```
   filterRowStyle: {
       position: "sticky",
       top: 100,
       background: 'white,
       zIndex: 5 /* optionally */
   },
```

To match `top` attribute with a sticky header, also add:

```
   headerStyle: {
       height: 100,
   } 
```

Good luck!
