### ISSUE TITLE
Type definition update for Column

### ISSUE THREAD

**Issue by ririvas** [mbrn/material-table#1523]
Recently, as part of commit #1343, the string column type was removed from the list of available options. 

```typescript
type?: ('string' | 'boolean' | 'numeric' | 'date' | 'datetime' | 'time' | 'currency');
```

We should include the string type, correct? Material-Table can render strings in JS and has been rendering. 

This for material-table@1.55

**Comment by ririvas** [comment]
I can't get the sandbox to explicitly fail, but the syntax highlighting for invalid types is there.

Either way, we can see that it works fine with a string

https://codesandbox.io/s/material-table-demo-9cp2h

**Comment by chitgoks** [comment]
i also would wish a feature can be provided where in if we specify type as date but our data is a string date, then it will automatically convert it to a date object once it is in edit mode.

**Comment by ririvas** [comment]
@chitgoks I would file that a separate feature request. This issue is tailored to a type definition

**Comment by chitgoks** [comment]
yes please thank you. perhaps a color picker type too? though i plan to custom code it in editable property

**Comment by ririvas** [comment]
I'm closing this issue. To avoid the type error, do not specify the type property in the column definition
