### ISSUE TITLE
Use custom editComponent in combination with custom render function

### ISSUE THREAD

**Issue by bastienmenis** [mbrn/material-table#1525]
When I specify a `render` props against a column, it overrides what I put in `editComponent`. I tried to combine the two in the `render` function but that generates lot of complexity. Here is what my render function looks like:

```
render: rowData => {
    if (rowData.tableData.editing) {
        return <MyEditComponent data={rowData} />
    } else {
        return <MyDisplayComponent data={rowData} />
    }
}
```

I had some challenges with this approach:
1. To save the modified property, I have to put the value in a custom state and override the property inside the `onRowUpdate` function. With the `editComponent` approach, this is covered by calling `props.onChange([...])`
2. When adding a row, `rowData` is undefined. So this object cannot be modified to save in the new property for that column...

For my use case, I would be easier if the custom `render` was only called when the row is not in edit mode. Or have another column prop `displayComponent` similar to `editComponent`.

Any thoughts on that? Or other way to achieve what I want to do?

**Comment by TroySchmidt** [comment]
I am not experiencing this behavior and am supplying a custom editComponent and custom render.  Probably going to need a minimal functioning codesandbox example of the bug.

**Comment by bastienmenis** [comment]
Here is a codesandbox showing the issue. When clicking the "Add" button it throws an error

https://codesandbox.io/embed/ecstatic-water-6dvnp?fontsize=14&hidenavigation=1&theme=dark

**Comment by TroySchmidt** [comment]
You were missing the `fieldName` property on the column.  Then also you are using React's poolable events so had to call e.persist() in order to get a hold on the e.target.value property reliably.  No errors and it isn't updating on the row because you `onChange` is just an empty promise.

[Updated example](https://codesandbox.io/s/gallant-wildflower-h26fi)

**Comment by bastienmenis** [comment]
Of course, that makes sense. `field` is not required when using only a custom `render`, but it is for using `editComponent`. Thanks, Troy!
