### ISSUE TITLE
Column width ignored

### ISSUE THREAD

**Issue by thelazydogsback** [mbrn/material-table#1526]
I'm merging the following object into one of my columns, and it seems to have no effect:

```
    const width = "500";
    const widthProps = {
        cellStyle:{ minWidth:width, width },
        headerStyle:{ minWidth:width, width},
    }

  ...cols...
      { title: "From", field: "from.business_ref", editable:"onAdd", ...widthProps,
```

Is there something else I'm missing?

**Comment by mbrn** [comment]
Hi 

By version 1.57.1 you can add width to column definitions directly. But do not forget make options.tableLayout:'fixed'. 

I will close the issue. You can reopen if it requires

**Comment by ifndefdeadmau5** [comment]
@mbrn I think you missed the typescript definition of 'width'
