### ISSUE TITLE
Tree Data -   How can I Expand an specific Row by Default?

### ISSUE THREAD

**Issue by fvgtekken** [mbrn/material-table#1528]
I think i saw something related to my quiestion here in the docs:
you can handle expand-collapse events of any data by onTreeExpandChange
but I dont realize how to use it.
Thanks  in advance.

**Comment by JigsWeb** [comment]
Hey I just found a solution for your old problem, hope could help someone.

You need to add a object "tableData" to your row with a key "isTreeExpanded" to true

`
const data = [{ exemple: 1, tableData: { isTreeExpanded: true }]
`

If you have trouble with expand panel, you can save expand state and re-inject it like:

`
const [expandedStates, setExpandedStates] = useState({})
const data = data.map(row => ({ ...row, tableData: { isTreeExpanded: expandedStates[row._id]  } }))

<MaterialTable
   onTreeExpandChange={(row, state) => setExpandedTicketStates({ ...expandedTicketStates, [row._id]: state })}
   data={data}
   ...
/>
`

You need uniq id for each row for this workaround

**Comment by fvgtekken** [comment]
I will try it and post some comments about it!
Thank you for your help!!
