### ISSUE TITLE
Ability to sort lookup field alphabetically

### ISSUE THREAD

**Issue by Oxymoron290** [mbrn/material-table#1530]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. 
I'm always frustrated when I need to sort a lookup field alphabetically and it defaults to the order of properties in the object.

**Describe the solution you'd like**
The problem occurs [here](https://github.com/mbrn/material-table/blob/34fb0c3a065d531ea6f67ed5bf2ee15c9b73ca0a/src/components/m-table-edit-field.js#L26). The only way to sort a `<Select>` element's `MenuItem`s is to provide it with the `MenuItem ` in the order you wish for them to be displayed. Since `Object.keys()` is unordered, and the keys for the `lookup` object are numbers, the `MenuItem`s are rendered by their property names and not by the property contents.

**Describe alternatives you've considered**
I've considered using a component other than material-table, since it does not support this functionality.

**Additional context**

Given:
```
lookup = {
   0: "B",
   2: "D",
   3: "A",
   1: "C"
}
```

expecting to see:

```
<Select>
    <MenuItem>A</MenuItem>
    <MenuItem>B</MenuItem>
    <MenuItem>C</MenuItem>
    <MenuItem>D</MenuItem>
</Select
```

instead saw:

```
<Select>
    <MenuItem>B</MenuItem>
    <MenuItem>C</MenuItem>
    <MenuItem>D</MenuItem>
    <MenuItem>A</MenuItem>
</Select
```

**Comment by j88ke** [comment]
@Oxymoron290 Did you ever find a solution for this? I've just discovered the same issue.

**Comment by Krempelj** [comment]
It's because of how ordering of numeric indices work in js objects. If you can use string indices, you can manually sort the lookup before setting it.
