### ISSUE TITLE
How to change style of 1 specific cell? Not a whole column or row but 1 specific cell based on the data.

### ISSUE THREAD

**Issue by lokoo** [mbrn/material-table#1531]
I have my data filled in like this:

```
 data={
        query =>
                new Promise((resolve, reject) => {
                        getData()
                        .then(result => {
                            resolve({
                                 data: result.data
                            })
                 
                  });
  }
```

Now based on a specific cell, I want to apply styling. For example if one of the cells consist of the letter A, I'd like to make the background red.

Lets say my material table looks like this:

Header 1   Header 2

aaaaa         bbbbbbb

bbbb          aaaaaaa

I want the 2 cells with all the a's in it for the background to be red. Not the whole row or the column of Header 2

How can I do this?

**Comment by Domino987** [comment]
You can override the cell component directly as written in the docs. And since the value and rowData is passed to the custom override, you can style in respect to the passed data.

**Comment by lokoo** [comment]
> You can override the cell component directly as written in the docs. And since the value and rowData is passed to the custom override, you can style in respect to the passed data.

Sorry I dont understand. Can you give an example?

**Comment by Domino987** [comment]
Here is a [sandbox](https://codesandbox.io/s/material-table-selection-different-data-from-table-iu9re) on how you could do it.

**Comment by lokoo** [comment]
> Here is a [sandbox](https://codesandbox.io/s/material-table-selection-different-data-from-table-iu9re) on how you could do it.

This worked for me. Thanks!
