### ISSUE TITLE
Table not loading at all in IE 11

### ISSUE THREAD

**Issue by ymihir** [mbrn/material-table#1533]
Go to https://material-table.com/ in IE 11, nothing is loading. I have implemented this by keeping in my mind it will work anywhere. I have tested this in chrome and developed. But now it is not working IE11 which is awful. Any solution for this?

**Comment by sagar-ganesh** [comment]
yes, its not working on IE. Also table not getting rendered properly on IE 11 if you change pagination value.

**Comment by ymihir** [comment]
Any update on this please?

**Comment by sagar-ganesh** [comment]
I tried and now its working in IE 11 (version 11.914.17763.0) with some alignment issues but site (https://material-table.com/) will not open in IE.  The alignment issues are due to the css flexbox.

**Comment by ymihir** [comment]
@sagar-ganesh  for me still not working. Wasted lot of time utilizing this table. No proper support as well.
