### ISSUE TITLE
Aligning detail panel column on right side causes filters columns to misalign

### ISSUE THREAD

**Issue by eclafelix** [mbrn/material-table#1538]
**Bug** 
When _detailPanelColumnAlignment_ is set to _right_ it causes filter columns to shift and move one column to the right on render. 

 
**To Reproduce**
Set 'detailPanelColumnAlignment' to 'right and 'filtering' to 'true' in options

**Expected behavior**
The columns of the filter row should be aligned with their respective field column 

**Screenshots**
![Screenshot_2020-01-17 Eclipse Mining](https://user-images.githubusercontent.com/59447349/72626616-40542780-3908-11ea-87af-1888053126cd.png)

**Desktop**
 - OS: Windows 
 - Browser Firefox
 - Version 72.0.1

**Comment by eclafelix** [comment]
Looks like the issue stems from m-table-filter-row.js there is no index prop being used so it is moving the filters as if detail panel is still at the start of the array. 
![MUI_filter](https://user-images.githubusercontent.com/59447349/72737466-de403000-3b5c-11ea-93ed-e65d6889ceb0.png)

**Comment by dyaacov** [comment]
Any update or a workaround on this?

Thanks!

**Comment by eclafelix** [comment]
The fix for me was really easy,  I just changed the index of the splice in m-table-filter-row to columns.length on line 269:

if (this.props.hasDetailPanel) {
          columns.splice(columns.length, 0, React.createElement(_TableCell["default"], {
            padding: "none",
            key: "key-detail-panel-column"
          }));
        }

**Comment by sujay-gandham-by** [comment]
I'm facing the same issue. @eclafelix Are you working on this issue or can I put in a fix for this?

**Comment by dyaacov** [comment]
Hi Sujay,

No, I'm not on it.
I'll appreciate it if you share your fix when ready.

Thanks!
