### ISSUE TITLE
Set Initial Ordered Column and Direction

### ISSUE THREAD

**Issue by BrettStatman** [mbrn/material-table#1539]
Hello,

Is there a way to set the initial ordered column and direction? I see the `onOrderChange` callback which provides `(orderedColumnId, orderDirection)`, but I don't see a way to initialize the table with this type of information, similar to setting `options.initialPage`. Use case is to store the column and direction order information and reinitialize a table with the same state.

**Comment by miktap** [comment]
I couldn't find a way myself. I implemented this on the data side.

**Comment by AbbalYouness** [comment]
In your column you can add somethin like this : 
```
{
  title: "Id",
  field: "id",
  defaultSort: "desc"
};
```
it will sort you by default on column id with desc order.

**Comment by BrettStatman** [comment]
Thank you @AbbalYouness. Using the `defaultSort` option in the column configuration, I am able to initialize the table with default sorting.

**Comment by Jsalvat** [comment]
Can I reopen this ticket?

I understand that with defaultSort we can sort by 'desc' or 'asc. But we need to sort too by orderedColumnId.

So it will be something like:

orderedColumnId: 2
orderDirection: 'asc'

We're saving that data on redux store and not on data object. Any prop that we can use to set initial value?
