### ISSUE TITLE
ClassName is not passed to action icon btn

### ISSUE THREAD

**Issue by alfonmga** [mbrn/material-table#1540]
```jsx
const useStyles = makeStyles(() => ({
  disableBtnHover: {
    "&:hover": {
      backgroundColor: "transparent",
    },
  },
}))

function CompanyUsersTable() {
  const classes = useStyles()

  return (
    <MaterialTable
      icons={muiUtils.tableIcons}
      columns={[
        { title: "NAME", field: "name" },
        { title: "EMAIL", field: "email" },
        { title: "ROLE", field: "role" },
        { title: "LAST LOGIN", field: "lastLoginAt" },
      ]}
      data={[
        {
          name: "John Doe",
          email: "hq@acme.com",
          role: "Account Owner",
          lastLoginAt: "53 minutes ago",
        },
      ]}
      title="Demo Title"
      actions={[
        {
          icon: () => (
            <Button variant="contained" size="small" className={classes.disableBtnHover}>
              Edit user
            </Button>
          ),
          iconProps: {
            className: classes.disableBtnHover,
          },
          onClick: (evt, rowData) => {},
        },
      ]}
    />
  )
}
```

Is this a bug? I'm trying to add a `<Button/>` and remove the hover effect from the parent button that material-table inserts so I can make it looks good and not like this:

![Screen Shot 2020-01-17 at 7 56 45 PM](https://user-images.githubusercontent.com/9363272/72638330-82f71d80-3963-11ea-94a6-6b1ec77087ec.png)

Class attribute is not set:
![Screen Shot 2020-01-17 at 8 02 47 PM](https://user-images.githubusercontent.com/9363272/72638747-627b9300-3964-11ea-90df-c8036fce1e65.png)

**Comment by alfonmga** [comment]
This is the problem:
https://github.com/mbrn/material-table/blob/36fb268fd6ed00f786235719fc9d9261ff6c51e3/src/components/m-table-action.js#L46-L55

We don't have any way to pass some styles to it.

**Comment by AugustoCalaca** [comment]
pass an `IconButton` instead `Button` to `icon = ()  => {}`

**Comment by alfonmga** [comment]
> pass an `IconButton` instead `Button` to `icon: () => {}`

That wouldn't work too, I have tried everything :/ there's no way to do it atm unless we can get #1541 merged.
