### ISSUE TITLE
How to use server side pagination with client filtration?

### ISSUE THREAD

**Issue by MohammedSaberMohammed** [mbrn/material-table#1543]
what i need is when i use remote data i want to be allowed to filter client side not server side here is my table
![Screenshot from 2020-01-19 18-33-56](https://user-images.githubusercontent.com/19964514/72684566-54577f00-3aea-11ea-96e9-5d484b24f038.png)
and my code for` remote data`
``` 
<MaterialTable
   title={Strings.userManagementList}
   data={query => {
     this.get(query);
     return new Promise(resolve => event.on('data-fetched', resolve));
    }}
    isLoading={store.loading}
    options={this.options}
    actions={this.actions}
    localization={this.localization}
    columns={this.columns}
    components={this.components}
  />
```
this works fine but also the search bar in the top left corner `when i type in it, it calls the end point again with search parameter` ---> this is normal but my problem is `when i change filter or search from search bar ---> related to any column it also calls the endpoint`

so what i want is:
 **1/ remote data
 2/ only the top left search field used in trigger remote data again 
3/ if i filter from columns filtration bar it searches inside the current table results no need to remote data unless i paginate or searched from the top left search field**

Thanks in advance.

**Comment by ambr89** [comment]
Hi,
I have the same problem.

you can use this tricks:
```js
<MaterialTable
Body: bodyProps => (
                            <MTableBody
                                {...bodyProps}
                                onFilterChanged={(columnId, value) => {
                                    //OR Do you job here :)
                                    bodyProps.onFilterChanged(columnId, value);
                                }} />)
                            }                   
                        }
...

/>
```

but I have a lot of other problems,
if you find a better solution please tell me.

Thanks in advance.
