### ISSUE TITLE
onRowUpdated is not re-rendering the view with Redux, isEditable & isDeletable not working.

### ISSUE THREAD

**Issue by Androsv96** [mbrn/material-table#1547]
I'm using material-table and I'm not being able to do the following: 
1: I have already populated the table, but the edit button is not hidding even with this condition: **isEditable: rowData => false**  Same with isDeletable.
2: After updating a row, inside onRowUpdate function I'm cloning my redux store this way: 
**let data = {...state.myReducer.myKey};**
Then I'm updating *data* with the row I just modified, after that I'm dispatching an action with the new data so my reducer updates my store, my view recieves the modified data but the table does not refresh (re-render) and I do not know why. I hope somebody can help me out with this. 
Thanks :3

**Comment by mrjdavidfg** [comment]
See #1400

**Comment by Androsv96** [comment]
I'm going to wait for the merge. Closing this issue.
