### ISSUE TITLE
Scroll Sync - multiple tables

### ISSUE THREAD

**Issue by ionutt** [mbrn/material-table#1548]
Hi, 

   I have two grids that I want to syncronize the horizontal scroll with react-scroll-sync.
   Anyone try to do that. The problem is that I don't have full control on the wrapper div around the table.

![image](https://user-images.githubusercontent.com/13276052/72733869-6a744680-3ba1-11ea-8fa2-5a06598bad81.png)

**Comment by ionutt** [comment]
I found an solution.
On render I will find the div that is the wrapper around <table class="muitable-root"> and pass that into ScrollSync. 

But, I think allowing to have controll on that wrapper div is a better solution.

Thanks

**Comment by AliTariq14** [comment]
Hi ionutt, 

Im also facing a similar issue, can you please share how you managed the overcome this problem ?

Thanks and regards
