### ISSUE TITLE
Refs on icons aren't used and are typed incorrectly

### ISSUE THREAD

**Issue by vdh** [mbrn/material-table#1553]
Firstly, I encountered incorrect typings on your icons:

```
Add?: React.ForwardRefExoticComponent<React.RefAttributes<SVGSVGElement>>;
```

It should match what `forwardRef` returns:

```
Add?: React.ForwardRefExoticComponent<any> & React.RefAttributes<SVGSVGElement>;
```

Or replace `any` with a more specific type (e.g. `IconProps`) if you want to be more explicit about props.

Secondly, I searched through your codebase, and I could not find _any_ uses of `ref` on icons. Is this overly-complicated requirement for icons really needed at all? Some commit messages mention "tooltips" but I don't see any refs being passed to the icon components.

Thirdly, your example wraps `forwardRef` around components that already forward refs. [`createSvgIcon`](https://github.com/mui-org/material-ui/blob/master/packages/material-ui-icons/src/utils/createSvgIcon.js) in `@material-ui/icons` already uses `forwardRef` for all the icons. Example icons like `AddBox` already forwards refs.

**Comment by vdh** [comment]
Bump…?

**Comment by vdh** [comment]
Hello? Is there anyone looking at issues? These types are clearly faulty (using `ForwardRefExoticComponent` incorrectly).

**Comment by zipzapp** [comment]
@vdh thanks for bringing up this issue! I was struggling with figuring out the correct typing for this as well and your solution was exactly correct.

**Comment by vdh** [comment]
Since stale bot is pestering like it always does, fine, here's a PR that addresses the bad types: https://github.com/mbrn/material-table/pull/2839
