### ISSUE TITLE
How to call a function when data comes into the table?

### ISSUE THREAD

**Issue by codenamethanos** [mbrn/material-table#1560]
I wanted to call a function when data comes into the material table.
I tried to use this. 

```
useEffect(() => {
        console.log(ref.current.state.data);
        //Do stuff
}); 
```
For some reason useEffect is called only when data is empty. Which means ref.current.state.data is an empty array.
A few moments later, when data comes into the material table, useEffect is not called. 

I see the following props which calls a function when rows are changed, page is changed, search and order is changed.
```
onChangeRowsPerPage={handleChangeRowsPerPage}
onChangePage={handleChangePage}
onSearchChange={handleSearchPage}
onOrderChange={handleOrderChange}
```
But there is no function that is called when data comes into the material table (Or even when there is a data change). A data change does not trigger useEffect as well. 

Any ideas?

**Comment by codenamethanos** [comment]
I also asked the question here in stackoverflow - https://stackoverflow.com/questions/59871681/how-to-call-useeffect-when-data-comes-into-material-table

**Comment by AugustoCalaca** [comment]
The default behavior for effects is to fire the effect after every completed render. That way an effect is always recreated if one of its dependencies changes. 

However, you don’t need to create a new subscription on every update, only if the data has changed.

try: 
```
useEffect(() => {
        console.log(ref.current.state.data);
        //Do stuff
}, [ref.current.state.data]); 
```

Also check the docs to get the behavior expected: https://en.reactjs.org/docs/hooks-reference.html#useeffect

**Comment by AugustoCalaca** [comment]
You will probably need to add an array of dependencies to your hook

Check the docs to get the behavior expected: https://en.reactjs.org/docs/hooks-reference.html#useeffect 
Also check the `useCallback` it might be a better alternative for your use case: https://en.reactjs.org/docs/hooks-reference.html#usecallback

**Comment by codenamethanos** [comment]
> You will probably need to add an array of dependencies to your hook
> 
> Check the docs to get the behavior expected: https://en.reactjs.org/docs/hooks-reference.html#useeffect
> Also check the `useCallback` it might be a better alternative for your use case: https://en.reactjs.org/docs/hooks-reference.html#usecallback

Problem here is that I cannot use ref.current as a dependency, it does not work. If I use data as dependency, the problem is that after data variable gets some values, table still remains empty for a few seconds so I am not able to use ref.current.state.data in my function as it will still be empty.

Let me check callback. Will update if it works.
