### ISSUE TITLE
Editable onRowUpdate not update

### ISSUE THREAD

**Issue by didopop3** [mbrn/material-table#1563]
Editable onRowUpdate not update. 

To Reproduce
1. Go to https://material-table.com/#/docs/features/editable
2. Click on the editable example
3. Click on Edit Button, after editing any value, after confirm, the result went back to the orginal value

Suspected reason
The oldData prop has "tableData" in it, and data doesn't. So data.indexOf(oldData) is alway -1, so the data can't be updated properly.
Of couse, to work around this, we can modify oldData ourselves, but for the convience, it would better to provide oldData without "tableData" in it
![image](https://user-images.githubusercontent.com/26617297/72981906-bc87c700-3e42-11ea-8ac1-c7b1d6e3158e.png)

**Comment by AugustoCalaca** [comment]
try this https://github.com/mbrn/material-table/issues/1413#issuecomment-572858590

**Comment by didopop3** [comment]
@AugustoCalaca Thanks! I'm aware of how to solve this. But I don't think the current version is the intentioned design and it's working in previous versions. 

However, I wasn't aware this is ticket for this already. So I will close this due to duplication
