### ISSUE TITLE
defaultFilter for a lookup filed

### ISSUE THREAD

**Issue by celia3511** [mbrn/material-table#1565]
Hi, I'm trying to set by defaultFilter a value of the list like active, someone can help me 

![image](https://user-images.githubusercontent.com/7703392/73011116-61c67f00-3df2-11ea-9f1f-251e9667121c.png)

**Comment by swatiwak** [comment]
Does anyone have any idea how to achieve this?

**Comment by manuel-uberti** [comment]
@celia3511 @swatiwak Have you ever managed to solve this problem?
