### ISSUE TITLE
Warning: Failed prop type: Invalid prop `components.Toolbar` supplied to `MaterialTable`.

### ISSUE THREAD

**Issue by duongdev** [mbrn/material-table#157]
**Describe the bug**
Warning: Failed prop type: Invalid prop `components.Toolbar` supplied to `MaterialTable`.

**To Reproduce**
Working with Typescript & this component (just like example):
```javascript
<MaterialTable
    columns={[
      { title: 'Adı', field: 'name' },
      { title: 'Soyadı', field: 'surname' },
      { title: 'Doğum Yılı', field: 'birthYear', type: 'numeric' },
      {
        title: 'Doğum Yeri',
        field: 'birthCity',
        lookup: { 34: 'İstanbul', 63: 'Şanlıurfa' },
      },
    ]}
    data={[
      {
        name: 'Mehmet',
        surname: 'Baran',
        birthYear: 1987,
        birthCity: 63,
      },
    ]}
    title="Demo Title"
  />
```

**Expected behavior**
Should not display prop types warning.

**Comment by mbrn** [comment]
You didn't use toolbar at example. I could not reproduce the case. Can you look at the example again, please?

**Comment by duongdev** [comment]
@mbrn oh I've just copied the example [here](https://github.com/mbrn/material-table#usage)

**Comment by mbrn** [comment]
Ok, but it does not cause a warning.

**Comment by duongdev** [comment]
@mbrn  I've injected some `console.log`s. The `components.Toolbar` prop seems difference to the others (it has `render` method while the others don't). Is it normal?

![image](https://user-images.githubusercontent.com/9253690/51108906-2760f400-1826-11e9-9676-f5258eaf0104.png)

**Comment by mbrn** [comment]
I don't know why it has a render method but it should be normal. Can you take a screenshot of warning that in your console?

**Comment by duongdev** [comment]
Here @mbrn 
![image](https://user-images.githubusercontent.com/9253690/51109446-d3570f00-1827-11e9-98cb-003c2abd5ae1.png)

By the way, I am using:
- @material-ui/core^3.8.1
- react@16.8.0-alpha.0
- react-dom@16.8.0-alpha.0
- prop-types@15.6.2

Not sure if it's because of the alpha version of react & react-dom but it should not be. I never heard about any prop-types issues of this react alpha version.

**Comment by duongdev** [comment]
I am currently working around by adding `components={{}}` prop to the `<MaterialTable />`. The prop-types warning's gone and the table changes nothing.

**Comment by mbrn** [comment]
Interesting. Can you paste your material-table usage completely?

**Comment by duongdev** [comment]
Here you are
```javascript
import React from 'react'

import { hot } from 'react-hot-loader/root'

import { Grid, Paper, Theme } from '@material-ui/core'
import { makeStyles } from '@material-ui/styles'
import MaterialTable from 'material-table'

const useStyles = makeStyles(({ spacing }: Theme) => ({
  root: {
    marginTop: spacing.unit * 5,
  },
}))

const UserList = () => {
  const classes = useStyles()

  return (
    <Grid className={classes.root} component={Grid} container spacing={16}>
      <Grid item xs>
        <Paper>
          <MaterialTable
            columns={[
              { title: 'Full name', field: 'name' },
              { title: 'Username', field: 'surname' },
              { title: 'Email', field: 'birthYear', type: 'numeric' },
              {
                title: 'Doğum Yeri',
                field: 'birthCity',
                lookup: { 34: 'İstanbul', 63: 'Şanlıurfa' },
              },
            ]}
            data={[
              {
                name: 'Mehmet',
                surname: 'Baran',
                birthYear: 1987,
                birthCity: 63,
              },
            ]}
            title="Demo Title"
            components={{}}
            options={{
              toolbar: false,
            }}
          />
        </Paper>
      </Grid>
    </Grid>
  )
}

export default hot(UserList)
```

**Comment by mbrn** [comment]
How did you override the components.Toolbar? Do not remove it.

**Comment by duongdev** [comment]
Ok, I will keep the workaround and wait for the next major release of React with hooks. Thanks for your support.

**Comment by mbrn** [comment]
You welcome. Dont forget sharing your experince with us:)
