### ISSUE TITLE
Edit options not working on latest version update

### ISSUE THREAD

**Issue by developerkarthick** [mbrn/material-table#1572]
### **bug**
 Simple table edit option not working on latest version . But in  `version@1.43.0 `its working 

check this link open any one snippet. edit the table .its not updating

[https://material-table.com/#/docs/features/editable](https://material-table.com/#/docs/features/editable)

**Comment by zilkenberg22** [comment]
/* const data = this.state.data;
                        data.push(newData);
                        this.setState({ data }, () => resolve()); */


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 /* const data = this.state.data;
                        data.push(newData);
                        this.setState([...data] ); */

**Comment by AliSaeed090** [comment]
unable to add new row in Custom Edit Component , The above code works, it successfully push data in array but nothing is showing on table, although table filed value is correctly set  and it is working when manually set object in data table list

**Comment by developerkarthick** [comment]
> /* const data = this.state.data;
> data.push(newData);
> this.setState({ data }, () => resolve()); */
> 
> ```
>  /* const data = this.state.data;
>                         data.push(newData);
>                         this.setState([...data] ); */
> ```

Its just updating state value .But bot reflected to table view.please check my question link
