### ISSUE TITLE
new row how to  get first row 

### ISSUE THREAD

**Issue by zilkenberg22** [mbrn/material-table#1574]
![Screenshot from 2020-01-28 17-15-34](https://user-images.githubusercontent.com/33345651/73250576-11845e00-41f2-11ea-9675-9aa455500488.png)

**Comment by yyuri** [comment]
This is not an issue, the feature already exist via API:

`addRowPosition: 'first' ` on options, as documented here:

https://material-table.com/#/docs/all-props
```
      options={{
        addRowPosition: 'first',
     }}
```

**Comment by zilkenberg22** [comment]
done
