### ISSUE TITLE
Custom render breaks grouping

### ISSUE THREAD

**Issue by thelazydogsback** [mbrn/material-table#1577]
I just spent several days writing custom rendering components to get things to look really pretty per customer feedback, and it seems this breaks grouping because rather than using the raw field: value, grouping uses the post-rendered value -- so if the render is a full React element rather than a string things don't work.

If this is the case, I'd really like to see a getGroupKey callback prop added. (Or overload the current grouping: prop to allow a `RowData=>string`.)

I hoping I've just overlooked something here...
thanks!

**Comment by lfsando** [comment]
Same for me

**Comment by thelazydogsback** [comment]
Turns out even if the render function returns a string rather than a react element (even if it just returns the raw string for the field) grouping will also not work.

**Comment by lfsando** [comment]
> Turns out even if the render function returns a string rather than a react element (even if it just returns the raw string for the field) grouping will also not work.

There's a second variable that you can use.
![image](https://user-images.githubusercontent.com/10608706/74448867-74186380-4e5a-11ea-88cd-4d3466c5040b.png)
For some reason there are two different values for data. When it's type row data is the rowData, but when type is group data is the field value.

**Comment by thelazydogsback** [comment]
It's nice to get the flag in case one would want to render things differently as a group -- but why not just pass the whole data row  in either case (rather than just the row value in the group case) so that the same renderer just works out-of-the-box?

**Comment by thelazydogsback** [comment]
I used this fix wrap my old renderers so that now work properly with groups as well.

So if you formerly had
`render: data => myRender(data.o.col)`
now use:
`render: fixRenderCol(myRender, 'o.col')`

![image](https://user-images.githubusercontent.com/4603468/74489169-527aa480-4e79-11ea-84ee-3c79a5c5cc68.png)
