### ISSUE TITLE
Initial selection??

### ISSUE THREAD

**Issue by thelazydogsback** [mbrn/material-table#1578]
How do I control the initial selection state of a row based on the rowdata?
(For example if rowData.state == 'active' I want to show the row as initially selected.)
thanks

**Comment by thelazydogsback** [comment]
Looks like:

   ` _.set(myData, 'tableData.checked', true);`

Not sure if tableData is supposed to be an implementation detail (not covered in selection docs) or if we're supposed to mess with it, but looks like that's the current method rather than a isChecked RowData callback prop.

**Comment by nagad814** [comment]
@thelazydogsback can you expand on the workaround. how to implement it. 

PS: I am hating my decision to use the library as a whole.

**Comment by thelazydogsback** [comment]
@nagad814 
I haven't worked on this project in a while.
In summary FWIR, the table stores the the selection state by adding it's own property to your data called `tableData`. (This is a bad idea for several reasons -- they should probably have a separate weak table on the side that stores table-specific state about your data, but that's the way it is...)
So to get your data checked, you need to set `tableData.checked=true` for the data in corresponding row -- here I'm using lodash to set this, but you don't need to.
