### ISSUE TITLE
Any way to display icon conditionally based on specific column value ?

### ISSUE THREAD

**Issue by kaleshasheik** [mbrn/material-table#158]
Hi,

  Is there any way to display icon based on specific column value ?

I have column,

{      title: 'Status',
      field: 'status',
            },

I want to display icon based on status value. If status value is requested, then show 'edit' icon, else, show 'cancel icon' .

Thanks in Advance,

**Comment by mbrn** [comment]
Yes you can. Use a funtion that takes rowdata and return icon. Look at more actions example. Second action is conditional. You can change icon, size, color, enability, onclick of action according your row data. 


https://mbrn.github.io/material-table/#/docz-examples-03-example-actions

**Comment by suchysek** [comment]
Would you be able to update examples as these links do not work anymore?

**Comment by Req** [comment]
The hidden function doesn't seem to work. Reopen?

**Comment by p9614** [comment]
@mbrn 
Could you please update the links to see the examples

**Comment by odedbendov** [comment]
This seems to be the updated link: https://material-table.com/#/docs/features/actions
