### ISSUE TITLE
Action icons vertical 

### ISSUE THREAD

**Issue by fr3sh** [mbrn/material-table#1585]
Hi 

Is it possible to have actions buttons verticaly not horizontaly?

From this:
![image](https://user-images.githubusercontent.com/6498987/73388871-4ddbbb00-42d3-11ea-9c47-796a2339d43d.png)

To this:
![image](https://user-images.githubusercontent.com/6498987/73388961-795ea580-42d3-11ea-916e-2acd047fb863.png)

This will save me some space and i need it  :(

**Comment by fr3sh** [comment]
I have found that even if you set the style for action for example min-width nothing happend. Maybe we can add one more property to style only div inside the td. For example if we set to display to grid it works. See examlple:
![image](https://user-images.githubusercontent.com/6498987/73393255-a8791500-42db-11ea-821b-703631175cce.png)

**Comment by Zeeshan666** [comment]
hey @fr3sh  can you plz tell me how to style actions icon on editable.

**Comment by fr3sh** [comment]
> hey @fr3sh can you plz tell me how to style actions icon on editable.

For now you can't do this. I have made a PR for new feature https://github.com/mbrn/material-table/pull/1591 we must to wait to release. 
For now (temp)  if you want to handle it you can use it from my npm.
 yarn add fr3sh-material-table

**Comment by fr3sh** [comment]
if you want  to style use like this:
<MaterialTable options={{                       
            actionsCellInsideStyle: { minWidth: 100, width: 100 },
             }}
  />
Or
<MaterialTable options={{                       
            actionsCellInsideStyle: { display: grid },
             }}
  />

**Comment by shovelend** [comment]
Would be really great to see this merged in!
