### ISSUE TITLE
Configurable empty row height

### ISSUE THREAD

**Issue by vikramkute** [mbrn/material-table#1586]
I have 2 tables next to each other. One is with data and another without data. and both tables has different heights. (because of row height).

Reason:
Table with data has row height of 32px. but it is hard coded in plugin for empty row count as 36px (For 'options.padding: dense' setting).

`const rowHeight = this.props.options.padding === 'default' ? 49 : 36;`

If you could make empty table row height configurable so that user can set it up.

Or 

If Padding is dense it should be 32 and for default padding height should be 52.8

Suggested change: (src/components/m-table-body.js)
`const rowHeight = this.props.options.padding === 'default' ? 52.8 : 32;`

Here are my dependencies:
"dependencies": {
    "@material-ui/core": "^4.9.0",
    "@material-ui/icons": "^4.5.1",
    "@material-ui/lab": "^4.0.0-alpha.40",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.4.0",
    "@testing-library/user-event": "^8.0.3",
    "material-table": "^1.56.0",
    "react": "^16.12.0",
    "react-adal": "^0.5.0",
    "react-dom": "^16.12.0",
    "react-router-dom": "^5.1.2",
    "react-scripts": "3.3.0",
    "typeface-roboto": "0.0.75"
  },

**Comment by awardnasc** [comment]
Issue #1005 was about this back in August of 2019 and Merge request #1010 apparently died waiting for a reviewer. I am running into this exact same issue with two tables beside each other. One empty, one full.

**Comment by afitzgerald** [comment]
Just ran into this same thing.  I have changed cell padding...so my row heights have changed.  BUT empty rows render with a hardcoded inline height of 49px...

<img width="423" alt="Screen Shot 2021-02-23 at 7 24 18 PM" src="https://user-images.githubusercontent.com/100173/108926668-da5ac900-760c-11eb-81e8-c6204893b42b.png">
<img width="294" alt="Screen Shot 2021-02-23 at 7 23 49 PM" src="https://user-images.githubusercontent.com/100173/108926670-daf35f80-760c-11eb-8a11-cac2dab95f03.png">
<img width="286" alt="Screen Shot 2021-02-23 at 7 23 43 PM" src="https://user-images.githubusercontent.com/100173/108926671-db8bf600-760c-11eb-922c-7f252e799fa0.png">

**Comment by 1nF0rmed** [comment]
Still facing a similar issue. Would make a PR if no one is already working on one for the updated repo
