### ISSUE TITLE
Getting rowIndex while update or delete

### ISSUE THREAD

**Issue by techyrajeev** [mbrn/material-table#1589]
is there any way to get rowIndex without calling `indexOf` method ?
```
onRowUpdate: (newData, oldData) =>
            new Promise((resolve, reject) => {
                setTimeout(() => {
                    {
                        /* const data = this.state.data;
                        const index = data.indexOf(oldData);
                        data[index] = newData;                
                        this.setState({ data }, () => resolve()); */
                    }
                    resolve();
                }, 1000);
            }),

```

It will be good if we have third option `onRowUpdate: (newData, oldData, rowIndex) =>`
so that we can avoid searching in whole list if we have huge data.

**Comment by MeltWS** [comment]
there is a proprety `tableData` which contains `id` for the row in `oldData` it's not correctly prototyped as the row is mutated, they are multiple issues talking about it.

https://github.com/mbrn/material-table/issues/1413
