### ISSUE TITLE
Option to enable/disable adding rows

### ISSUE THREAD

**Issue by gomorizsolt** [mbrn/material-table#1592]
**Is your feature request related to a problem? Please describe.**

We'd like to disable adding rows if the client reaches a certain limit of items.

**Describe the solution you'd like**

Looking for an option to control the "add" button's `disabled` property just as e.g. `isEditable` disables editing rows.

**Describe alternatives you've considered**

Our alternative solution goes as follows.

1. Set `editable.onRowData` to `undefined`(https://github.com/mbrn/material-table/issues/465).

```js
editable={{
   onRowAdd: (...) => this.maxLimitReached() ? undefined : this.add(...)
}}
```

2. Display a "placeholder" in place of the "hidden" `onRowAdd` icon.

```js
actions={[
   {
      icon: "add_box",
      tooltip: "...",
      isFreeAction: true,
      disabled: true,
      hidden: !this.maxLimitReached()
      onClick: () => {}
   }
]}
```

**Comment by thisismydesign** [comment]
Btw I don't understand the solution in https://github.com/mbrn/material-table/issues/465. AFAICT the request was also to be able to "disable the add button", but the issue was closed without solving this. You could also reopen that one as it already had some engagement.

Our workaround works but is very hacky.

**Comment by thisismydesign** [comment]
Don't close this issue. This is an automatic message by [Fresh](https://github.com/c-hive/fresh) - a bot against stale bots.

**Comment by Domino987** [comment]
Hi what would be your constraint to enable the adding of the rows?

**Comment by Domino987** [comment]
So how about:
`editable={{
   onRowAdd: this.maxLimitReached() ? (...) => this.add(...) : undefined
}}`

**Comment by thisismydesign** [comment]
I believe that was the quite uncomfortable workaround we used where we had to hide and replace the button instead of simply controlling its `disabled` property.

**Comment by Domino987** [comment]
Fixed with isEditable prop of editable

**Comment by thisismydesign** [comment]
Hey @Domino987, I tried `isEditable` on `1.62.0` and it doesn't address this issue.

The following still lets me add new rows.

```js
editable={{
  isEditable: () => false
})
```

We'd like a way to disable adding new rows in a user-friendly manner, such as a disabled Add button (perhaps with a tooltip). There seemed to be interest from others as well. Could you re-open this issue?

The following simply makes the Add button disappear:

```js
editable={{
   onRowAdd: undefined
}}
```
