### ISSUE TITLE
Add "defaultExpanded: true" on Group Feature options

### ISSUE THREAD

**Issue by willysvarela** [mbrn/material-table#1593]
I couldn't find this options on doc, so i had to try a lot of things to work.

Add this to documentation could solve some others devs problem.

**Comment by jgutix** [comment]
@willysvarela what is that Group Feature options? I'm still getting:
```
console.error
    Warning: Failed prop type: MaterialTable: prop type `options.defaultExpanded` is invalid; it must be a function, usually from the `prop-types` package, but received `number`.
```

Somehow when prop types are checked, the `defaultExpanded` attribute is set to `0` on `shapeTypes`, I cannot find the where is that set to 0
![Captura de Pantalla 2022-03-20 a la(s) 15 28 37](https://user-images.githubusercontent.com/1747459/159186975-6b7cd814-c59e-4097-88bf-42620c7e22c7.png)
