### ISSUE TITLE
Hidden Attribute for DetailPanel Item

### ISSUE THREAD

**Issue by DatChoob** [mbrn/material-table#1594]
**Is your feature request related to a problem? Please describe.**
This issue is not related to a problem. Just an optional functionality.

**Describe the solution you'd like**
I would like for there to be a **hidden** property to Detail Panel, just like Action.

**Describe alternatives you've considered**
Using Hidden for Now.

**Additional context**
I have a detailPanel Button that I would like to have hidden depending on a rowData attribute.

**Comment by ingvaldlorentzen** [comment]
I wanted this too, and I'm currently using the following workaround:

```js
const detailColumn = [
    rowData => ({
      disabled: !rowData.parentID,
      icon: () => rowData.parentID ? <SomeIcon/> : <></>,
      openIcon: () => <SomeOpenIcon/>,
      render: <div>Whatever you want</div>,
      tooltip: rowData.parentID ? 'Informative Tooltip' : null,
    }),
  ]
```
