### ISSUE TITLE
Broken rerender on open delete dialog

### ISSUE THREAD

**Issue by rudolfson** [mbrn/material-table#1595]
**Describe the bug**
When the dialog to confirm a row delete is open and a state change (of surrounding component) happens, the table rerenders in a broken way. The dialog vanishes but the table stays disabled (light grey rows).

**To Reproduce**
1. Go to 'https://codesandbox.io/embed/naughty-villani-yjw7n?fontsize=14&hidenavigation=1&theme=dark'
2. Hit delete on one of the rows (do not confirm, leave confirmation dialog open)
3. Click 'update' button
4. Table is rerendered - confirmation dialog vanishes, but table stays disabled

**Expected behavior**
The table shouldn't change at all (since the state doesn't concern the table itself) *or* it should hide the confirmation dialog and show the table correctly (analogue to cancelling the dialog manually).

**Screenshots**
Open confirmation dialog
![image](https://user-images.githubusercontent.com/953745/73528780-d4001a80-4415-11ea-97f3-ec5a9bd74602.png)
After clicking "update"
![image](https://user-images.githubusercontent.com/953745/73528835-ef6b2580-4415-11ea-82f5-4582bb12c9e8.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux (Manjaro)
 - Browser: Chrome 79.0.3945.130 and Firefox 72.0.2

**Comment by Poyoman39** [comment]
As a quickfix you can do this:
1. Det a reference to your material table
2. When your async delete function end, call this: `materialTableRef.current.setState({ lastEditingRow: null })`

**Comment by Poyoman39** [comment]
I did a PR ... if ever you have time to test it ;)

**Comment by Poyoman39** [comment]
Or even better, set your row data "tableData" attribute to this value: `tableData: { editing: true }`

**Comment by gtupak** [comment]
I am experiencing the same issue. Has anybody found a fix?

**Comment by gtupak** [comment]
#1618

**Comment by Poyoman39** [comment]
@gtupak  the best solution i found for now is to avoid your table to re-render during update. There is probably no reason for doing so. Table data should be updated AFTER async update operated ;)
