### ISSUE TITLE
Export to CSV only exports current page rows, not the entire table.

### ISSUE THREAD

**Issue by cooperate** [mbrn/material-table#1598]
How do i export all data/filtered data on the table, not just the current page to csv?

**Comment by adamelk** [comment]
same

**Comment by DanielObara** [comment]
I'm trying to export data to csv from grouped data but when I open the spreadsheet, the data does not appear.

**Comment by czsyjss** [comment]
`options={
  {exportButton: true,
  exportAllData: true }}`
