### ISSUE TITLE
@babel/runtime is not listed as a dependency nor peer dependency

### ISSUE THREAD

**Issue by wereHamster** [mbrn/material-table#1607]
The code in material-table/dist/index.js imports various modules from @babel/runtime, yet that package is not listed in dependencies or peer dependencies. A version of the babel runtime may be installed and hoisted through other packages or dependencies, but that does not ensure the correct version is installed.

My concrete failure is this:

> ./node_modules/material-table/dist/material-table.js
> Module not found: Can't resolve '@babel/runtime/helpers/assertThisInitialized' in '/home/runner/work/oecd-going-digital-toolkit/oecd-going-digital-toolkit/node_modules/material-table/dist'

I don't have @babel/runtime in my dependencies nor was it hoisted to the top-level node_modules by npm.

**Comment by xaroth8088** [comment]
This causes build failures if using yarn 2 + webpack PNP, with the following error: `Module not found: Error: material-table tried to access @babel/runtime, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.`

Thankfully, the workaround is simple: `yarn add @babel/runtime`.  Still, this should be corrected in Material Table's `package.json`.

**Comment by xaroth8088** [comment]
Probably this should remain open until #2374  is merged.
