### ISSUE TITLE
How do I disable edit/delete on a row?

### ISSUE THREAD

**Issue by jjt1234** [mbrn/material-table#1612]
I have a totals row that I don't want the user to be able to update/delete, I have tried:
editable = {{
isEditable: 
rowData => rowData.name === "Totals", 
isDeletable: rowData => rowData.name === "Totals", 
...
per the example, but this doesn't seem to work...is this a bug or have I done something wrong?

**Comment by william13murphy** [comment]
@jjt1234 is your column that has the title "Totals" called name? If not, then you should change rowData.name to rowData._columnName_. 

On another note, I am experiencing the same issue where I cannot prevent editing of rows that meet the given condition. My material-table package is up to date with 1.57.2

**Comment by sakhibgareevrr** [comment]
Done the same - it doesn't work for me

**Comment by william13murphy** [comment]
@sakhibgareevrr I have verified that isEditable is working properly in release 1.57.2

I recommend to delete package-lock.json and /node_modules, followed by installing your dependencies (npm i). If you would like, you can also share a code snippet here or in another issue.

**Comment by ildefonsorobinjohn** [comment]
try this 

   isDeletable: rowData =>  {
            rowData
      // isSupport = false
            if(isSupport) {
              return false
            } else {
              return true
            }
          }

or just copy paste this and test it from both false and true 
    isDeletable: rowData =>  true // disabled
    isDeletable: rowData =>  false // enabled

**Comment by Raji-P** [comment]
Thanks @ildefonsorobinjohn, option 1 worked for me..
