### ISSUE TITLE
How can I make responsive table in material table ?

### ISSUE THREAD

**Issue by BaldBoy2210626** [mbrn/material-table#1613]
**Is your feature request related to a problem? Please describe.**
I have a project that has to function as a responsive web app.
**Describe the solution you'd like**
So I need to function as have responsive feature.

How can I make a responsive table in the material table?

**Comment by mbrn** [comment]
Hi,

Actually mt is already responsive. It manages rows horizontally with scrollbar. But it does not support for any card view or something etc.

**Comment by mbrn** [comment]
I will close the issue. You can reopen if it requires.

**Comment by THPubs** [comment]
@mbrn You mean if we add it inside a `Card` component it won't have the scroll bards? I think I'm facing this issue now. Any way to enable the horizontal scroll bars even inside a Card view?
