### ISSUE TITLE
Unable to use nested data as field

### ISSUE THREAD

**Issue by jakeleventhal** [mbrn/material-table#162]
**Describe the bug**
If each row of data is like this:
`{
   'a': 1,
   'b': 2,
   'c': {
         'nested': 3
      }
}`
and I set the field for the column to `field: 'c.nested'`, the table doesn't allow searching and sorting on that field

**Expected behavior**
I should be able to use a nested attribute in the field prop.

**Comment by mbrn** [comment]
I didn't do something like this. But it will be good feature if it works. I will try @jakeleventhal :)
