### ISSUE TITLE
How to remove title in material-table

### ISSUE THREAD

**Issue by lakshmikanth-reddy-au2** [mbrn/material-table#1621]
I'm trying to remove the table title text on the top but couldn't find any solution.  I managed to remove the search bar and make title="" but this title will take up the space. I don't want that.
![image_2020_02_06T10_48_34_945Z](https://user-images.githubusercontent.com/49977739/73930928-69f7e180-48fd-11ea-9b5c-3298dc8b9a9a.png)

**Comment by mbrn** [comment]
Hi

You can use options.toolbar: false. 

I will close the issue. You can reopen if it requires

**Comment by AWIXOR** [comment]
The better way to hide the table title is to set `showTitle` to `false` in options like this :
```
options={{
        showTitle: false,
   }}
```

**Comment by AravindTReddy** [comment]
The solution provided by @AWIXOR is perfect. 
@mbrn with this options.toolbar: false, It will not only hide the title and also the whole toolbar(where search, export and other functionalities will be lost) 
So users can pick their choice accordingly.

**Comment by mohamud5** [comment]
showTitle: false removes the text label on the the toolbar while  toolbar: false removes the entire toolbar including the title

**Comment by QuentonB** [comment]
@mohamud5 This worked perfectly for me thanks!

**Comment by guilhermeludiokmm** [comment]
Someone can help me?
I need hide the header cell

**Comment by QuentonB** [comment]
@guilhermeludiokmm have you tried what @mohamud5 said? 

> showTitle: false removes the text label on the the toolbar while toolbar: false removes the entire toolbar including the title

**Comment by dschetu** [comment]
options={{ toolbar:false , paging:false,}} for removing header and footer section
