### ISSUE TITLE
Table Cell Formatting Width

### ISSUE THREAD

**Issue by p45mark** [mbrn/material-table#1625]
**Describe the bug**
The table cells are rendering at - what appears to be - fixed widths, which pushes the height to accommodate cell content

**To Reproduce**
Create a table using material table ver 1.57.1+ and add a somewhere around 90 characters of text to the cell

**Expected behavior**
The table cell size should adapt to content

**Screenshots**
Previously with Version 1.56.1
![image](https://user-images.githubusercontent.com/48729903/74054341-b6413100-4992-11ea-81c3-8370850a257c.png)

Now with Version 1.57.1+
![image](https://user-images.githubusercontent.com/48729903/74053396-96107280-4990-11ea-9b4f-49ef43a77da4.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: desktop
 - OS: mac mojave
 - Browser: all
 - Version

**Comment by beevelop** [comment]
I can confirm the same behavior. With 1.57.2 it seems as if the `tableLayout` setting is being ignored. Setting it to `auto` does not seem to affect the table at all. Even overwriting the `cellStyle` and `headerStyle` with `width: auto` doesn't work.

**Comment by bastienmenis** [comment]
I have the same issue, now all the columns are forced to the same width, instead of adapting to content. I believe it is caused by [this](https://github.com/mbrn/material-table/commit/618e7a997db9ff0cfb795aa3faab512862e6dfab#diff-0abc98af2c01fd8c771090c6a9512b22) commit.

There also appear to be a new columns prop, `width`, that is not mentioned in the [documentation](https://material-table.com/#/docs/all-props)

**Comment by beevelop** [comment]
Looks to me like the code from L87 onwards should be skipped for ` tableLayout=auto`?

**Comment by ricostone** [comment]
Same here for row select, 
![firefox_x73wr2jXn5](https://user-images.githubusercontent.com/1039656/74664313-c67cbb80-519d-11ea-86de-de35a6c7a188.png)

**Comment by ifndefdeadmau5** [comment]
Also the typescript definition of new prop 'width' is missing right now

**Comment by skitsanos** [comment]
yep, width settings are ignored.

**Comment by gabolucuy** [comment]
I can also confirm that version 1.57.2 ignores width of headers and cells, had to downgrade to version 1.57.0

**Comment by vikramkute** [comment]
Until this is fixed, I have added temporary fix in my theme file rather than downgrading to 1.57.0

`overrides: {
    MuiTableCell: {
      root: { width: 'auto !important' }
    }
  }`

**Comment by WangYidao** [comment]
You can use width property on column directly by setting `tableLayout: 'fixed`, while the documentation not updated yet

**Comment by skitsanos** [comment]
Even if you set tableLayout to 'fixed', it wont actually help. Just tested on 2.14.0, 

```
{
    field: 'id',
    title: 'Id',
    headerStyle: {
      width: '5ch',
      backgroundColor: 'red'
    }
  }
```

_width_  was not applied, but _backgroundColor_ was...

**Comment by amanjain14** [comment]
is this fixed yet?

**Comment by South-Paw** [comment]
@amanjain14 no its not. There hasn't been any more releases past 1.57.2

I've rolled back all our tables to 1.57.0 to fix this - I also don't understand how a breaking change like this is being left/ignored for so long (3 months now)

**Comment by uraz** [comment]
You can add `width` property to items in columns array, like so: 

`const columns = [
  { title: 'Title', field: 'fieldName', width: 'auto' },
];`

**Comment by skitsanos** [comment]
@uraz  thanks for the info, with width attrib on column directly it does works, so the width shouldn't be at `headerStyle`

**Comment by South-Paw** [comment]
@uraz cool 👍

Seems to work, but `width` is missing from the material-table `Column` type

**Comment by tadstratford** [comment]
This worked for me.
 cellStyle: {
        width: "25%",
      },
