### ISSUE TITLE
Expand/Collapse all DisplayDetails

### ISSUE THREAD

**Issue by DatChoob** [mbrn/material-table#1626]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**

- Have a way for the entire table to be opened on load for a specific displayDetail.
- 2 buttons to expand and close all display details

**Comment by DanielObara** [comment]
I just found the "defaultExpanded" option boolean. Isn't specific but work for all lines that's what I know for now.

```js
             options={{
                grouping: true,
                exportButton: true,
                exportAllData: true,
                defaultExpanded: true
              }}
```

**Comment by jakeleventhal** [comment]
Bump on this! was just about to make an issue for this. Would love the "Expand all" and "collapse all" buttons

**Comment by jakeleventhal** [comment]
not stale

**Comment by jakeleventhal** [comment]
not stale

**Comment by jakeleventhal** [comment]
not stale

**Comment by jakeleventhal** [comment]
not stale
