### ISSUE TITLE
Cannot check/uncheck initially checked rows, toolbar button not visible

### ISSUE THREAD

**Issue by michalkobelka** [mbrn/material-table#1632]
I have some initially checked rows via `checked: true` prop on the rowData. This works fine, the rows are checked by default. I have the selection set up like this:

```
options={{
  selection: true,
  selectionProps: (rowData: any) => ({
    checked: rowData.checked
  })
}}
```

Problem is that I can't check or uncheck rows when they are initially checked or unchecked by the `checked: true/false` prop. Clicking on the checkbox does nothing.

If I only use `checked: true` and I don't set `checked: false` for the rows, than I can check and uncheck those rows without `checked` flag.

What's more, the bulk action for selection (`position: 'toolbarOnSelect'`), which is visible when I select row manually, is not visible for initially checked rows. It seems that initially checked rows are not in selection.

**To Reproduce**
Set up the Material Table for selection. Use `checked: true/false` prop in data provided to material-table, for example:

```
<MaterialTable
  title="Handling Selection Changes Preview"
  columns={[
    { title: 'Name', field: 'name' },
    { title: 'Surname', field: 'surname' },
    { title: 'Birth Year', field: 'birthYear', type: 'numeric' },
    {
      title: 'Birth Place',
      field: 'birthCity',
      lookup: { 34: 'İstanbul', 63: 'Şanlıurfa' }
    }
  ]}
  data={[
    { name: 'Mehmet', surname: 'Baran', birthYear: 1987, birthCity: 63, checked: false },
    { name: 'Zerya Betül', surname: 'Baran', birthYear: 2017, birthCity: 34, checked: false },
    { name: 'Michal', surname: 'Kobelka', birthYear: 2017, birthCity: 34, checked: true }
  ]}
  options={{
    selection: true,
    selectionProps: (rowData: any) => ({
      color: 'primary',
      checked: rowData.checked
    })
  }}
/>
```

**Expected behavior**
Clicking the intially checked row unchecks it. Clicking the initially unchecked row makes it checked.  The button for bulk selection operation should be visible when there are initially checked rows.

**Comment by achillesoo7** [comment]
Hey,
have you tried changing your prop value with the onSelectionChange prop?

If yes, then please share a code snippet of that or it would be great if you can share a code snippet via codesandbox.io

**Comment by michalkobelka** [comment]
@achillesoo7 That is the way I was thinking at first - changing the prop value with `onSelectionChange`. But is it good idea to write all the logic for selecting checkboxes over again just to have some of them initally checked?

And it doesn't solve the problem with button not visible, there seems to be bigger problem with it. It seems initially checked checkboxes are not in the selection.

**Comment by achillesoo7** [comment]
So, what I understood is you are using your own prop to make some boxes initially checked. But when you try to uncheck those, by default material-ui change it's internal attribute, not your props so technically those are still true that is why the value is not getting change.

If I am wrong then it would be great if you can share some code snippet via codesandbox.io
