### ISSUE TITLE
Edit, Add / Delete data not working since 1.40.0 version 

### ISSUE THREAD

**Issue by selfishhari** [mbrn/material-table#1634]
**Describe the bug**
Editable table features are not updating the table in the recent versions.

This is true for the examples provided too

I had to downgrade to 1.40.0, all seems to be good there

**To Reproduce**
1. Go to https://material-table.com/#/docs/features/editable
2. Scroll down to editable example
3. Expand any example and edit/update/delete
4. Takes a few seconds but then you dont see the changes

**Desktop (please complete the following information):**
 - OS: Ubuntu 16
 - chrome

**Additional context**
I checked that the state is being updated correctly, however my conclusion was the table elements were not re rendering after the state change

**Comment by AugustoCalaca** [comment]
this was fixed here: https://github.com/mbrn/material-table.com/pull/18

**Comment by mleffert** [comment]
Any news on when the next release is?
