### ISSUE TITLE
Possibility to focus on row

### ISSUE THREAD

**Issue by akirakotsugai** [mbrn/material-table#1639]
I would like to make rows navigable by the keyboard. I already have a custom selection that changes the background color of the selected row, but apparently changing the selected row from the keyboard is not possible because it is necessary a key down handler in the table. Is it possible to implement that? I could work on that and send a pull request if you say I am allowed. How long does it usually take to have a new release?

**Comment by edubskiy** [comment]
Hi, @akirakotsugai . We also need feature like this. Do you have working solution with keyboard navigation for this component?

**Comment by akirakotsugai** [comment]
@edubskiy No, I found no work around that. What I did was change the internal implementation. I have the rows a tabindex = 0 and created a new prop called "rowsRefs" so I pass all the refs down to the rows, so I can programatically focus on the ref.

**Comment by keemor** [comment]
Hi @edubskiy,

Could you show some examples of how you achieved this? I'm wondering how to connect onKeyboard events

Cheers,

**Comment by edubskiy** [comment]
Hi, @akirakotsugai. Yes, sure, I can give example of how we managed to do row navigation in React.
Main idea:
1. User can click on the row and visually select it and then extract row data to pass to some handler
2. User can push up/down arrow to perform row selection and pass row data to some handler

Here is the code:
```react
class PageWithTable {
  constructor(props: any, context: any) {
    super(props, context);
    this.state = {selectedRow: null};
  }

  componentDidMount(): void {
    if (!this.props.isArrowNavigationDisabled) window.addEventListener("keydown", this.onKeyPress);
  }

  componentWillUnmount(): void {
    if (!this.props.isArrowNavigationDisabled) window.removeEventListener("keydown", this.onKeyPress);
  }

  onRowClick = (e: any, data: any) => {
    const clickedTarget = e.currentTarget as HTMLTableRowElement;
    this.selectRow({data, htmlElement: clickedTarget});
    // onRowClick could be called when user clicked on row
    // or when method click() was called
    // isTrusted is true when user clicked on row with mouse
    // if (e.isTrusted) {
    // }
  };

  onKeyPress = (e: KeyboardEvent) => {
    const button = e.code;
    let selectedRow: HTMLTableRowElement;
    if (button != "ArrowUp" && button != "ArrowDown") return;
    
    if (!this.state.selectedRow) {
      selectedRow = document.querySelector("tr.MuiTableRow-root.MuiTableRow-hover") as HTMLTableRowElement;
    } else if (button == "ArrowUp" && this.state.selectedRow.htmlElement.previousElementSibling) {
      selectedRow = this.state.selectedRow.htmlElement.previousElementSibling as HTMLTableRowElement;
    } else if (button == "ArrowDown" && this.state.selectedRow.htmlElement.nextElementSibling) {
      selectedRow = this.state.selectedRow.htmlElement.nextElementSibling as HTMLTableRowElement;
    } else return;
    
    selectedRow.click()
  };

  selectRow(row: SelectedRow) {
    if (this.state.selectedRow) this.state.selectedRow.htmlElement.classList.remove("selected");
    this.setState({selectedRow: row});
    row.htmlElement.classList.add("selected");
  }

  render() {
    return (
      <div>
        <MaterialTable onRowClick={this.onRowClick} columns={columns}>
          {this.props.children}
        </MaterialTable>
      </div>
    );
  }
}
