### ISSUE TITLE
PageSize dont change if new props in option appear

### ISSUE THREAD

**Issue by orestes22** [mbrn/material-table#1644]
**Describe the bug**
Hi, @mbrn  in material-table.js file, inside the function setDataManagerFields i recommend use the solution 
if( isInit && this.isRemoteData() ) 
{ 
    this.dataManager.changePageSize(props.options.pageSize);
}

This will avoid the problem that the table load the prop pageSize of "option" no matter if pageSize was changed manually. The reason is because if in the code some props are changed dinamically that make the pageSize change. 

For your info, just in case, and save you time
I found the commit where the actual solution was added:
Actual code:
(isInit || this.isRemoteData()) && this.dataManager.changePageSize(props.options.pageSize);

It was added in the commit 6d708f3, because the issues 1353, and released in the version 1.54.1

I checked and still acomplish 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by orestes22** [comment]
I create a pull request: https://github.com/mbrn/material-table/pull/1638

**Comment by nvtin** [comment]
@mbrn Could you have a look at this?
