### ISSUE TITLE
Remove title container

### ISSUE THREAD

**Issue by chitgoks** [mbrn/material-table#1646]
I do not want to place a title on the table, nor any custom actions so currently i have an extra space above the header.

is it possible to remove this? is there an existing option?

showTitle=false removes the title but the container still persists thereby showing an empty row on top of the headers.

**Comment by tlaukkanen** [comment]
@chitgoks any tips how you resolved hiding the container? Having the same problem 😃

**Comment by chitgoks** [comment]
![Screenshot_20200220_233757](https://user-images.githubusercontent.com/3955470/74950479-242d3400-543a-11ea-9832-8aabbd131b98.jpg)
Toolbar

**Comment by Ebram-Tharwat** [comment]
@chitgoks , You can remove the whole toolbar by setting `toolbar: false` (part of table `options`)

**Comment by chitgoks** [comment]
lol ok thats better.

**Comment by royliu007** [comment]
> @chitgoks , You can remove the whole toolbar by setting `toolbar: false` (part of table `options`)
that really what I want :)
