### ISSUE TITLE
Transparent header borders when using maxBodyHeight prop

### ISSUE THREAD

**Issue by Dito-Orkodashvili** [mbrn/material-table#1647]
**Describe the bug**
When you set maxBodyHeight prop and table header becomes sticky, it has transparent borders when scrolling. This is a famous issue with position: 'sticky'

**To Reproduce**
1. Set maxBodyHeight
2. Add rows
3. Scroll down

**Possible fix**
https://stackoverflow.com/questions/50361698/border-style-do-not-work-with-sticky-position-element

The selected answer on this post is working fine. You can add it if you think it's appropriate.

**Comment by ksuraj112** [comment]
@Dito-Orkodashvili Can you share the implementation? I'm having difficulty in modifying css for material-table `table` element
