### ISSUE TITLE
Export as CSV only exports current page

### ISSUE THREAD

**Issue by simernes** [mbrn/material-table#1648]
**Describe the bug**
When enabling export button, even if there are several pages of data, only the current page is exported.

**Comment by achillesoo7** [comment]
Hey @simernes 

Along with export option please write "exportAllData: true" also.

**Comment by simernes** [comment]
Thanks. However, I would argue that the expected default behaviour would be to export all data.

**Comment by itsmeganesh-cse-iiit** [comment]
@simernes , The default export is exporting only visible records only, Can you please check and add a prop as mentioned by @achillesoo7 . Thanks

**Comment by itsmeganesh-cse-iiit** [comment]
@simernes , The prop is avail be in new release thank you ! Can you please close this ticket, otherwise people will think like this issue is still pending . Thanks !
