### ISSUE TITLE
Skeleton

### ISSUE THREAD

**Issue by Angelk90** [mbrn/material-table#1651]
**Is your feature request related to a problem? Please describe.**
It would be an interesting feature to have the skeleton during information loading.

**Describe the solution you'd like**
As a suggestion I suggest:
- The skeleton will be displayed on all elements, TableHead, row, footer, until the information is taken.
- The skeleton will be displayed only on the rows, until the information is taken.
- Or the first time when the table is loaded the skeleton is displayed on TableHead, rows, footer.
When sorting, searching or changing the page, the skeleton is only displayed rows until the information is loaded.

**Additional context**
@mbrn  : 
![](https://pbs.twimg.com/media/EE6hMpbWkAAXsYg.jpg)

**Comment by Angelk90** [comment]
Is there any news?

**Comment by Angelk90** [comment]
Is there any news?

**Comment by Angelk90** [comment]
Is there any news?

**Comment by Angelk90** [comment]
Is there any news?

**Comment by Angelk90** [comment]
Is there any news?

**Comment by iamchathu** [comment]
Is there any update on this?

**Comment by Angelk90** [comment]
Is there any news?

**Comment by Angelk90** [comment]
.
