### ISSUE TITLE
Toggle of details panel doesn't work when invoked from the search

### ISSUE THREAD

**Issue by lukavida** [mbrn/material-table#1653]
When the following code:

```
        this.tableRef.current.onToggleDetailPanel(
            [rowData.tableData.id],
            this.tableRef.current.props.detailPanel[panelToToggle].render
        );
```

 is triggered on an item in search results, a problem occurs:

```
Uncaught TypeError: Cannot read property 'tableData' of undefined
    at DataManager.changeDetailPanelVisibility (data-manager.js:399)
```

The cause of the error is on the following line:
https://github.com/mbrn/material-table/blob/master/src/utils/data-manager.js#L154

`this.findDataByPath()` doesn't find anything since `this.sortedData` is array containing only matching items (starting with index 0), while the `path` contains `rowData.tableData.id` — index of the row before the results were filtered (e.g. 82).

The problem is solved by replacing `this.sortedData` with `this.filteredData`.

**Comment by ingvaldlorentzen** [comment]
I stumbled upon this same issue. I might be able to make a pull request in the future to fix it, if I find the time. Have you considered making a pull request? Seems like you have a pretty clear idea about how to fix it. 

Anyways, I found a workaround that is a variant of the code you provided. 

```js
tableRef.current.onToggleDetailPanel(
         [tableRef.current.dataManager.sortedData.findIndex(item => item.id === rowData.id)],
         tableRef.current.props.detailPanel[0].render)
```

Now, use this workaround at your own risk, it's a bit hacky.   
But basically, what I'm doing is finding the new index of the item in the `sortedData` array. Luckily, I had a unique `id` in the dataset I could easily find, if you don't have any unique fields in your dataset, then I'm not sure how you would go about solving this, but you might be able to figure something out by looking at the data in the `tableRef` or `dataManager` objects.

**Comment by ShoubhikBanerjee** [comment]
can you show a complete code example?

**Comment by ingvaldlorentzen** [comment]
If your using [Hooks](https://reactjs.org/docs/hooks-reference.html#useref), simply initialize the ref hook.
```js
const tableRef = useRef()
```

And add the hook ref object to the table
```
<MaterialTable {...allYouOtherProps} tableRef={tableRef}/>
```

Then you can use the function as shown in the last comment. 

Note that the `tableRef` value is not initialized immediately, so to avoid attempting to get nested values that don't exist from the `tableRef` I personally use [Lodash's](https://lodash.com/) [`get()`](https://lodash.com/docs/4.17.15#get) function with a default value.
