### ISSUE TITLE
Unnecessarily large empty space area when filtering columns 

### ISSUE THREAD

**Issue by urirahimi** [mbrn/material-table#1656]
**Describe the bug**
Take a look at the screenshot attached. Notice that the columnsButton prop is enabled and so is the custom action prop. When deselecting non action columns, there remains a large white space area underneath the action column. It seems like all of the columns are unnecessarily shifted to the right.  

**To Reproduce**
1. Make a material table and populate with 10 columns. Enable columnsButton, and actions
2. Deselect some of the columns and notice the empty white space under the actions column

<img width="1435" alt="Screen Shot 2020-02-15 at 7 34 53 PM copy" src="https://user-images.githubusercontent.com/19512370/74597678-168a3f80-5031-11ea-9078-9691f494168d.png">

**Comment by shamshashmi** [comment]
@urirahimi did you get any solution for the empty space... what i've found is its rendering empty Tr's in table respective to the pageSize value of the table ... regardless to the data size ;(

Please share if you get any solution... Thanks :))

**Comment by jakeleventhal** [comment]
not stale

**Comment by jakeleventhal** [comment]
not stale

**Comment by jakeleventhal** [comment]
no stale

**Comment by TheStu** [comment]
would also like to see a solution to this

**Comment by jakeleventhal** [comment]
not stale
