### ISSUE TITLE
Fixed Rows

### ISSUE THREAD

**Issue by aiosifelis** [mbrn/material-table#1667]
Hey there!
Great component. Good work!

Me and my team were wondering if there's any way to implement frozen/sticky rows in material-table. More specifically we want a functionality where the user is able to pin some rows to the top of the table body and they become fixed while the rest of the rows scroll in the table body. It's basically the opposite of the awesome fixed columns feature that your component has. 

Please let us know if this is doable.

Thanks

**Comment by thedmeyer** [comment]
This would be a great feature

**Comment by benmliang** [comment]
👍
