### ISSUE TITLE
onRowClick doesn't allow to copy/highlight string value

### ISSUE THREAD

**Issue by buhrenduh** [mbrn/material-table#1668]
**Describe the bug**
When implementing **onRowClick**, if I attempt to copy the string value by clicking and highlighting, the onClick action triggers. In my case, the onRowClick opens up a new page so I am not able to copy the string value. In my screenshot, I am trying to copy the date.

**To Reproduce**
1. Implement **onRowClick** that opens a new page
2. Highlight a string value in one of the columns

**Expected behavior**
I should be able to highlight/copy string values/text from the row without triggering the onRowClick event. 

Example, in material-ui (https://v3.material-ui.com/demos/tables/) if you go to **Sorting & Selecting** examples, there is an event click on the row, but I am also able to select and highlight the string.

**Screenshots**
I can't show the whole table, but onRowClick, this will open another page. 
![2020-02-19_12-43-56 (1)](https://user-images.githubusercontent.com/17522220/74874390-be478c00-5315-11ea-8742-6606f96d79f5.gif)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS
 - Browser [e.g. chrome, safari]: Chrome 
 - Version [e.g. 22]: 80.0.3987.106

**Additional context**
I don't know if it's a bug but it would definitely be an appreciated feature!

**Comment by jonasanx** [comment]
I don't think that's related to `material-table`. But here's it what you can do to fix it. 

```js
const handleOnClick = () => {
    const selection = window.getSelection().toString()
    if (selection.length <= 0) {
      doSomething();
    }
}
```
