### ISSUE TITLE
Adding custom component re-renders? the table

### ISSUE THREAD

**Issue by jonasanx** [mbrn/material-table#1669]
There's a modal window that will appear when `onRowClick` is triggered, I have set a `maxBodyHeight` so there a scroll will appear when there are many rows. When I scroll to a certain row and and I click on it, the modal will appear, and the scroll will stay in that position. That works as expected, but here is the thing. If I add a custom component as a container, and then I click on the row, the scroll resets? It goes all way up again. 

1. Without custom container.
```jsx
<MaterialTable
  icons={tableIcons}
  columns={columns}
  options={options}
  localization={localization}
  data={data}
  isLoading={loading}
  actions={actions}
  onRowClick={openDialogView}
/>
```
![without issue](https://i.imgur.com/KILFV8j.png)

2. With custom container
```jsx
<MaterialTable
  components={{ Container: props => <div>{props.children}</div> }}
  icons={tableIcons}
  columns={columns}
  options={options}
  localization={localization}
  data={data}
  isLoading={loading}
  actions={actions}
  onRowClick={openDialogView}
/>
```
![with issue](https://i.imgur.com/ErhJnRZ.png)

Pretty much changing any state resets the scroll position, but that only happens when I add a custom component.

**Comment by jonasanx** [comment]
Ok... so, I think It has to do something from the table being inside a context in my App.  When the Context changes for some reason causes the scroll position to reset.
```jsx
<Context.Provider>
  <AnotherComponent />
  <MaterialTableContainer>
     <MaterialTable />
  </MaterialTableContainer>
</Context.Provider>
```

So what I put the components object inside a useMemo and I think that did the trick, although I am not sure what side effects it may have. 
```jsx
 const components = useMemo(() => {
    return { Container: props => props.children }
  }, [])

  return (
    <MaterialTable
      components={components}
      icons={tableIcons}
      columns={columns}
      options={options}
      localization={localization}
      data={data}
      isLoading={loading}
      actions={actions}
      onRowClick={openDialogView}
    />
  )```

**Comment by Kadrangelion** [comment]
Great turnaround there! I was looking for it for hours ! :o 
I'm gonna add some few keywords so people can find this more easily! 

onClick onAction scrollbar top position reset event onEvent action click hooks material-table

**Comment by blshort43** [comment]
This just saved me a ton of time also. Thanks!!!!
