### ISSUE TITLE
Sharing state between two different tables.

### ISSUE THREAD

**Issue by Teslenk0** [mbrn/material-table#1670]
Hello, 

I have 2 different MTables and i am experiencing a problem when i select one row from one of this tables, it also selects the same one in the other, like they are sharing the index. I am using the same component in both pages, however i tried to differentiate using keys but got same behavior.

I will appreciate if someone can help me :)

**Comment by BerndSchrooten** [comment]
Try cloning the data before passing it to the table component. Material table is mutating the data prop directly which could cause this behavior for you. Following issue is related to this: https://github.com/mbrn/material-table/issues/1371

Hope this helps

**Comment by Teslenk0** [comment]
@BerndSchrooten Oh, i will try this and update you, however the behavior seems to be something like it is sharing the ref for the checkboxes between tables. When one is checked, it also checks in the other table for the same row.

I separated the tables in two different parent components and it works perfect, but i am not reusing 
:(

Thank you for your time!

**Comment by Teslenk0** [comment]
:)
