### ISSUE TITLE
Empty space when paging is set to true

### ISSUE THREAD

**Issue by bilix** [mbrn/material-table#1673]
**Describe the bug**
When paging is set to true, if there are not enough rows to fill the page, there's a huge empty space between the last row and the paging controls.

**Expected behavior**
table height should adapt to its content.

**Screenshots**
![image](https://user-images.githubusercontent.com/1675426/74921566-3bced300-53ce-11ea-9a32-d9238df8b572.png)

**Comment by jonasanx** [comment]
have you used `emptyRowsWhenPaging: false` in options?

**Comment by bilix** [comment]
That made it! 🙈 

Thank you very much! Still, that should probably be de default behaviour.
