### ISSUE TITLE
Material Table with Redux is creating more instances that it should

### ISSUE THREAD

**Issue by Jsalvat** [mbrn/material-table#1674]
**Describe the bug**
Material Table or DND are creating 1 instance extra per table with Redux and every time that u re render any material-table
**To Reproduce**
1. Go to any webapp with material-table and redux
2. Click on redux-devtools

**Expected behavior**
It may only create 1 instance per table, not 2.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser CHROME
 - Version [e.g. 22] Versión 80.0.3987.106 (64 bits)

It creates another instance with this state:
phase(pin):"IDLE"
completed(pin):null
shouldFlush(pin):false

Every time u re render table, it creates another instance.

![Captura de pantalla de 2020-02-20 12-41-29](https://user-images.githubusercontent.com/26542724/74930984-ff57a300-53de-11ea-85e6-e0fdd19a629e.png)

This instance store draggable things from material-table. Now draggable it's true because I was doing some tests. But If I disable draggable, material-table should disable and don't create more instances. I Hope that this screenshot helps to understand what's happening

**Comment by Jsalvat** [comment]
BUMP!

**Comment by oze4** [comment]
> BUMP!

Good luck getting any attention on this - they aren't very responsive in this repo.. [I've had this issue open](https://github.com/mbrn/material-table/issues/930) for a long, long time..

**Comment by Jsalvat** [comment]
bump

**Comment by oze4** [comment]
@Jsalvat the real issue here is with [react-beautiful-dnd](https://github.com/atlassian/react-beautiful-dnd/issues/1437), which is what Material Table uses under the hood.

As this is technically a duplicate issue, you can also check out [this open issue](https://github.com/mbrn/material-table/issues/930) for status updates.

Thank you!

**Comment by yasdev8** [comment]
Hi, I still have this issue and I am on 1.69.3 (material-table), any news?
