### ISSUE TITLE
Immutable data

### ISSUE THREAD

**Issue by hata6502** [mbrn/material-table#1676]
**Is your feature request related to a problem? Please describe.**
Data that propagated to material-table are mutated by creating tableData. 
This may causes other bugs on the outside of material-table. 

**Describe the solution you'd like**
Make propagated data immutable. 
In material-table, make shallow copy of propagated data, and create tableData to copied data. 

**Describe alternatives you've considered**
Add a note to the document  that propagated data are mutated. 
https://material-table.com/#/docs/all-props

**Comment by proutek** [comment]
See https://github.com/mbrn/material-table/issues/1371

**Comment by hata6502** [comment]
Thank you
