### ISSUE TITLE
Hide column

### ISSUE THREAD

**Issue by ytebboune** [mbrn/material-table#1677]
Hello, is there a way to have a hidden column ?
I have an id column that needs to be posted, but I don't want it to be displayed to users. 
I tried to set column the type: "hidden" but it doesn't work. 
I also tried to display:none as cellstyle and headerstyle, but the fact is that when we add a row with "plus" it shows the input to fill it.
I don't want the user to fill it, I only want datas that I prefilled on my table to have an ID, not the other ones.

How can I hide a column ?

**Comment by jonasanx** [comment]
This should work.

```jsx
    <MaterialTable
      columns={[
        {
          title: 'Provider',
          field: 'provider',
          hidden: true
        }
      ]}
    />
```

**Comment by ytebboune** [comment]
Thanks you :)

**Comment by flora8984461** [comment]
I am also wondering if there is a way to hide column if my current data does not has the field? (The data is dynamic) Current behavior is it will show an empty column.

Thanks!

**Comment by prateekpareekvyas** [comment]
how i can get this hide columns data

**Comment by neaRRRRR** [comment]
> 

Did you find any way to do that?
