### ISSUE TITLE
Bug in show and hide columns if the property selection is true

### ISSUE THREAD

**Issue by orestes22** [mbrn/material-table#1678]
**Describe the bug**
There is a bug with the table that the columns align to right when you hide a columns throw the menu in the toolbar. 

**To Reproduce**
1. Add to "option" the properties "selection:true" and "columnsButton: true"
2. After that click the menu in the toolbar and hide some columns and you will see how all the columns aligned to right.

Check this example https://codesandbox.io/s/issues-material-table-with-the-columns-3v70d

**Expected behavior**
The behavior have to be like when the selection property is false

**Screenshots**
https://codesandbox.io/s/issues-material-table-with-the-columns-3v70d

**Desktop (please complete the following information):**
 - OS: [window]
 - Browser [crome]
 - Version [1.57.2]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by orestes22** [comment]
You can reproduce this bug too in the demo.js file inside of the Material-Table project. 
@mbrn

**Comment by Domino987** [comment]
This could also be fixed by passing `tableLayout: fixed` in options.

**Comment by orestes22** [comment]
@Domino987  I tried that but it is a terrible solution because you lose the responsive in the table when you using a mobile.
