### ISSUE TITLE
Doesn't work with IE 11

### ISSUE THREAD

**Issue by SakatoShogo** [mbrn/material-table#1679]
**Describe the bug**
The components use APIs that are not available in IE 11.

**To Reproduce**
Visit one of the links with IE11.
[https://material-ui.com/components/tables/](url)

**Expected behavior**
No errors.

**Screenshots**
![error](https://user-images.githubusercontent.com/44148544/75004819-bfacbc00-54af-11ea-9e06-313a164d5f05.PNG)

**Comment by ymihir** [comment]
This is really not good. I am not sure if they mentioned anywhere in their web site for these issues.

**Comment by baileytincher** [comment]
IE 11 has been EOL for 5 years. I'd argue this is a user error for still using IE 11 than is a "bug"
