### ISSUE TITLE
Fixed column prop leading to misalignment

### ISSUE THREAD

**Issue by urirahimi** [mbrn/material-table#1686]
**Describe the bug**
When implementing the fixed column prop on material table with custom render data the 

**To Reproduce**
1. Create a material table with 10 or so custom rendered columns. Include an image in the custom render method for the column that is to be fixed.
2. Notice that the fixed column with images becomes misaligned to the rest of the columns. Also, the fixed column doesn't extend all the way down to the page. 

<img width="591" alt="Screen Shot 2020-02-22 at 2 18 44 PM" src="https://user-images.githubusercontent.com/19512370/75097932-6c556f00-557e-11ea-822c-c432d3d5e81a.png">
<img width="1411" alt="Screen Shot 2020-02-22 at 2 01 55 PM" src="https://user-images.githubusercontent.com/19512370/75097933-6cee0580-557e-11ea-999e-bd7dfedff747.png">

**Comment by jakeleventhal** [comment]
not stale

**Comment by jakeleventhal** [comment]
no stale

**Comment by jakeleventhal** [comment]
not stale

**Comment by jakeleventhal** [comment]
not stale

**Comment by jakeleventhal** [comment]
not stale

**Comment by janderson215** [comment]
@jakeleventhal you're the man.

Still not stale.
