### ISSUE TITLE
HeaderStyle is not respected when hover over Table Header

### ISSUE THREAD

**Issue by mkkhedawat** [mbrn/material-table#1687]
**Describe the bug**
On hover on TH, header style is overridden by default styles

**To Reproduce**
1. Go to 'https://material-table.com/#/docs/features/styling'
2. Click on 'https://material-table.com/#/docs/features/styling'
3. Observe that color of text 'surname' is white
4. Hover over it, the color becomes black which is a violation of headerStyle

**Expected behavior**
It should remain white

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] ALL

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mkkhedawat** [comment]
^ Bump

**Comment by Amritpd** [comment]
Bump

**Comment by ssinov00** [comment]
Bump

**Comment by evrii** [comment]
Any updates on this?
