### ISSUE TITLE
Avoid table headers moving when filtering to an empty table and rows have detailPanel enabled

### ISSUE THREAD

**Issue by guidola** [mbrn/material-table#1689]

**Comment by Domino987** [comment]
Please provide a detailed description or close the issue, since the title is not detailed enough.

**Comment by guidola** [comment]
Headers with 0 results after searching:
![image](https://user-images.githubusercontent.com/11554611/78240083-c67f1380-74de-11ea-9ea6-492f58f4d3b8.png)

Headers without filtering the table:
![image](https://user-images.githubusercontent.com/11554611/78240113-d4349900-74de-11ea-8dad-349dd50946b7.png)

Table rows have detailPanel set and hence the button that allows to open/close the panel makes the headers shift as the row is added.

**Comment by ghyoo91** [comment]
I think I have same problem.
Header with 0 results doesn't look the same as the when some results exist or before searching.
Maybe there are some CSS issues when the empty searching result shown.

![header_moving](https://user-images.githubusercontent.com/20279300/80585204-dc381800-8a4d-11ea-9728-4701c8adeef5.gif)

**Comment by feroult** [comment]
This is how I solved:

**Custom container:**

```javascript
components={{
    Container: props => <Paper {...props} className={classes.paper} />
}}
```

**Style:**

```javascript
const useStyles = makeStyles((theme) => ({
    paper: {
        '& thead th:first-child': {
            minWidth: '120px'
        }
    }
}));
```
