### ISSUE TITLE
How change this colors?

### ISSUE THREAD

**Issue by JoeKyy** [mbrn/material-table#169]
![intimacoes beta 1](https://user-images.githubusercontent.com/2018763/51393903-0519ef80-1b20-11e9-81e7-d3aa736f4a0c.png)

How i change this color? I was trying to search this on the documentation and the issues tab and didn't find it

**Comment by mbrn** [comment]
This is related with your theme. 
https://material-ui.com/customization/themes/

Example: 
```javascript
import { MuiThemeProvider, createMuiTheme } from '@material-ui/core/styles';
import blue from '@material-ui/core/colors/blue';

const theme = createMuiTheme({
  palette: {
    secondary: { main: '#11cb5f' }
  },
});

// Use MuiThemeProvider root of your application to effect everything on your application. 
<MuiThemeProvider theme={theme}>
          <MaterialTable ....../>
</MuiThemeProvider>
        
```
