### ISSUE TITLE
How to remove padding from the Toolbar (Title)

### ISSUE THREAD

**Issue by g3n35i5** [mbrn/material-table#1690]
I can't manage to remove the toolbar padding so that the title is left aligned with the table.
The component `<MTableToolbar />` creates the Material UI component `<Toolbar />` as a child. To remove the padding there, the property `disableGutters: true` must be passed. This is not done by the parent component. Is there another way to remove the padding?

I have read the [documentation](https://material-table.com/#/docs/features/component-overriding) but I cannot remove the padding via style classes.

**Comment by jonasanx** [comment]
I don't recommend this but you can totally modify the way MTableToolbar behaves. You only have to make a copy of it and use it as a custom component. There you can modify everything you want. 
  ```jsx
<MaterialTable
      components={{
        Toolbar: props => <CustomMTableToolbar {...props} />
      }} />
```

**Comment by g3n35i5** [comment]
Many thanks for your reply!
The problem with your solution is that I have to re-implement the complete behaviour of the MTableToolbar (actions, search, title, ...). I am looking for a way to use the toolbar as it is. Just stop with the property `disableGutters: true` on the Material-UI Toolbar.

**Comment by Androsv96** [comment]
It is not neccesary to re-implement the complete behaviour of the components. After overriding Toolbar actions keeps the same, searchs keeps the same. This way you can set the title you want and css it as you want. Don't forget to pass the {...props} to the MtableToolbar. Example:
```javascript
<MaterialTable
    components={
      Toolbar: props => (
        <MTableTooolbar {...props} />
         //Your Box, Buttons, etc.
)
}
/>
```

**Comment by g3n35i5** [comment]
This only works if I apply this patch [in this file](https://github.com/mbrn/material-table/blob/3499b134c2b2ac08b54cfec4fe6bc406108beac1/src/components/m-table-toolbar.js#L216), isn't it?

``` patch
-      <Toolbar className={classNames(classes.root, { [classes.highlight]: this.props.showTextRowsSelected && this.props.selectedRows && this.props.selectedRows.length > 0 })}>
+      <Toolbar {{...classes}} className={classNames(classes.root, { [classes.highlight]: this.props.showTextRowsSelected && this.props.selectedRows && this.props.selectedRows.length > 0 })}>
```

**Comment by Androsv96** [comment]
Try this:
```javascript
import MaterialTable, { MTableToolbar } from 'material-table';

then

<MaterialTable
    components={
      Toolbar: props => (
        <MTableTooolbar {...props} />
         //Your Box, Buttons, etc.
)
}
/>

```

**Comment by g3n35i5** [comment]
@Androsv96 I tried, but this only renders the default toolbar with additional elements.

**Comment by Androsv96** [comment]
I think I misunderstood your question so I was offering a wrong solution. After trying for a few minutes I don't see how to get rid of the padding in the title. :'/

**Comment by g3n35i5** [comment]
So, is there any other solution?

**Comment by oze4** [comment]
@g3n35i5 what do you mean by 

>  so that the title is left aligned with the table.

Is it not already aligned with the table on the left hand side?

**Comment by g3n35i5** [comment]
@oze4 i want to remove the padding (red circle) so that the title is left aligned with the first column title so that it looks like the bottom example:

![TableWithoutPadding](https://user-images.githubusercontent.com/17593457/77231249-03234480-6b9a-11ea-8474-2414719c6a61.png)

**Comment by oze4** [comment]
You may need to play with the styling but something like this should do the trick.. 

The key is to grab the `MTableToolbar` props prior to passing them into the component, and setting `propsCopy.showTitle = false;`.  This way `MTableToolbar` does not show the default title and you can supply your own.  It is easiest to put the title in a `Grid` with the `MTableToolbar` so they still appear next to eachother.

<img width="198" alt="image" src="https://user-images.githubusercontent.com/21092343/77231992-5d0d1580-6b6c-11ea-997b-c1f6e8e3998a.png">

## [You can find a live demo here](https://stackblitz.com/edit/react-j3vazw?embed=1&file=AppTable.js)

Please let me know if you have any questions.

```javascript
import React, { useState } from "react";
import MaterialTable, { MTableToolbar } from "material-table";
import tableIcons from "./TableIcons.js";
import { Typography, Grid } from '@material-ui/core';

const originalData = ["Rock", "Paper", "Scissors"].map(word => ({
  id: Math.floor(Math.random() * 300),
  name: word
}));

export default function AppTable() {
  const [data, setData] = useState(originalData);

  return (
    <MaterialTable
      data={data}
      icons={tableIcons}
      columns={[
        {
          title: "Id",
          field: "id"
        },
        {
          title: "Name",
          field: "name"
        }
      ]}
      components={{
        Toolbar: props => {
          // Make a copy of props so we can hide the default title and show our own
          // This let's us use our own Title while keeping the search
          const propsCopy = { ...props };
          // Hide default title
          propsCopy.showTitle = false;
          return (
            <Grid container direction="row">
              <Grid item xs={6}>
                <h2>Some Table Title</h2>
              </Grid>
              <Grid item xs={6}>
                <MTableToolbar {...propsCopy} />
              </Grid>
            </Grid>
          );
        }
      }}
    />
  );
}
```

**Comment by g3n35i5** [comment]
It works, wonderful! Thank you very much for your answer @oze4. I don't think this is the most elegant solution (the padding should be configurable in my opinion...), but so far it's enough for my purposes.

**Comment by oze4** [comment]
@g3n35i5 I most certainly agree - having some native, built-in way to edit the styling on the Toolbar would be ideal.  Unfortunately, this 'hack' is all I could find. (Keep in mind material-table is meant to be 'hacky' and extensible like this)..

[It does appear there are native ways to edit styling](https://material-table.com/#/docs/features/styling), just not for the Toolbar, sadly.

**Comment by alex-enchi** [comment]
You can override styles. Toolbar has these classes 
`MuiToolbar-root MuiToolbar-regular MuiToolbar-gutters` there might be a problem if class names will change in the future.
```
const useStyles = makeStyles((theme) => ({
    toolbarWrapper: {
        '& .MuiToolbar-gutters': {
            paddingLeft: 0,
            paddingRight: 0,
        }
    },
}))
```
Components settings
```
Toolbar: (props) => <div className={classes.toolbarWrapper}><MTableToolbar {...props}/></div>,
```

**Comment by oze4** [comment]
@alex-enchi well yeah, you can "override styles" like that but it's really no different than my example. Still have to provide a custom component. 

Material table allows you to easily override styles for certain items via props, etc without having to override an entire component. That's the point we were making.

**Comment by alex-enchi** [comment]
@oze4 , not arguing here. Passing styles and class names to components would be a much preferable solution. I would love to pass `Toolbar` props, since it is the main wrapper in `MTableToolbar` 

I just decided to write out a workaround with styles + small wrapper component instead of hiding part of the toolbar and re-render it. It is opinionated though.

**Comment by oze4** [comment]
@alex-enchi but you must realize your example also "re-renders" the toolbar... Anyhow, thanks for the example!

**Comment by g3n35i5** [comment]
Thanks for all the answers and your feedback! Both solutions work very well, as long as the developers do not implement the possibility to customize the toolbar, these are definitely good ways. 

As far as I understand it, [issues are prioritized by the number of reactions](https://github.com/mbrn/material-table#issue-prioritizing) so everybody keep a thumb up/down/left/right so the issue will be processed at some point :smile:

**Comment by oze4** [comment]
@g3n35i5 Material Table was designed to allow for this "overriding" type of behavior.  You can currently completely customize the Toolbar (or any main component).

There are currently multiple solutions for this issue from what I can see.
