### ISSUE TITLE
Unnecessary Table padding on the selection of  pagination 

### ISSUE THREAD

**Issue by chetankumars** [mbrn/material-table#1693]
**Describe the bug**
Table padding is goes on increasing without the data body on the selection of pagination

Could it possible to limit the increasing or fix the body data padding on selection of any pagination row data.
I have 3 records, if i choose  20 row selection, i want to limit the fixed body size.
<img width="941" alt="materialTable" src="https://user-images.githubusercontent.com/5195705/75215502-445f4900-57d4-11ea-8c39-b7d74953bc72.png">

**Comment by Androsv96** [comment]
You can modify maxBodyHeight  and minBodyHeight inside options props given to material table. Example:
```javascript
<MaterialTable 
    columns = {yourColumns}
    data = {yourData}
    options = {maxBodyHeight : 10, minBodyHeight : 10}
/>
```
This will set max and min body height. And if you want to change it again after getting your data, you can do it through a ternary.

**Comment by chetankumars** [comment]
Thank you

**Comment by viseshrp** [comment]
@Androsv96 Sorry, but I don't understand how that fixes the issue. The table is expected to resize based on its content. How is it possible to predict the right body height and set it dynamically every time?
@chetankumars can you please reopen this?

**Comment by viseshrp** [comment]
I noticed even if you do set the body dimensions, the table makes the content scrollable and still has that extra padding, if you select a number of rows greater than the content that is displayed. You will see the padding when you scroll down the body. This is still a bug.

**Comment by patrickp-dev** [comment]
@chetankumars there's an `emptyRowsWhenPaging` property in the [table options](https://material-table.com/#/docs/all-props) that controls whether the empty rows are rendered or not. It defaults to true so setting it to
`
options={
  ...otherOptions,
  emptyRowsWhenPaging: false,
}
`

should fix the issue.

**Comment by hosmanadam** [comment]
@patrickp-dev Thanks, that helped. It seems silly that this option defaults to true, it definitely looks weird.

**Comment by kishore-s-15** [comment]
@patrickp-dev Thanks.
