### ISSUE TITLE
In V 1.57.2 - > New Row Data not added to table data

### ISSUE THREAD

**Issue by itsmeganesh-cse-iiit** [mbrn/material-table#1694]
**Describe the bug**
In v 1.57.2 - > when I am trying to add new row, row is not adding to the table

**To Reproduce**
1. Go to 'Click New row'
2. Click on 'insert data'
3. Click save
4. loading bar and after nothing will be saved

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 80.0

**Smartphone (please complete the following information):**

**Additional context**

**Comment by itsmeganesh-cse-iiit** [comment]
**Problem faced :** OnRowadd I mutated the state and re rendered the state using set State and force update but not working.

**Resolution:**  Immutable concept then re rendered the state working as expected

**Comment by lunf** [comment]
You might need to update the sample code.

Thank you,
