### ISSUE TITLE
Not able to change style and order for checkbox column when "selection is set to true"

### ISSUE THREAD

**Issue by vaibhav-sharma-by** [mbrn/material-table#1695]
When we set "selection" property is set to true, then we always get checkbox as the first column, we cant change the order of the column. We have a use case in which we have an color indicator before selection column. I could not find a way to reorder the column, I thought to style the checkbox column with custom style to add color indicator in the same cell but I did not find a way.
<img width="916" alt="Screen Shot 2020-02-26 at 11 04 16 AM" src="https://user-images.githubusercontent.com/57350863/75315122-cd838800-5887-11ea-8f66-af0385f693f2.png">

**Comment by sm3sher** [comment]
I am looking for something similar

**Comment by elhoucine** [comment]
Seems like a bug, you cannot override the styles of this element.
