### ISSUE TITLE
Free Action trigger the native OverlayLoading component

### ISSUE THREAD

**Issue by LuisPinaSoares** [mbrn/material-table#1697]
Hi,

I have a free action that collects a few modifications done on table and then bundle saves them.
This free action returns a Promise.all of creates, updates and deletes...
I would like to trigger the native loader while Promise hasn't been resolved, like it's done in a typical row save (addRow or other).
What would be the best way to achieve this.

Thanks in advance!

**Comment by Androsv96** [comment]
Hello, I don't know if it is the best approach but you may use the isLoading prop to solve your problem, here is an example:
https://codesandbox.io/s/lucid-sun-k1ngq

**Comment by LuisPinaSoares** [comment]
Nice, that will suffice. Thanks!

**Comment by LuminousIT** [comment]
> Hello, I don't know if it is the best approach but you may use the isLoading prop to solve your problem, here is an example:
> https://codesandbox.io/s/lucid-sun-k1ngq

There's no example code in this link anymore
