### ISSUE TITLE
First/Action/Detail-expander column allocating most of table width

### ISSUE THREAD

**Issue by thelazydogsback** [mbrn/material-table#1700]
As shown below, the fist column that contains the detail expander is taking up quite a bit of table width.  I think this only started happening when I updated to the latest version that is supposed to fix isEditable().

![image](https://user-images.githubusercontent.com/4603468/75406058-50c2cf00-58c4-11ea-8a93-e22431ba97e7.png)

**Comment by jeffsupancic** [comment]
@thelazydogsback We're expierincing the same issue.  We may be able to look into this eventually look into.
