### ISSUE TITLE
Clear icon is not working for me

### ISSUE THREAD

**Issue by Ruchi1990** [mbrn/material-table#1701]
Clear icon is not working its showing label, not icon

**Comment by Domino987** [comment]
Can you show some of your code? What do you exactly want to do?

**Comment by jaimealv994** [comment]
You are probably using the wrong icon property, there are two icons (Clear, ResetSearch) that show the same label (clear) when the icon is missing.

![image](https://user-images.githubusercontent.com/36939361/76723983-e9ec4500-670e-11ea-9be1-834121166a4b.png)
