### ISSUE TITLE
custom column rendering and editable:never causing error on adding...

### ISSUE THREAD

**Issue by Mizan-Rifat** [mbrn/material-table#1706]
i've created a column for image.so i made it custom rendering and also made it editable:never.now when i want to add a new row it gives an error.
it shows:

> An error has occurred while a drag is occurring.Any existing drag will be cancelled.> Uncaught TypeError: Cannot read property 'image' of undefined

how to solve this?

**Comment by Domino987** [comment]
Can you share some of your code?
