### ISSUE TITLE
Selection in grouping gives "NaN is an invalid value for the `marginLeft` css style property" warning

### ISSUE THREAD

**Issue by proohit** [mbrn/material-table#1707]
**Describe the bug**
When I enable grouping of rows and selection, everytime I expand the group this warning shows up.

**To Reproduce**
I recreated a simple example from the grouping in the documentation and added selection, when the warning appears. [codesandbox](https://codesandbox.io/s/wonderful-keller-bkqhr?fontsize=14&hidenavigation=1&theme=dark) Try to expand a group and then check the console

**Expected behavior**
No warning when expanding group

**Screenshots**
![image](https://user-images.githubusercontent.com/46965017/75623438-3d588200-5baa-11ea-85c6-3db65b2f7ef1.png)

**Additional context**
To further troubleshoot,  I:
1. disabled grouping but enabled selection. No errors/warnings and expected behaviour
2. enabled grouping and disabled selection. Also no errors/warnings and expected behaviour

**Comment by oze4** [comment]
Pretty sure either [this line](https://github.com/mbrn/material-table/blob/master/src/components/m-table-body-row.js#L57) or [this line](https://github.com/mbrn/material-table/blob/master/src/components/m-table-body-row.js#L60) is why this error is happening..

**Comment by oze4** [comment]
@proohit I just tested a fix for this, confirmed that the fix works, and submitted a PR.

**Comment by proohit** [comment]
@oze4 sounds good, thank you. Let's hope for @mbrn to accept the PR. Seems rather busy isn't he?

**Comment by masbaehr** [comment]
Also having this issue, and the PR fix did work ;)

**Comment by oze4** [comment]
***REMINDER FOR MYSELF***

Resubmit PR for m-table-body-row - these changes had to be removed from the PR referenced above.

**Comment by Domino987** [comment]
Is this fixed?

**Comment by oze4** [comment]
@Domino987 we can close it out if got these changes in a diff PR that hasn't been submitted yet.

**Comment by kylenguyen1014** [comment]
@oze4 Is it fixed yet? I update material-table from 1.59.0 to 1.64.0 and the error is still there

**Comment by PedrinhowVieira** [comment]
Yeah, I can confirm, the warning is still here.
"react": "^16.12.0"
"material-table": "^1.64.0"

**Comment by masbaehr** [comment]
Unfortunately still experiencing! 

"material-table": "^1.68.0",
"react": "^16.13.1",


index.js:1406 Warning: `NaN` is an invalid value for the `marginLeft` css style property.
    in span (created by ForwardRef(ButtonBase))
    in ForwardRef(ButtonBase) (created by WithStyles(ForwardRef(ButtonBase)))
    in WithStyles(ForwardRef(ButtonBase)) (created by ForwardRef(IconButton))
    in ForwardRef(IconButton) (created by WithStyles(ForwardRef(IconButton)))
    in WithStyles(ForwardRef(IconButton)) (created by ForwardRef(SwitchBase))
    in ForwardRef(SwitchBase) (created by WithStyles(ForwardRef(SwitchBase)))
    in WithStyles(ForwardRef(SwitchBase)) (created by ForwardRef(Checkbox))
    in ForwardRef(Checkbox) (created by WithStyles(ForwardRef(Checkbox)))
    in WithStyles(ForwardRef(Checkbox)) (created by MTableBodyRow)
    in td (created by ForwardRef(TableCell))
    in ForwardRef(TableCell) (created by WithStyles(ForwardRef(TableCell)))
    in WithStyles(ForwardRef(TableCell)) (created by MTableBodyRow)
    in tr (created by ForwardRef(TableRow))
    in ForwardRef(TableRow) (created by WithStyles(ForwardRef(TableRow)))
    in WithStyles(ForwardRef(TableRow)) (created by MTableBodyRow)
    in MTableBodyRow (created by MTableGroupRow)
    in MTableGroupRow (created by MTableBody)
    in tbody (created by ForwardRef(TableBody))

**Comment by maxim-s-barabash** [comment]
@oze4 please reopen this.
