### ISSUE TITLE
how to import data from excel using react-excel-renderer

### ISSUE THREAD

**Issue by mirkarpude** [mbrn/material-table#1709]
Please give some example

**Comment by karanness86** [comment]
hey @mirkarpude i have used the below example to read through an excel/csv and then display the data in material table. Hope it helps. 

http://musttoknow.com/how-to-upload-file-in-react-js-application/ 
https://stackoverflow.com/questions/46909260/reading-excel-file-in-reactjs

**Comment by mirkarpude** [comment]
Thankyou
