### ISSUE TITLE
prevent empty rows from being entered

### ISSUE THREAD

**Issue by Marcioshub** [mbrn/material-table#1710]
Hi, im trying to prevent empty rows from being entered but it seems like it didn't work. I tried adding this:

`onRowAdd: newData =>
              newData === {}
                ? null
                : new Promise(resolve => {
                    console.log(newData);
                    setTimeout(() => {
                      resolve();
                      setState(prevState => {
                        const data = [...prevState.data];
                        data.push(newData);
                        return { ...prevState, data };
                      });
                    }, 600);
                  }),`

even if the newData is empty it still enters it.

**Comment by achillesoo7** [comment]
@Marcioshub try rejecting the promise if the data is invalid.

**Comment by Marcioshub** [comment]
i just did this following and it worked:

`
if (newData.email === undefined) {
                    console.log("inside if", newData.email);
                    return { ...prevState };
                  } else {
                    console.log("inside else", newData.email);
                    data.push(newData);
                    // add to firebase
                    addEmployee(newData);
                    return { ...prevState, data };
                  }
`
