### ISSUE TITLE
Debounce search query change when using remote data

### ISSUE THREAD

**Issue by Cristy94** [mbrn/material-table#1711]
**Is your feature request related to a problem? Please describe.**
When using remote data and searching using the search field a new fetch request is started after each keystroke. So when you type a longer word you make tens of requests to the server, when you actually just wanted to search for one word, this makes the table freeze for a long time and it spams the server.

**Describe the solution you'd like**
Have a `searchTimeout` option to debounce the search change event. A good default value would be 1-2 seconds.

**Describe alternatives you've considered**
Maybe have the option to search on submit instead of keystroke.

**Additional context**
Maybe it is related to this issue: https://github.com/mbrn/material-table/issues/1429

**Comment by Domino987** [comment]
As written in the [docs](https://material-table.com/#/docs/all-props), you can set it in the options:
`
debounceInterval | number | 200 | debounce interval for search and filter
`

**Comment by Cristy94** [comment]
Thanks a lot! I actually did a lot of googling and searching before and I didn't find that option. I was mostly looking at the examples, maybe it would be a good idea to add one example with it as it's always necessary when using remote data.
