### ISSUE TITLE
Displaying alert for confirmation on custom action

### ISSUE THREAD

**Issue by techyrajeev** [mbrn/material-table#1712]
Alert or Dialog support for any custom action
based on flag e.g showDialog: true, dialogueTitle:"Dialogue title", dialogueDesc:""

**Comment by Androsv96** [comment]
I may not be understanding your question but you are able to add whatever action you want to do after user clicks on your custom action.
```javascript
actions={[
    rowData => ({
      icon: AddBox,
      tooltip: 'Add',
      onClick: (event, rowData) => { ()=> alert(''Whatever)}
    })
]}
```

**Comment by techyrajeev** [comment]
Not a simple alert.
A confirmational material ui dialog

<Dialog
        open={open}
        onClose={handleClose}
        aria-labelledby="alert-dialog-title"
        aria-describedby="alert-dialog-description"
      >
        <DialogTitle id="alert-dialog-title">{"Use Google's location service?"}</DialogTitle>
        <DialogContent>
          <DialogContentText id="alert-dialog-description">
            Let Google help apps determine location. This means sending anonymous location data to
            Google, even when no apps are running.
          </DialogContentText>
        </DialogContent>
        <DialogActions>
          <Button onClick={handleClose} color="primary">
            Disagree
          </Button>
          <Button onClick={handleClose} color="primary" autoFocus>
            Agree
          </Button>
        </DialogActions>
      </Dialog>

**Comment by Androsv96** [comment]
If you want to show that Dialog when user clicks on the Add button I will suggest you to do the following:
Use useState hook to create a flag:
```javascript
const [showDialog, setShowDialog] = useState(false);
```
Now, when the user clicks on the button, instead of displaying the alert as in my example above use the setShowDialog(true) to change the state.
Now in your Dialog: 
```javascript
<Dialog
        open={showDialog}
></Dialog>
```

So each time the user clicks on the add button, the dialog will be displayed.
