### ISSUE TITLE
Importing the json array list into editable

### ISSUE THREAD

**Issue by turkdoktoru** [mbrn/material-table#1714]
Hello,

I am using react js.
**this.state = {
      drBounty: []
}**

I have a json array list named drBounty.
I want to import this list into MaterialTable and add, update, delete and cancel in the table.
However, I cannot import the json array list I have received as a list. can you help me ?

`          

            <MaterialTable
              columns={[{title: "id", field: "id"}]}
              data={
               [ {id: drBounty.map(items => items.id)} ]
              }
              editable={{
                isEditable: rowData => rowData.name === "a", // only name(a) rows would be editable
                isDeletable: rowData => rowData.name === "b", // only name(a) rows would be deletable
                onRowAdd: newData =>
                  new Promise((resolve, reject) => {
                    setTimeout(() => {
                      {
                        /* const data = this.state.data;
                        data.push(newData);
                        this.setState({ data }, () => resolve()); */
                      }
                      resolve();
                    }, 1000);
                  }),
                onRowUpdate: (newData, oldData) =>
                  new Promise((resolve, reject) => {
                    setTimeout(() => {
                      {
                        /* const data = this.state.data;
                        const index = data.indexOf(oldData);
                        data[index] = newData;
                        this.setState({ data }, () => resolve()); */
                      }
                      resolve();
                    }, 1000);
                  }),
                onRowDelete: oldData =>
                  new Promise((resolve, reject) => {
                    setTimeout(() => {
                      {
                        /* let data = this.state.data;
                        const index = data.indexOf(oldData);
                        data.splice(index, 1);
                        this.setState({ data }, () => resolve()); */
                      }
                      resolve();
                    }, 1000);
                  })
              }}
            />
`

**Comment by Androsv96** [comment]
What's your drBounty structure looks like?
