### ISSUE TITLE
table style column and row height + cut long characters

### ISSUE THREAD

**Issue by turkdoktoru** [mbrn/material-table#1716]
Hello,

How can I get the columns closer together like in the picture?
I also have a description field. How can I shorten long articles? So after 15 characters, you make it look like ...

Although I tried many ways, I could not bring the columns closer together.
Also, I could not shorten the long lines.  (**_white-space: nowrap;_**)

https://ibb.co/QpgZDrp
[https://ibb.co/QpgZDrp](url)

**Comment by turkdoktoru** [comment]
`

     this.state = {
      columns: [
        { title: 'id', field: 'id' },
        { title: 'doctorName', field: 'doctorName'},
        { title: 'doctorLastName', field: 'doctorLastName'},
        { title: 'totalBounty', field: 'totalBounty'},
        { title: 'description', field: 'description', cellStyle:{wordBreak: 'break-all'}}
      ]
     }
`

`

            <MaterialTable
              options={{
                toolbar: false,
                paging: false,
                headerStyle:{ backgroundColor: 'red', padding: '0'},
                rowStyle: { width: '10px' }
              }}
              title={"Bounty table"}
              style={{height: "50", width: "10"}}
              columns={ this.state.columns }
              data={ this.state.drBounty }
`

**Comment by LChris94** [comment]
Some notice from this topic? I have the same problems

**Comment by turkdoktoru** [comment]
no solution?
can you help me ?
I want to zoom in on the columns and adjust the height.

**Comment by shubuu97** [comment]
#sameissuefacing

**Comment by shubuu97** [comment]
> Hello,
> 
> How can I get the columns closer together like in the picture?
> I also have a description field. How can I shorten long articles? So after 15 characters, you make it look like ...
> 
> Although I tried many ways, I could not bring the columns closer together.
> Also, I could not shorten the long lines. (**_white-space: nowrap;_**)
> 
> https://ibb.co/QpgZDrp
> [https://ibb.co/QpgZDrp](url)

how did you resolve this issue?
