### ISSUE TITLE
Double header

### ISSUE THREAD

**Issue by patrickscuri** [mbrn/material-table#1718]
Hi,
I'd like to have two headers for the table.

Example:

`
header-0                                     header-1
sub-header-0    sub-header-1    sub-header-2    sub-header-3
content-0          content-1           content-2          content-3
`

I looked into the documentation but I can't find this feature. Thanks

**Comment by Domino987** [comment]
Can you explain that more? Maybe with a picture?

**Comment by joshdaquino** [comment]
I'm looking for this too, I believe @skupak means something like this.
<img width="1669" alt="Screen Shot 2020-03-18 at 15 14 46" src="https://user-images.githubusercontent.com/23712646/76931066-40ce6600-692b-11ea-90a1-7acd8f13c3e3.png">

**Comment by MrChe** [comment]
+1

**Comment by emersonbottero** [comment]
<MaterialTable
        icons={tableIcons}
        columns={columns}
        data={data}
        options={options}
         components={{
        Header: props => {
          console.log(props)
          return (
            <React.Fragment>
                 <thead>
                  <tr class="first">
                    <td colspan="2" style={{background: 'blue', color: 'white', padding: 5}}>Store ABC</td>
                    <td colspan="2" style={{background: 'red', color: 'white', padding: 5}}>Store DEF</td>
                  </tr>
                </thead>
                <MTableHeader {...props} />
            </React.Fragment>
          )},

    }}
      />

**Comment by mtsandeep** [comment]
I am also looking for this feature, to group the columns under one common title. 
The columns prop can be something like this
```javascript

const columns = [
  {
    title: 'column Name 1',
    field: 'column_id1',
  },
  {
    title: 'column Name 2',
    field: 'column_id2',
  },
  {
    // just a title to be used to group the below columns, so no field here
    title: 'column group',
    columns: [
      {
        title: 'Sub column Name',
        field: 'column_sub_id1',
      },
      {
        title: 'Sub column Name',
        field: 'column_sub_id2',
      },
    ],
  },
]
```

**Comment by anshullodha** [comment]
+1
