### ISSUE TITLE
Is posible hide edit options for specific row?

### ISSUE THREAD

**Issue by harold91** [mbrn/material-table#1719]
Hello, I have a configuration like this:

``` js

<MaterialTable
    editable={{
        isEditable: rowData => rowData.name === "a", // only name(a) rows would be editable
        isDeletable: rowData => rowData.name === "b", // only name(a) rows would be deletable
        onRowAdd: newData =>
            new Promise((resolve, reject) => {
                setTimeout(() => {
                    {
                        /* const data = this.state.data;
                        data.push(newData);
                        this.setState({ data }, () => resolve()); */
                    }
                    resolve();
                }, 1000);
            }),
        onRowUpdate: (newData, oldData) =>
            new Promise((resolve, reject) => {
                setTimeout(() => {
                    {
                        /* const data = this.state.data;
                        const index = data.indexOf(oldData);
                        data[index] = newData;                
                        this.setState({ data }, () => resolve()); */
                    }
                    resolve();
                }, 1000);
            }),
 }}
/>

```

And I would like instead of disabling the actions to edit, they will hide.
The row that meets a specific condition does not show the buttons to edit and delete.

Is there any way to make this possible? Thanks.

**Comment by achillesoo7** [comment]
Hey @harold91 

Here is the code snippet for implementing conditional actions.

`actions={[
        {
          icon: 'save',
          tooltip: 'Save User',
          onClick: (event, rowData) => alert("You saved " + rowData.name)
        },
        rowData => ({
          icon: 'delete',
          tooltip: 'Delete User',
          onClick: (event, rowData) => confirm("You want to delete " + rowData.name),
          disabled: rowData.birthYear < 2000
        })
      ]}`

**Comment by harold91** [comment]
Hello @achillesoo7, thanks for your reply.

Your code snippet is for adding actions, and in this way it is possible to hide and disable.

but when you set your table as editable the onRowAdd, onRowUpdate and onRowDelete functions inject your own buttons for each action, and I can only see the option to disable these actions but not hide them, and this is the issue.

**Comment by Sheing** [comment]
Encountered similar issue mentioned by @harold91 , i wanted to conditionally enable edit only if the field value on that specific row meets the criteria.

**Comment by Sheing** [comment]
So after some research, i found out a way to hide it, but that requires you to go into material-table.js file and add  `hidden: calculatedProps.editable.isEditable && !calculatedProps.editable.isEditable(rowData),` in line 663.
