### ISSUE TITLE
Order property on columns

### ISSUE THREAD

**Issue by LuisPerez94** [mbrn/material-table#1720]
**Is your feature request related to a problem? Please describe.**
When I try to put some columns dynamically after one component is mounted this new column is placed on first or last place only.

**Describe the solution you'd like**
I would like to have one property defined on columns properties called "order" wich refer to the index in wich that column should be placed.

**Additional context**
This is because i have columns with lookup's that it has to wait until get some information from a request. After that I can define that columns but i need to place them in the tirdth place,

**Comment by achillesoo7** [comment]
Hey @LuisPerez94 

I completely got your problem but it would be very helpful if you can share a code snippet where you have implemented your lookup column.

**Comment by LuisPerez94** [comment]
> Hey @LuisPerez94
> 
> I completely got your problem but it would be very helpful if you can share a code snippet where you have implemented your lookup column.

Sure, for example what would I have to do if I want to put a middlename column between name and age?

let's suppouse that middlename column data comes from another request and came after the table populate.

at this moment I have to manipulate the columns array inside the component but it's a little bit complicated. It would be great if this logic would be encapsulated by the dependency.

https://codesandbox.io/embed/sweet-frog-000y3?fontsize=14&hidenavigation=1&theme=dark
