### ISSUE TITLE
Access to rowData in DetailPanel.icon

### ISSUE THREAD

**Issue by mindtricksdev** [mbrn/material-table#1725]
I would love to be able to have an icon dependent of the underlying row data.

```
detailPanel={[
          {
            icon: rowData => (
              <img
                src={rowData.img}
              />
            ),
            render: rowData => {
              return rowData.details;
            }
          }
        ]}
```

**Comment by Domino987** [comment]
You can return a function which accepts the rowData:

```
detailPanel={rowData => ({
            icon: <img
                src={rowData.img}
              />
            ),
            render: rowData.details
        })
  }
```

**Comment by mindtricksdev** [comment]
Looks great, I'll give it a try.

Thanks!

**Comment by jan-bogaerts** [comment]
> You can return a function which accepts the rowData:
> 
> ```
> detailPanel={rowData => ({
>             icon: <img
>                 src={rowData.img}
>               />
>             ),
>             render: rowData.details
>         })
>   }
> ```

The function only appears to be called when it tries to expand the detailPanel, not while building the row data. So it expects the content of the detailPanel, not the definition with the icon. Not certain how to correct this?
