### ISSUE TITLE
Determining the tooltip of the buttons on the table

### ISSUE THREAD

**Issue by turkdoktoru** [mbrn/material-table#1726]
Hello,

When I hover over the buttons like "Edit, Delete, Update, Cancel" in the current editing table, I want the tooltip I set.

I also want the message that I set when I do "delete".

`

            <MaterialTable
              Icons={icons}
              options={{
                toolbar: false,
                paging: false,
                headerStyle:{ backgroundColor: 'red', padding: '0px' }
              }}
              title={"Prim tablosu"}

              style={{height: "50", width: "10"}}
              columns={ this.state.columns }
              data={ this.state.drBounty }
              editable={{
                
                onRowAdd: newData =>
                  new Promise((resolve, reject) => {
                    setTimeout(() => {
                      {
                        console.log("tıklandı")
                        /* const data = this.state.data;
                        data.push(newData);
                        this.setState({ data }, () => resolve()); */
                      }
                      resolve();
                    }, 1000);
                  }),
                
                
                onRowUpdate: (newData, oldData) =>
                  new Promise((resolve, reject) => {
                    console.log("tıklandı")
                    setTimeout(() => {
                      {
                        /* const data = this.state.data;
                        const index = data.indexOf(oldData);
                        data[index] = newData;
                        this.setState({ data }, () => resolve()); */
                      }
                      resolve();
                    }, 1000);
                  }),
                onRowDelete: oldData =>
                  new Promise((resolve, reject) => {
                    setTimeout(() => {
                      {
                        /* let data = this.state.data;
                        const index = data.indexOf(oldData);
                        data.splice(index, 1);
                        this.setState({ data }, () => resolve()); */
                      }
                      resolve();
                    }, 1000);
                  })
              }}
            />

`

**Comment by Androsv96** [comment]
Hi, localization prop could solve your problem, check it out here:
https://material-table.com/#/docs/all-props
