### ISSUE TITLE
Editing the selected line on actions

### ISSUE THREAD

**Issue by turkdoktoru** [mbrn/material-table#1727]
When I click on the line with the code below, I want to edit the line I selected. How can I do that.

`

            <MaterialTable
              Icons={icons}
              actions={
                [rowData => ({
                  icon: Edit,
                  tooltip: 'Edit row',
                  onClick: (event, rowData) => {
                    console.log(rowData.id)
                    //edit selected line
                  }
                })]
              }
`

**Comment by Androsv96** [comment]
Based on your code, It seems you don't have the intention of overriding actions prop so you could use editable prop as shown in material table example.
https://material-table.com/#/docs/features/editable

**Comment by turkdoktoru** [comment]
I need editing and deleting in the code below.
actions {

}

**Comment by Domino987** [comment]
You can hack it using the internal data sturcture and force a reload:
```
rowData.tableData.editing = 'update';
this.forceUpdate();
```

**Comment by fatihenerya** [comment]
I tried with the code you provided it was exactly as I wanted.
But after pressing the "update" button, pressing the save or cancel button gives an error.

how can I prevent this?

**Comment by Domino987** [comment]
What error :smiley:

**Comment by fatihenerya** [comment]
[https://ibb.co/LRFrgjD](url)

Hello,

The edit button works well. But when I press the save and cancel buttons, the error appears as below.


`

An error has occurred while a drag is occurring.Any existing drag will be cancelled.> Uncaught TypeError: Cannot read property 'onRowUpdate' of undefined👷‍ This is a development only message. It will be removed in production builds. 
    in MaterialTable (created by Anonymous)
    in Anonymous (created by WithStyles(Component))
    in WithStyles(Component) (at Bounty.js:380)
    in Bounty (at withAuth.js:39)
    in AuthWrapped (created by ConnectFunction)
    in ConnectFunction (at DefaultLayout.js:98)
    in Router.Consumer (created by Route)
    in Route (at DefaultLayout.js:93)
    in DefaultLayout (created by Router.Consumer)
    in Router.Consumer (created by withRouter(DefaultLayout))
    in withRouter(DefaultLayout) (at withAuth.js:39)
    in AuthWrapped (created by ConnectFunction)
    in ConnectFunction (at App.js:52)
    in Router.Consumer (created by Route)
    in Route (at App.js:52)
    in App (created by ConnectFunction)
    in ConnectFunction (at src/​index.js:57)


raw ErrorEvent {isTrusted: true, message: "Uncaught TypeError: Cannot read property 'onRowUpdate' of undefined", filename: "http://localhost:3000/static/js/7.chunk.js", lineno: 66190, colno: 32, …} 
    in MaterialTable (created by Anonymous)
    in Anonymous (created by WithStyles(Component))
    in WithStyles(Component) (at Bounty.js:380)
    in Bounty (at withAuth.js:39)
    in AuthWrapped (created by ConnectFunction)
    in ConnectFunction (at DefaultLayout.js:98)
    in Router.Consumer (created by Route)
    in Route (at DefaultLayout.js:93)
    in DefaultLayout (created by Router.Consumer)
    in Router.Consumer (created by withRouter(DefaultLayout))
    in withRouter(DefaultLayout) (at withAuth.js:39)
    in AuthWrapped (created by ConnectFunction)
    in ConnectFunction (at App.js:52)
    in Router.Consumer (created by Route)
    in Route (at App.js:52)
    in App (created by ConnectFunction)
    in ConnectFunction (at src/​index.js:57)
console.<computed> @ index.js:1437
r @ react_devtools_backend.js:6
printFatalError @ react-beautiful-dnd.esm.js:57
ErrorBoundary._this.onFatalError @ react-beautiful-dnd.esm.js:82
invokeGuardedCallbackDev @ react-dom.development.js:386
invokeGuardedCallback @ react-dom.development.js:439
commitRootImpl @ react-dom.development.js:25078
unstable_runWithPriority @ scheduler.development.js:704
runWithPriority$2 @ react-dom.development.js:12232
commitRoot @ react-dom.development.js:24918
finishSyncRender @ react-dom.development.js:24313
performSyncWorkOnRoot @ react-dom.development.js:24293
(anonymous) @ react-dom.development.js:12286
unstable_runWithPriority @ scheduler.development.js:704
runWithPriority$2 @ react-dom.development.js:12232
flushSyncCallbackQueueImpl @ react-dom.development.js:12281
flushSyncCallbackQueue @ react-dom.development.js:12269
discreteUpdates$1 @ react-dom.development.js:24410
discreteUpdates @ react-dom.development.js:1439
dispatchDiscreteEvent @ react-dom.development.js:5915
error (async)
componentDidMount @ react-beautiful-dnd.esm.js:101
commitLifeCycles @ react-dom.development.js:22088
commitLayoutEffects @ react-dom.development.js:25340
callCallback @ react-dom.development.js:337
invokeGuardedCallbackDev @ react-dom.development.js:386
invokeGuardedCallback @ react-dom.development.js:439
commitRootImpl @ react-dom.development.js:25078
unstable_runWithPriority @ scheduler.development.js:704
runWithPriority$2 @ react-dom.development.js:12232
commitRoot @ react-dom.development.js:24918
finishSyncRender @ react-dom.development.js:24313
performSyncWorkOnRoot @ react-dom.development.js:24293
(anonymous) @ react-dom.development.js:12286
unstable_runWithPriority @ scheduler.development.js:704
runWithPriority$2 @ react-dom.development.js:12232
flushSyncCallbackQueueImpl @ react-dom.development.js:12281
workLoop @ scheduler.development.js:648
flushWork @ scheduler.development.js:603
performWorkUntilDeadline @ scheduler.development.js:199
material-table.js:224 Uncaught TypeError: Cannot read property 'onRowUpdate' of undefined
    at MaterialTable.<anonymous> (material-table.js:224)
    at callCallback (react-dom.development.js:13916)
    at commitUpdateEffects (react-dom.development.js:13956)
    at commitUpdateQueue (react-dom.development.js:13944)
    at commitLifeCycles (react-dom.development.js:22120)
    at commitLayoutEffects (react-dom.development.js:25340)
    at HTMLUnknownElement.callCallback (react-dom.development.js:337)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:386)
    at invokeGuardedCallback (react-dom.development.js:439)
    at commitRootImpl (react-dom.development.js:25078)
    at unstable_runWithPriority (scheduler.development.js:704)
    at runWithPriority$2 (react-dom.development.js:12232)
    at commitRoot (react-dom.development.js:24918)
    at finishSyncRender (react-dom.development.js:24313)
    at performSyncWorkOnRoot (react-dom.development.js:24293)
    at react-dom.development.js:12286
    at unstable_runWithPriority (scheduler.development.js:704)
    at runWithPriority$2 (react-dom.development.js:12232)
    at flushSyncCallbackQueueImpl (react-dom.development.js:12281)
    at flushSyncCallbackQueue (react-dom.development.js:12269)
    at discreteUpdates$1 (react-dom.development.js:24410)
    at discreteUpdates (react-dom.development.js:1439)
    at dispatchDiscreteEvent (react-dom.development.js:5915)
(anonymous) @ material-table.js:224
callCallback @ react-dom.development.js:13916
commitUpdateEffects @ react-dom.development.js:13956
commitUpdateQueue @ react-dom.development.js:13944
commitLifeCycles @ react-dom.development.js:22120
commitLayoutEffects @ react-dom.development.js:25340
callCallback @ react-dom.development.js:337
invokeGuardedCallbackDev @ react-dom.development.js:386
invokeGuardedCallback @ react-dom.development.js:439
commitRootImpl @ react-dom.development.js:25078
unstable_runWithPriority @ scheduler.development.js:704
runWithPriority$2 @ react-dom.development.js:12232
commitRoot @ react-dom.development.js:24918
finishSyncRender @ react-dom.development.js:24313
performSyncWorkOnRoot @ react-dom.development.js:24293
(anonymous) @ react-dom.development.js:12286
unstable_runWithPriority @ scheduler.development.js:704
runWithPriority$2 @ react-dom.development.js:12232
flushSyncCallbackQueueImpl @ react-dom.development.js:12281
flushSyncCallbackQueue @ react-dom.development.js:12269
discreteUpdates$1 @ react-dom.development.js:24410
discreteUpdates @ react-dom.development.js:1439
dispatchDiscreteEvent @ react-dom.development.js:5915
index.js:1437 The above error occurred in the <MaterialTable> component:
    in MaterialTable
    in Unknown (created by WithStyles(Component))
    in WithStyles(Component) (at Bounty.js:380)
    in div (created by Row)
    in Row (at Bounty.js:337)
    in div (at Bounty.js:330)
    in Bounty (at withAuth.js:39)
    in AuthWrapped (created by ConnectFunction)
    in ConnectFunction (at DefaultLayout.js:98)
    in Route (at DefaultLayout.js:93)
    in Switch (at DefaultLayout.js:90)
    in Suspense (at DefaultLayout.js:89)
    in div (created by Container)
    in Container (at DefaultLayout.js:79)
    in main (at DefaultLayout.js:77)
    in div (at DefaultLayout.js:62)
    in div (at DefaultLayout.js:55)
    in DefaultLayout (created by Context.Consumer)
    in withRouter(DefaultLayout) (at withAuth.js:39)
    in AuthWrapped (created by ConnectFunction)
    in ConnectFunction (at App.js:52)
    in Route (at App.js:52)
    in Switch (at App.js:47)
    in Suspense (at App.js:46)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:45)
    in App (created by ConnectFunction)
    in ConnectFunction (at src/index.js:57)
    in Provider (at src/index.js:56)
    in Provider (at src/index.js:55)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
console.<computed> @ index.js:1437
r @ react_devtools_backend.js:6
logCapturedError @ react-dom.development.js:21836
logError @ react-dom.development.js:21872
update.callback @ react-dom.development.js:23215
callCallback @ react-dom.development.js:13916
commitUpdateEffects @ react-dom.development.js:13956
commitUpdateQueue @ react-dom.development.js:13944
commitLifeCycles @ react-dom.development.js:22145
commitLayoutEffects @ react-dom.development.js:25340
callCallback @ react-dom.development.js:337
invokeGuardedCallbackDev @ react-dom.development.js:386
invokeGuardedCallback @ react-dom.development.js:439
commitRootImpl @ react-dom.development.js:25078
unstable_runWithPriority @ scheduler.development.js:704
runWithPriority$2 @ react-dom.development.js:12232
commitRoot @ react-dom.development.js:24918
finishSyncRender @ react-dom.development.js:24313
performSyncWorkOnRoot @ react-dom.development.js:24293
(anonymous) @ react-dom.development.js:12286
unstable_runWithPriority @ scheduler.development.js:704
runWithPriority$2 @ react-dom.development.js:12232
flushSyncCallbackQueueImpl @ react-dom.development.js:12281
flushSyncCallbackQueue @ react-dom.development.js:12269
discreteUpdates$1 @ react-dom.development.js:24410
discreteUpdates @ react-dom.development.js:1439
dispatchDiscreteEvent @ react-dom.development.js:5915
react-dom.development.js:12299 Uncaught TypeError: Cannot read property 'onRowUpdate' of undefined
    at MaterialTable.<anonymous> (material-table.js:224)
    at callCallback (react-dom.development.js:13916)
    at commitUpdateEffects (react-dom.development.js:13956)
    at commitUpdateQueue (react-dom.development.js:13944)
    at commitLifeCycles (react-dom.development.js:22120)
    at commitLayoutEffects (react-dom.development.js:25340)
    at HTMLUnknownElement.callCallback (react-dom.development.js:337)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:386)
    at invokeGuardedCallback (react-dom.development.js:439)
    at commitRootImpl (react-dom.development.js:25078)
    at unstable_runWithPriority (scheduler.development.js:704)
    at runWithPriority$2 (react-dom.development.js:12232)
    at commitRoot (react-dom.development.js:24918)
    at finishSyncRender (react-dom.development.js:24313)
    at performSyncWorkOnRoot (react-dom.development.js:24293)
    at react-dom.development.js:12286
    at unstable_runWithPriority (scheduler.development.js:704)
    at runWithPriority$2 (react-dom.development.js:12232)
    at flushSyncCallbackQueueImpl (react-dom.development.js:12281)
    at flushSyncCallbackQueue (react-dom.development.js:12269)
    at discreteUpdates$1 (react-dom.development.js:24410)
    at discreteUpdates (react-dom.development.js:1439)
    at dispatchDiscreteEvent (react-dom.development.js:5915)


`

**Comment by fatihenerya** [comment]
https://github.com/mbrn/material-table/issues/1735

**Comment by oze4** [comment]
@fatihenerya can you provide a demo of this? I tried the code below but got an error. For some reason, I keep getting `this` as `undefined`...

```
import React from "react";
import MaterialTable, { MTableBodyRow } from "material-table";
import { Edit } from "@material-ui/icons";
import tableIcons from "./TableIcons.js";

const results = ["Rock", "Paper", "Scissors"].map(word => {
  return {
    id: Math.floor(Math.random() * 300),
    name: word
  };
});

const handleRowClick = event => {
  console.log(event);
};

export default function AppTable() {
  return (
    <MaterialTable
      data={results}
      title="My Table"
      icons={tableIcons}
      columns={[
        {
          title: "Id",
          field: "id"
        },
        {
          title: "Name",
          field: "name"
        }
      ]}
      actions={[
        rowData => ({
          icon: Edit,
          tooltip: "Edit row",
          onClick: (event, rowData) => {
            rowData.tableData.editing = 'update'
            // this.forceUpdate(); // <-- THIS CAUSES AN ERROR
          }
        })
      ]}
    />
  );
}
```

**Comment by Domino987** [comment]
Yes because that only works for class Components.

You can use a useState with a number that increments to force a rerender

**Comment by oze4** [comment]
@fatihenerya @Domino987 the only way I could get this to work is by using a custom edit component..

[You can view a live demo here](https://stackblitz.com/edit/react-vzvxef)

```javascript
import React, { useState, useEffect } from "react";
import MaterialTable, { MTableEditRow } from "material-table";
import { Edit } from "@material-ui/icons";
import tableIcons from "./TableIcons.js";

const originalData = ["Rock", "Paper", "Scissors"].map(word => {
  return {
    id: Math.floor(Math.random() * 300),
    name: word
  };
});

export default function AppTable() {
  const [placeholder, setPlaceholder] = useState(0);
  const [data, setData] = useState(originalData);

  const forceUpdate = () => {
    setPlaceholder(o => o + 1);
  }

  return (
    <MaterialTable
      data={data}
      title="My Table"
      icons={tableIcons}
      columns={[
        {
          title: "Id",
          field: "id"
        },
        {
          title: "Name",
          field: "name"
        }
      ]}
      actions={[
        rowData => ({
          icon: Edit,
          tooltip: "Edit row",
          onClick: (event, rowData) => {
            rowData.tableData.editing = 'update'
            alert(`\r\n***ROWDATA AFTER CLICKING EDIT***:\r\n\r\n${JSON.stringify(rowData, null, 2)}`);
            forceUpdate();
          }
        })
      ]}
      components={{
        EditRow: props => {
          return (
            <MTableEditRow 
              {...props}
              onEditingCanceled={(mode, rowData) => {
                rowData.tableData.editing = undefined;
                forceUpdate();
              }}
              onEditingApproved={(mode, newData, oldData) => {
                const dataCopy = [...data];
                const index = dataCopy.indexOf(oldData);
                dataCopy[index] = newData;
                setData(dataCopy);
              }}
            />
          );
        }
      }}
    />
  );
}
```

**Comment by turkdoktoru** [comment]
Thank you very much my friend. it was a code structure exactly what I wanted.
But I'm just having trouble here.
It brings data while editing, but it is passive.
I could not edit how to fix this.

[https://imgyukle.com/i/JaKyXy](url)

`

            <MaterialTable
              Icons={icons}
              style={{height: "50", width: "50"}}
              columns={ this.state.columns }
              data={ this.state.drBounty }

              options={{
                toolbar: false,
                paging: false,
                headerStyle:{
                  backgroundColor: 'red',
                  width: "auto",
                  padding: "0"
                },
                rowStyle:{
                  height:"0"
                }
              }}


              actions={[
                rowData => ({
                  icon: Edit,
                  tooltip: "Düzenle",
                  onClick: (event, rowData) => {
                    rowData.tableData.editing = 'update';
                    this.setState({
                      id: rowData.id,
                      user: rowData.user,
                      doctor: rowData.doctor,
                      doctorName: rowData.doctorName,
                      doctorLastName: rowData.doctorLastName,
                      totalBounty: rowData.totalBounty,
                      description: rowData.description,
                      customerName: rowData.customerName,
                      bountyDate: rowData.bountyDate,
                      createdDate: rowData.createdDate,
                      groupCode: rowData.groupCode
                    });
                    this.forceUpdate();
                  }
                })
              ]}
              components={{
                EditRow: props => {
                  return (
                    <MTableEditRow
                      {...props}
                      onEditingCanceled={(mode, rowData) => {
                        rowData.tableData.editing = undefined;
                        this.forceUpdate();
                      }}
                      onEditingApproved={(mode, newData, oldData) => {
                        const dataCopy = [...drBounty];
                        const index = dataCopy.indexOf(oldData);
                        dataCopy[index] = newData;
                        this.handleSubmitUpdate.bind(this);
                        //setData(dataCopy);
                      }}
                    />
                  );
                }
              }}

            />

`

**Comment by oze4** [comment]
So you want to change data when the edit button is clicked?

**Comment by turkdoktoru** [comment]
Yes,
The data comes in and I show it in the input. But I couldn't change it. So it comes passively.

Very thanks

**Comment by oze4** [comment]
@turkdoktoru  I think it would be helpful if you could explain your use case - but this is how you can change the data when the edit button is clicked..

### [You can view a live demo here](https://stackblitz.com/edit/react-vndhxh?embed=1&file=AppTable.js)

```javascript
import React, { useState } from "react";
import MaterialTable, { MTableEditRow } from "material-table";
import { Edit } from "@material-ui/icons";
import tableIcons from "./TableIcons.js";

const originalData = ["Rock", "Paper", "Scissors"].map(word => {
  return {
    id: Math.floor(Math.random() * 300),
    name: word
  };
});

export default function AppTable() {
  const [, forceUpdate] = useState(false);
  const [data, setData] = useState(originalData);

  /**
   * Method that allows us to easily set the table update state by forcing a re-render
   * @param rowData {Object} material-table rowData
   * @param status {Boolean} true/false whether or not we are updating a row
   */
  const isRowUpdating = (rowData, status) => {
    rowData.tableData.editing = status ? "update" : undefined;
    forceUpdate(status);
  };

  return (
    <MaterialTable
      data={data}
      title="I Love Tables"
      icons={tableIcons}
      columns={[
        {
          title: "Id",
          field: "id"
        },
        {
          title: "Name",
          field: "name"
        }
      ]}
      actions={[
        rowData => ({
          icon: Edit,
          tooltip: "Edit row",
          isFreeAction: true,
          onClick: (event, rowData) => {
            isRowUpdating(rowData, true);
          }
        })
      ]}
      components={{
        EditRow: props => {
          const newRowData = {
            ...props.data,        // *MUST INCLUDE tableData FROM ORIGINAL props.data!!*
            id: "DEFAULT VALUES", // <-- // Set whatever default data you want here 
            name: "ON EDIT"       // <-- // (or pull from state, etc.. whatever you want)
          };

          return (
            <MTableEditRow
              {...props}
              data={newRowData}
              onEditingCanceled={(mode, rowData) => {
                isRowUpdating(rowData, false);
              }}
              onEditingApproved={(mode, newData, oldRowData) => {
                const dataCopy = [...data];
                const index = data.indexOf(props.data); // Grab index from the data we were given in the props
                dataCopy[index] = newData;
                setData(dataCopy);

                // Use props.data here since it will contain 'tableRow' prop.
                //  // If we don't do this, we wouldn't be able to edit any row after updating here because
                //  // the table would still think we are in 'update' mode.
                isRowUpdating(props.data, false);
              }}
            />
          );
        }
      }}
    />
  );
}
```

**Comment by oze4** [comment]
@turkdoktoru it's hard to see what you're wanting to happen exactly... so, if you just want to set the `rowData`, but without giving the user a chance to edit it, something like this will work:

### [You can view a live demo here](https://stackblitz.com/edit/react-jpyevo?embed=1&file=AppTable.js)

```javascript
import React, { useState } from "react";
import MaterialTable, { MTableEditRow } from "material-table";
import { Edit } from "@material-ui/icons";
import tableIcons from "./TableIcons.js";

const originalData = ["Rock", "Paper", "Scissors"].map(word => {
  return {
    id: Math.floor(Math.random() * 300),
    name: word
  };
});

export default function AppTable() {
  const [, forceUpdate] = useState(false);
  const [data, setData] = useState(originalData);

  /**
   * Method that allows us to easily set the table update state by forcing a re-render
   * @param rowData {Object} material-table rowData
   * @param status {Boolean} true/false whether or not we are updating a row
   */
  const isRowUpdating = (rowData, status) => {
    rowData.tableData.editing = status ? "update" : undefined;
    forceUpdate(status);
  };

  return (
    <MaterialTable
      data={data}
      title="I Love Tables"
      icons={tableIcons}
      columns={[
        {
          title: "Id",
          field: "id"
        },
        {
          title: "Name",
          field: "name"
        }
      ]}
      actions={[
        rowData => ({
          icon: Edit,
          tooltip: "Edit row",
          isFreeAction: true,
          onClick: (event, rowData) => {
            const newRowData = { 
              ...rowData,
              id: "DEFAULT VALUES", // <-- // Set whatever default data you want here 
              name: "ON EDIT"       // <-- // (or pull from state, etc.. whatever you want)
            };
            const dataCopy = [...data];
            dataCopy[dataCopy.indexOf(rowData)] = newRowData;
            setData(dataCopy);
          }
        })
      ]}
      components={{
        EditRow: props => {
          return (
            <MTableEditRow
              {...props}
              onEditingCanceled={(mode, rowData) => {
                isRowUpdating(rowData, false);
              }}
              onEditingApproved={(mode, newData, oldRowData) => {
                const dataCopy = [...data];
                const index = data.indexOf(props.data);
                dataCopy[index] = newData;
                setData(dataCopy);
                isRowUpdating(props.data, false);
              }}
            />
          );
        }
      }}
    />
  );
}
```

**Comment by turkdoktoru** [comment]
Hello,

The code you wrote first meets exactly what I want.
But I encounter an error like the one below.
Thank you very much @ my friend.

[https://ibb.co/PwDF2Ds](url)

`

     import React, { Component, useState } from "react";
     import withAuth from "../../components/helpers/withAuth";
     import AlertMessageBox from "../../components/helpers/AlertMessageBox";
     import { connect } from "react-redux";
     import { Button, Col, Row, Table, Input } from "reactstrap";
     import MaterialTable, { MTableEditRow } from "material-table";
     import icons from '@material-ui/core/Icon';
     import DeleteOutline from '@material-ui/icons/DeleteOutline';
     import Edit from '@material-ui/icons/Edit';


     class Bounty extends Component {
       constructor(props) {
         super(props);

       this.state = {
           isLoaded: true,

      drBounty: [],
      drList: [],

      columns: [
        { title: 'Name', field: 'doctorName',
          cellStyle:{padding: "1px", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis", maxWidth: "1px"},
          editComponent: (props) => (
            <Input
              type="text"
              placeholder={props.columnDef.title}
              defaultValue={props.value}
              onChange={(e) => props.onChange(
                this.setState({
                  doctorName: e.target.value
                })
              )}
            />
          )
        },

        { title: 'LastName', field: 'doctorLastName',
          cellStyle:{padding: "1px", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis", maxWidth: "5px"},
          editComponent: (props) => (
            <Input
              type={"text"}
              placeholder={"Doktor soyadı"}
              defaultValue={props.value}
              onChange={(e) => props.onChange(
                this.setState({
                  doctorLastName: e.target.value
                })
              )}
            />
          )
        }
      ]
    };

       this.getBountyList = this.getBountyList.bind(this);
     }



     async componentDidMount() {
         await fetch(
      `${this.domain}/api/user/groupusers?groupCode=`+ this.props.account_profile.profile.profile.groupCode,
          {
             headers: {
             Authorization: `Bearer ${localStorage.getItem("id_token")}`,
             "Content-Type": "application/json"
           }
        }
    )
      .then(res => {
        if (res.ok) {
          return res.json();
        } else {
          return res.json().then(err => Promise.reject(err));
        }
      })
      .then(json => {
           console.log(json)
      })
      .catch(error => {
        console.log(error)
        return error;
      });
      }

     async getBountyList(id) {
    await fetch(`${this.domain}/api/bounty/list?groupCode=${this.props.account_profile.profile.profile.groupCode}&doctor=${id}`,{
         headers: {
          Authorization: `Bearer ${localStorage.getItem("id_token")}`,
          "Content-Type": "application/json"
        }
      })
      .then(res => {
        console.log(res);
        if (res.ok) {
          return res.json();
        } else {
          return res.json().then(err => Promise.reject(err));
        }
      })
      .then(json => {
        console.log(json)
      })
      .catch(error => {
        console.log(error);
        return error;
      });
      }

     render() {
         const {isLoaded, drList, drBounty} = this.state;

         const [, forceUpdate] = useState(false);
         const [data, setData] = useState(drBounty);
         const isRowUpdating = (rowData, status) => {
         rowData.tableData.editing = status ? "update" : undefined;
         forceUpdate(status);
    };

    if (!isLoaded) {
      return <div>Loading...</div>;
    } else {
      return (
        <div className={"animated fadeIn "}>



          <Row>
            <div> &nbsp; &nbsp; </div>

            <Col sm={{span:1, offset:0.9}}>

              <Table>
                <thead>
                <tr>
                  <th width={"20"} />
                  <th width={"50"}>Adı</th>
                  <th width={"70"}>Soyadı</th>
                </tr>
                </thead>
                <tbody>
                {
                  drList
                    .map(item => (
                      <tr key={item.id}>
                        <td>
                          <Button
                            block
                            outline
                            color="info"
                            onClick={() => this.getBountyList(item.id)}
                          >
                            Aç
                          </Button>
                        </td>

                        <td>{item.first_name} </td>
                        <td>{item.last_name}</td>

                      </tr>
                    ))}
                </tbody>
              </Table>

            </Col>


            &nbsp;&nbsp;&nbsp;
            &nbsp;&nbsp;&nbsp;


            <MaterialTable
              Icons={icons}
              style={{height: "50", width: "50"}}
              columns={ this.state.columns }
              data={ this.state.drBounty }


              actions={[
                rowData => ({
                  icon: Edit,
                  tooltip: "Edit row",
                  onClick: (event, rowData) => {
                    isRowUpdating(rowData, true);

                    this.setState({
                      id: rowData.id,
                      user: rowData.user,
                      doctor: rowData.doctor,
                      doctorName: rowData.doctorName,
                      doctorLastName: rowData.doctorLastName,
                      totalBounty: rowData.totalBounty,
                      description: rowData.description,
                      customerName: rowData.customerName,
                      bountyDate: rowData.bountyDate,
                      createdDate: rowData.createdDate,
                      groupCode: rowData.groupCode
                    });

                  }
                })
              ]}

              components={{
                EditRow: props => {
                  const newRowData = {
                    ...drBounty,        // *MUST INCLUDE tableData FROM ORIGINAL props.data!!*
                    id: "DEFAULT VALUES", // <-- // Set whatever default data you want here
                    doctorName: "ON EDIT"       // <-- // (or pull from state, etc.. whatever you want)
                  };

                  return (
                    <MTableEditRow
                      {...props}
                      data={newRowData}
                      onEditingCanceled={(mode, rowData) => {
                        isRowUpdating(rowData, false);
                      }}
                      onEditingApproved={(mode, newData, oldRowData) => {
                        const dataCopy = [...drBounty];
                        const index = drBounty.indexOf(props.data); // Grab index from the data we were given in the props
                        dataCopy[index] = newData;
                        setData(dataCopy);
                        isRowUpdating(props.data, false);
                      }}
                    />
                  );
                }
              }}
            />
          </Row>
        </div>
       );
      }
     }
     }

     export default connect(withAuth( Bounty ));
`

**Comment by oze4** [comment]
@turkdoktoru  Your link doesn't work.. also, this is incorrect..

```javascript
              const newRowData = {
                ...drBounty,        // *MUST INCLUDE tableData FROM ORIGINAL props.data!!*
                id: "DEFAULT VALUES", // <-- // Set whatever default data you want here
                doctorName: "ON EDIT"       // <-- // (or pull from state, etc.. whatever you want)
              };
```
as my notes mention, you have to include tabeData from original props.data...

```javascript
              const newRowData = {
                ...props.data,        // *MUST INCLUDE tableData FROM ORIGINAL props.data!!*
                id: "DEFAULT VALUES", // <-- // Set whatever default data you want here
                doctorName: "ON EDIT"       // <-- // (or pull from state, etc.. whatever you want)
              };
```

**Comment by turkdoktoru** [comment]
ok, very thanks problem solved
