### ISSUE TITLE
Add feature: disable action depending on row data

### ISSUE THREAD

**Issue by slevy85** [mbrn/material-table#173]
I have noticed that we can only declare an action disabled with `true/false` :  

```javascript
actions = [
    {
      icon: "arrow_upward",
      disabled: true,
      onClick: (e, row) => this.handleUp(e, row)
    }
]
```
I would like to disable it depending on a  condition on the row data, something like this :

```javascript
actions = [
    {
      icon: "arrow_upward",
      tooltip: "Move up",
      disabled: row => row.tableData.id === 0,
      onClick: (e, row) => this.handleUp(e, row)
    }
]
```

Is it possible ?

Thank you very much.

**Comment by mbrn** [comment]
Yes it is possible to return action data completely according to rowData:

```javascript
actions = [
    rowData => ({
      icon: "arrow_upward",
      tooltip: "Move up",
      disabled: rowData => rowData.tableData.id === 0,
      onClick: (e, row) => this.handleUp(e, row)
    })
]
```

Look at this: 
https://mbrn.github.io/material-table/#/docz-examples-03-example-actions
More Actions 2.icon

**Comment by slevy85** [comment]
Thank you !
I forgot about this.
It solves my problem so this feature I proposed is not needed I think.

**Comment by mxt305** [comment]
There are something wrong in the code. it's not correct to put function in the disabled property.
So the correct code is in the below.
`actions = [
    rowData => ({
      icon: "arrow_upward",
      tooltip: "Move up",
      disabled: rowData.tableData.id === 0,
      onClick: (e, row) => this.handleUp(e, row)
    })
]`
