### ISSUE TITLE
state aktarma ve text onChange olayı - state transfer and text onChange event

### ISSUE THREAD

**Issue by fatihenerya** [mbrn/material-table#1732]
Merhaba,

1. tablo üzerinde "edit" butonuna tıkladığımda, seçili satırdaki verileri state içine aktarmak istiyorum. 
2. Ayrıca satır üzerinde "protein" isimli alanda değişiklik yaptığımda da onChange olayına nasıl bağlayabilirim ?

`
     this.setState {
       id: id,
       proteion: selected row protein,
       comments: selected row comments
     }
`

şeklinde nasıl aktarabilirim.

[https://ibb.co/zmNktth](url)

**English description**
When I click the edit button, the data in the selected line

this.setState {
   id: id,
   proteion: selected row protein,
   comments: selected row comments
}

How can I transfer it in the form.

Also, how can I link to the onChange event when I make changes to the row?

`

     <MaterialTable
      editable={{
        onRowUpdate: (newData, oldData) =>
            new Promise((resolve, reject) => {
                setTimeout(() => {
                    {
                        /* const data = this.state.data;
                        const index = data.indexOf(oldData);
                        data[index] = newData;                
                        this.setState({ data }, () => resolve()); */
                    }
                    resolve();
                }, 1000);
            }),
     }}
     />

`

**Comment by Androsv96** [comment]
Could you please provide an example of what you want to do. Thank you.

**Comment by oze4** [comment]
***Turkish***: Bu popüler bir istek gibi görünüyor. Bunu başarabilmemin tek yolu özel bir düzenleme bileşeni kullanmaktı.

Burada canlı bir demo görebilirsiniz: https://stackblitz.com/edit/react-vzvxef?embed=1&file=AppTable.js 

---

***English***: It seems this is a popular request. The only way I was able to accomplish this was by using a custom edit component.

You can see a live demo here: https://stackblitz.com/edit/react-vzvxef?embed=1&file=AppTable.js 

Instead of an alert you could add that data to state.

---

```javascript
import React, { useState } from "react";
import MaterialTable, { MTableEditRow } from "material-table";
import { Edit } from "@material-ui/icons";
import tableIcons from "./TableIcons.js";

const originalData = ["Rock", "Paper", "Scissors"].map(word => {
  return {
    id: Math.floor(Math.random() * 300),
    name: word
  };
});

export default function AppTable() {
  const [placeholder, setPlaceholder] = useState(0);
  const [data, setData] = useState(originalData);

  const forceUpdate = () => {
    setPlaceholder(o => o + 1);
  }

  return (
    <MaterialTable
      data={data}
      title="My Table"
      icons={tableIcons}
      columns={[
        {
          title: "Id",
          field: "id"
        },
        {
          title: "Name",
          field: "name"
        }
      ]}
      actions={[
        rowData => ({
          icon: Edit,
          tooltip: "Edit row",
          onClick: (event, rowData) => {
            rowData.tableData.editing = 'update'
            alert(`\r\n***ROWDATA AFTER CLICKING EDIT***:\r\n\r\n${JSON.stringify(rowData, null, 2)}`);
            forceUpdate();
          }
        })
      ]}
      components={{
        EditRow: props => {
          return (
            <MTableEditRow 
              {...props}
              onEditingCanceled={(mode, rowData) => {
                rowData.tableData.editing = undefined;
                forceUpdate();
              }}
              onEditingApproved={(mode, newData, oldData) => {
                const dataCopy = [...data];
                const index = dataCopy.indexOf(oldData);
                dataCopy[index] = newData;
                setData(dataCopy);
              }}
            />
          );
        }
      }}
    />
  );
}
```

**Comment by Androsv96** [comment]
Hi. But what do you want to approach? As I see what you wanted was when user clicks on edit button get the row clicked data? And you could do this with the `onRowUpdate` method.

**Comment by oze4** [comment]
The `onRowUpdate` method only allows you to get the row data after the data has been updated. It is my understanding the issue is that @fatihenerya wants to grab the data from the row after the edit button is clicked, and put that data into state.  The example I have provided allows you to do that.

**Comment by oze4** [comment]
Issue is stale please reopen if needed.
