### ISSUE TITLE
Not editable column only during update

### ISSUE THREAD

**Issue by Drezir** [mbrn/material-table#1733]
Hi,

I have one column marked as editable: false.
I would like to have an option to allow editing a value only during adding new row - disallowing  it only during update mode.

I believe there is some workaround with custom component but It would be nice feature to distinguish it using props. Thanks

**Comment by Domino987** [comment]
As seen [here](https://material-table.com/#/docs/features/editable), you can provide a string instead of boolean:
```  { title: 'Name', field: 'name', editable: 'onUpdate' },```
