### ISSUE TITLE
Search on rowData that is not displayed

### ISSUE THREAD

**Issue by raimondi1337** [mbrn/material-table#1734]
I have some rowData that is not displayed in a column

```
const columns = ['Team Name', Team Count'];
const data = [{
    teamName: 'Space Pirates',
    teamCount: 2,
    teammateNames: ['Elon-chan', 'Daddy Bezos']
}];
```

I don't want to display a column for this data, but if I type 'Elon' in the Search box I want this row to be displayed
Is this currently supported, or do I need to make some kind of hidden column or something?

**Comment by Domino987** [comment]
You are not declaring the columns corretly. It would need to look like this:

```
const columns = [{field:'teamName' ,title:'Team Name'}, {field:'teamCount' ,title:'Team Count'}];
const data = [{
    teamName: 'Space Pirates',
    teamCount: 2,
    teammateNames: ['Elon-chan', 'Daddy Bezos']
}];
```

**Comment by raimondi1337** [comment]
I am aware the pseudocode was just to illustrate what I'm trying to do.

**Comment by Domino987** [comment]
Oh I am sorry, i musunderstood.

You can simply override customFilterAndSearch:
```
customFilterAndSearch: (term, rowData) => rowData.teammateNames.findIndex(v ==> v.contains(term)) !== -1 || rowData.teamName.includes(term)  },
```

**Comment by raimondi1337** [comment]
I guess that would work but I'd have to reimplement Search for the other fields too, correct? I don't want to only search on teammateNames. Making teammateNames an invisible column might be easier at that point... hmm...

**Comment by Domino987** [comment]
Since this is more an implementation detail and not an issue, could you close this?

**Comment by raimondi1337** [comment]
Thanks for your help

**Comment by raimondi1337** [comment]
Oh I see `customFilterAndSearch` is a property of a column, not of the table.
I can just override it on a column that I have that isn't filterable to accomplish this task.
