### ISSUE TITLE
named pages like all || pagesizeptions || all

### ISSUE THREAD

**Issue by raevillena** [mbrn/material-table#1738]
Proptypes invalid with named page option when doing something like this:
`pageSizeOptions: [5, 10, 20, 50, { value: pages.length, label: "All" }]`

I just did changed it on mine cause i cant wait for pr to get approve anymore, i just saw a pr like 4 days ago

so anyone who needs this urgent 
edit proptypes.js at dist folder of the module 

`pageSizeOptions:_propTypes["default"].arrayOf(_propTypes["default"].oneOfType([_propTypes["default"].number, _propTypes["default"].object])),`

![image](https://user-images.githubusercontent.com/25400402/76694486-381d2c00-66ae-11ea-82df-b20bff0ee5f4.png)

**Comment by oze4** [comment]
[Reference to PR](https://github.com/mbrn/material-table/pull/1729)

**Comment by oze4** [comment]
Refer to PR for more details.
