### ISSUE TITLE
Allow for external `count` prop

### ISSUE THREAD

**Issue by plummer-flex** [mbrn/material-table#174]
**Is your feature request related to a problem? Please describe.**
When handling filter/sort/pagination in external state, a user needs to be able to specify the total count of records in a set.

**Describe the solution you'd like**
A root level prop for `count` that, if set, will override the value passed to the `Pagination` component.

**Describe alternatives you've considered**
Overriding the `Pagination` component and injecting the `count` prop manually.

**Comment by mbrn** [comment]
Duplicate with #64
