### ISSUE TITLE
How to get data in database ? 

### ISSUE THREAD

**Issue by PubuduArosha** [mbrn/material-table#1742]
I can't understand how to connect DB and how to show data in the table from DB. also update, edit and delete.
![Screenshot (6)](https://user-images.githubusercontent.com/41939687/76943432-5a6caf00-6925-11ea-8ddc-8e197839a6c9.png)

**Comment by Androsv96** [comment]
Hello. I don't think material-table has anything to do with DB but I would suggest you to create an API so you could send the data and get a response from it, that way you can update your table with the new data.
So let's say the user modifies a row and saves it, then you could show a progress bar meanwhile you send the request to your API whit the new modified data.
