### ISSUE TITLE
Is there a way to make the body container 100% height?

### ISSUE THREAD

**Issue by krgt** [mbrn/material-table#1743]
I am trying to make the table use all the height available with the footer staying at the bottom of the container.

See this sandbox: https://codesandbox.io/s/material-table-cdfhs

I set the table style prop to:

```
const style = {
      display: "flex",
      flexDirection: "column",
      height: "100vh"
};
```

The table container uses all the height available, however the body doesn't. So the table shrinks and the footer moves up. If I set the body div to 100% height I get the desired result: https://imgur.com/a/wOetqbS

Is there a way to achieve this?

**Comment by oze4** [comment]
So `pageSize` is what determines body size (partially, at least).. Try setting your options to the following: (I tested this with your Sandbox and it seems to work)..

```javascript
    const options = { 
      filtering: true, 
      selection: true,
      pageSize: 20, // Some number large enough so that it expands to the entire page...
    };
```

**Comment by gsouf** [comment]
@oze4 that won't solve the issue. 

Ideally we would want for an option where footer and headers can be sticky and only the body scrolls

**Comment by ismile** [comment]
I need this as well,
I think we need option to overriding ScrollBar Component or ability to add style into it

**Comment by oze4** [comment]
I believe you can also try the minBodyHeight option?

<img width="599" alt="image" src="https://user-images.githubusercontent.com/21092343/83358190-7930ee00-a337-11ea-8762-caff03bf51cc.png">

**Comment by oze4** [comment]
Leaving this open because I agree - we should make it so you can scroll the body while the footer is sticky..

**Comment by LuisPinaSoares** [comment]
Hi, any news on this topic? This addition would come in handy.
Thanks!

**Comment by CatalinVoss** [comment]
+1 would be lovely

**Comment by ZakKa89** [comment]
+1

**Comment by GordonSmith** [comment]
FWIW here is my current solution using AutoSizer:
```typescript
import * as React from "react";
import MaterialTable, { MaterialTableProps } from 'material-table'
import { AutoSizer } from "react-virtualized";
import { icons } from '../util/table';

import "dojo/i18n";
// @ts-ignore
import * as nlsHPCC from "dojo/i18n!hpcc/nls/hpcc";

interface MaterialTableExProps<RowData extends object> extends MaterialTableProps<RowData> {
}

const MaterialTableEx: React.FunctionComponent<MaterialTableExProps<object>> = (props) => {
    const tableRef = React.useRef(null);
    React.useEffect(() => {
        tableRef.current.onQueryChange();
    }, [props.options.pageSize])

    return <MaterialTable
        tableRef={tableRef}
        icons={icons}
        {...props}
        data={query => {
            query.pageSize = props.options.pageSize;
            return (props.data as any)(query);
        }}
    />;
}

export const AutoSizeTable: React.FunctionComponent<MaterialTableExProps<object>> = (props) => {
    return <AutoSizer >
        {({ height, width }) => {
            const bodyHeight = height
                - 64    //  Title
                - 52    //  Footer
                - 2     //  Padding
                ;

            const pageSize = Math.max(Math.floor((bodyHeight) / 38.22) - 1, 1);
            const newProps = {
                ...props,
                options: {
                    ...props.options,
                    pageSize: pageSize,
                    pageSizeOptions: [],
                    headerStyle: { padding: '0.0em' },
                    minBodyHeight: bodyHeight,
                    maxBodyHeight: bodyHeight
                }
            };

            return <div style={{ width: `${width}px` }}>
                <MaterialTableEx {...newProps} />
            </div>;
        }}
    </AutoSizer>;
}; 

````

**Comment by LuisPinaSoares** [comment]
Hi! 

Just as a reference i ended up solving this issue the following way, using @oze4 sugestion.

```javascript
const tableHeight =window.innerHeight - 64 - 64 - 52 - 1) / window.innerHeight * 100;
```
and adding the following on options

```javascript
options={{
            maxBodyHeight: `${tableHeight}vh`,
            minBodyHeight: `${tableHeight}vh`,
}}
```

As @GordonSmith  mentioned on his code 64px is the header 52px is the pagination footer and the -1 is just for some minor computation error that may come from rounding on tableHeight and avoiding the outside scroll bar being invoked by the browser. The additional 64px is just because i have a fixed AppBar on the top of my app.

For me this did the trick!

**Comment by david-lee** [comment]
@LuisPinaSoares Thanks for your solution. I have a somehow different but related question. Did you happen to use a fixed column feature with maxBodyHeight? I am using version 1.68.0 and if you give maxBodyHeight then the header will be sticky. It is working fine but if fixed columns are applied, the fixed columns are not sticky. When I scroll non-fixed columns area then sticky header is working but the fixed columns are not scrolled.
Anyone who has the same issue?

**Comment by Jorgmassih** [comment]
I think css-grid is a better option than flex-box because you can get more control about the layout.

I just edited your `style` variable as follows:
```javascript
const style = {
      display: "grid",
      gridTemplateColums: "1fr",
      gridTemplateRows: "auto 1fr auto",
      height: "100vh"
    };
```

See this [sandbox](https://codesandbox.io/s/material-table-forked-lhe8o?file=/src/index.js:1103-1244) for the results.
