### ISSUE TITLE
exist some detailPanelIcons order column prop?

### ISSUE THREAD

**Issue by vandal777** [mbrn/material-table#1746]
I want to change the column position of my custom icons for expand detail panel.

exist some prop for do that?

i want to get these changes.

![image](https://user-images.githubusercontent.com/12391981/77085003-01257e00-6a00-11ea-9f1d-15b37ef8dbf1.png)

**Comment by oze4** [comment]
Something like this?  Look at the 'Multiple Detail Panels Example' from [here](https://material-table.com/#/docs/features/detail-panel)
