### ISSUE TITLE
Editable row blocks when it loses focus

### ISSUE THREAD

**Issue by bilix** [mbrn/material-table#1751]
**Describe the bug**
When editing a row, if something happens in your app that makes the row lose focus (like clicking another component or showing a toast notification), the row gets blocked (grey and disabled)

**Expected behavior**
The row doesn't get blocked.

**Screenshots**
![image](https://user-images.githubusercontent.com/1675426/77300055-bb153680-6ced-11ea-85a5-a44fad014048.png)

**Comment by yonihorwitz** [comment]
Same as #1487?

**Comment by bilix** [comment]
Yes, i'll close this one.
