### ISSUE TITLE
onQueryChange typescript definition

### ISSUE THREAD

**Issue by ozomer** [mbrn/material-table#1752]
**Is your feature request related to a problem? Please describe.**
In https://github.com/mbrn/material-table/issues/383 the solution to forcing the table
to refresh is to call `onQueryChange`. The function implementation can accept a partial `Query` and even a `null` or `undefined`, so in javascript you can simply call `table.onQueryChange()`.
In typescript however, the declaration must accept a full `Query`, so a full query parameter must be passed.

See: https://github.com/mbrn/material-table/blob/master/types/index.d.ts#L39

**Describe the solution you'd like**
`onQueryChange` should accept an optional `Partial<Query<RowData>>`.

**Describe alternatives you've considered**
There should be a `forceRemoteUpdate` function, or this use-case of `onQueryChange` should be well documented.

**Comment by thalysonalexr** [comment]
facing the same problem.

**Comment by vopecula** [comment]
Same problem :(
