### ISSUE TITLE
[Sugestion] - Mobile Cards (collapsed rows) for better mobile vertical view

### ISSUE THREAD

**Issue by JoseRodrigues443** [mbrn/material-table#1758]
**Is your feature request related to a problem? Please describe.**

On mobile view , a table with 5, 10, 20  columns is a pain in the ass to view. Is ugly not efficient to view, fast and easy. For mobile a vertical view would be the better approach.

**Describe the solution you'd like**

For mobile a vertical view would be the better approach. A toggle in the API that would allow a new mode "Mobile Cards" that 

A good example is found in this project: https://buefy.org/documentation/table
            Desktop Mode: https://i.imgur.com/I16eesL.png
            Mobile Mode: https://i.imgur.com/9glU2ft.png

They have a codePen link: https://codepen.io/pen?&editable=true&editors=101

**Describe alternatives you've considered**

Have the ability to hide advanced filters on mobile to have less clutter

**Additional context**

A good example is found in this project: https://buefy.org/documentation/table
            Desktop Mode: https://i.imgur.com/I16eesL.png
            Mobile Mode: https://i.imgur.com/9glU2ft.png

They have a codePen link: https://codepen.io/pen?&editable=true&editors=101

**Comment by oze4** [comment]
#1395
