### ISSUE TITLE
adjusting toolbar height

### ISSUE THREAD

**Issue by turkdoktoru** [mbrn/material-table#1765]
Hello,

The blue marked area takes up a lot of space. How can I adjust the height of the Toolbar?
Can you show by example?

[https://ibb.co/wpxdmnj](url)

**Comment by turkdoktoru** [comment]
I found a code structure like this, but I could not adjust the height.

`

         Toolbar: props => (
                  <div style={{ backgroundColor: 'blue', }}>
                    <MTableToolbar {...props} classes={{ customizeToolbar: "15px" }} />
                  </div>
                ),
`

     const styles = {
       customizeToolbar: {
         minHeight: "100px"
       }
     }
`

**Comment by turkdoktoru** [comment]
I need to change the style structure below. especially I have to change the min-height


  .MuiToolbar-regular {
    min-height: 64px;
  }


`

     .MuiToolbar-root {
       display: flex;
       position: relative;
       align-items: center;
     }
     .MuiToolbar-gutters {
       padding-left: 16px;
       padding-right: 16px;
      }
     @media (min-width:600px) {
       .MuiToolbar-gutters {
         padding-left: 24px;
          padding-right: 24px;
       }
     }
     .MuiToolbar-regular {
       min-height: 56px;
     }
      @media (min-width:0px) and (orientation: landscape) {
       .MuiToolbar-regular {
         min-height: 48px;
       }
     }
     @media (min-width:600px) {
        .MuiToolbar-regular {
         min-height: 64px;
       }
      }
     .MuiToolbar-dense {
       min-height: 48px;
     }
`

**Comment by solace** [comment]
If you want to just use the Mui dense option, I managed it with this:

```
Toolbar: props => (
                        <MTableToolbar
                          {...props}
                          classes={{ root: 'MuiToolbar-dense' }}
                        />
```

It results in both `MuiToolbar-regular` (default) and `MuiToolbar-dense` classes being applied with dense overriding regular. It's not great but it does the job.
