### ISSUE TITLE
÷Is there any way to make column type as password

### ISSUE THREAD

**Issue by tounoussiKhalid** [mbrn/material-table#1767]
So that it is displayed as asterisks (***) and when creating new row and when entering data it displayed as *** with icon to view it while typing.

**Comment by MuhammadHani10p** [comment]
Not sure about field but you can do that by overriding `render` method of each row and do handle (toggle password visibility) respectively.

**Comment by L1ghtman2k** [comment]
https://stackoverflow.com/questions/56939789/how-to-mask-password-with-materialtable/64419072#64419072
