### ISSUE TITLE
Don't hardcode date-io provider

### ISSUE THREAD

**Issue by dantman** [mbrn/material-table#1768]
**Is your feature request related to a problem? Please describe.**
`@material-ui/pickers` has a reason it uses a provider to provide a `@date-io` library instead of hardcoding one date provider. Not everyone uses the same date library and hardcoding one leads to unnecessary redundant date libraries and localization data being downloaded and differences in expected data types. This is the whole reason that `@date-io` exists instead of just using the date libraries directly.

material-table undoes this by depending on `@date-io/date-fns` directly. `@date-io/date-fns` and `date-fns` is downloaded and included in your bundles, even if you don't use date handling in Material Table. And if you already use `@material-ui/pickers` and have it setup with localization, then material-table undoes this and requires specifying localization info all over again.

**Describe the solution you'd like**
I'd much prefer it if material-table didn't try interfering with the interface mui/pickers provides to users. And instead just allowed the user to specify the date utils provider at the root like mui/pickers wants.

**Additional context**
This would also cut down on the number of date utils instances that material table ends up creating.

**Comment by dantman** [comment]
Still an issue.

**Comment by diegosps** [comment]
There is definitely an "issue" with how imports from optional features are handled in this project.
In production build:
jspdf 290 kb
react-beautiful-dnd 85 kb
data-fns: 49kb
jspdf-autotable: 31 kb

There are more, but with lower sizes.

So it's at least 455 kb added on top the 136 kbs from core for features that I'm not sure half of it's base use.

**Comment by eps1lon** [comment]
Bump

**Comment by mgdenno** [comment]
This one is giving me some trouble.  I really need to use MomentUtils on my project to deal with timezones. I am able to do this using MomentUtils in my other datetime pickers, but not in my tables.  Not really sure how to workaround this one.

Would the fix be as simple as removing the MuiPickersUtilsProvider from the material-table library and letting the user wrap the table in the one they want to use?

**Comment by eps1lon** [comment]
bump
