### ISSUE TITLE
Allow to set all properties (primarily classes) and relay to underlying MUI table

### ISSUE THREAD

**Issue by SweVictor** [mbrn/material-table#1769]
It would be great if overflowing props would be passed on to the underlying MUI table.

Setting `classes` is the most important to enable styling (for both table, tablerow, cell, ...), but also other.

Table styles can be worked around (a bit uglily) by styling descendants of a wrapper div with className on it, but it's far from ideal.

For cells, I have not found a solution. I would like to hide/transform cells (columns really) using responsive breakpoints in css, but without being able to set classes on specific columns/cells it seems really har.

For cells I believe passing through all non-handled properties of `columnDef` along with this.props would solve the issue, but there might be more elegant solutions.

https://github.com/mbrn/material-table/blob/3031eab70105df8d88c17984ca5cea878a9eae3f/src/components/m-table-cell.js#L117

Any short-term solutions to responsively hide columns would also be appreciated!

Thanks
/Victor

**Comment by GeenCo86** [comment]
Something new here? I would also like to know if any request is somehow possible?
