### ISSUE TITLE
add new editable-table rows

### ISSUE THREAD

**Issue by turkdoktoru** [mbrn/material-table#1772]
Hello,

I want to add a new row with editable-table. I need buttons like Save and Cancel when adding a new line.
I want to add a new line with the + button on the Toolbar.

that is, when the add button is pressed. new row will be added on the table.
I want the Save and Cancel buttons for the new line.

[https://ibb.co/G2MRtJD](url)

`

     <MaterialTable
              actions={[
                rowData => ({
                  icon: Edit,
                  tooltip: "Edit",
                  onClick: (event, rowData) => {
                    isRowUpdating(rowData, true);
                  }
                }),
                rowData => ({
                  icon: DeleteOutline,
                  tooltip: "Delete",
                  onClick: (event, row) => {
                    this.bountyModalDeleteForm();
                  }
                }),

                {
                  icon: Add,
                  onClick: (event, rowData) => {
                    isRowUpdating(rowData, true);
                    console.log('New record !');
                  },
                  isFreeAction: true,
                  tooltip: 'New record',
                }
              ]}

              components={{
                EditRow: props => {
                  const newRowData = {
                    ...props.data,
                    id:  props.data.id,
                    user: props.data.user,
                  };

                  return (
                    <MTableEditRow
                      {...props}
                      data={newRowData}
                      onEditingCanceled={(mode, rowData) => {
                        isRowUpdating(rowData, false);
                      }}
                      onEditingApproved={(mode, newData, oldRowData) => {
                        isRowUpdating(props.data, false);
                        this.handleSubmitUpdate(newData);
                      }}
                    />
                  );
                },

                Toolbar: props => (
                  <div style={{background: "blue"}}>
                    <StyledMTableToolbar {...props} />
                  </div>
                ),

`

**Comment by oze4** [comment]
This one seems a little more tricky.  Let me dig into this for a little bit.
