### ISSUE TITLE
currencySetting is not defined

### ISSUE THREAD

**Issue by eloyrubinos** [mbrn/material-table#1773]
Hi,

I need to display a currency column in a table and I was going to try and do it using the **currency** column type prop, but it displays USD by default.
I've noticed there exists a **currencySetting** prop in docs which accepts an object and I guess I would be able to specify the currency there, but I can't find any definition or example for the object.

**Comment by anarcometin** [comment]
I was also looking for this.
Going through the TypeScript definition, I think it should be something like this: 
`{ locale?: string, currencyCode?: string, minimumFractionDigits?: number, maximumFractionDigits?: number }`

**Comment by eloyrubinos** [comment]
That works, thank you :)
