### ISSUE TITLE
onRowAdd with no onRowDelete or onRowUpdate has no Actions column but shifts everything to the right

### ISSUE THREAD

**Issue by OrdiNeu** [mbrn/material-table#1776]
**Describe the bug**
If you provide an object to editable with `onRowAdd` but not `onRowUpdate` or `onRowDelete`, there is no action column. If you then create a new row, the first column gets replaced with a checkmark and an x, and every entry is shifted to the right (and off the table)

**To Reproduce**
Please see the following CodeSandbox for a reproduction of the bug:
https://codesandbox.io/s/polished-frog-e0zsn
Click on the Add button at the top right (CodeSandbox appears to have an issue here, so it might show up as "Ad" instead), and observe the positioning of the entries in the table in the new row.
This code is based off of the [Editable example](https://material-table.com/#/docs/features/editable) in the docs.

**Expected behavior**
A new column should have been created to deal with the new checkmark and x, OR it should have been created at the end so as not to shift all of the new data to the right

**Screenshots**
![image](https://user-images.githubusercontent.com/4656440/77943215-e0281d00-728a-11ea-99be-df2d6d80ffda.png).

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Chrome and Firefox
 - Version Chrome 80.0.3987.149 (Official Build) (64-bit) Firefox 74

Thank you for your time.

**Comment by ivan-khuda** [comment]
https://codesandbox.io/s/bitter-pine-16b64?file=/src/App.js

**Comment by weagertron** [comment]
@ivan-khuda although your recommendation would resolve the display issue, it does not fit what @OrdiNeu is experiencing.

I have a similar problem where I have user permissions in a CRUD style and if a user has the permission to Create but not Update then this display issue occurs. It may not always be desirable to have Create _and_ Update permissions.

I am also looking for a solution to this problem

**Comment by noksenberg** [comment]
This one really hurts the usability of the table.

**Comment by noksenberg** [comment]
This can be temporarily fixed by providing an empty string as the header for the actions column.

**Comment by amitava82** [comment]
@noksenberg Example please? Not sure where to add this.

**Comment by amitava82** [comment]
Any fix or workaround for this yet?

**Comment by saunlani** [comment]
bump
