### ISSUE TITLE
Change Edit behavior

### ISSUE THREAD

**Issue by jpparedesm9** [mbrn/material-table#1780]
Hi guys, please I need to modify the normal material-table behavior. I would like to display a custom message before to edit a row I mean, if you notice when you try to delete a row you receive a confirmation message before to proceed I would like to do the same with edit button (get a confirrmation message before to update the row).

I really appreciate your help.

**Comment by bladerunner2020** [comment]
That's really very sad that there is no way to detect if the table is in editing mode, add data validation and callbacks on changing editing mode... 
I have seen some related PRs but none were accepted...

**Comment by Domino987** [comment]
Would you like to see that before or after you press the edit button, or on save?
