### ISSUE TITLE
Getting unnecessary console warning when not rendering header

### ISSUE THREAD

**Issue by jakeleventhal** [mbrn/material-table#179]
**Describe the bug**
When the option for `header` is set to false, there are no titles to be shown for each column. However, if you don't include a title attribute in the `columns` prop, you get the following console warning:
``index.js:2178 Warning: Failed prop type: The prop `columns[0].title` is marked as required in `MaterialTable`, but its value is `undefined`.``

**To Reproduce**
Create a table with the header option set to false.
Use the following code for data the `columns` and `data` props:
`columns={[{ field: 'name' }, { field: 'value' }]}
data={[
   {
      name: 'Example',
      value: 'hello'
   }
]}`

**Expected behavior**
No console warnings

**Comment by mbrn** [comment]
You are right @jakeleventhal . I will look at this for next release.
