### ISSUE TITLE
Date format in column type date.

### ISSUE THREAD

**Issue by Androsv96** [mbrn/material-table#1790]
Is there anyway to set a specific date format for column type  date?
Current is: 04.02.2020 when editing. After editing is 4/2/2020
Wanted: 04-02-2020.

I have the following table

```javascript
 <MyTable
    title={TABLE_TITLE}
    columns={TABLE_COLUMNS}
    data={data}
    editable={{
      onRowUpdate: (newData, oldData) =>
        new Promise((resolve, reject) => {
          setTimeout(() => {
            {
            }
          return resolve();
          }, 1000)
       }),
    onRowAdd: (newData) =>
       new Promise((resolve, reject) => {

            setTimeout(() => {
                {
                   let tempNewData = data.concat({
                     ...newData, bornDate: MOMENT(newData.bornDate).format("DD-MM-YYYY"),
                     otherDate: MOMENT(newData.otherDate).format("DD-MM-YYYY"),
                     action: "added"
                  });
                  setData(tempNewData):
              }
            return resolve();
             }, 1000)
   }),
}}
```
As you see rigth after the user adds a row and selects a date I formate it to DD-MM-YYYY. It shows correctly. But if the user tries to modify it, the following error appears in the field:
![Untitled](https://user-images.githubusercontent.com/46198501/78266797-dfca9480-74cb-11ea-9619-29c134c66342.png)

Or is there anyway to disable that error msg?
Thanks.

**Comment by GusMartins499** [comment]
same issue

**Comment by yfrfelipe** [comment]
Same issue here too.
