### ISSUE TITLE
Column's defaultSort places column's arrow backwards

### ISSUE THREAD

**Issue by bvicinus** [mbrn/material-table#1792]
Tested this using columns of strings, numbers, and datetimes (with custom sorting functions). 
The default sort does sort the data correctly, it just displays an arrow in the improper direction. 
Using `defaultSort="asc"` places a downwards arrow on the column when it should be an upwards arrow. And vice versa. 

Removing the defaultSort fixes the issue (the arrows work as intended if you click on the column).

**Comment by william13murphy** [comment]
@bvicinus I noticed this as well. Quick fix included using ArrowDownward  instead of ArrowUpward
