### ISSUE TITLE
CustomFilters in Toolbars

### ISSUE THREAD

**Issue by sergio222-dev** [mbrn/material-table#1793]
Is there a way to put custom filters components inside of the toolbar?
The props on Custom Components Toolbar don't have any filter function that you can use to filter all data.

**Comment by renemroger** [comment]
I am trying to do the same thing. If I manage to find I way I will let you know.

**Comment by proohit** [comment]
As a workaround, you may be able to filter by managing your own filtered collections passing them to the table. Here is an example (I excluded any filtering algorithms, that's up to you):
```typescript
const data = [{ name: "Example1" }, { name: "Example2" }, { name: "Example3" }];
class FilterExample extends React.Component<{},{items: any[], filteredItems: any[]}> {
  state = {
    items: data,
    filteredItems: data,
  };

  handleFilterChange = (filterKey: string) => {
      //handle filtering
  };

  render() {
    return (
      <div>
        <MaterialTable
          columns={[
            { title: "Name", field: "name" },
          ]}
          data={this.state.filteredItems}
          components={{ FilterRow:()=><CustomFilterRow onFilterChange={this.handleFilterChange}/> }}
          options={{ filtering: true }}/>
      </div>
    );
  }
}

const CustomFilterRow: React.FunctionComponent<{onFilterChange: (filterKey: string) => void;}> = (props) => {
  return (
    <div>
      <Grid>
          <TextField label="name" type="text" onChange={(e)=>props.onFilterChange(e.target.value)}></TextField>
      </Grid>
    </div>
  );
};
```
You create a custom "FilterRow" in Components prop of the table. The input events are being created in the CustomFilterRow and handled in the FilterExample class. The data you want to finally show are being passed to MaterialTable.
