### ISSUE TITLE
prevent local sort event

### ISSUE THREAD

**Issue by omidmoradzadeh** [mbrn/material-table#1798]
I have an external data provider. so when I click on a column name for sorting, local sort fire and I can't find any event to prevent default it. can anyone help me to stop local sorting and wait for data from props?

` onOrderChange={(columnId, order ) => {
                    this.props.onOrderChange(name, columnId, order)
}}
`

in this event, I want to access an event to stop propagation.
Thank you.

**Comment by wlenzeder** [comment]
I'm having the same issue: after a column header is clicked, the currently displayed data is sorted locally before the request is sent to the server. When the new data is available, it is displayed with the rows being sorted like the old data. The rows are not sorted 1:1 like the server sent them and as they should be displayed.

I could work around this by setting a `customSort` on each column definition which does not change the already sorted data locally:

```
customSort: () => 0,
```

Hope that helps ..  but I'm also looking for a proper fix / solution.
