### ISSUE TITLE
Filter and sort not working if i wrapped the column text inside html

### ISSUE THREAD

**Issue by kailaskadam** [mbrn/material-table#1802]
**Describe the bug**
I have one of the column "component Title" which list the titles from API and renders the titles in material-table title column
column:-
[
    { title: 'Component Title', field: 'componentTitle' },
    { title: 'Created By', field: 'createdBy' }
]

Data:-
componentTitle:<a href="#" onClick={() => handlePreview(row.id)} >row.componentTitleName</a>
                    createdBy: row.createdByName,

The data renders correctly
but when i try to filter or sort component title it won't work.

**Expected behavior**
It should sort and filter the grid data according to component title

**Screenshots**

**Desktop (please complete the following information):**
 - OS: WIN 10
 - Browser Chrome
 - Version 78

is there any way to resolve this issue?

**Comment by lkostrowski** [comment]
Filter & search works for string data. It's fairly reasonable. If you use custom render, use `customFilterAndSearch` and provide your algorithm
