### ISSUE TITLE
Is there any way to show a confirmation alert in the same row data when using a custom action?

### ISSUE THREAD

**Issue by mtoan2111** [mbrn/material-table#1803]
Hi! 
Thanks for your wonderful library,

I would like to show a confirmation alert in the same row data when using a custom action. It looks like the built-in confirmation of onDeleteRow() action.

![image](https://user-images.githubusercontent.com/15266976/78695591-8083de80-7928-11ea-9dfd-65cc7100f31b.png)

Here is my custom action: 
``` 
action = [
   {
        icon: <LabelOff />,
        tooltip: 'help',
        onClick: (event, data) => {}
   }
]

 <MaterialTable actions={this.action} />
```

Does anyone have an idea?
Thanks for reading my issue!

**Comment by bleuscyther** [comment]
Same issue/feature: https://github.com/mbrn/material-table/issues/1968
