### ISSUE TITLE
Document how to correctly style the table header

### ISSUE THREAD

**Issue by chilversc** [mbrn/material-table#1804]
**Describe the bug**
I tried to follow the documentation on styling the header, overriding the header using `withStyles` and overriding the theme. In all cases I could not find a way to make the header correctly handle a dark background. I had specific trouble when it came to the sorting indicator.

**To Reproduce**
* https://material-table.com/#/docs/features/styling
* Sort one of the column headers
* The text will change to black text
* The sort icon will be in black

When viewed on a darker background such as purple or black this can make the text and the sort icon illegible.

**Expected behavior**
There should be a simple way to change the palette for the header (e.g. dark background with white text) that cascades to all the components in the header (such as the sorting label).

**Screenshots**
![image](https://user-images.githubusercontent.com/145440/78707747-eeb8a900-7908-11ea-8185-6431933cf732.png)

**Comment by usahai** [comment]
I have found a way for the sorting indicator:
```
SortArrow: forwardRef((props, ref) => <ArrowDownward {...props} ref={ref} style={{ color: "#ffffff"}} />),
ReturnToLabelSpec: forwardRef((props, ref) => <ArrowUpward {...props} ref={ref} style={{ color: "#ffffff"}} />),
```
wherever you're doing the imports for the colors. If you figure something out for the headers, please update it here. It would greatly help!
