### ISSUE TITLE
Changing the rowsPerPage doesn't display all of the rows if the number is higher than the amount of rows it starts with

### ISSUE THREAD

**Issue by roseak** [mbrn/material-table#1805]
**Describe the bug**
If the first data you load into the table has x number of rows per page, you can change the rows per page to be amounts that are smaller or equal to x,  but you can't do higher.  

**To Reproduce**
Have the default pageSize set to 100 with server side pagination.  If you change the rows per page to be 25 or 50, it'll change and show the correct amount.  If you click on 200, even if the prop data now has 200 items, it still will only show the first 100.  Not sure what's happening to the rest of the items, since the data being passed into the prop is correct and the pageSize and rowsPerPage and page are all correct.

**Comment by telperion357** [comment]
I have updated from 1.39.0 to 1.57.2, and now facing the same issue.

**Comment by fabiiomariiano** [comment]
Is there any update about this issue?

**Comment by madhuraadawadkar** [comment]
I am facing exactly same issue. Any updates on this?

**Comment by itusuarez** [comment]
This was my work around:

<MaterialTable
                tableRef={tableRef}
                columns={columns}
                data={data}
                options={{
                    showTitle: false,
                    headerStyle: {
                        fontWeight: "bolder"
                    },
                    pageSizeOptions: rowsPerPage,
                    pageSize: pageSize,
                    emptyRowsWhenPaging: false
                }}
                components={{
                    Toolbar: () => null,
                    Pagination: (props) => (
                        <TablePagination
                            {...props}
                            onChangeRowsPerPage={(event: React.ChangeEvent<HTMLInputElement>) => {
                                props.onChangeRowsPerPage(event);
                                setPageSize(parseInt(event.target.value, 10));
                            }}
                        />
                    ),
                }}
            />

**Comment by itusuarez** [comment]
`<MaterialTable
                tableRef={tableRef}
                columns={columns}
                data={data}
                options={{
                    showTitle: false,
                    headerStyle: {
                        fontWeight: "bolder"
                    },
                    pageSizeOptions: rowsPerPage,
                    pageSize: pageSize,
                    emptyRowsWhenPaging: false
                }}
                components={{
                    Toolbar: () => null,
                    Pagination: (props) => (
                        <TablePagination
                            {...props}
                            onChangeRowsPerPage={(event: React.ChangeEvent<HTMLInputElement>) => {
                                props.onChangeRowsPerPage(event);
                                setPageSize(parseInt(event.target.value, 10));
                            }}
                        />
                    ),
                }}
            />`

**Comment by itusuarez** [comment]
`
<MaterialTable
                tableRef={tableRef}
                columns={columns}
                data={data}
                options={{
                    showTitle: false,
                    headerStyle: {
                        fontWeight: "bolder"
                    },
                    pageSizeOptions: rowsPerPage,
                    pageSize: pageSize,
                    emptyRowsWhenPaging: false
                }}
                components={{
                    Toolbar: () => null,
                    Pagination: (props) => (
                        <TablePagination
                            {...props}
                            onChangeRowsPerPage={(event: React.ChangeEvent<HTMLInputElement>) => {
                                props.onChangeRowsPerPage(event);
                                setPageSize(parseInt(event.target.value, 10));
                            }}
                        />
                    ),
                }}
            />
`

**Comment by itusuarez** [comment]
This was my work around:
```
<MaterialTable
                tableRef={tableRef}
                columns={columns}
                data={data}
                options={{
                    showTitle: false,
                    headerStyle: {
                        fontWeight: "bolder"
                    },
                    pageSizeOptions: rowsPerPage,
                    pageSize: pageSize,
                    emptyRowsWhenPaging: false
                }}
                components={{
                    Toolbar: () => null,
                    Pagination: (props) => (
                        <TablePagination
                            {...props}
                            onChangeRowsPerPage={(event: React.ChangeEvent<HTMLInputElement>) => {
                                props.onChangeRowsPerPage(event);
                                setPageSize(parseInt(event.target.value, 10));
                            }}
                        />
                    ),
                }}
            />
```
