### ISSUE TITLE
unable to call defaultExportCsv() from custom overridden exportCsv() function

### ISSUE THREAD

**Issue by Vinayak-SP** [mbrn/material-table#1806]
I want to have a timestamp as the file name, passing the file name as property to options.exportFileName will get the timestamp when the page got rendered instead of when the export button was clicked. Hence I was trying something like below and I'm unable to call the `defaultExportCsv()` from the overridden `exportCsv()`

```
function Index({model}) {
  const handleExportCsv = () => {
    // set filename as timestamp here
    // call defaultExportCsv() here 
  }

  return (
    <MaterialTable
      columns={[
        { title: 'ID', field: 'id' },
        { title: 'Name', field: 'name' },
      ]}
      data={model}
      title="Title"
      options={{
        columnsButton: true,
        exportButton: true,
        actionsColumnIndex: -1,
        exportCsv: handleExportCsv
      }}
    />
  );
}
```

I have opened [stackoverflow question](https://stackoverflow.com/questions/61079702/how-to-call-defaultexportcsv-of-reactjs-material-table-from-the-overriden-expo) as well but didn't get answers there yet.

**Comment by fflsogliani** [comment]
any updates ?

**Comment by zacheryph** [comment]
I attempted extending `MTableToolbar` to override the `defaultExportCsv` method to no avail. `babel` turns this into a non-constructor for packaging it looks like and thus cannot be done, at least not the way i was trying.

**Comment by Vinayak-SP** [comment]
@zacheryph can it be at least given support of `tableRef`? So that it can be invoked by `tableRef.current.defaultExportCsv`.

**Comment by Domino987** [comment]
Cant you just use the `exportFileName` prop for that?

**Comment by Vinayak-SP** [comment]
@Domino987 Nope, the request is to call the `ddefaultExportCsv` from `exportFileName` prop. I don't think you have gone through the issue posted.

**Comment by Domino987** [comment]
I did but I thought exportFileName  also accepts a function. I opened a PR to fix that. With that you can pass a function to get the current date: exportFileName: () => new Date().toLocaleDateString()

**Comment by KeshriAyushi22** [comment]
Can anybody help me to point out, how to export hidden columns in csv? i tried giving  exportAllData: true. Still no luck
