### ISSUE TITLE
Duplication issue in Grouping date field 

### ISSUE THREAD

**Issue by SanthoAnbros** [mbrn/material-table#1810]
Getting duplication issue while grouping the date field, passing datetime value to the field and set property for the particular column to "date".
When i am trying to group by particular date column its not gives proper grouping, it shows multiple occurrence.
![image](https://user-images.githubusercontent.com/42858461/78924298-2c5b3480-7ab7-11ea-92cc-b1159f10c4a6.png)
![image](https://user-images.githubusercontent.com/42858461/78924381-501e7a80-7ab7-11ea-8e11-7ec7c81fdade.png)

**Comment by atishwarchand** [comment]
@SanthoAnbros did you manage to fix this Multiple Occurances issue?
