### ISSUE TITLE
Extra Column when add row

### ISSUE THREAD

**Issue by inpras** [mbrn/material-table#1811]
Editable row columns are not rendered inline of column headers however, there is a not needed column with style `key-detail-panel-cell` is added.

Resolution:
Commenting following lines from file "m-table-edit-row.js" would render editable row properly

`if (this.props.detailPanel) {
        var aligment = this.props.options.detailPanelColumnAlignment;
        var index = aligment === "left" ? 0 : columns.length;
        columns.splice(index, 0, React.createElement(_TableCell["default"], {
          padding: "none",
          key: "key-detail-panel-cell"
        }));
}`

however if you set following

`options={{
        actionsColumnIndex: -1,
  }}`

all columns are rendered fine but action buttons are rendered as last column.

**To Reproduce**
1. Create a material table with multiple detailPanel or user example Multiple "Detail Panels Example"
2. merge editable feature
`editable={{
        onRowAdd: (newData) => {}
}}` or something similar
3. Don't add any actions (I have not added any)
4. Click on + icon when editable row is displayed you shall see that column are not in line

Kindly let me know if I am missing something ...

**Comment by akshayKrSingh** [comment]
I am having the same exact issue. Also when you add `options={{actionsColumnIndex: -1}}` the Actions title is not being displayed for the column.

<img width="1401" alt="Screenshot 2020-04-13 at 8 01 42 AM" src="https://user-images.githubusercontent.com/8209379/79087526-25555000-7d5d-11ea-9164-8b5e17c26173.png">

@inpras were you able to find a workaround for this ?

**Comment by inpras** [comment]
Yes Akshay, 
Commenting following lines from file "m-table-edit-row.js" would render editable row properly

`if (this.props.detailPanel) { var aligment = this.props.options.detailPanelColumnAlignment; var index = aligment === "left" ? 0 : columns.length; columns.splice(index, 0, React.createElement(_TableCell["default"], { padding: "none", key: "key-detail-panel-cell" })); }`
