### ISSUE TITLE
Remote Data and custom filtering: filter value

### ISSUE THREAD

**Issue by dawid-w** [mbrn/material-table#1814]
Let's assume that I use Remote Data in my table.

>  Using this functionality, searching, filtering, sorting and paging are ignored by material-table and have to be manually 

How can i get some column filter value in order to use it in my filter function?
(I can use css selector but that's not very elegant solution)

I have tried to put sth like this as MaterialTable prop:
`
 onFilterChange={(filters) => {
          console.log(filters);
}}
`

but this function have never run, even so the remote data fetch function activates every time i change filter value.

PS. btw, how to avoid reloading data when filter changes?

**Comment by stnguyen90** [comment]
If you're using remote date like https://material-table.com/#/docs/features/remote-data, `query` has the filters. See: https://github.com/mbrn/material-table/blob/b9f35b85d1faaa4a70f6e6b4ffdfd185105ec085/src/material-table.js#L31
