### ISSUE TITLE
Add row programmatically

### ISSUE THREAD

**Issue by chitgoks** [mbrn/material-table#1816]
How to do this?

I wish to add some code when a new row is added. if there is an onEditingAdded event, this would work.

however, only onEditingCanceled and onEditingApproved are there which pertains to the ok and cancel button in the editing row.

Adding onEditingAdded  and onEditingDeleted will help

**Comment by Domino987** [comment]
@chitgoks What do you need that functionality for? Maybe we can find a different way or merge this with different use cases?

**Comment by chitgoks** [comment]
sorry. forgot to close this. i found a workaround in my use case.
