### ISSUE TITLE
[Major Issue] Add Row Inconsistent Behavior When Show Columns (columnsButton) is true

### ISSUE THREAD

**Issue by Vinayak-SP** [mbrn/material-table#1818]
**Describe the bug**
When options.columnsButton is made true, and few columns are unselected, on click of add button will only allow adding fields which are visible.

**To Reproduce**
1. Go to [Editable example]( https://material-table.com/#/docs/features/editable)
2. Click on show the source code and paste this code as property in `<MaterialTable>` tag
```
options={{
          columnsButton: true
        }}
```
3. Click on show columns button (beside add button) and deselect one or two columns (say name column). Now in table Name column is hidden.
4. Now click on the Add button. This will not display the Name field (hidden columns) to type data.

**Expected behavior**
Irrespective of columns selected to show, on click of Add button, it should allow data insertion for all columns.

**Screenshots**
<img width="743" alt="table_bug1" src="https://user-images.githubusercontent.com/10287706/79037972-426e0f80-7bf3-11ea-9cb1-c3da3ac26b21.PNG">
Deselecting Name and Surname columns to hide

<img width="723" alt="table_bug2" src="https://user-images.githubusercontent.com/10287706/79037983-544fb280-7bf3-11ea-8b3f-6ed47f9e4bff.PNG">
On click of add button, data insertion allowed without Name and Surname field.

**Comment by Vinayak-SP** [comment]
@mbrn, please take a look at this problem ASAP.

**Comment by LeanderCoevoet** [comment]
+1 We have the same problem. Is it possible to have an example provided in the documentation?

**Comment by MichielMortier** [comment]
Same problem here. Column does not space when a column is hidden.

**Comment by jarnekerkaert** [comment]
+1 We also have this problem.

**Comment by Vinayak-SP** [comment]
Any updates ?
