### ISSUE TITLE
Table is disabled when data changes under your feet while in row update mode

### ISSUE THREAD

**Issue by bergkvist** [mbrn/material-table#1820]
**Description**
When the data supplied to a table changes "under your feet" while you are editing - you lose focus of the item you were editing, and everything/the entire table is left disabled.

**How to reproduce**
1. Create an editable table, with a data source that might change at any time:
```jsx
function MyTable() {
  const [data, setData] = useState([])
  
  useEffect(() => {
    setData([{ something: 1 }])
    setTimeout(() => setData([{ something: 1 }, { something: 42 }]), 5000)
  }, [])  

  return <MaterialTable
    title='My Table'
    columns={[{ title: 'Something', field: 'something' }]}
    data={data}
    editable={{
      onRowAdd: newData => Promise.resolve()
      onRowUpdate: (newData, oldData) => Promise.resolve()
      onRowDelete: oldData => Promise.resolve()
    }}
  />
}
```
2. Click the edit button on the table, wait 5 seconds - and the entire table is disabled.

**Expected behavior**
1. The table should infer which item it is editing based on index (or a comparison function)
2. If the table is not able to infer which item in the new data corresponds to the old one - it should leave the "row update mode", so that everything is enabled/interactive again.

**Comment by timurista** [comment]
@bergkvist try version bumping to 1.6.0. Works for me so far
