### ISSUE TITLE
Change scrollbars style

### ISSUE THREAD

**Issue by aureliennezzar** [mbrn/material-table#1824]
Hi, im searching to get rid of the 2px white border around scrollbars of the table.
Any hints of how to overwrite scrollbar theme ?

Here its how its look like : 

![scrollbarpng](https://user-images.githubusercontent.com/58041407/79186960-42e8ef00-7e1b-11ea-8738-c640511e25bc.png)

Thanks in advance  !

**Comment by VLRTroll** [comment]
@aureliennezzar, if you until need this answer, let's go.

```
const useStyles = makeStyles({
  tableScrollBar: {
    '& .Component-horizontalScrollContainer-12 ::-webkit-scrollbar-thumb': {
      //CSS Styles here
      borderColor: 'red', // <- This is just an example
    }
  }
});

const App = () => {
  const classes = useStyles();
  ...
  return (
    <MaterialTable
      ...
      components={{
        Container: props => <Paper {...props} className = {classes.tableScrollBar}/>
      }}
    />
  );
};
```

**Comment by aureliennezzar** [comment]
Thanks I will try to update this old project 😁

**Comment by Justin2997** [comment]
Class : `Component-horizontalScrollContainer-12` is generate on every build. The number change. You should do someting like this : `[class*="Component-horizontalScrollContainer"]`.

**Comment by aureliennezzar** [comment]
> Class : `Component-horizontalScrollContainer-12` is generate on every build. The number change. You should do someting like this : `[class*="Component-horizontalScrollContainer"]`.

Okay, thanks you very much 😀

**Comment by Justin2997** [comment]
@aureliennezzar You have also to do a custom "regex" when you build you app. The class should be something link jss12 or jss25...
