### ISSUE TITLE
Add Row - OnCellChange

### ISSUE THREAD

**Issue by chenei** [mbrn/material-table#1825]
Hi,
When adding a new row, I want to run some validation on cell input.
For example, I have a column with **ID** header and when adding a row, the user adding some ID.

Now I want to check that this ID doesn't exist already in the table and then prompt the user (before he finishes to add the row).

Is it possible?

**Comment by Domino987** [comment]
Yes you can do that with the new validate prop of the columns by checking against the data you pass into the table itself.
