### ISSUE TITLE
Is there a callback for handling the event when someone dragged a column and dropped it in the grouping section?

### ISSUE THREAD

**Issue by gtupak** [mbrn/material-table#1829]
I am looking for a callback function similar to `onOrderChange` or `onColumnDragged` but that fires when the user drops a column header in the grouping zone. Am I missing something it by any chance or it's not implemented yet?

Thanks!

**Comment by hongjs** [comment]
following this feature

**Comment by flora8984461** [comment]
is there any progress for this issue?
