### ISSUE TITLE
rowStyle fontFamily does not change in the UI

### ISSUE THREAD

**Issue by PhilMcLachlan** [mbrn/material-table#1830]
**Describe the bug**
rowStyles does not support fontFamily, although headerStyle does.  The font family never changes, even if I use different families.

**To Reproduce**
  return (
    <MaterialTable
      title={title}
      columns={columns}
      data={data}
      actions={actions}
      localization={localization}
      className={className}
      options={{
        search: search,
        searchFieldAlignment: searchFieldAlignment,
        actionsColumnIndex: actionsColumnIndex,
        pageSize: pageSize,
        pageSizeOptions: pageSizeOptions,
        emptyRowsWhenPaging: false,
        rowStyle: {
          fontFamily: 'Courier',
          fontStyle: 'normal',
          fontWeight: 'normal',
          fontSize: '14px',
          lineHeight: '24px',
          letterSpacing: '0.25px',
          color: '#595959',
        },
        headerStyle: {
          fontFamily: 'Courier',
          fontStyle: 'normal',
          fontWeight: 'bold',
          fontSize: '14px',
          lineHeight: '24px',
          letterSpacing: '0.25px',
          color: '#3A3A3A',
        },
        searchFieldStyle: {
          fontFamily: 'Lato',
          fontStyle: 'normal',
          fontWeight: 'normal',
          fontSize: '14px',
          lineHeight: '24px',
          letterSpacing: '0.25px',
          color: '#595959',
        },
      }}
      icons={iconsUsed}
    />
  );

**Expected behavior**
I expect to be able to set fontFamily in rowStyle and see it change on the screen.

![image](https://user-images.githubusercontent.com/44417065/79282902-52505280-7e84-11ea-88a1-e8ab2bb18205.png)

**Desktop (please complete the following information):**
 - OS: OSX Mac
 - Browser chrome
 - Version 81.0.4044.92 (Official Build) (64-bit)

**Comment by raph90** [comment]
Same for me, but issue is with font size and font weight.

**Comment by PhilMcLachlan** [comment]
I ended up using cellStyle to style the row text, so I don't actually need this fix now.  Hope this helps you.

**Comment by mrjdavidfg** [comment]
Same problem here. This should be fixed in a similar way to what was done in this PR: https://github.com/mbrn/material-table/pull/1211
