### ISSUE TITLE
Help on Conditional Selection Boxes Example

### ISSUE THREAD

**Issue by trung-ung** [mbrn/material-table#1833]
Hi,
What I want to achieve is similar to https://material-table.com/#/docs/features/selection under tab Conditional Selection Boxes Example.

![Annotation 2020-04-15 150933](https://user-images.githubusercontent.com/55078059/79335705-20de9200-7f2b-11ea-9e22-8e632e213d5d.png)
I want this checkbox to be not selected when I click on the select all checkbox. I have been struggling not knowing how to implement it since I don't have access to the function to set "checked" state.

**Comment by Domino987** [comment]
Should be resolved with #1787
