### ISSUE TITLE
Responsive Title row

### ISSUE THREAD

**Issue by aress31** [mbrn/material-table#1834]
This library is great and helps to create quick and beautiful tables. However, I have noticed a potential improvement when it comes to responsive design. On mobile devices, on the very first row containing the table title and search field, when the title is too long it gets truncated to leave space for the search field, see the following screenshot.

![image](https://user-images.githubusercontent.com/11601622/79342212-c3474700-7f24-11ea-921d-05dce74f74e1.png)

I would suggest adding an extra option to let the user select the desired behaviour, either wrap the search field on another line or leave it as it is now. Looking forward to hearing your feedback.

**Comment by 3rgo** [comment]
I have the same issue, except I also have 2 free action buttons :
![image](https://user-images.githubusercontent.com/437847/84681023-d9c54b00-af33-11ea-8f70-fca46b4fa51e.png)

For me, the ideal layout would be a first row with the title aligned left and the action buttons aligned right, and the search field on a second row with full width.

Anyone know of a way to achieve that ?

**Comment by carlosfunk** [comment]
I tried passing a custom component to title, but it looks like `overflow: hidden` is set on the parent component so apart from letting me remove the ellipsis it has no effect.

**Comment by Elkanah-me** [comment]
@3rgo, I also wanted to achieve this and it turns out one way was to create a custom toolbar by overriding the original, with the `components` prop. Now, I'm stuck at hooking the custom search field I created to the in-built search algorithm.

**Comment by yossipik** [comment]
You can try to limit the width of the search field to leave more room for the title. This workaround worked for me
```
options={{
  searchFieldStyle: {maxWidth: 'calc(100vw - 160px)'}
}}
```
