### ISSUE TITLE
Override Edit button to perform some custom actions with rowData

### ISSUE THREAD

**Issue by t29gupta** [mbrn/material-table#1837]
I'm working on a React application. We need to override the "onClick" method of the edit button, So that we can perform some actions in between and update the state with current edited row. 
I tried the below mentioned code to get the event. The event is fired but I'm not able to get the rowData from the event.

`  icons={{
                  ...this.state.tableIcons,
                  Edit: props => {
                    return <Edit onClick={e=>this.editPage(e)} />;
                  }
                }}`

I found this code from the related issues, Issues are closed but can't find any resolution yet.
Any help or update regarding the issue is appreciated.

Regards
Tushar

**Comment by perfectstrong** [comment]
How about modifying `onRowUpdate` ?

**Comment by yurivangeffen** [comment]
Same here. `onRowUpdate` is only called after the edit is committed, but I want to update another component when stepping into edit mode of a row. I would expect
```typescript
onRowUpdate: (newData, oldData) => {
  // DO SOMETHING ON CLICK
  return new Promise((resolve, reject) => {
    // DO SOMETHING ON COMMIT
  })},
```
to do exactly that. Unfortunately it only fires after commit.

**Comment by Vinayak-SP** [comment]
@t29gupta I'm working on something similar. I need a Material-UI Dialog to pop on the click of the edit button. Did you get any solution for this?

**Comment by deepak-geeky** [comment]
Hello , i need similar feature in my app ,is there any way we can do it ?

**Comment by Vinayak-SP** [comment]
@deepak-geeky please follow [#1996](https://github.com/mbrn/material-table/issues/1996)
