### ISSUE TITLE
Default Filter not working for numeric columns

### ISSUE THREAD

**Issue by prabhakaryalla** [mbrn/material-table#1848]
**Describe the bug**
I was using version 1.53.0. Default Filter is not working for numeric types. we get empty rows 
Also tried by updating latest version (1.57.2)

**To Reproduce**

1. Add Default filter for the numeric Column.
   ` <MaterialTable
        columns={[
          { title: 'Adı', field: 'name' },
          { title: 'Soyadı', field: 'surname' },
          { title: 'Doğum Yılı', field: 'birthYear', type: 'numeric', defaultFilter: 1980},
          { title: 'Doğum Yeri', field: 'birthCity', lookup: { 34: 'İstanbul', 63: 'Şanlıurfa' } }
        ]}
        options={{
          filtering: true
        }}
        data={[{ name: 'Mehmet', surname: 'Baran', birthYear: 1980, birthCity: 63 }]}
        title="Demo Title"
      />`

2.Error:
we dont find any rows in the table which is wrong
![image](https://user-images.githubusercontent.com/42337157/79866846-06108f80-83fb-11ea-9627-99b1a9bee847.png)

**Expected behavior**
Show display the row after filtering 
![image](https://user-images.githubusercontent.com/42337157/79866644-b8942280-83fa-11ea-8a11-1be0c86f9c2f.png)

**Screenshots**

**Comment by LeQuiD** [comment]
Hi 
Just change the default filter like so.

defaultFilter: filterNumVar ? filterNumVar.toString() : null

the num will be converted to string and it works like a charm :D

**Comment by prabhakaryalla** [comment]
Thanks. :) It works when we convert into string.
