### ISSUE TITLE
Any way to customize columns ?

### ISSUE THREAD

**Issue by kaleshasheik** [mbrn/material-table#185]
Hi,

  Is there any way to customize the columns by adding something like columnstyle ?

Actually, I wanna reduce space between columns . so that, i can place the 2 tables side by side without scrolling.

Thanks,
Kalesha sheik

**Comment by IllusiveBagel** [comment]
Yeah you can use headerStyle

**Comment by IllusiveBagel** [comment]
Not sure if its exactly what you are looking for but when creating the columns you can add custom css using headerStyle

**Comment by kaleshasheik** [comment]
> Not sure if its exactly what you are looking for but when creating the columns you can add custom css using headerStyle

I tried with below

 {
      title: 'Name',
      field: 'name',
      headerStyle: {color: 'white', fontSize: 15,width: '1%'}
     
    },
    {
      title: 'Status',
      field: 'status',
      headerStyle: {color: 'white', fontSize: 15, width: '1%'}
      
    },

But, still width is not considering for columns

**Comment by IllusiveBagel** [comment]
Ok yeah I just tried a similar setup and everything apart from the width is changing for me too

**Comment by martindeanlund** [comment]
You're looking for the "cellStyle" property of "columns" if you're looking to work with column width.

**Comment by hamdi-islam** [comment]
> You're looking for the "cellStyle" property of "columns" if you're looking to work with column width.

Hi, i've tried to use "cellStyle" for resizing one of the columns but it didn't work for me. Here's how i did it.

```
{
            title: "Client",
            field: "client.company",
            cellStyle: { width: "20px" },
}
```
