### ISSUE TITLE
hi, is there a way to hide columns just for the view

### ISSUE THREAD

**Issue by jensysantana** [mbrn/material-table#1856]
hi, is there a way to hide columns just for the view?
i'm trying to hide my ids from an array data
and replace it only in the view for numbers, example: 1, 2, 3, 4, 5, 6, 7, 8, 9 ........

**Comment by perfectstrong** [comment]
Hiding column is as simple as set `hidden=true` in column definition.
Then you can add a view index on data reception, like
```
array.map((element, index) => ({...element, index});
```

**Comment by mkaes** [comment]
I was also wondering if this is possible, but found no way yet.
Using the hidden property does not help if you do not want to display those columns, because they will show up in the columns list and can be enabled.
Some sort of invisible flag would be good, so that it is possible to access the data when a row is rendered but it will never be shown and cannot be enabled.

**Comment by perfectstrong** [comment]
The data will always is accessible from any callback function with `rowData` as parameter. So if you does not list an attribute in `columns` definition, it is still there in `rowData`.

**Comment by mkaes** [comment]
Thanks for the answer. Works like a charm.

**Comment by jensysantana** [comment]
thanks alot. and yes in my columns array [
             { title: "ID", field: "_id", hidden:true,
]

then i have it hidded.

please if you have an example about how to implement view index  will be helpful. and thanks again.

**Comment by perfectstrong** [comment]
That should be straight forward with [`map` syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map).
````javascript
function SimpleAction() {
  return (
    <MaterialTable
      title="Example"
      columns={[
        { title: 'Id', field: 'index' },
        { title: 'Name', field: 'name' },
        { title: 'Surname', field: 'surname' },
        { title: 'Birth Year', field: 'birthYear', type: 'numeric' },
        {
          title: 'Birth Place',
          field: 'birthCity',
          lookup: { 34: 'İstanbul', 63: 'Şanlıurfa' },
        },
      ]}
      data={
           // Data can be retrieved as well by ajax. Use Promise in that case.
           [
               { name: 'Mehmet', surname: 'Baran', birthYear: 1987, birthCity: 63 },
               { name: 'Zerya Betül', surname: 'Baran', birthYear: 2017, birthCity: 34 },
           ].map((element, index) => ({...element, index})
       }        
      actions={[
        {
          icon: 'save',
          tooltip: 'Save User',
          onClick: (event, rowData) => alert("You saved " + rowData.name)
        }
      ]}
    />
  )
}
````

**Comment by jensysantana** [comment]
thank you thank you alot.
for your help. i just fixed.
