### ISSUE TITLE
Re-rendering detail panel

### ISSUE THREAD

**Issue by dancitron** [mbrn/material-table#1863]
Was wondering how to re-render the detail panel. I'm trying to add editable text fields, but have run into the issue of not being able to update State unless I close and re open the panel.

Thanks!

**Comment by kebugcheckex** [comment]
I have a similar issue. In my case the detail panel content is lazy loaded. So the first time it opens it will trigger an action to fetch the content. Once the content is ready, I want to the panel to re-render.

On the high level, my code looks like this:
```javascript
const Container = (props) => {
  console.log('Outside: ', props.content);
  const renderDetailPanel = (rowData) => {
    console.log('Inside', props.content);
    if (props.content == null) {
      dispatchAction('LOAD_CONTENT');
      return <Spinner />;
    }
    return <Content data={props.content} />
  };
  return <MaterialTable detailPanel={renderDetailPanel} />;
}
```

What I observed is that once the content is loaded and ready in `prop`, the detail panel will still render a spinner. I added some logging and realized that the second time the component renders, "outside" will log valid content while "inside" still logs null;

**Comment by renemroger** [comment]
You can let react take care of the re-rendering. I just added editable text fields to a detailed panel and I passed down the value and the setter to the data object.

**Comment by ckalas** [comment]
I'm seeing the same behaviour - at the parent component state is udpated, but inside it is seemingly behind and I have to manually toggle the panel to see the correct value be rendered
