### ISSUE TITLE
Duplicated `key-selection-cell` on row deletion

### ISSUE THREAD

**Issue by lucacattide** [mbrn/material-table#1867]
**Describe the bug**
Basically the same behaviour described on #1584 but during deletion.
In presence of multiple rows, with ```editable``` mode on, if I try to delete something - independently a set or a single row - I receive this exception:
> Warning: Encountered two children with the same key, `key-selection-cell`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.

**To Reproduce**
1. Populate the table with some data
2. Enable the `edit` mode
3. Try to delete a row by clicking on its own proper action - the single one action, not the multiple ```FreeAction``` one
4. Check the console

**Expected behavior**
The issue shouldn't be thrown by clicking on a single delete action of a row. The row keys should be dynamically generated, i.e. ```key={`key-selection-cell-${SOME_INDEX}`}```.
Or better the PR suggested on #1583 could solve the issue.

**Screenshots**
![Screenshot 2020-04-27 at 11 58 34](https://user-images.githubusercontent.com/12085296/80359666-70ec1b80-887e-11ea-9f40-d02fa483dd37.png)

**Desktop (please complete the following information):**
 - OS: OS X 10.15.4
 - Browser chrome
 - Version 84

**Additional context**
This is causing me many troubles, especially in the current Tree Data scenario in which I'm working on. The duplicated keys are preventing the table to set its own internal state properly after a mass rows deletion - the table still stuck in a (```disabled```?) state (check the above screenshot).
I think that this is a consequence of the main issue, which occurs even if parent/child relations between elements are not present.

**Comment by lucacattide** [comment]
I solved the tree data scenario with a different state management of the data involved, but generally the issue persist.

**Comment by JoseHerradez** [comment]
Same happening to me. Is there a workaround to solve this?

**Comment by Adnan-Hussain22** [comment]
Im also facing the same issue. Did you resolved it ?

**Comment by mtahir08** [comment]
any work around on it?

**Comment by WellsSA** [comment]
Same issue here :/
