### ISSUE TITLE
Can we have this plugin for vue js framework ?

### ISSUE THREAD

**Issue by krunalsheth3** [mbrn/material-table#1869]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by oze4** [comment]
Hey @krunalsheth3 porting this to Vue is not currently on the road map. Mostly due to the underlying framework that we use, doesn't support Vue. There are a couple great tables for Vue, though! Goodtable is pretty...well..good :smile:
