### ISSUE TITLE
Custom styling for hovering on table rows

### ISSUE THREAD

**Issue by Jdban** [mbrn/material-table#1870]
I am using `onRowClick` which enables row highlighting on hover, but then I enabled  the `rowStyle` option for `backgroundColor` for some custom behaviour and that appears to have overwritten the row highlighting on hover. 

How can I add back the highlighting on hover?

**Comment by roseak** [comment]
I'm also having the same problem

**Comment by Jdban** [comment]
@roseak We actually found the solution to this, so I will close this. I believe the `''` lets it fall back to default handling of the coloring?

Example:
```
rowStyle: (rowData) => ({
  backgroundColor:
    rowData.index === 5 ? selectedColor : '',
}
```

**Comment by roseak** [comment]
Amazing, thanks!
