### ISSUE TITLE
Is it possible to have vertical table headings in material-table?

### ISSUE THREAD

**Issue by deepankar-ap** [mbrn/material-table#1871]
I'm trying to design a table where headers are present on left-hand side instead of top. Is it possible to design this kind of table layout using material-table? Here's a screenshot for reference: 

![image](https://user-images.githubusercontent.com/58770061/80482189-62326100-8971-11ea-8aec-3725d2ac4f84.png)

**Comment by thanhmd** [comment]
Same question.

**Comment by oze4** [comment]
I do not believe this is possible as things currently stand. I like the idea though! 

Currently, this isn't on the radar but has been added to the list of long term projects, so I'm going to close this issue out. Please reopen if you feel it was wrongfully closed. 

We're currently accepting PRs as well - just FYI! :smile:
