### ISSUE TITLE
Conditional rendering row data

### ISSUE THREAD

**Issue by lakshmikanth-reddy-au2** [mbrn/material-table#1873]
I have row data and i want to render the data on a conditional basis. If a particular row status is INACTIVE that row should not be displayed. How can i achieve  this??

**Comment by JigsWeb** [comment]
You have to filter your data before.

https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Array/filter

**Comment by oze4** [comment]
You should be able to override the Row component. Just add a check before rendering the row. https://material-table.com/#/docs/features/component-overriding
