### ISSUE TITLE
Adding rounded corners to body of table

### ISSUE THREAD

**Issue by martinbkure** [mbrn/material-table#1874]
**Describe the bug**
First of all, thanks all for this component, it's full of good ideas :-).

but my problem is, I'm trying to add rounded corners to just the body of the table, but I've run out of ideas to do it.

I've tried adding a class to the body or just add inline styling like this:

```
components:{{
   Body: props => <MTableBody {...props} className="tablebodyy" style={{ styling... }} />
}}
```
But none of my ideas are working. From css alone I can't seem to catch the right node, so I'm not aware how I would do it.

This is an edge case where only the tbody should have rounded corners (and not the header part of the table), so I reckon, it's not a bug.
 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by RayanBassetti** [comment]
Same problem for me, I can't seem to apply any style to the TableBody.
In my case I've modified the rows to make them squares, but I can't find a way to put a display: flex and flexDirection: row to the Body element.

**Comment by oze4** [comment]
Your best bet is most likely going to be to override either the Body component or the Row component. [More here](https://material-table.com/#/docs/features/component-overriding).
