### ISSUE TITLE
Select all option overrides any conditional selection boxes in the table.

### ISSUE THREAD

**Issue by niketh-boreddy** [mbrn/material-table#1876]
When selection is enabled in a table and conditional selection of rows is enabled, the select all option overrides any conditional selection which is enabled, and selects all rows instead of selecting all the enabled rows.

1. Go to https://material-table.com/#/docs/features/selection
2. Click on 'Conditional Selection Boxes Example' tab
3. Click on the select all checkbox next to Name
![screenshot-material-table-com-1588354605579](https://user-images.githubusercontent.com/62398805/80827338-a784a780-8b98-11ea-840c-40ea04712e06.png)

**Expected behavior**
Only one of the rows should be selected

**Comment by sahanjith** [comment]
Hi @niketh-boreddy 

Have you found any workaround? having the same issue.

**Comment by niketh-boreddy** [comment]
Hi @sahanjith 
I've currently disabled the select all checkbox for my table.
You should be able to use the option `showSelectAllCheckbox` set to false for achieving the same

**Comment by joshakeman** [comment]
I noticed the same problem in my application and in my case this amounted to a fairly serious vulnerability that could have led to bad stuff. I should have checked it more thoroughly myself but I thought it was worth flagging, maybe the documentation should have a warning about this.

**Comment by nikme** [comment]
Spent a few hours today searching for the problem, 

The root cause is in data-manager.js on function _changeAllSelected_ you have next line of code
```
this.searchedData.map(function (row) {
          row.tableData.checked = row.tableData.disabled ? false : checked;
          return row;
        });
```
but row item itself doesn't have property disabled in tableData object.

and function for rendering row does use property _selectionProps_ in m-table-row.js file to get this from props.
e.q.
```
selectionProps: (rowData: PaymentUser) => ({
                  disabled: rowData.isPaid,
                  color: 'primary'
                })
```

I will continue to try to find a fix.

**Comment by nikme** [comment]
@Domino987 Why closing when this is still not working?

![image](https://user-images.githubusercontent.com/7325556/87561309-c76a3880-c6bc-11ea-8eee-d77306ec4008.png)

**Comment by MatiasCiccone** [comment]
@nikme try this https://github.com/mbrn/material-table/pull/1787#issuecomment-688826222
