### ISSUE TITLE
Date Format for the column

### ISSUE THREAD

**Issue by suhasbhatta** [mbrn/material-table#1879]
**Custom formatter for date type in the column**
How can i use custom rendering for the date in the column. As of now the date comes as 06/04/2020, but i want it as 06-Apr-2020. How can i do this.

**Comment by hongjs** [comment]
try this
```
{
          title: 'title_text',
          field: 'field_name',
          render: row => <span>{ row["field_name"] /*formatting code here*/ }</span>
}
```

**Comment by oze4** [comment]
@suhasbhatta it looks like there is a solution for this. Please reopen this issue if needed.

**Comment by suhasbhatta** [comment]
> @suhasbhatta it looks like there is a solution for this. Please reopen this issue if needed.

Sure. Thank you. :)
