### ISSUE TITLE
Having a custom render prop for actions

### ISSUE THREAD

**Issue by slevy85** [mbrn/material-table#188]
Hi,

I am trying to have a custom action component that provides `onClick` functionnality and I didn't succeed to do it.
I know I can change the icon to be a component and pass him properties like this :  
```javascript
const actions = [{
      icon: MyActionIconComponent
      iconProps: { prop1, prop2},
    }]
```

```javascript
function MyActionIconComponent({prop1,prop2}) {
  return <ActionIcon onClick={myClick}/>
```

But then the click handler is not called.

I am not sure why, I have in the code that the action icon is wrapped in a `IconButton` which provides onClick event, so maybe this event is not bubbled to my component.

Maybe a solution will to allow to let the actions be completely different :  
```javascript
const actions = [{
      render: rowData => <MyActionIconComponent prop1 prop2 />
    }]
```

What do you think ?

**Comment by mbrn** [comment]
Hi @slevy85,

I tried something like this: You should not use onClick on your own icon component. It already has an click handler and call your onClick. 

```
const MyActionIconComponent = (props) => <div>{props.prop1}-{props.prop2}</div>;

class App extends Component {
  state = {
    selectedCount: 0,    
    data: [
      { name: 'Mehmet', surname: 'Baran', birthYear: 1987, birthCity: 63, sex: 'Male', type: 'adult' },
      { name: 'Gülcan', surname: 'Baran', birthYear: 1987, birthCity: 34, sex: 'Female', type: 'adult' },
      { name: 'Zerya Betül', surname: 'Baran', birthYear: 1987, birthCity: 34, sex: 'Female', type: 'child' }
    ],
    columns: [
      { title: 'Adı', field: 'name' },
      { title: 'Soyadı', field: 'surname' },
      { title: 'Cinsiyet', field: 'sex' },
      { title: 'Tipi', field: 'type' },
      { title: 'Doğum Yılı', field: 'birthYear', type: 'numeric' },
      { title: 'Doğum Yeri', field: 'birthCity', lookup: { 34: 'İstanbul', 63: 'Şanlıurfa' } },
    ]
  }

  render() {
    return (
      <div style={{ maxWidth: '100%' }}>
        <MaterialTable
          columns={this.state.columns}
          data={this.state.data}
          title="Demo Title"
          options={{
            filtering: false,
            exportButton: true,
            exportDelimiter: ';',
            grouping: true,
            selection: false
          }}
          actions={[{
            icon: MyActionIconComponent,
            iconProps: { prop1: 'a', prop2: 'b'},
            onClick: (event, rowData) => alert(rowData.name)
          }]}
        />
        {this.state.selectedCount}
        <button onClick={() => {
          this.setState({ selectedCount: this.state.selectedCount + 1 });
        }}>
          ok
        </button>
      </div>
    );
  }
}
```

![image](https://user-images.githubusercontent.com/7895451/51846916-a4629200-232b-11e9-9404-341c5089906a.png)

**Comment by slevy85** [comment]
Yes but in my case I already have the click handler in the custom component, it is reused in other place so I don't want to duplicate the logic.

**Comment by mbrn** [comment]
Did you try event.stopPropagation(); in your click handler.

**Comment by slevy85** [comment]
Yes it ididn't work, it is like this :  
```html
<button class="MuiButtonBase-root-321">
    <span class="MuiIconButton-label-417">
         <svg class="MuiSvgIcon-root-446">
               <path d="...."></path>
        </svg>
     </span>
</button>
```
The button tag is the `IconButton` component, it has `onClick` handler, my component is inside, it is the svg icon. It also has an click handler, but it is never called because the top level button is the one receiving the click event

**Comment by mbrn** [comment]
Why do you need your own click handler. If you remove button from your code and use span>svg as icon, is it working?

```javascript
icon: props => (
 <span class="MuiIconButton-label-417">
         <svg class="MuiSvgIcon-root-446">
               <path d="...."></path>
        </svg>
     </span>
),
onClick: () => { 
  // do what you want here 
}
```

**Comment by slevy85** [comment]
My initial problem is to make the component reusable, I use this action outside of the table in other components.

For example I have the delete action, this action can be executed in the table via the action button, and also can be executed in the detail page of the item.
The deletion logic is encapsulated in a component which provides onClick event and others.
I wanted to use this component in my detail page, and also in the table.

**Comment by slevy85** [comment]
Thank you for you help I have made a workaround.
But what do you think of having `action.render` prop that would allow to render any component ?

**Comment by mbrn** [comment]
It could be added. But for very special cases like this you can implement your own column with custom render.
