### ISSUE TITLE
Is there a way to trigger add action outside the table?

### ISSUE THREAD

**Issue by mkim871** [mbrn/material-table#1880]
https://github.com/mbrn/material-table/blob/3031eab70105df8d88c17984ca5cea878a9eae3f/src/material-table.js#L154

I want to have `add icon` outside of the table then trigger **add action** to the table.
Code seems like it only triggers when there is `onRowAdd` in `editable` property.

Can someone give me a hint?

**Comment by oze4** [comment]
Hello, @mkim871 although it is extremely hacky, this can be accomplished.

[Please see my answer here](https://github.com/mbrn/material-table/issues/830#issuecomment-629228413) as well as [a live demo here](https://stackblitz.com/edit/react-vubq1a?embed=1&file=index.js).
