### ISSUE TITLE
rowStyle not applied to filtered table? 

### ISSUE THREAD

**Issue by brymon68** [mbrn/material-table#1882]
Hello, 

I have a table where I would like to highlight certain rows based on data in the table. 

For instance, say I have a table of Apps and I want to highlight certain apps based on data I already have. The snippet I have provided below is currently working as intended but I notice that if I use the search, the row returned is not styled. Is there a callback I should be using? 

My table options looks like: 
`
           options={{
              rowStyle: (rowData) => ({
                backgroundColor: check_if_app_blocked(rowData.app_name)
                  ? '#ff3333'
                  : null,
              }),
            }}
`

**Comment by saostad** [comment]
how did you solve your problem?
