### ISSUE TITLE
Table size

### ISSUE THREAD

**Issue by Markohui** [mbrn/material-table#1883]
How to implement table option : size="small" from material-ui table ?

**Comment by Markohui** [comment]
OK, I found it. It is   padding: "dense" in options.

**Comment by sbin0819** [comment]
Thanks, it's what I want ^^

**Comment by ofirkg** [comment]
> OK, I found it. It is padding: "dense" in options.

OMG i was looking for this prop for ages.
i started customizing components until i ran into this issue.
thanks!

this needs to be more clearly documented.

**Comment by Domino987** [comment]
I will close this since a fix was found. I encourage you to add a PR to https://github.com/mbrn/material-table.com to document this. Thank you!
