### ISSUE TITLE
How to add another option to exportCsv option?

### ISSUE THREAD

**Issue by ShadeeCat** [mbrn/material-table#1886]
I need to multiple choice button with setting a Excel export - the export I'll implement like exportCsv overriding option
Can I do it declaratively without modifying the source code?

```JSX
options={[{
    exportButton: true,
    exportLabel: 'Export as CSV',
    exportCsv: (columns, data) => {
        alert('You should develop a code to export ' + data.length + ' rows');
    }
}, {
    exportButton: true, 
    exportLabel: 'Export as Excel',
    exportCustom: (columns, data) => { /* third party code */ }
}]}
```

**Comment by oze4** [comment]
Hey @ShadeeCat this is possible to accomplish via actions.

Use [`isFreeAction`](https://material-table.com/#/docs/features/actions) to accomplish desired behavior.

[Live demo can be found here](https://stackblitz.com/edit/react-grwdwv?embed=1&file=index.js)

```javascript
import React, { useState } from "react";
import { render } from "react-dom";
import MaterialTable from "material-table";
import SaveAltIcon from '@material-ui/icons/SaveAlt';
import tableIcons from "./TableIcons.js";

const rando = max => Math.floor(Math.random() * max);
const words = ["Paper", "Rock", "Scissors"];
const rawData = [];

for (let i = 0; i < 100; i++)
  rawData.push({ id: rando(300), name: words[i % words.length] });

const columns = [
  { title: "Id", field: "id" },
  { title: "Name", field: "name" }
];

const App = () => {
  const [data, setData] = useState(rawData);

  return (
    <MaterialTable
      data={data}
      columns={columns}
      actions={[
        {
          isFreeAction: true,
          icon: () => <SaveAltIcon />,
          tooltip: "Export as CSV",
          onClick: (event, rowData) => {
            alert("Add `Export as CSV` logic here");
          },
        },
        {
          isFreeAction: true,
          icon: () => <SaveAltIcon />,
          tooltip: "Export as Excel",
          onClick: (event, rowData) => {
            alert("Add `Export as Excel` logic here");
          },
        },
        {
          isFreeAction: true,
          icon: () => <SaveAltIcon />,
          tooltip: "Export as ABCXYZ",
          onClick: (event, rowData) => {
            alert("Add `Export as ABCXYZ` logic here");
          },
        }
      ]}
      icons={tableIcons}
    />
  );
};

render(<App />, document.querySelector("#root"));
```

**Comment by jardon** [comment]
@oze4 While that does in fact work, it's less than ideal and aesthetically lacking.  The export implementation doesn't make any sense to me in its current form.  Clicking the export opens a menu that only has a single item?  

For one of my projects, I need to be able to export the data to PDF, but I would also like to keep the CSV functionality.  Since there's already a menu implemented, I would think that adding different export options would make sense.  I could have multiple export buttons, but it's not exactly intuitive.  

Would a custom export option be good? I don't really know tbh.  Maybe having more export options by default would be beneficial.  Just my two cents.  Overall I really love this table

**Comment by oze4** [comment]
@jardon I don't disagree at all. There is def room from improvement.

In my opinion, being able to add export options to the existing menu, with custom handlers, would be awesome.

I'm sure they'd love a PR for this!

**Comment by jardon** [comment]
I just put one in for a pdf export option, but don't quite have an xls export feature figured out.  Architecturally I'm not sure if a custom export option is really all that practical as I kind of doubt it will be used all that much, but making the tooling more flexible definitely isn't bad.  

But worst case CSV/PDF/XLS exporting is pretty inclusive imo.  I may put some time in to get this Excel export feature working for the issue reporter :)

**Comment by oze4** [comment]
I think including export to CSV/PDF/XLSX out of the box would be useful.  I think the author would love some more PRs for this feature! Good stuff man, thanks for the help!

I suppose from here on out we can refer to PRs for this "issue" - not really a need to leave this open.

**Comment by Jsalvat** [comment]
@jardon @oze4 That will be awesome, how it's going? Need any help? We've encontered 2 problems. 
First of all as @jardon says, we can't put more types of exports in the list of 1 item. Second, if we do the export list mannualy, we can't access to filtered data and it sucks.

Anyway, if someone needs any help, /w me.

JS
