### ISSUE TITLE
Actions column occupies the width of all hidden columns when viewed in Firefox.

### ISSUE THREAD

**Issue by telperion357** [mbrn/material-table#1887]
Hi there! Very nice table component!
But I have run into this issue.

**Describe the bug**
Actions column width is much bigger than expected, when the table with hidden columns is browsed in Firefox. The same component looks as expected when browsed in Chrome.

**To Reproduce**
Create the table component with some hidden columns and "Show columns" button, and some in-row actions like edit or delete.   
Set options columnsButton: "true" and tableLayout: "fixed".  
Add some data.  
Open the result in firefox.  
[See an example on Codesandbox](https://codesandbox.io/s/material-table-with-hidden-columns-cndj4) 
  
**Expected behavior**
The actions column occupies a small fixed size. Non-hidden columns occupies almost all the space of the table.  

**Actual behavior when browsed in Firefox**
![image](https://user-images.githubusercontent.com/9952749/81171635-61b74d00-8fa5-11ea-9de1-f155690627bd.png)  

**Desktop:**
 - OS: [Linux Mint 19]
 - Browser [Firefox for Linux Mint]
 - Version [75.0 (64-bit)]

**Comment by nick-romano-kci** [comment]
also in chrome

**Comment by nickdnickd** [comment]
Dealing with this now, it might have to do with how the action cell is styled. 
I've been plugging in random style objects from [this](https://github.com/mbrn/material-table/issues/888) thread to get the action buttons to center. Not ideal.

**Comment by JoeryH** [comment]
Hi guys, I managed to monkey patch this as follows. Basically we have to filter out hidden columns when setting the width and we need to recalculate that more often.

```js
import DataManager from 'material-table/dist/utils/data-manager'
import MT from 'material-table/dist/material-table'

MT.prototype.componentWillUpdate = function(nextProps) {
    const props = this.getProps(nextProps);
    this.dataManager.setColumns(props.columns);
}

DataManager.prototype.setColumns = function(columns) {
    const undefinedWidthColumns = columns.filter(c => c.width === undefined);
    let usedWidth = ["0px"];

    this.columns = columns.map((columnDef, index) => {
        columnDef.tableData = {
            columnOrder: index,
            filterValue: columnDef.defaultFilter,
            groupOrder: columnDef.defaultGroupOrder,
            groupSort: columnDef.defaultGroupSort || 'asc',
            width: columnDef.width,
            ...columnDef.tableData,
            id: index,
        };

        if(columnDef.width !== undefined) {
            if(typeof columnDef.width === "number") {
                usedWidth.push(columnDef.width + "px");
            }
            else {
                usedWidth.push(columnDef.width);
            }
        }

        return columnDef;
    });

    usedWidth = "(" + usedWidth.join(' + ') + ")";
    const undefinedVisibleColumns = undefinedWidthColumns.filter(columnDef => !columnDef.hidden)
    undefinedWidthColumns.forEach(columnDef => {
        columnDef.tableData.width = `calc((100% - ${usedWidth}) / ${undefinedVisibleColumns.length})`;
    });
}
```

**Comment by marioscialpi** [comment]
Try set `width: 0` within hidden columns:

```
{ title: 'Type', field: 'type', hidden: true, width: 0},
...
```

**Comment by rodrigoverasantis** [comment]
> Try set `width: 0` within hidden columns:
> 
> ```
> { title: 'Type', field: 'type', hidden: true, width: 0},
> ...
> ```

Not sure why, but totally worked for me for a weird issue. When setting <hidden: true> for a column, it will hide, but <Hidden Columns Button> won't show the column to show it back, so I have to include <hiddenByColumnsButton: true>. Then, when I click to show back the column it will crash. Adding <width: 0> fixed it.

**Comment by jonbjo** [comment]
I also have this issue but not due to the "Add or remove column". I use a lot of editable tables and in all of them I have an id column that is needed to post updates to the database, but it is hidden from the user in the tables. This causes the action column to be super wide though. Any ideas how to make this work well?

**Comment by Sefton419** [comment]
This is definitely still an issue. If action is hidden, it should not be included in the calculation of the action column width.

**Comment by hello-josh** [comment]
The width is being calculated as calc((100% - 0px) / number of columns); and number of columns includes hidden columns. I see `calc((100% - 0px) / 15);` for one of my tables
