### ISSUE TITLE
TypeScript typings incorrect for onRowClick prop

### ISSUE THREAD

**Issue by lookitsatravis** [mbrn/material-table#189]
Related to PR #161.

The `onRowClick` prop works as expected, but the TypeScript typings do not currently match the callback signature.

Docs describe the signature as `To handle row click (event, rowData)` which is how it is implemented. But in [index.d.ts](https://github.com/mbrn/material-table/blob/ecee1140e4d34a68dbddcaedff11d1490fac1199/index.d.ts) as of ecee114, the signature looks like this:

```ts
export interface MaterialTableProps {
  // ...
  onRowClick?: (rowData: any) => void;
  // ...
}
```

I was able to work around it by doing the following (in case any finds this before it's patched)

```jsx
// This gives an error:
// Type '(event: any, rowData: any) => void' is not assignable to type '(rowData: any) => void'. [2322]

<MaterialTable
  onRowClick={(event: any, rowData: any) => { this.onRowClicked(rowData) } }
/>

// This workaround is okay, but obviously not ideal.

const self = this;

<MaterialTable
  onRowClick={function (event: any) { self.onRowClicked(arguments[1]) } }
/>
```

**Comment by mbrn** [comment]
This is fixed. It will be in next release
