### ISSUE TITLE
how to change the arrow pagination to numbering pagionation?

### ISSUE THREAD

**Issue by a-ditucalan** [mbrn/material-table#1891]
hi i would like to change the arrow pagination to numbering pagination? is there a way to overide? 
![image](https://user-images.githubusercontent.com/58244709/81252383-60932800-9058-11ea-854b-0c71cfc3c77a.png)

**Comment by oze4** [comment]
Yes, this is possible.  You have to use `stepped` under `options.paginationType`..

[See here for more (under the 'options' section).](https://material-table.com/#/docs/all-props)

<img width="654" alt="image" src="https://user-images.githubusercontent.com/21092343/82136965-07a25d00-97d9-11ea-9cc3-17f9a81f6053.png">
