### ISSUE TITLE
Anyone knows of author's current status?

### ISSUE THREAD

**Issue by ifndefdeadmau5** [mbrn/material-table#1896]
Last stable release was almost 3 months ago, over 700+ issue aren't handling
just wondering if he has a problem with maintaining this project(maybe cuz of the virus?)

**Comment by aaronlna** [comment]
> I will return back to material-table project asap. But it seems i need about at least 1 or 2 months. Then we may organize a volunteer team to improve material-table. 

This was from mid-March.

**Comment by ifndefdeadmau5** [comment]
@aaronlna Thanks for info :)

**Comment by oze4** [comment]
I went ahead and started a fork of this repo that will be maintained. [You can read more here](https://github.com/oze4/material-table-core#readme), but my goal is to resolve outstanding issues/PR's without drastic changes to the codebase..

[@material-table/core](https://www.npmjs.com/package/@material-table/core#demo)

**Comment by cada592** [comment]
Thanks :)
