### ISSUE TITLE
Change table title variant to 'h5'

### ISSUE THREAD

**Issue by bzhang42** [mbrn/material-table#1899]
The default title for material-table has variant 'h6', but I want it to be 'h5'. I attempted to do this by passing in `title={<Typography variant={'h5'}>Table Title</Typography>}`, but this loses the other helpful styling like wrap and ellipses. How do I keep all the rest of the styling but only change the variant?

**Comment by oze4** [comment]
Honestly, your best bet is going to be to just recreate the table title component that is used internally.

[Something like this should provide what you are looking for](https://stackblitz.com/edit/react-vcm3qp?embed=1&file=index.js)

```javascript
import React from "react";
import { render } from "react-dom";
import { Typography } from '@material-ui/core';
import MaterialTable from "material-table";
import tableIcons from "./TableIcons.js";

/**
 * Custom title component
 */
const MyNewTitle = ({ text = "Table Title", variant = "h6" }) => (
  <Typography
    variant={variant}
    style={{whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis"}}
  >
    {text}
  </Typography>
);

/**
 * App with material-table
 */
const App = () => {
  return (
    <MaterialTable
      title={<MyNewTitle variant="h5" text="My Cool Table" />}
      data={[]}
      icons={tableIcons}
    />
  );
};

render(<App />, document.querySelector("#root"));
```

**Comment by oze4** [comment]
This issue has become stale, please reopen if needed.
