### ISSUE TITLE
Add Scroll Feature

### ISSUE THREAD

**Issue by mbrn** [mbrn/material-table#19]
Add Scroll Feature

**Comment by Domino987** [comment]
How would this feature look like exactly?

**Comment by mbrn** [comment]
It will show a scroll on table-body if table is in a specific heighted div.

**Comment by John0x** [comment]
This would be neat

**Comment by jlubeck** [comment]
Indeed! Any idea when this will be implemented?

**Comment by mbrn** [comment]
Hi @jlubeck ,

You may know, i always adding new features. But i have limited time for this project. I will do this, but i can't promise for a specific date. I will do this asap.

**Comment by jlubeck** [comment]
Totally understandable and thank you so much for the hyper fast response!

**Comment by quocbaondvn2000** [comment]
Hi @jlubeck 
I have followed your instructions
But not working
This is my code
`        <MaterialTable
          components={{
            Body: props =>
              (
                <div style={{ height: 200, width: '100%' }}>
                  <MTableBody {...props} />

                  ),
                  }}
                  ....
                  
          />
`
![2019-03-11_141734](https://user-images.githubusercontent.com/45376591/54108251-04aa2080-440e-11e9-80bb-8a32d505863f.jpg)

**Comment by jlubeck** [comment]
@quocbaondvn2000 I don't think that message was for me... and if you are trying to make @mbrn mentioned he would be implementing, well... it's not implemented yet! :D So let's give him some time and wait for his instructions.

Cheers!

**Comment by quocbaondvn2000** [comment]
@mbrn  I did the Add Scroll function.
Can you add it to your project?
thanks
PR: https://github.com/mbrn/material-table/pull/313
![2019-03-13_164715](https://user-images.githubusercontent.com/45376591/54269315-bcc2ff00-45af-11e9-8bab-81ad051026b9.jpg)

**Comment by mbrn** [comment]
Hi @mbrn ,

Thanks for your contribution. I will review it asap.

**Comment by mbrn** [comment]
This is done with 1.25.0

It is not perfect solution. But it works. 

2nd example at 
https://mbrn.github.io/material-table/#/docz-examples-16-example-others

**Comment by udayreddy** [comment]
The only problem is that the filter row scrolls up as well
