### ISSUE TITLE
how to do custom search in material table

### ISSUE THREAD

**Issue by vijthang61** [mbrn/material-table#190]
I want a method through which I can set up a hook to add custom search functionality, I dont see a way to add custom search.

If there is some prop or options through which we can set up custom search. Let me know. Any example code will be great

**Comment by mbrn** [comment]
You can add a custom search function for every column separetely. Add `customFilterAndSearch` field as function to column that you want to customize search algorithm

**Comment by vijthang61** [comment]
thanks, will use that
