### ISSUE TITLE
Update "editable" docs to properly trigger table re-render on this.setState(...)

### ISSUE THREAD

**Issue by kevin-coelho** [mbrn/material-table#1900]
**Describe the bug**
Using `data={this.state.data}` in parent react component will not trigger render on `this.setState(...)`.

**To Reproduce**
1. Go to [Editable docs](https://material-table.com/#/docs/features/editable)
2. Copy code
3. Run it
4. add / delete don't re-render the table

**To fix (this should be updated in docs)**
Use `data={Array.from(this.state.data)}`

**Expected behavior**
Table should be updated on "add" / "delete" actions on rows

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome

**Comment by Tingwei-Justin** [comment]
Thanks! This works for me! 
By the way, why this works?
