### ISSUE TITLE
Filter Controls do not hold typed text or dropdown value

### ISSUE THREAD

**Issue by PranatoshRoy** [mbrn/material-table#1901]
Hi,
Great Tool. Need urgent help regarding filtering.
I have used filtering in two tables and one is working just fine.
However in the other one, whatever I type in the filter controls it gets deleted right away causing filter to not working.

Kindly help what might be causing this issue where same thing works in another table.
@mbrn  PLS HELP

**Comment by oze4** [comment]
Would you be so kind to provide some code or a demo that reproduces the issue you are having?  As you said, it works in one table but not the other.  This leads me to believe the issue has something to do with what you're doing in the non-working table.
