### ISSUE TITLE
Can you define options.customSort and options.defaultSort together?

### ISSUE THREAD

**Issue by doctorallen** [mbrn/material-table#1903]
I have defined a `customSort` on my table, which appears to work, however it doesn't look like the `defaultSort` option on the column is working. If I comment out the `customSort` the table correctly loads up and sorts by the default direction I set, but once I define a `customSort` it will not load up and sort by default, the user needs to sort the column themselves.

Is there a workaround to sort the table on load if `deafultSort` cannot be defined?

**Comment by oze4** [comment]
It isn't clear what you are trying to do.. can you provide some example code?

**Comment by doctorallen** [comment]
@oze4 I have defined a `customSort` on a column of my table, because I have some custom sorting logic for a specific column. However when the table loads, it does not automatically sort that column, you have to click the column header for it to sort it. I want the behavior of `defaultSort`, how it sorts by a direction when the table loads, on the column that I've defined my `customSort` on. So on load, actually sort the column I defined the custom sorting logic on, not just when the user takes action.

**Comment by oze4** [comment]
Gotcha.. that makes sense.

Why not just apply the custom sorting algorithm (the one you want to use as default) on the data you are passing into material-table?

Something like this:

[You can view a live demo here](https://stackblitz.com/edit/react-ydhhlm?embed=1&file=index.js)

```javascript
import React, { useState } from "react";
import { render } from "react-dom";
import MaterialTable, { MTableBodyRow, MTableEditRow } from "material-table";
import tableIcons from "./TableIcons.js";
import { Edit } from "@material-ui/icons";

const rando = max => Math.floor(Math.random() * max);
const words = [ "Lorem", "ipsum", "dolor", "sit", "amet", "consectetur", "adipiscing", "elit" ];
const rawData = [];

for (let i = 0; i < words.length; i++)
  rawData.push({ id: rando(300), name: words[i % words.length] });

// Custom sorting algorithm that sorts by word length
const myCustomSortingAlgorithm = (a, b) => a.name.length - b.name.length;

const columns = [
  { title: "Id", field: "id" },
  { title: "Name", field: "name", customSort: myCustomSortingAlgorithm }
];

const App = () => {
  const [data, setData] = useState(rawData);

  return (
    <MaterialTable
      data={
        // Apply the custom sorting algorithm to the data
        // that we are passing into material-table.
        data.sort(myCustomSortingAlgorithm)
      }
      columns={columns}
      icons={tableIcons}
      options={{ sorting: true, pageSize: 10 }}
    />
  );
};

render(<App />, document.querySelector("#root"));
```

**Comment by doctorallen** [comment]
@oze4 I suppose that works, but it's not ideal since the table won't indicate which column is being sorted like it does when you set the `defaultSort`, it seems this might be my only option. Thanks.

**Comment by oze4** [comment]
@doctorallen I completely agree - it isn't ideal and they *should* work together..but if you look at the algorithm I'm using as default, you can see that it is sorting by the name property.
