### ISSUE TITLE
Actions and editable

### ISSUE THREAD

**Issue by feleko** [mbrn/material-table#1904]
I use property actions and editable. 
How to change the order in this way the actions(redbox) were at the end and editable(green box) first?
![action](https://user-images.githubusercontent.com/22773283/81650333-07e5d580-9432-11ea-9265-bb5ea53ca824.png)

**Comment by oze4** [comment]
Have you tried changing the order in the actions array? Can you provide an example of this issue?

**Comment by feleko** [comment]
I don't mean actions.

This my code:
```
              <MaterialTable
			isLoading={isLoading}
			title={title ? title : ""}
			columns={columns}
			data={data}
			localization={localization}
			actions={actions}
			editable={editable}
			options={optionsBase}
		/>
```

I want change order of columns   "actions"and  "editable".

**Comment by oze4** [comment]
For this you will have to override all actions - there is no native way to reorder those icons.
