### ISSUE TITLE
Strange actions width

### ISSUE THREAD

**Issue by Wint57** [mbrn/material-table#1906]
Hello. 
First of all, I want to say thank you for your work. This is very handy table.

I try to set up fix actions width. 
```
options={{
            paging: false,
            actionsCellStyle:{maxWidth: '55px',  },
          }}
```
But when I hide some columns,  actions width is expanding. I have tried Opera and Chrome brousers - all the same. Is this a bug?

**Comment by nick-romano-kci** [comment]
this bug stinks. I'm sure there's a better fix.. but if you want a fix today, you can put the following style block in index.html, or a css file. probably a bad idea, since this could have side effects in newer versions.

```
<style>
    .MuiTableCell-root {
      width: 1%
    }
  </style>
```

**Comment by Wint57** [comment]
@nick-romano-kci Thanks a lot for your answer but your magic have not worked in my case. I have added this style twice (into component where there is material-table and into index.html) but something has overrided this style.

**Comment by oze4** [comment]
@Wint57 can you provide a demo of the issue? You can use fork a starter demo to make it easier - [see here for more](https://github.com/mbrn/material-table/blob/master/.github/ISSUE_TEMPLATE/help.md)

**Comment by lfsando** [comment]
Same thing happening with me. If I use columnsButton and hide a few columns, this happens:
![image](https://user-images.githubusercontent.com/10608706/84520443-f6e6e900-aca9-11ea-9b71-0a18a3d2a3e8.png)
