### ISSUE TITLE
Option rowStyle is not applied after filtering in material-table

### ISSUE THREAD

**Issue by marjanatwork** [mbrn/material-table#1907]
**Describe the bug**
Hi,
I want to apply alternate coloring for odd and even rows in material-tabel in react application. I can successfully do it by calling my custom function , "AlternateRowColoring" when the data is loaded  but after I filter any columns the alternate coloring style function, "AlternateRowColoring" does not apply on filtered dataset. Same problem when I use search feature in material-tabel. 

**Expected behavior**
I expect that every time the dataset changes, either by filtering or by searching , the  "AlternateRowColoring" function is called and gives the alternate coloring style to the rows .

**Screenshots**
I call "AlternateRowColoring" in option in rowStyle of <MaterialTable> component:

 options={{
      rowStyle:  x =>  AlternateRowColoring(x) ,
      ...
               }}

I also tried "onFilterChange" event handler in <MaterialTable> to call "AlternateRowColoring" function, but it doesn't work as well:

onFilterChange={() =>  data.map((x, i) => (AlternateRowColoring(x))) } 

I would really appreciate it if you can help .

**Comment by oze4** [comment]
You should be able to use `makeStyles` from Material-UI for this..

[Live demo here](https://stackblitz.com/edit/react-krukbk?embed=1&file=index.js)

```javascript
// Basic idea of what you need to do
const useStyles = makeStyles({
  "@global tbody tr:nth-child(odd)": {
    background: "lightgray"
  },
  "@global tbody tr:nth-child(even)": {
    background: "white"
  }
});
```

```javascript
// Full demo
import React, { useRef, useState } from "react";
import { render } from "react-dom";
import MaterialTable from "material-table";
import { makeStyles } from "@material-ui/core/styles";
import tableIcons from "./TableIcons.js";

const rando = max => Math.floor(Math.random() * max);
const words = ["Paper", "Rock", "Scissors"];
const rawData = [];

for (let i = 0; i < 100; i++) {
  rawData.push({
    id: rando(300),
    name: words[i % words.length]
  });
}

const columns = [
  { title: "Id", field: "id" },
  { title: "Name", field: "name" }
];

const useStyles = makeStyles({
  "@global tbody tr:nth-child(odd)": {
    background: "lightgray"
  },
  "@global tbody tr:nth-child(even)": {
    background: "white"
  }
});

const App = () => {
  const [editable, setEditable] = useState();
  const [data, setData] = useState(rawData);
  const classes = useStyles();

  return <MaterialTable data={data} icons={tableIcons} columns={columns} />;
};

render(<App />, document.querySelector("#root"));
```

**Comment by marjanatwork** [comment]
Hi Matt,
Awesome! It worked for me. Thank you very much for the solution.
