### ISSUE TITLE
Dense padding prop does not apply to EditRow

### ISSUE THREAD

**Issue by LeanderCoevoet** [mbrn/material-table#1908]
**Describe the bug**
If you use the dense option, it does not affect the EditRow.

**To Reproduce**
1. Take the basic example: https://material-table.com/#/docs/features/editable
2. Add this as options:
```
options={{
                    padding: "dense"
}}
```
3. Try to edit or delete a row
4. See that the row has default size.

**Expected behavior**
The EditRow should be dense too. Having the EditRow be a different style from the rest of the table just stands out and looks out of place.

**Screenshots**
![image](https://user-images.githubusercontent.com/24369528/81706170-25399480-9470-11ea-89d3-d6eb1d0aed83.png)

**Desktop:**
- OS: Windows 10
 - Browser: Chrome
 - Version 81

**Additional context**
I saw that there was a related issue but for the header:
 #783

**Comment by oze4** [comment]
It looks like your best bet is going to be to override the `MTableEditRow` componnet and apply the styles that you need. https://material-table.com/#/docs/features/component-overriding

**Comment by LeanderCoevoet** [comment]
I made a pull request with the changes in that will do the dense padding to the table itself by default if it is set global. If it is something that somebody doesn't want then he/she can overwrite it much easier because the size prop is set.

**Comment by oze4** [comment]
Closing this issue out - refer to PR for more info.
