### ISSUE TITLE
I have data worth 1000 rows, so when using grouping, it does not work.

### ISSUE THREAD

**Issue by kdpisda** [mbrn/material-table#1910]
**I have data worth a few thousand rows, so when using grouping, it does not work.**

**To Reproduce**
Add any remote data source with data up to few thousands, and enable grouping.
Now when we try to group any column, it does not group.

**Expected behavior**
It should group as it does otherwise.

**Screenshots**
![screenshot-localhost_3001-2020 05 13-15_12_25](https://user-images.githubusercontent.com/22424149/81797278-3051fa80-952c-11ea-981d-d21a8e5c8e81.png)
It should work like this in very large data as well.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Chrome latest update

**Comment by oze4** [comment]
What do you mean it doesn't work?  Do you get an error?  We are going to need more details in order to assist you..

In the example below, which has 10,000 rows, it works fine..

You can view a [live demo here](https://stackblitz.com/edit/react-t7wmbq?embed=1&file=index.js)

```javascript
import React from "react";
import { render } from "react-dom";
import MaterialTable from "material-table";
import tableIcons from "./TableIcons.js";

const rando = max => Math.floor(Math.random() * max);
const names = ["Rock", "Paper", "Scissors"];
const data = [];

for (let i = 1; i <= 10000; i++) {
  data.push({
    id: rando(3000),
    name: names[i % names.length]
  });
}

const columns = [
  { field: "id", title: "Id" },
  { field: "name", title: "Name" }
];

render(
  <MaterialTable
    data={data}
    icons={tableIcons}
    columns={columns}
    options={{ grouping: true }}
  />, 
  document.querySelector("#root")
);
```

**Comment by kdpisda** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/22424149/82111869-8c539380-9765-11ea-94d9-762c7b46f6a5.gif)
There is no error on the console. Please check the GIF I have attached above.
