### ISSUE TITLE
Currency Format

### ISSUE THREAD

**Issue by ShadrackAdwera** [mbrn/material-table#1912]
My format is 'currency'. Is there a way to remove the $ prefix before the currency?

**Comment by mtahir08** [comment]
@ShadrackAdwera you can add currency format like this
`    {
      title: 'Curreny',
      field: 'field-name',
      type: "currency",
      currencySetting: { currencyCode: 'USD', minimumFractionDigits: 0, maximumFractionDigits: 2 }
    },
`

**Comment by oze4** [comment]
Closing this issue as it looks like there is a solution. Please reopen if needed.

**Comment by ShadrackAdwera** [comment]
Thank you for the assistance

**Comment by ShadrackAdwera** [comment]
> @ShadrackAdwera you can add currency format like this
> ` { title: 'Curreny', field: 'field-name', type: "currency", currencySetting: { currencyCode: 'USD', minimumFractionDigits: 0, maximumFractionDigits: 2 } },`

Hey, thanks but is there a way to completely remove the prefix from the currency code?
