### ISSUE TITLE
Issues with column width and column collisions when using Fixed Columns

### ISSUE THREAD

**Issue by alexanderkho** [mbrn/material-table#1913]
**Describe the bug**
I have a table with up to 40 columns so I want to use a fixed first column and have the rest of the columns be horizontally scrollable. However I am running into strange behavior when using a fixed column and then trying to set the "width" prop.

**To Reproduce**
It works fine if I set all columns to equal width: 

```
const MyTable = ({ tableData }) => {
  const columns = tableData.cols.map(col => ({
    title: col.title,
    field: col.field,
    width: 400
  }));
  return (
    <MaterialTable
      columns={columns}
      data={tableData.data}
      options={{
        fixedColumns: { left: 1 }
      }}
    />
  );
};
``` 

However if I try to adjust the width of just the first column:

```
const columns = tableData.cols.map(col => ({
    title: col.title,
    field: col.field,
    width: 400
  }));
columns[0].width = 200;
```
I get:
![image](https://user-images.githubusercontent.com/54090625/81836617-f0c1e900-9500-11ea-9148-bbdf84165a03.png)

As you can see in the image, Col A is colliding with Col B and they BOTH become fixed. 

I have also tried setting width using:
```
cellStyle: {
   minWidth: '400px'
}
```
However this seems to be ignored ONLY if I am using fixed columns. 

**Environment**
 - OS: macOS Catalina
 - Browser Chrome
 - Version 81

**Comment by thefat32** [comment]
Same here!

**Comment by radhey-sahaj** [comment]
Am running into the same issue, did you find any fix?

**Comment by kvskranthikumar** [comment]
This is a bug, can't get moved to stale state
