### ISSUE TITLE
Typescript columns error

### ISSUE THREAD

**Issue by raph90** [mbrn/material-table#1915]
I am creating a CustomColumn interface definition like this:
`export interface CustomColumn<T extends object> extends Column<T> {
  width?: string;
}`

and then using a hook to generate columns:
`export const useOverviewColumns = (): CustomColumn<OverviewTableData>[] => { ...etc`

OverviewTableData defines my data. 
I also have some CSS styles that I'm using in the columns: 

` const generalCellStyles: React.CSSProperties = {
    fontSize: "1.4rem",
    color: theme.palette.grey[300],
  };

  const alignCenter: React.CSSProperties = {
    textAlign: "center",
  };
`

and I use these like this:
`{
      title: "Internal Fund Name",
      field: "internalFundName",
      cellStyle: {
        ...generalCellStyles,
      },
      width: "11%",
    },
`

However, when I go to use the columns, Typescript throws this error: 

>  Type 'CSSProperties | ((data: OverviewTableData[], rowData: OverviewTableData) => CSSProperties) | undefined' is not assignable to type 'CSSProperties | ((data: object[], rowData: object) => CSSProperties) | undefined'.
>         Type '(data: OverviewTableData[], rowData: OverviewTableData) => CSSProperties' is not assignable to type 'CSSProperties | ((data: object[], rowData: object) => CSSProperties) | undefined'.
>           Type '(data: OverviewTableData[], rowData: OverviewTableData) => CSSProperties' is not assignable to type '(data: object[], rowData: object) => CSSProperties'.
>             Types of parameters 'data' and 'data' are incompatible.
>               Type 'object[]' is not assignable to type 'OverviewTableData[]'.

I am clearly specifying that my CustomColumn extends object, so I don't see what the issue is. It would be great if someone could help.

**Comment by raph90** [comment]
To anyone else having trouble with this, React.memo was the cause, it was messing up a generic declaration

**Comment by slhck** [comment]
I'm getting a similar error. I want to define a custom table that takes in the same props as the `MaterialTable`:

```
export interface CustomTableProps<T extends object> extends MaterialTableProps<T> {}
```

And I want it to take all kinds of row data.

So I instantiate it like this:

```
export interface RecentMeasurementsTableProps extends Omit<CustomTableProps<StatisticReport>, 'data' | 'columns'> {}
```

And define my columns as such:

```
const columns: Column<StatisticReport>[] = [];
```

And when I use `<CustomTable columns={columns}>`, I get:

```
Type 'Column<StatisticReport>[]' is not assignable to type 'Column<object>[]'.
  Type 'Column<StatisticReport>' is not assignable to type 'Column<object>'.
    Types of property 'cellStyle' are incompatible.
      Type 'CSSProperties | ((data: StatisticReport[], rowData: StatisticReport) => CSSProperties) | undefined' is not assignable to type 'CSSProperties | ((data: object[], rowData: object) => CSSProperties) | undefined'.
        Type '(data: StatisticReport[], rowData: StatisticReport) => CSSProperties' is not assignable to type 'CSSProperties | ((data: object[], rowData: object) => CSSProperties) | undefined'.
          Type '(data: StatisticReport[], rowData: StatisticReport) => CSSProperties' is not assignable to type '(data: object[], rowData: object) => CSSProperties'.
            Types of parameters 'data' and 'data' are incompatible.
              Type 'object[]' is not assignable to type 'StatisticReport[]'.
                Type 'object' is not assignable to type 'StatisticReport'.ts(2322)
index.d.ts(7, 3): The expected type comes from property 'columns' which is declared here on type 'IntrinsicAttributes & CustomTableProps<object> & { children?: ReactNode; }'
```

Any idea?

**Comment by raph90** [comment]
@slhck How are you actually using your custom component? What worked for me was I made a component called CustomTable and then called 
`<CustomTable<MyDataObjectInterface> {...props} />`

**Comment by raph90** [comment]
Post your code if you want me to have a look because I solved this exact problem on Friday

**Comment by slhck** [comment]
I have a custom table:

```
export interface CustomTableProps<T extends object> extends MaterialTableProps<T> {
}

const CustomTable: React.FC<CustomTableProps<object>> = (
  props: CustomTableProps<object> = {
    data: [],
    columns: [],
  },
): JSX.Element => {
  return (
    <MaterialTable
      options={{
        filtering: false,
        search: false,
        toolbar: false,
      }}
      {...props}
    />
  );
};

export default CustomTable;
```

And when I want to use it:

```
export interface RecentMeasurementsTableProps extends Omit<CustomTableProps<StatisticReport>, 'data' | 'columns'> {
  extended?: boolean;
}

const RecentMeasurementsTable: React.FC<RecentMeasurementsTableProps> = (
  props: RecentMeasurementsTableProps = { extended: false },
): JSX.Element => {
  const columns: Column<StatisticReport>[] = [
    // ...
  ];

  const data = [
    // ...
  ]

  if (props.extended) {
    // other stuff
  }

  return <CustomTable columns={columns} data={data} />;
};
```

I notice that I did not actually use generics for creating `<CustomTable>` ...

**Comment by slhck** [comment]
I think I got it. Define the custom table as generic (see [this](https://stackoverflow.com/a/51463284)):

```typescript
export interface CustomTableProps<T extends object> extends MaterialTableProps<T> {}

const CustomTable: <T extends object>(props: CustomTableProps<T>) => JSX.Element = (
  props = {
    options: {
      filtering: false,
      search: false,
      toolbar: false,
    },
    data: [],
    columns: [],
  },
) => {
  return (
    <MaterialTable
      options={{
        filtering: false,
        search: false,
        toolbar: false,
      }}
      {...props}
    />
  );
};

export default CustomTable;
```

Then instantiate it like this:

```
import CustomTable, { CustomTableProps } from './CustomTable';

export interface RecentMeasurementsTableProps extends Omit<CustomTableProps<StatisticReport>, 'data' | 'columns'> {
  extended?: boolean;
}

const RecentMeasurementsTable: React.FC<RecentMeasurementsTableProps> = (
  props: RecentMeasurementsTableProps = { extended: false },
): JSX.Element => {

  const columns: Column<StatisticReport>[] = [
    // whatever definition
  ];

  const data: Array<StatisticReport> = [
    // set the data
  ]

  if (props.extended) {
    // other stuff
  }

  return <CustomTable<StatisticReport> columns={columns} data={data} />;
};

export default RecentMeasurementsTable;
```

**Comment by raph90** [comment]
That's it, glad you solved.

**Comment by slhck** [comment]
Perhaps you want to close this issue if you solved it?

**Comment by oze4** [comment]
Closing this issue out. Please reopen if needed.
