### ISSUE TITLE
Provide a custom exportRender function for each column

### ISSUE THREAD

**Issue by thefat32** [mbrn/material-table#1916]
**Is your feature request related to a problem? Please describe.**
We are using material-table to export csv files. But when any column or column's title has a custom render that returns a React.Node (ex i18n Translate component) it get exported as [object Object].

**Describe the solution you'd like**
It would be usefull to have the option to provide a custom render function (row: RowData): string and (title: ReactNode): string for each column and column's title. And those functions used when provided to render csv data.

**Describe alternatives you've considered**

**Additional context**

**Comment by oze4** [comment]
How are you setting the title? Are you using a function within the title (on the columns prop) like [here](https://material-table.com/#/docs/features/custom-column-rendering) or something else?

**Comment by thefat32** [comment]
Hi there I'm setting columns like this

```tsx
import MaterialTable, { MTableToolbar } from 'material-table';

<MaterialTable
    // other props
    columns={[
      {
        field: 'someField',
        title: <Translate value="translationkey" />,
        render: rowData => <Translate value={rowData.translationKey} />
      }
    ]}
/>
```

Translate component from react-i18n. So my columns are all text based but when exporting csv I have problems with columns titles and translated columns.

**Comment by oze4** [comment]
@thefat32 it looks like you're going to have to add your own export logic to resolve this..

In the example below, the component I am using as the `title` contains a prop called `text`, which stores the text based representation of what is rendered on screen.  I am not familiar with the `Translate` component you are using, so I am not sure of the props it contains, but I assume you can drill into the object and grab the text based representation.

A live demo of the code below [can be found here](https://stackblitz.com/edit/react-puxti1?embed=1&file=index.js).

```javascript
import React, { useRef } from 'react';
import { render } from 'react-dom';
import MaterialTable from "material-table";

import tableIcons from "./TableIcons.js";
import MyComponent from "./MyComponent.js";

const rando = seed => Math.floor(Math.random() * seed);
const data = ["Rock", "Paper", "Scissors"].map(e => ({ id: rando(300 + e.length), name: e }));

const downloadCsv = (data, fileName) => {
  const finalFileName = fileName.endsWith(".csv") ? fileName : `${fileName}.csv`;
  const a = document.createElement("a");
  a.href = URL.createObjectURL(new Blob([data], { type: "text/csv" }));
  a.setAttribute("download", finalFileName);
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
}

const App = () => {
  const tableRef = useRef();

  return (
    <div>
      <MaterialTable
        tableRef={tableRef}
        data={data}
        icons={tableIcons}
        columns={[
          {
            field: "id",
            title: <MyComponent text="Id" />,
            render: rowData => <MyComponent text={rowData.name} />
          },
          {
            field: "name",
            title: <MyComponent text="Name" />,
            render: rowData => <MyComponent text={rowData.name} />
          }
        ]}
        options={{
          exportButton: true,
          exportCsv: (columns, data) => {
            // Turn headers into array of strings
            const headerRow = columns.map(col => {
              if (typeof col.title === 'object') {
                // I am not sure what props the Translate component exposes
                // but you would need to change `text` in `col.title.props.text`
                // to whatever prop you need.
                return col.title.props.title;
              }
              return col.title;
            });

            // Turn data into array of strings
            const dataRows = data.map(item => {
              const _item = { ...item }; // Make a copy of our item before modifying it
              delete _item.tableData; // Leave us with only the data we want
              return Object.keys(_item).map(key => item[key]);
            });

            // Aggregate header data and 'body' data
            const csvContent = [headerRow, ...dataRows].map(e => e.join(",")).join("\n");

            // This mirrors the default export behavior where the 
            // exported file name is the table title.
            const csvFileName = tableRef.current.props.title;

            // Allow user to download file as .csv
            downloadCsv(csvContent, csvFileName);
          }
        }}
      />
    </div>
  );
}
```

**Comment by thefat32** [comment]
Great example! Thanks!

**Comment by oze4** [comment]
@thefat32 no problem, glad to help!  If this resolved the problem you were having, would you mind closing this issue out?

**Comment by thefat32** [comment]
I still think it would be nice to have a pair of functions in the column definition, so they can be used in the default exportCsv funtion. This way there is no need for the user to understand the csv generation process. My proposal is something like this:

```ts
interface Column<RowData extends object> {
...otherProps
titleAsText?: () => string;
getValueAsText?: (data: RowData) => string
}
```
And in default exportCsv function

```ts
  defaultExportCsv = () => {
    const columns = this.props.columns
      .filter(columnDef => {
        return !columnDef.hidden && columnDef.field && columnDef.export !== false;
      })
      .sort((a, b) => (a.tableData.columnOrder > b.tableData.columnOrder) ? 1 : -1);
    const dataToExport = this.props.exportAllData ? this.props.data : this.props.renderData;
    const data = dataToExport.map(rowData =>
      columns.map(columnDef => {
        //return this.props.getFieldValue(rowData, columnDef);
        return columnDef.getValueAsText ? columnDef.getValueAsText() : this.props.getFieldValue(rowData, columnDef);
      })
    );

    const builder = new CsvBuilder((this.props.exportFileName || this.props.title || 'data') + '.csv');
    builder
      .setDelimeter(this.props.exportDelimiter)
      //.setColumns(columns.map(columnDef => columnDef.title))
      .setColumns(columns.map(columnDef => columnDef.titleAsText ? columnDef.titleAsText() columnDef.title))
      .addRows(data)
      .exportFile();
  }
```

What do you think about it?

**Comment by thefat32** [comment]
If you think this approach could make it through I will make a PR

**Comment by oze4** [comment]
@thefat32 unfortunately, I do not have access to approve/merge PRs, and those that do have those permissions are not exactly responsive. 

I went ahead and created a fork of this repo that will be maintained. It will always be 100% compatible with material-table and I do not plan on making dramatic changes to the code base. Ultimately, my goal is to knock out issues and PRs - if material table ever wants me to send them a PR with anything I update I'd be happy to do so. [You can read more here](https://github.com/oze4/material-table-core/blob/master/README.md)..

**My point is if you wanted to fork that repo and send a PR to it, I would gladly accept it.**

**Comment by thefat32** [comment]
Well I'd gladly present the PR in the two repos when I got the time

**Comment by oze4** [comment]
No worries.. what I'm getting at is, your PR won't get merged here for like 6 months. They're not very responsive.

**Comment by maurosbu** [comment]
@thefat32 I'd like to propose to use `getValueAsText` also in search context. What do you think?

**Comment by thefat32** [comment]
We've move our dependency to oze4 repo, will create the issue there and post the link here aftwerwards so we can continue the discussion there

**Comment by thefat32** [comment]
We move here https://github.com/mbrn/material-table/issues/1935

**Comment by thefat32** [comment]
We move here https://github.com/oze4/material-table-core/issues/2

**Comment by oze4** [comment]
This has been resolved in [@material-table/core](https://github.com/oze4/material-table-core) - You can use the `titleAsText: () => "Your Text Title"` column property for this. Check out a [code](https://github.com/oze4/material-table-core/blob/master/demo/src/Components/Demos/ExportCsvWhenColumnTitleIsNotText/index.js#L21) example here, as well as a [live demo here](https://oze4.github.io/material-table-core/#/demo/005)

**Comment by oze4** [comment]
See PR for more info

**Comment by thefat32** [comment]
@mbrn Do you think we can bring https://github.com/oze4/material-table-core/pull/3 to material-table?
