### ISSUE TITLE
cellStyle & headerStyle not working 

### ISSUE THREAD

**Issue by saiava** [mbrn/material-table#1919]
I'm trying to set a cellStyle & headerStyle but not working properly. I have a column text size of 1000 characters i want to trim to a fixed size with ellipses. I'm using the below code but it is not resizing.

{ title: element.Title, field: element.InternalName 
cellStyle: {
                height: 20,
                maxHeight: 20
              },
              headerStyle: {
                height:20,
                maxHeight: 20,
                verticalAlign: 'top'
              }
}
Any help please.

Thank you
Saiava

**Comment by oze4** [comment]
I would need to see some of your code as this is not something I can reproduce. I'd be willing to bet you're overriding styles somewhere else, though.

```javascript
import React, { useState } from "react";
import { render } from "react-dom";
import MaterialTable from "material-table";
import tableIcons from "./TableIcons.js";

const rando = max => Math.floor(Math.random() * max);
const words = ["Paper", "Rock", "Scissors"];
const rawData = [];

for (let i = 0; i < 100; i++) rawData.push({ id: rando(300), name: words[i % words.length] });

const columns = [
  { 
    title: "Id", 
    field: "id" 
  },
  { 
    title: "Name", 
    field: "name", 
    cellStyle: { 
      backgroundColor: '#039be5', 
      color: '#FFF',
      height: 200,
      maxHeight: 200
    } 
  },
];

const App = () => {
  const [data, setData] = useState(rawData);

  return (
    <MaterialTable
      data={data}
      columns={columns}
      options={{
        headerStyle: {
          backgroundColor: '#01579b',
          color: '#FFF',
        }
      }}
      icons={tableIcons}
    />
  );
};

render(<App />, document.querySelector("#root"));
```

**Comment by saiava** [comment]
This is not working. I've set the title to arount 200 char length & set maxheight to 5 but it is not setting to 5. My scenario is to set the height of header and cells to 5px with ellipses (...) appended.

import React, { useState } from "react";
import { render } from "react-dom";
import MaterialTable, { MTableBodyRow } from "material-table";
import tableIcons from "./TableIcons.js";

const rando = max => Math.floor(Math.random() * max);
const words = ["Paper", "Rock", "Scissors"];
const rawData = [];

for (let i = 0; i < 100; i++) rawData.push({ id: rando(300), name: words[i % words.length] });

const columns = [
  { 
    title: "Id", 
    field: "id" 
  },
  { 
    title: "NamedashfasdhfsdjhfsKDFKSDFKsdfksDFKDBFKHSDFHSDFKSDFKSDFKSDHIUsefdfiygiefgydgfiygfiygfygdfybdygeiyeg", 
    field: "name", 
    cellStyle: { 
      backgroundColor: '#039be5', 
      color: '#FFF',
      height: 20,
      maxHeight: 20,
      width:10,
      maxWidth:10
    } 
  },
];

const App = () => {
  const [data, setData] = useState(rawData);

  return (
    <MaterialTable
      data={data}
      columns={columns}
      options={{
        headerStyle: {
          height:5,
          maxHeight:5,
          minHeight:5,
          width:10,
          maxWidth:10,
          backgroundColor: '#01579b',
          color: '#FFF',
        }
      }}
      icons={tableIcons}
    />
  );
};

render(<App />, document.querySelector("#root"));

**Comment by oze4** [comment]
But it is working... you even changed the header color and watched it change..  The settings you're using aren't working because some of them conflict with existing styles (or parent styles).

To resolve this [you'll need to override the header](https://material-table.com/#/docs/features/component-overriding) component, which will give you free reign of styling.

**Comment by oze4** [comment]
Actually, this is working.  This is a css "issue" (it's just how css works, really) not a material-table issue.

[See updated demo](https://stackblitz.com/edit/react-f2ycnq?embed=1&file=index.js)

If you want to use text overflow in css you have to set a width...

```javascript
headerStyle: {
  maxWidth: 20, // <--- ADD THIS AND IT WILL WORK
  height: 10,
  maxHeight: 10,
  backgroundColor: "#039be5",
  color: "#FFF",
  textOverflow: "ellipsis",
  overflow: "hidden"
}
```
