### ISSUE TITLE
Remote data with no total count

### ISSUE THREAD

**Issue by alexanderkho** [mbrn/material-table#1920]
If I am fetching my data from an API that is not currently configured to return the total results count (pagination is achieved using results per page + offset), is it still possible to use the remote data feature of material table?

**Comment by oze4** [comment]
Yes, this is possible. Material table was built to handle scenarios such as these. See the [fetching remote data examples from the docs](https://material-table.com/#/docs/features/remote-data) for some good info.

**Comment by alexanderkho** [comment]
Hi @oze4 thanks for your reply. I'm asking if it is possible to do remote fetching when the API is not configured to return the total results count, e.g. something like this:

```
<MaterialTable
    // other props
    data={query =>
        new Promise((resolve, reject) => {
            // some API call 
            resolve({
                data: [data array]
                page: [current page]
                //API does not give us a results count count so totalCount is left blank
            });
        })
    }
/>;
```

Currently the above code is throwing a prop types error saying that totalCount is required. I'm asking if there is any workaround for this or if remote data only works with API's that return total count.

**Comment by oze4** [comment]
How do you expect Material Table to paginate when the total number of rows is unknown. 

No this is not possible with any table.

**Comment by alexanderkho** [comment]
Since pagination is handled externally by my API I was hoping I could adapt material table to my use case, even if the total number of results is unknown. Sounds like this is definitely not possible though. I'll go ahead and mark this as closed.

**Comment by oze4** [comment]
@alexanderkho 

It looks like you can leave `totalCount` empty and it should work.  I also added custom localization so that you can at least set the current page.  Without setting the current page it's hard to keep track of where you're at when paging.

It's tricky making this work without knowing the total number of items that could potentially be displayed in the table - if you don't even know how many total items there are, how can you expect material-table to know how many items there are?

[You can check out a live demo here](https://stackblitz.com/edit/react-7qa2ng?embed=1&file=index.js) that shows how you can accomplish this.

```javascript
import React, { useState } from "react";
import { render } from "react-dom";
import MaterialTable from "material-table";
import tableIcons from "./TableIcons.js";

const columns = [
  { title: "To-Do Id", field: "id" },
  { title: "User Id", field: "userId" },
  { title: "Title", field: "title" },
  { title: "Completed", field: "completed", type: "boolean" }
];

const options = {
  pageSize: 100,
  maxBodyHeight: 400,
}

const App = () => {
  const [currentPage, setCurrentPage] = useState(1);

  const localization = {
    pagination: { 
      labelDisplayedRows: `Page: ${currentPage}`
    }
  }

  const handleChangePage = (page) => {
    setCurrentPage(page + 1);
  }

  const handleRemoteData = query =>
    new Promise((resolve, reject) => {
      const url = `https://jsonplaceholder.typicode.com/todos?_page=${query.page+1}&_limit=${query.pageSize}`;
      fetch(url)
        .then(response => response.json())
        .then(result => {
          resolve({
            data: result,
            page: query.page, 
            //totalCount: result.total  // <-- You can just leave this off
          });
        });
    });

  return (
    <MaterialTable
      data={handleRemoteData}
      columns={columns}
      localization={localization}
      options={options}
      onChangePage={handleChangePage}
      icons={tableIcons}
    />
  );
}

render(<App />, document.querySelector("#root"));
```
