### ISSUE TITLE
Is it possible for a row in tree data editable ?

### ISSUE THREAD

**Issue by thanhdinh98** [mbrn/material-table#1922]
Firstly, thank you for this awesome datatable project you have made. I'm currently using this one in my project. It seems tree data currently just for displaying data. Is there any option for making a sub-row in tree data editable? If it has not done yet, is features like this one will be added in the future? 
Thank you in advance.

**Comment by oze4** [comment]
I would need to see some of your code, or if you could provide a demo of the issue you are having, that would be even better... this is already the default behavior of material-table.

[Please see a live demo here that shows how you can edit a "sub-row"]()

```javascript
// Code from demo
import React, { useState } from "react";
import { render } from "react-dom";
import MaterialTable, { MTableBodyRow } from "material-table";
import tableIcons from "./TableIcons.js";

const App = () => {
  return (
    <MaterialTable
      icons={tableIcons}
      data={
        /* DATA REMOVED HERE FOR BREVITY */
        /* SEE THE LIVE DEMO TO VIEW ALL OF THE CODE */
      }
      columns={
        /* COLUMNS REMOVED HERE FOR BREVITY */
        /* SEE THE LIVE DEMO TO VIEW ALL OF THE CODE */
      }
      parentChildData={(row, rows) => rows.find(a => a.id === row.parentId)}
      editable={{
        onRowUpdate: (newData, oldData) => new Promise(r => setTimeout(r, 1000)),
      }}
    />
  );
};

render(<App />, document.querySelector("#root"));
```

**Comment by thanhdinh98** [comment]
Thank you @oze4. I think I haven't given the question clearly yet. Let's me make some edit. 
I can make the table editable with the same configs as you just gave. On onRowAdd, the table is just giving me add row to the parent's view. Something likes this 
![image](https://user-images.githubusercontent.com/25563537/82139199-6fe05580-9850-11ea-81ed-727ea91ad09f.png)
For my need, I'd like to add a new row to the children's view with the default configs material-table has. For now, I've created my own editable table for my children's view with 3 action buttons and a modal for form's input.
And my code is something likes this
`<MaterialTable
          title="Tạo/Chỉnh sửa danh mục"
          columns={[
            { title: '', field: 'name' },
          ]}
          data={categories}
          options={{
            search: false,
            paging: false,
            sorting: false,
            header: false,
            selection: false,
            selectionProps: (rowData) => ({
              disabled: rowData.haveChildren,
              color: 'primary',
            }),
            actionsColumnIndex: -1,
          }}
          parentChildData={(row, rows) => rows.find((a) => {
            if (a.id === row.parent_id) {
              a.haveChildren = true;
              return true;
            }
            return false;
          })}
          actions={[
            {
              icon: () => <PlusCircle color="blue" />,
              tooltip: 'Thêm danh mục',
              isFreeAction: true,
              onClick: (event) => setOpenForm(true),
            },
            (rowData) => ({
              icon: () => <PlusSquare color={rowData.parent_id ? 'gray' : 'blue'} />,
              tooltip: 'Thêm danh mục con',
              onClick: (event, data) => {
                setOpenForm(true);
                setParent({ name: data.name, id: data.id });
              },
              disabled: !!rowData.parent_id,
            }),
            (rowData) => ({
              icon: () => <Delete color={rowData.haveChildren ? 'gray' : 'red'} />,
              tooltip: 'Xóa danh mục',
              onClick: (event, data) => {
                DeleteProductCategory(data.id)
                  .then((res) => {
                    history.push('/empty');
                    history.goBack();
                  })
                  .catch((err) => console.error(err));
              },
              disabled: rowData.haveChildren,
            }),
          ]}
        />`
