### ISSUE TITLE
Table Style corrupted when trying to use pagination and delete is not fulfilled 

### ISSUE THREAD

**Issue by SooSoo-El-Shreer** [mbrn/material-table#1923]
**Describe the bug**
In the Material-Table (1.54.1) if you click on the built in row delete functionality but you don't confirm with yes or no. Instead you go to click on either previous or next then the table will display in a weird style. My table has server side pagination and uses the built in row delete functionality:
`                        editable={{
                          onRowDelete: oldData =>
                            new Promise((resolve, reject) => {
                              setTimeout(() => {
                                {
                                  let data = this.state.rows
                                  const index = data.indexOf(oldData)
                                  data.splice(index, 1)
                                  this.setState({ data }, () => resolve())
                                  this.deleteRow(oldData.id)
                                }
                                resolve()
                              }, 1000)
                            }),
                        }}`
**To Reproduce**
1- Create a table with server side pagination (I am not sure if on client side pagination the same problem exists). 
2- go to second page of the table
3- click on delete icon of the row
4- don't click on yes or no, just click on previous page or next page
5- the table now appears lighter and the row delete buttons can't be clicked

**Expected behavior**
I expect the table to go back to its normal state when I click next or previous

**Screenshots**
![Material Table issue 0of2](https://user-images.githubusercontent.com/42125554/82154012-be531b80-9873-11ea-82f0-8de397a37b0f.png)
![Material Table issue 1of2](https://user-images.githubusercontent.com/42125554/82154014-c27f3900-9873-11ea-8566-4624c5da2cf2.png)
![Material Table issue 2of2](https://user-images.githubusercontent.com/42125554/82154015-c57a2980-9873-11ea-9508-f6c0e54f861d.png)

**Desktop (please complete the following information):**
 - OS: Windos
 - Browser chrome
 - Version 1.54.1

**Additional context**
I can fix this issue if someone can tell me how I can access the onClick of the delete icon. In other words what i want to do is the following:
on click of the Delete Icon I want to disable the pagination (setState({paginationBoolean: false}))
then in the 
`onRowDelete: oldData =>
                            new Promise((resolve, reject) => {
                              setTimeout(() => {
                                {
                                 this.setState({ paginationBoolean: true })
                                }
                                resolve()
                              }, 1000)
                            })`

**Comment by SooSoo-El-Shreer** [comment]
I would like to say that I was checking if this also happens if I try the inline update. It also has the same issue. So this problem is not restricted to delete

**Comment by oze4** [comment]
Is this still an issue in the latest version?
