### ISSUE TITLE
Error : Object Doesn't support property or method 'findIndex' in IE11

### ISSUE THREAD

**Issue by saiava** [mbrn/material-table#1924]
Hi,

I'm getting the below error in IE11 when i use Material-Table in SharePoint Framework along with React. Below is my Code:

import * as React from 'react';
import "@pnp/polyfill-ie11";
//import 'core-js';
//import "regenerator-runtime/runtime.js";
//import 'core-js/es6';
//import 'core-js/es7/reflect';
//import "@babel/polyfill";
//import 'core-js';
import styles from './SpTableData.module.scss';
import { ISpTableDataProps } from './ISpTableDataProps';
import { ISpTableState } from './../stateprops';
import { escape } from '@microsoft/sp-lodash-subset';
import { sp, Web, IField, IFieldInfo, IViewInfo } from "@pnp/sp/presets/all";
let spWeb = null;
export default class SpTableData extends React.Component<ISpTableDataProps, ISpTableState> {
  public constructor(props: any) {
    super(props);
    sp.setup({
      ie11: true,
      spfxContext: this.context
    });
    this.state = {
      Tools: [],
      Fields: [],
      spListViewInfo:null
    }
    this.getListItems = this.getListItems.bind(this);
    this.getViewQuery = this.getViewQuery.bind(this);
    this.getData = this.getData.bind(this);
    spWeb = Web(this.props.spContext.pageContext.web.absoluteUrl);
    //spWeb = Web(sp.web.toUrl())
  }
  public componentWillMount() {
    let context = this;
    this.getViewQuery(this.props).then(
      function (query) {
        context.getData(context);
      }
    )
  }
  public componentWillReceiveProps(props) {
    var context = this;
    this.getViewQuery(props).then(function (query) {
      context.getData(context);
    });
  }

  public getData(context) {
    context.getListItems(context.props).then(function (spitems) {
      let items = [];
      spitems.forEach(element => {
        let row = {};
        //debugger;
        context.state.Fields.map((field: IFieldInfo) => {
          if (field.TypeAsString === "Lookup") {
            row[field.InternalName] = element[field.InternalName].Title;
          }
          else {
            row[field.InternalName] = element[field.InternalName]
          }
        });
        items.push(row);
      });
      console.log("thisssssssss",items);
      context.setState(
        {
          Tools: items
        })
    })
  }

  public async getListItems(props: any) {
    let strFields: string[] = []; //this.state.Fields;
    let expandCols: string[] = [];
    /*this.state.Fields.map(elm => {
      if (elm === "Country") {
        strFields.push(elm + "/Title");
        expandCols.push(elm);
      }
      else {
        strFields.push(elm);
      }
    })*/
    this.state.Fields.map((elm: IFieldInfo) => {
      if (elm.TypeAsString === "Lookup") {
        strFields.push(elm.InternalName + "/Title");
        expandCols.push(elm.InternalName);
      }
      else {
        strFields.push(elm.InternalName);
      }
    })
    let result = await spWeb.lists.getById(props.list).items.select(...strFields).expand(...expandCols).get();
    console.log("data resultttttttttttt", result)
    return result;
  }
  public async getFieldsInfo(fieldColl: string[], props: any) {
    let fieldInfoColl: IFieldInfo[] = await Promise.all(fieldColl.map(async (currfield) => {
      let currfieldInfo: IFieldInfo = await spWeb.lists.getById(props.list).fields.getByInternalNameOrTitle(currfield)();
      console.log("current field infoooooo", currfieldInfo);
      return currfieldInfo;
    }));
    return fieldInfoColl;
  }
  public async getViewQuery(props: any) {
    //sp.web.lists.getById("").views.getById("");
    let spViewInfo = await spWeb.lists.getById(props.list).views.getById(props.listview).get();
    let result = await spWeb.lists.getById(props.list).views
      .getById(props.listview).fields.get();
    let lstFieldsWithInfo: IFieldInfo[] = null;
    await Promise.resolve(this.getFieldsInfo(result.Items, props)).then(function (response: IFieldInfo[]) {
      console.log("responseeeeee", response);
      lstFieldsWithInfo = response
    });
    console.log("##################", result);
    this.setState(
      {
        Fields: lstFieldsWithInfo, spListViewInfo:spViewInfo
      })
    return result;
  }
  public render(): React.ReactElement<ISpTableDataProps> {
    if (this.state.Tools.length > 0) {
      let columns = [];

      return (
        <div style={{ maxWidth: "100%" }}>
             <MaterialTable
            columns={
              this.state.Fields.map((element: any) => {
                switch (element.TypeAsString) {
                  case "Note":
                    return (
                      {
                        title: element.Title, field: element.InternalName,
                        render: props =>
                          <div dangerouslySetInnerHTML={{ __html: props[element.InternalName] }}></div>
                      }
                    )
                  case "Choice":
                    let objVal = {};
                    element.Choices.map((elm) => {
                      objVal[elm] = elm
                    })
                    return ({ title: element.Title, field: element.InternalName, lookup: { ...objVal } })
                  default:
                    return (
                      { title: element.Title, field: element.InternalName }
                    )
                }
              })
            }
            data={this.state.Tools}
            title={this.state.spListViewInfo.Title}
            style={{height: "50", width: "10"}}
            options={{
              filtering: true             
            }}
          />
        </div>
      );
    }
    else
      return (
        <div>No Data</div>
      )
  }
}

"TypeError: Object doesn't support property or method 'findIndex'
   at setDataManagerFields (https://localhost:4321/dist/sp-table-data-web-part.js:87937:5)
   at MaterialTable (https://localhost:4321/dist/sp-table-data-web-part.js:87884:1)
   at ul (https://spoprod-a.akamaihd.net/files/sp-client/sp-webpart-workbench-assembly_en-us_78bb8d9cee2a1258615d5c8689e23963.js:1:1251803)
   at ki (https://spoprod-a.akamaihd.net/files/sp-client/sp-webpart-workbench-assembly_en-us_78bb8d9cee2a1258615d5c8689e23963.js:1:1266577)
   at Anonymous function (https://spoprod-a.akamaihd.net/files/sp-client/sp-webpart-workbench-assembly_en-us_78bb8d9cee2a1258615d5c8689e23963.js:1:1295343)
   at Ua (https://spoprod-a.akamaihd.net/files/sp-client/sp-webpart-workbench-assembly_en-us_78bb8d9cee2a1258615d5c8689e23963.js:1:1293404)
   at Ia (https://spoprod-a.akamaihd.net/files/sp-client/sp-webpart-workbench-assembly_en-us_78bb8d9cee2a1258615d5c8689e23963.js:1:1298403)
   at xo (https://spoprod-a.akamaihd.net/files/sp-client/sp-webpart-"

**Comment by oze4** [comment]
You may be able to use a custom polyfill for this..

[Found here](https://stackoverflow.com/a/41938119/10431732)

```javascript
// https://tc39.github.io/ecma262/#sec-array.prototype.findIndex
if (!Array.prototype.findIndex) {
  Object.defineProperty(Array.prototype, 'findIndex', {
    value: function(predicate) {
     // 1. Let O be ? ToObject(this value).
      if (this == null) {
        throw new TypeError('"this" is null or not defined');
      }

      var o = Object(this);

      // 2. Let len be ? ToLength(? Get(O, "length")).
      var len = o.length >>> 0;

      // 3. If IsCallable(predicate) is false, throw a TypeError exception.
      if (typeof predicate !== 'function') {
        throw new TypeError('predicate must be a function');
      }

      // 4. If thisArg was supplied, let T be thisArg; else let T be undefined.
      var thisArg = arguments[1];

      // 5. Let k be 0.
      var k = 0;

      // 6. Repeat, while k < len
      while (k < len) {
        // a. Let Pk be ! ToString(k).
        // b. Let kValue be ? Get(O, Pk).
        // c. Let testResult be ToBoolean(? Call(predicate, T, « kValue, k, O »)).
        // d. If testResult is true, return k.
        var kValue = o[k];
        if (predicate.call(thisArg, kValue, k, o)) {
          return k;
        }
        // e. Increase k by 1.
        k++;
      }

      // 7. Return -1.
      return -1;
    }
  });
}
```

**Comment by saiava** [comment]
can you please help understand to where do we add the above mentioned code?

**Comment by saiava** [comment]
Hi I managed to add the above mentioned code. It is working fine if i remove the 'Filtering' option. I've attached the error that coming if i add filter option. One image is with filter option which is getting error. And other image is without filter which is getting the data correctly. Below is the code that i'm using. 
Note: i'm having data like richtext html format for one of the column data

![With-FilterOption](https://user-images.githubusercontent.com/54665207/82375499-4e44c100-9a3e-11ea-950c-a9c7c2de2ce3.png)
![Without-FilterOption](https://user-images.githubusercontent.com/54665207/82375509-51d84800-9a3e-11ea-9a6f-0e655a4d019b.png)

in Render:
let arrCols =  this.state.Fields.map((element: any) => {
        switch (element.TypeAsString) {
          case "Note":{
            return (
              {
                title: element.Title, field: element.InternalName, tooltip:element.Title,
                render: props =><div className="cellHighlight" onClick={this.setDialogText.bind(this,props[element.InternalName])}><div dangerouslySetInnerHTML={{ __html: props[element.InternalName] }}></div></div>
              }
            )
          }
          case "Choice":
            {
              let objVal = {};
              element.Choices.map((elm) => {
                objVal[elm] = elm
              })
              return ({ title: element.Title, field: element.InternalName,tooltip:element.Title, lookup: { ...objVal } })
            }
          default:
            {
              let objVal = {};
              this.state.Tools.map((elm) => {
                objVal[elm[element.InternalName]] = elm[element.InternalName]
              })
              return ({ title: element.Title, field: element.InternalName,tooltip:element.Title, lookup: { ...objVal }
              })
            }
        }
      })
      return (
        <div style={{ maxWidth: "100%" }}>
           <MaterialTable
            columns={arrCols}
            data={this.state.Tools}
            title={this.state.spListViewInfo.Title}
            options={{
              filtering: true,
            }}
          />
        </div>
      );

**Comment by oze4** [comment]
Looks like you need the correct polyfills for this to work in IE
