### ISSUE TITLE
add custom animation props or css style option for detail Panel in MTableBodyRow

### ISSUE THREAD

**Issue by Arashfiroozabadi** [mbrn/material-table#1925]
`function MTableBodyRow() {`
`var _getPrototypeOf2;`
`var _this;`
`.`
`.`
`.`
`(0, _classCallCheck2["default"])(this, MTableBodyRow);`

`    (0, _defineProperty2["default"])((0, _assertThisInitialized2["default"])(_this), "rotateIconStyle", function (isOpen) {`

# add customstyle prop
`return {
        transform: isOpen ? this.props.customstyle : 'none'
      };`
`}`

### its necessary for RTL components

**Comment by oze4** [comment]
Have you checked out the docs?  Your question is a little sloppy so it's exactly clear what you're asking.

https://material-table.com/#/docs/features/styling
