### ISSUE TITLE
Is it posible to use an async data promise?

### ISSUE THREAD

**Issue by DaanvandeHaar** [mbrn/material-table#1926]
Hey, i've been trying to use the Material-Table in combination with some firebase data. But the table doesn't accept Object promises as valid data. Any idea if this is posible and if how i would implement this.

**Comment by oze4** [comment]
Yes it does... https://material-table.com/#/docs/features/remote-data

**Comment by oze4** [comment]
Testing something.. ignore me..

@material-table/core::resolved
