### ISSUE TITLE
Query parameter in data prop gather filters from other tables

### ISSUE THREAD

**Issue by piekczyk** [mbrn/material-table#1929]
**Describe the bug**
Hey, I have a problem with using multiple tables in the same component (which also is material table). So basically situation looks like this 

I have parent material table with enabled details panels for each record. As a detail panels I'm rendering another material-table (child table so to say) based on reusable component which wraps material table (so column settings, etc. are the same for each record and the only differences are regarding the filters which are passed as prop to child table). Now when I open single detailed panel everything works fine, I get a child table with already applied filters. The problem is when I simultaneously open two or more detail panels. The filters gets mixed up (to be clear - each child table component gets it's own filters so there is no mistake), and by that I mean if I looked into the query.filters parameter in data prop I noticed that this parameter contains a data which is related to another child table component. So basically it looks like logic responsible for gathering all filters from table gathers also filters from simultaneously rendered other tables which has the same configuration in manner of columns etc.

**Expected behavior**
I would like to render few tables based on the same reusable table wrapper component without mixed filters in query parameter.

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser Brave

**Comment by oze4** [comment]
Hi @piekczyk would you mind creating a demo/example of the issue you are having? You can use the CodeSandbox or StackBlitz demo starter templates, which can be [found here](https://github.com/mbrn/material-table/blob/master/.github/ISSUE_TEMPLATE/help.md)
