### ISSUE TITLE
How to change the style of lookup dropdown list in material-table

### ISSUE THREAD

**Issue by marjanatwork** [mbrn/material-table#1936]
Hi,

I am using Material-Table in React application. I have a long list of values in lookup dropdown list. I want to change(reduce) the height of the look up dropdown list in two fields of my table, so that the scroll bar be appear once the user open dropdown list. I am wondering how I can change the styling of these lookup dropdown list. I would appreciate it if you can help me in this regards.

Many thanks

**Comment by oze4** [comment]
What do you mean by 'look up dropdown'?

**Comment by marjanatwork** [comment]
When you create a lookup for a column , it provides you with a dropdown list containing the lookup items.
<img width="165" alt="region" src="https://user-images.githubusercontent.com/48732421/82742588-12974900-9d15-11ea-886d-acd889a3e0b0.png">

**Comment by marjanatwork** [comment]
> What do you mean by 'look up dropdown'?

@oze4
When you create a lookup for a column , it provides you with a dropdown list containing the lookup items.

areas1

Areas

**Comment by marjanatwork** [comment]
Hi,
The other question is that how I can align the content of the cell (data) to the top of the cell for a particular column in Material-Table.  I would appreciate it if you can respond to both questions.

**Comment by Feijo** [comment]
Any news about it?

**Comment by tao101** [comment]
any updates about this i need to change the height of the lookup dropdown

**Comment by hamid842** [comment]
I did this way:
`const customTheme = createTheme({
    overrides: {
        MuiMenu: {
            list: {
                height: 190
            }
        }
    }
})`
so put MaterialTable inside "ThemeProvider".
