### ISSUE TITLE
Is it possible to customize the background color of the group row?

### ISSUE THREAD

**Issue by sarbogast** [mbrn/material-table#1937]
Is it possible to customize the style, and especially the background color of the group row header that appears on top of each group when grouping is enabled to make it more visible?

**Comment by vladvonpr** [comment]
I would also like this.

I need that group header row to be the same color as the rest of the header:
![image](https://user-images.githubusercontent.com/21250316/98448703-6ac7d900-2104-11eb-9cf9-ba1f47fe2536.png)

**Comment by johnjvester** [comment]
I have similar needs as @vladvonpr here ... when the headerStyle is applied and is anything but "white", use of grouping causes the header to look incorrect - exactly as shown in the the Nov 7, 2020 post.  

What is the effort to allow at least styling on the header to inherit the `headerStyle` when grouping is applied?

Also, what is the effort to allow a custom style for each grouped row?  This would be a nice-to-have, to make the list not look so bland with all of the rows in the table having the exact same color (unless I am missing something).
