### ISSUE TITLE
Any way to get Serial Numbers in the data table ?

### ISSUE THREAD

**Issue by Prasad-YS** [mbrn/material-table#194]
In Addition to the data that I'm getting I want show the Serial Number in 1st Column ? Is this possible ?

**Comment by mbrn** [comment]
@Prasad-YS 

You do this with current version. We already have an tableData.id field on every row of data. Just add a new column like this: columns:  { title: '#', field: 'tableData.id' }

**Comment by Prasad-YS** [comment]
> title: '#', field: 'tableData.id'

Sorry, Didn't get any number, just got a blank column

**Comment by Prasad-YS** [comment]
I'm using 6.8.6

**Comment by mbrn** [comment]
Can you share your material-table usage code

**Comment by Mizan-Rifat** [comment]
> Updated to new version, Got the serial number now, Thanks lot for your support

how to do that??

**Comment by SourishMukherjee** [comment]
Is it possible to make the tableData.id start from 1 instead of 0?

**Comment by ahsan-baloch** [comment]
Is it possible to make the tableData.id start from 1 instead of 0??

**Comment by abdulhadi1995** [comment]
@ahsan-baloch just do tableData.id + 1

**Comment by abdulhadi1995** [comment]
@ahsan-baloch 
`  { title: '#', field: 'tableData.id',
                        render:rowData => {
                        console.log(rowData)
                            return(
                                <p>{rowData.tableData.id+1}</p>
                            )
                        }
                    },`

**Comment by ahsan-baloch** [comment]
> @ahsan-baloch
> ` { title: '#', field: 'tableData.id', render:rowData => { return( <p>{rowData.tableData.id+1}</p> ) } }`

but with then when exported to pdf or csv the count shows from 0 not 1

**Comment by ahsan-baloch** [comment]
> @ahsan-baloch just do tableData.id + 1

render: (rowData) => rowData.tableData.id + 1
this worked for me but still when exporting it into csv or pdf count starts from 0 not 1

**Comment by abdulhadi1995** [comment]
@ahsan-baloch you could first customize the data before it begins writing to CSV. you'll have to look around for that unfortunately coz i used another package as I didn't know material table supported exporting to CSV.

**Comment by ahsan-baloch** [comment]
> @ahsan-baloch you could first customize the data before it begins writing to CSV. you'll have to look around for that unfortunately coz i used another package as I didn't know material table supported exporting to CSV.

ahh okay thanks for the help

**Comment by iraxaxaidi** [comment]
> > @ahsan-baloch just do tableData.id + 1
> 
> render: (rowData) => rowData.tableData.id + 1
> this worked for me but still when exporting it into csv or pdf count starts from 0 not 1

this works for me too but it doesn't update with search and sort. Any solution for it?

**Comment by vikram-java** [comment]
columns={[
            { title: '#', field: 'tableData.id', render:rowData => { return( <p>{rowData.tableData.id+1}</p> ) } },            
            { title: 'UserName', field: 'userName' },
            { title: 'Email ID', field: 'userEmail' },
            { title: 'Name', field: 'firstName' },
            { title: 'Mobile No', field: 'userMobileNO' }
          ]}

**Comment by mithash** [comment]
columns = [
        { title: '#, field: 'tableData.id', render:rowData => rowData.tableData.id+1} ,
        { title: 'First Name', field: 'FirstName',  },   
        { title: 'Last Name', field: 'LastName',  }
