### ISSUE TITLE
[v1.58.0] [Breaking] Multiple issues

### ISSUE THREAD

**Issue by matthewkwong2** [mbrn/material-table#1940]
**Describe the bug**
There are multiple issues in `material-table@1.58.0`
1. The following error is prompted if `search` is set to `true`, which is the default setting.
```
Warning: Failed prop type: Invalid prop `color` of value `inherit` supplied to `ForwardRef(TextField)`, expected one of ["primary","secondary"]
```

2. The style of `filled` search field is off.

3. The application will crash if `filter` is set to `true`.

**To Reproduce**
[![Edit material-table-bug](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/material-table-bug-tmdw3?fontsize=14&hidenavigation=1&theme=dark)

**Expected behaviour**
1. The error should not be prompted

2. The style of `filled` search field should look exactly like the one in [Material-UI](https://material-ui.com/components/text-fields/)

3. Setting `filter` to `true` should not crash the application.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge 83.0.478.37
 - Version: 1.58.0

**Workaround**
Downgrade to version `1.57.2`

**Comment by mbrn** [comment]
Hi @matthewkwong2 

Thanks for bug report. 

I solved crash and warning problem (1 & 3). But searchFieldVariant works as expected. Please check again. 

Version 1.58.1 published.
