### ISSUE TITLE
Editable: onEditStart

### ISSUE THREAD

**Issue by saikatstutorial** [mbrn/material-table#1942]
Can we have a **onEditingStart** function of editable to perform something when edit button is clicked?
Criteria:

- Shall work on both Add and Edit

- Shall have mode and data as params

**Comment by oze4** [comment]
Hi @saikatstutorial we can def put this on the list. Keep in mind, we are accepting PRs!

**Comment by deepak-geeky** [comment]
@oze4 For the time being is there any work around to implement this function ?

**Comment by talhahsn** [comment]
any update regarding this?

**Comment by saikatstutorial** [comment]
Reopening this
