### ISSUE TITLE
there's a way to get rowData props passed to the property icon on actions?

### ISSUE THREAD

**Issue by Jhenri-silva** [mbrn/material-table#1944]
In example, I have a button action in the action as a column, but I want this button rendered by the icon that it could receives state, that button has css properties that change due the state receiving in parameter. Or even disabled getting row props too, it would help so much

How could I access rowData inside the component I'm rendering in the icon property of actions?

`            actions={[
                {
                    disabled: (rowData) => {rowData.isDisabled}
                    icon: (iWannaThisPropRowData)=> { return ( <NewUserButton onClick={null} prop = iWannaThisPropRowData.isActive/> )},
                    onClick: (e, rowData) => handleSetAddUser(rowData, setAddUserGroupRowIndex, setOffAddUserGroup)
                },
                ]
            }`

**Comment by DominikEngel** [comment]
You can pass a function as the action and access the rowdata like this:
` rowData => ({
          icon: 'delete',
          tooltip: 'Delete User',
          onClick: (event, rowData) => confirm("You want to delete " + rowData.name),
          disabled: rowData.birthYear < 2000
        })`

**Comment by Jhenri-silva** [comment]
I didn't see the interface index, its able to receive a function that return Action<rowData>. Tks

**Comment by Jhenri-silva** [comment]
I suggest admin to put a props on the function of property icon of interface Action<rowData>

![image](https://user-images.githubusercontent.com/34718184/83277328-45738e00-a1a8-11ea-9fd0-0f6647bb692a.png)
