### ISSUE TITLE
Material-table: datepicker icon in filter column is not displaying

### ISSUE THREAD

**Issue by saiava** [mbrn/material-table#1945]
HI,

I've a table with a text and date type of column. I want to replace the default icon for free text filter column with search icon. and the date column should be the default date picker icon. My problem is i can able to replace the default text field icon with Search icon. But the problem is the Date column is not showing the datepicker icon in the date type of columns. Below is my code.

import Search from "@material-ui/icons/Search";
import DateRange from "@material-ui/icons/DateRange";
<MaterialTable
              //@ts-ignore
              columns={arrCols}
              data={this.state.Tools}
              title={this.state.spListViewInfo.Title}
              //@ts-ignore
              **icons={{ Filter: () => {<Search />}}}**
              options={{
                pageSize: 10,
        pageSizeOptions: [5, 10, 20, 30 ,50, 75, 100 ],
                filtering: !isIE ? true : false,
                headerStyle: { backgroundColor: '#034193', color: currentTheme.semanticColors.primaryButtonText }
              }}
            />
![image](https://user-images.githubusercontent.com/54665207/82881977-094ced00-9f5e-11ea-8a72-ad59f646c9a1.png)

Thank you
S

**Comment by usahai** [comment]
Hey, I'm fiddling around with some of this stuff as well, so I thought I'd share how I got it working
```
actions={[
  {
    icon: tableIcons.AddCircle,
    tooltip: "New Tape Request",
    isFreeAction: true,
    onClick: () => this.props.history.replace("/addTapeRequest")
  }
]}
```  
And I had exported the tableIcons from the other file:
```
export const tableIcons = {
    Add: forwardRef((props, ref) => <AddBox {...props} ref={ref} />),
    AddCircle: forwardRef((props, ref) => <AddCircle {...props} ref={ref} style={{ fill: iconColor }} />),
    {...rest}
}

```

**Comment by mukesh-pathak-by** [comment]
Hi,

I am getting similar issue. 

Datepicker icon in filter column is not displaying.

Is there any way to solve this. Thanks in advance
<img width="772" alt="datepicker" src="https://user-images.githubusercontent.com/62742570/88034263-118c6780-cb5e-11ea-937a-682357069f5b.PNG">

Regards,
Mukesh
