### ISSUE TITLE
Add a possibility to show a button to reset all filters at once in the filter bar

### ISSUE THREAD

**Issue by sarbogast** [mbrn/material-table#1946]
**Is your feature request related to a problem? Please describe.**
I have filters set on several columns, including some columns with a big lookup table, so with options potentially selected all across the list, and no button to reset those filters individually.

**Describe the solution you'd like**
At the very least a button to clear individual filters with a lookup, the same way we can already reset a simple text filter for example.
But ideally also the possibility to show a button at the and of the filter bar that clears all filters at once.

**Describe alternatives you've considered**
There are a couple of ugly workarounds described [there](https://github.com/mbrn/material-table/issues/1132) but they depend on the internal API of the component.

**Additional context**
![Capture d'écran 2020-05-26 23 26 40](https://user-images.githubusercontent.com/143758/82895501-6a011780-9fa8-11ea-9610-5fdb97670611.png)

**Comment by Domino987** [comment]
Seems like a good idea. Do you mind doing the individual delete lookup button as a PR?
