### ISSUE TITLE
Override loadingType

### ISSUE THREAD

**Issue by maitedev** [mbrn/material-table#1947]
Hello! I wanted to know if by any chance I could stop showing
Loading animation. I would like to use my own animation, general for my application, not just for tables. I tried leaving the loadingType option: "", but it is an error on my part.
Thanks in advance. :)

**Comment by Domino987** [comment]
Can you elaborate on what you are doing? Why do you have a loading spinner in the first place? It only appears if you set is loading or use the asnyc data functionally.

**Comment by maitedev** [comment]
Hi Domino, thanks for answering. In the app, I am using a load mask component, which will remain active until a response is received from the server. This load mask is activated on all asynchronous requests made in the application. The table material has its own load and since I am using the remote data function I am showing two load masks, mine and the table. The application can continue working that way, it is not a problem, but I would like to use only a general loading mask for the entire application and for this I should disable (if possible) the one that has Material-Table implemented.
Thanks in advance!
