### ISSUE TITLE
How to make all rows inline editable

### ISSUE THREAD

**Issue by reckinam** [mbrn/material-table#1948]
I was looking for the solution by default to show all rows editable instead of clicking edit and save.is there any option to do? .Thanks in advance

**Comment by ifndefdeadmau5** [comment]
Unfortunately not that I know of..

**Comment by Domino987** [comment]
Yes that is not supported. What you could do is override the render prop of the columns to be a textfield and handle the update yourself onChange

**Comment by TCM5** [comment]
+1 for this ideia!

**Comment by idarshan181** [comment]
+1, we need support if user can save updated row and move to next editable cell.
