### ISSUE TITLE
Add row with grouping missing the grouped columns

### ISSUE THREAD

**Issue by sanathkumarx** [mbrn/material-table#1949]
**Describe the bug**
If we use grouping and editable at the same time, when a new row is added the add row form will not have the columns which are grouped by. So when the new row is added the columns which are grouped by will have empty values.

**To Reproduce**
1. Go to https://material-table.com/#/docs/features/editable
2. Add grouping 
`options={{
       grouping: true
      }}
`
3. Group by Name
4. Click add row button
5. The form will not have name column

**Expected behavior**
On add row all columns should be available including grouped by columns

**Screenshots**

<img width="1157" alt="Screenshot 2020-05-27 at 3 21 24 AM" src="https://user-images.githubusercontent.com/19372431/82954025-8792a900-9fc9-11ea-8f06-772b741ad222.png">

**Desktop (please complete the following information):**

 - Device: Mac
 - Browser Chrome
 - Version: 81

**Comment by graves-k** [comment]
I would also like to be able to edit fields that are currently grouped.

**Comment by jjla26** [comment]
i have the same problem. Any ideas?.. when you try to edit or add a row you lose the grouping.

**Comment by nickjava** [comment]
I am facing the same issue, has anyone figured out an alternative approach?
