### ISSUE TITLE
Multiple Detail Panel Example not working

### ISSUE THREAD

**Issue by mariolazzari** [mbrn/material-table#195]
**Describe the bug**
After updating to version 1.15, Multiple Detail Panel feature is broken.

**To Reproduce**
Go to https://mbrn.github.io/material-table/#/docz-examples-11-example-detail-panel
and try second example.

**Expected behavior**
Custom detail panel should be visible after custom icon click on the left side of the row table.

**Screenshots**
![image](https://user-images.githubusercontent.com/26960147/52045843-a011c100-2545-11e9-90b8-945378c92a02.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 
 - Version  71.0.3578.98 (64bit)

**Additional context**
Same issue on my personal projects.

**Comment by mbrn** [comment]
Hi @mariolazzari ,

Thanks for bug report. I fixed the bug and it is now in npm as 1.15.1

**Comment by mariolazzari** [comment]
I tested version 1.15.1 and all it is working fine now.
Thanks a lot for fixing so quickly: I really appreciate this!
