### ISSUE TITLE
Wrong parameter name

### ISSUE THREAD

**Issue by markosimulak** [mbrn/material-table#1955]
Hi everyone,

I've just found out that **FilterComponent**  has wrong parameter name for one of its props.

`filterComponent?: ((props: {..., onFilterChanged: (rowId: string, value: any) => void})...`

As you can see from code above, **onFilterChanged** function for the first parameter takes **rowId** instead of **columnId**.

**Expected behavior**
Rename **rowId** to **columnId**, since it's related to columns and not to rows.

Cheers,
Marko

**Comment by Domino987** [comment]
Related #1958
