### ISSUE TITLE
Improve typescript definition for Column.filterComponent props

### ISSUE THREAD

**Issue by Wait4Code** [mbrn/material-table#1958]
**Is your feature request related to a problem? Please describe.**
Using Column.filterComponent option troubles me because type definition is not really accured. 
It is described as
```typescript
((props: {columnDef: Column<RowData>, onFilterChanged: (rowId: string, value: any) => void}) => React.ReactElement<any>)
```
In fact, as far as I seen, columnDef props is not only a `Column` type but also a `EditCellColumnDef`. This is particularly annoying when trying to access `tableData` attribute.

Also, `rowId` is a bit confusing because, in fact it is `columnId` that function wants.

**Describe the solution you'd like**
Change filterComponent type definition to something like 
```typescript
((props: {columnDef: Column<RowData> & EditCellColumnDef, onFilterChanged: (columnId: string, value: any) => void}) => React.ReactElement<any>)
```

**Comment by Domino987** [comment]
Can you create a PR and we will take a look at it ?
