### ISSUE TITLE
Can we customize the name of Exported CSV file

### ISSUE THREAD

**Issue by Prasad-YS** [mbrn/material-table#196]
As of now the exported CSV file will take Table title as CSV name, But Can we add our own CSV file name instead of the default name ?

**Comment by mbrn** [comment]
This is done. It will be in next release.

**Comment by Prasad-YS** [comment]
Thanks @mbrn , But how to use this ? What poprs added for this

**Comment by mbrn** [comment]
Add exportFileName to options of table.

https://mbrn.github.io/material-table/#/docz-props

**Comment by Prasad-YS** [comment]
Worked, Thanks for Support :)
