### ISSUE TITLE
Empty table row has the wrong height

### ISSUE THREAD

**Issue by matthewkwong2** [mbrn/material-table#1960]
**Describe the bug**
According to the [Material Design Specification](https://material.io/components/data-tables#specs), the height of the table row should be 52 dp (53 dp if counting the row separator), while currently the height of the empty row is 49 dp.

**Expected behavior**
The height of the empty table row should be 52 dp (or px in CSS).

**Comment by oze4** [comment]
Nice catch!

I'm sure they'd accept a PR for this, though. Let me know if you plan on knocking it out - if not I can do it in a little bit.
