### ISSUE TITLE
How can i swap the position of cancel and save button in sticky delete confirmation box ?

### ISSUE THREAD

**Issue by vignesh-udhay** [mbrn/material-table#1962]
![image](https://user-images.githubusercontent.com/20068785/83119146-f74d8480-a0ec-11ea-94d6-c6c7b5a2f520.png)

**Comment by Domino987** [comment]
@vignesh-udhay can you show us what you already tried and what did not work? 
Maybe take a look at the row override and see if you can swap them there.

**Comment by vignesh-udhay** [comment]
![image](https://user-images.githubusercontent.com/20068785/83247207-d3f40980-a1c0-11ea-8a55-7ba967ef4537.png)

I've found out that I have to override the 'EditRow' component when mode === 'delete'. But I'm not quite sure how to go about it. Do I have to pass in some props to the 'MTableEditRow' component like actions prop or should I return an entirely new component by using the props from 'EditRow' ?
