### ISSUE TITLE
Change icon on editable with another component (like button)

### ISSUE THREAD

**Issue by c0c4i** [mbrn/material-table#1964]
Hello, is it possible to have button instead of icon on editable table?
I know that for actions is possble but i can't find a solution for editable.
https://imgur.com/a/yqCKV2x

**Comment by amperera** [comment]
Yes you can. you have to just override the Edit action
https://material-table.com/#/docs/features/component-overriding

**Comment by c0c4i** [comment]
And can I have different button from every tipe of action?

**Comment by amperera** [comment]
yes you can. please check following example
` if (typeof action === "function") {
      let element = action(props.data);
      if (element.tooltip === "Edit") {
        return (
          <MButton
            id={'edit-btn'}
            aria-label={element.icon}
            size="small"
            onClick={(event) => element.onClick(event, props.data)}
          >
           <Image
             style={styles.editIcon}
             source={require("../../assets/icons-portal/edit-icon.png")}
            />
          </MButton>
        );
      }`

**Comment by c0c4i** [comment]
I understand but I'm not trying to override a "classic" action, I'm trying to override action of this specific action of editable table (see code).

I can override the icon for Add, Check and Cancel but I can't override two icon for Edit and Delete cause they don't have toolbar attribute.
![button](https://user-images.githubusercontent.com/45185144/83460573-04f56800-a467-11ea-9a9a-6c15c2d035e3.png)


```javascript
editable={{
  onRowAdd: (newData) =>
    new Promise((resolve, reject) => {
      ref
        .postReferent(newData)
        .then((res) => {
          setChange(!change);
          resolve();
        })
        .catch((err) => console.log(err));
    }),
  onRowUpdate: (newData, oldData) =>
    new Promise((resolve, reject) => {
      ref
        .putReferent(newData)
        .then((res) => {
          setChange(!change);
          resolve();
        })
        .catch((err) => console.log(err));
    }),
  onRowDelete: (oldData) =>
    new Promise((resolve, reject) => {
      ref
        .deleteReferent(oldData._id)
        .then((res) => {
          setChange(!change);
          resolve();
        })
        .catch((err) => console.log(err));
    }),
}}
```

**Comment by amperera** [comment]
You mean "tooltip" attribute ? You can access tooltip of edit or delete by calling action method with row data. It will return element

 let element = action(data);
