### ISSUE TITLE
MaterialTable type does not have onQueryChange declared

### ISSUE THREAD

**Issue by ntai** [mbrn/material-table#1965]
**Describe the bug**
`When` using tableRef of MaterialTable, onQueryChange and other functions are not declared for TypeScript. For example, my app complains as:

```
Property 'onQueryChange' does not exist on type 'MaterialTable<LocationType>'.  TS2339
    52 | 
    53 |     if (!isLoading && tableRef.current)
  > 54 |         tableRef.current.onQueryChange();
```

**To Reproduce**
[Here is the sandbox](https://codesandbox.io/s/react-typescript-u9y71?file=/src/index.tsx
)
Look for onQueryChange(), and see the lint message.

**Expected behavior**
It should not cause TypeScript compilation error, or lint error.

**Screenshots**
[Error Message](https://i.imgur.com/Q5mTA6J.png)

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.4
 - Browser Chrome 
 - Version 83.0.4103.61 (Official Build) (64-bit)

** Additional context
Some package dependencies:

```
  "dependencies": {
    "@material-ui/core": "^4.9.14",
    "@material-ui/icons": "^4.9.1",
    "@material-ui/lab": "^4.0.0-alpha.54",
    "material-table": "^1.58.2",
    "typescript": "^3.9.3",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-redux": "^7.2.0",
    "react-router": "^5.2.0",
    "react-router-config": "^5.1.1",
    "react-router-dom": "^5.2.0",
    "react-router-redux": "^4.0.8",
    "react-scripts": "3.4.1",
    "redux": "^4.0.5",
```

tsconfig
```
{
  "compilerOptions": {
    "target": "ES6",
    "outDir": "../cworg/reactui/static/reactui/",
    "sourceMap": true,
    "lib": [
      "es6",
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": true,
    "jsx": "react",
    "module": "esnext",
    "moduleResolution": "node",
    "noImplicitAny": true,
    "noImplicitThis": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "strict": true,
    "strictNullChecks": true,
    "noEmit": true
  },
  "include": [
    "src"
  ]
}
```

**Comment by oze4** [comment]
It looks like the `tableRef` needs definitions created - currently, the [`any` type is being used](https://github.com/mbrn/material-table/blob/master/types/index.d.ts#L44) for this prop.

As a workaround, you could do:

```javascript
if (count > 0 && tableRef.current) {
  (tableRef.current as any).onQueryChange(null);
}
```
