### ISSUE TITLE
Is it possible to create an action with confirmation message? (Similar to onRowDelete)

### ISSUE THREAD

**Issue by sabbiu** [mbrn/material-table#1968]
Currently when I try to delete a row, I get a confirmation message `Are you sure you want to delete`.

How can I so similar confirmation dialog for my custom actions passed via `actions: any[]` props?

**Comment by sabbiu** [comment]
Simialr to this?

![image](https://user-images.githubusercontent.com/19733021/83324155-f64e5b80-a282-11ea-80bb-46d0f3e173db.png)

**Comment by oze4** [comment]
Hey @sabbiu does your custom action delete the row or are you looking for something else?

It would be easiest if you could create an example of what you're looking for. [Please see here](https://github.com/mbrn/material-table/blob/master/.github/ISSUE_TEMPLATE/help.md) for demo starter templates, using either CodeSandbox or StackBlitz. This makes it easier for you to create a demo.

Thanks!

**Comment by sabbiu** [comment]
Hi @oze4 I have added an example,

[CodeSandbox illustrating my use case](https://codesandbox.io/s/material-table-starter-template-q43hz?file=/src/index.js)

I want to show that confirmation if a user tries to (let us take **Blog Project** as an example)

- user tries to archive the post
- admin tries to block the user

Currently, I am showing a popup modal to confirm the actions placed by the user. And, I was wondering if it is possible to show that confirm message inline (in the row itself, same as during delete action is performed).

**Comment by ivan-khuda** [comment]
Any success here?

**Comment by ivan-khuda** [comment]
@sabbiu I believe this can be helpful https://material-table.com/#/docs/features/detail-panel

**Comment by sabbiu** [comment]
@ivan-khuda 
Detail panel allows us to show option below the row.

I was wondering to show confirmation inline for my custom actions, which is similar to onRowDelete you can find [here](https://material-table.com/#/docs/features/editable)

**Comment by Zeswen** [comment]
+1. Would love to have a boolean in the `Action` type to show confirmation.

**Comment by meirkl** [comment]
> @ivan-khuda
> Detail panel allows us to show option below the row.
> 
> I was wondering to show confirmation inline for my custom actions, which is similar to onRowDelete you can find [here](https://material-table.com/#/docs/features/editable)

Did you manage to find a way to solve this?

**Comment by sabbiu** [comment]
@meirkl No, I didn't. AFAIK, the library doesn't provide such API.

Instead of that, I am showing a popup modal to confirm the actions placed by the user.

**Comment by kadet1090** [comment]
Another possible solution could be adding `render` property into `Action` so we could wrap it with some kind of confirmation HoC.

**Comment by aitfriha** [comment]
You can use the "actions" property
<MaterialTable
        ...
        actions={[
          {
            icon: 'edit',
            tooltip: 'Edit User',
            onClick: (event, rowData) => alert('You are editing ' + rowData.name)
          },
          {
            icon: 'delete',
            tooltip: 'Delete User',
            onClick: (event, rowData) => confirm('You want to delete ' + rowData.name)
          }
        ]}
      />
