### ISSUE TITLE
Is there a option to put title in ViewColumn feature?

### ISSUE THREAD

**Issue by JoeKyy** [mbrn/material-table#197]
I want to put some title in the column list in the View Columns feature, it is possible? And disable some checkboxes?

Example

![image](https://user-images.githubusercontent.com/2018763/52055305-2d551580-2546-11e9-83da-6e40cc171db7.png)

**Comment by mbrn** [comment]
Unfortunately. But if it is very important you can override the component. 

Additionally, this would be useful feature. I will try to implement this future.

**Comment by mbrn** [comment]
This is done @JoeKyy ,

You can add removable: false to your column definition that you don't want to removed by user. And i added addRemoveColumns localization field to localization.toolbar. 

This feature will be in next release.

**Comment by mortoni** [comment]
Hi @mbrn,

Could you please give an example of how I can get this idea of toggle on and off columns of my table? So Far I have something like:

`
import AddIcon from '@material-ui/icons/AddCircleOutline'
import FileCopy from '@material-ui/icons/FileCopy'
import Fecth from 'components/Fetch'
import Spinner from 'components/Spinner'
import Table from 'components/Table'
import Widget from 'components/Widget'
import { format } from 'date-fns'
import * as React from 'react'

export interface MissionsProps {
    item: any
    setDialog: any
}

const Missions: React.SFC<MissionsProps> = ({ item, setDialog }) => {
    const onAdd = () => {
        setDialog({
            actions: null,
            children: null,
            fullScreen: false,
            fullWidth: true,
            maxWidth: 'md',
            open: true,
            title: 'New Mission',
        })
    }

    const headerButtons = [
        {
            action: onAdd,
            component: <AddIcon />,
            key: 'addIcon',
        },
    ]

    const handleCloneMission = (event: any, rowData: any) => {}

    const actions = [
        {
            icon: () => <FileCopy color='primary' />,
            onClick: handleCloneMission,
            tooltip: 'Clone Missions',
        },
    ]

    const columns = [
        { title: 'Name', field: 'name', removable: false },
        {
            field: 'missionDate',
            render: (rowData: any) =>
                format(new Date(rowData.missionDate), 'Do MMM YYYY HH:MM'),
            title: 'Date/Time',
        },
        { title: 'Location', field: 'locationName' },
        { title: 'Status', field: 'status' },
        { title: 'Operation Type', field: 'missionType.name' },
        {
            field: 'missionCrewDetails[0]',
            removable: false,
            render: (rowData: any) =>
                rowData.missionCrewDetails &&
                rowData.missionCrewDetails[0] &&
                `${rowData.missionCrewDetails[0].person.firstName} ${rowData.missionCrewDetails[0].person.lastName}`,
            title: 'Crew',
        },
        { title: 'RPA', field: 'craftNicknames' },
        { title: 'Workflow', field: 'missionWorkflowVersion.workflowName' },
    ]

    const localization = {
        toolbar: {
            addRemoveColumns: 'test',
        },
    }

    const options = {
        actionsColumnIndex: -1,
        filtering: true,
        headerStyle: { backgroundColor: '#fafafa' },
        padding: 'dense',
        pageSize: 5,
        pageSizeOptions: [],
    }
    return (
        <Fecth url='missions'>
            {({ data, err, loading }: any) => (
                <Widget
                    title={'Missions'}
                    headerButtons={headerButtons}
                    item={item}
                >
                    <Spinner condition={loading}>
                        <Table
                            columns={columns}
                            data={data}
                            options={options}
                            actions={actions}
                            localization={localization}
                        />
                    </Spinner>
                </Widget>
            )}
        </Fecth>
    )
}

export default Missions

`
