### ISSUE TITLE
CircularProgress custom coloring

### ISSUE THREAD

**Issue by kjanos0502** [mbrn/material-table#1972]
Hi,

Sorry if I'm mistaken but I haven't found an easy way to override the color of the spinner which is indicating that the table data is being loaded. I can see that I can override the entire component, but I would not like to reimplement the faded background, etc.

Would it be possible to expose this as a simple prop?

**Comment by ssong** [comment]
I'd love to pick this up.

But before I get started, I wanted to double check, @kjanos0502 editing the `primary.main` colour in the `theme` will get the job done of changing the spinner colour (granted, it would also change the primary colour in the rest of the app as well) would this satisfy the acceptance criteria for this issue?

```
const theme = createMuiTheme({
  direction: direction,
  palette: {
    type: "light",
    primary: {
      main: '#f50057'
    }
  },
});
```

If the above is not satisfactory, is the intended outcome then to pass a custom field into the `theme` object and allow the end-user to override ONLY the spinner colour? Would y'all be ok with this? @oze4

**Comment by kjanos0502** [comment]
Thanks @ssong , I did not know about this possibility. It worked fine for me, so the issue can be closed from my perspective.

**Comment by oze4** [comment]
@ssong @kjanos0502 you can either change the color via theme (or even wrap the table in a sub-theme), or you can simply override the loading component. 

Please see here for more: https://material-table.com/#/docs/features/component-overriding

Closing this out as it has been resolved.

**Comment by ArunSachdev** [comment]
Can we change the position of the spinner to the top of the table instead of middle? my table is huge and when the spinner comes after saving a specific entry the spinner comes in the middle of the table for which one has to scroll down to see. So is there a way to move it up?
