### ISSUE TITLE
Weird action column width changing

### ISSUE THREAD

**Issue by jackHedaya** [mbrn/material-table#1977]
**Describe the bug**

Action column width unattractively changing when adding row.

**To Reproduce**

```
<MaterialTable
          columns={[
            {
              title: 'ID',
              field: 'id',
              filtering: false,
              editable: 'never',
            },
            { title: 'X', field: 'x', lookup: [] },
            { title: 'y', field: 'y' },
            { title: 'z', field: 'z' },
            { title: 'h', field: 'h', editable: 'h' },
          ]}
          localization={{
            body: { editRow: { deleteText: "Are you sure you'd like to delete this assignment?" } },
          }}
          options={{
            filtering: true,
            pageSizeOptions: [6, 10, 25, 50],
            pageSize: 6,
          }}
          data={[]}
          editable={{
            isEditable: (_) => true,
            isDeletable: (_) => true,
            onRowAdd: (newData) => ...
            onRowUpdate: (newData, oldData) => ...
            onRowDelete: (oldData) => ...
          }}
```

**Expected behavior**

Column widths should not change. Perhaps the action column should hold enough space for the buttons to come up

**Screen Recording**
[Screen Recording.zip](https://github.com/mbrn/material-table/files/4713111/Screen.Recording.zip)

(Github doesn't allow .mov files)

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser: Chrome

**Comment by oze4** [comment]
Hey @jackHedaya would you mind creating a demo of this issue? You can fork the CodeSandbox or StackBlitz start templates to make building a demo easier on you.  [You can find the demo templates here](https://github.com/mbrn/material-table/blob/master/.github/ISSUE_TEMPLATE/help.md#guidelines).

**Comment by jackHedaya** [comment]
Absolutely will do when I get a chance.
