### ISSUE TITLE
Custom title component that is a dropdown; but overflow: hidden

### ISSUE THREAD

**Issue by peebles** [mbrn/material-table#1978]
I want the Toolbar, with its Search and Export functions, but I want to replace the title with a component which happens to be a dropdown (react-dates, a date range picker).  The problem is that the title is styled with overflow: hidden on line #316 in m-table-toolbar.js.  This prevents the dropdown from displaying.  If I disable overflow:hidden in devtools, the dropdown behaves.

I have not found a way to override or otherwise affect this overflow property on the title div, established in renderToolbarTitle().  Is there a way?

**Comment by Domino987** [comment]
That is currently not supported. You have to override the whole toolbar and add the search bar yourself, which should be easy to implement, since the callbacks are already provided.
Here is an [example](https://material-table.com/#/docs/features/component-overriding).

**Comment by peebles** [comment]
I understand.  Re-implementing MTableToolbar isn't that easy, what with all the CSV export support.

I guess maybe being able to add another component between the title and the search field would be nice, and more scalable than just stuffing something into the title.
