### ISSUE TITLE
setting onFilterChange still triggers default filtering logic

### ISSUE THREAD

**Issue by da1z** [mbrn/material-table#1981]
I want to do my own serverside filtering with redux and etc. but when I set onFileterChange it still triggers default table filtering logic. I think it should do nothing even if

`        onFilterChange={e => {}}`

**Comment by Domino987** [comment]
This will be called, if the filter changes, to override the filter, you have to override the customSortAndFilter of the column or use a promise for that data prop.
Closing this since this is not an issue with the library.
