### ISSUE TITLE
Filtering multiselect is jumping on screen

### ISSUE THREAD

**Issue by da1z** [mbrn/material-table#1982]
When you choose something in Filter multiselect, especially not first option, it jumps on screen.

Example: 
[sandbox](https://codesandbox.io/s/material-demo-tyffl?fontsize=14&hidenavigation=1&theme=dark)

**Comment by Domino987** [comment]
That's a problem with the select from material-ui, not with this table. 
We will upgrade the material-ui version soon, and this will be fixed.
