### ISSUE TITLE
Default value of the searchText is not passed to the field state

### ISSUE THREAD

**Issue by FastAuth** [mbrn/material-table#1985]
**Describe the bug**
Default value of the searchText is not passed to the field state

**To Reproduce**
1. Set searchText in the table options

**Expected behavior**
The search field will have the default text

**Additional context**
Works in version 1.57.2, does not work in version 1.58.0

**Comment by lpetrora** [comment]
material-table@1.59.0 does not work either

**Comment by Domino987** [comment]
This should be fixed with #2005
