### ISSUE TITLE
Is it possible to hide the row with the column titles

### ISSUE THREAD

**Issue by zys** [mbrn/material-table#1986]
I have a table and I'd like to don't show the entire row with the column titles. I wanted something like the toolbar, with I can set with `options.tollbar: false`. How can I do this?

**Comment by LeanderCoevoet** [comment]
If I understand you right you want the hide the header?
This is indeed the same as you hide the toolbar:
`options.header: false`
```
options={{
      header: false
}}
```

**Comment by zys** [comment]
It was so obvious that the only explanation is that I lost my ability to read.

Thanks!
