### ISSUE TITLE
Align 'Actions' header title in left

### ISSUE THREAD

**Issue by dearpriyankasa** [mbrn/material-table#1988]
Hello,
I've been trying to align the 'Actions' text in the default actions header column to align to left. By default its 'text-align': 'center'. Need to override this and make it 'text-align': 'left'. How do I do it?
I tried 
options: {{
headerStyle: {
    textAlign: 'left'
}
}}
But this does not get applied to Actions header column.

**Comment by oze4** [comment]
Hi @dearpriyankasa thank you for your question!

Would you mind using [the links found here](https://github.com/mbrn/material-table/blob/master/.github/ISSUE_TEMPLATE/help.md) to create a reproducible demo? I think that will help streamline your question.

**Comment by zhushenhang** [comment]
I have a similar problem.
Have you solved this problem?

**Comment by edencorbin** [comment]
same issue, seems as the default headers are left aligned so should be the actions?

**Comment by zhushenhang** [comment]
@edencorbin sry,i hava no idea.
