### ISSUE TITLE
Localisation since 1.15

### ISSUE THREAD

**Issue by Domino987** [mbrn/material-table#199]
**Describe the bug**
Since the newest version (1.15) localisation for MTableGroupbar has to be a function returning the localisation object.
But the table class still needs the localisation as a object without the function wrapping.

**To Reproduce**
1. Provide a localisation object
2. Error will be visible in console

**Expected behavior**
All tables expect a object as localisation prop.

**Stacktrace**
index.js:1446 Warning: Failed prop type: MTableGroupbar: prop type `localization` is invalid; it must be a function, usually from the `prop-types` package, but received `object`.
    in MTableGroupbar (created by MaterialTable)

**Comment by mbrn** [comment]
v1.17.0 published
