### ISSUE TITLE
CellStyle to access the full rowData information and not only field

### ISSUE THREAD

**Issue by danieladacruz** [mbrn/material-table#1991]
I am trying to define the cell of a style using cellStyle but the information available on that is only the field associated to it. But I need to customize it according to other field information.

I saw this pull request  https://github.com/mbrn/material-table/commit/da0867689a0783b0c4c500ed90c6d924f52ca2d9 but still I am not being able to use it.

When I do something like:
```
cellStyle: (value, rowData) => {
                return {backgroundColor: {rowData.color}}
              }
```
rowData is undefined.

**Comment by oze4** [comment]
Hey @danieladacruz you're on the right track.. `rowData.color` won't be defined, unless you are defining it somewhere... keep that in mind...

What type does `rowData.color` have? Is it a string or an object?  If it's a string, you should be able to just do:

```javascript
cellStyle: (value, rowData) => {
  return {
    backgroundColor: rowData.color
  }
}
```

[Check out a live demo here](https://stackblitz.com/edit/material-table-starter-template-xfbddz)

```javascript
import React, { useState } from "react";
import { render } from "react-dom";
import MaterialTable from "material-table";
import tableIcons from "./TableIcons.js";

const rando = max => Math.floor(Math.random() * max);

const words = ["Paper", "Rock", "Scissors"];

const rawData = [];
for (let i = 0; i < 100; i++) {
  rawData.push({ id: rando(300), word: words[i % words.length] });
}

const columns = [
  { 
    title: "Id", 
    field: "id", 
    cellStyle: (cellValue, rowData) => { 
      // OPEN YOUR CONSOLE
      console.log({ cellValue, rowData });
      // `rowData.color` will not be defined...
      // neither will `rowData.tableData.color`...
      return { backgroundColor: 'purple' }
    } 
  },
  { 
    title: "Word", 
    field: "word" 
  }
];

const App = () => {
  const [data, setData] = useState(rawData);

  return (
    <MaterialTable
      data={data}
      columns={columns}
      title="Starter Template"
      icons={tableIcons}
    />
  );
};

render(<App />, document.querySelector("#root"));
```

**Comment by danieladacruz** [comment]
Thank you @oze4 
That's what I was exactly looking for. For some reason I wasn't being able to access the "rowData" when using the second paramter.
