### ISSUE TITLE
Add Column Reordering

### ISSUE THREAD

**Issue by JoeKyy** [mbrn/material-table#200]
**Describe the solution you'd like**
Since you put grouping table, is possible to add column reordering?

**Describe alternatives you've considered**
Like.. https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/column-reordering/

**Comment by mbrn** [comment]
You are right @JoeKyy. I will add column reordering asap. Because we already have drag and drop feature on column headers.

**Comment by mbrn** [comment]
This is done with 1.36.0
