### ISSUE TITLE
Issues with column layout when using Fixed Columns at different resolution

### ISSUE THREAD

**Issue by sachinagarwal010** [mbrn/material-table#2002]
@mbrn   I was trying to consume the material table with fixedColumns and taken the same sample as given in the documentation, but its seems whenever I am changing my screen resolution from 100 % to 110%, my fixed column is not aligned with another columns.. As per below screen shots see the fixed column is moving upwards while changing the resolution, Any suggestion please.

![image](https://user-images.githubusercontent.com/13916436/83962580-1ce04800-a8bc-11ea-91f3-d0402ac0650d.png)

**Comment by oze4** [comment]
What happens if you refresh the page after changing resolution?

**Comment by sachinagarwal010** [comment]
@oze4 on Refreshing the page it will align properly, but we cant refresh the page as my data will lose.

**Comment by tariqporter** [comment]
I assume work hasn't begun on this yet?

**Comment by sachinagarwal010** [comment]
yes , tru , even I am waiting for this to get resolved so that I can use it
.

**Comment by sachinagarwal010** [comment]
@mbrn Any updates on this please?

**Comment by dbgordon09** [comment]
It seems fixed columns don't follow the height of the entirety of the row when text in the headings causes the height of the header to increase/decrease.
![image](https://user-images.githubusercontent.com/29728112/94921803-44859c80-04b9-11eb-87f3-f7478a188664.png)

**Comment by cabal-chan** [comment]
Having a problem with this as well.

**Comment by dfrancisc** [comment]
I am also having this problem. Any solution so far?
