### ISSUE TITLE
Error pagination and grouping if value is undefined

### ISSUE THREAD

**Issue by Domino987** [mbrn/material-table#201]
**Describe the bug**
If a column field is undefined of one object, and it is grouped by that field, it crashes.

**To Reproduce**
1. Go to: https://mbrn.github.io/material-table/#/docz-examples-12-example-grouping
2. Add items with one field undefined
3. Sort for that field

**Expected behavior**
It should not crash, if one field is undefined, but should use the empty label provided in the columns object

**Comment by mbrn** [comment]
v1.17.0 published
