### ISSUE TITLE
Detail Panel to maintain state open/closed after refresh of data.

### ISSUE THREAD

**Issue by robertabenassi** [mbrn/material-table#2012]
**Is your feature request related to a problem? Please describe.**
A detail panel is very useful to show further info about a table row entry. The user can expand the detail to reach the info she needs. However, in complex scenarios (such as collaborative workflow and/or data refresh), the opened detail panels should remain open/closed even when the data displayed in the table refreshes (sure if some conditions on the single table row is met).

**Describe the solution you'd like**
I would like to define if a detail panel should be expanded or not, better with a "native" implemetation of the future.

**Describe alternatives you've considered**
Some issues are still open about that, but they rely mainly on "how to force the opening of a detail panel by an external button.
I think this feature will be very useful if provided out of the box.

**Comment by oze4** [comment]
@robertabenassi 

It is possible to show the detailPanel programmatically.  Please see the demo below:

### [Live demo can be found here](https://stackblitz.com/edit/material-table-starter-template-xhh4kr)

### Code for demo:

```javascript
import React, { useState, useRef } from "react";
import { render } from "react-dom";
import MaterialTable from "material-table";
import { Button } from "@material-ui/core";
import tableIcons from "./TableIcons.js";

const rando = max => Math.floor(Math.random() * max);

const words = ["Paper", "Rock", "Scissors"];

const rawData = [];
for (let i = 0; i < 100; i++) {
  rawData.push({ id: rando(300), word: words[i % words.length] });
}

const columns = [
  { title: "Id", field: "id" },
  { title: "Word", field: "word" }
];

const App = () => {
  const tableRef = useRef();
  const [data, setData] = useState(rawData);

  const handleShowDetailPanel = event => {
    if (!tableRef.current) return;

    const { detailPanel } = tableRef.current.props;
    let handleShowDetailPanel = detailPanel;

    // If props.detailPanel is an array not a func
    if (typeof detailPanel === 'object') {
      // ~ I AM USING INDEX 0 HERE - CHANGE TO WHATEVER YOU NEED ~
      handleShowDetailPanel = detailPanel[0].render
    }

    const _data = [...data]; // Make copy of data

    // Edit row at index 0
    _data[0].tableData = { 
      // Copy over existing tableData properties
      ..._data[0].tableData, 
      showDetailPanel: handleShowDetailPanel
    }

    // Update our data
    setData(_data);
  }

  return (
    <div>
      <div style={{ margin: 30 }}>
        <Button 
          color="primary" 
          variant="contained" 
          onClick={handleShowDetailPanel}
        >
          Click me to programmatically show index 0 detail panel
        </Button>
      </div>
      <p>Everything above this line is OUTSIDE of Material Table</p>
      <hr />
      <p>Everything below this line is INSIDE material table (excluding this &lt;p&gt; tag)</p>
      <MaterialTable
        tableRef={tableRef}
        data={data}
        columns={columns}
        title="Starter Template"
        icons={tableIcons}
        detailPanel={rowData => <div><h1>Halo</h1></div>}
        // ~ OR IF YOU WANT TO USE AN ARRAY HERE ~
        // detailPanel={[
        //   {
        //     render: rowData => <div><h1>Halo</h1></div>,
        //   }
        // ]}
      />
    </div>
  );
};

render(<App />, document.querySelector("#root"));
```

**Comment by mihilmy** [comment]
I also have the same request. I am doing a polled refresh of the data being shown in the table. The detail panel closes as soon as the next refresh comes in. Any solutions for this other than me doing a deep diff between API calls before calling `setState`?

**Comment by oze4** [comment]
@mihilmy in summary, you are requesting new data from your server on an interval?

If this is the case, your server/API/backend is acting as the single source of truth for the data that is rendered by material-table.  

This means you will have to keep track of which detail panel is open by updating your database when someone opens a panel, or by caching which panels are open client side via cookies/local storage/etc.  This logic is not baked into material-table, but we are flexible enough to allow for someone to integrate such logic.

This request is similar to retaining a selection across pages when using remote data.

[You can see more here on how to cache selections across pages client side with cookies](https://github.com/mbrn/material-table/issues/1921#issuecomment-635049441), as the logic would be the exact same here.

**Comment by mihilmy** [comment]
Yes exactly but I do not want to enable selection. Similar logic does not seem possible with the detail panel alone right? Unless you make the selection work with a detail panel.

**Comment by oze4** [comment]
@mihilmy it's the logic you'll need to focus on. Look at the example above that shows how I control the detail panel for any row programmatically.

Just as I control the selection programmatically while keeping track of what is selected, you can apply that logic to track which row should have it's detail panel open. 

**Suppliment selection for detail panel**

**Comment by iltumio** [comment]
I found this solution by overwriting the onToggleDetailPanel function and keeping track of opened panels. I know that it's not the best solution but at least it works. More tests and performance analysis will be needed because using refs that way is always dangerous and should be avoided.

```javascript
import React, { useEffect, useRef } from "react"
import MaterialTable from "material-table"

export function CustomMaterialTable(props) {
    const tableRef = useRef()
    const openedPanels = useRef({})
    const oldFunction = useRef()

    useEffect(() => {
        if (!oldFunction.current) {
            oldFunction.current = tableRef.current?.onToggleDetailPanel
        }

        if (oldFunction.current === tableRef.current?.onToggleDetailPanel) {
            tableRef.current.onToggleDetailPanel = (path, render) => {
                if (
                    tableRef.current.props.data[path[0]].tableData
                        .showDetailPanel
                ) {
                    delete openedPanels.current[path[0]]
                } else {
                    openedPanels.current = {
                        ...openedPanels.current,
                        [path[0]]: true,
                    }
                }

                oldFunction.current(path, render)
            }
        }
    }, [tableRef])

    return (
        <MaterialTable
            tableRef={tableRef}
            {...props}
            data={
                props.data?.map((d, i) => ({
                    ...d,
                    tableData: {
                        showDetailPanel: openedPanels.current[i]
                            ? props.detailPanel
                            : null,
                    },
                })) || []
            }
        />
    )
}

```
