### ISSUE TITLE
Access onFilterChange prop in the toolbar?

### ISSUE THREAD

**Issue by Ikpeba4ll** [mbrn/material-table#2015]
Im trying to add a custom filter (date range with two input field) in my app but i can't access the onfilterchange prop. How can I access it in the toolbar?

**Comment by oze4** [comment]
@Ikpeba4ll [per our guidelines](https://github.com/mbrn/material-table/blob/master/.github/ISSUE_TEMPLATE/help.md), can you please create a demo for this?

**Comment by smartdev1206** [comment]
Is this feature implemented now? I am trying to add date range filter like today, last week, last month to toolbar.
How can I archieve this?

**Comment by Ikpeba4ll** [comment]
No
