### ISSUE TITLE
material ui popover causes the table scroll to top

### ISSUE THREAD

**Issue by dilshadahmad372** [mbrn/material-table#2016]
I have used the material ui popover in my application. when the popover is opened the table scroll to top automatically. This was the problem with the material ui Popover and they have fixed it recently. The issue might be due to version you are using of @material/core is old. Can you please fix it.

To reproduce the issue:
Add material ui popover. Scroll the table down and then open the popover the table will scroll to top which is a bug.

**Comment by oze4** [comment]
Hello @dilshadahmad372 [per our guidelines](https://github.com/mbrn/material-table/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#guidelines), would you mind creating a demo for this?  Makes things a million times easier for everyone..

Within the guidelines you will also find links to material-table demo starter templates that you can fork for both CodeSandbox & StackBlitz..  This is to bootstrap/streamline the demo creation process, and ultimately make creating demos easier on people.

We greatly appreciate your understanding!
