### ISSUE TITLE
Limit rows <= results

### ISSUE THREAD

**Issue by cbaker** [mbrn/material-table#2017]
Heres my forked example
https://codesandbox.io/s/material-table-starter-template-890ih?file=/src/index.js

I don't want 400 rows to show when I put 400 & there is < 400 rows.
I suspect I can fix this by overriding the body component, curious if there's an easier way.

**Comment by cbaker** [comment]
I decided to just slap
`tr:empty{
    display:none;
}` 

in my css to fix it.

**Comment by oze4** [comment]
@cbaker In addition to your solution, and [per the docs](https://material-table.com/#/docs/all-props), you can use `options.emptyRowsWhenPaging` to remedy this.

```javascript
<MaterialTable
  // ...
  options={{
    emptyRowsWhenPaging: false, // true by default
  }}
  // ...
/>
```
---
#### From the docs:

<img width="801" alt="image" src="https://user-images.githubusercontent.com/21092343/84203737-98362b00-aa6f-11ea-9fb6-84155f8033e7.png">

**Comment by cbaker** [comment]
@oze4 Hey, thanks. What's the reasoning behind having it true by default?

**Comment by oze4** [comment]
@cbaker that's a good question. I honestly don't have an answer for you, unfortunately.. I'm not the author, just a contributor and fanboy 😁..

@mbrn (author) would you be so kind to elaborate on this?

**Comment by cbaker** [comment]
Furthermore @mbrn are you open to changing the default from true to false? I can make a pull request if so.

**Comment by oze4** [comment]
Worth noting that some folks may consider this a breaking change. Just as you prefer the default to be false, I suppose some out there may expect for it to be true and we could really mess with existing projects that are expecting true.  Or I could be wrong...food for thought at the least. 

FWIW - like 55% of me thinks that the default should be false.

**Comment by mbrn** [comment]
Hi @cbaker 

Actually pageSize is mostly 5 or 10. So When navigating on pages we don't want that footer position changes. So it is true by default.
