### ISSUE TITLE
Sorting with diacritical marks

### ISSUE THREAD

**Issue by gamesterr** [mbrn/material-table#2018]
When diacriticial letters are first (ł, ą, ć, ó, ń, ę, ż, ź) those records goes to the end of table

In order to reproduce this bug sort table with diacritical marks.
Also upper and lower case letters are sorted separately ...ABCDEF...abcdef

Expected behavior
Sorting should go like : Aa Ąą Bb Cc Ćć Dd Ee Ęę Ff Gg Hh Ii Jj Kk Ll Łł Mm Nn Ńń Oo Óó Pp Rr Ss Śś Tt Uu Ww Yy Zz Źź Żż -based on the Polish alphabet

**Comment by oze4** [comment]
@gamesterr while I agree this is a bug, you can override the search algorithm if you would like as a band-aid.  Thanks for pointing this out!
