### ISSUE TITLE
Switch Data from local to remote dynamically

### ISSUE THREAD

**Issue by eugenegordeiev** [mbrn/material-table#2020]
I would like to use the same material-table component for both local data (array) and remote (async function).

If I initially load remote data and then try to switch to local data, it works fine.  I can see the records reload in the table.

However, when I try to switch back to remote, I can see the pagination changes but the data in the table still shows local data.

Is there any way to refresh the table?

**Comment by oze4** [comment]
Hey @eugenegordeiev would you mind creating a demo for this ([per our guidelines](https://github.com/mbrn/material-table/blob/master/.github/ISSUE_TEMPLATE/help.md))?  Just makes things a million times easier for everyone.

In the link above you will find a CodeSandbox and StackBlitz demo template - you can fork either of them to help you bootstrap your demo and make things easier on you.

**Comment by eugenegordeiev** [comment]
Actually I think I fixed it. 
After switching to remote data, I have to make a call to refresh the data.

tableRef.current.onQueryChange();

After this, everything works as expected.
