### ISSUE TITLE
Filter values depending on the previous column filter

### ISSUE THREAD

**Issue by ParvathyVinod** [mbrn/material-table#2023]
Is there an option to have filtering like that in excel? like there are 4 values a,b,c,d in column A, and  
i am selecting the value 'a'. then in column B, the values in the filter dropdown should only have values of the rows having column A='a'

**Comment by oze4** [comment]
I'm not exactly sure what you mean.. would you mind creating a demo ([per our guidelines](https://github.com/mbrn/material-table/blob/master/.github/ISSUE_TEMPLATE/help.md#guidelines)) you can fork an issue template for either CoseSandbox or StackBlitz - that link has URLs to both starter templates. That should help you streamline demo creation.

**Comment by ParVKS** [comment]
<img width="788" alt="Screen Shot 2020-06-12 at 1 22 00 PM" src="https://user-images.githubusercontent.com/40163489/84479077-f2bdca00-acaf-11ea-859a-75dcb8ebf50a.png">
So this is the first case, columnB has these many values to select from. That is these are the "lookup" data.
<img width="595" alt="Screen Shot 2020-06-12 at 1 22 35 PM" src="https://user-images.githubusercontent.com/40163489/84479087-f81b1480-acaf-11ea-816c-628fb9d79ac3.png">

Then Column C has these many values to select from.
<img width="487" alt="Screen Shot 2020-06-12 at 1 22 47 PM" src="https://user-images.githubusercontent.com/40163489/84479092-fa7d6e80-acaf-11ea-9242-73e49e709fd2.png">
 
But if you are selecting attorney from column B, you can only select from these many values in column C.

So my question. is how do you modify the "lookup" data that we specify for each columns in material-table like the example i have given above?

**Comment by yaagesh** [comment]
Any solution?
