### ISSUE TITLE
currentPage attribute not updating on pagination

### ISSUE THREAD

**Issue by lpetrora** [mbrn/material-table#2024]
On version 1.60, when using remote data fetch, MaterialTable is not updating currentPage state on pagination

**To Reproduce**
1. Start with RemoteData example
2. currentPage on MaterialTable state is  0
3. Change to the next page
4. currentPage on MaterialTable state is still 0. 

**Expected behavior**
On another page different from first one currentPage should not be 0

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Vivaldi
 - Version 3.0.1874.38
 - MaterialTable version: 1.60.0

**Comment by oze4** [comment]
I'm not sure how exactly how you're using currentPage (or why) - if you wouldn't mind providing a demo, there are starter templates you can fork [here](https://github.com/mbrn/material-table/blob/master/.github/ISSUE_TEMPLATE/help.md#guidelines)..  With that being said, [the docs](https://material-table.com/#/docs/features/remote-data) have good demos for using remote data.
