### ISSUE TITLE
Fixed column width in percentage

### ISSUE THREAD

**Issue by amit1910** [mbrn/material-table#2027]
How to set a fixed column width with percentage,
The percentage doesn't seem to be working,

Any idea about how to achieve this.

**Comment by Leocete** [comment]
I'm also searching for the similar solution as it is done in jQuery Datatables: https://datatables.net/reference/option/columns.width

**Comment by Leocete** [comment]
Hi @amit1910 ,
I think material-table already have a solution for that - [https://github.com/mbrn/material-table/issues/1657#issuecomment-587411922](url)
