### ISSUE TITLE
Remote data with groupings

### ISSUE THREAD

**Issue by pellejacobs** [mbrn/material-table#2035]
**Is your feature request related to a problem? Please describe.**
Generic question: is grouping supported with remote data? I've played around with the remote data sample code, but it doesn't seem like the `data` prop fires the query when the grouping gets changed. 

**Describe the solution you'd like**
Given I'm using remote data
When I'm grouping by a certain column
Then it would be great if MT could process a response to just populate the grouping view

When I then expand a certain grouped row
Then MT could send a new data request for the data grouped in this specific row.

**Comment by thalysonalexr** [comment]
frustrating
