### ISSUE TITLE
How to change selected rows from outside of component?

### ISSUE THREAD

**Issue by Buuntu** [mbrn/material-table#2036]
I'm unable to find anything in the documentation about how to do this, I imagine it's using the `tableRef` property but I don't know what properties that contains that would be able to change the selected rows.  I am using a table with selection enabled, basically I want somewhere outside of this component to handle the selected rows as well (like remove certain rows).

```jsx
<MaterialTable
    columns={columns}
    data={files}
    title="Table"
    tableRef={tableRef}
    options={{
      selection: true,
    }}
>

const removeSelectedRow = (idx: number) => {
// what goes here?
tableRef.current.removeSelectedRow(idx);
}
```

**Comment by sphrases** [comment]
I need this so bad!

**Comment by Buuntu** [comment]
I think I figured out how to solve it using tableRef, although it's not great:

```jsx
const tableRef = useRef<any>(); // not sure if there's a better type for this

const removeFromChecked = (idx: number) => {
    if (!tableRef) {
      return;
    }

    tableRef.current.dataManager.changeRowSelected(false, [idx]);
};

return <MaterialTable
  tableRef={tableRef}
  data={data}
  columns={columns}
/>;
```

This seems like a common enough use case to be in the docs, I think.

**Comment by arkhemlol** [comment]
I don't get why this feature hasn't been implemented yet. Programmatically selected rows is a common use case, i.e. when table being used in forms.

**Comment by alehechka** [comment]
Trying to use the reverse of this by taking in URL query params an initially selecting a row based on the params. Tried using the tableRef technique shown by @Buuntu, but doing that makes it so you can't deselect the row from the table. This would be a good feature to add.

**Comment by gonyulian415** [comment]
new version should be
```js
tableRef.current.dataManager.changeRowSelected(false,[rowId])
tableRef.current.setState(tableRef.current.dataManager.getRenderState(),function(){
    return tableRef.current.onSelectionChange();
})
```
thx @Buuntu
