### ISSUE TITLE
Display actions column when selection is true

### ISSUE THREAD

**Issue by wassafr** [mbrn/material-table#2039]
**The problem**
When you have the `selection` option enabled and `actions` configured, the actions column will not be displayed and the action buttons will be displayed in the top right corner only when a selection is made.

While this is acceptable for multiple selection, I find it not intuitive at all for a single selection where one could expect to find actions buttons within each row. It also requires an extra click because you first need to select a row, then click on the action button.

Finally, I find the documentation not very clear about that behaviour.

**The solution**
I would recommend to simply display the actions column whatever the value of the `selection` option is.

It could also be useful to have an option to let developers choose between the current behaviour and my proposed behaviour.

Finally, I would suggest to improve the documentation by duplicating the example "Actions on Selected Rows Example" in the Selection section into the Actions section.

**The pep talk**
Very nice job on this component, very (very) useful. Congratulations.

**Comment by wassafr** [comment]
Closing as I've just seen a PR about that

**Comment by maxim-s-barabash** [comment]
I managed to achieve the desired result. But I get a warning.
Warning: Failed prop type: Invalid prop `actions[1]` supplied to `MaterialTable`.

https://codesandbox.io/s/material-demo-fgw0f

```js
import React from "react";
import MaterialTable from "material-table";

export default function ConditionalActions() {
  return (
    <MaterialTable
      title="Conditional Actions Preview"
      columns={[
        { title: "Name", field: "name" },
        { title: "Surname", field: "surname" },
        { title: "Birth Year", field: "birthYear", type: "numeric" },
        {
          title: "Birth Place",
          field: "birthCity",
          lookup: { 34: "İstanbul", 63: "Şanlıurfa" }
        }
      ]}
      options={{
        actionsColumnIndex: -1,
        selection: true,
        showSelectAllCheckbox: true
      }}
      data={[
        { name: "Mehmet", surname: "Baran", birthYear: 1987, birthCity: 63 },
        {
          name: "Zerya Betül",
          surname: "Baran",
          birthYear: 2017,
          birthCity: 34
        }
      ]}
      actions={[
        // not working
        rowData => ({
          icon: "save",
          position: "row",
          tooltip: "save User",
          onClick: (event, rowData) => alert("You saved " + rowData.name)
        }),
        // It works but issues a warning.
        {
          action: rowData => ({
            icon: "delete",
            tooltip: "Delete User",
            onClick: (event, rowData) =>
              confirm("You want to delete " + rowData.name),
            disabled: rowData.birthYear < 2000
          }),
          position: "row"
        }
      ]}
    />
  );
}

```
Any ideas how to do it right.
