### ISSUE TITLE
Grouping and custom sort are ignored

### ISSUE THREAD

**Issue by Domino987** [mbrn/material-table#204]
**Describe the bug**
If grouping is enabled, custom sort is ignored.

**To Reproduce**
1. Go to: https://mbrn.github.io/material-table/#/docz-examples-12-example-grouping
2. Add custom sort to a column
3. Group and click on group pill => no custom sorting

**Expected behavior**
* The custom sort is respected

**Comment by Domino987** [comment]
I love the grouping feature ( my boss as well). When will be able to expect a new release date with the fixes ?

**Comment by mbrn** [comment]
I hope this weekend i can publish a new feature for new small improvements including this.

**Comment by mbrn** [comment]
I have completed this. But it requires a trick when applying a customSort:

```javascript
{
        title: 'Adı', field: 'name', customSort: (a, b, type) => {
          if (type === 'row') {
            return a.name.length - b.name.length;
          }
          else if(type === 'group') {
            return a.length - b.length;
          }
        }
      },
```

**Comment by mbrn** [comment]
v1.17.0 published
