### ISSUE TITLE
Can I use "export as csv" method by using ref? 

### ISSUE THREAD

**Issue by ManalLiaquat** [mbrn/material-table#2041]
# Guidelines

 - #### Please include a demo of the issue/behavior/question you have
I have a button and I want to **export data as CSV format** on behalf of button's `onClick` function.
 - #### Please try to be as detailed as possible
Is there any way to do this or can I use ref to call methods of material-table?
 - #### You may fork one of the following starter templates if you would like:

   - #### [CodeSandbox](https://codesandbox.io/s/material-table-starter-template-xnfpo)
   - #### [StackBlitz](https://stackblitz.com/edit/material-table-starter-template)

**Comment by DatChoob** [comment]
I looked in the ref and here's the closest I've gotten with a Ref,

tableRef.current.props.components.Toolbar.Naked.propTypes.exportCsv()

This wont work, but I figured i'll put it here since I was curious.
