### ISSUE TITLE
Any way to add custom fields/buttons into toolbar?

### ISSUE THREAD

**Issue by just4fun** [mbrn/material-table#2048]
**Is your feature request related to a problem? Please describe.**

From the source code of [MTableToolbar](https://github.com/mbrn/material-table/blob/master/src/components/m-table-toolbar.js#L227-L234), I noticed there are only two places to include fields or actions inside toolbar. One is search field which will be rendered by `renderSearch()`, one is columns button and export button which will be rendered by `renderDefaultActions()`. Let's say I align search field to left, then align default actions to right.

Now I want to add one more button next to search field, but seems like no any prop exposed to render it.

**Describe the solution you'd like**

Expose one more prop to render custom fields/buttons, which could be put next to [div className={classes.spacer}](https://github.com/mbrn/material-table/blob/0550a9ed1945102305f7da30f58557d837c2cfad/src/components/m-table-toolbar.js#L231).

**Describe alternatives you've considered**

Currently there are two workarounds.

1. Use custom component to replace `MTableToolbar`. (I don't prefer this, since in my app both search field and export button are being used, if I replace built-in `MTableToolbar`, I need to duplicate these two things into new component).

2. Create the custom field or button I need, then give it `position: absolute` to manually adjust it next to search field.

**Additional context**

![image](https://user-images.githubusercontent.com/7512625/84673685-9fbc6f00-af5c-11ea-8159-1c7afd53f887.png)

**Comment by eglavin** [comment]
Yeah Id like to second this feature as it would be very usefull, Same for the export button, id like to add a export to pdf and export to email options but seems like im going to have to create a custom component to do so.

**Comment by valeriozhang** [comment]
any updates on this?

**Comment by kajalv** [comment]
This thread helps. Although the issue title may indicate something different, the comments do contain a working solution for this specific use case: https://github.com/mbrn/material-table/issues/830

**Comment by Dev967** [comment]
or just go crazy and use a bunch of div's. Like that,
                                 `<div style={{display: "flex", flexDirection: "row-reverse"}}>
                                    <Button color="primary" variant="outlined">
                                        Create New  <AddCircleIcon /> </Button>
                                    <div style={{width: "100%"}}>
                                    <MTableToolbar {...props} searchFieldVariant="standard" />
                                    </div>
                                </div>`
 i think you can adjust things with widths. or just go with another CSS approach to position these div's
 hope it helps
