### ISSUE TITLE
Can I display info on row hover?

### ISSUE THREAD

**Issue by Jsalvat** [mbrn/material-table#2050]
Hello!
I did my research and I think that there's no such a thing. I mean, I want to show some info when I hover over a certain row field.

Material-table can't do it atm right?

**Comment by VLRTroll** [comment]
I'm not sure what you said about info. If you were talking about Tooltips (for expample), so we could do something like this.
```
components={{
  Cell: (props) => 
    <Tooltip title={props.value} arrow>
      <MTableCell {...props} />
    </Tooltip>
}}
```

![print](https://user-images.githubusercontent.com/55628273/85153420-91a47200-b22c-11ea-9816-863a8782d81f.png)

**Comment by ariel262626** [comment]
There is similar action with the row? 
something like <MTableRow>
