### ISSUE TITLE
Render a custom component on render rowData

### ISSUE THREAD

**Issue by aquibbaig** [mbrn/material-table#2051]
When I map through the items in an array to render a custom component for each one of them, it shows no results. 
```
const columns = [
    {
      field: "name",
      title: "Name"
    },
    {
      field: "favNumbers",
      title: "Favourites",
      render: (rowData: { favNumbers: any[] }) => {
        rowData.favNumbers.forEach(m => {
          return <Chip variant="outlined" color="primary" label={m} />;
        });
      }
    }
  ];
  const data = [
    {
      title: "Aquib",
      favNumbers: [1, 2, 3, 4]
    }
  ];
```

## Expected behaviour:

Chip component for each of the items in the favNumbers array.

## Sandbox link

https://codesandbox.io/s/clever-rgb-q48n3?fontsize=14&hidenavigation=1&theme=dark

**Comment by mbrn** [comment]
Hi @aquibbaig 

Your render function does not return anything. 

Try this:
```javascript
render: (rowData: { favNumbers: any[] }) => {
        return rowData.favNumbers.map(m => {
          return <Chip variant="outlined" color="primary" label={m} />;
        });
      }
```

Better version:
```javascript
render: (rowData: { favNumbers: any[] }) => rowData.favNumbers.map(m =><Chip variant="outlined" color="primary" label={m}>);
```

**Comment by atishwarchand** [comment]
@mbrn @aquibbaig can you help me with this question...
Please
[https://github.com/mbrn/material-table/issues/2628#issue-746166717](url)
