### ISSUE TITLE
Selected row styling doesn't work

### ISSUE THREAD

**Issue by capan** [mbrn/material-table#2052]
# Guidelines

 - #### I have combined remote data and selected row styling examples. When I click on a row and another consequently first clicked row doesn't deselected automatically. Also after the selection of a row in the first page, on the next page same row is still selected. It seems like rowStyle property in options props doesn't work properly. 

Please see the codeSandbox link below

   - #### [CodeSandbox](https://codesandbox.io/s/material-table-starter-template-kvnqg?fontsize=14&hidenavigation=1&theme=dark)

**Describe the bug**
rowStyle property of options prop doesn't work properly when used with remote data. Selected rows can not be deselected.

**To Reproduce**
1. Sandbox link
2. Click on any row in the first page.
3. Click another row and see first row still selected.
4. Click the first row again and see first row doesn't get deselected.
5. Go to second page, see 5th and 6th rows are also selected even though you haven't clicked on them.

**Expected behavior**
On every row click selected rows must be visually updated. If user clicks on the already selected row row must be deselected.

**Screenshots**
![image](https://user-images.githubusercontent.com/7265736/84743421-97931c80-afba-11ea-9b3c-35c9b3ee5689.png)
![image](https://user-images.githubusercontent.com/7265736/84743446-a2e64800-afba-11ea-88ea-8315ff669420.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Browser [chrome]
 - Version [1.61.0]

**Comment by balaSpyrus** [comment]
I am also facing the same issue while handling row selection when i get remote data from server.
