### ISSUE TITLE
Resiazble columns

### ISSUE THREAD

**Issue by pavlyxar** [mbrn/material-table#2053]
Hello guys!
Thank you for your excelent job with the table.
Your lib is so advanced and it closes allmost bussines requests.
But our bussines needs resiazble columns, and I can't use another libs, because they are hardly compatible with yours.
I think resiazble columns can be a good feature for the lib.

Thank you a lot, your job is very valued for me!

**Comment by VLRTroll** [comment]
I totally agree. And I think this is a simple feat to add.
Looking a little bit inside the code, I guess when we try to set the header cell style (through the column.headerStyle) the CSS width property is simply ignored by the component.

So I hope this feature come asap.

**Comment by VLRTroll** [comment]
Reading about the last releases features, I found this one that is exactly what we are talking about.

![v1.59](https://user-images.githubusercontent.com/55628273/85166842-4004e300-b23e-11ea-952e-14eb0e60f1df.png)

If you are working on this or later version, you already have what you want. Else, try to update the Material Table's npm package.

**Comment by pavlyxar** [comment]
As far as I realize your comment, our ideas are little bit different, because I would like the opportunity to change columns width using the mouse. For examle, it was implemented in dev express tables and mui tables, which are based on material ui as material-table. Customers of these libs just can change the value of special prop in their table-component and I'd like it in material-table lib. I think it'll be the good feature, when you want to set the height of your table and you know that your page size is static.
https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/column-resizing/
https://codesandbox.io/embed/q8w3230qpj?autoresize=1&hidenavigation=1

**Comment by VLRTroll** [comment]
Oh, I got it. Definitely it's an amazing feature. And now I'm really sure I agree with you kkkk.
I'm waiting for it.

**Comment by iamsaurabhgupt** [comment]
@VLRTroll we would also want the resizable column feature. 
please prioritise this. 
thanks in advance.

**Comment by mukesh-pathak-by** [comment]
Hi Team,

This feature is quite handy even our team is looking forward towards this feature. Please priorities this.

Thank you,

**Comment by mbrn** [comment]
I started to work on this :)

**Comment by UsmanAzee** [comment]
Any update about this issue ? (the one @VLRTroll talked about) ...

**Comment by sandeepkumar-vedam-by** [comment]
Hi @mbrn, Hope you're doing great. We are eagerly waiting for this feature.

Could you please let us know expected release date with this feature ?

**Comment by ahmetozantekin** [comment]
> I started to work on this :)

hi @mbrn , is there any update? if there, contact me please :)
thanks.
