### ISSUE TITLE
Change Initial Value of rowsPerPage

### ISSUE THREAD

**Issue by NAkibRUET** [mbrn/material-table#2057]
The default value of rowsPerPage in Pagination is 5, it can be changed to other values. But I want to change the initial value to 10 or 20. 
Or, in other words I want the lowest rowsPerPage value be 10, not less than that. 
How can I do that?

**Comment by Kogl1n** [comment]
`options={{pageSize: 10}}`

**Comment by NAkibRUET** [comment]
> The easy answer is `options={{pageSize: 10}}` as an extra property to the table.

Thank you @Kogl1n . It seems to be working now
