### ISSUE TITLE
Issue with Horizontal scroll in Material Table

### ISSUE THREAD

**Issue by SagarDesai111** [mbrn/material-table#2058]
- Problem with Material Table columns, What should I do for a horizontal scroll?

`<MaterialTable
          columns={columns}
          tableRef={props.tableRef}
          title="Contacts"
          isLoading={!props.remote}
          onSearchChange={e => searchInData(e)}
          data={props.contactList}
          key={props.limit}
          components={{
            Pagination: () => {
              return (
                <TablePagination
                  rowsPerPageOptions={[5, 10, 25]}
                  count={props.count}
                  rowsPerPage={props.limit}
                  page={props.page - 1}
                  onChangePage={handleChangePage}
                  onChangeRowsPerPage={handleChangeRowsPerPage}
                />
              );
            },
          }}
          actions={[
            {
              icon: () => <FilterListIcon />,
              tooltip: 'Filters',
              isFreeAction: true,
              onClick: () => OpenFilterModal(),
            },
            {
              icon: 'add',
              tooltip: 'Add Contact',
              isFreeAction: true,
              onClick: () => setAddDrawer(),
            },
          ]}
        />`

Screenshot: https://prnt.sc/t18pg7

**Comment by atosh502** [comment]
you can add `whiteSpace: 'nowrap'` in `headerStyle` and in `cellStyle` to avoid text wrapping
