### ISSUE TITLE
 Is it possible to put the onclick event in the rows? 

### ISSUE THREAD

**Issue by p9614** [mbrn/material-table#2061]
I would like to know if there is any way to use the onclick property in the table rows, so that there will be a dialog
I tried as follows but I did not have the expected result

<MaterialTable
    title="Users"
    columns={[
      {title: 'IdUser',field: 'IdUser', type: 'numeric', hidden:'false'},
      {title: 'name',field: 'name'},
      { title: 'lastname', field: 'lastname' },
      {title: 'age', field: 'age', type: 'numeric',onClick:rowData=>{setRow(rowData);setOpen(true)}},
    ]}
    data={user.DataUser}
    options={{
      filtering: true
    }}
  />
);
}

**Comment by NAkibRUET** [comment]
use `onRowClick`

<MaterialTable
                title="Users"
                columns={[
                  { title: 'IdUser', field: 'IdUser', type: 'numeric', hidden: 'false' },
                  { title: 'name', field: 'name' },
                  { title: 'lastname', field: 'lastname' },
                  { title: 'age', field: 'age', type: 'numeric' }
                ]}
                data={user.DataUser}
                **onRowClick={event => this.handleRowClick(event)}**
                options={{
                  filtering: true
                }}
              />

**Comment by p9614** [comment]
@NAkibRUET 

Thanks, but is there a way that it can be by column and not by row?
For example, only by clicking on the name column will the dialog open
