### ISSUE TITLE
Date Format option on column

### ISSUE THREAD

**Issue by talanw** [mbrn/material-table#2072]
It would be nice to have a date format option on a column with a type of either 'date' or 'datetime'. With this in place, the table column can be set to a date format local to the user.

**Comment by cemnacar** [comment]
You can use dateSetting option in version 1.61.0.
toLocaleDateString('tr-TR') is used for formatting.

{
   title: 'Başlangıç Tarihi',
   field: 'startDate',
   type: 'date',
   dateSetting: { locale: 'tr-TR' },
}

**Comment by talanw** [comment]
thanks, that looks like it's resolved my issue.
