### ISSUE TITLE
Is it possible to make a bordered table using material-table?

### ISSUE THREAD

**Issue by NAkibRUET** [mbrn/material-table#2074]
I want to add borders to the table cells like the traditional html table. 
Is it possible in material-table?

**Comment by NAkibRUET** [comment]
I found the solution, so I am closing this issue
`
const TableCellStyle = {
  borderRight: '1px solid #e5e5e5'
};`

`const columnData:[{id: '0',title: 'Name',field: 'name',hidden: false,cellStyle: TableCellStyle}]`

```
<MaterialTable
  columns={columnData}
/>
```

**Comment by harkibit** [comment]
To avoid duplication you can apply a global style for the cells

`<MaterialTable
  columns={columnData}
  options={{
     cellStyle: {
          borderRight: '1px solid #eee'
     }
  }}
/>`

and for the header 
`<MaterialTable
  columns={columnData}
  options={{
     headerStyle: {
          borderRight: '1px solid #eee'
     }
  }}
/>`
