### ISSUE TITLE
Allow changing the cell color based on value. Easy Fix!

### ISSUE THREAD

**Issue by emersonbottero** [mbrn/material-table#2076]
While customizing a cell style based on value like in this example [here ](https://codesandbox.io/s/material-table-selection-different-data-from-table-iu9re) is not possible to customize color because it is overriden again in this [line](https://github.com/mbrn/material-table/blob/d6f1e8576273f39308db01706e4d765aed10a95b/src/components/m-table-cell.js#L100).

To test it just replace background with color in the linked example.
If we comment the line that sets color for me at least it still work in light ou dark mode as it should.

**To Reproduce**
1. Go to  [here ](https://codesandbox.io/s/material-table-selection-different-data-from-table-iu9re)
2. Replace background with color on line 26
3. chech text style of cell containing George Name
4. the color is set to inherit

**Expected behavior**
the text color should be set to any color specify in the component option.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser [edge. chrome]

**Additional context**
check it forcing color in the code is really necessary, if it is provide and option to define it in another way.

**Comment by Domino987** [comment]
Why do you not use options={{cellStyle}}?

**Comment by emersonbottero** [comment]
As descrbied on the first line is because the style is based on the value of the cell , like if value < 10 red,if beteewn 10 and 50 yellow, above 50 green, etc...

**Comment by Domino987** [comment]
As written in the docs, it can be a function:
```
cellStyle: value=>({
          backgroundColor: value === 'Mehmet'? '#EEE' : 'white',
        })
```
For cellStyle the value and row will be passed, for rowStyle only the row will be provided.

**Comment by emersonbottero** [comment]
unless you use 
cellStyle: value=>({
          color: value === 'Mehmet'? '#EEE' : 'white',
        })
as described on the example given, folowing the steps you can check.
color is overwritten again, there is a link in my description

**Comment by emersonbottero** [comment]
https://github.com/mbrn/material-table/blob/d6f1e8576273f39308db01706e4d765aed10a95b/src/components/m-table-cell.js#L100

**Comment by Domino987** [comment]
Can be done with cellStyle.

**Comment by emersonbottero** [comment]
No. It can't. Just read the comments above.
