### ISSUE TITLE
Editable disabled when updating and enabled when updating?

### ISSUE THREAD

**Issue by piekczyk** [mbrn/material-table#2078]
Hey, is there a way to block field during updating and allow to edit when new record is created? 
I have a situation where one column in the table should not be editable during updates but should be editable when creating a new record. Right now it seems to be impossible.

**Comment by Domino987** [comment]
As written in the docs the columns accept: 

editable | 'always' 'never' 'onUpdate' 'onAdd' | 'always' | Editable custom component
-- | -- | -- | --
