### ISSUE TITLE
MaterialTable with column type "date" is off by one

### ISSUE THREAD

**Issue by wontonst** [mbrn/material-table#2079]
# Guidelines

**To Reproduce**

```
const columns = [
            {
                title: "foo",
                field: "date",
                headerStyle: {textTransform: "capitalize"},
                type: "date",
                sorting: false
            },
            {title: "Views", field: "visits", type: "numeric"},
            {
                title: "Time Spent",
                field: "timeSpent",
                type: "numeric",
                render: (row) => prettyMilliseconds(row.timeSpent)
            }
        ];
data = [
            {
                date: '2020-06-13',
                timeSpent: 3,
                visits: 2,
            },
        ];

<MaterialTable
          columns={columns}
          data={data}
          title={title}
          icons={tableIcons}
        />
```

**Expected behavior**
The table should have one row with date 6/13/2020

**Screenshots**
![image](https://user-images.githubusercontent.com/2030556/85236920-35318600-b3d7-11ea-975f-3fe45eac824d.png)

**Workaround**
I can get the correct date to show by removing the line `type: 'date'` which gives me 2020-06-13 which isn't aesthetic but is correct.

Latest Chrome MacOS Mojave

material-table 1.62.0

**Comment by stevechae** [comment]
I noticed this issue too. I noticed that if you specify time as well, it is rendered correctly, for example `2020-06-13T12:00:00`.

**Comment by Domino987** [comment]
I cannot reproduce this. Can you provide a sandbox? Its most likely connected to time zone differences.

**Comment by ajmueller** [comment]
This is how the standard Date object behaves in JavaScript.  Here's an example in the Firefox console:

![image](https://user-images.githubusercontent.com/1442179/85801473-c8c8c680-b6f7-11ea-984b-862eac778d39.png)

Looking at the source, I believe [these two lines are the culprit](https://github.com/mbrn/material-table/blob/977211a6b3afcb853aa6263908fefbb00d0abefe/src/components/m-table-cell.js#L38-L39).  A small change to use date-fns's `parse` function should do the trick.  Here's a quick test with that date in RunKit using the version of date-fns specified in package.json:

![image](https://user-images.githubusercontent.com/1442179/85802023-e8142380-b6f8-11ea-9bc6-5a1925172b4d.png)

**Comment by Domino987** [comment]
I am not sure if that will be a breaking change. We should understand it first completely.
So new Date will parse the date into the local time zone. So Fri Jun 12 2020 GTM -0700 is actually the correct time stamp.
Just due to the offset (time zone), the previous day will be shown.
This is only the case if your offset if negative GMT. By doing parseISO you break the code for all user east of england xD

So I will look into that too
