### ISSUE TITLE
BUG: row font-family

### ISSUE THREAD

**Issue by osor1o** [mbrn/material-table#2080]
the new version does not recognize the font family roboto.

**Comment by mfmsajidh** [comment]
Yes, I also have the same issue
![image](https://user-images.githubusercontent.com/36571307/85809753-8db9a800-b776-11ea-9651-b2c231a5572f.png)

**Comment by Domino987** [comment]
Can you share your code? I do not have that issue.

**Comment by mfmsajidh** [comment]
Same code I copied from your official docs no difference [https://material-table.com/#/docs/features/actions](url)

**Comment by Domino987** [comment]
Something must be different or you would see exactly that. So you need to share your setup and try to reproduce that.

**Comment by idanamit** [comment]
I'm experiencing the same issue also and it wasn't like that last time I checked.

As far as I can see the difference is that each td element is receiving additional font styling options that wasn't there before:
![image](https://user-images.githubusercontent.com/8151381/86082662-9cd48900-badb-11ea-963d-ffe79d4d878c.png)

At least in my case these font styles are overriding my own font styles which results in the table looking the same as the picture attached by @mfmsajidh 

This is the PR that made this change: https://github.com/mbrn/material-table/pull/1997

is there a way to solve this issue while keeping the changes intact?

**Comment by mfmsajidh** [comment]
Yes, I agree with @idanamit . I checked, the font styles are being override by default
![image](https://user-images.githubusercontent.com/36571307/86105766-5c760a80-badd-11ea-968f-220ee995ad70.png)
![image](https://user-images.githubusercontent.com/36571307/86105780-626beb80-badd-11ea-87ca-d2036531cf61.png)

**Comment by mfmsajidh** [comment]
@Domino987 Any updates on this Bug Issue ????

**Comment by AmeerHamzaRiaz** [comment]
![image](https://user-images.githubusercontent.com/28997655/87875195-f6e4b200-c9e8-11ea-8ad8-cd2b51a07b14.png)
I am facing same problem, on version 1.64.0

**Comment by mindaugasnakrosis** [comment]
What is the status?

**Comment by ivoberger** [comment]
The official docs have the same problem. should be an easy enough fix, the change is even in the changelog for v1.62.0 (second line from the bottom)
![image](https://user-images.githubusercontent.com/16694197/88908256-edb1db80-d259-11ea-85be-83b417f8df71.png)
![image](https://user-images.githubusercontent.com/16694197/88908382-14701200-d25a-11ea-9722-c91aa4cf3ac5.png)

**Comment by correaricardo** [comment]
any updates?

**Comment by goneale** [comment]
Waiting

**Comment by mzakocs** [comment]
waiting as well

**Comment by mzakocs** [comment]
I found a workaround for this. You can get the Roboto font on your rows by adding this property to your MaterialTable:
`
options={{
    rowStyle: {
        fontFamily: "Roboto"
     }
}}
`

**Comment by DominikEngel** [comment]
Well writing "waiting" isn't any valuable input. But you're in luck! This project is open source so you have the power to contribute a proposed solution yourself. So if any of you has a proposal feel free to create a PR addressing this issue.

**Comment by Domino987** [comment]
Well writing "waiting" isn't any valuable input. But you're in luck! This project is open source so you have the power to contribute a proposed solution yourself. So if any of you has a proposal feel free to create a PR addressing this issue.

**Comment by correaricardo** [comment]
Great, @mzakocs! I'm using version **1.61.0**, which does not have this “bug”.

**Comment by shaselboeck** [comment]
Bug in 1.69.1 still present

**Comment by robin-sf** [comment]
@osor1o can we re-open this bug, please, since it's a regression present in the current released version

**Comment by Domino987** [comment]
Since this repo is abandoned by mbrn, please move to the community supported from https://github.com/material-table-core/core
