### ISSUE TITLE
How can I Horizontal Scrolling in the Material Table ?

### ISSUE THREAD

**Issue by sureshpareek915** [mbrn/material-table#2088]
# Guidelines

 - #### Please include a demo of the issue/behavior/question you have

 - #### Please try to be as detailed as possible
I've used MaterialTable and used 20 to 30 columns but the table looks weird, I want to do horizontal scroll but not working.
How can I Horizontal Scrolling in the material table?
https://prnt.sc/t5plhm, https://prnt.sc/t5pluf

 - #### You may fork one of the following starter templates if you would like:

   - #### [CodeSandbox](https://codesandbox.io/s/material-table-starter-template-xnfpo)
   - #### [StackBlitz](https://stackblitz.com/edit/material-table-starter-template)

**Comment by VLRTroll** [comment]
I've tried to get this bug on Material-Table, but I didn't get it.

I created a new table with few repeated columns to reach it, but for my surprise the table got a horizontal scroll bar automatically. [StackBlitz - Table with 50 columns](https://stackblitz.com/edit/material-table-starter-template-twysey)  **(Test running on 1.58.2 version on StackBlitz)**

![image](https://user-images.githubusercontent.com/55628273/86418950-3bade080-bca8-11ea-8407-782c227f2801.png)

**Comment by emerson88** [comment]
I am getting the same issue. I noticed the error is happening in my environment because I am using **display:flex** on the containers above the <MaterialTable>, I have changed to **display:block** and the table started to display the scroll.

In this topic below they are talking about it, link: 
https://github.com/mbrn/material-table/issues/1395#issuecomment-621467452

**Comment by harshpatel991** [comment]
If you're using the `<TableContainer>` or `<Table>` component inside of a MUI grid, just add `zeroMinWidth={true}` on the `<Grid item>` component like so:

```
  <Grid container>
                    <Grid item zeroMinWidth={true}>
                        <TableContainer component={Paper}>
....
```

**Comment by rofrol** [comment]
```css
.table-responsive {
  overflow-x: auto;
}
.table-responsive table {
  white-space: nowrap;
}
```

From https://stackoverflow.com/questions/19794211/horizontal-scroll-on-overflow-of-table/48930521#48930521
