### ISSUE TITLE
Table is not updated

### ISSUE THREAD

**Issue by SunaoSuzu** [mbrn/material-table#2091]
Hi

Now I am trying to use Material-tables with editable.
We are using redux to manage the state of applications.

After adding row , the table is updated. But after both editing and deleting row, table is not udated.
I have checked the state is updated well and the parent component of material-table is re-renderd.

Please let me know the point I have to check.

**Comment by Domino987** [comment]
We cannot help you without seeing your implementation because it works for sure, so something must be wrong with your code. Can you provide a sandbox or paste all the needed code? This is also not an issue with the table itself, so you should move this to stackoverflow. Link me once you did that.
