### ISSUE TITLE
Allow Material-UI makeStyles() for styling

### ISSUE THREAD

**Issue by asjustis** [mbrn/material-table#2092]
Hi,

Since MaterialTable is based on Material-UI, it would be amazing if it supported Material-UI's `makeStyles()` for styling.

Currently, we can only hardcode the styles in the MaterialTable properties. With the use of `makeStyles()` this could be avoided and it would help to keep the consistency with other Material-UI components.

```
const App = () => {
  const styles = useStyles();
  return (
    <MaterialTable
      data={words}
      columns={columns}
      options={{ headerStyle: styles.tableHead }}
    />
  );
};

const useStyles = makeStyles(theme => ({
  tableHead: {
    backgroundColor: theme.palette.primary.light
  }
}));
```

Same example in the sandbox: https://codesandbox.io/s/material-table-starter-template-qz52h

**Comment by Domino987** [comment]
The problem is that `headerStyle` acdepts CSS props, but styles.tableHead returns a className.
I think you could use the Material ui Theme Provider to achieve that.

**Comment by dreukrag** [comment]
What I did was to still have the theme affect the color of the table was this, though it feels rather hacky:
```

let header = {};
const PersonGroupStyle = makeStyles((theme) => {
  header = {
    backgroundColor: theme.palette.primary.main,
    color: theme.palette.primary.contrastText,
  };
  return {
    content: {
      ...theme.defaultContent,
    },
  };
});
```

Then simply use the prop

```
options = {{
    headerStyle: header,
}}
```
