### ISSUE TITLE
How can control individual row actions onClick without having effects seen in other rows?

### ISSUE THREAD

**Issue by yathomasi** [mbrn/material-table#2096]
# Unable to control the actions individually

Using state to handle actions in table row. of course has effects on all the rows.
But I couldn't figure out to show loading progressbar only on the action i clicked not on all the rows.
For example, here on click on edit button.
![Screenshot from 2020-06-26 00:04:23](https://user-images.githubusercontent.com/20840228/85776837-cc347000-b740-11ea-9c1d-82a2cebc03b3.png)
![Screenshot from 2020-06-26 00:05:24](https://user-images.githubusercontent.com/20840228/85776898-d9e9f580-b740-11ea-8ad1-8df2b9805564.png)

 - #### Here is codesandbox that shows the issue:

   - #### [CodeSandbox](https://codesandbox.io/s/material-table-actions-kehkh)

**Comment by yathomasi** [comment]
@ashindiano @code404sg
can you guys help here please ?

**Comment by ashindiano** [comment]
import React, { useState } from "react";
import { render } from "react-dom";
import MaterialTable from "material-table";
import tableIcons from "./TableIcons.js";
import EditIcon from "@material-ui/icons/Edit";
import IconButton from "@material-ui/core/IconButton";
import DeleteIcon from "@material-ui/icons/Delete";
import { makeStyles } from "@material-ui/core/styles";
import CircularProgress from "@material-ui/core/CircularProgress";
import { green } from "@material-ui/core/colors";

const rando = max => Math.floor(Math.random() * max);

const words = ["Paper", "Rock", "Scissors"];

const rawData = [];
for (let i = 0; i < 100; i++) {
  rawData.push({ id: rando(300), word: words[i % words.length] });
}

const useStyles = makeStyles(theme => ({
  root: {
    display: "flex",
    alignItems: "center"
  },
  wrapper: {
    margin: theme.spacing(1),
    position: "relative"
  },
  buttonSuccess: {
    backgroundColor: green[500],
    "&:hover": {
      backgroundColor: green[700]
    }
  },
  fabProgress: {
    color: green[500],
    position: "absolute",
    top: 6,
    left: 6,
    zIndex: 1
  },
  buttonProgress: {
    color: green[500],
    position: "absolute",
    top: "50%",
    left: "50%",
    marginTop: -12,
    marginLeft: -12
  }
}));

const App = () => {
  const classes = useStyles();
  const [data, setData] = useState(rawData);
  const [loading, setLoading] = useState(null);

  return (
    <MaterialTable
      data={data}
      columns={[
        { title: "Id", field: "id" },
        { title: "Word", field: "word" },
        {
          title: "Actions",
          render: rowData => {
            return (
              <div>
                <IconButton
                  aria-label="edit"
                  disabled={loading}
                  onClick={() => {
                    setLoading(rowData.id); //Set the unique id as your state
                    setTimeout(() => {
                      setLoading(null);
                    }, 1000);
                  }}
                >
                  <EditIcon />
                  {loading === rowData.id && ( //compare the state id and row id to display progress
                    <CircularProgress
                      size={38}
                      className={classes.fabProgress}
                    />
                  )}
                </IconButton>
                <IconButton aria-label="delete">
                  <DeleteIcon />
                </IconButton>
              </div>
            );
          }
        }
      ]}
      title="Starter Template"
      icons={tableIcons}
    />
  );
};

render(<App />, document.querySelector("#root"));

**Comment by yathomasi** [comment]
@ashindiano thank you so much ♥️
I haven't checked with my own table but this way it should works.
