### ISSUE TITLE
Onclick action button, should freeze the row to avoid multiple user clicks

### ISSUE THREAD

**Issue by JudeNiroshan** [mbrn/material-table#2099]
# Guidelines

When there are actions being used, users can click on those actions. It will trigger an onclick function along with the rowData object. But this will not freeze the clicked row being clicked once again. In this case, there will be multiple onclick calls for the same row. This must be blocked from the table row. 

 I'm always frustrated when multiple triggers are generated for the same row through actions in material table. 

**Describe the solution you'd like**
There should be a toogle like behaviour for any action that is being configured to material table rows.

**Describe alternatives you've considered**
It is possible to have conditional actions and freeze the entire table. But this is not what we want. We want to freeze only the clicked row. That will not destroy the user experience with the material table.

https://material-table.com/#/docs/features/actions

**Comment by Domino987** [comment]
How would you implement that? 
Do you think about, if its a promise that this will be awaited or until the function returns something?
What do you have in mind?
