### ISSUE TITLE
Grouping ignored render prop

### ISSUE THREAD

**Issue by Domino987** [mbrn/material-table#210]
**Describe the bug**
If a column is grouped, it ignores the render prop and if cannot render that value, it crashes.

**To Reproduce**
1. Go to https://mbrn.github.io/material-table/#/docz-examples-12-example-grouping
2. Change one field in data to be an object
3. Provide a render prop
4. Group that column

**Expected behavior**
The group row should render the render prop if provided

**Comment by Domino987** [comment]
Maybe provide an accessor prop which returns a string or number to group the items by and also display in the grouped row as "group header"?

**Comment by mbrn** [comment]
Maybe. I will think more.

**Comment by Domino987** [comment]
Maybe exchange the field prop to return a value instead if the field to enable custom fields like arrays ?

**Comment by Domino987** [comment]
This could also be used to omit the empty render prop, since it could also return the empty value.

**Comment by mbrn** [comment]
I let grouping if column has both render and field. And call render method with a (fieldValue, 'group') if gruped, else (rowData, 'row').

**Comment by mbrn** [comment]
this will be in v1.18.0

**Comment by Domino987** [comment]
That sound good. Thank you.
