### ISSUE TITLE
Default options for all tables

### ISSUE THREAD

**Issue by watanabeshuji** [mbrn/material-table#2104]
I want to apply the specific options to all tables in application.
How I do?

For example:
All Material Tables hav such options
```
        options={{
          showTitle: false,
          padding: 'dense',
          pageSize: 10,
          pageSizeOptions: [10, 20, 50],
          headerStyle: {
            backgroundColor: 'transparent',
            fontWeight: 'bold',
          }
        }}
```

**Comment by manolobattistadev** [comment]
Hi watanabeshuji,

to have a default options in all tables you can import a var configuration and use the property spread notation (It was added in ES2018).

Your table configuration
```
export const TableDefaultConfig = {
       options: {
           showTitle: false,
           padding: 'dense',
           pageSize: 10,
           pageSizeOptions: [10, 20, 50],
           headerStyle: {
              backgroundColor: 'transparent',
              fontWeight: 'bold',
          }
      }
}
```

Your page with table
```
import { TableDefaultConfig } from '../TableConfig';

<MaterialTable 
   options={{
       ...TableDefaultConfig.options,
       pageSize: 20, 
   }}
/>
```

**Comment by watanabeshuji** [comment]
thank a lot!

**Comment by belfortmaycon** [comment]
> import { TableDefaultConfig } from '../TableConfig';
> 
> <MaterialTable 
>    options={{
>        ...TableDefaultConfig.options,
>        pageSize: 20, 
>    }}
> />
> ```
Hi @manolobattistadev I've tried this but I got this error:

```
No overload matches this call.
  Overload 1 of 2, '(props: MaterialTableProps<{ locationNum: string; description: string; }> | Readonly<MaterialTableProps<{ locationNum: string; description: string; }>>): MaterialTable<...>', gave the following error.
    Type '{ pageSize: number; pageSizeOptions: number[]; headerStyle: { backgroundColor: string; fontWeight: string; }; rowStyle: { fontFamily: string; }; }' is not assignable to type 'Options<{ locationNum: string; description: string; }>'.
      The types of 'headerStyle.fontWeight' are incompatible between these types.
        Type 'string' is not assignable to type '"bold" | "-moz-initial" | "inherit" | "initial" | "revert" | "unset" | "normal" | (number & {}) | "bolder" | "lighter" | undefined'.
  Overload 2 of 2, '(props: MaterialTableProps<{ locationNum: string; description: string; }>, context: any): MaterialTable<{ locationNum: string; description: string; }>', gave the following error.
    Type '{ pageSize: number; pageSizeOptions: number[]; headerStyle: { backgroundColor: string; fontWeight: string; }; rowStyle: { fontFamily: string; }; }' is not assignable to type 'Options<{ locationNum: string; description: string; }>'.
      Types of property 'headerStyle' are incompatible.
        Type '{ backgroundColor: string; fontWeight: string; }' is not assignable to type 'CSSProperties'.ts(2769)
index.d.ts(45, 3): The expected type comes from property 'options' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<MaterialTable<{ locationNum: string; description: string; }>> & Readonly<...> & Readonly<...>'
index.d.ts(45, 3): The expected type comes from property 'options' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<MaterialTable<{ locationNum: string; description: string; }>> & Readonly<...> & Readonly<...>'

```

Could you help me?

Thanks

**Comment by manolobattistadev** [comment]
> No overload matches this call.
>   Overload 1 of 2, '(props: MaterialTableProps<{ locationNum: string; description: string; }> | Readonly<MaterialTableProps<{ locationNum: string; description: string; }>>): MaterialTable<...>', gave the following error.
>     Type '{ pageSize: number; pageSizeOptions: number[]; headerStyle: { backgroundColor: string; fontWeight: string; }; rowStyle: { fontFamily: string; }; }' is not assignable to type 'Options<{ locationNum: string; description: string; }>'.
>       The types of 'headerStyle.fontWeight' are incompatible between these types.
>         Type 'string' is not assignable to type '"bold" | "-moz-initial" | "inherit" | "initial" | "revert" | "unset" | "normal" | (number & {}) | "bolder" | "lighter" | undefined'.
>   Overload 2 of 2, '(props: MaterialTableProps<{ locationNum: string; description: string; }>, context: any): MaterialTable<{ locationNum: string; description: string; }>', gave the following error.
>     Type '{ pageSize: number; pageSizeOptions: number[]; headerStyle: { backgroundColor: string; fontWeight: string; }; rowStyle: { fontFamily: string; }; }' is not assignable to type 'Options<{ locationNum: string; description: string; }>'.
>       Types of pr



> > import { TableDefaultConfig } from '../TableConfig';
> > <MaterialTable
> > options={{
> > ...TableDefaultConfig.options,
> > pageSize: 20,
> > }}
> > />
> 
> Hi @manolobattistadev I've tried this but I got this error:
> 
> ```
> No overload matches this call.
>   Overload 1 of 2, '(props: MaterialTableProps<{ locationNum: string; description: string; }> | Readonly<MaterialTableProps<{ locationNum: string; description: string; }>>): MaterialTable<...>', gave the following error.
>     Type '{ pageSize: number; pageSizeOptions: number[]; headerStyle: { backgroundColor: string; fontWeight: string; }; rowStyle: { fontFamily: string; }; }' is not assignable to type 'Options<{ locationNum: string; description: string; }>'.
>       The types of 'headerStyle.fontWeight' are incompatible between these types.
>         Type 'string' is not assignable to type '"bold" | "-moz-initial" | "inherit" | "initial" | "revert" | "unset" | "normal" | (number & {}) | "bolder" | "lighter" | undefined'.
>   Overload 2 of 2, '(props: MaterialTableProps<{ locationNum: string; description: string; }>, context: any): MaterialTable<{ locationNum: string; description: string; }>', gave the following error.
>     Type '{ pageSize: number; pageSizeOptions: number[]; headerStyle: { backgroundColor: string; fontWeight: string; }; rowStyle: { fontFamily: string; }; }' is not assignable to type 'Options<{ locationNum: string; description: string; }>'.
>       Types of property 'headerStyle' are incompatible.
>         Type '{ backgroundColor: string; fontWeight: string; }' is not assignable to type 'CSSProperties'.ts(2769)
> index.d.ts(45, 3): The expected type comes from property 'options' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<MaterialTable<{ locationNum: string; description: string; }>> & Readonly<...> & Readonly<...>'
> index.d.ts(45, 3): The expected type comes from property 'options' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<MaterialTable<{ locationNum: string; description: string; }>> & Readonly<...> & Readonly<...>'
> ```
> 
> Could you help me?
> 
> Thanks

Could you share me your TableDefaultConfig.options? I see `headerStyle` on error, but headerStyle is a columns option. You have to pass a valid material-table options (https://material-table.com/#/docs/all-props).

**Comment by belfortmaycon** [comment]
> Could you share me your TableDefaultConfig.options? I see `headerStyle` on error, but headerStyle is a columns option. You have to pass a valid material-table options (https://material-table.com/#/docs/all-props).

Is quite the same of your comment, I just added a rowStyle:

```
export const TableDefaultConfig = {
  options: {
    pageSize: 10,
    pageSizeOptions: [10, 20, 50],
    headerStyle: {
      backgroundColor: 'transparent',
      fontWeight: 'bold',
    },
    rowStyle: { fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif' },
  },
};
```

**Comment by belfortmaycon** [comment]
@manolobattistadev I'm using typescript, and when trying to create the options using the interface Options from material-table, It's a generic interface that requeres the RowData, so I can use it. But after remove the headerStyle and put it directly on component, works.

```
options={{
      ...options,
      search: true,
      headerStyle: {
        backgroundColor: 'transparent',
        fontWeight: 'bold',
      },
    }}
```

Maybe is it a bug with Typescript?
