### ISSUE TITLE
not able to set space between rows

### ISSUE THREAD

**Issue by varbanov88** [mbrn/material-table#2105]
I want to set space between the rows in the table to achieve this effect:
![rows](https://user-images.githubusercontent.com/20975938/85948384-50614000-b959-11ea-8d1b-2f360b10c512.JPG)

I tried the following code:
```
<MaterialTable
        title=""
        columns={state.columns}
        data={state.data}
        options={{
          pageSize: 15,
          pageSizeOptions: [10, 15, 25, 50],
          searchFieldAlignment: 'left',
          rowStyle: {
            paddingBottom: '5px'
          }
        }}
      />
```

**Comment by ifndefdeadmau5** [comment]
This doesn't seem like a bug

**Comment by varbanov88** [comment]
then how can be achieved

**Comment by ifndefdeadmau5** [comment]
I mean you can't call it bug just because you can't achieve something with some library, I'd rather see it as enhancement

**Comment by varbanov88** [comment]
if you accept row styles and they are not applied, I consider this as a bug

**Comment by Domino987** [comment]
It is applied but material-ui blocks it. So its not a problem with material-table but with @material-ui. Please open an issue there. Thank you.
