### ISSUE TITLE
Export Button items do not display with v 1.63.1    

### ISSUE THREAD

**Issue by glenkitchen** [mbrn/material-table#2110]
**Describe the bug**
The Export Button menu items do not display after upgrading material table to v 1.63.1

**To Reproduce**
*   Create a CodeSandbox with Material Table and Options.exportButton = true (https://codesandbox.io/s/material-table-export-demo-92v45)  
*   Click the Export Button

**Expected behavior**
A menu should display export options: `Export to Csv` and `Export to Pdf` (New with 1.63.1)
Instead the menu items are blank    

**Screenshots**

![image](https://user-images.githubusercontent.com/9795765/86086495-2c5d4600-baa2-11ea-8bdd-192692048475.png)
   
![image](https://user-images.githubusercontent.com/9795765/86086510-354e1780-baa2-11ea-9751-1f07e6c2fe05.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Edge & Chrome (latest)

**Smartphone (please complete the following information):**
N/A

**Additional context**
Perhaps this commit [Add function for exporting table as PDF](https://github.com/mbrn/material-table/pull/1970) caused the issue?

**Comment by jardon** [comment]
I'm looking into it.  It seems that something else was merged at the same time that has caused this issue.  I'll update this thread when I find a solution.  Thank you for your patience!

**Comment by jardon** [comment]
I've created a PR to fix the issue.  It looks to me like Prettier CLI may have been the cause of the issue as there was a merge post my PR that omitted the default localization strings for the export buttons.  I'm not particularly familiar with the linter to say for sure.

Hopefully, this gets merged quickly!

**Comment by glenkitchen** [comment]
Thx @jardon. I appreciate the feature and the first turnaround on the fix.

**Comment by joeldsouzax** [comment]
Hey, I got this problem in version 1.62.0, Interestingly it only came up recently in iframe,  @jardon

**Comment by jardon** [comment]
Looks like 1.64 has been packaged.  This should be resolved.  Anyone have time to pull the new version and confirm this has been fixed in production?

**Comment by glenkitchen** [comment]
Working, Thanks.
