### ISSUE TITLE
'WebpackError: ReferenceError: window is not defined' when building a static site using gatsbyjs

### ISSUE THREAD

**Issue by floAr** [mbrn/material-table#2112]
Using the current version of material-table it is not possible to build out a static html side (for example using gatsby js)
During the build process the error   `WebpackError: ReferenceError: window is not defined` shows up. I'm using  "material-table": "^1.62.0",

It was working on an older version of material-table: https://codesandbox.io/s/yj6jnmqpw9?file=/package.json
but seems to be broken by something introduced in the meantime.  There are some leads on the gatsby side, but not enough to fix the error: https://www.gatsbyjs.org/docs/debugging-html-builds/#how-to-check-if-code-classlanguage-textwindowcode-is-defined

Any help is greatly appreciated

**Comment by hendra-go** [comment]
Yeah, i confirmed this bug.

The problem is jsPDF. Related to [Angular universal does not work with jsPDF: ReferenceError: window is not defined](https://github.com/MrRio/jsPDF/issues/2753)

It is not material-table fault, but probably not published new version until above issue fixed ?

**Comment by zackkrida** [comment]
Yeah this is pretty critical—means any use of Material Table in a project with server-side rendering (SSR) could break, especially considering this was released on a minor version bump (so folks deployment processes may automatically bump to this version).

**Comment by oze4** [comment]
Is this still an issue with `v1.63.0`? I know that version fixed a different jsPDF issue.

**Comment by floAr** [comment]
@oze4 I created a quick fix for this and confirmed it is working for the gatsby stack

**Comment by floAr** [comment]
> 
> 
> Is this still an issue with `v1.63.0`? I know that version fixed a different jsPDF issue.

I think the fix was about putting jsPDF into normal depenency instead of dev. I tried it yesterday and the fix was still present. It breaks when importing the jspdf package during a static build process (because it uses 'window' which is undefined without a browser)

**Comment by hendra-go** [comment]
Thanks @floAr , i also confirmed this PR works with Gatsby.

But for me, i will stick to `material-table 1.62.0` because that version had all i need for my current project.

I will upgrade only if my project needs PDF Export function or material-table becomes more modular or at least has an option to choose which export function suites your need.

Probably instead:
`exportButton: true`

We can use something like:
```
exportButton: {
    exportCsv: true,
    exportPdf: true
}
```

**Comment by willwill96** [comment]
Experiencing the same thing with SSR - just going to revert to 1.62.0 until this is resolved

**Comment by floAr** [comment]
There is a PR (#2114) that sould solve this problem, @mbrn maybe you want to have a look on this?

**Comment by s-kris** [comment]
Same issue with NextJS

**Comment by gxwheel152** [comment]
Agree --- would be nice to have the ability to turn off the PDF version. Hitting the same issue with a Gatsby site

**Comment by CloudZazu** [comment]
I have the same problem with Next.js

**Comment by mahdibarati** [comment]
version 1.65.0 had this bug from jspdf.
I'm using 1.62.0 and everything is OK now

**Comment by mariojfduarte** [comment]
facing same problem

**Comment by yashas123** [comment]
No fix yet? Same problem with Nextjs
```
Server Error
ReferenceError: window is not defined

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
file:///C:/project/frontend/node_modules/jspdf/dist/jspdf.min.js (37:30237)
<unknown>
file:///C:/project/frontend/node_modules/jspdf/dist/jspdf.min.js (1:62)
Object.<anonymous>
file:///C:/project/frontend/node_modules/jspdf/dist/jspdf.min.js (1:66)
Module._compile
internal/modules/cjs/loader.js (1158:30)
Object.Module._extensions..js
internal/modules/cjs/loader.js (1178:10)
Module.load
internal/modules/cjs/loader.js (1002:32)
Function.Module._load
internal/modules/cjs/loader.js (901:14)
Module.require
internal/modules/cjs/loader.js (1044:19)
require
internal/modules/cjs/helpers.js (77:18)
Object.<anonymous>
file:///C:/project/frontend/node_modules/material-table/dist/components/m-table-toolbar.js (60:37)
Module._compile
internal/modules/cjs/loader.js (1158:30)
Object.Module._extensions..js
internal/modules/cjs/loader.js (1178:10)
Module.load
internal/modules/cjs/loader.js (1002:32)
Function.Module._load
internal/modules/cjs/loader.js (901:14)
Module.require
internal/modules/cjs/loader.js (1044:19)
require
internal/modules/cjs/helpers.js (77:18)
```

**Comment by yashas123** [comment]
No fix yet? Same problem with Nextjs
```
Server Error
ReferenceError: window is not defined

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
file:///C:/project/frontend/node_modules/jspdf/dist/jspdf.min.js (37:30237)
<unknown>
file:///C:/project/frontend/node_modules/jspdf/dist/jspdf.min.js (1:62)
Object.<anonymous>
file:///C:/project/frontend/node_modules/jspdf/dist/jspdf.min.js (1:66)
Module._compile
internal/modules/cjs/loader.js (1158:30)
Object.Module._extensions..js
internal/modules/cjs/loader.js (1178:10)
Module.load
internal/modules/cjs/loader.js (1002:32)
Function.Module._load
internal/modules/cjs/loader.js (901:14)
Module.require
internal/modules/cjs/loader.js (1044:19)
require
internal/modules/cjs/helpers.js (77:18)
Object.<anonymous>
file:///C:/project/frontend/node_modules/material-table/dist/components/m-table-toolbar.js (60:37)
Module._compile
internal/modules/cjs/loader.js (1158:30)
Object.Module._extensions..js
internal/modules/cjs/loader.js (1178:10)
Module.load
internal/modules/cjs/loader.js (1002:32)
Function.Module._load
internal/modules/cjs/loader.js (901:14)
Module.require
internal/modules/cjs/loader.js (1044:19)
require
internal/modules/cjs/helpers.js (77:18)
```

**Temporary fix is to use nextjs dynamic import:**
```js
import dynamic from "next/dynamic";

const MaterialTable = dynamic(() => import("material-table"), { ssr: false });
```

**Comment by amahar** [comment]
I have this problem with Nextjs - reverting to version `material-table 1.62.0` for now.
