### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by AlexanderNaiden** [mbrn/material-table#2118]
**Describe the bug**
We successfully used material-table of version 1.57.2 but after it was changed with newer 1.58.0 or higher till 1.63.1 the error constantly occures in VS Code when run tests. It relates to `fast-deep-equal` component. For some reason it shows `RangeError: Maximum call stack size exceeded` when I ran `npm run test` command in VS Code . As I see in `package-lock.json` file the material-table uses  "fast-deep-equal": "2.0.1". I used all version of material-table from 1.58.0 till 1.63.1 and with all of them VS Code shows that errors. It works only with old version material-table 1.57.2. The exact place where is error occured is shown in `error in file in material-table.PNG` file.  See attached screenshots: here is exact place where is error occured -> https://yadi.sk/i/1wy9RhkxcZx4xg  and here is ouput in VS Code that shows `RangeError: Maximum call stack size exceeded` -> https://yadi.sk/i/IjKgSFeXXFff1A

**Expected behavior**
The tests should work fine as previously with version 1.57.2.

**Screenshots**
Attached screenshots with error:
1) https://yadi.sk/i/1wy9RhkxcZx4xg
2) https://yadi.sk/i/IjKgSFeXXFff1A

**Desktop :**

- OS: [windows 10 pro]
- Browser [chrome]
- Version [83.0.4103.116]

**Comment by ladnishad** [comment]
Were you able to resolve this?

**Comment by gauravagarwal2704** [comment]
Facing the same issue. Not able to identify what the problem is. I am using `material-table` inside Material-ui `Tab` component.
I am pretty sure it is not because of Tabs, because another table component got rendered, but not the one which is causing problem. I am not able to pin the problem. 
@ladnishad @AlexanderNaiden were you able to solve this ?

**Comment by upklio** [comment]
We were experiencing this issue when React Developer Tools was NOT installed. With it installed it weirdly works.

**Comment by ramonribeiro96** [comment]
I solved it by removing "field" from "columns" and just adding "render" with my data.

I don't know if this will help anyone.

**Comment by GomesEdelyBCG** [comment]
> We were experiencing this issue when React Developer Tools was NOT installed. With it installed it weirdly works.

If you don't mind, do you remember how did you solved this?

**Comment by ramonribeiro96** [comment]
I just rendered all the columns manually and it worked.

[Captura de Tela 2023-10-30 às 09.07.55.jpg]



Em 19 de out. de 2023, à(s) 15:44, GomesEdelyBCG ***@***.***> escreveu:



We were experiencing this issue when React Developer Tools was NOT installed. With it installed it weirdly works.

If you don't mind, do you remember how did you solved this?
