### ISSUE TITLE
 trigger onChangeRowsPerPage  = > onChangePage also trigger

### ISSUE THREAD

**Issue by phanvantien270290** [mbrn/material-table#2121]
# Guidelines

  - #### [CodeSandbox](https://codesandbox.io/s/material-table-starter-template-uw7in?file=/src/index.js)

**Describe the bug**
When I select **onChangeRowsPerPage** , the **onChangePage** function is also enabled
expected : only action clicked trigger.
**To Reproduce**

1. Select row per page '
2. Click choose  options 
3. See in console  (F12)
4. See  error 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/37722989/86317729-5eb1a380-bc5a-11ea-967e-a0a0b6440117.png)

**Additional context**
**More error**: when i set totalCount -> not working (ex: my data have 10 records: i want set count: 500)  
expected : 10 of 500

**Comment by Domino987** [comment]
This was done on purpose and you can differentiate between the two calls: https://github.com/mbrn/material-table/pull/2003
