### ISSUE TITLE
Change the style of body.editRow.deleteText

### ISSUE THREAD

**Issue by bturtu405** [mbrn/material-table#2122]
I need to change my delete text  style because my site is written with a rtl language.

**Comment by VLRTroll** [comment]
I don't know if there is a "standart" way to do that, but I was in the same situation and I solved with something like this:

```
//Material UI - Solution
const StyledEditRow = withStyles((theme) => ({
  root: {
    //h6 is the delete text HTML element that you wanna style
    '& h6': {
      fontSize: 'larger',
      fontWeight: 'bold',
      color: theme.palette.warning.main,
    },
  },
}))(MTableEditRow);
```

![image](https://user-images.githubusercontent.com/55628273/86410097-8faccb00-bc90-11ea-9b03-af4cc3a12766.png)

I hope this code drop can help you.
