### ISSUE TITLE
How to add toggle button to rows? 

### ISSUE THREAD

**Issue by VidushaZ** [mbrn/material-table#2123]
I want to add a toggle button which will disable the row on table. Is there any way to achieve this?

**Comment by ifndefdeadmau5** [comment]
You'll probably need disabled state to each rows and then add action that triggers state change(disabled) of each row, how does that sound?

**Comment by VidushaZ** [comment]
@ifndefdeadmau5 Yeah that sounds good.. How could I achieve this?

**Comment by ifndefdeadmau5** [comment]
Let's say you have data array like this
```js
[
    {
      disabled: false,
      name: 'Jack',
    },
    {
      disabled: false,
      name: 'Alice',
    },
];
```

and then provide your custom action button via `actions` prop, then you have control of your data array in the onClick handler. So you can simply set new state with inverted disabled data which will eventually going to `data` prop, that'll trigger table updates.

**Comment by VidushaZ** [comment]
@ifndefdeadmau5 Hi Thanx for ur reply... how can I add a button to each row?
