### ISSUE TITLE
Multi sorting data

### ISSUE THREAD

**Issue by Nolandos** [mbrn/material-table#2129]
Hello, 

Can I sorting data according to several columns? Default when i sort by column "name", and i want additionally sort by "value", data is sorted by based data. I read that, this functionally was in progress. Maybe someone did it ?

**Comment by nikitxskv** [comment]
+1

**Comment by thellimist** [comment]
+1

**Comment by nrdev88** [comment]
+1

**Comment by valeriozhang** [comment]
+1
