### ISSUE TITLE
Icon not loading in react only label is showing

### ISSUE THREAD

**Issue by mehuljariwala** [mbrn/material-table#213]
When i install in my react app then icon not loading

**Comment by mbrn** [comment]
Can you share screenshot and code usage of material-table.

**Comment by mehuljariwala** [comment]
"dependencies": {
    "@material-ui/core": "^3.8.1",
    "@material-ui/icons": "^3.0.1",
    "@material-ui/lab": "^3.0.0-alpha.24",
}

<MaterialTable
              columns={[
                { title: "Name", field: "name" },
                { title: "Soyadı", field: "surname" },
                { title: "Doğum Yılı", field: "birthYear", type: "numeric" },
                {
                  title: "Doğum Yeri",
                  field: "birthCity",
                  lookup: { 34: "İstanbul", 63: "Şanlıurfa" }
                }
              ]}
              data={[
                {
                  name: "Mehmet",
                  surname: "Baran",
                  birthYear: 1987,
                  birthCity: 63
                }
              ]}
              title="title"
              actions={[
                {
                  icon: "done_all",
                  tooltip: "Do",
                  onClick: (event, rows) => {
                    alert("You selected " + rows.length + " rows");
                  }
                }
              ]}
              options={{
                selection: true
              }}
              onSelectionChange={data =>
                alert("You selected " + data.length + " rows")
              }
            />

**Comment by mehuljariwala** [comment]
![image](https://user-images.githubusercontent.com/30499320/52197554-f81e2f80-2885-11e9-8d63-59c4cf76e65f.png)

**Comment by mbrn** [comment]
You should install icons with script tag in html or try to give icons like this: https://github.com/mbrn/material-table/issues/93#issuecomment-457015457

**Comment by mehuljariwala** [comment]
in react you should pass props like that i solved 
icons={{ FirstPage: FirstPage }}

**Comment by mehuljariwala** [comment]
some icons is not working on this also

**Comment by mbrn** [comment]
Which one?

**Comment by Favna** [comment]
@mehuljariwala as per referenced in https://github.com/mbrn/material-table/issues/93#issuecomment-457015457 and with a little bit of digging myself it turns out that the lib expects SortArrow while @material-ui/icons provides it under the name "Sort". This is working (TypeScript) code as of Material-Table v1.18.0

```ts
import { SvgIconProps } from '@material-ui/core/SvgIcon';
import Check from '@material-ui/icons/Check';
import ChevronLeft from '@material-ui/icons/ChevronLeft';
import ChevronRight from '@material-ui/icons/ChevronRight';
import FilterList from '@material-ui/icons/FilterList';
import FirstPage from '@material-ui/icons/FirstPage';
import LastPage from '@material-ui/icons/LastPage';
import Remove from '@material-ui/icons/Remove';
import SaveAlt from '@material-ui/icons/SaveAlt';
import Search from '@material-ui/icons/Search';
import SortArrow from '@material-ui/icons/Sort';
import ViewColumn from '@material-ui/icons/ViewColumn';
import MaterialTable, { Column } from 'material-table';
import React, { Component } from 'react';
import { commonObject } from '../utils/types';

interface Props {
  data: commonObject[];
  columns: Column[];
  title: string;
}

class MUITable extends Component<Props> {
  render () {
    return (
      <MaterialTable
        columns={this.props.columns}
        data={this.props.data}
        title={this.props.title}
        icons={{
          Check: () => <Check /> as React.ReactElement<SvgIconProps>,
          DetailPanel: () => <ChevronRight /> as React.ReactElement<SvgIconProps>,
          Export: () => <SaveAlt /> as React.ReactElement<SvgIconProps>,
          Filter: () => <FilterList /> as React.ReactElement<SvgIconProps>,
          FirstPage: () => <FirstPage /> as React.ReactElement<SvgIconProps>,
          LastPage: () => <LastPage /> as React.ReactElement<SvgIconProps>,
          NextPage: () => <ChevronRight /> as React.ReactElement<SvgIconProps>,
          PreviousPage: () => <ChevronLeft /> as React.ReactElement<SvgIconProps>,
          Search: () => <Search /> as React.ReactElement<SvgIconProps>,
          SortArrow: () => <SortArrow /> as React.ReactElement<SvgIconProps>,
          ThirdStateCheck: () => <Remove /> as React.ReactElement<SvgIconProps>,
          ViewColumn: () => <ViewColumn /> as React.ReactElement<SvgIconProps>,
        }}
      />
    );
  }
}

export default MUITable;
```

**Comment by pak11273** [comment]
The clear icon is not working for me:

![image](https://user-images.githubusercontent.com/2309184/55690122-ebd05480-5952-11e9-9fd0-7e9db319b47d.png)


````
 import Search from "@material-ui/icons/Search"
 import ViewColumn from "@material-ui/icons/ViewColumn"
 import SaveAlt from "@material-ui/icons/SaveAlt"
 import ChevronLeft from "@material-ui/icons/ChevronLeft"
 import ChevronRight from "@material-ui/icons/ChevronRight"
 import FirstPage from "@material-ui/icons/FirstPage"
 import LastPage from "@material-ui/icons/LastPage"
 import Check from "@material-ui/icons/Check"
 import FilterList from "@material-ui/icons/FilterList"
 import Remove from "@material-ui/icons/Remove"

<MaterialTable
                 icons={{
                   Check: () => <Check />,
                   Export: () => <SaveAlt />,
                   Filter: () => <FilterList />,
                   FirstPage: () => <FirstPage />,
                   LastPage: () => <LastPage />,
                   NextPage: () => <ChevronRight />,
                   PreviousPage: () => <ChevronLeft />,
                   Search: () => <Search />,
                   ThirdStateCheck: () => <Remove />,
                   ViewColumn: () => <ViewColumn />,
                   DetailPanel: () => <ChevronRight />
                 }}
                 columns={[
                   {title: "Ad_", field: "name"},
                   {title: "Soyad_", field: "surname"},
                   {title: "Do_um Y_l_", field: "birthYear", type: "numeric"},
                   {
                     title: "Do_um Yeri",
                     field: "birthCity",
                     lookup: {34: "_stanbul", 63: "_anl_urfa"}
                   }
                 ]}
                 data={[
                   {
                     name: "Mehmet",
                     surname: "Baran",
                     birthYear: 1987,
                     birthCity: 63
                   }
                 ]}
                 title="Demo Title"
               />
````

Is there a way to determine which icons we need to import for any particular layout?

**Comment by mbrn** [comment]
Hi @pak11273 

use: `ResetSearch`

You can look at here to complete list of icons. 
https://mbrn.github.io/material-table/#/docz-props

**Comment by pak11273** [comment]
Got it.  Should I leave these type questions on Gitter or StackOverflow?

**Comment by mbrn** [comment]
I prefer stackoverflow or here. To someone else see them.

**Comment by mforman1** [comment]
> Hi @pak11273
> 
> use: `ResetSearch`
> 
> You can look at here to complete list of icons.
> https://mbrn.github.io/material-table/#/docz-props

@mbrn The link is break, where can I find the complete list of icons?

**Comment by rocketkittens** [comment]
For action props, providing a string failed, search and pagination icons were showing, had to return a react element to get action icons to display..
```
        actions={[
            {
                icon: () => <AddBox />,
                tooltip: 'Add User',
                isFreeAction: true,
                onClick: (event) => alert("You want to add a new row")
            }
        ]}
```

**Comment by Jyotiaggarwal235** [comment]
Hi,I am facing the same issue...my icons are not displaying on web although added the library

**Comment by Henao** [comment]
Thanks @rocketkittens "had to return a react element to get action icons to display.."

 icon: () => <AddBox />,  icon: () => <Edit />,  icon: () => <Delete />, 

this worked for me.

**Comment by yudyhendry** [comment]
> () => <AddBox />

if you put your icons definition on separate file then use (in my case I defined all the icons in tableIcons object store in another file like icons.config.js)

`actions={[
          {
            icon: () => <tableIcons.Email />,
            tooltip: 'Send Email Reminder',
            onClick: (event, rowData) => alert('You send ' + rowData.name),
          },`

**Comment by stehen77** [comment]
some material.io icon doesn't work, like admin_panel_settings icons
example in my menu
 {label: msg ('menu.admin.roles'), icon: 'admin_panel_settings', to: '/ roles', features: [ROLE]},
in Ultima reactJs

**Comment by bishaludas** [comment]
I had the issue of pagination icons not loading in Ui
![Screenshot from 2021-02-19 16-15-49](https://user-images.githubusercontent.com/24315018/108493049-fdfcd700-72cd-11eb-9ff3-ad9e25c94741.png)

Fixed this issue by adding a link tag for material icons in public>index.html
Now it looks okay.
![Screenshot from 2021-02-19 16-16-50](https://user-images.githubusercontent.com/24315018/108493204-297fc180-72ce-11eb-86fe-c32cd3397c57.png)
