### ISSUE TITLE
Can we change the position of pagination to center bottom?

### ISSUE THREAD

**Issue by iamsaurabhgupt** [mbrn/material-table#2131]
**Is your feature request related to a problem? Please describe.**
Pagination options in bottom right conflict with chat icon.

**Describe the solution you'd like**
Pagination options to be shifted elsewhere. We prefer centre bottom. You may add various options to choose from.

**Describe alternatives you've considered**
None

**Additional context**
screenshot attached
![image](https://user-images.githubusercontent.com/43205009/86518555-e7ddfb80-be4f-11ea-9e7f-4f4e10585dc8.png)

**Comment by priyanshu-intellemo** [comment]
I'd also prefer this customization here!!!

**Comment by iamsaurabhgupt** [comment]
Closing as it is duplicate of https://github.com/mbrn/material-table/issues/540

**Comment by elsachannn** [comment]
maybe you can try like this:

const useStyles = makeStyles((theme) => ({
    table: {
        "& tfoot tr td div:nth-child(1)": {
            justifyContent: 'center',
            flex: 'initial'
        }
    }
  }))

  components={{
       Pagination: props => (<TablePagination {...props} className={classes.table} />)
    }}

**Comment by iamsaurabhgupt** [comment]
Thanks @elsachannn .
Can you please show a demo on codesandbox?

**Comment by elsachannn** [comment]
> Thanks @elsachannn .
> Can you please show a demo on codesandbox?

I'm sorry to see your reply now.
I hope this can help you.
[codesandbox](https://codesandbox.io/s/new-worker-q4zvn)

**Comment by iamsaurabhgupt** [comment]
Great, thanks for the help @elsachannn
