### ISSUE TITLE
Exported csv is blank if all the data has been grouped by one or more headers

### ISSUE THREAD

**Issue by PankajMoolrajani** [mbrn/material-table#2132]
# Guidelines

- #### Please include a demo of the issue/behavior/question you have

- #### Please try to be as detailed as possible

- #### You may fork one of the following starter templates if you would like:

  - #### [CodeSandbox](https://codesandbox.io/s/material-table-starter-template-xnfpo)
  - #### [StackBlitz](https://stackblitz.com/edit/material-table-starter-template)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by n-wagner** [comment]
I am experiencing the same issue. I see an undocumented workaround from combing through the source. In "localization" using the keys "exportPDFName" and "exportCSVName" in place of "exportName" seems to work if you set them to strings with what you want displayed.
```
localization{{
  exportCSVName: "Export as CSV",
  exportPDFName: "Export as PDF"
}}
```

**Comment by PankajMoolrajani** [comment]
Thanks @n-wagner . I will check this option out too.
For now I switched to another library as this was one of the core feature I needed.
Closing the issue, but I think solution given by @n-wagner will be helpful for others.
