### ISSUE TITLE
Triggering Add Mode externally

### ISSUE THREAD

**Issue by avin-kavish** [mbrn/material-table#2133]
Is it possible to trigger a row add using a button that is external to the table?

**Comment by VLRTroll** [comment]
Actually it is! All you need is in the following piece of code ([StackBlitz](https://stackblitz.com/edit/usb66k-j2etm7?file=demo.js)):

```
const MyComponent() {
 //...
 const addActionRef = React.useRef();

  return (
    <>
        <button onClick={() => addActionRef.current.click()}>
            Add new item
        </button>

        <MaterialTable
            //...
            components={{
                Action: props => {
                      //If isn't the add action
                      if (typeof props.action === typeof Function || props.action.tooltip !== 'Add') {
                            return <MTableAction {...props} />
                      } else {
                            return <div ref={addActionRef} onClick={props.action.onClick}/>;
                      }
                    }
                }}
            editable={{
                onRowAdd: (newData, oldData) => Promise.resolve(); //your callback here
            }}
        />
    </>
  );
}
```

And you'll get something like this:
![add_action](https://user-images.githubusercontent.com/55628273/86835740-e9d3d480-c072-11ea-9859-332d4344bcae.gif)

**Comment by avin-kavish** [comment]
Hey! Thanks for putting the time in for a detailed answer :)

**Comment by zahraei1376** [comment]
How can this code be used for editing?

**Comment by rullymartanto** [comment]
I tried to use same function here but want to keep the onRowAdd,
I have follow the top method but doesn't work.

it possible to pass ref on material-table and trigger the action?
like ref.current.onRowAdd ?

![image](https://user-images.githubusercontent.com/5577057/223313969-b17c72ab-4f8d-48f1-a523-5571b5261c19.png)
