### ISSUE TITLE
NPM ISSUE

### ISSUE THREAD

**Issue by ashindiano** [mbrn/material-table#2137]
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -2
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/eligrey/FileSaver.js.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

- #### Please try to be as detailed as possible
npm install gives ssh error when tried to install  jspdf 1.5.3

**Describe the bug**
Enterprise Networks do not allow ssh. But material table uses jspdf 1.5.3 which uses github:eligrey/FileSaver.js#1.3.8
enterprise networks does not allow ssh to FileSaver

**To Reproduce**

npm install

**Expected behavior**

**Comment by ashindiano** [comment]
It was because ssh client was not installed in Docker. Wrong assessment on the issue. So closing it

**Comment by black-puppydog** [comment]
I just stumbled over this issue as well and frankly I don't see why an ssh-agent should be required to install publicly available packages. Is this something that could be solved by specifying the requirements differently?
