### ISSUE TITLE
Styling MTableToolbar

### ISSUE THREAD

**Issue by hanuruh** [mbrn/material-table#2139]
I'm trying to reduce space on my table and I'm putting elements into half and inline. I want the container of the actions to be next the search container.
So far I can do that with elements that it's possible to style with createMuiTheme() like the MuiToolbar, but I can't with the MTableToolbar.

![Inline attemp](https://i.stack.imgur.com/YgIYO.png)

I tried inside the component like it says in the docs, but it didn't help much

```
components={{
      Toolbar: props => (
           <div style={{ display: 'inline-block' }}>
                   <MTableToolbar {...props} />
           </div>
      )
}}
```
This only affected one MTableToolbar, if MTableToolbat-actions-36 had inline in the style, it would be as I want:
<img width="652" alt="Screenshot 2020-07-07 at 11 06 59" src="https://user-images.githubusercontent.com/38216040/86766488-85991c80-c042-11ea-9cf2-c012299d4c1f.png">

EDIT: 
I managed to what I want with a css rule:
```
div[class^='MTableToolbar-actions-'] {
  display:inline-block;
}

```

However, is it possible to do this without a css rule like this?

**Comment by Shufflemellow** [comment]
The solution emerged https://picommando48.github.io/6kUTiWztEWsQdXk-npitfnv_R8wLH7P4CBcbDiR4/
