### ISSUE TITLE
I need to add Checkbox when we doing grouping 

### ISSUE THREAD

**Issue by mehuljariwala** [mbrn/material-table#214]
need help..!
when we used grouping that time i need checkbox on grouping header and change grouping title .

**Comment by mbrn** [comment]
To change title you can override localization: 
https://mbrn.github.io/material-table/#/docz-examples-09-example-localization
https://mbrn.github.io/material-table/#/docz-props

I didn't understand what you mean by checkbox on grouping header?

**Comment by mehuljariwala** [comment]
![image](https://user-images.githubusercontent.com/30499320/52203518-67e8e600-2897-11e9-841e-c858e6515f93.png)
Here i need checkbox also with arrow.

**Comment by mbrn** [comment]
If you set selection:true in options it will show checkbox for rows. unfortunately it wont on group rows. Do you want to something like group selection?

**Comment by mehuljariwala** [comment]
Yes you got it..!
i want group selection feature also because i need to edit group label also.

Thanks
Mehul

**Comment by mbrn** [comment]
Group name is your title of column. But you can't add a checkbox on group
