### ISSUE TITLE
React does not recognize the `errorState` prop on a DOM element.

### ISSUE THREAD

**Issue by tanvir002700** [mbrn/material-table#2142]
After upgrading material-table version 1.54.0 to 1.64.0 it's showing this error: 
` **React does not recognize the `errorState` prop on a DOM element.**`

[
![Screenshot from 2020-07-08 12-05-54](https://user-images.githubusercontent.com/8723553/86883281-80f06900-c113-11ea-841f-356e755ac65f.png)
](url)

**Comment by OgenrwotAaron** [comment]
I changed all  "errorState" to lowercase i.e "errorstate" in the package's files and it works well...
This explanation might help fix the bug https://reactjs.org/warnings/unknown-prop.html

**Comment by KerimG** [comment]
@OgenrwotAaron 
Want to submit a PR?

**Comment by dan-hu-spring** [comment]
experiencing the same issue, had to downgrade to 1.54

**Comment by morwalz** [comment]
Any fix so for for this issue ??

**Comment by OgenrwotAaron** [comment]
> @OgenrwotAaron
> Want to submit a PR?

Yeah sure, lemme get to it

**Comment by mfmsajidh** [comment]
Same here.... After upgrading to 1.64.0
![image](https://user-images.githubusercontent.com/36571307/87033302-980e8400-c203-11ea-9e10-3500a686b2fe.png)

> index.js:1406 Warning: React does not recognize the `errorState` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `errorstate` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in td (created by ForwardRef(TableCell))
    in ForwardRef(TableCell) (created by WithStyles(ForwardRef(TableCell)))
    in WithStyles(ForwardRef(TableCell)) (created by MTableCell)
    in MTableCell (created by MTableBodyRow)
    in tr (created by ForwardRef(TableRow))
    in ForwardRef(TableRow) (created by WithStyles(ForwardRef(TableRow)))
    in WithStyles(ForwardRef(TableRow)) (created by MTableBodyRow)
    in MTableBodyRow (created by MTableBody)
    in tbody (created by ForwardRef(TableBody))
    in ForwardRef(TableBody) (created by WithStyles(ForwardRef(TableBody)))
    in WithStyles(ForwardRef(TableBody)) (created by MTableBody)
    in MTableBody (created by Droppable)
    in table (created by ForwardRef(Table))
    in ForwardRef(Table) (created by WithStyles(ForwardRef(Table)))
    in WithStyles(ForwardRef(Table)) (created by Droppable)
    in div (created by Droppable)
    in div (created by Droppable)
    in div (created by Droppable)
    in Droppable (created by ConnectFunction)
    in ConnectFunction
    in ConnectFunction (created by MaterialTable)
    in div
    in Unknown (created by WithStyles(Component))
    in WithStyles(Component) (created by MaterialTable)
    in div (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (created by Container)
    in Container (created by MaterialTable)
    in Provider (created by App)
    in App (created by ErrorBoundary)
    in ErrorBoundary (created by DragDropContext)
    in DragDropContext (created by MaterialTable)
    in MaterialTable
    in Unknown (created by WithStyles(Component))
    in WithStyles(Component) (at EmployeesView.jsx:92)
    in div (at EmployeesView.jsx:91)
    in div (at EmployeesView.jsx:40)
    in EmployeesView (at EmployeesController.js:260)
    in EmployeesController (at RouteWithLayout.js:13)
    in main (at Main.js:43)
    in div (at Main.js:31)
    in Main (at RouteWithLayout.js:12)
    in Route (at RouteWithLayout.js:9)
    in RouteWithLayout (at AuthRouteWithLayout.js:16)
    in Route (at AuthRouteWithLayout.js:12)
    in AuthRouteWithLayout (at Routes.js:36)
    in Switch (at Routes.js:30)
    in Router (at Routes.js:29)
    in Routes (at App.js:52)
    in SnackbarProvider (at App.js:41)
    in ThemeProvider (at App.js:40)
    in PersistGate (at App.js:39)
    in Provider (at App.js:38)
    in App (at src/index.js:8)

**Comment by bcanozter** [comment]
same issue here after upgrading to 1.64.0

**Comment by Domino987** [comment]
Yes its a mistake and the PR is already up #2144

**Comment by morwalz** [comment]
@Domino987 PR shows issues in prettier. Please resole those. Admin can you please merge the pr soon to solve this issue.

**Comment by Domino987** [comment]
@morwalz The prettier CLI is broken but we do not know why currently. These cannot be fixed from my site, but must be done by changing the actions.

**Comment by codeslator** [comment]
![image](https://user-images.githubusercontent.com/44347689/87165816-a955a000-c298-11ea-8adc-8ad752e13778.png)
I have the same problem, it appear today, yesterday I didn't have this bug.

**Comment by oxicot** [comment]
Same issue on my local env. with 1.64.0

Also here:
https://codesandbox.io/s/material-demo-6ovwo?file=/package.json

**Comment by Domino987** [comment]
Will be fixed with 1.65

**Comment by morwalz** [comment]
when cab we expect this version ?

**Comment by Domino987** [comment]
The release cycle is every Sunday so tomorrow

**Comment by JirasakRomsai** [comment]
npm i material-table
more than version1.64.0 No problem
I use npm i material-table@1.68.0

**Comment by MisaelMa** [comment]
> npm i material-table
> more than version1.64.0 No problem
> I use npm i material-table@1.68.0

this if it works
