### ISSUE TITLE
When selecting row programmatic header checkbox not changing as intermediate selection

### ISSUE THREAD

**Issue by mukesh-pathak-by** [mbrn/material-table#2147]
# Guidelines

- #### Please include a demo of the issue/behavior/question you have

- #### Please try to be as detailed as possible
When selecting row programmatic header checkbox not changing as intermediate selection. Please find the SS for details.

<img width="955" alt="mat-tables" src="https://user-images.githubusercontent.com/62742570/86920860-f2e2a580-c147-11ea-829d-5bb14139e8e1.PNG">

- #### You may fork one of the following starter templates if you would like:

  - #### [CodeSandbox](https://codesandbox.io/s/material-table-starter-template-xnfpo)
  - #### [StackBlitz](https://stackblitz.com/edit/material-table-starter-template)

**Comment by mukesh-pathak-by** [comment]
I think the problem here is with the re-render of material table. I am using remote data; When I performing row selection is by clicking on row, is there any way to re-render material table.
I don't want to call an API again i just want header checkbox to be checked while performing row selection.

Is there any way to solve this problem. Thanks in advance.

**Comment by Domino987** [comment]
Can you fork the sandbox and show us what you are doing? So we can see what happens?

**Comment by mukesh-pathak-by** [comment]
Please find the sandbox code. When i click on row the row get seleted but header checkbox doesn't change to intermediate check.

It's works fine when selection is done via selecting check box

https://codesandbox.io/s/material-table-selection-different-data-from-table-391iv

Regards,
Mukesh Pathak

**Comment by Domino987** [comment]
You pass the event correctly to the `onRowSelected` but the event is different from the event needed for the checkbox vs the row (ClickEvent vs ChangeEvent). So you need to modify the clickevent from the row to act like the ChangeEvent. You can to that by setting target.checked to true.
`event.target.checked = !rowData.tableData.checked;`
Now the whole function looks like this and it works:
```
onRowClick={(event, rowData) => {
       event.target.checked = !rowData.tableData.checked;
       this.tableRef.current.onRowSelected(
           event,
           [rowData.tableData.id],
            rowData
       );
}}
```
I will close this. Feel free to open it, if this does not work for you.
