### ISSUE TITLE
[Actions] Custom action overlapping with export button

### ISSUE THREAD

**Issue by waynegrigsby** [mbrn/material-table#2149]
I'm currently working on building in a custom Action into my material-table but can't quite get the styling right. Or rather, I'm curious if what I'm trying to do is possible without having to build my own custom Toolbar. 

The following code snippet (and sandbox) seem to work, however, the "Export" button overlaps my custom drop down action. Is there any way to get these two options to not overlap without building my own custom Toolbar? 

[CodeSandbox](https://codesandbox.io/s/stoic-mayer-p5rx0)

```
<CustomMaterialTable
  title='Data Comparison'
  columns={tableCols}
  data={tableDoneLoading ? tableData : ''}
  options={{
    exportButton: true,
    exportCsv: (columns, data) => { csvDownload(data, buildFileName(stateName)) },
    pageSize: tableData.length
  }}
  actions={[
    {
      icon: 'flip',
      isFreeAction: true,
      onClick: (event, rowData) => console.log('select')
    }
  ]}
  components={{
    Container: props => props.children,
    Action: props => {
      if (props.action.icon === 'flip') {
        return (
          <div style={{ margin: '10px' }}>
            <YearDropDown
              year={year}
              type='default'
              minWidth='full'
              variant='standard'
              label='none'
              required
            />
          </div>
        )
      }
    }
  }}
/>
```

**Comment by waynegrigsby** [comment]
I was able to get it to look decent by adding `margin: '10px 10px 10px 2px', display: 'inline-flex'`. But I'm curious if there is a better way to do this... And additionally, is there a way to reorder the action buttons.

**Comment by coderwith-zeroskills** [comment]
I want export functionality by clicking button outside the material table?
OR
I want to customize export icon to a button with some text?
Is any of the two possible?
