### ISSUE TITLE
About the lookup in the MaterialTable

### ISSUE THREAD

**Issue by wanghanting** [mbrn/material-table#2150]
# Guidelines

- #### Recently, I was using MaterialTable in my project, but I found a problem.

All the exemples online are using static data for the lookup, but I want to use dynamic data, is that possible?
For exemple, I get the namelist from the database and want to put it in the lookup content. Thanks for help.

- #### 
![image](https://user-images.githubusercontent.com/36294574/87033225-681dab80-c218-11ea-90c6-478782d2168f.png)

**Comment by Domino987** [comment]
You can simply update the columns prop when the data is updated: 
```
function SimpleAction({namelist}) {
  const columns = React.useMemo(() => ([
        { title: 'Name', field: 'name' },
        { title: 'Surname', field: 'surname' },
        { title: 'Birth Year', field: 'birthYear', type: 'numeric' },
        {
          title: 'Birth Place',
          field: 'birthCity',
          lookup: namelist,
        },
      ]), [namelist]);
  return (
    <MaterialTable
      title="Simple Action Preview"
      columns={columns }
      data={[
        { name: 'Mehmet', surname: 'Baran', birthYear: 1987, birthCity: 63 },
        { name: 'Zerya Betül', surname: 'Baran', birthYear: 2017, birthCity: 34 },
      ]}        
      actions={[
        {
          icon: 'save',
          tooltip: 'Save User',
          onClick: (event, rowData) => alert("You saved " + rowData.name)
        }
      ]}
    />
  )
}
```

If this answers your question, feel free to close this issue.

**Comment by wanghanting** [comment]
Thanks!
