### ISSUE TITLE
Grouping data by column with object as field property

### ISSUE THREAD

**Issue by mmarzantowicz** [mbrn/material-table#2152]
- #### Please include a demo of the issue/behavior/question you have

Given following set of data:
```
[
  {
    id: 1,
    word: "word1",
    nested: {
      prop1: "value1",
      prop2: "value2"
    }
  },
  {
    id: 2,
    word: "word2",
    nested: {
      prop1: "value3",
      prop2: "value4"
    }
  },
  {
    id: 3,
    word: "word1",
    nested: {
      prop1: "value1",
      prop2: "value2"
    }
  },
  {
    id: 4,
    word: "word4",
    nested: {
      prop1: "value3",
      prop2: "value4"
    }
  }
]
```
and column definition:
```
{
    title: "Nested",
    field: "nested",
    render: (rowData, renderType) =>
      renderType === "row"
        ? rowData.nested.prop1 + " " + rowData.nested.prop1
        : rowData.prop1 + " " + rowData.prop2
  }
```
grouping does not work as expected.

- #### Please try to be as detailed as possible

After dragging and dropping last column (Nested) on grouping area, there is only one group of data `value1 value2` instead of expected two: `value1 value2` and `value3 value4`.

Is there any way to achieve grouping for columns with custom data render applied based on nested object?

- #### Full code example:

  - #### [CodeSandbox](https://codesandbox.io/s/material-table-starter-template-ddugk)

**Comment by ozgurmuraterhan** [comment]
+1

**Comment by vizardkill** [comment]
+2

**Comment by vizardkill** [comment]
+3

**Comment by vizardkill** [comment]
+4

**Comment by vizardkill** [comment]
:/

**Comment by vizardkill** [comment]
sin novedades?

**Comment by GersonDias** [comment]
I also would love this feature as well. For now, I need to create a new field in my object called groupingString or whatever and stringify the content of my objects so I can use JSON.parse in customSort and render (when type === 'group') and use that stringified field as the column field.

Would be nice to have a customGroupBy maybe?
