### ISSUE TITLE
Export as  PDF Unicode issues

### ISSUE THREAD

**Issue by shaheeralimm** [mbrn/material-table#2154]
![image](https://user-images.githubusercontent.com/30893632/87155171-19cfe180-c2d8-11ea-903b-7c9b03ece10d.png)

When try to export the table content its not showing arabic text instead of these showing some unicode. please check the screenshot above.

**Comment by bturtu405** [comment]
I also have this problem

**Comment by seromenho** [comment]
This might be an issue with jspdf. Maybe you could check that if you use that text without material-table and only with jspdf if you have the issue?

**Comment by vbtux** [comment]
Could you please tell me how to solve this problem?

**Comment by AbubakrKamal** [comment]
I also have same problem
