### ISSUE TITLE
window is defined in next.js

### ISSUE THREAD

**Issue by sk1794** [mbrn/material-table#2155]
I am getting error **widow not defined** in next.js after updating to v1.64.0, its because of jspdf You have used

**Comment by TaffarelXavier** [comment]
I have same problem.

**Comment by floAr** [comment]
This is related to #2112 and there is a pull request open already, in case you want to pluck the fix for yourself #2114 . The problem is withing jsPDF and the trick is to only import it if there is a window defined (which is not the case during server side render)

**Comment by Domino987** [comment]
Closing in favor of #2112

**Comment by yashas123** [comment]
**Temporary fix is to use nextjs dynamic import:**
```js
import dynamic from "next/dynamic";

const MaterialTable = dynamic(() => import("material-table"), { ssr: false });
