### ISSUE TITLE
Change colour on particular action onClick 

### ISSUE THREAD

**Issue by tschaka1904** [mbrn/material-table#2156]
How can I style a particular MT action based on a different state? 

Currently I'm doing something like this: 
```
 actions={[
              rowData => {
                const active = rowData && selected && rowData.tableData.id === selected.tableData.id;
                return {
                  icon: 'bug_report',
                  iconProps: { color: active ? 'secondary' : 'primary' },
                  onClick: (event, info) => {
                    setSelected(info);
                  },
                };
              },
]}
```

But instead of colouring the single element, it just stays `primary` and basically does nothing. Why? Because the actions is rendered for action row and the next row `!==` selected.

**Comment by VLRTroll** [comment]
Hello, @tschaka1904!

I tried to figure out why 'iconProps' is not working in your example, but I failed :/. Probably we are missing something. Nevertheless, it's simple to solve your issue. You can set the icon props directly on the component as shown below.
(Code avaliable on [CodeSand Box](https://codesandbox.io/s/material-table-starter-template-jogki?file=/src/index.js:1243-1606))

```
actions={[
  rowData => {
    const active = rowData && selected && rowData.tableData.id === selected.tableData.id;
    return {
      icon: () => <AddBox color={active ? 'secondary' : 'primary'} />,
      onClick: (event, info) => {
        setSelected(info);
      },
    };
  },
]}
```

![action-color](https://user-images.githubusercontent.com/55628273/87230924-645d6680-c389-11ea-9d47-bb4e38ee87bd.gif)
