### ISSUE TITLE
Make headers draggable only when grouping is true

### ISSUE THREAD

**Issue by rfones** [mbrn/material-table#216]
**Describe the bug**
Table headers are draggable when grouping is false. The only reason I can find to have draggable headers is for grouping.

**To Reproduce**
1. Look at any of the (non-grouping) demos.
2. Hover over a header, notice the ability to drag the header.

**Expected behavior**
Dragging on headers does nothing.
Hover over headers with no cursor change.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 71.0.3578.98

**Additional context**
Also I see a grab cursor in addition to the default cursor. When I drag horizontally it seems to shift the other headers like it's going to change the order of the columns, but it does nothing.

**Comment by mbrn** [comment]
You are right @rfones ,

I will add columnReorder feature. When grouping and columnReordering are false , header could not be draggable. 

Thanks.

**Comment by mbrn** [comment]
This will be in v1.18.0

**Comment by TheWoodStudio** [comment]
Sorry, this is still happening. Has been any change that's not on the docs?

**Comment by sanichka96** [comment]
@TheWoodStudio try to add `draggable: false` to options of table
