### ISSUE TITLE
Hidden Column field does not get reported to onRowAdd

### ISSUE THREAD

**Issue by darewreck54** [mbrn/material-table#2160]
**Describe the bug**
I have a table that has a column in which i hid the column and have an initial value.  When the column hidden = true, the initial value will not appear in onRowAdd(newValue).  When i disabled the hidden, the value appears in newValue.  From my understanding functionality should not change whether it the column is hidden or not.

**To Reproduce**
In this example:

https://codesandbox.io/s/material-table-starter-template-9ojxr

In the example below surname is hidden but initialized with a value.  When you submit, the surname should still be saved.

![image](https://user-images.githubusercontent.com/16171726/87217138-1ac63a80-c2fb-11ea-9917-9ecdd213d7dd.png)

I printed it out in the console and i don't see surname eventhou it's initialize.

Now if i turn hidden = false, you will see the surname appear.

![image](https://user-images.githubusercontent.com/16171726/87217129-02562000-c2fb-11ea-9416-32d7f02fc6bc.png)

**Expected behavior**
I expect that the functionality stay the same whether hidden is false or true.

![image](https://user-images.githubusercontent.com/16171726/87217164-6d075b80-c2fb-11ea-9208-f627d6c911b6.png)

based on the notes, it should hide it not remove the file from being saved.

**Screenshots**
Shown above

**Desktop (please complete the following information):**

- OS: [e.g. iOS] macOS
- Browser [e.g. chrome, safari] chrome

**Comment by rkaartikeyan** [comment]
@darewreck54 have you got any solution for this?

Kindly share with me if yes. I am also facing same issue.

**Comment by eduardkuun-degsa** [comment]
@rkaartikeyan I have the same issue. Any luck?
