### ISSUE TITLE
Hide and appear actions

### ISSUE THREAD

**Issue by p9614** [mbrn/material-table#2161]
I have to add more columns and the actions are taking up a lot of space.
Try using the selection option to make them appear in the header but it doesn't fetch the data from the row Data and I need it.
Is there a way to fetch the data from each row with the selection option? or
Is there any other way to hide and show actions?

    <MaterialTable
      title="Users"
      columns={[
        { title: 'IdUser', field: 'IdUser', type: 'numeric', hidden: 'false' },
        { title: 'name', field: 'name' },
        { title: 'lastname', field: 'lastname' },
        { title: 'age', field: 'age', type: 'numeric' },
        { title: 'date', field: 'date'},
      ]}
      data={user.DataUser}       
      options={{
        selection: true
      }}
      actions={[
                     {
                        icon: () => <AddIcCall/>,
                        tooltip: 'call', 
                        onClick:(event, rowData)=>{
                           setShow4(true);
                           setData4(rowData);
                        }
                     },   
                     {
                        icon: () => <AirportShuttlee/>,
                        tooltip: 'bus', 
                        onClick:(event, rowData)=>{
                           setShow3(true);
                           setData3(rowData);
                        }
                     },           
                     {
                        icon: () => <AirplanemodeActive/>,
                        tooltip: 'Flight', 
                        onClick:(event, rowData)=>{
                           setShow2(true);
                           setData2(rowData);
                        }
                     },
                     {
                        icon: () => <AddAlarm/>,
                        tooltip: 'Alarm', 
                        onClick:(event, rowData)=>{
                           setShow1(true);
                           setData1(rowData);
                        }
                     },
      ]}
    />
  )
}

**Comment by Domino987** [comment]
Can you describe your use-case more? I do not exactly know, what you want to achieve.

**Comment by p9614** [comment]
@Domino987 My question is if there is some way to pass the rowData through the selection or if there is some way to hide and show the actions as well as with the detail panel

**Comment by Domino987** [comment]
You can return a function for the actions and only show it, if needed.
```
actions={[
        {
          icon: 'save',
          tooltip: 'Save User',
          onClick: (event, rowData) => alert("You saved " + rowData.name)
        },
        rowData => shouldDisplayAction ? ({
          icon: 'delete',
          tooltip: 'Delete User',
          onClick: (event, rowData) => confirm("You want to delete " + rowData.name),
          disabled: rowData.birthYear < 2000
        }) : undefined
      ]}
```

**Comment by p9614** [comment]
@Domino987  
I dont  understand what the function would be, but I understand that what it is going to do is that given the condition it will hide the action, but the actions that would not put a condition still take too much space, is there a way to hide all the actions and With a button or with the selection, show them again when the user requires them? It occurred to me to put them in the detail panel but I have seen comments that are not good practice

**Comment by VLRTroll** [comment]
@p9614, I don't know if you need to put this "Hide button" inside the table, but if it's not the case maybe I have a solution for you. Adding a toggle button outside the table we can hide/show the table actions as you wanna, but this will re-render the table every time.
```
const MyComponent = () => {
  const [hideActions, setHideActions] = useState(true);
  ...
  return (<>
     <FormControlLabel
        label="Show Table Actions"
        control={
          <Switch
            defaultChecked={!hideActions}
            onChange={() => setHideActions(!hideActions)}
          />
        }
      />

      <MaterialTable
        ...
        actions={ !hideActions && actionsArray }
      />
  </>);
}
```
The source code you can access on [SandCodeBox](https://codesandbox.io/s/material-table-starter-template-53g9n?file=/src/index.js). And the result is:

![switch_actions_demo](https://user-images.githubusercontent.com/55628273/87796135-57c08e80-c81f-11ea-9e3e-917718c288c9.gif)
