### ISSUE TITLE
PDF Export Fails with React Element Title

### ISSUE THREAD

**Issue by zacheryph** [mbrn/material-table#2163]
# Guidelines

https://codesandbox.io/s/material-table-starter-template-045ln

**Describe the bug**
`title` allows a `string or React Element`. When using a react element, the new cannot-disable undocumented `Export to PDF` feature fails.

**To Reproduce**
With table do `title={<SomeReactElement/>}` as well as `options={{ exportButton: true }}`

1. Go to https://codesandbox.io/s/material-table-starter-template-045ln
2. Click on _Export_ Icon
3. Click on _Export to PDF_

**Expected behavior**
_to work?_

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. iOS] MacOS
- Browser [e.g. chrome, safari] Chrome & Firefox
- Version [e.g. 22] Latest

**Additional context**
It'd be nice to be able to disable things like this instead of them being forced. And to have them documented on the site.

**Comment by Domino987** [comment]
This is not supported by [jsPDF](https://github.com/MrRio/jsPDF), which is used to generate the table pdf. If you need something like this, I would consider opening a PR to change the currently used library to a different one that works better.

**Comment by zacheryph** [comment]
I'd rather it be something I can decide to enable (or disable) of it's going to be broken by default.
