### ISSUE TITLE
A way to not include jspdf

### ISSUE THREAD

**Issue by niicojs** [mbrn/material-table#2168]
Jspdf is 30% of material-table bundle size.  
PDF export is a nice feature but it would be nice to avoid including this lib when export is not needed. It would greatly benefits bundle size.

I don't know if getting it tree-shaking compatible is possible or 2 versions are needed but it would be awesome 😁

**Comment by niicojs** [comment]
I've just noticed bundle size almost double recently with 1.63.

https://bundlephobia.com/result?p=material-table@1.64.0

**Comment by johnmagbag1995** [comment]
Having same problem #2164

**Comment by niicojs** [comment]
Correct you opened the issue between the time I searched for previous issues and the time I opened it 😅
