### ISSUE TITLE
Lookup feature is not working in the filtering section

### ISSUE THREAD

**Issue by shimaFeizzadeh** [mbrn/material-table#2170]
There is a problem with the “Lookup Feature” at top of the table which filters rows. I 've investigated the basic sample in the documentation in it’s not working either.

Check this:
https://material-table.com/#/docs/features/filtering
[](https://material-table.com/#/docs/features/filtering)

![Screen Shot 1399-04-24 at 11 43 22](https://user-images.githubusercontent.com/67860868/87395864-4715db80-c5c7-11ea-8cfa-285550a4d672.png)

I have lots of tables in my projects which lookup is an essential part of them. So, please check it and guide me to find some constructive solutions for it.

Many thanks.

**Comment by Domino987** [comment]
See #2173
