### ISSUE TITLE
How to use a regular expression mask on one column text field (on create and edit)

### ISSUE THREAD

**Issue by khypra** [mbrn/material-table#2172]
I have a Table of users where i got a text field where i need it to comply to certain especifications that is represented by a Regular Expression.
this is a sample that works on php:
                         ` ([0-9]{2}[\.]?[0-9]{3}[\.]?[0-9]{3}[\/]?[0-9]{4}[-]?[0-9]{2})|([0-9]{3}[\.]?[0-9]{3}[\.]?[0-9]{3}[-]?[0-9]{2})`
                      
do i have a props on the material-table where i can use the expression ? or do i need to use the editComponent prop, and if i need to do that, how do i do it as cleanly as possible?

this is the columns part of my table:
        
          columns={[
            { title: "id", field: "id", editable: "never" },
            { title: "Login", field: "login" },
            { title: "Nome", field: "name" },
            {
              title: "CPF",
              field: "cpf",                              // this is the field where i want to put an mask on
              type: "numeric",
            },
            { title: "E-mail", field: "email" },
            {
              title: "Orgão",
              field: "orgao_codigo",
              lookup: { ...this.state.lookup_orgaos },
              editComponent: (props) => (
                <Autocomplete
                  {...{
                    options: this.state.orgaos,
                    getOptionLabel: (option) => option.sigla,
                    getOptionSelected: (option) => props.value,
                  }}
                  id="orgao_codigo"
                  renderInput={(params) => {
                    return <TextField {...params} value={props.value} />;
                  }}
                  onChange={(event, option) => {
                    props.onChange(option.codigo);
                  }}
                />
              ),
            },
          ]}

**Comment by Domino987** [comment]
Check out the new validate prop of the columns. #1998

**Comment by khypra** [comment]
I did it! 
i utilized the MaskedInput from the Material-ui components, and with the props render and editComponent, i made it happen!
The mask is like this
`this.state = {
       ...
       ...
       ...
      mask: [
        /\d/,
        /\d/,
        /\d/,
        ".",
        /\d/,
        /\d/,
        /\d/,
        ".",
        /\d/,
        /\d/,
        /\d/,
        "-",
        /\d/,
        /\d/,
      ],
}`
The column object works like this

```
{
              title: "CPF",
               field: "cpf",
 
               render: (rowData) => (
                 <MaskedInput
                   value=  {rowData.cpf}
                   disabled= "true"
                   mask={this.state.mask}
                   showMask
                 />
               ),
               editComponent: (props) => (
                 <MaskedInput
                   value=  {props.value}
                   id="cpf"
                   mask={this.state.mask}
                   onChange={(event) => {
                     event.persist();
                     props.onChange(event.target.value);
                   }}
                 />
               ),
}
```
I had some issues when needed to remove the mask to pass as json but solved with this manpulation before sending:
```
normalizeCPF(cpf) {
    var cpfInt = parseInt(cpf.replace(/[^0-9]/g, ""));
    return cpfInt.toString();
  }
```

@Domino987  thanks for the tip! i actually need to use the validade prop for other reasons as well, so it was good knowing it exists in advance!
