### ISSUE TITLE
Add Favorite Icon & Functionality

### ISSUE THREAD

**Issue by j0nathanchuang** [mbrn/material-table#2175]
Is there any way to add a favorite row functionality to the table? I've been trying for days and this is what I am imagining:

![](https://user-images.githubusercontent.com/44914742/87475014-01223d00-c5f2-11ea-8173-8a47306aacd4.png)

Ideally, the user wouldn't need to click edit to toggle between favorite/unfavorite. Additionally, I want to be able to add the icon into the Action column itself, I am just creating a new column for the button right now.

This is how I am creating the favorite column:
```
...
import IconButton from '@material-ui/core/IconButton';
...
const [columns, setColumns] = useState([
    { title: '', field: 'fav', type: 'boolean', filtering: false,
      render: rowData => ( data[rowData.tableData.id].fav ?
        <IconButton><FavoriteIcon style={{color:'#3898ec'}} /></IconButton> :
        <IconButton><FavoriteBorder style={{color:'#3898ec'}} /></IconButton>
      ),
    },
...
const [data, setData] = useState([
    { date: '2000-11-19', fav: true, ...
    { date: '2010-1-9', fav: false,  ...
    { date: '2010-1-9', fav: false, ...
...
```

Right now, even when I edit the column to check true/false, the icon doesn't change between FavoriteIcon/FavoriteBorder - it only refers to my original 'fav' value in useState. 

I am a rookie react user, would love to know how to implement this correctly or if the team wants to add this feature it would be greatly appreciated!

**Comment by VLRTroll** [comment]
Hi, @j0nathanchuang! 
Happilly, your problem it's simple to solve.

To toggle between favorite/unfavorite icon without open edit mode, you can use the MaterialUI Checkbox component to do this behavior for you. And to include the icon inside the Actions column, you just need to add the "actions" property inti your MaterialTable component.

[Code in CodeSandbox](https://codesandbox.io/s/material-table-starter-template-wrqxm?file=/src/index.js)
```
    <MaterialTable
      ...
      actions={[
        rowData => ({
          tooltip: 'Favorite',
          icon: () => (
            <Checkbox
              color='default'
              defaultChecked={rowData.favorite}
              icon={<FavoriteBorderOutlinedIcon color="primary" />}
              checkedIcon={<FavoriteIcon color="primary" />}
              disableRipple
              style={{padding: 0}}
            />
          ),
          onClick: () => {
            rowData.favorite = !rowData.favorite;
          }
        })
      ]}
    />
```

![favorite_demo](https://user-images.githubusercontent.com/55628273/87588812-a7d21080-c6ba-11ea-9421-29c16e6affa0.gif)

**Comment by j0nathanchuang** [comment]
Incredible! Thank you @mbrn 

I have a new issue now, which is the state of the favorite icon is not saved when I click to the next page or sort the columns.

In other words, when I favorite a row and go on the next page then come back, the favorited row is no longer favorited. Do you know how I can fix this?

**Comment by VLRTroll** [comment]
This probabily it's happening because you're not persisting the data across the pages, so when you come back, the state of your data is restarted.

@j0nathanchuang, are you saving the changes in some place like Local Storage or database?

**Comment by j0nathanchuang** [comment]
@VLRTroll I am using local storage, this is how I am doing it:
```
...
const LOCAL_STORAGE_KEY = 'key;
...
//Load saved leads
  useEffect(() => {
    const storedLeads = JSON.parse(localStorage.getItem(LOCAL_STORAGE_KEY))
    if (storedLeads) setData(storedLeads)
  }, []);

  //Save our leads so when we refresh the page, it doesn't go away
  useEffect(() => {
    localStorage.setItem(LOCAL_STORAGE_KEY, JSON.stringify(data))
  }, [data]);
...
```

This saves the changes when I edit the table columns like the date or name, but not the favorite button state.

**Comment by VLRTroll** [comment]
@j0nathanchuang,  you can try something like this:

```
    <MaterialTable
      ...
      actions={[
        rowData => ({
          tooltip: 'Favorite',
          icon: ...,
          onClick: () => {
            rowData.favorite = !rowData.favorite;
            localStorage.setItem(LOCAL_STORAGE_KEY, JSON.stringify(data));
          }
        })
      ]}
    />
```
In the code above I keep the onClick callback implementation inside the "actions" just for example, but at this point I recommend you to exchange it for a function pointer like "handleFavoriteClick".
