### ISSUE TITLE
Error installing v 1.64.0 and up

### ISSUE THREAD

**Issue by andyvanhelsing** [mbrn/material-table#2178]
To reproduce:
npm install material-table@1.64.0

npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/eligrey/FileSaver.js.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

Not seen when installing v 1.63.0 and earlier

**Comment by stevestovold** [comment]
Also getting this issue

**Comment by batsauto** [comment]
This is related to Issue #2109 

Which was caused by this PR https://github.com/mbrn/material-table/pull/1970

**Comment by usahai** [comment]
Please resolve! Trying to update from 1.57.2 to get some new features but not able to upgrade!

**Comment by vmmelo** [comment]
Any workaround?

**Comment by batsauto** [comment]
in my package.json i made this edit
`"material-table": "1.62.0",`

**notice the removal of the ^** carrot. 

This is the last major version before using jsPDF that i know of.

**Comment by ZakKa89** [comment]
Thank you @batsauto , we were manually changing the package lock and that was becoming tedious

**Comment by chmelevskij** [comment]
When using meteor js and upgrading to `1.69.0` had following issue when running tests:
```
TypeError: Cannot assign to read only property 'then' of object '#<t>'
```
Downgrading back to:
```
"material-table": "1.62.0",
```
Solved the issue, leaving comment here for anyone else running into this cryptic issue with meteor

**Comment by DRsabadash** [comment]
For anyone stumbling across this, a workaround to be able to install v 1.64.0 or greater is to ensure you have git installed in your environment. 

if you're installing/running un-dockerized, just make sure git is in your PATH and accessible from the command line.
if you're installing/running dockerized, add the line RUN apk add --no-cache git to your Dockerfile before any npm commands.
