### ISSUE TITLE
Make columns with React elements sortable

### ISSUE THREAD

**Issue by robinzimmer1989** [mbrn/material-table#218]
Right now when I add a select box or a textfield (@material-ui/core) or any jsx into a cell, the column is not sortable anymore. Is there a way to add a string as a hidden, sortable value to the cell?

Example:

```
const columns = [
  {field: 'column1', title: 'Column 1'}, 
  {field: 'column2', title: 'Column 2'}
]

const data = [
  {
  column1: 'Field 1',
  column2: {
     sortable: 'String value of select box or textfield',
     element: <Select value='String value of select box or textfield' />
    },
  }

]

<MaterialTable
  columns={columns}
  data={data}
  title={'Title'}
/>
```

**Comment by mbrn** [comment]
You can.

Just add a `customSort: (a, b) => a.fieldX - b.fieldY` to your column definition. Additionally, you can add a `customFilterAndSearch` to add a search behaviour to your column.
