### ISSUE TITLE
Adding Custom Action Component  - The proper way

### ISSUE THREAD

**Issue by benedery** [mbrn/material-table#2186]
Hey,
I've wanted to add a custom component instead of the button you provide to add a row.

first i was only changing the icon property in the 
```              {
                       icon: () => <AddRowButton />,
                       tooltip: "Add Row",
                       isFreeAction: true,
                       onClick: (event, rowData) => handleDeleteRow(rowData),
                     },
```

BUT it causes a warning of validating DOM with button inside another button.

So I was able to resolve this warning by adjusting the components section
```
                  components={{
                    Action: (props) => {
                      if (props?.action?.tooltip === "Add Row") {
                        return <AddRowButton  />;
                      } else return <MTableAction {...props} />;
                    },
                  }}
```

BUT, Basing my solution on a tooltip looks strange,  
and maybe cause problems in production in the future.  
I want to know if there is a better/safer/cleaner way,  
Thanks.

**Comment by mbrn** [comment]
Hi @benedery 

Please take a look at second example at:

https://material-table.com/#/docs/features/component-overriding

**Comment by atinyakov** [comment]
It seems that @benedery asked about customizing "Add button" which is located in a **header**, not in a row. 
I have the same issue, and it seems that the reply above does not address this. @mbrn please assist.

**Comment by benedery** [comment]
@atinyakov iv'e already make a solution in https://github.com/mbrn/material-table/pull/2206, but they decided to declined, you can use it local if you want.
