### ISSUE TITLE
Adding rowStyle in material table always reset order direction to ascending

### ISSUE THREAD

**Issue by mukesh-pathak-by** [mbrn/material-table#2187]
# Guidelines

I am trying to use server side ordering but when i use rowStyle, the order direction returned by material table is always "asc" ascending
- #### Please include a demo of the issue/behavior/question you have

    rowStyle: (rowData) => ({
            backgroundColor: rowData.tableData.checked ? theme.palette.action.hover : '',
            pointerEvents: rowData.isDisabled ? 'none' : 'inherit'
          })

- #### Please try to be as detailed as possible

Please let me is there any way to resolve this issue.
- #### You may fork one of the following starter templates if you would like:

  - #### [CodeSandbox](https://codesandbox.io/s/material-table-starter-template-xnfpo)
  - #### [StackBlitz](https://stackblitz.com/edit/material-table-starter-template)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sandeepkumar-vedam-by** [comment]
Hi, We found issue in latest version that orderDirection is always returning 'asc' for remote data.

It is working fine with older versions 1.57.2. Related Issue [2177](https://github.com/mbrn/material-table/issues/2177)

@mbrn  @Domino987  Could you please confirm and fix the issue ?

FYI.. @mukesh-pathak-by  @gabriel-kohen-by
