### ISSUE TITLE
Duplicate details panel open state when rendering multiple tables 

### ISSUE THREAD

**Issue by elliotkennedy** [mbrn/material-table#2189]
**Descrption**

When rendering multiple tables, dropdown state seems to interact between the tables.

[See the demo here](https://stackblitz.com/edit/material-table-starter-template-v4tpne)

Possibly related to https://github.com/mbrn/material-table/issues/1971 (I do not receive the same warning, but it seems like a key clash)

In my project (`"material-table": "^1.65.0"`), I have 2 tables on separate components with the same data source, but different column layouts. One table has a dropdown and the other does not.

When I click the dropdown on the first table, then navigate to the second table. The corresponding row one the second table **is also dropped down**. Despite the second table not having a dropdown configured!

**I was unable to reproduce this exact behaviour in the sandbox**, but if you click the dropdowns on different tables, you can see they have an effect on each other's state.  

**To Reproduce**

1. Go to [the sandbox](https://stackblitz.com/edit/material-table-starter-template-v4tpne)
2. Scroll to the first table with a details panel dropdown
3. Click on the first row to open the details panel
4. Scroll down to the second table with dropdown
5. Click on the second row to open the details panel
6. See that both rows 1 + 2 open on the second table

**Expected behavior**
You would expect only the second panel to open on the second table.

**Screenshots**

**Desktop (please complete the following information):**

- OS: [Linux]
- Browser [Firefox (79.0b7)]
- Version ["material-table": "^1.65.0"] (also version 1.58.2 in sandbox)

**Comment by Domino987** [comment]
Material table mutates your data. This is a known problem. Since the shared data is mutated, all changes are reflected in every instances that access the same data => All tables show the same detail panels. Once this mutation problem is solved, this will not happen anymore.

In the meantime, copy your code shallowly to prevent the shared mutation, e.g data={[...data]}

**Comment by elliotkennedy** [comment]
Thanks again @Domino987 - as you mentioned offline, the correct shallow copy code is -

```
 data={data.map(d => ({...d}))}
```
