### ISSUE TITLE
Allow to add filter inputs in header

### ISSUE THREAD

**Issue by Ubax** [mbrn/material-table#2195]
**Is your feature request related to a problem? Please describe.**
I wanted to created a sticky filters, but it is not possible when the inputs are not in header. Right now it is only possible to have filters in table body

**Describe the solution you'd like**
The most user friendly solution would be adding a choice for a user to decide if they wanted filters to be placed as an additional row in table body or as inputs in header. It can be done by passing value 'header' into filtering prop.

**Describe alternatives you've considered**
The alternative is passing onFilterChanged to header, so while overriding header component one can use it to change filters values.

**Comment by ZakKa89** [comment]
This has been requested a couple of times now (see links belowe), I would also really like this feature.
At least I would want to be able to put the filterrow inside the header, so I can make it sticky. Making the header sticky already works great. 

https://github.com/mbrn/material-table/issues/780
https://github.com/mbrn/material-table/issues/1521

**Comment by suwigyarathore** [comment]
Eagerly waiting for this feature too

**Comment by carlosfunk** [comment]
Not stale
