### ISSUE TITLE
Not able to override 2 components at a time. Is it actually possible?

### ISSUE THREAD

**Issue by vijayasagarMantapudi** [mbrn/material-table#2196]
# Guidelines

- #### Please include a demo of the issue/behavior/question you have

- #### Please try to be as detailed as possible

- #### You may fork one of the following starter templates if you would like:

  - #### [CodeSandbox](https://codesandbox.io/s/material-table-starter-template-xnfpo)
  - #### [StackBlitz](https://stackblitz.com/edit/material-table-starter-template)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by VLRTroll** [comment]
@vijayasagarMantapudi, could you please explain a little bit more about your issue?

**Comment by vijayasagarMantapudi** [comment]
`<MaterialTable
    // other props
    components={{
        Header: props=> {return(
            // some table rows
          )
         },
        Action: props => (
          <Button
            onClick={(event) => props.action.onClick(event, props.data)}
            color="primary"
            variant="contained"
            style={{textTransform: 'none'}}
            size="small"
          >
            My Button
          </Button>
        )
    }}
/>`
