### ISSUE TITLE
How to apply styling to actionsCellStyle in edit mode? 

### ISSUE THREAD

**Issue by winicehui** [mbrn/material-table#2198]
I am wondering how to apply styling to the actions cells when the table is in edit mode? I am able to apply styling through the `actionsCellStyle` field under `options`, but the styling does not apply to the cells are in edit mode. 

For example: 

Specifically, I am trying to create a bordered table.

I have added `cellStyle = {border: '1px solid black'}` to each column object. This changes the cell style both in editing/ not in editing. 
`columns={[
                        {   title: 'Channels', 
                            field: 'channel', 
                            cellStyle: { border: '1px solid black', color: '#707070' }}
...]}`

I have also added
`options={{  
                    actionsCellStyle: { border: '1px solid black' }
 }}
`, to add border styling to the action cells. However, the border styling is applied only to the action cell styles when it is not in editing. 

![image](https://user-images.githubusercontent.com/35130094/87843021-bc9ed780-c865-11ea-8001-617c6397db53.png)

![image](https://user-images.githubusercontent.com/35130094/87844203-e2c97500-c86f-11ea-8694-5c187f17f06d.png)

Is there any way to apply the styling specified by the `actionsCellStyle`  field to the action cells in edit mode as well (this would seem more intuitive)? I have tried alternative methods to achieve my intended goal too by adding styling to the EditRow component, cellStyle etc. , but none of which worked. 

Or is there an option to add borders to the table, that I am just not seeing in the props/ documentation? 

Possibly related: [https://github.com/mbrn/material-table/issues/1136]
Thank you!

**Comment by VLRTroll** [comment]
@winicehui, I think this will solve your problem:
```
const useStyles = makeStyles({
  tableRow: {
    '& td': {
      border: '1px solid black !important',
    }
  }
});

const MyComponent = () => {
  const classes = useStyles();
  ...

  return (
    <MaterialTable
      ...
      options={{
        ...
        headerStyle: {
          border: '1px solid black'
        }
      }}
        components={{
          ...
          Row: props => <MTableBodyRow {...props} className={classes.tableRow} />,
          EditRow: props => <MTableEditRow {...props} className={classes.tableRow} />,
        }}
    />);
}
```
And this is enougth to create a bordered table. [CodeSandBox](https://codesandbox.io/s/material-table-starter-template-s95bo?file=/src/index.js)
![image](https://user-images.githubusercontent.com/55628273/87857048-089b5c00-c8fa-11ea-9a64-4931877b8c9a.png)
![image](https://user-images.githubusercontent.com/55628273/87857050-1224c400-c8fa-11ea-8159-46baf6d1c0a7.png)

**Comment by winicehui** [comment]
@VLRTroll  The solution you provided worked and is much simpler. Thank you!
