### ISSUE TITLE
Hide or remove the bottom border of last row

### ISSUE THREAD

**Issue by chaofan232** [mbrn/material-table#2200]
- #### Need to hide the bottom border.

    Hi, all. 

     Is there any style property I can use to hide or remove the table's bottom border only?

     I searched for a lot. But haven't found a right way to do it.

    Does anyone have any suggestions?
    Thanks in advance.

**Comment by VLRTroll** [comment]
@chaofan232, try this:
```
const useStyles = makeStyles({
  table: {
    "& tbody tr:last-child td": {
      border: 0
    }
  }
});

const MyComponent= () => {
  const classes = useStyles();
  ...

  return (
    <MaterialTable
      ...
      components={{
        Container: props => <Paper {...props} className={classes.table} />
      }}
    />
  );
};
```

**Comment by chaofan232** [comment]
@VLRTroll , thank you so much. This works perfectly.
