### ISSUE TITLE
Pagination shows only 2 or 3 pages at a time.

### ISSUE THREAD

**Issue by a-utkarsh** [mbrn/material-table#2201]
> [
![Screenshot from 2020-07-18 15-27-24](https://user-images.githubusercontent.com/29899695/87850132-78fea900-c90b-11ea-83cd-36c4ff099499.png)
](url)
As we can see, only three pages are visible(next page, previous page), not all the pages are included. I have to achieve something like this.
![Screenshot from 2020-07-18 15-30-54](https://user-images.githubusercontent.com/29899695/87850176-d266d800-c90b-11ea-90d3-d32c94d33497.png)

**Comment by johnmagbag1995** [comment]
Just simply use[ Component overriding](https://material-table.com/#/docs/features/custom-column-rendering) and [Material-UI's Pagination component](https://material-ui.com/components/pagination/)

**Comment by a-utkarsh** [comment]
I tried that way too but the problem is material ui pagination doesn't works that way, it needs the list of items to be rendered and then custom logic to implement the pagination. The logic for pagination I can write, but how will i get the items of the table as list. can you please provide some example regarding this, or is there any props just to show more page number.

**Comment by KVtofan** [comment]
Hello, could anybody please provide a worked example of custom Pagination component?
