### ISSUE TITLE
Spaces trimmed in cell

### ISSUE THREAD

**Issue by muj-programmer** [mbrn/material-table#2202]
How to prepend spaces in cell.

This does not work
```html
&nbsp; String content
```

**Comment by VLRTroll** [comment]
@muj-programmer, this blank space can be exchanged for a cell padding?

**Comment by muj-programmer** [comment]
> @muj-programmer, Can this blank space be exchanged for a cell padding?

Yes, this is my approach

```
cellStyle: (data, rowData) => ({
              border: "1px solid #e3e3e3",
              paddingLeft: `${rowData["level"] * 16}px`,
            }),
```

**Comment by muj-programmer** [comment]
I think this issue could closed now.
