### ISSUE TITLE
MaterialTable : Is there a way that the Row edit option is available only for checked rows?  Basically a Feature to edit multiple rows at once

### ISSUE THREAD

**Issue by Luckshmikamath** [mbrn/material-table#2203]
Is there a way that the Row edit option is available only for checked rows?  Basically a Feature to edit multiple rows at once

**Comment by thedmeyer** [comment]
@Luckshmikamath This has been requested multiple times before. Unfortunately still no update from the maintainers.

See: #331 #1865 #2025

**Comment by jeffsupancic** [comment]
I'm also looking for this feature.  @mbrn is this on the road map or anyway we can get it on there?
