### ISSUE TITLE
How can I create searchable lookup?

### ISSUE THREAD

**Issue by MrsSima** [mbrn/material-table#2209]
Hi!
Now I have a column with lookup
`{title: "Item", field: "item", lookup: items},`

But unfortunately this code provides ordinary dropdown. I have quite long list of items, so I need search function for dropdown. 
I tried custom rendering with something like 
`    {title: "Item", field: "item",

        editComponent: (tableData) => {
        return <Dropdown
                placeholder={"Select item"}
                onChange={(e, {value}) => {
                    if (typeof value === "string") {
                        tableData.rowData.item = {text: value, value: value};
                    }
                }}
                fluid
                search
                selection={tableData.rowData.item}
                text={tableData.rowData.item.text}
                options={items}
            />; } },`

But seems like I'm doing something wrong, and maybe there is much more pleasant way to get searchable lookup?

Thank you!

**Comment by papplaszlo0** [comment]
Hello!

Something similar was at my side as well. Have you set the field property in colunm definition? 

Regards,
Laszlo

**Comment by MrsSima** [comment]
It's this with lookup 
`export const customColumnHeadings: Column<customRowType>[] = [
    {title: "Name1", field: "name1"},
    {title: "Name2", field: "name2", lookup: Names2},
    {title: "Name3", field: "name3", lookup: Names3},
    {title: "Name4", field: "name4", lookup: Names4},
    {title: "Name5", field: "name5", lookup: Names5}
];`
And became like this after
`export const customColumnHeadings: Column<customRowType>[] = [
    {title: "Item1", field: "item1"},
    {title: "Item2", field: "item2", lookup: Items2},
    {title: "Item3", field: "item3", editComponent: (tableData) => {
    return <Dropdown
            placeholder={"Select item"}
            onChange={(e, {value}) => {
                if (typeof value === "string") {
                    tableData.rowData.item3 = {text: value, value: value};
                }
            }}
            fluid
            search
            selection={tableData.rowData.item3}
            text={tableData.rowData.item3.text}
            options={items}
        />; } },},
    {title: "Item4", field: "item4", lookup: Items4},
    {title: "Item5", field: "item5", lookup: Items5}
];`

I will share the error message a bit later:)
