### ISSUE TITLE
Items not unselecting after action

### ISSUE THREAD

**Issue by jakeleventhal** [mbrn/material-table#221]
**Describe the bug**
When using a table with selection, after doing the action, the rows remain checked.

**To Reproduce**
Use selection table, select, rows, click action.

**Expected behavior**
Action performs and rows are unchecked after

**Comment by mbrn** [comment]
I will take a return value to remove selections or not. So it will be optional.

**Comment by mbrn** [comment]
Hi @jakeleventhal ,

On next release you would be select or unselect all rows. Using tableRef

```javascript
<MaterialTable
                  tableRef={this.tableRef}
                  columns={this.state.columns}
                  data={this.state.data}
                  title="Demo Title"
                  options={{
                    selection: true
                  }}
                />

<button onClick={() => this.tableRef.current.onAllSelected(true)}>
              Select
            </button>
