### ISSUE TITLE
Is there a multi selector option?

### ISSUE THREAD

**Issue by iamsaurabhgupt** [mbrn/material-table#2215]
**Is your feature request related to a problem? Please describe.**
Some values in table have multiple options. So, while editing a row, editable table must provide the option of multiple selector.
e.g. in screenshot ([demo by Material Table](https://material-table.com/#/docs/features/editable)), we should be allowed to select both Istanbul and Şanlıurfa 
**Describe the solution you'd like**
Currently only single select is allowed on editing. We want multi select also.

**Describe alternatives you've considered**
Making a modal outside the table (not preferable)

**Additional context**

![image](https://user-images.githubusercontent.com/43205009/88091640-fb59c800-cbac-11ea-8811-c2d8f0a11048.png)

**Comment by riorinald** [comment]
use custom edit component 
for example added autocomplete component with option multiple
```
columns = [{
      title: 'Name', field: 'name',
      editComponent: props => (
        <Autocomplete
        multiple
        id="tags-standard"
        options={top100Films}
        getOptionLabel={(option) => option.title}
        defaultValue={[top100Films[13]]}
        renderInput={(params) => (
          <TextField
            {...params}
            variant="standard"
            label="Multiple values"
            placeholder="Favorites"
          />
        )}
      />
      )
    }]
```

**Comment by iamsaurabhgupt** [comment]
@riorinald thanks for your suggestion. 
would try to implement if this works.
