### ISSUE TITLE
 Is it possible to put the actions in the detail panel?

### ISSUE THREAD

**Issue by p9614** [mbrn/material-table#2217]
I am trying to put a button to open a dialog inside the detail panel.
The problem is that I need to pass the data of the row that selecting to the dialog, I am trying to send the rowData as it is done in the actions but they appear as undefined
Is there any other way to pass the rowData?

                  detailPanel={[{
                     icon: 'account_circle',
                     tooltip: 'Show Surname',
                     render: props=> {
                       return (
                      <IconButton aria-label="User"  >
                      <MenuBookIcon   onClick={(event, rowData)=>{
                        setRows(rowData);
                        setOpen(true);}
                     } />
                    </IconButton>

                       )
                     },
                   },
               
               ]}

**Comment by janderson215** [comment]
The `props` param in the render function is the `rowData`. You can retrieve any row data from that param.

**Comment by basefox** [comment]
> I am trying to put a button to open a dialog inside the detail panel.
> The problem is that I need to pass the data of the row that selecting to the dialog, I am trying to send the rowData as it is done in the actions but they appear as undefined
> Is there any other way to pass the rowData?
> 
> ```
>               detailPanel={[{
>                  icon: 'account_circle',
>                  tooltip: 'Show Surname',
>                  render: props=> {
>                    return (
>                   <IconButton aria-label="User"  >
>                   <MenuBookIcon   onClick={(event, rowData)=>{
>                     setRows(rowData);
>                     setOpen(true);}
>                  } />
>                 </IconButton>
> 
>                    )
>                  },
>                },
>            
>            ]}  
> ```


`
 detailPanel={[
                {
                  icon: 'account_circle',
                  render: rowData => {
                    console.log(rowData);
                    return (
                      <div>
                        <HandleCollapse id={rowData.Id} rowData={rowData} />
                      </div>
                    );
                  },
                  tooltip: 'Show Surname'
                }
              ]}
`
