### ISSUE TITLE
Table height not fix according rows

### ISSUE THREAD

**Issue by lamhungypl** [mbrn/material-table#2218]
My table scoll when datepicker show, i want it show as popper.
The height of the table should be fixed according to the number of rows

![Screen Recording 2020-07-22 at 12 19 04](https://user-images.githubusercontent.com/43105576/88137433-ba49ce00-cc15-11ea-8b0d-a7b7d230f4be.gif)

**Comment by lamhungypl** [comment]
`doubleHorizontalScroll` seems resolve this issue, but I still don't know how it work! .
```javascript
<MaterialTable
  {...other}
  options={{
  {...rest}
  doubleHorizontalScroll: true,
  }}
/>
```

**Comment by saurabhnemade** [comment]
You can also take a look at https://reactdatepicker.com/#example-configure-popper-properties
Popper can help auto position react-datepicker popover.
