### ISSUE TITLE
Is there a way to add custom Component on Add row feature?

### ISSUE THREAD

**Issue by pzapo** [mbrn/material-table#2219]
I want to have custom add (dropdown) component for one column when adding new row. I've found that i can change editComponent but i am unable to found information for something like add Component?

**Comment by VLRTroll** [comment]
Hi, @pzapo. In material-table, the same edit component is used on row add and on row update, so you can use editComponent do it.
```
const columns = [
  {
    title: "Type",
    field: "type",
    editComponent: props => (
      <DropDown
        value={props.value}
        onChange={e => {
          console.log(e.target.value);
          props.onChange(e.target.value);
        }}
      />
    )
  },
  { title: "Name", field: "name" }
];
```
```
const DropDown = ({ value, onChange }) => (
  <Select onChange={onChange} value={value || ""}>
    <MenuItem value="text">Text</MenuItem>
    <MenuItem value="number">Number</MenuItem>
    <MenuItem value="boolean">Boolean</MenuItem>
  </Select>
);
```

![dropdown_demo](https://user-images.githubusercontent.com/55628273/88207717-9642b880-cc26-11ea-85d7-f6970a363288.gif)

**Comment by pzapo** [comment]
Great! Thanks!
