### ISSUE TITLE
Add ability to delete rows

### ISSUE THREAD

**Issue by jakeleventhal** [mbrn/material-table#222]
**Is your feature request related to a problem? Please describe.**
There should be the ability to easily delete rows from an action since this is a common use case with selection

**Describe the solution you'd like**
After selecting rows, have an option to delete the rows via an action.

**Comment by mbrn** [comment]
Why you don't delete selected rows from  your state that you set as data to material-table?

**Comment by jakeleventhal** [comment]
i currently am doing that but it seems inefficient to use a filter on my state array

**Comment by shmoshkin** [comment]
have same problem

**Comment by Domino987** [comment]
Why not simply add a delete action and remove the item on click?
`actions={[
                        {
                            icon: () => <Delete color='action' />,
                            onClick: this.archiveOrder,
                            tooltip: localizedStrings.deleteOrder,
                        }
                    ]}`

**Comment by mbrn** [comment]
I am working on editable features: 

![image](https://user-images.githubusercontent.com/7895451/54109563-0ebd2680-43f0-11e9-88aa-a278d5b71c2c.png)

**Comment by mbrn** [comment]
You can delete rows with editable feature. You will provide a onRowDelete function to delete rows. 

https://mbrn.github.io/material-table/#/docz-examples-15-example-editable
