### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Steviebaa** [mbrn/material-table#2230]
**Error**: Uncaught (in promise) RangeError: Maximum call stack size exceeded

**Env**: create-react-app

**Cause**: 
- I fetch data from my api
- I pass the data to a functional component: TblComponent(data, moreData)
- I manipulate this data to create my rows and columns
- Return material-table with this data

- I have two Select components in the title of the table - currentValue and handleChange are passed down to TblComponent from stateful parent.
- Renders fine on first load
- Change one of the select components, new data comes in and console.log shows data is fine right before adding it to material-table component
- Something starts looping and I get the error above.

**Detailed Error**:
index.js:7 Uncaught RangeError: Maximum call stack size exceeded
    at equal (index.js:7)
    at equal (index.js:48)
    at equal (index.js:48)
**.........**
    at equal (index.js:48)
    at equal (index.js:48)
    at equal (index.js:48)
equal @ index.js:7
equal @ index.js:48
**.........**
equal @ index.js:48
equal @ index.js:48
Show 170 more frames
index.js:1 The above error occurred in the <MaterialTable> component:
    in MaterialTable
    in Unknown (created by WithStyles(Component))
    in WithStyles(Component) (at SectionsTable.js:52)
    in div (at SectionsTable.js:51)
    in SectionsTable (at Library.js:102)
    in div (created by ForwardRef(Container))
    in ForwardRef(Container) (created by WithStyles(ForwardRef(Container)))
    in WithStyles(ForwardRef(Container)) (at Library.js:97)
    in Library (at Layout.js:64)
    in div (at Layout.js:92)
    in SnackbarProvider (at Layout.js:77)
    in ThemeProvider (at Layout.js:76)
    in Layout (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in Route (at src/index.js:27)
    in Switch (at src/index.js:26)
    in Router (at src/index.js:25)
    in Provider (at src/index.js:24)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
console.<computed> @ index.js:1
logCapturedError @ react-dom.development.js:19527
logError @ react-dom.development.js:19564
update.callback @ react-dom.development.js:20708
callCallback @ react-dom.development.js:12490
commitUpdateQueue @ react-dom.development.js:12511
commitLifeCycles @ react-dom.development.js:19883
commitLayoutEffects @ react-dom.development.js:22803
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
commitRootImpl @ react-dom.development.js:22541
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
commitRoot @ react-dom.development.js:22381
finishSyncRender @ react-dom.development.js:21807
performSyncWorkOnRoot @ react-dom.development.js:21793
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
discreteUpdates$1 @ react-dom.development.js:21893
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
react-dom.development.js:11102 Uncaught RangeError: Maximum call stack size exceeded
    at equal (index.js:7)
    at equal (index.js:48)
    at equal (index.js:48)
**.........**
    at equal (index.js:48)
    at equal (index.js:48)
    at equal (index.js:48)
flushSyncCallbackQueueImpl @ react-dom.development.js:11102
flushSyncCallbackQueue @ react-dom.development.js:11072
discreteUpdates$1 @ react-dom.development.js:21893
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
index.js:1 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in Library (at Layout.js:64)
    in div (at Layout.js:92)
    in SnackbarProvider (at Layout.js:77)
    in ThemeProvider (at Layout.js:76)
    in Layout (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in Route (at src/index.js:27)
    in Switch (at src/index.js:26)
    in Router (at src/index.js:25)
    in Provider (at src/index.js:24)

**Comment by tarekgabarin** [comment]
I'm also having the same issue

**Comment by gauravagarwal2704** [comment]
Facing the same issue. Not able to identify what the problem is. I am using `material-table` inside Material-ui `Tab` component.
I am pretty sure it is not because of Tabs, because another table component got rendered, but not the one which is causing problem. I am not able to pin the problem. 
@tarekgabarin @Steviebaa  were you able to solve this ?
cc: @mbrn

**Comment by tarekgabarin** [comment]
I solved it by using a different library altogether. I just used
mui-datatables instead

**Comment by OnkelTem** [comment]
Same here. Started happening after upgrading. Not sure which version began to trigger that.

**Comment by OnkelTem** [comment]
Ok, I figured out the reason.

In the field declarations I had:
```
title: <Trans>FooBar</Trans>
```
where Trans is the component from **@lingui/macro**:

```
import { Trans, t } from '@lingui/macro';
```

When I replaced it with: 
```
title: i18n._(t`Date`),
```

it began to work.

The version is 1.69.2

**Comment by maxrikotero** [comment]
> ```js
> i18n
> ```
@OnkelTem Can i ask you if i18n is an external library ?

**Comment by OnkelTem** [comment]
@maxrikotero 

Sorry for the delay (since I've configured gmail filters I began to miss notifications!). Here is a list of i18n stuff from our **package.json**:

```
    "@lingui/react": "^2.8.3",
    "@lingui/cli": "^2.8.3",
    "@lingui/core": "^2.8.3sdfsdfsdf",
    "@lingui/macro": "^2.8.3",
```

**Comment by DCardenas** [comment]
I'm having this problem as well. The strange thing for me is that it only happens after I build. It works fine otherwise.

**Comment by DCardenas** [comment]
Just a quick follow up as I'm attempting to fix. My issue appears to be that I'm rendering two different tables with the same component that use dummy data fields. Passing through actual fields and just changing the render fixed the issue for me.

**Comment by upklio** [comment]
We were experiencing this issue when React Developer Tools was NOT installed. With it installed it weirdly works.
