### ISSUE TITLE
There is no clear button for input type 'text' in Mozilla Firefox

### ISSUE THREAD

**Issue by Ozea** [mbrn/material-table#2231]
# In Chrome it's visible, but in Firefox it's not

**Bug description**
Trying to find some information about that missing clear button in Mozilla Firefox I got this link https://developer.mozilla.org/en-US/docs/Archive/Web/CSS/::-ms-clear. Any thoughts about this issue? How can this clear button be implemented in Mozilla Firefox for input type "text" and "search"?

**Screenshots**

Chrome:

<img width="1404" alt="Screen Shot 2020-07-23 at 11 05 38 AM" src="https://user-images.githubusercontent.com/30413423/88264455-723db080-ccd4-11ea-8421-b8a2a4ef6556.png">

Mozilla Firefox:

<img width="1404" alt="Screen Shot 2020-07-23 at 11 10 31 AM" src="https://user-images.githubusercontent.com/30413423/88264835-217a8780-ccd5-11ea-8d6f-a255e2b8a3f5.png">

**Expected behavior**
Input value is removable by clicking on clear button

**Comment by ashishsantikari** [comment]
If you desperately need the clear button to exist, the easy way forward is to write a HOC which looks prop and if value equals true, place a clear icon on the right side(or wherever you want). Also, to have same effect on other browsers, remove the :ms-clear pseudo element.
