### ISSUE TITLE
Password value cleared when password visibility icon is clicked

### ISSUE THREAD

**Issue by pravinvarma** [mbrn/material-table#2232]
I have following item in the column array
```
  editComponent: props => (
                <TextField 
                    id="dummy_id"
                    type={this.state.showPassword ? 'text' : 'password'}
                    fullWidth
                    variant="outlined"
                    margin="dense"
                    value={props.value ? props.value : ""}
                    onChange={this.handleChange(props)}
                    InputProps={{
                        endAdornment: <InputAdornment position="end">
                            <IconButton
                            aria-label="toggle password visibility"
                            onClick={this.handleShowPassword}
                            >
                            {this.state.showPassword ? <Visibility /> : <VisibilityOff />}
                            </IconButton>
                        </InputAdornment>
                    }}/>
```
and handleShowPassword is
```
    handleShowPassword = () =>{
        this.setState({
            showPassword: !this.state.showPassword
        });
    }
```
when I add some text in password field and hit show password icon button(https://codesandbox.io/s/8106lm5n19), the value is cleared. It happens for the entire row fields.

**Expected behavior**
It should not clear the value from the prop. Attaching the video. I will try to create a demo link.

[Screen Recording 2020-07-23 at 6.01.08 PM.zip](https://github.com/mbrn/material-table/files/4965880/Screen.Recording.2020-07-23.at.6.01.08.PM.zip)

**Comment by pravinvarma** [comment]
the issue is due to the 
components={{
                            EditRow: props => <EditableRow mtProps={props} tableKey={"somekey"}/>
                        }}
closing the issue..thanks

**Comment by pravinvarma** [comment]
Apologies for the flip-flop..but with the above attribute, we should have value retained in the textField. Reopening after some research

**Comment by ashishsantikari** [comment]
@pravinvarma  First of all  setState method is asynchronous. The below code you pasted is indeterministic. `handleShowPassword = () =>{
        this.setState({
            showPassword: !this.state.showPassword
        });
    }`

The code should be `handleShowPassword = () => {
    this.setState(prevState => {
      showPassword: !prevState.showPassword;
    });
  };
`
