### ISSUE TITLE
Columns cannot be brought back after hiding

### ISSUE THREAD

**Issue by exuyilo** [mbrn/material-table#2237]
# Guidelines

- #### Demo
https://codesandbox.io/s/material-table-starter-template-e2mxt

**Describe the bug**
We use material-table in our application and are caching which columns are hidden so that we can restore that on a reload.
But since release 1.65.0 this does not work anymore, as apparent in the sandbox. The observed behavior is that the columns disappear completely and cannot be brought back.
Is there another way to get the desired behavior using the current version?

**Observed**
![image](https://user-images.githubusercontent.com/68732517/88388849-98874d00-cdb5-11ea-9e5c-68e79cea01b1.png)

**Expected**
![image](https://user-images.githubusercontent.com/68732517/88388903-b81e7580-cdb5-11ea-9e6e-9f60f9a576f2.png)

**Comment by sta2m** [comment]
Same problem here ... Any news ?
