### ISSUE TITLE
Warning: React does not recognize the `cellEditable` prop on a DOM element.

### ISSUE THREAD

**Issue by lfsando** [mbrn/material-table#2244]
``` javascript
<MaterialTable data={clients}  columns={[]} />
```
**Describe the bug**

There is something in the data that is triggering this error. 
I don't even need to set columns or any other prop.
I believe it didn't happen before the latest update
Happens after data is loaded.

<img width="837" alt="bug1" src="https://user-images.githubusercontent.com/10608706/88496376-4e5bc280-cf93-11ea-95fb-a626bac6e886.png">
<img width="1067" alt="bug2" src="https://user-images.githubusercontent.com/10608706/88496505-ad213c00-cf93-11ea-90e0-b9eac5b777bc.png">

- OS: Windows 10
- Browser Chrome
- Version 84.0.4147.89
- Typescript

**Comment by ZakKa89** [comment]
Encountering this warning as well.

**Comment by flora8984461** [comment]
Encountering the same issue. `Warning: Unknown event handler property `onCellEditFinished`. It will be ignored.`
`Warning: Unknown event handler property `onCellEditStarted`. It will be ignored.`

**Comment by mike-niemand** [comment]
Sadly 1.66 doesn't have cell editing. Nice component though.

**Comment by cnebs** [comment]
Encountering this also

**Comment by jakub-bao** [comment]
Having the same issue as well.

```
console.error node_modules/@testing-library/react/dist/act-compat.js:52
      Warning: React does not recognize the `cellEditable` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `celleditable` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
          in td (created by ForwardRef(TableCell))
          in ForwardRef(TableCell) (created by WithStyles(ForwardRef(TableCell)))
```

**Comment by Denis-Step** [comment]
`React does not recognize the `cellEditable` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `celleditable` instead. If you accidentally passed it from a parent component, remove it from the DOM element.`

Is this broken for a new React update? Such a shame

**Comment by kkirsche** [comment]
Also experiencing this issue, sadly.

**Comment by jaypalexa** [comment]
> Encountering this warning as well. Also 'onCellEditStarted' and 'onCellEditFinished'.
> 
> Going back tot 1.66 fixed it

I'm seeing this even in 1.66.0.  :-/

**Comment by Lav-Hinsu** [comment]
Still here in 1.66.0

**Comment by ridvanaltun** [comment]
I have the same issue on version 1.67.1

**Comment by hafeez-ullah-khan** [comment]
having 
1 Warning: Unknown event handler property `onCellEditStarted`. It will be ignored.
    in td (created by ForwardRef(TableCell)).
////////////////////////////////////
2 index.js:1 Warning: React does not recognize the `cellEditable` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `celleditable` instead. If you accidentally passed it from a parent component, remove it from the DOM element
/////////////////////////////
3 Warning: Unknown event handler property `onCellEditFinished`. It will be ignored.
    in tr (created by ForwardRef(TableRow))
/////////////////////////////////////////////

**Comment by orhanhub** [comment]
All! Bump up the version to 1.68.0.

If it is still there delete your node_modules and reinstall
make sure that you can see node_modules folder when you do ```ls```
then 
``` rm -rf node_modules
npm install```

this case can be remain closed

**Comment by matthewcoding0** [comment]
> All! Bump up the version to 1.68.0.
> 
> If it is still there delete your node_modules and reinstall
> make sure that you can see node_modules folder when you do `ls`
> then
> 
> ```
> rm -rf node_modules
> npm install
> ```
> 
> this case can be remain closed

Updating the version to 1.68.0 instead leads to another error:
```
Warning: Unknown event handler property `onBulkEditRowChanged`. It will be ignored.
    in tr (created by ForwardRef(TableRow))
    in ForwardRef(TableRow) (created by WithStyles(ForwardRef(TableRow)))
    in WithStyles(ForwardRef(TableRow)) (created by MTableEditRow)
    in MTableEditRow (at DailyReport.js:226)
    in EditRow (created by MTableBody)
    in tbody (created by ForwardRef(TableBody))
    in ForwardRef(TableBody) (created by WithStyles(ForwardRef(TableBody)))
    in WithStyles(ForwardRef(TableBody)) (created by MTableBody)
    in MTableBody (created by Droppable)
    in table (created by ForwardRef(Table))
    in ForwardRef(Table) (created by WithStyles(ForwardRef(Table)))
    in WithStyles(ForwardRef(Table)) (created by Droppable)
    in div (created by Droppable)
    in div (created by Droppable)
    in div (created by Droppable)
    in Droppable (created by ConnectFunction)
    in ConnectFunction
    in ConnectFunction (created by MaterialTable)
    in div
    in Unknown (created by WithStyles(Component))
    in WithStyles(Component) (created by MaterialTable)
    in div (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (created by Container)
    in Container (created by MaterialTable)
    in Provider (created by App)
    in App (created by ErrorBoundary)
    in ErrorBoundary (created by DragDropContext)
    in DragDropContext (created by MaterialTable)
    in MaterialTable
    in Unknown (created by WithStyles(Component))
    in WithStyles(Component) (at DailyReport.js:168)
    in DailyReport (at AdminPanel.js:189)
    in div (created by ForwardRef(DialogContent))
    in ForwardRef(DialogContent) (created by WithStyles(ForwardRef(DialogContent)))
    in WithStyles(ForwardRef(DialogContent)) (at AdminPanel.js:187)
    in div (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (created by ForwardRef(Dialog))
    in div (created by Transition)
    in Transition (created by ForwardRef(Fade))
    in ForwardRef(Fade) (created by Unstable_TrapFocus)
    in Unstable_TrapFocus (created by ForwardRef(Modal))
    in div (created by ForwardRef(Modal))
    in ForwardRef(Portal) (created by ForwardRef(Modal))
    in ForwardRef(Modal) (created by ForwardRef(Dialog))
    in ForwardRef(Dialog) (created by WithStyles(ForwardRef(Dialog)))```

**Comment by yerycs** [comment]
I tried to downgrade to v1.57.2 and it removed warning.

**Comment by Elvin2019** [comment]
v1.57.2  yes, it removes warning but now the issue is sorting remote data.

**Comment by piscespieces** [comment]
I've downgraded material-table like 3 times or more while working in a single project. That made the trick for me for a myriad of random errors. There are fixes to all of those errors (at least the most of them) but material-table haven't approved a single PR since a while by now.

**Comment by asaadawey** [comment]
same issue here

**Comment by RFNuma** [comment]
Lo unico que creo que podemos hacer frente a este problema es instalar una versión anterior.

**Comment by NadsonR** [comment]
Hey everyone, it seems the latest version _v1.69.2_ is working fine regards to this problem. I have updated here and I haven't got those errors anymore.

**Comment by DewangS** [comment]
well, I am using 1.67.0 and getting the same error\warning. @NadsonR  1.69.x has it's own problem of browser freezing so, be cautious not sure if you've encountered it so far as I had to downgrade it to 1.67.0 to get around the freezing issue.

**Comment by maviniciuus** [comment]
> well, I am using 1.67.0 and getting the same error\warning. @NadsonR 1.69.x has it's own problem of browser freezing so, be cautious not sure if you've encountered it so far as I had to downgrade it to 1.67.0 to get around the freezing issue.

Yeap, same here! 1.69.0 has memory leak every time has two tables at the same screen at render, or u change routes and go back to screen with the table, try do it 5 or 10 times!


> I tried to downgrade to v1.57.2 and it removed warning.
1.57.0 Remove alerts, no memory problem, but no export to PDF, right? Here it disappeared when I downgraded! :(

**Comment by ArcticTee** [comment]
Is #2275 related?

**Comment by Yashpk789987** [comment]
> Hey everyone, it seems the latest version _v1.69.2_ is working fine regards to this problem. I have updated here and I haven't got those errors anymore.

beaware of the browser freezing problem
