### ISSUE TITLE
Row editing with fixedColumns

### ISSUE THREAD

**Issue by viral-sh** [mbrn/material-table#2247]
**Describe the bug**

When we hit edit row with some fixed columns and edit cells (in a different container than action cell), clicking save action does not work. 

**Expected behaviour**
Edits should consistently work in fixed columns.

**Additional context**
Currently, edits are stored in local state in EditRow component Ref: [src/components/m-table-edit-row.js](https://github.com/mbrn/material-table/blob/73d4a47af5f8b8ef4ff3004d4983f6ff32a02cc1/src/components/m-table-edit-row.js#L145)

As in the case of fixed tables, we have 2-3 separate edit-rows (in each separate table), their local state is out of sync and saving by clicking on action or enter is not consistent.

Suggestion:
I think we should move edits from local state to an outer level. There are also some issues for bulk editing or controlled editing.
I know you are working on refactoring so not creating a PR for this. However, if you can guide me, I am happy to work on this and submit a PR :)

**Comment by rishhub-jain** [comment]
function Editable() {
  const { useState } = React;

  const [columns, setColumns] = useState([
    { title: 'Name', field: 'name' },
    { title: 'Surname', field: 'surname', initialEditValue: 'initial edit value' },
    { title: 'Birth Year', field: 'birthYear', type: 'numeric' },
    {
      title: 'Birth Place',
      field: 'birthCity',
      lookup: { 34: 'İstanbul', 63: 'Şanlıurfa' },
    },
  ]);

  const [data, setData] = useState([
    { name: 'Mehmet', surname: 'Baran', birthYear: 1987, birthCity: 63 },
    { name: 'Zerya Betül', surname: 'Baran', birthYear: 2017, birthCity: 34 },
  ]);

    return (
      <MaterialTable
        title="Basic Fixed Columns Preview"
        columns={[
          { title: 'Name', field: 'name', width: 150 },
          { title: 'Name', field: 'name', width: 150 },
          { title: 'Name', field: 'name', width: 150 },
          { title: 'Name', field: 'name', width: 150 },
          { title: 'Name', field: 'name', width: 150 },
          { title: 'Name', field: 'name', width: 150 },
          { title: 'Name', field: 'name', width: 150 },
          { title: 'Name', field: 'name', width: 150 },
          { title: 'Name', field: 'name', width: 150 },
          { title: 'Name', field: 'name', width: 150 },
          { title: 'Name', field: 'name', width: 150 },
          { title: 'Name', field: 'name', width: 150 },
          
          { title: 'Name', field: 'name', width: 150 },
          { title: 'Name', field: 'name', width: 150 },
          { title: 'Name', field: 'name', width: 150 },
          { title: 'Surname', field: 'surname', width: 150 },
          { title: 'Birth Year', field: 'birthYear', type: 'numeric', width: 150 },
          {
            title: 'Birth Place',
            field: 'birthCity',
            lookup: { 34: 'İstanbul', 63: 'Şanlıurfa' },
            width: 150
          },
          
        ]}
        data={data}        
        editable={{
        onRowAdd: newData =>
          new Promise((resolve, reject) => {
            setTimeout(() => {
              setData([...data, newData]);
              
              resolve();
            }, 1000)
          }),
        onRowUpdate: (newData, oldData) =>
          new Promise((resolve, reject) => {
            setTimeout(() => {
              const dataUpdate = [...data];
              const index = oldData.tableData.id;
              dataUpdate[index] = newData;
              setData([...dataUpdate]);

              resolve();
            }, 1000)
          }),
        onRowDelete: oldData =>
          new Promise((resolve, reject) => {
            setTimeout(() => {
              const dataDelete = [...data];
              const index = oldData.tableData.id;
              dataDelete.splice(index, 1);
              setData([...dataDelete]);
              
              resolve()
            }, 1000)
          }),
      }}
        options={{
     
          actionsColumnIndex: -1,
          searchFieldStyle: { display: "none" },
          fixedColumns: {
            left:0,
            right: -1
          },
          columnResizable: true 
        }}
      />
    )
  }


check this code out, when action button is on fixColumn the edit doesn't works
