### ISSUE TITLE
Changing the header background color,  font size and font color

### ISSUE THREAD

**Issue by cybermizrach** [mbrn/material-table#225]
How can I change the header background color,  font size and font color?

**Comment by mbrn** [comment]
Add a header style on your column definition that you want to style: 
{ title: '...', field: '...', headerStyle: {backgroundColor: 'red'}}

If you want to apply a style to all columns just add a header style to options.

**Comment by cybermizrach** [comment]
Thanks! It works when adding the headerstyle per column. 

I want to apply the style to all columns. It seems not working.

`<MaterialTable
  columns={[
    {
      title: 'Name',
      render: rowData => rowData.name + ' ' + rowData.surname,
    },
    { title: 'Birth Year', field: 'birthYear', type: 'numeric' },
    {
      title: 'Birth Place',
      field: 'birthCity',
      lookup: { 34: 'İstanbul', 63: 'Şanlıurfa' },
    },
    {
      title: 'Score',
      field: 'successScore',
      render: rowData => {
        const score = rowData.successScore + '%'
        const color = rowData.successScore > 70 ? '#4CAF50' : '#f44336'
        return (
          <div style={{ width: '100%', backgroundColor: '#ddd', height: 20 }}>
            <div
              style={{
                textAlign: 'left',
                padding: 1,
                color: 'white',
                width: score,
                backgroundColor: color,
                height: 20,
              }}
            >
              {score}
            </div>
          </div>
        )
      },
    },
  ]}
  data={[
    {
      name: 'Mehmet',
      surname: 'Baran',
      birthYear: 1987,
      birthCity: 63,
      successScore: 58,
    },
    {
      name: 'Zerya Betül',
      surname: 'Baran',
      birthYear: 2017,
      birthCity: 34,
      successScore: 90,
    },
  ]}
  title="Custom Render"
  headerStyle={{backgroundcolor:'red'}}
/>`

**Comment by mbrn** [comment]
Use this:
```javascript
<MaterialTable
...
options={{
headerStyle:{backgroundcolor:'red'}
}}
/>
```

**Comment by cybermizrach** [comment]
Thanks @mbrn!

**Comment by betocolon23** [comment]
Hi, do you know how to change the title of the table? 
<MaterialTable
title={this.props.title}
/>

**Comment by Pragadeeshwaranj** [comment]
Hi, how to change the color of the icon?

**Comment by MaykonMorais** [comment]
Hi @mbrn, how i can change the background of the table?

**Comment by vrajpal-jhala** [comment]
> Hi, do you know how to change the color of the title of the table?

Hi @betocolon23, 
I did it using MuiThemeProvider to override default styling, as MuiTypography-h6 component is being used for the table title.
```
const theme = createMuiTheme({
  overrides: {
    MuiTypography: {
      h6: {
        fontWeight: 'bolder !important',
        color: darken('#5CDB94', 0.15),
      },
    },
  },
});

<ThemeProvider theme={theme}>
  <MaterialTable
    ...
  />
</ThemeProvider>
```

**Comment by betocolon23** [comment]
Great!! Thanks

**Comment by alexanderkho** [comment]
Is there anyway to access MUI theme colors (I want to set color="primary") inside the headerStyle prop? Or would I have to use a custom override for this?

**Comment by alexanderkho** [comment]
Is there anyway to access MUI theme palette colors directly in the headerStyle prop? I want to set color="primary". Would I need a custom override for this?

**Comment by asifkabani** [comment]
@alexanderkho here is how I did it:

```
import { makeStyles, useTheme } from "@material-ui/core/styles";
const theme = useTheme()

<MaterialTable
          headerStyle: {
            width: 26,
            whiteSpace: 'nowrap',
            textAlign: 'left',
            flexDirection: 'row',
            overflow: 'hidden',
            textOverflow: 'ellipsis',
            paddingLeft: 5,
            paddingRight: 5,
            backgroundColor: theme.palette.primary.table,
            fontWeight: 'bold',
            color: theme.palette.primary.main,
          },
/>
```

**Comment by MehbubRashid** [comment]
How to change the style of action column header?

**Comment by Saikrishna-Muppa-TA** [comment]
> Use this:
> 
> ```js
> <MaterialTable
> ...
> options={{
> headerStyle:{backgroundColor:'red'}
> }}
> />
> ```

How to add different color for even rows in MaterialTable
