### ISSUE TITLE
Sorting by column is lost when data is updated

### ISSUE THREAD

**Issue by bertrandp** [mbrn/material-table#2252]
**Describe the bug**
Updating the data of a table resets any sorting.

**To Reproduce**

1. Go to https://stackblitz.com/edit/react-9qzndg
2. Sort a column
3. Click 'Get API data'
4. Observe the column losing its sorting

**Expected behavior**
I want the table to keep the sorting when updating the data.

**Additional context**
I think this behaviour was introduce at version 1.62.0 with this [commit](https://github.com/mbrn/material-table/commit/9803a245e334f615687545f31cef2b40dc85c124)

**Comment by GordonSmith** [comment]
FYI I see the same thing but with a simple resize event...

**Comment by flora8984461** [comment]
Same issue here. Wondering if there is any update on this issue? Thank you!

**Comment by yoavz** [comment]
I'm also having this problem, +1

**Comment by JasonLunsford** [comment]
Definitely seeing this issue too. Running material-table v1.68.0. ANY updates that cause a component render (like updating state via useState hook) will trigger this defect.

**Comment by ablontech** [comment]
Same issue with v1.68.1

**Comment by andreaschiappacasse** [comment]
I also see this problem, especially annoying since it makes using sorting and selecting at the same time not usable when using state to track selection changes.

**Comment by CarterScadden** [comment]
Also having this problem

**Comment by bertrandp** [comment]
@mbrn what are your thoughts on this issue ?

**Comment by gtupak** [comment]
Hey guys I fixed this by using a workaround. Long story short, what I did was:
1. Save the `tableRef` of the `MaterialTable` component
2. Right before you update the data, check the `tableRef.current.state`. If the default sorting changed, save the `orderBy` and `orderDirection` values to a local ref.
3. Also if the default sorting changed, pass these values to the parent component via a callback. The parent should then update the columns array that it passes to the component containing the MaterialTable component, with the new sorting values. By updating I mean updating the state of the columns. For this, you will need to save the columns to the component's state.

I hope this helps anyone. I know it might be a bit confusing but I'll let you with this for now. Maybe I find some time to put an example together somewhere.

**Comment by diamondfish** [comment]
I also have this issue, it's very annoying. Downgrading until this is fixed. Hope to see a fix soon.

**Comment by Drast10** [comment]
> Hey guys I fixed this by using a workaround. Long story short, what I did was:
> 
> 1. Save the `tableRef` of the `MaterialTable` component
> 2. Right before you update the data, check the `tableRef.current.state`. If the default sorting changed, save the `orderBy` and `orderDirection` values to a local ref.
> 3. Also if the default sorting changed, pass these values to the parent component via a callback. The parent should then update the columns array that it passes to the component containing the MaterialTable component, with the new sorting values. By updating I mean updating the state of the columns. For this, you will need to save the columns to the component's state.
> 
> I hope this helps anyone. I know it might be a bit confusing but I'll let you with this for now. Maybe I find some time to put an example together somewhere.

@gtupak , do you have any example for it

**Comment by imnasnainaec** [comment]
This issue was resolved when we switched to `@material-table/core` (a maintained fork of `material-table`):
https://www.npmjs.com/package/@material-table/core
https://github.com/material-table-core/core

**Comment by bertrandp** [comment]
This issue is still open

**Comment by davidroman-hub** [comment]
@bertrandp  use this: npm i @material-table/core and change in your component with this instead
 ` import MaterialTable from '@material-table/core'; `
  for me it works!

**Comment by vishaltambe70** [comment]
npm i @material-table/core
and change in your component with this instead
import MaterialTable from '@material-table/core';
it really  works!

**Comment by neillindberg** [comment]
> This issue was resolved when we switched to `@material-table/core` (a maintained fork of `material-table`): https://www.npmjs.com/package/@material-table/core https://github.com/material-table-core/core

When was this? What release please? I've a forked branch of this project from awhile back and it doesn't seem to use `@material-table/core`. I'm seeing both loss of filters on remote data usage and loss of sort, or reset to original column sort, on bulk edit checkbox check when setting my selected list onSelectionChange.

**Comment by bloodykheeng** [comment]
issue is still happening in 2024 i used material table core am using this version "@material-table/core": "^6.2.3", 
on first reload it doesnt happen but when i trigger global state and i try to  use any table action eg column filtering  or show or hide  columns the table just resets

**Comment by imnasnainaec** [comment]
@bloodykheeng If you have an issue with `@material-table/core`, you should post it in https://github.com/material-table-core/core/issues rather than here.
