### ISSUE TITLE
Translate 'Export as CSV' or 'Export as PDF' 

### ISSUE THREAD

**Issue by erikasoares** [mbrn/material-table#2253]
I'm trying to translate the export button phrase using the Localization feature as showing in the picture but the 'toolbar.exportName' doesn't translate the phrase and there is not an option to translate the pdf's phrase, only de csv's phrase.
![localization](https://user-images.githubusercontent.com/6515315/88848757-484a2980-d1bf-11ea-8586-022c5e8c9f9f.PNG)
![localization2](https://user-images.githubusercontent.com/6515315/88848768-4c764700-d1bf-11ea-802e-75719c6be729.PNG)

**Comment by jpbulbulian** [comment]
These are the new localization labels.
Since the new _Export as PDF_ feature it's available the docs wasn't updated.

```
  localization: {
    addRemoveColumns: "Add or remove columns",
    nRowsSelected: "{0} row(s) selected",
    showColumnsTitle: "Show Columns",
    showColumnsAriaLabel: "Show Columns",
    exportTitle: "Export",
    exportAriaLabel: "Export",
    exportCSVName: "Export as CSV",
    exportPDFName: "Export as PDF",
    searchTooltip: "Search",
    searchPlaceholder: "Search",
    searchAriaLabel: "Search",
    clearSearchAriaLabel: "Clear Search"
  },
```

**Comment by erikasoares** [comment]
It worked. Thanks!
