### ISSUE TITLE
Custom Table Pagination Action

### ISSUE THREAD

**Issue by cybermizrach** [mbrn/material-table#226]
Hi,

Can I use the something similar to the Custom Table Pagination Action  in https://material-ui.com/demos/tables/? If so, how? 

I'm using Firestore so I won't download all records but 1 page at a time. I want to get the next or previous page from Firestore when I clicked the Next or Previous button.

Also, can I only display the  Next or Previous buttons.

Thanks!

**Comment by vijthang61** [comment]
Yes you an override the default pagination component and achieve it with server side calls for pagination

**Comment by cybermizrach** [comment]
Thanks @vijthang61!

Is there any guide or example how to do it? Should I use the overriding components?

**Comment by mbrn** [comment]
@cybermizrach 

https://mbrn.github.io/material-table/#/docz-examples-10-example-component-overriding

**Comment by y3sh** [comment]
@mbrn link is broken, maybe somewhere here? https://material-table.com/#/docs/features/component-overriding

**Comment by mikehellman** [comment]
@mbrn The link you posted is broken. If you could please repost the link or update the documentation that would be greatly appreciated.
