### ISSUE TITLE
Columns CustomValue

### ISSUE THREAD

**Issue by xStorm111** [mbrn/material-table#2266]
# Guidelines
Hello,
- #### Please include a demo of the issue/behavior/question you have
I'm trying to migrate my project from Mui-Datatable (https://github.com/diaver/mui-datatables/) to material-table, and i ran into a problem that would be much easier if you have a function like his library called CustomValue (customBodyRender equals to your Render)
![image](https://user-images.githubusercontent.com/22938156/89166688-4d69f880-d572-11ea-9d22-b2e02583c82f.png)

- #### Please try to be as detailed as possible

So, i'm trying define my value to Filter/Search with your function customFilterAndSearch, but this requires to many code (in my opinion) just to define that my custom Value to Filter is not what Render is showing.
On the next images give you the difference between both libraries
![image](https://user-images.githubusercontent.com/22938156/89167045-cf5a2180-d572-11ea-83d3-8fe81f412db8.png)
![image](https://user-images.githubusercontent.com/22938156/89167113-e6990f00-d572-11ea-99ef-d59fab16530d.png)

Your function works ok in this case, but everytime i want a custom Value to filter i need to create a custom algorithm? I just want to point that my custom value is a string. 

- #### You may fork one of the following starter templates if you would like:
https://codesandbox.io/s/lp8pvk1zk9

**Is your feature request related to a problem? Please describe.**
Currently no

**Describe the solution you'd like**
Create a function like CustomValue.
example:
{
title: 'test'
field: 'test'
render: {something... like a component}
customValue: (rowData) => rowData.test
}

**Comment by e-hop** [comment]
+
