### ISSUE TITLE
How to edit action icons style??

### ISSUE THREAD

**Issue by Mizan-Rifat** [mbrn/material-table#2267]
How to edit action icons style??
I tried:
```
cellEditable={{
        cellStyle: {fontSize:'20px'},
}}
```
But it doesn’t work....

**Comment by timkomip** [comment]
I am having this issue too. I am trying to remove bottom dashed border from the editable fields. I think the issue is here:

https://github.com/mbrn/material-table/blob/master/src/components/m-table-cell.js#L171-L187
