### ISSUE TITLE
Save action triggered with invalid data on Enter key pressed

### ISSUE THREAD

**Issue by mrjdavidfg** [mbrn/material-table#2270]
**Describe the bug**
On Editable feature, if some column has the  `validate` property and you focus on some input and press Enter, the save action is triggered (`onRowAdd`, `onRowUpdate`) even if the row has invalid data.

**To Reproduce**
1. Go to https://codesandbox.io/s/cranky-morse-eo9gf
2. Click on "Add" row icon.
3. Click on some input.
4. Press 'Enter' key.
5. The row was added with empty (invalid) data.

**Expected behavior**
Pressing enter should not trigger save action with invalid data.

**Comment by jscotty723** [comment]
Having this same issue. Is there a way to work around or fix this?

**Comment by awesomeToan** [comment]
Any update on it ?

**Comment by alpcoker** [comment]
I have a [PR proposal](https://github.com/mbrn/material-table/pull/2440) that fixes that bug.  If it is that urgent, you may checkout my [branch ](https://github.com/alpcoker/material-table/tree/hotfix/validate-on-enter) and build your own version with my code. @mrjdavidfg @jscotty723 @awesomeToan 

@mbrn do you have time to review my PR ?

**Comment by JuddAO19** [comment]
Any update on this?

**Comment by Ashwarrior** [comment]
I'm having the same issue. Any update on this??

**Comment by GustafFig** [comment]
I am having the same issue. Some update on this?

**Comment by Vishal0612** [comment]
Any update on this issue pls help
