### ISSUE TITLE
Loose div causing unwanted overflow

### ISSUE THREAD

**Issue by gregorioospina** [mbrn/material-table#2272]
Hi! Ive been using material table within a Material-UI Dialog and there is a loose div within the table body which is causing an y,x overflow. I want to make this overflow: "hidden", however there is no way to access the div. Here is my code and a screenshot of the element inspection of the table.
![image](https://user-images.githubusercontent.com/33071558/89298825-74383580-d62b-11ea-88c8-c6073ca7a3c2.png)
![image](https://user-images.githubusercontent.com/33071558/89299041-c37e6600-d62b-11ea-88da-1d31d340298f.png)

I am not sure how to access those divs or remove them since they have no id or classname, and it is not evident where they are placed in the code, plus they seem to be wrapping with no other style the table so I see no real use for them.

**Comment by evrii** [comment]
@gregorioospina did you end up figuring this out?
