### ISSUE TITLE
How Can I add one more option to the ToolBar

### ISSUE THREAD

**Issue by Prasad-YS** [mbrn/material-table#228]
I want to add my own custom CSV export to toolbar, anyway to achieve this ? Please help me if it is feasible

**Comment by mbrn** [comment]
1. Currently you can do with workaround. Copy toolbar code and change what you want. Then override toolbar component with yours'.

2. Add a actions which has `isFreeAction: true` property. You can export your data in onClick of this button.

**Comment by Prasad-YS** [comment]
Thanks @mbrn , Thanks for your quick response, I'm working on your suggestion

**Comment by xStorm111** [comment]
Hello @mbrn, can you give an example, i'm trying to implement a refresh button to refresh only the table data and i can't keep the default toolbar options and add that icon at the same time.

I'm trying with following code:
![image](https://user-images.githubusercontent.com/22938156/72162688-5323a500-33ba-11ea-93a5-5f26f02b31c6.png)
