### ISSUE TITLE
align not available within columns in typescript

### ISSUE THREAD

**Issue by kayotimoteo** [mbrn/material-table#2280]
Using the latest version, I am not able to insert the align inside the collumn.
`
const columns = [
    {
      title: 'Tipo',
      field: 'tipo',
      align: 'center',
      cellStyle: {
        backgroundColor: '#039be5',
        color: '#FFF'
      },
      headerStyle: {
        backgroundColor: '#039be5'
      }
    },
  ]
`

**Comment by allupaku** [comment]
were you able to fix this ?
