### ISSUE TITLE
How to detect a click on Edit or Delete button

### ISSUE THREAD

**Issue by darinayordanova-itsoft** [mbrn/material-table#2282]
Hey 

I can't find a way to change my context when the row id in edit or delete mode.

I have this now:
![p1](https://user-images.githubusercontent.com/63228753/89415024-f875e000-d733-11ea-8362-a1006ea9b8ef.PNG)

Where the validation of the button NEXT is saved in the context state

I want to be able to achieve this(&same for the delete confirmation):
![p2](https://user-images.githubusercontent.com/63228753/89415289-53a7d280-d734-11ea-9624-2b740cd32880.PNG)

Thanks a lot in advance :)

**Comment by ivan-angelov** [comment]
I have the same problem

**Comment by raghav848** [comment]
hi @darinayordanova-itsoft , can you please tell me how you able to add style and custom text to add button they provided ?
