### ISSUE TITLE
Warning: Unknown event handler property `onBulkEditRowChanged`. It will be ignored.

### ISSUE THREAD

**Issue by felipe-gustavo** [mbrn/material-table#2284]
**Demo**
  - #### [CodeSandbox](https://codesandbox.io/s/inspiring-einstein-n7jb3?file=/src/App.js:579-590)

**Describe the bug**
When i try delete any row, the warning "Warning: Unknown event handler property `onBulkEditRowChanged`. It will be ignored" is showded:

**To Reproduce**

1. Delete a row from table;

**Screenshots**
![image](https://user-images.githubusercontent.com/55498940/89430704-66f77580-d715-11ea-9147-4dbf905ff366.png)

**Desktop:**

- OS: Windows
- Browser: chrome
- Material-Table Version: 1.68.0

**Aditional:**
This doesn't hinder normal functioning, is only ocd :)

**Comment by GiovanniCapizzi** [comment]
same

**Comment by felipe-gustavo** [comment]
Now, I can't add a new row, when i try, i get me this error:
![image](https://user-images.githubusercontent.com/55498940/89449697-d4b09b00-d72f-11ea-821c-dd5745b04ab0.png)

To reproduce, just add a new row.

**Comment by kkirsche** [comment]
Also seeing this issue

**Comment by methawutfield** [comment]
Downgrade to v1.67.1 this work for me.

**Comment by KellyVillalobos** [comment]
Downgrading also worked for me. Looks like an issue with the latest release. The same problem happens on their doc site as well.

**Comment by b3ni** [comment]
+1

**Comment by Domino987** [comment]
It was renamed to `onBulkEditRowChanged`. So please use this moving formward.

**Comment by Fyvel** [comment]
Hi, I'm not sure why the issue has been closed  
as you can see in the sandbox example, `onBulkEditRowChanged` isn't called

**Comment by kkirsche** [comment]
It is by their own code though. Such as in https://github.com/mbrn/material-table/blob/master/src/components/m-table-body.js

**Comment by Dev00114** [comment]
![Annotation 2020-08-29 181519](https://user-images.githubusercontent.com/64122930/91652600-cbaba480-ea23-11ea-839b-d6d1dd596549.jpg)
I think this error is by the this.props set.

**Comment by nuvenn** [comment]
Downgrade to v1.66.0 has worked for me.

**Comment by ankursehdev** [comment]
Any resolutions for this? I am still seeing this on 1.68.0 and future releases too

**Comment by adeelibr** [comment]
Any update on this issue?

**Comment by kkirsche** [comment]
I haven’t had issues with https://github.com/material-table-core/core
