### ISSUE TITLE
Actions Column does not show when selection is true

### ISSUE THREAD

**Issue by Nipodemos** [mbrn/material-table#2285]
Hello!

**Describe the bug**
It is quite simple actually. I want a table that has a selection in begginng, and a actions for edit and delete in the end os the columns. However, when I set the option `selection: true`, the actions column simply disappear, nowhere to be found.

**To Reproduce**

1. Open this codesandbox: https://codesandbox.io/s/material-table-starter-template-3ri1j?file=/src/index.js
1. Open the codesanbox link that is on beggining of this issue
2. Note that the actions column is showing normally when the selection is off
3. Look for a commented code that activates selection
4. Uncomment the code and see that actions disappear and selection appear

**Expected behavior**
Both columns to show at the same time, and actions column respect the columnIndex property in case it is set

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Chrome
- Version 84.0.4147.105 64 bits

**Additional context**
I have tried to set `actionsColumnIndex: -1` as per documentation, but it has no effect. Try to put 1 or 2 in the value, still no effect

**Comment by atosh502** [comment]
@Nipodemos Please look into comments [this](https://github.com/mbrn/material-table/issues/676#issuecomment-629342351) and [this](https://github.com/mbrn/material-table/issues/676#issuecomment-623953859). Issue #676

**Comment by Nipodemos** [comment]
@atosh502 thanks you very much for the clarification
