### ISSUE TITLE
install error when run  yarn add command 

### ISSUE THREAD

**Issue by sytpb** [mbrn/material-table#2287]
error An unexpected error occurred: "https://raw.githubusercontent.com/eligrey/FileSaver.js/e865e37af9f9947ddcced76b549e27dc45c1cb2e/package.json: getaddrinfo ENOENT raw.githubusercontent.com".

is that an issue ?

**Comment by ZakKa89** [comment]
Yes please check this thread 
https://github.com/mbrn/material-table/issues/2178

**Comment by ZakKa89** [comment]
reverting back to 1.62 seems to work for me

**Comment by terada46** [comment]
Same issue for me when using terminal in Visual Studio Code. 
Solved it by running the command in iTerm2.
