### ISSUE TITLE
onSearchChange is not a function

### ISSUE THREAD

**Issue by Nolandos** [mbrn/material-table#2294]
Hi ,

I using in my app **onSearchChange**. Suddenly my app is broken, and i have error: 
**onSearchChange is not a function**. Moreover when i console tableRef I see that onSearchChange is disappeared. I fix them, when i change onSearchChange on onSearchChangeDebounce. What happened with onSearchChange ?

**Comment by jinman** [comment]
+1 We are also having the same issue. We are using tableRef to select the search query as shown here [Sandbox](https://codesandbox.io/s/reset-search-from-outside-material-table-b6ssj?file=/src/table.js) but now it fails. Any workarounds?

**Comment by Nolandos** [comment]
@jinman of what i remember function have other name (maybe onSearchChangeDebounce), console.log table ref and check this. You can downgrade your material-table version, and you will have old name.

**Comment by ZeeshanTamboli** [comment]
Yes method is now changed to `onSearchChangeDebounce` as can be seen in the code: https://github.com/mbrn/material-table/search?q=onSearchChangeDebounce&type=code.
