### ISSUE TITLE
if no data show default message

### ISSUE THREAD

**Issue by redimongo** [mbrn/material-table#2295]
trying to get a default message to show if no data is returned.

`https://codesandbox.io/s/condescending-perlman-04wm8?file=/src/Table.jsx:3773-3786`

I am wondering what is the correct way to do this?

**Comment by redimongo** [comment]
We have a solution but would love a better way to do it.

https://stackoverflow.com/questions/63311224/material-table-if-no-data-show-message/63311533?noredirect=1#comment111953152_63311533

**Comment by atosh502** [comment]
If no data is passed and you want to render a default <b>string</b> you can use `body.emptyDataSourceMessage` option in `localization` prop. I think in order to display a custom component you have to override the `MTableBody` component for now.
