### ISSUE TITLE
Is there a way to show a message in the table when the table is empty? 

### ISSUE THREAD

**Issue by chriswalz** [mbrn/material-table#2298]
# Guidelines

- #### Please include a demo of the issue/behavior/question you have

E.g. https://images.app.goo.gl/wShyLD4sGiNRpVff8

- #### Please try to be as detailed as possible

- #### You may fork one of the following starter templates if you would like:

  - #### [CodeSandbox](https://codesandbox.io/s/material-table-starter-template-xnfpo)
  - #### [StackBlitz](https://stackblitz.com/edit/material-table-starter-template)

**Comment by atosh502** [comment]
There is a `body.emptyDataSourceMessage` option in `localization` prop with default value of  `No records to display` shown whenever the `data` is empty.

**Comment by lamhungypl** [comment]
@atosh502 , how to hide empty row, i `set emptyDataSourceMessage = ''` but it doesn't work. i don't want render any row if empty data

**Comment by atosh502** [comment]
@lamhungypl If you don't want to render the rows you can disable empty rows by setting `emptyRowsWhenPaging` option to `false` or you can just override the `Body` component of material-table and return `null` if there's no data. Here's an [example](https://codesandbox.io/s/material-table-starter-template-03pp6?file=/src/index.js).
