### ISSUE TITLE
No edit icon on bulk edit

### ISSUE THREAD

**Issue by Mizan-Rifat** [mbrn/material-table#2299]
there is no edit icon in bulk editing.i tried with documentation code it's still not working...

**Comment by atosh502** [comment]
Here's the [code sandbox](https://codesandbox.io/s/gifted-visvesvaraya-gvszk?file=/public/index.html) for the documentation [code](https://material-table.com/#/docs/features/editable) you mentioned. As you can see I was able to get the `Edit` icon for bulk edit. Maybe a reproducible demo of your problem would be nice.

**Comment by Mizan-Rifat** [comment]
@atosh502  well i had v1.67.1. now i've updated to new version.and it's working..thanks
