### ISSUE TITLE
detailPanelColumnStyle applies style to <div> instead of the <td>  

### ISSUE THREAD

**Issue by VJC-CDev** [mbrn/material-table#2301]
Hello,

First of all thank you all for the hard work with on this package.

I've been trying to use the new detailPanelColumnStyle but noticed that if you don't use a function for the detailpanel the styling is not applied to the **td** but to the **div** inside the **td**

File: m-table-body-row.js
Function: renderDetailPanelColumn
Line 197~204:

` } else {
      return (
        <TableCell size={size} padding="none" key="key-detail-panel-column">
          <div
            style={{
              width: 42 * this.props.detailPanel.length,
              textAlign: "center",
              display: "flex",
              ...this.props.options.detailPanelColumnStyle,
            }}`
 
I was trying to use the detailPanelColumnStyle option to limit the width of the column but due to this code i am unable too :(
Or does someone have a different method?

Thank you in advance

**Comment by cuongqle** [comment]
Yes, i am having same this issue. Panel column at the moment rendered wider than expected
![image](https://user-images.githubusercontent.com/7144697/93403628-455fe100-f8b2-11ea-9f7c-049392627d0f.png)
