### ISSUE TITLE
Grouping is not accessible

### ISSUE THREAD

**Issue by bigianb** [mbrn/material-table#2303]
The group functionality is not accessible because it cannot be used without dragging a mouse. Is there an option that can be set to allow users to enable grouping via the keyboard?

**Comment by harithaandem** [comment]
I am working on grouping, I found that grouping is not working via the keyboard. I am passing defaultGroupOrder as 0 from the parent component for one of the column headers. When it is rendering for the first time it is working. But when the parent component changes the defaultgroupOrder and passes it to the MaterialTable,  it is not applying any changes. 

My requirement is, based on the selection of column header in a dropdown the grouping should happen. I am passing the defaultGroupOrder as 0 for the selected header in the dropdown. But the MaterialTable is not re-rendering.

Can anyone help me with this?

Thanks in Advance

**Comment by georgeiliadis91** [comment]
So the only way to group data is by implementing it with drag n drop? I am trying to see if it is possible to do it another way.

**Comment by bigianb** [comment]
> So the only way to group data is by implementing it with drag n drop? I am trying to see if it is possible to do it another way.

You can use the keyboard but it’s not documented ... a screen reader reads instructions on how. You use space to initiate and then arrow keys.
