### ISSUE TITLE
customSort doesn't work.

### ISSUE THREAD

**Issue by dgoldie** [mbrn/material-table#2307]
I must be doing something actively stupid.
my customSort param is totally ignored.
there's no error.
with or without a render param.

Is there some other option I need to set?

thanks for any help.

this is in chrome on a mac.

basic table with a field in column data:
 {
    field: 'aasm_state',
    title: 'Stage',
    customSort: (a, b) => alert(a),
    // customSort: (a, b) => console.log('custom sort', a, b),
    // render: rowData => <p>{displayStage(rowData)}</p>
  },

and options:
<MaterialTable
        columns={columns}
        data={displayDraws}
        options={{
          search: false,
          showTitle: false,
          sorting: true
        }}
...

**Comment by zipzapp** [comment]
by the snippet of code you pasted, it looks like you still need to define the customSort function 
`customSort: (a, b) => alert(a)`

If you are sorting strings or numbers, you can use `(a, b) => a - b`

**Comment by mvelebit** [comment]
@zipzapp Shouldn't the alert get fired anyways? I'm experiencing the exact same issue, tried downgrading from 1.69, still doesn't work on 1.67.1 :/ 
My code snippet's basically the same, I have defined it as: 
```
customSort: (x, z) => {
        console.log('blabla fired', x)
        return x - z
      },
```

Nothing happens when I hit the sort arrow.
