### ISSUE TITLE
Detail panels doesn't work on 2nd page and so on.

### ISSUE THREAD

**Issue by DmitryVitd** [mbrn/material-table#231]
When you are going to the second page and so on, all detail panels triggers for first page, instead of the current one

You could go to the 2nd page, click to expand panel on 1st row, for example, then go back to page 1 and 1st row will be expanded on the 1st page, instead of 2nd.

**Comment by mbrn** [comment]
You are right @DmitryVitd ,

I resolve it in code. I will publish a new release today or tomorrow.

**Comment by mbrn** [comment]
This will be in v1.18.0

**Comment by exp0nge** [comment]
@mbrn I think it's broken again on 1.36.1

**Comment by mbrn** [comment]
I will take a look at it.

**Comment by mbrn** [comment]
@exp0nge 

I tested it with both normal and remote data and it works. Can you check it again?

**Comment by exp0nge** [comment]
@mbrn can you post your examples? More than one page

**Comment by mbrn** [comment]
Look at first example at https://material-table.com/#/docs/features/remote-data:

- I added just this to table: detailPanel={rowData => rowData.first_name}

![image](https://user-images.githubusercontent.com/7895451/57903382-72dbeb00-7876-11e9-899e-0411e6c2a019.png)
