### ISSUE TITLE
Add group selection

### ISSUE THREAD

**Issue by luislinietsky** [mbrn/material-table#2314]
# Guidelines

Great library. I am using it a lot. Could it be possible while using both selection and grouping, to add a selection box before the name of each group, to select all group elements?

Thanks!

**Comment by ollyrowe** [comment]
Hi @luislinietsky, I've had a go at implementing this and I've come up with a working prototype. I've added a screenshot below, feel free to provide any feedback. I'll likely submit a pull request for this soon, however, I'm not sure they'll accept it as they have requested for people to not make pull requests with many changes.

![group selection](https://user-images.githubusercontent.com/46567570/90672559-33a50280-e24e-11ea-8a9b-d483a9b8224b.PNG)

**Comment by luislinietsky** [comment]
> Hi @luislinietsky, I've had a go at implementing this and I've come up with a working prototype. I've added a screenshot below, feel free to provide any feedback. I'll likely submit a pull request for this soon, however, I'm not sure they'll accept it as they have requested for people to not make pull requests with many changes.
> 
> ![group selection](https://user-images.githubusercontent.com/46567570/90672559-33a50280-e24e-11ea-8a9b-d483a9b8224b.PNG)
@ollyrowe That looks great! I hope the pull request is approved !
