### ISSUE TITLE
Migration to 1.68.0 seems to break my code

### ISSUE THREAD

**Issue by mindaugasnakrosis** [mbrn/material-table#2315]
**Describe the bug**

After migrating my version from `1.67.0` to `1.68.0` my code seems to break while.
No errors on `1.67.0` version with the same code.
**To Reproduce**

1. Click on create new record.
2. Start typing text to one of the column inputs.
3. Code instantly crashes with errors:

```
in MTableEditRow (created by MTableBody)
in tbody (created by ForwardRef(TableBody))
```

```
in ErrorBoundary (created by DragDropContext)
in DragDropContext (created by MaterialTable)
in MaterialTable
```
**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/14983636/90114341-42c21700-dd5b-11ea-9263-54a31ff14862.png)
![image](https://user-images.githubusercontent.com/14983636/90114374-4d7cac00-dd5b-11ea-912f-40a3a331e78e.png)

**Comment by mindaugasnakrosis** [comment]
Maybe it has something to do with changed on 1.68.0 to `src/components/m-table-body.js` **dateTimePickerLocalization** in:

https://github.com/mbrn/material-table/compare/v1.68.0...master

**Comment by Lalee10** [comment]
@mindaugasnakrosis upgrading to v1.69.0 fixed this issue for me

**Comment by tadstratford** [comment]
I upgraded to 1..69 and it is crashing on data refresh of data using setData().  It updates fine and then after 3 updates, it crashes.
