### ISSUE TITLE
How to move actions to group/top level row?

### ISSUE THREAD

**Issue by JaxLu** [mbrn/material-table#2318]
Hi so I am grouping some data together using one of the fields, and now I would like the actions to be based on the top group/row level instead of the individual nested rows. How can I move the actions like edit/delete to be on the top most level row for each nested object? 

I've attached a picture of what I would like to do as it helps understand the issue better:

Any help would be greatly appreciated.

![image](https://user-images.githubusercontent.com/69636975/90143598-b96c0e00-dd75-11ea-9fd0-5f22d65d7f04.png)

**Comment by HyeongjinJoo** [comment]
I would like to know the solution to this issue.

**Comment by thatgravity** [comment]
+1 I am actually working on something now where this could be super helpful. i.e have an action button on the "parent" row that can pass the data of the "children" row(s).
