### ISSUE TITLE
Add row breaks in editable table

### ISSUE THREAD

**Issue by weidner** [mbrn/material-table#2319]
v1.68.0

Click add icon, then type anything into column field.  The screen goes blank.  This happens in the example app in the examples.  Reverting back one version was my fix.

Thx.

**Comment by msichterman** [comment]
Thanks for this. Was running into the same issue but will revert until this issue is fixed.

**Comment by weidner** [comment]
Sure! Glad to help.

**Comment by garrettEledui** [comment]
I am also having this same issue. How do I go about getting a working version? 

Thanks in advance.

**Comment by weidner** [comment]
I'm pretty sure all I did was: npm install material-table@1.67.1 --save

You may need to run: npm uninstall material-table first.  But not sure.

Dave Weidner
503.799.4258

**Comment by msichterman** [comment]
Shouldn't need to uninstall, just re-install the version above and you should be good to go
