### ISSUE TITLE
cant run my own function on click action

### ISSUE THREAD

**Issue by shmoshkin** [mbrn/material-table#232]
icon: add
tooltip: Add,
onCLick(event, rows) => {
i cant access my own file so i cant run any function of mine... cant change my app state or anything else...
}

i also dont have access to this.setState or this.props....

**Comment by mbrn** [comment]
You can run functions in your component with this.functionName.

But you should use arrow functions or binded functions

**Comment by Domino987** [comment]
You could just extarct that function like this:
```
private archiveOrder: (event: React.MouseEvent, rowData: IOrder) => void = (event, rowData) => {console.log(rowData)}

<MaterialTable>
 actions={[{
     icon: 'archive',
     onClick: this.archiveOrder,
     tooltip: 'Archive'
}]}
</MaterialTable>
```
