### ISSUE TITLE
detailPanel and onRowClick exp

### ISSUE THREAD

**Issue by xuxiaoyang883** [mbrn/material-table#2320]
# Guidelines

- #### Please include a demo of the issue/behavior/question you have

- #### Please try to be as detailed as possible

- #### You may fork one of the following starter templates if you would like:

  - #### [CodeSandbox](https://codesandbox.io/s/material-table-starter-template-xnfpo)
  - #### [StackBlitz](https://stackblitz.com/edit/material-table-starter-template)

**Describe the bug**
when I use detailPanel and onRowClick composition props,i take the 'this setState' or 'redux dispatch' toggles render,there is an infinity circle of rerendering .

how can i prevent the infinity rerendering?
**To Reproduce**

**Expected behavior**
i want to stop rerender;

**Screenshots**
![image](https://user-images.githubusercontent.com/46732297/90206994-b7f32200-de17-11ea-8578-c7a7c41d4f42.png)
![image](https://user-images.githubusercontent.com/46732297/90207021-c9d4c500-de17-11ea-9926-f95c353704d6.png)
![image](https://user-images.githubusercontent.com/46732297/90207032-d1946980-de17-11ea-8165-7401e99a3532.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Jairove** [comment]
@xuxiaoyang883  This is not a bug, and not related to material-table, setState produces a render, so you cannot invoke it from the render method, that's what is causing the loop. In short, is like you are invoking render from render. Consider using another lifecycle method like componentDidUpdate() to retrieve data from server only when needed.
