### ISSUE TITLE
How export only CSV 

### ISSUE THREAD

**Issue by ninew089** [mbrn/material-table#2323]
I wan to export only CSV , I don't want export PDF .

**Comment by ollyrowe** [comment]
I've just had a look, it appears that there isn't an option to toggle individual export formats - I think this option should added. In the meantime, one option is to downgrade material-table to v1.62.0 (export to PDF was introduced in v1.63.0).

**Comment by ninew089** [comment]
@ollyrowe  thank you so much .

**Comment by zeckdude** [comment]
You can do the following:

```js
const options = {
  exportButton: {
    csv: true,
    pdf: false,
  },
};

<MaterialTable data={data} columns={columns} options={options} />;
```
