### ISSUE TITLE
here a sample sowing the option doubleHorizontalScroll does not work:

### ISSUE THREAD

**Issue by srinivasmangipudi** [mbrn/material-table#2325]
here a sample sowing the option doubleHorizontalScroll does not work:
https://codesandbox.io/s/material-demo-ynctq?fontsize=14&hidenavigation=1&theme=dark

_Originally posted by @hbinkle in https://github.com/mbrn/material-table/issues/1297#issuecomment-562010285_

**Comment by KiwiKilian** [comment]
The horizontal scrollbar completely disappears in our application when enabling `doubleHorizontalScroll`.
