### ISSUE TITLE
How to disable cell editing by condition of another cell?

### ISSUE THREAD

**Issue by Cetger** [mbrn/material-table#2327]
Hi, i want to ask a question about make disable cell. I read docs of library but i couldnt find what i look for. We can use isEditable to disable by condition. But i want to disable only one cell. Suppose, I have people data. I'm using combobox to select job of person. Next cell is income.  If selected value from combobox is student, i want to make disable income column.  In the other side, i dont want to disable all column on this row. 
I hope that I can explain my issue. Is there any feature that I can use and i couldnt see in docs?

**Comment by v1teka** [comment]
Yes, there is special feature for your case :)

I don't know, what structure you are using to store your table data, but for example:

If We store table`s **data** in a const (may be in component`s state) it can be accessed directly: `data[rawData.tableData.id].job`

'editable' attribute of column can be a function (it doesn`t work in CellEditable mode):

```
const [columns, setColumns] = useState([
    { title: 'Works as', field: 'job', editable: 'onUpdate',
      lookup: { 'student': 'Studies at a university', 'dev': 'Javascript developer' }, },
    { title: 'Surname', field: 'surname', editable: 'never' },
    { title: 'Salary', field: 'income', type: 'numeric', 
editable: (columnDef, rowData) => !(data[rowData.tableData.id].job == 'student')},
  ]);

```
