### ISSUE TITLE
Support listening to scroll event (horizontal and vertical both) and setting scroll position

### ISSUE THREAD

**Issue by tarunchine** [mbrn/material-table#2328]
Please support the following on the table:

- Listen to onScoll event
- A way to set the scroll position 

Usecase:

1. The scroll event will be useful if we have multiple tables and want to scroll them in sync
2. In case on some user action if we want to scroll to a specific position (horizontally  or vertically)

Thanks

**Comment by akhilaudable** [comment]
+1

**Comment by BhushanChandak** [comment]
I am also facing issue to scroll dynamic on some action to particular position
