### ISSUE TITLE
Disable sorting

### ISSUE THREAD

**Issue by NebeschenkoIhor** [mbrn/material-table#2329]
Hi.
I have a column with numbers in a string: `"10, 11, 17"`.
How to disable sorting in material-table?

Because I have a result like:
2
10,
1

**Comment by NebeschenkoIhor** [comment]
Finded solution add:
`customSort: () => 0,`
In header settings.

**Comment by zipzapp** [comment]
Glad you got your problem resolved. It looks like the sorting wasn't working because the data types of the numbers you sent into the table were actually strings, which are going to be sorted according to their unicode properties, and not their values as numbers.
