### ISSUE TITLE
Column specific edits in cellEditable 

### ISSUE THREAD

**Issue by priyanshu-intellemo** [mbrn/material-table#2331]
I've tried cellEditable in my material table.
I need some columns not to have the edit option.
It'd be great if there'd be some 'editable: false' option for the column just like we have for the editable table.

**Comment by anaerobic** [comment]
@priyanshu-intellemo use e.g. `{ field: 'name', title: 'Name', editable: 'never' }`, see https://material-table.com/#/docs/all-props
