### ISSUE TITLE
export csv not giving proper data for date 

### ISSUE THREAD

**Issue by KeshriAyushi22** [mbrn/material-table#2333]
while exporting CSV for the date I didn't get a few of the data as expected.

![issue](https://user-images.githubusercontent.com/49064703/90624227-40692c80-e235-11ea-845e-d3fc2f1717e7.png)
![issue1](https://user-images.githubusercontent.com/49064703/90624237-43641d00-e235-11ea-8d12-b2276e0b832f.png)

**Comment by ollyrowe** [comment]
Hi @KeshriAyushi22, the dates have been formatted like that because the Excel column is not wide enough to fit it. Try widening the date column within Excel and report back. Thanks

**Comment by KeshriAyushi22** [comment]
@ollyrowe Hi, Thanks for the solution, wasn't knowing size of column could impact . Also, can you tell me , Is there a way to export the hidden columns in material table? I tried doing exportAllData:true , but no luck.

**Comment by ollyrowe** [comment]
@KeshriAyushi22, yes there is, you just need to add the "export: true" option to your column definition.

**Comment by KeshriAyushi22** [comment]
Hi @ollyrowe, its not working i tried it with `csvExport: true` ,  `export: true`  both.
