### ISSUE TITLE
Using variables for columns and tableData instead of using State, the selections and grouping will disappear after edit row

### ISSUE THREAD

**Issue by flora8984461** [mbrn/material-table#2334]
# Guidelines

- #### Please include a demo of the issue/behavior/question you have

- #### Please try to be as detailed as possible

In my situation, I am using variables instead of useState for table data and columns, If refactoring the code to useState it would be a lot of work. When I use selections, after I click on the action, what I have selected will be gone, the user needs to re-select which is not a good user experience. 
Code: https://codesandbox.io/s/using-variables-for-data-selections-ouhle

When I use grouping, after I edit a row, the grouping is gone. Code: https://codesandbox.io/s/using-variables-for-columns-grouping-obqxi?file=/src/App.js

And I notice if I useState for columns and data, the grouping and selections will keep. 

I wonder if the only solution is to use State? Would there be any other possible solutions? 

Thanks everyone!

**Comment by tonyal128** [comment]
I think you need to use state. Otherwise you are losing the value on re render.
