### ISSUE TITLE
Fixed columns are not scrolled with sticky header

### ISSUE THREAD

**Issue by david-lee** [mbrn/material-table#2336]
**Describe the bug**

It is happening when you use fixed columns and sticky header both. The fixed columns are not scrolled and maxBodyHeight is not applied to the fixed columns. You can see how it works with below sample.

  - #### [CodeSandbox: fixed columns not working](https://codesandbox.io/s/material-table-starter-template-forked-vzpn0?file=/src/index.js)

**Expected behavior**

The fixed columns should be scrolled along with other columns.

**Desktop (please complete the following information):**

- OS: [macOS Mojave v10.14.6]
- Browser [chrome Version 84.0.4147.125 (Official Build) (64-bit)]
- Version [material-table v1.68.0]

**Comment by pradeepkrishna1409** [comment]
I'm having the same issue. The fixed columns are not scrolled and maxBodyHeight is not applied to the fixed columns.

**Comment by anmolmalik97** [comment]
Any update on this
