### ISSUE TITLE
FindDOMNode is deprecated warning

### ISSUE THREAD

**Issue by EyadAlghamdi** [mbrn/material-table#2345]
I am making a simple table and anytime i hover over any icon i get a huge warning about how findDOMNode is deprecated in StrictMode. 
I know i can build the project and not have this error anymore but if its deprecated i would rather not have this issue cause a problem in the future.

![image](https://user-images.githubusercontent.com/58611925/90918407-99aa9a80-e3b2-11ea-8857-9f8adca970b4.png)

the code is very straight forward i just added an empty table like so with its icons;

![image](https://user-images.githubusercontent.com/58611925/90918808-4edd5280-e3b3-11ea-84d7-d25f463cfea6.png)
![image](https://user-images.githubusercontent.com/58611925/90918889-7af8d380-e3b3-11ea-81f3-45efb331bc19.png)

Im not making anything special with this table just a standard table and it always shows this error. is everyone else getting the same warning?

Thank you!

**Comment by e11en** [comment]
+1

**Comment by dhilt** [comment]
Relates to https://github.com/mui-org/material-ui/issues/13394.

**Comment by grachet** [comment]
No solution yet ?
