### ISSUE TITLE
Is there any way to remove detail panel's expand icon??

### ISSUE THREAD

**Issue by Mizan-Rifat** [mbrn/material-table#2347]
i want to expand a row by clicking on the row.but i don't want that expand icon.is there any way to to remove it??

**Comment by KeshriAyushi22** [comment]
hey @Mizan-Rifat how have you added that question label to it? Can you plz let me know

**Comment by OnkelTem** [comment]
Stumbled upon the same issue and well... I won't be surprised if that's not possible.
