### ISSUE TITLE
Warning: React does not recognize the `scrollWidth` prop on a DOM element.

### ISSUE THREAD

**Issue by lfsando** [mbrn/material-table#2357]
# Guidelines

![image](https://user-images.githubusercontent.com/10608706/91068590-e7b9db00-e60a-11ea-8e5b-48f8aa3f451b.png)
After latest update (1.69.0) I'm getting this warning on my tables.
I am using Typescript.

Probably related to this commit: 3ff58213f0a10a5a38e0b0119ebcdb63db0af18c

**Comment by rlaace423** [comment]
Same here.

**Comment by Jean-MarcCheynier** [comment]
same but i'm not using Typescript

**Comment by familiarcat** [comment]
We are also using Typescript and just upgraded to 1.69.0 - looks like it might be in the Material Styles

**Comment by CristianEliab** [comment]
![image](https://user-images.githubusercontent.com/31315146/91315449-4ef79c80-e77d-11ea-90eb-a0f519939e19.png)
`[](url)`

Hello, in this moment I have the same problem. I'm using react js and I reinstall MaterialTable.

**Comment by merobal** [comment]
Will be fixed by #2369

**Comment by indrajithi** [comment]
Is there any temporary work around for now?

**Comment by merobal** [comment]
v1.69.1 is just released, finally 🎉

**Comment by camilo0119** [comment]
> v1.69.1 is just released, finally 🎉

Thank's
