### ISSUE TITLE
Option to turn off committing edits when Enter key pressed

### ISSUE THREAD

**Issue by chris-nissen** [mbrn/material-table#2360]
When editing a row, when the Enter key is pressed, the edit is committed. If the editor is a multi-line editor, e.g. for rich text, this leaves no way to add new lines in the text. It would be nice to have an option to disable commit-on-enter.

**Comment by fanatyko47** [comment]
Hi,

I have same problem, added multi-line rich text editor and cannot add new lines with enter press, because it saves record.
Add way to disable it or override the way it works would be great !

PS. material-table is great

**Comment by rosostolato** [comment]
Isn't there any hack to bypass it?
