### ISSUE TITLE
"Save" tool tip shown when prompting user to delete row...

### ISSUE THREAD

**Issue by andre7000** [mbrn/material-table#2363]
Feature Request
When clicking on the delete icon of an Editable table. The "check" icon to confirm deletion of the row has a tool tip with the title "Save".
![Material-Table - Save Tooltip on Confirm Delete](https://user-images.githubusercontent.com/11604916/91227117-da6c2180-e6da-11ea-865f-69a678802b5c.JPG)

To Reproduce

Go to 'Editable Table.'
Click on 'Delete Icon'
Hover over 'Check' icon
See "Save"

Desired Behavior
Tool tip to show "Delete"

Screenshots

**Comment by LahiruRajapaksha** [comment]
Feature Request
---
Can we have the feature as 
 * Delete and Cancel tooltips when deleting a row
 * Save and Cancel tooltips when editing a row
