### ISSUE TITLE
Can material table support backend pagination

### ISSUE THREAD

**Issue by Azteker** [mbrn/material-table#2364]
Now all data need to be put into table at once, this has a performance issue when the data size is huge. Can we add a customized way for the table's pagination so we can use backend pagination? Or is it already supported?

**Comment by MatiasManevi** [comment]
I'll add to this.


Since there is no backend pagination built in. Is it possible to implement virtualization of the not shown rows? 

Having a table with 1.000.000 freezes the browser!
