### ISSUE TITLE
Help styling title, title background, border and icons

### ISSUE THREAD

**Issue by shumry** [mbrn/material-table#2365]
# Is it possible to style the title bar, the border, and icons

#### Right now my table is looking like this: 
<img width="848" alt="Screen Shot 2020-08-26 at 1 16 12 PM" src="https://user-images.githubusercontent.com/31782757/91258130-33e95480-e79e-11ea-8603-1b7c45c07456.png">

I want to make the whole thing gold on black, and was wondering if it was possible to 
- Style the title and its background to be black on gold
- Style the action icons (edit and delete and add row) and the subsequent column to be black on gold
- Style the footer to be black on gold
- Have gold borders (with hex D4AF37)

Right now I have tried styling the borders by       
```
<MaterialTable
        title="Catalog Upload"
        style={{ width: "60%", borderColor:"#D4AF37", }}
        ...
```

Any help is appreciated. Thank you!

**Comment by EmrajiPower** [comment]
> # Is it possible to style the title bar, the border, and icons
> #### Right now my table is looking like this:
> <img alt="Screen Shot 2020-08-26 at 1 16 12 PM" width="848" src="https://user-images.githubusercontent.com/31782757/91258130-33e95480-e79e-11ea-8603-1b7c45c07456.png">
> 
> I want to make the whole thing gold on black, and was wondering if it was possible to
> 
> * Style the title and its background to be black on gold
> * Style the action icons (edit and delete and add row) and the subsequent column to be black on gold
> * Style the footer to be black on gold
> * Have gold borders (with hex D4AF37)
> 
> Right now I have tried styling the borders by
> 
> ```
> <MaterialTable
>         title="Catalog Upload"
>         style={{ width: "60%", borderColor:"#D4AF37", }}
>         ...
> ```
> 
> Any help is appreciated. Thank you!

You can´t use `style` attribute for specific element like title because it is wrapping all the container of table. So, you could add jsx elements to wrap elements like title
`
<MaterialTable
         title={<div style={{ paddingLeft: "2rem", borderColor:"#D4AF37", }}>"Catalog Upload"</div>}         
        ...
`
if you are looking for change the style of the borders o footer, make sure of read https://material-table.com/#/docs/features/component-overriding and override any of these components like this:
`
components={{
        Groupbar: props => (
            <div style={{ backgroundColor: 'D4AF37' }}>
                <MTableToolbar {...props} />
                {props.children}
            </div>
        )
    }}
`
