### ISSUE TITLE
Is it possible to have a separate button that adds a row?

### ISSUE THREAD

**Issue by shumry** [mbrn/material-table#2366]
Right now it seems that the only way to add a row is to add "onRowAdd" to the editable. That would add an app icon to the toolbar. Is it possible to direct my own button to add a row?

**Comment by robertvorthman** [comment]
Look at the [Component Overriding Documentation](https://material-table.com/#/docs/features/component-overriding) to see how to override the `Actions` component.  Try something like this:

```js
import MaterialTable, { MTableActions } from 'material-table'

...

<MaterialTable
    {...tableProps}
    components={{
        Actions: props => <div>
            <MTableActions {...props} />
            <button>Add Row</button>
        </div>,
    }}
/>
```
