### ISSUE TITLE
Details panel works only on the first page

### ISSUE THREAD

**Issue by anjmao** [mbrn/material-table#237]
**Describe the bug**
If details panel is enabled and there is more than one page it works only on first page. Opening details panel on other pages actually opens it only on first page.

**To Reproduce**
1. Create at least two pages of data.
2. Expand details panel on second page.
3. Go back to first page, only it's data is visible

**Expected behavior**
Details panel should be opened on correct row.

BTW. Thanks for great component.

**Comment by mbrn** [comment]
Hi @anjmao ,

Which version do you use? Because i resolved this problem in v1.18.0.

**Comment by anjmao** [comment]
@mbrn Awesome, it works now, thanks a lot!
