### ISSUE TITLE
How to truncate the text with ellipsis?

### ISSUE THREAD

**Issue by asifkabani** [mbrn/material-table#2380]
I have request for a fixed table and my table headers are being cut off. I tried this:

```
headerStyle: {
              width: 26,
              whiteSpace: 'nowrap',
              textAlign: 'left',
              flexDirection: 'row',
              overflow: 'hidden',
              textOverflow: 'ellipsis',
              paddingLeft: 5,
              paddingRight: 5,
              backgroundColor: theme.palette.primary.table,
              fontWeight: 'bold',
              color: theme.palette.primary.main,
            },
```
But it does not seem to add ellipsis. I am thinking because there is an icon for sorting showing up, the truncation may be happening after the icon. Is there a way to target the column heading text specifically instead of the ```headerStyle```?

![image](https://user-images.githubusercontent.com/9083341/91501880-3fb34480-e88c-11ea-9392-4d62a533f9e9.png)

**Comment by izuminskoe** [comment]
Sorted headers are rendered as MuiTableSortLabel. You can override them using MuiThemeProvider

**Comment by asifkabani** [comment]
I tried using `MuiTableSortLabel` and added the properties needed for overflow ellipsis but did not work.

**Comment by asifkabani** [comment]
Basically looking for a way for the table to be a fixed size and depending on how many columns there are, have a truncated header and row content to be 100% also while being responsive it should know to truncate or not depending on how many columns are next to one another.

**Comment by izuminskoe** [comment]
You need something like this: https://codesandbox.io/s/broken-breeze-z86jl

**Comment by asifkabani** [comment]
Thank you this solves my issue
