### ISSUE TITLE
how to get row index after sorting or filtering??

### ISSUE THREAD

**Issue by Mizan-Rifat** [mbrn/material-table#2382]
to get a row index i can do rowData.tableData.id. but when i  do sort or filter this id does not change.how to get that changed index??

**Comment by mackankowski** [comment]
I couldn't find any way to do that but use just Material UI components (so no material-table), sort implementing and then to keep my own state with row indexes. Or maybe to overwrite material-table's Body component somehow.

**Comment by mackankowski** [comment]
@Mizan-Rifat: Actually there's some workaround we accomplished in our project. Let's see:

```
  const columns: Column<SomeType>[] = [
    {
      field: 'name',
      title: 'Name',
      render: (item) => (
        <span tabIndex={item.id}>
            {item.name}
        </span>
      ),
    },
  ...
  ];
````

In the following example, I can use `tabIndex` to navigate after sorting or filtering (it could be some other attribute, like `data` or `aria`). The purpose of that is to scroll to selected row using [Element.scrollIntoView()](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) method.

Let me know if it helps!

Best regards,
Maciej

**Comment by kirawiley** [comment]
can we get index added to the render method of columns? ex: (rowData, index) => {} 
I need to number each row and currently there is no way to do that other than rowData.tableData.id which does not update when resorting
