### ISSUE TITLE
row actions with and without selection

### ISSUE THREAD

**Issue by liviozanol** [mbrn/material-table#2384]
When selection is true on options and you add actions, actions are only displayed if you select rows. Is this a normal behavior?

I need a duplicate action on each row without selection - just like the edit line example that works no matter if you have set selection true/false, and also a delete action that only appears on row selection. Is it possible to do this?

Did not asked on stackoverflow because I don't know if this is a normal behavior, a bug or a feature request.

Example:
https://material-table.com/#/docs/features/selection

Go to "Actions on Selected Rows Example" and paste this code:
```function ActionsOnSelectedRows() {
  return (
    <MaterialTable
      title="Actions On Selected Rows Preview"
      columns={[
        { title: 'Name', field: 'name' },
        { title: 'Surname', field: 'surname' },
        { title: 'Birth Year', field: 'birthYear', type: 'numeric' },
        {
          title: 'Birth Place',
          field: 'birthCity',
          lookup: { 34: 'İstanbul', 63: 'Şanlıurfa' },
        },
      ]}
      data={[
        { name: 'Mehmet', surname: 'Baran', birthYear: 1987, birthCity: 63 },
        { name: 'Zerya Betül', surname: 'Baran', birthYear: 2017, birthCity: 34 },
      ]}        
      options={{
        selection: true
      }}
      actions={[
        {
          tooltip: 'Remove All Selected Users',
          icon: 'delete',
          onClick: (evt, data) => alert('You want to delete ' + data.length + ' rows')
        },

//ADDED
//ADDED
//ADDED
        {
          icon: 'delete',
          tooltip: 'Duplicate',
          onClick: (event, rowData) => {
            const materialTable = this.materialTableRef.current;            
          }
//ADDED
//ADDED
//ADDED
        }
      ]}
    />
  )
}

**Comment by ihuaylupo** [comment]
I'm having the same issue. I want to create a custom row action but when I add the options = {{selection: true}} the custom action is only displayed if I have rows selected.
