### ISSUE TITLE
Error when exporting pdf with cyrillic letters

### ISSUE THREAD

**Issue by Jekillokda** [mbrn/material-table#2386]
Hello. I have problem with exporting pdf. As I know material-table uses jsPdf so problem is in it, and in jsPdf this problem can be fixed by fonts, so can I use custom fonts in material-table to fix it?
![error](https://user-images.githubusercontent.com/20152316/91563436-83b74f80-e947-11ea-8e4f-3774110ce332.png)

Thanks. Material-table is very nice and convinient to use.

**Comment by vbtux** [comment]
I have the same problem
