### ISSUE TITLE
Low performance when using a filter and passing different list of data.

### ISSUE THREAD

**Issue by cazetto** [mbrn/material-table#2388]
I have the table being controlled by a filter that returns one of two data arrays.
When I navigate between these data lists more than 4 times, there is a decrease in the performance of the table, until from the 8th filter change, the application completely crashes.

Here is the example to reproduce the problem.
https://gist.github.com/cazetto/ee8fc6096b33f7b69b84e79a65428650

A video with the problem:
https://drive.google.com/file/d/10ZXX84jUL18IIV4ndE5Jj2B3zOOLJ5Ze/view?usp=sharing

1. Click many times in different Tabs
2. See the performance problem

**Expected behavior**
The table should render without slowness.

- OS: [MacOS Catalina]
- Browser [chrome]
- Version [e.g. 84.0.4147.135]

**Comment by liviozanol** [comment]
I'm also having a similar issue with performance when changing data dynamically setting state.

**Comment by raycoarmas** [comment]
I have same issue, downgrade to 1.68.1 work fine.

**Comment by yoavz** [comment]
I can also confirm weird performance issues. Downgrading to 1.68.1 worked for me.

**Comment by cococov** [comment]
Same issue here. (using router between two tables)

**Comment by cococov** [comment]
1.68.1 works fine.

**Comment by cazetto** [comment]
Really, 1.68.1 worked for me too.

**Comment by Benjaminlooi** [comment]
Having same issue, everytime i paginate, it suddenly uses a lot more cpu and memory until the tab hangs.

**Comment by graves-k** [comment]
Same issue here. 
Reverting to 1.68.1 did not help.

**Comment by b3ni** [comment]
Same issue.
1.68.1 works
