### ISSUE TITLE
Is it possible to add Tooltip if user action is disabled ?

### ISSUE THREAD

**Issue by kaleshasheik** [mbrn/material-table#239]
Hi,

If action is disabled, tooltip is not showing. 

     rowData => ({
                tooltip: 'show details',
                disabled: rowData.tableData.id > 0,

Any other possible way to show, why action was disabled ?

**Comment by mbrn** [comment]
Hi @kaleshasheik ,

Material-ui Tooltips is not working for disabled contents. But i will look at it again to find a solution.

**Comment by kaleshasheik** [comment]
> Hi @kaleshasheik ,
> 
> Material-ui Tooltips is not working for disabled contents. But i will look at it again to find a solution.

@mbrn Thank you

**Comment by rfones** [comment]
Disabled elements do not fire a hover event. You need to wrap your disabled element in a span (or other element).

https://material-ui.com/demos/tooltips/#disabled-elements

**Comment by mbrn** [comment]
@rfones ,

I will wrap actions with a span. Thanks.

**Comment by mbrn** [comment]
This is done. You can use version 1.20.0
