### ISSUE TITLE
Is there any way to add a thousands seperator for a sortable table?

### ISSUE THREAD

**Issue by thchong-code** [mbrn/material-table#2392]
I have tried passing `.toLocaleString()` and it works displaying the seperators but then the sort functions won't work as intended. Is there any workaround for this ?

**Comment by Lalee10** [comment]
[Sorting Docs](https://material-table.com/#/docs/features/sorting)

You can pass in a custom sort function for each column. That function for your use case should look something like

`customSort: (a, b) => parseInt(a.replace(/,/g,"")) - parseInt(b.replace(/,/g,""))`

`str.replace(/,/g, "")` will replace all commas from your string then you can parseInt to convert it to number and compare

**Comment by thchong-code** [comment]
Alright let me try it out

**Comment by thchong-code** [comment]
> Alright let me try it out



> [Sorting Docs](https://material-table.com/#/docs/features/sorting)
> You can pass in a custom sort function for each column. That function for your use case should look something like
> 
> `customSort: (a, b) => parseInt(a.replace(/,/g,"")) - parseInt(b.replace(/,/g,""))`
> `str.replace(/,/g, "")` will replace all commas from your string then you can parseInt to convert it to number and compare

Alright let me try it out

**Comment by thchong-code** [comment]
Thanks for the tip @Lalee10

**Comment by thchong-code** [comment]
Working.
