### ISSUE TITLE
On Filter, show aggregate / total for a column

### ISSUE THREAD

**Issue by rphovley** [mbrn/material-table#2395]
What I'm trying to accomplish:
- When a user filters the data in my dataset, I would like to show a total for the elements that have been filtered. 

Do you have any recommendations for how you would solve this problem? 

So far, I've tried to add a "total" section into the MLTablePagination component and update the total inside by overriding the "filteredComponent" on the column that's being filtered. So, that when the filter is executed, the total is updated. 

[Example attempt]https://codesandbox.io/s/material-table-starter-template-forked-4tfkn?file=/src/index.js
In the example, the intended behavior is the user starts to type in "Vanilla" and the total updates to the sum of all the records that have the "Vanilla" flavor. The actual behavior for my solution is the user starts to type but the component re-renders (because total is part of state) and causes the filter to be cleared on the re-render

<img width="1423" alt="Screen Shot 2020-08-30 at 10 58 22 AM" src="https://user-images.githubusercontent.com/10646939/91664964-c2681980-eaaf-11ea-9c77-20ca029134da.png">

Any ideas?

**Comment by lbuscherX** [comment]
Any luck on this one? I'm also interested in the solution.

**Comment by rphovley** [comment]
Nothing that I'm proud of. And it may only work because of some translational deal between typescript and javascript or something else beyond my understanding. I expect this to break at some point in the future.

Essentially, I put the function call accidentally in a function and used setTimeout to simulate a promise for some testing and that conveniently worked. This is the function. 

```
const calcTotal = (filteredPayments: Payment[]): Promise<number> => {
  const count = filteredPayments.reduce(aggTotal, 0)
  return new Promise((resolve) => resolve(count)) // returning as a promise to escape re-rendering the material table when setting the count
}
...
filterComponent: ({ columnDef, onFilterChanged }): ReactElement => {
     const { tableData } = columnDef as Payment&TableData
      ...
     setTotal(await calcTotal(filteredPayments)) // set external state using a promise. this worked to break out of reacts re-rendering for me.
})
```

I wish I had found a better solution
