### ISSUE TITLE
Latest Material Table upgrade is hanging the browser on same row selection continuously

### ISSUE THREAD

**Issue by sachinagarwal010** [mbrn/material-table#2397]
Hello Team/ @mbrn  , I was using Material Table 1.68.0 version till now and recently I have upgraded to 1.69.0 now and after upgrading I am facing below two issues.

1.)  on selecting any row in the table its resizing the column width automatically.
2.) If we keep on selecting the same row continuously , its hanging the browser and we cant do anything.

I have attached code sandbox Environment where I am using the material table 1.69.0 version and if I will revert the older version 1.68.0 , both of the issues will not occur.

SandBox Link :- [https://codesandbox.io/s/jovial-brattain-0qn0u?file=/src/compo.tsx](https://codesandbox.io/s/jovial-brattain-0qn0u?file=/src/compo.tsx)

Code Changes:-
I have created a component named as Compo and in that compo I have defined the **constant columns outside the component.** and using the material table to render the data.

So what are the changes has been introduced in new version which is causing this issue.. Please let me know .
Or suggest me if I am missing something.

![image](https://user-images.githubusercontent.com/13916436/91697461-cc147e80-eb8e-11ea-9835-abe624abed69.png)

**Comment by mykhailo-pugovkin-dev-optima** [comment]
The same for me.

**Comment by gauthamilango** [comment]
+1

**Comment by kvskranthikumar** [comment]
@mbrn, this is a critical issue, can we get this fixed in next release.

**Comment by raviteja-gundu-by** [comment]
@mbrn The very basic behavior (row selection) got disturbed in upgrading to the latest version 1.69.0.
It really annoys the user to see the columns resizing for every row selection. Can we expect this to be fixed in next release

**Comment by SrinivasErram** [comment]
**Facing the same issue, need the resolution at the earliest**

**Comment by kvskranthikumar** [comment]
@mbrn, any updates on this issue?
Due to this, we can't upgrade the material-table version to 1.69.0

**Comment by kranthikumar-kvs-by** [comment]
Related to - https://github.com/mbrn/material-table/issues/2486

**Comment by kvskranthikumar** [comment]
Relates to https://github.com/mbrn/material-table/issues/2486

**Comment by kvskranthikumar** [comment]
I can still see the issue with the latest version 1.69.2
Here is the sample to recreate this issue -

https://codesandbox.io/s/compassionate-meitner-802l6

Just clicking on the rows hangs the browser.

**Comment by kranthikumar-kvs-by** [comment]
@mbrn, this is a critical issue, can we get this fixed in next release.
