### ISSUE TITLE
Using hidden with useMediaQuery hook on columns when columns is passed as state to material doesn't change when mediaQuery is true

### ISSUE THREAD

**Issue by pedrohenriiz** [mbrn/material-table#2398]
My table will have a lot of columns and fields that will have large amount of characters. So, I need to use hidden props to hide some of then when the screen size is below some breakpoint. When I was using the columns directly on material-table, it worked like a charm, but I had to implement a filter option. When doing this, when the media query breakpoint is setted as true, the filter lose their value and the table come back to 'normal'.
I know that passing the columns as array to material-table isn't the proper way to do this, then I changed it to state. The filter maintain their values as expected, but the hidden stopped to work. When any breakpoint criteria is true, the column isn't hidden. 

I'll provide a codesandbox example to see better what my issue is.
[Click here to see](https://codesandbox.io/s/eager-lichterman-n2n82?file=/src/App.js)

To reproduce is quite simple:
1). Select any filter on birth place.
2). Resize your screen to be below 'sm' - smartphone or below. 
3). See that the name doesn't hide.

My questions is: How I'm suppose to handle the hidden change when passing the columns as state?

**Comment by Krunal91** [comment]
This would work.
```function App() {
  const theme = useTheme();
  const matches = useMediaQuery(theme.breakpoints.down("sm"))
  let columns = [
    {
      title: "Name",
      field: "name",
      hidden: matches,
    },
    { title: "Surname", field: "surname" },
    { title: "Birth Year", field: "birthYear", type: "numeric" },
    {
      title: "Birth Place",
      field: "birthCity",
      lookup: { 34: "İstanbul", 63: "Şanlıurfa" }
    }
  ]

  return (
    <MaterialTable
      title="Custom Filtering Algorithm Preview"
      columns={columns}
      data={[
        {
          id: 1,
          name: "a",
          surname: "Baran",
          birthYear: 1987,
          birthCity: "63",
          sex: "Male",
          type: "adult"
        },
        {
          id: 3,
          name: "c",
          surname: "Baran",
          birthYear: 1987,
          birthCity: "34",
          sex: "Female",
          type: "child"
        },
        {
          id: 6,
          name: "f",
          surname: "Baran",
          birthYear: 1987,
          birthCity: "63",
          sex: "Female",
          type: "child"
        }
      ]}
      options={{
        filtering: true
      }}
      //onTreeExpandChange={(data) => setTeste(!teste)}
    />
  );
}```

**Comment by pedrohenriiz** [comment]
I tested out your code and it works like mine.

I wrote my question kinda badly, sorry.  What I need to happen is when the screen goes below some breakpoint, the filter doesn't lose their state. For example, if I filter the birth place to İstanbul, only the results that have this value will appear, but when the screen size changes (goes below some breakpoint), this value on filter is lost. I need it to maintain. Do you have any idea how it's possible to do this?

**Comment by osvaldokalvaitir** [comment]
Any solution? I need this too

**Comment by osvaldokalvaitir** [comment]
Any solution? I need this too

**Comment by osvaldokalvaitir** [comment]
Any solution? I need this too

**Comment by cococov** [comment]
@osvaldokalvaitir put columns inside a useState and create an useEffect that trigger on "matches" changes:

```js
  useEffect(() => {
    if (matches) {
      setColumns((previous) => {
        return previous.map((current) => {
          if ('checksColumns that will be hidden') {
            return { ...current, hidden: true };
          }
          return current;
        });
      });
    } else {
      setColumns((previous) => {
        return previous.map((current) => {
          return { ...current, hidden: false };
        });
      });
    }
  }, [matches]);
  ```

**Comment by osvaldokalvaitir** [comment]
> @osvaldokalvaitir put columns inside a useState and create an useEffect that trigger on "matches" changes:
> 
> ```js
>   useEffect(() => {
>     if (matches) {
>       setColumns((previous) => {
>         return previous.map((current) => {
>           if ('checksColumns that will be hidden') {
>             return { ...current, hidden: true };
>           }
>           return current;
>         });
>       });
>     } else {
>       setColumns((previous) => {
>         return previous.map((current) => {
>           return { ...current, hidden: false };
>         });
>       });
>     }
>   }, [matches]);
> ```

I will test here =)
