### ISSUE TITLE
Date Format

### ISSUE THREAD

**Issue by GabrielBack28** [mbrn/material-table#2401]
When inserting new data in the table, the default format is `dd.MM.yyyy`, however what I use is `dd/MM/yyyy`. In `columns.dateSettings.locale` I put the format `dd/MM/yyyy`, but `dd.MM.yyyy` is still shown. I am trying to modify this format to match what is rendered.

**Comment by rubiadias** [comment]
@GabrielBack28 vê se te ajuda:

[#1038 ](https://github.com/mbrn/material-table/issues/1038#issuecomment-525293773)
[#975 ](https://github.com/mbrn/material-table/issues/973#issuecomment-521792897)

**Comment by GabrielBack28** [comment]
@rubiadias muito obrigado. Ajudou bastante.

**Comment by yfrfelipe** [comment]
Ver essa thread sendo respondida em português me dá até gosto em ler!!

**Comment by awaism551** [comment]
why not conversation in English? 👎

**Comment by yfrfelipe** [comment]
@awaism551, dá uma olhada nessa ferramenta aqui, vai te ajudar. (https://www.duolingo.com/)
