### ISSUE TITLE
Text input filters very slow when using example code from material-table.com

### ISSUE THREAD

**Issue by saunlani** [mbrn/material-table#2402]
```
// Example taken from https://material-table.com/
function CustomFilteringAlgorithm() {
  return (
    <MaterialTable
      title="Custom Filtering Algorithm Preview"
      columns={[
        {
          title: 'Name', 
          field: 'name',
          customFilterAndSearch: (term, rowData) => term == rowData.name.length
        },
        { title: 'Surname', field: 'surname' },
        { title: 'Birth Year', field: 'birthYear', type: 'numeric' },
        {
          title: 'Birth Place',
          field: 'birthCity',
          lookup: { 34: 'İstanbul', 63: 'Şanlıurfa' },
        },
      ]}
      data={[
        { name: 'Mehmet', surname: 'Baran', birthYear: 1987, birthCity: 63 },
        { name: 'Zerya Betül', surname: 'Baran', birthYear: 2017, birthCity: 34 },
      ]}
      options={{
        filtering: true
      }}
    />
  )
}
```

When entering text into the filter text inputs, the response is noticeably slow.  This occurs with the above example code. 
 Interestingly enough, the demo provided on the website does not experience the issue.  However, when creating a new project from scratch with create-react-app, the delay is very noticeable, especially when holding down a single letter key, entering text into the filter.

1. Go to [https://material-table.com/#/docs/features/filtering]
2. Notice the example provided does not experience an delay/lag when holding down a key in the filter box.

3. npx create-react-app my-app
4.) cd my-app
5.) npm install material-table @material-ui/core --save
6.) Drop example code in App.js
7.) npm start
8.) Notice the delay is present when adding a lot of text at once.

**Expected behavior**
Text input filter should not lag or experience delay.

**Comment by LostInCode404** [comment]
@saunlani I faced something similar, I am guessing that it is because the table is re-rendering everytime any filter is changed because that must be part of state inside table component. Even though the actual filtering is debounced, the rendering still happens on state change.

If I provide custom `filterComponent`, the value is no longer part of state of the material-table's table component and the lag is gone.
