### ISSUE TITLE
How to add tooltip to header label?

### ISSUE THREAD

**Issue by asifkabani** [mbrn/material-table#2403]
I want to be able to add a tooltip component to the header column heading so that when I hover over the column heading text I see the tooltip. What is the best way to do this?

**Comment by asifkabani** [comment]
I just realized there is a `tooltip` property available for columns after searching through text. Is there any plans to add the placement prop to the tooltip to control what direction it is displayed? Currently it's only at the bottom.

**Comment by mackankowski** [comment]
What about overring with`columns.title` like this:

```
import { Tooltip } from '@material-ui/core';

  const columnsWithHeaderTooltip = props.columns.map((column) => ({
    ...column,
    title: (
      <Tooltip title={column.title ?? ''}>
        <span>{column.title}</span>
      </Tooltip>
    ),
  }));
```

For cells (but no headers),`components.Cell` overriding is enough:

```
  components={{
          Cell: (props) => (
            <Tooltip title={props.value ? props.value : ''}>
              <MTableCell {...props} />
            </Tooltip>
          ),
        }}
```

I hope it helps,
Maciej
