### ISSUE TITLE
Catastrophic freeze in infinite loop when updating table context

### ISSUE THREAD

**Issue by cdruck** [mbrn/material-table#2404]
See SOF issue https://stackoverflow.com/questions/63602354/material-ui-react-table-hangs-on-switching-tabs

**Describe the bug**
Table crashes unforgivingly when trying to recalculate column widths on update. On debug, seems due to infinite loop in reducePercentsInCalc.

**To Reproduce**
https://codesandbox.io/s/winter-pond-1zsn3?file=/public/index.html

**Comment by moussaidOualid** [comment]
same problem !

**Comment by cdruck** [comment]
https://github.com/mbrn/material-table/blob/6b2e168f8bb768b1582998377ed6363abcb0ad71/src/utils/common-values.js#L14 is the culprit as far as I can tell (infinite loop)

**Comment by ablontech** [comment]
Same issue here

**Comment by moussaidOualid** [comment]
I think the problem is in the new features in v 1.69.
Downgrading to 1.68.1 solved the problem for me

**Comment by cdruck** [comment]
> I think the problem is in the new features in v 1.69.
> Downgrading to 1.68.1 solved the problem for me

1.68.0 (I don't know about 1.68.1) has other issues, with onBulkUpdate (even if you're not using that feature)

**Comment by pyrsv** [comment]
same issue in 1.69
have table with local data and input that changes comment for every row 
on first change it is ok, second update takes about 2 seconds, but third .... 
![photo_2020-09-29_10-56-35](https://user-images.githubusercontent.com/41165536/94529487-793bee80-0242-11eb-96cb-634dbc4c60b9.jpg)

**Comment by Denis-Step** [comment]
I have the same issue and will update with more info later. I am able to update context after the initial render ONCE. Subsequent changes to context cause an infinite loop.

**Comment by meiraleal** [comment]
I have a similar issue and fixed it by removing (for now) React.StrictMode.

**Comment by marcespinoza** [comment]
> I think the problem is in the new features in v 1.69.
> Downgrading to 1.68.1 solved the problem for me

Thanks man, works for me too.

**Comment by eeropenttinen** [comment]
I have also the same issue with v 1.69. Downgrading to 1.68.1 solved the problem. 

> I think the problem is in the new features in v 1.69.
> Downgrading to 1.68.1 solved the problem for me

Thanks man, resolved the issue for me.

**Comment by briankostar** [comment]
Same issue. Downgrading to 1.68 helped fixed it.

**Comment by cking27** [comment]
Also downgraded to 1.68.1 to resolve this issue.  Helpful hint ( as I had to do a second pass to resolve). I had in my package.json  "material-table": "^1.69.0". Note the Caret. It indicates "Compatible with version". To be sure you indeed just get 1.68.1 you may want to remove the Caret to: "material-table": "1.68.1"

**Comment by cristian-azocar** [comment]
If you don't want to downgrade, you can also set the width for each column to `width: 'auto'`. This fixed it for me and I'm using v1.69.1

**Comment by AshrinJose** [comment]
> I think the problem is in the new features in v 1.69.
> Downgrading to 1.68.1 solved the problem for me

Thanks man. This worked for me.

**Comment by peacechen** [comment]
Unfortunately mbrn is inactive and not merging PR's. Use the official community fork [@material-table/core ](https://github.com/material-table-core/core)instead.

**Comment by nzayatz14** [comment]
> I think the problem is in the new features in v 1.69.
> Downgrading to 1.68.1 solved the problem for me

FWIW also worked for me
