### ISSUE TITLE
How to change a specific cell style onRowUpdate

### ISSUE THREAD

**Issue by kpongyu** [mbrn/material-table#2409]
Is there a way to update the specific cell style to help the user realize that this cell has been edited? I guess it should be in onRowUpdate function but not sure how to realize the feature.

**Comment by mackankowski** [comment]
You can keep state with selected indexes (or other property like id - whatever you row data contains) and then, you then just comparing like this:

```
```

**Comment by mackankowski** [comment]
You can keep state with edited `id` (or other property you wish):

`const [editedRows, setEditedRows] = useState([])`

Then, to update it in `editable.onRowUpdate` body:

```
      editable={{
        onRowUpdate: newData => { ... }
      }
```

And finally to style the row:

```
     options={{
        rowStyle: (rowData) =>
           editedRows.contains(rowData.id)
             ? 
               { backgroundColor: 'red' } 
               : {}
      }}
```

Let me know if it helps,
Maciej
