### ISSUE TITLE
How to show the filters along with column name

### ISSUE THREAD

**Issue by vijthang61** [mbrn/material-table#241]
I want to show the filters in the same row along with column headers and not as a separate header. Let me know how to achieve this.

**Comment by mbrn** [comment]
Hi @vijthang61 ,

Material table does not provide this feature. But you can override header component to achieve this.

**Comment by vijthang61** [comment]
Any example to override header component?

**Comment by mbrn** [comment]
You can look at component overriding examples at docs:
https://mbrn.github.io/material-table/#/docz-examples-10-example-component-overriding

**Comment by vijthang61** [comment]
but I need some example on how to write code where I combine filter and header together in one line, can you help me with this

**Comment by mbrn** [comment]
@vijthang61 ,

This is not a easy change. You should develop your own header component that handles every feature of default header and default filter row. 

But i don't know what you exactly want? Can you show me an example? such as another datatable
