### ISSUE TITLE
Error when re-rendering after async API data update called in `onCellEditApproved`

### ISSUE THREAD

**Issue by glassblowerscat** [mbrn/material-table#2412]
[Demo](https://codesandbox.io/s/material-table-editable-cell-promise-handling-error-demo-97y1d?file=/src/index.js:651-661)

**Describe the bug**
When making an API call in `onCellEditApproved` and using the "loading" state provided by the API client to dynamically render the table component, the following development errors will be thrown in the browser console:

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in MTableEditCell (created by WithTheme(MTableEditCell))
    in WithTheme(MTableEditCell) (created by MTableBodyRow)
    in tr (created by ForwardRef(TableRow))
    in ForwardRef(TableRow) (created by WithStyles(ForwardRef(TableRow)))
    in WithStyles(ForwardRef(TableRow)) (created by MTableBodyRow)
    in MTableBodyRow (created by MTableBody)
    in tbody (created by ForwardRef(TableBody))
    in ForwardRef(TableBody) (created by WithStyles(ForwardRef(TableBody)))
    in WithStyles(ForwardRef(TableBody)) (created by MTableBody)
    in MTableBody (created by Droppable)
    in table (created by ForwardRef(Table))
    in ForwardRef(Table) (created by WithStyles(ForwardRef(Table)))
    in WithStyles(ForwardRef(Table)) (created by Droppable)
    in div (created by Droppable)
    in div (created by Droppable)
    in div (created by Droppable)
    in Droppable (created by ConnectFunction)
    in ConnectFunction
    in ConnectFunction (created by MaterialTable)
    in div
    in Unknown (created by WithStyles(Component))
    in WithStyles(Component) (created by MaterialTable)
    in div (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (created by Container)
    in Container (created by MaterialTable)
    in Provider (created by App)
    in App (created by ErrorBoundary)
    in ErrorBoundary (created by DragDropContext)
    in DragDropContext (created by MaterialTable)
    in MaterialTable
    in Unknown (created by WithStyles(Component))
    in WithStyles(Component) (at src/index.js:63)
```
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in MaterialTable
    in Unknown (created by WithStyles(Component))
    in WithStyles(Component) (at src/index.js:63)
```

**To Reproduce**
1. Open the above demo in CodeSandbox
2. Click in one of the editable cells and change the value
3. Note that the above errors appear in the console

**Expected behavior**
Promises should be properly handled by `onCellEditApproved` so that if the table re-renders as a result of an asynchronous data update/loading state change, no memory leak occurs.

**Desktop (please complete the following information):**

- OS: MacOS 10.15.4
- Browser: Chrome
- Version: 84.0.4147.135

**Smartphone (please complete the following information):**

**Additional context**

My original use case was with the Apollo Client. In `onCellEditApproved`, I would call a mutation that, upon completion, would refetch the query providing the data to the`<MaterialTable>` component. Apollo client queries provide a `loading` state value that is commonly used the way I'm using it:

```
const MyComponent = () => {
  const { data, loading } = useQuery(MY_QUERY);

  return loading ? null : (
    <MaterialTable data={data} {...rest} />
  )
}
```

In my demo, I have mocked this up using an async wrapper around `localStorage`.

**Comment by glassblowerscat** [comment]
Update: The first of the two errors above goes away if, instead of doing what I describe at the end of my original post, I do this:

```
const MyComponent = () => {
  const { data, loading } = useQuery(MY_QUERY);

  return <MaterialTable data={data} isLoading={loading} {...rest} />
}
```

This is obviously still a problem—both because there's one error remaining, and also because I ought to be able to do the other version without any issues... it's a very common pattern.

**Comment by glassblowerscat** [comment]
BUMP

**Comment by saunlani** [comment]
bump

**Comment by lucabelmonte** [comment]
bump

**Comment by glassblowerscat** [comment]
bump

**Comment by glassblowerscat** [comment]
bump
