### ISSUE TITLE
Fill column on another column value change before submitting

### ISSUE THREAD

**Issue by mindaugasnakrosis** [mbrn/material-table#2413]
I tried not to post an issue here respecting the contributors time and asked the question on stackoverflow.
However - no response, so I'll post here too.

I have two columns in my material-table.

- Product
- Product price

Columns:

```
const columns = [
  {
    title: 'Product',
    field: 'product',
    editComponent: props => {
      return (
        <Autocompleter
          onChange={props.onChange}
        />
      );
    },
  },
  {
    title: 'Price',
    field: 'price',
    editable: 'never'
  }
};

```
On first column (**product**) value change, I want to make second column value the **price** of **product**. **Price** column is not editable. It is decided on what **product** I choose (1st column)

https://stackoverflow.com/questions/63649390/material-table-conditional-column-edit-value

**Comment by mindaugasnakrosis** [comment]
@mbrn is this possible at the moment?

**Comment by mindaugasnakrosis** [comment]
Anyone had a similar problem?

**Comment by mindaugasnakrosis** [comment]
not stale

**Comment by fofederico** [comment]
+1 Here, @mindaugasnakrosis could you solve the problem?
