### ISSUE TITLE
How to change editComponent's alignment

### ISSUE THREAD

**Issue by eymentopcuoglu** [mbrn/material-table#2417]
Default alignment of a currency type column is 'right':

![alignRight](https://user-images.githubusercontent.com/48262971/92189461-60206780-ee67-11ea-9094-2e6fcb279f17.PNG)

I've changed it to 'left':

![alignLeft](https://user-images.githubusercontent.com/48262971/92189480-6a426600-ee67-11ea-8c2a-32481f075b3d.PNG)

But the editComponent's alignment remained the same: 

![editComponent](https://user-images.githubusercontent.com/48262971/92189506-7af2dc00-ee67-11ea-98ac-1c9719574c0f.PNG)

Here is the corresponding code section:

```
columns={[
                {title: 'Tarih', field: 'date', type: 'date', dateSetting: {locale: 'tr-TR'}},
                {title: 'Malzeme', field: 'description'},
                {
                    title: 'Fiyat',
                    field: 'price',
                    type: 'currency',
                    currencySetting: {currencyCode: 'TRY', locale: 'tr-TR'},
                    align: 'left'
                },
            ]}
```

**Comment by glassblowerscat** [comment]
I ended up using a wrapped component to style the `div` inside the table cell:

```
import { MTableCell } from 'material-table';

const TableCell = withStyles({
  root: {
    '& > div': {
      ... styles
    },
  },
})(MTableCell);

{...}

<Table
    {...props}
    components={{
      Cell: (props) => <TableCell {...props} />,
  }}
/>
```
