### ISSUE TITLE
Material Table is hanging the browser on adding, updating and deleting rows one by one continuously

### ISSUE THREAD

**Issue by VictorPotes** [mbrn/material-table#2418]
Hello Team, this material-table is incredible and it helps a lot of people as well, thank you so much for your support! The issues that I'm facing are the following:

**Describe the bug**
1.  When I add rows one by one continuously, around the 10th row the material-table hangs the browser and I have to refresh the page.
2.  When I update rows one by one continuously, around the 10th row the material-table hangs the browser and I have to refresh the page.
3.  When I delete rows one by one continuously, around the 10th row the material-table hangs the browser and I have to refresh the page.
4.  When I do a mix of CRUD of rows one by one continuously, around the 10th row the material-table hangs the browser and I have to refresh the page.

**Expected behavior**
What I expect to happen is that I would like to do a CRUD continuously without to refresh the browser because it's hanged by the material-table.

**Screenshots**
The browser is hanging
![image](https://user-images.githubusercontent.com/25420216/92208001-e0d36980-ee4f-11ea-8307-d9f05153e22a.png)
This is the table
![image](https://user-images.githubusercontent.com/25420216/92208321-8edf1380-ee50-11ea-965d-42aae0a227f8.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Google Chrome

**Additional context**
The server is working well and I can do a CRUD continuously with other alternatives.

Again thank you so much for your support, I hope you can replicate this issue and solve it for next releases.

**Comment by bvenkatr10** [comment]
I have a similar problem exactly as described above except my OS is mac. Additionally, repeatedly updating a row is causing the page to hang too.

**Comment by Nsquik** [comment]
Had the same problem, installing older version (1.52.0, u can try newer ones) fixed the problem for me 👍

**Comment by VictorPotes** [comment]
@Nsquik Thank you for your support. I tried the 1.68.0 version and it didn't work. I'll try with the 1.52.0 version.

**Comment by pskrajnyy** [comment]
@VictorPotes  do you resolve this problem?

**Comment by VictorPotes** [comment]
@pskrajnyy I returned to 1.67.0 version and it worked again

**Comment by SheikhJuned** [comment]
> Had the same problem, installing the older version (1.52.0, u can try newer ones) fixed the problem for me 👍
> 
> Edit:
> Tried version 1.68.0 -> Works flawlessly
> Tried version 1.69.0 -> Hangs the browser on frequent data change.

I triad it and work fine by downgrade to 1.68.0

**Comment by lbuscherX** [comment]
I ended up reverting all the way back to 1.52 (I could probably inch it forward to newer versions but it works fine for me right now). 1.69, 1.68, and 1.67 all freeze up.

**Comment by CodeMasterZeroOne** [comment]
Had this issue as well,
**Returned to 1.67.0** and it's back to normal.
User is able to update row by row and it does not freeze the browser.

**Comment by alexdobsom** [comment]
I have this logic in the table but it's crashing after **two** interactions with the action buttons. I used multiple versions -- some are worse (crashes only after one interaction)
```javascript
options={{ 
         rowStyle: (rowData) => ({
                backgroundColor: rowData.highlighted === true ? "#ffeb3b5c" : ""
                color: rowData.red === true ? "red" : "", 
          })
}}
```
I don't know what to do😐

**Comment by peacechen** [comment]
Unfortunately mbrn is inactive and not merging PR's. Use the official community fork [@material-table/core ](https://github.com/material-table-core/core)instead.

**Comment by amisoliman** [comment]
> Had the same problem, installing the older version (1.52.0, u can try newer ones) fixed the problem for me 👍
> 
> Edit:
> Tried version 1.68.0 -> Works flawlessly
> Tried version 1.69.0 -> Hangs the browser on frequent data change.

Downgrading to 1.52.0, also fixed the issue for me. Thanks

**Comment by deivid-01** [comment]
> Had the same problem, installing the older version (1.52.0, u can try newer ones) fixed the problem for me 👍
> 
> Edit:
> Tried version 1.68.0 -> Works flawlessly
> Tried version 1.69.0 -> Hangs the browser on frequent data change.

Works perfectly! 😄

**Comment by rakeshseal0** [comment]
> Had the same problem, installing the older version (1.52.0, u can try newer ones) fixed the problem for me 👍
> 
> Edit: Tried version 1.68.0 -> Works flawlessly Tried version 1.69.0 -> Hangs the browser on frequent data change.

This answer saved my day! use 1.68.0

**Comment by harisali10** [comment]
Hi All , My project contains Mui5 When I downgraded Material Table from ^2.0.3 to 1.68.0 . My app hanged issues get resolved however It dramatically changed the layout design of my app . Any suggestion . It only happens when I open the Material table respective page .
