### ISSUE TITLE
Add search reset option

### ISSUE THREAD

**Issue by pcolbert** [mbrn/material-table#242]
**Is your feature request related to a problem? Please describe.**
No integrated search clear/reset

**Describe the solution you'd like**
Display the typical small, circled x in right of search bar to clear and reset search

**Describe alternatives you've considered**
Already have added custom action using isFreeAction (i.e. Add), so could also add a reset action icon, but I also like the column and export toolbar action items, so a reset icon would be after these standard actions. An integrated solution would be the most elegant approach.

**Additional context**

**Comment by mbrn** [comment]
I will do this enhacement for next releases.

**Comment by mbrn** [comment]
This is done. You can use version 1.20.0
