### ISSUE TITLE
How to position the add row to the first position instead the last position on the table?

### ISSUE THREAD

**Issue by VictorPotes** [mbrn/material-table#2421]
Hi team! I need to position the add row on the first position on the table, but I haven't found the way in the documentation.

- #### Please include a demo of the issue/behavior/question you have
#### This is how appears now:

![image](https://user-images.githubusercontent.com/25420216/92320525-b2889200-efe7-11ea-9162-93ecb2ca3393.png)

#### This is how I need the add row appears:

![image](https://user-images.githubusercontent.com/25420216/92320570-072c0d00-efe8-11ea-8ec3-cdf6a6fd599e.png)

- #### Please try to be as detailed as possible
When I click on the add button, the add row appears in the last position on the table, the problem is when there are around 20 rows in the table, the user has to scrolldown to add the new row. What I need is that add row appears in the first position on the table, thus if there are a lot of rows in the table, the user doesn't need to scrolldown to add a new row.

Thank you so much for your support.

**Comment by mackankowski** [comment]
I think the `options.addRowPosition` with `first` value is what you’re looking for. 

See more:
https://material-table.com/#/docs/all-props

**Comment by VictorPotes** [comment]
@mackankowski That's exactly what I was looking for, thank you so much!
