### ISSUE TITLE
Bulk edit missing localization

### ISSUE THREAD

**Issue by Lurtt** [mbrn/material-table#2424]
I would like to change the tooltip of bulk edit after hover, but there is no key to change the translation

https://material-table.com/#/docs/features/localization

**Comment by bernardobgam** [comment]
Doesn't appear in the documentation but the localization keys appear to be body.bulkEditTooltip, body.bulkEditApprove, body.bulkEditCancel

**Comment by makkahwi** [comment]
Ya
"Edit All", "Save All Changes", "Discard All Changes" seem not to be localize-able
