### ISSUE TITLE
The `editable` field in the ColumnDef does not work if a function is specified

### ISSUE THREAD

**Issue by stgraham2000** [mbrn/material-table#2427]
The editable field in the column definition is supposed to support a function or a string literal but if a function is specified then the function is not called in order to determine if the field should be rendered as editable or not.

**To Reproduce**

The following code snippet can be used to reproduce the problem:

```
interface RowData {
  animal: string;
  count: number;
}

const columns: Column<RowData>[] = [
  { title: "Animal", field: "animal", editable: "never" },
  { title: "Count", field: "count", editable: (_, row) => {
    return false /* This doesn't have any affect */
  }},
];

const data: RowData[] = [
  { animal: "Cow", count: 20 },
  { animal: "Pig", count: 30 },
  { animal: "Duck", count: 50 },
  { animal: "Horse", count: 5 },
  { animal: "Chicken", count: 40 },
];

export const Default = () => (
  <BaseMaterialTable
    columns={columns}
    data={data}
    cellEditable={{
      onCellEditApproved: (newValue, _1, _2, _3) => {
        return new Promise((resolve, reject) => {
          console.log("newValue: " + newValue);
          setTimeout(resolve, 1000);
        });
      },
    }}
  />
);
```

**Expected behavior**

It's expected that the `count` field would not be rendered as editable if the function above always returns `false` and if you alter the function to return `true` then the field should be rendered as editable.  This code shows that the field is rendered as editable no matter what the return value is.

**Desktop (please complete the following information):**

- OS: macOS Catalina - 10.15.5
- Browser Chrome v85
- material-table version: 1.69.0

**Comment by Ericxgao** [comment]
I am still running into this issue - what are my options here?
