### ISSUE TITLE
Trying to call onQueryChange(), but tableRef.current is always null

### ISSUE THREAD

**Issue by Azteker** [mbrn/material-table#2432]
```
function InstanceTable() {
    const tableRef = React.createRef();
    const reloadTableData = () => {
       tableRef.current.onQueryChange();
    };

    return (
    <MaterialTable
      title="Instance"
      tableRef={tableRef}
      ...
    />
}
```
When reloadTableData is called, tableRef.current is null.

**Comment by wasuaje** [comment]
Same issue here!

**Comment by e-hop** [comment]
+1

**Comment by e-hop** [comment]
workaround:

Declare the ref as global, outside your main function.
![Uploading image.png…]()

**Comment by kepelrs** [comment]
If you don't want a global ref: replace `const tableRef = React.createRef();` with `const tableRef = React.useRef();` instead. Worked for me.

**Comment by giladbr** [comment]
The solution above worked for me!
"if you don't want a global ref: replace const tableRef = React.createRef(); with const tableRef = React.useRef(); instead. Worked for me.".

**Comment by spars57** [comment]
Thank you bro, I was stuck here for 2 hours. Replacing createRef() for useRef() fixed the problem for me.
