### ISSUE TITLE
Poor performance. Page gets unresponsive

### ISSUE THREAD

**Issue by DewangS** [mbrn/material-table#2433]
In my functional component, I've a simple table which gets populated via axios call to my NodeJs(Express) based API with minimal data. In my table I don't do any fancy rendering etc. I am getting severe lagging in page rendering. I've debugged the code and can confirm that there are no issues with my APIs as they work perfectly fine with native Material UI table. For now I am switching back to MUI native tables. 

My package details are as per below ...

**"@material-ui/core": "^4.11.0",
"@material-ui/icons": "^4.9.1",
"material-table": "^1.69.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",**

Browser : Chrome Version 85.0.4183.83 (Official Build) (64-bit)

Env. : MacOS Mojave 10.14.5

**Comment by riyaarora65** [comment]
I am also getting the same issue from tomorrow.

**Comment by sharmaadvay0** [comment]
Same issue.

**Comment by JongtaekChoi** [comment]
I think it may work to remove the `tableData` attribute of each item of the columns of props at render function.

**Comment by peacechen** [comment]
This was fixed in PR #2689

Unfortunately mbrn is inactive and not merging PR's.  Use the official community fork [@material-table/core](https://github.com/material-table-core/core) instead.

**Comment by dalbir** [comment]
For me rowStyle is the problem, for now removed that. But I think @mbrn should merge the PRs

**Comment by jhoanborges** [comment]
> For me rowStyle is the problem, for now removed that. But I think @mbrn should merge the PRs

This was my solution too. Thank you so much
