### ISSUE TITLE
Close an expanded detailPanel

### ISSUE THREAD

**Issue by vbtux** [mbrn/material-table#2437]
How to close an expanded detailPanel when I click the button on it

```
detailPanel = {
    [
        rowData => ({
            icon: "chevron_left",
            openIcon: "expand_more",
            render: () =>
                <div onClick={() => closeExpandedPanel()}>
                    {rowData.nameObject}
                </div>,
        }),
        ]
      }
```

**Comment by corneliushka** [comment]
in the onClick method, insert this ; it will toggle the detail panel linked to your row : 

tableRef.current.onToggleDetailPanel([rowData.tableData.id], tableRef.current.props.detailPanel)
