### ISSUE TITLE
I want to show the filters in the same row along with column headers and not as a separate header. Let me know how to achieve this.

### ISSUE THREAD

**Issue by vijthang61** [mbrn/material-table#244]
I am requesting this to avoid duplicating same code again while overriding components

**Comment by mbrn** [comment]
@vijthang61 ,

This is not a easy change. You should develop your own header component that handles every feature of default header and default filter row.

But i don't know what you exactly want? Can you show me an example? such as another datatable

**Comment by vijthang61** [comment]
![image](https://user-images.githubusercontent.com/47169215/53019406-aaefaf80-347a-11e9-8b37-862ff0c16600.png)

I want to have filters on same line as column header in this image

**Comment by vijthang61** [comment]
I managed to get the filter on same line by setting the title

Whatever value i display in title that i had modified by creating custom function

renderColumnHeader = (title,field,lookup) => {
    return(
      <div style={{display:"flex"}}>
        <div>
          {title}
        </div>
        <div>
          {lookup===undefined &&<TextField
                id={field}
                value={this.state.filter}
                onChange={this.onFilterChanged}               
            />}
            {lookup && 
              <FormControl style={{ width: '100%' }}>
                <Select
                  multiple
                  value={this.state.filter || []}
                  onChange={this.onFilterChanged} 
                  input={<Input id="select-multiple-checkbox" />}
                  renderValue={selecteds => selecteds.map(selected => lookup[selected]).join(', ')}
                  MenuProps={MenuProps}
                >
                  {
                    Object.keys(lookup).map(key => (
                      <MenuItem key={key} value={key}>
                        <Checkbox checked={this.state.filter && this.state.filter.indexOf(key.toString()) > -1} />
                        <ListItemText primary={lookup[key]} />
                      </MenuItem>
                    ))
                  }
                </Select>
              </FormControl>
            }
        </div>
      </div>
    );
  }

But the problem is since the columns are sortable, when I click  on the filter field it first applies sort, so now the complication is to sort only when clicked on header name and not the filter field.

**Comment by mbrn** [comment]
You may implement your own header component. So you can handle all events and manage them according to your project.
