### ISSUE TITLE
Grouping: Remove "empty column"

### ISSUE THREAD

**Issue by gnusmaslled** [mbrn/material-table#2445]
How to remove the "white space column" in the table that is caused by the group column?

When data is grouped, the column used for grouping takes a lot of "empty space" in the table when expanding it.

Example:

```
function DefaultGroupedField() {
  return (
    <MaterialTable
      title="Default Grouped Field Preview"
      columns={[
        { title: 'Name', field: 'name', defaultGroupOrder: 0 },
        { title: 'Surname', field: 'surname' },
        { title: 'Birth Year', field: 'birthYear', type: 'numeric' },
        {
          title: 'Birth Place',
          field: 'birthCity',
          lookup: { 34: 'İstanbul', 63: 'Şanlıurfa' },
        },
      ]}
      data={[
        { name: 'Mehmet', surname: 'Baran', birthYear: 1987, birthCity: 63 },
        { name: 'Mehmet', surname: 'Ali', birthYear: 1987, birthCity: 63 },
        { name: 'Zerya Betül', surname: 'Baran', birthYear: 2017, birthCity: 34 },
      ]}        
      options={{
        grouping: true,
        header: false
      }}
    />
  )
}
```

I would like to remove the "white space" caused by the name column and instead have the column with the surname to be displayed more to the left so that "Baran" and "Ali" align left with the title of the grouped field (which is "**Name:** Mehmet" in this case).

![image](https://user-images.githubusercontent.com/66059526/92907130-5aa5bd00-f425-11ea-8df0-717f4e4e8652.png)

**Comment by asifkabani** [comment]
Came here looking for the solution to this as well, any ideas?
