### ISSUE TITLE
Table with checkbox errors

### ISSUE THREAD

**Issue by shmoshkin** [mbrn/material-table#245]
hi'
i copied the table from the doc and got this error:
failed prop type - invalid prop value of type number suplied to checkbox, expected string

**Comment by mbrn** [comment]
I will look at this asap.

**Comment by shmoshkin** [comment]
@mbrnI have another problem that maybe connected to this one. when going through the next page and select checkbox, it always selects the one in the same row of the first page.

**Comment by mbrn** [comment]
Yes this is known bug and i fixed it in v1.18.0. Please upgrade your material-table dependency

**Comment by mbrn** [comment]
This is done with 1.19.2
