### ISSUE TITLE
Material-table breaking material ui css 

### ISSUE THREAD

**Issue by ninew089** [mbrn/material-table#2452]
<img width="1001" alt="Screen Shot 2563-09-13 at 12 57 43" src="https://user-images.githubusercontent.com/57795422/93011556-65955480-f5c1-11ea-8fbd-b86d716b6e19.png">
when i click page have materail-table
<img width="749" alt="Screen Shot 2563-09-13 at 12 58 11" src="https://user-images.githubusercontent.com/57795422/93011564-7219ad00-f5c1-11ea-8d4f-2a1e3cc75740.png">
after 
<img width="881" alt="Screen Shot 2563-09-13 at 12 58 23" src="https://user-images.githubusercontent.com/57795422/93011571-81005f80-f5c1-11ea-9cfc-6002cc5793e0.png">
back login page

**Comment by braulioaliaga** [comment]
I have the same issue
Any solution?
