### ISSUE TITLE
data update of the table freezes the browser and lock the program in new version !

### ISSUE THREAD

**Issue by nightwolf-041** [mbrn/material-table#2453]
hi,
 I used to use the table without any problems, but yesterday I **update it to the latest version(1.69.0)** and stumbled into a big problem.
When I update the data, the browser freezes and the application becomes locked !!

It's enough to re fetch the data several times to see this problem.

**Comment by airspin** [comment]
have the same issue

**Comment by Daniel371** [comment]
Same here. First thought I'm creating too many re renders which freezes the table, but have checked and tested everything and so far looks like it is material-table issue. At first data fetch everything was working fine and then, on second or third data fetch browser freeze.

**Comment by Daniel371** [comment]
> hi,
> I used to use the table without any problems, but yesterday I **update it to the latest version(1.69.0)** and stumbled into a big problem.
> When I update the data, the browser freezes and the application becomes locked !!
> 
> It's enough to re fetch the data several times to see this problem.
> 
> #### of course, no problem from version 1.67.0 down to the bottom.

I had the same issue and I can confirm that this is material-table issue. I have downgraded to version 1.61.0 and everything works perfect. Just do **npm install material-table@1.61.0**

**Comment by janderson215** [comment]
I have the same issue with 1.69 - took me a while to figure out it was an issue with material-table and not with my code. Downgrading to 1.68 fixed the issue for me, but I really want to be able to disable that PDF export button :(

**Comment by nightwolf-041** [comment]
> > hi,
> > I used to use the table without any problems, but yesterday I **update it to the latest version(1.69.0)** and stumbled into a big problem.
> > When I update the data, the browser freezes and the application becomes locked !!
> > It's enough to re fetch the data several times to see this problem.
> > #### of course, no problem from version 1.67.0 down to the bottom.
> 
> I had the same issue and I can confirm that this is material-table issue. I have downgraded to version 1.61.0 and everything works perfect. Just do **npm install material-table@1.61.0**

### You can use Version 1.67.0, It works well, too.

**Comment by nightwolf-041** [comment]
> I have the same issue with 1.69 - took me a while to figure out it was an issue with material-table and not with my code. Downgrading to 1.68 fixed the issue for me, but I really want to be able to disable that PDF export button :(

**All you need to do is add this option**
```
 options={{
     exportButton: false
 }}
```

**Comment by janderson215** [comment]
Yes, but isn’t that only in version 1.69+?

**Comment by peacechen** [comment]
Unfortunately mbrn is inactive and not merging PR's. Use the official community fork [@material-table/core ](https://github.com/material-table-core/core)instead.

**Comment by janderson215** [comment]
> Unfortunately mbrn is inactive and not merging PR's. Use the official community fork [@material-table/core ](https://github.com/material-table-core/core)instead.

Thanks for the heads up. Any word on what happened? I hope he and his family are ok!
