### ISSUE TITLE
Make filter row sticky along with header row

### ISSUE THREAD

**Issue by mukesh-pathak-by** [mbrn/material-table#2454]
Hi,

Is there any way to make filter row sticky along with header.
I could not find a nice way to do that so i went ahead by modifying filter style.

filterCellStyle: { backgroundColor: 'white', position: 'sticky', top: 40, padding: "3px 5px 5px", height: 40 },

But the problem with above implementations is checkbox column is not consider as part of filtercell so that scroll along,

![image](https://user-images.githubusercontent.com/62742570/93078550-49b8ae00-f6a8-11ea-9587-8b9fd12b2f05.png)

Is there any way to fix that.
Thanks in Advance

**Comment by mackankowski** [comment]
@mukesh-pathak-by - try setting `filterRowStyle` in table's `options`:

```
   filterRowStyle: {
       position: "sticky",
       top: 100,
       background: 'white,
       zIndex: 5 /* optionally */
   },
```

To match `top` attribute with a sticky header, also add:

```
   headerStyle: {
       height: 100,
   } 
```

Good luck!

**Comment by mackankowski** [comment]
@mukesh-pathak-by let's see my anwser: https://github.com/mbrn/material-table/issues/1521#issuecomment-883499349
