### ISSUE TITLE
What should i do to know where the cell i edited to change with newValue? 

### ISSUE THREAD

**Issue by bhangun** [mbrn/material-table#2456]
I want to make the table cell editable, so i used cellEditable as below.
but i didn't know where the cell i edited (row and column index), so i can't change the old value. Instead i can change the oldValue with newValue parameter.

Did i missed something with the API or documentation ?
Because i didn't found the example in the documentation or others.

**Describe the bug**
1) not enough resources/API
2) object-shorthand occured to thi line code
` onCellEditApproved: (newValue, oldValue, rowData, columnDef) => {`
so i added this comment
```
         /* eslint object-shorthand: "error" */
        /* eslint-env es6 */
        onCellEditApproved: (newValue, oldValue, rowData, columnDef) => {
```

![image](https://user-images.githubusercontent.com/124742/93186593-03775380-f769-11ea-9b17-aa063ce7a79e.png)

**To Reproduce**
```
<MaterialTable
      title="Example table"
      columns={state.columns}
      data={state.data}
      cellEditable={{
        onCellEditApproved: (newValue, oldValue, rowData, columnDef) => {
          return new Promise((resolve, reject) => {
            /* console.log('newValue: ' + newValue);  */
              setState((prevState) => {
              const data = [...prevState.data];
              /* ..... */
              return { ...prevState, data };
            }); 
            setTimeout(resolve, 1000);
          });
        }
      }}
/>
```
**Expected behavior**
Row and column index i was edited.
Or parameter/variable/API something like that.

**Screenshots**

**Desktop (please complete the following information):**

- OS: MacOS
- Browser  chrome, safari
- Version 22

**Comment by bhangun** [comment]
I just found to solved this issue, which is found the field/cell you just edited. 
**columnDef.field** tell where the cell you just edited, then map it to **rowData**.
just like this:
` rowData[columnDef.field] = newValue`

and this is the complete ones:
```
<MaterialTable
      title="Example table"
      columns={state.columns}
      data={state.data}
      cellEditable={{
        onCellEditApproved: (newValue, oldValue, rowData, columnDef) => {
          return new Promise((resolve, reject) => {
              setState((prevState) => {
              const data = [...prevState.data];
             rowData[columnDef.field] = newValue
              return { ...prevState, data };
            }); 
            setTimeout(resolve, 1000);
          });
        }
      }}
/>
```

**Comment by bhangun** [comment]
but about warning object-shorthand i still solved with add this comments.

```
/* eslint object-shorthand: "error" */
/* eslint-env es6 */
```

**Comment by lynnhardy** [comment]
This is the most comprehensive documentation I've found on the onCellEditApproved method. Thank you for sharing. You saved me additional hours trying to figure out that black box.
