### ISSUE TITLE
Empty Header Space material table issue

### ISSUE THREAD

**Issue by Adithya-codes** [mbrn/material-table#2458]
![Screenshot (183)](https://user-images.githubusercontent.com/62156166/93201669-2147b700-f76f-11ea-8e9a-a92d42365763.png)

Hi there ,  i removed the default search feature of the material table ,is there a way around now to remove the header white space above the columns , and push the columns up so that there is no 
empty space

**Comment by Puterism** [comment]
If you want to hide toolbar, you can replace to `null` on `components` props.

```
<MaterialTable
  {...props}
  components={{
    Toolbar: () => <></>,
  }}
/>
```

But, I think it's a bug. It's not appropriate to display an empty toolbar.
Doesn't it look good to be hidden when not using the toolbar feature?
