### ISSUE TITLE
Free actions disappear on row selection

### ISSUE THREAD

**Issue by hewby** [mbrn/material-table#2459]
I've seen a couple of issues surrounding the behaviour of the selection actions. I recognise that @mbrn prefers single row actions not to be available on selecting multiple rows which is fair, but the current behaviour doesn't seem to allow a button present but disabled until rows are selected. This is because free actions, along with row actions, are being removed on selection.

![Material_Table_No_Selection](https://user-images.githubusercontent.com/54192575/93236936-55bf7100-f777-11ea-8cf7-5f60bb6149a4.png)
![Material_Table_One_Selection](https://user-images.githubusercontent.com/54192575/93236937-56580780-f777-11ea-86b8-7ee774bc2f14.png)

In this example, the view columns button is disappearing on selection of rows, which is unexpected since there's no reason it should be affected by the selection. I want to be able to put a disabled button in the toolbar and then enable it when a selection is made, which is why my delete button is a free action (we use fontawesome instead of material icons, which is why the delete button isn't rendering properly yet). Unfortunately this disappears as well and can't be replaced using a custom render since it isn't in a column.

How can I get toolbar buttons which accept the data passed from a selection, and should I raise the disappearing columnsButton as a bug?

**Comment by dimitrie-agafitei-FNR** [comment]
Anyone working on this issue? This is quite a bug
