### ISSUE TITLE
onSelectionChange and React Hooks causes a re-render that overwrites the tableData checked true

### ISSUE THREAD

**Issue by zachrickards** [mbrn/material-table#2460]
```
const [selectedAthletes, setSelectedAthletes] = useState([]);

<MaterialTable
    icons={tableIcons}
    localization={{
        header: {
            actions: '',
        },
    }}
    options={{
        actionsColumnIndex: -1,
        draggable: false,
        filtering: true,
        pageSize: 10,
        paging: true,
        search: false,
        showTitle: false,
        toolbar: false,
        selection: true
    }}
    columns={COLUMNS}
    data={athletes || []}
    isLoading={isNil(athletes) || isLoading}
    onSelectionChange={rows => {
         setSelectedAthletes(rows);
    }}
/>
```
- #### Please try to be as detailed as possible
The above code causes tableData to go from { id: 0, checked: true } and then the re-render happens and it's back to { id: 0 }

**Expected behavior**
Either re-render does not happen as a prop of the table didn't change or a re-render merges table data

**Comment by supervanya** [comment]
I am experiencing the same issue, this is critical for our feature and I can't find a workaround besides not using state, but then I can't seem to find an easy way to tell table which checkboxes should be checked on load

**Comment by stkaspar** [comment]
same here, waiting for the fix
