### ISSUE TITLE
How customize color and size of Toolbar icons?

### ISSUE THREAD

**Issue by PedrinhowVieira** [mbrn/material-table#2464]
I am trying to edit the color and size of the Toolbar icons. I manage to do it on custom actions added by passing a Icon component form Material-UI, like this:

```
icon: () => <ChangeHistoryIcon style={iconStyle} />,
        tooltip: 'some tooltip',
        isFreeAction: true,
        onClick: () => handleClick(),
```
The issue occurs when I add the export functionality, I do not have control over the icon and I achieve something like this:

![image](https://user-images.githubusercontent.com/45289640/93346416-55bc8100-f80a-11ea-888c-65f28a82ecd1.png)

I tried following the lib's example and also tried some CSS tricks:

```
const useStyles = makeStyles({
  toolbar: {
    color: '#0076CE',
  },
});

components={{
  Toolbar: (properties) => (
    <MTableToolbar {...properties} classes={{ root: classes.toolbar }} />
  ),
}}
```

But then the Title ends up with the color (not wanted) and the Icon stays the same:

![image](https://user-images.githubusercontent.com/45289640/93346875-d24f5f80-f80a-11ea-9653-0a5d2050e576.png)

Any idea how could I achieve this?

**Comment by Jcg408** [comment]
I'm having the same issue. I finally gave up and used old school Css  stylesheet to target. I would love to see a solution to this issue. It seems it  would be have been solved somewhere, somehow.

**Comment by PedrinhowVieira** [comment]
@Jcg408 can you share a sample of your code so I can use the same workaround for now?
