### ISSUE TITLE
Filtering not working for numeric columns ?

### ISSUE THREAD

**Issue by Prasad-YS** [mbrn/material-table#247]
Filtering of columns working for all string columns. but if I try for  numeric it's always shows blank table,
Even for data columns I'm unable to enter the date manually, for time it's taking 'PM' which is not there in my data

**Comment by mbrn** [comment]
I will look at this asap.

**Comment by mbrn** [comment]
This is done with 1.22.3

**Comment by JosephP91** [comment]
The problem is still there in version 1.54.2. Check the attached image to see the problem:

![Capture](https://user-images.githubusercontent.com/4980377/72088131-e05af100-3309-11ea-83b4-f2aa455a8ec3.PNG)
