### ISSUE TITLE
Load remote data using react-query

### ISSUE THREAD

**Issue by chandjenAC** [mbrn/material-table#2474]
Hi, 

Thank you for the effort you have put in developing this library.

I am trying to use "react-query" to load remote data in conjunction with "material-table"...Is there a way to load remote data using the "useQuery" hook provided by "react-query"?..... could you please help me out or give me some suggestions?

Thank you!

**Comment by geochronology** [comment]
Yes it is possible. 

See docs on [remote data](https://material-table.com/#/docs/features/remote-data).

Async data calls need to be structured as a promise. For example:

```
  const { status, data, error } = useQuery('artists', () =>
    fetch('/api/artists').then((x) => x.json())
  )

<div style={{ marginBottom: '20px' }}>
        <h2>React Query Table</h2>
      </div>
      {error && <div>{error}</div>}
      <div>
        {status === 'loading' ? (
          <span>Loading...</span>
        ) : status === 'error' ? (
          <span>Error: {error.message}</span>
        ) : (

              <MaterialTable
                columns={[
                  { title: 'ID', field: 'id' },
                  { title: 'Name', field: 'name' },
                  { title: 'Affinity', field: 'affinity' },
                  { title: 'Popularity', field: 'popularity' }
                ]}

                data={query =>
                  new Promise((resolve, reject) => {
                    resolve({
                      data: data.artists,
                      page: 1,
                      totalCount: 100
                    })
                  })
                }
              />
)}
      </div>

```

**Comment by chandjenAC** [comment]
here what you are trying to do is get the entire data at once using "useQuery" without implementing remote pagination and then pass it to M-Table...in this case M-Table handles the pagination for you ...but what if I want to use "usePaginatedQuery" instead of "useQuery"... and get the next page data only when the user clicks on next page..

**Comment by chandjenAC** [comment]
here what you are trying to do is get the entire data at once using "useQuery" without implementing remote pagination and then pass it to M-Table...in this case M-Table handles the pagination for you ...but what if I want to use "usePaginatedQuery" instead of "useQuery"... and get the next page data only when the user clicks on next page..

**Comment by chandjenAC** [comment]
> Yes it is possible.
> 
> See docs on [remote data](https://material-table.com/#/docs/features/remote-data).
> 
> Async data calls need to be structured as a promise. For example:
> 
> ```
>   const { status, data, error } = useQuery('artists', () =>
>     fetch('/api/artists').then((x) => x.json())
>   )
> 
> <div style={{ marginBottom: '20px' }}>
>         <h2>React Query Table</h2>
>       </div>
>       {error && <div>{error}</div>}
>       <div>
>         {status === 'loading' ? (
>           <span>Loading...</span>
>         ) : status === 'error' ? (
>           <span>Error: {error.message}</span>
>         ) : (
> 
>               <MaterialTable
>                 columns={[
>                   { title: 'ID', field: 'id' },
>                   { title: 'Name', field: 'name' },
>                   { title: 'Affinity', field: 'affinity' },
>                   { title: 'Popularity', field: 'popularity' }
>                 ]}
> 
>                 data={query =>
>                   new Promise((resolve, reject) => {
>                     resolve({
>                       data: data.artists,
>                       page: 1,
>                       totalCount: 100
>                     })
>                   })
>                 }
>               />
> )}
>       </div>
> ```

here what you are trying to do is get the entire data at once using "useQuery" without implementing remote pagination and then pass it to M-Table...in this case M-Table handles the pagination for you ...but what if I want to use "usePaginatedQuery" instead of "useQuery"... and get the next page data only when the user clicks on next page..

**Comment by chandjenAC** [comment]
> Yes it is possible.
> 
> See docs on [remote data](https://material-table.com/#/docs/features/remote-data).
> 
> Async data calls need to be structured as a promise. For example:
> 
> ```
>   const { status, data, error } = useQuery('artists', () =>
>     fetch('/api/artists').then((x) => x.json())
>   )
> 
> <div style={{ marginBottom: '20px' }}>
>         <h2>React Query Table</h2>
>       </div>
>       {error && <div>{error}</div>}
>       <div>
>         {status === 'loading' ? (
>           <span>Loading...</span>
>         ) : status === 'error' ? (
>           <span>Error: {error.message}</span>
>         ) : (
> 
>               <MaterialTable
>                 columns={[
>                   { title: 'ID', field: 'id' },
>                   { title: 'Name', field: 'name' },
>                   { title: 'Affinity', field: 'affinity' },
>                   { title: 'Popularity', field: 'popularity' }
>                 ]}
> 
>                 data={query =>
>                   new Promise((resolve, reject) => {
>                     resolve({
>                       data: data.artists,
>                       page: 1,
>                       totalCount: 100
>                     })
>                   })
>                 }
>               />
> )}
>       </div>
> ```

thank you for the reply....here what you are trying to do is get the entire data at once using "useQuery" without implementing remote pagination and then pass it to M-Table...in this case M-Table handles the pagination for you ...but what if I want to use "usePaginatedQuery" instead of "useQuery"... and get the next page data only when the user clicks on next page...

thank you

**Comment by cargallo** [comment]
@chandjenAC did you found a solution?

**Comment by allangpio** [comment]
Same problem here, did someone managed to solve it?

**Comment by GyanendroKh** [comment]
Without using the [remote data](https://material-table.com/#/docs/features/remote-data) option provided, I just pass in the data attribute and it works.   
Here is the full source code.   
```typescript
const useMoviePaginationData = () => {
  const [pageSize, setPageSize] = useState(5);
  const [page, setPage] = useState(0);
  const { data, isFetching } = useMovieAll({
    take: pageSize,
    skip: page * pageSize
  });

  return {
    pageSize,
    page,
    totalCount: data?.size ?? 0,
    data: data?.data ?? [],
    isFetching,
    setPage,
    setPageSize
  };
};

export const Movie: FC = () => {
  const { push } = useHistory();
  const {
    pageSize,
    page,
    totalCount,
    data,
    isFetching,
    setPage
  } = useMoviePaginationData();

  return (
    <MaterialTable
      title="Movies"
      icons={tableIcons}
      columns={[
        {
          title: 'Title',
          field: 'title'
        },
        {
          title: 'Description',
          field: 'description'
        }
      ]}
      actions={[
        {
          icon: AddBox,
          isFreeAction: true,
          onClick: () => {
            push('/movie-add');
          }
        }
      ]}
      isLoading={isFetching}
      options={{ pageSize, pageSizeOptions: [pageSize], loadingType: 'linear' }}
      page={page}
      totalCount={totalCount}
      data={data}
      onChangePage={p => {
        setPage(p);
      }}
    />
  );
};
```
You have to provide all `page`, `totalCount` and `data` attribute or else it won't work.

**Comment by cargallo** [comment]
@GyanendroKh I ended up doing something similar
