### ISSUE TITLE
Row Data value shows only last row value inside inner click. 

### ISSUE THREAD

**Issue by abdulhadi1995** [mbrn/material-table#2475]
![image](https://user-images.githubusercontent.com/32241778/93594273-f8256180-f9ce-11ea-9155-46438c839f19.png)
I have attached an image as you can see i m custom rendering a column. When the rowData comes in its absolutely fine for the first IconButton component. The console log there shows the right rowData values. Click on it basically opens a menu that shows other actions Inside the <Menu/> component. Now clicking on a MenuItem, its onClick console log shows the value of only the last rowData entry. Can you please help me out with this. I tried to look for how to customized your actions props but couldn't find anything. So went with this approach. 

![image](https://user-images.githubusercontent.com/32241778/93594493-5d795280-f9cf-11ea-8391-2502812efe00.png)
This is what it looks like on frontend. You click the hamburger icon and this menu pops up. The values are fine on the hamburger click but not fine when clicking these menu items.

**Comment by mayerspitz** [comment]
Thanks for asking this questions and seeing that I'm not completely alone...

I am not sure if this could serve as a solution or as a work around, but it works for me.

- On the button being used to open the menu, I use the onClick event to set the selected menu row which I want to use, and save it to the component state.

    ```
const [slcRow, setSlcRow] = React.useState(null);
    const handleClick = (event, row) => {
        setAnchorEl(event.currentTarget);
        setSlcRow(row);
    };

    <Button 
        aria-controls="simple-menu" 
        aria-haspopup="true" 
        onClick={(event ) => {handleClick(event, row) }}
        >
        Open Menu
    </Button>
```

- In the MenuItem onClick event I check the state to retrieve that row and do the work needed...

  ```
 const handleEditOpen = (event, row) => {
       row = slcRow;
       loadEditData(row.clientId);
       setEdit(true);
       setAnchorEl(null);
   };

   <Menu id="long-menu" anchorEl={anchorEl} keepMounted open={open} onClose={handleClose1}>
       <MenuItem onClick={(event) => { handleEditOpen(event, row) }}>Edit </MenuItem>
   </Menu
```

**Comment by mayerspitz** [comment]
Thanks for asking this questions and seeing that I'm not completely alone...

I am not sure if this could serve as a solution or as a work around, but it works for me.

- On the button being used to open the menu, I use the onClick event to set the selected menu row which I want to use, and save it to the component state.


```
    const [slcRow, setSlcRow] = React.useState(null);
    const handleClick = (event, row) => {
        setAnchorEl(event.currentTarget);
        setSlcRow(row);
    };
```

```
    <Button 
        aria-controls="simple-menu" 
        aria-haspopup="true" 
        onClick={(event ) => {handleClick(event, row) }}
        >
        Open Menu
    </Button>
```

- In the MenuItem onClick event I check the state to retrieve that row and do the work needed...

```
   const handleEditOpen = (event, row) => {
       row = slcRow;
       loadEditData(row.clientId);
       setEdit(true);
       setAnchorEl(null);
   };
```

```
   <Menu id="long-menu" anchorEl={anchorEl} keepMounted open={open} onClose={handleClose1}>
       <MenuItem onClick={(event) => { handleEditOpen(event, row) }}>Edit </MenuItem>
   </Menu
```
