### ISSUE TITLE
Duplicate key in MTableBodyRow while adding new row dynamically

### ISSUE THREAD

**Issue by bmg02** [mbrn/material-table#2478]
Hey there! I am facing an error of having duplicate key in MTableBodyRow while a new row dynamically in the table.

### Goal:
When the user enters the data in the current row, a new row will be created automatically.

### What I have tried:
A const variable to store the new row data.
```
const blankRow = {
    column1: '',
    column2: '',
    column3: '',
    column4: '',
};
```

A state hook to store the user input data in the array.

`const [ valueState, setValueState ] = React.useState(blankRow);`

So, when the user adds some data in the row, I append the blank row in the state variable.
```
const handleValueChange = (e) => {
    let prcses = valueState;
    prcses.push(blankRow);
    setValueState(prcses);
}
```

The code of `<MaterialTable />` is given here.
```
<MaterialTable
    columns={[
        {
            title: 'Column 1',
            field: 'column1',
            render: rowData => <InputField type='number' onChange={ handleValueChange } id={ 'col1-' + rowData.tableData.id } key={ 'col1-' + rowData.tableData.id } />
        },
        {
            title: 'Column 2',
            field: 'column2',
            render: rowData => <InputField type='number' onChange={ handleValueChange } id={ 'col2-' + rowData.tableData.id } key={ 'col2-' + rowData.tableData.id } />
        },
        {
            title: 'Column 3',
            field: 'column3',
            render: rowData => <InputField type='number' onChange={ handleValueChange } id={ 'col3-' + rowData.tableData.id } key={ 'col3-' + rowData.tableData.id } />
        },
        {
            title: 'Column 4',
            field: 'column4',
            render: rowData => <InputField type='number' onChange={ handleValueChange } id={ 'col4-' + rowData.tableData.id } key={ 'col4-' + rowData.tableData.id } />
        },
    ]}
    data={ valueState }
    options={{
        sorting: false,
        search: false,
        toolbar: false,
        paging: false,
        draggable: false,
        tableLayout: 'fixed',
    }}
/>
```

### Issue:
With the above code, I can successfully add a new row. But in the console, showing below error.
`Warning: Encountered two children with the same key, 'row-1'. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.`

How do I solve this? How can I give unique keys to MTableBodyRow?

### Development environment:
> react: 16.13.1
> react-dom: 16.13.1
> material-ui/core: 4.11.0
> material-table: 1.69.0

**Comment by Arlien** [comment]
+ 1

**Comment by Stanley-Yao** [comment]
@mbrn Same issue here, do you have a plan on fix this one? Thanks

**Comment by gjgd** [comment]
I had the same issue, and it was because the `data` prop passed to MaterialTable was a list containing the same object twice.
```js
const books = [book1, book1];
```

Solved by making the second object a copy of the first one
```js
const books = [book1, {... book1} ];
```
