### ISSUE TITLE
jspdf dependency throwing warnings

### ISSUE THREAD

**Issue by rosostolato** [mbrn/material-table#2479]
I upgraded from version `1.65.0` to `1.69.0` and I'm getting warning for `jspdf` that are breaking my gitlab pipeline.

```
./node_modules/jspdf/dist/jspdf.umd.min.js
Critical dependency: the request of a dependency is an expression
```

**Comment by correaricardo** [comment]
Duplicated: mbrn/material-table#2326

**Comment by merobal** [comment]
v1.69.1 is just released, finally 🎉

**Comment by shamoons** [comment]
Still having the same issue with `v1.69.1`

**Comment by merobal** [comment]
Try to delete your package-lock or yarn-lock file and do a clean install

**Comment by SurmaAa** [comment]
bump
