### ISSUE TITLE
2 tables on same component

### ISSUE THREAD

**Issue by shmoshkin** [mbrn/material-table#248]
i got 2 components, each of them with table.
i try to put them 2 in another component but only 1 table is rendered.
seem its impossible to render 2 components wi table - mega bug...

**Comment by mbrn** [comment]
Hi @shmoshkin ,

I use multiple tables in same component in many cases. Can you share your code/structure with me to understand what is wrong with ?

**Comment by shmoshkin** [comment]
@mbrn 
I wrote 2 components. then put them both is a new component and can see both. maybe id problem?

the code very simple:
render(){
<component1/>
<component2/>
}

a table in each of them is exactly like documentation. when put only each of them it works

**Comment by shmoshkin** [comment]
@mbrn fix my own bug, thanks
