### ISSUE TITLE
Mask password column

### ISSUE THREAD

**Issue by amitraja-4606** [mbrn/material-table#2481]
Any workaround for masking a column data as password. 
![image](https://user-images.githubusercontent.com/71187082/93856290-70916880-fcd6-11ea-8724-122b4fff7087.png)
As of now material table has many data type support for columns. 

I have a scenario where I need to mask the password column but I am not able to do it.

![image](https://user-images.githubusercontent.com/71187082/93856725-1513aa80-fcd7-11ea-9f80-82397e412a5d.png)

I have some data in the above columns. How can I mask password column?
Here is my column definition

columns = [
    {
      title: "Tenant",
      field: "name",
      validate: (rowData) =>
        rowData.name === "" ? "Name cannot be empty" : "",
    },
    {
      title: "Username",
      field: "username",
      validate: (rowData) =>
        rowData.username === "" ? "Username cannot be empty" : "",
    },
    {
      title: "Password",
      field: "password",
      type: 'password'
      validate: (rowData) =>
        rowData.password === "" ? "Password cannot be empty" : "",
    },
    {
      title: "Service URL",
      field: "service_url",
      cellStyle: { wordBreak: "break-all" },
      validate: (rowData) =>
        rowData.service_url === "" ? "URL cannot be empty" : "",
    },
    {
      title: "Input Path",
      field: "input_path",
      validate: (rowData) =>
        rowData.input_path === "" ? "Path cannot be empty" : "",
    },
  ];

**Comment by L1ghtman2k** [comment]
https://stackoverflow.com/questions/56939789/how-to-mask-password-with-materialtable/64419072#64419072
