### ISSUE TITLE
Sorting with remote data

### ISSUE THREAD

**Issue by mindaugasnakrosis** [mbrn/material-table#2482]
Using remote data.

1. I click on column to sort by it
2. I get correct `orderBy` and `orderDirection` (_asc_)
3. I click on the same column to sort again.
4. I get correct `orderBy` and incorrect `orderDirection` (_asc again, should be desc now_)
5. I click on the same column to sort again, I expected sort to be disabled for this column now as I already clicked three times.
6. I get incorrect `orderBy` (_should be null_) and incorrect `orderDirection` (desc, should be null now because it is third time I click sort)

Logs screen:

![image](https://user-images.githubusercontent.com/14983636/93858334-a75e8300-fcc4-11ea-9d7f-ae708dfc244a.png)

Material-table version: 1.69.0

**Comment by rohail411** [comment]
I'm also suffering from this issue

**Comment by MaartenCleenders** [comment]
this is also the case is for the pagination and the search

**Comment by mindaugasnakrosis** [comment]
Could you comment on this @mbrn ?

**Comment by RokasDevelopment** [comment]
Ditto, I have the same problem. Waiting for response, thanks!

**Comment by Mizan-Rifat** [comment]
Actually i'm finding this table is totally useless.lot of issues are not resolving.there is problem with search also..

**Comment by TylerEikenberg** [comment]
Also been having this issue for a while now.

**Comment by nmkname** [comment]
I solved it with setting `defaultSort` for each field.
`const [filter, setFilter] = useState({ field: "name", order: "asc" })
...
<MaterialTable
   columns={[
       {
           field: "name",
           title: "name",
           defaultSort: sortField.order,
   ]}
/>
`
However, it has some drawbacks. When you change state, material table sorts your current data by order you provided, so there is glimpse of data visually getting sorted twice. You may change order state after your data is loaded as well to avoid such behaviour.

**Comment by mindaugasnakrosis** [comment]
Not stale

**Comment by kukuandroid** [comment]
> I solved it with setting `defaultSort` for each field.
> `const [filter, setFilter] = useState({ field: "name", order: "asc" }) ... <MaterialTable columns={[ { field: "name", title: "name", defaultSort: sortField.order, ]} /> `
> However, it has some drawbacks. When you change state, material table sorts your current data by order you provided, so there is glimpse of data visually getting sorted twice. You may change order state after your data is loaded as well to avoid such behaviour.

where does sortField come from ?

**Comment by dml-tl** [comment]
The sorting works already good. Btw. since you changed SubscriptionTable, you also modified /client/trading. I think it's just easier if you go to /client/subscriptions and remove Subscriptionstable and just use your DataTable as test.

1. The API started to look good, but to safe work, you can consider to add render function per column instead of only header. That way you can just pass values to your data function, like it's shown in https://mui.com/components/tables/ or https://mdbootstrap.com/docs/react/tables/datatables/. 
2. Also you can move sortRequest to options to keep columns definition clean. (maybe you don't even need those and can keep sortDirection as the definition of each columns.

Here is an example call that would be similar to other DataTables. 

```
          <DataTable
            columns={
              [
                { id: "select", title: '', headerRender: selectAllHeader, columnRender: rowData => (<input id={rowData.id} className="form-checkbox" type="checkbox" onChange={rowData.handleClick} checked={rowData.isChecked} />)},
                { id: "id", title: 'Id' },
                { id: "contract", title: 'Contract', sortable: true, id: 'customer' },
                { id: "interval", title: 'Interval', sortable: true, id: 'billingPeriodDays' },
                { id: "payment", title: 'Payment', sortable: true, id: 'amount' },
                { id: "maxPayout", title: 'Max Payout' },
              ]
            }

            options = {
              sortRequest: columnSortRequested,
              defaultSort: defaultSort,
            }

            data={list.map(sub => {
              return (
                {
                  "id": sub.id,
                  "contract": sub.contract,
                  "interval": sub.interval,
                  "payment": `${sub.payment} €`,
                  "maxPayout": sub.maxPayout,
                }
              )
            })}
          />
```
