### ISSUE TITLE
When the user presses the enter key while editing a row, it confirms and saves the changes. How can I prevent this?

### ISSUE THREAD

**Issue by tran-simon** [mbrn/material-table#2484]
You can see this behavior in these demos: https://material-table.com/#/docs/features/editable

When you press enter, it saves the whole row.

I can I make it so that we can press enter without exiting edit mode?

thanks

**Comment by gxtaillon** [comment]
I don't think there's a setting to toggle enter at this time, but there are workarounds to disable that behavior. Maybe one of them would fit your need. See comments in https://github.com/mbrn/material-table/pull/2008

**Comment by imnasnainaec** [comment]
I would like to be able to able to turn off or override the onEnter behavior for just a single column.

**Comment by imnasnainaec** [comment]
Related: #2360

**Comment by phuoctrung-ppt** [comment]
you can use editComponent and handle by Key Event
