### ISSUE TITLE
Is it possible to set a minimum width for a column? 

### ISSUE THREAD

**Issue by KerimG** [mbrn/material-table#2487]
We have tables in which not all columns are equally important and would like to make one column significantly wider than the others. Is that possible?

**Comment by kumarunster** [comment]
@KerimG did you tried to pass `width`option to your column definition? can be a number (pixel) or string.
Seems to be undocumented, but that option exists and I saw somewhere reference to it.

**Comment by KerimG** [comment]
Thank you, @kumarunster. Yes that's how we solved it. Didn't think it'd work, since it's not documented but cool!

**Comment by IdLevi1705** [comment]
Thank you @kumarunster ! This should be documented.
