### ISSUE TITLE
Column render function behaves differently on local vs. production environments

### ISSUE THREAD

**Issue by ylut** [mbrn/material-table#2489]
Hello,
I have a simple column render condition which renders a ghost animation based on this.props.isLoading:

```
const emptyData = [{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}];

<MaterialTable
...
data={this.props.isLoading ? emptyData : this.props.data}
columns={this.props.columns.map((column: TableColumn, index) => ({
          title: column.title,
          field: column.field,
          render: this.props.isLoading
            ? () => <GhostGesture widthPercent={column.ghostLength}/>
            : column.render,
        }
/>
```

`<GhostGesture widthPercent={column.ghostLength}/>` is just a react component which contains a div with some styling as you can see in the picture below.

Things behave nicely on local environment:
![image](https://user-images.githubusercontent.com/58393953/94013270-84120180-fdb2-11ea-8e99-8746a4f77dc1.png)

But in production, it just renders empty rows instead:
![image](https://user-images.githubusercontent.com/58393953/94013445-c1768f00-fdb2-11ea-82ed-57ebaec1d50f.png)

In both cases the data itself renders fine when this.props.isLoading=false.

I'm using version 1.68.0

Is there anything I'm doing wrong here?
Thanks,

**Comment by arunwilson-vetifly** [comment]
Hi @ylut Did you find a solution for this problem.

**Comment by ylut** [comment]
Hi,
Apparently the problem was in the way my production environment translates the opacity units in my SCSS files - the ghost animations did appear, only with nearly zero opacity.
I Fixed it by changing the opacity units from percentages (10%) to floating points (0.1) which work on both local and production environments.

Sorry for the hassle.
