### ISSUE TITLE
How to turn off pagination check for multiplicity 5

### ISSUE THREAD

**Issue by Kuzmich100kM** [mbrn/material-table#2490]
I need the table to take up all the available height, so it can have any number of rows. This throws an error in the console. How can I disable checking for a multiplicity of 5?

https://codesandbox.io/s/blissful-hamilton-9mcd2?file=/demo.js

![изображение](https://user-images.githubusercontent.com/46998842/94071585-d710a680-fdfc-11ea-882f-8e270fdea4b1.png)

**Comment by kumarunster** [comment]
@Kuzmich100kM check `pageSizeOptions` option.

in your codesandbox:

```
const options = { pageSize: numRows, 
                    pageSizeOptions: [5, 10, 20, numRows] };
```

**Comment by Kuzmich100kM** [comment]
It works, thanks!
