### ISSUE TITLE
PDF export has Turkish character issue

### ISSUE THREAD

**Issue by tolgaduzenli** [mbrn/material-table#2494]
# Guidelines

- #### Please include a demo of the issue/behavior/question you have
![Screenshot 2020-09-26 at 08 43 09](https://user-images.githubusercontent.com/3314060/94335623-7d1f0500-ffe5-11ea-9da0-8b0ff222754f.png)
![Screenshot 2020-09-26 at 08 43 21](https://user-images.githubusercontent.com/3314060/94335624-7db79b80-ffe5-11ea-86a8-07879d60d3ae.png)

- #### Please try to be as detailed as possible
PDF export has Turkish character issue. Is this something known issue or can it be handled by localisation ? 

- #### You may fork one of the following starter templates if you would like:
Official example from demo [page](https://material-table.com/#/docs/features/export)

**Comment by pskrajnyy** [comment]
Hi, do you fix this problem?

**Comment by aneskurtovic** [comment]
Same problem with Bosnian characters

**Comment by tolgaduzenli** [comment]
@pskrajnyy 
I couldn't find any solution. Just disabled pdf export for now.
