### ISSUE TITLE
Is there any way to prevent columns headers horizontal draggable ?

### ISSUE THREAD

**Issue by nightwolf-041** [mbrn/material-table#2495]
hi,
 I use the grouping prop, but because my table direction is **RTL**, when i move the columns headers together,, it doesn't work properly.
so i want to disable **horizontal drag and drop** for headers...
any idea ?

**Comment by kjanos0502** [comment]
Hi,

Maybe setting the draggable prop to false?
It is under options.
https://material-table.com/#/docs/all-props

**Comment by piscespieces** [comment]
You can pass the `options` prop to your table like this:

```
options={{
    draggable: false,
    grouping: false,
    sorting: false,
    pageSize: 5,
    actionsColumnIndex: -1
}}
```

As you can see, one of the options is `draggable` which takes a Boolean value (`true` or `false`)
