### ISSUE TITLE
Auto select few checkbox when page loads on a condition 

### ISSUE THREAD

**Issue by 1501bharti** [mbrn/material-table#2497]
# Guidelines

Can we auto select few check boxes using some condition or we have to use custom check boxes rather than the selection : true  option 

- #### Please include a demo of the issue/behavior/question you have

- #### Please try to be as detailed as possible

- #### You may fork one of the following starter templates if you would like:

  - #### [CodeSandbox](https://codesandbox.io/s/material-table-starter-template-xnfpo)
  - #### [StackBlitz](https://stackblitz.com/edit/material-table-starter-template)

**Comment by dlopezd** [comment]
You can add the following to each object in data who apply your condition
`tableData: { checked: true } `
