### ISSUE TITLE
customFilterAndSearch breaks global search

### ISSUE THREAD

**Issue by sanichka96** [mbrn/material-table#2498]
I use _customFilterAndSearch_ to be able to filter dates by range. It works fine, but when I user global search field, the effect is always the same - the whole data is presented on the screen.

![image](https://user-images.githubusercontent.com/18401192/94431737-f65d5a00-0195-11eb-8f2a-117354c408b4.png)

![image](https://user-images.githubusercontent.com/18401192/94431787-0bd28400-0196-11eb-8e95-5bf6e0191eab.png)

Expected result: search should be working even if _customFilterAndSearch_  is used on some columns.

Thank you in advance!

**Comment by ArunPatole** [comment]
Hello, I am also facing this issue.  After adding customFilterAndSearch for a few columns, the global search stopped working. Let me know what could be the issue, thanks in advance.

**Comment by ArunPatole** [comment]
@mbrn in case you have any inputs, thanks.

**Comment by Domino987** [comment]
@sanichka96 Can you share your code pls?

**Comment by sanichka96** [comment]
@Domino987 
Here is how I define _customFilterAndSearch_ and _defaultFilter_ functions in one of my date columns:

```jsx
customFilterAndSearch: (filter, rowData) => dateHelper.isDateInRange(filter.dateFrom, filter.dateTo, rowData.startDate),
defaultFilter: filterHelper.getDefaultDateFilterValues(filterValues, 'startDate'),
```
`isDateInRange` method just checks if `rowData.startDate` is between `filter.dateFrom` and `filter.dateTo`.
`getDefaultDateFilterValues` fetches values from filter object, which I keep in localStorage by name of the field. I need it, because I have a requirement to save filters state on every refresh and even after logout.

Just in case: I use _customFilterAndSearch_ just in case of date types and _getDefaultDateFilterValues_ in every column, where filter feature is turned on.

**Comment by Coystark** [comment]
Same issue here

**Comment by Domino987** [comment]
Since mbrn abandoned the repo, could you try @material-table/core?

**Comment by Dos771** [comment]
> @Domino987
> Here is how I define _customFilterAndSearch_ and _defaultFilter_ functions in one of my date columns:
> 
> ```js
> customFilterAndSearch: (filter, rowData) => dateHelper.isDateInRange(filter.dateFrom, filter.dateTo, rowData.startDate),
> defaultFilter: filterHelper.getDefaultDateFilterValues(filterValues, 'startDate'),
> ```
> 
> `isDateInRange` method just checks if `rowData.startDate` is between `filter.dateFrom` and `filter.dateTo`.
> `getDefaultDateFilterValues` fetches values from filter object, which I keep in localStorage by name of the field. I need it, because I have a requirement to save filters state on every refresh and even after logout.
> 
> Just in case: I use _customFilterAndSearch_ just in case of date types and _getDefaultDateFilterValues_ in every column, where filter feature is turned on.

Hello Sanichka96. Now I am looking solution daterange in my table, and your code is helpfull. May you share your full code function dateHelper.isDateInRange() ?

**Comment by sanichka96** [comment]
@Dos771 Of course!

_dateToBeFiltered_ has format '26.04.2021' in my case, so I have to parse it as a **Date** object (see _parseDateWithDots_ method below)
```js
export function isDateInRange(dateFrom, dateTo, dateToBeFiltered) {
  const parsedDateToBeFiltered = parseDateWithDots(dateToBeFiltered);

  if (!parsedDateToBeFiltered) {
    return !(dateFrom || dateTo);
  }

  if (!(dateFrom || dateTo)) {
    return true;
  } else if (!dateFrom) {
    return parsedDateToBeFiltered <= new Date(dateTo).setHours(0, 0, 0, 0);
  } else if (!dateTo) {
    return parsedDateToBeFiltered >= new Date(dateFrom).setHours(0, 0, 0, 0);
  }
  return parsedDateToBeFiltered >= new Date(dateFrom).setHours(0, 0, 0, 0)
    && parsedDateToBeFiltered <= new Date(dateTo).setHours(0, 0, 0, 0);
}
```

```js
export function parseDateWithDots(dateString) {
  if (!dateString) {
    return null;
  }

  if (dateString.includes(' ')) {
    dateString = dateString.split(' ')[0];
  }

  const dateArray = dateString.split('.');
  return new Date(dateArray[2], dateArray[1] - 1, dateArray[0]);
}
```

**Comment by Dos771** [comment]
> @Dos771 Of course!
> 
> _dateToBeFiltered_ has format '26.04.2021' in my case, so I have to parse it as a **Date** object (see _parseDateWithDots_ method below)
> 
> ```js
> export function isDateInRange(dateFrom, dateTo, dateToBeFiltered) {
>   const parsedDateToBeFiltered = parseDateWithDots(dateToBeFiltered);
> 
>   if (!parsedDateToBeFiltered) {
>     return !(dateFrom || dateTo);
>   }
> 
>   if (!(dateFrom || dateTo)) {
>     return true;
>   } else if (!dateFrom) {
>     return parsedDateToBeFiltered <= new Date(dateTo).setHours(0, 0, 0, 0);
>   } else if (!dateTo) {
>     return parsedDateToBeFiltered >= new Date(dateFrom).setHours(0, 0, 0, 0);
>   }
>   return parsedDateToBeFiltered >= new Date(dateFrom).setHours(0, 0, 0, 0)
>     && parsedDateToBeFiltered <= new Date(dateTo).setHours(0, 0, 0, 0);
> }
> ```
> 
> ```js
> export function parseDateWithDots(dateString) {
>   if (!dateString) {
>     return null;
>   }
> 
>   if (dateString.includes(' ')) {
>     dateString = dateString.split(' ')[0];
>   }
> 
>   const dateArray = dateString.split('.');
>   return new Date(dateArray[2], dateArray[1] - 1, dateArray[0]);
> }
> ```

Thank you for you usefull code, but there is some problem.
When you using global search in table and same time will use date range, global search won't work. 

and advice who will use this code, your date format depends your browser.

**Comment by sanichka96** [comment]
@Dos771, you are welcome.
> Thank you for you usefull code, but there is some problem.
> When you using global search in table and same time will use date range, global search won't work.

Well, broken global search when using _customFilterAndSearch_ was my original problem, that's why I raised this issue.

> and advice who will use this code, your date format depends your browser.

My date format does not depend on browser. Date with dots format has been chosen by me for beautiful and clear display purpose. I get timestamp from backend and display just date part dd.MM.yy. That's all.
