### ISSUE TITLE
Column 'field' property dont accepts inner object fields?

### ISSUE THREAD

**Issue by dpossamai** [mbrn/material-table#2499]
Is there a way to use a field inside an object to appear in the column 'field' property? Something like:

```
let columns = [
        { title: 'ID', field: 'id', editable: 'never' },
        { title: 'Name', field: 'name' },
        { title: 'course', field: 'course.course_id' },
    ];

<MaterialTable
                title="Users"
                columns={columns}
                data={[
        { id: '1', name: 'user1', course: { course_id: 3, name: 'course 2'} },
    ]}
/>
```

I want to use the field inside the "course" object.

Thanks in advance.

**Comment by kumarunster** [comment]
@dpossamai that seems to work out of the box. https://codesandbox.io/s/material-table-starter-template-forked-l8cff?file=/src/index.js
what do you observe?

**Comment by dpossamai** [comment]
That's it! I was doing something wrong here. Thanks!
