### ISSUE TITLE
How to type ref on material-table

### ISSUE THREAD

**Issue by cmontois** [mbrn/material-table#2501]
# Guidelines

Hey,

I don't know which type I have to put on my table ref, currently I have the following code:

```tsx
import * as React from 'react';
import MaterialTable from 'material-table';

const productsListRef = React.createRef<MaterialTable<object>>();

React.useEffect(() => {
        if (anyFilterSet && productsListRef && productsListRef.current) {
            productsListRef.current.onQueryChange(); // Here i have a typescript error (see below)
        }
}, [appliedWorkflow, appliedFilters, pageSize]);

<MaterialTable
         tableRef={productsListRef}
         ....
/>
```

Typescript error: Property 'onQueryChange' does not exist on type 'MaterialTable<object>'.

How can should I type the reference to the table ?

Thank you !

**Comment by cmontois** [comment]
Seems like I have to put MaterialTableProps instead of MaterialTable ?

**Comment by nextglabs** [comment]
Try this type: `React.RefObject<unknown>`

Unrelated, Refs in useEffect doesn't seem to work properly
https://github.com/mbrn/material-table/issues/1560#issuecomment-578586797

**Comment by yejiyang** [comment]
`React.RefObject<unknown>` does not help. Anyone can help?

**Comment by katesroad** [comment]
const tableRef = useRef<{ tableContainerDiv: React.RefObject<HTMLDivElement> }>(null);
