### ISSUE TITLE
Add row on custom action add button.

### ISSUE THREAD

**Issue by aniket3mule** [mbrn/material-table#2505]
# Guidelines

- #### Please include a demo of the issue/behavior/question you have

- #### Please try to be as detailed as possible

- #### You may fork one of the following starter templates if you would like:

  - #### [CodeSandbox](https://codesandbox.io/s/material-table-starter-template-xnfpo)
  - #### [StackBlitz](https://stackblitz.com/edit/material-table-starter-template)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pthomas931** [comment]
I believe you're trying to setup a "free action" that creates a row? You can find an example of how to make a free action here on the "Free Action Example":
https://material-table.com/#/docs/features/actions

Then you will just need to move the table data to component state and change the state using the new action:

```
function FreeAction() {
  const [data, setData] = useState([
    { name: "Mehmet", surname: "Baran", birthYear: 1987, birthCity: 63 },
    { name: "Zerya Betül", surname: "Baran", birthYear: 2017, birthCity: 34 },
  ]);

  return (
    <MaterialTable
      title="Free Action Preview"
      columns={[
        { title: "Name", field: "name" },
        { title: "Surname", field: "surname" },
        { title: "Birth Year", field: "birthYear", type: "numeric" },
        {
          title: "Birth Place",
          field: "birthCity",
          lookup: { 34: "İstanbul", 63: "Şanlıurfa" },
        },
      ]}
      data={data}
      actions={[
        {
          icon: "add",
          tooltip: "Add User",
          isFreeAction: true,
          onClick: (event) =>
            setData([
              ...data,
              {
                name: "NewName",
                surname: "NewSurname",
                birthYear: 2020,
                birthCity: 63,
              },
            ]),
        },
      ]}
    />
  );
}
```
