### ISSUE TITLE
Is there any way I can access corresponding row data when I click only on edit icon.  I do not want to change the functionality of the edit button but just want to access the row data when I click on it. 

### ISSUE THREAD

**Issue by sidagwl5** [mbrn/material-table#2506]
# Guidelines

- #### Please include a demo of the issue/behavior/question you have

- #### Please try to be as detailed as possible

- #### You may fork one of the following starter templates if you would like:

  - #### [CodeSandbox](https://codesandbox.io/s/material-table-starter-template-xnfpo)
  - #### [StackBlitz](https://stackblitz.com/edit/material-table-starter-template)

**Comment by pthomas931** [comment]
So you would like an icon on the row to be clickable, but not the row itself?

If so, there is a great example here: https://material-table.com/#/docs/features/editable

Can you add some more detail?
