### ISSUE TITLE
Freeze Brower when adding more then 10 rows 

### ISSUE THREAD

**Issue by ShashankSirmour** [mbrn/material-table#2514]
# Guidelines
just start adding rows with the upper "add" button, add 15 or more rows you can see the browser freeze
Demo: https://wmkle.csb.app/
Code:  https://codesandbox.io/s/bold-fire-wmkle?file=/src/App.js

**The bug**
using editable material- table Browser  start Freeze after adding just 10 rows it the whole app start freezing and after adding just 10 rows every action freezes the whole application
 
**To Reproduce**
use  Editable  Example and add more than 10 rows you can start feeling the lag

**Expected behavior**
adding rows should not freeze the browser currently we cant add more than 15 rows because after adding 15 rows it will freeze the whole application and take a long to load

**Desktop (please complete the following information):**

- OS: Window
- Browser: Chrome
- Version 85.0.4183.121 (Official Build) (64-bit)

**Comment by SamerAlsayegh** [comment]
So I had the same issue, I ended up doing a temporary work-around (still not sure what the potential pitfalls), but going into data-manager, [line 83](https://github.com/mbrn/material-table/blob/5e9ef9affbc83db80301c4edee4306aabcc3701f/src/utils/data-manager.js#L83). Simply just comment it out.


It does make the table much faster for me, but as I said, I am 99% sure its being used internally somewhere. But filtering, pages, exporting all seem to work on my end.

**Comment by ShashankSirmour** [comment]
> [line 83](https://github.com/mbrn/material-table/blob/5e9ef9affbc83db80301c4edee4306aabcc3701f/src/utils/data-manager.js#L83). Simply just comment it out

thanks, man very nice observation I changed my package version to 1.59 and it's working but will surely use your trick once I will use newer version features

**Comment by peacechen** [comment]
Unfortunately mbrn is inactive and not merging PR's. Use the official community fork [@material-table/core ](https://github.com/material-table-core/core)instead.
