### ISSUE TITLE
Update table's data frequently via web sockets

### ISSUE THREAD

**Issue by salmanbabri** [mbrn/material-table#2517]
Hi,

So I am trying to create a table which initially loads some data & displays it. Then it receives frequent updates from server (via web sockets) & then incorporates those changes into it & render them seamlessly.

So the code looks something like this:-

```
export const MyTable: React.FC<Props> = ({ data }) => {

    return <MaterialTable
        columns={/*some columns here*/}
        data={data}
        editable={{
          onRowUpdate: (newData, _) =>
            axios.post(/*send post request*/),
        }}
        options={{ sorting: true }}
      />
}
```

So data is passed to this component as props, and it is expected to change as the server sends messages to clients about the changes. What happens is that as soon as the props change after the initial render, I receive the following error:-

"TypeError: Cannot assign to read only property 'tableData' of object".

I read the documentation & saw a section remote data fetch, but I am not sure how can I can utilize that to fix my problem, considering that I initially fetch some data & subsequent updates are piecemeal.

**Comment by DasTobbel** [comment]
First of all "data" should be an array, so '''data={Object.values(data)}''' may fix your issue.
As the updates via websocket are changes of the previous "data" you could try going for something like this:
```javascript
// WEbsocket recieve funcion
[...]
const isUpdateIndex = data.findIndex(elmnt => elmnt.id === websocketChange.id);
if ( isUpdateIndex > -1) {
  data[isUpdateIndex] = websocketChange;
} else {
  data.push(websocketChange);
}
// Send the new data to the component and listening for changes in "componentDidUpdate" or in the "useEffect"
[...]
```
This will trigger the rerender (and may destroy the changes you did not yet save in the edit of a table)

**Comment by salmanbabri** [comment]
> 
> 
> First of all "data" should be an array, so '''data={Object.values(data)}''' may fix your issue.
> As the updates via websocket are changes of the previous "data" you could try going for something like this:
> 
> ```js
> // WEbsocket recieve funcion
> [...]
> const isUpdateIndex = data.findIndex(elmnt => elmnt.id === websocketChange.id);
> if ( isUpdateIndex > -1) {
>   data[isUpdateIndex] = websocketChange;
> } else {
>   data.push(websocketChange);
> }
> // Send the new data to the component and listening for changes in "componentDidUpdate" or in the "useEffect"
> [...]
> ```
> 
> This will trigger the rerender (and may destroy the changes you did not yet save in the edit of a table)

Thanks for the reply.

Data is an array, I am using typescript so that is not an issue.
The data manipulation you've mentioned, I've done it in AppComponent, which passes the data down to MyTable component. Can you elaborate a bit what I'll be doing in the useEffect method? Will I be needing some sort of ref to MaterialTable & then setting some property of it?

`useEffect(() => {//what logic to mention here}, [data]);`

**Comment by DasTobbel** [comment]
Sadly i'm not familiar with the Typescript way of defining components...

The none TS Way could be something like :
```
function RoomsTable(props) {
  const [data, setData] = useState(props.data || [] );
  useEffect(() => {  setData(data) }, [ data ]  });
  return (/*render material table here with 'data={data}'* /);
}
```

**Comment by salmanbabri** [comment]
Ok, I figured it out. The issue was that I was changing state in parent component with the help of immer js. It seems like material table isn't compatible with that library. As soon as I changed my implementation for state updation, it started working fine.
