### ISSUE TITLE
dark theme table

### ISSUE THREAD

**Issue by shmoshkin** [mbrn/material-table#252]
dark theme is a common case in our days.
please if you can add option to dark theme table..

**Comment by jakeleventhal** [comment]
+1

**Comment by mbrn** [comment]
We use material-ui library in material-table if you use its ThemeProvider component material-table will apply the same theme. 

https://material-ui.com/customization/themes/

**Comment by Foosballfan** [comment]
I can confirm that the table takes on the application's dark theme

![image](https://user-images.githubusercontent.com/15104463/53418949-c86bce80-39d0-11e9-80ca-2988dfc52add.png)

**Comment by mstfymrtc** [comment]
Hello @mbrn, I'm not using material ui but material-table. How can I activate dark mode for the table? Do I have to write custom styling?

**Comment by chitgoks** [comment]
This is weird. i have no idea why the table rows do not use the theming.
![row](https://user-images.githubusercontent.com/3955470/74400945-9b6f3080-4e5a-11ea-9519-56adbd71ad62.png)

**Comment by VidushaZ** [comment]
@mstfymrtc Did u find a method to activate dark mode? Instead of customizing?

**Comment by VidushaZ** [comment]
@mstfymrtc check this link : 
https://material-ui.com/customization/palette/#dark-mode
