### ISSUE TITLE
how can i swap positions when selected records

### ISSUE THREAD

**Issue by phanvantien270290** [mbrn/material-table#2523]
# Guidelines

I want to swap title and actions postions  in header table

expected: when i select records, any actions shown in left table 

![swap_p](https://user-images.githubusercontent.com/37722989/95176224-c55cd500-07e6-11eb-9230-fd387a735073.JPG)

**Comment by Domino987** [comment]
You would need to override the whole toolbar component to achieve this: https://material-table.com/#/docs/features/component-overriding that:
