### ISSUE TITLE
Using react-redux for editable table

### ISSUE THREAD

**Issue by syatom** [mbrn/material-table#2525]
Is it possible to use the react-redux function dispatch inside the editable onRowUpdate property? I need to update the redux store with the edited data from the table. How can this be achieved without using the state.

**Comment by Domino987** [comment]
Of course you can, what did you try?

**Comment by syatom** [comment]
Here is an example of my code trying to use dispatch:
return (
        <MaterialTable
            options={{
                filtering: false,
                search: false,
                paging: false,
            }}
            title="Other Client Addresses"
            columns={columns}
            data={data}
            editable={{
                onRowUpdate: (newData, oldData) => new Promise((resolve, reject) => {
                    setTimeout(() => {
                        resolve(newData)
                    }, 1000)
                }).then((address) => {
                    props.dispatch(updateOtherAddress(address))
                })

            }}
        />
    );
}

export default connect()(EditableTable)

**Comment by syatom** [comment]
This is now working here is the code:
return (
        <MaterialTable
            options={{
                filtering: false,
                search: false,
                paging: false,
            }}
            title="Other Client Addresses"
            columns={columns}
            data={data}
            editable={{
                onRowUpdate: (newData, oldData) => new Promise((resolve, reject) => {
                    setTimeout(() => {
                        resolve(newData)
                    }, 1000)
                }).then((address) => {
                    props.updateOtherAddress(address)
                })

            }}
        />
    );
}

const mapDispatchToProps = (dispatch) => ({
    updateOtherAddress: (address) => dispatch(updateOtherAddress(address))
})

export default connect(null, mapDispatchToProps)(EditableTable)
