### ISSUE TITLE
How to add custom loading animation after editing and deleting actions?

### ISSUE THREAD

**Issue by cf-232** [mbrn/material-table#2528]
### Custom Loading animation
 Hi, all. Just wondering is there a proper way to add custom loading animation after the operations (add a new row, update data, delete a data)?

Cheers.

**Comment by asifkabani** [comment]
Came looking for the same thing

**Comment by ifndefdeadmau5** [comment]
AFAIK there's only 'linear' and 'circular' type of loading animation for now, it is pretty hard to locate any custom component between sub table components since current implementation doesn't exposes any available slots for that.
