### ISSUE TITLE
How to change Boolean icon in the rows to "-" and "+" instead of "-" and "✓" ?

### ISSUE THREAD

**Issue by sadegh16** [mbrn/material-table#2534]
# Guidelines

- #### Please include a demo of the issue/behavior/question you have

- #### Please try to be as detailed as possible

- #### You may fork one of the following starter templates if you would like:

  - #### [CodeSandbox](https://codesandbox.io/s/material-table-starter-template-xnfpo)
  - #### [StackBlitz](https://stackblitz.com/edit/material-table-starter-template)

**Comment by cdruck** [comment]
Check the icons section of https://material-table.com/#/docs/all-props
