### ISSUE TITLE
Add an "OnClick" listener for when entering edit mode

### ISSUE THREAD

**Issue by pajohns** [mbrn/material-table#2537]
Currently it does not seem possible to tap into any callback to determine if we're in edit mode or not. I wish to selectively show/hide columns depending on whether we're in edit mode or not. I propose the following:

1. Provide callbacks on both the inline edit buttons and the bulk edit buttons that will expose the current editing mode.
2. Provide the ability to determine if a column is viewable in edit mode or view mode - ie a column attribute that when not used will provide all modes as default but you can specify either "edit" or "view" if you want to restrict the edit mode.

**Comment by dalenhughes** [comment]
I'm looking for this to be exposed so I can disable sorting when in editing mode. 

Sorting while editing a row causes a critical bug where no data is shown and the page has to be refreshed.
