### ISSUE TITLE
How can I add up and down key selection changes in material table rows ? With React js

### ISSUE THREAD

**Issue by AliSaeed090** [mbrn/material-table#2539]
# Guidelines

- #### Please include a demo of the issue/behavior/question you have

- #### Please try to be as detailed as possible

- #### You may fork one of the following starter templates if you would like:

  - #### [CodeSandbox](https://codesandbox.io/s/material-table-starter-template-xnfpo)
  - #### [StackBlitz](https://stackblitz.com/edit/material-table-starter-template)

**Comment by kamrannawaz** [comment]
the same issue i m facing, i want row selection on key down and up event without clicking on specific row.
