### ISSUE TITLE
Add <Link> from react router to actions > onClick 

### ISSUE THREAD

**Issue by WildOsk** [mbrn/material-table#2541]
Following this example -> https://stackoverflow.com/questions/58702960/how-to-add-link-react-router-to-material-table

I've wondered if it is possible to include <Link> tag from react router:

Example 2 :
```
  const [data, setData] = useState([{
    id: "1",
    name: "Name 1"
  },
  {
    id: "2",
    name: "Name 2"
  }]);
<MaterialTable
      title="Products"
      columns={[
        {title: 'ID',field: 'id', type: 'numeric', hidden:'false'},
        { title: 'Name',field: 'name', }
      ]} 
      data={data}
      options={{
        filtering: true,
        sorting: true
      }}
      actions={[
        {
          icon: 'edit',
          tooltip: 'Edit ',
          onClick: (event, rowData) => 
            <Link to={`/product/edit/${rowData.id}`}>Edit</Link> 
        },
               {
                  icon: 'delete',
                  tooltip: 'delete user',
                  onClick: (event, rowData) => alert(rowData.name + " Deleted")
                }
      ]}
      />
```

I've considered as an alternative to: [Component Overriding](https://material-table.com/#/docs/features/component-overriding)
But it overrides both actions, edit and delete

**Comment by IdLevi1705** [comment]
I was facing the same issue when I tried to render a component from actions. Try the following (it works for me):
.
.
.
actions={[
        {
          icon: 'edit',
          tooltip: 'Edit ',
          onClick: (event, rowData) => ReactDOM.render(
            <Link to={`/product/edit/${rowData.id}`}>Edit</Link>, 
              document.createElement('root') // basically here you create another component. make sure garbage collection removes it if not you need to remove it manually.
        },
               {
                  icon: 'delete',
                  tooltip: 'delete user',
                  onClick: (event, rowData) => alert(rowData.name + " Deleted")
                }
      ]}
      />

**Comment by usahai** [comment]
If you're using react-router, you could do

```
onClick: () => props.history.replace("/" + path)
```
Either replace or push would work

**Comment by WildOsk** [comment]
Hello,  i am using react-router
thanks for your proposal, it works like a charm.

 You gave me the idea,
i've decided to use 
const history = useHistory();

**Then:**
onClick: (event, rowData) => history.push(`${path}/edit/${rowData.id}`, {datos:rowData}) 

On the following page: 
I've taken the state in the same way, through 
const history = useHistory();

history.location.state.datos.id

**Comment by usahai** [comment]
If its an icon, this is how I'm doing it 
```
const columns = [
    {
        title: "Request ID",
        field: "requestId",
        cellStyle: {
            paddingLeft: "25px"
        },
        headerStyle: {
            paddingLeft: "25px"
        },
        render: rowData => (
            <Link
                to={{
                    pathname: "/{path}",
                    state: {
                        details: details
                   }
                }}
            >
                <Typography className={classes.reqId}>{rowData.requestId}</Typography>
            </Link>
        )
    },
];
```
So you could replace the `<Typography>` with an `<IconButton>` component, and it should work.

**Comment by WildOsk** [comment]
Yes, its a great idea, i've had already view that,
But i didn't know if rowData would work writing it in **columns > render**

Thanks for your answers

**Comment by Domino987** [comment]
Closing since it seems fixed. If not pleas reopen.
