### ISSUE TITLE
How to change footer/ pagination style?

### ISSUE THREAD

**Issue by IdLevi1705** [mbrn/material-table#2543]
Hi, I am trying to change the 'text' style in my footer table but couldn't find which element has this setting.
as you can see in the picture below, I changed the icon's style and the number of rows but can't find where to change the number of rows in one page '1-10 of 10.'

![image](https://user-images.githubusercontent.com/23003297/95867088-c33ecd00-0d36-11eb-924b-955b656b0f85.png)

**Comment by chandjenAC** [comment]
Hi..i am having the same issue..
did you find a fix ?

**Comment by IdLevi1705** [comment]
Yes I did. Are you trying to override the Pagination component? The I needed it is just to change the pagination, nothing else.

**Comment by chandjenAC** [comment]
what I wanted is to change the background and styles for text elements.. and this is what I did.. not sure whether it is the right way to do it.... but achieved what I was looking for..

Override Pagination Component 👍      
  components={{
            Pagination: (props) => {
              return <CustomPaginationComponent {...props} />;
            },
          }}
Defining CustomPaginationComponent:
  const CustomPaginationComponent = (props) => {
    const { page, rowsPerPage, count, onChangePage } = props;
    let from = rowsPerPage * page + 1;
    let to = rowsPerPage * (page + 1);
    if (to > count) {
      to = count;
    }
    return (
      <td>
        <Grid
          container
          alignItems="center"
          justify="flex-end"
          style={{ paddingTop: 8 }}
        >
          <Grid item>
            <IconButton
              disabled={page === 0}
              onClick={(e) => onChangePage(e, page - 1)}
            >
              <PrevIcon
                fontSize="small"
                color={page === 0 ? "disabled" : "primary"}
              />
            </IconButton>
          </Grid>

          <Grid item>
            <Typography variant="caption" style={{ color: "white" }}>
              {from}-{to} of {count}
            </Typography>
          </Grid>
          <Grid item>
            <IconButton
              disabled={to >= count}
              onClick={(e) => onChangePage(e, page + 1)}
            >
              <NextIcon
                fontSize="small"
                color={to < count ? "primary" : "disabled"}
              />
            </IconButton>
          </Grid>
        </Grid>
      </td>
    );
  };
