### ISSUE TITLE
Duplicate columns on Cell Editing

### ISSUE THREAD

**Issue by scorpys** [mbrn/material-table#2548]
# Guidelines

  - #### [Demo](https://pf1ir.csb.app/)
  - #### [CodeSandbox](https://codesandbox.io/s/pf1ir)

**Describe the bug**
There is a bug when clicking editable cell with fixed columns at material-table. Some duplicated columns appears after click on editable cell

**To Reproduce**
Add **cellEditable** prop to MaterialTable and set **fixedColumns** option value
Open demo and click on some "First Name" cell (George for example). Editable columns duplicates instead of fixed column (Id)

**Expected behavior**
Id column doesnt disappear and input appears only at click position/

**Screenshots**
Before click
![image](https://user-images.githubusercontent.com/3193590/96056134-753cdd00-0e8e-11eb-9996-9b7171867c57.png)

After click
![image](https://user-images.githubusercontent.com/3193590/96055937-0e1f2880-0e8e-11eb-8988-b5dd9eba3313.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Chrome
- Version 86.0.4240.75

**Comment by Jsalvat** [comment]
We've the same problem. Any ETA?

**Comment by MichaelKapustey** [comment]
Issue is reproducible on a material-table website. Go to https://material-table.com/#/docs/features/fixed-columns, open code and add 
```
 cellEditable={{
        onCellEditApproved: (newValue, oldValue, rowData, columnDef) => {
          return new Promise((resolve, reject) => {
            console.log('newValue: ' + newValue);
            setTimeout(resolve, 1000);
          });
        }
      }}
```

**Comment by MichaelKapustey** [comment]
Present in v1.68.0 too
And in v1.67.0 clicking on cell broke a page
