### ISSUE TITLE
Can`t edit blank cells, only the ones with data I can edit on cellclick, please help

### ISSUE THREAD

**Issue by turbaceanu15** [mbrn/material-table#2550]
# Guidelines

- #### Please include a demo of the issue/behavior/question you have
![Capture](https://user-images.githubusercontent.com/72971720/96241958-90513f00-0fab-11eb-8961-a0c77f81a70b.PNG)
i want to insert data here in the blank area, but I can`t, please help me
- #### Please try to be as detailed as possible
![88506634-f86d3600-cff7-11ea-94b8-bd966fa75143](https://user-images.githubusercontent.com/72971720/96242013-a6f79600-0fab-11eb-886d-8967afde6c8c.png)
also I would like to remove that line.
- #### You may fork one of the following starter templates if you would like:

**Comment by frewmack** [comment]
For your first issue, add an `emptyValue` prop to your column definitions to provide something to click on when the cell is empty.
Example:
```
// ...
    <MaterialTable
      columns={[
        { title: 'Name', field: 'name', emptyValue: '(empty)' },
        // ...
      ]}
// ...
```
For your second issue, unfortunately there does not seem to be a way to override the styling in this particular case. Here is the source for applying styling to an editable cell:
https://github.com/mbrn/material-table/blob/5e9ef9affbc83db80301c4edee4306aabcc3701f/src/components/m-table-cell.js#L170-L187

**Comment by laurenabrahall** [comment]
Adding a work around for the dashed line issue here for future travellers:

```
import { createTheme } from "@mui/material"

export const theme = createTheme({
  components: {
    MuiTableCell: {
      styleOverrides: {
        root: {
          "& > div": {
            borderBottom: "none !important"
          },
        }
      }
    }
  }
})
```
