### ISSUE TITLE
Selection not working in material table 

### ISSUE THREAD

**Issue by PriyankDeep** [mbrn/material-table#2553]
**Problem**
I have made selection: true but I am having problem in material-table which is the checkboxes do not get selected whenever I click them. Can anyone tell me the reason?

**Code**

    <MaterialTable
           columns={columns}
            data={dummyData}
            options={{
              search: false,
              selection: true,
              showTitle: false,

              rowStyle: {
                fontSize: 12,
              },
        
              paging: false,
            }}
            icons={tableIcons}
            editable={{
              onRowUpdate: (newData, oldData) =>
                new Promise((resolve) => {
                  handleRowUpdate(newData, oldData, resolve);
                }),
              onRowAdd: (newData) =>
                new Promise((resolve) => {
                  handleRowAdd(newData, resolve);
                }),
              onRowDelete: (oldData) =>
                new Promise((resolve) => {
                  handleRowDelete(oldData, resolve);
                }),
            }}
          />

**Comment by shivarad** [comment]
> **Problem**
> I have made selection: true but I am having problem in material-table which is the checkboxes do not get selected whenever I click them. Can anyone tell me the reason?
> 
> **Code**
> 
> ```
> <MaterialTable
>        columns={columns}
>         data={dummyData}
>         options={{
>           search: false,
>           selection: true,
>           showTitle: false,
> 
>           rowStyle: {
>             fontSize: 12,
>           },
>     
>           paging: false,
>         }}
>         icons={tableIcons}
>         editable={{
>           onRowUpdate: (newData, oldData) =>
>             new Promise((resolve) => {
>               handleRowUpdate(newData, oldData, resolve);
>             }),
>           onRowAdd: (newData) =>
>             new Promise((resolve) => {
>               handleRowAdd(newData, resolve);
>             }),
>           onRowDelete: (oldData) =>
>             new Promise((resolve) => {
>               handleRowDelete(oldData, resolve);
>             }),
>         }}
>       />
> ```

I have the same issue , could you find any solution?
