### ISSUE TITLE
Add onFilterChange prop to documentation

### ISSUE THREAD

**Issue by royhadad** [mbrn/material-table#2554]
I needed to use the prop onFilterChange, but couldn't find it in the docs:
https://material-table.com/#/docs/all-props

after some hours, and trying some work-arounds I finally found this PR and realized this prop actually exists:
https://github.com/mbrn/material-table/pull/1281

would be nice if it was mentioned in the docs as well to help future devs :-)

**Comment by Asurapy** [comment]
Yeah there are a stuff that is not on the  documentation at all, We are using this library for a project but all of this is really making  us rethink our decision.

**Comment by usahai** [comment]
Oh man, same problem. Needed to do serverside stuff, but this prop wasn't listed, so I spent quite a while doing workarounds, until I found it in one of the examples. Would be great if the documentation was updated to include this
