### ISSUE TITLE
How can I receive the rendered values instead of data when exporting to pdf?

### ISSUE THREAD

**Issue by pedrohenriiz** [mbrn/material-table#2557]
I'm trying to implement an export functionality on the project that I'm working but I'm facing some problems. I have renders functions that modify the values that came from my database and showing on table. This works fine, the table lists exactly what I want, but, when I try to export the values, I got the values that aren't formatted, the 'original value'.

I want to know if there's a way to pass this formatted values, something like a flag or a params to options, so when I click to export, the PDF have the formatted values instead of the 'original data'.

Here is my table
![image](https://user-images.githubusercontent.com/56472003/96467253-1b774280-1201-11eb-836a-37abbf5b3b2c.png)

And this is the pdf
![image](https://user-images.githubusercontent.com/56472003/96467188-09959f80-1201-11eb-927c-0e2a0fcb27b1.png)

**Comment by atishwarchand** [comment]
how did you manage to get the chips (Devedor and Normal) in the table?

Share the code please

**Comment by pedrohenriiz** [comment]
To achieve this chip, you have to use a custom column rendering function. You can see the documentation [here](https://material-table.com/#/docs/features/custom-column-rendering)

Then, in this function, you can use whatever you want. In my case, I used the Material-ui [chip](https://material-ui.com/components/chips/) component.

To create this "color-change" effect, you have to pass a prop to the component that you created (in my case, I used this chip with styled component) and create a function to verify if the value is equal to something.

Here is an example
```
// The column that you want to change
 columns={[
      {
        field: 'name',
        title: 'name',
        render: renderName,
      }
    ]}
```

```
 function renderName(rowData) {
// Here you can render anything that you want.
// This verifyName function you can create to verify if the name is equal to something and return some properties
// or whatever you want
// EXAMPLE: {  
 color: 'red',
 label: 'Pedro',
}

const verifiedName= verifyName(rowData.name)


 return (<Chip color={verifiedName.color} label={verifiedName.label} /> )
}
```
It's a simple example explaining the logic. If you don't understand something, send me a message.

**Comment by atishwarchand** [comment]
@pedrohenriiz i am trying to send you a direct message but couldnt actually.....


This is my current code: 
`import React, { useState, useEffect } from 'react';
import { forwardRef } from 'react';
import Grid from '@material-ui/core/Grid'

import MaterialTable from "material-table";
import { AutoComplete } from 'material-table';
import { MTableEditField } from 'material-table';
import AddBox from '@material-ui/icons/AddBox';
import ArrowDownward from '@material-ui/icons/ArrowDownward';
import Check from '@material-ui/icons/Check';
import ChevronLeft from '@material-ui/icons/ChevronLeft';
import ChevronRight from '@material-ui/icons/ChevronRight';
import Clear from '@material-ui/icons/Clear';
import DeleteOutline from '@material-ui/icons/DeleteOutline';
import Edit from '@material-ui/icons/Edit';
import FilterList from '@material-ui/icons/FilterList';
import FirstPage from '@material-ui/icons/FirstPage';
import LastPage from '@material-ui/icons/LastPage';
import Remove from '@material-ui/icons/Remove';
import SaveAlt from '@material-ui/icons/SaveAlt';
import Search from '@material-ui/icons/Search';
import ViewColumn from '@material-ui/icons/ViewColumn';
import axios from 'axios'
import Alert from '@material-ui/lab/Alert';
import Page from 'components/Page';
import { httpClient } from '../appUtility/Api';
import {
    Col,
  } from 'reactstrap';

const tableIcons = {
  Add: forwardRef((props, ref) => <AddBox {...props} ref={ref} color='error'/>),
  Check: forwardRef((props, ref) => <Check {...props} ref={ref} color='primary'/>),
  Clear: forwardRef((props, ref) => <Clear {...props} ref={ref} color='error'/>),
  Delete: forwardRef((props, ref) => <DeleteOutline {...props} ref={ref} color='secondary' />),
  DetailPanel: forwardRef((props, ref) => <ChevronRight {...props} ref={ref} />),
  Edit: forwardRef((props, ref) => <Edit {...props} ref={ref} color='primary' />),
  Export: forwardRef((props, ref) => <SaveAlt {...props} ref={ref} />),
  Filter: forwardRef((props, ref) => <FilterList {...props} ref={ref} />),
  FirstPage: forwardRef((props, ref) => <FirstPage {...props} ref={ref} />),
  LastPage: forwardRef((props, ref) => <LastPage {...props} ref={ref} />),
  NextPage: forwardRef((props, ref) => <ChevronRight {...props} ref={ref} />),
  PreviousPage: forwardRef((props, ref) => <ChevronLeft {...props} ref={ref} />),
  ResetSearch: forwardRef((props, ref) => <Clear {...props} ref={ref} />),
  Search: forwardRef((props, ref) => <Search {...props} ref={ref} />),
  SortArrow: forwardRef((props, ref) => <ArrowDownward {...props} ref={ref} />),
  ThirdStateCheck: forwardRef((props, ref) => <Remove {...props} ref={ref} />),
  ViewColumn: forwardRef((props, ref) => <ViewColumn {...props} ref={ref} />)
};

function validateEmail(email){
  const re = /^((?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\]))$/;
  return re.test(String(email).toLowerCase());
}

function ManageRoles() {

  var columns = [
    {title: "Role", field: "role_id"},
    {title: "Role Name", field: "role_name"},
    {title: "Permissions", field: "permission_name"}
  ]
  const [data, setData] = useState([]); //table data

  //for error handling
  const [iserror, setIserror] = useState(false)
  const [errorMessages, setErrorMessages] = useState([])
  const [selectedRow, setSelectedRow] = useState(null);

  useEffect(() => { 
    httpClient.get("role/getRoles")
        .then(res => {               
            setData(res.data.roles)
         })
         .catch(error=>{
             console.log(error)
             console.log("Error")
         })
  },[])





  const handleRowUpdate = (newData, oldData, resolve) => {
    //validation
    let errorList = []
    if(newData.role_name === ""){
      errorList.push("Please enter role name")
    }
    // console.log(newData);
    if(errorList.length < 1){
      var querystring = require('querystring');
        // stringify is known issue
        const datapost = querystring.stringify({
            role_name: newData.role_name,
        })
        const header = {
            headers: {
                "Content-Type": "application/x-www-form-urlencoded"
            }
        }
        console.log(datapost);
      httpClient.put("role/updateRole/"+newData.role_id, datapost, header)
      .then(res => {
        console.log(res.data)
        // const dataUpdate = [...data];
        // console.log(dataUpdate)
        // const index = oldData.tableData.role_id;
        // alert(dataUpdate)
        // dataUpdate[index] = newData;
        setData(res.data.roles);
        resolve()
        setIserror(false)
        setErrorMessages([])
      })
      .catch(error => {
        console.log(error)
        setErrorMessages(["Update failed! Server error"])
        setIserror(true)
        resolve()
        
      })
    }else{
      setErrorMessages(errorList)
      setIserror(true)
      resolve()

    }
    
  }

  const handleRowAdd = (newData, resolve) => {
    //validation
    let errorList = []
    if(newData.role_name === undefined){
      errorList.push("Please enter role name")
    }

    if(errorList.length < 1){ //no error
        var querystring = require('querystring');
        // stringify is known issue
        const datapost = querystring.stringify({
            role_name: newData.role_name,
        })
        const header = {
            headers: {
                "Content-Type": "application/x-www-form-urlencoded"
            }
        }
        console.log(datapost);
      httpClient.post("role/addRole", datapost, header)
      .then(res => {
        console.log(res)
        let dataToAdd = [...data];
        dataToAdd.push(newData);
        setData(res.data.roles);
        resolve()
        setErrorMessages([])
        setIserror(false)
      })
      .catch(error => {
        console.log(error)
        setErrorMessages(["Cannot add data. Server error!"])
        setIserror(true)
        resolve()
      })
    }else{
      setErrorMessages(errorList)
      setIserror(true)
      resolve()
    }

    
  }

  const handleRowDelete = (oldData, resolve) => {
    
    httpClient.delete("role/deleteRole/"+oldData.role_id)
      .then(res => {
        // const dataDelete = [...data];
        // const index = oldData.tableData.role_id;
        // dataDelete.splice(index, 1);
        console.log(res.data.roles)
        setData(res.data.roles);
        resolve()
      })
      .catch(error => {
        setErrorMessages(["Delete failed! Server error"])
        setIserror(true)
        resolve()
      })
  }


  return (
    <Page title="View Roles" breadcrumbs={[{ name: 'role / view', active: true }]}> 
    <div className="App">
      
      <Col xl={12} lg={12} md={12}>
      <Grid container spacing={1}>
      <Grid item xs='3'></Grid>
          <Grid  item xs='12' >
          <div>
            {iserror && 
              <Alert severity="error">
                  {errorMessages.map((msg, i) => {
                      return <div key={i}>{msg}</div>
                  })}
              </Alert>
            }       
          </div>
            <MaterialTable
              title="ROLES"
              columns={columns}
              data={data}
              icons={tableIcons}
              options={{
                headerStyle: {
                  backgroundColor: '#0a5e9c',
                  color: '#FFF',
                  draggable: true,
                },
                exportButton:true,
                actionsColumnIndex: -1
              }}
              onRowClick={((evt, selectedRow) => setSelectedRow(selectedRow.tableData.id))}
              editable={{
                onRowUpdate: (newData, oldData) =>
                  new Promise((resolve) => {
                      handleRowUpdate(newData, oldData, resolve);
                      
                  }),
                onRowAdd: (newData) =>
                  new Promise((resolve) => {
                    handleRowAdd(newData, resolve)
                  }),
                onRowDelete: (oldData) =>
                  new Promise((resolve) => {
                    handleRowDelete(oldData, resolve)
                  }),
              }}
            />
          </Grid>
          <Grid item xs={3}></Grid>
        </Grid>
        </Col>
    </div>
    </Page>
  );
}

export default ManageRoles;`

and currently this is how my data is shown on the normal table.

![Screenshot 2020-11-19 at 12 40 15 PM](https://user-images.githubusercontent.com/61366632/99605566-68e70980-2a64-11eb-837d-447a97fc5132.png)


If you can help me would really be appreciated as I am very new to react.

**Comment by pedrohenriiz** [comment]
@atishwarchand I thinks this could be useful: https://codesandbox.io/s/flamboyant-grass-07w5u?file=/src/TableColumns.js

**Comment by pedrohenriiz** [comment]
So, I've managed to find a way to change the values using  a custom export function but still doesn't know if there is some props or flag that I can use instead of doing this. Anyone have an idea?

**Comment by Baira** [comment]
> So, I've managed to find a way to change the values using a custom export function but still doesn't know if there is some props or flag that I can use instead of doing this. Anyone have an idea?

Please share your custom export function!

**Comment by pedrohenriiz** [comment]
Most of my pages has an option to download CSV and PDF. So, every page has an exportPDF/exportCSV function, which looks like this.
```jsx

//exportPdf.js
export default function exportPdf(tableColumns, tableData, formatMessage) {
  if (tableData.length === 0) {
    return toast.info(formatMessage({ id: 'reports.empty-data' }));
  }

  const docTitle = formatMessage({ id: 'cities.title' });

  const config = reportsConfig();

  const modifyConfig = {
    doc: {
      title: docTitle,
    },
    header: {
      title: {
        text: docTitle,
      },
    },
    body: {
      tableData: {
        head: tableColumns,
        body: tableData,
      },
    },
  };

  const newConfiguration = _.merge(config, modifyConfig);

  return generatePdf(newConfiguration);
}
```
The reportsConfig function return is an object that has some initial values and I change some of them as you can see on 'modifyConfig' and merge them on 'newConfiguration'. Then I pass the newConfiguration variable to a generic PDF function, which only creates the document and open on a new screen.

So you pass this function to Material Table exportPdf function.

```jsx

<MaterialTable
//...
options={{
// It's only an example, you can simplify this.
exportPdf: (tableColumns, tableData) => exportPdf(tableColumns, tableData)
}}
 />
```

```jsx
// My code has more stuff but I think this is the essential part.
//generatePdf.js
export default function generatePdf(config) {
  const doc = new JsPDF(config.page.paperStyle);

   const {
    tableData,
  } = config.body;

  const content = {
    columns: tableData.head.map(item => {
      return {
        header: item.title,
        dataKey: item.field,
      };
    }),
    body: tableData.body,
  };

  doc.autoTable(content);

  doc.setProperties({ title: config.doc.title });
  doc.viewerPreferences({ DisplayDocTitle: config.doc.displayDocTitle });

  if (typeof doc.putTotalPages === 'function') {
    doc.putTotalPages(config.footer.pagination.totalPagesExp);
  }

  window.open(doc.output('bloburl'));

  return doc;
}
```
