### ISSUE TITLE
Duplicate data1

### ISSUE THREAD

**Issue by apsrcreatix** [mbrn/material-table#256]
**About the bug**

node_modules > material-table > index.d.ts > Line 41: `customSort?: (data1: any, data1: any, type: 'row' | 'group') => number;`

I have seen the code in the repository, it's (data2: any) instead of (data1: any). 
But while installing the node module for version "material-table": "^1.17.0", it is showing this error because of duplicate data1.
Please update it and let me know. 

**Screenshot**

![screen shot 2019-02-23 at 11 11 14 am](https://user-images.githubusercontent.com/24192742/53282294-d82ead00-375b-11e9-95a6-10cd724d4eca.png)

Or Am I the only one facing this?

Thanks.

**Comment by mbrn** [comment]
This is done with v1.19.2
