### ISSUE TITLE
Bulk editing hides actions

### ISSUE THREAD

**Issue by StasKarpov** [mbrn/material-table#2561]
**Describe the bug**
When bulk editing table, icons from the actions column dissapear.

**To Reproduce**
https://material-table.com/#/docs/features/editable 
Go to "Bulk Edit Example"

1. Click on the "Edit All" pencil icon.
2. "Delete" button from Actions column dissapears.

**Expected behavior**
Buttons in the action column stay visible in bulk edit mode.

**Comment by akhilmhdh** [comment]
@StasKarpov I actually came across this just now. So for anyone missing the actions it will be on Top Right after searchbar. I think when activating bulk edit, instead of rendering action on each column they probably rendered it when selecting one.

**Comment by StasKarpov** [comment]
The problem is also that if you will specify only the actions for the whole table (like add new row or selection actions) the actions column will be rendered anyway.

Though I figured out that if you will provide options.actionsColumnIndex less then -1 then it won't be rendered at all, and than I can just add the custom actions column.

**Comment by julielanblue** [comment]
I'm also looking for a solution to this issue!

**Comment by testanalysis** [comment]
It seems there is a bug with Bulk Edit with Row Selection. When Options, Selection is True, and Bulk Edit is selected, all columns will shift to the right by a column.

**Comment by vicky8989** [comment]
i meet this problem too. when the options set selection:true,  actions button from actions props is disappear。looking for a solution.

**Comment by spenceg85** [comment]
not stale

**Comment by pallaviaggarwal28** [comment]
Not stale. Following. 
Also, in bulk edit, the whole table data is passed, even if there is a change in some rows. 
Can we just get the Row wise diff using bulk edit, so that only the actual updated rows are passed.

**Comment by 8kigai** [comment]
has this problem solved yet ?
