### ISSUE TITLE
Sorting of column is lost when toggle between pages.

### ISSUE THREAD

**Issue by pradeepkrishna1409** [mbrn/material-table#2566]
**Description**

Is there a way to preserve sorting of column when toggle between pages. I was able to preserve filter-settings and pagesize selections by pushing column and data props to parent state? 

Any ideas or help would be much appreciated.

**Comment by yehonadav** [comment]
ill vote up for this, i have an issue when rerendering the table data, im losing my sorting, is there a way to control the sort state?

**Comment by solty2212** [comment]
> ill vote up for this, i have an issue when rerendering the table data, im losing my sorting, is there a way to control the sort state?
@yehonadav 
Hi, I have a similar problem, do you find a solution?

**Comment by yehonadav** [comment]
haven't found one yet, meanwhile I'm implementing my own filters and serve the result to my table =(
