### ISSUE TITLE
Text Overflow: ellipsis

### ISSUE THREAD

**Issue by vinceliu21** [mbrn/material-table#257]
I have created a smaller width table. The cell of one column sometimes will have very long pieces of text. Currently the cell body keeps wrapping/stacking on top of each other and the row grows exponentially large in the table. Is there a way to do turn this cell into an ellipsis? I tried using cellStyle with textOverflow: ellipsis, but it did not work. 

![image](https://user-images.githubusercontent.com/9737822/53296393-072c3980-37c3-11e9-9a58-bfecd169f3f6.png)

**Comment by mbrn** [comment]
Hi @vinceliu21 ,

I will try your case asap.

**Comment by vinceliu21** [comment]
Thanks! Let me know if you want to see the code I tried or more pictures. Preferably, I would like the rows to stay the same size instead of having one row of data be 3x the size of another because the text in a cell was too long.

**Comment by mbrn** [comment]
Hi @vinceliu21 ,

Can you try this cellStyle

```javascript
cellStyle: { textOverflow: 'ellipsis', whiteSpace: 'nowrap', overflow: 'hidden', maxWidth: 100}
```

**Comment by rikr2sanchez** [comment]
I was going to ask about the possibility of displaying the full text in a tooltip, then I thought that it is better to show this in a detail component

**Comment by haroldjcastillo** [comment]
Addtional option:
```jsx
import styled from 'styled-components';

const TextOverflow = styled.div`
  width: ${(props) => (props.width ? `${props.width}px` : '300px')};
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
`;

export default TextOverflow;
```
Then,  modify the render and could be reused on any other column.
```jsx
render: (rowData) => (
      <TextOverflow width="100">{rowData.description}</TextOverflow>
    ),
```

**Comment by chen-bowen** [comment]
None of these works for me :/ please help
