### ISSUE TITLE
How to make a table mobile friendly?

### ISSUE THREAD

**Issue by tran-simon** [mbrn/material-table#2572]
I have the same problem as this user on stackoverflow: https://stackoverflow.com/questions/31678280/material-design-lite-how-to-display-table-on-mobile

Images taken from the stackoverflow question:

Desktop:

![desktop](https://i.stack.imgur.com/FzqGD.jpg)

Mobile:

![mobile](https://i.stack.imgur.com/g84PO.jpg)

Should I just not use material-table?

thanks

**Comment by DmitryKandratsenka** [comment]
Yeah, you should not use table for mobile app at all, or set min-width to make it scrollable.
i would use cards instead of table.
card can represent a single row. but it's more readable on small screen.
