### ISSUE TITLE
Reactjs: How to make all row checkbox check true when material table is loaded?

### ISSUE THREAD

**Issue by PriyankDeep** [mbrn/material-table#2573]
I am using react material table in my project and i want to make select all by default checked. How to achieve that??
```
function BasicSelection() {
  return (
    <MaterialTable
      title="Basic Selection Preview"
      columns={[
        { title: 'Name', field: 'name' },
        { title: 'Surname', field: 'surname' },
        { title: 'Birth Year', field: 'birthYear', type: 'numeric' },
        {
          title: 'Birth Place',
          field: 'birthCity',
          lookup: { 34: 'İstanbul', 63: 'Şanlıurfa' },
        },
      ]}
      data={[
        { name: 'a', surname: 'b', birthYear: c, birthCity: d },
        { name: 'e', surname: 'f', birthYear: g, birthCity: h },
      ]}        
      options={{
        selection: true
      }}
    />
  )
}
```

**Comment by dlopezd** [comment]
You can add the following in each object of your data
`tableData: { checked: true} `

**Comment by fofederico** [comment]
@dlopezd Hi! Where can i find all the props available por tableData? Do yo know if i can add data to row behind the scenes without "comitting" the line, something like "isEditing: true" ?

**Comment by dlopezd** [comment]
Hi @fofederico here is the doc: https://material-table.com/#/docs/all-props
I haven't work yet editing data with material-table. I could not help you 😞

**Comment by priyankdeeps78** [comment]
.
