### ISSUE TITLE
Poor table re-render performance, all elements are always re-rendered

### ISSUE THREAD

**Issue by Cristy94** [mbrn/material-table#2581]
Entire table, all rows and all cells always re-render when something changes, even though nothing related to those cells actually 
changed. This results in browser freezes between 50ms-1s (based on number of rows and row complexity) whenever you select a row or when anything triggers a table re-render.

![img](https://user-images.githubusercontent.com/1384885/97786276-ca753000-1baa-11eb-8e0a-21ec93fe0227.png)

I made sure the props I pass to the table are memoized, but it still says the props changed (components, options, icons, etc...) and there seems to be no way to stop the re-rendering of rows. I assume that it says that props (like "icons") changed, even though they didn't change because a new object is passed each time instead of a reference to the same object.

Other static elements (like table header, pagination, etc.) are always re-render even though they don't need to.

Is it possible to memoize the rows/cells so that they only re-render when props related to them actually change?

**Comment by peacechen** [comment]
Unfortunately mbrn is inactive and not merging PR's. Use the official community fork [@material-table/core ](https://github.com/material-table-core/core)instead.
