### ISSUE TITLE
loadingType linear position

### ISSUE THREAD

**Issue by Yehudamoskowitz** [mbrn/material-table#2582]
Hi, 
When loadingType=linear then the loading div is at the bottom of the table. However, when there are a lot of rows showing and table is reloading then the loading bar is not seen.
Would it be possible to add an option that when loadingType=linear then the loading div should be right under the title before the table rows so that it can be seen even when viewing say 100 rows per page.

Thank you

**Comment by AravindTReddy** [comment]
Any luck on this ? Would be a great asset to have it.
