### ISSUE TITLE
Cannot use Fixed columns with maxBodyHeight

### ISSUE THREAD

**Issue by hinsxd** [mbrn/material-table#2583]
**Describe the bug**
With FixedColumns and maxBodyHeight and when the table need scrolling, the body of the table (non fixed columns) are scrolled separately with the fixed ones.
**To Reproduce**
https://codesandbox.io/s/fixed-columns-with-maxbodyheight-kgiv3

**Expected behavior**
They scroll together.

**Screenshots**
https://imgur.com/Kzb843a

**Desktop (please complete the following information):**

- OS: macOS 10.15.7
- Browser: Chrome 86

**Comment by gmolabs** [comment]
+1

**Comment by developer-do** [comment]
+1

**Comment by gengengengengen** [comment]
+1, same issue happened to me ...

**Comment by Warasar** [comment]
+1
