### ISSUE TITLE
Multiple occurrences on a row with same id.

### ISSUE THREAD

**Issue by atishwarchand** [mbrn/material-table#2585]
Hey Guys, I am stuck with this issue where i want to combine the permissions table into 1 cell. (See the screenshot.)
Current View

<img width="1332" alt="Screenshot 2020-11-03 at 9 35 51 AM" src="https://user-images.githubusercontent.com/61366632/97922716-63799600-1db9-11eb-96af-20f645ad790a.png">

Probably the permissions should be separated by a comma, but all should be in just one cell. (Like screenshot)

![Screenshot 2020-11-03 at 9 45 22 AM](https://user-images.githubusercontent.com/61366632/97922839-94f26180-1db9-11eb-88b8-33e2ca461e4c.png)

My Data is coming like this... (PostMan Screenshot)
![Screenshot 2020-11-03 at 9 39 02 AM](https://user-images.githubusercontent.com/61366632/97922905-a9cef500-1db9-11eb-838a-9cf0bd1b2025.png)

My current Code:`import React, { useState, useEffect } from 'react';
import { forwardRef } from 'react';
import Grid from '@material-ui/core/Grid'

import MaterialTable from "material-table";
import AddBox from '@material-ui/icons/AddBox';
import ArrowDownward from '@material-ui/icons/ArrowDownward';
import Check from '@material-ui/icons/Check';
import ChevronLeft from '@material-ui/icons/ChevronLeft';
import ChevronRight from '@material-ui/icons/ChevronRight';
import Clear from '@material-ui/icons/Clear';
import DeleteOutline from '@material-ui/icons/DeleteOutline';
import Edit from '@material-ui/icons/Edit';
import FilterList from '@material-ui/icons/FilterList';
import FirstPage from '@material-ui/icons/FirstPage';
import LastPage from '@material-ui/icons/LastPage';
import Remove from '@material-ui/icons/Remove';
import SaveAlt from '@material-ui/icons/SaveAlt';
import Search from '@material-ui/icons/Search';
import ViewColumn from '@material-ui/icons/ViewColumn';
import axios from 'axios'
import Alert from '@material-ui/lab/Alert';
import Page from 'components/Page';
import {
    Col,
  } from 'reactstrap';

const tableIcons = {
  Add: forwardRef((props, ref) => <AddBox {...props} ref={ref} color='error'/>),
  Check: forwardRef((props, ref) => <Check {...props} ref={ref} color='primary'/>),
  Clear: forwardRef((props, ref) => <Clear {...props} ref={ref} color='error'/>),
  Delete: forwardRef((props, ref) => <DeleteOutline {...props} ref={ref} color='secondary' />),
  DetailPanel: forwardRef((props, ref) => <ChevronRight {...props} ref={ref} />),
  Edit: forwardRef((props, ref) => <Edit {...props} ref={ref} color='primary' />),
  Export: forwardRef((props, ref) => <SaveAlt {...props} ref={ref} />),
  Filter: forwardRef((props, ref) => <FilterList {...props} ref={ref} />),
  FirstPage: forwardRef((props, ref) => <FirstPage {...props} ref={ref} />),
  LastPage: forwardRef((props, ref) => <LastPage {...props} ref={ref} />),
  NextPage: forwardRef((props, ref) => <ChevronRight {...props} ref={ref} />),
  PreviousPage: forwardRef((props, ref) => <ChevronLeft {...props} ref={ref} />),
  ResetSearch: forwardRef((props, ref) => <Clear {...props} ref={ref} />),
  Search: forwardRef((props, ref) => <Search {...props} ref={ref} />),
  SortArrow: forwardRef((props, ref) => <ArrowDownward {...props} ref={ref} />),
  ThirdStateCheck: forwardRef((props, ref) => <Remove {...props} ref={ref} />),
  ViewColumn: forwardRef((props, ref) => <ViewColumn {...props} ref={ref} />)
};

const api = axios.create({
  baseURL: `http://localhost/admin/`
})

function validateEmail(email){
  const re = /^((?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\]))$/;
  return re.test(String(email).toLowerCase());
}

function ManageRoles() {

  var columns = [
    {title: "Role", field: "role_id"},
    {title: "Role Name", field: "role_name"},
    {title: "Permissions", field: "permission_name" }
  ]
  const [data, setData] = useState([]); //table data

  //for error handling
  const [iserror, setIserror] = useState(false)
  const [errorMessages, setErrorMessages] = useState([])
  const [selectedRow, setSelectedRow] = useState(null);

  useEffect(() => { 
    api.get("/getRoles")
        .then(res => {               
            setData(res.data.roles)
         })
         .catch(error=>{
             console.log(error)
             console.log("Error")
         })
  },[])

  const handleRowUpdate = (newData, oldData, resolve) => {
    //validation
    let errorList = []
    if(newData.role_name === ""){
      errorList.push("Please enter role name")
    }
    // console.log(newData);
    if(errorList.length < 1){
      var querystring = require('querystring');
        // stringify is known issue
        const datapost = querystring.stringify({
            role_name: newData.role_name,
        })
        const header = {
            headers: {
                "Content-Type": "application/x-www-form-urlencoded"
            }
        }
        console.log(datapost);
      api.put("/updateRole/"+newData.role_id, datapost, header)
      .then(res => {
        console.log(res.data)
        // const dataUpdate = [...data];
        // console.log(dataUpdate)
        // const index = oldData.tableData.role_id;
        // alert(dataUpdate)
        // dataUpdate[index] = newData;
        setData(res.data.roles);
        resolve()
        setIserror(false)
        setErrorMessages([])
      })
      .catch(error => {
        console.log(error)
        setErrorMessages(["Update failed! Server error"])
        setIserror(true)
        resolve()
        
      })
    }else{
      setErrorMessages(errorList)
      setIserror(true)
      resolve()

    }
    
  }

  const handleRowAdd = (newData, resolve) => {
    //validation
    let errorList = []
    if(newData.role_name === undefined){
      errorList.push("Please enter role name")
    }

    if(errorList.length < 1){ //no error
        var querystring = require('querystring');
        // stringify is known issue
        const datapost = querystring.stringify({
            role_name: newData.role_name,
        })
        const header = {
            headers: {
                "Content-Type": "application/x-www-form-urlencoded"
            }
        }
        console.log(datapost);
      api.post("/addRole", datapost, header)
      .then(res => {
        console.log(res)
        let dataToAdd = [...data];
        dataToAdd.push(newData);
        setData(res.data.roles);
        resolve()
        setErrorMessages([])
        setIserror(false)
      })
      .catch(error => {
        console.log(error)
        setErrorMessages(["Cannot add data. Server error!"])
        setIserror(true)
        resolve()
      })
    }else{
      setErrorMessages(errorList)
      setIserror(true)
      resolve()
    }

    
  }

  const handleRowDelete = (oldData, resolve) => {
    
    api.delete("/deleteRole/"+oldData.role_id)
      .then(res => {
        // const dataDelete = [...data];
        // const index = oldData.tableData.role_id;
        // dataDelete.splice(index, 1);
        console.log(res.data.roles)
        setData(res.data.roles);
        resolve()
      })
      .catch(error => {
        setErrorMessages(["Delete failed! Server error"])
        setIserror(true)
        resolve()
      })
  }

  return (
    <Page title="View Roles" breadcrumbs={[{ name: 'role / view', active: true }]}> 
    <div className="App">
      
      <Col xl={12} lg={12} md={12}>
      <Grid container spacing={1}>
      <Grid item xs='3'></Grid>
          <Grid  item xs='12' >
          <div>
            {iserror && 
              <Alert severity="error">
                  {errorMessages.map((msg, i) => {
                      return <div key={i}>{msg}</div>
                  })}
              </Alert>
            }       
          </div>
            <MaterialTable
              title="ROLES"
              columns={columns}
              data={data}
              icons={tableIcons}
              options={{
                headerStyle: {
                  backgroundColor: '#0a5e9c',
                  color: '#FFF'
                },
                exportButton:true,
                actionsColumnIndex: -1
              }}
              onRowClick={((evt, selectedRow) => setSelectedRow(selectedRow.tableData.id))}
              editable={{
                onRowUpdate: (newData, oldData) =>
                  new Promise((resolve) => {
                      handleRowUpdate(newData, oldData, resolve);
                      
                  }),
                onRowAdd: (newData) =>
                  new Promise((resolve) => {
                    handleRowAdd(newData, resolve)
                  }),
                onRowDelete: (oldData) =>
                  new Promise((resolve) => {
                    handleRowDelete(oldData, resolve)
                  }),
              }}
            />
          </Grid>
          <Grid item xs={3}></Grid>
        </Grid>
        </Col>
    </div>
    </Page>
  );
}

export default ManageRoles;`

Please do help as i am new to this. thanks

**Comment by padgad336** [comment]
you can set data <MaterialTable
    // other props
           data={data.map((row, index) => ({
          ...row,
          index: index + 1,
        }))}
/>
