### ISSUE TITLE
Header columns nesting using column object(json)

### ISSUE THREAD

**Issue by tshrb** [mbrn/material-table#2599]
I want to render nested columns inside material table. I know it is possible using [Component Overriding](https://material-table.com/#/docs/features/component-overriding).

A good example has been already shared here in the issue tracker: [https://codesandbox.io/s/gracious-hawking-sqx1i
](https://codesandbox.io/s/gracious-hawking-sqx1i
).

The problem with this approach is that you need to know all the columns in advance.

My use case is that I get columns from API dynamically and I want to render these nested columns using column object. This means that I need something like this: [https://codesandbox.io/s/staging-pond-chkoq](https://codesandbox.io/s/staging-pond-chkoq)

```javascript
const columns = [
    {
      field: "lowerA",
      title: "lowerA",
      children: [
        {
          field: "lowerAChild1",
          title: "lowerAChild1"
        },
        {
          field: "lowerAChild2",
          title: "lowerAChild2"
        }
      ]
    },
    { field: "upperA", title: "upperA" },
    { field: "lowerB", title: "lowerB" },
    { field: "upperB", title: "upperB" }
  ];
```

Is this possible in any way?

**Comment by tshrb** [comment]
Here is the same question in stackoverflow: [https://stackoverflow.com/questions/64804797/header-columns-nesting-using-column-objectjson](https://stackoverflow.com/questions/64804797/header-columns-nesting-using-column-objectjson)

**Comment by thedoctorde** [comment]
> Here is the same question on stackoverflow: https://stackoverflow.com/questions/64804797/header-columns-nesting-using-column-objectjson

This question is not available anymore. Please re-open the issue
