### ISSUE TITLE
How Can I pass rowData to custom rendered switch's on change method

### ISSUE THREAD

**Issue by priyankakumari1011** [mbrn/material-table#260]
I have a custom rendered column in my table. I want to get rowData on change of that switch

![image](https://user-images.githubusercontent.com/41110363/53398671-349a0280-39d0-11e9-8fac-807016a603d6.png)

**Comment by priyankakumari1011** [comment]
I got the solution. I can get the rowData in render itself.

**Comment by alyssonmessias** [comment]
@priyankakumari1011 can you show example that how resolved this problem? 
I have the same problem and I am not getting it to work, when the page changes it does not update the component.

**Comment by priyankakumari1011** [comment]
@alyssonmessias  This is how I was doing that (this method was being called inside render)

setColumns = (roles) => {
    this.columns = []
    this.columns.push({ title: 'DeviceId', field: 'id' })
    this.columns.push({ title: 'Device Type', field: 'deviceType' })
    this.columns.push({ title: 'Platform Id', field: 'platformId', hidden: true})
    this.columns.push({ title: 'Primary Owner', field: 'primaryOwner' })
    this.columns.push({ title: 'IsFree', field: 'isFree', hidden: true, searchable: false, render: rowData => {
      return (
        <span>{rowData.isFree.toString()}</span>
      )
    } })
      this.columns.push({
        title: 'IsDedicated', field: 'isDedicated', filtering: false, searchable: false, render: rowData => {
          return (
            <Switch
              disabled={!roles.changeDedicated}
              checked={rowData.isDedicated}
              onChange={(event) => {
                this.handleChange(event, rowData)
              }}
              value={rowData.isDedicated}
            />
          )
        }
      }) 
    
    this.columns.push({
      title: 'IsFaulty', field: 'isFaulty', hidden: true, searchable: false, render: rowData => {
        return (
          <span>{rowData.isFaulty.toString()}</span>
        )
      }
    })
  }
