### ISSUE TITLE
Freezing UI on rowStyle: Paused before potential out-of-memory crash

### ISSUE THREAD

**Issue by alexdobsom** [mbrn/material-table#2601]
**Bug descriptions**
 Every time, after one or two clicks on the buttons of my UI, I get a permanent freeze of the entire interface. I tested it with multiple versions and still encounter the same problem. After a few seconds of freezing the browser goes in debug mode (see screenshot below)

I have dynamic **columns** based on the current page I'm viewing
```javascript
columns={ columns }
```
**which appears that is causing the problem !!!**

**How to reproduce**
I have this code in the table's options:
```javascript
options={{ 
         rowStyle: (rowData) => ({
                backgroundColor: rowData.highlighted === true ? "#ffeb3b5c" : ""
                color: rowData.red === true ? "red" : "", 
          })
}}
```
**Screenshots**
This is what's happening in the browser's in Sources via Inspect. It is actually going in debug mode after a few seconds of freezing:

![image](https://user-images.githubusercontent.com/30396343/98740656-19457580-23b4-11eb-86c0-bace3d5bc2a4.png)

I don't know how to fix this issue.

**Comment by Kogl1n** [comment]
I experience exactly the same freeze problem and could narrow it down to rowStyle:
```        
rowStyle: (rowData, index) => {
          if (index % 2) {
            return {backgroundColor: "#f2f2f2", maxHeight: '50px'}
          } else {
            return {maxHeight: '50px'}
          }
      }
```
When the table component is shown performance goes down that simple Radio Button click animations become slower and slower.

**Comment by alexdobsom** [comment]
> I experience exactly the same freeze problem and could narrow it down to rowStyle:

@Kogl1n Do you have dynamic columns? If so, try to make them static.

**Comment by Kogl1n** [comment]
@alexdobsom Indeed. I first thought the problem was caused by the loop rendering multiple tables (but limited amount) from data I receive from an endpoint API. I will try using static columns and make the tables visible depending on the data I receive. It worked perfectly in this way before, though.

**Comment by alexdobsom** [comment]
@Kogl1n it seems that the more rules and conditions you add to your app the best is to have the columns in your Table.jsx file. If you pass them as props, they may cause the entire app to halt or even crash.
For me it worked by having a switch conditional before the table, based on the location.pathname so it returned me the needed columns based on the current page. The data works even if I passed it as a prop.

Previously I was using the column data from props. 

It worked before I added row styling however.

**Comment by danielgp1984** [comment]
I also have the same problem from version 1.64.0 or higher

**Comment by andyvanhelsing** [comment]
can confirm, v1.68.1 does not seem to have this problem

**Comment by danielgp1984** [comment]
I am executing version 1.68.0 and this version no have problem.

**Comment by RedFish** [comment]
Did you try to use `useCallback` to declare your function ?

```
const rowStyle = useCallback((rowData, index) => {
          if (index % 2) {
            return {backgroundColor: "#f2f2f2", maxHeight: '50px'}
          } else {
            return {maxHeight: '50px'}
          }
}, []);
```

**Comment by danielgp1984** [comment]
Yes, I am trying but I am not successful, only in version 1.68.0 I am successful, with or without callback

**Comment by peacechen** [comment]
Unfortunately mbrn is inactive and not merging PR's. Use the official community fork [@material-table/core ](https://github.com/material-table-core/core)instead.
