### ISSUE TITLE
How could change or remove on column reisizing icon

### ISSUE THREAD

**Issue by yuniwahuni** [mbrn/material-table#2603]
First,  thank you very much  for mbrn's effort (and other contributors).

I'm using column resize function. (v1.69)
how could I remove or empty or change column resizable  icon... 
below attaed image.

![matcolumn](https://user-images.githubusercontent.com/21077163/98891306-46dc0d00-24e1-11eb-9b95-19e2e1883805.PNG)

**Comment by yuniwahuni** [comment]
I got it myself.
https://github.com/mbrn/material-table/issues/51#issuecomment-429316397

**Comment by git2467** [comment]
> I got it myself. thanks too @mbrn.^^ [#51 (comment)](https://github.com/mbrn/material-table/issues/51#issuecomment-429316397)

how did you do it?
