### ISSUE TITLE
Enable and Disabling Pagination Buttons

### ISSUE THREAD

**Issue by petermarks12** [mbrn/material-table#2604]
I have been through docs and could not find any prop which can be used to enable and disable those next and previous pagination buttons.

I want to implement custom pagination where data is going to arrive per page basis because I do not want to flood table with 50K entries.

If the api returns 25 entries and page size is 25 rows, then those buttons are automatically disabled.  There is no way to keep them enabled so that on press of next or previous button we can make more requests.  If  there is solution to this problem, please let me know.

**Comment by fahadali6767** [comment]
Same question

**Comment by DmitryKandratsenka** [comment]
@petermarks12  @fahadali6767 , i believe the better choice here to override pagination bar component:
![image](https://user-images.githubusercontent.com/74970709/100102610-222e5080-2e64-11eb-903f-1e30d8bc2d78.png)

**Comment by smargoli2** [comment]
Anyone find a solution for this?
