### ISSUE TITLE
How to adjust the width of the Material Table and how do I make the icons show up?

### ISSUE THREAD

**Issue by brittanywang** [mbrn/material-table#261]
Right now my icons are now showing up as shown in screenshot below: 
<img width="1318" alt="screen shot 2019-02-26 at 9 02 43 pm" src="https://user-images.githubusercontent.com/35832643/53467237-31236d00-3a0a-11e9-802c-708de7ad25df.png">
would the code simply be:
```
<MaterialTable
     icons={
                { Search, NextPage }
                }
     columns={[....]}
 />
```
I tried doing so, but I got this error:
![image](https://user-images.githubusercontent.com/35832643/53469941-b875de00-3a14-11e9-8942-b929e0d686ba.png)

In addition, is there a way to adjust the size of Material Table itself? I don't see a width/height prop. 

Thank you so much in advance!

**Comment by brittanywang** [comment]
Is there also a way to disable displaying:
<img width="310" alt="screen shot 2019-02-26 at 10 47 31 pm" src="https://user-images.githubusercontent.com/35832643/53471132-90887980-3a18-11e9-9af6-2329809f77a8.png">

**Comment by vinceliu21** [comment]
I also have a similar question. Is there a way to adjust the width of both the table itself and respective columns of the table?

**Comment by JWLangford** [comment]
@brittanywang for your question about displaying the Rows per page: 
`<MaterialTable
  options={{ paging: false }}
/>
`
That did it for me.

**Comment by brittanywang** [comment]
@JWLangford thank you!

**Comment by mbrn** [comment]
To set width of columns use both cellStyle and headerStyle: 

```javascript 
{ title: 'Name', field: 'name',
     cellStyle: {
       width: 20,
       maxWidth: 20
     },
     headerStyle: {
       width:20,
       maxWidth: 20
     }
    },
```

**Comment by mbrn** [comment]
for table width you can cover table with a `div` that has its own width

**Comment by brittanywang** [comment]
@mbrn thank you for your comments! I am still unable to display the icons. Do you have any suggestions? Currently I'm using: 
```
<MaterialTable
     icons={
                { Search, NextPage }
                }
     columns={[....]}
 />
```
Thank you for your time!

**Comment by mbrn** [comment]
@brittanywang How did you import icons Search and NextPage

**Comment by brittanywang** [comment]
@mbrn forgot to close this, resolved in (#93). Many thanks again!

**Comment by indraneelpradhan** [comment]
when i set data table in container, it exceeds than container, how i fix this issue

**Comment by juliosilvacwb** [comment]
I had the same problem, but I solved as

cellStyle: {
                width: 300,
                minWidth: 300
            },
            headerStyle: {
                width: 300,
                minWidth: 300
            },
...

If you want to down size use maxWidth, but if you want to up size use minWidth

**Comment by royliu007** [comment]
> Is there also a way to disable displaying:
> <img alt="screen shot 2019-02-26 at 10 47 31 pm" width="310" src="https://user-images.githubusercontent.com/35832643/53471132-90887980-3a18-11e9-9af6-2329809f77a8.png">

in the options you can disable the pagination by using `paging: false`
```
options = {{
    paging: false
}}

**Comment by nettycoons-soft-team-hp** [comment]
@mbrn can you update the 
m-table-header.js to have the width not being overridden by custom setup?

**Comment by jaggaer-npasic** [comment]
> but if you want to up size use minWidth

it's not working...

**Comment by Henao** [comment]
> > but if you want to up size use minWidth
> 
> it's not working...


It's true, it doesn't work, but this does: Put width: 120 (or whatever value you need) as an attribute of the column, just like you do with title: "my title", width: 50, ... etc
https://material-table.com/#/docs/features/fixed-columns

**Comment by Strauteka** [comment]
This works for me.

With Gson in backend as json.

*JsonDataKeys:* simple enum to store names.

``` Java
public static JsonObject getKeyCell() {
        JsonObject key = new JsonObject();
        key.addProperty(JsonDataKeys.title.name(), "Key");
        key.addProperty(JsonDataKeys.field.name(), JsonDataKeys.key.name());
        key.addProperty(JsonDataKeys.editable.name(), "never");

        JsonObject keyCellStyle = new JsonObject();
        keyCellStyle.addProperty("maxWidth", "200px");
        key.add("cellStyle", keyCellStyle);
        key.add("headerStyle", keyCellStyle);
        key.addProperty("width", "200px");
        return key;
    }
```

**Comment by RoosterH** [comment]
It looks like the min value is 100. 
I tried 
cellStyle: {
backgroundColor: '#bfbfbf',
color: '#000000',
width: 100,
maxWidth: 100
},
headerStyle: {
backgroundColor: '#bfbfbf',
color: '#000000',
width: 100,
maxWidth: 100
}
It only works for number above 100.  Cannot go any lower.

**Comment by GersonDias** [comment]
having the same here, if I put something below 100, it's doesn't work... so, I need a column for a "row number" that should be way smaller than the other fields... it isn't possible?

**Comment by jagadeeshkoka** [comment]
> To set width of columns use both cellStyle and headerStyle:
> 
> ```js
> { title: 'Name', field: 'name',
>      cellStyle: {
>        width: 20,
>        maxWidth: 20
>      },
>      headerStyle: {
>        width:20,
>        maxWidth: 20
>      }
>     },
> ```

This one is not working for me 

`<MaterialTable
                icons={Common.tableIcons}
                title=""
                columns={[
                  {
                    field: "sNo",
                    title: " S.No",
                    headerStyle: {
                      fontWeight: "bold",
                      width: 2,
                      maxWidth: 2,
                    },
                    cellStyle: { width: 2, maxWidth: 2 },
                  },
                  {
                    field: "downtimeId",
                    headerStyle: { fontWeight: "bold" },
                    title: "System Downtime ID",
                  },

                  {
                    field: "startDateTime",
                    title: "Start Date/ Time",
                    headerStyle: { fontWeight: "bold" },
                  },
                  {
                    field: "endDateTime",
                    title: "End Date/ Time",
                    headerStyle: { fontWeight: "bold" },
                  },
                  {
                    field: "message",
                    headerStyle: { fontWeight: "bold" },
                    title: "Error Message",
                  },
                  {
                    // field: "action",
                    title: "Action",
                    headerStyle: { fontWeight: "bold" },

                    type: "text",
                    render: (rowData) => (
                      <>
                        {" "}
                        <Link style={{ cursor: "pointer" }}>
                          {" "}
                          <EditIcon color="primary" fontSize="small" />{" "}
                        </Link>
                        <Link style={{ cursor: "pointer" }}>
                          {" "}
                          <DeleteIcon color="primary" fontSize="small" />{" "}
                        </Link>
                      </>
                    ),
                  },
                ]}
                options={{ exportButton: true, paginationType: "stepped" }}
                data={rows}
              ></MaterialTable>`

I doesn't reflect on screen.

**Comment by abhinav2000kiit** [comment]
> > To set width of columns use both cellStyle and headerStyle:
> > ```js
> > { title: 'Name', field: 'name',
> >      cellStyle: {
> >        width: 20,
> >        maxWidth: 20
> >      },
> >      headerStyle: {
> >        width:20,
> >        maxWidth: 20
> >      }
> >     },
> > ```
> 
> This one is not working for me
> 
> ```
>         `<MaterialTable
>             icons={Common.tableIcons}
>             title=""
>             columns={[
>               {
>                 field: "sNo",
>                 title: " S.No",
>                 headerStyle: {
>                   fontWeight: "bold",
>                   width: 2,
>                   maxWidth: 2,
>                 },
>                 cellStyle: { width: 2, maxWidth: 2 },
>               },
>               {
>                 field: "downtimeId",
>                 headerStyle: { fontWeight: "bold" },
>                 title: "System Downtime ID",
>               },
> 
>               {
>                 field: "startDateTime",
>                 title: "Start Date/ Time",
>                 headerStyle: { fontWeight: "bold" },
>               },
>               {
>                 field: "endDateTime",
>                 title: "End Date/ Time",
>                 headerStyle: { fontWeight: "bold" },
>               },
>               {
>                 field: "message",
>                 headerStyle: { fontWeight: "bold" },
>                 title: "Error Message",
>               },
>               {
>                 // field: "action",
>                 title: "Action",
>                 headerStyle: { fontWeight: "bold" },
> 
>                 type: "text",
>                 render: (rowData) => (
>                   <>
>                     {" "}
>                     <Link style={{ cursor: "pointer" }}>
>                       {" "}
>                       <EditIcon color="primary" fontSize="small" />{" "}
>                     </Link>
>                     <Link style={{ cursor: "pointer" }}>
>                       {" "}
>                       <DeleteIcon color="primary" fontSize="small" />{" "}
>                     </Link>
>                   </>
>                 ),
>               },
>             ]}
>             options={{ exportButton: true, paginationType: "stepped" }}
>             data={rows}
>           ></MaterialTable>`
> ```
> 
> It doesn't reflect on screen. columns are still the same way they are.

yes this is no more working. please tell what to do and how to do. i am worried.

**Comment by mpalverca** [comment]
try to put in <div className></div> :
root: {
        maxWidth: '100%',
        maxHeight: '100%',
       
      },
this can show all fields of the material-table

**Comment by fappaz** [comment]
After a lot of struggle to set a relative width to the column, I tried several combinations of settings and [posted the solution (including a codesandbox) here](https://stackoverflow.com/a/68752376/2516673).

This is the one that worked best for me:

```js
<MaterialTable
  columns={[
    { title: "Name", field: "name" },
    { title: "Email", field: "email" },
    {
      title: "Status",
      field: "status",
      cellStyle: {
        cellWidth: '15%'
      }
    }
  ]}
  data={users}
  options={{
    tableLayout: 'auto'
  }}
/>
```

**Comment by SujuDghub** [comment]
@brittanywang This is how i use.
const actions = [
    {
      icon: () => <ModeEditOutlineIcon sx={{ color: "#01579B" }} />,
      tooltip: "Edit Logistics",
      onClick: (event, rowData) => handleEditRowData(rowData),
    },
    {
      icon: () => <DeleteIcon sx={{ color: "#01579B" }} />,
      tooltip: "Remove Logistics",
      onClick: (event, rowData) => handleDeleteRowData(rowData),
    },
  ];

<MaterialTable
        icons={tableIcons}
       ..................
        actions={actions}
      />
