### ISSUE TITLE
How to use exportCsv function?

### ISSUE THREAD

**Issue by chenei** [mbrn/material-table#2616]
Hi all,
I have a table with TreeData. currently, the exportAllData prop doesn't work well, and collapsed rows don't get export.
I saw that there is any option to use exportCsv, I understand the input but I am not sure what I should return so it will trigger the export.

Can someone please provide an example?

**Comment by chenei** [comment]
I found this, thanks
https://github.com/mbrn/material-table/blob/master/src/components/m-table-toolbar.js#L58

**Comment by yonihorwitz** [comment]
Hi @chenei - please let me know if you make any progress on printing treedata.  I'm currently working through the same issue.

**Comment by chenei** [comment]
Hi @yonihorwitz ,
I think I am going to use the same implementation with the CSVBuilder. 
Probably going to loop through all the childs. I will post the implementation when I have it.

**Comment by yonihorwitz** [comment]
Same.  I was stuck on where to find the child data until I saw the childData property in each row...

```
options={{
                exportCsv: (columns, data) => {
                  var new_data = [];
                  
                  data.forEach(d => {
                    new_data.push(d);
                    if (!!d.tableData.childRows)
                    d.tableData.childRows.forEach(r => {
                      new_data.push(r);
                    });                    
                  });

                  const builder = new CsvBuilder("output.csv");
                  builder
                    .setColumns(columns.map((columnDef) => columnDef.title))
                    .addRows(new_data.map((rowData) =>
                      columns.map((columnDef) => rowData[columnDef.field])
                    ))
                    .exportFile();
                }
}
```
