### ISSUE TITLE
How to remove unwanted space in the pagination if no enough data ?

### ISSUE THREAD

**Issue by athuldom** [mbrn/material-table#2620]
# Guidelines

- #### Please include a demo of the issue/behavior/question you have
If there are 20 rows selected in the pagination rows, and only 10 data present on the table, but the space for 10 data is allocated simply. How can i remove such unwanted space from there ? 
- #### Please try to be as detailed as possible
![u267](https://user-images.githubusercontent.com/67672807/99370007-2944e400-28e3-11eb-9658-5295c7430e3d.PNG)

Like in the above image there is an unwanted space there, how to remove that ?

**Comment by dnohashi** [comment]
That can be addressed via option: { emptyRowsWhenPaging: false }
https://material-table.com/#/docs/all-props

**Comment by athuldom** [comment]
Thank you, it worked
