### ISSUE TITLE
Column.validate is not working with cellEditable

### ISSUE THREAD

**Issue by MichaelKapustey** [mbrn/material-table#2621]
**Describe the bug**
No validation error displayed while using cellEditable

**To Reproduce**

1. Go to https://material-table.com/#/docs/features/editable
2. Open Cell Editable Example
3. Add validation to first column
`{ title: 'Name', field: 'name', validate: rowData => ({ isValid: false, helperText: 'Name cannot be empty' })`
4. Click on any cell in first column and see that error is not visible

**Expected behavior**
Error should be visible

***Details***
m-table-edit-cell.js should check columnDef.validate and pass result to inner EditComponent error property

**Comment by asok-mirror** [comment]
An alternate way would be 

validate: rowData => (rowData.name === undefined || rowData.name.trim() == '') ? 'Name cannot be Empty' : true

**Comment by ankgupta067** [comment]
> An alternate way would be
> 
> validate: rowData => (rowData.name === undefined || rowData.name.trim() == '') ? 'Name cannot be Empty' : true

Issue what i see is validate method itself is not getting called .

**Comment by MatthewSmithLexacom** [comment]
I was wondering why my validation wasn't working from example

**Comment by patrickviscount** [comment]
Having the same issue

**Comment by MichaelKapustey** [comment]
Hey @patrickviscount . Its highly unlikely this package will be updated. There is a fork "[@material-table/core](https://github.com/material-table-core/core)". Try posting the issue there. Or, maybe it was fixed already
