### ISSUE TITLE
Versions are unnecessarily pinned

### ISSUE THREAD

**Issue by ATLUSio** [mbrn/material-table#2626]
**Log of error**

```
npm ERR! Found: @material-ui/core@4.11.0
npm ERR! node_modules/@material-ui/core
npm ERR!   @material-ui/core@"^4.9.2" from the root project
npm ERR! Could not resolve dependency:
npm ERR! peer @material-ui/core@"4.0.1" from material-table@1.69.2
npm ERR! node_modules/material-table
npm ERR!   material-table@"^1.69.0" from the root project
```

This occurs with the following dependency:

```
"material-table": "^1.69.0",
"@material-ui/core": "^4.9.2",
```

The most recent commit to this repo in the package.json removed the carat (^) before all packages, and I don't think that is intended. It forces the users of this package installing the latest version into the version the package.json specifies.

**Describe the bug**

When removing the carats (^) before the package versions, `material-table` is _requiring_ the users of this package to have their versions pinned. So, for example, I cannot use `material-ui` version `4.11.0` because this package requires me to use `4.0.1` as per the latest version `1.69.2`.

**To Reproduce**

Installing `material-table` version 1.69.2 will cause this error to occur.

**Expected behavior**

I expect that I should be able to use `material-ui` `4.0.1` and newer, so `4.11.0` should be a valid.

**Additional context**

I don't think this was intended. Can we verify whether this is or not?

Commit in question: https://github.com/mbrn/material-table/commit/c6c98c84050b541b2a9ce1b7741eeaae8a5806e0

**Comment by mnoster** [comment]
I am experiencing the same issue at the moment

**Comment by FedeBev** [comment]
Hi there,
I'm facing the same issue.

If this is not intended I will address this with a PR with the fix, can someone give me a feedback?

Thanks

**Comment by shubhamappstec** [comment]
I am facing same issue
