### ISSUE TITLE
Allow for custom action buttons

### ISSUE THREAD

**Issue by SamuelPoulin** [mbrn/material-table#2627]
# Guidelines

- #### Please include a demo of the issue/behavior/question you have

![Oval icon button](https://user-images.githubusercontent.com/35999846/99571075-d9c4ed80-29a0-11eb-8c82-0168edbdd425.PNG)

- #### Please try to be as detailed as possible

As you can see here, since the action buttons on the table are IconButtons, adding anything that has different height and width values distorts the button highlight into an oval shape. In this case, I have a Chip component instead of an icon, which triggers the behavior.

**Describe the solution you'd like**

Is there any way we could provide the entire button component if wanted? This would enable greater customization for tables.

**Comment by asok-mirror** [comment]
just add this to actions, it should work.

{
        icon: props => <SettingsApplicationsSharp className="fill-detailsButton" />,
        tooltip: "Application Details",
        onClick: (event, rowData) => handleDetailsClick(rowData)
    }

**Comment by SamuelPoulin** [comment]
This is a nice way to not use something else than icons if you need to also explain the icon's action on hover, but is unfortunately not a replacement to having complete control over the action buttons.

Material's Chip component looks great at the end of a row as a button and I'm trying to figure out a way to use it instead of the icon button.

**Comment by bgbbmm** [comment]
This is very annoying that you have to have all actions inside IconButton. I want to have a regular button with text displayed, and something like this _should_ be easy, however it is not. This feature would help without having to re-write entire components of the table.
