### ISSUE TITLE
Column Width not being respected

### ISSUE THREAD

**Issue by brunomptorres** [mbrn/material-table#2633]
After the newly released 1.6.2, the column widths stopped being respected. Until now we just set the `width` parameter in the columns configuration and that made the columns have that width, but since the update, the column's widths are automatically calculated. 

Did this configuration changed or is this a bug that was introduced? If this was intentional how should we lock the width of the columns from now on?

Example of how we've been doing so far:
```
const columns = [
        {
            title: "Status",
            sorting: false,
            render: ({ status }) => status,
        },
        {
            render: (rowData) => getActionButtons(rowData),
            width: 150,
        },
        {
            title: "Actions",
            field: "more",
            sorting: false,
            headerStyle: { textAlign: "center" },
            cellStyle: { textAlign: "right" },
            render: (rowData) => getButtons(rowData),
            width: 120,
        },
        {
            render: ({ uuid, status }) => getGoTo(uuid, status),
            width: 40,
        },
];
```

**Comment by zeckdude** [comment]
Sounds like this may fix that? https://github.com/mbrn/material-table/pull/2511

**Comment by brunomptorres** [comment]
@zeckdude if the `width` parameter starts to be taken into account again, it should solve it.

**Comment by avionbg** [comment]
> Sounds like this may fix that? #2511

That will only allow us to apply width by using headerStyle / cellStyle together. Width is still overwritten with the CommonValues.reducePercentsInCalc function...

**Comment by zeckdude** [comment]
Ah ok. I reverted to 1.64.0 for now and that solved it

**Comment by brunomptorres** [comment]
We reverted to 1.69.1 and locked it there for now, as it works as we expect.

**Comment by MglMX** [comment]
Version 1.69.1 works fine for me to set the width of a column.

In version 1.69.2, the width seems to be ignored again.

**Comment by OnkelTem** [comment]
1.69.3 - I don't see any regularity it the calculation of columns width.

```
        columns={[
          { title: t('ID'), field: 'id', type: 'numeric', width: 1 },
          { title: t('Name'), field: 'name', width: 1 },
          { title: t('Bitrate'), field: 'bitrate', type: 'numeric', width: 2 },
        ]}
```

makes each column to have `width: calc(146.333px);` style. I.e. - equal. 
So it's still buggy.

**Comment by Lionqueen94** [comment]
It would be nice if this issue can fixed. We are also locked on v1.69.1 due to this bug...

**Comment by Lionqueen94** [comment]
Bump, still not fixed

**Comment by arulprabhin** [comment]
Still there in v2.0.3
