### ISSUE TITLE
Is there any way to insert html in the column title?

### ISSUE THREAD

**Issue by Andrey-Mayanov** [mbrn/material-table#2642]
Hi! I need to make it so that there is a question mark with a tooltip next to the title text. Is there a way? Thanks!

**Comment by DmitryKandratsenka** [comment]
@Andrey-Mayanov every column object receives `title` prop. It can be string or React.Element.

![image](https://user-images.githubusercontent.com/74970709/100109012-b223c880-2e6b-11eb-9eb2-cb426927cc11.png)

**Comment by Andrey-Mayanov** [comment]
hmm, really. The site has old information, thank you!
