### ISSUE TITLE
Make row selection controllable: developer should decide if row is selected or not

### ISSUE THREAD

**Issue by DmitryKandratsenka** [mbrn/material-table#2644]
> Because i dont want to lose selected state of a row after a render. There is another option to do this. I could keep selected in another field of table state. But by this way i need a id field to map data.

Why do you want to store selected values? selected values should be controllable outside of material-table.
for example i can't make selectable some rows, which i want to select by default.

So, you could just make it controllable introducing new field. 

it's better to rely on ID field.
or even better, make new field - comparator - so developer decide itself how to compare two rows between each other. and by default it will be comparison by IDs. Check material-ui Autocomplete#getOptionSelected as an example.
or we can introduce function property `isRowSelected`, we will compare some local state with every table row and decide if it's selected or not ourselves.

mutation of rows which user of component passed as properties is very bad practice.

what do you think, @mbrn?

P.S. very thanks for your work and for this library, i like it, but want to improve some things. i appreciate it!

_Originally posted by @DmitryKandratsenka in https://github.com/mbrn/material-table/issues/414#issuecomment-732976827_

**Comment by khrishan** [comment]
I am using it in my project  where I manually create the `tableData` element before passing to the `<MaterialTable />` component and set the checked value to what we have stored in the DB/redux

our issue now is that we have a table with children parts - when the state changes, this forces the table to re-render and thus forgets what rows have been expanded (as I am overriding the tableData variable) - which our users are finding really annoying

...which I agree with @DmitryKandratsenka isn't best practice

if I could set whether a value can be checked or not, that would remove my really bad/not working workaround (yn)

**Comment by LukeHardyLexacom** [comment]
> I am using it in my project where I manually create the `tableData` element before passing to the `<MaterialTable />` component and set the checked value to what we have stored in the DB/redux
> 
> our issue now is that we have a table with children rows- when the state changes, this forces the table to re-render and thus forgets what rows have been expanded (as I am overriding the tableData variable) - which our users are finding really annoying
> 
> ...which I agree with @DmitryKandratsenka isn't best practice
> 
> if I could set whether a value can be checked or not, that would remove my really bad/not working workaround (yn)

Hi @khrishan,

Could you please share part of your code where you are building your tableData element before passing through to material table?
