### ISSUE TITLE
Table width off the screen with selection = true

### ISSUE THREAD

**Issue by WendySclerandi** [mbrn/material-table#2647]
I upgraded from 1.67.1 to 1.69.2 and now in the tables where I have selection = true the width of the table does not fit the screen. I have tableLayout = 'fixed' set and I tried change it but it behaves the same way.

Before update:
![image](https://user-images.githubusercontent.com/21165322/100127155-95809400-2e5d-11eb-9bde-e994e281aa6d.png)

After:
![image](https://user-images.githubusercontent.com/21165322/100125183-3d489280-2e5b-11eb-80c3-1eb4bb8cebc9.png)
![image](https://user-images.githubusercontent.com/21165322/100125198-433e7380-2e5b-11eb-9ee6-89373baadb41.png)

**Comment by Samurus** [comment]
Some rendering bugs seem to happen in versions after 1.67.1
https://github.com/mbrn/material-table/issues/2643
https://github.com/mbrn/material-table/issues/2650
It might be related.
