### ISSUE TITLE
Is stable column sort supported?

### ISSUE THREAD

**Issue by TheDiveO** [mbrn/material-table#2648]
While reading and looking through the (highly appreciated!) documentation, I could not find any indication as to whether stable sorting is supported or not. The sortable table example of material-ui.com shows this feature and I would like to use it in my own projects because it allows multi-column sorting without additional support code for multi-selections. Users simply sort columns in the (albeit) reverse order of what they want the sort to be.

Looking at your examples I see that a compare function for sorting is supported; unfortunately, this does not support stable sorting in itself. The reason is that you need information about the element's order before the sort started, where this information often is simply in the form of element indices.

Do you plan to support stable column sorting; if yes, is there some E.T.A.?

**Comment by TheDiveO** [comment]
ping?

**Comment by zoosm3** [comment]
@TheDiveO I am not sure of "stable", but I think you can use customSort to define your own stable sort order.

https://material-table.com/#/docs/features/sorting Custom Sorting Algorithm Example
