### ISSUE TITLE
Responsive table footer

### ISSUE THREAD

**Issue by lasren** [mbrn/material-table#265]
**Is your feature request related to a problem? Please describe.**
On lower resolution screens & mobile we have table on vertical scroll -> responsive. But pagination is behind the scroll, so it's not responsive. For this reason on mobile resolutions we have all page vertical scroll (because footer text doesn't fit) and datatable scroll (2 vertical scrools on page is bad practice).
Problem screenshot: https://imgur.com/a/usRA578
How need to be: https://imgur.com/a/jjG8QdB

**Describe the solution you'd like**
Maybe the solution can be to put tfoot (table footer) to upper div, which is div style overflow-x: auto  .That way, table footer will be also on vertical scroll.
Example: https://imgur.com/a/vNQ8H5S

**Describe alternatives you've considered**
1) Alternative - make all table responsive. Tooltip, body,tfoot and everything on mobile need to be responsive. 
2) Hide "Rows per page:" text on mobile.

**Additional context**
Please check material table demo page, same problem on low resolution screens exist there.

Thank you and sorry for bad english.

**Comment by mbrn** [comment]
This is done with 1.23.4.

**Comment by lasren** [comment]
This is not the result I was willing to be, but thanks for that also.

The bad thing, now we have 2 horizontall scroll bars on one table.
Can you put pagination (or in other words table footer) in first scroll bar?
https://i.imgur.com/BQnqDpb.png

**Comment by mbrn** [comment]
I will try to do better solution for this issue.

**Comment by lasren** [comment]
I have updated my comment before,  for more information.

**Comment by mbrn** [comment]
This is done with 1.27.0
