### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Andrey-Mayanov** [mbrn/material-table#2650]
Hello! Can you tell me if someone has a memory leak on versions higher than 1.67? I updated to 1.69 and noticed that if a page with a table is rendered several times, it will be a memory leak. I started downgrading versions and realized that it wasn't happening, like, at 1.67.

**Comment by hburbano** [comment]
Yup, it might be related to this https://github.com/mbrn/material-table/issues/2643#issuecomment-734046369

**Comment by Andrey-Mayanov** [comment]
@hburbano , thank you! I will keep an eye on this bug.

**Comment by LuisPinaSoares** [comment]
Hi,

Yes if i am not wrong for me starts happening after 1.66.0, just tried the latest version and the bug is still there.
And happens pretty fast. 2 clicks is enough

**Comment by MathieuCh** [comment]
Hey,

Same here. Huge leak which after few clicks freeze the browser 

Passing directly the array to the prop 'columns' seems to be alright, but otherwise with dynamic columns there is a leak

**Comment by Samurus** [comment]
@MathieuCh thank you very very you solved my problem which I wasted like 30 hours in 2 weeks. See https://github.com/mbrn/material-table/issues/2643
As mentioned by @hburbano  the DataManager still needs bugfix: https://github.com/mbrn/material-table/blob/b7474ca0f5497f04ff3a3d50e709d86de7c639b0/src/utils/data-manager.js#L62

**Comment by orange-beans** [comment]
> Hello! Can you tell me if someone has a memory leak on versions higher than 1.67? I updated to 1.69 and noticed that if a page with a table is rendered several times, it will be a memory leak. I started downgrading versions and realized that it wasn't happening, like, at 1.67.

Same here, spent whole day to figure out that it was caused by material-table. Have to roll back to 1.57.

**Comment by dfejza** [comment]
Saw memory leaks (switching between routes with material-table and non table, after 10 times or so saw tab memory usages at 1gb and unresponsive) with latest build 1.69.1. 
I can't replicated with 1.67

**Comment by royjosefsson** [comment]
@1.9.2 gave us memory leaks. Downgrading it to @1.57.2 solved the issue.

**Comment by andremantaswow** [comment]
can confirm memory leak happens with dynamic columns (even if you dont change them but use React.useState like in their [editable examples](https://material-table.com/#/docs/features/editable))

just by not using the `useState` (assuming you dont need it), the issue seems to not happen

**Comment by uooopss** [comment]
i'm not use dynamic columns, but i have a memory leak. 
addition useMemo fixed this bug.
```
cosnt columns = useMemo(() => [{...column object}], [])
<MaterialTable columns={columns} data={[...some rows]} />
```

**Comment by jagadeeshkoka** [comment]
I dont know how accurate is my solution is, I have faced the same issue, in my usecase I have static columns array, which is outside of functional component, this caused to freez every 3 clicks or renders.
So I have  placed my columns array inside functional component, which now seems to be working. 

`export default LoginHistory(props) {
const coloums = [ { //data }];
<MaterialTable columsn={columns} //remaining props />
}`

**Comment by dungmidside** [comment]
> I dont know how accurate is my solution is, I have faced the same issue, in my usecase I have static columns array, which is outside of functional component, this caused to freez every 3 clicks or renders.
> So I have placed my columns array inside functional component, which now seems to be working.
> 
> `export default LoginHistory(props) { const coloums = [ { //data }]; <MaterialTable columsn={columns} //remaining props /> }`

Your solution work for me too. That's weird, I still don't know why this happen : (

**Comment by antoine-briand** [comment]
Can relate this issue too. 

I moved my columns array into a separate file which I imported into my component. After this, my page started to freeze after 4 or 5 re-renders (I use tab panels navigation). 

Moving the columns array back into the component where the table is defined fixed it.

I'm really curious about the reason behind this 👀

**Comment by AlanQuadros** [comment]
I force downgrade to 1.66.0 version. No more memory leaks

**Comment by sinclas** [comment]
Hi,

Same here.  1.69 and after 3 refreshes, I have a non-responsive page.  My columns are generated by assigning them via the state object since I support turning the column's hidden attribute true/false through the UI.   I will into what options for downgrading are but the DnD column grouping is what got me interested in using this in the first place.   Does anyone know how this can happen?  my guess would be event binding.  Will take a look around....  Any help on this would be great!

**Comment by Samurus** [comment]
Since the owner was afk for lile 6 months there has been etablished this community fork which might fix this issue:
I migrated yesterday within seconds and luckily no broken changes which you could read about in the docs.
Here is the guide:
https://material-table-core.com/docs

**Comment by LuisPinaSoares** [comment]
I have been using that fork and recommend! Thanks to the crew carrying on with the project.
@oze4 should establish a patreon for donation I think...

**Comment by nmimagenysonido** [comment]
> I force downgrade to 1.66.0 version. No more memory leaks

It works for me (and solve many hours of inspecting)

**Comment by LucienChu** [comment]
I came into this issue twice, months ago I need a quick implementation, by the time I found the table got frozen after 2+ renders, I spent hours to inspect my react code, then I gave up.

Now I encountered the same issue, and thanks guys, I know now it was not my fault.

**Comment by uganof** [comment]
forcing to version 1.68.0 works without problems.
The anomaly has been found since version 1.69.0
