### ISSUE TITLE
columns hidden:true hiddenByColumnsButton:true cause type error

### ISSUE THREAD

**Issue by nivranaitsirhc** [mbrn/material-table#2654]
**Describe the bug**
Setting columns hidden and hiddenByColumnsButton to "true" cause an  "type undefined error" when unhiding the column.

Thrown Error:
`Uncaught TypeError: Cannot read property 'match' of undefined`

Where the Error was thrown:
```
var reducePercentsInCalc = function reducePercentsInCalc(calc, fullValue) {
  var captureGroups = calc.match(/(\d*)%/);

  if (captureGroups && captureGroups.length > 1) {
    var percentage = captureGroups[1];
    return calc.replace(/\d*%/, "".concat(fullValue * (percentage / 100), "px"));
  }

  return calc.replace(/\d*%/, "".concat(fullValue, "px"));
};
```
 

**To Reproduce**

1. Create a column
```
columns = {
 { Title: 'some_title',field: 'some_field', hidden:true,hiddenByColumnsButton:true}
}
```
2. Enable buttons to the table
`options = {columnsButton:true}`
3. After rendering the component select the columns button to show the hidden column.

**Expected behavior**
It will show the hidden column

**Desktop (please complete the following information):**

- OS: Windows 10 Pro, 20H2 
- Browser: Chromium Edge, 87.0.664.47 (Official build) (64-bit)
- Version  1.69.2

**Additional context**
What am I am trying to achieve is hide un necessary columns after render to de-clutter the table.
From searching I found some PR but is still pending. Is there any alternative workaround? Please help.

**Comment by nivranaitsirhc** [comment]
Found a solution:

if  `calc` is not truthy the function will return fullValue.

I will be creating a PR later.

**Comment by EM15** [comment]
Same issue here, waiting for the PR from @nivranaitsirhc . Do you know exactly when this bug was introduced? Which version were you pointing at?

**Comment by nivranaitsirhc** [comment]
This might not be fixed instantly.

**Comment by oze4** [comment]
I am not going to close this issue here, but we have implemented this [fix](https://github.com/material-table-core/core/issues/20) over at [`@material-table`](https://github.com/material-table-core/core) (we are a fork of `material-table` and we plan on pushing the changes up to `material-table` when we can (only mbrn can update `material-table`).

**Comment by x-fusion** [comment]
@oze4 I run into same issue as OP, I would like to ask is there any way I could fix it on my own? Because it seems material-table repository haven't been updated to resolve this issue and I really need this functionality

**Comment by oze4** [comment]
Check out the repo https://github.com/material-table-core/core it is a community driven fork of this repo created in order to keep this repo alive. A fix for this issue has been applied in said repo.

**Comment by Shiivani** [comment]
Is this issue fixed I am also getting same kind of error while trying to show the hidden column var captureGroups = calc.match(/(\d*)%/); at this line

**Comment by sinclas** [comment]
same issue here with hidden toggle causing: **Uncaught TypeError: Cannot read property 'match' of undefined**
 "material-table": "^1.69.3",
Is there a way to fix this prior to the next update?
