### ISSUE TITLE
Change color of check icons

### ISSUE THREAD

**Issue by Takesuma** [mbrn/material-table#2659]
# Change color of check icons

**Excepted**
I excepted icons in boolean type to change color

**To Reproduce**
TableIcons.js
``` js
...
Check: forwardRef((props, ref) => (
    <Check style={{ color: "#008000" }} {...props} ref={ref} />
  )),
...
```

index.js
``` js
...
    <MaterialTable
        data={data}
        columns={columns}
        title="Starter Template"
        icons={tableIcons}
      />
...
```

![image](https://user-images.githubusercontent.com/29368956/100629783-fca0bb80-3329-11eb-82c2-46fb8e769b0b.png)
Here the icons before the table are colored but not in the table 

**StackBlitz**
https://stackblitz.com/edit/material-table-starter-template-c2mqgj?file=index.js

**Comment by Samurus** [comment]
Try this: 
const columns = [
  { title: "Id", field: "id" },
  { title: "Word", field: "word" },
  { title: "Boolean", field: "boolean", type: "boolean",  
 cellStyle: (e, rowData) => {
        if (!rowData.boolean) {
          return { color: "red" };
        } else return {color: "green"}
      },
  }
];
