### ISSUE TITLE
Keep expanded groups, expanded, when searching

### ISSUE THREAD

**Issue by timrchavez** [mbrn/material-table#266]
**Is your feature request related to a problem? Please describe.**
Collapsing expanded groups on search is an awkward experience.

**Describe the solution you'd like**
When searching a table with groups, groups automatically collapse. It would be a better experience if groups that have search results in them are already expanded, to keep them expanded.

**Comment by mbrn** [comment]
Hi @timrchavez ,

Exactly. I will add this feature.

**Comment by mbrn** [comment]
This is done with 1.23.2
