### ISSUE TITLE
Experience issues with customSort

### ISSUE THREAD

**Issue by LuisPinaSoares** [mbrn/material-table#2666]
I am using version 1.66.0

My table works no problem and native sorting works fine by clicking the headers of all columns.
I a trying to add custom sorting just because if you use accented words it helps to use `array.localeCompare()` as a sort function.

But if i add the following to my column:
```javascript
    {
      title: 'Nome',
      field: 'mp_nome',
      customSort: (a, b) => a.localeCompare(b),
      render: ({ mp_nome }) => emptyCellFiller(mp_nome),
    },
```

When i click the column header nothing happens, it disregards onClick event and does no sorting.

**Is someone experiencing similar behaviour?**

I have pagination activated in my tables

**Comment by Samurus** [comment]
Can you provide some example in a sandbox? I just tryed out with some random numbers from 1-100 which is working. Using version 1.67.1
 {
    title: "quantity",
    field: "quantity",
    editable: "never",
    customSort: (rowA, rowB) => rowA.quantity< rowB.quantity,
    render: (rowData) => {return (<div>{rowData.quantity}</div>)},
   },

**Comment by mvelebit** [comment]
I'm having the same issue on v1.69.0; The customSort function doesn't get triggered at all.
