### ISSUE TITLE
"No records to display" even when there is data when using version 1.19

### ISSUE THREAD

**Issue by yungwiche** [mbrn/material-table#267]
**Describe the bug**
The table shows "No records to display" even when there's data. It seems like the upgrade to 1.19 might have caused this problem. The bug's behavior is the same as another closed issue, which can be found here: [https://github.com/mbrn/material-table/issues/259](url). When I downgraded to version 1.18, the table works as expected.

On closer inspection using Chrome's React Developer Tools, unlike version 1.18, in version 1.19, the table has a new state called "originalData", which actually does contain the actual data that was provided, how ever the "data" state contains nothing (contrary to version 1.18, in which the "data" state had the provided data).

**To Reproduce**
1. Navigate to [https://stackblitz.com/edit/react-rpbcta](url)
2. Upgrade material-table to version 1.19
3. See error

**Comment by mariolazzari** [comment]
I have the same problem after updating to 1.19. 
Previous version is fine with same api calls.

**Comment by xadie** [comment]
same issue here. After mounting it doesn't refresh when data props change

**Comment by jakeleventhal** [comment]
I've created a sandbox that shows how dynamic updates break this.
https://codesandbox.io/s/6zrvx6opww

Installed on the sandbox is v1.18.0 - this works

When upgrading to 1.19.x, it no longer works

**Comment by mbrn** [comment]
I resolved problem. You can upgrade to 1.19.2
