### ISSUE TITLE
Major Issue in cellEditable while editing table cell, please check!!!!

### ISSUE THREAD

**Issue by theWanderer78** [mbrn/material-table#2672]
i am using material table in my code.I am using cell editable. But when i edit my table cell, its style become wierd. Please see the image. How to fix this. 

Seems like its does not work well with too many rows.

can we change the styling...?? like remove cross button

and change check size?

Codesandbox code: https://codesandbox.io/s/material-demo-forked-h1f8d?file=/demo.js:1142-1513

<img width="876" alt="Screen Shot 2020-12-04 at 12 00 24 PM" src="https://user-images.githubusercontent.com/33008095/101142099-2d8b3400-363b-11eb-81ff-829a497a77b2.png">

**Comment by Samurus** [comment]
Easiest fix would be this:
{     title: "Surname",field: "surname",**cellStyle: { minWidth: 150 }**,initialEditValue: "initial edit value"},

**Comment by PriyankDeep** [comment]
@Samurus Is there anyway to remove those check and cross icon?? or change its size

**Comment by Samurus** [comment]
please read documentation https://material-table.com/#/docs/features/component-overriding
you can override EditField like this:
  components={{
        EditField: (props) => (
          <div style={{ backgroundColor: "#whatever" }}>
            maybe use input field here
          </div>
        )
      }}
Alternatively please read documentation: https://material-table.com/#/docs/features/editable
This examples shows how you can customize editable for one row. Accept and decline buttons are not needed in this case.

**Comment by thefat32** [comment]
@PriyankDeep 
@Samurus 

Check ad Cross icons are implemented in EditCell component. This component is not listed in

https://material-table.com/#/docs/features/component-overriding

but it can be overrided like any others:

```ts
<MaterialTable<InvestmentEquipmentTableItem>
          components={{
            EditCell(props) {
              return 'EDIT-CELL-OVERRIDE';
            }
          }
         {...otherProps}
</
```

You can use https://github.com/mbrn/material-table/blob/master/src/components/m-table-edit-cell.js as implementation example. This way you have full control over cell edition component

**Comment by thefat32** [comment]
EditCell component receives columnDef with all details about the column including the type so you can render properly (EditField component is the one that renders depending on type (selector, chexkbox, text, etc) Do you have different cell types in the same column? Please if you can share with my your column's definition code.

**Comment by PriyankDeep** [comment]
@Samurus @thefat32 @kristinhorton @mbrn When using cellEdiatable, we have to first click on the cell, then edit it, click on check or cross button. But is there any way in which we can just click on tab button and make an edit. ??

**Comment by thefat32** [comment]
@PriyankDeep take a look at [EditCell](https://github.com/mbrn/material-table/blob/master/src/components/m-table-edit-cell.js) and [EditField](https://github.com/mbrn/material-table/blob/master/src/components/m-table-edit-field.js)

Explaining short
- EditCell receives `onCellEditFinished` callback
- EditField has onChange property

You can reimplement EditCell to call onCellEditFinished when you want. I don't think you can make it work as a normal input as new value needs to be informed to material-table using the callback onCellEditFinished, this call ends edit process. But you can implement finish edition with Enter key and cancel edition with Esc key instead of check and cross icons.

**Comment by PriyankDeep** [comment]
@thefat32 can you show in codesandbox??
