### ISSUE TITLE
pageSize in the options does not change the number of rows per page

### ISSUE THREAD

**Issue by mmind-hub** [mbrn/material-table#268]
Hi,

Should i give more options to the MaterialTable so it can show more than five rows ?
I tried pageSize without success.

Thank you

 <MaterialTable
            options={{
              emptyRowsWhenPaging: false,
              pageSize: 10
            }} />

**Comment by mbrn** [comment]
It seems a new bug after v1.19.0. I will resolve this for next release.

**Comment by mbrn** [comment]
I fixed this with 1.19.1

**Comment by mmind-hub** [comment]
Thank you ! 
Working perfectly.
