### ISSUE TITLE
Support React 17

### ISSUE THREAD

**Issue by charlesc32** [mbrn/material-table#2683]
Any plans for upgrading to support React 17?

**Comment by johnthagen** [comment]
This active fork has a peer dependency of `react@17.0.1`: https://github.com/material-table-core/core

**Comment by shubhamappstec** [comment]
Any Update???

**Comment by johnthagen** [comment]
@shubhamappstec I would suggest you try https://github.com/material-table-core/core, which has been much more actively maintained. They have fixed a number of outstanding issues in `material-table`.

**Comment by PathToLife** [comment]
I still can't install on react 17

command
`npm i material-table`

package.json
`"react": "^17.0.1"`

result
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@"^16.8.0 || ^17.0.0" from @material-ui/core@4.11.4
```

Any plans on just updating the package.json dependency? Chances are it'll be compatible without any changes

**Comment by PathToLife** [comment]
https://github.com/mbrn/material-table/pull/2797
