### ISSUE TITLE
Generic service for remote data fetching

### ISSUE THREAD

**Issue by mchmielo** [mbrn/material-table#2684]
Hi, at the beginning, thanks for great work with this project!

I am trying to obtain remote data with service I wrote:
```
export interface IBaseServiceProps {
    baseRoute: string,
    authData: Auth,
}

export interface IDbService<T extends object> {
    getPaginated: (query: Query<T>) => Promise<QueryResult<T>>,
}

export class BaseDbService<T extends object> implements IDbService<T> {

    state: {
        baseRoute: string;
        authData: Auth;
    };

    constructor(props: IBaseServiceProps) {
        this.state = {
            baseRoute: props.baseRoute,
            authData: props.authData
        }
    }
   async getPaginated(query: Query<T>): Promise<QueryResult<T>> {
      // Axios call
   }
}
```

And then, when using this service on data prop:

```
export function Page() {
    const { authData } = useAuthContext();
    let service = new BaseDbService<Product>({baseRoute: "products", authData: authData});
    return (
        <>
              <MaterialTable
                  data={service.getPaginated} // <-------------- throws Cannot read property 'baseRoute' of undefined 
```
Every time I try to use the service to either get or update data, I get exception 'Cannot read property 'baseRoute' of undefined. When I was using this "manually" it worked well. When I moved all the axios.get() logic to the data prop it works ok.
I am pretty new to react, so please let me know if it is a problem with material-table, or something else.
Thanks!

**Comment by Gillibald** [comment]
`data={(query) => service.getPaginated(query)}` should work

**Comment by mchmielo** [comment]
Yes, it does, thanks!
