### ISSUE TITLE
Catastrophic freeze on bulkUpdate in v1.69.2

### ISSUE THREAD

**Issue by cdruck** [mbrn/material-table#2685]
In version 1.69.2, which I briefly tried to see if bulkUpdate was fixed, I still have a catastrophic failure when repeatedly updating/validating fields.

Here's a sandbox
https://codesandbox.io/s/bulk-edit-fail-material-table001-forked-mpr06?file=/src/App.js

The bug occurs when repeatedly clicking on editAll - saveAll. At each iteration the waiting time is longer, until it eventually completely freezes and timeouts.

Upon investigation it looks like it is looping in styling: 
![image](https://user-images.githubusercontent.com/56411423/101889942-4d24de00-3ba0-11eb-886e-0ffa084a4a89.png)

**Comment by peacechen** [comment]
Unfortunately mbrn is inactive and not merging PR's. Use the official community fork [@material-table/core ](https://github.com/material-table-core/core)instead.
