### ISSUE TITLE
TypeError: "tableData" is read-only 

### ISSUE THREAD

**Issue by JoshSum** [mbrn/material-table#269]
hey i got this error 
TypeError: "tableData" is read-only 
after link to another page and return to the table page, 
any solution?
![image](https://user-images.githubusercontent.com/36181034/53669148-b035d100-3ca8-11e9-93fa-67fd4f68c1ef.png)

**Comment by mbrn** [comment]
Hi @JoshSum ,

I will take a look t this.

**Comment by mbrn** [comment]
I moved data manipulations to in another class. so this could be resolved. I will close issue. If occur again you can reopen this. 

Try v1.19.2
