### ISSUE TITLE
Option tableLayout: "fixed" is not working properly in version 1.69.2

### ISSUE THREAD

**Issue by nelsonx73** [mbrn/material-table#2698]
# Guidelines

- #### Please include a demo of the issue/behavior/question you have
import React, { useEffect, useState } from "react";
// Material table
import MaterialTable from "material-table";
const columns = [
  {
    width: 250,
    title: "Country name",
    field: "country",
  },
  {
    width: 250,
    title: "Country name",
    field: "country",
  },
  {
    width: 250,
    title: "Country name",
    field: "country",
  },
  {
    width: 250,
    title: "Country name",
    field: "country",
  },
  {
    width: 250,
    title: "Country name",
    field: "country",
  },
  {
    width: 250,
    title: "Country name",
    field: "country",
  },
  {
    width: 250,
    title: "Country name",
    field: "country",
  },
  {
    width: 250,
    title: "Country name",
    field: "country",
  },
  {
    width: 250,
    title: "Country name",
    field: "country",
  },
  {
    width: 250,
    title: "Country name",
    field: "country",
  },
  {
    width: 250,
    title: "Country name",
    field: "country",
  },
];

function Cases() {
  const [data, setData] = useState([
    {
      country: "Dominican Republic",
      population: "100000",
    },
  ]);

  return (
    <div className="row d-flex justify-content-center">
      <div className="col-md-10 ">
        <MaterialTable
          data={data}
          columns={columns}
          options={{
            tableLayout: "fixed",
          }}
        />
      </div>
    </div>
  );
}

export default Cases;

- #### Please try to be as detailed as possible

The option tableLayout: "fixed" is not working as expected in material-table version 1.69.2.  But, if I use version1.69.1 it works fine.

Please take a look at it.  Your library is awesome.

Thanks.

**Comment by optumjpete** [comment]
I am experiencing this issue as well. If I revert to 1.69.1, this is fixed.

Fixed column widths are ignored completely.
