### ISSUE TITLE
Add summary row feature

### ISSUE THREAD

**Issue by mbrn** [mbrn/material-table#27]
Add summary row feature

**Comment by gulcann** [comment]
Hello, I started working on this.
Good work.

**Comment by jakeleventhal** [comment]
What would this look like/what would it be?

**Comment by robinzimmer1989** [comment]
Are there any updates on this?

**Comment by mbrn** [comment]
Hi @robinzimmer1989 ,

I could not look at this reason of other issues and projects. But i will add this feature on next month.

**Comment by thebriando** [comment]
Any progress?

**Comment by adamsaper** [comment]
Would love to know the status of this feature as well. 
Thanks

**Comment by dsubram1** [comment]
Any update on this status? At least when will this be available?

**Comment by json2d** [comment]
hey @mbrn I'd like to help out on this feature if possible.

I've tried stacking 2 `MaterialTable` components, one for the data and one for the summary, but that has some problems mainly in getting the column spacing and alignment to match with the data table above.

**Comment by eddiemonge** [comment]
Something like this?: 

![image](https://user-images.githubusercontent.com/127535/64753934-e2d34880-d4d9-11e9-9d20-1685ce773e76.png)


Some notes to consider:
- Grouped rows and how to handle values in those: https://github.com/mbrn/material-table/issues/277. Only add the root row?
- Rows on pages that are not on the current page.  Disable pagination for this type of table?
- What does the API look like? Is the row customizable?

**Comment by Hopp3r** [comment]
Any update on this feature?

**Comment by sanojsilva** [comment]
Hey any Update on this???

**Comment by Hopp3r** [comment]
Sadly no. @mbrn is "working on material-table pull requests" and doesn't want to look at any of the issues.

**Comment by dhany007** [comment]
sir, any update on this ?, ty

**Comment by alfanjuni** [comment]
any update for this?

**Comment by OrbitalJeffL** [comment]
any update on this?

**Comment by gabrielbaldeon** [comment]
any update on this?

**Comment by jakeleventhal** [comment]
not stale

**Comment by OrbitalJeffL** [comment]
Any update?

**Comment by mahmoudfathy2020** [comment]
is there any updates on this ?

**Comment by kdoda** [comment]
update?

**Comment by xescuder** [comment]
Not yet a solution?

**Comment by TheEcho** [comment]
Any update ?

**Comment by ErhanArda** [comment]
Is there anybody out there?

**Comment by LYSAYHOI** [comment]
Any update?

**Comment by Nikhilbk1705** [comment]
any updates?

**Comment by surajdhungana46** [comment]
any update

**Comment by piotrpodyma10** [comment]
c'mon how long can you work on it

**Comment by HyeongjinJoo** [comment]
any update on this?

**Comment by ErhanArda** [comment]
https://mui.com/x/react-data-grid/ may solve your problem
