### ISSUE TITLE
editComponent on  cellEditable 

### ISSUE THREAD

**Issue by thefat32** [mbrn/material-table#2700]
It Would be great to override EditField when using  cell level edition (cellEditable) like it can be done when using row level edition. The only way now is to override EditField in the whole table.

@mbrn if you are ok with this I can make a PR! Please tell

**Comment by orinoco** [comment]
Would love to see this feature, was totally expecting it to be there based on the demos I had seen, before discovering it only works with full row edits.

**Comment by orinoco** [comment]
PS. You can workaround the issue by using an editor in the render prop of a column, and making sure you give it your state getter and setter.

**Comment by chiaberry** [comment]
I'm looking for a way to override EditField when editing a cell, I hope this feature gets added to material table.
