### ISSUE TITLE
Editable with custom button

### ISSUE THREAD

**Issue by AbdurRehman26** [mbrn/material-table#2705]
I have override the action buttons but I need to trigger bulk edit. Is there any way to add a custom button with bulk Edit functionality ?
 
![image](https://user-images.githubusercontent.com/21219332/102723696-9527cb80-432b-11eb-8544-9379ce9d9705.png)

**Comment by bgbbmm** [comment]
Hello,
Maybe you can get this to work by doing a combination of some things which are available on the website and what I can see in the source code. 

First, look at the [duplicate action example](https://material-table.com/#/docs/features/actions). The functionality provides a button to duplicate the current row and trigger the changeRowEditing function. It utilizes the tableRef to access the dataManager for material-table. 

Second, it appears that within data-manager.js there is a function to set that bulk edit feature called [changeBulkEditOpen](https://github.com/mbrn/material-table/blob/master/src/utils/data-manager.js). Judging from the duplicate action example, you would need to trigger a state update after setting this value in order for the bulk edit to appear.

**Comment by bgbbmm** [comment]
Also is it possible for you to post your code for your custom buttons/overridden action buttons? That's something I am interested in using.

**Comment by PATTANPARVIN** [comment]
I'm also looking for same bulk edit with custom button, please anyone can help.


Thanks in advance
