### ISSUE TITLE
How to have a filter on columns?

### ISSUE THREAD

**Issue by ashutoshPrithvi** [mbrn/material-table#2710]
How can get an option to filter the columns. Like if there are 5 columns [S.No, Name, Age, Number, Course] , how can we hide the S.No and then make it appear once again with the help of some action like click of a button or using checkbox?

**Comment by oze4** [comment]
Hi! Can you please fork [this SandBox](https://codesandbox.io/embed/material-table-starter-template-xnfpo?codemirror=1) and create a reproducible example?
