### ISSUE TITLE
Pagination is not work for material datatable

### ISSUE THREAD

**Issue by SheikSena** [mbrn/material-table#2713]
# Guidelines

**Describe the bug**
Next page link is not working. 
![image](https://user-images.githubusercontent.com/40268724/103228930-eea97f00-4957-11eb-8e60-dc2b8f0a0ea9.png)

**To Reproduce**
Steps to reproduce the behaviour:

**Console Screenshots**
![image](https://user-images.githubusercontent.com/40268724/103228788-9f634e80-4957-11eb-9ea9-c80ebdfdd0b1.png)

![image](https://user-images.githubusercontent.com/40268724/103228845-befa7700-4957-11eb-9457-2201efabc9f3.png)

**Desktop (please complete the following information):**
- OS: Windows
- Browser [Chrome]

**Comment by mindaugasnakrosis** [comment]
It looks like you pass onPageChange that is not a function. What do you exactly pass as a parameter there?
