### ISSUE TITLE
defaulfFilter cause error when column set lookup

### ISSUE THREAD

**Issue by coolmaxter** [mbrn/material-table#2718]
When I combine the **defaultFilter** and **lookup** function, material-table failed to render as the selected is not a array.

stack print
```
        renderValue
        C:/workspace/nodejs/***/node_modules/material-table/dist/components/m-table-filter-row.js:171
        168 |   id: "select-multiple-checkbox" + columnDef.tableData.id
        169 | }),
        170 | renderValue: function renderValue(selecteds) {
        > 171 |   return selecteds.map(function (selected) {
        | ^  172 |     return columnDef.lookup[selected];
        173 |   }).join(", ");
        174 | },
        View compiled
        SelectInput
        C:/workspace/nodejs/***/node_modules/@material-ui/core/esm/Select/SelectInput.js:270
        267 |   value: value
        268 | }) || displayEmpty) {
        269 |   if (renderValue) {
        > 270 |     display = renderValue(value);
        | ^  271 |   } else {
        272 |     computeDisplay = true;
        273 |   }
        View compiled
```

**To Reproduce**
Column write like this:
{
      title: 'Status',
      display_priority: 1,
      field: 'nodeStatus',
      filtering: true,
      **defaultFilter: 'busy',**
      defaultSort: 'asc',
      hidden: false,
      **lookup: { 'idle': 'Stand by', 'busy': 'Running', 'offline':'Offline', 'disabled':'Disabled', 'unknown': 'Unknown'}**
}

**Desktop (please complete the following information):**

- OS: WIN10
- Browser Chrome/ Edge
- Version 87

**Additional context**
MaterialVersion: 1.69.2

**Comment by hbermani** [comment]
This is not a bug, you just need to supply a string array for the default filter like this

defaultFilter: ['busy', 'offline']

**Comment by amaxwell-rgare** [comment]
> This is not a bug, you just need to supply a string array for the default filter like this
> 
> defaultFilter: ['busy', 'offline']

Someone should add an example of using this filter to the documentation. This took way too long for me to find.
