### ISSUE TITLE
How to change Toolbar style and title text when row selected?

### ISSUE THREAD

**Issue by flaviodelgrosso** [mbrn/material-table#2719]
Hi all! I'm trying to use for the first time this awesome material-table and I'm searching a way to style the toolbar and change the default title (row(s) selected), the color and the border radius when one or more rows are selected.

<img width="808" alt="Schermata 2021-01-02 alle 14 12 56" src="https://user-images.githubusercontent.com/58950085/103458087-093b7980-4d05-11eb-90b2-e60af7373958.png">

Thanks in advance for any help

**Comment by mindaugasnakrosis** [comment]
You can override the toolbar: https://material-table.com/#/docs/features/component-overriding

**Comment by m282726** [comment]
Hi, when overriding the toolbar style, how do we affect the style of the export icon and search clear icon?  Using toolbar overriding recommended above, I'm able to get the background and title text styled, and using the searchFieldStyle option the search icon and text are handled.  But I haven't been able to figure out how to style the clear icon in the search component and the export button.  

Appreciate any help with this.  Thanks!

**Comment by dmarquez83** [comment]
I need to change this text when selecting a row for a custom text and in the options I do not get one that allows it

**Comment by TheGameNewWorldOrder** [comment]
@dmarquez83 You can use localization option to change the label in toolbar
