### ISSUE TITLE
 Right click menu

### ISSUE THREAD

**Issue by heylenz** [mbrn/material-table#272]
I think it would be a good idea to add a right-click menu.

**Comment by mbrn** [comment]
Hi @heylenz ,

For what? Cell clicks

**Comment by heylenz** [comment]
When I select a single row or multiple rows, I can right-click on the menu to edit and perform some operations, like excel

**Comment by mbrn** [comment]
I will consider this. It could be useful.

**Comment by heylenz** [comment]
hi @mbrn ,I found some references, it would be very useful if they could be combined.
https://github.com/fkhadra/react-contexify
https://github.com/valerybugakov/react-selectable-fast

**Comment by StwartMassmann** [comment]
Hi @mbrn , are you planning to add this functionality?  This feature is very interesting.

**Comment by conerye** [comment]
hi @mbrn I am looking for this feature as well. select one or more rows and right-click to bring up a context menu...

**Comment by alexander-r-jaimy** [comment]
any chance right click on row will be implemented?

**Comment by nextglabs** [comment]
+1
