### ISSUE TITLE
How can I get the *current* data in the table?

### ISSUE THREAD

**Issue by TamjidTayeb** [mbrn/material-table#2721]
How can I get the current data in the material table? I want my user to be able to sort the table and after that I want to download the data in its sorted state. At the moment I am just downloading the data that I pass to the mtable component but is there a way I can access the data once it has been sorted ?

**Comment by mindaugasnakrosis** [comment]
Are you using remote data? Just pass `exportButton` as an `option` to table component. Sort beforehand and press "Export". It should work.
