### ISSUE TITLE
Crash when add new more than 4 rows

### ISSUE THREAD

**Issue by nvlong198** [mbrn/material-table#2722]
Video error: 
https://youtu.be/tn_xHCNicTk

https://user-images.githubusercontent.com/23328191/103619735-d7c0e900-4f64-11eb-8425-a526e9021a45.mp4

Playground: https://codesandbox.io/s/material-table-playground-forked-telyi?file=/src/CustomEditComponent.js 

![image](https://user-images.githubusercontent.com/23328191/103606079-29a74600-4f48-11eb-84b9-3febbef76c77.png)

**Desktop:**
- OS: Ubuntu 20.04, Windows 10
- Browser: chrome
- Version: 1.69.2

Thanks for your consideration.

**Comment by mindaugasnakrosis** [comment]
I can not seem to reproduce the issue in your sandbox. If you can reproduce it, can you log what error it produces, because it does not reach the line `resolve();`

**Comment by nvlong198** [comment]
@mindaugasnakrosis  onRowAdd slowing down when adding new rows.
did you see my video? 
https://youtu.be/tn_xHCNicTk

**Comment by mtrucc** [comment]
I also encountered this problem
