### ISSUE TITLE
Memory leak [reproducible codesandbox]

### ISSUE THREAD

**Issue by josmithua** [mbrn/material-table#2727]
Codesandbox: https://codesandbox.io/s/compassionate-banzai-vgucy

**Description of bug**
The issues I am seeing are:

1. Data being modified by the MaterialTable component
2. Memory leak when data is refreshed and table is re-rendered

**To Reproduce**
1. Have dev tools open to memory tab
2. Unfocus/focus the app window (can be done by focusing dev tools, then app window again). React-Query will refetch the data, which will cause 2 rerenders (setting isFetching to true and back to false again after the fetch)
3. Repeat this until you start to notice the tab lag and the memory increase (about 12 times for me, gets really bad at 15)
4. Open a new tab with the same codesandbox, this time comment out the MaterialTable and uncomment the custom table. You will notice there is no memory problem, and the React effect will not be triggered

**NOTE**: The memory problem only occurs when there are multiple columns in the table... Try with one column and you shouldn't notice a problem, although the React effect will still be triggered...

**Expected behavior**
1. The data passed into the MaterialTable component should not be changed
2. There should not be a memory leak.

**Desktop (please complete the following information):**

- OS: macOS
- Browser Brave
- Version Version 1.18.75 Chromium: 87.0.4280.101 (Official Build) (x86_64)

**Comment by just-exe** [comment]
@josmithua I ran into this issue as well. I was able to replicate the problem and the fix with only using one column. 

I fixed the issue by downgrading to version 1.57.2. Other versions may work, this was just the first I tried.

**Comment by josmithua** [comment]
Thanks @just-exe for your suggestion, I can confirm that v1.57.2 does not exhibit the same memory leak behavior, although the React effect (in the sandbox) still triggers when it shouldn't, so I guess that is a separate issue.

**Comment by josmithua** [comment]
On further investigation, v1.69.0 introduces the memory leak problem. So I will be downgrading my production app to v1.68.1 until this gets resolved.

**Comment by zhushenhang** [comment]
same issue.
thank you . I am also going to downgrade to v1.68.1

**Comment by mindaugasnakrosis** [comment]
Same issue, downgraded

**Comment by peacechen** [comment]
Unfortunately mbrn is inactive and not merging PR's. Use the official community fork [@material-table/core ](https://github.com/material-table-core/core)instead.

**Comment by josmithua** [comment]
@peacechen thanks for the heads up, I'm ashamed to say I didn't check if this was still being maintained. I'll be trying the fork. Thanks for your work on this!

I will leave the issue open, as it still stands.

**Comment by yejiyang** [comment]
Found the same issue, and downgrading to v1.68.1 solved the issue. @josmithua  @just-exe  Thanks for report the issue and provide the solution.

**Comment by oze4** [comment]
I created an issue [over at `@material-table/core`](https://github.com/material-table-core/core) for this.

This issue has priority and I will be focusing on it shortly.

**Comment by josmithua** [comment]
Hi @oze4, I switched over to @material-table/core today and I’m not experiencing the same memory leak issue, so it might have fixed already

**Comment by oze4** [comment]
Oh sweet. Glad that fixed it!

**Comment by zhushenhang** [comment]
Hi @josmithua ,Are the APIs of these two libraries the same? Which version of @ material table / core library do you use?

**Comment by oze4** [comment]
Hello @zhushenhang! 

You can read more about [@material-table/core here](https://github.com/material-table-core/core/blob/master/README.md#about) TLDR; we are a community driven fork of this repo, trying to keep it alive (so we can push changes to this repo) as mbrn appears tonhave become rather busy over the past months. 
You may also find a list of "breaking changes" between @material-table/core and this repo [here](https://material-table-core.com/docs/getting-started/breakingchanges)

**Comment by zhushenhang** [comment]
@oze4 thanks bro

**Comment by josmithua** [comment]
> Hi @josmithua ,Are the APIs of these two libraries the same? Which version of @ material table / core library do you use?

Hi! I’m using the latest version.

**Comment by artem-tarasenko** [comment]
It's been a pain in the ass for a few days for me. I'm quite new to dev stuff but, anyway, there is some kind of an issue with calculating columns width in the component or something and the problem is that it's being done recursively which generates enormous strings after several iterations. 

That's nice that someone created a community fork to keep things running, gonna check it.

**Comment by sinclas** [comment]
is this fork viable for a beta release of a production app?

**Comment by peacechen** [comment]
I've been using [material-table-core](https://github.com/material-table-core/core/) in production for 6+ months. It is far stabler and continues to add features.
