### ISSUE TITLE
Warning: Each child in a list should have a unique "key" prop.  Check the render method of `MTableCell

### ISSUE THREAD

**Issue by EltonGohJH** [mbrn/material-table#2729]
# Guidelines

Hi I am new to react and I have been getting this error in my console. Any tips on how to solve it.

![image](https://user-images.githubusercontent.com/75515229/104031028-34dbc980-5207-11eb-87f0-8f8e2beca690.png)

**Comment by TMWWDW** [comment]
> edit: turns out it was error on my end.

Can you share how you resolved the isssue?

**Comment by EltonGohJH** [comment]
Hi sorry for the late reply. I did a custom render for column and I use map on an array and forgot to map the keys.

**Comment by shushu27** [comment]
Hey, I have the same issue. I use map on an array as well, but I dont know how to map the keys. Could you help me? @EltonGohJH

**Comment by CanPacis** [comment]
> Hey, I have the same issue. I use map on an array as well, but I dont know how to map the keys. Could you help me? @EltonGohJH

You can provide the index of the each item in an array as a key.

```
list.map((item, i) => <MTableCell key={i} />)
```

**Comment by shushu27** [comment]
My material table version is 1.69.3 and doesnt provide MTableCell
