### ISSUE TITLE
How to get rowData index?

### ISSUE THREAD

**Issue by cesoftinfo** [mbrn/material-table#273]
Is is possible to get rowData index on click?

**Comment by mbrn** [comment]
You can access id of rowData by `rowData.tableData.id`. But this is initial index. It is not index of sorted or filtered data.

**Comment by mbrn** [comment]
@cesoftinfo ,

If rowData.tableData.id is not enogh for you, please reopen issue.

**Comment by AWIXOR** [comment]
you can use what @mbrn said like this for example: `onRowClick={(event, rowData) => console.log(rowData.tableData.id)};`

**Comment by arunakasoju** [comment]
Back to index topic, how to get index of rowdata? I like to show alternate colors for rows, and using 'rowData.tabledata.id % 2' for this. It works fine, but as mbrn already said above, it doesn't work when the table is sorted. How can we solve 'alternate colors to rows'?

Thanks a lot in advance.
