### ISSUE TITLE
Cannot install this package.

### ISSUE THREAD

**Issue by jeff-brooks** [mbrn/material-table#2730]
I'm not able to install this package as described in the page instructions.

I created a new create-react-app and then tried to install this package, which did not work.

My commands:
npx create-react-app new-create-react-app
cd new-create-react-app
npm start (verified that app runs successfully in the browser)
npm install material-table @material-ui/core

result:
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: new-create-react-app@0.1.0
npm ERR! Found: @material-ui/core@4.11.2
npm ERR! node_modules/@material-ui/core
npm ERR!   @material-ui/core@"*" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @material-ui/core@"4.0.1" from material-table@1.69.2
npm ERR! node_modules/material-table
npm ERR!   material-table@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by mpbunch** [comment]
Same / similar issue:
I have tried using a few older versions of material-ui/core with no luck.

❯ npm i material-table       
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: react-amplify@0.1.0
npm ERR! Found: @material-ui/core@4.11.2
npm ERR! node_modules/@material-ui/core
npm ERR!   @material-ui/core@"^4.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @material-ui/core@"4.0.1" from material-table@1.69.2
npm ERR! node_modules/material-table
npm ERR!   material-table@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/terminator/.npm/eresolve-report.txt for a full report.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/terminator/.npm/_logs/2021-01-11T18_25_54_799Z-debug.log

**Comment by jeff-brooks** [comment]
@mpbunch , `npm i material-table@1.69.0` didnt work for me. Can you provide anything further on how you got that to work? Was it in a fresh install of create-react-app?

**Comment by jeff-brooks** [comment]
Ok, after looking at https://github.com/mbrn/material-table/issues/2720, it appears that the version of npm is part of the problem. I downgraded npm from 7+ to 6.14.11 and was able to install material-table version 1.69.0

**Comment by mpbunch** [comment]
@jeff-brooks Glad you were able to get it working.

I am on npm 7.3.0
Not a clean install, tried to upgrade all dependencies which didn't work (error above), and then was able to upgrade everything except material-table to latest, and then upgraded material-table to 1.69.0.

**Comment by batazor** [comment]
Is there a solution to this problem?

**Comment by anantt-08** [comment]
Any Solution?

**Comment by RaiMX** [comment]
Please fix this issue

**Comment by westsideori** [comment]
Facing the same issue when trying to deploy app to Netlify. Unable to get material-table 1.69.2 to work with latest version of @material-ui/core.

**Comment by HamdiNawfel** [comment]
Facing the same issue  but it works for me by:
1*deleting node_moduls
2*deleting package-lock.json
3* add this two line to dependencies object in pachage.json
 "@material-ui/core": "^4.0.1",
    "material-table": "^1.69.2",
4* npm i -f
