### ISSUE TITLE
Material Table Freezes on adding more than 3 or 4 rows

### ISSUE THREAD

**Issue by Gowthami11** [mbrn/material-table#2731]
I have a customized material table with mutiple api calls. when i am adding and editing more than 3 rows, the app is freezing on save of 4th row.

![image](https://user-images.githubusercontent.com/44780784/104096285-9a8c8c00-52c1-11eb-9b46-44c4a4c7f1be.png)

please help me here

**Comment by peacechen** [comment]
Unfortunately mbrn is inactive and not merging PR's. Use the official community fork [@material-table/core ](https://github.com/material-table-core/core)instead.
