### ISSUE TITLE
Add HeaderCell component override

### ISSUE THREAD

**Issue by yam2** [mbrn/material-table#2732]
I wanted to add colspan to the header cell. I ended up writing a custom Header component which is quite a bit just for this. This can be solved with having an override for HeaderCell which can be as simple as {HeaderCell: props => <TableCell {...props} colSpan={2}/>}

**Comment by alehechka** [comment]
In relation to this, it would be nice to have a custom render component in the column definition (like the custom rowCell rendering) to render an individual custom HeaderCell
