### ISSUE TITLE
Sorting does not persist through rerenders [reproducible codesandbox]

### ISSUE THREAD

**Issue by ishake** [mbrn/material-table#2734]
Codesandbox: https://codesandbox.io/s/material-table-sorting-bug-mdzsx

**Description of bug**
Our sorts are no longer persisting through rerenders for client-side data-driven tables (tables where an array is passed in for the data). (Note: if you switch to material-table v1.59.0 in the Codesandbox example, the bug disappears.)

**To Reproduce**
In sandbox, sort by one of the columns, then click one of "Set" buttons.

**Expected Behavior**
The sort persists after clicking the "Set" button.

**Actual Behavior**
The sort is reset to the initial sort after clicking the "Set" button.

**Environment**
OS: macOS
Browser: Chrome
Version 87.0.4280.88 (Official Build) (x86_64)

**Comment by peacechen** [comment]
Unfortunately mbrn is inactive and not merging PR's. Use the official community fork [@material-table/core ](https://github.com/material-table-core/core)instead.
