### ISSUE TITLE
onBulkUpdate doesn't give EDIT icon next to the search

### ISSUE THREAD

**Issue by DewangS** [mbrn/material-table#2736]
# Guidelines

- #### Please include a demo of the issue/behavior/question you have
I have below code which is in line with the sample code provided on material-table site though I can't see one\single EDIT\PEN icon next to the search as per the sample. All I am getting it edit icons against individual rows which is not I want. I'm using "material-table": "^1.67.0" as later versions had browser freezing issue.
```
<MaterialTable
              title="Issue Permits"
              icons={tableIcons}
              columns={columns}
              data={applicationList}
              options={{
                showTitle: true,
                isLoading: true,
                
                headerStyle: {
                  backgroundColor: "#01579b",
                  color: "#FFF",
                },
              }}
              editable={{
                onBulkUpdate: (changes) =>
                  new Promise((resolve, reject) => {
                    setTimeout(() => {
                      resolve();
                    }, 1000);
                  }),
                onRowUpdate: (newData, oldData) =>
                  new Promise((resolve, reject) => {
                    setTimeout(() => {
                      const dataUpdate = [...applicationList];
                      const index = oldData.tableData.id;
                      dataUpdate[index] = newData;
                      setApplicationList([...dataUpdate]);

                      resolve();
                    }, 1000);
                  }),
              }}
              
            />
```
- #### Please try to be as detailed as possible
Not getting the bulk edit pen icon next to the SEARCH text box as per the sample provided on https://material-table.com/#/docs/features/editable 

- #### You may fork one of the following starter templates if you would like:

  - #### [CodeSandbox](https://codesandbox.io/s/material-table-starter-template-xnfpo)
  -
  - #### [StackBlitz](https://stackblitz.com/edit/material-table-starter-template)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DewangS** [comment]
closing this as it is only available in v.1.68.0 onwards. Just upgraded package version to v.1.69.2 and it works though now having a complete different issue. Now the page won't even load. will raise a new bug.

**Comment by MhEsn** [comment]
I have the same issue.did you find any solution?

**Comment by DewangS** [comment]
@MhEsn no one maintains this repo so I started using "@material-table/core": "^2.3.37" which is a fork of this but at least those people maintains the repo and also you will get prompt response. Hope this helps.
