### ISSUE TITLE
Incrementing row number not available

### ISSUE THREAD

**Issue by z-quest** [mbrn/material-table#2738]
QUESTION ? I want the rows to display incrementing role numbers. Starting from 1 till the number of rows. For example, the table to have a column that says No. and the column shows current index number, but when the rows change by filter or search the numbers has to refresh and start to show form 1 again. I tried to implement by using rowData.tableData.id , but it only gives a fixed number and doesn't update when rows are filtered or searched.

**Comment by z-quest** [comment]
@

**Comment by z-quest** [comment]
Can someone please tell me how to do this?

**Comment by jagadeeshkoka** [comment]
> Can someone please tell me how to do this?

@z-quest You can create new column, and while populating ur array jusr calculate ur serial number and display it as new column
