### ISSUE TITLE
State & memo reset on Action override when re-render of material table triggered

### ISSUE THREAD

**Issue by cbaker** [mbrn/material-table#2743]
I'm trying to override the Action component to return a custom selector that allows a user to utilize a preconfigured filter.
The state, memos, etc of my component get fully reset when the table data changes, not sure exactly what's going on here.

Minimal reproducible sandbox:
https://codesandbox.io/s/charming-elgamal-oefuv

**Comment by derekrprice** [comment]
Minimal reproducible test case: https://codesandbox.io/s/charming-elgamal-oefuv?file=/src/App.js

**Comment by cbaker** [comment]
Update this issue persists even when you don't override action and you override the icon button component via:
```
{
      icon: "link",
      tooltip: "blah",
      onClick: () => {},
      iconProps: {
          component: () => (
             <MyComponent
                 setData={setData}
                 sourceData={sourceData}
            />
        )
    }
}
```

**Comment by cbaker** [comment]
Externally getting the ref then doing something along the line of the following example appears to remedy the problem?
```
const { current } = tableRef;
const newData = data.filter((d) => d.b < 10);
current.dataManager.setData(newData);
current.setState(current.dataManager.getRenderState());
```

**Comment by mayuresh82** [comment]
Hi @cbaker  can you provide a complete example using your sandbox
