### ISSUE TITLE
column data shifts to the right in bulkUpdate mode v.1.68.x

### ISSUE THREAD

**Issue by DewangS** [mbrn/material-table#2746]
**Bug Description**

So, I have a requirement to allow user to bulk update one column out of 10. When I click on the 'edit' pen icon on the top right corner next to the search criteria with the magnifier icon, all the column content shifts by a column width to the right side which really look out of context content compared to column headers as column headers doesn't move. 

**How To Reproduce**

Create a material table component with onBulkUpdate element under editable as per below ...

 ```
<MaterialTable
              title="Test Bulk Updates"
              icons={tableIcons}
              columns={columns}
              data={data}
              options={{
                showTitle: true,
                isLoading: true,
                pageSize: 10,
                headerStyle: {
                  backgroundColor: "#01579b",
                  color: "#FFF",
                },
              }}
              editable={{
                onBulkUpdate: (changes) =>
                  new Promise((resolve, reject) => {
                    setTimeout(() => {
                        console.log('+++ CHANGES : ', changes)
                        const dataUpdate = [...data];
                        for (var key in changes) {
                            if (changes.hasOwnProperty(key)) {                            
                              dataUpdate[key] = changes[key].newData
                            }
                        }
                        setData([...dataUpdate]);
                      resolve();
                    }, 1000);
                  })
              }}
            />
```

I noticed that if you add just a dummy 'actions' element to the table, it doesn't shift the column content though I really don't want to have a work around like this as I don't have any individual action per row. As you can see from the below code **I've set the hidden flag to true** to hide action icon to keep actions as a first column as a placeholder to avoid this whole shifting issue.

If I am not wrong, I think the issue is due to added extra 'cancel' icon on the top right corner as soon as you hit the edit\pen icon i.e. this additional icon results in unnecessary shifting of column contents. This is is clearly a bug in v.1.69.0. Unfortunately I can't go to anything lower version as the bulk update is only available in v.1.68.0 onwards.

```
actions={[
                {
                  icon: 'edit',
                  hidden: true,
                  tooltip: 'Update',
                  onClick: (event, rowData) => {
                    // Do save operation
                  }
                }
              ]}
```

**Expected behavior**
I am expecting no shifting of current column content when I hit the edit\pen icon.

**Screenshots**

Not sure how to attach screen images here

**Desktop (please complete the following information):**

- OS: MacOS Mojave 10.14.5
- Browser Chrome 
- Version 87.0.4280.141 (Official Build) (x86_64)

**Smartphone (please complete the following information):**

N/A

**Additional context**

N/A

**Comment by anmolmalik97** [comment]
Try this in options.

`options={{
                    actionsColumnIndex: -1
}}`

**Comment by DewangS** [comment]
Thanks @anmolmalik97 your suggested solution seems to do the trick.. thanks
