### ISSUE TITLE
Error in currencySettings when set code in 'COP'

### ISSUE THREAD

**Issue by Alejandro-Arroyave** [mbrn/material-table#2749]
**Describe the bug**
I set in my project the currency settings like this:

```
export const columnCurrencySetting = {
  locale: 'es-CO',
  currencyCode: 'COP',
  minimumFractionDigits: 0,
}

{
   title: example,
   field: example,
   type: 'currency',
   currencySettings: columnCurrencySetting 
}
```
The formatting is bad, when the number have 4 digits the formatting would be $5.300, not $5300 like is shown in the screenshot.

**To Reproduce**

1. Make a table with some currency type column
2. Set currencySettings.currencyCode='COP' and currencySettings.locale='es-CO'
3. Put a 4-digits number in these columns

**Expected behavior**
Format to $1.000, not to $1000

**Screenshots**
![image](https://user-images.githubusercontent.com/52082711/105095500-bfc48b80-5a73-11eb-8152-7d3a5d7fb63a.png)

**Comment by Cnordbo** [comment]
The currency settings is actually based on the browsers native language sensitive number formatting. 
https://github.com/mbrn/material-table/blob/b7474ca0f5497f04ff3a3d50e709d86de7c639b0/src/components/m-table-cell.js#L85

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat

This can be tested directly in your console
```js
Intl.NumberFormat('es-CO',{ style: 'currency', currency: 'COP', minimumFractionDigits: 0 }).format(1300)
```
or
```js
let amount = 1300;
amount.toLocaleString('es-CO', { currency: 'COP', style: 'currency'});
```

Also, have a look at this: 

> According to the Real Academia Española, the standard form in Spanish is to separate numbers in groups of three, separated with whitespace, if the number has more than four digits, i.e. at least five (Source: https://www.rae.es/dpd/números, section 2.a, in Spanish).

Original mention: https://stackoverflow.com/a/59250342/1555514

**Comment by Alejandro-Arroyave** [comment]
Oh, I understand, i didn't know that, thanks for explain me @Cnordbo
