### ISSUE TITLE
Resizable columnns 

### ISSUE THREAD

**Issue by TimCodes** [mbrn/material-table#275]
I have a need for columns to be resizable. It's needed in situations where a user wants to customize the way a table looks. Turning the cols on or off is great. This will just add one more way to customize the table look and feel. Also, great for situations where there is a lot of text in one column

**Comment by mbrn** [comment]
@TimCodes , I will consider this feature

**Comment by TimCodes** [comment]
Awesome, Thank you

**Comment by bherzberg96** [comment]
I second the implementation of this feature.

**Comment by FastAuth** [comment]
@mbrn Please consider this feature, actually there is no option to provide custom header cell or pass column width, so I can't implement this on my own

**Comment by rikr2sanchez** [comment]
It would be great to have this feature
