### ISSUE TITLE
v1.69.2 randomly pins all the dependencies

### ISSUE THREAD

**Issue by vdh** [mbrn/material-table#2751]
The most egregious one being pinning `date-fns` from `^2.0.0-alpha.27` to `2.0.0-alpha.27`, causing the old alpha to install with plenty of eye-catching flame emojis in the console (which is how I noticed the issue). FYI, `date-fns` is already at `2.16.2` right now and there doesn't seem like a good reason to backtrack to using an alpha version in a patch version release like that.

```
🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥

  Thank you for testing (⩗) date-fns v2!

  In v2 we've introduced a number of breaking changes
  that make date-fns even more consistent and reliable.
  Please read the changelog carefully: https://git.io/fxCWb

  Please support us at Open Collective: https://opencollective.com/date-fns

🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥
```

It appears to have been pinned in commit c6c98c84050b541b2a9ce1b7741eeaae8a5806e0

**Comment by lpillonel** [comment]
Also facing this issue, causing my bundle size to increase significantly.
Possible to set back dependencies to minor version ?

Also, I would suggest to set jspdf (and his plugins) as a peer dependencies, so it could be included only when needed ?

**Comment by johnthagen** [comment]
> Also, I would suggest to set jspdf (and his plugins) as a peer dependencies, so it could be included only when needed ?

I think that the [`@material-table/core`](https://github.com/material-table-core/core) fork addresses this: https://material-table-core.com/docs/breaking-changes

**Comment by vdh** [comment]
@Domino987 Could you please undo this version pinning change you made? Pinning to an old alpha is not a good idea :(

**Comment by Domino987** [comment]
@vdh can you specify what i supposedly did?

**Comment by vdh** [comment]
@Domino987 It was in this commit: https://github.com/mbrn/material-table/commit/c6c98c84050b541b2a9ce1b7741eeaae8a5806e0

All the versions changed to pinned versions (`^` removed), causing the `2.0.0-alpha.27` version of `date-fns` to be installed, amongst other pinned changes. I can't see any hints in the commit on how that related to your other changes, or why versions needed to be hard-pinned like that. Especially a `date-fns` alpha version?

**Comment by Domino987** [comment]
Mbrn decided that that was a good idea. The problem is that he abandoned this project so there is no way to fix this, since only he can merge and releases.

**Comment by vdh** [comment]
That's disappointing.

Just FYI, you'd have fewer dependency issues if you use the `package-lock.json` file to manage the version pinning, rather than hard-pinning all the dependencies in `package.json`.

**Comment by Domino987** [comment]
Unfortunately there is nothing I can do to help you since I am not the owner and the owner abandoned this repo. You could migrate to material-table-core, which is a community fork.
