### ISSUE TITLE
Is there a way to call the add row function from outside the table? To simulate the add button getting clicked?

### ISSUE THREAD

**Issue by tran-simon** [mbrn/material-table#2755]
Hi,

I want to add a button outside the table that behaves just like the 'add' action button. 

In the code, I see that the add button is defined here:

````
  if (calculatedProps.editable.onRowAdd) {
        calculatedProps.actions.push({
          icon: calculatedProps.icons.Add,
          tooltip: localization.addTooltip,
          position: "toolbar",
          disabled: !!this.dataManager.lastEditingRow,
          onClick: () => {
            this.dataManager.changeRowEditing();
            this.setState({
              ...this.dataManager.getRenderState(),
              showAddRow: !this.state.showAddRow,
            });
          },
        });
      }
````'


Is there a way to simulate the onClick from outside the table? Thank you

**Comment by LuisPinaSoares** [comment]
Hi!,
I was looking for something similar,
I would like to be able to open a table with the onRowAdd activated.

**Comment by bgbbmm** [comment]
Yes I just did this similar thing in my project (I added a click to edit feature on the row click handler to make it easier to open a row up for editing). The trick is to get the tableRef instance. Once you do this it opens up for all sorts of other things!

I got the idea from the [Duplicate Action example](https://material-table.com/#/docs/features/actions):
Look at the code there (I've also copied it below) and you can see how they did create the ref, pass it in the tableRef prop, and use it inside of their custom action. You've also got the code you need above to do what you want, just need to apply it like they did in the example. 

I hope this helps you!
