### ISSUE TITLE
ReferenceError: React is not defined

### ISSUE THREAD

**Issue by davidbarman** [mbrn/material-table#2758]
Not sure if this is the appropriate place to post this.
First app using material-table.  App works find in React dev mode.  However, after deploying the app.  I have tried both Vercel and Netlify.  Both platforms are giving me the same result.
Any component that has the material-table element, crashes right after mounting.  I can see the table render and then the screen goes blank.  When looking in the browser console, I find:  "ReferenceError: React is not defined"
If I temporarily comment out the <MaterialTable> element and its contents then the component doesn't error out.  This has led me to a problem with the way I am using MaterialTable.  I am trying to use MT in multiple components and they all have the error issue.

Here is an example of one of them:
<MaterialTable
        editable={{
          isEditable: (rowData) => {
            return true;
          },
          onRowAdd: (newData) =>
            new Promise((resolve) => {
              console.log(newData);
              console.log(props.customerNumber);
              let enabled = newData.enabled ? newData.enabled : false;
              let newRow = {
                ...newData,
                enabled: enabled,
              };
              // add new user and then refresh state from database
              serviceContractService
                .addAdminUser({
                  ...newRow,
                })
                .then(() => {
                  serviceContractService.getAdminUsers().then((users) => {
                    setUserList(users);
                    console.log(users);
                  });
                  resolve();
                });
            }),
          onRowUpdate: (newData, oldData) =>
            new Promise((resolve, reject) => {
              console.log("hello");
              console.log(newData);
              console.log(
                userList.filter((user) => user._id === newData._id)[0]
              );
              serviceContractService.updateAdminUsers(newData).then(() => {
                console.log(".then");
                serviceContractService.getAdminUsers().then((users) => {
                  setUserList(users);
                  console.log(users);
                });
                resolve();
              });
            }),
          onRowDelete: (oldData) =>
            new Promise((resolve, reject) => {
              console.log(oldData);
              serviceContractService
                .deleteAdminUsers({
                  ...oldData,
                })
                .then(() => {
                  serviceContractService.getAdminUsers().then((users) => {
                    setUserList(users);
                    console.log(users);
                  });
                  resolve();
                });
              resolve();
            }),
        }}
        icons={tableIcons}
        data={userList}
        columns={columns}
        pageSize={25}
        checkboxSelection
        rowHeight={75}
        title="Admin User Details"
        options={{ search: true, exportButton: false, pageSize: 5 }}
      />

**Comment by davidbarman** [comment]
Also, my dependencies in package.json are as follows:
"dependencies": {
    "@date-io/core": "^2.10.6",
    "@date-io/dayjs": "^1.3.13",
    "@material-table/core": "^2.2.3",
    "@material-ui/core": "^4.11.2",
    "@material-ui/data-grid": "^4.0.0-alpha.14",
    "@material-ui/icons": "^4.11.2",
    "@material-ui/styles": "^4.11.2",
    "@testing-library/jest-dom": "^5.11.8",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "axios": "^0.21.1",
    "dayjs": "^1.10.4",
    "material-table": "^1.69.2",
    "pdfmake": "^0.1.70",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-router-dom": "^5.2.0",
    "react-scripts": "4.0.1",
    "supertokens-auth-react": "^0.2.2",
    "web-vitals": "^0.2.4"
  },

**Comment by zhushenhang** [comment]
you can issue here https://github.com/material-table-core/core/issues
