### ISSUE TITLE
onSelectionChange is broken

### ISSUE THREAD

**Issue by shabeelsyed** [mbrn/material-table#276]
**Describe the bug**
With latest version 1.19.0, onSelectionChange is not getting fired for check box selections.

**To Reproduce**
https://mbrn.github.io/material-table/#/docz-examples-05-example-selection
Second example alert box does not show.

**Expected behavior**
onSelectionChange() should be fired on selection changes.

**Comment by mbrn** [comment]
This is done. You can use version 1.20.0
