### ISSUE TITLE
Cell Editable not working

### ISSUE THREAD

**Issue by niketh-boreddy** [mbrn/material-table#2760]
# Guidelines

- #### Please include a demo of the issue/behavior/question you have

- #### Please try to be as detailed as possible

- #### You may fork one of the following starter templates if you would like:

  - #### [CodeSandbox](https://codesandbox.io/s/material-table-starter-template-xnfpo)
  - #### [StackBlitz](https://stackblitz.com/edit/material-table-starter-template)

**Describe the bug**
In order to control if particular cells are editable the material-table docs note that "You can use `column.editable` to make a column cells editable or non-editable". However, the editable field does not work even when supplied with an appropriate function.

**To Reproduce**

1. In a table define the `cellEditable` prop appropriately
2. Add a `editable: ((columnDef: Column<RowData>, rowData: RowData) => boolean)` prop to any of the columns 

**Expected behavior**
It is expected that for the cells which do not satisfy the editable function, the cell should not be editable (should not have the dotted underline), but it still is.

**Screenshots**
<img width="720" alt="Screen Shot 2021-01-27 at 3 03 29 PM" src="https://user-images.githubusercontent.com/62398805/106066888-6cc18880-60b2-11eb-853e-4cbcd2759f5c.png">

**Comment by dppatel03** [comment]
I am using 
`cellEditable={{
            cellStyle: {},
            onCellEditApproved: (newValue, oldValue, rowData, columnDef) => {
                return new Promise((resolve, reject) => {
                    console.log('newValue: ' + newValue);
                    setTimeout(resolve, 4000);
                    alert("testing")
                });
            }
        }}`

But this is not working and no action is made
