### ISSUE TITLE
Selection shouldn't hide toolbar action

### ISSUE THREAD

**Issue by CJSarao** [mbrn/material-table#2763]
I've looked around and I can't find a way to have both the selection action and my default toolbar action visible at the same time. Here are screenshots of the current behavior and what I would expect would be doable.

1. 0 rows selected, toolbar action is visible :![logo](https://i.imgur.com/FGxWRRj.png])
2. x rows selected, selection action visible but toolbar action disappears : ![logo](https://i.imgur.com/WMkhIm2.png)
3. What I need the behavior to be when x rows selected, all actions visible (don't know how to do this) :  ![logo](https://i.imgur.com/i94IpAF.png)

**Comment by boakai-mamey** [comment]
+1
