### ISSUE TITLE
Material Table checkbox selectAll with conditional check

### ISSUE THREAD

**Issue by burcusozay** [mbrn/material-table#2768]
Hi,
I am trying to decrease value of the nRowSelected count when I give a condition for checkbox checked. I mean there is 10 row on my table and one of the record is "Mehmet" but the others are not. Then when I checked the "selectAll" checkbox tof of the table I want to table header text is "9 row(s) selected"."

How can I managed the change the nRowSelected value via my condition.

Here is my condition.
Ex.
 

 ```
options={{
            selection: true,
            selectionProps: rowData => ({
                checked: rowData.name !== "Mehmet",
                value: rowData.id,               
          })
       }}
```
 I checked the base codes. nRowSelected value is looks the checked row count but after the condition which I give above, yes some checkboxes are not checked but nRowSelected value still equals the row count.

**Comment by MatiasCiccone** [comment]
@burcusozay try this https://github.com/mbrn/material-table/pull/1787#issuecomment-688826222
