### ISSUE TITLE
Infinite loop request api when use queryRemote data then delete last row of pages.

### ISSUE THREAD

**Issue by saman-waruka** [mbrn/material-table#2771]
# I found an issue with Infinite loop request API  when using queryRemote data

**Describe the bug**
I found when I delete the last row of pages  exclude 1st-page ( on 1st-page work correctly, but another page has issued)

**To Reproduce**

1. set table with queryRemote data
2. set page size 5
3. add data on queryRemote to 6 rows
4. go to page 2
5. you will see only the 6th row
6. delete the 6th row
7. run function onQueryChange()
8. after run onQueryChange() will produce the loop

**Desktop (please complete the following information):**

- OS: [osx]
- Browser [chrome]

**Comment by pablos91** [comment]
I just came across this bug. Did it get fixed already? Is there any workaround for this ? After going to the last page and then running onQueryChange() starts an infinite loop.

![image](https://user-images.githubusercontent.com/1850835/125771047-e2f2a197-6e9b-4375-857f-1c0af6f5b7e9.png)

**Comment by pablos91** [comment]
I just came across this bug. After calling `tableRef.current && tableRef.current.onQueryChange(values);` when being on the last page puts me into infinite loop. Is there any workaround for this ? 

![image](https://user-images.githubusercontent.com/1850835/125772278-8a5134f7-a121-4f97-b001-665ef46d655f.png)

**Comment by link82** [comment]
I'm experiencing the same problem using remote data when i try to use a filter.
It seems to happen when filtered results number is less than current pageSize.

i.e if `pageSize` is 5 and I receive less than 5 items from API it keeps requesting again more data (without changing page number)

**Comment by link82** [comment]
Found a solution: I don't know why but if no data is returned from API it expects that page property returned from function to equal zero.

```
      return {
        data: entries.map( el => {
          const art = this.state.articles[el.article_id]

          return {
            ...el,
            tableData: {id: `entry-${el.id}`},
            article_part_code: el.part_code,
          }
        }),
        page: entries.length ? pagination.current_page : 0,
        totalCount: pagination.total_count
   }
```
This way it seems to work properly
