### ISSUE TITLE
Sorting is not working with remote data

### ISSUE THREAD

**Issue by PATTANPARVIN** [mbrn/material-table#2774]
Hi,

I'm using Material Table (v 1.67.0) with remote data onOrderChange (orderedColumnId, orderDirection) function always returning orderDirection = 'asc', it should return alternatively both 'asc' and 'desc'. But with static data, sorting is working good, This seems to be a specific issue when fetching remote data.

`  handleTableSorting = (order, direction) => {
    console.log('handleTableSorting', order, direction);
    const query = `ORDER BY '${this.state.columnName}' ${direction}`;
    AP.request(`${SEARCH_ISSUE}&jql=${query}&startAt=${start}&maxResults=${max}`)
      .then((data) => {
          this.setState({ tableData : data });
      })
  }
`

` <MaterialTable  
         columns={this.state.columns}
         data={this.state.tableData}
         onOrderChange={this.handleTableSorting}
         sorting={true}
 />`

- OS: [windows 10]
- Browser [chrome]
- Version [1.67.0]

Please reply the solution ASAP.

Thank you

**Comment by peacechen** [comment]
Unfortunately mbrn is inactive and not merging PR's. Use the official community fork @material-table/core instead.
This bug should be fixed in the current version.

**Comment by AravindTReddy** [comment]
> @material-table/core

Just installed this and the sorting works but not as expected, it randomly sorts without order.
