### ISSUE TITLE
Set initial widths for resizable columns

### ISSUE THREAD

**Issue by MartaGolabek** [mbrn/material-table#2776]
Hello,

I am using **columnResizable** feature, but I would like to have more control over the column widths. First of all, I would like to set width of each column to max width on the first render (initial values), then on each resize event, I would like to set/persist the new widths. Is this currently possible?

**Comment by delbaze** [comment]
Hello,

Which version do you have? I can't find "columnResizable" prop?
Anyway, I have set initial values width (and height of the cell, and so of the row) this way : 

```
  columns: [
      {
        width: 100,
        title: "My Title",
        field: "myfield",
        cellStyle: {
          height:80,
          textAlign: "center",
        }
      }
  ]
```
Width prop has to be number (I have tried something like "3rem", didn't work)
Hope it will help, bye

**Comment by MartaGolabek** [comment]
Hello,

Thank you for your answer. I am using version 1.69.2.

Are you using fixed tableLayout? Does the column always have exactly 100px width or sometimes more if more space is available?

**Comment by delbaze** [comment]
> Hello,
> 
> Thank you for your answer. I am using version 1.69.2.
> 
> Are you using fixed tableLayout? Does the column always have exactly 100px width or sometimes more if more space is available?

Hello, 

In some case, my table is table-layout:fixed and some other auto.
In both, I use the width: 100 for the icon column. So this column is always 100px.
The other columns are auto (less wide if space is reduced, wider if more space is available).

**Comment by delbaze** [comment]
if you want to have real resizable columns, I think you should consider to make your own fork, this functionnality is not implemented (yet) in material-table.
