### ISSUE TITLE
How to completely disable columns width algorithm 

### ISSUE THREAD

**Issue by MartaGolabek** [mbrn/material-table#2777]
Hello,

I would like to manually set widths on each column. The summed columns widths are then greater than the viewport width, thus the table should enable horizontal scroll automatically.

Unfortunately, the horizontal scroll isn't enabled and the widths of all columns amount to a negative number:  `width: calc(-3px);` and are then set automatcally (equal widths).

Details:
I am using `tableLayout: "fixed"` and the widths are set directly on columns. I have also tried setting them via headerStyle and cellStyle on columns. None of these worked as expected. 

I would appreciate any help on that issue.

**Comment by zoosm3** [comment]
@MartaGolabek See below
https://material-table.com/#/docs/features/styling
https://material-table.com/#/docs/features/custom-column-rendering
