### ISSUE TITLE
Action buttons in table header and clear selection icon

### ISSUE THREAD

**Issue by mariolazzari** [mbrn/material-table#278]
**Describe the bug**
After upgrading to version 1.20, action buttons in table header losse their postition, as shown in attached screenshot.

I was not able to find into documentation the 'clear selection icon' from 'icons' section. Could you please update documentation?

**To Reproduce**
Add one or more free action to data table

**Expected behavior**
Free action icons should be aligned to right 

**Screenshots**
![image](https://user-images.githubusercontent.com/26960147/53788875-4ecd6680-3f23-11e9-98b6-0ac45ea8157a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version latest

**Comment by mbrn** [comment]
Hi @mariolazzari ,

I fixed it. Try version 1.20.1
