### ISSUE TITLE
Is it possible to make the new row that is generated by onRowAdd material table to appear at the top of the section?

### ISSUE THREAD

**Issue by v1v2v3vv55** [mbrn/material-table#2780]
Title.

As what is shown in the doc of material table, when you use editable with onRowAdd, the new row is always spawn at the bottom of the section. Is there a way to make that row appear at the top? Or how do I assign an onClick effect so that when user click on the Add button, it will automatically go to the bottom of the page? Let's just use the example on the doc: https://material-table.com/#/docs/features/editable

**Comment by rphovley** [comment]
Just found out how to do this, in the `options` prop for the table, add the attribute `addRowPosition: 'first'`
![Screen Shot 2021-02-14 at 12 09 49 PM](https://user-images.githubusercontent.com/10646939/107886522-8ab62800-6ebd-11eb-964e-95ed59579ebb.png)

I think that should probably be the default and the documentation for this is challenging to find but hopefully that helps/works for you

**Comment by chrisintegro** [comment]
@rphovley unfortunately, this only resolves the issue if the user happens to be at the top of the table.  If they've scrolled down the page, then they don't see the new row added.  Unless there's some other solution to scroll to the new row, I think this is a usability bug (as opposed to a question).
