### ISSUE TITLE
Is there any way to set the total record count in mat-table so that I can use it in server side pagination.

### ISSUE THREAD

**Issue by PiyushJoshi-GDM** [mbrn/material-table#2782]
import { AfterViewInit, Component, ViewChild } from '@angular/core';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatSort } from '@angular/material/sort';
import { tap } from 'rxjs/operators';
import { Subscription } from 'rxjs';
import { HttpClientService } from '../shared/services/httpClient.service';
import { UriConstant } from '../shared/constants/uri.constant';
import { LoaderService } from '../shared/services/loader.service';
import { SnackBarService } from '../shared/services/snack-bar.service';
import { AnalysisRequest } from '../model/analysis-results/analysis-results.model';
import { Router } from '@angular/router';
import { GridPagingModel, LandingPage } from '../model/landing-pages/landing-page';

  ngOnInit() {
    this.loaderService.setLoaderActive(true);
  }
  ngAfterViewInit() {
    this.getTableRecords(1, 5, "product", 'asc', '');
    this.dataSource.paginator = this.paginator;
    this.dataSource.sort = this.sort;
    this.dataSource.paginator.length = 100;

    // when paginator event is invoked, retrieve the related data
    this.paginatorSubscription$ = this.paginator.page
      .pipe(
        tap(() => {
          this.getTableRecords(this.paginator.pageIndex, this.paginator.pageSize, this.sort.active, this.sort.direction, this.filterValue)})
      )
      .subscribe();
  }

**Comment by zoosm3** [comment]
@PiyushJoshi-GDM this GitHub is NOT for Angular's material-table.
