### ISSUE TITLE
How to trigger edit row ?

### ISSUE THREAD

**Issue by rullymartanto** [mbrn/material-table#2784]
Hi I am trying to add function / other action in edit button in row, so I create action.
```
actions={[
                        {
                            icon: 'edit',
                            tooltip: 'Edit Index',
                            onClick: (event, rowData) => {
                                onEditClick(event, rowData);
                            }
                        },

```
will display 2 button edit
![image](https://user-images.githubusercontent.com/5577057/108472274-1c0f0b00-72bf-11eb-9912-6346210be2d2.png)
The red button edit is the action,
the yellow is isEditable.

how to make my edit button action (red button) also have function same with isEditable action function ?
because when I am click my edit button action (red button)  the row sill don't editable

![image](https://user-images.githubusercontent.com/5577057/108472520-70b28600-72bf-11eb-8e16-cc81e5bb26d1.png)

**Comment by jaflesch** [comment]
Did someone find a solution for this issue? I'm having the same trouble here.
