### ISSUE TITLE
how use onMouseOver and onMouseLeave in row

### ISSUE THREAD

**Issue by quocbaondvn2000** [mbrn/material-table#279]
I have a code
Row: props => (
                <MTableBodyRow
                  onMouseOver={() => console.log('show')}
                  onMouseLeave={() => console.log('hide')}
  {...props} />
I want to.. image
![2019-03-06_151550](https://user-images.githubusercontent.com/45376591/53790494-a8508800-3f59-11e9-8887-09e76b3f18bb.jpg)
),
Thanks

**Comment by mbrn** [comment]
Hi @quocbaondvn2000 ,

Your code has not problem. I fixed problem with Row overriding. You can upgrade to 1.20.2
