### ISSUE TITLE
Pagination component override - Problem with total count

### ISSUE THREAD

**Issue by mfahem** [mbrn/material-table#2791]
Hi, 

I am trying to do a simple pagination on my MaterialTable component. I have data coming from an API that returns a JSON with infos about the current page and the total count (current page number, number of elements in the current page, total number of pages, total number of elements). 

I store all of those elements in state and I've provided them to the Pagination component. However, when the state value is updated, the data gets fetched but the pagination still shows : 0-0 of 0.

Do you have any idea why this could happen ?

Here is the code so you can understand better : 

```
export default function Clients() {
    const [clients, setClients] = React.useState([])
    const [pageSize, setPageSize] = React.useState(10)
    const [currentPage, setCurrentPage] = React.useState(0)
    const [isLoading, setIsLoading] = React.useState(true)
    let totalElements = 0
    let totalPages = 0
    
    React.useEffect(() => {
        fetchAllClients()
    }, [])

    const fetchAllClients = () => {
        setIsLoading(true)
        fetch(`https://my-api.com/clients?size=${pageSize}&page=${currentPage}`)
            .then(result => result.json())
            .then(jsonResult => {
                totalElements = jsonResult.totalElements
                totalPages = jsonResult.totalPages
                setCurrentPage(jsonResult.currentPageNumber)
                setClients(jsonResult.content)
                setIsLoading(false)
            })
            .catch(error => {
                console.log("Error : " + error)
                setIsLoading(false)
            })
    }

    const columns = [
        { title: 'Gender', field: 'gender', searchable: false  },
        { title: 'First Name', field: 'firstName', searchable: false },
        { title: 'Last Name', field: 'lastName' , searchable: false },
        { title: 'Company', field: 'company', searchable: false  }
    ];

    const handleRowsPerPageChange = (event) => {
        setPageSize(event.target.value)
    }

    useEffect(() => {
        fetchAllClients()
    }, [pageSize, currentPage])

    const handlePageChange = (event, newPageNumber) => {
        setCurrentPage(newPageNumber)
    }

    return (
        isLoading ? <div></div> :
        <div>
            <MaterialTable columns={columns}
                           data={clients}
                           title='Clients'
                           options={{
                               search: false,
                               pageSize: pageSize
                           }}
                           components={{
                               Pagination: props => (
                                   <TablePagination
                                       {...props}
                                       rowsPerPageOptions={[5, 10, 20]}
                                       rowsPerPage={pageSize}
                                       count={totalElements}
                                       page={currentPage}
                                       onChangePage={handlePageChange}
                                       onChangeRowsPerPage={handleRowsPerPageChange}
                                   />
                               )
                           }}
             />
        </div>
    )
}
```

Thank you for your help

**Comment by scipe** [comment]
Are you sure that you have right numbers in jsonResult?

**Comment by mfahem** [comment]
Yes I do, when I console log, it shows 52 for the total number of elements for instance

**Comment by antonioCozzi** [comment]
@mfahem 
I have the same issue that seems to be chained with the prop `pageSize` in the options object. I followed this thread (https://stackoverflow.com/questions/57568738/material-table-how-to-add-more-rows-per-page-and-fix-rendering-reactjs/57569050?noredirect=1#comment101598852_57569050) but the table doesn't refresh the size. 

I added this in the table props but is working only the first render:
`options={{
                    pageSize: size,
                    emptyRowsWhenPaging: false
                }}`

with `size` defined in a `useState`.

**Comment by antonioCozzi** [comment]
It seems that the parameter `pageSize` that I've found sets a max page size. 

You can have different page sizes but the table won't overflow the `pageSize` you define in the `options` prop (it seems).

I think it's better call this prop something like `maxPageSize`.

**Comment by mfahem** [comment]
@antonioCozzi @scipe I think I found my problem. The totalElements variable was not a state variable. So when it gets updated, it never sends the value to the table. When I converted it to a state variable it worked
