### ISSUE TITLE
Alphabetize values in filter and edit drop downs

### ISSUE THREAD

**Issue by metzelSherpas** [mbrn/material-table#2792]
When the lookup object for a column is a numeric-key based value, like these:

lookup = {
1: "ddd",
2: "bbb",
3: "aaa",
4: "ccc",
}

They appear in the order of key for each item, like

ddd
bbb
aaa
ccc

I need to make them appear in alphabetical order based on the value, not the order of the keys.

I've tried to update the object using a map,  but this isn't supported.  I've tried updated the object with sort to reorder the object , but I have learned that JS will always reorder an object with integer based keys to show in numeric order based on the keys.

how can I get the dropdowns to appear like

aaa
bbb
ccc
ddd

THANK YOU

**Comment by atharifar** [comment]
I have this sorting problem with the "lookup" in Material Table as well. I have not find a solution yet.
It is like, the lookup filter in Material Table converts the object, in your given example  {1: "ddd", 2: "bbb", 3: "aaa",4: "ccc"} ,  to an array with indices provided by the keys. therefore, any sorting attempt is ignored. 

Another similar example, if the lookup is {1: "Admin", 4: "Developer", 12: "Guest",, 11: "Operator", 2: "Viewer" }  then the drop down is like below and not sorted alphabetically. 

Admin
Viewer
Developer
Operator
Guest

**Comment by drummerpva** [comment]
Same issue here, using object as used never work, it's a limitations of javascript, to solve this the library need update code to use a Map instead.
