### ISSUE TITLE
material-table onRowupdate validation not working

### ISSUE THREAD

**Issue by yashaswinibprasad87** [mbrn/material-table#2795]
import React, { useState } from "react";
import MaterialTable from "material-table";
import { forwardRef } from "react";
import AddBox from "@material-ui/icons/AddBox";
import ArrowDownward from "@material-ui/icons/ArrowDownward";
import Check from "@material-ui/icons/Check";
import ChevronLeft from "@material-ui/icons/ChevronLeft";
import ChevronRight from "@material-ui/icons/ChevronRight";
import Clear from "@material-ui/icons/Clear";
import DeleteOutline from "@material-ui/icons/DeleteOutline";
import Edit from "@material-ui/icons/Edit";
import FilterList from "@material-ui/icons/FilterList";
import FirstPage from "@material-ui/icons/FirstPage";
import LastPage from "@material-ui/icons/LastPage";
import Remove from "@material-ui/icons/Remove";
import SaveAlt from "@material-ui/icons/SaveAlt";
import Search from "@material-ui/icons/Search";
import ViewColumn from "@material-ui/icons/ViewColumn";
import TextField from "@material-ui/core/TextField";
const tableIcons = {
Add: forwardRef((props, ref) => 
<AddBox {...props} ref={ref} />
),
Check: forwardRef((props, ref) => 
<Check {...props} ref={ref} />
),
Clear: forwardRef((props, ref) => 
<Clear {...props} ref={ref} />
),
Delete: forwardRef((props, ref) => 
<DeleteOutline {...props} ref={ref} />
),
DetailPanel: forwardRef((props, ref) => (
<ChevronRight {...props} ref={ref} />
)),
Edit: forwardRef((props, ref) => 
<Edit {...props} ref={ref} />
),
Export: forwardRef((props, ref) => 
<SaveAlt {...props} ref={ref} />
),
Filter: forwardRef((props, ref) => 
<FilterList {...props} ref={ref} />
),
FirstPage: forwardRef((props, ref) => 
<FirstPage {...props} ref={ref} />
),
LastPage: forwardRef((props, ref) => 
<LastPage {...props} ref={ref} />
),
NextPage: forwardRef((props, ref) => 
<ChevronRight {...props} ref={ref} />
),
PreviousPage: forwardRef((props, ref) => (
<ChevronLeft {...props} ref={ref} />
)),
ResetSearch: forwardRef((props, ref) => 
<Clear {...props} ref={ref} />
),
Search: forwardRef((props, ref) => 
<Search {...props} ref={ref} />
),
SortArrow: forwardRef((props, ref) => 
<ArrowDownward {...props} ref={ref} />
),
ThirdStateCheck: forwardRef((props, ref) => 
<Remove {...props} ref={ref} />
),
ViewColumn: forwardRef((props, ref) => 
<ViewColumn {...props} ref={ref} />
)
};
export default function TableC() {
const [nameError, setNameError] = useState({
error: false,
label: "",
helperText: "",
validateInput: false
});
const [state, setState] = React.useState({
data: [
{
name: "Mehmet",
surname: "Baran"
},
{
name: "Zerya Betül",
surname: "Baran"
}
]
});
return (
<MaterialTable
title="Editable Example"
columns={[
{
title: "Name",
field: "name",
editComponent: props => (
<TextField
type="text"
error={
!props.value && nameError.validateInput
? nameError.error
: false
}
helperText={
!props.value && nameError.validateInput
? nameError.helperText
: ""
}
value={props.value ? props.value : ""}
onChange={e => {
if (nameError.validateInput) {
setNameError({
...nameError,
validateInput: false
});
}
props.onChange(e.target.value);
}}
/>
)
},
{ title: "Surname", field: "surname" }
]}
data={state.data}
icons={tableIcons}
editable={{
onRowAdd: newData =>
new Promise((resolve, reject) => {
setTimeout(() => {
console.log(newData)
if (!newData.name) {
setNameError({
error: true,
label: "required",
helperText: "Required helper text",
validateInput: true
});
reject();
return;
}
resolve();
const data = [...state.data];
data.push(newData);
setState({ ...state, data });
}, 600);
}),
onRowUpdate: (newData, oldData) =>
new Promise((resolve, reject) => {
setTimeout(() => {
console.log("Update",newData)
if (newData.name === "") {
setNameError({
error: true,
label: "required",
helperText: "Required helper text",
validateInput: true
});
reject();
return;
}
resolve();
if (oldData) {
setState(prevState => {
const data = [...prevState.data];
data[data.indexOf(oldData)] = newData;
return { ...prevState, data };
});
}
}, 600);
})
}}
/>
);
}

**reject() method  is not working onRowUpdate method, only works with onRowAdd
version of Material-table  [1.69.0]
material-ui/core [4.11]
Looking for immediate solution to work**

**Comment by DewangS** [comment]
have you tried validate with your column definition? 

e.g. 
columns={[
{
title: "Name",
field: "name",
**validate: rowData => !validateName(rowData.first_name)  ? { isValid: false, helperText: 'Please enter First Name' } : true,**
},
{ title: "Surname", field: "surname" }
]}
const validateName = (firstName) => {

    if (firstName === "" || typeof firstName === undefined) {
      return false
    }

    return true;
}

**Comment by yashaswinibprasad87** [comment]
@DewangS above solution works when there is no editComponent ={{.......}}  is used , I need to have custom textFeild 

Example :   editComponent: (rowData) => {

                    return ( <FormControlLabel
                        control={

                            <TextField className={this.props.classes.textFieldTable}
                            autoFocus
                                id="desc"
                                name="desc"
                                error={
                                    !rowData.value && this.state.nameError.validateInput
                                        ? this.state.nameError.error
                                        : false
                                }
                                helperText={
                                    !rowData.value && this.state.nameError.validateInput
                                        ? this.state.nameError.helperText
                                        : ""
                                }
                                value={this.state.dataObj.desc || rowData.value || ''}
                                onChange={e => { 
                                    if (this.state.nameError.validateInput) {
                                        this.setState({
                                            nameError: { ...this.state.nameError, validateInput: false }
                                        });
                                    }
                                    rowData.onChange(e.target.value);  }}
                                variant="outlined"
                                size="small"
                                InputProps={{
                                    classes: {
                                        root: this.props.classes.outlinedInput,
                                        focused: this.props.classes.focused,
                                        notchedOutline: this.props.classes.notchedOutline,
                                    },
                                    className: this.props.classes.input
                                }}

                            />

                        }
                    />


                )}
When used above onRowUpdate method proises reject and return not Working properly, but works on onAddRowUpdate method


Looking for the fix and solution

**Comment by DewangS** [comment]
ah..ok. My bad. Let's hope someone fixes it.
