### ISSUE TITLE
Can't delete invalid rows, only if they are valid.

### ISSUE THREAD

**Issue by vycdev** [mbrn/material-table#2796]
# Guidelines

**Describe the bug**

If you add column validation, you won't be able to delete a row if it's invalid.

**To Reproduce**

Have a table with editing, deleting and column validation.
Introduce data in the table via code, hardcode it. It has to be invalid data.
Try to delete a row with invalid data on it, you won't be able to because the row is invalid.

**Expected behavior**

You should be able to delete a row regardless of if its valid or not.

**Screenshots**
This is for showing that the row is invalid:
![image](https://user-images.githubusercontent.com/49570123/109396368-d646e800-7939-11eb-9183-4824cf8ecf50.png)

This shows that the row was hardcoded and it's invalid:
![image](https://user-images.githubusercontent.com/49570123/109396363-cfb87080-7939-11eb-8956-49d2f529e9cb.png)

This shows that you can't click on the confirm delete button because the row is invalid.
![image](https://user-images.githubusercontent.com/49570123/109396393-f2e32000-7939-11eb-9430-4e1821a968c1.png)

**Additional context**

I think this is caused by the fact that the same button is used for saving the edit and deleting the row. So the same functions apply on it, including checking if the row is valid, so naturally on the confirm delete button there are the functions that will disable it if it's invalid, which shouldn't be the case.

OS: Windows 10
Browser: Chrome 88

I have tried it on the documentation website in an editor and it also happened there.

Note: I just took the example from the documentation website and I added `validate: rowData=>false` to make one of the columns always invalid, then if you try to delete a row, you won't be able to because the data is invalid.
```js
function Editable() {
  const { useState } = React;

  const [columns, setColumns] = useState([
    { title: 'Name', field: 'name', validate: rowData=>false },
    { title: 'Surname', field: 'surname', initialEditValue: 'initial edit value' },
    { title: 'Birth Year', field: 'birthYear', type: 'numeric' },
    {
      title: 'Birth Place',
      field: 'birthCity',
      lookup: { 34: 'İstanbul', 63: 'Şanlıurfa' },
    },
  ]);

  const [data, setData] = useState([
    { name: 'Mehmet', surname: 'Baran', birthYear: 1987, birthCity: 63 },
    { name: 'Zerya Betül', surname: 'Baran', birthYear: 2017, birthCity: 34 },
  ]);

  return (
    <MaterialTable
      title="Editable Preview"
      columns={columns}
      data={data}
      editable={{
        onRowAdd: newData =>
          new Promise((resolve, reject) => {
            setTimeout(() => {
              setData([...data, newData]);
              
              resolve();
            }, 1000)
          }),
        onRowUpdate: (newData, oldData) =>
          new Promise((resolve, reject) => {
            setTimeout(() => {
              const dataUpdate = [...data];
              const index = oldData.tableData.id;
              dataUpdate[index] = newData;
              setData([...dataUpdate]);

              resolve();
            }, 1000)
          }),
        onRowDelete: oldData =>
          new Promise((resolve, reject) => {
            setTimeout(() => {
              const dataDelete = [...data];
              const index = oldData.tableData.id;
              dataDelete.splice(index, 1);
              setData([...dataDelete]);
              
              resolve()
            }, 1000)
          }),
      }}
    />
  )
}
```

**Comment by Vyctor661** [comment]
It's been almost a month

**Comment by sanjeeviraj** [comment]
Until the above issue is addressed, There is a work around . We can use actions prop define the delete action instead of using editable prop.

`actions={[ {
                icon: () => <DeleteIcon/>,
                onClick: (event) => {
                  //delete 
                },                
                tooltip: "Delete",
              }
]}`

**Comment by Vyctor661** [comment]
6 months and nothing :(

**Comment by harrryhsu** [comment]
If this hasn't been figure out, you can check for the editing mode in validate() call, something like
validate: (data) => data.tableData && data.tableData.editing == "delete"
