### ISSUE TITLE
It is possible to resize column width by dragging in material table?

### ISSUE THREAD

**Issue by srivikk** [mbrn/material-table#2798]
I'm trying to resize the column width by mouse-drag.

I have gone through different searches but couldn't find anything to fulfill my query in material-table.

I found a solution to do so , but it was in angular.

[Resize column in angular material-table](https://stackblitz.com/edit/mat-table-resize)

I would like to do the same in react if it is possible.

![resi](https://user-images.githubusercontent.com/63007683/109611046-aa9f4a00-7b53-11eb-94a0-99a226a77132.PNG)

I found this columnResizable:true in [material-table demo github](https://github.com/mbrn/material-table/blob/master/demo/demo.js) but it doesn't seem to be working.

Is there any way how can I achieve this in material-table in react?

**Comment by edgar-pozadas-by** [comment]
I have the same question, I saw different issues about this feature and I found the PR 
https://github.com/mbrn/material-table/pull/2351
But I can't find the way to implement it

**Comment by kirin-yuen** [comment]
@edgar-pozadas-by @srivikk 

```js
options={{
        tableLayout: "fixed", // set fixed
        columnResizable: true,
}}
```

**Comment by kirin-yuen** [comment]
But the resize functio still any problem, it's not to goog to use.
