### ISSUE TITLE
Filtering with remote data

### ISSUE THREAD

**Issue by Vigneshkanthimathinathan** [mbrn/material-table#2799]
Hi, Iam using remote data in material table and I want to set filter for each column.
data={query =>
        new Promise((resolve, reject) => {
          let url = 'http://192.168.0.55:7000/paycheck/'
          url += query.pageSize
          url += '/' + (query.page + 1) + '/'
          if(query.search == '')
          {
            url += 'nodata'
          }
          else{
            url += (query.search)
          }   
          fetch(url)
            .then(response => response.json())
            .then(result => {
              resolve({
                data: result.data,
                page: result.page - 1,
                totalCount: result.total,
              })
            })
        })
      }
Currently I am sending search value to backend using query.search Can someone let me know how to send filtered value of each column using query.

**Comment by Vigneshkanthimathinathan** [comment]
# @mbrn

**Comment by zoosm3** [comment]
@Vigneshkanthimathinathan I guess you can use `query` as well. Print `query` by `console.debug(query)` for detail.

**Comment by Vigneshkanthimathinathan** [comment]
> 
> 
> @Vigneshkanthimathinathan I guess you can use `query` as well. Print `query` by `console.debug(query)` for detail.

@zoosm3 Thanks a lot.
