### ISSUE TITLE
Add the column attribute grouping, and add a groupIndex

### ISSUE THREAD

**Issue by heylenz** [mbrn/material-table#280]
Add the column attribute grouping, and add a groupIndex, which can be displayed at the beginning of the rendering.
like:
```
    columns: [
      { title: 'Adı', field: 'name' },
      { title: 'Soyadı', field: 'surname' },
      { title: 'Cinsiyet', field: 'sex', groupable: true, groupIndex: 1 },
      { title: 'Tipi', field: 'type', removable: false, groupable: true, groupIndex: 0 },
      { title: 'Doğum Yılı', field: 'birthYear', type: 'numeric' },
      { title: 'Doğum Yeri', field: 'birthCity', lookup: { 34: 'İstanbul', 63: 'Şanlıurfa' } },
    ]

```
if add attrs in column , maybe can remove grouping,
```
          options={{
            filtering: true,
            // grouping: true, //this grouping maybe can remove!
            selection: true,
            columnsButton: true,            
          }}
```
If you find it woks, I can try to implement this feature.

**Comment by mbrn** [comment]
Hi @heylenz ,

We already have default grouping feature. 

Look at the 2nd example at this: https://mbrn.github.io/material-table/#/docz-examples-12-example-grouping

**Comment by heylenz** [comment]
Sorry, I didn't look closely at the full document.

**Comment by xiaomaini** [comment]
> Hi @heylenz ,
> 
> We already have default grouping feature.
> 
> Look at the 2nd example at this: https://mbrn.github.io/material-table/#/docz-examples-12-example-grouping

Do you have an updated link by any chance? I couldn't find any default grouping options.
