### ISSUE TITLE
Attempted import error: 'makeStlyes' is not exported from '@material-ui/core/styles'.

### ISSUE THREAD

**Issue by brentN5** [mbrn/material-table#2801]
**Describe the bug**
I tried to import @material-ui/core/styles and it is giving me an error

**To Reproduce**
import { makeStlyes } from "@material-ui/core/styles"; 
Try to import the style and it will give you an error

**Expected behaviour**
To import the style without an error

**Screenshots**
https://i.imgur.com/sldblbZ.png

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: Version 88.0.4324.190

**Additional context**
Issue number #991 also had this error but the issue was closed. This is still occurring in the latest version.

**Comment by exkungen** [comment]
You have a typo in your screenshot: it's `makeStyles` instead of `makeStlyes`

**Comment by brentN5** [comment]
Yeah the typo wasn't the issue (the typo was only in the github issue). I have found the problem and it has been fixed.

**Comment by ChoppinBlockParty** [comment]
Hi, What was the issue I have this problem and have no clue how to solve it?

**Comment by vireshshah** [comment]
What was the issue? Do we need to import `withStyles` from `@material-ui/styles` instead of `@material-ui/core/styles` now in newer version? I am using "@material-ui/core": "^5.0.0-alpha.38".
