### ISSUE TITLE
On table load, open all the Details Panel by default

### ISSUE THREAD

**Issue by awalinsopan** [mbrn/material-table#2807]
# Guidelines

- #### Details Panel to be Open and Shown by Default. 

- #### Can I specify a prop to indicate that by default the details panel will stay open, unless the users clicks them to close?

**Comment by zoosm3** [comment]
@awalinsopan It might help
https://github.com/mbrn/material-table/issues/2012

**Comment by awalinsopan** [comment]
> @awalinsopan It might help
> #2012

Thanks! I will try!
