### ISSUE TITLE
set count for pagination

### ISSUE THREAD

**Issue by adriansnep16** [mbrn/material-table#281]
Hello!
For the custom pagination I'm not able to set the total number of items because the default value is the length of the table data. I'm receiving data from the server page by page(for example 10 rows per page) using "onChangePage" event but the total number of elements is for example 100.  So for custom pagination we cannot use length of the table data as "count" option.

**Comment by mbrn** [comment]
Hi @adriansnep16 ,

I will take a look at this asap
