### ISSUE TITLE
Abandoned project?

### ISSUE THREAD

**Issue by vizardkill** [mbrn/material-table#2819]
I open the discussion because I am concerned about the inactivity of the project, it is a large library and they have not been updated for months.
If you are looking for trained people I could give you a hand

**Comment by vizardkill** [comment]
??

**Comment by villuv** [comment]
Yes, indeed. It is very quiet here.
There seems to be a community fork of this repository that has progressed a bit further in some sense:

https://github.com/material-table-core/core

At least I'm keeping my eye on that one.

**Comment by vizardkill** [comment]
It's a shame, this project is undoubtedly incredible and is part of a very important web functionality for all of us

**Comment by oliviertassinari** [comment]
The author might have lost interest in the project after Material-UI released its own rich table component. There are forks and similar projects, so I think that developers can find interesting alternatives.
