### ISSUE TITLE
Is there a way to add debounce for the search?

### ISSUE THREAD

**Issue by Jak3b0** [mbrn/material-table#282]
Hi,

I would like to add some debouncing for the search because this operation can be costly. Debouncing would allow the logic to run only when the user is not typing anymore.

Is there something built in already for this?

Thank you!

**Comment by mbrn** [comment]
Hi @Jak3b0 ,

For large data sets debounce could be effective. I will consider this feature for next releases.

**Comment by Jak3b0** [comment]
Great! Glad to hear that :)

Do you have an ETA for next release?

**Comment by mbrn** [comment]
Actually no. But i am planning to publish a release for this week

**Comment by Jak3b0** [comment]
In the meantime, do you think there might be a way to work around it?

**Comment by mbrn** [comment]
I think you wont need a debounce. Because today i started to implement remoteData feature that covers all events for server side data management. I will add a debounce to search when remoteData feature is in use. 

So just wait a few days to publish it. #64

**Comment by mbrn** [comment]
I added debounce to search. You can download 1.21.0

**Comment by Jak3b0** [comment]
Great, thanks!

Is there anything to set in order to have the debounce active?

**Comment by mbrn** [comment]
Yes it work for 200ms by default. We can add a options to set it later.

**Comment by Jak3b0** [comment]
Yeah, I had to flush my node_modules folder to have the new version. The debounce is working now.

I've noticed though that when you type in the search field, the text is sometime not rendered right away giving the impression that the grid is laggy. This was not the case with the previous version. Are you able to reproduce on your end?

Thank you by the way to have added this :)

**Comment by mbrn** [comment]
Ok i will check it.

**Comment by Jak3b0** [comment]
I just tested with a production build and, unless I type like crazy, the
speed is good. Sorry about that. 🙂

Jacques

**Comment by mbrn** [comment]
:) I will add a options to change debounce period. Its 200ms in default. If you are a crazy you can change it as 100 or 50ms:)

**Comment by mbrn** [comment]
This is done with v1.22.0
