### ISSUE TITLE
Lookup filter doesn't apply ellipses when adding multiple values

### ISSUE THREAD

**Issue by pedrohenriiz** [mbrn/material-table#2822]
I have a table with a lookup filter to let the user check which types of values they want to see, but they can filter by multiples. What is happening is that the lookup filter isn't adding the ellipses (...) when the lookup has many values, which leads to a overflow.

Here it's possible to see what's going on:
![image](https://user-images.githubusercontent.com/56472003/110988095-da6a0100-834e-11eb-9dc2-d2ac4565d733.png)

The status column is wider than needed.

Searching through the docs, both on material-table and material-ui, I couldn't find anything that I can use to change this behaviour, but when looking on some examples on material-ui, I could see that when you add multiples values, an ellipse appears.

Here is the link to the documentation to see the material ui example:  [Example](https://material-ui.com/components/selects/)
To test, just go to the Multiple Select section and add some values to name select

An image to see what I'm trying to accomplish.
![image](https://user-images.githubusercontent.com/56472003/110988593-827fca00-834f-11eb-8dc3-cf455ce541f3.png)

There is something that I can do to add this ellipses when adding multiple values? Thanks.

**Comment by osvaldokalvaitir** [comment]
I need that too!
