### ISSUE TITLE
Styling - column.headerStyle and column.cellStyle not working

### ISSUE THREAD

**Issue by izidorio** [mbrn/material-table#2823]
# Guidelines

~/material-table/dist/components/m-table-header.js
#97 width: width,
```
var style = (0, _objectSpread2.default)({}, _this.props.headerStyle, columnDef.headerStyle, {
  boxSizing: "border-box",
  width: width,
  maxWidth: columnDef.maxWidth,
  minWidth: columnDef.minWidth
});
```
~/material-table/dist/components/m-table-cell.js
#76 width: width,
```
var cellStyle = {
  color: "inherit",
  width: width,
  maxWidth: _this.props.columnDef.maxWidth,
  minWidth: _this.props.columnDef.minWidth,
  boxSizing: "border-box",
  fontSize: "inherit",
  fontFamily: "inherit",
  fontWeight: "inherit"
};
```
- #### Please include a demo of the issue/behavior/question you have
code 
````
  const columns = [
    {
      title: '#',
      field: 'order',
      headerStyle: { backgroundColor: '#039be5', width: 70, maxWidth: 70 },
      cellStyle: { width: 70, maxWidth: 70  },
    },
    { title: 'Sigla', field: 'initials' },
    { title: 'Nome', field: 'name' },
  ];
````
<img width="1247" alt="Screen Shot 2021-03-12 at 19 54 12" src="https://user-images.githubusercontent.com/6155952/111007062-bcab9480-836c-11eb-8ea7-b287d3ec1833.png">

- #### Please try to be as detailed as possible

I don't discover the problem, but when comment lines #97 `width: width,` in file `m-table-header.js` and #76 `width: width`, in file `m-table-cell.js` this problem is resolved. Its props width and maxWidth are repassade

**Describe the bug**
I try to change the width column, but not working. I use this code
```
const columns = [
    {
      title: '#',
      field: 'order',
      headerStyle: {
        backgroundColor: '#039be5',
        width: 70,
        maxWidth: 70,
      },
      cellStyle: {
        width: 70,
        maxWidth: 70,
      },
    },
    { title: 'Sigla', field: 'initials' },
    { title: 'Nome', field: 'name' },
  ];
```
Background Color is working.

**Desktop (please complete the following information):**

- OS: iOS
- Browser: chrome

**Comment by fbegue** [comment]
yeah the width has been garbage for me here.
I instead reverted from 1.69.3 => 1.69.1 and used the column `width` (which is broken beyond 1.69.1)
