### ISSUE TITLE
DataGrid Checkbox selection slow

### ISSUE THREAD

**Issue by luizabentivoglio** [mbrn/material-table#2824]
I'm handling a simple DataGrid with 12 colums and 7 rows.
It seems that when I select either each rows or one row there is one second of delay to show the rows selected.
I've already read the same issue with Table and I'm wondering if you are facing this problem as well.

Just to be sure, here the code that I use:

`return (
    <ThemeProvider theme={theme}>
      <div style={{ height: 520, width: "100%" }}>    
      <DataGrid
          rows={rows} 
          columns={columns}
          checkboxSelection
        />
      </div>     
    </ThemeProvider>    
  )`

**Comment by Kraviecc** [comment]
+1 on that. I'm using an older version of the table and I'm also facing performance issues while selecting checkboxes.

I bet that it has to do with rerenders.

**Comment by luizabentivoglio** [comment]
Hi Michael, at the end I decided to use react-bootstrap-table2 as the table library and material-ui for other things like the navbar or autocomplete. RBT has a higher level of customization and with super performance. Now i have no more problems ;)

[Luiza Bentivoglio - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=y1fqg)	[y1fqg]
