### ISSUE TITLE
Filter on a column with multiple values

### ISSUE THREAD

**Issue by yashSangai** [mbrn/material-table#2827]
I was creating a custom filter component for a column where the user can search on the list of values for that particular column, select it(Can be multiple too), and filter it. I created the component but it is throwing an error on it. 

Can you please help? I am stuck on this for a long time.

  - #### [CodeSandbox](https://codesandbox.io/s/recursing-greider-qe9s2)

**Comment by mfmsajidh** [comment]
This is a bug
@yashSangai Please change the label to "bug".

I tried it use a simple Select component from material-ui... The same issue comes again

![image](https://user-images.githubusercontent.com/36571307/111443283-3a85ec00-872f-11eb-8e3c-84594d5cab5a.png)

**Comment by yashSangai** [comment]
For an array of values too, it fails(If we support multiple filter values). @mfmsajidh

**Comment by yashSangai** [comment]
@mbrn Please change the label to "bug"
