### ISSUE TITLE
How can I listen for sort changes or tap into the onClick event for sorting by column headers?

### ISSUE THREAD

**Issue by claytongroth** [mbrn/material-table#2838]
### The Problem

I am having a difficult time finding a good strategy for doing the following:

- Whenever the table's `orderBy` and `orderDirection` states change, update some state outside **Material-Table** to save that  ( I am using redux-persist ).  let's say `myOrderBy` and `myOrderDirection` are my values I'm storing for easy reference.
- When the component loads or the stored values update, reset the table's `orderBy` and `orderDirection` states according to `myOrderBy` and `myOrderDirection`.
- This way, I could leave and come back, or refresh the page, and preserve my sort order from before.
- I am working with pretty big datasets so minimizing full reload of the component is ideal.

Here is a sandbox with _roughly what I am trying to set up_:
https://codesandbox.io/s/material-table-starter-template-forked-yj0x8

### What I've tried:

- I tried giving the material-table's data a custom component for `title` with an click handler that will update my state. Then using **Material-Table**'s `defaultSort` property to tell table which column to sort by. The issue here is that the actual state of the table is not caught up with `my` state because I am only able to look at the ref and it is tricky to listen for changes in the `tableRef.current.state` object with React ref.
```javascript

const myTableRef = React.createRef();

// columnPrefs would be in props, coming from Redux
const titleElement = (titleString, field) => (
    <div
      onClick={() => {
        // set the redux store
        setUserColumnPreferences({ field, sort: columnPrefs.sort === 'desc' ? 'asc' : 'desc' });
        // I cannot compare Refs here because the ref is not actually updated.
      }}
    >
      {titleString}
    </div>
  );
const [columns, setColumns] = useState([
  { title: titleElement('id', 'id'), field: "id" },
  { title: titleElement('word', 'word'), field: "word" }
]);

  useEffect(() => {
    // Take props and update table data...
    if (columnPrefs) {
      setColumns(
        columns.map((col) => {
          if (col.field === columnPrefs.field) {
            return { ...col, defaultSort: columnPrefs.sort };
          }
          // delete the old default sort...
          return { ...col, defaultSort: null };
        })
      )
    }
  }, [columnPrefs]);

... 
 <MaterialTable
      tableRef={myTableRef}
      data={data}
      columns={columns}
      title="Starter Template"
      icons={tableIcons}
    />
```
The issue with the above is that the standard click handlers for the column titles then become a bit weird (they get stuck on asc or desc inconsistently) and the saved state for `myOrderBy` and `myOrderDirection` are one step behind that of the actual table. 

Obviously, going straight off of `myTableRef.current.state.orderBy` and `myTableRef.current.state.orderDirection` would do the trick, but I am not sure how to "WATCH" these values and keep them in-step with my redux state.

Thanks!

**Comment by zoosm3** [comment]
@claytongroth onOrderChange might help.
https://material-table.com/#/docs/all-props
