### ISSUE TITLE
I Want to change the cell color when moving the mouse to the line.

### ISSUE THREAD

**Issue by quocbaondvn2000** [mbrn/material-table#284]

**Comment by mbrn** [comment]
I want to be sure. 

Your event will be onMouseEnter for whole row, then you will change the just one cell's color

am i right?

**Comment by quocbaondvn2000** [comment]
Yes, that's right
Can you give me a sample code

**Comment by RipFlight** [comment]
I've added this CSS and it did the trick!

[class^="MuiTableRow-root-"]:nth-child(n+2):hover{
    background-color: rgba(255, 192, 203, 0.726);
}
Any other recomendations, thank you.
