### ISSUE TITLE
Bug with exporting

### ISSUE THREAD

**Issue by Facinorous-420** [mbrn/material-table#2843]
**Describe the bug**
As requested, here is my issue :)
When I have set my page limit to a certain amount ofrows, and try to export all data in the table it only exports what is in the current page.

**To Reproduce**

My code:
https://p.bss.nz/elalekihub.ts

**Expected behavior**
I expect it to export whatever data is in the table at the time, not just the current page viewed. If I use the search bar to search for a specific thing, it will export whatever is in that search.

**Screenshots**
Here is a gif of it happening with my table:
https://bss.nz/i/04-02-2021-S4TDlYk3If.gif

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Firefox
- Version: 87

**Comment by ljpedroso** [comment]
@Facinorous-420 You have to set exportAllData to true under options property. Below is an example.

````javascript
data={rows}
title="Logs"
options={{
  pageSize: 5,
  showTitle: true,
  filtering: false,
  search: false,
  sorting: false,
  actionsColumnIndex: -1,
  exportButton: true,
  exportAllData: true,
  exportFileName: "Logs",
  searchFieldAlignment: "left",
}}
````

![Screen Shot 2021-04-19 at 10 25 47 AM](https://user-images.githubusercontent.com/2606481/115253002-f903aa80-a0f9-11eb-99af-e79dedd73965.png)


https://material-table.com/#/docs/all-props

**Comment by ljpedroso** [comment]
@mbrn I think this issue can be closed.
