### ISSUE TITLE
Detail panel is collapsing when fetching remote data

### ISSUE THREAD

**Issue by sanichka96** [mbrn/material-table#2846]
Hi!
I'm having issue with a detail panel feature. What I need is fetching data from server on a row expansion and show the data in a detail panel. 
Current behavior looks like this:
- I click on the arrow next to the row to see details,
- if row details info exists in redux store, I fetch it directly from there, if not - fetch data from server and strore them in redux,
- in the first case, the data is shown immediately, but in the second one, I have to click on the arrow twice: first, I see an empty detail panel, which collapses after props are changed, cause I save data to redux and want to show it in the panel, and second step - I click and see the data.

**Question**: how can I prevent detail panel collapsing while wainting for response from server? 

**Method which is responsible for showing details:**

```
const showAuditDetails = id => {
    const auditLogDetails = auditLogs.find(log => log.id === id);

    if (!auditLogDetails) {
      fetchAuditDetails(id);
    }

    if (auditLogDetails) {
      return (
        <div>
          // row details
        </div>
      );
    }
  };
```

**Method, which is responsible for fetching data from server and saving it to redux store:**

```
const fetchAuditDetails = async id => {
    await apiUtils.fetchAuditLogDetails(id)
      .then(response => {
        saveAuditLogDetails(response.data);
      })
      .catch(e => eh.handleErrorResponse(e, props));
  };
```

P.S.: _auditLogs_ and _saveAuditLogDetails_ are one of the props of my component.

Thank you for any help and hints! :)

**Comment by ffeliks** [comment]
@sanichka96 did you end up finding a solution for this? I find myself in a similar situation? I would appreciate any tips on how you solved this.

**Comment by sanichka96** [comment]
@ffeliks Nope, I didn't. I'm no longer working in the project where this issue appeared =/
