### ISSUE TITLE
Glitch of disordered components on page loading

### ISSUE THREAD

**Issue by Maggie199** [mbrn/material-table#285]
**Describe the bug**
Material Table has a glitch of distorted components every time when it's being loading, which is very bad UX

**Expected behavior**
It should load smoothly

**Screenshots**
![loading](https://user-images.githubusercontent.com/5753379/53856983-5a537880-3f89-11e9-8229-fb67798e0fd8.gif)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Chrome
 - Version: 72.0

**Comment by mbrn** [comment]
Hi @Maggie199 ,

How did you load your icons. Did you add a link to your head in html

**Comment by Maggie199** [comment]
@mbrn Yes I did, I even tried to make a local copy of it and use the link in my head to see if it will load faster, but it didn't help :(

**Comment by mbrn** [comment]
I am not sure why it happens. Can you check your file load time from network tab.

**Comment by Maggie199** [comment]
@mbrn Looks like the css file is loaded after the main js file. Could it be the cause? Not sure why it only happens to me...

**Comment by mbrn** [comment]
It can be. which css loaded after main js. And can you share your html code.

**Comment by Maggie199** [comment]
@mbrn The html seems to be very large, and I'm not sure what's the best way to share it 😅

**Comment by mbrn** [comment]
You can check your all css and font file to be load on head section. And add main.js script to end of body.

**Comment by Maggie199** [comment]
@mbrn Looks like we use `react-helmet-async` to load assets in head, do you think that could cause the issue here?

**Comment by mbrn** [comment]
I am not sure how it works. But it's name contains async :)

**Comment by amit-ametek** [comment]
Hi, Were you able to able to find any solution for this issue?. I am facing the same problem. Whole page gets distorted on first load. If I go to another page and then comes back, the issue is resolved.

**Comment by mbrn** [comment]
Hi @amit-ametek , do you use react-helmet-async ?

**Comment by amit-ametek** [comment]
Hi @mbrn , no I am not using react-helmet-async. But yes, I am loading my components asynchronously. I have created my own component to do this i.e. to load other components asynchronously.

**Comment by amit-ametek** [comment]
Forgot to add one important point: The issue occurs only in deployed version. Locally, table loads perfectly.

**Comment by mbrn** [comment]
@amit-ametek ,

Do you use nextjs or razzle or something like them?
