### ISSUE TITLE
Support for right to left

### ISSUE THREAD

**Issue by pouryapb** [mbrn/material-table#2852]
for a right to left website it has a lot of problems that some can be fixed with an unnecessary solution. for example the icon in GroupRow has a rotating style, in my case I just needed to put a - sign in that style so it rotates the right way and I couldn't find a way but copying the whole component and changing that one character for it.
also some things like fixed columns don't work in rtl.
I'm using the way documented in material ui website for making my site right to left.

**Comment by amin750** [comment]
you can set style property to make table rtl

example:
`
                   <MaterialTable
                            style={{
                              maxHeight: "400px",
                              overflowY: "scroll",
                              direction: "rtl"
                            }}
                            paging={false}
                            ...
`
