### ISSUE TITLE
show grouped column in rows in material-table

### ISSUE THREAD

**Issue by payandeh** [mbrn/material-table#2857]
**Summary:**

in material-table when when you try to group by data by a field , that column not display as a column any more ‪‪

**Step to Reproduce:**

- create table

```
<MaterialTable
  title="Default Grouped Field Preview"
  columns={[
    { title: 'Name', field: 'name', defaultGroupOrder: 0 },
    { title: 'Surname', field: 'surname' },
    { title: 'Birth Year', field: 'birthYear', type: 'numeric' },
    {
      title: 'Birth Place',
      field: 'birthCity',
      lookup: { 34: 'İstanbul', 63: 'Şanlıurfa' },
    },
  ]}
  data={[
    { name: 'Mehmet', surname: 'Baran', birthYear: 1987, birthCity: 63 },
    { name: 'Zerya Betül', surname: 'Baran', birthYear: 2017, birthCity: 34 },
  ]}        
  options={{
    grouping: true
  }}
/>
```

- group by with a field

`{ title: 'Name', field: 'name', defaultGroupOrder: 0 }‪
`

**Actual Result:**

column "Name" not display as a column any more

**Expected Result:**

display column "Name" as it was before grouping and

**Comment by yemmieh** [comment]
Anyone got a fix for this? I am having same issue

**Comment by bferrell16** [comment]
Having the same issue
