### ISSUE TITLE
how can i make a column that has two columns inside it?

### ISSUE THREAD

**Issue by Flavio27** [mbrn/material-table#2859]
Hello Everyone,
Could someone please tell me how can i make a column that has two columns inside it? I'm trying to create one like this:
![image](https://user-images.githubusercontent.com/28609172/115048560-13e2de80-9eb0-11eb-9827-de3b5536b32f.png)

But I'm not understanding what type of field I should use in the column to make
My table:
![image](https://user-images.githubusercontent.com/28609172/115048908-7cca5680-9eb0-11eb-8e65-9e64364e0c58.png)
And code:

>   const columns = [
>       { title: "January", field: "jan", align: "center"},
>       { title: "February", field: "feb"},
>       { title: "March", field: "mar"},
>       { title: "April", field: "apr"},
>       { title: "May", field: "may"},
>       { title: "June", field: "jun"},
>       { title: "July", field: "jul"},
>       { title: "August", field: "aug"},
>       { title: "September", field: "sep"},
>       { title: "October", field: "oct"},
>       { title: "November", field: "nov"},
>       { title: "December", field: "dec"}   
>   ];

**Comment by indicava** [comment]
I just defined the top-level columns for the “columns” property and then used the “render” property of of each column to render custom “split” columns.
