### ISSUE TITLE
How to customize actions buttons in editable table

### ISSUE THREAD

**Issue by kien-pham** [mbrn/material-table#2864]
Hello,

I'm using editable table and I also want to customize edit/delete buttons like this
<img width="140" alt="Screen Shot 2021-04-22 at 11 02 15 PM" src="https://user-images.githubusercontent.com/43236511/115746773-d0600700-a3be-11eb-8ec1-433a19856df3.png">

I search over the internet but haven't seen the answer. If I use component action, how do I define edit/delete action?
```
editable={{...}}
components={{
Action: props => (
<> 
// how to add custom edit/delete here?
</>
)
}}
```

Thank you

**Comment by zoosm3** [comment]
@kien-pham Have you ever checked Action Overriding Example?
https://material-table.com/#/docs/features/component-overriding
