### ISSUE TITLE
When fixed columns will be available?

### ISSUE THREAD

**Issue by trigerviktoriia** [mbrn/material-table#2868]
Will the fixed columns be available soon? If yes, when?)
Now the error is: «You can not use fixed columns feature with detail panels, treedata or grouping for now».
Thank you in advance)

**Comment by OnkelTem** [comment]
@trigerviktoriia Note also that widths get broken in 1.69.3. Try 1.69.1 first. Tho it doesn't seem to be related to your question directly.

**Comment by dlopatin-v** [comment]
> @trigerviktoriia Note also that widths get broken since 1.69.2. Try 1.69.1 first. Tho it doesn't seem to be related to your question directly.

When it will be fixed, I need to set width to each column, but can I so easyly downgrade package? (I think it is possible that I loose another functionaluty)
