### ISSUE TITLE
Issue with multi select in version 1.20.0

### ISSUE THREAD

**Issue by vijthang61** [mbrn/material-table#287]
**Describe the bug**

When I do multi select in tree data, if parent row is selected it doesnt select the child row automatically, also when I check all the individual rows it doesnt reflect in select at the column header.

![image](https://user-images.githubusercontent.com/47169215/53954016-f355d100-40fa-11e9-942a-c29ec03d536b.png)

**Comment by mbrn** [comment]
I will resolve this asap.

**Comment by mbrn** [comment]
This is done with 1.23.6
