### ISSUE TITLE
How to disable "seconds" in time format?

### ISSUE THREAD

**Issue by patricklau12** [mbrn/material-table#2870]
Hi everyone,

For example: { title: 'Adjusted Clock-in', field: 'adj_clockin', type: 'datetime'}

It would show the date and time with YYYY/MM/dd HH:mm:ss.

How to remove the "ss", I don't want the table becomes too complex.

Thanks.

**Comment by zoosm3** [comment]
@patricklau12 How about using render method to format and show datetime?
https://material-table.com/#/docs/features/custom-column-rendering
