### ISSUE TITLE
Material table not install with react 17.0.2

### ISSUE THREAD

**Issue by yangoff** [mbrn/material-table#2874]
using --force Recommended protections disabled.
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: slw-aplicacao@0.1.0
npm WARN Found: react@17.0.2
npm WARN node_modules/react
npm WARN   react@"^17.0.0" from the root project
npm WARN   3 more (material-table, @material-ui/core, react-dom)

**Comment by OnkelTem** [comment]
So you cannot use it? Well, you maybe don't this yet, but you've actually had some luck man.

**Comment by yangoff** [comment]
why? lol this soo bad?

**Comment by PathToLife** [comment]
https://github.com/mbrn/material-table/pull/2797

It would have thought this would fix it?

**Comment by PathToLife** [comment]
https://github.com/mbrn/material-table/pull/2797#issuecomment-840747258

Commented on what I think is causing it, TLDR; I think `@material-ui/pickers@"3.2.2"` only works with react 16

**Comment by lakshay17244** [comment]
Any updates on this? Need to use material table with a React 17 project. Can someone fix the peer dependency on @material-ui/pickers@"3.2.2"

**Comment by DanielDerma** [comment]
17.0.2 where, with npm don't work and with yarn is all of bugged

**Comment by Downchuck** [comment]
`react-beautiful-dnd` could use a bump as well.

**Comment by oander11** [comment]
Having the same issue, not installable on 17.0.2, caused by dependency on @material-ui/pickers@"3.2.2".

**Comment by Flam3rboy** [comment]
same

**Comment by IcarusHU** [comment]
+1 for this, already using in a React 17 project, cannot correctly npm update, in case of force install or force audit fix, material-table messes up own versions crashing the whole applicatoin, unbelievable... I advertise this plugin to my colleagues as one of the bests with no issue at all, and then, out of the blue a major blocker issue for months now... don't even use picker in mattable, Please fix this ASAP

**Comment by Flam3rboy** [comment]
@IcarusHU I just used this maintained fork instead: https://material-table-core.com/
