### ISSUE TITLE
[Styling[[Pagination Row] Can't override styling

### ISSUE THREAD

**Issue by enzo-phinx** [mbrn/material-table#2882]
- #### Please include a demo of the issue/behavior/question you have
 
![image](https://user-images.githubusercontent.com/60398463/117526214-01812f80-af9a-11eb-8779-85a6a9c2cb22.png)

- #### Please try to be as detailed as possible

Cant modify the styling of the number of pages 

**Describe the bug**
 Even though I'm setting the props according to the docs, can't override the styling of the filtering row. 
 ```
  <MaterialTable
        isLoading={isLoading}
        data={rows}
        columns={columns}
        options={{ filterRowStyle: { background: "red" } }}
      />
 ```

**Comment by bferrell16** [comment]
Unsure how much this will help, I was trying to figure styling pagination out for a bit and found MuiThemeProvider to work. In this example I used it to set the font size, but you could change the background color in a similar way.

```
import { createMuiTheme, MuiThemeProvider } from '@material-ui/core/styles'

const theme = createMuiTheme({
  overrides: {
        MuiTypography: {
          caption: {
            fontSize: '1.5rem'
          }
  }
})
```
then
```
<MuiThemeProvider theme={theme}>
        <MaterialTable />
</MuiThemeProvider>
```

Although, this will style anything with class `MuiTypography-caption`, have to find a way to narrow it down to that one.
