### ISSUE TITLE
Amount of rows not initialized correctly and blocked when overriding Pagination

### ISSUE THREAD

**Issue by SeanMengis** [mbrn/material-table#2888]
**Situation**
I fetch log information from the backend and want to display them in the material-table that works based on MaterialUI. Since there might be a lot of data I only fetch a limited amount at once and refetch every time I do a page navigation.

**Problem one**
The table gets initialized with only 5 rows and the first 5 logs. When navigating trough the pages I always have these 5 first logs. Also changing the amount of rows does not seem to work.

**Problem two**
In my handleChangeRowsPerPage() I'm calling setSearchCriteria but it always uses the previous value instead of the new one. Does that have something to do with the fact that setState is asynchronous? Any lead on how I can have the actual value?

**Other info**

- I use Typescript
- I tried using options={{pageSize: searchCriteria.rowsPerPage}} which correctly displays the amount of rows but does not solve the problem where I always have the first set of logs. And I think it is intended that I can also set the number of rows in components={{Pagination: Stuff}}
- I found a couple of similar posts on stackoverflow which sadly did not help. So I'm counting on you guys ;-) Thanks!

**Code**
Simplified version: https://codesandbox.io/s/eloquent-gauss-3p2ev?file=/src/App.tsx

```
import React, { useState } from "react";

import { TablePagination } from "@material-ui/core";

import BaseTable from "./BaseTable";

interface DataModel {
  date: string;
  message: number;
}

export default function ReportsPage() {
  const columns = [
    {
      field: "date",
      title: "Date",
      editable: "never"
    },
    {
      field: "message",
      title: "Message",
      editable: "never"
    }
  ];

  const data: DataModel[] = generateDummyLogEvents();

  const [searchCriteria, setSearchCriteria] = useState({
    rowsPerPage: 25,
    currentPage: 0,
    size: data.length
  });

  function generateDummyLogEvents() {
    const dataArray: DataModel[] = [{ date: "01.01.1970", message: 0 }];
    for (let i = 1; i < 500; i++) {
      if (i % 3 === 0) {
        dataArray.push({ date: "01.01.1970", message: i });
      } else if (i % 7 === 0) {
        dataArray.push({ date: "11.09.2000", message: i });
      } else {
        dataArray.push({ date: "24.12.2021", message: i });
      }
    }
    return dataArray;
  }

  function handlePageChange(event: unknown, newPage: number) {
    setSearchCriteria((prevState) => ({
      ...prevState,
      currentPage: newPage
    }));
    console.log("Current Page: " + searchCriteria.currentPage)
  }

  function handleChangeRowsPerPage(event: React.ChangeEvent<HTMLInputElement>) {
    console.log("Event value: " + parseInt(event.target.value, 10)); // logs the selected value
    setSearchCriteria((prevState) => ({
      ...prevState,
      rowsPerPage: parseInt(event.target.value, 10)
    }));
    console.log("Value that has been set: " + searchCriteria.rowsPerPage); // logs the previous value
  }

  return (
    <div>
      <BaseTable // MaterialTable with the icons already included
        columns={columns}
        data={data}
        components={{
          Pagination: (props: any) => {
            return (
              <TablePagination
                {...props}
                count={searchCriteria.size}
                page={searchCriteria.currentPage}
                onChangePage={handlePageChange}
                rowsPerPage={searchCriteria.rowsPerPage}
                rowsPerPageOptions={[10, 25, 50, 100]}
                onChangeRowsPerPage={handleChangeRowsPerPage}
              />
            );
          }
        }}
      />
    </div>
  );
}
```

**Comment by swaechter** [comment]
@SeanMengis (Coworker of Sean): Can you post your solution here too so other people can benefit from it and close the issue? Best Simon

**Comment by SeanMengis** [comment]
Sure! The solution we have for now works but doesn't exactly solve the problem where we cannot correctly override the material-table "Pagination" component. So I disabled the material-table pagination and used the separate Material-UI pagination component.

Set the options to something like this: 
`options={{
     pageSize: searchCriteria.size,
     pageSizeOptions: [10, 25, 50, 100],
     paging: false
}}`

and then use the Material-UI component:

```
<TablePagination
      count={totalCount}
      page={searchCriteria.currentPage}
      onChangePage={handlePageChange}
      rowsPerPage={searchCriteria.rowsPerPage}
      rowsPerPageOptions={[10, 25, 50, 100]}
      onChangeRowsPerPage={handleRowsPerPageChange}
 />
```


The API for the TablePagination can be found here: https://material-ui.com/api/table-pagination/
