### ISSUE TITLE
Vunerability in jspdf dependency

### ISSUE THREAD

**Issue by vikramarka** [mbrn/material-table#2890]
Hi,
npm audit showing critical vulnerability for jspdf library and the vulnerability is fixed in 2.3.1
Can  you please bump up it version?

**Comment by alexwenzel** [comment]
+1

**Comment by philbert440** [comment]
+1 
https://www.npmjs.com/advisories/1709

**Comment by aechurch14714** [comment]
+1

**Comment by b3ni** [comment]
+1

**Comment by b3ni** [comment]
+1
