### ISSUE TITLE
Detail panel icon click and row click problem 

### ISSUE THREAD

**Issue by appukuttan-shailesh** [mbrn/material-table#2894]
I find that clicking on the detail panel icon does not trigger the row click function.
As example, slightly modifying the 3rd example at [](https://material-table.com/#/docs/features/detail-panel) to :
```
onRowClick={(event, rowData, togglePanel) => {
        console.log("Hello")
        togglePanel();
      }}
```

When I click on the 'expand/collapse' button the console.log statement **does not** get executed.
But clicking anywhere else on the row executes the above.

I am not sure if this is the expected behavior. If so, can anyone guide me on how I can make the icon click and the row click do the same actions?

**Comment by ganeshkokare** [comment]
same problem i faced

**Comment by MinaIsaac1994** [comment]
Has anyone found a solution to this?

**Comment by appukuttan-shailesh** [comment]
I moved to a fork of this repo that is still maintained:
https://github.com/material-table-core/core
