### ISSUE TITLE
Style recalculation on render takes exponentially more time than previous render

### ISSUE THREAD

**Issue by ChapterSevenSeeds** [mbrn/material-table#2899]
Given the latest version of React and MaterialTable, take the following code:

`<MaterialTable title="Preview"
        columns={previewColumns}
        data={data}
        options={{
            actionsColumnIndex: -1,
            pageSize: 10
        }}
  />`

The 'data' variable is declared like so:

`const [data, setData] = useState([]);`

The 'previewColumns' variable is declared as an array of objects each containing the properties 'title' and 'field'. 

Now, every time I call 'setData' with a new array of objects returned from an HTTP request, the styles for each of the table cells get longer and longer. Please see the following image:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/63123355/119895662-47774680-befb-11eb-912e-0cf4de25052f.png)

It seems like this issue only manifests itself if the data set that I pass to 'setData' is either the same size or the the exact same set of data. Either way, I had to downgrade to version 1.62.0 to prevent this from happening.

**Comment by aaronchua13** [comment]
having the same issue.

**Comment by ChapterSevenSeeds** [comment]
I just want to add that this does not happen on versions earlier than 1.69.0.

**Comment by mikroware** [comment]
Same as #2825, does indeed not seem to happen before 1.69.0. We downgraded to 1.68.0 for now.
