### ISSUE TITLE
Add inline editing feature

### ISSUE THREAD

**Issue by mbrn** [mbrn/material-table#29]
Add inline editing feature

**Comment by jakeleventhal** [comment]
Any update on when this will be added?

**Comment by mbrn** [comment]
@jakeleventhal 

I can't promise any date to close these issues. But i will do all them as soon as possible.

**Comment by jakeleventhal** [comment]
I think that what would make this great would be if you could edit by clicking on a cell rather than editing an entire row at once

**Comment by mbrn** [comment]
I aggre with your opinion. When user click on the edit button, the row's data would replace with edit components and a submit button.

**Comment by jakeleventhal** [comment]
I feel like it’d be cleaner to just have the “submit” button not exist. Instead, you could specify an onBlur which would submit after clicking away or pressing the enter key

**Comment by mbrn** [comment]
Maybe, i will think about it

**Comment by jakeleventhal** [comment]
Something that needs to be in this issue is the ability to have a callback function.

so that the user can write code after the cell has been edited.

**Comment by urirahimi** [comment]
Hi @mbrn is there any update on this feature?

**Comment by mbrn** [comment]
Hi @urirahimi ,

Firstly i will resolve #135. After resolving #135 i can look at this.

**Comment by mbrn** [comment]
This is done with 1.23.0
