### ISSUE TITLE
Table Supports Density and Can Be Made "Dense"

### ISSUE THREAD

**Issue by brianpdev** [mbrn/material-table#290]
The table supports MaterialUI Density so that it is easy to specify that the table is "Dense". Less white space in the table, preferred for desktop usage.

**Comment by mbrn** [comment]
Hi @brianpdev ,

I tried something about this. But we use buttons, checkboxes and so. So it could broke some design if we apply this. So won't apply dense. Sorry

**Comment by stemarf50** [comment]
Hey @mbrn, I understand that certain components can break on dense. But can you still please support such that dense can be applied if we do **not** use checkboxes and buttons in the table?

**Comment by mbrn** [comment]
of course. I will try to do it.

**Comment by stemarf50** [comment]
Thank you very much. I've chosen to use this for my project and this option will really help :)

**Comment by stemarf50** [comment]
Hey @mbrn, any update on this one?

**Comment by mbrn** [comment]
@stemarf50 unfortunately. I am working on new documentation nowadays.

**Comment by masbaehr** [comment]
I was also looking forward for this feature. I propose a VERY UGLY workaround, but probably better than nothing. Note that this will not interfere with other pages, so it is better than importing a *.css file, as this would stay in DOM until you reload the page. It could probably be made even better by adding a custom class to make only certain tables in the same page dense. (Adjust padding value to your liking)

```javascript
const specialCSS = "<style>.MuiTableCell-root.MuiTableCell-body.MuiTableCell-alignLeft { padding: 0 !important } .MuiTableCell-root.MuiTableCell-body.MuiTableCell-paddingNone .MuiIconButton-root { padding: 0 !important }</style>"
```
```jsx
<div dangerouslySetInnerHTML={{__html: specialCSS}}></div>
```

Result:

![image](https://user-images.githubusercontent.com/38694044/59715151-867ec680-9213-11e9-8bd1-b0360a842848.png)

**Comment by OnkelTem** [comment]
Also look forward to seeing it working.

**Comment by flavioribeiro** [comment]
+1

**Comment by atinyakov** [comment]
+1

**Comment by gabizz** [comment]
I have stumbled upon the same issue today... i 've solved it somehow, not 100% material way, but it serves my purpose... adding to the MaterialTable component the following options: 

                options={{
                    cellStyle: { padding: '0.3em'},
                    headerStyle: { padding: '0.3em'},
                  }}
