### ISSUE TITLE
Bulk Edit onclick event is very slow

### ISSUE THREAD

**Issue by PATTANPARVIN** [mbrn/material-table#2908]
I am using  Bulk update with **V1.69.3**,

- I'm handling 200 rows with dynamic columns of different types of fields(Select field(single & multi), User picker(single & multi), Text field, Text Area, Date and Time Picker...)

**Describe the bug**
- When clicks on Bulk Update button it is taking around 15 seconds to show the edit window.
- While clicks on Cancel button then also it's taking time
- why rendering is taking time when data's are bulk and how to reduce it

`         onBulkUpdate: (changes) => new Promise((resolve, reject) => {
                      this.setState({
                        isLoading: true,
                      });
                      try {
                        setTimeout(() => {
                          const isValidationPassed = this.submitBulkFieldValues(changes);
                          if (!isValidationPassed) {
                            reject();
                          } else {
                            resolve();
                          }
                        }, 1000);
                      } catch (err) {
                        reject(err);
                      }
                    }),`

**Expected behavior**
 1. Need to make it fast UI
 2. I should able to show the loader when button is clicked

**Screenshots**
![Bulk-Edit1](https://user-images.githubusercontent.com/53428566/121313858-6e367380-c924-11eb-9fbf-0bb7e0b40c80.PNG)
![image](https://user-images.githubusercontent.com/53428566/121314066-a1790280-c924-11eb-889c-cc36d1dd7fcd.png)

https://user-images.githubusercontent.com/53428566/121363573-b40b3000-c954-11eb-8be9-f1c1b77c3916.mp4

**Comment by PATTANPARVIN** [comment]
Is there any possibility for bulk edit with custom button, please anyone can help.

**Comment by Rambanam** [comment]
+1

**Comment by Michael-Hanley** [comment]
+1
