### ISSUE TITLE
Changing style (column width, cell width, etc.) 

### ISSUE THREAD

**Issue by brittanywang** [mbrn/material-table#291]
- [x] Is there another way to change the column/cell styles? 
I tried what was suggested in issue (#261) as in:
```
columns=
{ title: 'Name', field: 'name',
     cellStyle: {
       width: 20,
       maxWidth: 20
     },
     headerStyle: {
       width:20,
       maxWidth: 20
     }
    },
```
but there are no changes to the width of the columns. I also tried changing the width and maxWidth:1 to see if there were any changes and there weren't: 
<img width="1050" alt="screen shot 2019-03-07 at 1 33 47 pm" src="https://user-images.githubusercontent.com/35832643/53990745-d068f400-40dd-11e9-8311-cecb1efc4ad7.png">

- [x] After fixing the size of the column, is there a way to not make the top chart expanded with the Detail Panel is shown?
<img width="1042" alt="screen shot 2019-03-07 at 1 45 35 pm" src="https://user-images.githubusercontent.com/35832643/53991451-7b2de200-40df-11e9-9e69-9ac216cf0429.png">

- [x] Is there a way to change the font for the data displayed (for consistency with my headers) as well? I tried doing:
```
data={[
        { cField: 'Subject', result: this.state.subject, headerStyle: { fontSize: 20}},
        { cField: 'Location', result: this.state.location, headerStyle: { fontSize: 20}}
]}
```

This is a pretty heavy post. Thank you in advance!

**Comment by mbrn** [comment]
Hi @brittanywang ,

I will check this case asap.

**Comment by timrchavez** [comment]
`cellStyle` works for me but `headerStyle` does not appear to be working. When I set `width: '100%'` in `headerStyle`, I expect it to apply `width: 100%` to the header for this column, but I do not believe that's happening.

**Comment by orestes22** [comment]
Hi, Im not sure if was fixed this, but Im using Material-Table version 1.24 

and it works for me. Maybe Im not understanding very well the doubt. (forgive me if that is the case)

Please try to change the style like this: 

headerStyle: {width: '50%', backgroundColor: '#ddd', height: 10, textAlign:'center'}

I beleive that only works with inline style, using JS for the style, 

I tried others way, and doesnt works, Im not sure way, I hope @mbrn can find the solutions.

I hope this comment help you

Best Regards

**Comment by ShawTim** [comment]
i face the same issue. setting width in `headerStyle` doesnt work for me. but `cellStyle` does.

**Comment by mbrn** [comment]
Actually, material-ui table components do not let to change width of columns. It set all columns' width automatically. But i will try to broke it with css.

**Comment by orestes22** [comment]
Hi, please check this in order to analyze why is working for me https://codesandbox.io/s/8y77w4yr40

Maybe you have to import this HOC from material-ui  to your class and wrap the class name at the end with that, like this:

import { withStyles } from "@material-ui/core/styles";
import stylepage from "stylepage";

class App extende React.Component
.
.
export default withI18next(["home", "common"])(withStyles(stylespage)(App ));

I hope this works now for you

But it will be nice it could be more easy to modify

Best Regards

**Comment by brittanywang** [comment]
I figured out how to address sub-issue 2...

- [x] (not having the top chart expanded with the Detail Panel is shown). 

It is entirely dependent on the data generated. One of my data fields happens to be really, really long so the width is adjusted accordingly. To fix this, I adjusted the css overflow. 

Hoping someone can find a way to 

- [ ]  change the font for the generated data

**Comment by mbrn** [comment]
@brittanywang 

You can change fonts with css too,

**Comment by symnetry** [comment]
i face the same issue, one of my data is so long
but can set cellstyle:{whiteSpace:'nowrap'}
and it works for me

**Comment by hasankhalid** [comment]
Is there anyway to perhaps change the padding properties in material ui's TableCell component? I want to decrease the width of the column which contains only a number but using cellStyle:{width: '75px'} won't work.

**Comment by ambr89** [comment]
Hi @hasankhalid to change padding size, I've set

`<MaterialTable
                    columns={[
                 
                        { title: 'Nome', field: 'name', cellStyle:{ padding: '5px'} }, // chage cell pading
                        { title: 'Valido ', field: 'isValid', cellStyle:{padding: '5px'} }
                    ]}
                    data={[
                               .... my data
                    ]}
                    title="My Title"
                    options={{
                        toolbar: false,
                        paging: false,
                        headerStyle:{backgroundColor:'red', padding: '5px'}, //change header padding
                        //cellStyle:{ padding: '5px'} here not work for me
                    }}
                />  `

Anyway, I've the problem that I can't set exactly width.

Have you solve this problem?

**Comment by mbrn** [comment]
Material-ui table components uses auto layout. So columns are being auto width. Currently i cant change them.

**Comment by ambr89** [comment]
Thanks!

**Comment by vladimanaev** [comment]
@mbrn, is there any plan on supporting column width adjustments?

When having table with many (10-15) columns and with text of a sentence the table becomes very ugly and not readable.

Thanks!

**Comment by FoxTM4** [comment]
You can place something like this in your css file and it will make long rows not ugly. 
Probably will have to change numbers but this works for me. 
.MuiTableCell-alignLeft{
    width: 10px;
    max-width: 32em;
    text-overflow: inherit;
    overflow: scroll;
}

**Comment by yanivfranco** [comment]
I encounter the same issue...as I have 1 digit columns and I want to set their width manually.
@mbrn Columns width sounds like a very basic feature for a table component...I am really surprised it is not supported. Is there any plan on adding this? 
Regardless, your work is awesome and this component is great!

**Comment by conerye** [comment]
Is it possible to change the width of the column that contains the detail panel expansion icon? I would like to set it to a set width, which is much narrower than it defaults to.

**Comment by bableves** [comment]
> Is it possible to change the width of the column that contains the detail panel expansion icon? I would like to set it to a set width, which is much narrower than it defaults to.

I need that too. Any update on this one?

**Comment by dalisalvador** [comment]
@mbrn @symnetry @vladimanaev  The best way I found to change the width of the columns and potentially style of the cells/cell is the following:

```
 columns={[
          ...state.columns.map(data => {
              return {
                field: data.field,
                title: data.title,
                render: rowData => 
                      (<div style={{minWidth: "250px"; paddingLeft: "10px"}}>  {rowData[data.field]}  </div>)
              };
            })
       ]}
```
Basically renders a div with the desired with, and autolayout will do the rest.
Hope that makes sense.

**Comment by midoalone** [comment]
@dalisalvador your solutions works perfect, thanks

**Comment by vnanaware** [comment]
How to make fixed( sticky header) in Material-table

**Comment by rakeshlanjewar** [comment]
To break word to next line please use 

` { title: "Remark", field: "remark", cellStyle: { wordBreak: 'break-all' } }`

It will automatically wrap the text to next line and does not break the styling. 

Tested on chrome 👍 with material-ui 🥇

**Comment by binyominc** [comment]
@dalisalvador thanks!  Just to extend this (probably already obvious), if you want to just change the width of one column, you can use that same approach

**Comment by thanhttb** [comment]
Just downgrade to 1.53.0. It works for me though.
`npm install material-table@1.53.0`

**Comment by cristiantobol** [comment]
Use `width` as attribute of `columns` instead of `cellStyle`.

```
columns={[
          { 
             width: 100,
             title: "Details", 
             field: "url", 
          },
          { title: "Name", field: "name" },

```

**Comment by anggar85** [comment]
> Use `width` as attribute of `columns` instead of `cellStyle`.
> 
> ```
> columns={[
>           { 
>              width: 100,
>              title: "Details", 
>              field: "url", 
>           },
>           { title: "Name", field: "name" },
> ]}
> ```

This solve the problem, thank you!

**Comment by ethanIncentify** [comment]
I've tried adding the width attribute to the columns array, but this isn't supported for typescript. Any workarounds for types?

**Comment by psykzz** [comment]
@ethanIncentify you could use `headerStyle: { width: <width> },`.
This worked for me.

**Comment by ethanIncentify** [comment]
@psykzz I've tried this, but this runs into the same problem. @cristiantobol 's solution works however typescript complains.

**Comment by juliosilvacwb** [comment]
I had the same problem, but I solved as

cellStyle: {
                width: 300,
                minWidth: 300
            },
            headerStyle: {
                width: 300,
                minWidth: 300
            },
...

If you want to down size use maxWidth, but if you want to up size use minWidth

**Comment by zacheryph** [comment]
I use the following in my column and it seems to work.  It's a bit of a _hidden_  solution cause `width` is not documented under the column properties.

```javascript
{ width: '1%', cellStyle: { whiteSpace: 'nowrap' }, ... }
```

**Comment by MoiseScalzo** [comment]
@mbrn please add width property as TypeScript prop.

**Comment by superjose** [comment]
@cristiantobol  solution works!! 

For TypeScript apply this hack:

```ts
columns={[
          { 
             ...(true && ({ width: 20 } as object)),
             title: "Details", 
             field: "url", 
          },
          { title: "Name", field: "name" },
]}
```
We use a spread operator inside an object to dynamically set it. We set it to true to always include it and cast it to `object` (`any` works).

**Comment by Nandiniyadavraj** [comment]
hello there,

I want to change the font color of my table's column called status where I m displaying 2 different status as PASSED(green) and FAILED(red).

I had done some research and tried in my code but none of working.
Here's the code I had been used:

       {
            dataField: 'Compliance.Status',
            text: 'Compliance status',
            cellStyle: params => params.value > "PASSED" ? {color: 'red'} : {color: 'green'}
        }

2nd way: 

      getTrProps = (state, rowInfo, instance) => {
        if (rowInfo) {
          return {
            style: {
              color: rowInfo.Compliance.Status > "PASSED" ? 'red' : 'green'
            }
          }
        }
      }
    render() {
      {
            dataField: 'Compliance.Status',
            text: 'Compliance status',
            getTrProps: this.getTrProps
        }
     }

Plz let me know if you have solution for this one. Thank you...!!

**Comment by dyaacov** [comment]
> cellStyle: {
> width: 300,
> minWidth: 300
> },
> headerStyle: {
> width: 300,
> minWidth: 300
> },

I always get minimum of 150, no matter what I try.
please help

**Comment by piekczyk** [comment]
the problem is also with enabling detailed panel and the same time have a hidden column. The calculation of width: calc(100% - 0px) / (number of columns) take into account also the hidden one which ruins styling.

**Comment by jttaynton** [comment]
In a previous version (1.56.1) the columns of the table would attempt to fill the space based on the data present.  In the latest version (1.57.2) it is calculating the width based on number of columns.  Is there any way to set this to work like the previous version?  That worked well for us.  The auto-width layout does not.  It looks like it is applying the width calc inline on each cell.  Is there any way to turn this off to the old way?

**Comment by nirawat** [comment]
so good with sample code.

{
        title: t("item_sku_name_thai"),
        field: "name_thai",
        width: 250,
        cellStyle: { whiteSpace: "nowrap" },
  }

**Comment by mschluper** [comment]
Setting the width explicitly helped solve a performance problem for me.

In m-table-cell.js width is calculated like so
var width = CommonValues.reducePercentsInCalc(_this.props.columnDef.tableData.width, _this.props.scrollWidth);
and with multiple rows and columns (say over 7) this froze Chrome.

**Comment by DewangS** [comment]
I honestly don't know why this issue was closed as it's still an issue in v1.67 though I've managed to find a workaround. Not happy that the minWidth, maxWidth are not respected .. just add **whiteSpace: 'nowrap' and paddingLeft\Right**. as per below sample

```
const columns = [
  { field: "requestID", 
  title: "Request No.", 
  searchable: false,
    cellStyle: {
        width: 80,
        minWidth: 50
      },
      headerStyle: {
        width: 80,
        minWidth: 80, 
        whiteSpace: 'nowrap',
        paddingLeft: '2em',
        paddingRight: '2em'
      }
 },
  { field: "applicantID", 
  title: "Staff No.", 
  searchable: true,
    cellStyle: {
        width: 50,
        minWidth: 50,
      },
      headerStyle: {
        width: 50,
        minWidth: 50,
        whiteSpace: 'nowrap',
        paddingLeft: '2em',
        paddingRight: '2em'
      }  },
  { field: "name", 
  title: "Name",  
  searchable: false,
    cellStyle: {
        width: 250,
        minWidth: 250,
      },
      headerStyle: {
        width: 250,
        minWidth: 250,
        whiteSpace: 'nowrap',
        paddingLeft: '1em',
        paddingRight: '17em'
      }},
]
```

**Comment by akshaykumar771** [comment]
I am using version  ^1.69.2 and I can set the width of the column but after i refresh the page everything resets and the style does not apply. 

`{ title: "First Name", field: "first_name", width: 100}`
Any solutions?

**Comment by felipedsc** [comment]
Waiting for solution on 1.69.2

**Comment by capsule5** [comment]
with the latest version it works like that:
`width: null,
      cellStyle: {
        width: 200,
      },`

thanks @jttaynton

**Comment by pumppi** [comment]
Is it possible to make example in docs? It looks like this is need feature and everyone is looking for the solution. Found out it from this issue. Thanks :)

**Comment by iokaravas** [comment]
> with the latest version it works like that:
> `width: null, cellStyle: { width: 200, },`
> 
> thanks @jttaynton

This seems to break my build when not running the development server...

**Comment by pritam1206** [comment]
dynamic columns width with latest version 
columns={[
                  {
                    title: 'Create Date',
                    field: 'create_date',
                     cellStyle: {
                      whiteSpace: 'nowrap',
                    },
              ....]}

**Comment by yerycs** [comment]
Is it possible to change cell style when edit row?
I use custom component when edit, it required wide cell width.

**Comment by satishpatidar** [comment]
Just Use { cellStyle: {width: '1%', maxWidth: '1%'}, headerStyle: {width: '1%', maxWidth: '1%'}}

**Comment by jttaynton** [comment]
The old solution of just setting width:null on first column now causes an error.  Is there any way to force old behavior where columns are spread based on their content on not evenly split by numbers of columns nor having to explicitly set width on each column?

**Comment by ammaramame** [comment]
i tried minWidth and it did worked for me

**Comment by andrewdeakins** [comment]
I was using px settings which didn't work, when i started using % instead it started to work.

**Comment by Nodirbek3d** [comment]
such a pain in the but! I tried everything described here, but width of column is not changing at all, this is critical for the app, is there any wait to change width at all??? I am at the point of giving up on material table and using MUI native table!

**Comment by DewangS** [comment]
Hi @Nodirbek3d that's really do as the below works well for me ... have you already tried this?

 ```
cellStyle: {
        width: 80,
        minWidth: 50
      },
      headerStyle: {
        width: 80,
        minWidth: 80, 
        whiteSpace: 'nowrap',
        paddingLeft: '2em',
        paddingRight: '2em'
      }
```

**Comment by AndiF** [comment]
Hi @Nodirbek3d

I have the same issue, it seems the width in headerStyle gets not applied to the th element.
It still shows a calculated with in the dom.

For me, it helped to override the header column width in the materiual ui theme:

	```
const theme = React.useMemo(() =>
		createMuiTheme({
				overrides: {
					MuiTableCell: {
						head: {
							width: '0 !important',
						}
					}
				}
			}
		), []);
```
		
Than I could set the column width based on cellStyle:

	```
	{
			title: 'xxx',
			field: 'xxx',
			cellStyle: {
				width: 35,
				maxWidth: 35
			}
		}
```
Mayby that helps for you as well. Good Luck.

**Comment by thisisglee** [comment]
if anyone looking for cell width for long texts likes and wants dots truncate.

https://github.com/mbrn/material-table/issues/257#issuecomment-469239722

**Comment by zezking** [comment]
> Hi @Nodirbek3d
> 
> I have the same issue, it seems the width in headerStyle gets not applied to the th element. It still shows a calculated with in the dom.
> 
> For me, it helped to override the header column width in the materiual ui theme:
> 
> ```
> const theme = React.useMemo(() =>
> 		createMuiTheme({
> 				overrides: {
> 					MuiTableCell: {
> 						head: {
> 							width: '0 !important',
> 						}
> 					}
> 				}
> 			}
> 		), []);
> ```
> 
> Than I could set the column width based on cellStyle:
> 
> ```
> {
> 			title: 'xxx',
> 			field: 'xxx',
> 			cellStyle: {
> 				width: 35,
> 				maxWidth: 35
> 			}
> 		}
> ```
> 
> Mayby that helps for you as well. Good Luck.
> 
> (Propably "auto" rather "0" is more html conform ;-) )

This worked really well for me and this might be obvious but remember to apply the cellStyle to all the columns that you have

**Comment by MoonSulong** [comment]
> Just Use { cellStyle: {width: '1%', maxWidth: '1%'}, headerStyle: {width: '1%', maxWidth: '1%'}} To decrease the width of column and to increase the width increase the percentage

Thanks so much, I am using the latest version 1.69.3 and confirm this is the only way that works for me in this discussion.
