### ISSUE TITLE
column with different types

### ISSUE THREAD

**Issue by arendeutsch** [mbrn/material-table#2910]
Is it possible to define a column with different types ? i.e both boolean and numeric for instance ?

**Comment by sabbirsristy7494** [comment]
@arendeutsch please see the documentation of the this library. There is column props that takes objects. Inside each object you can define type of each column.
![Capture](https://user-images.githubusercontent.com/56749379/121513725-fabc6100-ca0c-11eb-8e4b-b0dfba069ce1.JPG)

**Comment by arendeutsch** [comment]
Yes, but what i meant was if its possible to have different types in the same column. i.e one column where entries can have both bool and numeric 
lets say i have a general table with two columns name and value and the value column can take entries with both boolean and numeric.

**Comment by sabbirsristy7494** [comment]
@arendeutsch I don't think so it is possible to define two datatypes for one column. It should not be possible. If you have to use two data types in a cell then do not define the data type, then it will take string as by default. If you are facing problem to display the data, then you use render property. I hope I assumed your problem correctly.
