### ISSUE TITLE
Options prop throwing a Type error in Typescript

### ISSUE THREAD

**Issue by pgbradbury** [mbrn/material-table#2917]
**Describe the bug**
The options prop is typed incorrectly, throwing a typescript error

**To Reproduce**

1. Create a table with the options parameter as a tsx
2. Create a component with the options as a tsx
3. Pass the object component into the table component options prop
4. See error "No overload matches this call."

**Expected behavior**
No type error

**Additional context**
Looking at index.d.ts it seems the type is set to 

`options?: Options<RowData>;`

I believe it should be

`options?: Options<RowData>[];`

**Comment by pgbradbury** [comment]
Any update on this, it currently means that it can't be used in a typescript project

**Comment by adamTarr** [comment]
@pgbradbury try `Partial<Options<RowData>>`, that is what has worked for my team.
