### ISSUE TITLE
npm install / update error with material-table to prod 

### ISSUE THREAD

**Issue by franroav** [mbrn/material-table#2918]
# Guidelines

![image](https://user-images.githubusercontent.com/42781679/122417059-38624200-cf57-11eb-9426-11286237a27b.png)

Hey guys, i have an issue with installing material-table. what could be this issue?

![errror_material_table](https://user-images.githubusercontent.com/42781679/122419357-d73b6e00-cf58-11eb-98d6-98aaa39e2089.png)

**Comment by ozio** [comment]
Same issue here, but related to `@material-ui/core@4.11.3`. Seems like everything is working fine with this version, but running `npm install` with `--force` flag is pretty annoying.
