### ISSUE TITLE
Change style of icon in detailPanel

### ISSUE THREAD

**Issue by ramonribeiro96** [mbrn/material-table#2919]
Hi, i have a question, i didn't found nothing about it in documentation.

How i can change style of icon in detailPanel? He be with space very long of checkbox of selection.

<img width="180" alt="Cap" src="https://user-images.githubusercontent.com/29488690/122421861-11aa0880-cf63-11eb-8e9b-5be039770a3e.png">

Someone can help me?

 I didn't found nothing in props to this in Interface of DatailPanel?

`export interface DetailPanel<RowData extends object> {
  disabled?: boolean;
  icon?: string | React.ComponentType<any>;
  openIcon?: string | React.ComponentType<any>;
  tooltip?: string;
  render: (rowData: RowData) => string | React.ReactNode;
}`

**Comment by bferrell16** [comment]
You could adjust the styling of the icon (if that is what is adding the empty space) via theme overrides: 

```
const theme = createMuiTheme({
    overrides: {
        MuiSvgIcon: {
        root: {
          padding: 0,
          margin: 0,
        }
      }
  }
}

<MuiThemeProvider theme={theme}>
        <MaterialTable />
</MuiThemeProvider>
```

Not sure if that is exactly the class you need to target, but inspect element and see where the gap is coming from then override that style should do it. Be wary though it will affect all icons on the table unfortunately. Could add some more clever selectors to get around that. 

Another option would be to make the table dense spacing via options and the `padding: 'dense'` prop.

**Comment by ramonribeiro96** [comment]
Apparently it's a div that has a style made. it would be nice to have a props inside DetailPanel to get the most out of it.

![div](https://user-images.githubusercontent.com/29488690/123146080-e37d6a80-d433-11eb-99cf-d38b701cf4f8.jpg)
