### ISSUE TITLE
'MaterialTable' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by HusnuAkcak** [mbrn/material-table#2925]
![cannot be used as JSX component](https://user-images.githubusercontent.com/29748234/123748749-4ac86e00-d8bd-11eb-8500-5607e5b77b81.png)

**Comment by HusnuAkcak** [comment]
[SOLUTION]

I was importing the package as

import { MaterialTable } from 'material-table';

Then I changed it to

const MaterialTable = require("material-table").default;

Now, its compiled and rendered.

**Comment by iibarbari** [comment]
How do you import components like `MTableToolbar`? @HusnuAkcak

**Comment by philippjuno** [comment]
That solution does not work for typescript.
