### ISSUE TITLE
Can't resolve '@material-ui/core/styles/colorManipulator' with Material core:  "^5.0.0-beta.0"

### ISSUE THREAD

**Issue by alejandro6901** [mbrn/material-table#2931]
# Material UI core upgrade error with React

**Describe the bug**
 Material UI core library upgrade from version "^4.11.4" to "^5.0.0-beta.0" throws errors. 
 Material UI docs for version 5 explain the new changes here: https://next.material-ui.com/guides/migration-v4/
**Screenshots**
Attached some screens: 

<img width="653" alt="Screen Shot 2021-07-03 at 18 09 30" src="https://user-images.githubusercontent.com/17208941/124369607-a03cac00-dc2a-11eb-9030-2c0ce70c71a0.png">
<img width="380" alt="Screen Shot 2021-07-03 at 18 10 49" src="https://user-images.githubusercontent.com/17208941/124369608-a0d54280-dc2a-11eb-9d51-e1e0e228d670.png">

**Comment by onair-lena** [comment]
I have the same issue after upgrade to  "^5.0.0-beta.0"
![image](https://user-images.githubusercontent.com/47395779/125308177-5a25cd80-e339-11eb-99b2-68390b481c80.png)

**Comment by alejandro6901** [comment]
> I have the same issue after upgrade to "^5.0.0-beta.0"
> ![image](https://user-images.githubusercontent.com/47395779/125308177-5a25cd80-e339-11eb-99b2-68390b481c80.png)

Hi, @onair-lena 

The main issue is that Material UI V5 has changed the project structure for styles and other folders, for instance: 

before in Material v4
import { ColorManipulator } from "@material-ui/**core/styles/**colorManipulator"

now in Material v5
import { ColorManipulator } from "@material-ui**/styles/**colorManipulator"

**Comment by alejandro6901** [comment]
@onair-lena 

https://next.material-ui.com/guides/migration-v4/#styles

<img width="954" alt="Screen Shot 2021-07-12 at 09 20 37" src="https://user-images.githubusercontent.com/17208941/125313488-82d6a480-e2f2-11eb-9b24-f6484f25ac3d.png">
