### ISSUE TITLE
use onPageChange instead

### ISSUE THREAD

**Issue by dcerlanda** [mbrn/material-table#2935]
having this warning 

Warning: Failed prop type: The prop `onChangePage` of `ForwardRef(TablePagination)` is deprecated. Use the `onPageChange` prop instead.

package.json

"dependencies": {
    "@amcharts/amcharts4": "^4.10.20",
    "@fullcalendar/bootstrap": "^5.8.0",
    "@fullcalendar/core": "^5.8.0",
    "@fullcalendar/daygrid": "^5.8.0",
    "@fullcalendar/interaction": "^5.8.0",
    "@fullcalendar/react": "^5.8.0",
    "@material-ui/core": "^4.12.0",
    "@material-ui/icons": "^4.11.2",
    "@reduxjs/toolkit": "^1.6.0",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.5.0",
    "@testing-library/user-event": "^7.2.1",
    "apexcharts": "^3.27.1",
    "availity-reactstrap-validation": "^2.7.1",
    "axios": "^0.21.1",
    "axios-mock-adapter": "^1.18.2",
    "bootstrap": "^4.5.0",
    "chart.js": "^3.4.1",
    "chartist": "^0.11.4",
    "draft-js": "^0.11.7",
    "echarts": "^4.9.0",
    "echarts-for-react": "^2.0.16",
    "fullcalendar": "^5.8.0",
    "fullcalendar-reactwrapper": "^1.0.7",
    "google-maps-react": "^2.0.6",
    "lodash.clonedeep": "^4.5.0",
    "match-sorter": "^6.3.0",
    "material-table": "^1.69.3",
    "mdbreact": "^4.27.0",
    "metismenujs": "^1.3.0",
    "morris.js": "^0.5.0",
    "node-sass": "^4.14.1",
    "raphael": "^2.3.0",
    "react": "^16.13.1",
    "react-ace-editor": "0.0.3",
    "react-alert": "^7.0.3",
    "react-alert-template-basic": "^1.0.2",
    "react-alert-template-mui": "^1.0.7",
    "react-apexcharts": "^1.3.9",
    "react-bootstrap-sweetalert": "^5.2.0",
    "react-bootstrap-table-next": "^4.0.3",
    "react-bootstrap-table2-editor": "^1.4.0",
    "react-bootstrap-table2-filter": "^1.3.3",
    "react-bootstrap-table2-overlay": "^2.0.0",
    "react-bootstrap-table2-paginator": "^2.1.2",
    "react-c3js": "^0.1.20",
    "react-chartist": "^0.14.3",
    "react-chartjs-2": "^2.11.2",
    "react-closeable-tabs": "^1.1.5",
    "react-cropper": "^2.1.8",
    "react-custom-scrollbars": "^4.2.1",
    "react-dom": "^16.13.1",
    "react-draft-wysiwyg": "^1.14.7",
    "react-dropzone": "^11.3.4",
    "react-headless-tabs": "^1.1.1",
    "react-image-lightbox": "^5.1.1",
    "react-jvectormap": "0.0.16",
    "react-ladda": "^6.0.0",
    "react-metismenu": "^1.4.0",
    "react-pro-sidebar": "^0.4.3",
    "react-quill": "^1.3.5",
    "react-redux": "^7.2.4",
    "react-router-dom": "^5.2.0",
    "react-scripts": "^4.0.3",
    "react-table": "^7.7.0",
    "reactstrap": "^8.5.1",
    "redux": "^4.1.0",
    "redux-saga": "^1.1.3",
    "simplebar-react": "^3.0.0-beta.5"
  },

**Comment by matthoffner** [comment]
Hi @dcerlanda I went ahead and made some prop type updates to this in #2937. Our test configuration fails on prop-type errors, so we would love to get this out soon. Thanks!

**Comment by raulrobi2018** [comment]
Hi people! I have the same issue using this packages:

`"@material-ui/core": "^4.12.3",
    "@material-ui/icons": "^4.11.2",
    "@material-ui/lab": "4.0.0-alpha.60",
    "material-table": "^1.69.3",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
`
I tried with with previous versions but it remained the same.

**Comment by nborisic** [comment]
Same here! Please update this because it's clogging the console. /:

**Comment by Cristy94** [comment]
Same issue, it works but it just shows the deprecated error. Is there a specific version that doesn't have this issue?

**Comment by chris-jalon** [comment]
@Cristy94 use the forked package: https://github.com/material-table-core/core

**Comment by Cristy94** [comment]
> @Cristy94 use the forked package: https://github.com/material-table-core/core

Thanks, it worked!

Is this repo no longer maintained? Is that the main one now?

**Comment by chris-jalon** [comment]
> > @Cristy94 use the forked package: https://github.com/material-table-core/core
> 
> Thanks, it worked!
> 
> Is this repo no longer maintained? Is that the main one now?

yes and yes. more info: https://github.com/mbrn/material-table/issues/3044
