### ISSUE TITLE
Add one row (single) selection mode

### ISSUE THREAD

**Issue by angelelizalde21** [mbrn/material-table#294]
hi

I think it would be great to have the option to select both one and multimples rows

I would appreciate very much if I added this feature

**Comment by mbrn** [comment]
Hi @angelelizalde21 ,

It already have selection feature. 

https://mbrn.github.io/material-table/#/docz-examples-05-example-selection

**Comment by angelelizalde21** [comment]
if I'm using the selection option, but would I like to have the option to select one row at a time, or some way to just select one?

**Comment by mbrn** [comment]
You can do it with onRowClick event. It will give you clicked rowData. So you can send a rowStyle to table according to selected row. 

If you can not do it let me know. I will add a example about it.

**Comment by angelelizalde21** [comment]
I already made the code.
 in fact it works thanks a lot, I hope in a while you could add selection modes (sinlge or mutiple).
for now it works, thanks for the excellent help
greetings.

**Comment by gaurav-agarwal27** [comment]
Hey @mbrn I am confused on how to let the user only select only one row only.
Since there is only option for checkboxes and not radio buttons. Can you add an example over here please ?

**Comment by imhotrez** [comment]
> You can do it with onRowClick event. It will give you clicked rowData. So you can send a rowStyle to table according to selected row.
> 
> If you can not do it let me know. I will add a example about it.

Hello. It's a pitty but my skills of TypeScript and React is low. Would you please give me example of this code?
