### ISSUE TITLE
onChangePage and onChangeRowsPerPage is deprecated

### ISSUE THREAD

**Issue by saikun0293** [mbrn/material-table#2942]
These are the errors I get on rendering material table 

![image](https://user-images.githubusercontent.com/56252312/125084233-ebe9cc80-e0e6-11eb-9d1f-ead18d04e132.png)
![image](https://user-images.githubusercontent.com/56252312/125086445-46842800-e0e9-11eb-97a5-a3cc6569396a.png)
![image](https://user-images.githubusercontent.com/56252312/125086399-3b30fc80-e0e9-11eb-8b9d-2dccfce5b30d.png)

This is code being rendered

```jsx
  <MaterialTable
        title="CRUD operations using Material Table"
        columns={cols}
        data={users}
   />
```
I'm trying to perform CRUD operations using material-table 

1. I have simply imported Material Table onto my component
2. I have specified columns outside the component as follows

```js
const cols = [
  { title: "Name", field: "name" },
  { title: "Username", field: "username" },
  { title: "Email", field: "email" },
  { title: "Phone", field: "phone" },
  { title: "Website", field: "website" },
];
```
3. users is from useState hook
```js
const [users, setUsers] = useState([]);
```

**Desktop:**

- OS: Windows
- Browser: Chrome
- Version: 91.0.4472.124

**Additional context**

I am not quite sure why is this happening. I have indeed followed the instructions as specified in the documentation and I have installed material-icons core and icons

**Comment by saikun0293** [comment]
I see this issue is currently being resolved. Didn't notice. It's an amazing library thanks for your hardwork!

**Comment by irkreja** [comment]
Still it is not solved. Please resplace all onChangePage and onChangeRowsPerPage with onPageChange and onRowsPerPageChange.

**Comment by Tropicalista** [comment]
I have same error.

**Comment by mat-kul** [comment]
me too, tested on 
```
"material-table": "^1.69.3",
"react": "^17.0.2",
"@material-ui/core": "^4.12.3",
```

**Comment by uqclien** [comment]
@saikun0293 could you share which release has the fix?
