### ISSUE TITLE
Error pagination

### ISSUE THREAD

**Issue by MarvinM7** [mbrn/material-table#2943]
The table loads normally and I can change the number of lines per page, but I can't change pages.

**Just loading the component already show 3 errors:**

1. Warning: Failed prop type: The prop `onChangePage` of `ForwardRef(TablePagination)` is deprecated. Use the `onPageChange` prop instead. 
![image](https://user-images.githubusercontent.com/32967685/125168084-0751e780-e17a-11eb-8105-760613a5c2ce.png)

2. Warning: Failed prop type: The prop `onChangeRowsPerPage` of `ForwardRef(TablePagination)` is deprecated. Use the `onRowsPerPageChange` prop instead.
![image](https://user-images.githubusercontent.com/32967685/125168102-1e90d500-e17a-11eb-9fd0-3529f2db9626.png)

3. Warning: Failed prop type: The prop `onPageChange` is marked as required in `ForwardRef(TablePagination)`, but its value is `undefined`.
![image](https://user-images.githubusercontent.com/32967685/125168112-2b152d80-e17a-11eb-804e-88a063c7d82c.png)

**When clicking on any button to pass the page (first, previous, next, last), another error appears:**

1. Uncaught TypeError: _this.props.onChangePage is not a function
![image](https://user-images.githubusercontent.com/32967685/125168133-3ec09400-e17a-11eb-8481-d40b023027a4.png)

packages:

- react": "^17.0.2
- material-table": "^1.69.3
- @material-ui/core": "^4.12.1

<MaterialTable
        icons={icones}
        columns={colunas}
        data={linhas}
        title={titulo}
        options={{
            paging: true,
            pageSize: linhas.length < 10 ? linhas.length !== 0 ? linhas.length : 1 : 10,
            emptyRowsWhenPaging: true,
            pageSizeOptions: [1, 5, 10, 20, 50, 100]
        }}
        localization={{
            body: {
                emptyDataSourceMessage: 'Sem registros'
            },
            pagination: {
                labelRowsSelect: 'Linhas',
                labelRowsPerPage: 'Linhas por página',
                firstAriaLabel: 'Primeira página',
                firstTooltip: 'Primeira página',
                previousAriaLabel: 'Página anterior',
                previousTooltip: 'Página anterior',
                nextAriaLabel: 'Próxima página',
                nextTooltip: 'Próxima página',
                lastAriaLabel: 'Última página',
                lastTooltip: 'Última página'
            },
            toolbar: {
                searchPlaceholder: 'Procurar',
                searchTooltip: 'Procurar'
            }
        }}
/>

**Comment by rodrigo-rrp** [comment]
I'm getting the same error but only on the PROD environment. Maybe it's related to the file being minified?

**Comment by Beta-7** [comment]
I believe this [PR](https://github.com/mbrn/material-table/pull/2937) will address this issue. Until then would downgrading the material-ui/core version work?

**Comment by xerigo** [comment]
I have the same issue!

**Comment by MarvinM7** [comment]
> I believe this [PR](https://github.com/mbrn/material-table/pull/2937) will address this issue. Until then would downgrading the material-ui/core version work?

the patch posted by chelproc in this conversation worked for me, thank you for the link. I will close this issue.
