### ISSUE TITLE
Sorting gets cleared

### ISSUE THREAD

**Issue by mihai-hoinaru** [mbrn/material-table#2944]
`<Table data={data} isLoading={isTableLoading} handleShow={handleShow} />`
`<Modal show={showModal}>
...
</Modal>`

and opening the modal from **onRowClick**:
`onRowClick={(evt, rowData) => handleShowModal(rowData)}`
resets the sorting of a column. Is this a bug or something that I'm missing?

One thing I've noticed: if I'd have a console.log on the **onRowClick** event, the sorting would not reset, but as long as I change a state, the sorting resets.

Version: "material-table": "^1.69.2"

**Comment by k-rokicki** [comment]
I think it is still the same bug (?) as here: https://github.com/mbrn/material-table/issues/491

**Comment by mihai-hoinaru** [comment]
> I think it is still the same bug (?) as here: #491

Thanks, I'll give it a try and update the issue.

**Comment by mihai-hoinaru** [comment]
Now it seems that sorting no longer clears, but I have a bigger issue with a memory leak after I refresh the data on the table which is passed as a prop. If I have a button and on click it fetches the data, the memory explodes and the page crashes.

**Comment by mihai-hoinaru** [comment]
#2650 Great -_-
