### ISSUE TITLE
Dependency on outdated version of @material-ui/pickers

### ISSUE THREAD

**Issue by shineforth** [mbrn/material-table#2946]
The material-table package has a dependency on @material-ui/pickers 3.2.2 which does not support React v17 and this npm package is also being deprecated anyway. See this link -> https://github.com/mui-org/material-ui-pickers/issues/2157.

The latest version of pickers is 3.3.10 so at a minimum we need this updated to that. Beyond that this package needs to be updated to use React v17 compatible dependencies.

Here's the error I get when building my application (which I tracked to this package's dependency):

`npm WARN @material-ui/pickers@3.2.2 requires a peer of react@^16.8.4 but none is installed. You must install peer dependencies yourself.
npm WARN @material-ui/pickers@3.2.2 requires a peer of react-dom@^16.8.4 but none is installed. You must install peer dependencies yourself.`

**Comment by romanown** [comment]
how i can upgrade @material-ui/pickers v3 to v4?
