### ISSUE TITLE
Is there a way to change the color of some cells in a table?

### ISSUE THREAD

**Issue by kotatsunokoneko** [mbrn/material-table#2950]
Is there a way to change the color of some cells in a table?
Not for rows.

**Comment by JIMVCGCG** [comment]
The `columns` prop takes an optional `cellStyle` object or function that can be used to impact the cell background color.
Something like:

```
const columns = [
// ... 
cellStyle: (cellValue, rowData) => {
  const style = {
    backgroundColor: cellValue > 0 ? "#8EC3E7" : "#FECDB2"
  }
  return style
}
]
```
