### ISSUE TITLE
Uncaught TypeError: _this.props.onChangePage is not a function

### ISSUE THREAD

**Issue by Ancientae0N** [mbrn/material-table#2952]
I have a table which has pagination, I'm trying to go to the next page and it throws the error `Uncaught TypeError: _this.props.onChangePage is not a function`, everything was working fine until today, in fact the same application I had deployed last night is working, but in local it's failing now.

![image](https://user-images.githubusercontent.com/21144876/125859168-b3ec9c60-227e-44fd-b63d-b0d47ee700a8.png)

`The error onClick of the arrow for the next page`

![image](https://user-images.githubusercontent.com/21144876/125859501-34204ed9-e206-45b8-9232-60f4bbd0e700.png)

**Comment by AKLEIN26** [comment]
I' facing the same issue as well.

**Comment by 9jaboy** [comment]
see #2935

**Comment by brahmdev** [comment]
the solution given https://github.com/mbrn/material-table/pull/2937#issuecomment-879017952 worked for me.
Hope this won't be needed once it is released

**Comment by jesperborgstrup** [comment]
The breaking change was reverted in `@material-ui/core` version 4.12.3: https://github.com/mui-org/material-ui/releases/tag/v4.12.3.

Upgrading to this version fixed the issue for me 

> [Table] Re-introduce deprecated TablePagination `onChangePage` to `ActionsComponent` (#27407) @eps1lon

**Comment by Implausiblerecruitment2** [comment]
> the solution given [#2937 (comment)](https://github.com/mbrn/material-table/pull/2937#issuecomment-879017952) worked for me. Hope this won't be needed once it is released





https://information-ashamed.github.io/pyqt4316/
