### ISSUE TITLE
Customize Bulk Update Button

### ISSUE THREAD

**Issue by macsee** [mbrn/material-table#2955]
Hi to all.

I'm currently using in my project the row editing functionality and I would like to implement bulk update in the near future. I was wondering if there's a way to use different icons for these two actions, since my toolbar uses bigger buttons and my rows tiny icons for edit and delete. I also want to change the message from the tooltip in bulk update button as I did with regular update button. 
Thanks!

**Comment by oliviertassinari** [comment]
cc @m4theushw something we might want to consider in the row edit API (in the back of our head)

**Comment by macsee** [comment]
I managed to do it (for now) by overriding the Action component, like the solution proposed on this issue #2133. Just in case someone is looking to achieve the same, this is what I did:

```javascript
<MaterialTable
            //...
            components={{
                 Action: (props) => {
                        if (props.action["position"] === "toolbar" && props.action.icon.name === "Edit") {
                          // Code for my custom button that keeps same functionality for BulkUpdate
                           return (
                                <button
                                  className="MuiButtonBase-root MuiIconButton-root MuiIconButton-colorInherit"
                                  onClick={props.action.onClick}
                                   >
                                     <div className={"btn btn-light tx-13"}>
                                         <i className="fas fa-edit mg-r-5"></i> Editar
                                    </div>
                               </button>
                            );
                       }
                      else return <MTableAction {...props} />;
              }
}}
```
