### ISSUE TITLE
e.props.onChangePage - error coming up for 1.68.0

### ISSUE THREAD

**Issue by ankursehdev** [mbrn/material-table#2960]
I am using Material-table in react project and seeing **e.props.onChangePage** in my production when I click on the pagination. 

![image](https://user-images.githubusercontent.com/34501847/126540021-b4523e4c-7a25-480f-9987-f312cf35570e.png)

![image](https://user-images.githubusercontent.com/34501847/126540102-a9e29207-eb45-450e-9ae0-6f9e8e02047f.png)

![image](https://user-images.githubusercontent.com/34501847/126540243-a783cc2d-5dcc-45bc-8869-a7d94f26e0c0.png)

I am including all the code above, I am not using this prop directly into my code but still facing this issue. 

**To Reproduce**

I just click on the next button of the pagination and this error is showing up in the console. 
and the user is not able to move to another page. 

**Expected behavior**
User should be able to move to another page. 

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome and Mozilla, that is where I have tried and its similar on both browsers.

**Comment by EvanVujcec** [comment]
Yeah I'm having the same problem but I don't think this is a new problem as downgrading doesn't help.

My code for context:
```jsx
const VendorList: React.FC<IVendorListProps> = (props) => {
  const [vendors, setVendors] = React.useState<IVendor[]>();
  const [alias, setAlias] = React.useState<string>();
  const [editAliases, setEditAliases] = React.useState<boolean>(false);

  React.useEffect(() => {
    SpApi.fetchVendors(setVendors);
  }, []);

  const selectVendor = (e, vendorSelected: IVendor): void =>
    props.setVendor(vendorSelected);

  return (
    <>
      {editAliases ? (
        <TextField
          label="Alias"
          variant="outlined"
          value={alias}
          onChange={(e) => setAlias(e.target.value)}
        />
      ) : null}
      {vendors ? (
        <>
          <MaterialTable
            title="Vendors List"
            columns={columns}
            data={vendors}
            icons={icons}
            onRowClick={editAliases ? null : selectVendor}
            onSelectionChange={(rows) => {
              console.log(rows);
            }}
            options={{
              // paging: false,
              draggable: false,
              selection: editAliases,
              rowStyle: (rowData: IVendor, index: number) => {
                let style: React.CSSProperties = {};
                if (!(index % 2)) {
                  style = {
                    ...style,
                    backgroundColor: styles.alternateRowColor,
                  };
                }
                return style;
              },
            }}
          />
        </>
      ) : (
        <CircularProgress />
      )}
    </>
  );
};
```

**Comment by isrhedden** [comment]
I am experiencing this issue as well in production. Interestingly, though, my code works locally (Windows OS).

I am using material-table v1.69.3 and @material-ui/core v4.12.2. I've used material-table plenty of times before without issue so I'm still working on what changed in this project.

**Comment by EvanVujcec** [comment]
@isrhedden yeah I just realized it was likely a mui/core issue as issues #2952 and #2935 seem to be related

**Comment by EvanVujcec** [comment]
For now, this seems to be the workaround https://github.com/mbrn/material-table/issues/2937#issuecomment-879017952

**Comment by ankursehdev** [comment]
@EvanVujcec That looks promising, I will try that but my whole application uses 20 different tables. I don't want to update them all. 

Updating MUI/CORE is working for anyone?

**Comment by EvanVujcec** [comment]
@ankursehdev actually it's probably better to just move to [the new project](https://github.com/mbrn/material-table) as this seems to be abandoned. It works and is just a drop in replacement for material-table, just update imports.

**Comment by ankursehdev** [comment]
Seems like a lot of apps are broken right now, I use React-table and Material Table, and pagination is broken in both of the tables. 

Look here: https://github.com/mui-org/material-ui/issues/27192

Hopefully, they will fix it soon.

@EvanVujcec when you move to the new project what does that mean? I am already using material-table 1.69.0, is there a newer version or a new repo?

**Comment by EvanVujcec** [comment]
Oh that would make sense since one of the changes in the fork is that they changed the name to match the breaking change cause they've been prepping it for mui-v5 migration

**Comment by EvanVujcec** [comment]
@ankursehdev Yes sorry I used the wrong link in previous post. It's just a fork of this project that's actually being maintained [the new project](https://github.com/material-table-core/core). The only change you need to make after installing is updating imports to point to the new package. Also check over the [breaking changes](https://material-table-core.com/docs/breaking-changes).

**Comment by jesperborgstrup** [comment]
The breaking change was reverted in `@material-ui/core` version 4.12.3: https://github.com/mui-org/material-ui/releases/tag/v4.12.3.

Upgrading to this version fixed the issue for me 

> [Table] Re-introduce deprecated TablePagination `onChangePage` to `ActionsComponent` (#27407) @eps1lon
