### ISSUE TITLE
High vulnerability in dependency jspdf => Update package.json?

### ISSUE THREAD

**Issue by NicolasCViseo** [mbrn/material-table#2965]
Hello,

Installing and working with the latest material-table, npm is warning about a high vulnerability in the projet :
![image](https://user-images.githubusercontent.com/87130438/126760214-81c8bcc0-3bb8-4125-9653-ea5f2bc46b78.png)

Maybe updating the dependency to the latest version of jspdf could be better ?

Best regards,

Nicolas

Edit :
There is a pull request regarding this issue waiting to be accepted :
https://github.com/mbrn/material-table/pull/2934

**Comment by keemor** [comment]
Hi @mbrn

Is there a chance that this PR will be merged? It would be really awesome :) 
There are few other bugs that could be closed along with this one.

Thank you very much!

**Comment by keemor** [comment]
I successfully updated jspdf using this solution 

https://stackoverflow.com/questions/15806152/how-do-i-override-nested-npm-dependency-versions

![image](https://user-images.githubusercontent.com/1793635/135101155-e1d4d5fc-b14a-4f40-96ed-164007b9b331.png)

**Comment by lucasgonze** [comment]
@keemor Your solution is creative. Kudos. I am considering it for our project and need to figure out the tradeoffs. What were your thoughts on the down side of the shrinkwrap workaround?

**Comment by lucasgonze** [comment]
The other option is to switch to this fork, which contains the jspf update and other maintenance commits: 

https://github.com/material-table-core/

**Comment by keemor** [comment]
@lucasgonze Due to the ending of the project in which material-table was used we locked up the version at 1.68.0. Later versions had some problems which are probably solved, but I didn't want to take any risk. My jspdf bump workaround was satisfying and I haven't noticed any problems until now.
