### ISSUE TITLE
Examples of how one could add custom HTML components

### ISSUE THREAD

**Issue by jonasvag** [mbrn/material-table#297]
**Is your feature request related to a problem? Please describe.**
Please add examples of how one could add custom HTML components to the toolbar (and other as well). I know it is possible to do such things, but the documentation lacks some good examples on how to implement it properly.

**Describe the solution you'd like**
![header](https://user-images.githubusercontent.com/24210048/54076728-247b0080-42b7-11e9-8710-cb0b2a78f9ac.png)

Please update docs with more amazing usage examples.

**Comment by mbrn** [comment]
Hi @jonasvag ,

I will add a example about this. Thanks for advice

**Comment by HaswinVidanage** [comment]
Hi @jonasvag , @mbrn can you I know how this is done ?
also is it possible to create a custom add row button and replace it with the existing add row button on the toolbar ?

Thanks in advance.  :)

**Comment by mbrn** [comment]
Hi @jonasvag 

You can override Action component. So you can draw your own add row button on toolbar.

**Comment by rssluca** [comment]
HI! 
How so? It looks to me that Action/Actions overrides each row actions not the toolbar..

I would like to see and example too as I would like to add custom button to the toolbar!

Thanks!!

**Comment by mbrn** [comment]
Hi @rssluca 

You should set isFreeAction: true to see buttons on toolbar. I will add a example to actions asap.

**Comment by rssluca** [comment]
Done it, I also added a PR to add a searchFieldAlignment option so that the search field can be moved to the left as well.

For anyone else, you can add a custom element in the action component, for example:

```
const AddButton = (
      <Button
        variant="contained"
        color="primary"
        className={classes.marginBottom}
        component={Link}
        to={`${fullPath}/new`}
        size="small"
      >
        <AddIcon fontSize="small" className={classes.leftIcon} />
        ADD NEW
      </Button>
    );

const actions = [
      {
        icon: () => AddButton ,
        tooltip: "Add User",
        onClick: (event, rowData) => {
          alert("You clicked user " + rowData.name);
        },
        iconProps: {
          color: "primary"
        },
        isFreeAction: true
      }
    ];
```
