### ISSUE TITLE
The columns provided to material table are static, but contain functions which update on every render, resetting the table state. Provide a stable function or column reference or an row id to prevent state loss.

### ISSUE THREAD

**Issue by sufius** [mbrn/material-table#2971]
As soon as I'm using the render option in the columns object I'm getting following console message:

> _The columns provided to material table are static, but contain functions which update on every render, resetting the table state. Provide a stable function or column reference or an row id to prevent state loss._

Here is an example similar to my configuration:
```

import React from "react";
import MaterialTable from "material-table";

const columns = [
  { title: "Id", field: "id", type: "numeric" },
  { title: "Email", field: "email" },
  { title: "First Name", field: "first_name", render: rowData => (<div>{rowData.companion1}</div> }
];

const App = () => {
  const [data, setData] = useState([]);

  return (
    <MaterialTable
      data={getData}
      columns={columns}
    />
  );
};
```

I'm using material-ui 5@beta.2

Any help welcome

**Comment by sufius** [comment]
It's strange here it is working even without useCallback (maybe I'm doing smth wrong)...

[https://codesandbox.io/s/create-react-app-forked-u8n48?file=/src/Table.js](https://codesandbox.io/s/create-react-app-forked-u8n48?file=/src/Table.js)

**Comment by tamilarasu602** [comment]
@sufius The check is run from the second render onwards. In the above example, `Table` component doesn't re-render. Check the console logs, there is only one line.
Adding 
```
useEffect(() => {
    setState(true);
}, [data]);
```
to your code shows the warning.

**Comment by sufius** [comment]
@tamilarasu602 Indeed, I updated the example. Thank you.

**Comment by LeJav** [comment]
Hello,

I have exactly the same issue but do not understand what is wrong and how to avoid this warning in the console log.
Message is: The columns provided to material table are static, but contain functions which update on every render, resetting the table state. Provide a stable function or column reference or an row id to prevent state loss. 

My render function displays a checkbox. Here the code:
```
                        render: (rowData) => (
                          <Checkbox
                            checked={rowData.validated}
                            value={rowData.validated}
                            onChange={handleChangeCheckbox(rowData.attr1)}
                            name={'checkbox_' + rowData.attr1}
                            color="primary"
                          />
                        ),
```
This seems to be a stable function, no?
I have also an unique id property for each row.
What is wrong?

Many thanks for your help.

**Comment by ar4hc** [comment]
Stupid Question:
Could it be that the loss of state also disables the full text search, from the input in the top right of the table ?

i used to have a column render like this:
```js
    render: (rowData) => <DateRender value={rowData || null} col={'last_action_date'} />,
```

and had the warning and no working search

and after changin to
```js
render: (rowData) => dateRender(rowData?.last_action_date),
```
the search did work again.
And the warning disappeared.

My columns are defined somewhat complex:

The columns are in a state and the state is set using  inside the (functional)  component:
```js
    const columns = applyFilters(initColumns, context.listFilters).map((c, i) => {...};
    setTableColumns(columns);
```
but initColumns and dateRender() are defined outside the component, but in the same file/module.
