### ISSUE TITLE
this.props.onChangePage is not a function!!!

### ISSUE THREAD

**Issue by edijr92** [mbrn/material-table#2973]
the method onChangePage in m-table-pagination.js change, is not working correctly I was able to fix it by change the methods to       "onPageChange"

**Comment by crema-git** [comment]
getting the same issue `m-table-pagination.js:67 Uncaught TypeError: _this.props.onChangePage is not a function`  

           onChangePage={(page) => {
              console.log('page: ', page);
              setPage(page);
            }}
            
            onPageChange={(page) => {
              console.log('page: ', page);
              setPage(page);
            }}
passing both function according to doc and the error

**Comment by b3ni** [comment]
Same problem

**Comment by nareshviswakarma** [comment]
even iam into onChangePage to onPageChange .but its not working again showing that same error. what to do now can  anyone suggest me

**Comment by sm3sher** [comment]
@nareshviswakarma look at https://github.com/material-table-core/core
It is basically identical to this library and regularly maintained.

**Comment by maitedev** [comment]
[` 
  handleChangePage = (page) => {
    console.log(page)
  };
onChangePage={(page) => this.handleChangePage(page)}`](url)
