### ISSUE TITLE
Export button is missing from Options 

### ISSUE THREAD

**Issue by JeomJeom** [mbrn/material-table#2976]
I encountered an issue on MaterialTable's export button. It didn't show up in the table after adding `<MaterialTable options={{exportButton: true}} />`

I discovered that `exportButton` wasn't found in the `Options interface`, when I stepped into the `options` props in the `MaterialTable`. To tackle with this issue, I've tried to remove the `node_modules` folder and install it again.

Apparently, it doesn't seem to solve the issue. This is the list of the elements shown in my `Options interface`.
<img width="656" alt="Screenshot 2021-08-02 at 6 13 34 PM" src="https://user-images.githubusercontent.com/38584966/127834698-cc1c2b2c-b151-4405-a9c9-9049ab3dd51b.png">

Could anyone help me with this issue?

**Comment by sufius** [comment]
seems it is going to be deprecated:

[material-table-core](https://material-table-core.com/docs/api/props/options/)

**Comment by JeomJeom** [comment]
@sufius Thank you. Problem solved
