### ISSUE TITLE
Please update jspdf version 

### ISSUE THREAD

**Issue by karolyreka** [mbrn/material-table#2978]
# Guidelines

- #### Please include a demo of the issue/behavior/question you have
![image](https://user-images.githubusercontent.com/20512492/128181752-a3129d83-7272-4ff2-a99e-c40fb23739bd.png)

- #### Please try to be as detailed as possible
When running npm audit there is a high vulnerability issue listed for the jspdf dependency.
There is a new version of this dependency (2.3.1) that could be used and does not have any vulnerability issues.

**Comment by Lionqueen94** [comment]
Please fix 🙏

**Comment by lucasgonze** [comment]
See https://github.com/material-table-core/ for the fix
