### ISSUE TITLE
[Docs] Examples section collapses after clicking on a specific example

### ISSUE THREAD

**Issue by jonasvag** [mbrn/material-table#298]
**Describe the bug**
Issue related to docs. Examples section collapses after clicking on a specific example.

**To Reproduce**
1. Go to https://mbrn.github.io/material-table/
2. Click on 'Examples' menu item.
3. Click on one of the available examples.
4. See >> examples section automatically collapses.

**Expected behavior**
It should stay expanded so one could easily navigate between different examples. Now one has to click to expand the examples section every time he wants to navigate to the different example.

**Comment by mbrn** [comment]
You are right @jonasvag. I realized it before but it is about a docz bug:
https://github.com/pedronauck/docz/issues/569

I am waiting them to resolve it.

**Comment by mbrn** [comment]
I developed a new documentation site. material-table.com
