### ISSUE TITLE
Custom Sorting 

### ISSUE THREAD

**Issue by VidushaZ** [mbrn/material-table#2980]
Hi,

I have column contains memory values with MB and GB.
Normal sort option does not work as expected because of the units. (GB,MB)
Is there any way to fix this? or add a custom sorting function?

Thanx

**Comment by sysrajith** [comment]
up

**Comment by minusfive** [comment]
Columns have a `customSort` prop you can pass, described in the docs: https://material-table.com/#/docs/features/sorting
