### ISSUE TITLE
row with multiple rows

### ISSUE THREAD

**Issue by muscaiu** [mbrn/material-table#2983]
I've been looking over the documentation, but did not find  a way to build a table like the one in the image.

The only idea would be to put another table inside the big rows, but i would like to avoid that.

Is there any example for a table like this?
Thanks in advance.

<img width="1551" alt="Screenshot 2021-08-11 at 15 22 22" src="https://user-images.githubusercontent.com/11426309/129028412-1cd530f1-7492-4153-bc37-d83635c56339.png">

**Comment by vineetgolchha** [comment]
Hi did you find a solution? even I am trying to build a similar table but can't find the solution.
