### ISSUE TITLE
Min width not work with headerStyle.

### ISSUE THREAD

**Issue by kirin-yuen** [mbrn/material-table#2984]
**Describe the bug**
minHeight work with header style, but minWidth doesn't. 

**To Reproduce**

1. Visit https://codesandbox.io/s/frosty-sound-xbjmx?file=/src/App.js
2. Please press F12 to open dev tool and inspect target element to see the style, minWidth not apply but minHeight do

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/13096729/129145458-58f4af2e-0717-4127-9cf7-55b9c5778727.png)

**Comment by chris-jalon** [comment]
This is poorly documented, but if you look at [the source](https://github.com/mbrn/material-table/blob/b7474ca0f5497f04ff3a3d50e709d86de7c639b0/src/components/m-table-header.js#L88), it seems minWidth / maxWidth are properties of Column, not headerStyle. So they should go directly in your column object (next to `field`, `title`) like this: 

```js
{
  title: "one",
  field: "one",
  width: "40px",
  minWidth: "90px",
  headerStyle: {
    minHeight: "120px"
  }
}
```

**Comment by kirin-yuen** [comment]
> This is poorly documented, but if you look at [the source](https://github.com/mbrn/material-table/blob/b7474ca0f5497f04ff3a3d50e709d86de7c639b0/src/components/m-table-header.js#L88), it seems minWidth / maxWidth are properties of Column, not headerStyle. So it should go directly in your column object (next to `field`, `title`) like this:
> 
> ```js
> {
>   title: "one",
>   field: "one",
>   minWidth: "90px",
>   headerStyle: {
>     minHeight: "120px"
>   }
> }
> ```

I found that not work for me, the column will have style width with calc(xxxx),
![image](https://user-images.githubusercontent.com/13096729/129825166-dea7fb3f-0a66-4406-a40a-4f9c334035ae.png)

**Comment by chris-jalon** [comment]
@kirin-yuen It does seem unstable still, yes...
Look at my example here: https://codesandbox.io/s/cool-cohen-bif21?file=/src/App.js it appears to be working. Try switching the order, using `90` instead of `"90px"`, etc.
