### ISSUE TITLE
Filtering does not toggle checkbox if pressed on the text

### ISSUE THREAD

**Issue by jonasvag** [mbrn/material-table#299]
**Describe the bug**

**To Reproduce**
1. Go to https://mbrn.github.io/material-table/#/docz-examples-06-example-filtering
2. Expand 'Birth Place' checkbox filter.
3. Click on the title's text (but NOT on the checkbox itself), for example, 'Istanbul'.
4. See >> it activates filtering, but the checkbox remains unchecked.

**Expected behavior**
Checkbox toggles if a text is pressed. This is weird, cuz sometimes it is reproducible and sometimes not.

**Comment by mbrn** [comment]
Very strange bug:) Thanks @jonasvag ,

I will resolve it asap.

**Comment by jonasvag** [comment]
Did you test it on docs page?

**Comment by mbrn** [comment]
I didn't published it yet. I will publish it asap with new version. I think that it is not very urgent bug:)

**Comment by mbrn** [comment]
This is done with 1.22.3
