### ISSUE TITLE
materil-table filter value resets upon typing - re-render issue 

### ISSUE THREAD

**Issue by yogesh-wemotive** [mbrn/material-table#2990]
Hi all,
I faced the issue same as in https://github.com/mbrn/material-table/issues/160 and in https://github.com/mbrn/material-table/issues/729 related to prevent resetting of filter value upon typing.

I tried the solution specified by @mbrn here https://github.com/mbrn/material-table/issues/160#issuecomment-456765643

Since I am using functional component that is why I tried in the following way.     
     
![Screenshot from 2021-08-23 11-56-28](https://user-images.githubusercontent.com/75840814/130404211-5e43bc28-ce41-4d45-91fe-45fd75b67423.png)

But unfortunately, after performing some filter app crashes saying memory leak.

![Screenshot from 2021-08-23 11-51-32](https://user-images.githubusercontent.com/75840814/130404258-98fc4265-11d1-490b-bd23-55fe6a806635.png)

Please help me to get solution for this.
Thanking You!

**Comment by dev-yogesh** [comment]
Hi @mbrn, 
Any guess or workaround?
Cheers...

**Comment by BhushanChandak** [comment]
I am also facing the same issue. can't find any solution. Any help will participate @mbrn
