### ISSUE TITLE
Material Table - Localization of the search

### ISSUE THREAD

**Issue by kadirtereci** [mbrn/material-table#2991]
**- `We are having trouble with the search part. Due to local letter conversions, the search does not give the desired results.** 

![img1](https://user-images.githubusercontent.com/46989233/130412948-2bc7b325-ebc0-4bb0-b655-74b3dce784e5.png)
`image1`

**As can be seen in the images I added, although there is a record named "ELİF"(image1), it can not be found when I type "elif" in the search field(image2).**

![img2](https://user-images.githubusercontent.com/46989233/130412924-90295b10-4e26-43c3-a6b3-648c35a45626.png)
`image2`

**- When I looked at the source codes, I saw that toUppercase was used in the search section. As a potential solution, I think toLocaleUppercase can be used here.**

![image](https://user-images.githubusercontent.com/46989233/130411191-c3536393-6b3d-448f-8c9c-12387d857d7b.png)

**Thank You**

**Comment by BugraTuncer** [comment]
++ same problem
