### ISSUE TITLE
How to sort the data by clicking column (not only text or icon)

### ISSUE THREAD

**Issue by tkk777** [mbrn/material-table#2994]
I would like to ask how to sort the data by clicking column?

it is because data cannot be sorted when I click the column (not on column text or icon).

Thanks.

**Comment by kadirtereci** [comment]
give all datas to material table. It can handle sort

**Comment by kadirtereci** [comment]
also if your column number dont forget to give type: 'numeric'

**Comment by tian-lan-landing** [comment]
If customized render function returns react components, sorting may not work. In this case you should set column.customSort like
```
columns={[
    { title: 'Birth Year', render: (row) => (<span class="birthYear">row.birthYear</span>), customSort: (a, b) => a.birthYear - b.birthYear },
  ]}
```
