### ISSUE TITLE
All checkbox filters be checked by default

### ISSUE THREAD

**Issue by jonasvag** [mbrn/material-table#300]
**Is your feature request related to a problem? Please describe.**
It would be nice to have an option to mark all checkbox filters as checked by default (on page load). Because now all checkboxes are unchecked by default...

**Comment by themausam** [comment]
Is there an ability to mark certain rows as selected when table is loaded?

**Comment by mbrn** [comment]
@jonasvag 

You can add defaultFilter property to your boolean column definition like this:

{ title: 'Evli', field: 'isMarried', type: 'boolean', defaultFilter: 'checked' }

**Comment by mbrn** [comment]
Hi @themausam ,

Just add  tableData: {checked: true} to row that you want to default selected.
