### ISSUE TITLE
how to add multiple rows ,when clicking on add button how many time we click that many add rows need to display

### ISSUE THREAD

**Issue by saimohan12345** [mbrn/material-table#3006]
# Guidelines

- #### Please include a demo of the issue/behavior/question you have

- #### Please try to be as detailed as possible

- #### You may fork one of the following starter templates if you would like:

  - #### [CodeSandbox](https://codesandbox.io/s/material-table-starter-template-xnfpo)
  - #### [StackBlitz](https://stackblitz.com/edit/material-table-starter-template)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nvlong198** [comment]
I have the same question.
