### ISSUE TITLE
Change row icon for false value

### ISSUE THREAD

**Issue by mononobi** [mbrn/material-table#3008]
Hello

Thank you for your awesome material-table.
I need to change the default icon for boolean columns with false value which is "__" into another icon.
but I can't find any related settings for this icon in "icons" config of material table, is there anything like "Check" for false values?

Thanks in advance

**Comment by kadirtereci** [comment]
Hi,

Do you want to show something like that?

![true-false](https://user-images.githubusercontent.com/46989233/134671623-692b5757-9d01-4107-9721-99703e7b57b6.png)

**Comment by mononobi** [comment]
> Hi,
> 
> do you want to show something like this?
> 
> ![true-false](https://user-images.githubusercontent.com/46989233/134671623-692b5757-9d01-4107-9721-99703e7b57b6.png)
> 

Yes, exactly
