### ISSUE TITLE
Add tabs to the table

### ISSUE THREAD

**Issue by jonasvag** [mbrn/material-table#301]
**Describe the solution you'd like**
I would like to be able to add several tabs to the table, as described here:
https://material-ui.com/demos/tabs/
It would be really useful to display well-structured information.

**Comment by mbrn** [comment]
Why you don't add tables in tabs ?

**Comment by jonasvag** [comment]
Yeah, it might work.
Thus, I may come back to this later if I find any issue in the future. Thanks.
