### ISSUE TITLE
Unknown characters are replacing tree expand icon and search area

### ISSUE THREAD

**Issue by harikrishnankh** [mbrn/material-table#3014]
I am using the material table for the tree data. Now I am seeing "ch" instead of the tree expanding icon and "se" in the place of search
![expand icon_error](https://user-images.githubusercontent.com/14846379/133303964-27e2d78d-0cc3-4369-88d8-18349339484e.PNG)
![search icon error](https://user-images.githubusercontent.com/14846379/133303968-3d606c96-74f4-44eb-8769-fb1586317847.PNG)
 icon. All default icons are showing this error. I tried to map it manually but it's is messing  up my code

**Comment by yoobi** [comment]
Hello, I have the same issue, am I missing something ?

I have done 
```
yarn add material-table @material-ui/core
yarn add @material-ui/icons
```

**Comment by bevanmw** [comment]
I also have this issue, here is a CodeSandbox with the issue: https://codesandbox.io/s/green-microservice-ovz0e

**Comment by bevanmw** [comment]
I fixed this by following the instructions in the README here: https://github.com/mbrn/material-table#2add-material-icons
