### ISSUE TITLE
Loading indicator not visible with a greater number of rows

### ISSUE THREAD

**Issue by igloocube** [mbrn/material-table#302]
**Is your feature request related to a problem? Please describe.**
Loading indicator (spinner) does not show on the screen when pageSize is of a large size as it is below the bottom of the visible area on the screen.

**Describe the solution you'd like**
Either change it to be aligned to the top not the middle of the table (verticalAlign) by default so it always shows regardless of row count, or allow us to apply a style here: https://github.com/mbrn/material-table/blob/637cb03fe38466bcba5a2d3b92112b53108c6a66/src/material-table.js#L377

**Describe alternatives you've considered**
Two solutions above

**Additional context**
None

Thank you :)

**Comment by mbrn** [comment]
Hi @igloocube ,

I will align it to top. You are right. Thanks.

**Comment by mbrn** [comment]
Hi @igloocube ,

You can override OverlayComponent in component to create overlay according to your requirement.

**Comment by mbrn** [comment]
This is done with 1.35.2
