### ISSUE TITLE
Support MUI 5

### ISSUE THREAD

**Issue by SaeedBoroo** [mbrn/material-table#3023]
# MUI 5
I have an error. when I update MUI to version 5. `Material-Table` needs `@Material-ui/icons` but in MUI 5 we haven't this. 
[**mui5 ---> @mui/icons**]
please update...

**Comment by perosa100** [comment]
will there be an update for mui 5?

**Comment by gabizz** [comment]
> will there be an update for mui 5?

This is Mehmet's decision. We should ask him :)

**Comment by AlexThurston** [comment]
Just as a word of warning, we switched to MUI 5, and there is something with the way that MUI and Material Table handle CSS that causes much of the MUI CSS to be overridden by what has been done in Material Table.  I'm not sure what the solution is, but (and certainly if you are using react router) this causes the application to behave very strangely.

What is looks like normally:
![image](https://user-images.githubusercontent.com/3537360/134441999-cf4ef3dc-4605-438f-a0ea-157ef746003e.png)

What it looks like once I load a page with a Material Table:
![image](https://user-images.githubusercontent.com/3537360/134442032-e78e41cc-7ffa-4f7c-9e02-cc1cbbdc244c.png)

**Comment by Jucabel** [comment]
If you look in yarn, MT has not been updated for a while (22 weeks), so, personally I will test this:

[https://mui.com/components/data-grid/getting-started/](https://mui.com/components/data-grid/getting-started/)

after that I'll decide if it is worth the migration.

**Comment by cc-greglorenzen** [comment]
I went through migration steps as outlined here: [](https://mui.com/guides/migration-v4/) and wasn't able to get it working. I had issue with the material-ui icons library as well. There was a certain point where I was at least able to get it to compile, but even then, I had similar CSS issues that @AlexThurston mentioned above.

I'm just going to leave the migration unfinished on a separate branch on my project, and come back to it if material table ever gets updated. Once tree data gets added to mui/x-data-grid (whenever that may be), I may pull the trigger on MUI pro if MT isn't updated by then.

**Comment by AlexThurston** [comment]
I ended up biting the bullet and just spending the afternoon required to convert all our material-table usage to data-grid and implementing what needed to be implemented to have the same behaviour.

It ended up not being all that difficult.

**Comment by cc-greglorenzen** [comment]
> I ended up biting the bullet and just spending the afternoon required to convert all our material-table usage to data-grid and implementing what needed to be implemented to have the same behaviour.
> 
> It ended up not being all that difficult.

Are you using the pro version of data grid?

**Comment by AlexThurston** [comment]
Nope.

**Comment by Jucabel** [comment]
> I ended up biting the bullet and just spending the afternoon required to convert all our material-table usage to data-grid and implementing what needed to be implemented to have the same behaviour.
> 
> It ended up not being all that difficult.

I did the same, I find it the best way to go with.

**Comment by hutber** [comment]
So I guess the answer is, it cannot work with v5? And I need to drop this package right? @Jucabel
