### ISSUE TITLE
Column sorting, paginated data

### ISSUE THREAD

**Issue by Capototo** [mbrn/material-table#3024]
Hi!

I'm having problems sorting data by clicking on any column because i have paginated data. How can i do custom sort?
I've read [docs](https://material-table.com/#/docs/all-props) but customSort in columns isn't working.

**What i want is to set a variable when click on the header of any column.** 

After that, this variable is sent to backend and i get new data.

Here is the code when i want to set the variable by clicking the header of a column:

`    {title:'Código',field:'codigo',
      customSort: () => {setColumna("codigo")}
    }`

Thanks!

**Comment by ouya99** [comment]
@Capototo 

i had to solve the same problem.

`   
          components={{
            Header: props => (
              <MTableHeader {...props} onOrderChange={this.handleSortOrderChange}  />
            )
          }}
`

gives you access to the order event, in handleSortOrderChange you add your custom code.
