### ISSUE TITLE
Vulnerabilities found in dependency library jspdf@2.1.0

### ISSUE THREAD

**Issue by JenniferX** [mbrn/material-table#3026]
Security scan found a Vulnerability issue (Regular Expression Denial of Service (ReDoS) in the dependency library jspdf@2.1.0.
Upgrade to jspdf@2.3.1 may resolve the Security Concern.

![material-table](https://user-images.githubusercontent.com/13933174/134574232-5252af91-1c37-4511-a5be-de0dc035f782.PNG)

**Comment by lucasgonze** [comment]
See https://github.com/material-table-core/
