### ISSUE TITLE
How to customize the button in the start position?

### ISSUE THREAD

**Issue by quocbaondvn2000** [mbrn/material-table#303]
![2019-03-12_084505](https://user-images.githubusercontent.com/45376591/54095460-08bc4b00-43da-11e9-85de-21560ddc46d0.jpg)
thanks

**Comment by quocbaondvn2000** [comment]
And I want to be able to format the fixed height of the table
![2019-03-12_084505](https://user-images.githubusercontent.com/45376591/54095573-90a25500-43da-11e9-97f2-2dbfdcce870a.jpg)
Demo: https://codesandbox.io/s/43ml13vq19

**Comment by mbrn** [comment]
Do you want to add styles to columnsButtons and exportButton?

`And I want to be able to format the fixed height of the table`
Duplicate with #19

**Comment by quocbaondvn2000** [comment]
I have followed your instructions
But not working
This is my code

<MaterialTable
          components={{
            Body: props =>
              (
                **<div style={{ height: 200, width: '100%' }}>**
                  <MTableBody {...props} />
                </div>
              ),
          }}
....

/>

A
![2019-03-11_141734](https://user-images.githubusercontent.com/45376591/54106375-7ed7a680-4408-11e9-83b1-c4af3a1f2ce0.jpg)
nd it displays like this
