### ISSUE TITLE
Trying to remove onPageChange warning

### ISSUE THREAD

**Issue by even996** [mbrn/material-table#3036]
Hi!
Am trying to remove this warning.

vendors~main.chunk.js:281042 Warning: Failed prop type: The prop onPageChange is marked as required in ForwardRef(TablePagination), but its value is undefined.
at TablePagination (http://localhost:3000/static/js/vendors~main.chunk.js:91674:37)

Everything else works just fine.
Am using @material-ui/core 4.11.4 and material table 1.69.3

I think its somewhere here i need to add onChangePage but am not sure how.

![image](https://user-images.githubusercontent.com/33283405/136379051-b7d290e3-175b-4eba-b77e-13fc2abe2f40.png)

`<MaterialTable icons={tableIcons} title="Lines status list" data={listData} columns={columns} />`

Thanks in advance :)

**Comment by RanjithR94** [comment]
vbnh

**Comment by RanjithR94** [comment]
i'm also tring to do that in 2023, still unncessary warning msg is coming in console log
