### ISSUE TITLE
MTableSteppedPagination export

### ISSUE THREAD

**Issue by manolo-battista** [mbrn/material-table#3038]
# Guidelines

**Describe the bug**

material-table has a `MTableSteppedPagination` the component is not export from the package.

This problem was present also in the old [material-table](https://material-table.com/#/)

**Screenshots**
![material-table](https://user-images.githubusercontent.com/81776297/136563559-b16a21a0-b902-441c-98ef-bd2410be168a.png)

**Comment by mattvioli** [comment]
Has there been any update on this one?

**Comment by mattvioli** [comment]
@manolo-battista 

I used imported it directly from components to get around it, adding a ts-ignore for the type issue.

`// @ts-ignore
import MTableSteppedPagination from 'material-table/dist/components/m-table-stepped-pagination';`
