### ISSUE TITLE
Can I use this "material-table" module in material-ui v5?

### ISSUE THREAD

**Issue by mr-new-0509** [mbrn/material-table#3041]
Hello. How are you?
I am building a website using Material-UI v5.
I wanted to use "material-table" module so I imported it.
But it occured the error like as following.

./node_modules/@material-ui/pickers/esm/_shared/ToolbarText.js
[1] Attempted import error: 'fade' is not exported from '@material-ui/core/styles'.

The version of "material-table" module is "1.69.3".
Could you please help me?

**Comment by mr-new-0509** [comment]
Thanks.👍

**Comment by arendeutsch** [comment]
@orinoco I can't seem to make it work even with this fork ? does it still work or has it been changed since october ?

**Comment by pdkovacs** [comment]
@arendeutsch 

> I can't seem to make it work even with this fork ? does it still work or has it been changed since october ?

You have to use the experimental branch for MUI v5 support:

```
npm install @material-table/core@next
```
