### ISSUE TITLE
Community fork (since this is deprecated)

### ISSUE THREAD

**Issue by Domino987** [mbrn/material-table#3044]
Hello everybody, since the maintainer abandoned this project and he is the only one who can merge PRs, we created a community fork with many bug fixes, changes and Muir v5 support as well.

If you have problems or requests for this project, check it out at [material-table-core](https://github.com/material-table-core/core).

**Comment by harshadajog** [comment]
Thanks for taking care of it! Its a very useful library

**Comment by DineshPrakasam** [comment]
in material table tree view while adding child component under a parent component,need to show that child component after adding in expansion.but it is getting as collapsed,(requirement is after adding child it should be expanded) ,kindly anyone help me on this,thanks.

**Comment by itsmemyk** [comment]
Looking for a maintained alternative? I've been building react-tree-grid — it covers Grid, Tree, and TreeGrid with sorting, grouping, drag-to-group, virtualization, and frozen columns. It's actively maintained and has a live demo at https://itsmemyk.github.io/react-tree-grid/
