### ISSUE TITLE
grouping with custom render not working

### ISSUE THREAD

**Issue by sinclas** [mbrn/material-table#3046]
HI,

If I apply a render for a specific column,  the groupby seems to work for the grid, but the group title for each section is blank.  If I remove the render code, it appears.   Is there a group renderer that is different from the row?

ie. render: rowData=>this.formatStatusCol(rowData.status),
(The status is a code and this will display a font color depending on the status.  This will cause the group by subsections to display blank.

Thanks,
Steve

**Comment by ryjogo** [comment]
try:
```
render: (row) => {
const status = rowData.status ? rowData.status : rowData
return (this.formatStatusCol(status))
}
```

**Comment by ryjogo** [comment]
actually, ignore that - there is a solution here;
https://github.com/mbrn/material-table/issues/1577
