### ISSUE TITLE
How to keep state edit mode

### ISSUE THREAD

**Issue by phuoctrung-ppt** [mbrn/material-table#3047]
When starting edit mode. Open dialog editing, but at here, edit mode cancelling. I try set tableData.editing = update, that working. But i have some issue relate to edit mode on material table. 
How to keep state edit mode, disable all rows except row edit when open dialog?

**Comment by ShoshanaTzi** [comment]
I also got this problem, do you have any idea?

**Comment by EmberDuong** [comment]
Same problem too

**Comment by rehaanredkar15** [comment]
Did anyone found a fix for this Problem?

**Comment by edoLtomo** [comment]
Hi, is there anyone can have alternative solution?
