### ISSUE TITLE
Material Table doesn't keep state edit mode when opening dialog

### ISSUE THREAD

**Issue by phuoctrung-ppt** [mbrn/material-table#3048]
# This is my sandbox to reproduce 

https://codesandbox.io/s/so-material-onclick-edit-forked-3w97o?file=/src/App.js

**Describe the bug**
When opening dialog, edit mode of material table disappeared. This issue happen when editing data, not happen on add new data 
**To Reproduce**

1. Click edit button on material table
2. Click on field ( sur name field ) >> dialog open
3. Observable edit mode on material table is disappeared

**Expected behavior**
When open dialog with mode edit. Please keep state edit on material table
**Screenshots**
![image](https://user-images.githubusercontent.com/57030690/138827671-e820d934-39c6-4827-b59d-9aa576503656.png)

doesn't happen on add mode
![image](https://user-images.githubusercontent.com/57030690/138827739-5d01c52a-959f-4b3f-b5bc-945883e6edec.png)

**Comment by EmberDuong** [comment]
I have the same problem. When open some dialog edit mode on material table is disappeared. Can someone help?
