### ISSUE TITLE
Type script update - add sortDirection parameter to customSort function

### ISSUE THREAD

**Issue by tian-lan-landing** [mbrn/material-table#3054]
**Is your feature request related to a problem? Please describe.**

No issue, only type update.

**Describe the solution you'd like**

Add optional parameter `sortDirection` to the `customSort` function [here](https://github.com/mbrn/material-table/blob/b7474ca0f5497f04ff3a3d50e709d86de7c639b0/types/index.d.ts#L159).

```diff
  customSort?: (
    data1: RowData,
    data2: RowData,
-   type: "row" | "group"
+   type: "row" | "group", 
+   sortDirection?: "desc",
  ) => number;
```

**Describe alternatives you've considered**

The data manager is actually passing three parameters or passing the fourth parameter with "desc", see codes [here](https://github.com/mbrn/material-table/blob/b7474ca0f5497f04ff3a3d50e709d86de7c639b0/src/utils/data-manager.js#L553-L556), so the type is currently `sortDirection?: "desc"`. But it may be more comprehensive if the sortDirection is `"asc" | "desc"`.

**Additional context**

I want the sort direction because I want some records to always be on the top.
https://codesandbox.io/s/material-table-starter-template-forked-vhgps?file=/src/index.js

It works even in typescript without the proposed change, but it's better if hints comes from typescript itself.

**Comment by JeomJeom** [comment]
@tian-lan-landing Could you reopen this issue? I'm looking for this feature as well. Your solution really helps
