### ISSUE TITLE
How to avoid default sorting on Grouped Column?

### ISSUE THREAD

**Issue by Hemasai-k** [mbrn/material-table#3059]
When using defaultGroupOrder it seems defaultGroupSort is getting applied as asc by default.
I do not want to apply any sorting and need to display data as it comes.
How to avoid default sorting on Grouped Column?

**Comment by johannesstenberg** [comment]
@Hemasai-k Hello. I've faced the same issue and found  a solution. Put this in the column options:
`customSort: () => 0`

This prevents the group from being sorted as asc by default.

**Comment by Hemasai-k** [comment]
@johannesstenberg It Worked 👍 ,Thanks for the solution

**Comment by rhythm-3099** [comment]
@Hemasai-k does this work when there are multiple row groupings applied?
