### ISSUE TITLE
Issue with filtering unchecking using the remote data option

### ISSUE THREAD

**Issue by roseak** [mbrn/material-table#306]
**Describe the bug**
When using remote data, the filters clear on page load with the new data.  Would be nice to be able to select multiple filters to be sent when remote filtering.

**To Reproduce**
Use server side pagination for data, then try to filter based on lookup. When the data has reloaded, the checkbox is undone.

**Expected behavior**
The checkbox stays checked and you can select multiple as you can when not doing server side data.

**Comment by roseak** [comment]
Also noticed that the filter is persistent till you select another filter, but you're unable to uncheck the current filter to just see all the results, so being able to uncheck the filter box would also be 👌

**Comment by mbrn** [comment]
This is done.
