### ISSUE TITLE
is there a way to migrate form material ui  V 4 to V 5 ? 

### ISSUE THREAD

**Issue by ramdaniAli** [mbrn/material-table#3061]
Hi, I wanted to know if material-table can support Material Ui 5?  
Otherwise is there a way of migrating to material Ui 5 ?

**Comment by ramdaniAli** [comment]
@mbrn  hi I  can help for this if you want to ,  I have already done the migration, but I am having difficulty making a pull request.

**Comment by njlochner** [comment]
@ramdaniAli It looks like this project has been abandoned. There is an active community fork at https://github.com/material-table-core/core

**Comment by ramdaniAli** [comment]
@njlochner thanks

**Comment by olex-green** [comment]
> @ramdaniAli It looks like this project has been abandoned. There is an active community fork at https://github.com/material-table-core/core

The community fork doesn't work with V5 - currently is crushing.
