### ISSUE TITLE
How to replace icon for columnResizable?

### ISSUE THREAD

**Issue by git2467** [mbrn/material-table#3064]
Hi all,

**Context**
I am using React Typescript MaterialTable, and i wanted the columns to be resizable.
I managed to do so by setting the option property "columnResizable: true".

**Problem**
However, the icon is a distorted letter instead as shown below:
![image](https://user-images.githubusercontent.com/71249221/142384672-b13f02b1-f998-47d8-97b2-f5ab715c5264.png)

**Question**
It seems different from tableIcons. Do i need to install a specific version of "@material-ui/icons"?
Appreciate if anyone can help me and thank you in advance!

**Code**
` <MaterialTable
          icons={tableIcons}
          ...
          options={{
            columnResizable: true,
          ...
          }}`

**Comment by rudiwawa** [comment]
i have tried several versions of material-table, and i decided to use the version of "material-table": "1.60.0" for width setting

`     {
                title: 'status',
                field: 'status',
                width: 130,
                editComponent: ({ value, onChange }) => (
                  <TextField
                    select
                    value={value}
                    onChange={(e) => onChange(e.target.value)}
                  >
                    s
                    {enumOfStatus.map((val) => (
                      <MenuItem key={val} value={val}>
                        {val}
                      </MenuItem>
                    ))}

                  </TextField>
                ),`

**Comment by git2467** [comment]
> i have tried several versions of material-table, and i decided to use the version of "material-table": "1.60.0" for width setting
> 
> ![image](https://user-images.githubusercontent.com/26498067/142589923-76f51491-3d2f-41f2-89a3-71c6076f5229.png)

Hi, thaank you for your reply. However, it is not the answer that i am looking for.

I would like to let the user adjust the column dynamically, which is why I am using the option property "columnResizable: true".
This option property works, but a rotated "d" icon appears (refer to my original post).
I hope to replace this specific icon with something more pleasing.

**Comment by git2467** [comment]
Okay managed to solve this issue after looking thru the source code.

**Solution**
Just like how tableIcons are imported in the material-table's README.md, simply:

import icon-of-your-choice from "@material-ui/icons/icon-of-your-choice";

const tableIcons = {
...
Resize: forwardRef((props, ref: React.Ref<SVGSVGElement>) => <icon-of-your-choice{...props} ref={ref} />),
...
};
