### ISSUE TITLE
onRowUpdate does not stay in edit mode if promise is rejected for any version after 1.58

### ISSUE THREAD

**Issue by HaullingLlama** [mbrn/material-table#3068]
#2516 is another bug for this that was closed by the stale bot which served only to keep a bug in the code.

- Following sandbox and change the material-table version to 1.59 or greater
https://codesandbox.io/s/materialtabledemo-validation-error-kgnww?file=/package.json 

- Detailed Repro Steps
If you open this sandbox which is locked into version 1.56.1, edit a row and empty the name column, save changes, the row will stay in edit mode with error message. This works all the way through ~1.58.0 but breaks after that.
NEXT
in the package.json change the material table version to ^1.56.1 (latest version of 1 but any version 1.59 or up has the issue), edit a row and empty the name column, save changes, the row exits edit mode and keeps the old data.

Expected behavior would be what takes place in versions 1.58 or earlier. If when a row is being added and the onRowUpdate promise is rejected stay in edit mode... don't exit it.

There was a link saying it was fixed in #2592 but this cockroach has survived.

**Comment by edoLtomo** [comment]
Hi @HaullingLlama , do you find any solution for this issue? i am facing same situation here
