### ISSUE TITLE
Why are you not update material-table for mui 5?

### ISSUE THREAD

**Issue by simonsantan** [mbrn/material-table#3069]
I am using material table in my many projects. But I am not able to use it with mui 5. Why are not update this material-table for mui 5?

**Comment by milespop** [comment]
Why don't you do it?

**Comment by faizanarif196** [comment]
Because I am not a senior developer. I just only only use it:)

**Comment by sm3sher** [comment]
> Because I am not a senior developer. I can just use it:)

I would recommend using this: https://github.com/material-table-core/core
It's basically the same and support MUI5.
