### ISSUE TITLE
How to render the action column in a material table with a customized header and row

### ISSUE THREAD

**Issue by git-khione** [mbrn/material-table#3071]
I have this material table with a customized header since I wanted to split columns and rows....  so for that what I did is override the material table header and the row

[https://codesandbox.io/s/inspiring-christian-rmj4g?file=/src/App.js:4278-7859](https://codesandbox.io/s/inspiring-christian-rmj4g?file=/src/App.js:4278-7859)

The problem now have now is.. once I add data to my material table, the edit and delete buttons aren't there since I haven't called the action column
![image](https://user-images.githubusercontent.com/46352201/144698696-39785f98-1533-4fb0-adfb-2f1bd5c522df.png)

Does anyone know how to call the action column

@VLRTroll @macsee @NearHuscarl @doctorallen @jahredhope

**Comment by git-khione** [comment]
Nevermind figured it out

**Comment by jahredhope** [comment]
I'm glad you figured it out.
Would you consider adding what the solution to your message? Others may stumble across this thread with the same question.
