### ISSUE TITLE
How to set selected all as default?

### ISSUE THREAD

**Issue by weilinzung** [mbrn/material-table#3074]
How to set `selected all` as default?

Also,
I can only see `selectionProps` has disabled, but not selected?

thanks!

**Comment by ShariqKhan2012** [comment]
`showSelectAllCheckbox` is the relevant property, but is `true` by default, if you have enabled selection. Unless I am not understanding your question correctly.

**Comment by weilinzung** [comment]
I mean select all items by default. I have figured out by using other method.
