### ISSUE TITLE
Is there a way to change the size of the filter pop up? 

### ISSUE THREAD

**Issue by aaronboyd92** [mbrn/material-table#3078]
![Screenshot 2021-12-09 at 12 47 06](https://user-images.githubusercontent.com/17007038/145391116-baaca3e7-17fd-4ea6-afde-68b485476618.png)

I am wondering if I can change the size of this popup window. I have tried to look through the components to override but I haven't been able to find the correct one. 

Thanks!

**Comment by Eserkani** [comment]
hi  aaronboyd92
did you find your answer for your question ?? @aaronboyd92
