### ISSUE TITLE
Unexpected behavior when grouping and selection options are both enabled on version > 1.18.0

### ISSUE THREAD

**Issue by jjdstr** [mbrn/material-table#308]
**Describe the bug**
With `options={{ selection: true, grouping: true, }}`, there is an unexpected behavior change recently.
On 1.18.0, the selection checkbox works fine without collapsing the groups.
On the newer versions, they will collapse and make it harder to use.

**To Reproduce**
1. Go to https://codesandbox.io/s/j79j586k4w
2. Click on the groups to expand them
3. Click on any of the selection checkboxes
4. Note that all the groups collapse 
5. (to see that it works fine on 1.18.0) Change the material-table dependency to 1.18.0 and repeat step 2 and 3 above 

**Desktop:**
 - OS: Windows, Chrome OS
 - Browser: Chrome
 - Version: 72.0.3626.121

**Comment by mbrn** [comment]
This is done with 1.23.2
