### ISSUE TITLE
Allow customising the detail panel expanded icon when open and closed

### ISSUE THREAD

**Issue by bevanmw** [mbrn/material-table#3081]
When setting the DetailPanel icon for grouped data the icon just rotates. I would like to be able to specify a different icon for when the detail panel is open without rotation. In my use case I would like to have a + icon when the group is closed and a - icon when the group is open.

I would like to have 2 icons that can be specified, one for when a detail panel / group is open and one for when it is closed.

**Comment by dbgordon09** [comment]
This is desperately needed for a project we are working on as well! @mbrn 🙏
