### ISSUE TITLE
Material-ui style loss when material-table rendered

### ISSUE THREAD

**Issue by Kibergx** [mbrn/material-table#3089]
I have an issue like in this report: https://github.com/mbrn/material-table/issues/773
So when I render the MaterialTable all of my styles breaking (the blue background changing to white in all other material-ui components). I am not using themreproviders, just the react starting project with material-ui.

But nothing solving me the problem, just to downgrading material-table version in my project's package.json:
"material-table": "1.36.0"

That's it, I could not find any other solution. I tried match the material-ui version with the material-table's material-ui version like in the linked report, but it not helped.

Please give me a suggestion how can I solve this problem with the new material-table version. Thank you!

**Comment by relativelyrehan** [comment]
Same problem, As soon as I change the data props in the table, the table lost all of the styling. Then If I refresh the page, it starts to work again fine.
