### ISSUE TITLE
Custom actions missing in version 1.23

### ISSUE THREAD

**Issue by mariolazzari** [mbrn/material-table#309]
**Describe the bug**
After last updates, I loose all my custom actions (both free and row ones). Downgrading to material-table": "^1.22.3" all actions are fine.

I noticed that action section of documentation is affected by this issue.
See hereby attached screenshot (missing circled icon)

![image](https://user-images.githubusercontent.com/26960147/54209193-a0569200-44dd-11e9-9af9-8dff1c23f221.png)

**Comment by rbeers** [comment]
All mine disappeared too.

**Comment by mbrn** [comment]
This is done with 1.23.1
