### ISSUE TITLE
material-table  >=1.63.1 depends on vulnerable versions of jspdf

### ISSUE THREAD

**Issue by emilschultz** [mbrn/material-table#3090]
Hi,

We are using material table in a React app in our organization. We are doing a major security update and found this voulnerability related to material-table.

As mentioned in the title, material-table  >=1.63.1 depends on vulnerable versions of jspdf.

This is the precise warning i get in my terminal when running an audit: 

`jspdf  <2.3.1
Severity: high
Regular Expression Denial of Service (ReDoS) - https://github.com/advisories/GHSA-57f3-gghm-9mhc
fix available via npm audit fix --force
Will install material-table@1.63.0, which is a breaking change
node_modules/jspdf
  material-table  >=1.63.1
  Depends on vulnerable versions of jspdf
  node_modules/material-table`

Setting material-table to @<=1.63.0(or by running `npm audit fix --force`) causes the build to fail.

Can you help with this?

Best,
Emil Schultz

**Comment by JJ-M** [comment]
We are seeing the same issue.

Unfortunately we have a policy where I am unable to put live code that has High and Critical dependences in npm audit, so I think this is a bug, and not a question, and I hope a quick change to increment the version is possible....

Best regards,
JJ

**Comment by JJ-M** [comment]
Just seen the community fork of this repository so will look to upgrade to that ....

Thanks,
JJ
