### ISSUE TITLE
HeaderStyle color not working with sorting true

### ISSUE THREAD

**Issue by nlafleur** [mbrn/material-table#3101]
I want to render a MaterialTable, and style the header with a blue background, with white text.
I've included the following options in my MaterialTable:

```
options={{
  draggable: false,
  emptyRowsWhenPaging: false,
  maxBodyHeight: "100%",
  paging: false,
  search: false,
  sorting: true,
  showTitle: false,
  thirdSortClick: false,
  toolbar: false,
  headerStyle: {
    backgroundColor: theme.palette.primary.main,
    color: theme.palette.primary.contrastText,
    padding: theme.spacing(1.5, 1)
  }
}}
```
theme.palette.primary.main = "#007CC0", with the contrastText = "#FFFFFF"

This initially renders the table correct, blue header background with white text.
But when you sort a column, or hover the header, it turns black.

**To Reproduce**
This also happens in the official MaterialTable examples:
https://material-table.com/#/docs/features/styling > "Cell Header Styling Example"
The font color is white, when you hover the header, it turns black.

I tried to fix it with my custom header component.. but this does not accept classNames, example:
```
components={{
  Header: props => {
    return (
      <MTableHeader {...props} className={classes.tableHeader} />
    )
  }
}}
```
This way I cannot reach the sort label (span)

**Comment by smohit02** [comment]
Is there any workaround to this issue yet?
To prevent the font from turning black and to keep the font to###  follow the color that's been set in the **headerStyle** upon hover and on selecting sorting.

**Comment by nlafleur** [comment]
> Is there any workaround to this issue yet? To prevent the font from turning black and to keep the font to follow the color that's been set in the **headerStyle** upon hover and on selecting sorting.

Hi, I switched to the MUI DataGrid, easy to use, comparable with this material-table package
