### ISSUE TITLE
Vulnerable issue with JsPdf v2.1.0

### ISSUE THREAD

**Issue by nmanthena18** [mbrn/material-table#3103]
# Guidelines
- #### Having vulnerable issue with severity is high

**Describe the bug**
Material table internally using the jsPDF v2.1.0 package which having vulnerable issue, this was fixed in jsPDF v2.5.1.
but Material table still using the old version of jsPDF, probably need to upgrade the version, but not sure about the impact for the upgrade.

**To Reproduce**

1.  npm init 
2.  npm i material-table
3.  npm audit --json 
3. Scroll down to  the report 
**{
      "findings": [
        {
          "version": "2.1.0",
          "paths": [
            "material-table>jspdf"
          ]
        }
      ],
      "metadata": null,
      "vulnerable_versions": "<2.3.1",
      "module_name": "jspdf",
      "severity": "high",
      **

**Expected behavior**
No vulnerable issues should be there

**Additional context**

**Comment by rullymartanto** [comment]
any update on this?
