### ISSUE TITLE
Is it possible to only allow one lookup option at a time

### ISSUE THREAD

**Issue by hvalola** [mbrn/material-table#3105]
# Guidelines

At the moment lookup getting populated  from backend request on my application(typescript application)
                     { title: "Role", field: "role" ,lookup: roles ,width:250,},

by default multiple options can be selected from lookup

![image](https://user-images.githubusercontent.com/13590947/152961771-21017a79-3d5c-46ba-a007-95920855e89b.png)

But the requirement is to only allow one option to be selected

How to implement this.
Note: onFilterChange not working

**Comment by Domino987** [comment]
You could simply override the component and render a custom react component yourself with your custom logic. Render for normal cells, editComponent for edits and filterComponent for the filter row. All in the column object.
