### ISSUE TITLE
Get Filtered Data

### ISSUE THREAD

**Issue by francieleportugal** [mbrn/material-table#311]
I'm trying to get the filtered data from the table, but I can't access it. How could I have access to it? I´ve searched in the doc but did not find anything about it. 
In react-table I could do something like this: 
`this.reactTable.getResolvedState().sortedData;`

It has something similar this react-table function?

**Comment by mbrn** [comment]
Unfortunately. But i will add some functions like this to let users to protect state.

**Comment by tg970** [comment]
Hi, @mbrn just checking in on this. Getting the filtered data would be awesome!! Thanks for everything, this is a great project!

**Comment by PhilSchwerttraeger** [comment]
Hey @mbrn, love this project! And I am also looking forward to this feature. Would be really great to have access to the filtered data in an comfortable way.

**Comment by tylercaceres** [comment]
try looking at my post in #752 [My Workaround](https://github.com/mbrn/material-table/issues/752#issuecomment-564137746)
I used ref.
I know this isn't the solution you're looking for, but it did work for me.
(sorry for the bad formatting in the post too)

**Comment by JimiSweden** [comment]
I found this thread today and have now worked on and tested two working solutions that probably is what you want, so I thought I should share it =)

**Option 1** - listen for changes in MaterialTable.state.data  with reference. (useRef, and UseEffect)
**Option 2** - built in MaterialTable.onSearchChange combined with reference to MaterialTable.state.data
 **note, I have included 2 flavors of option 2.** 

Thanks @tylercaceres for the example you provided, it didn't fit for me but gave me a hint on how to do it.

Code is found here: [MaterialTableGettingHoldOfRenderData.js](https://gist.github.com/JimiSweden/efa79ca1ff5dc1113ec93f96cd3e4440)
material-table example getting filtered data, the tables current view data, including 2 options and some other examples of actions/buttons, how to use SvgIcon from Material-UI
