### ISSUE TITLE
Filtering prop no longer works.

### ISSUE THREAD

**Issue by skearney414** [mbrn/material-table#3118]
Hi there, 
Since the latest update it seems that the filtering prop no longer works when set to true. 
When this is true, this.tableContainerDiv is null within componentDidMount. If i comment out filtering then the table loads correctly.
Any ideas on this issue ? 
Thanks
<img width="798" alt="Screenshot 2022-03-21 at 20 51 46" src="https://user-images.githubusercontent.com/64700854/159361785-02b2eaf7-74bc-40b2-8a58-a22c61d4e13b.png">

<img width="1018" alt="Screenshot 2022-03-21 at 20 49 22" src="https://user-images.githubusercontent.com/64700854/159361459-a4f22362-4db2-4100-a942-fd52c28e6a7b.png">

**Comment by Domino987** [comment]
You could try the community fork material-table-core

**Comment by skearney414** [comment]
Thanks @Domino987 , Using the fork resolves the error
