### ISSUE TITLE
Add onChangeFilter handler

### ISSUE THREAD

**Issue by real-didi** [mbrn/material-table#312]
I've added custom inline editing to the grid and now when I change the filter I want to be able to reset editing row id.

It would be great if we can have onChangeFilter handler as we now already have change handlers for other grid actions. (or maybe I missing something and I can hook up to this event somehow now already)

**Comment by mbrn** [comment]
Sorry @real-didi ,

I didn't understand your requirements. Can you share code or explain with a piece of code?
