### ISSUE TITLE
will the same thing happen again? do we have to go back to mbrn?

### ISSUE THREAD

**Issue by rudiwawa** [mbrn/material-table#3123]
Since mbrn abandoned this project,so the community version of @material-table/core appears, but now mbrn is back and has launched version 2xx, should we use the community version or the mbrn version?

**Comment by Domino987** [comment]
It depends on how much mbrn is actually here again. We are roughly 1k commits ahead of the mbrn base branch prior to the AFAIK not working v2 update. We will keep the fork alive I think since a lot of work was done on it.
