### ISSUE TITLE
Migrating from v1.69.x

### ISSUE THREAD

**Issue by danyy1996** [mbrn/material-table#3125]
# Guidelines

- #### Please include a demo of the issue/behavior/question you have

We are currently using material-table v1.69.1. We noticed the package has been updated to v2.x (indicating there are breaking changes) however there is no Release, I couldn't find a Changelog or a migration guide. Can we have a list of the breaking changes and possible ways to migrate from v1.69.x?

**Comment by bamse16** [comment]
v2.x upgraded from `@material-ui` v4 to `@mui` v5 (same package, rebranded).

If you're using both in your project, it's probably safer to upgrade them both.

**Comment by danyy1996** [comment]
> v2.x upgraded from `@material-ui` v4 to `@mui` v5 (same package, rebranded).
> 
> If you're using both in your project, it's probably safer to upgrade them both.

Thanks for this. There's no other breaking changes with regards to props or anything like that? It's merely support for `@mui` v5?

**Comment by bamse16** [comment]
From what I'm seeing in the commit history, no.

Upgrade on a local branch and test it yourself.

**Comment by danyy1996** [comment]
> From what I'm seeing in the commit history, no.
> 
> Upgrade on a local branch and test it yourself.

Thanks!
