### ISSUE TITLE
Disabled checkboxes getting checked

### ISSUE THREAD

**Issue by gsandivya** [mbrn/material-table#3127]
I have disabled checkboxes for few rows. But, if we check 'Select All', even the rows for which selection was disabled, are getting checked.

**Comment by Ronnie434** [comment]
Can you try this? This one worked for me.
 options={{
                      selection: true,
                      selectionProps: (rowData) => {
                        rowData.tableData.disabled = rowData.name === "Mehmet";
                        return {
                          disabled: rowData.name === "Mehmet",
                          color: "primary",
                        };
                      },
                    }}

**Comment by gsandivya** [comment]
Thanks @Ronnie434, it worked for me. _material-table version : 1.69.3_
