### ISSUE TITLE
The peer dependency for @mui/styles is fixed at the specific version 5.5.0

### ISSUE THREAD

**Issue by CruseCtrl** [mbrn/material-table#3128]
In the [package.json](https://github.com/mbrn/material-table/blob/18f7cce93907ce75ead050eccfc86753f7acf00a/package.json#L97), the peer dependency for `@mui/styles` is set to `"5.5.0"` instead of `"^5.5.0"`, which forces any users of this library to use that specific version of `@mui/styles`. The latest version of `@mui/styles` at the time of writing is [5.6.0](https://www.npmjs.com/package/@mui/styles), which should still be compatible with `material-table`

Is there a reason to use a specific version like this, or shall I raise a PR to fix it?

It looks like @mbrn introduced this as part of the [mui5 upgrade](https://github.com/mbrn/material-table/commit/18f7cce93907ce75ead050eccfc86753f7acf00a#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R97)

**Comment by hnhegde** [comment]
Looks like PR [31467](https://github.com/mbrn/material-table/pull/3147) will fix this.
