### ISSUE TITLE
× TypeError: Cannot read properties of undefined (reading 'direction')

### ISSUE THREAD

**Issue by Hajin-dev** [mbrn/material-table#3130]
**Describe the bug**
material-table cause error because fail to read props.theme.direction
**To Reproduce**

I run material-table Demo code in sample page to test, but it failed.

My React App run like this 
index.js

- App.js
  - BrowserRouter
     - ThemeProvider theme={theme}
     - Container maxWidth="sm"
     - Navi //Navigation menubar
     - Routes
            └ Route path="/sampleTable" element={sampleTable} -> export default sampleTable.js;

And I set default theme with this (At app.js)

let theme = createTheme({
    typography:{
    "fontFamily":[
      'Open Sans','sans-serif'
    ].join(","),
  }
  }
);

**Expected behavior**
I thought props means default theme but there is no default direction argument so it causese error.

**Screenshots**
![image](https://user-images.githubusercontent.com/93587017/162421871-ee57ba33-79c2-4c02-a621-0b59acca3b64.png)

**Desktop (please complete the following information):**

- OS: Windows 10 19043.1586
- Browser MS Edge  100.0.1185.29
- Version material-table version 1.69.3
├── @fontsource/roboto@4.5.5
├── @material-ui/core@4.12.4
├── @material-ui/icons@4.11.3
├── lodash@4.17.21
├── material-table@1.69.3
├── nan@2.15.0 extraneous
├── react-dom@17.0.2
├── react-icons@4.3.1
├── react-router-dom@6.3.0
├── react-scripts@2.1.3
├── react@17.0.2
├── web-vitals@2.1.4
└── webpack@4.19.1

**Comment by Hajin-dev** [comment]
well I think I solve it.
Solution was so easy. I have to set property at material-table.
![image](https://user-images.githubusercontent.com/93587017/162551108-32ac4f15-036a-4b36-ac94-b934e01bd343.png)
`<Route path="/Amulet" theme={theme} element={<Amulet/>} />`

**Comment by THEO-184** [comment]
@Hajin-dev please can you elaborate much more on what property you set on the table?...I really need your help ASAP please?

**Comment by jhoanborges** [comment]
+1

**Comment by iliyanyotov** [comment]
+1, can you please elaborate on what this `direction` property is used for? RTL?

**Comment by mtrett** [comment]
I ran into this issue as well when making a whole bunch of updates to my libraries.
My project has a single js file that manages/returns MaterialTable that any other files call when they need it. In this I declared a theme and made it available to MaterialTable using ThemeProvider

```
import { createTheme, ThemeProvider } from '@mui/material';

export default function table(props) {

//sticking with default theme from @mui/material
const theme = createTheme();
const MtlTable = props => {
return (
//wrapping MaterialTable in ThemeProvider so that above theme is available to it
  <ThemeProvider theme={theme}>
    <MaterialTable />
  </ThemeProvider>
)}

return {
        MtlTable
    }
}
```
Since doing this I noticed some of the components of my material table look odd, likely because I'm pulling the theme from @mui/material instead of material-ui/core. I'll troubleshoot that as I go.

**Comment by rmehlinger** [comment]
This ticket should be reopened. While @Hajin-dev does indeed have a viable workaround, as @mtrett points out, it comes with some problems. and it is certainly non-obvious. cc @mbrn

**Comment by iwestlin** [comment]
I stucked on this problem all day, and it turns out that the cause is I used an different `ThemeProvider` than this project. 😅

I use the theme provider from `@mui/material/styles`
and the project uses `useTheme` from `import { withStyles } from "@mui/styles"`

Solutions (for me at lease...
- remove node_modules and lock file, reinstall dependencies. (I don't know why but this works...
- Or, something like:
```js
import { ThemeProvider } from '@mui/styles'
...
  const mytheme = {} // some valid theme
  return (
    <ThemeProvider theme={mytheme}>
      <MaterialTable
      ...
      />
```

**Comment by msn-well** [comment]
> I stucked on this problem all day, and it turns out that the cause is I used an different `ThemeProvider` than this project. 😅
> 
> I use the theme provider from `@mui/material/styles` and the project uses `useTheme` from `import { withStyles } from "@mui/styles"`
> 
> Solutions (for me at lease...
> 
> * remove node_modules and lock file, reinstall dependencies. (I don't know why but this works...
> * Or, something like:
> 
> ```js
> import { ThemeProvider } from '@mui/styles'
> ...
>   const mytheme = {} // some valid theme
>   return (
>     <ThemeProvider theme={mytheme}>
>       <MaterialTable
>       ...
>       />
> ```

Thansk! work for me

**Comment by gkowalc** [comment]
import { ThemeProvider } from '@mui/styles'
import { createTheme } from '@mui/material';
I was facing the same problem  and solution proposed by @iwestlin  solved the issue in my case: 
`const data = [
        { name: "Mohammad", surname: "Faisal", birthYear: 1995 },
        { name: "Nayeem Raihan ", surname: "Shuvo", birthYear: 1994 },
      ];
      const columns = [
        { title: "Name", field: "name" },
        { title: "Surname", field: "surname" },
        { title: "Birth Year", field: "birthYear", type: "numeric" },
      ];
      const mytheme =  createTheme({
      });

    return (
        <ThemeProvider theme={mytheme}>
        <MaterialTable title="Basic Table" columns={columns} data={data}/>
        </ThemeProvider>
      );`

**Comment by CarolinaHoffer** [comment]
> I stucked on this problem all day, and it turns out that the cause is I used an different `ThemeProvider` than this project. 😅
> 
> I use the theme provider from `@mui/material/styles` and the project uses `useTheme` from `import { withStyles } from "@mui/styles"`
> 
> Solutions (for me at lease...
> 
>     * remove node_modules and lock file, reinstall dependencies. (I don't know why but this works...
> 
>     * Or, something like:
> 
> 
> ```js
> import { ThemeProvider } from '@mui/styles'
> ...
>   const mytheme = {} // some valid theme
>   return (
>     <ThemeProvider theme={mytheme}>
>       <MaterialTable
>       ...
>       />
> ```

Thank you! May the universe grant you all your wishes, my friend.
