### ISSUE TITLE
The `fixedColumns` property is not working correctly

### ISSUE THREAD

**Issue by aatanasovwf** [mbrn/material-table#3132]
This is how the Material Table looks without using the `fixedColumns` prop. Notice that the first column is 'Name'.
![default](https://user-images.githubusercontent.com/104444088/165329864-383732b4-8335-4aa1-a1fb-a600ac75de90.png)

This is how it looks when I try to make the first column on the left fixed.
![bug11](https://user-images.githubusercontent.com/104444088/165333315-16daff5c-8617-4ff2-87b2-dd2f5e4af232.gif)

1. It is rendering the last column of the table 'Birth City' instead of 'Name'.
2. On resize the content of the fixed column changes with another part of the content of the table.
3. On resize the fixed column size changes from the non-fixed columns.

Here is the code to the example with dummy data

```
export const MuiTable = (): JSX.Element => {
    return (
        <MaterialTable
            columns={[
                { title: 'Name', field: 'name' },
                { title: 'Surname', field: 'surname' },
                { title: 'Birth Year', field: 'birthYear', type: 'numeric' },
                { title: 'Birth City', field: 'birthCity', lookup: { 34: 'Nashville', 63: 'California' } }
            ]}
            data={[
                { name: 'Rowan', surname: 'Chavez', birthYear: 1987, birthCity: 63 },
                { name: 'Christopher', surname: 'Mcleod', birthYear: 1987, birthCity: 63 },
                { name: 'Britney', surname: 'Hawes', birthYear: 1987, birthCity: 34 },
                { name: 'Gareth', surname: 'Bates', birthYear: 1987, birthCity: 63 },
                { name: 'Sam', surname: 'Rodriquez', birthYear: 1987, birthCity: 63 }
                ]}
            title="Demo Title"
            options={{
                fixedColumns: {
                    left:1,
                    right:0
                }
            }}
        />
    )
}

```

The same behavior appears when I try to fix two column on the left.
![bug2](https://user-images.githubusercontent.com/104444088/165333376-1abbc1df-855f-4a2a-b470-e2cc51312095.gif)

**Comment by AxelLR992** [comment]
I've copied your example and I can't reproduce the bug.
Which version of Material-UI are you using? Are you using the CssBaseline component in the root of your project? Do you have styles that can be affecting the behaviour of your material-table?
