### ISSUE TITLE
Is this Material Table compatibility with MUI 5 ?

### ISSUE THREAD

**Issue by jainprashul** [mbrn/material-table#3144]
Is this Material Table compatibility with MUI 5 ? 

As it based on material-ui.

**Comment by momolly1024** [comment]
Seems cannot work (Got many errors)

**Comment by NehaChaudhary311** [comment]
I'm working with "material-table": "2.0.3", and MUI5 and it's working for me. I'm facing a few styling issues though.

**Comment by jainprashul** [comment]
@NehaChaudhary311  How to you add icons ?

**Comment by hutber** [comment]
haha @NehaChaudhary311 how on earth are you working with v2?! The latest release is 1.69
https://github.com/mbrn/material-table/releases/tag/v1.69.0

**Comment by KalanaPerera** [comment]
@hutber what she says is correct: https://www.npmjs.com/package/material-table/v/2.0.3 , but little confused. 

@NehaChaudhary311 were you able to fix the styling issues? I am also having the same problem.

Whenever I use the Material Table component, other styles go away. :/
