### ISSUE TITLE
Add validation to inline edit. 

### ISSUE THREAD

**Issue by mbrn** [mbrn/material-table#315]

**Comment by jayarjo** [comment]
Is this not possible, via some kind of workaround?

**Comment by jayarjo** [comment]
From what I see `material-table` creates editable row in a TR, which makes it impossible to swap the whole editable row component with a form handler of some king. It's much easier that way of course, but probably makes more sense to have editable row as a detached generic container.

**Comment by ganeshr43** [comment]
This is an important feature! @mbrn have you picked this? If not, let me know, I will try to address this.
