### ISSUE TITLE
Add custom field component for inline edit. 

### ISSUE THREAD

**Issue by mbrn** [mbrn/material-table#316]

**Comment by orestes22** [comment]
Hi, Do you finished this?
Is there a option already to insert a Select component in a column that I want to Edit or Add ?

Best Regards

**Comment by mbrn** [comment]
Hi @orestes22 

I didnt started this issue yet. But if you add a lookup to your column definition it will draw a select instead of textfield

**Comment by orestes22** [comment]
It could be solutions for Select, and I will use it. Thanks !!!

However, Is there a way to Edit this Lookup, because the underline is appearing very short and I will add some color to the options. ?

**Comment by orestes22** [comment]
Also how Add color to the Actions buttons in the "Inline Edit option"

**Comment by mbrn** [comment]
After i publish this issue you can:). But now you can not

**Comment by orestes22** [comment]
Sorry for not understand very well, your answer is No, for my 2 questions?

**Comment by orestes22** [comment]
Kindly recommend to add in your next release in this area, the possibility to capture onClick in the "Add" button before happens.
Also create a a property to limit how many rows the user can insert.

**Comment by orestes22** [comment]
Im not going to use the Inline option, I will wait your release where I can style.
Best Regards

**Comment by mbrn** [comment]
Ok @orestes22 . I will consider your opinions. Thanks.

**Comment by orestes22** [comment]
Hi, isthere a solution in this feature ?

**Comment by mbrn** [comment]
> Hi, isthere a solution in this feature ?

Look at 3rd example.

**Comment by orestes22** [comment]
Good!!,, thanks!!,,,
