### ISSUE TITLE
Width issues with Actions column

### ISSUE THREAD

**Issue by sbacarob** [mbrn/material-table#3160]
**Describe the bug**
When using _actions_, the header cell respects some styling elements, but not all of them. For instance, text cannot be left-aligned. It will always be centered, even if `headerStyle` specifies `textAlign: 'left'`, which will work for all other columns.

Additionally, when `columnsButton` is set to `true`, column sizes seem to adjust automatically, except for the `Actions` column, which will get very wide, and, because of the centered header, will look misaligned. 

**To Reproduce**

1. Go to [this code sandbox](https://codesandbox.io/s/material-table-change-width-of-column-kty8g?file=/src/App.js:0-857)
2. Replace the contents with the snippet below
3. You will see a very narrow _actions_ column
4. Use the _show columns_ button to remove a couple of columns
5. See how the _actions_ column gets wider and the header text remains centered, even though header styles specify left text alignment.

Snippet: 
```javascript
import React from "react";
import MaterialTable from "material-table";

export default function CustomEditComponent(props) {
  const tableRef = React.createRef();

  const tableColumns = [
    { title: "Lorem ipsum", field: "lorem" },
    { title: "Name", field: "name" },
    { title: "Custom status", field: "customStatus" }
  ];

  const tableData = [
    {
      lorem: "lorem",
      name: "name",
      customStatus: "customStatus"
    }
  ];

  return (
    <MaterialTable
      tableRef={tableRef}
      actions = {[{icon: "X", tooltip: "delete", onClick: (event, rowData) => {console.log("nothing to see here")}}]}
      columns={tableColumns}
      data={tableData}
      title="Change Column Width Example"
      options={{
        tableLayout: "fixed",
        columnsButton: true,
        headerStyle: {textAlign: 'left'}
      }}
    />
  );
}
```

**Expected behavior**
Alignment defined in header styles should apply to actions column. Actions column should resize as columns get added/removed

**Screenshots**
<img width="615" alt="imagen" src="https://user-images.githubusercontent.com/8399424/178639171-a066d430-b100-49b9-a4e3-ba3ca78097b1.png">

**Desktop (please complete the following information):**

- OS: OSX
- Browser: Firefox
- Version: 102.0.1

**Comment by a-asgh** [comment]
I have a similar issue with the Actions column. Mine also is way too wide, but it doesn't seem to have anything to do with the `columnsButton` option. I'm not sure what specifically causes it.

I have noticed that on some rerenders of the page (in my case by changing the language via the i18next framework) the issue fixes itself. Refreshing the page causes the issue to reappear.

Also, this bug didn't appear on Firefox. Only on Chrome (I haven't tested other browsers yet)

**Comment by yatharth** [comment]
Still this issue.

**Comment by solkim95** [comment]
Still this issue.
