### ISSUE TITLE
how to use material-table 2.0.3 with mui v5 and react v18 ?

### ISSUE THREAD

**Issue by mm0hammadi** [mbrn/material-table#3167]
Hey!

i want to use matarial-table with MUI5 ? but i take error like this Module not found: Can't resolve '@mui/material/styles'”
how can i  fix??!

React 18 Support?????????

**Comment by KevinVandy** [comment]
This package seems to be on life support, and will probably never work with React 18. There are similar alternatives out there though that are more modern

**Comment by jimmytricks** [comment]
Can I bump this? If anyone is working on this would be great to know 🙏

**Comment by sophia-kravchenko** [comment]
> 
Could you please link some examples? I'm in search now and need something like this

**Comment by KevinVandy** [comment]
> @KevinVandy Could you please link some examples? I'm in search now and need something like this

@sophia-kravchenko Good list of alternatives here https://www.material-react-table.com/#let's-compare

**Comment by sophia-kravchenko** [comment]
@KevinVandy thank you a lot

**Comment by TatyanaVl** [comment]
I just want to confirm that I am reading this correct.  material-table will never support react v18 and the only option is to switch to one of the alternative libraries:
https://www.material-react-table.com/#let's-compare

Thank you!
