### ISSUE TITLE
Editable actions are disable

### ISSUE THREAD

**Issue by nawazmujawar** [mbrn/material-table#3168]
Hey!!

I have updated material-table version from 1.39.2 to 1.62.0 in my project. Since then editable actions are disable in table and not even click is working for the action
refer the screenshot
![image](https://user-images.githubusercontent.com/63554510/182370675-043b6809-476f-4e04-b7b8-51ce4a9b947d.png)
```
 editable={{
                              onRowAdd: handleDataStoreLinkAdd,
                              onRowUpdate: handleDataStoreLinkUpdate,
                              onRowDelete: handleDataStoreLinkDelete,
                            }}
```
```
 const handleDataStoreLinkUpdate = (newData: any, oldData: any): Promise<void> => {             
              return new Promise<void>(resolve => {
                newData.actionType === DataStoreActionType.INSERT ? null : (newData.actionType = DataStoreActionType.UPDATE);
                var index = values.dataStoreLinks.indexOf(oldData);
                values.dataStoreLinks[index] = newData;
                setValues(values);
                resolve();
              });
            };
```

**Comment by corneliushka** [comment]
Cannot help for your problem, but be aware that you can create an "Actions" column and with render prop you can display manually your icons/buttons with an onClick logic. Hope it helps.
