### ISSUE TITLE
Actions column should not use `MuiTableCell-paddingCheckbox`

### ISSUE THREAD

**Issue by timrchavez** [mbrn/material-table#317]
I would like to control the style of the Actions column independently of the Checkbox column, but that is not easily done since they share `MuiTableCell-paddingCheckbox`. It would be preferable if they used separate classes.

**Comment by mbrn** [comment]
actionsCellStyle added to options. So you can add any style to cell, such as background color

**Comment by mbrn** [comment]
This is done with 1.35.2
