### ISSUE TITLE
expand issues

### ISSUE THREAD

**Issue by DineshPrakasam** [mbrn/material-table#3173]
Hello, i am a begginer in react js , my issue is i adding my child data in material table it will added successfully but it only expanding after i click expand icon , as my requirement is after added child data it can be expand automatically without any trigger point , kindly help me thank you .,

**Comment by heisaduvan** [comment]
Hello, I have same problem. I need to expand automatically when I change the table data. How can we achieve this? Is there a trick?

**Comment by DineshPrakasam** [comment]
> Hello, I have same problem. I need to expand automatically when I change the table data. How can we achieve this? Is there a trick?

still am trying to fix this issue but no can help .
