### ISSUE TITLE
MUI: The LocalizationProvider component was moved from '@mui/lab' to @mui/x-date-pickers'

### ISSUE THREAD

**Issue by jacogasp** [mbrn/material-table#3177]
## Description
Using material-table v2.0.3 and MUI 5 the following deprecation warning is displayed

```
MUI: The LocalizationProvider component was moved from '@mui/lab' to @mui/x-date-pickers'
You should use
"import ( LocalizationProvider } from '@mui/x-date-pickers'
or
'import ( LocalizationProvider } from 'amui/x-date-pickers/LocalizationProvider''
More information about this migration on our blog: https://mui.com/blog/lab-date-pickers-to-mui-x/.
```

Already fixed in PR https://github.com/mbrn/material-table/pull/3176

**To Reproduce**
Simply open a webpage with a table that uses date pickers

**Expected behavior**
No warnings

**Desktop:**

- OS: [macOS]
- Browser [chrome, safari, firefox]

**Comment by KevinMull** [comment]
In my (root) Application.js file I've changed to the new **"import LocalizationProvider } from '@mui/x-date-pickers'"** but now get the following error..

"export 'default' (imported as 'LocalizationProvider') was not found in '@mui/x-date-pickers'"

Application.js...
export default connect(mapStateToProps)(Application);

**Comment by jacogasp** [comment]
> In my (root) Application.js file I've changed to the new **"import LocalizationProvider } from '@mui/x-date-pickers'"** but now get the following error..
> 
> "export 'default' (imported as 'LocalizationProvider') was not found in '@mui/x-date-pickers'"
> 
> Application.js... export default connect(mapStateToProps)(Application);

You cannot simply import from `@mui/x-date-pickers` in your application to fix the warning, you must change the source code of material-table, as I did in this PR.

Out of scope: the idiom **`was not found`** `in '@mui/x-date-pickers'` probably means that you have an old version of `@mui/x-date-pickers` which doesn't have `LocalizationProvider`. But as I told you above, upgrading it won't solve the warning, you must update the library itself.
