### ISSUE TITLE
Fixed thead, scrollable tbody

### ISSUE THREAD

**Issue by timrchavez** [mbrn/material-table#318]
**Is your feature request related to a problem? Please describe.**
There are times when you don't want to use paging, but have more rows than screen real estate. In this case, it would be nice to keep the header in view so the user can maintain context and quickly associate column values with column types.

**Describe the solution you'd like**
It would be nice to be able to keep the `thead` fixed while allowing `tbody` to be scrollable with a prop setting.

**Comment by mbrn** [comment]
I will merge #313 asap.

**Comment by timrchavez** [comment]
Thanks for being so responsive!!

**Comment by mbrn** [comment]
This is done. I added maxBodyHeight to options.
