### ISSUE TITLE
Status library

### ISSUE THREAD

**Issue by ibr4qr** [mbrn/material-table#3181]
Is this library still mantained or at list there's someone who can review pull requets??

**Comment by KevinVandy** [comment]
Not really. You can try to use a fork that tries to stay up to date a bit called [Material-Table-Core](https://material-table-core.com/)

For new projects, look for alternative libraries. 

Mui Datatables, the MUI X Datagrid, or even AG Grid are good, though they may require a paid license for advanced features.

I have also tried to make a free replacement library for this called [Material React Table](https://www.material-react-table.com/) that a lot of devs are liking, but it is a bit different in design.
