### ISSUE TITLE
column alignment issue while 'Bulk Edit'

### ISSUE THREAD

**Issue by JefinDX** [mbrn/material-table#3190]
In the material-table documentation page for '**Bulk Edit Example**' [material-table](https://material-table.com/#/docs/features/editable)
If I removed the 'onRowDelete' function from 'editable' prop, then the column alignments are getting affected.
```
return (
    <MaterialTable
      title="Bulk Edit Preview"
      columns={columns}
      data={data}
      editable={{
        onBulkUpdate: changes =>
          new Promise((resolve, reject) => {
            setTimeout(() => {
              resolve();
            }, 1000);
          })  
      }}
    />
  )
```
Sorry that I couldn't add a screenshot. My organization restrictions don't allow me to take screenshot from company laptop :(

**Comment by weilu** [comment]
![Image](https://github.com/user-attachments/assets/e801af96-0685-4636-a53c-7a82d377f6ef)

This is still an issue. Screen recording above shows that without the `onRowDelete` function defined, the columns are misaligned in bulk edit mode (off by one). When `onRowDelete` is added, the misalignment issue goes away.
