### ISSUE TITLE
Adjust table height based on the data present.

### ISSUE THREAD

**Issue by ShedrackGodson** [mbrn/material-table#3197]
I want to make the table height automatically adjustable since my current setup make the table's height to be large even if the table is empty.

Help me with this guys

**Comment by arjunbhandari3** [comment]
@ShedrackGodson  You can use `emptyRowsWhenPaging` key for this case. You can refer here: [https://material-table.com/#/docs/all-props](material-table). 

`
 <MaterialTable
    options={{
      emptyRowsWhenPaging: false
    }}
 />
`

**Comment by ShedrackGodson** [comment]
This is helpful @arjunbhandari3 , thanks
