### ISSUE TITLE
Collapsed tree table view on state change

### ISSUE THREAD

**Issue by shabeelsyed** [mbrn/material-table#320]
Im using the latest tree table feature.
During state changes the tree is getting collapsed. 
Eg: https://mbrn.github.io/material-table/#/docz-examples-13-example-tree-data 
      Select a row after expanding the tree , will collapse the tree to original position.

  Is there any work around to keep it open, or remember last open state ?

Regards
Shabeel

**Comment by mbrn** [comment]
Hi @shabeelsyed ,

This is a bug. I will resolve it asap.

**Comment by mbrn** [comment]
This is done with 1.23.6

**Comment by Minifish57** [comment]
Hi, i have the 1.30.0 and the bug is still there with the example code 
![Image of Code](https://media.giphy.com/media/QZIeLVn9ub69oX3bJh/giphy.gif)

**Comment by mbrn** [comment]
This is fixed. It will be in next release.
