### ISSUE TITLE
onSelectionChange does not fire for child rows, in tree view.

### ISSUE THREAD

**Issue by shabeelsyed** [mbrn/material-table#322]
**Describe the bug**
onSelectionChange does not fire for child rows, in tree view.

**To Reproduce**
https://mbrn.github.io/material-table/#/docz-examples-13-example-tree-data
Debug the code, it fires only for top most rows, not for its children.
onSelectionChange = () => {
    if (this.props.onSelectionChange) {
      const selectedRows = this.state.data.filter(row => row.tableData.checked);
      this.props.onSelectionChange(selectedRows);
    }
  }

**Expected behavior**
Fire it for all the rows including parent and child.

**Comment by mbrn** [comment]
This is done with 1.27.1

**Comment by shabeelsyed** [comment]
Thanks, I verified!
