### ISSUE TITLE
Hide cell on details show

### ISSUE THREAD

**Issue by adamszeptycki** [mbrn/material-table#325]
Hey, awesome library thanks :)
Is it possible to hide the selected row when showing detail Panel?
I have duplicated data in detailPanel and it doesn't look so great.

**Comment by mbrn** [comment]
How you will close detail panel if row would be hidden ?

**Comment by adamszeptycki** [comment]
I would have an extra, button in that detail view (which again is in designs).

**Comment by mbrn** [comment]
Ok. I can do this with options flag. HideRowWhenDetailPanelExpanded: true

I will do it asap.

**Comment by ColinKrist** [comment]
This is sort of off topic, how did you trigger the detailPanel to hide via a button? I'm curious for my own implementation of a custom edit row form and having a submit button that would close the detailPanel.

**Comment by mbrn** [comment]
@ColinKrist I can send the closeDetailPanel function as a second parameter.
