### ISSUE TITLE
How to make a field uneditable when adding a new roe

### ISSUE THREAD

**Issue by KevinMull** [mbrn/material-table#3257]
I am using the standard edit row button and plus button to add a new record.
Basically I have a 'Id field' that should be disabled (un-editable) when editing the row but **enabled**  when adding a new row.

So far I have tried....

```
{
            field: 'TopicId',
            title: 'Topic Id',
            editComponent: (props) => {
                return (
                    <TextField                        
                        value={props.value}
                        disabled={props.value !=='' ? 'disabled' : ''}
                    />
                );
            },
        },
```

Assuming that the value of the id field is '' when adding a new row but it remains disabled (correctly) when editing a row but (incorrectly) when adding a new row.

I've also tried...

```
{
            field: 'TopicId',
            title: 'Topic Id',
            width: "20%",
            editable: ( _ ,rowData ) => rowData && rowData.TopicId === '',          

        },
```

But same as above, it remains disabled in both cases.

Alternatively is there a way of intercepting and manipulating the onClick of the Plus button and disabling the field there before the new row is rendered?

**Comment by kevinmcppe** [comment]
OK, sorted it.

I neede to add the followin line...
editable: 'onAdd',
Note you can also use the reverse which is...
editable: 'onUpdate',

More details here....
https://[material-table](https://material-table.com/#/docs/all-props).com/#/docs/all-props

Please close

**Comment by KevinMull** [comment]
Resolved
