### ISSUE TITLE
Error: Editable with Grouping

### ISSUE THREAD

**Issue by revskill10** [mbrn/material-table#327]
**Describe the bug**
The input fields get disabled when using editable with grouping

**To Reproduce**
Using both `editable` and `grouping` in props.

**Expected behavior**

If the table is currently grouped, either disable editable, or revert the group state to non-grouping when clicking on edit icon.

**Comment by mbrn** [comment]
Hi @revskill10 ,

I will think about it and find a good solution for this case.

**Comment by eluchsinger** [comment]
Possibly the same issue extends to Tree Data. When I try to edit / delete a child row, the whole table gets disabled.

**Comment by conext18** [comment]
Same problem. For actions in a group works perfectly, but for the children not.
![Captura de Tela 2019-03-19 às 17 41 30](https://user-images.githubusercontent.com/48719068/54640968-c47f1980-4a6f-11e9-9ae3-9a55289dea22.png)

**Comment by mbrn** [comment]
I will look at this issue asap.

**Comment by taranto** [comment]
I am currently with the same issue.

**Comment by mbrn** [comment]
This is done.

**Comment by Clem-** [comment]
> 
> 
> Same problem. For actions in a group works perfectly, but for the children not.
> ![Captura de Tela 2019-03-19 às 17 41 30](https://user-images.githubusercontent.com/48719068/54640968-c47f1980-4a6f-11e9-9ae3-9a55289dea22.png)

How did you managed to add actions to group? Thanks :)

**Comment by res63661** [comment]
Hi there - same problem using latest v1.47.0.  
When grouped i switch to edit mode and rows become greyed but i cannot edit anything. 

Before:
![image](https://user-images.githubusercontent.com/14989048/62741275-56c88f80-ba08-11e9-99dd-3f2bf4e0cfa2.png)

After (everything is disabled):
![image](https://user-images.githubusercontent.com/14989048/62741335-7eb7f300-ba08-11e9-93cb-6e87e1aa7c7a.png)

I love this thing keep up the great work!!
