### ISSUE TITLE
Bulk editing

### ISSUE THREAD

**Issue by jakeleventhal** [mbrn/material-table#331]
**Is your feature request related to a problem? Please describe.**
It is very annoying to have to click over and over to edit multiple rows.
There are many examples where users will have to edit each row in a table for user input data.

**Describe the solution you'd like**
There should be a way to open up editing on the entire table for bulk edits with a save and a cancel button.

**Comment by mbrn** [comment]
Why not:)

**Comment by wandrzejczak** [comment]
+1 :)

**Comment by hungbang** [comment]
@mbrn
is this feature released?

**Comment by omercavuslu** [comment]
+1

**Comment by michaero** [comment]
+1 
very much needed

**Comment by arheinjohnson** [comment]
+1!

**Comment by VidushaZ** [comment]
+1

**Comment by iamsaurabhgupt** [comment]
+1 @mbrn please prioritise this.
We would want to bulk edit certain fields e.g. Status selector changes.
This would highly improve the user productivity.

**Comment by TCM5** [comment]
+1 @mbrn any news on this?

**Comment by jeffsupancic** [comment]
+1

**Comment by atosh502** [comment]
Bulk edit was added in the release [1.68.0](https://github.com/mbrn/material-table/releases/tag/v1.68.0)

**Comment by iamsaurabhgupt** [comment]
@atosh502 That's great. 
But, this saves only the time to click edit on every row.
In any case cell level editing now saves that.
The true power of Bulk editing will be when one can select 100s of rows and enter value on them simultaneously.

It can be visualised like this:
![image](https://user-images.githubusercontent.com/43205009/89805202-eb515a80-db52-11ea-8737-2e38569b05da.png)
So, to change the birth year of both to 1989, we would still need to enter them twice.
If we are able to select the rows and select the field to set the value, then both can be changed at once.
Let me know if there's any confusion.
Hope it makes sense @mbrn

**Comment by PedrinhowVieira** [comment]
+1 It would be great if I could select all the lines I want to update, click edit, change a field value in one of them and confirm, editing all selected lines values.

**Comment by PedrinhowVieira** [comment]
@iamsaurabhgupt 

I solved this by creating a custom edit function to the table:

```
onSelectionChange={(rows) => {
  allSelectedRows = rows;
}}

editable={{
  isEditable: (rowData) => data[rowData.tableData.id].Locked !== true,
  onRowUpdate: (newData, oldData) => new Promise((resolve) => {
    const dataUpdateArray = [...data];
    if (allSelectedRows.length) {    // if there is multiple checkboxes selected
      const updatedData = updatedDiff(oldData, newData);
      allSelectedRows.map((item) => {
        return Object.assign(dataUpdateArray[item.tableData.id], updatedData);
      });
    } else {    // if there is no selected checkbox, you are editing the row
      dataUpdateArray[oldData.tableData.id] = newData;
    }
    setData([...dataUpdateArray]);
    resolve();
  }),
}}
```

**Comment by PedrinhowVieira** [comment]
@iamsaurabhgupt 

I solved this by adding a custom function to the table:

```
const [allSelectedRows, setAllSelectedRows] = useState([]);

onSelectionChange={(rows) => {
  setAllSelectedRows([...rows]);
}}

editable={{
  isEditable: (rowData) => data[rowData.tableData.id].Locked !== true,
  onRowUpdate: (newData, oldData) => new Promise((resolve) => {
    const dataUpdateArray = [...data];
    if (allSelectedRows.length && allSelectedRows.includes(oldData)) {    // if there is multiple checkboxes selected
      const updatedData = updatedDiff(oldData, newData);
      allSelectedRows.map((item) => {
        return Object.assign(dataUpdateArray[item.tableData.id], updatedData);
      });
    } else {    // if there is no selected checkbox, you are editing the row
      dataUpdateArray[oldData.tableData.id] = newData;
    }
    setData([...dataUpdateArray]);
    resolve();
  }),
}}
```

**Comment by iamsaurabhgupt** [comment]
Thanks a lot @PedrinhowVieira. Will try to implement this.
Do have it implemented somewhere in CodeSandbox for ease of understanding and quick implementation?

**Comment by PedrinhowVieira** [comment]
@iamsaurabhgupt sure, here is a [stackblitz](https://stackblitz.com/edit/material-table-bulk-edit?file=src/App.js) I made using only the necessary to achieve the bulk editing.

**Comment by PedrinhowVieira** [comment]
@iamsaurabhgupt sure, here is a [stackbliz](https://stackblitz.com/edit/material-table-bulk-edit?file=src/App.js) made with all the necessary code to achieve the bulk editing. If you want more details about the implementation, I made a post in [stackoverflow].(https://stackoverflow.com/questions/63811146/how-to-achieve-bulk-editing-in-material-table/63811147)

**Comment by iamsaurabhgupt** [comment]
Thanks a lot @PedrinhowVieira. It works.
Yet, it would have been wonderful if there was a selector for field and input for value.
![image](https://user-images.githubusercontent.com/43205009/92700979-1656e600-f36d-11ea-806f-bb65ced36a4c.png)

**Comment by PedrinhowVieira** [comment]
No problem @iamsaurabhgupt.
About your suggestion, in my case, my users have to be able to edit multiple fields at the same time. In my solution they can edit, for example, Birth Year and Birth Place at the same time, plus I think it don't add more input fields, maintaining the UI simple and clean.

**Comment by PedrinhowVieira** [comment]
You are welcome @iamsaurabhgupt.
About your suggestion, in my case, my users have to be able to edit multiple fields at the same time. In my solution they can edit, for example, Birth Year and Birth Place at the same time, plus I think it don't add more input fields, maintaining the UI simple and clean.

**Comment by iamsaurabhgupt** [comment]
@PedrinhowVieira is my use case doable?

**Comment by iamsaurabhgupt** [comment]
ok @PedrinhowVieira, thanks for the effort though.
@mbrn can you shed some light on how to achieve my desirable functionality?

**Comment by shaheeralimm** [comment]
Is this feature implemented? Its not working as per document.

**Comment by qwert666** [comment]
@iamsaurabhgupt icon is accepting a ReactElement, it's not the best way as the library is expecting a button, not select/input fields so you'll have to overwrite the stylings but you can achieve your goal.
```{javascript}
      actions={[
        {
          icon: () => <MyFields ids={ids} />,
```

**Comment by iamsaurabhgupt** [comment]
@qwert666 Thanks a lot for the suggestion.
Please share your code on codesandbox or stackblitz for a functional preview.

**Comment by qwert666** [comment]
@iamsaurabhgupt https://codesandbox.io/s/aged-hooks-6oj0b?file=/src/App.tsx

**Comment by admasodaniel** [comment]
Hey, @mbrn, @iamsaurabhgupt.
my PR: https://github.com/mbrn/material-table/pull/2359
should solve this issue.

**Comment by jakeleventhal** [comment]
not stale

**Comment by jakeleventhal** [comment]
not stale

**Comment by jakeleventhal** [comment]
not stale

**Comment by prateekpareekvyas** [comment]
Any update on this issue
