### ISSUE TITLE
Footer And Searchbar render wrong

### ISSUE THREAD

**Issue by talolard** [mbrn/material-table#332]
**Describe the bug**
Hello, 
I'm trying to replace mui-datatable with this library but am unfortunately running into errors. Basically I get this
![image](https://user-images.githubusercontent.com/5352830/54497471-4863c500-48fb-11e9-8666-3c099bdf0233.png)

Where the search bar appears "funny" and the toolbar on the bottom is also "funny".  

This is in a pretty big code base so hard to extract a simple reporducible example, I can share the following: 

1. Using mui-datatable works fine
2. We're using material-ui css in js. We've tried disabling bootsrapping but that didn't help
3. We've tried multiple versions of material-table,a s far back as 1.22.0 and the problem persists. 

The code we use to call this
```jsx
const TaskProgressView = props => {

    const data = props.data
    return (
      <MaterialTable
        data={data}
        columns={columns}

      />
    );
  }



**Desktop (please complete the following information):**
 - OS:Ubuntu 18.04
 - Browser Firefox
 - Version 65.01

**Comment by mbrn** [comment]
Hi @talolard ,

Did you add this to your html? 

<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

**Comment by talolard** [comment]
Thank you! That solves it
