### ISSUE TITLE
How to filter date column by date range

### ISSUE THREAD

**Issue by talolard** [mbrn/material-table#333]
Hi,
I'd like to override the default date filtering so that the user can select a start and end date, does the api allow for that and  how would I go about doing that? 
Thanks

**Comment by mbrn** [comment]
Unfortunately. material-table currenty does not have this feature. But i will add this feature asap.

**Comment by jakeleventhal** [comment]
this would be awesome

**Comment by mbrn** [comment]
> this would be awesome

I need time @jakeleventhal 

I am working on a new documentation of material-table. After documentation completed i will start to features like this.

**Comment by prevostc** [comment]
This would be very much appreciated. Or maybe a way to customise the column filter? Like a `renderColumnFilter: (params: { shouldShowRow: (data: T) => boolean }) => React.ReactNode` option

**Comment by perfectmak** [comment]
Hi @mbrn How is this coming along, if you need some help, I can help making this possible.

**Comment by jeffsupancic** [comment]
I'm interested in this feature, any update?

**Comment by khoa-ng** [comment]
Hi mbrn.
Thanks for your material-library.
Can I customize filter widget?
I want to add date range as a filter.
Thanks.

**Comment by jeffsupancic** [comment]
@khoa-ng checkout my pull request, I added the ability to pass in a filter component in the column definition.  You can use my fork or wait for the PR to hopefully be merged in before long.

**Comment by NikolaGrujicic** [comment]
Hello @mbrn @talolard  , just wanna check up, is this future added by now ?
i need to filter by date range and i need to finish this by end of week,
if it is still not posible to do it using material-table do you have any suggestion on what else i could try ?
Thank you

**Comment by jeffsupancic** [comment]
@NikolaGrujicic  checkout this PR https://github.com/mbrn/material-table/pull/1351 it's now been merged in.  You'll have to implement a custom filter component.

**Comment by jakeleventhal** [comment]
not stale

**Comment by jakeleventhal** [comment]
not stale

**Comment by mindaugasnakrosis** [comment]
not stale

**Comment by RokasDevelopment** [comment]
> What is the status for this issue?
Hi, I am also interested. Thanks

**Comment by pradeepkrishna1409** [comment]
Not stale

**Comment by turbaceanu15** [comment]
Any status for this issue?

thanks

**Comment by iamwilson** [comment]
Has this been merged?

**Comment by jeffsupancic** [comment]
> @NikolaGrujicic  checkout this PR https://github.com/mbrn/material-table/pull/1351 it's now been merged in.  You'll have to implement a custom filter component.

@iamwilson this has been merged in. See the comment above.

**Comment by iamwilson** [comment]
@jeffsupancic - Noted with thanks sir !

**Comment by andrewphan568** [comment]
Hi, I am also interested. Thanks

**Comment by msherif988** [comment]
Check this out its working with me 

```
import Paper from "@material-ui/core/Paper";
import Typography from "@material-ui/core/Typography";
import Grid from "@material-ui/core/Grid";
import TextField from "@material-ui/core/TextField";
import MaterialTable, { MTableToolbar, MTableBody  } from "material-table";
import Button from "@material-ui/core/Button";

const AddingDateRangeFilter=()=>{
  const [Date1, setDate1] = useState();   /* add state for starting date */
  const [Date2, setDate2] = useState();    /* add state for ending date */

const FilterByDateRange = () => {   /* function for adding 2 textfields for date range */
    return (
      <>
        <Grid alignItems="center" container justify="center">
          <Grid item xs={12} sm={6} md={4} lg={4}>
            <Paper
              elevation={3}
              style={{
                margin: "10px auto",
                textAlign: "center",
                padding: "10px",
              }}
            >
              <Typography> {lang.SearchbyDateRange} </Typography>
              <TextField
                value={Date1}
                onChange={(e) => setDate1(e.target.value)}
                type="date"
                id="date"
                label='Start Date'
                InputLabelProps={{
                  shrink: true,
                }}
                style={{ margin: "10px" }}
              />
              <TextField
                value={Date2}
                label='End Date'
                onChange={(e) => setDate2(e.target.value)}
                type="date"
                id="date"
                InputLabelProps={{
                  shrink: true,
                }}
                style={{ margin: "10px" }}
              />
              <div>
                <Button
                  onClick={() => {
                    setDate1("");
                    setDate2("");
                  }}
                  variant="contained"
                  color="primary"
                >
                  Clear      /* when click clear date1 and date2 will be reset to empty and the data will be reset to all data */
                </Button>
              </div>
            </Paper>
          </Grid>
        </Grid>
      </>
    );
  };

const myData = () => {  /* function to determine the data to be rendered to the table */
    let myArr = [];
    if (Date1 && Date2) {
      YourData.map((item) =>
        item.date >= Date1 && item.date <= Date2 ? myArr?.push(item) : null
      );
    } else {
      myArr = YourData;  /* YourData is the array you want to display and filter */
    }

    return myArr;
  };
return(
<>
   <MaterialTable
        title='Your Title'
        columns={Your columns }  -- your columns must have date field --
        data={myData()}
        options={Your options}
        actions={Your actions}
        components={{
          Toolbar: (props) => (
            <>
              <MTableToolbar {...props} />
              <FilterByDateRange />  /* here you add the function to your table header */
            </>
          ),
 Body: (props) => (
            <>
               /* your can add here what ever code you want and you can access the data rendered from (props.renderData) */
             /* for example I would like to get the amount of expenses from date1 to date2 */
        <tbody>
                <tr
                  style={{
                    padding: "20px 5px",
                    fontWeight: "bold",
                    fontSize: "120%",
                    background: "#ededed",
                  }}
                >
                  <td></td>
                  <td></td>
                  <td style={{ padding: "20px 0px" }}>Total expense}</td>
                  <td></td>
                  <td>
                    {_.sum(
                      props.renderData?.map((item) => Number(item.amount))
                    )}
                  </td>
                  <td></td>
                </tr>
              </tbody>
              <MTableBody {...props} />
            </>
        }}
      />
</>
)
}
```

**Comment by yagomassiah** [comment]
How is this going? native support for date-range is coming anytime soon? Absolutely love the package!

**Comment by okechukwu0127** [comment]
> Check this out its working with me
> 
> ```
> import React, { useState } from "react";
> import Paper from "@material-ui/core/Paper";
> import Typography from "@material-ui/core/Typography";
> import Grid from "@material-ui/core/Grid";
> import TextField from "@material-ui/core/TextField";
> import MaterialTable, { MTableToolbar, MTableBody  } from "material-table";
> import Button from "@material-ui/core/Button";
> 
> const AddingDateRangeFilter=()=>{
>   const [Date1, setDate1] = useState();   /* add state for starting date */
>   const [Date2, setDate2] = useState();    /* add state for ending date */
> 
> const FilterByDateRange = () => {   /* function for adding 2 textfields for date range */
>     return (
>       <>
>         <Grid alignItems="center" container justify="center">
>           <Grid item xs={12} sm={6} md={4} lg={4}>
>             <Paper
>               elevation={3}
>               style={{
>                 margin: "10px auto",
>                 textAlign: "center",
>                 padding: "10px",
>               }}
>             >
>               <Typography> Search by Date Range </Typography>
>               <TextField
>                 value={Date1}
>                 onChange={(e) => setDate1(e.target.value)}
>                 type="date"
>                 id="date"
>                 label='Start Date'
>                 InputLabelProps={{
>                   shrink: true,
>                 }}
>                 style={{ margin: "10px" }}
>               />
>               <TextField
>                 value={Date2}
>                 label='End Date'
>                 onChange={(e) => setDate2(e.target.value)}
>                 type="date"
>                 id="date"
>                 InputLabelProps={{
>                   shrink: true,
>                 }}
>                 style={{ margin: "10px" }}
>               />
>               <div>
>                 <Button
>                   onClick={() => {
>                     setDate1("");
>                     setDate2("");
>                   }}
>                   variant="contained"
>                   color="primary"
>                 >
>                   Clear      /* when click clear date1 and date2 will be reset to empty and the data will be reset to all data */
>                 </Button>
>               </div>
>             </Paper>
>           </Grid>
>         </Grid>
>       </>
>     );
>   };
> 
> const myData = () => {  /* function to determine the data to be rendered to the table */
>     let myArr = [];
>     if (Date1 && Date2) {
>       YourData.map((item) =>
>         item.date >= Date1 && item.date <= Date2 ? myArr?.push(item) : null
>       );
>     } else {
>       myArr = YourData;  /* YourData is the array you want to display and filter */
>     }
> 
>     return myArr;
>   };
> return(
> <>
>    <MaterialTable
>         title='Your Title'
>         columns={Your columns }  -- your columns must have date field --
>         data={myData()}
>         options={Your options}
>         actions={Your actions}
>         components={{
>           Toolbar: (props) => (
>             <>
>               <MTableToolbar {...props} />
>               <FilterByDateRange />  /* here you add the function to your table header */
>             </>
>           ),
>  Body: (props) => (
>             <>
>                /* your can add here what ever code you want and you can access the data rendered from (props.renderData) */
>              /* for example I would like to get the amount of expenses from date1 to date2 */
>         <tbody>
>                 <tr
>                   style={{
>                     padding: "20px 5px",
>                     fontWeight: "bold",
>                     fontSize: "120%",
>                     background: "#ededed",
>                   }}
>                 >
>                   <td></td>
>                   <td></td>
>                   <td style={{ padding: "20px 0px" }}>Total expense}</td>
>                   <td></td>
>                   <td>
>                     {_.sum(
>                       props.renderData?.map((item) => Number(item.amount))
>                     )}
>                   </td>
>                   <td></td>
>                 </tr>
>               </tbody>
>               <MTableBody {...props} />
>             </>
>         }}
>       />
> </>
> )
> }
> ```

This worked for me. But i was able to achieve the filter without the MTableBody and everything worked 100%.

Thanks very much for such a fantastic code. You have saved me days of research.
Regards
