### ISSUE TITLE
Paging buttons outside of the table on mobile

### ISSUE THREAD

**Issue by jakeleventhal** [mbrn/material-table#335]
**Describe the bug**
On mobile, the paging extends beyond the table

**Screenshots**
![Mar-17-2019 22-59-13](https://user-images.githubusercontent.com/15133828/54504117-a519ac80-4908-11e9-9b29-40fc25e59c40.gif)

**Comment by mbrn** [comment]
This is known bug. I will resolve this asap.

**Comment by mbrn** [comment]
This is done with 1.27.0

**Comment by vdh** [comment]
I'm seeing this issue with 1.55.0

**Comment by vdh** [comment]
I managed to solve the overflow by applying `min-width: 0` to the table row element.
