### ISSUE TITLE
There is a BUG in the "general" checkbox 

### ISSUE THREAD

**Issue by orestes22** [mbrn/material-table#338]
**Describe the bug**
After select all the checkbox, the general checkbox is checked, however the selection is off if some state of my class changed. 

**To Reproduce**
Im working in the version "^1.23.3". 

I create this example, where I added 1 second before change the state in my class, and you will see how the general checkbox will desapear. 

https://codesandbox.io/s/lx2v9pn91m

**Expected behavior**
I expect that the general checkbox dont lose the check mark if I update a state in my class. 

Please let me know if I explain the issue correctly 

I hope you can fix it asap, your table is very good!!

Best Regards

**Comment by mbrn** [comment]
Hi @orestes22 ,

This is very interesting bug:) . I resolved it. It will be in next release.

**Comment by mbrn** [comment]
I published. You can download v1.24.0

**Comment by orestes22** [comment]
Thanks very much for take care so faster!!!
