### ISSUE TITLE
Banded Columns

### ISSUE THREAD

**Issue by Domino987** [mbrn/material-table#340]
Is there a good way to implement banded columns like this: https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/banded-columns/
or do you want me to try to add this feature into this lib?

**Comment by mbrn** [comment]
I don't know it is useful or not.

**Comment by mbrn** [comment]
No need this feature.

**Comment by xploreraj** [comment]
Hi @mbrn , I think its useful to show grouped data and enhances the use cases of material-table.

**Comment by emersonbottero** [comment]
https://github.com/mbrn/material-table/issues/1718 @Domino987
