### ISSUE TITLE
Footer border not rendered correctly when table with DetailPanel is empty

### ISSUE THREAD

**Issue by FlavyP** [mbrn/material-table#344]
**Describe the bug**
When having a table with detailPanel but no records, the bottom border line is not rendered correctly. As far as I looked into, it's from the "colspan" or the fact that MuiTableCell body is thinks has space for all columns except one.

**To Reproduce**
1. Take the example from here: https://mbrn.github.io/material-table/#/docz-examples-11-example-detail-panel
2. Replace data with: 
```
data={[
  ]}
```
**Expected behavior**
Border line should be rendered on the full width of the table.

**Screenshots**
![g1](https://user-images.githubusercontent.com/9482352/54686288-36f80400-4b19-11e9-8c95-1b26a7b5a4b6.PNG)
![g2](https://user-images.githubusercontent.com/9482352/54686309-46774d00-4b19-11e9-9b0a-8f5ea7ef3bbe.PNG)

**Additional context**
Somehow increasing the "colSpan" value is fixing it. `<td class="jss1775 jss1777" colspan="5"` instead of 4.

**Comment by mbrn** [comment]
Thanks @FlavyP 

I fixed it with version 1.25.1.
