### ISSUE TITLE
Removing select all button from table

### ISSUE THREAD

**Issue by malix1** [mbrn/material-table#347]
Hello.
How can I remove or disable select all button from table ?

**Comment by mbrn** [comment]
Hi @malix1 ,

There is no any option to hide selectAll checkbox from header. If you want, i will be grateful with you PR. 

As a workaround you can override header component of table. Look at examples: 

https://mbrn.github.io/material-table/#/docz-examples-10-example-component-overriding

**Comment by mbrn** [comment]
This is done with 1.26.1. 

Usage: 

```javascript
<MaterialTable
                options={{
                  selection: true,                  
showSelectAllCheckbox: false
                }}
............
              />
```

**Comment by malix1** [comment]
Thank you
And i'm sorry. I could not help :(

Have a nice day

Mehmet Baran <notifications@github.com>, 21 Mar 2019 Per, 13:36 tarihinde
şunu yazdı:

**Comment by mbrn** [comment]
Not important @malix1 , You give us a new simple feature idea :)
