### ISSUE TITLE
Undefined rowData on custom action

### ISSUE THREAD

**Issue by mariolazzari** [mbrn/material-table#348]
**Describe the bug**
After upgrading to version 1.26.0, all my custom actions are not working, because rowData is undefined now.

After downgrading to version 1.25.1 all is working fine,

I tried the online example https://mbrn.github.io/material-table/#/docz-examples-03-example-actions with version 1.26.0 and I had the same issue.

**Comment by mbrn** [comment]
This is fixed with 1.26.1
