### ISSUE TITLE
Editable: edit only selected fields/columns

### ISSUE THREAD

**Issue by wandrzejczak** [mbrn/material-table#350]
Hello,

**Example:**
https://mbrn.github.io/material-table/#/docz-examples-15-example-editable

**Currently:**
When I add Edit option all fields are available to be edited

**Expectation:**
Possible to disable specific columns to avoid editing them.
For example, I'd wish to have the option to disable Birth year/place should not be changed, only Name and Surname should.

Wojtek.

**Comment by mbrn** [comment]
Hi @wandrzejczak ,

I will add many options to editable feature such as disable, validation, custom component and so on. 

I will add all of them asap.

**Comment by wandrzejczak** [comment]
Hi @mbrn,

Thank you!

p.s.
I really like your implementation of the table grid, simple and elegant :)
Aswome job, thanks for all your effort :)

Wojtek.

**Comment by mbrn** [comment]
@wandrzejczak 

You can star repo :) Thanks. I love opensource communities.

**Comment by spazzarama** [comment]
@wandrzejczak @mbrn I have the same requirement and have created a pull request with a solution.

I didn't find this issue until after making the change, so hopefully it suits what you had in mind.

The change allows you to make a column readonly when editing, while remaining editable when adding a new row.

**Comment by mbrn** [comment]
Thanks @spazzarama 

Let me test it and i will publish it today.

**Comment by mbrn** [comment]
I published it with 1.29.0

**Comment by spazzarama** [comment]
@mbrn thanks

**Comment by alyssonmessias** [comment]
The change to the `"editable"` property was not changed in the documentation.

It still has the old example: `"readonly: true"`. And now to work it should use `"editable: true"`.

https://material-table.com/#/docs/features/editable

**Comment by alyssonmessias** [comment]
This `readonly` property of the **columns** component is not working. When included, the field is still editable.

**Comment by mbrn** [comment]
We change it as editable. Can you try it?

**Comment by mbrn** [comment]
Hi @alyssonmessias ,

I added to documentation. It will be published tomorrow.

**Comment by hdwivedi9** [comment]
Hey @mbrn ,
How can I make certain columns editable based on rowData value. Like if I have a table with three columns id, role, status & I want rows with editable role and status if their id > 10 and I want remaining rows with id <= 10 to only have editable status and not editable role

**Comment by mbrn** [comment]
Hi @hdwivedi9 ,

You can use custom edit component. https://material-table.com/#/docs/features/editable

**Comment by hdwivedi9** [comment]
@mbrn yeah I tried using that but there is no way to handle conditions(rowData.id>10) to make certain columns editable. If there is an onClick() event handler on edit icons then it is possible otherwise I can't see a way to do this.

**Comment by mbrn** [comment]
Actually it is possible:

It calls your editComponent with rowData. You can return MTableEditField (import {MTableEditField} from 'material-table') or return value directly according to your condition. 
```javascript
  <EditComponent
                key={columnDef.tableData.id}
                columnDef={cellProps}
                value={value}
                rowData={this.state.data}
                onChange={value => {
                  const data = { ...this.state.data };
                  setByString(data, columnDef.field, value);
                  // data[columnDef.field] = value;
                  this.setState({ data });
                }}
                onRowDataChange={data => {
                  this.setState({ data });
                }}
              />
```

**Comment by hdwivedi9** [comment]
Thanks for the solution. I understood it and tried to implement it. It works fine if I return cell.value but when I return MTableEditField it renders nothing in table which is odd since it is the default value.

*****
import {MTableEditField} from 'material-table'
.....
<MaterialTable
....
                 components={{
                    EditField: cell => {
                        console.log(cell);
                        return MTableEditField;
                    }
                }}
/>
*******
Anyways thanks a lot.

**Comment by chidananda-mn** [comment]
Hello All,

https://material-table.com/#/docs/features/editable
In the above docs ,under Cell Editable Example-> am unable update the value after editing any suggestion
