### ISSUE TITLE
rowData  showing empty and detail rows also not working

### ISSUE THREAD

**Issue by arpitalopa** [mbrn/material-table#351]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mbrn** [comment]
Hi @arpitalopa ,

Can you explain the problem with more detail, please?

**Comment by arpitalopa** [comment]
For edit a row, data of that particular row is showing empty and actions
and detail row also have same problem as well as delete also , all are not
getting row data hence not get column data like id to  delete particular
data.
But as I do npm install some times it start working fine but later again it
create same problem and again after several npm install it starts working.
Its not like after every npm install it start working. I don't know why but
sometimes when i did npm install it starts working and sometimes after
several npm install it will not work .

**Comment by mbrn** [comment]
I publish a lot of versions weekly. So you may install buggy versions sometimes. Please be sure you at the latest version of material-table. it is 1.26.1

**Comment by arpitalopa** [comment]
ya i installed the latest one previously it was working fine after
installing new one it is creating problem

**Comment by mbrn** [comment]
can you share your code (only table usage piece)

**Comment by arpitalopa** [comment]
<MaterialTable
components={{
Toolbar: props => (
<div>
<MTableToolbar {...props} /><br />
<div align="left" style={{ paddingLeft: 20 }}><Button variant="contained"
color="primary" onClick={this.handleClickOpen}>Add New Rule</Button></div>
</div>)
}}
columns={[
{ title: 'Rule Id', field: 'ruleId' },
{ title: 'Name', field: 'ruleName' },
{ title: 'Class', field: 'ruleClass' },
{ title: 'Active', field: 'status' },
{ title: 'Apply On', field: 'applyOn' },

]}
data={this.props.data}
title={this.props.title}
options={{
// columnsButton: true,
exportButton: true,
showEmptyDataSourceMessage: true,
emptyRowsWhenPaging: false
}}
actions={[

{
icon: 'edit',
tooltip: 'Edit',
onClick: (event, rowData) => {
return (<Button color="secondary" onClick={this.handleClickOpenEdit(rowData)
}>

</Button>)
},
},

]}
detailPanel={rowData => {
return (
<div
style={{
// fontSize: 100,
textAlign: 'left',
color: 'black',
// backgroundColor: '#43A047',
padding: '10px',
paddingLeft: '20px'

}}
>
<b>Check For:</b> {rowData.checkFor}<br /><hr />
<b>Severity:</b> {rowData.impactLevel}<br /><hr />
<b>Properties:</b> {rowData.properties}<br /><hr />
<b>Description:</b> {rowData.ruleDescription}<br /><hr />
<b>Remediation Suggestion:</b> {rowData.remediationSuggestion}

</div>

)
}
}
/>

**Comment by arpitalopa** [comment]
Not all time it fails sometimes it is working

**Comment by arpitalopa** [comment]
close
