### ISSUE TITLE
can i get remotedata from detailpanel

### ISSUE THREAD

**Issue by symnetry** [mbrn/material-table#352]
something like this 
```
detailPanel={[
	{
		tooltip: 'xxx',
		render: rowData => {
			return new Promise((resolve,reject)=>{
				fetch(`${MAIN}/v1/xxx?xx=${rowData.xxx}`)
					.then(response=>response.json())
					.then(res=>{
						let {xxx}=res
						resolve(<div>{xxx}<div/>)
					})
			})
		},
	},
]}
```

**Comment by mbrn** [comment]
You can return a new component in detail panel render:

```
detailPanel={[
	{
		tooltip: 'xxx',
		render: rowData => <YourComponent data={rowData}/>
	},
]}
```

Then your data componentDidMount function of YourComponent

**Comment by symnetry** [comment]
thanks!
it works

**Comment by deepatr12** [comment]
The detailPanel does not open up. It just opens and closes automatically

**Comment by deepatr12** [comment]
I tried this. The detailPanel does not open up. It just opens and closes automatically. How do we render the data received from remote?

**Comment by deepatr12** [comment]
I tried this. The detailPanel does not open up. It just opens and closes automatically. How do we render the data received from remote? The render of the CustomComponent gets called before data is received from remote.

**Comment by gabrielhpugliese** [comment]
@deepatr12 that's true. This issue shouldn't be closed. I am using hooks to fetch stuff and I am certain it does not work and has exactly the same behaviour you are describing.
