### ISSUE TITLE
Toggle detailPanel on click of a cell

### ISSUE THREAD

**Issue by bjhm** [mbrn/material-table#354]
Currently there is options to use the preset buttons at the beginning of the table OR onRowClick to toggle the detailPanel. Is it possible to add a solution to allow the togglePanel function upon clicking of a cell (td or button within td) trigger this functionality?

**Comment by bjhm** [comment]
Or possibly the ability to update a detailPanel toggle button with a class / ID we can target to trigger a click upon?

**Comment by mbrn** [comment]
I may add a onCellClick feature. You can toggle detail panel or anything else with this event. 

I will add this asap.

**Comment by bjhm** [comment]
Hello @mbrn,

Wondering if this feature was still being considered? 

Thanks!

**Comment by mbrn** [comment]
Hi @bjhm ,

Yes i will. But now i am working on bugs firstly.

**Comment by adithyamaheshb** [comment]
Is there any way to handle the previous panel which means I want to show only one detail panel expanded at a given point of time.
Thanks.

**Comment by heyjaypray** [comment]
^ That would be a nice feature!  So there aren't a ton of detail panels open at once.
