### ISSUE TITLE
editable problem

### ISSUE THREAD

**Issue by ariverak** [mbrn/material-table#360]
Hello everyone, someone knows if I can select the columns I want to edit.
![image](https://user-images.githubusercontent.com/29168528/54840034-cf71be00-4caa-11e9-9df1-510be755a102.png)

**Comment by mbrn** [comment]
Hi @ariverak ,

Unfortunately, you can not. It does not support for cell editing. Perhaps, later I can add this feature. But now i am focused other issues and adding some complementary enhacements on editing row.
