### ISSUE TITLE
Custom grouping action ?

### ISSUE THREAD

**Issue by revskill10** [mbrn/material-table#362]
In my case, i use graphql query to fetch data.
So when doing grouping, i'd love to have custom grouping action, so that i could do refetch data based on the grouping data as new variables.

**Comment by mbrn** [comment]
Do you want add some actions to group row?

**Comment by revskill10** [comment]
@mbrn I prefer keeping current behaviour, but exposing an event handler, like `onGrouping` which arguments is the `field` array of grouping headers ?
