### ISSUE TITLE
Get red in the console window when typing anything into

### ISSUE THREAD

**Issue by kasajian** [mbrn/material-table#363]
**Describe the bug**
Get red in the console window when typing anything into 

Editable Examples (https://mbrn.github.io/material-table/#/docz-examples-15-example-editable)

I get:
Warning: A component is changing an uncontrolled input of type text to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component.

**To Reproduce**
1. new folder, type:  create-react-app samptab
2. cd samptab
3. npm install material-table --save
4. npm start
5. Update index.html in public folder, and add:
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
6. in App.js add:
import MaterialTable from 'material-table'
7.  in App.js, add the <MaterialTable......
from Editable Examples
8.  save and switch to browser.  must refresh browser.  in the table, add a new row, and start typing in the first field.

**Screenshots**

[App.zip](https://github.com/mbrn/material-table/files/2999812/App.zip)

![image](https://user-images.githubusercontent.com/2384797/54871858-2b564880-4d78-11e9-99cb-716cc927be73.png)

windows 10, latest chrome.

[package.zip](https://github.com/mbrn/material-table/files/2999813/package.zip)

**Comment by mbrn** [comment]
Hi @kasajian ,

Thanks for opening issue. It is a small bug. I will resolve it asap.

**Comment by mbrn** [comment]
This is done with version 1.31.0
