### ISSUE TITLE
Cant import MTableEditRow

### ISSUE THREAD

**Issue by mazzini** [mbrn/material-table#364]
im trying to customize the textfield by overriding the components, but MTableEditRow import doesn't work.

import MaterialTable, { MTableEditRow } from 'material-table';

console.log(MTableEditRow);
undefined

**Comment by mbrn** [comment]
Hi @mazzini ,

I have forgotten exporting the MTableEditRow. I fixed it. It will be in next release in a few days.

**Comment by mazzini** [comment]
Tnx! Amazing work btw
