### ISSUE TITLE
Table colSpan support

### ISSUE THREAD

**Issue by Jim25** [mbrn/material-table#365]
Hi,

I want to do colspan in table column. Is there any way to do by this library ?

Thanks in advance.

**Comment by mbrn** [comment]
Hi @Jim25 ,

It does not support for colspans. But as a workaround you can override the Row and Cell component to change their behaviour. 

Look at overriding example: 
https://mbrn.github.io/material-table/#/docz-examples-10-example-component-overriding

**Comment by Jim25** [comment]
Thank you mbrn!

I will give it a try.

**Comment by zootopia106** [comment]
can you share how you controlled in details?

**Comment by unnikrishna** [comment]
Hi @mbrn the above git-hub link is not opening, can you show any code-sandbox example for row-span and col-span

**Comment by pixelass** [comment]
The page was moved here https://material-table.com/#/docs/features/component-overriding

**Comment by dandv** [comment]
Maybe I'm missing something, but I don't see an example of colspan at [that link](https://material-table.com/#/docs/features/component-overriding)?

**Comment by nguyenhaduchieu** [comment]
Solution here, you can insert header components. Example here: [](https://codesandbox.io/s/sharp-ellis-exyk6)
