### ISSUE TITLE
'data' is modified by library code, requiring post-processing prior to saving it to disk

### ISSUE THREAD

**Issue by kasajian** [mbrn/material-table#366]
**Describe the bug**
I need to "save" the data to disk as json, enabling admin to modify the file on disk if the want.  However, the library code seems to add additional bits to the data that need to be stripped out before file can be saved.

Right now, before saving the data to disk, we have to do the following

Code that needs to run once:

        var columnNames = columns.map(_ => _.field);

Prior to writing to file, we cannot write the content of 'data' directly, but first need to loop through each row, and then for each row, only keep the data that's in the original column list.:

        var fileContent = data.map(_ => columnNames.reduce((newObj, key) => ({ [key]: _[key], ...newObj }), {}));

**Comment by mbrn** [comment]
Table add a tableData field to every row to store some related data on it such as checked, detailPanel etc. 

You should remove tableData field for every row if you want to save data to anywhere

**Comment by kasajian** [comment]
Yeah, I get that.   Having the tableData field in each row is implementation detail and leaky abstraction.  I was just proposing that the library shouldn't modify the data that's supplied to it by the application.   If you disagree, that's fine.   Obviously it's your choice.

At the application layer it can be addressed, as you indicated.  Although, I wouldn't add code to the application layer that references "tableData".   That seems like there would be intimate knowledge in the application of the internals of the library code.   I prefer using the code I put in the original post where a new table is created with only the properties matching the column list.   That way there's no knowledge of tableData in the application code.    If tableData goes away, or other private fields are added to the object, the application code will continue to work.

**Comment by mbrn** [comment]
Hi @kasajian ,

To follow changes on a row with every render i have to add a additional field. Or i need to unique id of every row. So i decided to use tableData field. Thanks for clear comment.
