### ISSUE TITLE
HTML output contains "[object Object]"

### ISSUE THREAD

**Issue by domekol** [mbrn/material-table#368]
**Describe the bug**
HTML output has alot unknown 'html' properties.
Seems the "material-table" library properties are passed trough to MUI-components.

**To Reproduce**
1. Go to 'https://mbrn.github.io/material-table/#/docz-examples-01-example-basic'
2. Open rendered HTML Sourcecode
3. Inpsect the rendered output of the table
4. See alot xxx="[object Object]"

**Expected behavior**
A clean html is rendered.

**Comment by mbrn** [comment]
Hi @domekol ,

I will resolve them asap.

**Comment by mbrn** [comment]
This is done with 1.28.2
