### ISSUE TITLE
Cannot find name MTableToolbar in index.tsx

### ISSUE THREAD

**Issue by apsrcreatix** [mbrn/material-table#369]
**MTableToolbar error**
(148,25): Cannot find name 'MTableToolbar'.
Let me know about this.

**Additional context**
![Screenshot from 2019-03-25 21-38-14](https://user-images.githubusercontent.com/24192742/54935611-a40aff80-4f46-11e9-901d-1756341a4d99.png)

**Comment by mbrn** [comment]
Hi @apsrcreatix ,

It is a bug about typescript typings. If you have problems with compiling your typescript, you can add skipLibCheck: true to your tsconfig.json as a workaround. 

I will resolve it in next release asap.

**Comment by apsrcreatix** [comment]
I have changed it to type **any**. It worked for me. Thanks.

**Comment by mbrn** [comment]
This is done with 1.27.2
