### ISSUE TITLE
When using lookup with integer value 0 the filtering returns empty results

### ISSUE THREAD

**Issue by kfirshahar** [mbrn/material-table#370]
**Describe the bug**
When defining a Material table with column lookup field which defines a key with integer 0  for filtering, the data is not properly filtered and ignores records with integer 0 on the relevant column. When using non-zero number or with the string '0' there is no problem.

**To Reproduce**
1. Define a Material table is it appears in the example in https://mbrn.github.io/material-table/#/docz-examples-06-example-filtering
2. Change the value of **birthCity** from **63** to **0** in lines 18 and 14, which is mapped to **'Şanlıurfa'**
3. Select the filter with option **'Şanlıurfa'** on the column **Birth Place**
4. No records are returned by the filter

**Expected behavior**
Data records with value 0 in the birthCity field should be seen in the table

**Screenshots**
![image](https://user-images.githubusercontent.com/5998768/54935874-e5d97d00-4f29-11e9-8aa9-753a6a1fec7a.png)

**Desktop (please complete the following information):**
 - chrome Version 72.0.3626.121 (Official Build) (64-bit)
 - windows 7

**Comment by mbrn** [comment]
Hi @kfirshahar ,

Thanks for clear description about but. I will resolve it asap.

**Comment by mbrn** [comment]
This is done with 1.28.2

**Comment by kfirshahar** [comment]
Hi @mbrn ,
Thanks for the quick fix, it works fine now :)
