### ISSUE TITLE
Select is missing localization?

### ISSUE THREAD

**Issue by TatiTheFreaK** [mbrn/material-table#371]
**Describe the bug**
In https://github.com/mbrn/material-table/blob/master/src/material-table.js , line 252 it looks like "rows" is hardcoded, so we can't localize it. Is this the case?

**Expected behavior**
Have a prop or something to allow us to localize the string

**Screenshots**
![image](https://user-images.githubusercontent.com/11199668/54946854-c6395900-4f17-11e9-932e-b1f900c516a2.png)

**Comment by mbrn** [comment]
I developed it a few days ago. I will add localization for it asap. Or why you dont contribute: )

**Comment by TatiTheFreaK** [comment]
It works now, thank you for the quick merge :D
