### ISSUE TITLE
How to make toolbar take less space

### ISSUE THREAD

**Issue by kasajian** [mbrn/material-table#375]
When turning off search, sorting and showTitle, toolbar takes too much space -- how would one make the height shorter and the remaining "Add" button closer to the edge:

![image](https://user-images.githubusercontent.com/2384797/54953814-5ec6dd80-4f06-11e9-8b86-5d11fa78a03e.png)

        <MaterialTable
            components={{
                Toolbar: props => (
                    <div style={{ backgroundColor: '#e8eaf5' }}>
                        <MTableToolbar {...props} />
                    </div>
                ),
            }}
            options={{
                search: false,
                sorting: false,
                showTitle: false,
                toolbarButtonAlignment: "left"
            }}

**Comment by kasajian** [comment]
Providing this example in the docs will also help new users on how to locate additional props within the source and how to override them.

**Comment by mbrn** [comment]
Hi @kasajian ,

You can change its minHeight with css like this. 

```javascript
<MaterialTable
                components={{
                  Toolbar: props => (
                    <div style={{ backgroundColor: '#e8eaf5' }}>
                      <MTableToolbar {...props} classes={{ root: "my-temp-class" }} />
                    </div>
                  ),
                }}
```

```html
<style>
      .my-temp-class {
        min-height: 36px !important;
      }
    </style>
```

**Comment by kasajian** [comment]
Thank you.   I would have never assumed that a <style> section would have been required for this.   I tried doing the above with a style attribute in the MTableToolbar component, and it didn't work.

But what you have shown there does work, so thank you!

**Comment by mbrn** [comment]
Actually i don't prefer classes. I should transfer style to TableToolbar from MTableToolbar.

**Comment by kasajian** [comment]
I tried that, but it didn't work because you can't put "!important" in style attribute I don't think

**Comment by mbrn** [comment]
You can not set it as style. You should use css classes. Look at this:

https://material-ui.com/customization/overrides/

**Comment by kasajian** [comment]
Thanks. Let me study that.
