### ISSUE TITLE
How to go to a specific page when number of pages is very large?

### ISSUE THREAD

**Issue by hsluoyz** [mbrn/material-table#377]
I have used the new server-side pagination feature here: https://github.com/mbrn/material-table/issues/64 and it is awesome. Thanks for your work!

The issue I encountered is that there can be 100 pages in my scenario. And somehow I need to go to the 50th page. But the there's no a "go to page x" way for me to directly go to a page. I have to click the "left" and "right" buttons for many times to go to a page far from start or end.

![image](https://user-images.githubusercontent.com/3787410/54965718-bddf2d80-4fac-11e9-812f-ada3113ee2c3.png)

I think the best way for me would be letting me input the page number: (forget about it's Mac instead of web:))

![image](https://user-images.githubusercontent.com/3787410/54965881-64c3c980-4fad-11e9-9f98-998bc58f39a2.png)

But I'm also OK with the Google way (by providing 10 pages):

![image](https://user-images.githubusercontent.com/3787410/54965815-28906900-4fad-11e9-9f31-368f96110101.png)

Thanks!

**Comment by mbrn** [comment]
Hi @hsluoyz ,

Can you try adding paginationType: 'stepped' to options of table. It may resolve your requirements.

**Comment by hsluoyz** [comment]
@mbrn Hi, I tried your solution, but it only gave me one more page. The length is too small. I may want at least buttons for next 10 pages, or provide a "Go To" input box.

![image](https://user-images.githubusercontent.com/3787410/55964892-10f0fa00-5ca8-11e9-948e-9fbc6bdefffe.png)

**Comment by mbrn** [comment]
Hi @hsluoyz ,

I will do this but i need time.

**Comment by zhaoyao91** [comment]
This feature is needed in cases of large set of pages. Could this issue be reopened?

**Comment by ivanvladimirov** [comment]
> 
> 
> Hi @hsluoyz ,
> 
> I will do this but i need time.

Hey, do you have an idea if you will add it as a functionality?

**Comment by saunlani** [comment]
need this feature!

**Comment by saunlani** [comment]
@hsluoyz did you come up with a solution for this yet?

**Comment by Azarchaniel** [comment]
Also came here for the same reason. I would like to have option to set a number of pages 'around' current page. Example:
Currently, when I am on page 6, I see something like this < 5 **6** 7 >.
I would like to have an option, like {numberOfPagesAroundCurrent: 2}, and the result will be < 4 5 **6** 7 8 >.
I'm talking about this code: [m-table-stepped-pagination.js:55](https://github.com/mbrn/material-table/blob/42d966eacdbe47cd176f9c5c68e3d97b126b489e/src/components/m-table-stepped-pagination.js#L55)
