### ISSUE TITLE
custom filtering

### ISSUE THREAD

**Issue by orestes22** [mbrn/material-table#379]
Hi, crack, :). How to render a custom Filter?, I mean : I have a columns where I render different options, so I will want make a Filter where the user can select from this options and show the rows that have those options.

Best Regards

**Comment by revskill10** [comment]
@mbrn This is i think essential for better UX ;)
For example, for `date` column type, i'd love to implement a range filter instead of "one date" filter.

How do you think about expose a `filterRender` function ?

**Comment by mbrn** [comment]
Of course this will be useful. But firstly i want to apply filter with default operations such as string contains, startswith etc.

**Comment by orestes22** [comment]
Hi, I know you are busy. but just in case, Is there any comment in this feature?

**Comment by mbrn** [comment]
> Hi, I know you are busy. but just in case, Is there any comment in this feature?

I will do it. But firstly i want to resolve bugs to make table more stable.

**Comment by orestes22** [comment]
Noted. Thanks

**Comment by udayreddy** [comment]
@mbrn can we also inject css styles to different filter types in the row, please ?

**Comment by mbrn** [comment]
> @mbrn can we also inject css styles to different filter types in the row, please ?
> Probably in along the lines of headerProps or if there is a better way to use overrides from Mui themes.. That would be great too.

I will consider this when start to improve filtering.

**Comment by jeffsupancic** [comment]
@mbrn I'm looking to implement custom filter components, in particular range filters.  Any update on this?
