### ISSUE TITLE
Two warnings appear if multiple groups are set via defaultGroupOrder

### ISSUE THREAD

**Issue by crotten** [mbrn/material-table#380]
**Describe the bug**
I currently have defaultGroupOrder set to 0 and 1 for the two columns and it works as expected but I get a warning saying certain attributes are not defined (isTreeData and onTreeExpandChanged).

**To Reproduce**
1. Add defaultGroupOrder to two different columns with the values of 0 and 1
2. Open the console for the web browser 
3. Expand one of the groups in the table
4. Warnings appear in the console

**Expected behavior**
These warnings should not appear

**Screenshots**
<img width="671" alt="Screen Shot 2019-03-26 at 10 19 07 AM" src="https://user-images.githubusercontent.com/8238886/55010054-8e7eef80-4fb1-11e9-8d68-c18b55cfef55.png">
<img width="671" alt="Screen Shot 2019-03-26 at 10 19 20 AM" src="https://user-images.githubusercontent.com/8238886/55010081-976fc100-4fb1-11e9-8453-90122e4e8788.png">

**Desktop (please complete the following information):**
 - OS: Mac OS X (Mojave)
 - Browser: Chrome
 - Version: 72.0.3626.121

**Additional context**
Creating this bug report based on the conversation on Gitter.

**Comment by mbrn** [comment]
This is done with 1.28.2
