### ISSUE TITLE
Question about tree data

### ISSUE THREAD

**Issue by v1nns** [mbrn/material-table#388]
How could I get the status when the tree has expanded by Parent component? Should I need to override some component like Body or Row?

**Comment by mbrn** [comment]
Hi @v1nns 

What do you mean by expanded? Do you want to handle expand event?

**Comment by v1nns** [comment]
Hi @mbrn, I would like to get a event every time the tree has expanded, for example, there is the event **OnRowClick**, but it's not called when you click on the button (icon: >) to expand the tree data.

**Comment by mbrn** [comment]
@v1nns ,

I will add event that you want asap for next release. Generally i publish new releases in a few days.

**Comment by v1nns** [comment]
@mbrn, alright, thank you. Congratulations for the work done, material-table is really useful, especially on the project I've been working.

**Comment by v1nns** [comment]
@mbrn, any updates?

**Comment by mbrn** [comment]
@v1nns , today i focused to bugs only. But this weekend i will resolve most of bugs and small issues like this.

**Comment by mbrn** [comment]
@v1nns 

This is done with version 1.32.0

**Comment by v1nns** [comment]
@mbrn Thank you!
