### ISSUE TITLE
Details panel colspan miscalculated

### ISSUE THREAD

**Issue by Daniel0827** [mbrn/material-table#389]
**Describe the bug**
Detail panel's td colspan only counts the data columns, but not the automatically added columns for actions or the Detail panel buttons.

You can also see this on the Details panel examples.

**Screenshots**
![kép](https://user-images.githubusercontent.com/11861569/55221247-5245cc00-5209-11e9-868c-22513dc71f36.png)

![kép](https://user-images.githubusercontent.com/11861569/55221311-6e496d80-5209-11e9-86fa-7af499cd463c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Browser: Firefox 66.0.2
 - Version: 1.28.2

**Comment by mbrn** [comment]
Hi @Daniel0827 

I will resolve it asap.

**Comment by ColinKrist** [comment]
To all facing this issue, https://github.com/mbrn/material-table/issues/380 introduced bug and is not present in 1.28.1.

**Comment by ColinKrist** [comment]
@mbrn is this issue addressed in an upcoming release? the version I mentioned was the last release and 1.28.2 is current release.

**Comment by mbrn** [comment]
@ColinKrist 

Let me check it. I fixed it but i will check again.

**Comment by mbrn** [comment]
This is done with 1.29.1
