### ISSUE TITLE
Columns that are unhidden from remote data not displaying filter input?

### ISSUE THREAD

**Issue by CalebCox** [mbrn/material-table#390]
I've got a table that's using the `data=query` function to grab remote data, this query is also grabbing parameters (vary in amount based on user inputs) and turning these parameters into hidden columns. When one of these additional columns is unhidden, the filter input is not being displayed below the column name.

**Table Query Code**
```javascript
data={query =>
            new Promise((resolve, reject) => {
              fetch(url, {
                headers: {
                  // update current page and pageSize on pagination
                  Range:
                    "items=" +
                    query.pageSize * query.page +
                    "-" +
                    (query.pageSize * (query.page + 1) - 1)
                }
              })
                .then(response => {
                  // grab total amount of items from response content range
                  let contentRange = response.headers.get("Content-Range");
                  let itemTotal = parseInt(
                    contentRange.match(/[^items *\-*/].+/g)
                  );
                  this.setState({ rowTotal: itemTotal });
                  return response.json();
                })
                .then(result => {
                  // grab first item in results (all items will have the same entity parameters, no need to iterate over each result item)
                  let item = result[0];
                  // iterate over each entity parameter to ensure we grab all of them
                  item.entityParam.forEach(param => {
                    // create new column for each entity parameter, set column title, field data using render, and hidden to true.
                    let newColumn = {
                      title: param.inputLabel,
                      render: rowData =>
                        rowData.entityParam.find(
                          x => x.inputLabel === param.inputLabel
                        ).displayValue,
                      hidden: true
                    };
                    // check that the column doesn't already exist to avoid duplicate column listings.
                    const found = this.state.columns.some(
                      el => el.title === newColumn.title
                    );
                    if (!found) {
                      this.setState({
                        columns: [...this.state.columns, newColumn]
                      });
                    }
                  });
                  resolve({
                    data: result,
                    page: query.page,
                    totalCount: this.state.rowTotal
                  });
                });
            })
          }
```

This is setting up all of our hidden columns in the show/hide and rendering the data to the row properly but not displaying the filter input as shown below:

**Show/Hide Columns Displaying Properly**
![showhide](https://user-images.githubusercontent.com/20094217/55246366-76120d80-521b-11e9-8885-1874b3d63da8.png)

**No Filter on Added Column**
![nofilter](https://user-images.githubusercontent.com/20094217/55246436-96da6300-521b-11e9-8556-1fe4e762631d.png)

**Comment by mbrn** [comment]
Hi @CalebCox,

You didn't add 'field' to your newColumn. So material-table does not know how to filter or search on this area. You should add a field area or add a customFilterAndSearch function to column.

**Comment by CalebCox** [comment]
@mbrn Thank you for the response! I didn't see the 'field' used in the remote data example in the documentation so that never crossed my mind!

Regarding that 'field' value, the field I need is in an object, nested inside of another object which is part of an array of objects being returned from the fetch, I know the 'field' expects a string, is there any way to do dot notation to drill down the the level/index I need for that key value?

**Comment by mbrn** [comment]
You can use this kind of field: 'names.surname'

I guess that you asked for this?

**Comment by CalebCox** [comment]
@mbrn , apologies for the late follow up, this appears to have worked! Thank you!

```javascript
field: `${param.paramName}`
```
