### ISSUE TITLE
actions prop error with newest release

### ISSUE THREAD

**Issue by ColinKrist** [mbrn/material-table#392]
**Describe the bug**
* actions prop types must have changed in a recent release. It used to accept array of objects or functions where the functions get rowData passed to them. The functionality still works, but now I'm getting prop errors.

**To Reproduce**
create table with actions have one of these actions be a function that returns an object with these required props.

**Expected behavior**
* let actions have functions as an array entry again without errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/27971797/55281450-8bae3280-5302-11e9-96ac-403f3b3df9e8.png)
![image](https://user-images.githubusercontent.com/27971797/55281455-9bc61200-5302-11e9-80c5-605b8957a59e.png)

**Desktop (please complete the following information):**
 - Version: 1.28.2

**Comment by mbrn** [comment]
Hi @ColinKrist ,

Thanks for bug issue. I fixed it and it will be in next release.

**Comment by mbrn** [comment]
This is published with 1.28.3
