### ISSUE TITLE
Filter and Export do not use field accessor for complex data

### ISSUE THREAD

**Issue by barbieri** [mbrn/material-table#393]
**Describe the bug**

If I have a complex object as below, the data is properly displayed, but export do CSV and filtering do not work as it doesn't use `byString()` accessor:

```js
const data = [
{"name": {"first": "Hello", "last": "World"}},
];
const columns = [
{"field": "name.first", "title": "First Name"},
];
```

**Expected behavior**
All access should be the same.

**Comment by mbrn** [comment]
Hi @barbieri 

I will take a look at it asap. If you need a quick workaround you can override exportCsv feature to solve your problem.

**Comment by barbieri** [comment]
no hurry, I was just investigating... the actual project will use flat data structure, so won't be affected.

**Comment by crotten** [comment]
@mbrn thanks for the tip about the workaround. :)

**Comment by mbrn** [comment]
This is done with version 1.31.0
