### ISSUE TITLE
Warning: Failed prop type: Invalid prop `detailPanel` supplied to `MaterialTable`

### ISSUE THREAD

**Issue by theofournier** [mbrn/material-table#394]
Hi,
First thanks for your awesome package.

I have this error when I put an array of detailPanel as props to the MaterialTable component.
![image](https://user-images.githubusercontent.com/25389865/55301589-65aa9e80-5478-11e9-8ac3-a130349a807f.png)

Here my code :
![image](https://user-images.githubusercontent.com/25389865/55301666-a4405900-5478-11e9-9bcc-10196f1c7b09.png)

But all is working well. There is just this warning in the console.
![image](https://user-images.githubusercontent.com/25389865/55301690-cf2aad00-5478-11e9-8a68-4b85edf030d6.png)

Do you know what is the problem?

Thanks

**Comment by mbrn** [comment]
Hi @theofournier ,

I guess that it is a PropTypes warning. I will take a look at it asap.

**Comment by mbrn** [comment]
This is done with version 1.31.0

**Comment by lasimonne** [comment]
The warning is still there in version 1.40.1

**Comment by mbrn** [comment]
Hi @lasimonne ,

I will check it asap.

**Comment by emrekara37** [comment]
Hi,
i tried in `1.47.0` it works.
Thanks

**Comment by hugoxhaal** [comment]
Still happening in version 1.54.1

**Comment by lfsando** [comment]
Happening for me. I think it started after the last update that fixed color props.


    backend.js:6 Warning: Failed prop type: Invalid prop `detailPanel` supplied to `MaterialTable`.
    in MaterialTable
    in Unknown (created by WithStyles(Component))
    in WithStyles(Component) (created by ClientList)
    in div (created by ClientList)
    in ClientList (created by ConnectFunction)

**Also, after this new update it started giving me more warning messages:**

    backend.js:6 Warning: Failed prop type: Invalid prop `color` of value `inherit` supplied to 
    `ForwardRef(TextField)`, expected one of ["primary","secondary"].
    in ForwardRef(TextField) (created by WithStyles(ForwardRef(TextField)))
    in WithStyles(ForwardRef(TextField)) (created by MTableToolbar)
    in div (created by ForwardRef(Toolbar))
    in ForwardRef(Toolbar) (created by WithStyles(ForwardRef(Toolbar)))
    in WithStyles(ForwardRef(Toolbar)) (created by MTableToolbar)
    in MTableToolbar (created by WithStyles(MTableToolbar))
    in WithStyles(MTableToolbar) (created by Toolbar)
    in div (created by Toolbar)
    in Toolbar (created by MaterialTable)
    in div (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (created by Container)
    in Container (created by MaterialTable)
    in Provider (created by App)
    in App (created by ErrorBoundary)
    in ErrorBoundary (created by DragDropContext)
    in DragDropContext (created by MaterialTable)
    in MaterialTable
    in Unknown (created by WithStyles(Component))
    in WithStyles(Component) (created by ClientList)
    in div (created by ClientList)

**And:**
    Warning: Failed prop type: Invalid prop `color` of value `inherit` supplied to 
    ForwardRef(FormControl)`, 
    expected one of ["primary","secondary"].
    in ForwardRef(FormControl) (created by WithStyles(ForwardRef(FormControl)))
    in WithStyles(ForwardRef(FormControl)) (created by ForwardRef(TextField))
    in ForwardRef(TextField) (created by WithStyles(ForwardRef(TextField)))
    in WithStyles(ForwardRef(TextField)) (created by MTableToolbar)
    in div (created by ForwardRef(Toolbar))
    in ForwardRef(Toolbar) (created by WithStyles(ForwardRef(Toolbar)))
    in WithStyles(ForwardRef(Toolbar)) (created by MTableToolbar)
    in MTableToolbar (created by WithStyles(MTableToolbar))
    in WithStyles(MTableToolbar) (created by Toolbar)
    in div (created by Toolbar)
    in Toolbar (created by MaterialTable)
    in div (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (created by Container)
    in Container (created by MaterialTable)
    in Provider (created by App)
    in App (created by ErrorBoundary)
    in ErrorBoundary (created by DragDropContext)
    in DragDropContext (created by MaterialTable)
    in MaterialTable
    in Unknown (created by WithStyles(Component))
    in WithStyles(Component) (created by ClientList)
    in div (created by ClientList)`

**Comment by ahaq0** [comment]
Getting this as well, any help would be appreciated! 

connectAdvanced.js:233 Warning: Failed prop type: Invalid prop `color` of value `inherit` supplied to `ForwardRef(TextField)`, expected one of ["primary","secondary"].
    in ForwardRef(TextField) (created by WithStyles(ForwardRef(TextField)))
    in WithStyles(ForwardRef(TextField)) (created by MTableToolbar)
    in div (created by ForwardRef(Toolbar))
    in ForwardRef(Toolbar) (created by WithStyles(ForwardRef(Toolbar)))
    in WithStyles(ForwardRef(Toolbar)) (created by MTableToolbar)
    in MTableToolbar (created by WithStyles(MTableToolbar))
    in WithStyles(MTableToolbar) (created by MaterialTable)
    in div (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (created by Container)
    in Container (created by MaterialTable)
    in Provider (created by App)
    in App (created by ErrorBoundary)
    in ErrorBoundary (created by DragDropContext)
    in DragDropContext (created by MaterialTable)
    in MaterialTable
    in Unknown (created by WithStyles(Component))
    in WithStyles(Component) (created by Students)
    in Students (created by App)
    in RouterPage (created by App)
    in div (created by FocusHandlerImpl)
    in FocusHandlerImpl (created by Context.Consumer)
    in FocusHandler (created by RouterImpl)
    in RouterImpl (created by LocationProvider)
    in LocationProvider (created by Context.Consumer)
    in Location (created by Context.Consumer)
    in Router (created by App)
    in div (created by App)
    in App

**Comment by ldsmike88** [comment]
The warning still occurs in 1.54.2.

**Comment by msidlo** [comment]
Warning occurs in material-table@1.56.1

**Comment by brunojkurt** [comment]
I think this must to be placed on open issues.

**Comment by brunojkurt** [comment]
***I found a solution for this warning in my case, maybe the source of your warning its not the same***

Since the warning is throwed by some object validation i started to removing items hoping the warning goes away to find the issue, and realize that when i removed the icon prop, the warning was gone, so i took a look in the docs again and saw the problem:

I was declaring the icon prop in the wrong way:
![wrong](https://user-images.githubusercontent.com/31192708/73537912-68fc1700-4408-11ea-96a4-1d10fbd47283.PNG)

Right way:
![right](https://user-images.githubusercontent.com/31192708/73537972-8cbf5d00-4408-11ea-85b8-a90d2dbef72b.PNG)

**Comment by ldsmike88** [comment]
@brunojkurt, 
While your solution fixes it and I'm using it because I don't want the annoying warning, the documentation says you should be able to do it either way:

## detailPanel
Field | Type | Default | Description
-- | -- | -- | --
disabled | boolean | false | Flag for button disabled or enabled
icon | string or ReactElement |   | Icon of button from material icons or custom component

**Comment by brunojkurt** [comment]
@ldsmike88 
I agree, it should support material icons and other custom elements according the docs.

**Comment by dannielarriola** [comment]
Another solution, create a function in same file that return the icon component

**Comment by JimiSweden** [comment]
> Another solution, create a function in same file that return the icon component

@dannielarriola 
can you give an example? I tried this but it still shows the same error.

```
function getIcon() {
    return VerticalSplitTwoTone;
}
...
detailPanel={[
                    { icon: getIcon(),
...
```

**Comment by thomskint** [comment]
I just did this `icon: ()=> <ChatIcon/>,`
