### ISSUE TITLE
Something wrong with detailPanel

### ISSUE THREAD

**Issue by imajindev** [mbrn/material-table#396]
```
detailPanel={[
                {
                  tooltip: 'Show orders',
                  render: (agent) => {
                    return (<CustomComponent agent={agent} />)
                  },
                },
              ]}
```
tried to do this
it doesnt work

but tried to do this
```
detailPanel={[
                {
                  tooltip: 'Show crew orders',
                  render: (agent) => {
                    return (
                      <div style={{ overflowY: 'auto', height: '300px' }}>
                        <div>{agent.name}</div>
                      </div>
                    )
                  },
                },
              ]}
```

which is basically the render in CustomComponent and it works
any idea?
does it need to be PureComponent? really no idea whats going on here

**Comment by imajindev** [comment]
hmm seems like for detailPanel, the component inside of it should not be doing any fetching to remove server for more data to display in the detail panel component?

**Comment by mbrn** [comment]
Actually you can. Detail panel works very simple. It only renders you component when you expand detail panel.

**Comment by imajindev** [comment]
yeah i also thought thats how the behaviour will be, but somehow it just dont work

**Comment by mbrn** [comment]
@imajindev 

Take a look at this:

https://codesandbox.io/embed/j41j6yr5k9

**Comment by imajindev** [comment]
yeah my component is not as straight forward as the example
it fetch something from server then do a loop to render its own list
so the height of the component is a variable. i will give you code example next time. for now i have opt to not using this component.  i developed my own custom solution for this
