### ISSUE TITLE
Error in update for inline editing

### ISSUE THREAD

**Issue by tkarpeichik** [mbrn/material-table#400]
Nice component.   Is the inline editing ready for use?  Have you come across the following?

Trying to use the inline edit feature but getting the following error after clicking save:

```
ErrorEvent {isTrusted: true, message: "Uncaught TypeError: Cannot read property 'then' of undefined", filename: "webpack-internal:///../node_modules/material-table/dist/material-table.js", lineno: 682, colno: 68, …}
```

The line tossing the error is:

_this5.props.editable.onRowUpdate(newData, oldData)

Here's the function containing the above line:
```
function () {
                _this5.props.editable.onRowUpdate(newData, oldData).then(function (result) {
                  _this5.dataManager.changeRowEditing(oldData);

                  _this5.setState((0, _objectSpread2.default)({
                    isLoading: false
                  }, _this5.dataManager.getRenderState()), function () {
                    if (_this5.isRemoteData()) {
                      _this5.onQueryChange(_this5.state.query);
                    }
                  });
                }).catch(function (reason) {
                  _this5.setState({
                    isLoading: false
                  });
                });
              });
```

**Comment by mbrn** [comment]
I published inline editing but it needs many improvements. I will check this case asap.

**Comment by mbrn** [comment]
@tkarpeichik 

Did you return a Promise in editable.onRowUpdate functions. it expects a Promise

**Comment by mbrn** [comment]
If it does not work please ask a question on stackoverflow with a tag material-table

**Comment by adithyadinesh96** [comment]
Even i am getting same issue any help ?

**Comment by acsakshay** [comment]
Getting this error after recent update. Does this have to do anything with newer React version? 
Also, another issue (https://github.com/mbrn/material-table/issues/1293) has an effect due to recent changes from material-ui/core update.

Any help or temporary fix?

**Comment by mageshkumar1598** [comment]
@mbrn Still this bug is there. Any help to resolve it?

**Comment by pbogaard** [comment]
Still this bug?
