### ISSUE TITLE
sometimes want fixed the action panel

### ISSUE THREAD

**Issue by symnetry** [mbrn/material-table#402]
sometimes my data are too long ,
i want my action panel at the last and aways fixed position 
like this↓
![1554200629(1)](https://user-images.githubusercontent.com/20887001/55395674-97089480-5574-11e9-9886-c4b5aba96bba.png)

**Comment by mbrn** [comment]
we already have a issue that is about freezed columns. #43

**Comment by jakeleventhal** [comment]
This feature would be awesome! Looking forward to it Mehmet and thanks for all the effort. I know I speak for everyone when I say we appreciate it.

**Comment by mbrn** [comment]
> This feature would be awesome! Looking forward to it Mehmet and thanks for all the effort. I know I speak for everyone when I say we appreciate it.

Thanks @jakeleventhal 

I love work for opensource:). I am very busy nowadays but i will resolve all issues asap. You know me:)

**Comment by jakeleventhal** [comment]
not stale

**Comment by jakeleventhal** [comment]
not stale

**Comment by jakeleventhal** [comment]
not stale

**Comment by jakeleventhal** [comment]
not stale

**Comment by jakeleventhal** [comment]
not stale
