### ISSUE TITLE
Get grouping feature Chips list

### ISSUE THREAD

**Issue by HenryTux** [mbrn/material-table#405]
Hi there mbrn!

Your component has been very very useful for a project I am currently working on, but I came across with a minor issue when the view I am rendering refreshes (i.e. receives new props) and I have grouped columns by dragging their headers to the grouping component, where chips are then displayed. The grouping is reset to default, displaying no chips at all and sorting the columns as usual, if that makes sense.

My question is if there is any way I can somehow keep in my parent state the columns I am grouping. I have been looking into it and going over the source code to see if there is a prop I may use to get a list or object that I can pass as prop to the Table itself later on, when the render updates.

Thanks in advance!

**Comment by mbrn** [comment]
Hi @HenryTux ,

You can store columns in your store. table add a field as 'tableData', and store everything on it. If you keep columns in your own state, problem will be resolved. 

Otherwise problem is same with #263
