### ISSUE TITLE
Dark theme does not work in column headers

### ISSUE THREAD

**Issue by Rassilion** [mbrn/material-table#406]
**Describe the bug**
Dark theme does not work in column headers

**To Reproduce**
https://codesandbox.io/embed/5zzvv984rk

**Screenshots**
![image](https://user-images.githubusercontent.com/1886248/55413220-91f61600-5571-11e9-9c6b-19f744ed1486.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: chrome
 - Version: 73

**Comment by mbrn** [comment]
This is published with 1.28.3
