### ISSUE TITLE
Detailpanel width problem

### ISSUE THREAD

**Issue by Rassilion** [mbrn/material-table#408]
**To Reproduce**
Bug starts with 1.28.2, 1.28.1 version work as expected.
https://codesandbox.io/embed/5zzvv984rk

**Expected behavior**
![image](https://user-images.githubusercontent.com/1886248/55463763-62dbb500-5602-11e9-84e6-ae74638d656c.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/1886248/55463724-4e97b800-5602-11e9-8d26-25c87b5a2d29.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: chrome
 - Version: 73

**Comment by Rassilion** [comment]
duplicate of #389

**Comment by mbrn** [comment]
This is done with 1.29.1
