### ISSUE TITLE
Option to add a new row at the beginning of the table 

### ISSUE THREAD

**Issue by namy16** [mbrn/material-table#410]
Hello @mbrn,

I had a chat with you recently about adding a feature so that we can add a new row at the beginning of the table while clicking on the default Add Icon. You talked about adding an option of addRowPosition field. Can you please add this feature ?, I need it asap.

**Comment by mbrn** [comment]
addRowPosition field added to options with version 1.31.0

**Comment by namy16** [comment]
works perfectly, thank you @mbrn
