### ISSUE TITLE
how to add a new row with my own customised Add Button

### ISSUE THREAD

**Issue by namy16** [mbrn/material-table#411]
Hi @mbrn 

Can you please share a code snippet which describes how to trigger the same functionality that the default add Icon button is doing i.e to create a new row, with my customised action button placed at the left of the toolbar.

`<button> Add New Task </button>`

**Comment by jbkuczma** [comment]
I was able to mimic the default add button's functionality with the following:

```js
<>
  <MaterialTable innerRef={ref => this.myTable = ref} />
  <MyCustomButton 
    onClick={() => this.myTable.setState({ showAddRow: !this.newMenuMealsRef.state.showAddRow })}
  >
    Add New Item
  <MyCustomButton>
</>
```

**Comment by namy16** [comment]
It works like a charm :) thanks a lot @jbkuczma @mbrn
