### ISSUE TITLE
New column option next to readOnly

### ISSUE THREAD

**Issue by 1981ats** [mbrn/material-table#412]
Please excuse my bad English.
Please give the option on the column next to readOnly to define second option that it will not be editable to insert a new value After inserting the new data I send it to the server where it is inserted into the database with id according to the sequence. If the id is displayed, it is not desirable to allow it to be edited. When editing, I set a new property of the readOnly column. I must not enter the id value when inserting it, as it will be added by the server sequence.

**Comment by mbrn** [comment]
Hi @1981ats 

I will add this feature asap.

**Comment by 1981ats** [comment]
Great. Thank you very much.

**Comment by spazzarama** [comment]
@mbrn if you want you can change my implementation so that readonly means readonly in add too. I don’t use the add row feature in my project so it has no impact.

**Comment by mbrn** [comment]
editable feature added to options.
