### ISSUE TITLE
Pagination wrong if my theme specify padding for MuiIconButton

### ISSUE THREAD

**Issue by 1981ats** [mbrn/material-table#413]
Please excuse my bad English.
If i overrides **padding** for **MuiIconButton** **root**, because default is unnecessarily big for me, display pagination in table foother is wrong. 

```
overrides: {
    MuiIconButton: {
      root: {
        padding: 2,
      }
    },
},
```

![material-table-pagination-wrong](https://user-images.githubusercontent.com/49246481/55499116-7e1be400-5645-11e9-84a5-b521df7df49b.png)
The problem is probably in the **m-table-pagination.js** line
<Typography variant="caption" style={{flex: 1, textAlign: 'center', **lineHeight: '48px'**}}>
at a fixed value of 48px, which corresponds to the default sizes in material ui theme, but if I change padding or other sizes, it will cause a problem.

**Comment by mbrn** [comment]
I will test this case asap and try to find a custom solution

**Comment by 1981ats** [comment]
Great. Thank you very much.

**Comment by mbrn** [comment]
This is done with version 1.32.0
