### ISSUE TITLE
onChangeRowsPerPage is not triggered if remote data

### ISSUE THREAD

**Issue by spazzarama** [mbrn/material-table#415]
**Describe the bug**
The onChangeRowsPerPage event is not triggered if using remote data.

**To Reproduce**
1. Add onChangeRowsPerPage={(pageSize) => {console.log('Page size changed!'};} to remote data example (like in https://mbrn.github.io/material-table/#/docz-examples-14-example-remote-data)
2. Change page size
3. Do not see "Page size changed!" in console

**Expected behavior**
onChangeRowsPerPage handler called when a remote data source is used and user changes page size.

**Workaround**
Within your remote data function the new page size will be provided.

**Additional context**
The following is the code that produces the issue. Line 282 would need to be duplicated into the first condition.

https://github.com/mbrn/material-table/blob/master/src/material-table.js#L273

                  if (this.isRemoteData()) {
                    const query = { ...this.state.query };
                    query.pageSize = event.target.value;
                    query.page = 0;
                    this.onQueryChange(query);
                  }
                  else {
                    this.dataManager.changeCurrentPage(0);
                    this.setState(this.dataManager.getRenderState(), () => {
                      this.onChangeRowsPerPage(event.target.value);
                    });
                  }

**Comment by spazzarama** [comment]
@mbrn I can make this change, but not sure if you want to make this or just update documentation?

**Comment by mbrn** [comment]
Hi @spazzarama ,

We can do this. But firstly we should add a callback to onQueryChange function. This callback will be fired after setState completed. 

If you want you can send a PR?

Thanks for your contributions.

**Comment by mbrn** [comment]
This is done with version 1.31.0
