### ISSUE TITLE
Zindex of table header gets in the way of react-select dropdowns

### ISSUE THREAD

**Issue by ColinKrist** [mbrn/material-table#416]
**Describe the bug**
We have a form above a table that has a react-select component that when opening it causes issues with the header of material-table. 

perma-link to the index set in the header:
https://github.com/mbrn/material-table/blob/92b55a4e88858c45218beacfeb8234ff3274a8c7/src/m-table-header.js#L181

Is there a reason why the zIndex is set? I haven't dug around too much, but thought I'd inquire. Could it have to do with the feature of body scrolling? If that's the case could we toggle the style based off the prop being set?

**Screenshots**

![image](https://user-images.githubusercontent.com/27971797/55528358-23dd4c00-5662-11e9-9de3-f3f7d5591189.png)

**Expected behavior**
header respects elements trying to display on top of it.
![image](https://user-images.githubusercontent.com/27971797/55528443-79195d80-5662-11e9-8e12-60fc651bf566.png)

**NOTE** achieved expected behavior by removing zIndex from styles in header.

**Desktop (please complete the following information):**
 - OS: all
 - Browser all
 - Version: 1.29.1

**Comment by mbrn** [comment]
Hi @ColinKrist 

Thanks for giving clear information about bug. It could be related with stickyHeaderStyle. I will take a look at this bug asap.

**Comment by mbrn** [comment]
Hi @ColinKrist ,

You can change z-index of header by giving a `headerStyle` to options. 

```javascript
 <MaterialTable
                options={{
                  maxBodyHeight: 400,
                  headerStyle: {
                    zIndex: 8
                  }
                }}
...
              />
```

**Comment by radulle** [comment]
I think same reason might be that AppBar doesn't cast shadow over the table.

**Comment by Amyx000** [comment]
Adding z-index:0 on TableCell of TableHead works perfectly fine.
