### ISSUE TITLE
MTableEditRow to use DataManager getFieldValue to support nested data fields

### ISSUE THREAD

**Issue by spazzarama** [mbrn/material-table#417]
**Is your feature request related to a problem? Please describe.**
Existing values for nested fields display as blank when editing a row.

**Describe the solution you'd like**
MTableEditRow to retrieve the current value of a cell using the data manager getFieldValue function as per MTableBodyRow

**Describe alternatives you've considered**
Copying data from sub-objects onto properties of the root record, however this gets cumbersome when interacting with a broader system.

**Additional context**
I have changes for a pull request to add support for this.

Related to #162

**Comment by mbrn** [comment]
@spazzarama 

Please send your PR. I will merge it if it has not a side effect. I will examine.
