### ISSUE TITLE
How to set init order columnId and direction?

### ISSUE THREAD

**Issue by 1981ats** [mbrn/material-table#420]
Please, is any way to set init order columnId and direction, if i save this params in onOrderChange.

**Comment by mbrn** [comment]
Look at first example.

https://mbrn.github.io/material-table/#/docz-examples-04-example-sorting

**Comment by 1981ats** [comment]
Thank you very much, I looked at examples, but this I unfortunately overlooked in the code.

**Comment by xhahid43eb** [comment]
> Look at first example.
> 
> https://mbrn.github.io/material-table/#/docz-examples-04-example-sorting

Link is expired

**Comment by sergeycw** [comment]
Hi! @mbrn could you please update the link? I can't find working example. Many thanks in advance!

**Comment by jayarjo** [comment]
Sorting examples are here: https://material-table.com/#/docs/features/sorting

**Comment by sergeycw** [comment]
> Sorting examples are here: https://material-table.com/#/docs/features/sorting

Yes, thanks, I saw it. But there is no example of how to set init order columnId and direction.
