### ISSUE TITLE
Option to expand all rows by default

### ISSUE THREAD

**Issue by truongtv22** [mbrn/material-table#421]
Hello @mbrn,

I had a tree table, I want to option to expand all rows by default.
Can you please add this feature.

Thanks you.

**Comment by mbrn** [comment]
I think you added this already :) @truongtv22

**Comment by Flixbox** [comment]
@mbrn Could you share how you were able to accomplish this?

**Comment by Flixbox** [comment]
Nevermind, I found the PR with the change:

https://github.com/truongtv22/material-table/pull/13/commits/e8b015fae34b52fb28e5dd16c24765a58c52d4d9

I simply added `defaultExpanded: true` to the table options.
