### ISSUE TITLE
When you select an item, display 2 search box

### ISSUE THREAD

**Issue by malix1** [mbrn/material-table#424]
**Displaying 2 Search boxes**
When you select item/items, displays 2 search boxes

**Screenshots**
![image](https://user-images.githubusercontent.com/18161682/55550718-9c372200-56e1-11e9-8c2d-6d119714c96c.PNG)

**Comment by mbrn** [comment]
Interesting bug:) I will resolve this asap.

**Comment by malix1** [comment]
Thank you :)

**Comment by devel0** [comment]
Sorry I mistake in search before submit I searched for "**selection search**" because _selection_ option of material table and _search_ boxes twice, but cannot found that thread that would found instead using "**select search**". Feel free to close this one. I'll look for the other one.

**Comment by devel0** [comment]
23ece5a12c7b9c1cde46aa62120642cb13254749 fixes this.
