### ISSUE TITLE
Body Scroll Not working

### ISSUE THREAD

**Issue by hasankhalid** [mbrn/material-table#425]
I am giving the table a maximum height in options but the table overflows the maximum height and the header is not sticky. In case the max height does not work, Is there any other way to make the header of the table fixed on scroll? 
![Screen Shot 2019-04-04 at 6 31 44 PM](https://user-images.githubusercontent.com/20278920/55559596-f77c0b00-5707-11e9-98d6-c649ca11fb34.png)
![Screen Shot 2019-04-04 at 6 31 18 PM](https://user-images.githubusercontent.com/20278920/55559598-f814a180-5707-11e9-9b7c-fccdde8c68ed.png)

**Comment by mbrn** [comment]
Hi @hasankhalid ,

Which version do you use?

**Comment by hasankhalid** [comment]
Must have been a dependency issue or something. I just reinstalled the package and it is working fine.
