### ISSUE TITLE
Add freezed columns feature. 

### ISSUE THREAD

**Issue by mbrn** [mbrn/material-table#43]
Add freezed columns feature.

**Comment by urirahimi** [comment]
Ideally freezed columns would work as they do in this demo https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/tree-data/

Where it has a fixed initial width and allows the user to drag/adjust after it is rendered

**Comment by mbrn** [comment]
no need for now.

**Comment by revskill10** [comment]
This is useful feature to have , @mbrn when will it be landed ?

**Comment by mbrn** [comment]
I opened this issue on the first days of material-table. But i am only one developer of material-table and it is my hobby project. So i can not promise a date about issues. But as you know, i resolve issues, add features day by day :)

**Comment by revskill10** [comment]
@mbrn The intended behaviour is ability to freeze header, footer, columns on the right, columns on the left. This is nessessary when our table has about 30 columns.
In my use case, i have a table with columns like `day1, day2,...day31` for a month.

**Comment by mbrn** [comment]
You are right. I will add this feature asap.

**Comment by krunalsheth3** [comment]
+1 to this request.

**Comment by feleko** [comment]
+1 to this request

**Comment by MaxGorshkov** [comment]
+1 to this request

**Comment by JKrymarys** [comment]
+1 :)

**Comment by JKrymarys** [comment]
@all
Any workarounds in the meantime?

**Comment by ysmike** [comment]
+1 to this request

**Comment by PrincAm** [comment]
+1 as well :)

**Comment by omnislashbr** [comment]
+1

**Comment by joshling1919** [comment]
For anyone who needs a quick fix (not sure how good of a solution this is for all browsers), this codepen was a helpful example for how to implement this through CSS: https://codepen.io/paulobrien/pen/LBrMxa

```js
 const columns = [
    {
      title: 'Name',
      field: 'fullname',
      cellStyle: {
        backgroundColor: '#039be5',
        color: '#FFF',
        position: 'sticky',
        left: 0
      },
      headerStyle: {
        backgroundColor: '#039be5',
        position: 'sticky',
        left: 0,
        zIndex: 11
      }
    }
  ];
const Table = () => {
  return(
    <MaterialTable
        columns={columns}
        data={data}
        title={`Demo Title`}
        options={{
          headerStyle: {
            backgroundColor: '#01579b',
            color: '#FFF',
            position: 'sticky',
            top: 0
          }
        }}
      />
  );
}
```

**Comment by philg74** [comment]
+1 to this request.

**Comment by nisarg271** [comment]
+1 to this request.

**Comment by NickAlvesX** [comment]
+1 to this request.

**Comment by mbrn** [comment]
Hi,

I researched about this feature to find a effective way. Found a solution:

Drawing table twice and one will be absolute. But i have to make table-layout fixed when table has freezed columns. 

Please check datatables solution. And give me your feedback. 
https://datatables.net/extensions/fixedcolumns/examples/initialisation/two_columns.html

**Comment by gabriel-kohen-jdas** [comment]
@mbrn , what you had shown in the link is exactly the functionality folks are looking for.
I think that if you want to have also freeze columns on the right(maybe v2), you can work as well. You just put the dynamic table in the middle with the correct width and on the left and right of the dynamic tables you can show the frozen columns.

**Comment by codenamethanos** [comment]
Yes, the solution you mentioned is perfect. An option prop like this will do - 
```
fixedColumns:   {
            leftColumns: 2
}
```

**Comment by mbrn** [comment]
This is done with 1.57.1

Please check the documentation: https://material-table.com/#/docs/features/fixed-columns

**Comment by vdh** [comment]
@mbrn Why did you hard-code a `width` onto every column now, even when we're not using this feature? It's even ahead of the `this.props.headerStyle` and `columnDef.headerStyle` spreads, so there's no way to fix it when it breaks a custom `width` style 😞

**Comment by sachinagarwal010** [comment]
> This is done with 1.57.1
> 
> Please check the documentation: https://material-table.com/#/docs/features/fixed-columns

I was trying to consume the material table with fixedColumns and taken the same sample as given in the documenattaion, but its seems whenever I am changing my screen resolution, my fixed column is not aligned with another columns.. As per below screen shots see the fixed column is moving upwards while changing the resolution, Any suggestion please.

![image](https://user-images.githubusercontent.com/13916436/83962107-e43e6f80-a8b7-11ea-93a3-a27a187fc6f5.png)
