### ISSUE TITLE
Keep track of column visibility state

### ISSUE THREAD

**Issue by spazzarama** [mbrn/material-table#430]
**Is your feature request related to a problem? Please describe.**
Column visibility state is not tracked between refresh of data. E.g. if paging a remote data source, each time you go to the next page, the columns shown/hidden reset.

**Describe the solution you'd like**
Column visibility state to be tracked between data refreshes (e.g. when paging a remote data source, or when updating the local data source state after editing).

**Describe alternatives you've considered**
The only option at the moment is to disable column visibility selection.

**Comment by spazzarama** [comment]
One other option might be to expose the event when columns are hidden / shown so that the application can track this state.

**Comment by 1981ats** [comment]
A column visibility change event (with info of new state visibility on each column, so that I can save the current status to the configuration) would be very useful.

**Comment by mbrn** [comment]
I will implement a layout export import feature. So users can store it and then apply it later(even if browser restarted)

**Comment by spazzarama** [comment]
@mbrn if you can provide some pointers I may be able to assist on this one - the feature is fairly important for my use case.

**Comment by mbrn** [comment]
@spazzarama i will change datamanager like query for remote data. So query could be stored in anywhere. So firstly i should work on. Please be more patient:)
