### ISSUE TITLE
I can't figure out why it is coming

### ISSUE THREAD

**Issue by apsrcreatix** [mbrn/material-table#434]
![image](https://user-images.githubusercontent.com/24192742/55689129-bbaea300-599e-11e9-8f37-a07cf39140a2.png)
Please help.

**Comment by jbkuczma** [comment]
How are you passing your data into your table? The `data` prop expects whatever you pass to it to be either an array or a function for fetching remote data.

**Comment by apsrcreatix** [comment]
I am passing it as an array, I think it is because I had an issue in the data coming from the API. When I resolved it, this error got resolved for me. But this should not happen like this. There should be a better error handling mechanism. I will try to come up with a better suggestion in future if possible.

**Comment by mbrn** [comment]
> I am passing it as an array, I think it is because I had an issue in the data coming from the API. When I resolved it, this error got resolved for me. But this should not happen like this. There should be a better error handling mechanism. I will try to come up with a better suggestion in future if possible.

You are right @apsrcreatix . I should implement user friendly errors. But i don't have enough time nowadays.
