### ISSUE TITLE
Number of selected items not displayed in table header

### ISSUE THREAD

**Issue by CalebCox** [mbrn/material-table#436]
**Describe the bug**
When items are selected, the number of items does not display as shown in the demos/documentation, even with `selection: true`

**To Reproduce**
1. Setup a new table similar to below:
```javascript
<MaterialTable
            columns={this.state.columns}
            data={this.state.data}
            options={{
              filtering: true,
              paging: true,
              maxBodyHeight: 600,
              selection: true,
              pageSize: 15,
              pageSizeOptions: [15, 20, 25, 50, 100],
              showTitle: false,
              columnsButton: true,
              toolbarButtonAlignment: "right",
              actionsColumnIndex: 1
            }}
            actions={[
              {
                icon: "settings",
                tooltip: "Actions",
                // isFreeAction: true,
                onClick: (event, rowData) => {
                  console.log(rowData);
                }
              }
            ]}
          />
```
2. Click on a rows checkbox
3. See the header not display the number of selected items.

**Expected behavior**
The number of selected items should be displayed within the table header as shown below:
![Screen Shot 2019-04-08 at 2 39 58 PM](https://user-images.githubusercontent.com/20094217/55748259-3661d780-5a0c-11e9-8fb4-c8d87e2a1131.png)

**Screenshots**
![Screen Shot 2019-04-08 at 2 40 38 PM](https://user-images.githubusercontent.com/20094217/55748292-4bd70180-5a0c-11e9-8d0e-24c523864c1f.png)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.2
 - Browser: Chrome
 - Version: Version 73.0.3683.86

**Comment by mbrn** [comment]
This is done with version 1.31.0
