### ISSUE TITLE
Allow customization of edit cell

### ISSUE THREAD

**Issue by gmichalec-pandora** [mbrn/material-table#437]
**Is your feature request related to a problem? Please describe.**
There are cases where the provided field types aren't sufficient. It would be nice to be able to customize the 'edit' mode of a particular field.

**Describe the solution you'd like**
Add a new column property to provide a function for a custom edit cell renderer.

**Describe alternatives you've considered**
Couldn't find any way around it.

**Additional context**
PR incoming

**Comment by mbrn** [comment]
Hi @gmichalec-pandora 

Thanks for contribution. I will check it asap and merge it.

**Comment by mbrn** [comment]
editComponent added.
