### ISSUE TITLE
Move editRow to be the first row in table

### ISSUE THREAD

**Issue by gmichalec-pandora** [mbrn/material-table#439]
**Is your feature request related to a problem? Please describe.**
The current 'Add row' functionality renders the new row interface as the last row in the table. If you have a large table, this may be off the screen, leaving the user confused/unable to find the row edit interface.

**Describe the solution you'd like**
By moving the new row interface to be the first row in the table, it is much more discoverable - immediately below the add row button the was clicked.

**Describe alternatives you've considered**
You could do something like auto-scrolling the table perhaps, but this seems simpler and more intuitive. I also experimented with rendering the add row interface outside the table (below the header), but this solution works better.

**Additional context**
![material-table](https://user-images.githubusercontent.com/39168929/55750136-85e9d880-59f7-11e9-999f-32bcadc74138.png)

**Comment by ColinKrist** [comment]
omg yes

**Comment by mbrn** [comment]
editRowPosition feature added with version 1.31.0

**Comment by SarthakU** [comment]
This is addRowPosition in options now, if anyone arrives here from google.

**Comment by SarthakU** [comment]
This is addRowPosition in options now, if anyone arrives here from google.

**Comment by awarmfastbear** [comment]
code example:


```
<MaterialTable
....
options={{
addRowPosition: "first"
}}
...
/>
