### ISSUE TITLE
Select row collapse the tree 

### ISSUE THREAD

**Issue by Minifish57** [mbrn/material-table#443]
Hi, i have the 1.30.0 and when i select a row in a tree table all the expanded rows collapsed
(i have two search bar though)
I take the example code  from the docs site

**Expected behavior**
The rows which are expanded need to stay expanded

**Screenshots**
![Image of Code](https://media.giphy.com/media/QZIeLVn9ub69oX3bJh/giphy.gif)

**Desktop :**
 - OS: Windows 10 pro
 - Browser Chrome 
 - Version 73.0.3683.103 (Official Build) (64-bit)

**Comment by mbrn** [comment]
This is done with version 1.31.0

**Comment by mbrn** [comment]
This is done with version 1.31.0

**Comment by Minifish57** [comment]
thx a lot

**Comment by raph90** [comment]
I'm on version 1.4 and this doesn't seem to be fixed...

**Comment by yfebles** [comment]
I am on the version 1.40.1 and the issue still is present

**Comment by ruthwe** [comment]
same here!!

**Comment by v1nns** [comment]
Up
