### ISSUE TITLE
Toolbat icons alignment

### ISSUE THREAD

**Issue by mariolazzari** [mbrn/material-table#444]
**Describe the bug**
After version 1.30 introduction, my 'isfreeAction's are not aligned in toolbat, as shown by depicted screenshots

vesionr 1.29.x

![image](https://user-images.githubusercontent.com/26960147/55811004-bb222380-5ae8-11e9-962f-edaca00b1aa2.png)

version 1.30

![image](https://user-images.githubusercontent.com/26960147/55811023-c5dcb880-5ae8-11e9-83e2-376468a8830a.png)

**Comment by pak11273** [comment]
I had a similar issue.  I would downgrade back to 1.29.1

**Comment by mbrn** [comment]
This is fixed. It will be in next release.
