### ISSUE TITLE
How add Columns programatically?

### ISSUE THREAD

**Issue by orestes22** [mbrn/material-table#445]
I must add Columns programatically, because my Data have fixed object but it can have 1 or 3 columns extra, dependes of user selection of his data. 

So, my question is How add columns depending of this extra element that could be 1 or 2 or 3. 

Thanks in advance for your time

Best Regards

**Comment by orestes22** [comment]
I want add that I working the table with "remote" using the query

**Comment by pak11273** [comment]
This sounds like a good use case for Map.  After you receive your data from your api you can construct a new array for the columns prop.

**Comment by orestes22** [comment]
Yes, i could, but in some columns I rendering so I having some errors.
For example check this: https://codesandbox.io/s/lx2v9pn91m
How to resolve that?

**Comment by orestes22** [comment]
I did that before ask but didnt work, but you are right it have to work, maybe I missing something, I will try again!!. Thanks for your support @pak11273

**Comment by pak11273** [comment]
This question should go to stackoverflow!  Be the first and close this one hahaha!
