### ISSUE TITLE
selection with search duplicate the control

### ISSUE THREAD

**Issue by devel0** [mbrn/material-table#447]
**Describe the bug**
search box displayed twice in the toolbar when select option enable and select checkbox ticked

**To Reproduce**
1. Go to https://mbrn.github.io/material-table/#/docz-examples-05-example-selection
2. Click on a selection checkbox

**Expected behavior**
Only one searchbox should display

**Screenshots**

![image](https://user-images.githubusercontent.com/13405008/55827309-2defc680-5b0a-11e9-9bf3-db9032617bd1.png)

**Comment by pak11273** [comment]
Can you post this issue on Stackoverflow?  It seems more like a programming error, rather than a software bug.

**Comment by mbrn** [comment]
@pak11273 it seems a bug related with material-table. I think that we should forward only questions(help-wanted) to stackoverflow.

**Comment by orestes22** [comment]
@mbrn This is duplicated issues. The original is #424

**Comment by orestes22** [comment]
Im telling you to avoid doble tag

**Comment by devel0** [comment]
I confirm 23ece5a12c7b9c1cde46aa62120642cb13254749 fixed this issue.
I was out of sync from 6 days when I forked the project but the fix was issued meanwhile thanks to original issue #424

**Comment by orestes22** [comment]
This is published in the  version 1.31.0
