### ISSUE TITLE
[Feature request] Event handler for group dragging

### ISSUE THREAD

**Issue by revskill10** [mbrn/material-table#448]
I'd love to attach event handler when dragging column groups.

Main use case is to set query string based on group headers.

**Describe the solution you'd like**

In grouping options, allows an event handler like
```js
function onDropped(currentDroppedColumns) {}
```

**Comment by behrouz-s** [comment]
How can I get groups list after user drag groups?

**Comment by paulrimiru** [comment]
Any progress on this feature?

**Comment by hongjs** [comment]
following this feature
