### ISSUE TITLE
initialPage in options does not work

### ISSUE THREAD

**Issue by bchara** [mbrn/material-table#450]
Using provided demo.js, as an ex. add to second table:
`          <MaterialTable
            options={{
              pageSize: 3,
              initialPage: 3,
            }}
            data={[
              { name: "Mehmet", surname: "Baran", birthYear: 1987, birthCity: 63 },
              { name: "Zerya Betül", surname: "Baran", birthYear: 1987, birthCity: 63 },
              { name: "Smith", surname: "Joe", birthYear: 1979, birthCity: 77 },
              { name: "Smith2", surname: "Joe", birthYear: 1979, birthCity: 77 },
              { name: "Smith3", surname: "Joe", birthYear: 1979, birthCity: 77 },
              { name: "Smith4", surname: "Joe", birthYear: 1979, birthCity: 77 },
              { name: "Smith5", surname: "Joe", birthYear: 1979, birthCity: 77 },
              { name: "Smith6", surname: "Joe", birthYear: 1979, birthCity: 77 },
              { name: "Smith7", surname: "Joe", birthYear: 1979, birthCity: 77 },
              { name: "Smith8", surname: "Joe", birthYear: 1979, birthCity: 77 },
              { name: "Smith9", surname: "Joe", birthYear: 1979, birthCity: 77 },
              { name: "Smith10", surname: "Joe", birthYear: 1979, birthCity: 77 },
              { name: "Smith11", surname: "Joe", birthYear: 1979, birthCity: 77 },
              { name: "Smith12", surname: "Joe", birthYear: 1979, birthCity: 77 },
              { name: "Smith13", surname: "Joe", birthYear: 1979, birthCity: 77 },
              { name: "Smith14", surname: "Joe", birthYear: 1979, birthCity: 77 },
              { name: "Smith15", surname: "Joe", birthYear: 1979, birthCity: 77 },
              { name: "Smith16", surname: "Joe", birthYear: 1979, birthCity: 77 },
              { name: "Smith17", surname: "Joe", birthYear: 1979, birthCity: 77 },
              { name: "Smith18", surname: "Joe", birthYear: 1979, birthCity: 77 },
              { name: "Smith19", surname: "Joe", birthYear: 1979, birthCity: 77 },
              { name: "Smith20", surname: "Joe", birthYear: 1979, birthCity: 77 },
              { name: "Smith21", surname: "Joe", birthYear: 1979, birthCity: 77 },
            ]}`
Notice that the starting page does not change...

dataManager.changeOrder is setting the currentPage to 0 and is called after dataManager.changeCurrentPage in setDataManagerFields... is it enough to change their calling order?

Many thanks!

**Comment by mbrn** [comment]
This is done with version 1.31.0
