### ISSUE TITLE
how can i put the selected state in tree data by first render

### ISSUE THREAD

**Issue by symnetry** [mbrn/material-table#454]
my data may like this 
```
[
    {
      id: 1,
      name: 'a',
      type: 'adult',
      selected:true,
    },
    {
      id: 2,
      name: 'b',
      parentId: 1,
      selected:true,
    },
    {
      id: 3,
      name: 'c',
      parentId: 1,
      selected:true,
    },
    {
      id: 4,
      name: 'd',
      parentId: 3,
      selected:false
    },
    {
      id: 5,
      name: 'e',
      selected:false
    },
    {
      id: 6,
      name: 'f',
      parentId: 5,
      selected:false
    }
]
```

and i how can i control the checkbox selected
like this 
![1554978571(1)](https://user-images.githubusercontent.com/20887001/55950585-d5463800-5c87-11e9-9c92-ca4e25b30132.jpg)

**Comment by mbrn** [comment]
Hi @symnetry 

We decided to forward help requests to stackoverlow. Can you ask this question on stackoverflow with material-table tag, please?

I will reply it with same speed :)
