### ISSUE TITLE
updating data through props causes all nested rows to collapse/ gives full render

### ISSUE THREAD

**Issue by Whitebytes** [mbrn/material-table#455]
I do something like
render(){
<MaterialTable 
data={this.state.data} ...

whenever new data arrives from the sever (progress-data server initiated) I modify the data within the changed rows, and do a setState{data:data}).. this causes a full render and all expanded nested rows are collapsed..
Wats the best way to update rowdata without a full render?

**Comment by mbrn** [comment]
Hi @Whitebytes ,

After changing data of table it requires calculate everything according to new data. This means you update table. So it needs a render. What is problem with this?

**Comment by Whitebytes** [comment]
Hello @mbrn,
thanx for your help. see attached pic. Everytime i get an update on the progress of the uploaded file from the server, all expended nested child elements collapse, and selections are lost. Is the a "proper" way to upload this row/cell info without rerendering the whole table?
![Schermafbeelding 2019-04-11 om 19 26 21](https://user-images.githubusercontent.com/1280960/55978462-26f2c080-5c90-11e9-882d-0b8b53c2cf19.png)

**Comment by bastienmenis** [comment]
I am facing the same issue. I think the way to fix it would be to add props to control the selection and which detail panels are expanded.

**Comment by mbrn** [comment]
Actually material-table store selection, expand and other flags on your data and columns. Look at your data, everyrow has a tableData field after first render. If you can keep tableData and copy it to new row it will keep state of table.

**Comment by Whitebytes** [comment]
Thats strange, i'm pretty sure i'm not refreshing de date, this is the code for the updated:
subscribe(this.props.token, 'uploadProgress',
                (message) => {
                var payload = JSON.parse(message.payload);
                var data = this.state.data;
                var row = data.find((row)=>{return row.mediaRawId == payload.mediaRawId})
                
                if (row){
                    row.progress=payload.progress
                    row.size =payload.size
                    this.setState({'data':data});
                }
            })

**Comment by mbrn** [comment]
Can you ask this question on stackoverflow or create a codesandbox example to reproduce easily?

**Comment by bastienmenis** [comment]
@mbrn Thank you for your response, using `tableData` solved my problem.

**Comment by Whitebytes** [comment]
here is the reproduce in sandbox
https://codesandbox.io/s/k3v7477417

**Comment by mbrn** [comment]
@Whitebytes 

I fixed this issue with version 1.32.0 . Can you upgrade it please?

**Comment by JoeKyy** [comment]
This error has not been fixed, I found it today on 1.32.0
![GIF](https://user-images.githubusercontent.com/2018763/56769052-75bb5280-6786-11e9-986e-0f160b69528a.gif)

**Comment by JoeKyy** [comment]
This error has not been fixed. I found it today on 1.32.0

![GIF](https://user-images.githubusercontent.com/2018763/56769188-d185db80-6786-11e9-87f3-087dfb397d31.gif)

**Comment by JoeKyy** [comment]
This error has not been fixed. I found it on 1.32.0

![wertwerwerwe](https://user-images.githubusercontent.com/2018763/56769426-8d470b00-6787-11e9-9002-625063c9d92e.gif)
