### ISSUE TITLE
Update data when using Remote Data after custom action?

### ISSUE THREAD

**Issue by CalebCox** [mbrn/material-table#457]
I have a custom action that is making an API call to my backend to delete data from my database, this in turn removes the item that is being displayed from the database.

How can I get the remote data to be queried again so that Material Table can re-render with the changes applied? 

I initially thought to try to re-render the component using a setState change but that doesn't appear to be working. (i can see the state changing accordingly but the table never fetchs the data again)

```javascript
             {
                  icon: "delete",
                  tooltip: "Delete Partner",
                  onClick: (event, rowData) => {
                    console.log(rowData);
                    let data = {
                      entityId: rowData[0].entityId
                    };
                    fetch("/deleteEntity", {
                      method: "POST",
                      headers: {
                        "Content-Type": "application/json"
                      },
                      body: JSON.stringify(data)
                    }).then(response => {
                      if (response.status === 204) {
                        let index = currentSelectedRows.findIndex(
                          x => x.entityId === rowData[0].entityId
                        );
                        currentSelectedRows.splice(index, 1);
                        this.setState({ currentSelected: currentSelectedRows });
                        console.log("Partner Deleted");
                      } else if (response.status === 500) {
                        console.log("Something went wrong");
                      }
                    });
                  }
                }
```

**Comment by mbrn** [comment]
@CalebCox 

We decided to forward help requests to stackoverflow. Can you ask this question on SO with `material-table` tag. I or another user will reply it asap.

**Comment by CalebCox** [comment]
@mbrn posted to SO, see [here](https://stackoverflow.com/questions/55639565/update-data-when-using-remote-data-after-custom-action)
