### ISSUE TITLE
Grouping: Auto Expansion or workaround to Expand All 

### ISSUE THREAD

**Issue by jcg359** [mbrn/material-table#458]
Hello - 

Is there a flag similar to defaultExpanded but for for grouping rather than trees?

Alternatively, is there a way i could programatically invoke an expand on all rows?

Thanks in advance!

**Comment by mbrn** [comment]
Hi @jcg359 ,

1. I can use defaultExpanded prop to expand all groups by default. 
2. Unfortunately. But i can add a button on group bar to expand/collapse all. Is this enough for your requirement.

**Comment by jcg359** [comment]
That would be great thank you.

**Comment by CQuinn222** [comment]
Did the defaultExpanded prop ever get added for default groups expansion?

**Comment by anishdev89** [comment]
Is this feature got added?
