### ISSUE TITLE
What is the proper way to have a sum row?

### ISSUE THREAD

**Issue by bluryi** [mbrn/material-table#460]
Hi-

Could anyone show me what is the proper way to have a sum/subtotal row that can be excluded from column sorting? 
For example:
```
columns={[
                { title: 'Name', field: 'name', defaultSort: 'asc' },
                { title: 'Candy', field: 'candy', type: 'numeric' },
              ]}
data={[{ name: 'Mehmet', candy: 2 }, { name: 'Zerya', candy: 3 }]}
```
Now I want to add a sum row at the end which has "Total       5", and this row should be fixed at the bottom. 
Is there a way to do this?

Thanks in advance!

**Comment by mbrn** [comment]
Hi @bluryi ,

I am planning to add summary row feature (#27). It will be done asap.

**Comment by bluryi** [comment]
Got it. Thanks a lot!

**Comment by codenamethanos** [comment]
Seconded. Summary will be really useful!

**Comment by jasonvooo** [comment]
Any update on this feature?

**Comment by rxhl** [comment]
Any update on this feature?

**Comment by RaphaelSparK** [comment]
Any update on this feature?
