### ISSUE TITLE
Refetch data from remote endpoint

### ISSUE THREAD

**Issue by zanjan2010** [mbrn/material-table#463]
Is there any solution to refetch data from remote datasource?

**Comment by mbrn** [comment]
Look at this: 

https://mbrn.github.io/material-table/#/docz-examples-14-example-remote-data

**Comment by zanjan2010** [comment]
I didnt get any idea about the example 
I need to force material table to get data from remote endpoint in the current page programmatically

**Comment by mbrn** [comment]
You can use tableRef to take ref of table. Then call tableRef.onQueryChange().

If you could not, please ask a question in Stackoverflow with material-table tag.

**Comment by zanjan2010** [comment]
Thanks It's done
