### ISSUE TITLE
Disable add button when Editable if the field in last row has x value

### ISSUE THREAD

**Issue by cybermizrach** [mbrn/material-table#465]
**Is your feature request related to a problem? Please describe.**
I have a table that some rows. If the last row has either an ID 3 or Allocation % of 100, I want to disable the add button

| ID | Allocation % |
| 1 | 25% |
| 2 | 55% |
| 3 | 100% |

**Describe the solution you'd like**
The editable should have the functionality to disable the add button based on the value of some fields.
Another related functionality is to disable the add button if the table has X records.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by mbrn** [comment]
@cybermizrach 

As a workaround: Currently if you set `onRowAdd` function as undefined it will remove add button. So you can set `onRowAdd` according to your conditions. 

But i will add a options to editable table to configure buttons according to some conditions. For example some rows may not be updateable or removable.

**Comment by MaxGorshkov** [comment]
> Currently if you set `onRowAdd` function as undefined it will remove add button

but how I can do it with some condition? ex, only for rows with id > 10?

**Comment by mbrn** [comment]
> > Currently if you set `onRowAdd` function as undefined it will remove add button
> 
> but how I can do it with some condition? ex, only for rows with id > 10?

You can not. I will add some features editable like this case.

**Comment by cybermizrach** [comment]
> @cybermizrach
> 
> As a workaround: Currently if you set `onRowAdd` function as undefined it will remove add button. So you can set `onRowAdd` according to your conditions.
> 
> But i will add a options to editable table to configure buttons according to some conditions. For example some rows may not be updateable or removable.

Thanks @mbrn ! How can I set `onRowAdd` function as undefined and where should I add that logic?

**Comment by mbrn** [comment]
editable={
// Do not use onAddRow here. So it will be undefined. 
}

**Comment by itaimayer** [comment]
> editable={
> // Do not use onAddRow here. So it will be undefined.
> }



> > > Currently if you set `onRowAdd` function as undefined it will remove add button
> > 
> > 
> > but how I can do it with some condition? ex, only for rows with id > 10?
> 
> You can not. I will add some features editable like this case.

have you elready add this feature?

**Comment by phoenix214** [comment]
@mbrn I need this feature also. Did you add it already?

**Comment by Wadprog** [comment]
I am having the same issue, the problem is I have different types of users and some cannot simply create new data when I try 
`onRowAdd: () => (isAdmin ? handleAdd : undefined),` the Add icon is still here any help

**Comment by Wadprog** [comment]
I found the way around it `onRowAdd: conditionTrue ? handleAdd : undefined,`
