### ISSUE TITLE
Don't use custom render for grouping

### ISSUE THREAD

**Issue by revskill10** [mbrn/material-table#466]
Currently, group dragging doesn't work if a column has a custom render function.

## Solution

Use a `dragRender` function which specify the string to show when grouping

**Comment by victor-accarini** [comment]
@mbrn I have the same problem and would like to help fix this...

Do you prefer a specific function to handle group rendering or should we handle everything inside the `render` function?

For the latter option it would be nice to send a third argument with all group rows data, so we could choose which rows to use when rendering for the group...

**Comment by csforbes** [comment]
For anyone else dealing with this issue, I was able to get past this issue by writing a "customRender" utility function.

```
function customRender(value, renderType, renderFunc, field, ...args) {
    if (renderType === 'row') {
        return renderFunc(value[field], ...args);
    }
    if (renderType === 'group') {
        return renderFunc(value, ...args);
    }
}

//normal render function
function renderCellData(status) {
   //do stuff
}

//using in column object
...
field: 'status',
render: (value, renderType) => customRender(value, renderType, renderCellData, 'status')
```

**Comment by KLM-GIT** [comment]
Thanks @csforbes - your solution works great for grouping by a rendered column value.

**Comment by somandubey** [comment]
> For anyone else dealing with this issue, I was able to get past this issue by writing a "customRender" utility function.
> 
> ```
> function customRender(value, renderType, renderFunc, field, ...args) {
>     if (renderType === 'row') {
>         return renderFunc(value[field], ...args);
>     }
>     if (renderType === 'group') {
>         return renderFunc(value, ...args);
>     }
> }
> 
> //normal render function
> function renderCellData(status) {
>    //do stuff
> }
> 
> //using in column object
> ...
> field: 'status',
> render: (value, renderType) => customRender(value, renderType, renderCellData, 'status')
> ```

Thanks @csforbes, this was a nice hack to solve the same!, appreciate the share.

**Comment by thalysonalexr** [comment]
Hello Guys!
This solution don't work for  me!

I have a Boolean column and I want the label "Sim" to true and "Não" to false, but when doing:

```ts
render: (rowData, type) => {
        if (type === 'row') return rowData.hasPages ? 'Sim' : 'Não'
        return !rowData ? 'Não' : 'Sim'
},
```

works for row but when I group I get two values ​​true, and does not render any value for label "No". Has anyone had this same problem?

![image](https://user-images.githubusercontent.com/22718988/108366737-15a16600-71cf-11eb-8c94-9ba1a8eb7fb1.png)

**Comment by thalysonalexr** [comment]
I realized that I don't get the type of group when my past value is a false Boolean ...

![image](https://user-images.githubusercontent.com/22718988/108517804-400e2480-729e-11eb-84d1-2d720011e1b6.png)

The problem is on line 112, where it checks only if there is a value ... if the value is false, nothing passes. Could you make an adjustment to check if there is a value or if the value is boolean?

**Comment by Piterr1995** [comment]
If you use custom render, both grouping and filtering will be problematic. What I suggest is to take a step back and modify the data BEFORE passing it to Material Table as a prop. You'll eliminate the problem instead of trying to solve it (link why should do it: https://kentcdodds.com/blog/don-t-solve-problems-eliminate-them).

**Comment by anabeatrizzz** [comment]
@revskill10 can you give an example of `dragRender` function?
