### ISSUE TITLE
onRowDblClick function

### ISSUE THREAD

**Issue by CalebCox** [mbrn/material-table#467]
**Is your feature request related to a problem? Please describe.**
Having the ability to differentiate actions based on single row click and double click similar to MUI's `<TableRow />` component from within the `<MaterialTable />` component would be nice.

**Describe the solution you'd like**
A property `onRowDblClick` that takes a function that has access to the `event` and `rowData` values.

**Describe alternatives you've considered**
using timers to determine if the action is a double click in conjunction with `rowData.tableData.checked`

**Comment by kwasik-com** [comment]
Is this feature added?

**Comment by TorokEni** [comment]
Is it? Or are there any alternatives? It would be very useful. Thank you in advance

**Comment by TorokEni** [comment]
I found a workaround, inside the onRowClick function i can use the following:
 onRowClick={(evt, selectedRow) => {
                        (evt.target as HTMLElement).ondblclick = () =>{}
}
