### ISSUE TITLE
Editcomponent Rowdata parameter

### ISSUE THREAD

**Issue by Antsol74** [mbrn/material-table#471]
Hi, with regards to the effective possibility that editcomponent provides, I would like if it were possible, that when editing the line, to be able to read the values contained in the variable rowdata.
For example, if I use a select in a column as an editcomponent, if I wanted to change the value assigned, which is currently being edited, the value of the select is not displayed.
I think that if in the render columns function, in the file m-table-edit-row.js, it would be possible to read the Rowdata parameter, which contains all the values of the row, I could obtain, by reading the Rowdata parameter, the display of the current value of the select and consequently to be able to modify it regularly.
I trust your feedback and in any case, thank you for your work. 
Greetings

![editcomponent_rowdata](https://user-images.githubusercontent.com/48327120/56197402-0aaca600-6039-11e9-8ad7-1196f722c0c7.PNG)

**Comment by mbrn** [comment]
Hi @Antsol74 ,

I can add this easily. So developer would have more options.

**Comment by mbrn** [comment]
This done with 1.35.1
