### ISSUE TITLE
When using lookup the filtering returns empty results

### ISSUE THREAD

**Issue by mastercoks** [mbrn/material-table#474]
**Describe the bug**
When using the filter using lookup, it returns "No records to display"

**To Reproduce**
1. Go to https://mbrn.github.io/material-table/#/docz-examples-10-example-component-overriding
2. Select the filter with option 'Şanlıurfa' on the column 'Doğum Yeri'
4. See 'No records to display'

**Expected behavior**
Data records with value 'Şanlıurfa' in the  'Doğum Yeri' field should be seen in the table

**Screenshots**
![Print 1](https://user-images.githubusercontent.com/7410215/56236074-1c08a900-605f-11e9-8724-ed4703a9659a.png)
![Print 2](https://user-images.githubusercontent.com/7410215/56236080-1f039980-605f-11e9-94a5-75d4a8090514.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome 73.0.3683.103 64 bits

**Additional context**
Looking at the code, I checked that it takes the text from the table, and matches the value, so it returns empty.
`material-table\dist\utils\data-manager.js`
![material-table\dist\utils\data-manager.js](https://user-images.githubusercontent.com/7410215/56236660-866e1900-6060-11e9-8abc-057d579d8633.png)
![Print 4](https://user-images.githubusercontent.com/7410215/56236669-88d07300-6060-11e9-972f-642e6c66b9f6.png)

**Comment by mbrn** [comment]
Hi @mastercoks 

I will resolve this issue on next release. It will be published in a few days.

**Comment by john-pc** [comment]
@mbrn any updates 🥇  ?

**Comment by mbrn** [comment]
Hi @john-pc 

I am very busy nowadays. But i will start to resolve issues in a few days.

**Comment by john-pc** [comment]
@mbrn I will make a PR

**Comment by mbrn** [comment]
@john-pc This would be nice. Thanks.

**Comment by mbrn** [comment]
Published with 1.34.1
