### ISSUE TITLE
Link as cell data

### ISSUE THREAD

**Issue by jatinvmehta** [mbrn/material-table#478]
In our requirement, we have to display list of titles in one of the column. Each title should be a link and on hover over we need to display modal which display details about each title. How can i achieve this ?

**Comment by mbrn** [comment]
Hi @jatinvmehta ,

I think that you can use custom render feature to achive this case. Look at example. 

https://mbrn.github.io/material-table/#/docz-examples-07-example-custom-render

If it works, why you dont ask this question on Stackoverflow with `material-table` tag? This would be helpful for other developers :)

**Comment by jatinvmehta** [comment]
Will try that. Can i put any component inside that render method ? like link or button

**Comment by mbrn** [comment]
Of course. It gives you rowdata and expect a component to draw

**Comment by revskill10** [comment]
@mbrn In case of using `Link` (or custom React component), grouping doesn't work.

**Comment by mbrn** [comment]
I will find a solution to this case @revskill10

**Comment by kkomaz** [comment]
@mbrn 

Instead of avatar like the example if we hook a component inside with a onClick or onChange function?  How do we stop the propagation if we utilize a `onRowClick` on the `<MaterialTable />` component?

**Comment by kkomaz** [comment]
Example:

```
      columns: [
        {
          field: 'check',
          editable: 'never',
          cellStyle: {
            padding: 'inherit',
            width: '5%',
          },
          render: data => (
            <Checkbox
              disabled={data && data.tableData.editing === 'update'}
              checked={_.get(data, 'check', false)}
              value={_.get(data, 'check', false)}
              onChange={e => this.handleChange(e, data.tableData.id)} //deals with check mark
            />
          )
        },
```

![demo](http://g.recordit.co/iA7pcNsz1z.gif)

**Comment by kkomaz** [comment]
Nevermind figured it out via `disableClick: true` on the column!

**Comment by xStorm111** [comment]
> I will find a solution to this case @revskill10

Have you found a solution for this?
