### ISSUE TITLE
Grouping for Boolean cell doesn't work

### ISSUE THREAD

**Issue by revskill10** [mbrn/material-table#479]
**Describe the bug**
When grouping a Boolean column, header is empty

**To Reproduce**
Grouping a Boolean column

**Expected behavior**
Grouping Header should show True/False value

**Comment by mbrn** [comment]
This done with 1.35.1

**Comment by ramdaniAli** [comment]
I got the same problem  , 
I did something like this  
{ 
     field: 'boolean field', 
     title: 'title' , 
     grouping: true , 
    render : rowData => rowData.isSomthingActive ? <trueIcon /> :   <FalseICon />
}

if you can guide me it will be very nice
