### ISSUE TITLE
Header background color injection with MuiThemeProvider

### ISSUE THREAD

**Issue by udayreddy** [mbrn/material-table#483]
**Describe the bug**
MuiTableCell or MuiTableHeader theme overrides do not work for background color.
It gets overriden by MTableHeader-header

**To Reproduce**
1. Inject header backgroundColor through MuiThemeProvider

        MuiTableCell: {
            root: {
                padding: '2px 5px 2px 5px',
            },
            head: {
                fontSize: 15,
                fontWeight: 'bold',
                backgroundColor: normalTheme.colors.GREY[700],
            },
            body: {
                backgroundColor: normalTheme.colors.BLUEGREY[300],
                color: normalTheme.colors.WHITE,
                fontSize: 13,
            },
            footer: {
                backgroundColor: normalTheme.colors.GREY[700],
            },
        },

**Expected behavior**
Background color change

**Desktop (please complete the following information):**
 - OS: MAC
 - Browser chrome
 - Version latest

**Comment by mbrn** [comment]
Hi @udayreddy,

You can add a headerStyle to options of table. 

<MaterialTable options={{headerStyle:{...}}} />

**Comment by ayrtongomes** [comment]
Hi, how can I use css selectors on headerStyle options?

Something like that:
```
options={{
                headerStyle: {
                    fontWeight: "700",
                    background: "#f2f2f2",
                    "&:first-child": {
                        borderRadius: '10px 0 0 0',
                    },
                    "&:last-child": {
                        borderRadius: '0 10px 0 0',
                    },
                }
            }}
```

**Comment by r-tock** [comment]
You cannot theme it easil;y if we are overriding using headerStyle
