### ISSUE TITLE
When you select searched item, it does not return all selected items.

### ISSUE THREAD

**Issue by malix1** [mbrn/material-table#484]
**Describe the bug**
When search item and then select that item. It returns just 1 element not all selected items.

**Expected behavior**
Should return all selected items.

**Screenshots**
![img1](https://user-images.githubusercontent.com/18161682/56412572-5c4d6e80-628d-11e9-8e58-f571558ee922.PNG)
![img2](https://user-images.githubusercontent.com/18161682/56412571-5c4d6e80-628d-11e9-8d35-f566c820d153.PNG)

**Additional context**

**Comment by mbrn** [comment]
Hi @malix1 

I tested this case with last version and could not find any problem. I will close this issue. If you still have problem please reopen this issue.
