### ISSUE TITLE
Change Order of columns

### ISSUE THREAD

**Issue by WejusT1k** [mbrn/material-table#485]
Hey, i have some question:)

Can I change order of columns by drag'n'drop or change width of columns using mouse?)

Maybe i can hang the event handler on the column?

**Comment by pak11273** [comment]
These features are not available yet.

**Comment by mbrn** [comment]
Hi @WejusT1k 

I am working on a new documentation of material-table. After documentation completed i will start to features like this.

**Comment by WejusT1k** [comment]
> Hi @WejusT1k
> 
> I am working on a new documentation of material-table. After documentation completed i will start to features like this.

Hi:)

Thanks a lot

**Comment by JKrymarys** [comment]
Hi, 
I see that can drag&drop columns to change their order, It seems to not be working completely well, tho. 
So what's the status of this feature? :)

**Comment by mbrn** [comment]
Hi @JKrymarys ,

Which version of MT do you use? 

Try examples:
https://material-table.com/#/docs/features/grouping

**Comment by JKrymarys** [comment]
Hi!
Thanks for the fast reply :) 
I am using newest version that is released.

I've tried the examples and the issue still exists, thus I described it in an [issue](https://github.com/mbrn/material-table/issues/578)
