### ISSUE TITLE
Add Chips in the header which the data was filtered

### ISSUE THREAD

**Issue by orestes22** [mbrn/material-table#486]
I would like to recommend to add the feature of add in the header a Chips component which the data that was filtered, because in that way the user will keep track all filtered he made. 

And also it can delete the chip if he doesnt doesnt want more that filtered

Best Regards

**Comment by WejusT1k** [comment]
You can override Toolbar Component:)

**Comment by orestes22** [comment]
Yes, I know, and i already using it in that way

but my advice is because @mbrn is updating the table in that area to affer custom filtering so I could be nice it appear by default and more easy to handler.
