### ISSUE TITLE
Fix errors in console

### ISSUE THREAD

**Issue by KKrisu** [mbrn/material-table#49]
Hi there.

I've just installed the `material-table` which looks very promising, however it throws multiple errors in console. The same issue happens on your demo page

![image](https://user-images.githubusercontent.com/577112/46656369-317fb080-cbae-11e8-9c01-1889b73c7d57.png)

**Comment by mbrn** [comment]
Hi @KKrisu, 

All of them are warning but i will resolve them as soon as possible. Thanks for giving information.

**Comment by mbrn** [comment]
@KKrisu. Problems resolved. You can upgrade to version 0.8.2

**Comment by KKrisu** [comment]
Thank you @mbrn
