### ISSUE TITLE
Remote paging default sort not working

### ISSUE THREAD

**Issue by jakeleventhal** [mbrn/material-table#490]
**Describe the bug**
For remote data, the orderBy prop of the query is null if a field is set as the default sort.

**To Reproduce**
1. Make a column with default sort
2. Use remote data and console log `query.orderBy` - it is set to null instead of the defaulted column.

**Comment by jakeleventhal** [comment]
I don't see this change reflected in the latest version (1.34.0). Is this in an unreleased version?

**Comment by mbrn** [comment]
yes. it is not released yet.

**Comment by mbrn** [comment]
Published with 1.34.1
