### ISSUE TITLE
Need the ability to use radio buttons on filters

### ISSUE THREAD

**Issue by jakeleventhal** [mbrn/material-table#492]
**Is your feature request related to a problem? Please describe.**
When filtering from lookup, there should be an option to filter using radio buttons instead of checkboxes. This way you can limit the user to only selecting one option

**Describe the solution you'd like**
An option to add radio buttons to the filter

**Comment by jakeleventhal** [comment]
not stale

**Comment by mahesh-kedari** [comment]
Is there any plan for adding this feature? Or is there any workaround for this functionality?

**Comment by jakeleventhal** [comment]
not stale

**Comment by jakeleventhal** [comment]
not stale

**Comment by jakeleventhal** [comment]
not stale
