### ISSUE TITLE
Need ability to use different operators on numeric filters

### ISSUE THREAD

**Issue by jakeleventhal** [mbrn/material-table#493]
**Is your feature request related to a problem? Please describe.**
There should be a way to select operators on number filters (>, >=, <, <=, etc.)

**Comment by mbrn** [comment]
This is in my plans

**Comment by jayarjo** [comment]
+1

**Comment by jayarjo** [comment]
Can you tell us how does one trigger filtering manually with custom params?

**Comment by jakeleventhal** [comment]
This is not stale!

**Comment by jakeleventhal** [comment]
not stale

**Comment by willvictor** [comment]
+1

**Comment by jakeleventhal** [comment]
not stale

**Comment by jakeleventhal** [comment]
not stale
