### ISSUE TITLE
No way to refetch data on remote data when props change

### ISSUE THREAD

**Issue by jakeleventhal** [mbrn/material-table#495]
**Describe the bug**
I have a table that uses a function to fetch remote data. The function uses a prop that can change. However, when the prop changes, data query function does not get called again so the data never gets updated - and there is no way to force the call to get called again.

**To Reproduce**
1. Create a table with remote data that calls a function to fetch the data
2. Use a prop in the function
3. Update the prop - then notice how the function doesn't get called again despite the class containing the table rerendering

**Comment by mbrn** [comment]
You may fire the onQueryChange of table manually. Look at tableRef

**Comment by jakeleventhal** [comment]
This works, but it resets all the filter values. Also, when applying a filter, it doesnt go back to page 1

**Comment by mbrn** [comment]
Same case:

https://github.com/mbrn/material-table/issues/491#issuecomment-489216996
