### ISSUE TITLE
TypeError: Generic type 'ReactElement<P>' requires 1 type argument(s).

### ISSUE THREAD

**Issue by angelelizalde21** [mbrn/material-table#499]
**Describe the bug**
On v1.32.0 

../node_modules/material-table/index.d.ts
(18,20): Generic type 'ReactElement<P>' requires 1 type argument(s).

**Comment by angelelizalde21** [comment]
I still have this problem in v1.34.0 a have to install v1.29.0 for now to use the table.

I would appreciate a solution to this problem, it really helps me in my project

**Comment by mbrn** [comment]
Hi @angelelizalde21 ,

I will take a look at it asap. 

As a workaround you can add `skipLibCheck: true` to your tsconfig file

**Comment by mbrn** [comment]
Published with 1.34.1
