### ISSUE TITLE
render fires even no changes on data source

### ISSUE THREAD

**Issue by devel0** [mbrn/material-table#500]
**Describe the bug**
Changing a textfield outside the material table cause column render fire.

**To Reproduce**
https://codesandbox.io/s/github/devel0/repros/tree/2f37d7e3d240d36791ae24572e441c08f1ac35c7/material-table/test01

**Expected behavior**
rerender should limited to data source

**Screenshots**
![Peek 2019-04-22 18-08](https://user-images.githubusercontent.com/13405008/56510284-9d61af00-6529-11e9-9a66-cdf2d85c5a82.gif)

render count incremented by the render of the column not from the text input itself ( [code](https://github.com/devel0/repros/blob/2f37d7e3d240d36791ae24572e441c08f1ac35c7/material-table/test01/src/App.tsx#L64-L67) )

**Comment by mbrn** [comment]
Hi @devel0 

Actually i didn't worked on performance of material-table. But i know it has some performance issues. I will examine them asap. 

Thanks

**Comment by devel0** [comment]
Hi @mbrn,
I wondering if render shouldn't be controlled through a table prop ( a number ) that user can connect to a state variable, so that table render proceed only on internal events ( page changed, etc ) or when this prop "age" changes respect to previous received values.
For example I can increment that number in my app when I know datasource changed and this way material table know that data source changed and allow render or not; maybe the way is to use that in `ShouldComponentUpdate`.
I don't know if there are other ways which the table can observe a generic dataset in an efficient way.

**Comment by mbrn** [comment]
Thanks for recommendation. I will consider this way when working on performance.

**Comment by masbaehr** [comment]
The problem becomes very serious especially if you have a "render" method in your columns which is doing some longer-lasting work. Then it can happen that the UI blocks completely.
