### ISSUE TITLE
How can I select a grouped rows

### ISSUE THREAD

**Issue by behrouz-s** [mbrn/material-table#503]
How can I select a group of rows with a single checkbox?

**Comment by mbrn** [comment]
Hi @behrouz-s ,

Do you use tree data feature?

**Comment by behrouz-s** [comment]
No, I use dragable row grouping

**Comment by mbrn** [comment]
Currently nested selection is active only for tree data. But it makes sense to same behaviour with grouping. I will add this feature asap. But firstly i will work on performance issues and bugs

**Comment by mbrn** [comment]
I checked this request. It will take my time. But i will do it.

**Comment by azaidi4** [comment]
Hi @mbrn. Has this feature been implemented?

**Comment by mbrn** [comment]
> Hi @mbrn. Has this feature been implemented?

Not yet. But i will

**Comment by sergeyromanovdev** [comment]
Hi @mbrn. Have you had a chance to implement this feature?

**Comment by carlosgonzalezucv** [comment]
Hello @mbrn. Would you implement this feature soon?

**Comment by gabolucuy** [comment]
Hello, any updates on this feature?

**Comment by jonesty** [comment]
@mbrn Any idea when this one might get done, mate? We are very interested in this functionality also.

**Comment by jonesty** [comment]
@mbrn Any update on this?

**Comment by haroldwaste** [comment]
lovable feature, very much waiting for it. Thx @mbrn

**Comment by foxwu** [comment]
@mbrn any update? still waiting for this feature to be merged. Thanks.

**Comment by AravindTReddy** [comment]
This is going to be an incredible feature addition. My wait starts now :) 
Thanks
