### ISSUE TITLE
Table is too slow with 800 rows

### ISSUE THREAD

**Issue by behrouz-s** [mbrn/material-table#504]
**Describe the bug**
I load table with 800 rows, and each of them has 2 or 3 nested data, but it is to slow, specially after grouping the rows.
every row has 220 columns and every nested data has 20 columns

**Desktop:**
 - OS: [Ubuntu 18.04]
 - Browser [chromium]
 - Version [Version 73.0.3683.103]

**Comment by mbrn** [comment]
Hi @behrouz-s 

I didn't work on performance issues. Nowadays i am working on documentation(material-table). Then i will return back to issues. And my first focus will be performance problems.

**Comment by mbrn** [comment]
Hi @behrouz-s ,

I improved grouping code. In my tests it is now 10 times faster when grouping data. I test with 100K row and group the worst case(each row different value) and it takes about 500ms-1000ms

**Comment by mbrn** [comment]
This is done with 1.35.2
