### ISSUE TITLE
Make Edit Button disabled or removed based on condition for rows

### ISSUE THREAD

**Issue by LTank** [mbrn/material-table#506]
Right now there seems to be no way to disable the edit button on each row based on conditions.

For example like in this picture where the button is grayed out based on a condition. 
![image](https://user-images.githubusercontent.com/24596368/56663172-b8f1c480-66a5-11e9-8f32-3bd842af3397.png)

**Comment by mbrn** [comment]
Hi @LTank ,

I added isEditable and isDeletable fields. I will publish it tomorrow. You can look at usage on documentation.

**Comment by mbrn** [comment]
1.35.0 published

**Comment by mbrn** [comment]
https://material-table.com/#/docs/features/editable

**Comment by ajayraveendran** [comment]
Hey @mbrn 

Really enjoying using mat-table. I was wondering if there is a way to conditionally disable the check button based on values entered during adding/updating a row?

For e.g. User clicks on edit, they enter value A in Column1, check button stays clickable, if they enter value B or leave column1 blank, the check button is unclickable.

Thanks!

**Comment by n-so** [comment]
Hi @mbrn 
 I tried using  isEditable: rowData => rowData.name === "Sarah"  but edit icon is not disabling 
what can be causing this?
Thx.

**Comment by chipmunk25** [comment]
isEditable has an option to show either delete only or edit only based on the user permissions?

**Comment by chipmunk25** [comment]
> Hi @mbrn
> I tried using isEditable: rowData => rowData.name === "Sarah" but edit icon is not disabling
> what can be causing this?
> And is there any way to disable actions buttons on (react) state condition
> Thx.

it u can case your rowData.name and "Sarah" to make sure the compare works well

**Comment by Jvictor97** [comment]
Is there a way to actually **remove** the edit button? I only want the inline delete feature on my MaterialTable, and would like to use a custom action for editing.

**Comment by chipmunk25** [comment]
> Is there a way to actually **remove** the edit button? I only want the inline delete feature on my MaterialTable, and would like to use a custom action for editing.

u can do two things , either u use an action then u do your own remove or edit button or use edittable who u use only one

**Comment by chipmunk25** [comment]
u can also customize an edittable button

**Comment by muhadel** [comment]
@mbrn 
 isEditable and isDeletable  are not working!! , can you help?

**Comment by twgardner2** [comment]
Having the same issue. Even `isDeletable: (rowData) => false` doesn't disable the delete button

**Comment by chipmunk25** [comment]
> Having the same issue. Even `isDeletable: (rowData) => false` doesn't disable the delete button

it looks like material-table is having a problem mine has stop working

**Comment by gabriellupu** [comment]
> Having the same issue. Even `isDeletable: (rowData) => false` doesn't disable the delete button

same here

**Comment by zhex900** [comment]
This is broken after `1.54.0`

**Comment by Androsv96** [comment]
isEditable and isDeletable not working even with:
isEditable: rowData => false,
isDeletable : rowData => false

**Comment by pain2theworld** [comment]
Not working.

**Comment by Androsv96** [comment]
See #1400

**Comment by dashName** [comment]
currently isEditable false disable the icon but is there a way to actually remove / hide the icon?

**Comment by ksavic** [comment]
Is there a way to disable add button?

**Comment by muhadel** [comment]
@ksavic 
You can remove onRowAdd from the editable props object.

**Comment by r-rusev** [comment]
How can I disable 'Delete' button from edit row? I don't want it to be hidden but only disabled. How could I achieve this?
