### ISSUE TITLE
Remove box-shadow around table

### ISSUE THREAD

**Issue by fgenoese** [mbrn/material-table#508]
Hi,

I am trying to figure out how to remove the box-shadow around tables. The styling exercises show how to edit columns, rows and cells but the shadow seems to be outside the table.

Any hint?

**Comment by mbrn** [comment]
Hi @fgenoese 

You can try overriding container:

```javascript
import { Paper } from '@material-ui/core';

<MaterialTable
component={{
     Container: props => <Paper {...props} elevation={0}/>
}}
/>
```

**Comment by fgenoese** [comment]
Unfortunately, the code has no effect, i.e. the resulting HTML still says:
`<div class="MuiPaper-root-8 MuiPaper-elevation2-12 MuiPaper-rounded-9">...</div>`

**Comment by mbrn** [comment]
sorry. Make component => components. 

import { Paper } from '@material-ui/core';

```javascript
<MaterialTable
component={{
     Container: props => <Paper {...props} elevation={0}/>
}}
/>
```

**Comment by fgenoese** [comment]
Works like a charm - and I learned something new about Material UI styling I guess.
Thanks!

**Comment by dashName** [comment]
> sorry. Make component => components.
> 
> import { Paper } from '@material-ui/core';
> 
> ```js
> <MaterialTable
> components={{
>      Container: props => <Paper {...props} elevation={0}/>
> }}
> />
> ```

is there a way to remove the border-shadow (divider that appears after fixed column) while using fixedColumns property?

**Comment by ejrekruit** [comment]
> Unfortunately, the code has no effect, i.e. the resulting HTML still says:
> `<div class="MuiPaper-root-8 MuiPaper-elevation2-12 MuiPaper-rounded-9">...</div>`

I'm having the same

**Comment by shamoons** [comment]
I get `Property 'component' does not exist on type 'IntrinsicAttributes & `

**Comment by PauloJFCabral** [comment]
Hello, I still not remove elevation for paper! Any solution?

**Comment by KamauAlex** [comment]
> I get `Property 'component' does not exist on type 'IntrinsicAttributes & `



> sorry. Make component => components.
> 
> import { Paper } from '@material-ui/core';
> 
> ```js
> <MaterialTable
> components={{
>      Container: props => <Paper {...props} elevation={0}/>
> }}
> />
> ```
