### ISSUE TITLE
Table flashes on render

### ISSUE THREAD

**Issue by blackbadgerltd** [mbrn/material-table#509]
**Describe the bug**

When using a Mui theme which is dark, a rerender of the table due to navigation or data change results in selected areas of the table flashing white, then returning to dark.

**To Reproduce**
Steps to reproduce the behaviour
1. Create a table with a dark theme
2. Update data from a remote source

**Expected behavior**
Table should render without flickering 

**Desktop (please complete the following information):**
 - OS: OS X 10.14
 - Browser chrome
 - Version 56

Flickering Is most prevalent on the toolbar and 2nd row onwards. May be due to loading spinner?

**Comment by mbrn** [comment]
This done with 1.35.1
