### ISSUE TITLE
Pagination not working on Internet Explorer 11

### ISSUE THREAD

**Issue by Mihier-Roy** [mbrn/material-table#510]
**Bug Description**
The pagination options do not render on Internet Explorer 11, thus preventing the use of the pagination functionality. It instead shows the following:
![image](https://user-images.githubusercontent.com/31336766/56716935-24e13500-6759-11e9-8d8d-04e3a6d5b5f8.png)

**To Reproduce**
1. Open a page with material-table on IE11
2. Check the Pagination options to see if they are present
3. See error

**Expected behavior**
The same page renders perfectly on Google Chrome with no issues, indicating that the Icons are being imported properly.
**Edit:** Just tested on **Microsoft Edge 41.16299.1004.0** and **Firefox 66** and it works with no issues.
![image](https://user-images.githubusercontent.com/31336766/56716900-0e3ade00-6759-11e9-8de6-a5d3a4292cf7.png)

**Desktop:**
 - OS: Windows 10 1709
 - Browser: Internet Explorer
 - Version: 11

**Additional context**
Not sure what is causing this behavior, it could be pollyfill/feature compatibility related since the same page is rendered with no issues on newer browsers.

**Comment by mbrn** [comment]
This done with 1.35.1

**Comment by Mihier-Roy** [comment]
Thanks a bunch! Figured it would be something with the Pollyfill!

Cheers! 🍺

**Comment by Mihier-Roy** [comment]
Looks like it's working now!
Figured it would be something wrong with the polyfill.
Also, I believe babel-pollyfill is in the process of being deprecated in favor of importing stuff directly from core-js 3. Nothing too urgent but you might have to change it sometime in the future!
Here is a full explanation of why and how to replace it : [Babel-pollyfill deprecation](https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md#babel) 

Thanks a ton for the help! 
Cheers 🍻

**Comment by mbrn** [comment]
Uwc.

Of course. I will do it asap.
