### ISSUE TITLE
Add row render function

### ISSUE THREAD

**Issue by geohuz** [mbrn/material-table#511]
I'm wondering if I can highlight a row based on specific condition? I couldn't find the feature.
Have a row rendering function I can conditionally change the row styles.

**Comment by mbrn** [comment]
Hi @geohuz ,

Look at 3rd example at: https://material-table.com/#/docs/features/styling

It uses conditional rowStyle feature. You can apply your own condition.

**Comment by geohuz** [comment]
I have read the doc, in this code:
```
        options={{
          rowStyle: {
            backgroundColor: '#EEE',
          }
        }}
```

I can't figure out how to add a condition like ```if (field.value===true) { backgroundColor: '#eee'}```?

**Comment by geohuz** [comment]
ah! I see!
