### ISSUE TITLE
onSelectionChange does not return selected rows when used with search

### ISSUE THREAD

**Issue by themausam** [mbrn/material-table#514]
**Description**
I have a requirement to show a separate list of records that are currently ticked before being finalised. **onSelectionChanged** works well and returns ticked rows when simply using pagination but does not work as expected when using it along with search.

**To Reproduce**
1. Assume records **A1, A2, A3, A4, A5** on Page 1 and **A6, A7, A8, A9, A10** on Page 2.
2. Search **A1** and tick it _(type complete word, do not use partial word search)._ **onSelectionChanged** correctly returns one item.
3. Now search **A3** and tick it. Table correctly says 2 rows selected but **onSelectionChanged** is still returning one item.
4. Try again with items on another page and search for **a8** and tick it. **onSelectionChanged** still returns one item.

**Expected behavior**
**onSelectionChanged** to return all ticked items just like it does with pagination.

**Comment by mbrn** [comment]
This is done with 1.35.2
