### ISSUE TITLE
Add API for selecting/deselecting rows programmatically

### ISSUE THREAD

**Issue by olehmelnyk** [mbrn/material-table#515]
I have a list of options with checkboxes and action buttons separated from the list/table.
When one or options checked - buttons become enabled.
Once button pressed - I send a request to the server with selected ids and want to deselect checkboxes, which will make buttons disabled again.

Also, it would be nice to have the ability to load the table with initially selected options.

**Comment by pwork2015** [comment]
need this to. It's so easy to release. Please...

**Comment by orestes22** [comment]
Hi, there is way to do that. In the response of the API you have to set to true the variable "checked ".
This variable is inside of dataTable.
Example:
response.DataTable.checked=true

**Comment by pwork2015** [comment]
What is "response of the API"? Can you provide more deep example?

**Comment by orestes22** [comment]
Sorry, i thought you are asking for remote connection.

In your case try to do this in onClick event of your button: data.tableData.checked=true

**Comment by orestes22** [comment]
If it is an array your data:
data[numberRow].checked=true

**Comment by bretep** [comment]
What if you don't know the row number in the array, just the key that is checked?

For my use case, the user searches for something, gets a table of results back, they select a few items, then may modify their search to select more items. 

I store the selected items in a separate variable, using an "onClick" function.

If the user searches again for a previous query, the table loads, but values he has already checked are not checked.

Ideally there would be a way to say "These keys are checked" when loading a table.

Interestingly, the [antd](https://ant.design/components/table/) tables take care of all of that for the user. That might be a good reference point. I recently moved from antd to material-ui and wanted a good replacement.

material-tables seems like it's the one I'm going to stick with.

**Comment by orestes22** [comment]
Hi @bretep , you at least need have an "Id" of that information, or something that you can difference some information from another, using that element you can cheked the row that you want. 

If you use the material-table not in remote mode it keep that reference but if you used it in remote mode you must keep that reference in your state and tell to the table when you need it mark something or change color, because in the remote mode the only data that the table know is the table is showed in that moment. So you must compare using something unique and see if the data showed in that table appear in your saved state. 

Best Regards

**Comment by diegosps** [comment]
Thanks @orestes22 for the `data[numberRow].tableData.checked=true`
However, I also needed:
- data[numberRow].tableData.**disabled**=true
This would disable the entire row, including the checkbox
- option to disable the selection count message
It looks really ugly in my theme (bright orange in a dark theme) and draw too much attention.


In the mean time, It's possible to implement your own check column:

- You can pass a component to column's title: `title?: string | React.ReactElement<any>` (nice)
Material-ui checkbox, for example
- Override the component toolbar, if you want to get rid of the selection count message;
- Define the render method of the column with another checkbox and control state.

**Comment by orestes22** [comment]
@diegosps  About point 1, it could be a feature and you can open a ticket for that. 
The point 2, i already make PR to do that. Just waiting for @mbrn accept the request. https://github.com/mbrn/material-table/pull/596

The point 3 and 5, the answer is yes, You can implement your own checkbox, using the render method in the column, check this example https://material-table.com/#/docs/features/custom-column-rendering

The point 4, please check the example 2 https://material-table.com/#/docs/features/component-overriding

Best Regards

**Comment by mbrn** [comment]
Now you can call tableRef.onAllSelected(true)

**Comment by ahmedbrandver** [comment]
in which version is this available?

**Comment by fidelcoria-aa** [comment]
@ahmedbrandver  We are on "material-table": "1.68.0" and it works.
@mbrn it's actually tableRef.current.onAllSelected(true)
also your comment would be more helpful if you provided adequate context

i.e. https://github.com/mbrn/material-table/blob/6b2e168f8bb768b1582998377ed6363abcb0ad71/demo/demo.js

**Comment by jigarlodaya12** [comment]
How can I unselect a selected row pragmatically?
version: material-table@1.54.1
NextJs.

**Comment by s4m0r4m4** [comment]
I found this issue while searching around, I appreciate the info! Just a suggestion for the maintainers, it could be useful to provide this info (the way you can programmatically set the checked status) on this page somewhere: https://material-table.com/#/docs/features/selection. To my knowledge, I was not able to find the info anywhere in the docs.
