### ISSUE TITLE
Table flashes and delete words when searching in remote data table

### ISSUE THREAD

**Issue by terapepo** [mbrn/material-table#516]
**Describe the bug**
After implementing the remote data table as the example provided, if the user types on the search input, the table flashes for every word typed and sometimes if you type really fast, it will delete some of the words you typed, I would recommend to implement a debounce or throttling for the search input. Also and I know it's a already reported bug, but the filters state also reset #491 .

**Comment by XHMM** [comment]
[The demo](https://material-table.com/#/docs/features/remote-data) on doc site is a living bug example： when input something, table always fetching remote.  Waiting for fix. 🧐

**Comment by mbrn** [comment]
Hi @terapepo 

This is not a bug. You used columns directly. I advise you to use them in parent components' state. So tableData of columns will not be disappear when you setState in data function.

**Comment by mbrn** [comment]
Actually it has a debounce. It is default 200ms. You can change it with options.debounceInterval

**Comment by GuilhermeDaniluski** [comment]
> Hi @terapepo
> 
> This is not a bug. You used columns directly. I advise you to use them in parent components' state. So tableData of columns will not be disappear when you setState in data function.

Hi @mbrn 

How can i achieve it? Do i have to declare columns in the parent component?

```JSX
<MaterialTable
        style={{ width:'100%'}}
        title={<Typography style={{ fontSize:'calc(10px + .5vw)' }}>Title</Typography>}
        columns={[
          { title: 'Id', field: 'id' },
          { title: 'Nome', field: 'name' },
          { title: 'E-mail', field: 'email' },
          { title: 'Role', field: 'roles[0]', sorting: false },
        ]}
        options={{ 
            search: true,
            debounceInterval:1000
          }}
        data={query => tableService.searchUsers(query)
        
        }/>
```

Thank You.

**Comment by logust79** [comment]
For me it was nothing to do with debounce. It was because I had an `await` in `useEffect` hook. After I introduce `useCallback` for the awaited function, the problem disappeared.
So if you have a `useEffect` hook as follows:
```javascript
useEffect(() => {
  const inner = async () => {
    const state = await getState()
    setState(state)
  };
  inner()
}, [getState, ...])
```
You can change your `getState` to
```javascript
const getState = useCallback( async(): Promise<State> => {...}, [props.foo, props.baa])
```

**Comment by ambr89** [comment]
Hi @mbrn ,
do you have resolve?

When I try to update data, the values of filter disappears.

Thanks in advance.

**Comment by jaggaer-npasic** [comment]
debounceInterval:1000
It's not working.
