### ISSUE TITLE
How to get selected columns in columnsButton?

### ISSUE THREAD

**Issue by behrouz-s** [mbrn/material-table#517]
I am going to send selected column to server to save client's table customization.
how can I get list of selected columns in columnsButton?

**Comment by mbrn** [comment]
Do you mean selected 'ROWS'?

**Comment by behrouz-s** [comment]
> Do you mean selected 'ROWS'?

No, I'm going to get a list of selected columns (checked columns) in columnsButton.

**Comment by mbrn** [comment]
You can filter your columns data. MT adds a tableData field to your columns. 

1. Use columns from your state. 
2. Then this.state.columns.filter(a => a.tableData.hidden === true) gives you selected columns.

**Comment by mbrn** [comment]
I guess it works.
