### ISSUE TITLE
No way to edit the edit value

### ISSUE THREAD

**Issue by jakeleventhal** [mbrn/material-table#521]
**Is your feature request related to a problem? Please describe.**
There is no way to edit the value that appears for default editing.
For instance, if the column uses field X but the column has a render function that displays product of fields X and Y, when I click edit it currently just shows the value for X.

**Describe the solution you'd like**
I want to be able to show either no value in the edit field or to have some custom function to display a custom value when I click edit.

**Comment by mbrn** [comment]
I think this is the correct way. Actual value should be shown in edit component. You can use custom edit component if you want to change it.

**Comment by jakeleventhal** [comment]
I am unable to use both remote data paging and custom components
https://codesandbox.io/embed/n9572w936j

**Comment by mbrn** [comment]
> I am unable to use both remote data paging and custom components
> https://codesandbox.io/embed/n9572w936j

Can you open this as another issue, please?
