### ISSUE TITLE
Setting Column Width when column has filter

### ISSUE THREAD

**Issue by finbar123** [mbrn/material-table#522]
Hi great solution very easy to use.

Is there a way to style the filter cell, the situation we have is a column that we want to set as a small width.

We can set the Heading and Cell styles to say "10px", but if the column has a filter enabled the column width will be set to the default for the filter.

Thanks

Finbar

**Comment by mbrn** [comment]
Hi @finbar123 ,

I can add filterCellStyle feature asap.

**Comment by finbar123** [comment]
Mehmet

 

That would be an excellent solution

 

Second suggestion J as well as an Icon Disable option a Hidden option would be good so we can toggle a line of actions and not have any spaces, we tried using  iconProps:this.state.showDeleted ? ({style:{visibility:"hidden", width:”0px”}}):{}, but if leaves a space in the toolbar !

 

Thanks

 

Finbar

**Comment by mbrn** [comment]
I will consider it.

**Comment by mbrn** [comment]
1.35.0 published

**Comment by finbar123** [comment]
Mehmet

 

Hi thanks for adding the feature, but I am having trouble getting it to work, I have defined as below cell and header both get applied but filter is ignored, have I misunderstood how it should work ?   I upgraded to 1.36.1

 

columns={[ 

              {title: 'Id', field: 'id' ,type:"numeric",searchable:true,filtering:true,sorting:true,

                cellStyle:{maxWidth:100,padding:"5px", margin:"5px", color:"green"},

                headerStyle: {color:"red",

                    maxWidth:"100",padding:"5px", margin:"5px"

                  },

                  

                  filterCellStyle:{maxWidth:100,padding:"5px", margin:"5px", color:"blue"}

               }

 

…]}

 

Regards

 

Finbar

**Comment by finbar123** [comment]
Mehmet

Hi did you make any further progress on this suggestion

Kind Regards

Finbar

**Comment by mbrn** [comment]
I didn't work on this yet. Thanks for your patience.

**Comment by finbar123** [comment]
No problem J

**Comment by IdkMan2** [comment]
I am also intrested in using this feature.

**Comment by ParVKS** [comment]
any update on this @mbrn

**Comment by SheaOHagan** [comment]
Hi Mehmet, I am also interested in using this feature. I tried `filterCellStyle: { width: 'auto' }` but it doesn't seem to apply. Thank you
