### ISSUE TITLE
Adding textfield in toolbar only allows single char typing

### ISSUE THREAD

**Issue by blackbadgerltd** [mbrn/material-table#523]
**Describe the bug**

When adding a textfield to the toolbar component, typing into it allows allows 1 character before it renders the whole component and focus is lost.

**To Reproduce**
1. Add a textfield to the toolbar component
Link it’s value to this.state and attach a change handler
Run
Type into the text field

**Expected behavior**
Text should be input as typed, beyond 1 char, and maintain focus

**Desktop (please complete the following information):**
 - os 10.14.3
 Chrome 58

**Comment by mbrn** [comment]
Actually this is not about material-table. If you use functional component to override toolbar it will rerender your textfield on every change. So it will be another textfield and loses focus. 

But you can use it in a component like this. 

```javascript
 <MaterialTable
                  ref={this.tableRef}
                  columns={this.state.columns}
                  data={this.state.data}
                  title="Demo Title"
                  options={{
                  }}
                  components={{
                    Toolbar: NewBar
                  }}
                />

```

```javascript
class NewBar extends React.Component {
  state = {
    text: 'Abc'
  }

  render() {
    return (
      <div>
        <MTableToolbar {...this.props} />
        <TextField value={this.state.text}
          onChange={event => {
            this.setState({ text: event.target.value });
          }}
        />
      </div>
    )
  }
}
```

**Comment by Hatko** [comment]
@mbrn any ideas on how I can pass some props from `MaterialTable` parent component to `NewBar` from your example?

**Comment by osky9913** [comment]
@Hatko  did you find any solution ?

**Comment by nmkname** [comment]
@osky9913, just use function expression or wrapper component
`Toolbar: (props) => <NewBar {...props} yourProp={yourProp} />`

**Comment by nmkname** [comment]
@osky9913, just use function expression or wrapper component
`Toolbar: (props) => <Newbar {...props} yourProp={yourProp}  />`

**Comment by llezhava** [comment]
@mbrn 
Why is this issue closed? 

`Toolbar: (props) => <Newbar {...props} yourProp={yourProp} />` does not work. Material-table unmounts and mounts the component

**Comment by vatsaMishipay** [comment]
Facing the same issue , Any updates on this ?

**Comment by muhammada86** [comment]
Did someone found any solution to this error, this is still an irritating error,
If anyone have any patch or solution, Please share it!!!

**Comment by ruan-lucas** [comment]
Facing the same issue...

**Comment by SebastianMaciel** [comment]
I have componentized a custom textfield for this, and then memo(MyComponent). And that was so.
