### ISSUE TITLE
Shouldn't be able to hover over the actions column header

### ISSUE THREAD

**Issue by jakeleventhal** [mbrn/material-table#524]
**Describe the bug**
When hovering over the actions column header of a table, the text gets bold, like the other columns (indicating that it could be sortable).

**To Reproduce**
1. Create a table with actions
2. Hover over the column header that says "Actions"

**Expected behavior**
Nothing should happen

**Screenshots**
<img width="103" alt="Screen Shot 2019-04-28 at 3 05 02 PM" src="https://user-images.githubusercontent.com/15133828/56870634-0aac8e80-69c7-11e9-96ed-7bfb7a1505a3.png">
<img width="107" alt="Screen Shot 2019-04-28 at 3 05 05 PM" src="https://user-images.githubusercontent.com/15133828/56870635-0aac8e80-69c7-11e9-8f19-17c6fc8e0550.png">

**Comment by mbrn** [comment]
1.35.0 published
