### ISSUE TITLE
How to add Select/ Dropdown in action 

### ISSUE THREAD

**Issue by mehuljariwala** [mbrn/material-table#526]
How can i add Dropdown in action button and after click on selection how to get data of whole row.

**Comment by mbrn** [comment]
Hi @mehuljariwala ,

Did you check custom rendering feature. You can render anything inside a cell?

https://material-table.com/#/docs/features/custom-column-rendering

**Comment by mehuljariwala** [comment]
Yeah i check but i like to have dropdown and checkbox both together!

@mbrn

**Comment by mbrn** [comment]
You can return many elements in a fragment or div.

render: rowData => <div><DropDown/><Checkbox/></div>

**Comment by mehuljariwala** [comment]
not working i tried to many thing

**Comment by mbrn** [comment]
![image](https://user-images.githubusercontent.com/7895451/57057966-79366880-6cb5-11e9-80f0-98fc53dc4513.png)

render: rowData => (
            <>
                <select>
                  <option>Select a value</option>
                </select>
                <input type="checkbox"/>
            </>

          )

**Comment by mehuljariwala** [comment]
Okay Let me check to implement on my project!

Thanks Buddy!
