### ISSUE TITLE
Remote data - orderBy null even if column defaultSort was set

### ISSUE THREAD

**Issue by wojtonow** [mbrn/material-table#527]
**Describe the bug**
When use remote data, query.orderBy has null value even if column has set defaultSort. 

**To Reproduce**
https://codesandbox.io/embed/4wy3loo469

**Expected behavior**
When fetching data with the API, it is a good solution to set the order in the backend, especially when only portions of data are returned.

**Comment by mbrn** [comment]
Hi @wojtonow 

I fixed this bug. It will be in next release. Thanks for feedback.

**Comment by mbrn** [comment]
Published with 1.34.1

**Comment by wojtonow** [comment]
Thanks for the improvement but the change does not work as you would expect. In the first query, as orderBy, we get a column index, and after a manual sort change we get an object with a column definition. The data returned as orderBy should be the same in each case

I updated the example on codesandbox
https://codesandbox.io/embed/4wy3loo469

**Comment by mbrn** [comment]
I published 1.34.2. Try it please

**Comment by wojtonow** [comment]
Now work's perfectly
