### ISSUE TITLE
How can I change the color of the table header color on over and sorting?

### ISSUE THREAD

**Issue by geohuz** [mbrn/material-table#529]
Currently the header color changed to black when hover or click and sorting, when I changed the table background color to blue it looks not highlighted, what if I want to change the font color to "white"? I can't find a solution for this requirement.

**Comment by mbrn** [comment]
Can you add headerStyle: {color :'white'} to options?

**Comment by geohuz** [comment]
@mbrn , yes I have added the headerStyle: {color: "white"}, but the problem is, the color changes to dark with mouse hovering (showing filter arrow and title text with dark color), that's bad when I use a dark background color for the header, the header text is hardly seen under this scenario, I'm wondering how can I make adjustment for this hovering color changing behavior.

**Comment by georgian4049** [comment]
Please help in this regard
