### ISSUE TITLE
date filter: picker language customizable

### ISSUE THREAD

**Issue by DreadCube** [mbrn/material-table#531]
**Is your feature request related to a problem? Please describe.**
Actually, if i filter a row of the type date, the datepicker is always in english. For my webapp and german clients isn't that cool.

**Describe the solution you'd like**
I need to define in some way the date picker language. Maybe this way:
`options={
   {
       datePickerLocale: require('@date-io/date-fns/locale/de')
   }
}`

**Describe alternatives you've considered**
As an alternative,  i see that material-table could handle it byself. Read `navigator.language` and then load the associated locale file from date-fns.

**Additional context**

**Comment by PetrovOlexander** [comment]
Any updates on this matter?
The only missing localization is the datepicker.

**Comment by mbrn** [comment]
unfortunately. I will take a look at it asap.

**Comment by tobilarscheid** [comment]
Still current! /reopen

**Comment by mtumiati** [comment]
meanwhile I did the override of the filter row and changed the dateTimePickerLocalization prop

```
import it from "date-fns/locale/it";

//...
<MaterialTable
          //...
          components={{
            FilterRow: (props) => {
              return (
                <MTableFilterRow
                  {...props}
                  localization={{
                    dateTimePickerLocalization: it,
                  }}
                />
              );
            },
          }}
        />
```

**Comment by TheIndependentBrotherhood** [comment]
Hi,

@iltumio , your solution is good for the format of the date.
But how I can change also the language of the buttons ?

**Comment by grinch007** [comment]
Hi, I have a question, do you know how to change the window type to, for example, year? or without ampm?
