### ISSUE TITLE
search from external field

### ISSUE THREAD

**Issue by blackbadgerltd** [mbrn/material-table#532]
I would like to have my search field external to the table. For remote datasources this is fine as I can intercept the query object and modify it, but for local data objects I cannot apply the filter it seems. Is there a way to do this?

I would also like to do the same for filters if possible also.

Cheers
BB

**Comment by mbrn** [comment]
Hi @blackbadgerltd ,

Look at 3rd example. It lets you to override filtering and search algorithm. So you can search on external fields. 

https://material-table.com/#/docs/features/filtering

**Comment by blackbadgerltd** [comment]
Cheers, I was hoping for more of a ‘set the search text’ and let the magic happen, otherwise I would have to reimplement the standard search on every column, and filtering.

**Comment by thedmeyer** [comment]
Revisiting this. Why isn't this an included feature?
