### ISSUE TITLE
Make action column header optional

### ISSUE THREAD

**Issue by lazeebee** [mbrn/material-table#533]
**Is your feature request related to a problem? Please describe.**
I would like to be able to have actions without the column header name

**Describe the solution you'd like**
Action column header name should be optional

**Comment by mbrn** [comment]
You can override it with localization

localization={{
  header : {
     actions: ''
  }
}}

**Comment by lazeebee** [comment]
That will do. Thanks for all your work!

**Comment by vishaltambe70** [comment]
Worked!!!

**Comment by obsd** [comment]
@mbrn is there a way to hide the actions column completely?
If not do you want me to create pull request for that?

**Comment by MahmoudAliEng** [comment]
@obsd  is that possible now ? 
I have a custom row I want to add actions on hover event fired on row...
