### ISSUE TITLE
Editable Currency type render "ok"

### ISSUE THREAD

**Issue by icharge** [mbrn/material-table#534]
**Describe the bug**
I'm using Editable field data and set type as `currency` and then in inline editing **ok** is show up!.

**To Reproduce**
1. Set Columns and field type as `currency`.
2. Define editable `onRowUpdate` callback.
3. Run & click edit icon.
4. "ok" will show up.

**Expected behavior**
Inline Textbox for currency format.

**Screenshots**
![image](https://user-images.githubusercontent.com/1619007/57052929-c36b1a00-6cb4-11e9-8265-75b636c1ea82.png)

**Desktop (please complete the following information):**
 - OS: Any
 - Browser Any

**Comment by bobctr** [comment]
As a workaround for now, you can overwrite the editComponent in the column definition:

```
{
      title: "Value",
      field: "value",
      type: "currency",
      editComponent: props => (
        <input
          type="numeric"
          value={props.value}
          onChange={e => props.onChange(e.target.value)}
        />
      )
    }
```

**Comment by eddiemonge** [comment]
Its because there is no currency field definition at the moment: https://github.com/mbrn/material-table/blob/v1.50.0/src/components/m-table-edit-field.js#L126

**Comment by mforman1** [comment]
> As a workaround for now, you can overwrite the editComponent in the column definition:
> 
> ```
> {
>       title: "Value",
>       field: "value",
>       type: "currency",
>       editComponent: props => (
>         <input
>           type="numeric"
>           value={props.value}
>           onChange={e => props.onChange(e.target.value)}
>         />
>       )
> }
> ```

@bobctr Thanks for the workaround, do you have any idea how can I make it similar to the other fields?

![image](https://user-images.githubusercontent.com/39950157/66707891-b74db300-ed50-11e9-8e30-24e909a66fd4.png)

**Comment by Domino987** [comment]
Cannot be reproduced anymore. IF this is still relevant, feel free to reopen this issue.
