### ISSUE TITLE
Readonly columns in editable table not working

### ISSUE THREAD

**Issue by terapepo** [mbrn/material-table#536]
**Describe the bug**
When using the readonly property on column in a editable table, the column can still be modified. The [demo](https://material-table.com/#/docs/features/editable) it's the perfect example that showcase the bug. I remember this was working in previous versions.

- material-table version: material-table@1.34.2

**Comment by terapepo** [comment]
Found on the source code that this property is now called "editable" and you can set it to one of this:  'always' | 'onUpdate' | 'onAdd' | 'never'. Please update the docs and the [demo](https://material-table.com/#/docs/features/editable)!

**Comment by mbrn** [comment]
Hi @terapepo ,

I updated docs. It will be published tomorrow.

**Comment by gushroom** [comment]
I see that on https://material-table.com/#/docs/all-props in the column prop section "readonly" is still an a field in the columns section, is this intentional.

**Comment by hawzie197** [comment]
@GustavWahl I am thinking it is a mistake. Setting `readonly: true` has no effect. The proper way to handle is  to add `editable: 'never'` to the column dictionary.
