### ISSUE TITLE
How to work with LastEvaluatedKey for pagination?

### ISSUE THREAD

**Issue by tsuga** [mbrn/material-table#538]
I have my backend with AWS DynamoDB.
The pagination mechanism there is to use "LastEvaluatedKey".
Reference: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Query.html#Query.Pagination

How can material-table deal with this type of pagination?

**Comment by mbrn** [comment]
Actually, i dont have any experience with aws dynamodb. i dont know i understand it correctly. But i can give you an advise. 

Store LastEvaluatedKey on your components' state. Then call your rest service with this parameter.
