### ISSUE TITLE
Remote data with table state

### ISSUE THREAD

**Issue by rayray93** [mbrn/material-table#539]
Hi there, great work done (y) 

Is there a way to write in pagePerRow, Search and Filter values from query? 

Currently in remote data fetch before api call I saved query in localStorage(need so if user refreshes page), and if its first fetch I re-write query with my localStorageQuery, so i expected to have all values in place after refresh(Also i see that resolved remote data have all those values), but only one who works is - page

Is there any workaround or way to pass those values?

Thanks,
Ray

**Comment by mbrn** [comment]
Currently you cant. But i can add this simple feature asap.

**Comment by rayray93** [comment]
Thanks, it would be great :)

**Comment by diegosps** [comment]
For completeness, I think ordering properties should be included too, basically all query properties.

In my case I want a "page to item" function with remote data from an external component. 
I can do it with tableRef and onQueryChange as stated in #383 , but i need some way to reset the table state to not produce divergent information.

Thanks

Off topic: your work here is amazing, congrats.

**Comment by GordonSmith** [comment]
I guess this never happened?  New user here and would also like the ability to set/get the entire query state (and I would expect it to reset the visuals for filter and sorted.

**Comment by mindaugasnakrosis** [comment]
What is the status?

**Comment by saunlani** [comment]
any update on this?
