### ISSUE TITLE
breaking change with react-redux@^6.0.0 / ^7.0.0

### ISSUE THREAD

**Issue by ejerry** [mbrn/material-table#542]
**Describe the bug**
Error message on import of 'material-table' along with `react-redux@^6.0.0` or `react-redux@^7.0.0`:

`Uncaught Invariant Violation: storeKey has been removed and does not do anything. To use a custom Redux store for specific components, create a custom React context with React.createContext(), and pass the context object to React Redux's Provider and specific components like: <Provider context={MyContext}><ConnectedComponent context={MyContext} /></Provider>. You may also pass a {context : MyContext} option to connect`

Please see attached log files:
[localhost-1556949549615.log](https://github.com/mbrn/material-table/files/3144578/localhost-1556949549615.log)

This seems to be stemming from the `breaking change #2`  [noted here.](https://github.com/reduxjs/react-redux/releases/tag/v6.0.0)

**To Reproduce**
1. `create-react-app`
2. `yarn add react`
3. `yarn add react-redux`
4. `yarn add material-table`
5. add `import MaterialTable from 'material-table'` to App.js
6. `yarn start`

**Expected behavior**
It should work with react-redux@^6.0.0   :)

**Screenshots**
![image](https://user-images.githubusercontent.com/11894358/57182261-0ca4a080-6e52-11e9-84e0-689098f96fc6.png)

**Versions tried**
I get this same error with any of these versions:
`react-redux@6.0.0`
`react-redux@7.0.0`
`react-redux@7.0.2`
`react-redux@7.0.3`

**Desktop (please complete the following information):**
 - OS: Windows Server 2016
 - Browser: Chrome
 - Version: 74

**Comment by mbrn** [comment]
Hi @ejerry ,

Actually react-beautiful-dnd uses redux. But i will look at this case asap.

**Comment by ejerry** [comment]
Thank you very much @mbrn for the fast review! This is a great component.

**Comment by ejerry** [comment]
woops I missed the react-beautiful-error line @mbrn, I will post an issue there.

**Comment by ejerry** [comment]
Perhaps it can be excluded if there are no DND configurations required?

**Comment by mbrn** [comment]
> Perhaps it can be excluded if there are no DND configurations required?

I can try it.

**Comment by john-pc** [comment]
@mbrn any update ? my app crashes because of dnd feature

**Comment by mbrn** [comment]
Hi @john-pc ,

Why does it crash?

**Comment by ejerry** [comment]
@mbrn and @john-pc seems this _was_ already addressed over at [react-beautiful-dnd](https://github.com/atlassian/react-beautiful-dnd/issues/1056#issuecomment-489679488)

Simply remove your own `react-redux` dependency and all will be well.
