### ISSUE TITLE
CheckAll box not working probably

### ISSUE THREAD

**Issue by allennyzhang** [mbrn/material-table#545]
**Describe the bug**
if any records' was selected, then will dynamic display the button `Schedule`, but the `CheckAll` checkbox doesn't selected correctly.

![image](https://user-images.githubusercontent.com/24515577/57306787-03e3f100-7116-11e9-9306-202dd26f202d.png)
![image](https://user-images.githubusercontent.com/24515577/57306818-11997680-7116-11e9-9863-2a04aa1a6b2e.png)
![image](https://user-images.githubusercontent.com/24515577/57306840-1b22de80-7116-11e9-997d-a1ffb3ad49aa.png)
![image](https://user-images.githubusercontent.com/24515577/57306868-237b1980-7116-11e9-963a-409a867870d3.png)

**Comment by mbrn** [comment]
Hi @allennyzhang ,

Which version of MT do you use? Because i tested it with latest version and it works.

**Comment by emrekara37** [comment]
I am closing this issue. You can reopen if you need.
