### ISSUE TITLE
Handleclick on tablecell

### ISSUE THREAD

**Issue by fredbast** [mbrn/material-table#546]
The new method handleClickCell has changed and doesnt take into account the props onclick:

handleClickCell = e => {
if (this.props.columnDef.disableClick) {
e.stopPropagation();
}
}

and the old one was:

handleClickCell = e => {
const { columnDef, rowData, onClick } = this.props;
if( columnDef.disableClick || typeof onClick !== 'function') return;
onClick(e, rowData);
}
The correction suggested:
 if (_this.props.columnDef.disableClick) {
        e.stopPropagation();
      } else if (_this.props.onClick) {
          _this.props.onClick();
      }

and for cursor style:
if (_this.props.columnDef.disableClick) {
        cellStyle.cursor = 'default';
      } else if (_this.props.onClick) {
        cellStyle.cursor = 'pointer';
      }

**Comment by fredbast** [comment]
the new method has changed and doesnt take into account the props onclick:

 handleClickCell = e => {
    const { columnDef, rowData, onClick } = this.props;
    if( columnDef.disableClick || typeof onClick !== 'function') return;
    onClick(e, rowData);
  }

**Comment by fredbast** [comment]
and the new method is  
handleClickCell = e => {
    if (this.props.columnDef.disableClick) {
      e.stopPropagation();
    }
  }

**Comment by mbrn** [comment]
Hi @fredbast ,

Why you dont send your suggestion as a PR. I can merge it if you send

**Comment by mbrn** [comment]
I checked PR but i think no need for this merge.

**Comment by fredbast** [comment]
Hello,

please chek the code of tag v1.19.2 you will see:

handleClickCell = e => {
    const { columnDef, rowData, onClick } = this.props;
    if( columnDef.disableClick || typeof onClick !== 'function') return;
    onClick(e, rowData);
  }

and since tag v1.20.0 :
 handleClickCell = e => {
    if (this.props.columnDef.disableClick) {
      e.stopPropagation();
    }
  }

Regards

**Comment by fredbast** [comment]
Hello i have added this comment :

« Hello,
please chek the code of tag v1.19.2 you will see:
handleClickCell = e => {
const { columnDef, rowData, onClick } = this.props;
if( columnDef.disableClick || typeof onClick !== 'function') return;
onClick(e, rowData);
}
and since tag v1.20.0 :
handleClickCell = e => {
if (this.props.columnDef.disableClick) {
e.stopPropagation();
}
}
Regards »

Regards
--------------------------------------------------------------
Frédéric Bastide

frederic.bastide@keyword.fr<mailto:frederic.bastide@keyword.fr>
Tél.  : +33 (0)4 67 07 72 00
[logo-keyword-SD-mail]<http://www.keyword.fr/>
--------------------------------------------------------------
Avant d'imprimer, pensez à l'environnement.
--------------------------------------------------------------

Ce message et toutes les pièces jointes sont adressés à l'attention exclusive de leurs destinataires et sont strictement confidentiels. Si vous le recevez par erreur, merci de le détruire après en avoir informé l'expéditeur sans délai. Toute divulgation, copie ou usage par une personne autre que son destinataire sont interdits. Keyword S.D. décline toute responsabilité pour toute altération, déformation ou falsification subie par le message au cours de sa transmission

This message and its attachments are intended only for the person or entity to which it is addressed and are strictly confidential. If you have received this in error, please delete the material from any computer after having informed the sender. Any copy or other use of this information by persons or entities other than the intended recipient is prohibited. Keyword S.D. accepts no liability for any alteration, distortion or falsification that may occur during the transmission of this message.

De : Mehmet Baran <notifications@github.com>
Envoyé : dimanche 26 mai 2019 00:06
À : mbrn/material-table <material-table@noreply.github.com>
Cc : Frédéric Bastide <frederic.bastide@keyword.fr>; Mention <mention@noreply.github.com>
Objet : Re: [mbrn/material-table] Handleclick on tablecell (#546)


I checked PR but i think no need for this merge.

**Comment by mbrn** [comment]
Hi @fredbast 

But we never set a onClick to MTableCell after a point.

**Comment by fredbast** [comment]
Hello this code was Ok but now it doesnt work :


    handleCellValue(props:any)  {
        const myProps = {...props};

        if (myProps.value && myProps.value.idElement) {
            myProps.idelement = myProps.value.idElement
            myProps.onClick= () => {
                this.props.formIdHandler(myProps.idelement)
            }


        }

        if (props.value)  {
            myProps.value = props.value.labelElement?props.value.labelElement:props.value
        }
        return (

            <MTableCell {...myProps} className={myProps.onClick?AppClasses().link2Form:''}/>
        )
    }
…
getTabsContainer(infoForm:any) {
        const classes = this.props.classesHandler;
        if (infoForm.data.table) {

            const dataTab = infoForm.data.table[this.state.value]
            return (<TabContainer key={infoForm.prefixe+"-"+this.state.value}>

                            <MaterialTable
                             components={{
                                Cell: props => (
                                    this.handleCellValue(props)
                                ),
                                Toolbar: props => (
                                    <div className={classes.todolistHeader}>
                                      <MTableToolbar {...props} />
                                    </div>
                                  ),
                              }}
                                {...dataTab}
                                options={{
                                    filtering: true,
                                    columnsButton: true,
                                    pageSize:10,
                                    headerStyle:{color:'white',backgroundColor:'#AAA',textAlign:'center'},
                                    // exportButton: true,
                                }}
                                localization={
                                    materialTableLocalization
                                }

                            />

                        </TabContainer>);
        }
        return null;
    }



    render() {
        const dataLoaded = this.props.infoForm.dataLoaded;
         if (!dataLoaded) {
            this.getInfos();
         }
        return (
            <div>
            {!dataLoaded &&
                            <ModalWait/>
            }
                <Tabs value={this.state.value} onChange={this.handleChangeOnglet} variant="scrollable" scrollButtons="off" indicatorColor="primary"
                  textColor="primary">
                    {this.getTabs(this.props.infoForm)}
                </Tabs>
                {this.getTabsContainer(this.props.infoForm)}
            </div>

        );
    }
}


--------------------------------------------------------------
Frédéric Bastide

frederic.bastide@keyword.fr<mailto:frederic.bastide@keyword.fr>
Tél.  : +33 (0)4 67 07 72 00
[logo-keyword-SD-mail]<http://www.keyword.fr/>
--------------------------------------------------------------
Avant d'imprimer, pensez à l'environnement.
--------------------------------------------------------------

Ce message et toutes les pièces jointes sont adressés à l'attention exclusive de leurs destinataires et sont strictement confidentiels. Si vous le recevez par erreur, merci de le détruire après en avoir informé l'expéditeur sans délai. Toute divulgation, copie ou usage par une personne autre que son destinataire sont interdits. Keyword S.D. décline toute responsabilité pour toute altération, déformation ou falsification subie par le message au cours de sa transmission

This message and its attachments are intended only for the person or entity to which it is addressed and are strictly confidential. If you have received this in error, please delete the material from any computer after having informed the sender. Any copy or other use of this information by persons or entities other than the intended recipient is prohibited. Keyword S.D. accepts no liability for any alteration, distortion or falsification that may occur during the transmission of this message.

De : Mehmet Baran <notifications@github.com>
Envoyé : lundi 27 mai 2019 10:02
À : mbrn/material-table <material-table@noreply.github.com>
Cc : Frédéric Bastide <frederic.bastide@keyword.fr>; Mention <mention@noreply.github.com>
Objet : Re: [mbrn/material-table] Handleclick on tablecell (#546)


Hi @fredbast<https://github.com/fredbast>

But we never set a onClick to MTableCell after a point.

**Comment by mbrn** [comment]
Why you don't add a onClick event to your MTableCell content.

I think your idea i adding a link to cell, am i right?

**Comment by fredbast** [comment]
You are right but i dont understand what tou mean by « add a onClick event to your MTableCell content »

--------------------------------------------------------------
Frédéric Bastide

frederic.bastide@keyword.fr<mailto:frederic.bastide@keyword.fr>
Tél.  : +33 (0)4 67 07 72 00
[logo-keyword-SD-mail]<http://www.keyword.fr/>
--------------------------------------------------------------
Avant d'imprimer, pensez à l'environnement.
--------------------------------------------------------------

Ce message et toutes les pièces jointes sont adressés à l'attention exclusive de leurs destinataires et sont strictement confidentiels. Si vous le recevez par erreur, merci de le détruire après en avoir informé l'expéditeur sans délai. Toute divulgation, copie ou usage par une personne autre que son destinataire sont interdits. Keyword S.D. décline toute responsabilité pour toute altération, déformation ou falsification subie par le message au cours de sa transmission

This message and its attachments are intended only for the person or entity to which it is addressed and are strictly confidential. If you have received this in error, please delete the material from any computer after having informed the sender. Any copy or other use of this information by persons or entities other than the intended recipient is prohibited. Keyword S.D. accepts no liability for any alteration, distortion or falsification that may occur during the transmission of this message.

De : Mehmet Baran <notifications@github.com>
Envoyé : lundi 27 mai 2019 10:15
À : mbrn/material-table <material-table@noreply.github.com>
Cc : Frédéric Bastide <frederic.bastide@keyword.fr>; Mention <mention@noreply.github.com>
Objet : Re: [mbrn/material-table] Handleclick on tablecell (#546)


Why you don't add a onClick event to your MTableCell content.

I think your idea i adding a link to cell, am i right?

**Comment by mbrn** [comment]
I mean why don't use custom render feature instead of overriding Cell component. 

https://material-table.com/#/docs/features/custom-column-rendering

**Comment by fredbast** [comment]
Hello,

In our context it’s more confortable what i have done…

I don’t understand why you don’t want to add this functionnality for non breaking API.

Regards

--------------------------------------------------------------
Frédéric Bastide

frederic.bastide@keyword.fr<mailto:frederic.bastide@keyword.fr>
Tél.  : +33 (0)4 67 07 72 00
[logo-keyword-SD-mail]<http://www.keyword.fr/>
--------------------------------------------------------------
Avant d'imprimer, pensez à l'environnement.
--------------------------------------------------------------

Ce message et toutes les pièces jointes sont adressés à l'attention exclusive de leurs destinataires et sont strictement confidentiels. Si vous le recevez par erreur, merci de le détruire après en avoir informé l'expéditeur sans délai. Toute divulgation, copie ou usage par une personne autre que son destinataire sont interdits. Keyword S.D. décline toute responsabilité pour toute altération, déformation ou falsification subie par le message au cours de sa transmission

This message and its attachments are intended only for the person or entity to which it is addressed and are strictly confidential. If you have received this in error, please delete the material from any computer after having informed the sender. Any copy or other use of this information by persons or entities other than the intended recipient is prohibited. Keyword S.D. accepts no liability for any alteration, distortion or falsification that may occur during the transmission of this message.

De : Mehmet Baran <notifications@github.com>
Envoyé : lundi 27 mai 2019 10:46
À : mbrn/material-table <material-table@noreply.github.com>
Cc : Frédéric Bastide <frederic.bastide@keyword.fr>; Mention <mention@noreply.github.com>
Objet : Re: [mbrn/material-table] Handleclick on tablecell (#546)


I mean why don't use custom render feature instead of overriding Cell component.

https://material-table.com/#/docs/features/custom-column-rendering

**Comment by mbrn** [comment]
But we never set onClick of a cell. You use it in a if expression, but it will never work.

**Comment by fredbast** [comment]
please chek the code of tag v1.19.2 you will see:
handleClickCell = e => {
const { columnDef, rowData, onClick } = this.props;
if( columnDef.disableClick || typeof onClick !== 'function') return;
onClick(e, rowData);
}


--------------------------------------------------------------
Frédéric Bastide

frederic.bastide@keyword.fr<mailto:frederic.bastide@keyword.fr>
Tél.  : +33 (0)4 67 07 72 00
[logo-keyword-SD-mail]<http://www.keyword.fr/>
--------------------------------------------------------------
Avant d'imprimer, pensez à l'environnement.
--------------------------------------------------------------

Ce message et toutes les pièces jointes sont adressés à l'attention exclusive de leurs destinataires et sont strictement confidentiels. Si vous le recevez par erreur, merci de le détruire après en avoir informé l'expéditeur sans délai. Toute divulgation, copie ou usage par une personne autre que son destinataire sont interdits. Keyword S.D. décline toute responsabilité pour toute altération, déformation ou falsification subie par le message au cours de sa transmission

This message and its attachments are intended only for the person or entity to which it is addressed and are strictly confidential. If you have received this in error, please delete the material from any computer after having informed the sender. Any copy or other use of this information by persons or entities other than the intended recipient is prohibited. Keyword S.D. accepts no liability for any alteration, distortion or falsification that may occur during the transmission of this message.

De : Mehmet Baran <notifications@github.com>
Envoyé : mardi 28 mai 2019 10:19
À : mbrn/material-table <material-table@noreply.github.com>
Cc : Frédéric Bastide <frederic.bastide@keyword.fr>; Mention <mention@noreply.github.com>
Objet : Re: [mbrn/material-table] Handleclick on tablecell (#546)


But we never set onClick of a cell. You use it in a if expression, but it will never work.

**Comment by mbrn** [comment]
Yes there was. But now we don't use it in new versions.

**Comment by fredbast** [comment]
So for those that use this it s a breaking API…

The code i have sent resolve the « problem » and works…

--------------------------------------------------------------
Frédéric Bastide

frederic.bastide@keyword.fr<mailto:frederic.bastide@keyword.fr>
Tél.  : +33 (0)4 67 07 72 00
[logo-keyword-SD-mail]<http://www.keyword.fr/>
--------------------------------------------------------------
Avant d'imprimer, pensez à l'environnement.
--------------------------------------------------------------

Ce message et toutes les pièces jointes sont adressés à l'attention exclusive de leurs destinataires et sont strictement confidentiels. Si vous le recevez par erreur, merci de le détruire après en avoir informé l'expéditeur sans délai. Toute divulgation, copie ou usage par une personne autre que son destinataire sont interdits. Keyword S.D. décline toute responsabilité pour toute altération, déformation ou falsification subie par le message au cours de sa transmission

This message and its attachments are intended only for the person or entity to which it is addressed and are strictly confidential. If you have received this in error, please delete the material from any computer after having informed the sender. Any copy or other use of this information by persons or entities other than the intended recipient is prohibited. Keyword S.D. accepts no liability for any alteration, distortion or falsification that may occur during the transmission of this message.

De : Mehmet Baran <notifications@github.com>
Envoyé : mardi 28 mai 2019 10:23
À : mbrn/material-table <material-table@noreply.github.com>
Cc : Frédéric Bastide <frederic.bastide@keyword.fr>; Mention <mention@noreply.github.com>
Objet : Re: [mbrn/material-table] Handleclick on tablecell (#546)


Yes there was. But now we don't use it in new versions.

**Comment by mbrn** [comment]
Alright. I will check it again with your code.

**Comment by jayarjo** [comment]
@fredbast you've attempted PR to the transpiled code, which obviously cannot be accepted. 

Also "my code worked and now it doesn't" is not legitimate explanation of the issue. What could have been helpful in this case was to link the exact commit that introduced the regression.
