### ISSUE TITLE
Clickable Row

### ISSUE THREAD

**Issue by kuantayevs** [mbrn/material-table#547]
I am trying to override component Row so it can be clickable and pass some action to it.
I have action buttons which do call, however I want to do the same call on row click. Can you give me advise how to solve it?

```
components={{
	Row: props => (
		<MTableBodyRow onClick={this.someFunc} {...props} />
	)
}}
```

**Comment by mbrn** [comment]
Hi @kuantayevs ,

Look at 3rd example at https://material-table.com/#/docs/features/detail-panel. MT already has a onRowClick prop.

**Comment by gsabetta** [comment]
@mbrn I did had to make an override for other reasons and I need to have an event listener on the override 
`          components={{
            Row: props => {
              const {
                data: { compareTo }
              } = props;

              if (compareTo) {
                compareTo.tableData = { ...props.data.tableData };
              }

              return (
                <>
                  <MTableBodyRow onRowClick={() => (/* some listener */)} className="result-row" {...props} />
                  {compareTo && <MTableBodyRow className="result-row differential-row" {...props} data={compareTo} />}
                </>
              );
            }
          }}`

My override renders 2 rows per data point if certain logic is set and I need to add an event listener to the row Is this supported?

thanks

**Comment by gsabetta** [comment]
@mbrn 
I made an override cuz I'm working with a diff table and I'm rendering 2 rows for each data point while in diff view 


```
          components={{
            Row: props => {
              const {
                data: { compareTo }
              } = props;

              if (compareTo) {
                compareTo.tableData = { ...props.data.tableData };
              }

              return (
                <>
                  <MTableBodyRow onRowClick={() => (/* some listener */)} className="result-row" {...props} />
                  {compareTo && <MTableBodyRow className="result-row differential-row" {...props} data={compareTo} />}
                </>
              );
            }
          }}
```

I can't get the listener to work, is there a way around this?
