### ISSUE TITLE
Column ordering gets reset on pagination

### ISSUE THREAD

**Issue by jakeleventhal** [mbrn/material-table#548]
**Describe the bug**
If you reorder columns, they get reset if paginated data is fetched

**Expected behavior**
Column ordering should not reset

**Comment by mbrn** [comment]
I think that it is about you are not storing columns on state. After rerender it lost order data on columns. But i will take a look at it.

**Comment by theamanbhargava** [comment]
@jakeleventhal can you add reproduction steps please?

**Comment by mbrn** [comment]
I test it and it works.
