### ISSUE TITLE
Is it able to move the detail panel `Icon` from left to right

### ISSUE THREAD

**Issue by YongZhangEmbed** [mbrn/material-table#549]
![image](https://user-images.githubusercontent.com/46992381/57343440-f5580280-7132-11e9-948e-90f3c2f7fea9.png)

**Comment by mbrn** [comment]
Currently no. But you can use onRowClick to toggle detail panel. 

Look at 3rd example at:
https://material-table.com/#/docs/features/detail-panel

**Comment by YongZhangEmbed** [comment]
Is it possible to remove the `Icon`?

**Comment by mbrn** [comment]
You can not. But you i can add this feature. Because a lot of developer asked for it.

**Comment by YongZhangEmbed** [comment]
thanks for your feedback, hope this feature coming soon

**Comment by Leocete** [comment]
@mbrn, has the feature of hiding the "toggle" icon been implemented?
Also, is it possible to show a detail panel by default (without clicking anywhere)?

**Comment by edwinckc** [comment]
> @mbrn, has the feature of hiding the "toggle" icon been implemented?
> Also, is it possible to show a detail panel by default (without clicking anywhere)?

Not related to the original issue, but I was also looking for this feature. Using this as a workaround:

```
detailPanel={[
    (rowData) => ({
        disabled: isEmpty(rowData.notes),  // hides hover state
        icon: isEmpty(rowData.notes) ? ' ' : ChatBubbleOutline,  // single space used here, empty string defaults to chevron
        openIcon: isEmpty(rowData.notes) ? ' ' : ChatBubble, // single space
        ...
    }),
]}
```

**Comment by yzhaoa** [comment]
Try 

```
      sx={{
        '.MuiDataGrid-row > .MuiDataGrid-cell:first-child, * > .MuiDataGrid-columnHeader:first-child': {
          order: 1,
        }
      }}

```
