### ISSUE TITLE
Change Header row Height

### ISSUE THREAD

**Issue by denis-sk** [mbrn/material-table#552]
Make it possible to change the header row height.

Now I do not know how to do it. I can change only header cell style.

**Comment by mbrn** [comment]
Hi @denis-sk 
 You can use options.headerStyle to change header rowHeight. 

![image](https://user-images.githubusercontent.com/7895451/57427077-f8361e80-722a-11e9-8cc0-6e47ab975e2c.png)

**Comment by denis-sk** [comment]
No. Header Style change th cell style, but tr style not changes. 

![image](https://user-images.githubusercontent.com/26207133/57521379-cb683100-7328-11e9-9335-a6c9355a2631.png)

**Comment by mbrn** [comment]
I will add cellStyle to options to effect all cells.

**Comment by denis-sk** [comment]
Do you mean the cellstyle will be applied to the header cell and row cell? If yes, I think they should work independently of each other.

**Comment by mbrn** [comment]
No it will be applied to all cells(not headers)

**Comment by sshanzel** [comment]
#1214 PR for passing cellStyle down to ColumnDef for options to take effect.

**Comment by sshaw** [comment]
Problem here is `tr` has a height of `56px` so if cell height is smaller is does not matter. `56px` is used.

**Comment by EdmarPereira** [comment]
I found a solution for my use, I need to edit this property to change the size of the table header and table body:
.MuiTableCell-root {
  height: 10px !important;
  padding: 0px !important;
  font-size: 0.7rem !important;
}

.MuiButtonBase-root{
  height: 10px !important;
}

with this you can adjust for you

**Comment by Forsaiken** [comment]
I found a solution changing the paddingTop and paddingBottom on HeaderStyle

**Comment by asok-mirror** [comment]
> I found a solution for my use, I need to edit this property to change the size of the table header and table body:
> .MuiTableCell-root {
> height: 10px !important;
> padding: 0px !important;
> font-size: 0.7rem !important;
> }
> 
> .MuiButtonBase-root{
> height: 10px !important;
> }
> 
> with this you can adjust for you

This seems to be hiding the footer as well

**Comment by asok-mirror** [comment]
The row height is not getting applied though I can see the height property at tr level. weird though!! 

Any thoughts?

**Comment by solisadeqi** [comment]
height dose not work :( , have tried multiple solutions

**Comment by yashaswinibprasad87** [comment]
any fix for the issue?

**Comment by jason-zeiler-bayer** [comment]
Could use some help here as well if anyone has found a solution?
