### ISSUE TITLE
react, react-dom version

### ISSUE THREAD

**Issue by wandrzejczak** [mbrn/material-table#553]
I've noticed that in package.json react and react-dom have different versions.
It is recommended to have both versions the same.

https://stackoverflow.com/questions/53024307/typeerror-dispatcher-usestate-is-not-a-function-when-using-react-hooks

**Comment by mbrn** [comment]
Absolutely.

**Comment by theamanbhargava** [comment]
@mbrn Can we close this issue?

**Comment by mbrn** [comment]
Of course.

A trick:
If you write you comments like this : "This closes #ISSUE_NUMBER, bla bla bla", after merging issues would be closed automatically.

https://help.github.com/en/articles/closing-issues-using-keywords
