### ISSUE TITLE
rowStyle being overwritten by MuiTableCell-root

### ISSUE THREAD

**Issue by roseak** [mbrn/material-table#554]
**Describe the bug**
Seems like despite rowStyle adding the styles for rows, MuiTableCell-root is overriding them (trying to increase the font size of the data in the table).

**Comment by mbrn** [comment]
Actually rowStyle does not effect the inside cells. You may try MuiThemeProvider

**Comment by brichbe** [comment]
@roseak I'm having the same problem you described - wanting to increase the font size of table cells, but attempting to do that via `rowStyle` is not working.  Did you find any solution using MuiThemeProvider?

**Comment by roseak** [comment]
Instead of being able to adjust it for all of the columns, you have to add `cellStyle` to each column with the fontSize you want.  Like `{ title: "Name", field: "name", cellStyle: { fontSize: "12px" } }`
