### ISSUE TITLE
Uncaught TypeError: Cannot read property 'tableData' of undefined after first page

### ISSUE THREAD

**Issue by exp0nge** [mbrn/material-table#555]
**Describe the bug**
From page 2 and onwards, when you click on the detail pane / chevron, the table errors out with: `Uncaught TypeError: Cannot read property 'tableData' of undefined`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Version [e.g. 22] 1.32.0

**Smartphone (please complete the following information):**

**Additional context**

**Comment by exp0nge** [comment]
@mbrn for reference the code: https://github.com/mbrn/material-table/pull/175#issuecomment-459372239

**Comment by Domino987** [comment]
Close in favor of #175
