### ISSUE TITLE
maxBodyHeight does not take a percentage

### ISSUE THREAD

**Issue by blackbadgerltd** [mbrn/material-table#556]
**Describe the bug**
When trying to have a table fit within a flexible area, providing a string of 'x%' makes the table expand to its full height

**To Reproduce**
1. provide a maxbodyheight of say 20% inside a div of fixed size

**Expected behavior**
Table should render to max height of percentage of parent

**Desktop (please complete the following information):**
 - OS: OSX 1.14
 - Browser Chrome, safari
 - Version 68

** maybe due to overflowY set to auto?

**Comment by mbrn** [comment]
Hi @blackbadgerltd ,

Actually this is not a bug. % height could not be applied cause of parent component that is not specified a height. 

Trick: You can use maxBodyHeight: **'80vh'** :)

**Comment by rahuldsce** [comment]
maxBodyHeight:'calc(100vh - 190px)'  try this
