### ISSUE TITLE
Ability for Striped column or style for group of column

### ISSUE THREAD

**Issue by jatinvmehta** [mbrn/material-table#557]
I start using this library and it is pretty amazing. I am looking for following feature and wondering if it is already available or on your roadmap.

1. Ability to style rows based on certain condition. I am rendering employee information and i wanted to style all employees by department. So HR needs to be green, Tech should be yellow etc. I am already having data sorted such a way while getting back from backend.
2. I have around 20 columns so obviously i get scroll bar and wondering if pagination can be moved to left and top or configurable.
3. Ability for file upload

Let me know if any of above feature already exists or in pipeline

**Comment by mbrn** [comment]
Hi @jatinvmehta ,

1. This is possible right now: 3rd example: https://material-table.com/#/docs/features/styling
2. This is in my roadmap. I will add pagination position option. 
3. Do you ask for file upload component for editable feature? If so, you can override EditComponent of column.

**Comment by jatinvmehta** [comment]
Thank you very much for your quick reply. I will try item 1. Do you have any ETA on 2nd item ? Also for item 3, looking for ability where we can upload 1000+ item through upload ability so not sure if EditComponent can work here or not

**Comment by mbrn** [comment]
Actually i work a lot for MT but i can not promise on any date. Because MT is my hobby project. I work for a company and upwork(freelance) on various projects. But i will do it asap. 

For 3: I think if you use a well component you can upload many files. It does not depend to MT.
