### ISSUE TITLE
CONTRIBUTING.md URL is broken inside README.md

### ISSUE THREAD

**Issue by theamanbhargava** [mbrn/material-table#558]
**Describe the bug**
The URL to CONTRIBUTING.md is broken

**To Reproduce**
1. Go to README.md
2. Click on hyperlink for CONTRIBUTING.md
3. See 404 error

**Expected behavior**
CONTRIBUTING.md should open up

**Platforms**
Issue is there across all platforms.

**Comment by mbrn** [comment]
Thanks
