### ISSUE TITLE
Large pagination count results in scrollbars. 

### ISSUE THREAD

**Issue by Flash619** [mbrn/material-table#565]
**Describe the bug**
When pagination goes in the hundreds, scroll bars appear.

**To Reproduce**
1. Create a table with a few hundred items.
2. Set the max rows per page to 100 or 200.

**Expected behavior**
Overflow should be hidden, or pagination should expand.

**Screenshots**
![image](https://user-images.githubusercontent.com/1608113/57534468-b037fa00-7305-11e9-984c-5467113bcd65.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by mbrn** [comment]
Hi @Flash619 

I tested it with 10000 rows of data and 1000 per page. But it does not occur. Can you test it with latest version please?

**Comment by mbrn** [comment]
I guess it would be resolved.
