### ISSUE TITLE
Add contribution section to readme and docz

### ISSUE THREAD

**Issue by mbrn** [mbrn/material-table#57]
A contributing.md file should be added main path
short description should add to readme and this should refer the contributing
contribution page should be added to docz as last page on the menu tree

**Comment by mbrn** [comment]
- A contributing.md file should be added main path
- short description should add to readme and this should refer the contributing 
- contribution page should be added to docz as last page on the menu tree

**Comment by luizbaldi** [comment]
Hi, I'm taking this one :)

**Comment by mbrn** [comment]
of course. You can check other big projects in github and write a similar one.

**Comment by luizbaldi** [comment]
PR open in #60.
