### ISSUE TITLE
Delete selected rows

### ISSUE THREAD

**Issue by cesoftinfo** [mbrn/material-table#571]
Hi, after update deleting selected rows does not work and selected rows remain selected. Rows are removed from state but not from table?

**Comment by mbrn** [comment]
Hi @cesoftinfo ,

Can you share a code sample to reproduce case?

**Comment by cesoftinfo** [comment]
When I try to delete selected rows, it does remove it from state but selected rows are not being removed from table and selected rows remain selected.  
 actions={[
              {
                tooltip: 'Remove All Selected Users',
                icon: 'delete',
                onClick: (evt, data) => {
                  let i;
                  for (i = data.length - 1; i >= 0; i--) {
                    let index = data[i].tableData.id;
                    this.state.alldata.splice(index, 1);
                  }
                }
              }
            ]}

**Comment by JpMza** [comment]
i have a similar issue, im beig able to remove the row from the state but after seting the state all te table data is removed.

**Comment by Domino987** [comment]
That is not a problem with the table, but how you update the data. Feel free to ask on how to do that in the [gitter chat](https://gitter.im/material-table/Lobby) or SO.
