### ISSUE TITLE
Add and control table footer

### ISSUE THREAD

**Issue by flyingangel** [mbrn/material-table#573]
Not talking about the footer with pagination. But the last row where you can display the sum or the percentage of one column.

The row must be fixed when navigating with pagination, must not have any empty space between this footer row and the last row of a table

We can set footer for all or just one chosen column but the number of declared footer must be the same as header columns

The footer, by default, use a **sum** function if the header of the table is of type **number**, or **percentage** with an option to specify precision after **,** or **.** (local dependent). A custom rendering function is needed, receiving the entire table data as function parameter.

If any row in a table is update or through onRowUpdate/Delete/Add, footer will be re-rendered

https://datatables.net/examples/advanced_init/footer_callback

**Comment by mbrn** [comment]
This is my roadmap. I will add a summarize row feature asap.

**Comment by iherger** [comment]
I am also looking for such a sum row at the end. That would really be cool, and would make material-table even better than it already is!

**Comment by codenamethanos** [comment]
I also want this feature really badly.  
Is it atleast possible to make a custom row? And then render some data into it and use it as a workaround with current features?

**Comment by radmonteiro** [comment]
any news when will this be available?

**Comment by mindaugasnakrosis** [comment]
@mbrn 

> This is my roadmap. I will add a summarize row feature asap.

What is the status?
