### ISSUE TITLE
Really need forceUpdate() method

### ISSUE THREAD

**Issue by pwork2015** [mbrn/material-table#577]
Hello! Please, make the method forceUpdate() or refresh(), which will do the next:

_this.onQueryChange(_this.state.query);

I need it for working with remoteData. Your algorithm with data: (query) => ... is NOT suitable for my hard project. Thank you for help!

**Comment by theamanbhargava** [comment]
Can you share a code snippet so we can see the exact use case?

**Comment by mbrn** [comment]
Hi @pwork2015,

I wrote a example for this case. Please check 2nd example at:

https://material-table.com/#/docs/features/remote-data

**Comment by gelzoh** [comment]
This doesn't work on TypeScript

> Hi @pwork2015,
> 
> I wrote a example for this case. Please check 2nd example at:
> 
> https://material-table.com/#/docs/features/remote-data

**Comment by WalissonPires** [comment]
+1
