### ISSUE TITLE
Drag&drop is not moving filter field 

### ISSUE THREAD

**Issue by JKrymarys** [mbrn/material-table#578]
When I try to move column, that  has been already filtered, the column is moved properly, but not the filter. It stays in the old position (it's still working, tho).

**To Reproduce**
1.  Turn on features of table like drag&drop and filter 
2. Activate some filter
3. Move column with filtered values 

**Expected behavior**
I expect that filter will "stick" to the column, and change it's position together with the header and values. 

**Screenshots**

![image](https://user-images.githubusercontent.com/17932699/57692268-a6d0c980-7646-11e9-8f19-7461b7d532d3.png)
I can move column, but filter is not moving with the rest. 
![image](https://user-images.githubusercontent.com/17932699/57692300-b8b26c80-7646-11e9-907d-2dd40ce76051.png)

**Desktop (please complete the following information):**
 - Chrome v74

**Comment by mbrn** [comment]
This is done with 1.36.4
