### ISSUE TITLE
Build error - 'MenuProps' is not exported from '@material-ui/core'

### ISSUE THREAD

**Issue by luizbaldi** [mbrn/material-table#58]
Hi,

I recently started a project using `material-table` and when the server starts I get this error:

```
./node_modules/material-table/dist/m-table-filter-row.js
Attempted import error: 'MenuProps' is not exported from '@material-ui/core'.
```

What do you guys think is the best solution for this? I'm also available to open a PR and fix this error.

**Comment by mbrn** [comment]
Hi @luizbaldi,

Thanks you for issue. Bug resolved with version 1.0.0-rc.2 please try it

**Comment by luizbaldi** [comment]
Thanks @mbrn, it worked just fine!

And sorry for creating an unnecessary issue.

**Comment by mbrn** [comment]
No it was not unnecessary @luizbaldi. Thank for your issue :)
