### ISSUE TITLE
Server side rendering warning

### ISSUE THREAD

**Issue by oliviertassinari** [mbrn/material-table#580]
**Describe the bug**
Hydration mismatch warnings are raised when server-side rendering the components.

**To Reproduce**
1. Go to https://next.material-ui.com/components/tables/#material-table in dev mode
2. Open the console

**Expected behavior**
No warnings.

Version 1.35.2. I believe it's related to i18n props that leak to the DOM node.

**Comment by mbrn** [comment]
This will be in next release and i will send pr to mui docs with newer version of MT.

**Comment by oliviertassinari** [comment]
Nice! :)

**Comment by adamsoffer** [comment]
Was this resolved?
