### ISSUE TITLE
How to use tableRef prop to pass ref over withStyles

### ISSUE THREAD

**Issue by CatLover94** [mbrn/material-table#581]
Hi, 
 
I am trying to provide a className to the component to be able to override the CSS of the table component (without using JSS or changing my MaterialUI theme).

In the docs, I found this "tableRef" props but I couldn't find an example of how to use it and what I can benefit from passing this props. 

Thanks!

**Comment by mbrn** [comment]
Which component of MT do you want to apply a style?

**Comment by CatLover94** [comment]
Is it possible to provide a way to assign className to components like:

**Comment by mbrn** [comment]
> Is it possible to provide a way to assign className to components like:
> Toolbar: props => (<MTableToolbar {...props} className="material-table-toolbar" />),

No. But you can use JSS to apply a class. 

Check this: https://material-ui.com/customization/css-in-js/
