### ISSUE TITLE
How to customize styles using MuiThemeProvider?

### ISSUE THREAD

**Issue by sabarigr** [mbrn/material-table#583]
I was trying to change the font family from Roboto to a custom font. For this I tried this,

```
const theme = createMuiTheme({
  overrides: {
    MuiTable: {
      root: {
        fontFamily: Georgia, sans-serif
      }
  }
});
```

and imported this theme to my app. Only the default styles are being generated and not the one I gave through the theme object. 

Does this approach work or using the cellStyle / headerStyle options the only way to style the table?

Please help

**Comment by mbrn** [comment]
Hi @sabarigr,

You can use cell styles and header style. Did you try override to Typography in your theme?

**Comment by sabarigr** [comment]
@mbrn Exactly. I couldnt override the default typography in theme overrides.

**Comment by mbrn** [comment]
Check this: 
https://codesandbox.io/embed/epic-almeida-ykjlw

**Comment by rxhl** [comment]
Hi @mbrn, the code sandbox link you provided above does not work. Could you please check?

**Comment by Shawnxkwang** [comment]
> Check this:
> https://codesandbox.io/embed/epic-almeida-ykjlw

The link doesn't work
