### ISSUE TITLE
Hide first and last page option in pagination

### ISSUE THREAD

**Issue by YuuwakU** [mbrn/material-table#584]
I want to hide the first page and last page option in pagination as in our backend pagination we do not provide that option.

**Comment by mbrn** [comment]
showFirstLastPageButtons added to options. This will be on next release.

**Comment by YuuwakU** [comment]
Thanks a ton, brother! :)

**Comment by mbrn** [comment]
UWC

Thanks in github means clicking star repository:)

**Comment by YuuwakU** [comment]
Done sir!

**Comment by mbrn** [comment]
This is done with version 1.39.0
