### ISSUE TITLE
Placeholder for search input

### ISSUE THREAD

**Issue by Likurg2010** [mbrn/material-table#586]
HI. Is there some possibility to add placeholder for "Search" input?

**Comment by mbrn** [comment]
This is done with 1.36.4

**Comment by tmikoss** [comment]
@mbrn seems to be missing from https://github.com/mbrn/material-table/blob/master/types/index.d.ts

**Comment by emrekara37** [comment]
` localization={{
                    toolbar: {
                      searchPlaceholder: 'Placeholder'
                    }
                  }}`

it works
