### ISSUE TITLE
Adding a actionHeaderStyle prop just like the headerStyle prop

### ISSUE THREAD

**Issue by urirahimi** [mbrn/material-table#588]
**Is your feature request related to a problem? Please describe.**
Please add an actionHeaderStyle prop just like the headerStyle prop 

**Describe the solution you'd like**
When you use the editable feature, it automatically colors the column header without allowing you to edit that color. Create a prop to solve the header style problem in the codesandbox below.

See this codesandbox: https://4pg4i.codesandbox.io/

**Comment by jakeleventhal** [comment]
not stale

**Comment by jakeleventhal** [comment]
not stale

**Comment by jakeleventhal** [comment]
not stale

**Comment by jakeleventhal** [comment]
not stale

**Comment by jakeleventhal** [comment]
not stale
