### ISSUE TITLE
Support drag&drop without grouping 

### ISSUE THREAD

**Issue by JKrymarys** [mbrn/material-table#590]
Hi,
I would like to have a possibility to change order of columns by drag&drop mechanism.  

Currently, it's only possible together when grouping is activated. It would be great if this could be a separate feature.

**Comment by priemd** [comment]
In the meantime you can override Groupbar component
```javascript
                Groupbar: props => (
                  <div style={{ display: "none" }}>
                    <MTableGroupbar {...props} />
                  </div>
                ),
```

**Comment by mbrn** [comment]
I will do this asap. 


Hey @priemd :) You are a solution guy :)
> In the meantime you can override Groupbar component
> 
> ```js
>                 Groupbar: props => (
>                   <div style={{ display: "none" }}>
>                     <MTableGroupbar {...props} />
>                   </div>
>                 ),
> ```

**Comment by mbrn** [comment]
This should be done with version 1.36.6
