### ISSUE TITLE
Showing examples first in documentation

### ISSUE THREAD

**Issue by AmeddahAchraf** [mbrn/material-table#591]
**It would be better if you show the examples section first in the documentation for better visualisation of the feature**

<img width="714" alt="Screen Shot 2019-05-16 at 12 54 55 PM" src="https://user-images.githubusercontent.com/33070929/57851989-dbc15580-77d9-11e9-9f0b-791992d47f07.png">

**Comment by mbrn** [comment]
I think examples at the end is more effective. Why do you want this?
