### ISSUE TITLE
Creating new action overrides pre-existing actions' component

### ISSUE THREAD

**Issue by Stetchy** [mbrn/material-table#592]
**Describe the bug**
Creating a new action/component pair changes any pre-existing actions' component to the new one.

**To Reproduce**
1. Add a new component/action pair like the following:
```
                    actions={[
                        {
                          icon: 'save',
                          tooltip: 'Save User',
                          onClick: (event, rowData) => console.log(rowData)
                        }
                      ]}
                    components={{
                        Action: props => (
                          <Button
                            onClick={(event) => props.action.onClick(event, props.data)}
                            color="primary"
                            variant="contained"
                            style={{textTransform: 'none'}}
                            size="small"
                          >
                            My Button
                          </Button>
                        ),
                      }}
```
2. Bug will render on reload.

**Expected behavior**
Pre-existing actions' components remain unchanged while the new action is added.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/6255097/57876617-b1898b00-780d-11e9-9366-e50d15bc1288.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chromium (Electron)

**Comment by mbrn** [comment]
Hi @Stetchy 

I could not reproduce the case. Can you check it with latest version please?

**Comment by mbrn** [comment]
I guess problem should be resolved. Please reopen if it is not.

**Comment by Stetchy** [comment]
Hi @mbrn, sorry for the slow reply - I can confirm it is fixed in the newest version.
