### ISSUE TITLE
Editable not updating my row properly when field is a nested object

### ISSUE THREAD

**Issue by serge20** [mbrn/material-table#597]
Hi,

I am using the table on an object that has nested objects.

for example: 

`{
  name: "My Name",
  nest: {
       nested: {
          address: "My Address"
      }
   }
}`

The table can display the values by setting the field to "nest.nested.address".

When I make the table editable and I update the field. Instead of it updating the value in nest.nested.address

It created a new key in the object  "nest.nested.address": "MyAddress". 

Is that a bug or does the table not support updating nested objects on edit?

**Comment by mbrn** [comment]
Actually it is a bug. I can resolve it asap.

**Comment by serge20** [comment]
@mbrn Thanks for the quick reply, is there any ETA on when this will be resolved? It's blocking my team from using it so we're just wondering if we should wait or try to find an alternative library.

**Comment by mbrn** [comment]
Hi @serge20 ,

I am very busy nowadays. But i will work for MT after 1june. So i think this issue will be resolved in 10 days.

**Comment by mbrn** [comment]
This should be done with version 1.36.6
