### ISSUE TITLE
Is there a way to insert new row at a certain index, rather than at end or beginning of table?

### ISSUE THREAD

**Issue by HanaaAbbas** [mbrn/material-table#600]
I have a counter data field. If I make this field editable "onAdd" only. Is there a way I can make it change the insertion point from the first row or last row according to options to the index specified and render the remaining rows accordingly? 

Thank you very much.

**Comment by mbrn** [comment]
Currently you cant. But i think to add a newFieldValue function to let users assign a initial value to fields.
