### ISSUE TITLE
Add custom styles

### ISSUE THREAD

**Issue by pwork2015** [mbrn/material-table#601]
Hi!
Please add option customStyles here:
![изображение](https://user-images.githubusercontent.com/50596432/57999805-5f7f8880-7adf-11e9-9820-731583df8923.png)
style: {
  maxHeight: props.options.maxBodyHeight,
  overflowY: 'auto',
  ...(props.options.customStyles || {}),
 }

**Comment by zproxy00** [comment]
Cannot find changes, and "height" doesn't work.
<props.components.Container style={{ position: 'relative', ...props.style }}> - that?
It works not as I need. Need to add properties to style: { maxHeight, overflowY, ...HERE... } as in my screenshot.

**Comment by pwork2015** [comment]
Cannot find changes, and "height" doesn't work.
<props.components.Container style={{ position: 'relative', ...props.style }}> - that?
It works not as I need. Need to add properties to style: { maxHeight, overflowY, ...HERE... } as in my screenshot.

**Comment by mbrn** [comment]
This feautere did not published yet. It will be in next release(tomorrow)

**Comment by mbrn** [comment]
This is done with version 1.38.0

**Comment by wfaucet** [comment]
Cannot understand how to use it. Where to set style.height, for example? You did not add code where I ask.

**Comment by pwork2015** [comment]
Cannot understand how to use it. Where to set style.height, for example? You did not add code where I ask.

**Comment by mbrn** [comment]
<MaterialTable
      style={{padding: 20}}
...
/>

**Comment by pwork2015** [comment]
It works not as we need. I still cannot set style of inner div.
This

style: {
     maxHeight: props.options.maxBodyHeight,
     overflowY: 'auto'
 }

is not editable, but it must be editable..

**Comment by pwork2015** [comment]
where can I find this part in source code (/src )?

![изображение](https://user-images.githubusercontent.com/50596432/57999805-5f7f8880-7adf-11e9-9820-731583df8923.png)
