### ISSUE TITLE
Override Checkbox color

### ISSUE THREAD

**Issue by YongZhangEmbed** [mbrn/material-table#604]
Is it able to override checkbox  color  when selected?
![image](https://user-images.githubusercontent.com/46992381/58083623-dfbdf080-7ba8-11e9-8f76-9b4a2af4da1d.png)

**Comment by diegosps** [comment]
One way is with a local material theme.

See the last example:
https://material-table.com/#/docs/features/styling

**Comment by YongZhangEmbed** [comment]
> One way is with a local material theme.
> 
> See the last example:
> https://material-table.com/#/docs/features/styling

Thanks, it helps me to fix this issue
