### ISSUE TITLE
Issue with custom column rendering

### ISSUE THREAD

**Issue by will-code-for-cash** [mbrn/material-table#605]
**Issue with custom column rendering - cutting off popover being displayed**

Steps to reproduce
1. Create a column with custom component that includes a popover or menu that can be opened when you click on the cell.
2. Make sure you try this further down the grid to reproduce.
3. Can see popover/menu getting cut off
![image](https://user-images.githubusercontent.com/30115849/58111069-aad18e00-7be8-11e9-87c4-32481965a53c.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/30115849/58111286-1ca9d780-7be9-11e9-9d1a-4920fa2e1000.png)

Occurs on:
Desktop
Mobile devices

**Comment by mbrn** [comment]
Hi @will-code-for-cash ,

I got similar issue for custom rendering. I solved problem with use a component instead of inline render function. 

Do not use like this if you have a popover: 
render: rowData => <...>

Use like this:
render: MyComponent

You can access this.props.rowData in MyComponent

**Comment by bartdelange** [comment]
Hi,

Sorry to open a closed issue, however I have a question that is basically exactly the same issue as this one.
Feeding the render option a component is no longer a valid option so it this issue has come back.
The render option either just thinks it's a function (when using reacts functional components), or it does not render at all throwing an error (when using a class): `this.props.columnDef.render is not a function`.

I am using it with a split button (https://material-ui.com/components/button-group/#split-button) like below:
![Screenshot 2020-08-31 at 16 15 18](https://user-images.githubusercontent.com/32978882/91730091-ca09ea00-eba5-11ea-9e7e-f48888eb9dae.png)

But it renders badly like the example in the first post:
![Screenshot 2020-08-31 at 16 15 22](https://user-images.githubusercontent.com/32978882/91730159-e27a0480-eba5-11ea-8e7f-e132106290f4.png)
