### ISSUE TITLE
lookup on dynamic data

### ISSUE THREAD

**Issue by samazadi** [mbrn/material-table#606]
I'm trying to create an editable table that lets users edit and select an option from the dropdown. 

I see that the examples use the lookup, but how can I use this if I'm retrieving the data from an API and I don't know all the lookup values it can use? For example, I want to get a list of all users from my API, then allow the user to edit and select a different user from the dropdown. 

`columns: [
        {
          title: 'Account Name',
          field: 'accountName',
          lookup: { 34: 'sample@123.com', 63: 'mytest@123.xom' }
        }
]`

**Comment by mbrn** [comment]
Hi @samazadi 

You can use editComponent feature. Please look at 3rd example.

**Comment by linoyco** [comment]
hii @mbrn @samazadi 
where is the 3rd example?

**Comment by charantej-kandukuri** [comment]
// Suppose you have the following array object from an end point:

```
const clients = [
    { id: 1, clientname: 'rohit', email: 'rohit@example.com'},
    { id: 2, clientname: 'mohan', email: 'mohan.kumar@example.com'}
]
```

// Now let us convert it to JavaScript Object with key and value pairs:

```
const clientOptions = {};
clients.map(client => {
    const { id, email } = client;
    clientOptions[ clientid ] = email
})
```
// Now look at the output by console.log(clientOptions) , we will get the following output:
// Output:
`{ 1 :  rohit@example.com, 2 : mohan.kumar@example.com }`

**Comment by aamirafridi** [comment]
> hii @mbrn @samazadi
> where is the 3rd example?

https://material-table.com/#/docs/features/editable

**Comment by MarMP** [comment]
I have  the same question

**Comment by MarMP** [comment]
if i do that @charantej-kandukuri the lookup is an empty field, why?

**Comment by saadqc** [comment]
instead of object, it would've been better if lookup object was an array of objects. Right now, there is no way to sort select filter entries.
