### ISSUE TITLE
Conditional Actions - styling (hidden?)

### ISSUE THREAD

**Issue by natalia-migas** [mbrn/material-table#609]
Hi, 
I would like to completely hide the action button, not only disable it (conditionally). 

![image](https://user-images.githubusercontent.com/25534910/58175341-38bc8000-7ca0-11e9-8199-686b4ef6785e.png)

In docs (https://material-table.com/#/docs/features/actions) is written 

> "You can set an action to disabled or change its color according to rowData", 

but there is no changing color example, so I don't know how could I do that. Maybe this could resolve my problem, by change styling to "display: none".

**Comment by mbrn** [comment]
Hi @natalia-migas ,

You can use display:none css but it is not a effective solution. I may apply a better solution something like disabled(hidden)

**Comment by mbrn** [comment]
This is done with version 1.38.0

**Comment by buszmen201** [comment]
Hey. Thanks for the great module. But I think conditional actions are still missing (so I don't know why it is closed). I found a workaround (since `disabled` prop of Action accepts only boolean (possibly types [TS] are not updated?). Maybe interface Action can accept any function which returns boolean? 
```typescript
export interface Action<RowData extends object> {
  disabled?: boolean | ((data: RowData | RowData[]) => boolean); // here
  icon: string | (() => React.ReactElement<any>);
  isFreeAction?: boolean;
  tooltip?: string;
  onClick: (event: any, data: RowData | RowData[]) => void;
  iconProps?: IconProps;
  hidden?: boolean;
}
```
But okay, here is my workaround

```jsx
<MaterialTable
  actions={[
    (rowData) => {
       return rowData.propToCheck 
         ? { icon: 'custom-icon', disable: true, onClick: (rowData) => { /* anythink */ } }
         : { icon: 'another-icon', disable: false, onClick: (rowData) => { /* anythink */ } }
    }
  ]}
/>

**Comment by ifndefdeadmau5** [comment]
@buszmen201 You saved my ass! thanks

**Comment by sanjeeviraj** [comment]
> Hey. Thanks for the great module. But I think conditional actions are still missing (so I don't know why it is closed). I found a workaround (since `disabled` prop of Action accepts only boolean (possibly types [TS] are not updated?). Maybe interface Action can accept any function which returns boolean?
> 
> ```ts
> export interface Action<RowData extends object> {
>   disabled?: boolean | ((data: RowData | RowData[]) => boolean); // here
>   icon: string | (() => React.ReactElement<any>);
>   isFreeAction?: boolean;
>   tooltip?: string;
>   onClick: (event: any, data: RowData | RowData[]) => void;
>   iconProps?: IconProps;
>   hidden?: boolean;
> }
> ```
> 
> But okay, here is my workaround
> 
> ```js-jsx
> <MaterialTable
>   actions={[
>     (rowData) => {
>        return rowData.propToCheck 
>          ? { icon: 'custom-icon', disable: true, onClick: (rowData) => { /* anythink */ } }
>          : { icon: 'another-icon', disable: false, onClick: (rowData) => { /* anythink */ } }
>     }
>   ]}
> />
> ```

`<MaterialTable
  actions={[
    (rowData) => {
       return rowData.propToCheck 
         ? { icon: 'custom-icon', disable: true, onClick: (event,rowData) => { /* anythink */ } }
         : { icon: 'another-icon', disable: false, onClick: (event,rowData) => { /* anythink */ } }
    }
  ]}
/>`

**Comment by sanjeeviraj** [comment]
> Hey. Thanks for the great module. But I think conditional actions are still missing (so I don't know why it is closed). I found a workaround (since `disabled` prop of Action accepts only boolean (possibly types [TS] are not updated?). Maybe interface Action can accept any function which returns boolean?
> 
> ```ts
> export interface Action<RowData extends object> {
>   disabled?: boolean | ((data: RowData | RowData[]) => boolean); // here
>   icon: string | (() => React.ReactElement<any>);
>   isFreeAction?: boolean;
>   tooltip?: string;
>   onClick: (event: any, data: RowData | RowData[]) => void;
>   iconProps?: IconProps;
>   hidden?: boolean;
> }
> ```
> 
> But okay, here is my workaround
> 
> ```js-jsx
> <MaterialTable
>   actions={[
>     (rowData) => {
>        return rowData.propToCheck 
>          ? { icon: 'custom-icon', disable: true, onClick: (rowData) => { /* anythink */ } }
>          : { icon: 'another-icon', disable: false, onClick: (rowData) => { /* anythink */ } }
>     }
>   ]}
> />
> ```

adding event param in onclick events
```
<MaterialTable
  actions={[
    (rowData) => {
       return rowData.propToCheck 
         ? { icon: 'custom-icon', disable: true, onClick: (event,rowData) => { /* anythink */ } }
         : { icon: 'another-icon', disable: false, onClick: (event,rowData) => { /* anythink */ } }
    }
  ]}
/>
```

**Comment by brayanL** [comment]
@buszmen201 your example works fine if you want to render one button conditionally, but what if you want to render two buttons conditionally or more?.
I was investigating, actions only allow one function, not multiples.
<img width="596" alt="Screen Shot 2020-09-09 at 14 31 28" src="https://user-images.githubusercontent.com/8359783/92644643-4c329680-f2a9-11ea-9a1a-f8c28ae17884.png">

**Comment by KannarFr** [comment]
This is not working when selection: true, correct?

**Comment by ifndefdeadmau5** [comment]
@KannarFr That's more of this issue #676 

and if you want to use both `actions as a function` and `selection: true` together this might help you https://github.com/mbrn/material-table/issues/676#issuecomment-634383844
