### ISSUE TITLE
Feature for advance selection

### ISSUE THREAD

**Issue by saikatstutorial** [mbrn/material-table#610]
**options prop properties needed**

`<MaterialTable columns={this.gridColumns} data={this.gridData} options={this.gridOptions} />`

To enable/disable selection checkbox at row level
`this.gridOptions.selectionAllowed = (row) => {}`

To pre-select selection checkbox (instead of manually manipulating tableData.checked) at row level
`this.gridOptions.selected = (row) => {}`

Combination of both should also work together like pre-selected and disabled. These options would be available only if `this.gridOptions.selection = true` is on.

**Comment by mbrn** [comment]
Hi @saikatstutorial ,

This is done. I added `selectionProps` to options. It will be in next release and documentation

https://material-table.com/#/docs/features/selection

**Comment by mbrn** [comment]
This is done with version 1.37.0
