### ISSUE TITLE
Using remote data, custom filter function is not invoked

### ISSUE THREAD

**Issue by JKrymarys** [mbrn/material-table#611]
**Describe the bug**
Custom filtering function is not working when table is getting remote data. 

**To Reproduce**
1. Create table with remote as source of data.
2. Add your own function eg. ` customFilterAndSearch: (term, rowData) => term == rowData.name.length`
3. Try to invoke this filter

**Expected behavior**
I expect function to work. Nothing is happening though. 

**Desktop (please complete the following information):**
- Chrome v74

**Comment by mbrn** [comment]
Hi @JKrymarys ,

This is normal. It expects filtering should work remotely. You should apply filters in data function.

**Comment by pan1982** [comment]
I need to filter remote data on Enter, which function can help me? Thank you.
