### ISSUE TITLE
Missing Icon on Group Header Chip

### ISSUE THREAD

**Issue by myang310** [mbrn/material-table#612]
Describe the bug
Chip used in Grouping Functionality is missing up and down arrow icon

To Reproduce
Add a column to drag and drop area.

I also set up the icons object that's passed to the prop:
```import {
  Add,
  ArrowDownward,
  ArrowUpward,
  Check,
  ChevronLeft,
  ChevronRight,
  Clear,
  Delete,
  Edit,
  FilterList,
  FirstPage,
  LastPage,
  Remove,
  SaveAlt,
  Search,
  ViewColumn,
} from '@material-ui/icons';

const materialTableIcons = {
  Add: Add,
  ArrowDownward: ArrowDownward,
  ArrowUpward: ArrowUpward,
  Check: Check,
  Clear: Clear,
  Delete: Delete,
  DetailPanel: ChevronRight,
  Edit: Edit,
  Export: SaveAlt,
  Filter: FilterList,
  FirstPage: FirstPage,
  LastPage: LastPage,
  NextPage: ChevronRight,
  PreviousPage: ChevronLeft,
  ResetSearch: Clear,
  Search: Search,
  ThirdStateCheck: Remove,
  ViewColumn: ViewColumn,
};
```

Expected behavior
Should see Chip with Arrow Upward icon.

Screenshots

![image](https://user-images.githubusercontent.com/9114821/58195702-9350de80-7c96-11e9-8066-e7207fd1c236.png)

**Comment by jamesg1** [comment]
Thanks for this post I didn't want to import all the icons via the link and I couldn't find an easy import statement in the docs.

**Comment by myang310** [comment]
unfortunately, I don't think that their docs include all the icons that they use (for example, arrow_upward)

**Comment by mbrn** [comment]
Hi @myang310 , @jamesg1 ,

I added to SortArrow to documention. You can override `SortArrow` to fix grouping icon problem.

https://material-table.com/#/docs/all-props

**Comment by jamesg1** [comment]
Thanks @mbrn I didn't see that as I'm using 1.3.0 due to using an older React version.
