### ISSUE TITLE
Selection box in FilterRow

### ISSUE THREAD

**Issue by priemd** [mbrn/material-table#613]
**Describe the bug**
Why is there a selection box in the filtering row?  Maybe I'm missing something but can't see any value in selecting the filter row.  I never noticed it but one of the first things that came up in front of my users today was 'why is there a selection box in the filtering row'.  Ticky-Tacky but users will be users.

**To Reproduce**
Open a table with filtering and selection enabled.

**Expected behavior**
No checkbox in filter row.
![Screen Shot 2019-05-22 at 10 36 55 PM](https://user-images.githubusercontent.com/2279532/58221884-24997280-7ce2-11e9-9efc-537e10862368.png)*Screenshots**
*Additional context**
I tried overriding EditRow setting selection={{Boolean(false}} but then all the valid filter cells just shifted out of place to the left:

![Screen Shot 2019-05-22 at 10 18 39 PM](https://user-images.githubusercontent.com/2279532/58221611-39293b00-7ce1-11e9-9d48-bec21565262c.png)
*

Also tried setting filterCellStyle to 'display: "none"' but that just remove all filter cells accept for the selection cell.

**Comment by mbrn** [comment]
Hi @priemd,

If you set lookup for column it will use select instead of a textfield. But if you want to use textfield you can use render function of column instead of giving a lookup. Please check custom render feature on documentation.

**Comment by priemd** [comment]
It’s not the actual filter component for columns I’m referring to... I’m wondering why there is a checkbox defaulted to display as the first column in the filter row as it doesn’t need to be there?  No easy way to override either besides copy and paste source minus the line that slices the columns and adds the checkbox

**Comment by AntoniusGolly** [comment]
![image](https://user-images.githubusercontent.com/3856505/60775273-d967e180-a120-11e9-8fe8-89ef1b56003e.png)
He is referring to this checkbox. I think bug label is actually correct.

**Comment by priemd** [comment]
@AntoniusGolly that is the correct 'select all' checkbox you have circled, what I was referring to has already been corrected.  The issue was referring to a checkbox being in the filter row below the header which was useless.  Issue should be closed just not sure what push fixed it, sorry.

**Comment by AntoniusGolly** [comment]
Alright. Thanks for correcting.

**Comment by priemd** [comment]
actually looking at my screenshot it was already fixed, must have been a late night ;)  I swear there was a checkbox at some point in the filter row.  If not my bad, must have been seeing double.
