### ISSUE TITLE
EditComponent: TextField onKeyPress close editable actions

### ISSUE THREAD

**Issue by kkomaz** [mbrn/material-table#616]
I have a custom textfield component that will make an update on the row based on enter press (key down).  Is there a way I can close the edit actions when I do?

```
          editComponent: inputProps => (
            <TextField
              onKeyPress={e => this.handleOnKeyPress(e, inputProps)}
            />
          )
        },
```

## handleOnKeyPress
```
handleOnKeyPress() {
  close the editable Options after async post/put update
}
```

**Comment by mbrn** [comment]
Hi @kkomaz 

You can call onEditingCanceled function of MT by using tableRef. Please check document. Look at 2nd example to usage of tableRef https://material-table.com/#/docs/features/remote-data
