### ISSUE TITLE
I see following warning when I render the page.

### ISSUE THREAD

**Issue by behrouz-s** [mbrn/material-table#617]
Warning: Failed prop type: Invalid prop `children` supplied to `TableCell`, expected a ReactNode.
    in TableCell (created by WithStyles(TableCell))
    in WithStyles(TableCell) (created by MTableCell)
    in MTableCell (created by MTableBodyRow)
    in tr (created by Context.Consumer)
    in TableRow (created by WithStyles(TableRow))
    in WithStyles(TableRow) (created by MTableBodyRow)
    in MTableBodyRow (created by MTableBody)
    in tbody (created by TableBody)
    in TableBody (created by WithStyles(TableBody))
    in WithStyles(TableBody) (created by MTableBody)
    in MTableBody (created by Droppable)
    in table (created by Table)
    in Table (created by WithStyles(Table))
    in WithStyles(Table) (created by Droppable)
    in div (created by Droppable)
    in div (created by Droppable)
    in Droppable (created by ConnectFunction)
    in ConnectFunction
    in ConnectFunction (created by MaterialTable)
    in div (created by ScrollBar)
    in ScrollBar (created by MaterialTable)
    in div (created by Paper)
    in Paper (created by WithStyles(Paper))
    in WithStyles(Paper) (created by MaterialTable)
    in Provider (created by App)
    in App (created by ErrorBoundary)
    in ErrorBoundary (created by DragDropContext)
    in DragDropContext (created by MaterialTable)
    in MaterialTable
    in Unknown (created by WithStyles(Component))
    in WithStyles(Component) (at File.js:153)
    in div (at File.js:120)
    in File (created by Context.Consumer)
    in Route (at Expense.js:20)
    in div (at Expense.js:17)
    in Expense (at ContentPage.js:16)
    in div (at ContentPage.js:15)
    in ContentPage (created by Context.Consumer)
    in Route (at App.js:40)
    in div (created by ForwardRef(Container))
    in ForwardRef(Container) (created by WithStyles(ForwardRef(Container)))
    in WithStyles(ForwardRef(Container)) (at App.js:39)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:22)
    in App (at src/index.js:6)

**Comment by mbrn** [comment]
Hi @behrouz-s ,

Can you specify the case to reproduce the case? Such as using grouping, filtering or etc.

**Comment by batjko** [comment]
I get this error as well, not on first render, but when the table re-renders due to the table rows changing (prop changing).

**Comment by IngenieroLata** [comment]
I found out this warning appears when the column is not able to find a value under `data` or is a boolean value. I end up using the render function to remove the warning. 

Wondering if the `emptyValue` should act as default placeholder on this cases.

**Comment by Domino987** [comment]
Can you reproduce that in a sandbox s owe can take a look at it?
