### ISSUE TITLE
How to specify DetailPanel column width?

### ISSUE THREAD

**Issue by behrouz-s** [mbrn/material-table#618]
Detail Panel's icon is shown in vertical alignment when number of column is more than 8.
![download](https://user-images.githubusercontent.com/1307397/58333792-e8335700-7e46-11e9-8e60-95ed8ec42f27.png)
![download (1)](https://user-images.githubusercontent.com/1307397/58334037-6132ae80-7e47-11e9-9ec9-0ec63d2b4fc9.png)

**Comment by mbrn** [comment]
This should be done with version 1.36.6

**Comment by behrouz-s** [comment]
The problem was fixed in mentioned version, but I have same problem in version 1.39.0!

**Comment by mbrn** [comment]
Let me take a look again.

**Comment by behrouz-s** [comment]
Would you please fix the problem, it could be seen in your documentation too.
![download (1)](https://user-images.githubusercontent.com/1307397/61156723-c0827600-a4fc-11e9-9c49-f55461a9bd13.png)
