### ISSUE TITLE
Styling with MuiThemeProvider does not work with @material-ui/core@4.0.0

### ISSUE THREAD

**Issue by timsazon** [mbrn/material-table#619]
**Describe the bug**
Table ignores styling with MuiThemeProvider on @material-ui/core@4.0.0.

**To Reproduce**
1. Install @material-ui/core@4.0.0
2. Add MuiThemeProvider with your theme
4. Nothing changes (default theme)

**Expected behavior**
Theme from MuiThemeProvider should be applied.

**Screenshots**
It can be checked out in [the docs example](https://material-table.com/#/docs/features/styling)

**Comment by mbrn** [comment]
I will upgrade it to MT 4.0 asap.

**Comment by mbrn** [comment]
Upgraded with version 1.37.0

**Comment by Neko250** [comment]
With `material-table@1.37.0`

I'm using `@material-ui/styles/ThemeProvider` instead of `@material-ui/core/styles/MuiThemeProvider`. This is my theme configuration:

```jsx
import { createMuiTheme, responsiveFontSizes } from '@material-ui/core/styles'
import blue from '@material-ui/core/colors/blue'
import { ThemeProvider } from '@material-ui/styles'

const theme = responsiveFontSizes(createMuiTheme({
  palette: {
    type: 'dark',
    primary: blue
  }
}))
```

But the table renders like this:

![chrome_MO0hoX3SNH](https://user-images.githubusercontent.com/2650578/58465397-823d1d00-812f-11e9-8b6b-668307bd242f.png)

**Comment by timsazon** [comment]
@Neko250 
It's looks like you have several instances of mui styles.
Try to reinstall node_modules or just run `npm dedupe` (see [duplicated module in node_modules](https://material-ui.com/getting-started/faq/#duplicated-module-in-node-modules)).

**Comment by Neko250** [comment]
> @Neko250
> It's looks like you have several instances of mui styles.
> Try to reinstall node_modules or just run `npm dedupe` (see [duplicated module in node_modules](https://material-ui.com/getting-started/faq/#duplicated-module-in-node-modules)).

It worked, thank you ! :tada:

**Comment by Lukashev** [comment]
@material-ui/core@4.0.1, same problem
