### ISSUE TITLE
Overriding Column Header

### ISSUE THREAD

**Issue by v1nns** [mbrn/material-table#623]
Is it possible to override Column Header? I want to override it in order to add an icon button above it. I checked the documentation, but only saw it's possible to override its style and not the component.

**Comment by mbrn** [comment]
Hi @v1nns 

You can override Header component but you should implement all header functionalities. But i can show you a trick: 

Look at first column
```javascript
columns: [
      { title: <div><Icon>save</Icon> Name</div> , field: 'name' },
      { title: 'Soyadı', field: 'surname', grouping: false }
    ]
```

> This workaround will cause a warning. But i wont close this issue and add React component to PropTypes to avoid warning.

**Comment by mbrn** [comment]
We already applied react element to title. You can use it in current version without warnings :)

**Comment by v1nns** [comment]
Hi @mbrn, that's a nice trick, it didn't even cross my mind. Well, thank you for your help!
