### ISSUE TITLE
Layout breaks in production build (create-react-app)

### ISSUE THREAD

**Issue by serg-kan** [mbrn/material-table#625]
**Describe the bug**
I use React 16.8.6, material-ui/core v4.0.1 and material-table v1.36.4. In production build, when I move to a page where material table is being used, all the markup breaks.
After multiple clicks between pages everything becomes ok. 
I thought that maybe it happens because of JSS classes

**To Reproduce**
1. Use create-react-app -> npm run build
2. Move to the page where material-table is being used
3. See broken layout

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/11990119/58477107-6ea7ab80-815b-11e9-9dad-91283b3db2e9.png) 

![image](https://user-images.githubusercontent.com/11990119/58477119-76ffe680-815b-11e9-9e36-3f3bb535b6ec.png)

![image](https://user-images.githubusercontent.com/11990119/58477136-80894e80-815b-11e9-890b-7d22694ad925.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 70

**Comment by mbrn** [comment]
To Remember: 

> @mbrn thank you, just installed 1.37.0 but the problem still exists. It happens only with a production build, when I use development server everythink is ok.
In production build after a couple of clicks the problem disappears

**Comment by lkameya** [comment]
I'm facing the same issue.
React 16.8.6 and Material-UI 4.0.1.

**Comment by mbrn** [comment]
Hi @serg-kan 

I tried this case but it works properly. 

I developed a page with appbar and table

My CRA:
"@material-ui/core": "^4.0.1",
"material-table": "^1.37.0",
"react": "^16.8.6",
"react-dom": "^16.8.6",
"react-scripts": "3.0.1"

**Comment by serg-kan** [comment]
@mbrn with these versions it worked, thank you.
I just changed "material-table": "1.37.0" to "material-table": "^1.37.0", can you please explain why does this changed the behavior?

**Comment by mbrn** [comment]
it may upgraded to 1.38.0 that i publish a few hours ago :)

**Comment by MohitKS5** [comment]
Just in case anyone stumbles here, it works only with exact set of versions as mentioned by @mbrn. Tried with  "material-table": "^1.39.0" failed, "material-table": "^1.37.0" failed , even altering material core version "@material-ui/core": "^3.9.x" fails !
