### ISSUE TITLE
Disable draggable column header

### ISSUE THREAD

**Issue by v1nns** [mbrn/material-table#626]
Hi @mbrn, I looked the documentation to disable drag'n'drop column header and only found the flag **column.grouping: false**, but had no effect because I'm not grouping any data. How do I disable the draggable feature in column header? I don't wanna permit to change the column order, otherwise it messes with my workaround to freeze a column.

**Comment by mbrn** [comment]
I can add a columnReordering flag to options for next release.

**Comment by v1nns** [comment]
Hey @mbrn, sup? Did you take a look at this?

**Comment by mbrn** [comment]
Hi @v1nns 

I am not at work and can not work at village. This is Feast of Ramadan days for muslims:). Thanks for patience

**Comment by v1nns** [comment]
Ooops, sorry @mbrn, I had no idea about that. I wish a happy Ramadan Feast to you.

**Comment by v1nns** [comment]
Up

**Comment by hrafaelveloso** [comment]
I think the  #753 solution is what we want for disable the drag header functionality. Can you please merge that @mbrn ? That's a simple opt-out that people could use :)

**Comment by hrafaelveloso** [comment]
Hi @mbrn , I think the #779  solution is what we are looking. That's a simple opt-out and I'm looking forward for that feature.

**Comment by coltanium13** [comment]
hi @mbrn , is there a way to prevent one column from being re ordered when dragging and dropping the headers? I want my first column to always stay in the first position, but the rest of the columns can be moved around. I did not see a column flag property to prevent it from being dragged. Thank you!

**Comment by jason-zeiler-bayer** [comment]
looking for this option as well
