### ISSUE TITLE
Trigger table with defaultFilter and remote data source

### ISSUE THREAD

**Issue by DaveBathnes** [mbrn/material-table#627]
Hello, 

Firstly, great table library! This is saving me a lot of time.

I'm having trouble with the following scenario:

1. In my application I use a remote data source and so have configured remote data as per documentation. I have an API that handles all the filtering/sorting etc.
2. I am using table filters with a few columns acting as drop down filters (using lookup values)
3. I would like to trigger the table with differing filter values. This data will come down using props.
4. I do it like this:

```
{
	title: 'Mobile',
	field: 'mobile_id',
	defaultFilter: this.props.mobile_filter,
	lookup: mobileText,
	filtering: true
},
```

What I pass down through props is an array with the ID e.g. [1].  It seems to work, except the table does not filter properly. The drop down has the right value selected, but the data is not filtered. 

Do you know what's going wrong? Is the default filter being applied after the initial remote data call?

**Comment by mbrn** [comment]
It should call you data function with initialFilter values. You should filter data on your remote data source. Can you check it please?

**Comment by DaveBathnes** [comment]
Hi, thank you.

Yes, my data function is fine. It works on filtering except in the case when the defaultFilter is supplied.

The filters array is empty when I pass a defaultFilter to the table.

**Comment by mbrn** [comment]
It might be a bug. I will check it.

**Comment by mbrn** [comment]
This is done with version 1.38.0

**Comment by DaveBathnes** [comment]
Excellent, thank you. Tested, and all is working.
