### ISSUE TITLE
Including material-table overrides material-ui theme

### ISSUE THREAD

**Issue by sickyoon** [mbrn/material-table#628]
**Describe the bug**

material-table loads default material-ui styles again overriding theme styles.

**To Reproduce**

1. Create MUI theme and change `theme.typography.fontFamily`
2. Load theme using `MuiThemeProvider`
3. Create React page and ensure theme is applied
4. Create React page with `MaterialTable`
5. Look at developer tools to find typography styles have been overriden.

**Expected behavior**

Should not have duplicated material-ui style elements after including `MaterialTable`

**Screenshots**

<img width="367" alt="Screen Shot 2019-05-28 at 6 24 41 PM" src="https://user-images.githubusercontent.com/24367477/58516420-e2ef4880-8175-11e9-96d9-6a8a895b7eeb.png">

<img width="472" alt="Screen Shot 2019-05-28 at 6 25 37 PM" src="https://user-images.githubusercontent.com/24367477/58516725-f949d400-8176-11e9-9b29-240f98a89628.png">

**Environment**

```
npx create-react-app my-app --typescript
```

```
"@material-ui/core": "^4.0.0",
"material-table": "^1.37.0",
```

**Comment by mbrn** [comment]
I tested this but i think this is not MT related case. When you use a muithemeprovider it adds styles of every component that used inside. 

This is normal you will see two MuiTypography styles. 

```javascript
 <>
        <Typography>Text1</Typography>
        <MuiThemeProvider theme={theme}>
          <Typography>Text2</Typography>
        </MuiThemeProvide>
</>
```

**Comment by zumdahl76** [comment]
I have the same issue i'm trying to figure out. when i add the <MaterialTable> tag in my page, the whole material-ui theme changes. It's the only module that does that. I'll let you know if i find how to fix it. Thanks.

**Comment by mbrn** [comment]
I will take a look again.

**Comment by Clem-** [comment]
I'm having the same problem.
After the module is loaded, the MaterialUI theme (eg. button styles) is broken.

PS: I'm using NextJS

**Comment by WillemLabu** [comment]
I can confirm this happens with `.MuiButtonBase-root` too.

Is there a way to make your styles more specific at all?

**Comment by bilel-noomene** [comment]
+1

**Comment by ahomatthew** [comment]
+1

**Comment by ahomatthew** [comment]
I had to go back to 1.36.0 to get it to stop behaving this way.

**Comment by jtesch** [comment]
I am having this issue as well. In my case it affected Button styles and Textfield's select options. Both utilized `.MuiButtonBase-root`.
Downgrading to 1.36 fixed the issue.

**Comment by wolfdgreat** [comment]
was this fixed? I used 1.57 and having the same issue.

**Comment by m3h0w** [comment]
Same problem here. Other components' using material UI style is changing when I include the material-table.

**Comment by bishoym** [comment]
Issue is persistent on 1.69

**Comment by nsdonato** [comment]
Issue is persistent on 1.69.3

**Comment by matiquec** [comment]
Issue is persistent on 1.69.3 I had to go back to 1.32.0

**Comment by adrianskogvold** [comment]
Added this to the top of my ThemeProvider in my application as a workaround to prevent the classnames to clash.

```
import { unstable_ClassNameGenerator as ClassNameGenerator } from '@mui/material/className';

ClassNameGenerator.configure((componentName) => `randomPrefix-${componentName}`);
```
