### ISSUE TITLE
Select All Checkbox Spacing

### ISSUE THREAD

**Issue by CoolCyberBrain** [mbrn/material-table#629]
The select all checkbox seems to have the wrong margins in mui v4

<img width="986" alt="Screen Shot 2019-05-28 at 22 00 29" src="https://user-images.githubusercontent.com/8357970/58530582-0b863b00-8194-11e9-8df5-c475a7abce14.png">

**Comment by mbrn** [comment]
I saw them. I will take a look asap.

**Comment by CoolCyberBrain** [comment]
temporary fix:
```
<MaterialTable
    title=""
    columns={this.columns}
    data={this.data}
    options={{
        selectionProps: { style: {} }
     }}
 />
```

**Comment by mbrn** [comment]
This is done with version 1.39.0
