### ISSUE TITLE
Redux with Remote Data

### ISSUE THREAD

**Issue by ismaildervisoglu** [mbrn/material-table#630]
I'm pulling data into the table using redux. It works seamlessly when I send the data directly without paging, but it does not
  {
data: // your data array
  page: // current page number
  totalCount: // total page number
}
I get an error when I try to send it this way.

**Comment by mbrn** [comment]
Hi @ismaildervisoglu 

Can you share your table usage code, please?

**Comment by ismaildervisoglu** [comment]
Table Code:
```
<MaterialTable
            columns={columnss}
            icons={{
              Check: () => <Check />,
              Export: () => <SaveAlt />,
              Filter: () => <FilterList />,
              FirstPage: () => <FirstPage />,
              LastPage: () => <LastPage />,
              NextPage: () => <ChevronRight />,
              PreviousPage: () => <ChevronLeft />,
              Search: () => <Search />,
              ThirdStateCheck: () => <Remove />,
              ViewColumn: () => <ViewColumn />,
              DetailPanel: () => <ChevronRight />,
            }}
            data={data}
            options={{
              search: false,
              selection: true,
              toolbar: false,
              showTitle: false,
              headerStyle: { padding: '4px 8px 4px 8px' },
              paginationType: 'stepped',
            }}
            components={{
              Cell: props => (
                <MTableCell {...props} style={{ padding: '4px 8px 4px 8px' }} />
              ),
            }}
            onSelectionChange={(rows) => { this.changeSelection(rows); }}
            onChangeRowsPerPage={(value) => this.onChangeRowsPerPage(value)}
            onChangePage={(page) => this.onChangePage(page)}
          />
```

Reduce code:

```
import {
  RECEIVE_STUDENT_LIST_TABLE_DATA,
  REQUEST_STUDENT_LIST_TABLE_DATA,
} from '../actions/studentListTableAction';

const initialState = {
  userListTableData: [],
  userListTableDataLoading: false,
};

export default function (state = initialState, action) {
  switch (action.type) {
    case REQUEST_STUDENT_LIST_TABLE_DATA: {
      return Object.assign({}, state, {
        userListTableDataLoading: true,
      });
    }
    case RECEIVE_STUDENT_LIST_TABLE_DATA: {
      return Object.assign({}, state, {
        userListTableData: {
          data: action.data.resultContainer,
          page: 2,
          totalCount: 100,
        },
      });
    }
    default:
      return state;
  }
}
```

**Comment by mbrn** [comment]
What is data that you set to MT?

Actually MT does not care you retrieve data from redux store or state.

**Comment by ismaildervisoglu** [comment]
userListTableData: {
          data: action.data.resultContainer,
          page: 2,
          totalCount: 100,
        },

**Comment by mbrn** [comment]
you should give a data array or function that returns a promise. This is not proper way to give data to MT. 

Use 
data={userListTableData.data}
or
data={query =>
        new Promise((resolve, reject) => {
            resolve(userListTableData
        })
}

**Comment by ismaildervisoglu** [comment]
Ok. When I give data this way data={userListTableData.data} retrieves the data, but does not get page and totalCount

**Comment by mbrn** [comment]
Yes. This means MT will manage pagination.

**Comment by ismaildervisoglu** [comment]
but when I can't get totalCount or page i cannot print the size of the data 16-20 of **TotalCount**

**Comment by mbrn** [comment]
You must set totalCount. Pagination works according to totalCount

**Comment by ismaildervisoglu** [comment]
I'm trying to ask you that. How should I give totalCount? I give an error when I give the object I sent to the data in previous messages.

**Comment by mbrn** [comment]
data={query =>
new Promise((resolve, reject) => {
resolve({
  data: // your data array
  page: // current page number
  totalCount: // total page number
})
}

**Comment by ismaildervisoglu** [comment]
When I give data like this: 
```
data={query => new Promise((resolve, reject) => {
            resolve({
              data: userListTableData.data,
              page: userListTableData.page,
              totalCount: userListTableData.totalCount,
            });
          })
          }
```
It gives an ERROR:

Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `MaterialTable`.

**Comment by mbrn** [comment]
This is not data related error. Please check your imports

**Comment by ismaildervisoglu** [comment]
I found the error MTableCell import give an error. It works when I delete it. How should I import?
import MaterialTable, { MTableCell } from 'material-table';

**Comment by mbrn** [comment]
Please check data in console. It should work.

**Comment by ismaildervisoglu** [comment]
I checked the data coming right. But there is a continuous circularprogrees icon in the table.

**Comment by mbrn** [comment]
Sorry @ismaildervisoglu ,

I could not help you without code. Please check examples in documentation

**Comment by ismaildervisoglu** [comment]
Table Container:

```
<Table
          actionArchieve={this.archieveStudent}
          actionEdit={this.editStudent}
          changeSelection={this.tableSelection}
          addArchivedButtonBool
          data={userListTableData}
          actionColumnEducationCareerBool
          columns={t('students.students.student_list_table_columns', { returnObjects: true })}
          changeRowsPerPage={this.changeRowsPerPage}
          changePage={this.changePage}
        />
```

Table Component:
 ```
<MaterialTable
            columns={columnss}
            isLoading={false}
            icons={{
              Check: () => <Check />,
              Export: () => <SaveAlt />,
              Filter: () => <FilterList />,
              FirstPage: () => <FirstPage />,
              LastPage: () => <LastPage />,
              NextPage: () => <ChevronRight />,
              PreviousPage: () => <ChevronLeft />,
              Search: () => <Search />,
              ThirdStateCheck: () => <Remove />,
              ViewColumn: () => <ViewColumn />,
              DetailPanel: () => <ChevronRight />,
            }}
            data={query => new Promise((resolve, reject) => {
              resolve({
                data: data.data,
                page: data.page,
                totalCount: data.totalCount,
              });
            })
            }
            options={{
              search: false,
              selection: true,
              toolbar: false,
              showTitle: false,
              headerStyle: { padding: '4px 8px 4px 8px' },
              paginationType: 'stepped',
            }}
            onSelectionChange={(rows) => { this.changeSelection(rows); }}
            onChangeRowsPerPage={(value) => this.onChangeRowsPerPage(value)}
            onChangePage={(page) => this.onChangePage(page)}
          />
```

**Comment by mbrn** [comment]
If you use remote data feature and change data manually, you should call onQueryChange function of table manually after data changes. Please check documentation examples of remote data feature. It has an example of tableRef usage.

**Comment by paillave** [comment]
I understand the solution, but it is far to be simple. I believe that given the fact that redux is one of the most recommended architecture for react, the paging feature should be more "redux friendly". Actually the problem is exactly the same regarding to the editable feature that is 100% not "redux friendly". I can take care of this improvement if you want.

**Comment by mbrn** [comment]
Hi @paillave 

Any contribution is apprepriatable:). MT is controlled component for paging. If you want to make it uncontrolled you can override the paging component.

**Comment by lfernando-silva** [comment]
I made a trick to handle pagination handling the TablePagination component, but just for a temporary solution. As @paillave said, is not really redux-friendly

```
                   data={props.data} 
                   components={{
                        Pagination: (componentProps) => <TablePagination
                            {...componentProps}
                            count={response.count}
                            page={page}
                            rowsPerPage={skip}
                            onChangePage={(evt, page) => {
                                let nextPage = page + 1
                                this.setState({page: nextPage})
                                props.doList({ order: 'created_at,DESC', limit: 10, offset: nextPage * skip })
                            }}
                        />
                    }}
```

**Comment by paillave** [comment]
As this may be the best material grid, I am trying to work on it to make it more redux friendly.

**Comment by Monfernape** [comment]
@paillave any updates on this?

**Comment by raikusy** [comment]
Can anyone provide a good example for using MT with redux remote data? Me along many other people having trouble with that.

**Comment by sebaranowski** [comment]
Luckily my response header contains `x-total-count` which allows me to do this (dont like it but it works):

```ts
const getData = (query): Promise<QueryResult<ITodo>> => {
    return new Promise((resolve, reject) => {
      Promise.resolve(props.getEntities(query.page, query.pageSize)).then((data) => {
        const temp: IResponseData<ITodo> = data as unknown as IResponseData<ITodo>; // hmm..
        const axRes: AxiosResponse = temp.value;
        const totalCount = Number(axRes.headers['x-total-count']);

        resolve({
          data: axRes.data,
          page: query.page,
          totalCount,
        });
      });
    });
  };
```
```ts
 <MaterialTable
        title=""
        data={getData}
        columns={[
          ...
```

**Comment by cuiziang** [comment]
Here is mine:
```javascript
                        data={async query => {
                            await dispatch(fetchItems(query));
                            return (
                                {
                                    data: items.items.map(r => ({ ...r })),
                                    page: query.page,
                                    totalCount: items.totalCount
                                }
                            )
                        }
                        }
```

**Comment by matiaslato** [comment]
in other pro

> Try mine with Redux and hook base on @sebaranowski.
> 
> It works for me.
> 
> ```js
>  const getData = query => {
>         return new Promise((resolve, reject) => {
>             Promise.resolve(dispatch(fetchAllItems(query))
>                 .then((data) => {
>                     const TableData = data.payload.items.map(r => ({ ...r }))
>                     const totalCount = data.payload.totalCount; // Or from x-total-count in header
> 
>                     resolve({
>                         data: TableData,
>                         page: query.page,
>                         totalCount,
>                     });
>                 }))
>         });
>     };
> ```

in other proyect I use this with thunk buttttt with sagas? i cant find a way

**Comment by francisngo** [comment]
@mbrn 

> If you use remote data feature and change data manually, you should call onQueryChange function of table manually after data changes. Please check documentation examples of remote data feature. It has an example of tableRef usage.

Can you show where in documentation? I only see it being used as an action button but not onChangePage

**Comment by alam7860** [comment]
plz tell me about pegination in material table  with firebase database (remote data) in react-hook redux
