### ISSUE TITLE
Issue after upgrade to  1.37.0 or 1.38.0 

### ISSUE THREAD

**Issue by JKrymarys** [mbrn/material-table#632]
**Describe the bug**
After upgrade to  1.37.0 or 1.38.0 there is a error:  

`
TypeError: Object(...) is not a function
Module../node_modules/@material-ui/pickers/dist/material-ui-pickers.esm.js `

other dependencies in project:

    "@material-ui/core": "3.9.3",
    "@material-ui/icons": "3.0.2",
    "axios": "0.18.0",
    "classnames": "2.2.6",
    "http-proxy-middleware": "0.19.1",
    "material-table": "1.36.6",
    "react": "^16.8.6",
    "react-datepicker": "2.4.0",
    "react-dom": "16.8.6",
    "react-dropzone": "10.1.3",
    "react-redux": "7.0.2",
    "react-router-dom": "5.0.0",
    "react-scripts": "2.1.8",
    "react-spinners": "0.5.4",
    "redux": "4.0.1",
    "redux-thunk": "2.3.0",
    "uuid": "3.3.2"

*Note*
I checked if this not an issue with other dependency. After problem occurred for the first time I recovered last verstion, removed all updates from package.json and started to upgrade dependencies one by one.

**Comment by mbrn** [comment]
Can you upgrade @material-ui/core and @material-ui/icons to 4.0.1 please

**Comment by JKrymarys** [comment]
Is this really necessary? I'd like to avoid this until material-ui v4 will be stable enough

**Comment by mbrn** [comment]
Actually i resolved same issue with mui 4.0.1. But you are already using MT@1.36.6. It should not require mui4.

**Comment by JKrymarys** [comment]
I agree, but I want to upgrade MT to latest version :) Leaving it at 1.36.6 is just a temp fix.

**Comment by mbrn** [comment]
No pain, no gain @JKrymarys :)

**Comment by kwhitley** [comment]
Given that `material-ui` v4 is not 100% backwards compatible with some build chains (including my own), this potentially breaking dep update really classifies this as more of a major version of `material-table`, sadly

**Comment by kwhitley** [comment]
I found this out today during a demo when an automatic `material-table` bump from `1.36.xx` to `1.38.xx` caused a runtime error in my build (it all stems from the use of "process" in `material-ui` v4, and `fuse-box` build chain mangling that in their own v3)

**Comment by mbrn** [comment]
You are right at this case. Do you think that should I change version as 2.0.0 ?

**Comment by tudro** [comment]
Is it possible to remove `material-ui v4` from v1.x and put it on v2.x? I have so many errors because many libs don't work ok with `material-ui v4`. Thank you

**Comment by mbrn** [comment]
I will set version number as 2.0.0 after a few developments. So this problem will be resolved.

**Comment by sshaw** [comment]
It's not clear what versions are compatible with Material UI 3.X. The current version of this library is 1.54.1 which has a Material UI peer dependency of 4.X

Seems that the whole v2 thing never materialized. It'd be good to know what version to use with Material UI 3.X.
