### ISSUE TITLE
Empty table with input cells

### ISSUE THREAD

**Issue by iaaltojarvi** [mbrn/material-table#634]
Hi,

I am trying to make a table that contains no data (empty table) before the user inputs the data needed. Is that possible with material table? Couldn't figure that out in docs.

**Comment by tudro** [comment]
Hello, 

Just set `data` empty. Take the `Simple action example` from [here](https://material-table.com/#/docs/features/actions). If you set ```data={[]}``` then you get a table with no data. You can translate the *No records to display* using the `localization` object, check [here](https://material-table.com/#/docs/all-props).

**Comment by iaaltojarvi** [comment]
Thanks a lot!
