### ISSUE TITLE
Adding a custom render function to the Search icon causes two warnings in the console

### ISSUE THREAD

**Issue by Flixbox** [mbrn/material-table#636]
**Describe the bug**
If I add a custom render function to the "Search" icon prop, two warnings will appear in the console.

**To Reproduce**

https://codesandbox.io/embed/blissful-sky-8w5th

**Expected behavior**
The console stays clear of errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/14835021/58565468-17730b00-822f-11e9-9eec-9b4a0a5deb04.png)

**Desktop (please complete the following information):**
 - OS: any
 - Browser any

**Comment by mbrn** [comment]
Hi @Flixbox ,

Thanks for clear issue. I will take a look at this asap.

**Comment by mbrn** [comment]
@Flixbox,

This is not a bug. Actually React.forwardRef required after mui4.0.0 upgrade. So if you change you icon usage like this it will be resolved:

icons={{
      Search: React.forwardRef((props, ref) => <div ref={ref}>SRC</div>)
}}

**Comment by rnacken** [comment]
@mbrn I know this is not a bug, and the issue is closed - but I ran into this and could not fix it with your proposed solution. So I figured it may be valuable to give more detail on your fix.
I tried this (typescript):
```
import { Search } from '@material-ui/icons';

const SearchWithRef = React.forwardRef<SVGSVGElement, {}>((props, ref) => (
      <Search ref={ref} {...props} />
));

...

icons={{
     Search: () => <SearchWithRef />,
}}
```
But the error still shows up. Any idea what I did wrong? I thought this is your solution.

**Comment by mbrn** [comment]
Can you try this: 

```javascript
import { Search } from '@material-ui/icons';

icons={{
     Search: React.forwardRef<SVGSVGElement, {}>((props, ref) => (
      <Search ref={ref} {...props} />
)),
}}
```
