### ISSUE TITLE
Unusable checkbox header with filter and selection options true.

### ISSUE THREAD

**Issue by waisbek** [mbrn/material-table#639]
**Describe the bug**
Using the table options:
```
selection: true
filtering: true
```
A checkbox without function appears in the filter row, is it possible remove it?

**Expected behavior**
I expect use the filtering and selection options without the "extra" checkbox in the filter row.

**Screenshots**
Attached screenshot
![image](https://user-images.githubusercontent.com/8702612/58574320-9cfab900-8237-11e9-9bdc-6a25dfff2163.png)

**Comment by mbrn** [comment]
I agree with you:). At least someone thinks like me:). I will remove it asap.

**Comment by mbrn** [comment]
This is done with version 1.39.0

**Comment by waisbek** [comment]
Thanks!
