### ISSUE TITLE
Formatting issue after 1.39.0

### ISSUE THREAD

**Issue by jakeleventhal** [mbrn/material-table#641]
**Describe the bug**
1.39.0 causes actions to be formatted improperly

**To Reproduce**
Look at second example on the documentation for detail expansion panel

**Expected behavior**
The actions should not go to a new line

**Screenshots**
![Screen Shot 2019-05-30 at 8 43 43 AM](https://user-images.githubusercontent.com/15133828/58633694-31f0c700-82b7-11e9-86f9-b4164562d8e4.png)

**Desktop (please complete the following information):**
 - OS: OS X 10.14.5
 - Browser: Chrome
 - Version: 74.0.3729.169

**Comment by waisbek** [comment]
I also can´t change the style using MuiThemeProvider after update to 1.39.0

**Comment by mariolazzari** [comment]
Is it possible to specify the detail panel width, in order to avoid new lines in details panel actions? Thanks!

**Comment by waisbek** [comment]
Please, forget my comment, now it's working perfectly!
