### ISSUE TITLE
Is there a way disable circular progress

### ISSUE THREAD

**Issue by ismaildervisoglu** [mbrn/material-table#642]
I'm using remote data. When the table is empty, progress icon is released. Is there a way to disable this?

**Comment by mbrn** [comment]
When you resolve or reject promise progress will be disappeared.

**Comment by ismaildervisoglu** [comment]
At first the data is empty, if the user is filtering, I access the data. How do I prevent the progress icon from appearing at first when this data is empty for this scenario?

**Comment by mbrn** [comment]
Just call reject for first call of data function. You can track your first call with an flag or counter.

**Comment by ismaildervisoglu** [comment]
I've tried like this but did not work
query => new Promise((resolve, reject) => {
  reject('Promise failed');
})

**Comment by mbrn** [comment]
It should work. Can you create a sandbox please?

**Comment by hbinkle** [comment]
I have the same problem, endless loading/spinning when trying to use remote data:
https://codesandbox.io/s/material-demo-yvqym?fontsize=14&hidenavigation=1&theme=dark
