### ISSUE TITLE
Setting the size of the table

### ISSUE THREAD

**Issue by Jak3b0** [mbrn/material-table#643]
Hi,

I just upgraded to Material-UI v4 and there is now a `size` property on a `Table` that allows us to change it from `medium` to `small`. This property seems to be missing from `MaterialTable`. Is there a way to set it on the underlying `Table`? 

This is causing me some issues since we are using both `Table` and `MaterialTable` and the padding are not the same anymore.

Thank you!

**Comment by mbrn** [comment]
I can add this property to MT.

**Comment by Jak3b0** [comment]
Thank you!

**Comment by stevepopovich** [comment]
Is there an easy way to get the same effect right now?

**Comment by dnknitro** [comment]
Are there any updates on this issue?

**Comment by LeanderCoevoet** [comment]
+1
