### ISSUE TITLE
Fonts doesnt working and material table breaking the whole element style

### ISSUE THREAD

**Issue by syahidnurrohim** [mbrn/material-table#644]
**Describe the bug**
After material table installed and used on a component, it'll break the material-ui style and the fonts is no working, i use material table 1.39.0.

All of the actions is working fine as i expected, but the style of the page is become so weird, transition doesnt works, drawer nav is flexed, top bar background color become white, and many more
Material UI ver 4.0..1

**Screenshots**
![Err2](https://user-images.githubusercontent.com/33978311/58644081-bf213380-832a-11e9-9aef-ad4cbd55e477.png)
![Err](https://user-images.githubusercontent.com/33978311/58643599-c72ca380-8329-11e9-91eb-0297a258102b.png)
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by syahidnurrohim** [comment]
But all the actions is working as i expected

**Comment by syahidnurrohim** [comment]
Material UI version 4.0.1
React version 16.8.6

**Comment by hinsxd** [comment]
Same problem here. Tried in the fresh environment with only material-table installed, renders <MaterialTable /> and same result.

**Comment by syahidnurrohim** [comment]
wow thanks but thats just worked for the icons not for the styles didnt

**Comment by syahidnurrohim** [comment]
i think the styles problem is resolved by making css to `!important`

**Comment by syahidnurrohim** [comment]
i think the styles problem is resolved by making css to `!important`
im going to close this issue right now

**Comment by fullmoon6661** [comment]
What do you have on your "./styles.css" if I may ask. I have similar problem where my material List lay horizontal when I mount material-table

**Comment by mbrn** [comment]
Hi @fullmoon6661 ,

It seems there is a problem with MT and mui4.0 styles. I will resolve this problem asap. Thanks.
