### ISSUE TITLE
[Docs & Types] Importing icons from @material-ui/icons in TypeScript 

### ISSUE THREAD

**Issue by hinsxd** [mbrn/material-table#647]
Importing icons with the way mentioned in tutorial will raise type errors.

```typescript
import { Icons } from 'material-table';
const tableIcons: Icons = {
  Add: AddBox,
  Check: Check,
  Clear: Clear,
  Delete: DeleteOutline,
  DetailPanel: ChevronRight,
  Edit: Edit,
  Export: SaveAlt,
  Filter: FilterList,
  FirstPage: FirstPage,
  LastPage: LastPage,
  NextPage: ChevronRight,
  PreviousPage: ChevronLeft,
  ResetSearch: Clear,
  Search: Search,
  SortArrow: ArrowUpward,
  ThirdStateCheck: Remove,
  ViewColumn: ViewColumn
};
// Type 'ComponentType<SvgIconProps>' is not assignable to type '(() => ReactElement<any, string ...
```

The correct way should be 
```typescript
const tableIcons: Icons = {
  Add: () => <AddBox />,
  Check: () => <Check />,
  Clear: () => <Clear />,
  Delete: () => <DeleteOutline />,
  DetailPanel: () => <ChevronRight />,
  Edit: () => <Edit />,
  Export: () => <SaveAlt />,
  Filter: () => <FilterList />,
  FirstPage: () => <FirstPage />,
  LastPage: () => <LastPage />,
  NextPage: () => <ChevronRight />,
  PreviousPage: () => <ChevronLeft />,
  ResetSearch: () => <Clear />,
  Search: () => <Search />,
  SortArrow: () => <ArrowUpward />,
  ThirdStateCheck: () => <Remove />,
  ViewColumn: () => <ViewColumn />
};
```

It seems that the type of icons are declared as `Add?: () => React.ReactElement<any>;`, which forces imports to be arrow functions, but the icons are exported from @material-ui/icons as `React.ComponentType<SvgIconProps>`

**Comment by mbrn** [comment]
I can change them React.Type. Thanks.

**Comment by robinlarsson** [comment]
I am also using TypeScript and been struggling with the icons. I have the same solution as @hinsxd and get issues with tooltip:

`Warning: Failed prop type: Invalid prop `children` supplied to `Tooltip`. Expected an element that can hold a ref. Did you accidentally use a plain function component for an element instead? For more information see https://material-ui.com/guides/composition/#caveat-with-refs`

**Comment by argentinaluiz** [comment]
@robinlarsson Me too

**Comment by tony-molumby** [comment]
@mbrn any update on this issue?  I am having the same problem as @robinlarsson and @argentinaluiz.  The only two icons which throw the error are the Filter and Search Icons:

    const icons = {
      Filter: props => <FilterList {...props} />,
      Search: props => <Search {...props} />
    }

> I am also using TypeScript and been struggling with the icons. I have the same solution as @hinsxd and get issues with tooltip:
> 
> `Warning: Failed prop type: Invalid prop `children`supplied to`Tooltip`. Expected an element that can hold a ref. Did you accidentally use a plain function component for an element instead? For more information see https://material-ui.com/guides/composition/#caveat-with-refs`

**Comment by thedanielfactor** [comment]
I would like to know if there is any resolution on this.  We are trying to use the same thing with TypeScript.

**Comment by richardmcconnell12** [comment]
I have imported the Icons correctly, and added them according to "Correct way it should be" but receiving an error that reads ```Generic type 'MaterialTable<RowData>' requires 1 type argument(s).```

**Comment by sunpar** [comment]
I got this working by declaring like this: 

`import ShowChartIconOutlined from '@material-ui/icons/ShowChartOutlined';
import { SvgIconProps } from '@material-ui/core';

type Menu = {
  id: number;
  icon: (props: SvgIconProps) => JSX.Element;
  label: string;
}[];

const NavBarMenus: Menu = [
  {
    id: 1,
    icon: ShowChartIconOutlined,
    label: 'Dashboard',
  },
...
];`

**Comment by bargar** [comment]
See [this comment](https://github.com/mbrn/material-table/issues/1004#issuecomment-525274793) in related issue mbrn/material-table#1004 for a workaround.

**Comment by Domino987** [comment]
Closing due to updated docs.
