### ISSUE TITLE
Missing field searchPlaceholder in localization prop (TypeScript)

### ISSUE THREAD

**Issue by juanpablolc** [mbrn/material-table#649]
**Describe the bug**
The localization prop does not have the type for the searchPlaceholder field.

**To Reproduce**
1. Add the field searchPlaceholder to the localization prop.

**Expected behavior**
The localization prop of the MaterialTable accepts the searchPlaceholder field.

**Screenshots**
![image](https://user-images.githubusercontent.com/32797043/58666092-0d690f00-82f8-11e9-8858-b3fc69f5d740.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 74

**Comment by MarcelMitzkus** [comment]
After updating the component to the neweset version, my localization is broken because of "searchPlaceHolder".

**Comment by mbrn** [comment]
This is published with 1.39.1
