### ISSUE TITLE
Never editable field with lookup renders key instead of value

### ISSUE THREAD

**Issue by Daniel-Yonkov** [mbrn/material-table#650]
**Describe the bug**
Having the following configuration for a column:
``` 
this.columns = [ 
  {
    title: "Company Name",
    field: "company",
    lookup: companyLookup,
    editable: "never"
  }
]
```
Upon trying to edit the row, I get the key instead of the lookup value.

**To Reproduce**
1. Create columns definition with lookup with hook for `editable` not allowing edit. 
2. Click on the Edit row button
3. Value displayed is the **key** instead of the **value**.

**Expected behavior**
Expecting the `editComponent` to render the **value** of the `lookup` configuration rather than **key**

**Screenshots**
- Before edit:
![image](https://user-images.githubusercontent.com/21025190/58717684-74f48c80-83d4-11e9-9487-95bc3dcb8aaf.png)
- On Edit:
![image](https://user-images.githubusercontent.com/21025190/58717737-95244b80-83d4-11e9-8bf9-f67f417cd22b.png)

**Desktop (please complete the following information):**
 - OS: Ubutu 14.04 (vagrant machine - ubuntu/trusty64)
 - Browser - Firefox
 - Version 66.0.3

**Additional context**
Workaround I have figured out:
1. Add editable hook for `onEdit` or for all actions
2. Add custom `editComponent` with the following definition: 
```
editComponent: props => (
	<span>{props.columnDef.lookup[props.value]}</span>
)
```

**Comment by mbrn** [comment]
This is done with 1.39.2

**Comment by Daniel-Yonkov** [comment]
> This is done with 1.39.2

@mbrn - Thanks for the fix!
