### ISSUE TITLE
Option for "add" to have a floating action button at the bottom right instead of at the to right

### ISSUE THREAD

**Issue by paillave** [mbrn/material-table#654]
**Is your feature request related to a problem? Please describe.**
We try to have our application following standards of Material UI, and it seems that the "add" button when the grid is in edit mode is not like most of typical material UI screens.

**Describe the solution you'd like**
What would make it consistent with most common screens with an "add" button would be a floating action button (Fab) at the bottom right like represented here: https://material-ui.com/components/buttons/#floating-action-buttons
If such a change is done as is:
* I believe that current users of the grid might complain that it changed compared to before. 
* I also believe some other users would complain that the button overlaps the grid

Therefore there should be an option to permit the developer to choose whether this button appears like it used to appear: at the top right on the header bar, or as a typical material UI floating action button at the bottom right.

**Comment by paillave** [comment]
I can take care of the development if you want

**Comment by mbrn** [comment]
Hi @paillave 

I think there is no need for development. 

1. You can change position of actions columns with options.actionsColumnIndex. Please look at example at https://material-table.com/#/docs/features/actions
2. You can override icons with Icons.Add. Please look at list of icons from https://material-table.com/#/docs/all-props

**Comment by paillave** [comment]
You might be right indeed. I'll see if I can have a Fab button there.
