### ISSUE TITLE
Tree Data get Selected Rows

### ISSUE THREAD

**Issue by KyriacosP** [mbrn/material-table#655]
![material-tebleTreeData](https://user-images.githubusercontent.com/44581807/58754472-398fb600-84d9-11e9-82ee-068b8e213527.PNG)

onSelectionChange seems to be working wrong here the rows argument contains multiple copies of each row selected although the toolbar count seems to be working fine

**Comment by mbrn** [comment]
Hi @KyriacosP 

Thanks for issue. This is a bug. I will resolve this problem asap.

**Comment by waisbek** [comment]
Hello,

I have the same issue. @mbrn do you have a deadline to fixed this bug, please?

Thanks!

**Comment by KyriacosP** [comment]
i removed the duplicates from the selected array based on their id it works well in my case but it may be slow if your selection array is too large. here is my code:
`unique(array) {
    let arr = [];
    for(let i = 0; i < array.length; i++) {
      if(!arr.some(x=>x.id===array[i].id)) {
        arr.push(array[i]);
      }
    }
    return arr;
  }`

**Comment by cristiadis** [comment]
@emrekara37 This is not fixed. I still get duplicate values when selecting, in version 1.46.0

**Comment by charlesc32** [comment]
I am also still seeing this issue. I think the fix only addressed if parent row duplicates. Children are still being duplicated.

**Comment by estubmo** [comment]
I'm also experiencing this issue.
![image](https://user-images.githubusercontent.com/5949794/85954281-8d87fb00-b976-11ea-9a31-f75282251392.png)
