### ISSUE TITLE
implement edit/delete action within a menu of the row

### ISSUE THREAD

**Issue by ArouiniLobna** [mbrn/material-table#658]
Hello Every one,

I am trying to use material-table within my project, however i am stuck with few features that i need and not sure how to do that using this library.

basically i have rows with data, and in each row i got a menu that pop up edit/delete options. Curently they only show next to each other within action column.

Also, another feature i need is: in a cell, if i dont have data, i need to click a button which will allow to enter data in texterea and the menu with edit/delete will be hidden. if i enter some text, then the text will apear and the button will not show again. if the i enter nothing and enter, the button show back.

I attach design for refrence 
![Capture1](https://user-images.githubusercontent.com/29419606/58772668-5d4c1c80-85fd-11e9-88d1-edb86b87759a.PNG)
![Capture](https://user-images.githubusercontent.com/29419606/58772677-676e1b00-85fd-11e9-81b3-76e576ef07bb.PNG)

Thank you

**Comment by mbrn** [comment]
Hi @ArouiniLobna 

You can use custom render feature for both menu and edit component.

**Comment by robert-levy** [comment]
Hey. I'm trying to implement a menu button too. I added an object to the columns array which loads the options button, but I'm not sure how to show the menu when I click on it.

This is the object in the columns array.

`            let actionsColumn = {
                field: 'actions', Title: 'actions', render: rowData =>
                    <Tooltip title="options">
                        <IconButton aria-label='options' size="small" onClick={(event) => handleOptionsClick(rowData,event)}>
                            <Icon>more_horiz</Icon>
                        </IconButton>
                    </Tooltip>
            }`

This is the handOptionsClick function. 

`
    const handleOptionsClick = (rowData,event) => {
        setAnchorEl(event.currentTarget);
        //bring up menu
        return(
        <Menu id="simple-menu" anchorEl={anchorEl} keepMounted open={Boolean(anchorEl)} onClose={handleClose} >
            <MenuItem onClick={handleClose}>Validate</MenuItem>
            <MenuItem onClick={handleClose}>Invalidate</MenuItem>
            <MenuItem onClick={handleClose}>Reset</MenuItem>
        </Menu>)}`
