### ISSUE TITLE
Add text in Actions 

### ISSUE THREAD

**Issue by VipinJoshi** [mbrn/material-table#660]
Hi,
I have a requirement to add text just next to the icon in Actions. But I am getting a hover effect because of this class **MuiIconButton** (MuiIconButton-root). For reference please check the attached image. I want to get rid of this hover effect.
![emage1](https://user-images.githubusercontent.com/25978758/58786885-2b8b8380-8606-11e9-8a50-401966dfaf7c.png)

**Comment by VipinJoshi** [comment]
I have overridden the theme so It's done

**Comment by durgeshsatyam** [comment]
https://github.com/mbrn/material-table/issues/830#issuecomment-513485705
Please refer to this answer
