### ISSUE TITLE
Customising PageSizeOption

### ISSUE THREAD

**Issue by yashSangai** [mbrn/material-table#661]
Is there any way to load all of the data, irrespective of the page size? I mean, I want no page size on the table and load all of the data.

**Comment by mbrn** [comment]
just give array of your data to data field of component:

https://material-table.com/#/docs/features/search

**Comment by yashSangai** [comment]
I didn't understand. I am talking about the page size that comes on the table toolbar which is by default 5, I don't want that. If for example I have 50 rows of data then it should load all of it rather than just 5 (Default Page Size). How would I do that?

**Comment by mbrn** [comment]
Try this:

<MaterialTable
options={{
pageSize: 50,
pageSizeOptions: [50, 100, 200]
}}
/>

**Comment by yashSangai** [comment]
Oh it worked! Thanks for the help.

**Comment by soumyaDivami** [comment]
Hey, can somebody help me as to how can I get the current page and set the same?

**Comment by KeshriAyushi22** [comment]
can anybody tell how to set the current selected pagesize from the array ? and then use that page size on every reload irrespective of going back to the default value
