### ISSUE TITLE
formating date

### ISSUE THREAD

**Issue by rayray93** [mbrn/material-table#662]
Hi there, how to format date ? 

for now I have table column type: "datetime"... 
but that column dosent format date ? ( it just displaying timestamp )

is there option to format date auto? so i dont need to map thought response and format field values manually?

**Comment by mbrn** [comment]
Hi @rayray93 

You can use type: 'date', If you want a custom solution you can use custom render feature.

**Comment by lethuan692** [comment]
> Hi @rayray93
> 
> You can use type: 'date', If you want a custom solution you can use custom render feature.

i use render feature and show on datatable oke, but how about  export feature?
