### ISSUE TITLE
Leave full width search input and allow to set placeholder

### ISSUE THREAD

**Issue by Annderson** [mbrn/material-table#663]
I'm working on a project, when using the search function, I want to apply certain styles to make the input fill the entire screen, but I can not do that in searchFieldStyle, could you leave the fullWidth open?

I needed the placeholder also been open, to rebeber values, can this be done?

Also TopBar would need it to be more open to changes in its layout, so I realized it does not have a style prop for TopBar

**Comment by mbrn** [comment]
Hi @Annderson 

You can override the toolbar according to your needs. Please check docs : https://material-table.com/#/docs/features/component-overriding

If you have any problem please feel comfort to access me.
