### ISSUE TITLE
Changing column order not updated in Edit mode

### ISSUE THREAD

**Issue by kamaral75** [mbrn/material-table#664]
**Describe the bug**

Changing the order of the columns is not showing correctly in editable mode.

**To Reproduce**
1. Go to the editable material-table demo [https://material-table.com/#/docs/features/editable](https://material-table.com/#/docs/features/editable)
2. Click on the column headers and drag and drop columns into a new order
3. Click the 'edit' button to edit a row
4. The editable rows are not in the same order as the newly updated columns
5. The editable rows appear in the original order prior to changing the column order
6. This results in the editable rows not aligning with the relevant column label

![material-table-editable](https://user-images.githubusercontent.com/13367900/58828659-ee2df280-8613-11e9-88c4-acebcf9317bc.png)

**Expected behavior**
After changing column order, the rows should appear in the new order while in Editable mode.

**Comment by mbrn** [comment]
Hi @kamaral75 

It seems there is a but within edit row component. I will resolve it asap. Thanks.

**Comment by mbrn** [comment]
This is done with 1.39.2
