### ISSUE TITLE
Publish a build using ESModules

### ISSUE THREAD

**Issue by eps1lon** [mbrn/material-table#665]
**Is your feature request related to a problem? Please describe.**
Using `material-table` bundles all of `@material-ui/core` because no build is published using ESModules.

**Describe the solution you'd like**
Transpile the source with `modules: false` and publish that build as well with a `module` entry in your `package.json`

**Describe alternatives you've considered**
Using a fork that is published under a different name

**Additional context**
Currently only a commonJS build is published. Since [you use named imports](https://github.com/mbrn/material-table/blob/a05fd97517a74ac8d52d0eb036433efe320de949/src/material-table.js#L2) this translates into webpack bundling all of `@material-ui/core`.

**Comment by mbrn** [comment]
I will check this asap.
