### ISSUE TITLE
MuiThemeProvider is not working when material version is updated to 4.0.2

### ISSUE THREAD

**Issue by VipinJoshi** [mbrn/material-table#667]
I am using  MuiPaper Paper and MuiIconButton as mention below It was working fine but as we move to material 4.0.2. the theme change is not working.
const theme = createMuiTheme({
  overrides: {
    MuiPaper: {
      root: { backgroundColor: 'blue' },
      elevation2: {
        boxShadow: 'none',
      },
      rounded: {
        borderRadius: 0,
      },
    },
    MuiIconButton: {
      root: {
        borderRadius: 0,
      },
    },
  },
});

<MuiThemeProvider theme={theme}>
      <MaterialTable .... />
</MuiThemeProvider>

**Comment by jonesne92** [comment]
Am also noticing this. Using @material-ui/core version 4.0.2 and material-table version 1.39.0. Whenever a MaterialTable is present on the page, the styling specified in createMuiTheme isn't applied to my components. When I remove the MaterialTable, the styling returns

**Comment by yerbol777** [comment]
> Am also noticing this. Using @material-ui/core version 4.0.2 and material-table version 1.39.0. Whenever a MaterialTable is present on the page, the styling specified in createMuiTheme isn't applied to my components. When I remove the MaterialTable, the styling returns

I have the same problem, please fix (

**Comment by mbrn** [comment]
It seems there is a problem with styles of mui and MT. I will take a look asap.

**Comment by thetw** [comment]
I'm unfortunately facing the same problem. While using the MUI ThemeProvider the Material Table seems to apply its own styles to the html head and overrides for instance my custom typography settings, which causes a visual mess on the page. Would be glad if this issue can have some prio, because it makes Material Table unusable for now, which is very sad.

**Comment by jaydeep987** [comment]
Horrible bug. All styles overriden/replaced/gone after using MT. Blocker issue. After removing MT from page, everything works fine. Wasted few hours with this.
Please fix ASAP, we appreciate in advance!
Using `material-ui^4.0.2`

**Comment by jaydeep987** [comment]
> Horrible bug. All styles overriden/replaced/gone after using MT. Blocker issue. After removing MT from page, everything works fine. Wasted few hours with this.
> Please fix ASAP, we appreciate in advance!
> Using `material-ui^4.0.2`

EDIT:
Works find with MT `v1.38.0`.
Wish someone fix in new version.

**Comment by mbrn** [comment]
I will :)

**Comment by Kaleem-** [comment]
hurry up ?

**Comment by filipkroca** [comment]
This bug is occupied since version v1.38.0. I have downgraded to version v1.37.0 and styles are back. This is a very insidious bug, I spent an hour searching what happened to my styles.

INFO:
quick fix = `"material-table": "1.37.0"`

**Comment by theredfish** [comment]
Hello,
I don't know if it can help, the console is showing this warning when MaterialTable is imported : 

> It looks like there are several instances of `@material-ui/styles` initialized in this application.
This may cause theme propagation issues, broken class names and makes your application bigger without a good reason.

Have a good day and thank you :)

**Comment by VoltCruelerz** [comment]
Downgrading from 1.40 to 1.37 worked for us as well.

**Comment by sw-yx** [comment]
just thought i'd say that v1.37  works for me (with @material-ui/core 4.3.0). however i also see inside my console warning: 

```
It looks like there are several instances of `@material-ui/styles` initialized in this application.
This may cause theme propagation issues, broken class names, specificity issues, and makes your application bigger without a good reason.

See https://material-ui.com/r/styles-instance-warning for more info.
```

leaving for searchability

**Comment by Domino987** [comment]
Is this still an issue?
