### ISSUE TITLE
new event onColumnsChange

### ISSUE THREAD

**Issue by MaxGorshkov** [mbrn/material-table#668]
in continue of #517
**when** can I get list of selected columns in columnsButton?

this event can be fired after each change of visualization columns in mode columnsButton = true

**Comment by mbrn** [comment]
Currently there is no event for columns changed. But i can add it asap.

**Comment by MaxGorshkov** [comment]
it will be great!

**Comment by dj1703** [comment]
Any update on that topic? This feature would be highly appreciated.

**Comment by fkrauthan** [comment]
I would also be interested in this feature as I plan to store the users setting in localstorage so when they return they get the same column setup.

**Comment by djimpanse** [comment]
I just created a [PR](https://github.com/mbrn/material-table/pull/919) with this feature. Any feedback is appreciated.
