### ISSUE TITLE
Override editing button

### ISSUE THREAD

**Issue by marinsagovac** [mbrn/material-table#669]
A code as sample works for me if I want to override buttons of specified type (create, save, cancel), but for existing data I can not override a button with custom material UI. There override only one button instead both for save and cancel (it works on new action, but not on edit action):

>      Action: privProps => (
>          (privProps.action.icon && privProps.action.icon.render().props.children === 'add_box' && props.addComponent.visible)
>            ? (
>              <Button
>                color="secondary"
>                variant="contained"
>                style={{ textTransform: 'none', marginLeft: '0.5em' }}
>                size="small"
>                onClick={event => privProps.action.onClick(event, privProps.data)}
>              >
>                <AddIcon />
>                {props.addComponent.title || 'Create'}
>              </Button>
>            )
  

How to override a custom button on editing (existing row) ?

**Comment by mbrn** [comment]
You can use privProps.action for your condition:

```javascript
import MaterialTable, { MTableAction } from material-table;

Action: privProps => {
if(privProps.actions.icon) { // Or you can add custom fields to action and use them
return your component
}
else {
return <MTableAction {...privProps}/>
}
```

**Comment by marinsagovac** [comment]
But override a buttons? I ended with that way... I've extends `MTableAction` it will **wrap** and can't change to button of material-ui components.

```
import MaterialTable, { MTableAction } from material-table;

Action: privProps => {
if(privProps.actions.icon) { // Or you can add custom fields to action and use them
return your component
}
else {
return
                   <Button
                    onClick={(event) => {
                      let action = privProps.action;

                      if (typeof action === 'function') {
                        action = action(privProps.data);

                        if (!action) {
                          return null;
                        }
                      }

                      action.onClick(event, privProps.data);
                    }}
                    {...privProps}
                  >
                    {'Button'}
                    {console.debug(privProps)}
                  </Button>
}
```

**Comment by mbrn** [comment]
You should put your code in if cluase. Not else cluase

**Comment by marinsagovac** [comment]
Thanks.
