### ISSUE TITLE
Provide ability to customize the component of a specific action

### ISSUE THREAD

**Issue by Renaud009** [mbrn/material-table#670]
**Is your feature request related to a problem? Please describe.**
I would like to customize the "add" action component only. Right now, a component can be provided for all actions. We cannot provide a different component for different action or can we ?

**Describe the solution you'd like**
Provide a way to customize specifically the "add" action or any kind of actions. Maybe provide the ability to specify a component for each kind of default actions?

**Describe alternatives you've considered**
I considered validating action type before rendering my component using component props but couldn't find any props to achieve such a validation

**Comment by mbrn** [comment]
Hi @Renaud009 

Try this 

```javascript
import MaterialTable, { MTableAction } from material-table;

Action: privProps => {
if(privProps.actions.icon) { // Or you can add custom fields to action and use them
return your component
}
else {
return <MTableAction {...privProps}/>
}
```

**Comment by ciiiii** [comment]
@mbrn I found action like edit and delete have not  property icon or tooltip, so how can I customize these actions.
![image](https://user-images.githubusercontent.com/28784251/68527069-e76f7e00-031d-11ea-81d6-8b7d72cc7387.png)
