### ISSUE TITLE
Expose Setters for page number

### ISSUE THREAD

**Issue by udayreddy** [mbrn/material-table#672]
**Is your feature request related to a problem? Please describe.**
I want to use mouse wheel\scroll to move between pages
**Describe the solution you'd like**
Function props for setPage() or nextPage() \ prevPage().

**Describe alternatives you've considered**
I tried setting the initialPage after initial render but the table does not re-render on that prop change, Which is fine 👍 
But I cannot set programmatically select pages on the table without having a custom pagination component

**Additional context**
I can help out if you think this adds value

**Comment by mbrn** [comment]
Hi @udayreddy 

You can call onChangePage of MT with tableRef. tableRef.onChangePage(null, 2)

Please check documentation: 
2nd example uses tableRef:
https://material-table.com/#/docs/features/remote-data
