### ISSUE TITLE
User experience of adding new record

### ISSUE THREAD

**Issue by canpolatoral** [mbrn/material-table#673]
**Is your feature request related to a problem? Please describe.**
In editable mode, if you have 6 records in a table and your page size is 5 and then you decide to add new row, your new record is added at the end of the table. And, you cannot understand that if record is added or not.

**Describe the solution you'd like**
After adding new record, table should navigate to page where the record is located.

**Describe alternatives you've considered**
Maybe, setPage method could be added. And developer could set page manually.

**Additional context**
I added screenshots to make it clear.

This table has 6 records.
![image](https://user-images.githubusercontent.com/15803845/58916493-84553c00-872c-11e9-9926-db2ede181e67.png)

When adding a new record.
![image](https://user-images.githubusercontent.com/15803845/58916497-86b79600-872c-11e9-8201-0a43d78d8921.png)

After adding process completed, you can't understand where the new record is
![image](https://user-images.githubusercontent.com/15803845/58916493-84553c00-872c-11e9-9926-db2ede181e67.png)

The new record is at the end. This user experience needs to be developed.
![image](https://user-images.githubusercontent.com/15803845/58916488-80291e80-872c-11e9-838d-3de04fa9ba20.png)

**Comment by IraSkyx** [comment]
Did you try adding addRowPosition in options props like so ?
`options: {
addRowPosition: 'first'
}`

**Comment by canpolatoral** [comment]
Yeah, I tried it. When I save the record in database. It goes at the end of table, too. Maybe, I can order data when I retrieve from database but I feel that this solutions are a bit complicated and I didn't like it.

I did another workaround for this problem. 
I looked to the source code and I solved my problem in a different way :)
**I do not recommend this solution to anyone :)**

```
 <MaterialTable
        tableRef={table}
        title="Book Categories
        .
        .
        onRowAdd: newData =>
            new Promise(resolve => {
              setTimeout(() => {
                table.current.dataManager.changeCurrentPage(newPage);
              }, 600);
            }),
            />
```

**Comment by canpolatoral** [comment]
Also, I checked `addRowPosition: 'first' `prop again.
It adds the new row to the first row of table in editing time, but after you click to check icon to finish, it adds to the end.

**Comment by canpolatoral** [comment]
Finally, I used `options: { addRowPosition: 'first' }` and retrieved data from db in reverse order.
