### ISSUE TITLE
Conditional detail panel options

### ISSUE THREAD

**Issue by jakeleventhal** [mbrn/material-table#675]
**Is your feature request related to a problem? Please describe.**
I want to be able to do the same thing as here https://github.com/mbrn/material-table/issues/609 as you are able to do for actions with detail panels.

**Describe the solution you'd like**
 I want to conditionally have a detail panel for a row based on the conditions of the row

**Comment by jakeleventhal** [comment]
Didn't realize there was already a prop for this

**Comment by jakeleventhal** [comment]
There is a way to disabled the panel, but not hide it completely - reopening

**Comment by mbrn** [comment]
I can add hidden field to detailPanel asap.

**Comment by raph90** [comment]
Is there a way to conditionally not have a detail panel - something like : 

`detailPanel={[
                      {
                      render: rowData => {
                         if (!rowData.headerRow) {
                            return <h2>yes</h2> 
                         } else {
                            return false
// this would completely remove any detail panel for this row
                         }
                      }
                      }
                    ]}`

**Comment by jakeleventhal** [comment]
@raph90 I think it makes more sense to have a separate function that returns true or false that is different from the render function

so you would have something like

**Comment by annuranjan2019** [comment]
I do have the same issue. It would be nice to have the same component for tables in both the cases - when I have to display the row details, and when I don't have any row details to show. 

My suggestion is to make `detailsPanel` prop to accept `false` as well in case there is no component to render.  
like: 
`
detailsPanel: { 
    rowHasDetails ? rowData => ...  : false
}
`

**Comment by ldsmike88** [comment]
Another way to do it would be to add another property that accepts a function: 

```
{
  visible: rowData => !rowData.expandable, // returns Boolean
  render: rowData => <div>{rowData.name} {rowData.surname}</div>,
}
````

Disabled should also accept a function. Currently, you can either disable the panel for all rows or none unless I'm mistaking.

**Comment by aesnyder** [comment]
Has anyone figured out a way to do this? If so can you please share? 

Otherwise, is anyone working on a pull request??

**Comment by ldsmike88** [comment]
The workaround is to disable it and use `display: none` on your icon:

```
const detailPanel = [
  rowData => ({
    disabled: !rowData.expandable,
    icon: () => <UnfoldMore className={!rowData.expandable && classes.displayNone} />,
    openIcon: UnfoldLess,
    render: () => <div>content</div>,
  })
];
```

**Comment by aesnyder** [comment]
Thanks @ldsmike88

**Comment by michaelgthomas** [comment]
> The workaround is to disable it and use `display: none` on your icon:
> 
> ```
> const detailPanel = [
>   rowData => ({
>     disabled: !rowData.expandable,
>     icon: () => <UnfoldMore className={!rowData.expandable && classes.displayNone} />,
>     openIcon: UnfoldLess,
>     render: () => <div>content</div>,
>   })
> ];
> ```

THANK YOU SO MUCH!!!!!!!

**Comment by cristiangabor** [comment]
There is still a column where the icon should be. Is there a way not to show that column for detailPanel?

**Comment by viktor-mir** [comment]
Up topic :) ! 

> My suggestion is to make `detailsPanel` prop to accept `false` as well in case there is no component to render.
> like:
> `detailsPanel: { rowHasDetails ? rowData => ... : false }`

This would be nice solution!

**Comment by viktor-mir** [comment]
> The workaround is to disable it and use `display: none` on your icon:
> 
> ```
> const detailPanel = [
>   rowData => ({
>     disabled: !rowData.expandable,
>     icon: () => <UnfoldMore className={!rowData.expandable && classes.displayNone} />,
>     openIcon: UnfoldLess,
>     render: () => <div>content</div>,
>   })
> ];
> ```

BIG BIG THANK YOU! For a while it is best solution among existed.

**Comment by Gr8tDaNe** [comment]
> There is still a column where the icon should be. Is there a way not to show that column for detailPanel?

I've created a custom package that hides the detailPanel column because I couldn't wait for it to be implemented, if you wanna test it, [here](https://github.com/Gr8tDaNe/material-table) it is.
Once installed you can just use `options.renderDetailPanelColumn: false` to hide it (remember to implement a rowclick or another way to open it). 

I'm a noob so this is probably not the ideal way of publishing a package, but I was short on time. 
I'll submit a pull request later today. 

(I've pasted this in another issue too, sorry)

**Comment by jakeleventhal** [comment]
not stale

**Comment by petr-like** [comment]
```
const detailPanel = condition ? []: [
  rowData => ({
    render: () => <div>content</div>,
  })
];
```
With this decision, we don't render element.

**Comment by AlekseiMordas** [comment]
@petr-like I have a field code95, if this field empty - I don't want to show panel option for a particular row.
My code is:
`detailPanel={
                           rowData => (rowData.code95==='') ? [] : [
                              rowData => ({
                                render: () => <div>content</div>,
                              })
                            ]
                       }`
Unfortunately, it doesn't work. Can you please suggest the right way?

**Comment by jakeleventhal** [comment]
not stale

**Comment by Jean-MarcCheynier** [comment]
I'm also looking for a way to have some row with details and other rows without. As of now, it not possible to put a condition on the presence of the 'expand button'

Would it be possible at least to make the property 'disabled' of the DetailPanel a function ?
It would be possible at least to enable details based on the rowData

**Comment by Gr8tDaNe** [comment]
@Jean-MarcCheynier if you have it open with onRowClick you can add rowData as an argument and open the panel conditionally like so: 
`onRowClick={(event, rowData, togglePanel) => {
    if (rowData.hasDetailPanel) {
                  togglePanel();
                } else {
                  return null;
                }
}}`

If you're opening it through a button, do the same.

**Comment by Jean-MarcCheynier** [comment]
@Gr8DaNe  It would be nice to have to possibility to change the icon visibility based on the rowData
                        ...,
                        detailPanel={[{
                            **visible: rowData => {  //return boolean  },**
                            disabled: false,
                            isFreeAction: true,
                            render: rowData => <DetailPanel parentId={rowData.id} />
                        }]}

**Comment by natrajkalyan** [comment]
I agree with @Jean-MarcCheynier . It would be really helpful

**Comment by mateosantosdev** [comment]
not stale

**Comment by skye-levit** [comment]
is there a solution so far?

**Comment by Dart18** [comment]
After several programmatic attempts I implemented this solution:
1) Scss

```scss
.MuiTableRow-root {
    &.hide-detailPanel {
        td:first-child {
            pointer-events: none;
            button { display: none; }
        }
    }
}
```

2) Override the Row component to provide the `hide-detailPanel` class conditionally
```tsx
    const components: Components = {
        Row: (props: any) => (
                <MTableBodyRow
                    {...props}
                    className={clsx({
                        ['hide-detailPanel']: <your condition returning a boolean here based on props>,
                    })}
                />
            ),
    }
```

3) Pass the components to the MaterialTable
```tsx
<MaterialTable
    ...
    components={components}
    ...
/>
