### ISSUE TITLE
Is there a way to keep column hidden but still have its filters shown?

### ISSUE THREAD

**Issue by teamtechalpha** [mbrn/material-table#679]
We saw that searchable property allows for columns to be searched even when hidden but is it also true for remote data? 

Is there a way to let users select filters while keeping the column hidden?

Thanks for your input and great work.

**Comment by mbrn** [comment]
You can implement searhcing in your remote data source. 

Showing filters is not possible when column is hidden. But you can set render to your column definition to hide data.
