### ISSUE TITLE
Migrate date-fns to Dayjs

### ISSUE THREAD

**Issue by baoduy** [mbrn/material-table#683]
I would recommend to use Dayjs for date formatting and operating as this is a smalled library which offers the functionality similar to moment.

https://bundlephobia.com/result?p=dayjs@1.8.14

Thanks.

**Comment by mbrn** [comment]
I will take a look at it.

**Comment by zacheryph** [comment]
Since this depends on `@material-ui/pickers` is there anyway to pull the Utils that is being provided to them? using whatever utilities already available is smaller than including something else.
