### ISSUE TITLE
Need to be able to disable/conditionally render the edit/delete buttons

### ISSUE THREAD

**Issue by jakeleventhal** [mbrn/material-table#684]
**Is your feature request related to a problem? Please describe.**
Some rows you may want the user to not be able to delete or edit.

**Describe the solution you'd like**
There should be a function that lets you specify the conditions in which a row can be editable/deletable

**Comment by mbrn** [comment]
Hi @jakeleventhal  

Actually i did this. Please check documentation: 

https://material-table.com/#/docs/features/editable

**Comment by jakeleventhal** [comment]
I see now, it's not in the all props section of the docs though and there isn't an example so that is why i missed it. Perhaps this issue can just be to have that section of the docs updated
