### ISSUE TITLE
how to custom search in toolbar

### ISSUE THREAD

**Issue by quocbaondvn2000** [mbrn/material-table#685]
I want to turn off automatic search. Instead, The search will start when you press enter
![2019-06-06_082940](https://user-images.githubusercontent.com/45376591/59000575-48f26480-8835-11e9-8a58-ba7656bf6e96.jpg)

Thanks.

**Comment by mbrn** [comment]
i can add this feature. Thanks.

**Comment by nvtin** [comment]
@mbrn How is this feature?
I am using remote data, then the automation search is making the app jerky while typing.

**Comment by twhetzel** [comment]
@nvtin do you have an example of how you are using Search with remote data?

**Comment by mqasim1990** [comment]
> @mbrn search field is not working with remote data, making the app jerk but not searching any field related to search query

**Comment by lokeshcausecode** [comment]
@mbrn What is the update on this issue?

**Comment by mqasim1990** [comment]
@lokeshcausecode 
Check this one.

https://github.com/mbrn/material-table/issues/1119#issuecomment-536701020

**Comment by MisterFredy** [comment]
you have example of this?
