### ISSUE TITLE
Change the style of body.editRow.deleteText

### ISSUE THREAD

**Issue by ahboujelben** [mbrn/material-table#688]
Hello,

First, thank you for this very useful library -I've been using it for a while and it's obvious a lot of work and thought has been put into it

I'm just trying to customise few things and I realised I couldn't change the colour/size of the text that appears when a row is about to be deleted ("Are you sure delete this row?" by default). I'm wondering if there is a way to change the style of that text.

Many thanks.

**Comment by bturtu405** [comment]
hi there is a solution to this problem?
