### ISSUE TITLE
Editing does not go away if "editable" value changes

### ISSUE THREAD

**Issue by jakeleventhal** [mbrn/material-table#689]
**Describe the bug**
I have onRowEdit as a conditional function that is altered via a state variable (when i press the enter button). When i click my edit button, the edit option becomes available. Then when I try to edit a row, then click the discard button, the field is still editable and If i try to click save, the app crashes.

**To Reproduce**
Watch GIF below

**Expected behavior**
When the editable prop is removed, the table should automatically discard the changes (as if clicking the X button on the row)

**Screenshots**
![Jun-06-2019 14-35-56](https://user-images.githubusercontent.com/15133828/59057625-c4b9d480-8868-11e9-8cb4-c9543122893a.gif)

**Comment by mbrn** [comment]
You can change tableData.editMode of current row

**Comment by jakeleventhal** [comment]
How am I to do this? I don't see any reference to `tableData` or `editMode` of the docs?

**Comment by mbrn** [comment]
Currently MT calls editing mode code in a inline function. I will replace it a function that member of MT class. So you can call it with tableRef. 

![image](https://user-images.githubusercontent.com/7895451/59411524-211a7800-8dc4-11e9-822f-62b6188d33b5.png)

**Comment by jakeleventhal** [comment]
not stale

**Comment by jakeleventhal** [comment]
not stale

**Comment by jakeleventhal** [comment]
not stale

**Comment by jakeleventhal** [comment]
not stale

**Comment by jakeleventhal** [comment]
not stale
