### ISSUE TITLE
Actions on the right side of table 

### ISSUE THREAD

**Issue by caseychoiniere** [mbrn/material-table#69]
**Is your feature request related to a problem? Please describe.**
I think this is just a question rather than a feature request

**Describe the solution you'd like**
I'd like to have the actions show up on the right and I'm wondering if there's a way to apply colors to the icons?

**Describe alternatives you've considered**
I'm thinking that instead of the Actions props I might need to use the custom render prop. It would be nice if actions supported a left or right props and a color prop for the icon though.

**Comment by mbrn** [comment]
@caseychoiniere ,

Try version 1.1.0 to styling a action button with iconProps.  Look at the actions example at https://mbrn.github.io/material-table/#/docz-examples-example-actions

**Comment by rbkumar88** [comment]
Instead of always keeping it on the left or right side, is there a possibility to keep it anywhere(before or after any field) we want in the table.?

**Comment by mbrn** [comment]
Hi @caseychoiniere ,

This issue resolved by @gulcann ( She is my wife:). I will publish new release in this week.
