### ISSUE TITLE
Ability to change whether or not a column is editable based on conditions of the row

### ISSUE THREAD

**Issue by jakeleventhal** [mbrn/material-table#690]
**Is your feature request related to a problem? Please describe.**
Right now, the current options for the editable prop on a column are 'always' 'never' 'onUpdate' 'onAdd'. There should be another option that lets you specify a function to determine the value based on the row.

**Describe the solution you'd like**
A function that lets you determine if a column is editable based on the data in the row.

**Comment by mbrn** [comment]
Good idea

**Comment by mohitmutha** [comment]
I have suggested a fix in #714 and added a pull request

**Comment by jakeleventhal** [comment]
So is this issue closed then?

**Comment by mbrn** [comment]
Yes. Now you can use it with version 1.39.1
