### ISSUE TITLE
Adding spanning rows?

### ISSUE THREAD

**Issue by thebriando** [mbrn/material-table#691]
Is there a way to add spanning rows in a table to generate things like total/subtotal like in here? https://material-ui.com/components/tables/#spanning-table

**Comment by mbrn** [comment]
Currently you cant. But you can override pagination component to add new row to end of table.

**Comment by dandv** [comment]
Should this issue be open, since it's help-wanted?

**Comment by MrChe** [comment]
+1, this need implement

**Comment by devpato** [comment]
+1

**Comment by jhoanborges** [comment]
+1
