### ISSUE TITLE
Overriding component throws warning validateDOMNesting

### ISSUE THREAD

**Issue by catalinleca** [mbrn/material-table#693]
Is there anyway to get rid of that error if I am overriding my component like:

````
              components={{
                Row: props => {
                  console.log('in row: ', props);
                  return (
                    <Grid>
                      <MyCustomRow/>
                    </Grid>
                  )
                },
              }
````
other than just using tr td and th inside MyCustomRow?

and what can happen if I leave it like this with the warning?

**Comment by mbrn** [comment]
Hi @catalinleca 
 It expects a `tr` and `td` inside tr. To prevent warnings you should return tr.

**Comment by catalinleca** [comment]
Yee I agree with you, but I was wondering what will happen if I don't follow this rules

**Comment by mbrn** [comment]
Please look at this:

https://stackoverflow.com/questions/2974573/div-inside-table

It is about html.
