### ISSUE TITLE
custom Action component conflicts with Add row component

### ISSUE THREAD

**Issue by AntoniusGolly** [mbrn/material-table#696]
**Describe the bug**
The Add Row item changes to whatever is given as a custom action component.

**To Reproduce**
1. provide a custom action component on `components` (this will add custom buttons to the row action)
2. have a `editable.onRowAdd` method set (this will add the Add Row button on the top right
row)

**Expected behavior**
* the row actions should change to the provided custom action components
* the Add row button *should remain the the Plus icon*
* The latter ist not the case

**Screenshots**
![image](https://user-images.githubusercontent.com/3856505/59166305-8e11e180-8b28-11e9-8fc5-9ffcf4edc8a7.png)

**MaterialTable Markup**
```
<MaterialTable
        title="Teams"
        columns={this.state.columns}
        data={this.state.data}
        icons={tableIcons}       
        editable={{
          onRowAdd: this.onRowAdd,
          onRowUpdate: () => {}
        }}
        components={{
          Actions: props => (
            <div>
              <IconButton
                onClick={() =>
                  this.props.history.push(`/teams/${props.data.uuid}`)
                }
              >
                <Edit />
              </IconButton>
              <IconButton
                onClick={() =>
                  this.props.history.push(`/teams/${props.data.uuid}`)
                }
              >
                <Edit />
              </IconButton>
            </div>
          )
        }}
      />
```

**Comment by agrinko** [comment]
Same here. I didn't even create a custom Actions component. I just added onRowAdd, onRowUpdate and onRowDelete callbacks, and instead of "add" button, I see the edit and delete buttons at the toolbar:
![b2f75075482f4298fcdb80bf6feac66d](https://user-images.githubusercontent.com/7050015/60760719-d4346500-a042-11e9-95cf-a947378b7cd1.png)
