### ISSUE TITLE
defaultSort column doesn't change when reseting columns displayed and setting the defaultSort value on a different column

### ISSUE THREAD

**Issue by gxwheel152** [mbrn/material-table#697]
**Describe the bug**
defaultSort column doesn't change when reseting columns displayed and setting the defaultSort value on a different column

**To Reproduce**
Create a data source and multiple columns views of that data 
Change the columns view, expected the following: 
1. Columns displayed are changed ==> YES
2. Column options, e.g., colors and filtering, are updated ==> YES
4. Column defaultSort is updated  ==> NO

**Expected behavior**
Expected the defaultSort to change along with the other column options. 

**Material-Table Version**
 - Version:     "material-table": "^1.39.0"

**Additional context**
I solved this by creating separate components (unique JS files) and passing the columns, options, data, etc. to the individual components, but ... since all other column settings are changing, wanted to ask about this value getting updated as well. 

**Screen Shots**
Initial Set of Columns, with the 7th column sorted
![2019-06-09_18h59_33](https://user-images.githubusercontent.com/42223563/59167308-d4961a80-8aed-11e9-9ad1-102ae901895c.png)

Switch to a new "VIEW" (set of columns with associated options)
![2019-06-09_18h59_43](https://user-images.githubusercontent.com/42223563/59167329-ebd50800-8aed-11e9-9041-dece2c471f4a.png)

defaultSort stays on 7th column, instead of switching to the 9th column ("Bonus Rate"), see code below for view of the column attribute. 
![2019-06-09_19h00_02](https://user-images.githubusercontent.com/42223563/59167374-26d73b80-8aee-11e9-8e84-1e51c6a9e695.png)

`  {
    title: "Tech Falls",
    field: "tech_falls",
    filtering: false,
    headerStyle: {
      backgroundColor: "#008080",
      color: "#FFF",
    },
  },
  {
    title: "Falls",
    field: "fall_total",
    filtering: false,
    headerStyle: {
      backgroundColor: "#008080",
      color: "#FFF",
    },
  },
  {
    title: "Bonus Rate",
    field: "bonus_predictor",
    filtering: false,
    defaultSort: "desc",
    headerStyle: {
      backgroundColor: "#008080",
      color: "#FFF",
    },
  },
]`

**Comment by mbrn** [comment]
Hi @gxwheel152 
Thanks for clear issue. I will take a look at this asap.

**Comment by gxwheel152** [comment]
Any update on this issue?

**Comment by alimirzaei** [comment]
In case of changing data, you can pass a new key to the component. Here is the sandbox which is working:
https://codesandbox.io/s/broken-glitter-n3fs2

**Comment by gxwheel152** [comment]
I'll have to check that out in my next round of updates. Thanks for the details
