### ISSUE TITLE
Check box icon stretched

### ISSUE THREAD

**Issue by giorgi-m** [mbrn/material-table#698]
First, thanks for what seems  a nice table. 

The checkbox icon is stretched for nested objects, see the screenshot.

![Screenshot from 2019-06-10 10-47-09](https://user-images.githubusercontent.com/41240312/59177493-5d07d000-8b6d-11e9-811d-d8fab7d6b97a.png)

**To Reproduce**
https://codesandbox.io/s/suspicious-snyder-62lgu

**Comment by mbrn** [comment]
Hi @giorgi-m 

This happened after mui 4.0. I will take a look at it asap.

**Comment by mbrn** [comment]
This is done with 1.39.2
