### ISSUE TITLE
Hiden sorting lable in the actions header

### ISSUE THREAD

**Issue by GachaSalt** [mbrn/material-table#699]
Problem:
I found that there is a hiden sorting lable lies within the acitions header and can not be removed. In most cases, it's fine, but it prevents me from properly aligning (especially aligning centrally) the contents of the action column, which is a problem to me.

Solution:
In the m-table-header.js, the actions header is rendered by 
```
 key: "renderActionsHeader",
    value: function renderActionsHeader() {
      var localization = (0, _objectSpread2["default"])({}, MTableHeader.defaultProps.localization, this.props.localization);
      return React.createElement(_core.TableCell, {
        key: "key-actions-column",
        padding: "checkbox",
        className: this.props.classes.header,
        style: (0, _objectSpread2["default"])({}, this.props.headerStyle, {
          textAlign: 'center'
        })
      }, React.createElement(_core.TableSortLabel, {
        disabled: true
      }, localization.actions));
    }
```
This problem could be temporarily solved by replacing the `React.createElement(_core.TableSortLabel, {disabled: true}, localization.actions)` with `React.createElement('div', null, localization.actions)`.
For a long term solution, I hope this hiden sorting label could be removed permanently or optionally in the future.

Thank you for your great work on this useful project.

**Comment by mbrn** [comment]
Hi @GachaSalt 

I will consider this. Thanks for your clear description.

**Comment by buhrenduh** [comment]
@GachaSalt did you find any work arounds for this? I am facing the same alignment problems as you.

**Comment by eloyrubinos** [comment]
@buhrenduh I'm facing the same issue. Did you manage to find a workaround?
