### ISSUE TITLE
Customize toolbar rendering

### ISSUE THREAD

**Issue by tadeuqc** [mbrn/material-table#70]
**Describe the solution you'd like**
rendering a custom toolbar would allow to render controls like the title and the search textbox in different orders, or even add button like add/edit Records in a modal.

**Describe alternatives you've considered**
It could be done creating a custom component and pointing it on a prop. So we could incorporate the behaviors with a totally custom UI

**Comment by mbrn** [comment]
Hi @tadeuqc,

This is a good idea. I can add `components` property that could allow user to customize any component such as toolbar, search input, footer etc. 

Please star repo and wait for next releases. I will add this property.

**Comment by tadeuqc** [comment]
Great! Thats awesome! If you need any help reach me out! I'm quite new to react but i've been doing a lot of stuff by myself lately!

**Comment by mbrn** [comment]
@tadeuqc 

if you want to contribute you can look at the issues which i labeled as good first issue. You can contribute to resolving them. 

If you have any trouble i can help you.

**Comment by mbrn** [comment]
Hi @tadeuqc ,

Sorry for late job:(. But this is done. You can change any component of material-table in next release. 

Next release will be published in a few days.
