### ISSUE TITLE
Overriding the Select All

### ISSUE THREAD

**Issue by RobertLbebber** [mbrn/material-table#700]
I need to have a separate functional behavior on the SelectAll checkbox. (Select All in the Remote query vs any subset we are displaying). So I am trying to see what functions I can use to do this. I need to disable the default behavior where if you select all on a page it manually, it will check the SelectAll box. This isn't true if there is more than one page of data.

Got any ideas?

**Comment by BVH77** [comment]
You can use the actions with property isFreeAction: true, isn't it?

**Comment by RobertLbebber** [comment]
That could potentially work css aside, but i'll want to show that the items listed have been selected. I haven't had any luck working inside of tableRef, yet

**Comment by schen3** [comment]
Need this feature as well, is there any updates?

**Comment by alexanderwhatley** [comment]
I need this feature as well, any updates @mbrn?

**Comment by raydot** [comment]
I also need this feature.  Specifically I'm looking for a way to select all of a page, but not the entire data set.
