### ISSUE TITLE
rowStyle height does not work for anything under 49px in height

### ISSUE THREAD

**Issue by CalebCox** [mbrn/material-table#701]
**Describe the bug**
`rowStyle={ height: ''}` does not work properly. If you set the height to anything under 49 pixels this fails to render properly.

**To Reproduce**
1. Create a new material table or go to https://material-table.com/#/docs/features/styling
2. Add `options={{ rowStyle: { height: '10px'}}` in your table or the example table in the official docs
3. See that the table row height does not change.

**Expected behavior**
Previously this was working, if I set the row height to 10px it should apply that style.

**Screenshots**
![materialTableRowHeight](https://user-images.githubusercontent.com/20094217/59216304-58511500-8b89-11e9-828e-11533f3a387f.jpg)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.4
 - Browser: Chrome
 - Version: 74.0.3729.169 (Official Build) (64-bit)

- Browser: Firefox
- Version: 66.0.5

**Additional context**
There is nothing indicating that another style is overriding this rowStyle change, as shown in the screenshot provided.

**Comment by mbrn** [comment]
It requires 49px at least. But i will take a look at it to decrease minimum size.

**Comment by arash-sadr** [comment]
Hi @mbrn,

Thanks for taking up this enhancement. may I knw if there is any update about this issue? :)

**Comment by EdmarPereira** [comment]
@mbrn, do you have some update related to the row height less the 49px ?

**Comment by EdmarPereira** [comment]
I found a solution for my use, I need to edit this property to change the size of the table header and table body:
.MuiTableCell-root {
height: 10px !important;
padding: 0px !important;
font-size: 0.7rem !important;
}

.MuiButtonBase-root{
height: 10px !important;
}

with this you can adjust for you
