### ISSUE TITLE
Font-size of label inside MTablePaginationInner

### ISSUE THREAD

**Issue by lucasortigoso** [mbrn/material-table#704]
I need to increase the font-size of label inside **MTablePaginationInner**. How can I do that?

https://github.com/mbrn/material-table/blob/6706ace054e36a6e188b068edcdee7c63c1aab0e/src/components/m-table-pagination.js#L54

**Comment by mbrn** [comment]
Hi @lucasortigoso 

Currently you can't with a easy way. But you can override pagination component.

**Comment by Edisonsan** [comment]
How to override the pagination component to increse the font, the font is so small, and i cant find a place to increase it.  If the solution is override pagination component could somebody help me with an example, thanks.
