### ISSUE TITLE
Add CSS class for column TD

### ISSUE THREAD

**Issue by vk-rpp** [mbrn/material-table#705]
How can I add a CSS class for particular column directly to TD element ?
Sometimes it's needed.

**Comment by mbrn** [comment]
I will look at it to find a solution

**Comment by pak11273** [comment]
If your data is dynamic then you will have to do it programmatically.  You can do this by creating a stylesheet and modify the classes that the column uses.  Use css pseudo classes to pinpoint td cells.  Refer to this [doc](https://material-ui.com/customization/components/) to find the class.

If you just want to change the column styling then refer the the material-table [doc](https://material-table.com/#/docs/features/styling)
