### ISSUE TITLE
Info about actual order of table headers

### ISSUE THREAD

**Issue by Likurg2010** [mbrn/material-table#706]
Hi. Is it any possibility to get info about actual order of table headers after drag-n-drop action?

**Comment by mbrn** [comment]
You can, It stores it in tableData field of column. You can look at your column(in state) in debug mode. 

Please reply if you cant find.

**Comment by nikhilwbhatia** [comment]
Hi, I'm struggling to find where this information is stored, I see table data on each of the rows stored in my state, but can't find anything about column ordering. Can you please elaborate?
