### ISSUE TITLE
Tree data icon style

### ISSUE THREAD

**Issue by RobelTekle** [mbrn/material-table#707]
If I active the tree-data option, how can I set the arrow icon style according to row data ? Using `options.rowStyle` I have no access to arrow_icon

**Comment by mbrn** [comment]
Hi @RobelTekle ,

Currently you can't, Why do you need a feature like this?

**Comment by RobelTekle** [comment]
Hi @mbrn ,
I'm using tree-data for my table, and I need to give a style to my rows according to their position/level in the tree (parents and children have different style). And the style concern the arrow icon too.

**Comment by mbrn** [comment]
I will think a solution for this case. It can be useful for other users too.

**Comment by gianlucamateo** [comment]
I would appreciate some styling options in general, I am trying to reduce vertical row padding, but the default iconButton is hindering me.

**Comment by farzad-jafari** [comment]
I have this problem too. is there a solution?

**Comment by gauravsoti1** [comment]
I also want to change the tree expand icon according to the row
