### ISSUE TITLE
Removing only item from last page leaves user out of page range

### ISSUE THREAD

**Issue by AndySeymour2904** [mbrn/material-table#708]
**Describe the bug**
Deleting the only item in a 10 page table leaves the user on the 10th page rather than displaying the 9th page. The pagination also reads '46-45 of 45' and 'No records to display' is visible

**To Reproduce**
1.Create multiple paged table
2. Delete last and only element
3. Observe table says 'No records to display'

**Expected behavior**
The Table should load the previous page which contains data

**Screenshots**
![image](https://user-images.githubusercontent.com/36265276/59367029-2f6c8380-8d33-11e9-9839-d330426b99b0.png)
![image](https://user-images.githubusercontent.com/36265276/59367683-81fa6f80-8d34-11e9-8816-fb856710ca64.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser Chrome

**Additional context**
Happy to put a PR in, two options from quickly skimming the code seem to be;
- Call changePage from MaterialTable component in componentWillReceiveProps
- Call changePage in Pagination component

**Comment by AndySeymour2904** [comment]
@mbrn Happy to do the work here if we agree on it, feel free to assign me and I'll crack on :)

**Comment by mbrn** [comment]
@AndySeymour2904  You can start to any issue work on. Just type comment on issue when you start and how you will resolve it. 

Thanks for your contributions.

**Comment by AndySeymour2904** [comment]
I'll take this issue today then :)

Plan is to use `dataManager.changeCurrentPage` in this method;
https://github.com/mbrn/material-table/blob/master/src/material-table.js#L52

Check whether the current page is in range and if not, change to the page at the last index
