### ISSUE TITLE
Sticky Header & Sticky Scrollbars

### ISSUE THREAD

**Issue by karrettgelley** [mbrn/material-table#709]
**Is your feature request related to a problem? Please describe.**
Yes.
There is currently no easy way to make the table header sticky. There is also not an easy way to make the horizontal scrollbar visible at all times. 

**Describe the solution you'd like**
I'd like to make the \<Paper> wrapper scrollable horizontally. I'd also like to be able to style the header using the headerStyle option such that I can apply a sticky style. I think I found a solution that solves both of these issues - see additional context.

**Additional context**
If you omit the styles of the \<Table> wrappers in src/material-table.js then I am able to solve both issues. The wrappers can be found on lines 495 and 584 and are shown to be applying 'overflowX: auto' and 'overflowY: auto'. 
After these styles are omitted, one would be able to style the outermost container using options={{ style: { overflow: scroll, height: 500px }}} which would allow the horizontal & vertical scrollbars to be shown at all times :).
Furthermore, the aforementioned problem of making the header cells sticky can then be solved by using options={{ headerStyle: { position: sticky, top: 0 }}.

**Comment by karrettgelley** [comment]
The reason I closed it is because there is a very easy solution that I found. First you need to set the header style to sticky:

options={{ headerStyle: { position: 'sticky', top: 0 } }}

This alone does not do anything. Next you need to set the body height of the table in order to trigger a vertical scrollbar to appear:

options={{ headerStyle: { position: 'sticky', top: 0 }, maxBodyHeight: '650px' }}

**Comment by mgilarmo** [comment]
Hi @karrettgelley, I am having difficulty resolving the issue.  Could you provide some clarification? (I'm really new to dev)

When you reference src/material-table.js, are you referring to something in the src folder in your project or to node_modules/material-table/dist/material-table.js?  (I'm assuming the "src" reference was just a to say go to the source code in the node mod)

Also, I'm using version 1.40.1 . . . so, if I have the correct file from above, I found "overflowX: auto" on line 522:
`          style: {
            "float": props.theme.direction === "rtl" ? "" : "right",
            overflowX: 'auto'
          },
`

and "overflowY: auto" on line 619:
`          style: {
            maxHeight: props.options.maxBodyHeight,
            overflowY: 'auto'
          }
`

Are these the correct overflow properties to remove?

Finally, a question on adding the sticky header . . . are you saying to add these lines as props within `<MaterialTable />` or within the material-table.js file from above?
`options={{ style: { overflow: scroll, height: 500px }}}`
`options={{ headerStyle: { position: 'sticky', top: 0 } }}`
`options={{ headerStyle: { position: 'sticky', top: 0 }, maxBodyHeight: '650px' }}`

Thanks, and sorry for my confusion.

**Comment by edwardmcleodjones** [comment]
For anyone wanting to avoid hard-coding the `maxBodyHeight `and make it responsive if the window is resized, hooks help make this pretty straightforward to implement.  

Take a look at: https://codesandbox.io/s/509jvrqr8n?from-embed (from: https://codesandbox.io/react-hooks) and adjust according to your needs.  I take the `height` property then subtract an offset for the table header + page header, and pass that into `maxBodyHeight`, e.g. 

```js
const { height } = useWindowResize();
...
maxBodyHeight: height - 48
```

You could use [`ref `or `react-dom`](https://davidwalsh.name/get-react-component-element) to get the header elements and find their heights instead of hard-coding the offset if you preferred.
