### ISSUE TITLE
Warning: Failed prop type: You are using a deprecated typography variant: `title` that will be removed in the next major release.

### ISSUE THREAD

**Issue by rasheedb** [mbrn/material-table#71]
When using the material-table 1.1.1 package, I receive the following warning in the browser console output.

Warning: Failed prop type: You are using a deprecated typography variant: `title` that will be removed in the next major release.

Reproduce
- Just place material-table in any render method
- Currently using REACT 16.6.0

**Comment by shelbaz** [comment]
hey @mbrn , whens next release ?...

**Comment by mbrn** [comment]
@shelbaz 

a few minutes ago :). You can upgrade to 1.2.0 now:)
