### ISSUE TITLE
Toggle detail panel on page change

### ISSUE THREAD

**Issue by crewtaylor** [mbrn/material-table#710]
Is there a way one can toggle the detail panel to closed on a page change or on other events other than rowClick?

**Comment by mbrn** [comment]
Hi @crewtaylor ,

You can call tableRef.onToggleDetailPanel(rowNum, renderPanel) if you dont use tree data or grouping feature. 

Please take a look at tableRef example: https://material-table.com/#/docs/features/remote-data (2nd example)

**Comment by AnandMM** [comment]
Hello, I am facing this issue and not able to move to next page when Detail Panel is open. Can someone please help
