### ISSUE TITLE
State change on data clears the column search input

### ISSUE THREAD

**Issue by crewtaylor** [mbrn/material-table#711]
When the state of the data into the table changes the search-by-column fields are cleared. However, the main search bar at the top right of the table does not clear out.

**Comment by elruinnou** [comment]
@mbrn Hi, has it made to the Master? or even maybe Development branch, I'd like to give it a try. Kinda desperately doing workaround the state to hold the filters value for this couple days.

**Comment by mbrn** [comment]
> @mbrn Hi, has it made to the Master? or even maybe Development branch, I'd like to give it a try. Kinda desperately doing workaround the state to hold the filters value for this couple days.

Hi @elruinnou 
 you can work on your own repo by forking this. Then you can send a pr if you test it.

**Comment by mbrn** [comment]
Actually, column filters should not clear. You can use columns in state of your parent component. So column filters will not be cleared when you update data on state.

**Comment by elruinnou** [comment]
@mbrn do you mean using defaultFilter property in column declaration, no?

**Comment by elruinnou** [comment]
@mbrn do you mean by using DefaultFilter in columns? actually that does the trick, but it will lose focus on the active filter. If only there will be any options to set the focus manually.
