### ISSUE TITLE
Hook to decide whether a cell is editable based on row data

### ISSUE THREAD

**Issue by mohitmutha** [mbrn/material-table#714]
We have a requirement where we want to edit only certain cells in the row based on other properties in the data

for e.g. if the `category` of a particular row is `VIP` then the `name` and `age` can be edited and if the `category` is `Normal` then only the `name` can be edited. 

I did not find any possibility to do this in the current implementation. 

Suggestion for implementation
- All specifying a function for the `editable` property in column definition . 
- In the `MTableEditRow` class add the below in the renderColumns function
```
 if (typeof columnDef.editable == 'function'){
    allowEditing = columnDef.editable(columnDef, this.props.data)
  }
```

**Comment by mohitmutha** [comment]
duplicate of #690

**Comment by mbrn** [comment]
I merged your pr. Thanks for contribution. I will publish it tomorrow.

**Comment by mbrn** [comment]
This is published with 1.39.1

**Comment by mohitmutha** [comment]
Thanks

**Comment by theodore-koch** [comment]
Was an example on how to use this new feature added to the documentation, or does anyone have an example?
