### ISSUE TITLE
Disable filter icon 

### ISSUE THREAD

**Issue by JKrymarys** [mbrn/material-table#716]
I am trying to disable an icon that is displayed in the filters field. Right now I am just setting non existing tag in _icons.Filter_ overrides. It's working, but also giving warning in the console. 

Is this any other supported method to disable such an icon? (except for component overriding which I imagine would be overkill for this use...)

**Comment by mbrn** [comment]
I will add a flag to options for this case.

**Comment by tobilarscheid** [comment]
Hi, any updates on this? Currently I am overriding with 
```
icons = {{ Filter: React.Fragment }}
```

but this leaves an 8px wide `MuiInputAdornment-root MuiInputAdornment-positionStart` in front of the input field - not ideal.

![image](https://user-images.githubusercontent.com/5900890/68092153-78f76f80-fe88-11e9-8637-d3d2cb7b6919.png)
