### ISSUE TITLE
Tree Data or nested child data not exported as CSV

### ISSUE THREAD

**Issue by SuhashMediboina** [mbrn/material-table#718]
Is it possible to have the following snippet download tree data that is visible on expanding rows?

`const options = {
      exportButton: true,
      exportAllData: true,
 };`

Actual: Setting `exportAllData: true,` only applies to data that is paginated and not parent-child tree nesting

Thanks!

**Comment by mbrn** [comment]
I will work on exporting according to grouping or tree features. But now i am focused on bugs.

**Comment by RegisParpex** [comment]
UP
Very useful feature

**Comment by DamilolaStem** [comment]
I am still having this problem. When I group, the data does not show up on export

**Comment by gayatridube5** [comment]
I am trying to export parent and child rows from material table with react
   options={{
                exportAllData:true,
                exportButton: true,
               }}
but still it is only exporting parent rows in csv. Please help me out with this issue

**Comment by Gabrielasalvo** [comment]
I have the same issue :(

**Comment by gayatridube5** [comment]
Try using kendo grid

**Comment by pratik-nagpure** [comment]
I observed same issue here is the [Sanbox](https://codesandbox.io/s/sharp-https-db0ujl?file=/src/App.js)

**Comment by arshadashrafi** [comment]
You can pass an `exportCsv` function to `options`. Material-table uses [filefy](https://www.npmjs.com/package/filefy) to export a csv file. You can include that package and make your own function that reads all data:
```
exportCsv: (columns) => {
        const columnTitles = columns.map((columnDef) => columnDef.title);
        const columnFields = columns.map((columnDef) => columnDef.field);
        new CsvBuilder("data.csv")
             .setColumns(columnTitles)
             .addRows(
                     // Make sure you use the original data that contains all data, not the second argument of this function (which is left out)
                     data.map((entry) => columnFields.map((field) => entry[field]))
             )
             .exportFile();
}
```
