### ISSUE TITLE
Issue with icons on search and pagination

### ISSUE THREAD

**Issue by vksantoshsunny** [mbrn/material-table#720]
I am using the latest version of react and material-table. I could see once the table is rendered the icons that are supposed to appear near the search box and also pagination in the footer are not appearing correctly. Attached a picture to show that. 

create react app and material UI installed packages and started with a very basic example of material table

**Expected behavior**

 "dependencies": {
    "material-table": "^1.39.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-scripts": "3.0.1"
  }

Using the chrome latest version web browser

![Capture](https://user-images.githubusercontent.com/26269568/59472986-7c1ba000-8e94-11e9-9b61-4f507af56304.PNG)

**Comment by mbrn** [comment]
Hi @vksantoshsunny 

Please check 2. section in this installation guide: https://material-table.com/#/docs/install
