### ISSUE TITLE
Placeholder for filtering

### ISSUE THREAD

**Issue by vk-rpp** [mbrn/material-table#723]
Hi, I can't add placeholder for the filtering. Did I miss anything ? 
Basically I found the issue, when I tried to move filtering from one particular column outside of the filtering row. For now I had to use CSS position absolute to do this, but it looks like a hack. 

I wish it is possible to use filtering with placeholder outside of the table. Thank you

PS. Any ways I found material-table really simple, useful and powerful ! Thank you for a great lib

**Comment by mbrn** [comment]
Hi @vk-rpp ,

You can use filterPlaceholder with latest version:

 { title: 'Id', field: 'id', filterPlaceholder: 'placeholder' },
