### ISSUE TITLE
Zebra rows support

### ISSUE THREAD

**Issue by vk-rpp** [mbrn/material-table#724]
**Is your feature request related to a problem? Please describe.**
I added zebra (striped table rows) via CSS hovewer it's not fully correctly worked, because when I enable filtering, the filtering row counts as the row of the table.

**Describe the solution you'd like**
Add classes to use background colors for data rows (odd, even). It would be great to have simple possibility to add "zebra". For example by adding one class for the table. Forexample:
<MaterialTable
   className="table-striped"

**Describe alternatives you've considered**
alternative is CSS :nth-child(odd)

As an example Bootstrap table striped rows:
https://getbootstrap.com/docs/4.0/content/tables/#striped-rows

**Comment by mbrn** [comment]
Hi @vk-rpp 

This is in my roadmap. It will be ready asap.

**Comment by schen3** [comment]
Any update from this enhancement?

**Comment by schen3** [comment]
This has been fixed. @mbrn 
https://github.com/mbrn/material-table/issues/598
