### ISSUE TITLE
Autofocus on a chosen column field

### ISSUE THREAD

**Issue by flyingangel** [mbrn/material-table#726]
Missing feature or how to achieve this : on new row click (to generate a new editing line), add an event hook or a way to do custom job like autofocus on a field (input, select, textarea)

Also the documentation needs to be updated. The add button is generated only if event **onRowAdd** is specified, and returning a Promise will result with a Loading screen instead of an instant update

**Comment by Totalbug92** [comment]
Is there a way to make it autofocus the first column when adding a row?

**Comment by flyingangel** [comment]
@Totalbug92 Not yet! Lots of events and callbacks are not yet added. I guess you need to use vanilla JS with onclick event

**Comment by Totalbug92** [comment]
Yes, I managed to do it by overriding the editComponent for the first column with a MaterialUI 
`<Input ... inputProps({autoFocus: true}}/>`
