### ISSUE TITLE
Warning: Prop `data-react-beautiful-dnd-draggable` did not match. Server: "2" Client: "0"

### ISSUE THREAD

**Issue by locona** [mbrn/material-table#727]
**Bug?**
Showing the above warning

```
Warning: Prop `data-react-beautiful-dnd-draggable` did not match. Server: "2" Client: "0"
```

**Environment**
* next.js: 8.1.0
* material-ui/core: ^4.1.1
* material-table: 1.39.1

**May be related**
* https://github.com/atlassian/react-beautiful-dnd/issues/1196
* https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/api/reset-server-context.md

**Comment by emrekara37** [comment]
Hi @locona 
Check https://github.com/atlassian/react-beautiful-dnd/issues/1196

**Comment by locona** [comment]
oh, thank you!
