### ISSUE TITLE
selected lookup field is getting refreshed when setStatus is touched for opening the dialogue.

### ISSUE THREAD

**Issue by kumar-prashant16** [mbrn/material-table#729]
**Describe the bug**
after selecting the lookup data, it filters accourding to data, but when opening the dialogue box, which is get triggered by setState, its resetting the lookup field selection to normal. 
**To Reproduce**
1. Go and select the Lookup field
2. Click on Open dialogue module, which should be on row data
3. You can see that, the selected Lookup field data is gone, and resetted to normal, even if we didnt touched the lookup data.
4. See error in images. 

**Expected behavior**
the lookup data filter value should be retained, as it was, when ever the data is set through setState method.
**Screenshots**
Added Screen sort. 

**Desktop (please complete the following information):**
 - OS: windows10
 - Browser: chrome
 - Version : 75.0.3770.90 

**Smartphone (please complete the following information):**
NA
<img width="938" alt="Step 2 - after clicking on openmodel, lookup field selection gets refreshed" src="https://user-images.githubusercontent.com/50446092/59603523-3f1b0c00-9127-11e9-8385-af97693ebd3a.PNG">
<img width="954" alt="Step-1_selecting the lookup filter value" src="https://user-images.githubusercontent.com/50446092/59603524-3fb3a280-9127-11e9-9b7e-c0c0293109d9.PNG">

**Additional context**

**Comment by kumar-prashant16** [comment]
please help resolving it. 
steps in decreasing order image.

**Comment by kumar-prashant16** [comment]
@mbrn how do i solve it?

If there is a filter selected and there is an popup dialogue box needed to open, we need to set the state for opening Dialogue Box. but when you touches the setState, it clears the lookup filtered value to initial. 

thanks for assistance.  :-)

**Comment by kumar-prashant16** [comment]
@emrekara37 Hi Sir, when can i expect it to be resolved?

**Comment by chongsoon** [comment]
Hi @kumar-prashant16 , I was facing the same issue, but I found out in #160 , you could set the column definition in the state first, and load the state variable instead. Not sure if this is considered a solution or workaround.
