### ISSUE TITLE
Add image type to field display

### ISSUE THREAD

**Issue by ledinhtri97** [mbrn/material-table#733]
I need to add image display in field Thumbnail, but now in type of display have only ```Data type: 'boolean', 'numeric', 'date', 'datetime', 'time', 'currency'``` 

How can I add image to display, if exist feature, please let's me know more information. Thank you!

**Comment by AntoniusGolly** [comment]
You can use the custom `render` method of the cell. Please have a look at the custom rendering section. It has an example with an image, I think.

**Comment by sadhruva** [comment]
create custom component:
like  const Image= <img style={{height:'100px',width:'100px'}} src={require('../img/logo.png')} />

        <MaterialTable
          columns={[
          **{ title: 'Adı', field: 'render' },**
            { title: 'Adı', field: 'name' },
            { title: 'Soyadı', field: 'surname' },
            { title: 'Doğum Yılı', field: 'birthYear', type: 'numeric' },
            { title: 'Doğum Yeri', field: 'birthCity', lookup: { 34: 'İstanbul', 63: 'Şanlıurfa' } }
          ]}
          data={[{ **render:Image,** name: 'Mehmet', surname: 'Baran', birthYear: 1987, birthCity: 63 }]}
          title="Demo Title"
        />
 
it should work.
