### ISSUE TITLE
Support adding an ID to table, row, and cell.

### ISSUE THREAD

**Issue by mviens** [mbrn/material-table#735]
**Is your feature request related to a problem? Please describe.**
For styling and testing purposes, it is necessary to be able to add an ID to the table and each row and cell.

**Describe the solution you'd like**
Having an `id` property that can be set would solve this. For the table, this property should be able to be set directly, in the same manner as `title`. For the rows, it seems appropriate that the property should specify a prefix and then have the row number appended to it. The same could apply for cells, or the calculated ID for the row could be used and further append the column number to it. Within the column configuration, a column ID should also be able to be specified.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by sshanzel** [comment]
How can i contribute?

**Comment by therohitjha** [comment]
> **Is your feature request related to a problem? Please describe.**
> For styling and testing purposes, it is necessary to be able to add an ID to the table and each row and cell.
> 
> **Describe the solution you'd like**
> Having an `id` property that can be set would solve this. For the table, this property should be able to be set directly, in the same manner as `title`. For the rows, it seems appropriate that the property should specify a prefix and then have the row number appended to it. The same could apply for cells, or the calculated ID for the row could be used and further append the column number to it. Within the column configuration, a column ID should also be able to be specified.
> 
> **Describe alternatives you've considered**
> n/a
> 
> **Additional context**
> n/a

just follow the bellow screenshot ;)
<img width="337" alt="Capture" src="https://user-images.githubusercontent.com/45750703/72609738-b2019500-394b-11ea-83c2-a20410b9810c.PNG">

**Comment by Soquar** [comment]
I need the same feature  as mviens for the testautomation to find the cells.

therohitjha doesnt work, because i dont want to have a column with the index in table, but that every cell has a unique id

**Comment by panipinaka** [comment]
I need the same feature for the testautomation to find the cells.

**Comment by Gayathri1996** [comment]
Hi,

I need to add id to the each table header and pagination elements.


  <MaterialTable
      title=""
      icons={tableIcons}
      columns={columns}
      data={data}
      options={{
        draggable: false,
        actionsColumnIndex: -1,
        actionsCellStyle: {
          display: "flex",
          justifyContent: "center",
          minHeight: "54px",
          width: "100%",
          marginBottom: "-1px",
        },
        search: false,
      }}
/>

Adding customized header and pagination making the code very lengthy. Is there any way to add the id to the column header cell and pagination in a simple way?
