### ISSUE TITLE
How to specify column alignment?

### ISSUE THREAD

**Issue by mviens** [mbrn/material-table#736]
I do not see how to specify the `MuiTableCell-alignCenter` or `MuiTableCell-alignRight` values. All of the cells are being applied with `MuiTableCell-alignLeft`. As a terrible work-around, I am having to apply hacky CSS styles to override the left alignment. 

In general, it seems the properties supported by MuiTable are not available to use for MaterialTable, unless I am misunderstanding something. I would appreciate any assistance. Thanks.

This is the SandBox I have been working with, which was forked from the main one listed on the Material-UI website:  https://codesandbox.io/s/material-demo-s0x7t

Ultimately, I want the first table to have columns that are centered, except the first column. For the second table, I want only the last column to be centered.

**Comment by mbrn** [comment]
Hi @mviens 

I will check this asap.

**Comment by kl1mm** [comment]
When can we expect the fix?

**Comment by mbrn** [comment]
> When can we expect the fix?

Hi @kl1mm ,

I will return back to material-table in 2 weeks. And i won't take more freelance jobs until resolve most of issues :). Thanks for your patience and support.

**Comment by kl1mm** [comment]
Thanks for the reply.

**Comment by chitgoks** [comment]
Up

**Comment by Dobata7** [comment]
Up
