### ISSUE TITLE
Error : getFieldValue is not a function when editing a child (Tree Data)

### ISSUE THREAD

**Issue by jessy-bgl** [mbrn/material-table#739]
**Describe the bug**
When I click on the "edit" action button of a child row of a Tree Data table **with parameter _editable: "onAdd"_ on one of the columns**, I get the error : 

> Uncaught TypeError: _this2.props.getFieldValue is not a function

**To Reproduce**
1. Create a Tree Data table **with the parameter editable: "onAdd" on (at least) one column**
2. Add a row
3. Add one or more children to this row
4. Click on the Edit action button
5. See the error

**Expected behavior**
Ability to edit the fields of the row.

**Screenshots**
![image](https://user-images.githubusercontent.com/51905435/59837458-93073a00-934d-11e9-876e-f2d8f266f147.png)

> Clicking on the edit action button of the row "groupe10" :

![image](https://user-images.githubusercontent.com/51905435/59837473-9995b180-934d-11e9-97c7-bba12122d304.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Chrome
 - Version 74.0.3729.169

**Comment by Xzas22** [comment]
Having the same error message pop up. Everything appears to work correctly, but the React error is concerning.

**Comment by theodore-koch** [comment]
Same here when setting editable param to 'never'

**Comment by foramshah1112** [comment]
Getting the same error on clicking Add Icon for the first time after page loads, when using editComponent, later the error goes away on it's own.

**Comment by jayarjo** [comment]
Same here. Also would be great to have column drag&drop logic configurable, so that it could be switched off if required (observing the same `react-beautiful-dnd` error here).

**Comment by HazilMohamed** [comment]
Is there any fix available right now??

**Comment by cristiadis** [comment]
Same issue here. Adding "editable: 'never'" to a column causes the issue when clicking on Edit.

**Comment by RamilMamedo** [comment]
any updated on this? ☹️

**Comment by Tobbe129** [comment]
Please open this again, its not fixed!
