### ISSUE TITLE
Warning: Failed prop type: Invalid prop `data` of type `array` supplied to `MTableActions`, expected `object`.

### ISSUE THREAD

**Issue by balibou** [mbrn/material-table#74]
**Describe the bug**
When I copy paste the code of https://mbrn.github.io/material-table/#/docz-examples-example-selection in a new create react app and I select a row, I have the following warning:

```Warning: Failed prop type: Invalid prop `data` of type `array` supplied to `MTableActions`, expected `object`.```

**To Reproduce**
1. install last create-react-app
2. install the package (1.1.2)
3. copy the code of selection example
4. click to select a row
5. See warning

**Expected behavior**
No warning displayed

**Comment by mbrn** [comment]
Hi @balibou,

Thanks your your issue. I resolved it and it will be in next release. Please star repo and wait for next releases

**Comment by RodolfoHill** [comment]
I have the same problem in Oct 19 - 2019. 

I am using material-table     "^1.50.0"

index.js:1375 Warning: Failed prop type: Invalid prop `data` supplied to `MaterialTable`.
    in MaterialTable
    in Unknown (created by WithStyles(Component))
    in WithStyles(Component) (at ProgramDetailTable.js:213)
    in div (at ProgramDetailTable.js:212)

**Comment by rustycoslett** [comment]
I also have the same problem on just 1 of my tables, but not the other 6.  Very strange.

**Comment by LuminousIT** [comment]
I have the same issue on 1 out of about 15+ tables in my portal.. What could be wrong?

**Comment by spaceneurocruzz** [comment]
> I have the same problem in Oct 19 - 2019.
> 
> I am using material-table "^1.50.0"
> 
> index.js:1375 Warning: Failed prop type: Invalid prop `data` supplied to `MaterialTable`.
> in MaterialTable
> in Unknown (created by WithStyles(Component))
> in WithStyles(Component) (at ProgramDetailTable.js:213)
> in div (at ProgramDetailTable.js:212)

@RodolfoHill have you solved this? I encountered the same problem today.

**Comment by himanshuvashist** [comment]
I am still having this problem
i am using `"material-table": "^1.69.1",`
```
Warning: Failed prop type: Invalid prop `data` supplied to `MaterialTable`.
    in MaterialTable
    in Unknown (created by WithStyles(Component))
    in WithStyles(Component) (at loanlist.js:189)
...
```
```
<MaterialTable
          columns={this.state.columns}
          data={this.state.data}
```

this warning comes from this snippet of code
![image](https://user-images.githubusercontent.com/35025815/97272141-7d662680-1857-11eb-8000-80b980becff0.png)

```
    let updatedData = [...this.state.data];
    updatedData[e.tableData.id].status = "rejected";
    console.log(updatedData)
    this.setState({ data: updatedData },()=>{
      console.log(this.state)
    });
```
![image](https://user-images.githubusercontent.com/35025815/97271996-4db71e80-1857-11eb-945e-4eb4a4036af6.png)
