### ISSUE TITLE
Add icon before title

### ISSUE THREAD

**Issue by mqasim1990** [mbrn/material-table#740]
Hi everyone how can i add an icon before title ?

like this 
![image](https://user-images.githubusercontent.com/23281307/59837081-13d23000-9366-11e9-8ff1-162aafc88828.png)

**Comment by AugustoCalaca** [comment]
Yeah, it is possible.

Example:
```
components={{
  Toolbar: props => (
    <div style={{display: 'flex', alignItems: 'center', }}>
      <YourIcon />
      <MTableToolbar {...props} />
    </div>
  ),
}}
```

You can add other styles or components to your liking in toolbar.

**Comment by mqasim1990** [comment]
> Yeah, it is possible.
> 
> Example:
> 
> ```
> components={{
>   Toolbar: props => (
>     <div style={{display: 'flex', alignItems: 'center', }}>
>       <YourIcon />
>       <MTableToolbar {...props} />
>     </div>
>   ),
> }}
> ```
> 
> You can add other styles or components to your liking in toolbar.

It works thanks @AugustoCalaca
