### ISSUE TITLE
Hide row option from pagination

### ISSUE THREAD

**Issue by mqasim1990** [mbrn/material-table#741]
Hi everyone how can i hide only rows option from table pagination
![image](https://user-images.githubusercontent.com/23281307/59868062-4f421e00-93a9-11e9-80e3-a4c5ca983b0d.png)

**Comment by mbrn** [comment]
Hi @mqasim1990,

You can override localization with empty text. 

![image](https://user-images.githubusercontent.com/7895451/60486656-b31cee80-9ca7-11e9-8e61-947e417661df.png)
