### ISSUE TITLE
How to force Detail Panel to rerender?

### ISSUE THREAD

**Issue by behrouz-s** [mbrn/material-table#742]
Detail panel don't get updated, unless I close and reopen it.
How to rerender detail panel?

**Comment by behrouz-s** [comment]
I solved the problem by connecting "Detail Panel" component to "store" directly.

**Comment by hcsgzh** [comment]
@behrouz-s I have the same problem as yours. Can you tell me how to connect "Detail Panel" component to "store" directly?  Thanks!

**Comment by behrouz-s** [comment]
@hcsgzh you should design a detail panel as separated component then design a container and connect your detail panel component to the container.
[Redux usage with React](https://redux.js.org/basics/usage-with-react)
