### ISSUE TITLE
Remove warning for invalid column type

### ISSUE THREAD

**Issue by sornman** [mbrn/material-table#745]
**Is your feature request related to a problem? Please describe.**
When specifying a custom column type, the following error occurs:

`Warning: Failed prop type: Invalid prop 'columns[1].type' of value 'textarea' supplied to 'MaterialTable', expected one of ["string","boolean","numeric","date","datetime","time","currency"].`

**Describe the solution you'd like**
Remove the warning if it encounters a type that it doesn't recognize.

**Additional context**
I am using custom column types, specifically 'select', to trigger a react-select dropdown, and 'textarea'. To accomplish this, I use:

`components={{
EditField: props => {
if (props.columnDef.type === 'select') { ...
} else if (props.columnDef.type === 'textarea') { ...
}
}
}}`

Everything seems to be working great, except for the above warning message in the console.

**Comment by Domino987** [comment]
IS this still a problem?
