### ISSUE TITLE
Change onClick for edit icon

### ISSUE THREAD

**Issue by sornman** [mbrn/material-table#747]
Is it possible to override the onclick for the edit icon for an editable table? I have been trying with several suggestions from the git issues (components={{ Action: ...), but can't find a way to just specify the edit button. I have some table entries that are only showing a few columns, and I want to make the edit button go to a page where they can edit all the information.

**Comment by mbrn** [comment]
Hi @sornman,

you can add your custom action with any icon or override edit icon with this code:
icons:{{
Edit: props => <YourIcon/>
}}

**Comment by sornman** [comment]
@mbrn So something like this? How do I get the rowData?
`
          icons={{
            ...tableIcons,
            Edit: props => {
              let rowData = {id: 1};
              // if editPage, go to separate page
              if (this.props.editPage === true) {
                return <Edit onClick={e => this.editPage(e, rowData)} />;
              }
              // edit inline, default behavior
              return <Edit />;
            }
          }}

editPage = (e, rowData) => {
  window.location = somepath + rowData.id;
}
`
The only thing coming through in props is {disabled: undefined}. Also, when I set rowData such as in the code above, it still flashes the inline editing fields before forwarding to the edit page. How can I get that action to stop?

**Comment by sornman** [comment]
Well, I didn't end up reassigning the onClick for the edit icon when my this.props.editPage is set, instead providing a custom actions entry. I lose the 'Delete' action, but I am handling it on my custom edit page already so it isn't a big deal. For those of you wanting to do something similar, here is what I did.
```
import ViewIcon from '@material-ui/icons/OpenInNew';
const ViewButton = props => <ViewIcon {...props} />;
...
<MaterialTable
  editable={this.props.editPage ? false :
    {
      onRowAdd: ...
      onRowUpdate: ...
      onRowDelete: ...
    },
  }
  actions={!this.props.editPage ? [] :
    [{
      icon: props => ViewButton(props),
      tooltip: 'View',
      onClick: (event, rowData) => {
        let pathName = window.location.pathname;
        if (!pathName.endsWith('/')) pathName += '/';
        window.location = pathName + rowData.id;
      }
    }]
  }
/>
```
