### ISSUE TITLE
Preselect functionality

### ISSUE THREAD

**Issue by artus9033** [mbrn/material-table#749]
**Is your feature request related to a problem? Please describe.**
The project lacks support for a mechanism for preselection, e.g. when the table is used as a selection component and loads available items from an API endpoint, some of which may have already been selected; then, the only way to skip the already selected elements from being shown as unselected (without the checkbox ticked) is to filter them out from the data array, so that they are not shown at all.

**Describe the solution you'd like**
The project should implement a property either on the table component or within the data prop that would allow to mark some of the rows as already selected

**Comment by mbrn** [comment]
Hi @artus9033,

I may add a new field to response of promise to preselect, filter etc on some rows. This is good idea. I will do this asap.

**Comment by artus9033** [comment]
@mbrn, thank you!

**Comment by jasonvooo** [comment]
Any update on this feature?

**Comment by jasonvooo** [comment]
@artus9033 have found a way to preselect the data. For each row the table reads from the tableData attribute on the row data.
```javascript
tableData: {
   checked: true
}
```

**Comment by maamve** [comment]
I was able to do this by adding a selectionProps in the options.
`selectionProps: rowData => ({
              checked: rowData.isSelected
            })`

but i have the problem that the "Select All" on the header breaks if i do this. This logic seems to just override the display of the check but no the state of the row

**Comment by t72o** [comment]
We can control checked status like this:
> 
> 
> Hi @gmumdzhiev ,
> 
> Can you try this:
> 
> ```js-jsx
> options={{
> 
>            selection: true,
>           selectionProps: rowData => ({
>               checked: rowData.name === "Mehmet",
>               onClick: (event , rowData) => this.handleCheckboxClick(event,rowData),
>           })
>         }}
> ```

found here https://github.com/mbrn/material-table/issues/1356
