### ISSUE TITLE
Fix sorting numbers when hiding column

### ISSUE THREAD

**Issue by balibou** [mbrn/material-table#75]
**Describe the bug**
On https://mbrn.github.io/material-table/#/docz-examples-example-options when hiding column 'name' and sorting multiple times column 'birth year', the sorting is broken

**To Reproduce**
1. Go to https://mbrn.github.io/material-table/#/docz-examples-example-options
2. Click on 'Show columns'
3. Uncheck 'name'
4. Sorting multiple times column 'birth year'
5. See bug

**Expected behavior**
Sorting should be working multiple times

**Comment by mbrn** [comment]
Thanks @balibou , I resolved it. It will be in next release.
