### ISSUE TITLE
Accessing filtered data as an object

### ISSUE THREAD

**Issue by mathgeek12** [mbrn/material-table#752]
Is there anyway to capture the data that has been filtered to use for data viz?
I want the data supplied to my graph to be based on the data rendered in the table, if its filtered i want the data in the graph to update.

**Comment by MaxLeiter** [comment]
bump? Anyone have ideas?

**Comment by tylercaceres** [comment]
Any update on this?

**Comment by codenamethanos** [comment]
If someone needs a simple datatable with summary footer row this should work - https://github.com/codenamethanos/materialui-table 
Just 500 lines of code
