### ISSUE TITLE
Prevent column reordering

### ISSUE THREAD

**Issue by xiaomaini** [mbrn/material-table#753]
Any way to prevent the user from moving the columns around?

**Comment by gianlucamateo** [comment]
I checked the code the other day, and there doesn't seem to be one. It should be fairly simple to implement.

`let content = (
          <Draggable
            key={columnDef.tableData.id}
            draggableId={columnDef.tableData.id.toString()}
            index={index}>
            {(provided, snapshot) => (
              <div
                ref={provided.innerRef}
                {...provided.draggableProps}
                {...provided.dragHandleProps}
              // style={this.getItemStyle(snapshot.isDragging, provided.draggableProps.style)}
              >
                {columnDef.title}
              </div>
            )}
          </Draggable>
        );`

This is a react-beautiful-dnd component that is inserted into each header cell. With an additional parameter in props.options, this could be changed to only use something like 
`<div>
                {columnDef.title}
</div>`

**Comment by xiaomaini** [comment]
Thanks, I will take a look later and create a PR if there is no objections to adding such a feature.

**Comment by iamwilson** [comment]
I thought being able to drag the columns was a feature. I find it cool.

**Comment by gianlucamateo** [comment]
I also like the feature. But I think it can get in the way of some functionality and custom components. It would therefore appropriate to make it optional, or ideally opt-out.

In my use case I am rendering a second row in the header with controls that control some column properties, and am using a fixed layout with computed widths. Moving columns around in that scenario is not pretty.

**Comment by mviens** [comment]
@xiaomaini Please do implement this as it is not always desirable to have some columns be draggable.

**Comment by manishco** [comment]
> any updates to this would be great as its a feature we're looking for as well

See #779
