### ISSUE TITLE
MTableGroupbar

### ISSUE THREAD

**Issue by Domino987** [mbrn/material-table#755]
The documentation of [Component Overriding](https://material-table.com/#/docs/features/component-overriding) is wrong because the Groupbar field requires a MTableGroupbar element not a MTableFilterRow as described. I don know where you moved the docs for libzy material-table or else I would have created a PR to address this.
Thank you !!

**Comment by emrekara37** [comment]
Hi @Domino987 
Documentation [Repo](https://github.com/mbrn/material-table.com)

**Comment by emrekara37** [comment]
Fix [PR](https://github.com/mbrn/material-table.com/pull/4)

**Comment by Domino987** [comment]
Thank you. I didn't have the time.
