### ISSUE TITLE
Is it possible to order action items?

### ISSUE THREAD

**Issue by OscarGalindo** [mbrn/material-table#757]
Hi guys!!

One simple question, it's possible to move edit icon (that is included automatically as an action if table is editable) in the position that I want?

In the image, I want the "More options" button after the edit icon, is it possible?

![image](https://user-images.githubusercontent.com/1871363/60113037-3bb00200-9771-11e9-9502-ec967258452f.png)

Thank you so much!

**Comment by OscarGalindo** [comment]
Tried something overriding Actions but obviously I broke once I click on edit, the icons for tick and close were override too

**Comment by TheWoodStudio** [comment]
Same question here. Can't move default icons (onRowUpdate, onRowDelete)

**Comment by nikhilwbhatia** [comment]
Also trying to do this...

**Comment by thelazydogsback** [comment]
Also need to do this -- or at least separate free actions from row actions. (Maybe free action to the left of search and row actions to the right.

**Comment by Sefton419** [comment]
I am experiencing this issue as well - it should definitely not be considered stale.

**Comment by domisProgrammingMemes** [comment]
I do also experience this issue and would like to have it solved.

**Comment by jaipatel248** [comment]
Yeah facing the same issue

**Comment by jaipatel248** [comment]
> Hi guys!!
> 
> One simple question, it's possible to move edit icon (that is included automatically as an action if table is editable) in the position that I want?
> 
> In the image, I want the "More options" button after the edit icon, is it possible?
> 
> ![image](https://user-images.githubusercontent.com/1871363/60113037-3bb00200-9771-11e9-9502-ec967258452f.png)
> 
> Thank you so much!

You can use options's actionsCellStyle field if you want to reverse the order of buttons 
I was facing the same issue I fixed using 

`
            options={{
                actionsColumnIndex: 99,
                actionsCellStyle: {
                    direction: 'rtl',
                },
            }}
`
