### ISSUE TITLE
Displaying number 0

### ISSUE THREAD

**Issue by balibou** [mbrn/material-table#76]
Hello !

It would be nice to have the possibility to display number 0 in the row (for now it is hidden)

Thanks !

PS: awesome package 😃

**Comment by mbrn** [comment]
@balibou ,

i didn't understand what you mean. Can you explain, please?

**Comment by mbrn** [comment]
I got it and resolved it:). It will be in next release. Thanks for your all contributions @balibou .

**Comment by balibou** [comment]
😃 thanks for these quick replies and fixes !
