### ISSUE TITLE
Tree data does not indent

### ISSUE THREAD

**Issue by jakeleventhal** [mbrn/material-table#760]
**Describe the bug**
Tree data does not indent when dropped down

**To Reproduce**
1. Create tree data with multiple dropdowns
2. Expand each row

**Expected behavior**
The title for each dropdown should be indented to show that it is a child of the parent - just like how the arrows indent. The behavior is also correct on grouped tables

**Screenshots**
<img width="376" alt="Screen Shot 2019-06-25 at 7 16 00 PM" src="https://user-images.githubusercontent.com/15133828/60139915-c3037280-977d-11e9-9a0b-a66bff464503.png">

**Comment by jakeleventhal** [comment]
It should be a prop because sometimes this behavior is desired

**Comment by waisbek** [comment]
Any update about this issue, please?

**Comment by benjaminvdb** [comment]
I'm also looking for a solution!

PS: material-table is awesome 😃

**Comment by emrekara37** [comment]
Hi everyone 
We will fix asap

**Comment by dnn5b** [comment]
There's a [pull request](https://github.com/mbrn/material-table/pull/1057) for this. Any feedback?

**Comment by blshort43** [comment]
Any solution to this yet?

**Comment by jakeleventhal** [comment]
not stale!

**Comment by Phillip-Kemper** [comment]
not stale. I would greatly appreciate if the Pull Request could be merged in as I would love to continue using material-table and do prefer it over lower level table libraries..

**Comment by asharafshahi** [comment]
This could be accomplished with a simple custom column render function.  Just render a <div> and pass in a left padding according to the depth of the tree the row is at

**Comment by jakeleventhal** [comment]
no stale

**Comment by PhilObi** [comment]
Has there been any solutions for this?

**Comment by lpandzic** [comment]
```
 columns={[
                                {
                                    title: 'Service Unique Name',
                                    type: 'string',
                                    field: 'serviceUniqueName',
                                    editable: 'never',
                                    cellStyle: (rowDataArray, rowData) => {
                                        const paddingLeft = 30 * rowData.level;
                                        console.log(paddingLeft)
                                        return ({ paddingLeft: paddingLeft} as React.CSSProperties)
                                    }
                                },
```

**Comment by lpandzic** [comment]
Here's my solution:

```
 columns={[
    {
        title: 'FooBar',
        type: 'string',
        field: 'fooBar',
        cellStyle: (rowDataArray, rowData) => {
            const paddingLeft = 30 * rowData.level;
            console.log(paddingLeft)
            return ({ paddingLeft: paddingLeft} as React.CSSProperties)
        }
    },
 ```
 Note that you have to compute the level property (depth) and add it to data.

**Comment by jakeleventhal** [comment]
not stale
