### ISSUE TITLE
Warning: Failed prop type: Invalid prop `actions[0]` supplied to `MaterialTable`.

### ISSUE THREAD

**Issue by Captainlonate** [mbrn/material-table#761]
**Describe the bug**
The following appears in the console: `Warning: Failed prop type: Invalid prop `actions[0]` supplied to `MaterialTable`.`
```
"@material-ui/core": "^4.1.3",
"@material-ui/icons": "^4.2.1",
"material-table": "^1.40.0",
```

**To Reproduce**
1. Make a new MaterialTable
2. add the `actions` prop to it like so:
```
actions={[
  {
    icon: tableIcons['Edit'],
    tooltip: 'Edit Collateral',
    onClick: (event, rowData) => {
      console.log("Clicked", rowData);
    }
  }
]}
```
`Note that you can use Edit, or tableIcons['Edit'] and get the same warning in the console`

`Note that if you pass a string instead, no prop type failure, but the icon doesn't show up. Instead you just see the first couple of letters of whatever you type. But again, no prop type failure. But I don't want text, I want an icon.`

`Note that I just copy and pasted the starter code, and all I changed was this action prop`

`Note that "Edit" is from the following starter code (trimmed down for brevity)`
```
import Edit from '@material-ui/icons/Edit'

const tableIcons = {
  ...
  Edit: forwardRef((props, ref) => <Edit {...props} ref={ref} />),
  ...
}
```

**Expected behavior**
No prop type failure

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome
 - Version 75.0.3770.100

**Comment by Kove11** [comment]
I am also experiencing this same error when passing an icon component in the actions. `index.js:1437 Warning: Failed prop type: Invalid prop `actions[0]` supplied to `MaterialTable`.`

**Comment by Kove11** [comment]
Per #127 

You can fix this error by passing an icon like so:  `icon: () => <Edit/>`

**Comment by oze4** [comment]
> 
> 
> Per #127
> 
> You can fix this error by passing an icon like so: `icon: () => <Edit/>`

This did not work for me... Any suggestions? I've tried just about everything.

**Comment by nikhilwbhatia** [comment]
That fix worked for me, why does this syntax fix this issue? What is it about wrapping it in a function that makes it valid?

**Comment by nikhilwbhatia** [comment]
+1, Kove's change got rid of that error but then breaks the selection part when it tries to display my icon after selecting a row

**Comment by oze4** [comment]
I wonder what I'm doing wrong...that syntax doesn't fix this for me :(

**Comment by oze4** [comment]
I FINALLY FOUND A FIX!

I was previously supplying my `actions` as objects like this:

```
actions={[{
    icon: () => <LocationCityOutlined />,
    tooltip: <Typography>ABC</Typography>,
    onClick: (event, rowData) => handleAction(event, rowData, "abc")
}, {
    icon: () => <Opacity />,
    tooltip: (<Typography>XYZ</Typography>),
    onClick: (event, rowData) => handleAction(event, rowData, "xyz")
}]}
```

_Changing each action to a **`function`** resolved this for me!!!_

### **THE FIX:**

```
actions={[
    rowData => ({
        icon: () => <LocationCityOutlined />,
        tooltip: <Typography>ABC</Typography>,
        onClick: (event, rowData) => handleAction(event, rowData, "abc")
    }), 
    rowData => ({
        icon: () => <Opacity />,
        tooltip: (<Typography>XYZ</Typography>),
        onClick: (event, rowData) => handleAction(event, rowData, "xyz")
    })
]}
```

**Comment by nikhilwbhatia** [comment]
Worked for me, thanks!!

**Comment by nikhilwbhatia** [comment]
Just realized this seems to fix the above issue, but iconProps no longer works when defining actions like this

**Comment by nadundr** [comment]
This is partially resolved.
@oze4 solution only work for row action icons. If you need a **isFreeAction:true** then it won't work as expected.

![image](https://user-images.githubusercontent.com/193364/107218247-55878100-6a4a-11eb-8ada-87de2c7378b0.png)

If I put the last action inside a rowData it won't display in the intended location.

![image](https://user-images.githubusercontent.com/193364/107218583-c5960700-6a4a-11eb-833a-7144005c1543.png)

intended location:

![image](https://user-images.githubusercontent.com/193364/107219089-8ae09e80-6a4b-11eb-8783-8e0cd6c27475.png)
