### ISSUE TITLE
Fixed Columns

### ISSUE THREAD

**Issue by francesco-clementi** [mbrn/material-table#765]
Is there a way to fix the position of the first column in a table with over 40 columns?

**Comment by dnn5b** [comment]
Created a [PR](https://github.com/mbrn/material-table/pull/1076) for this feature. What do you think about it?

**Comment by francesco-clementi-bip** [comment]
Hi dnn5b,
actually I was looking for another kind of fixed columns. 

As shown in the attachment, I'd like to fixed the column when I use the stick on the down.

I'd like that when I'm scrolling right I can be able to still see the first columns.

![image](https://user-images.githubusercontent.com/50021302/64433112-21be6400-d0be-11e9-92a6-79c32f252119.png)

**Comment by ShevaShen** [comment]
I was able to fix the first column (action column) by applying some CSS.

`const useStyles = makeStyles({
  stickyActionsColumn: {
    '& table:first-child': {
      '& tr': {
        '& td:first-child, th:first-child': {
          backgroundColor: '#f5f5f5',
          position: 'sticky',
          left: 0,
          zIndex: 999
        },
        '& th:first-child': {
          zIndex: 9999
        }
      }
    }
  }
});`

**Comment by francesco-clementi-bip** [comment]
@ShevaShen thanks sheva, your help is really appreciated,.
I managed to fixed the header of the actions column.
Could it be possibile to fix not only the header, but the whole column?

**Comment by ShevaShen** [comment]
@francesco-clementi-bip if you apply the style to the parent div of the table, this should fix the whole first column

**Comment by codenamethanos** [comment]
https://material-table.com/#/docs/features/fixed-columns 
Seems to be solved?

**Comment by ShevaShen** [comment]
right, saw it in the new release https://github.com/mbrn/material-table/issues/43

**Comment by javed-ahmad** [comment]
looking for same solution with sticky header any suggestion?
