### ISSUE TITLE
Add support for className

### ISSUE THREAD

**Issue by mviens** [mbrn/material-table#766]
**Is your feature request related to a problem? Please describe.**
While there is support for `<MaterialTable style={{}} ... />`, there does not seem to be support for `<MaterialTable className={} ... />`.

**Describe the solution you'd like**
I want to be able to define a CSS class name using `<MaterialTable className={classes.myTable} ... />` or `<MaterialTable className='myTable' ... />`..

**Describe alternatives you've considered**
Wrapping the `<MaterialTable />` in a `<div>` and using CSS to find it that way (hacky).

**Comment by pak11273** [comment]
So we don't bloat the codebase, there is no need to add a className since we can already style material table with either style or by overriding the Container component like this:

````
<MaterialTable
     Container: props => (
      <div style={{ ... }}>
        <div {...props} />
      </div>
    )
</MaterialTable>
````

**Comment by sabbin** [comment]
Thanks for the response, I tried that but that actually wraps the `Toolbar` inside a `div` which has `padding:0`. It does not apply the `padding` prop to the `MToolbar` component.

The result is the following 

```html
<div style="padding: 0px;">
    <div class="class="MuiToolbar-root MuiToolbar-regular MTableToolbar-root-420 MuiToolbar-gutters">...</div>
</div>
```

I need to remove the padding from the child `div`, in this case the `MuiToolbar-root`

**Comment by pak11273** [comment]
Do it inside the Toolbar as shown in the [documentation](https://material-table.com/#/docs/features/component-overriding):

````
components={{
          Toolbar: props => (
            <div>
              <MTableToolbar {...props} />
              <div style={{padding: '0px 10px'}}>
                <Chip label="Chip 1" color="secondary" style={{marginRight: 5}}/>
                <Chip label="Chip 2" color="secondary" style={{marginRight: 5}}/>
                <Chip label="Chip 3" color="secondary" style={{marginRight: 5}}/>
                <Chip label="Chip 4" color="secondary" style={{marginRight: 5}}/>
                <Chip label="Chip 5" color="secondary" style={{marginRight: 5}}/>
              </div>
            </div>
          ),
        }}
````

**Comment by sabbin** [comment]
That does not work either.. it just creates another div beside the `<MTableToolbar/>` 

Look at the images below

![Screenshot 2019-09-16 at 11 56 22](https://user-images.githubusercontent.com/12841157/64945554-7362ad80-d879-11e9-8d43-dfc1dc6fc00d.png)

![Screenshot 2019-09-16 at 11 55 40](https://user-images.githubusercontent.com/12841157/64945568-78276180-d879-11e9-9a3b-3ce876aaeffa.png)

I need to remove the padding from `<div class="MuiToolbar-root MuiToolbar-regular MTableToolbar-root-420 MuiToolbar-gutters">...</div>` not to add other `<div>` elements

**Comment by andriymiz** [comment]
You can override styles by `withStyles()`.
```
const StyledMTableToolbar = withStyles({
  root: {
    paddingLeft: 0,
    paddingRight: 0,
  },
})(MTableToolbar);
```

```
components={{
  Toolbar: props => (
    <StyledMTableToolbar {...props} />
  )
}}
```

**Comment by loolooii** [comment]
> So we don't bloat the codebase, there is no need to add a className since we can already style material table with either style or by overriding the Container component like this:
> 
> ```
> <MaterialTable
>      Container: props => (
>       <div style={{ ... }}>
>         <div {...props} />
>       </div>
>     )
> </MaterialTable>
> ```

Sorry, but this is simply not true. Your solution also "bloats" the codebase and is actually worse. What you're suggesting is to add a `div` element just to remove the padding. React components should have `className`, period. This is just a matter of passing a prop.

**Comment by vakyla98** [comment]
Is className implemented?

**Comment by pstephenwille** [comment]
I had to laugh at the comment `So we don't bloat the codebase,...` because inline styles are code bloat.  Without react `classNames` I can't target table implementations and reduce code bloat via cascading styles.  Plus, the source code is way bloated with all the `style` objects.   IMO, it's a step backwards.
