### ISSUE TITLE
Add support for default and specified classNames for columns and rows

### ISSUE THREAD

**Issue by mviens** [mbrn/material-table#767]
**Is your feature request related to a problem? Please describe.**
Yes, styling the columns and rows is extremely difficult and must rely on hacky CSS selectors.

**Describe the solution you'd like**
I would like to see `<MaterialTable rowClass={} and columnClass={} ... />`. In addition I would like to see support for specifying (and overiding) a column class directly with the column definition. While the `cellStyle` is supported within the column definition, it is not efficient to have to repeat the same information for multiple columns.

**Describe alternatives you've considered**
I have resorted to elaborate (and fragile/hacky) CSS selectors to implement CSS styles.

**Additional context**
n/a

**Comment by intelligentspark** [comment]
+1 - I'm having difficulty applying a smaller font size to my table and it seems this is the issue.  I'd love to be able to leverage MuiTheme to globally reduce the font size, for example within table cells.
