### ISSUE TITLE
Remote data error handling

### ISSUE THREAD

**Issue by mghazanfar** [mbrn/material-table#768]
**Is your feature request related to a problem? Please describe.**
It is related to when we use callback in data that uses Promise, I'm unable to show error if any error occurs. For example if there's no network, API gives "Network Error" where the table keeps showing loading state.
**Describe the solution you'd like**
I think after .then(), we must reject the promise by giving it error in catch block i.e. .catch(error=>reject({error}));

**Describe alternatives you've considered**
Prior to usage of your library, I had my own error state to show but when I started using your library, I starting relying on it but this was quite surprising that it does not handle error but shows loading state. Please handle it.

**I'm using axios for calling APIs**

**Comment by AugustoCalaca** [comment]
A issue alike was reported and marked as bug [#744](https://github.com/mbrn/material-table/issues/744#issue-459099240).
