### ISSUE TITLE
[HELP] IconProps / Change the order of actions

### ISSUE THREAD

**Issue by gomorizsolt** [mbrn/material-table#769]
Hey @mbrn!

Thanks for maintaining this awesome project, really like the features it provides. :)

I have encountered some issues while using the package.

1. As far as I understand, the size of a particular icon can be modified via the `iconProps` property, e.g.:

```js
iconProps: {
   fontSize: "large"
}
```

However, it doesn't really affect the icon's appearance at all. What'd be a possible reason for this unexpected behavior?

2. Is there any way to change the order of the icons under the actions column?

If you need further details, don't hesitate to ask. :)

Thanks in advance.

**Comment by gianlucamateo** [comment]
Icons are wrapped in IconButtons as is usual in Material-UI. Therefore the size of the icon itself doesn't have a large influence. If you want to reduce row heights, try enabling compact mode by setting the options flag "padding" to "dense"

**Comment by gomorizsolt** [comment]
Thanks @gianlucamateo, I'll give that option a try.
