### ISSUE TITLE
Enhancement: Accessing search bar while selecting rows

### ISSUE THREAD

**Issue by balibou** [mbrn/material-table#77]
example on: https://mbrn.github.io/material-table/#/docz-examples-example-selection

1. Select a row
2. Search bar is unreachable

When selecting a row with a checkbox, I would like to still access to search bar (moreover, all the tooltip menu)

**Comment by mbrn** [comment]
Why not? I will work on it.

**Comment by mbrn** [comment]
This is done @balibou . It will be in next release.

**Comment by balibou** [comment]
Thanks @mbrn !
