### ISSUE TITLE
Prop to disable scroll

### ISSUE THREAD

**Issue by jerlockk** [mbrn/material-table#771]
**Is your feature request related to a problem? Please describe.**
When I have few rows in the table, the scroll is unnecessary.

**Describe the solution you'd like**
I would like to have a prop to disable the scroll in the table.

**Additional context**
![image](https://user-images.githubusercontent.com/34114364/60304302-9e82d400-98fe-11e9-8dfb-9b9f90c120c9.png)
As the image shows, the scroll in this case is unnecessary because there are few rows.

**Comment by gianlucamateo** [comment]
![image](https://user-images.githubusercontent.com/1481367/60326090-2dd4c980-9989-11e9-97ec-8ec1d65379b2.png)
is this what you're looking for?

**Comment by jerlockk** [comment]
😮 Yes, that's what I was looking for, thank you very much
