### ISSUE TITLE
Is there a way to trigger filter based on an event outside the scope of table?

### ISSUE THREAD

**Issue by abhishekgupta92** [mbrn/material-table#774]
**Is your feature request related to a problem? Please describe.**
I want to add a special input box where user can search or choose from the drop down one of the possible options in the column. Selecting any of it the table should automatically be updated.

**Describe the solution you'd like**
If the architecture allows us to trigger the filter.

**Describe alternatives you've considered**
Changing the data set dynamically.

**Comment by mindaugasnakrosis** [comment]
@abhishekgupta92 did you find a solution?
