### ISSUE TITLE
Enhancement: Filtering selecting rows

### ISSUE THREAD

**Issue by balibou** [mbrn/material-table#78]
example on: https://mbrn.github.io/material-table/#/docz-examples-example-selection

1. Select a row
2. Try to display only selected rows

When selecting a row with a checkbox, I would like to filter only selected rows

**Comment by mbrn** [comment]
Good idea. I will work on it.

**Comment by mbrn** [comment]
@balibou, 

Why you don't fork repo and try something like that?

**Comment by balibou** [comment]
@mbrn I will have a look 😃

**Comment by luizbaldi** [comment]
Hi @balibou, feel free to ask here if you have any doubts or suggestions 😄

**Comment by balibou** [comment]
Hi @luizbaldi, I'm already working on a branch 😄Just a bit tricky because the checkbox column is not a proper column, but I should figure a good solution ! Will pull request it soon

**Comment by balibou** [comment]
@luizbaldi @mbrn Can I get the access rights for pushing my PR ? 😃

**Comment by mbrn** [comment]
Thanks for your contribution @balibou.

Did you fork project? You can send your changes with this order:

1. Fork the project
2. Clone the your own repo to the local.
3. Change what ever you want
4. Commit and push your changes to your repo.
5. Create a pull request. 
6. I will be very happy to accept it :)

**Comment by balibou** [comment]
@mbrn ah ok actually I didn't fork it. Will do that then

**Comment by mbrn** [comment]
This is in v1.3.0
