### ISSUE TITLE
Single Row Selection - Detail Panel

### ISSUE THREAD

**Issue by preludeofme** [mbrn/material-table#782]
I'm not finding any documentation on how to set up single-row selection. I saw issue #294 that had a link to the old documentation but it's a deadlink now. Is there updated documentation on the options to use? 

i'd like to have the table expand only one row at a time. 

thanks

**Comment by preludeofme** [comment]
Nevermind, i found the option just wasn't in the documents. 

for anyone else in the future needing this, you just need to add the option "detailPanelType"

`options={{
                    search: false,
                    paging: false,
                    selection: false,
                    detailPanelType: "single" // or 'multiple' by default
                }}`

[detailPanelType](https://github.com/mbrn/material-table/blob/master/types/index.d.ts#L181 )

**Comment by HiLuLiT** [comment]
@preludeofme what version is this feature available from? tried it and it's not working for me...
