### ISSUE TITLE
Dense padding prop does not apply to column headers

### ISSUE THREAD

**Issue by jakeleventhal** [mbrn/material-table#783]
**Describe the bug**
If you use the dense option, it does not affect the header row

**To Reproduce**
1. Create a table with dense props

**Expected behavior**
The header row should be dense too

**Screenshots**
<img width="341" alt="Screen Shot 2019-07-02 at 6 46 35 PM" src="https://user-images.githubusercontent.com/15133828/60551604-ca84c780-9cf9-11e9-9b49-af96c3f1ee45.png">

**Comment by jakeleventhal** [comment]
@gianlucamateo

**Comment by gianlucamateo** [comment]
I see how this would be useful, but the main reason behind the option was that some things about row heights can't be changed with styling, such as the size of the iconbuttons used for tree expansion or actions. 

To my knowledge, the same does not apply to the headers, and I suggest solving the issue with custom styling.

**Comment by jakeleventhal** [comment]
I get where you're coming from - but I really disagree. I think the biggest use case is for just styling purposes and wanting data to be presented in a more compact/condensed way. After all, tables are mostly just showing text data.

Having the header be a different style from the rest of the table just stands out and looks out of place.

What are your thoughts?

**Comment by gianlucamateo** [comment]
I guess it makes sense. I am, however, not going to be able to invest time into adjusting this. Maybe you could look at it?
