### ISSUE TITLE
Table options doesn't changes

### ISSUE THREAD

**Issue by Enzerot** [mbrn/material-table#789]
**Describe the bug**
I have wrapper component for MaterialTable that have filter property. When this property changes I want to change options of the table too.

I've tried a couple of ways for that:
1. Render another MaterialTable with another options object
2. Render one MaterialTable and set its options depends on my filter property
But both of them doesn't work!

**Expected behavior**
Options must be changeable

**Comment by KPpuria** [comment]
hi, did you find a solution for this?

**Comment by mbrn** [comment]
> hi, did you find a solution for this?

Hi @KPpuria 

Please upgrade to latest version. Because we solved a few options problem on latest versions.
