### ISSUE TITLE
Table extending longer than it should

### ISSUE THREAD

**Issue by jakeleventhal** [mbrn/material-table#79]
**Describe the bug**
When the table is showing N rows but there are <N rows of data, the there is still space for N rows. For example, in the pagination if you say to show 20 rows at a time, but there are only 2 rows of data, the table extends and is very long and just shows blank white space.

**To Reproduce**
1. Make a table
2. Select to show 20 rows when only 3 rows of data are present

**Expected behavior**
 The table should conform to the number of rows that are present in the table and should show some indication that there is no data when there is none ("No Data" or something like that).

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

**Comment by SilviaJoyceBalraj** [comment]
@mbrn This is the same issue I am facing too. Could you please check on this.

**Comment by mbrn** [comment]
@SilviaJoyceBalraj , I am very busy nowadays. But 3 developers are working on some issues. So we will resolve this too, asap.

**Comment by mbrn** [comment]
This is done @jakeleventhal, @SilviaJoyceBalraj,

I added a __emptyRowsWhenPaging__ options to prevent render empty data rows.

It will be in next release.

**Comment by eddiemonge** [comment]
In the next major release can it be changed to false with a breaking change note?
