### ISSUE TITLE
Remotely Toggle Detail Panel

### ISSUE THREAD

**Issue by preludeofme** [mbrn/material-table#790]
I'm running into a problem where i have a detail panel open to  view records in a table, and i am wanting to close the detail panel (or all panels if possible) if the user clicks a specific button. 

**Describe the solution you'd like**
add a function to close all detail panels or specific ones by passing an index

**Describe alternatives you've considered**
i'm working on a workaround where when a user clicks on a row, it stores the togglePanel function in an array with the index to the row. Then when the user clicks the button, i'm having it call the togglePanel function to try and close the panel. However, i can't tell if the panel is open or not, so what happens is sometimes it will close and other times it will stay open or if it's already closed it will open it. 

in case someone needs a work around until this feature can be added:

i'm using mobx for state management 
```

//-------React Component --------------

        let clickRow = (row, toggle, event) => {
            var toggleRow = { index: event.currentTarget.sectionRowIndex, toggle: toggle };
            //-----this is where i'm calling the state to manage the panel toggling
            props.dataState.addToggleRow(toggleRow);
           //--------------------------------------------------
            toggle();
        };

return(
            <MaterialTable
                title=""
                icons={{
                    DetailPanel: ChevronRight
                }}
                columns={columns)}
                data={Data}
                isLoading={props.dataState.tableLoading}
                detailPanel={RowDetail}
                onRowClick={(event, rowData, togglePanel) => clickRow(rowData, togglePanel, event)}
            />)

//---------State ----------------
@observable RowsToggle = [];

@observable LastRowClicked = { index: -1, clickCount: 0 };
@action addToggleRow = row => {
        //---check if there's already a toggle row in the array
        var matchingRow = this.RowsToggle.filter(function(item) {
            return item.index == row.index;
        })[0];
        //---set lastrowclicked to the index and add a click count
        if (this.LastRowClicked.index == row.index) {
            this.LastRowClicked.clickCount++;
        } else {
            this.LastRowClicked.index = row.index;
            this.LastRowClicked.clickCount = 1;
        }
        //----if index is not in the toggle array then add the row
        if (!matchingRow) {
            this.RowsToggle.push(row);
        }
    };
isOdd = num => {
        return num % 2;
    };
@action toggleRow = () => {
        //---if there aren't any items in the toggle array then skip
        if (this.RowsToggle.length > 0) {
            //get the index and the toggle function from the array
            var lastIndex = this.LastRowClicked.index;
            var matchingRow = this.RowsToggle.filter(function(item) {
                return item.index == lastIndex;
            })[0];
            //if the click count is odd then fire toggle event (as odd means it's only been clicked once or 3 times which means it should already be closed)
            if (this.isOdd(this.oddLastRowClicked.clickCount) == 1) {
                matchingRow.toggle();
            }
        }
    };
```

**Comment by KATT** [comment]
Yeah, I want to do something similar in order to maintain expanded rows through page reload (updating query string)... my use-case would go a bit further too where it'd be nice if the whole state of the table could be controlled from outside. Probably doable to get a nice API by doing a larger rewrite using hooks

**Comment by mlepicki** [comment]
You should be able to do that by resetting `tableData` property of a rowData. See https://github.com/mbrn/material-table/issues/357 where it was mentioned

**Comment by rocketkittens** [comment]
https://github.com/mbrn/material-table/issues/1340#issuecomment-573429029
