### ISSUE TITLE
column Filters are removed when an Action is performed

### ISSUE THREAD

**Issue by aramkoukia** [mbrn/material-table#791]
Column Filters are removed when an Action is performed

**To Reproduce**
1. Enter some column filters
2. Edit the record
3. Save the change
4. column Filters are removed 

**Expected behavior**
Column filters should stay the same and not removed

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser All
 - Version 1.29.1

**Comment by eugeneli71** [comment]
any updates on this ? i am facing the same issues.

**Comment by imranshabbir** [comment]
I am also facing this, on Edit when record is updated. Filters are getting removed. Please suggest solution.
