### ISSUE TITLE
When column filter value changed, current page does not go to 0, when use remote data.

### ISSUE THREAD

**Issue by mswindu** [mbrn/material-table#792]
**Describe the bug**
When column filter value changed, current page does not go to 0, when use remote data.

**To Reproduce**
1. Get remote data
2. Change current page (increase)
3. Enter some column filters
4. Current page number hasn't been changed

**Expected behavior**
Сurrent page number must be 0 after the change column filter value.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser All
 - Version v1.40.1

**Additional context**
I suggest changing onFilterChangeDebounce method. Make it similar to onSearchChangeDebounce method. 

Add to code block
"if (this.isRemoteData ()) {"
// reset current page
query.page = 0;

**Comment by dalenhughes** [comment]
YES PLEASE! This bug starts an infinite loop of network requests and crashes my whole app.
