### ISSUE TITLE
how to get rows or data after filtering?

### ISSUE THREAD

**Issue by marcosvcastro** [mbrn/material-table#794]
how to get rows or data after filtering?

**Comment by kaienbcjdoapwkfldue** [comment]
What do you mean by "get rows or data"? You get them in the `fetchData` callback function.

**Comment by marcosvcastro** [comment]
callback what function?
Exemple:
```
data={[
          { name: 'Mehmet', surname: 'Baran', birthYear: 1987, birthCity: 63 },
          { name: 'Zerya Betül', surname: 'Baran', birthYear: 2017, birthCity: 34 },
         { name: 'name Test', surname: 'Test', birthYear: 2017, birthCity: 34 },
        ]}  
```
In the filter column 'birthCity' i come in with '34'. 
The grid render the two records with 'birthCity: 34'.
I want to get the result containing two records.

Result:{[
   { name: 'Zerya Betül', surname: 'Baran', birthYear: 2017, birthCity: 34 },
         { name: 'name Test', surname: 'Test', birthYear: 2017, birthCity: 34 },
]}

**Comment by kaienbcjdoapwkfldue** [comment]
Check out https://material-table.com/#/docs/features/remote-data

Event though you might be not working with remote data, you can provide your own callback to the `data` property. You can then filter your local data manually and get direct access to the result.

I'm not sure if there is currently a more direct way.
