### ISSUE TITLE
hide-xs

### ISSUE THREAD

**Issue by kecoco16** [mbrn/material-table#797]
Hi!

I would like to know if there is any way to hide a column only in mobile.

Regards.

Edit:
I found this solution i don't know if is the best way to do it but works well.

```
import useMediaQuery from '@material-ui/core/useMediaQuery'
import { useTheme } from '@material-ui/core/styles'

const matches = useMediaQuery(theme.breakpoints.down('md'))

<MaterialTable
  columns={[
    {
      title: 'Show always',
      field: 'always',
    },
    {
      title: 'Hide on xs',
      field: 'hideXs',
      headerStyle: matches ? { display: 'none' } : {},
      cellStyle: matches ? { display: 'none' } : {}
    }
  ]}
/>
```

If someone knows a native or better solution please let me know, thanks.

**Comment by rajivsubra1981** [comment]
The below solution seems to work 
 columns ={ [  { title: 'Hide on xs', field: 'hideXs', hidden: matches }]}

**Comment by emrekara37** [comment]
i close this issue. reopen if you needed please
