### ISSUE TITLE
Add export feature

### ISSUE THREAD

**Issue by mbrn** [mbrn/material-table#8]
Users can export table data as pdf or excel file

**Comment by SilviaJoyceBalraj** [comment]
@mbrn Hi, 
Could you show an example how to add export as PDF and Excel features to the table.

Thanks

**Comment by luizbaldi** [comment]
Hi @SilviaJoyceBalraj! Have you checked [this documentation link?](https://mbrn.github.io/material-table/#/docz-examples-example-default-actions) Just press the _Export_ button and choose `"Export as CSV"`.

If it's not clear enough, could you tell us how it can get better?

**Comment by mbrn** [comment]
There is no export as PDF feature yet. But it will be, after i add pdf construction feature to filefy project.

**Comment by SilviaJoycePHMS** [comment]
@mbrn  Could you please let me know when this enhancement will be added?

**Comment by mbrn** [comment]
Hi, we should add pdf feature to filefy. I cant promise, but it is not very close. You can export as csv only.

**Comment by Prasad-YS** [comment]
Any way to change the Exported CSV file name ? Currently it's taking title of the table as CSV name

**Comment by mbrn** [comment]
Hi @Prasad-YS ,

Why not. I can do this easily. But this is another issue. Can you open a new issue for as export file naming, please?

**Comment by Prasad-YS** [comment]
> Hi @Prasad-YS ,
> 
> Why not. I can do this easily. But this is another issue. Can you open a new issue for as export file naming, please?

Done, raised new issue #196

**Comment by Surbhi-Kohli** [comment]
> Hi, we should add pdf feature to filefy. I cant promise, but it is not very close. You can export as csv only.

Is the export as els feature implemented?

**Comment by Surbhi-Kohli** [comment]
> Users can export table data as pdf or excel file

How to do that..Please give code demo

**Comment by bel7aG** [comment]
@mbrn the .xls & .pdf extensions are available or not?

**Comment by tpthusara** [comment]
can we implement PDF export to material tables?

**Comment by awaism551** [comment]
As of now, Pdf and Csv extensions are available in Export feature, xlsx extension feature not available, right?
