### ISSUE TITLE
how to check if detailPanel is expanded or collapsed?

### ISSUE THREAD

**Issue by sandeshakya** [mbrn/material-table#800]
I'm using the onRowClick prop to expand/collapse detail panels. I'm making API calls and calling setState() on the onRowClick handler, since I can't in detailPanel. I only want these calls to execute if the row is being opened. Is it possible to check the detailPanel status in onRowClick prop?

Thank you.

**Comment by preludeofme** [comment]
i couldn't find anything that would tell you that state of each row, best i came up with is like in #790 i've got a workaround for closing out open panels or remotely toggling them. it's a bit ugly but might work if you're looking for something like that.

**Comment by TheHalcyonSavant** [comment]
```jsx
function Detail() {
  useEffect(() => () => console.log('on collapse event'));
}
<MaterialTable
  ...
  detailPanel={() => <Details />}
  />
```
