### ISSUE TITLE
layout breaks as soon as material-table is imported onto the page, 

### ISSUE THREAD

**Issue by jayarjo** [mbrn/material-table#804]
As soon as I import `material-table` component onto the page, layout breaks. I suspect that it has something to do with the order in which core material-ui and material-table styles are loaded. Do we have any control over this?

**Comment by jayarjo** [comment]
Happens because `.MuiButtonBase-root` class with all its styles somehow makes to the top. From what I see normally it sits lower in the hierarchy.

**Comment by jayarjo** [comment]
I think this is why it happens: 
![Screenshot from 2019-07-07 12-58-06](https://user-images.githubusercontent.com/150075/60766181-e7811800-a0b6-11e9-8433-17682693d751.png)

Notice all the `Mui*` styles after `makeStyles`. They are basically added twice (there are some of them already defined before `makeStyles`) and I suspect effectively override all the `makeStyles`.

**Comment by jayarjo** [comment]
For some reason I do not observe such behavior in the isolated sandbox: https://codesandbox.io/s/material-demo-2p5qg. So I guess it has to be some setting somewhere. Any ideas?

**Comment by masagameplay** [comment]
This issue is coming from an old Material-UI version in this project (https://github.com/mbrn/material-table/issues/773)

**Comment by jayarjo** [comment]
So what's the fix? Fork it, update and use that one?

**Comment by kaienbcjdoapwkfldue** [comment]
@jayarjo After struggling with this for a while, I now simply updated all the dependecies of my client to their latest version (`npm update`), which solved the problem. So maybe try to update everything related to `material-ui` as well as `material-table`.

**Comment by Renaud009** [comment]
Updating all dependencies didn't actually fixed the issue for me.

**Comment by alex-fivetalent** [comment]
I found with material-table 1.36 to 1.40 fixed the issue, maybe because we had been using hooks with other material ui components and update changed the material-table version of ui/core to 4.

**Comment by oze4** [comment]
This happened to me out of nowhere... I didn't apply any updates, or even install any new packages... literally watched this happen to me from one 'hot reload' to the next. Nothing would fix this for me... I installed `@material-ui/styles` - which made matters worse.

I did not have `@material-ui/styles` installed before all of this started happening (I was hoping it would fix it)..

Just as magically as this issue appeared, it disappeared after uninstalling `@material-ui/styles` - even though I did not have it installed prior to this issue...

Any idea why this happens? This has made me think twice about using this library..

**Comment by jayarjo** [comment]
The solution that worked for me was using same version of `material-ui/*` modules as used by material-table.

**Comment by naudej** [comment]
@jayarjo Hi, How do I check which version the material-ui that material-table is using? I recently created a project added in Material-UI and now Material-table and experienced this issue.

**Comment by ParasDevp** [comment]
it is working you just need to update the version of material table , if your material table version is 1.69.3 update it to 2.0.0
