### ISSUE TITLE
Reduce the bundle size

### ISSUE THREAD

**Issue by slevy85** [mbrn/material-table#805]
I have analyzed with `source-map-explorer` the build size of my application that uses material-table, and I noticed that it was responsible of a large part of the size.
One issue is that it imports all material-ui components instead of just the ones needed, the other issue is the react-beautiful-dnd dependencies (almost half of the bundle size).

1. For the first issue i think we can use path imports for the materialui dependencies :  
Instead of 
```
import { Button, TextField } from '@material-ui/core';
```
we can do :  
```
import Button from '@material-ui/core/Button';
import TextField from '@material-ui/core/TextField';
```
More information [in the material ui documentation](https://material-ui.com/guides/minimizing-bundle-size/)

2.  For the second issue I am not sure how it can be done, but there could be a way to opt-out of the draggable feature, and those who wants it needs to include react-beautiful-dnd in their dependencies.

There are probably other solutions.

What do you think ?

Thank you very much.

**Comment by perfectstrong** [comment]
The first issue is mentionned in `README`. [https://github.com/mbrn/material-table#2add-material-icons](https://github.com/mbrn/material-table#2add-material-icons)

**Comment by emrekara37** [comment]
#867
