### ISSUE TITLE
How to add a row in Edit mode under an existing row, in a tree datatable?

### ISSUE THREAD

**Issue by cristiadis** [mbrn/material-table#808]
First of all, thank you for all your great work!

Second, regarding my need, I'd like to be able to add a row under an existing row, so I can make full use of the tree functionality. Is there a way to do that? Or do you have any input on how I can connect the addRow() handler connected to the global "Add" action, with my custom "Add" action added on each row?

For example, in my screenshot below, if I click on +, I'd like to get the editable form under "Animal", and then I'd be able to add my data for the new row.

Thanks so much, in advance!

![image](https://user-images.githubusercontent.com/8373205/60877564-5d63bb80-a23e-11e9-94ae-b9ddf1131fd3.png)

**Comment by sabahath786** [comment]
I am having the same query, addRowPOsition give only 'first ' and 'last' , how can we add new row position to the custom index.

**Comment by antonioiliev** [comment]
Hi all,

Same request here. I am thinking of workarounds but seem to be stuck for now.

**Comment by lucbas** [comment]
Hi 👋🏼
We also face this issue and haven't found a solution yet.
Any ideas?
Maybe add a + Icon with each parent row?

**Comment by yiy142** [comment]
Same here. 
It is quite simple to implement a tree-view with the "edit" feature, but I really love the sorting and filtering feature of material table.
