### ISSUE TITLE
If paging is set to false, pageSize matters?

### ISSUE THREAD

**Issue by yashSangai** [mbrn/material-table#811]
If paging is set to false, then will pageSize affect the number of rows rendered on the table. For example, if paging is False, pageSize is 50 and I have 100 rows of data, then how many rows will render 100 or 50?

**Comment by hrafaelveloso** [comment]
If you set `paging : false`, the number of `pageSize` isn't important because it's not taken into account .

Simple codesandbox where you can test that (you don't need 100 rows to test):
[https://codesandbox.io/s/naughty-butterfly-puhk2](https://codesandbox.io/s/naughty-butterfly-puhk2)

**Comment by yashSangai** [comment]
Oh, I understand! Thanks for the help.
