### ISSUE TITLE
How do I change the default color for row hover?

### ISSUE THREAD

**Issue by rxhl** [mbrn/material-table#814]
I'm trying to change the default color for the row hover event. As I see it, the default seems to be,

```
.MuiTableRow-root.MuiTableRow-hover:hover {
  background-color: 'rgba(0, 0, 0, 0.07)';
}
```

How do I change it from the React component?

Many thanks!

**Comment by rxhl** [comment]
bump

**Comment by rxhl** [comment]
Any updates?

**Comment by PiAlexay** [comment]
`
import React from 'react';
import ReactDOM from 'react-dom';
import { createMuiTheme } from '@material-ui/core/styles';
import { ThemeProvider } from '@material-ui/styles';

const theme = createMuiTheme({
  overrides: {
   MuiTableRow: {
      hover: {
         cursor: 'pointer',
      }
    }
  }
});

ReactDOM.render(
    <ThemeProvider theme={theme}>
        <App/>
    </ThemeProvider>
    , document.getElementById('root'));
`

**Comment by rxhl** [comment]
Thanks @PiAlexay but the solution doesn't seem to work. Do you have a working code sandbox example?

**Comment by PiAlexay** [comment]
Look at the code again.  What is your problem?

**Comment by rxhl** [comment]
@PiAlexay It does not work, the `MuiTableRow` component is not getting overwritten. You can check it yourself. cc @mbrn

**Comment by JThissen** [comment]
@rxhl, the answer provided by @PiAlexay does in fact work. However, `hover:` should be replaced by `"&:hover":` instead.

**Comment by masbaehr** [comment]
If you're looking for a dirty, but simple + quick way of achieving a row-hover do this:

Insert anywhere on the page:
```html
<div dangerouslySetInnerHTML={{__html: "<style>.MuiTableRow-root:hover{ background: #dedede !important }"}}></div> 
```

Sometimes the "react-way" just overcomplicates CSS-overriding like a rube-goldberg-machine ;-)

**Comment by rxhl** [comment]
@masbaehr That's why I ended up doing. The solutions by @PiAlexay and @JThissen do not work for me, maybe because I already had a top level theme and no matter how I wrap the MaterialTable in the ThemeProvider, it just won't work.

This is what I did.

```css
// App.css

.MuiTableRow-root:hover { 
    background: #dedede !important 
}

```

**Comment by masbaehr** [comment]
Putting workaround in root-level css (and i think also in other css) has one drawback though - once loaded it will be there until a full page reload. So assuming you want this to happen only on some pages, it's still problematic. I think the better solution would be to add such a feature directly in to the table component (e.g. like there is rowStyle there should also be rowStyleHover)

**Comment by GBincaz** [comment]
If anyone read this, that's how I did it :
```
       const tableTheme = createMuiTheme({
            overrides: {
                MuiTableRow: {
                    hover: {
                        "&:hover": {
                            backgroundColor: "rgba(33, 150, 243, 0.25) !important"
                        }
                    }
                }
            }
        });

        <ThemeProvider theme={tableTheme}>
             <MaterialTable 
                ... 
                onRowClick={(event, rowData) => {
                     console.log(rowData);
                }}
                ...
              />
         </ThemeProvider>

```
The onRowClick assignement enable hover in the grid, the theme override the style of the hover.

**Comment by OnkelTem** [comment]
> I'm trying to change the default color for the row hover event. As I see it, the default seems to be,
> 
> ```
> .MuiTableRow-root.MuiTableRow-hover:hover {
>   background-color: 'rgba(0, 0, 0, 0.07)';
> }
> ```
> 
> How do I change it from the React component?
> 
> Many thanks!

I'm not quite sure why do all these people recommend patching the theme ;-)

This is how I did it:

```js
const useStyles = makeStyles(theme => ({
  table: {
    '& tbody>.MuiTableRow-root:hover': {
      background: 'red',
    }
  },
}));

function MyTable() {
  const classes = useStyles();
  return (
    <div className={classes.table}>
      <MaterialTable .../>
    </div>
  );
}
```

The thing is - passing `className` to the `<MaterialTable>` element wouldn't help because it sort of screws up standard MaterialUI techniques a little.

**Comment by Davst** [comment]
Struggling to enable hover for rows, anyone care to explain how they even got a default row hover behavior?

**Comment by Pat1420** [comment]
> If anyone read this, that's how I did it :
> 
> ```
>        const tableTheme = createMuiTheme({
>             overrides: {
>                 MuiTableRow: {
>                     hover: {
>                         "&:hover": {
>                             backgroundColor: "rgba(33, 150, 243, 0.25) !important"
>                         }
>                     }
>                 }
>             }
>         });
> 
>         <ThemeProvider theme={tableTheme}>
>              <MaterialTable 
>                 ... 
>                 onRowClick={(event, rowData) => {
>                      console.log(rowData);
>                 }}
>                 ...
>               />
>          </ThemeProvider>
> ```
> 
> The onRowClick assignement enable hover in the grid, the theme override the style of the hover.

Thank you for the OnRowClick making the style to be applied...
You can skip the ThemProvider thanks to 
`options={{
            showTitle: false,
            searchFieldAlignment: "left",
            filtering: false,
            rowStyle: {
              "&:hover": { backgroundColor: "#EEE" }
            }
          }}`

**Comment by Alarees** [comment]
hi,

> `options={{ rowStyle: { "&:hover": { backgroundColor: "#EEE" } } }}`

its not working man
@Pat1420

**Comment by Pat1420** [comment]
> hi,
> 
> > `options={{ rowStyle: { "&:hover": { backgroundColor: "#EEE" } } }}`
> 
> its not working man
> @Pat1420

You are right, Seems not working anymore with the last version was working for an older version it seems .....i will update my post. thanks for the feedback

**Comment by RidhwanDev** [comment]
This works for me:

```
createStyles({
          rowHover: {
              "&:hover": {
                  cursor: "pointer",
                  backgroundColor: "rgba(87, 197, 111, 0.13) !important"
               }
          }
 })

<TableRow key={row}  hover classes={{ hover: classes.rowHover }}>
   <TableCell>
      {row}
   </TableCell>
</TableRow>
```

If you want a working example component:

```
const useStyles = makeStyles((theme: Theme) =>
      createStyles({
          rowHover: {
              "&:hover": {
                  cursor: "pointer",
                  backgroundColor: "rgba(87, 197, 111, 0.13) !important"
               }
          }
      })
   );

const TableView: React.FC = () => {
    const classes = useStyles();
    return (
        <TableContainer component={Paper}>
            <Table aria-label="simple table">
                <TableHead>

                    <TableRow>
                        <TableCell align="left">Name</TableCell>
                    </TableRow>
                </TableHead>
                <TableBody>

                    {["bob", "jimmy", "larry"]
                        .map((row) => (
                            <TableRow key={row}
                                hover
                                classes={{
                                    hover: classes.rowHover
                                }}
                            >
                                <TableCell>
                                    {row}
                                </TableCell>
                            </TableRow>
                        ))}
                </TableBody>
            </Table>
        </TableContainer>
    );
};
```

**Comment by osvaldokalvaitir** [comment]
> hi,
> 
> > `options={{ rowStyle: { "&:hover": { backgroundColor: "#EEE" } } }}`
> 
> its not working man
> @Pat1420


Hello, I have the same problem and I can't solve it! did you manage to put the styling by rowStyle on the hover?

        rowStyle: row => {
          const { id } = row.tableData;
          return {
            backgroundColor: id % 2 ? colors.lighter : colors.white,
            '&:hover': { backgroundColor: colors.darker },
          };
        },

not working!

**Comment by pprathmesh-vmw** [comment]
> Struggling to enable hover for rows, anyone care to explain how they even got a default row hover behavior?

Just add 'hover' to the TableRow should be enough to just enable hover!

`<TableRow hover>`

**Comment by ariel262626** [comment]
Any updates?

**Comment by osvaldokalvaitir** [comment]
Any solution?

**Comment by Pat1420** [comment]
Just had a look on this again and another solution to avoid overriding theme is to override the component MTableBodyRow

`components={{
            Row: (props) => (
              <MTableBodyRow className={classes.tableRow} {...props} />
            )}}`

MTableBodyRow is imported from material-table
`import MaterialTable, { MTableToolbar, MTableBodyRow } from "material-table";`

and thanks to 
`
const useStyles = makeStyles({
tableRow: {
    "&:hover": {
      backgroundColor: "#2BCB4E!important",
    },
  },
});
`
it makes the job...

**Comment by ThaFurther** [comment]
> ```
> import React from 'react';
> import ReactDOM from 'react-dom';
> import { createMuiTheme } from '@material-ui/core/styles';
> import { ThemeProvider } from '@material-ui/styles';
> 
> const theme = createMuiTheme({
>   overrides: {
>    MuiTableRow: {
>       hover: {
>          backgroundColor: 'green',
>       }
>     }
>   }
> });
> 
> ReactDOM.render(
>     <ThemeProvider theme={theme}>
>         <App/>
>     </ThemeProvider>
>     , document.getElementById('root'));
> ```

Works perfectly fine for me. Thank you.

**Comment by si7o** [comment]
There is a prop called **hover** on MuiTableRow. you need to use along with theme overrides (if you want a different color).
![imagen](https://user-images.githubusercontent.com/5405326/97563055-d615fa80-19e2-11eb-9c8d-309dce9e7f50.png)

other aproach could be setting :hover for root className:
```
MuiTableRow: {
      root: {
        '&:hover': {
          backgroundColor: 'green'
        }
      }
    },
```

**Comment by zhonghankong** [comment]
> @rxhl, the answer provided by @PiAlexay does more or less work.
> 
> E.g., to change the color by hovering over a single cell:
> 
> ```
> const themeTable = createMuiTheme({
>     overrides: {
>       MuiTableCell: {
>         root: {
>           "&:hover": {
>             backgroundColor: "rgba(33, 150, 243, 0.5)"
>           }
>         }
>       }
>     }
>   });
> ```
> 
> ![Example](https://user-images.githubusercontent.com/31924219/62212598-5a716c00-b3a1-11e9-811f-bfaf5151e008.png)
> 
> Furthermore, MaterialTable must be wrapped by a MuiThemeProvider component, e.g.
> 
> ```
> <MuiThemeProvider theme={themeTable}>
> *---YOUR TABLE---*
> </MuiThemeProvider>
> ```

Just like to add on in case anyone has the same requirements as me. Upon TableRow-hover for TableBody, i wanted to color the font color of all TableCells on the hovered row. 

And since i will be using the same styled table numerous times in different pages, i wanted to override the theme so i didn't have to repeatedly specify the style in each row/table. 

![image](https://user-images.githubusercontent.com/18184189/102386940-bbd3c280-400a-11eb-8625-18872f24a774.png)

30 minutes of intense trial and error didn't yield any useful results, but learnt enough to understand how it worked. 
This is how i did it: 
```
const theme = createMuiTheme({
  overrides: {
    MuiTableRow: {
            root: {
                '&.MuiTableRow-hover:hover': { 
                    cursor: 'pointer',
                    '& .MuiTableCell-body': {
                        color: sharedColor.hover
                    }
                }
            }
        }
    }
})

...

<MuiThemeProvider theme={theme}>
  Table here...
<MuiThemeProvider/>
````

If anyone has a better way of overriding, please do share

**Comment by julia-dizhak** [comment]
> ```
> import React from 'react';
> import ReactDOM from 'react-dom';
> import { createMuiTheme } from '@material-ui/core/styles';
> import { ThemeProvider } from '@material-ui/styles';
> 
> const theme = createMuiTheme({
>   overrides: {
>    MuiTableRow: {
>       hover: {
>          backgroundColor: 'green',
>       }
>     }
>   }
> });
> 
> ReactDOM.render(
>     <ThemeProvider theme={theme}>
>         <App/>
>     </ThemeProvider>
>     , document.getElementById('root'));
> ```



> ```
> import React from 'react';
> import ReactDOM from 'react-dom';
> import { createMuiTheme } from '@material-ui/core/styles';
> import { ThemeProvider } from '@material-ui/styles';
> 
> const theme = createMuiTheme({
>   overrides: {
>    MuiTableRow: {
>       hover: {
>          backgroundColor: 'green',
>       }
>     }
>   }
> });
> 
> ReactDOM.render(
>     <ThemeProvider theme={theme}>
>         <App/>
>     </ThemeProvider>
>     , document.getElementById('root'));
> ```

this works for me
```
MuiTableRow: {
        root: {
          '&:hover': {
            backgroundColor: colors.palette.primary.light,
          },
        },
      }
```

**Comment by paleika** [comment]
I found two ways to set style using classes overrides

disadvantage of the first approach: you hardcode mui classname as a string to override it, may be inconsistent
disadvantage of the second approach: the rule extends to the table header

1 - using `hover` prop for TableRow - as @zhonghankong mentioned
resulting className will be `.MuiTableRow-root.MuiTableRow-hover:hover`
``` js
// create mui theme with override, use this value in Theme context provider
const theme = createMuiTheme({
  overrides: {
    MuiTableRow: {
      root: {
        '&.MuiTableRow-hover': {
          '&:hover': {
            backgroundColor: 'lightblue',
          },
        },
      },
    },
  },
});

// set hover property to the table row
<TableRow
  hover
  { ...otherProps }
>
```

2 - without `hover` prop for TableRow - as @julia-dizhak mentioned
resulting className will be `.MuiTableRow-root:hover`
``` js
// create mui theme with override, use this value in Theme context provider
const theme = createMuiTheme({
  overrides: {
    MuiTableRow: {
      root: {
        '&:hover': {
          backgroundColor: 'lightblue',
        },
      },
    },
  },
});

// do not add hover property to the table row
<TableRow
  { ...otherProps }
>
```

**Comment by DanJecu** [comment]
This is the full answer ⬇️
```
const theme = createTheme({
  components: {
    MuiTableRow: {
      styleOverrides: {
        root: {
          "&.MuiTableRow-hover:hover": {
            backgroundColor: red[200],
          },
        },
      },
    },
  },
});
```

**Comment by GabbereX** [comment]
its worked for me

```
MuiTableRow: {
  styleOverrides: {
    root: {
      '& td': {
        cursor: 'pointer',
        transition: 'background-color .2s ease-in-out',
      },
      '&:hover td': {
        backgroundColor: 'rgba(91, 192, 222, .1) !important',
      },
      '&:hover td:after': {
        backgroundColor: 'transparent !important',
      },
    },
  },
},
```
