### ISSUE TITLE
Checked rows disappearing 

### ISSUE THREAD

**Issue by Monteyne** [mbrn/material-table#82]
Hello,
checked rows keep disappearing after receiving next props, 
i have looked into source, seems like new data from componentWillReceiveProps don't have "checked" property.

**Comment by mbrn** [comment]
Hello @Monteyne,

You are right. This is a bug. I will resolve this asap.

**Comment by balibou** [comment]
Hello @Monteyne @mbrn,
Is it possible to get a workflow please ?
Thanks !

**Comment by mbrn** [comment]
1. Render table with table and onSelectionChange event. 
2. select some rows and this fires onSelectionChange event. In onSelectionChange event do something with setState on your component that uses table. So the component will rerender. Then checked rows will be disappeared.

**Comment by balibou** [comment]
still working on it but didn't find a good solution

**Comment by mbrn** [comment]
This problem resolved with #132. Thanks to @balibou
