### ISSUE TITLE
Make the entire row a link

### ISSUE THREAD

**Issue by deadghost** [mbrn/material-table#820]
material-table provides a lot of functionality I need out of the box: search, sort, export, etc. In my case I'm not using the editing functionality and would like the row to link to a page that allows editing the entry. My first thought was the override the Row component and wrap `MTableBodyRow` in `a`; however, this is invalid HTML. My second thought was to use the `onRowClick` prop but it wouldn't display the link url on hover and generally seems smelly. My current approach is the override each cell's rendering with a mui `Link` such that `<a>` appears inside `<td>`. It's ok but not ideal.

Do you have any thoughts on doing this in a clean way using material-table?

**Comment by meldsz** [comment]
I was trying to add a link to elements in a column and onclick route to a new page. Did you try anything of this sort? Any suggestions?

**Comment by eddiemonge** [comment]
> however, this is invalid HTML

Not if you change the other components and use css to create the table using display

**Comment by michaelpward** [comment]
Looks like your answer may be here:

https://github.com/mbrn/material-table/issues/824

**Comment by deadghost** [comment]
@michaelpward yeah that's essentially the approach I was previously using. It doesn't make the whole row a link but makes a link inside each `<td>`. It essentially works but it kind of smells.

**Comment by MaxLeiter** [comment]
Also curious if there's a better solution, but the custom <a> wrapping works for now

**Comment by tylercaceres** [comment]
Any update on this? Did anyone find a solution? Thanks in advance.

**Comment by larsblumberg** [comment]
Since the compoent uses regular HTML table elements for rendering tables, such as `<table><tbody><tr><td>` there's no chance to make the entire row a link. See also [this StackOverflow answer](https://stackoverflow.com/a/17147876/543875). The only option left is to render a link _iside_ each `<td>` cell.

**Comment by thclark** [comment]
As @larsblumberg points out, you can't make the entire row an `<a>` in pure html. But there's no reason you couldn't use javascript.

Eg for those using react-router, I think it *should* be possible to `push()` to `history` in the `onRowClick()` callback, thereby providing an internal redirect on row click. 

*However*, for some reason, `onRowClick` also tries to toggle a detail panel, which if not present, causes an error. Here's the code:
```
import React, { Component } from 'react'
import { connect } from 'react-redux'
import { push } from 'connected-react-router'
import MaterialTable from 'material-table'


class ResourceTable extends Component {
  constructor(props) {
    super(props)
    this.onRowClick = this.onRowClick.bind(this)
  }

  onRowClick(event, rowData, togglePanel) {
      this.props.onViewItem(this.props.endpoint, rowData.id)
  }

  render() {
    const {
      endpoint,
      ...rest
    } = this.props

    return (
      <MaterialTable
        onRowClick={this.onRowClick}
        {...rest}
      />
    )
  }
}

const mapDispatchToProps = dispatch => ({
  onViewItem: (endpoint, id) => {
    dispatch(push(`${endpoint}/${id}`))
  },
})

export default connect(null, mapDispatchToProps)(ResourceTable)
```
And here's the error:
<img width="1050" alt="Screenshot 2019-12-25 at 18 33 17" src="https://user-images.githubusercontent.com/7223170/71449478-16fb0e00-2745-11ea-96f7-ce0b66183535.png">

If anyone has any suggestions to get around this error I'd welcome them!

**Comment by yujinwunz** [comment]
For anyone looking at this, I was very happy when I found the solution here: https://github.com/mbrn/material-table/issues/547

**Comment by orhanhub** [comment]
if you are willing to use React Router (v5), you can push it to history which will render the page for you automatically. You have top tap into ```onRowClick``` functionality for Material-Table.

here is a sample

```
import React from "react";
import MaterialTable from "material-table";
//others ignored for brevity
import { useHistory } from "react-router-dom";

export default function Demo() 
{
  let history = useHistory();
  return 
    (
      <div> 
      <MaterialTable 
        columns=[//ignored for brevity]
        data=[//ignored for brevity]
        onRowClick={(event, rowData) => {
          //for a static path with no params
          history.push("/demopath");
          //for dynamic path with id coming from data, feel free to edit history.push above
        }}
       />
      </div>
     )
 }
```

and wherever you are using your React Router Switch, add your <Route path="demopath" component={myDemoPathComponent} /> to the switch.

if you would like to ignore certain parts of the components upon forwarding to myDemoPathComponents, see React Router how to hide components from path.

**Comment by oze4** [comment]
What's wrong with `onRowClick`?  [You can easily override the row element](https://material-table.com/#/docs/features/component-overriding)..  Use the default row component (`MTableBodyRow`) wrapped in a `div` with a `title` attribute. 

Similar to this example, but using the row component mentioned above, as well as a title attribute instead of style.. You should be able to integrate logic which determines the rendered title. 

Taken from the docs:

```javascript
import MaterialTable, { MTableToolbar } from 'material-table';

<MaterialTable
    // other props
    components={{
        Toolbar: props => (
            <div style={{ backgroundColor: '#e8eaf5' }}>
                <MTableToolbar {...props} />
            </div>
        )
    }}
/>
```

**Comment by orhanhub** [comment]
thanks for the responses oze4, wrapping MTableBodyRow in a div causes validateDOMNesting error on the console and the table formatting is ignored. To fix it you can use MTableBodyRow without wrapping in a div.

**Comment by oze4** [comment]
@orhanhub nice!  Glad it works.

**Comment by oze4** [comment]
This issue looks to be resolved. Please open if you feel it was closed in error.

**Comment by alexander-r-jaimy** [comment]
I must say that I'm totally lost for how to achieve this behavior.
I need to convert a row into `<a>` tag. My previous solution was styling the row with a `display:table-row`. 
How can I modify a MTableBodyRow to replicate same behavior?

**Comment by gideonaina** [comment]
> thanks for the response @oze4, wrapping MTableBodyRow in a div causes validateDOMNesting error on the console and the table formatting is ignored. To fix it you can use MTableBodyRow without wrapping in a div.

"use MTableBodyRow without wrapping in a div" ? Any sample code please. I would think I have to wrap it in something. Thank you
