### ISSUE TITLE
How to add multi select/ dropdown on edit.

### ISSUE THREAD

**Issue by tech-khushboo** [mbrn/material-table#823]
Using lookup I am able to select a single option. How to select multiple?
Like in the filter you are giving checkbox and selecting more than one option that same thing I want to implement with the edit.

**Comment by hutber** [comment]
I'm jut looking at this now, if I find any solution I'll let you know, kisses

**Comment by hutber** [comment]
Hey you guys!
So ye, its possible: https://github.com/mbrn/material-table/issues/1492
I put a little example in there for where to look.
I would say you can close this issue now.
