### ISSUE TITLE
How to access table ref in parent component?

### ISSUE THREAD

**Issue by chaitanya1019** [mbrn/material-table#827]
Hi i'm struggling in accessing the table ref of material- table in a parent component.
My use case is as follows:
I have a form to search a job, up on getting a response of matched jobs i will show them in material-table. i'm passing a function to data prop in material-table to manage data fetching and tableref to forcefully fetch data when the user has modified the search criteria.i'm passing the search data as props to jobsearch results component and calling this.tableref.current.onQueryChange() in componentDidUpdate to fetch data. JobSearchResults is inside JobSearch Component, and is conditionally rendered if there is data. I would like to call tableRef onQueryChange method in Jobsearch component.
Please help.

**Comment by benjaminvdb** [comment]
Here's some example code. I haven't compiled it so I can't give any guarantees, but you might find it helpful anyway.

The idea is to create a forward reference using `React.createRef()` in the outer scope and pass it to the table component using the `ref` prop. You can then access the table component using the reference. For more details see [Forwarding Refs
](https://reactjs.org/docs/forwarding-refs.html)

```
const ParentComponent = () => {
    const tableRef = React.createRef();
    const [allSelected, setAllSelected] = useState(false);

    const handleSelectAll = () => {
        setAllSelected(!allSelected);
        tableRef.current.onAllSelected(setAllSelected)
    }

    <MaterialTable
        data={ {id: 1, value: "First row"}, {id: 2, value: "Second row"} }
        columns={{ title: "Diagnose", field: "value" }}
        tableRef={ tableRef }
        options={{
            selection: true
        }
    />

    <Button onClick={handeSelectAll}>Toggle</Button>;
}
```
