### ISSUE TITLE
How to add new row in between the table using row actions

### ISSUE THREAD

**Issue by sabahath786** [mbrn/material-table#829]
I really appreciate your work on Material Table, Im trying to implement new actions on each row of the table, 
**To Reproduce**

1. Add action [+] to all the rows of the table.
2. On click on add action, new empty row should be created above the current row, 
like, if the selected row index is 5, new row should be created (5-1) index.

**Comment by sabahath786** [comment]
Hi

Nope this was my query how can i add [+] button for each row, this is just a prototype i added when i raised the question for better understanding. it would be more appreciated if i get code how i can add it.

**Comment by Domino987** [comment]
The add empty row between rows (not end or start) is currently not supported. Can you make a PR if you need this feature?

**Comment by sabahath786** [comment]
I need this feature

**Comment by Domino987** [comment]
It is not supported. Can you create a PR to address this?
