### ISSUE TITLE
Override plus button functionality for adding new table row

### ISSUE THREAD

**Issue by iqasim-com** [mbrn/material-table#830]
Instead of using material-table predefined plus icon for adding new row, i want to add plus icon functionality to the *Add new region* button
image attached below

![image](https://user-images.githubusercontent.com/23281307/61214374-323b0980-a721-11e9-9ed9-3f4e0a4c4b9d.png)

**Comment by nalgritz** [comment]
you can add a `icons` props like this
```
<MaterialTable
    columns={columnData}
    data={data}
    icons={{
        Add: props => <Icon {...props} />
    }}
/>
```

but one thing is that all the buttons are preset `<IconButton />` with a ripple effect. I want it to be overridden by a simple button with text but still finding a way.

**Comment by mqasim1990** [comment]
Thanks for your reply @nalgritz 
This is exactly what i want but i want to add this icon outside of this table like in above image, i want to place this in **Add new Region** location

**Comment by sabahath786** [comment]
@mqasim1990 , I have the same query, but my add row action is on the row itself, i want to add one action on the row add(+) and onclick on this icons i want to create an empty row below the current(selected row) ,

Please find attached image, i have added [+] icon for each row, onClick of [+] ,I am trying to create empty row below or above. I have been stuck from two days. 
1.Tried with component over riding, it did not work

I really appreciate your help.
Thanks in advance. 
![attachedGithub](https://user-images.githubusercontent.com/52918792/61289296-b4830680-a7d1-11e9-9485-2faeaad29d5d.PNG)
 row.

**Comment by nalgritz** [comment]
hello @mqasim1990 & @sabahath786 , I guess we are looking for the same feature while this requires material-table to expose the Add click event so that we can apply outside the table. I haven't had time to dig the package so I'm sorry I can't help at the moment.

hope anyone can help or exposing the method is a feature request?

thanks both.

**Comment by Nicolas-Medina-Teracode** [comment]
I need exactly the same, if anyone made any progress with that please let us know :)

**Comment by durgeshsatyam** [comment]
I have figured out a naughty solution to do this job.
Add a ref in the new overridden icon Add like this.
`
...
  // initializing a ref in React.
  const myTextIcon = React.useRef(null);
...
<MaterialTable
    ...
    icons={{
        Add: props => (
          <div ref={myTextIcon} className={classes.addButton}>
            <i className="fa fa-plus" />
            Add new Region
          </div>
        ),
      }}
...
/>
`
Now we accessed our parent of parent element via that ref like shown in code below in the useEffect() where it seems to have an IconButton.
and we deleted the class responsible for this ripple: 'MuiIconButton-root'
As in code snippet below.
(Note: you can also use componentDidMount() instead of useEffect()).
`
  React.useEffect(() => {
    // removing the class 'MuiIconButton-root' from parent of parent of our ref node.
    myTextIcon.current.parentNode.parentNode.classList.remove('MuiIconButton-root');
  }, []);
`

I hope it will remove the ripples.
Thanks
Regards.

**Comment by sabahath786** [comment]
@durgeshsatyam , Hello Durgesh, if you check my query, I am not trying to override action, im trying to add [+] action on row itself, from which i can able to insert new row after every row on [+] click,

I really appreciate if you can help me out.
Thanks in advance.

**Comment by antonioiliev** [comment]
I need exactly the same feature as @sabahath786, @Nicolas-Medina-Teracode  and @nalgritz have pointed out above! Any progress is very welcome.

**Comment by sergeycw** [comment]
Hi guys! Everything is great, but how I can disable hover on custom add button?

**Comment by sabahath786** [comment]
Any progress on my query ? or any clue please !

**Comment by Inaki-Berra-Teracode** [comment]
I'm trying to add a new button to the Add Icon, not an icon. But the problem is that it wraps the icon in a button. Could we have a way to add a component? Or maybe a way to remove the hover effect that it adds.
<img width="480" alt="Screen Shot 2019-09-05 at 10 32 52" src="https://user-images.githubusercontent.com/49873925/64355691-07aa5600-cfd8-11e9-8ae5-d883c3ca4360.png">

**Comment by masbaehr** [comment]
I also had this problem and solved it like this: 
Plain old javascript comes to the rescue:

First override the add icon manually by setting a custom data attribute for the query selector
```javascript
icons={{
                Add: props => <Icon data-mycustomid={"add-icon-handler"} />
              }}
```

then use this code snippet wherever you want to trigger the add. So you can hide the original icon and show the add function at any place

```javascript
document.querySelector("[data-mycustomid='add-icon-handler']").parentNode.click()
```

**Comment by shasanka** [comment]
here is a little hack :
 `icons={{
													Add: props => (
													<div> 
														<Button
															variant="contained"
															size="small"
															style={{
															borderRadius: "25px",
															boxShadow: "none",
															backgroundColor: "#4E9ABF"
															}}
															{...props}
															> 
															<AddIcon fontSize="small"
                                  								style={{ color: "#FFFFFF" }}/>
															<Typography
															variant="button"
															style={{
																fontSize: "10px",
																color: "white"
															}}
															>
															ADD NEW
															</Typography>
														</Button>
													</div>)
												}}`

**Comment by eborrallo** [comment]
Try this

`
import { forwardRef } from "react";
import Fab from "@material-ui/core/Fab";
import AddIcon from "@material-ui/icons/Add";

<MaterialTable
// ... your other props
icons={{
            Add: forwardRef((props, ref) => (
              <Fab ref={ref} {...props} color="primary" aria-label="add">
                <AddIcon /> 
              </Fab>
            ))
          }}
/>
`

**Comment by hshelbur** [comment]
An easy workaround to remove the ripple is to add `display: none` in your css for the class responsible for the ripple: `.MuiTouchRipple-root`

**Comment by getMeName** [comment]
Hello to All,
I want to add to the Add button an additional functionality - I want once I click the button to redirect me to the top of the page - on scroll at the moment with CSS I added a "stciky" property of the toolbar and the content of the table is big and when I click the button it adds new row to the top of the page - but the page does not scroll to the top - it stays at the point of scroll - in the middle of the page for example. I want to add something small - an arrow function maybe just once it is cliked to get me to the top of the page

**Comment by ucka6kabal** [comment]
> Hello to All,
> I want to add to the Add button an additional functionality - I want once I click the button to redirect me to the top of the page - on scroll at the moment with CSS I added a "stciky" property of the toolbar and the content of the table is big and when I click the button it adds new row to the top of the page - but the page does not scroll to the top - it stays at the point of scroll - in the middle of the page for example. I want to add something small - an arrow function maybe just once it is cliked to get me to the top of the page

@mbrn could you please have a look, is there a way to do that?

**Comment by umarethina** [comment]
Hey all! 
I had the same issue, found a solution, might help someone. I'm new to react, please comment, if this is not the right way to approach the issue. thank you!

 <MaterialTable
     ...
     actions={[
          {
              icon: 'cloud_upload',
              tooltip: 'Upload',
              isFreeAction: true
          }
      }]
       components={{
           Action: props => {
              if(props.action.icon === 'cloud_upload'){
                  return(
                     <Button>
                         ...... 
                    </Button>
                  )
             }

This works for me!!

**Comment by umarethina** [comment]
After adding this code in, I realized it better not to override with components. An easier approach would be to add the iconButton as a const and use that in the iconButton. This way you will still be able to use the editable functionality of the material table. Hope this helps! @ucka6kabal 

`  const uploadButtonIcon = () => <Button variant="contained" component="label" className={classes.uploadButton} >
                                    <i className="material-icons md-16">cloud_upload</i>
                                    Upload APK
                                    <input type="file"
                                           className={classes.uploadFileInput}
                                           accept="*.apk"
                                           onChange={(e) => handleAPKUpload(e.target.files)}></input>
                                 </Button>`

`actions={[
              {
                icon: props => uploadButtonIcon(),
                tooltip: 'Upload APK',
                isFreeAction: true
              },
            ]}`

**Comment by thisismydesign** [comment]
We'd also like to customize the add button and the current way it works makes that difficult.

**Comment by masbaehr** [comment]
> 
> 
> > Hello to All,
> > I want to add to the Add button an additional functionality - I want once I click the button to redirect me to the top of the page - on scroll at the moment with CSS I added a "stciky" property of the toolbar and the content of the table is big and when I click the button it adds new row to the top of the page - but the page does not scroll to the top - it stays at the point of scroll - in the middle of the page for example. I want to add something small - an arrow function maybe just once it is cliked to get me to the top of the page
> 
> @mbrn could you please have a look, is there a way to do that?

Note: To scroll something to the top you can simply do a scrollTop = of that element (if it's the page  use window.scrollTop, and if inside an element something like this:

```javascript
document.querySelector(".MuiTable-root").parentNode.scrollTop = 0
```

**Comment by chitgoks** [comment]
There are problems to these. if you manage to override the add button, what happens to the delete and update buttons in every row?

in my case, i only wish to have the add button do something else instead of adding a new row. e.g. show an alert()

**Comment by the-lazy-val** [comment]
Is there a way, I can override plus [+] button functionality to open a new dialog box.

**Comment by chitgoks** [comment]
add an icon in actions property and set isFreeAction to true, then you can open the dialog in the onClick() event.

**Comment by Solijons** [comment]
> add an icon in actions property and set isFreeAction to true, then you can open the dialog in the onClick() event.

Thank you for this @chitgoks fixed my issue.

**Comment by hardyyb3** [comment]
> I'm trying to add a new button to the Add Icon, not an icon. But the problem is that it wraps the icon in a button. Could we have a way to add a component? Or maybe a way to remove the hover effect that it adds.
> <img alt="Screen Shot 2019-09-05 at 10 32 52" width="480" src="https://user-images.githubusercontent.com/49873925/64355691-07aa5600-cfd8-11e9-8ae5-d883c3ca4360.png">

Any soultions to this one yet

**Comment by Solijons** [comment]
> > I'm trying to add a new button to the Add Icon, not an icon. But the problem is that it wraps the icon in a button. Could we have a way to add a component? Or maybe a way to remove the hover effect that it adds.
> > <img alt="Screen Shot 2019-09-05 at 10 32 52" width="480" src="https://user-images.githubusercontent.com/49873925/64355691-07aa5600-cfd8-11e9-8ae5-d883c3ca4360.png">
> 
> Any solutions to this one yet

 <MaterialTable
              components={{
                Actions: (props) => {
                  return(
                    <Button
                      onClick={() => console.log('click')}
                    >Hello World</Button>
                  );
                }
              }}
              actions={[
                {
                  icon: 'add',
                  onClick: (event: any, rowData: any) => {
                    console.log('Hello World!');
                  },
                  isFreeAction: true,
                  tooltip: 'Add Button',
                }
              ]}
              data={[]}
              columns={[]}
            />

You are going to have override component. See above how I am doing it. Hope it helps

**Comment by vaniatoperich** [comment]
> I also had this problem and solved it like this:
> Plain old javascript comes to the rescue:
> 
> First override the add icon manually by setting a custom data attribute for the query selector
> 
> ```js
> icons={{
>                 Add: props => <Icon data-mycustomid={"add-icon-handler"} />
>               }}
> ```
> 
> then use this code snippet wherever you want to trigger the add. So you can hide the original icon and show the add function at any place
> 
> ```js
> document.querySelector("[data-mycustomid='add-icon-handler']").parentNode.click()
> ```

I am trying to implement this approach for a "selection" action but not sure where to place the querySelector to?

**Comment by agatatocz** [comment]
> > > I'm trying to add a new button to the Add Icon, not an icon. But the problem is that it wraps the icon in a button. Could we have a way to add a component? Or maybe a way to remove the hover effect that it adds.
> > > <img alt="Screen Shot 2019-09-05 at 10 32 52" width="480" src="https://user-images.githubusercontent.com/49873925/64355691-07aa5600-cfd8-11e9-8ae5-d883c3ca4360.png">
> > 
> > 
> > Any solutions to this one yet
> 
> ```
>  <MaterialTable
>               components={{
>                 Actions: (props) => {
>                   return(
>                     <Button
>                       onClick={() => console.log('click')}
>                     >Hello World</Button>
>                   );
>                 }
>               }}
>               actions={[
>                 {
>                   icon: 'add',
>                   onClick: (event: any, rowData: any) => {
>                     console.log('Hello World!');
>                   },
>                   isFreeAction: true,
>                   tooltip: 'Add Button',
>                 }
>               ]}
>               data={[]}
>               columns={[]}
>             />
> ```
> 
> You are going to have override component. See above how I am doing it. Hope it helps

Unfortunately it overrides all the actions so we get the add button instead of edit and delete icons. In my case isFreeAction does not do anything - the behaviour is the same no matter what value I pass.

**Comment by masbaehr** [comment]
> 
> 
> > I also had this problem and solved it like this:
> > Plain old javascript comes to the rescue:
> > First override the add icon manually by setting a custom data attribute for the query selector
> > ```js
> > icons={{
> >                 Add: props => <Icon data-mycustomid={"add-icon-handler"} />
> >               }}
> > ```
> > 
> > 
> > then use this code snippet wherever you want to trigger the add. So you can hide the original icon and show the add function at any place
> > ```js
> > document.querySelector("[data-mycustomid='add-icon-handler']").parentNode.click()
> > ```
> 
> I am trying to implement this approach for a "selection" action but not sure where to place the querySelector to?

in the onClick handler of the component you want to perform the add action

**Comment by Solijons** [comment]
> actions={[
>                 {
>                   icon: 'add',
>                   onClick: (event: any, rowData: any) => {
>                     console.log('Hello World!');
>                   },
>                   isFreeAction: true,
>                   tooltip: 'Add Button',
>                 }
>               ]}

            <MaterialTable
              title="Some table"
              columns={[
                { field: 'val', title: 'Value' },
                { field: 'number', title: 'Number' },
              ]}
              data={[
                { val: 'Data', number: 0 }
              ]}
              actions={[
                {
                  icon: () =>  <span>Button</span>,
                  onClick: (event: any, rowData: any) => {
                    console.log('Hello World!');
                  },
                  isFreeAction: true,
                  tooltip: 'Add Button',
                }
              ]}
            />

I think if you dont want to lose edi, delete features try doing this way, Override icon icon: () =>  <span>Button</span>. Unfortunately, you are going to style your span to look like button. Let me know if it works.

**Comment by Solijons** [comment]
> > > > I'm trying to add a new button to the Add Icon, not an icon. But the problem is that it wraps the icon in a button. Could we have a way to add a component? Or maybe a way to remove the hover effect that it adds.
> > > > <img alt="Screen Shot 2019-09-05 at 10 32 52" width="480" src="https://user-images.githubusercontent.com/49873925/64355691-07aa5600-cfd8-11e9-8ae5-d883c3ca4360.png">
> > > 
> > > 
> > > Any solutions to this one yet
> > 
> > 
> > ```
> >  <MaterialTable
> >               components={{
> >                 Actions: (props) => {
> >                   return(
> >                     <Button
> >                       onClick={() => console.log('click')}
> >                     >Hello World</Button>
> >                   );
> >                 }
> >               }}
> >               actions={[
> >                 {
> >                   icon: 'add',
> >                   onClick: (event: any, rowData: any) => {
> >                     console.log('Hello World!');
> >                   },
> >                   isFreeAction: true,
> >                   tooltip: 'Add Button',
> >                 }
> >               ]}
> >               data={[]}
> >               columns={[]}
> >             />
> > ```
> > 
> > 
> > You are going to have override component. See above how I am doing it. Hope it helps
> 
> Unfortunately it overrides all the actions so we get the add button instead of edit and delete icons. In my case isFreeAction does not do anything - the behaviour is the same no matter what value I pass.

> actions={[
>                 {
>                   icon: 'add',
>                   onClick: (event: any, rowData: any) => {
>                     console.log('Hello World!');
>                   },
>                   isFreeAction: true,
>                   tooltip: 'Add Button',
>                 }
>               ]}

            <MaterialTable
              title="Some table"
              columns={[
                { field: 'val', title: 'Value' },
                { field: 'number', title: 'Number' },
              ]}
              data={[
                { val: 'Data', number: 0 }
              ]}
              actions={[
                {
                  icon: () =>  <span>Button</span>,
                  onClick: (event: any, rowData: any) => {
                    console.log('Hello World!');
                  },
                  isFreeAction: true,
                  tooltip: 'Add Button',
                }
              ]}
            />

I think if you dont want to lose edit, delete features try doing this way, Override your add icon: () =>  <span>Button</span>. Unfortunately, you are going to style your span to look like button. Let me know if it works.

**Comment by agatatocz** [comment]
> > > > > I'm trying to add a new button to the Add Icon, not an icon. But the problem is that it wraps the icon in a button. Could we have a way to add a component? Or maybe a way to remove the hover effect that it adds.
> > > > > <img alt="Screen Shot 2019-09-05 at 10 32 52" width="480" src="https://user-images.githubusercontent.com/49873925/64355691-07aa5600-cfd8-11e9-8ae5-d883c3ca4360.png">
> > > > 
> > > > 
> > > > Any solutions to this one yet
> > > 
> > > 
> > > ```
> > >  <MaterialTable
> > >               components={{
> > >                 Actions: (props) => {
> > >                   return(
> > >                     <Button
> > >                       onClick={() => console.log('click')}
> > >                     >Hello World</Button>
> > >                   );
> > >                 }
> > >               }}
> > >               actions={[
> > >                 {
> > >                   icon: 'add',
> > >                   onClick: (event: any, rowData: any) => {
> > >                     console.log('Hello World!');
> > >                   },
> > >                   isFreeAction: true,
> > >                   tooltip: 'Add Button',
> > >                 }
> > >               ]}
> > >               data={[]}
> > >               columns={[]}
> > >             />
> > > ```
> > > 
> > > 
> > > You are going to have override component. See above how I am doing it. Hope it helps
> > 
> > 
> > Unfortunately it overrides all the actions so we get the add button instead of edit and delete icons. In my case isFreeAction does not do anything - the behaviour is the same no matter what value I pass.
> 
> > actions={[
> > {
> > icon: 'add',
> > onClick: (event: any, rowData: any) => {
> > console.log('Hello World!');
> > },
> > isFreeAction: true,
> > tooltip: 'Add Button',
> > }
> > ]}
> 
> ```
>         <MaterialTable
>           title="Some table"
>           columns={[
>             { field: 'val', title: 'Value' },
>             { field: 'number', title: 'Number' },
>           ]}
>           data={[
>             { val: 'Data', number: 0 }
>           ]}
>           actions={[
>             {
>               icon: () =>  <span>Button</span>,
>               onClick: (event: any, rowData: any) => {
>                 console.log('Hello World!');
>               },
>               isFreeAction: true,
>               tooltip: 'Add Button',
>             }
>           ]}
>         />
> ```
> 
> I think if you dont want to lose edit, delete features try doing this way, Override your add icon: () => Button. Unfortunately, you are going to style your span to look like button. Let me know if it works.

It works :D Thank you!

**Comment by BilalDev** [comment]
Hi, I've the same problem but I need props in icon property to access data. Something like this :
`icon: (props) =>  <Switch checked={props.data.someBoolean} /> `
Is this possible ?

**Comment by LoicHa** [comment]
Hello guys i manage to perform it thanks to this comment on stack : https://stackoverflow.com/questions/55846015/how-to-remove-background-ripple-effect-from-custom-action-button-in-material-tab

I have now a perfect addbutton styled as i wished 
![image](https://user-images.githubusercontent.com/28562111/82038488-e68c2000-96a3-11ea-8a20-2091cbcb6d16.png)

**Comment by oze4** [comment]
If I am understanding this correctly, you want to be able to add a new row using a button that lives outside of material-table?

The only way I could get this to work is by using `tableRef` as well as tying the `editable` prop to state.  The biggest downside to this is that while you are in the process of adding a new row, the toolbar icon is visible (the one you don't want shown).  In order to resolve that issue, I had to override the Toolbar component, and filter out which actions are shown.

Please keep in mind this is hacky, but it gets the job done.

You can view a [live demo here](https://stackblitz.com/edit/react-vubq1a?embed=1&file=index.js)

```javascript
import React, { useRef, useState } from "react";
import { render } from "react-dom";
import MaterialTable, { MTableToolbar } from "material-table";
import tableIcons from "./TableIcons.js";

import "./style.css";

const rando = max => Math.floor(Math.random() * max);
const rawData = ["Rock", "Paper", "Scissors"].map(name => ({
  id: rando(100),
  name
}));

const columns = [
  { field: "id", title: "Id" },
  { field: "name", title: "Name" }
];

const App = () => {
  const [editable, setEditable] = useState();
  const [data, setData] = useState(rawData);
  const tableRef = useRef();

  const handleAddRow = () => {
    tableRef.current.state.showAddRow = true;
    setEditable({
      onRowAdd: newData =>
        new Promise((resolve, reject) => {
          setEditable();
          setData([...data, newData]);
          resolve();
        })
    });
  };

  return (
    <div>
      <button onClick={handleAddRow} className="add-row-btn">
        Add New Row
      </button>
      <p>The button above is located outside of material-table</p>
      
      <MaterialTable
        tableRef={tableRef}
        data={data}
        icons={tableIcons}
        columns={columns}
        editable={editable}
        options={{
          actionsColumnIndex: -1
        }}
        components={{
          Toolbar: props => (
            <MTableToolbar
              {...props}
              actions={props.actions.filter(a => a.tooltip !== "Add")}
            />
          )
        }}
      />
    </div>
  );
};

render(<App />, document.querySelector("#root"));
```

**Comment by kobechenyang** [comment]
Is there anyway to listen to the onClick event of default add button?

**Comment by oze4** [comment]
@kobechenyang are you referring to the "default add button" as the button that appears when you set:

```javascript
<MaterialTable editable={{ 
    onRowAdd: props => { ... }
  }}
/>
```
If so, I have not found a native way to listen for that onClick event. The best I have been able to do is override components to intercept events..

**Comment by kobechenyang** [comment]
@oze4 yes. But I want to keep the same behavior. I guess I can do what you do here
`const handleAddRow = () => {
    tableRef.current.state.showAddRow = true;
    setEditable({
      onRowAdd: newData =>
        new Promise((resolve, reject) => {
          setData([...data, newData]);
          setEditable();
          resolve();
        })
    });
  };`

**Comment by oze4** [comment]
Hey @kobechenyang I have a similar demo..

It is not complete - the only bug is that you can only select 'Add Row' one time.. If you select "Add Row", then cancel, and try to select "Add Row" again, nothing happens. Need to find a way to reset the state is where I left off, I believe..

[Live demo here](https://stackblitz.com/edit/react-fvu6j5?embed=1&file=index.js)

```javascript
import React, { useState, useRef } from "react";
import { render } from "react-dom";
import MaterialTable, { MTableActions, MTableEditRow } from "material-table";
import { AddBox } from "@material-ui/icons";
import tableIcons from "./TableIcons.js";

const originalData = ["Rock", "Paper", "Scissors"].map(word => {
  return {
    id: Math.floor(Math.random() * 300),
    name: word
  };
});

function App() {
  const tableRef = useRef();
  const [isAdding, setIsAdding] = useState(false);
  const [data, setData] = useState(originalData);

  return (
    <MaterialTable
      tableRef={tableRef}
      data={data}
      title="Override onRowAdd Demo"
      icons={tableIcons}
      columns={[
        {
          title: "Id",
          field: "id"
        },
        {
          title: "Name",
          field: "name"
        },
      ]}
      actions={[
        (rowData => ({
          position: "toolbar",
          icon: AddBox,
          tooltip: "Add row",
          onClick: (event, newRow) => {
            tableRef.current.state.showAddRow = true;
            setIsAdding(true)
          }
        }))({ position: 'toolbar' })
      ]}
      components={{
        Actions: (props, rowData) => {
          console.log({ from: 'components.Actions', props, rowData, tableRef });
          return (
            <MTableActions 
              {...props}
              onEditingCanceled={(mode, rowData) => {
                rowData.tableData.editing = undefined;
                forceUpdate();
              }}
              onEditingApproved={(mode, newData, oldData) => {
                const dataCopy = [...data];
                const index = dataCopy.indexOf(oldData);
                dataCopy[index] = newData;
                setData(dataCopy);
              }}
            />
          );
        }
      }}
      options={{
        actionsColumnIndex: -1
      }}
      localization={{
        header: {
          actions: '',
        }
      }}
    />
  );
}

render(<App />, document.querySelector("#root"));
```

**Comment by kobechenyang** [comment]
What I want to achieve is pre-populate the rowdata when the add button is clicked.
Looks like `tableRef.current.state.showAddRow = true;` will create a new empty rowData by itself. 
it would be nice if there is a `onEditingStarted` event so we can manage the data by ourselves. 
I ended up with something like this
```javascript
<MTableEditRow
 {...props}
   data={props.data?props.data:newItem}
   onEditingCanceled={(mode, rowData) => {
     cancelEdit();
     props.onEditingCanceled(mode);
   }}
 />
```

`newItem` is a state I manage locally and have the data I want populated.

**Comment by oze4** [comment]
Hey @kobechenyang you can accomplish this by following these steps:

[You can view a live demo here](https://stackblitz.com/edit/react-amqzyk?embed=1&file=index.js)

 - Create a default row object (this default object could potentially reside in state as well....something to think about)
```javascript
// Keep in mind, this object must have the same shape 
// as all of the other objects in the main 'data' prop..
const DEFAULT_ROW_OBJECT = {
  id: "999999",
  name: "Joe Schmoe",
}
```
 - Override the `EditRow` component
```javascript
components={{
  EditRow: props => {
    const propsCopy = { ...props };
    propsCopy.data = DEFAULT_ROW_OBJECT;
    return <MTableEditRow {...propsCopy} />
  } 
}}
```
**Core of live demo:**

```javascript
import React, { useState } from "react";
import { render } from "react-dom";
import MaterialTable, { MTableEditRow } from "material-table";
import tableIcons from "./TableIcons.js";

const DEFAULT_ROW_OBJECT = {
  id: "Hello, I am",
  name: "the default object!",
}

const originalData = ["Rock", "Paper", "Scissors"].map(word => ({
  id: Math.floor(Math.random() * 300),
  name: word
}));

function App() {
  const [data, setData] = useState(originalData);

  return (
    <MaterialTable
      data={data}
      icons={tableIcons}
      columns={[
        {
          title: "Id",
          field: "id"
        },
        {
          title: "Name",
          field: "name"
        },
      ]}
      editable={{
        onRowAdd: newRowData => {
          return new Promise((resolve, reject) => {
            setData(oldData => [...oldData, ...newRowData]);
            resolve();
          })
        }
      }}
      components={{
        EditRow: props => {
          const propsCopy = { ...props };
          propsCopy.data = DEFAULT_ROW_OBJECT;
          return <MTableEditRow {...propsCopy} />
        } 
      }}
      options={{
        actionsColumnIndex: -1
      }}
    />
  );
}

render(<App />, document.querySelector("#root"));
```

**Comment by oze4** [comment]
@kobechenyang actually, [it looks like the `column.initialEditValue` is what you're looking for..](https://material-table.com/#/docs/features/editable)

**Comment by kobechenyang** [comment]
> @kobechenyang actually, [it looks like the `column.initialEditValue` is what you're looking for..](https://material-table.com/#/docs/features/editable)

ah I missed that. Thanks !

**Comment by awarmfastbear** [comment]
@LoicHa 
> 
> Hello guys i manage to perform it thanks to this comment on stack : https://stackoverflow.com/questions/55846015/how-to-remove-background-ripple-effect-from-custom-action-button-in-material-tab
> 
> I have now a perfect addbutton styled as i wished , without the warning of a button embeded in a button
> ![image](https://user-images.githubusercontent.com/28562111/82038488-e68c2000-96a3-11ea-8a20-2091cbcb6d16.png)

Could you please provide an example as to how you were able to Style your AddButton in the upper left?

**Comment by LoicHa** [comment]
> @LoicHa
> 
> > Hello guys i manage to perform it thanks to this comment on stack : https://stackoverflow.com/questions/55846015/how-to-remove-background-ripple-effect-from-custom-action-button-in-material-tab
> > I have now a perfect addbutton styled as i wished , without the warning of a button embeded in a button
> > ![image](https://user-images.githubusercontent.com/28562111/82038488-e68c2000-96a3-11ea-8a20-2091cbcb6d16.png)
> 
> Could you please provide an example as to how you were able to Style your AddButton in the upper left?

@awarmfastbear,

Yes , SASS code bellow
```
.MuiToolbar-root {
    > div:nth-child(1) {
      order:2;
      text-indent:20px;
    }
    > div:nth-child(2) {
      order:1;
    }
    > div:nth-child(3) {
      order:3;
    }
    > div:nth-child(4) {
      order:4;
    }
}
```

**Comment by oze4** [comment]
This issue looks to be resolved. Thanks everyone! Feel free to reopen if you feel it should be open.

**Comment by apple151947** [comment]
> @mqasim1990 , I have the same query, but my add row action is on the row itself, i want to add one action on the row add(+) and onclick on this icons i want to create an empty row below the current(selected row) ,
> 
> Please find attached image, i have added [+] icon for each row, onClick of [+] ,I am trying to create empty row below or above. I have been stuck from two days.
> 1.Tried with component over riding, it did not work
> 
> I really appreciate your help.
> Thanks in advance.
> ![attachedGithub](https://user-images.githubusercontent.com/52918792/61289296-b4830680-a7d1-11e9-9485-2faeaad29d5d.PNG)
> row.

@sabahath786 ,
Were you able to achieve the add [+] functionality on each row?? Could you please share the code??

**Comment by sabahath786** [comment]
HI,

Nope this was my query how can i add [+] button for each row, this is just
a prototype i added when i raised the question for better understanding. it
would be more appreciated if i get code how i can add it.




Thanks & regards
Sabahath Anjum
Software Engineer

**Comment by Vinhtu** [comment]
> If I am understanding this correctly, you want to be able to add a new row using a button that lives outside of material-table?
> 
> The only way I could get this to work is by using `tableRef` as well as tying the `editable` prop to state. The biggest downside to this is that while you are in the process of adding a new row, the toolbar icon is visible (the one you don't want shown). In order to resolve that issue, I had to override the Toolbar component, and filter out which actions are shown.
> 
> Please keep in mind this is hacky, but it gets the job done.
> 
> You can view a [live demo here](https://stackblitz.com/edit/react-vubq1a?embed=1&file=index.js)
> 
> ```js
> import React, { useRef, useState } from "react";
> import { render } from "react-dom";
> import MaterialTable, { MTableToolbar } from "material-table";
> import tableIcons from "./TableIcons.js";
> 
> import "./style.css";
> 
> const rando = max => Math.floor(Math.random() * max);
> const rawData = ["Rock", "Paper", "Scissors"].map(name => ({
>   id: rando(100),
>   name
> }));
> 
> const columns = [
>   { field: "id", title: "Id" },
>   { field: "name", title: "Name" }
> ];
> 
> const App = () => {
>   const [editable, setEditable] = useState();
>   const [data, setData] = useState(rawData);
>   const tableRef = useRef();
> 
>   const handleAddRow = () => {
>     tableRef.current.state.showAddRow = true;
>     setEditable({
>       onRowAdd: newData =>
>         new Promise((resolve, reject) => {
>           setData([...data, newData]);
>           setEditable();
>           resolve();
>         })
>     });
>   };
> 
>   return (
>     <div>
>       <button onClick={handleAddRow} className="add-row-btn">
>         Add New Row
>       </button>
>       <p>The button above is located outside of material-table</p>
> 
>       <MaterialTable
>         tableRef={tableRef}
>         data={data}
>         icons={tableIcons}
>         columns={columns}
>         editable={editable}
>         options={{
>           actionsColumnIndex: -1
>         }}
>         /// IF YOU DONT WANT TO SEE THE ADD ACTION WITHIN 
>         /// THE TOOLBAR WHEN YOU ARE ADDING A NEW ROW THEN
>         /// YOU WILL NEED TO UNCOMMENT THIS:
>         // components={{
>         //   Toolbar: props => (
>         //     <MTableToolbar
>         //       {...props}
>         //       actions={props.actions.filter(a => a.tooltip !== "Add")}
>         //     />
>         //   )
>         // }}
>       />
>     </div>
>   );
> };
> 
> render(<App />, document.querySelector("#root"));
> ```

Hi. thank you . but i want it have button edit and update when i have a checkbox. you have a solution ?

**Comment by Vinhtu** [comment]
> n accomplish this by following these steps:

 @oze4 Hi. thank you . but i want it have button edit and update when i have a checkbox. you have a solution ?

**Comment by NikhilChugh** [comment]
> @mqasim1990 , I have the same query, but my add row action is on the row itself, i want to add one action on the row add(+) and onclick on this icons i want to create an empty row below the current(selected row) ,
> 
> Please find attached image, i have added [+] icon for each row, onClick of [+] ,I am trying to create empty row below or above. I have been stuck from two days.
> 1.Tried with component over riding, it did not work
> 
> I really appreciate your help.
> Thanks in advance.
> ![attachedGithub](https://user-images.githubusercontent.com/52918792/61289296-b4830680-a7d1-11e9-9485-2faeaad29d5d.PNG)
> row.

Hi, If someone is still looking for a solution, the way is to manipulate the data(with editable props in header) on click of plus icon , instead of manipulating the material table structure.

**Comment by DineshPrakasam** [comment]
in material table tree view while  adding child component under a parent component,need to show that child component after adding in expansion.but it is getting as collapsed,(requirement is after adding child it should be expanded) ,kindly anyone help me on this,thanks.
