### ISSUE TITLE
Adding more options to export

### ISSUE THREAD

**Issue by HoyongJung** [mbrn/material-table#832]
Hi! I wish if I can add more options to the export button.

Is there a way to give a user options to export all or export data on the page?

Right now, when I click the export button, it only shows one option "Export CSV", but I thought it could be great if there is a list of options like "Export all Data as CSV", "Export Current Page Data as CSV" and etc.

**Comment by nikhilwbhatia** [comment]
+1

**Comment by lanhnguyen2010** [comment]
+1

**Comment by maxsd** [comment]
Hi ! Good idea :)
Is there already a way to add custom options in the export menu list so we could add a link or something ?

**Comment by salmanbabri** [comment]
Please make the export button dropdown more customizable so we can add options on-demand or rename them.

**Comment by Tickerabucky** [comment]
They already have it in their examples, but it is not reachable in source code.

https://material-table.com/#/docs/features/export
