### ISSUE TITLE
How define columns with lookup parameters dynamically?

### ISSUE THREAD

**Issue by jochercoles** [mbrn/material-table#833]
Hi, I'm using Material-table, and I have the follow problem. I have two columns with the lookup parameter defined in every columns. If I defined and load the array before to defined the columns, the component Material-table works well, but if I load dynamically the array, it isn't load or show in the component.

Examples, my code:

**This code Work well:**
let tp = { 0: 'SIN IDENTIFICAR', 1: 'LARGA DISTANCIA', 2: 'REPARTO', 3: 'RETIRO', 4: 'NO DESCUENTA COMBUSTIBLE' };

let soc = { 1100: "ALSA", 1200: "CASA" };

**This code don't Work as I hope:**
  let tp = {};
  props.SourceGrid[3].forEach(function( item ) {
    tp[item.keyDescuento] = item.descripcion;
  });  

  let soc = {};
  props.SourceGrid[4].forEach(function( item ) {
    soc[item.idSociedad] = item.sociedadDescripcion;
  });

**_Here, I have the definition of the columns of the Material-table component_**:
  const [state, setState] = React.useState({
    columns: [
      { title: 'usrPlazaDescuento', field: 'usrPlazaDescuento', hidden: true },
      { title: 'Usuario Plaza Descuento', field: 'nombre' },
      { title: 'Patente', field: 'patente' },
      { title: 'Tipo Descuento', field: 'tipoDescuentoId', **lookup: tp** },
      { title: 'Sociedad', field: 'sociedadId', **lookup: soc** },
    ],
    ....
    ....
  });

Regards, Javier.

**Comment by shivam123456789** [comment]
I am also facing the same issue, need help.

**Comment by perfectstrong** [comment]
Although there is no direct solution by far, an other way is putting your `lookup` objects in `state`, requesting API in `componentDidMount` then `setState`.

It should look like this:
````javascript
state = {
    isLoading: true,
    lookup: {},
    data: [],
};

componentDidMount = () => 
    fetchData()
        .then(newData =>
            this.setState({
                isLoading: false,
                lookup: newLookupObject,
                data: newData,
            })
        )
;

render() {
    return (
        <MaterialTable
            isLoading={this.state.isLoading}
            columns={[
                {
                    field: "first",
                    title: "firstColumn",
                    emptyValue: "",
                    lookup: this.state.lookup,
                }
            ]}
            data={this.state.data}
            />
    )
};
````
