### ISSUE TITLE
Lack of icon in free action

### ISSUE THREAD

**Issue by kslysz** [mbrn/material-table#838]
Hi, I've created an example with free action (https://codesandbox.io/embed/gifted-liskov-ih72m) Why my free action doesn't have an icon Filter?

**Comment by jdmairs** [comment]
why was this closed?  The codepen shows the icon missing and when I copy the Free action example from the docs the Add or AddBox icons does not display...I see the cropped word 'add' inside a circle.

**Comment by kslysz** [comment]
actions={[
                rowData => ({
                  icon: () => <ArrowDropUp />,
                  tooltip: 'Move up',
                  onClick: (event, rowData) => this.moveUp(rowData)
                }),
                rowData => ({
                  icon: () => <ArrowDropDown />,
                  tooltip: 'Move down',
                  onClick: (event, rowData) => this.moveDown(rowData)
                })
              ]}

**Comment by jdmairs** [comment]
that works
