### ISSUE TITLE
Custom action icon smaller than default edit icon.

### ISSUE THREAD

**Issue by jeffjvick** [mbrn/material-table#839]
**Describe the bug**
I have a table with the built-in edit action (editable) enabled and one custom action.  The custom action icons are smaller than the built-in edit one.  To make this more clear in the screenshot I assigned the custom action the 'edit' icon so you can see the size difference.

**To Reproduce**
Create a custom action and assign the 'edit' icon to it.
Make the row editable.

**Expected behavior**
Custom action icons should be the same size as the default icons.  Unless there is something I'm missing.

**Screenshots**
![Screen Shot 2019-07-16 at 11 34 47 PM](https://user-images.githubusercontent.com/203289/61352751-fdaf7680-a822-11e9-8a53-279ec34e1082.png)

**Comment by nikhilwbhatia** [comment]
Also running into this issue

**Comment by nikhilwbhatia** [comment]
@jeffjvick  can you remind me how you changed the icon size for custom action buttons?

**Comment by SVTerziev** [comment]
@nikhilwbhatia the only way is to update `fontSize = "small"` to _normal_ in node_modules/src/components/m-table-action.js

Usually you should be able to change it via [iconProps](https://material-ui.com/api/icon/), but currently the small font-size is being applied after `iconProps` and is overriding whatever value you pass to it.

I've created a pull request to fix this issue.

**Comment by SVTerziev** [comment]
@nikhilwbhatia the only way is to update `fontSize = "small"` to _default_ in node_modules/src/components/m-table-action.js

Usually you should be able to change it via [iconProps](https://material-ui.com/api/icon/), but currently the small font-size is being applied after `iconProps` and is overriding whatever value you pass to it.

I've created a pull request to fix this issue.

**Comment by SVTerziev** [comment]
@nikhilwbhatia the only way is to update `fontSize = "small"` to _default_ in node_modules/src/components/m-table-action.js

Usually you should be able to change it via [iconProps](https://material-ui.com/api/icon/), but currently the small font-size is being applied after `iconProps` and is overriding whatever value you pass to it.

I've created a pull request to fix this issue.

**Comment by nikhilwbhatia** [comment]
Thank you!
