### ISSUE TITLE
AlphaNumberic Sort

### ISSUE THREAD

**Issue by SilviaJoyceBalraj** [mbrn/material-table#84]
Example: 
Sorting works fine on the following values -  112300, 34500, 54300

But the below example does a string sort instead of an alphanumeric search:

$112,300
$34,500
$54,300

Expected O/P : 
$34,500
$54,300
$112,300

Actual O/P:
$112,300
$34,500
$54,300

**Comment by mbrn** [comment]
Hi @SilviaJoyceBalraj ,

We almost done this issue :)
