### ISSUE TITLE
How To Get The Next Page Button Work

### ISSUE THREAD

**Issue by joeyk16** [mbrn/material-table#840]
Hi guys. Firstly the table you created is awesome.

I'm having an issue with pagination that I can't find an answer for. I can't get the next page button to work, and can't see how.

When setting up pagination for an API I can see that there's an `onChangePage` and `onChangeRowsPerPage`. Which is great. 

I can hit the API and with page count and page number. So let's say return 5 apples for page 1. 

But what I can't seem to do is to see how may pages are remaining so I can press next. 

Let's say there are 20 apples in total, and I return the first 5 apples for page 1.  On the table, it shows the 5 apples, but I can't press next page. I can see it, but I can no press it. I can't see any totalPages param or something equivalent to let Material Table know there are more pages.

Do you know a way to show how many pages are remaining?

Thank you.

Image to help explain: https://monosnap.com/file/1NcjSo8mCJf6uzMAFH9J5v1thjyis6. 

```
#sudocode

const Table = props => {
  useEffect(() => {
    const params = {
      zone_id: currentZone,
      page: currentPage,
      page_count: pageCount
    };

    #Fetch request goes get the data and set the data.
  }

  const onChangePage = page => {
    setCurrentPage(page);
  };

  const onChangeRowsPerPage = count => {
    setPageCount(count);
  };

  return (
    <MaterialTable
      icons={tableIcons}
      columns={columns}
      onChangePage={onChangePage}
      onChangeRowsPerPage={onChangeRowsPerPage}
      data={data}
    />
  )
}
```

**Comment by kaienbcjdoapwkfldue** [comment]
Hi, it seems to me you are doing pagination the wrong way. Let material-table manage the the current page state. You don't need `onChangePage`. I do pagination as the docs suggest and provide a callback function returning a promise for the `data` property, say:

```js
const fetchData = async(query) => {
    const { filters, orderBy, orderDirection, page, pageSize } = query  // feed this to your api!
   /**
    * Check the docs for the structure of these properties/objects. Extract the information you need,
    * process it and then fetch a new batch of data from you api!
    * For instance, the page property or query hold the page that _should_ be retrieved now
    */
 
  // return this so material-table knows what to do
   return {
      data,   // the data that should be shown on the updated UI
      page,   // you basically do not need to mess with page yourself, just directly return it
      totalCount,   // the number of remaining items - beware: this is conditional on the current filters!
   }

}
```
This callback is called whenever the user changes something, i.e., on page navigation, adding/removing/change a filter, searching etc.

And then 

```jsx
<MaterialTable
   ...
   data={fetchData}
/>
```
This should be orthogonal to letting the user set the number of items to show (`pageSize`), which will simply trigger a refetching of fresh data via your privided callback.
Hope this helps, Cheers!

**Comment by joeyk16** [comment]
@kaienbcjdoapwkfldue Yep, I ended up doing exactly that. Here are the docs that will help someone with the same issue.

https://material-table.com/#/docs/features/remote-data
