### ISSUE TITLE
_this.props.editable.onRowUpdate(...) is undefined

### ISSUE THREAD

**Issue by Brehmly** [mbrn/material-table#841]
**Describe the bug**
When I try to update users in the table, it saws that onRowUpdate is undefined. It also says that another function in the code is undefined.

**Expected behavior**
To be able to edit without an error happening

**Additional context**
Here is my code for the table. The table is displaying user information from a server, and as such I cannot take a screenshot of the table. Trying to use either of the edit functions, whether from the actions or the onRowUpdate. Also, I have another table on another page that is a Material Table and uses the editable prop just fine
`<MaterialTable columns={[{title: 'ID', field: '_id', editable: 'never'},
                    {title:'Name', field: 'name', editable: 'onUpdate'},
                    {title:'Phone Number', field: 'phoneNumber', editable: 'onUpdate'},
                    {title: 'Email', field: 'email', editable: 'onUpdate'},
                    {title: 'Address', field: 'newAddress', editable: 'onUpdate'},
                    {title: 'Contacts', field: 'newContacts', editable: 'never'},
                    {title: 'Date Joined', field: 'dateJoined', editable: 'never'}]} data={this.props.users}
                    title = 'Users'
                    actions = {[
                            {
                                icon: 'create',
                                tooltip: 'Edit',
                                onClick: (event, rowData) => {this.props.users.grabUser(rowData._id)}

                            }
                        ]}
                               editable ={{
                                   onRowUpdate: (newData, oldData) => {
                                       nameArray = newData.name.split(' ');
                                       firstName = nameArray[0];
                                       lastName = nameArray[nameArray.length - 1];
                                       new Promise((resolve, reject) => {
                                               setTimeout(() => {
                                                   this.props.editUsers(oldData._id, firstName, lastName, newData.email, newData.phoneNumber, newData.address.zipCode, newData.address.state, newData.address.city, newData.address.street);
                                                   resolve()
                                               }, 1000);
                                               reject();
                                           })
                                   }
                               }}
                />`

**Comment by emrekara37** [comment]
Hi @Brehmly 
if the error persists can you tell me the version number
