### ISSUE TITLE
How do I reduce the size between the columns? Also is there a way to render the entire table at 50 percent its current size?

### ISSUE THREAD

**Issue by sayran123** [mbrn/material-table#845]
Hi,
I was wondering if it is possible to reduce the space in between columns? I've tried using the column.cellstyle but I can't figure out how to get it working. Also I was wondering if there was a way to render the entire table at a percentage of its current size? I am trying to render 18 columns and I hate that I need to scroll left and right to see the entire table. Thanks for any help!

**Comment by nikhilwbhatia** [comment]
+1
