### ISSUE TITLE
Suppose a user checks some rows in material table and then he checks the select all check box and then unchecks it again,all rows will get unchecked.I want a feature where a user gets to uncheck all checked rows by a button click.How can that be done

### ISSUE THREAD

**Issue by Surbhi-Kohli** [mbrn/material-table#846]
**Is your feature request related to a problem? Please describe.**
There seems to be no way to uncheck all rows at once other than going to each row and unchecking the box

**Describe the solution you'd like**
I want that on clicking of a button,all rows of the table get unchecked.

**Describe alternatives you've considered**

**Additional context**

**Comment by perfectstrong** [comment]
You can implement a free action then use the ref. Please look here https://github.com/mbrn/material-table/issues/515
