### ISSUE TITLE
Doesn't work with IE 11

### ISSUE THREAD

**Issue by oliviertassinari** [mbrn/material-table#847]
**Describe the bug**

The components use APIs that are not available in IE 11. For instance, Array.prototype.find().
https://github.com/mbrn/material-table/blob/695f95c3b3c8fa70cc3e2fe56e7d649b2eae0ca6/src/utils/data-manager.js#L271

**To Reproduce**
1. Go to 'https://material-table.com/
1. See error

**Expected behavior**

No errors.

**Desktop (please complete the following information):**
 - Browser: IE 11

**Additional context**

Related to https://github.com/mui-org/material-ui/issues/16209. I would encourage the usage of a utility function. I would avoid Lodash in the solution, at least, if you can save bundle size.

**Comment by AbelRodriguezGumiel** [comment]
When will this fix be included?
