### ISSUE TITLE
Remote data with selection

### ISSUE THREAD

**Issue by ismaildervisoglu** [mbrn/material-table#850]
**Describe the bug**
When we use the remote data and select feature together, the selected lines are reset when we change the page and return to the previous page.

**Expected behavior**
Keep selected rows.

**Comment by Absolutestunna** [comment]
Any update on this issue?

**Comment by ismaildervisoglu** [comment]
Any update on this issue? @emrekara37

**Comment by pixelass** [comment]
#1189 provides a sloution
