### ISSUE TITLE
The search feature should wait for user to stop typing

### ISSUE THREAD

**Issue by nvtin** [mbrn/material-table#860]
When I implement the search box with remote data. It is always jerky when I type the text. Because It always make the update the search text and do a query to get data when I type.

Solution to fix this issue is make the timeout to wait for user to stop typing at least 500 milliseconds. So the search will be called after user stop typing 500 ms.

Actually we will have options to user set the time if they want to custom:
```
options: {
  ..
  search: true,
  searchProps: {
    waitForTyping: 500
  },
 ..
}
```

**Comment by oze4** [comment]
Check out `debounceInterval` under `Options` [in the docs](https://material-table.com/#/docs/all-props) - the default is `200ms`.

Should be able to do something like:

```
<MaterialTable
    ...
    options={{
        ...
        debounceInterval: 500,
        ...
    }}
    ...
/>
```

**Comment by nvtin** [comment]
@oze4 Thanks so much. I read the docs but I missed it.
