### ISSUE TITLE
Nested data as field (nested list)

### ISSUE THREAD

**Issue by nikhilwbhatia** [mbrn/material-table#870]
Is there a way to specify a column field to take on "c"s value (nested within a list). I understand you can access nested dictionary values as outer.inner, but wasn't sure if this syntax extended to values nested within lists. (Also need this field to be sortable/filterable).

{"a": 1, "b": [{"c": 1}, {"d": 1}]

**Comment by hinsxd** [comment]
Same problem here. But your data structure seems to be a bit strange as your `b` is an array with two object with single property. 
One solution would be manually mapping the nested values to first level values.

```js
const data = [{ a: 1, b: { c: 1, d: 1 } }];
<MaterialTable
   ...
   data={data.map(({ a, b: { c, d } }) => ({ a, c, d }))}
/>
```

**Comment by eoghanmccarthy** [comment]
Is there a solution for when a nested key is the same as a first level key? Obviously the below doesn't work.

```javascript
const data = [{ id: '1234', project: { id: '5678' } }];

<MaterialTable
   ...
   data={data.map(({ id, project: {id} }) => ({ id, id }))}
/>
```

**Comment by eoghanmccarthy** [comment]
Or you can map the key to value manually.

```javascript
const data = [{ id: 1, project: { id: 1 } }];

<MaterialTable
   ...
   data={data.map(({ id, project }) => ({
      id: id,
      projectId: project.id
   }))}
/>
```
