### ISSUE TITLE
Sortcustom for each direction

### ISSUE THREAD

**Issue by FroggDev** [mbrn/material-table#876]
Hi,

I am trying to sort column based on selected column +date

If i add this :
`customSort: (a,b)=>(a+name+a.date.split('/').reverse().join('')).localeCompare(b.date.split('/').reverse().join('')+b.name`

In Asc order my result will be name **asc** and date **asc**
In Desc order my result will be name **desc** and date **desc**

I am trying to get :
 
In Asc order my result will be name **asc** and date **desc**
In Desc order my result will be name **desc** and date **desc**

I don't know if it is possible to achieve this actually.

Maybe a solution is to add the sort direction in the customSort method, like
`customSort: (a,b,direction)`

or have a possibility to set a sort by direction like :
`customSortAsc: (a,b)`
`customSortDesc: (a,b)`

**Comment by jayarjo** [comment]
@emrekara37 what kind of help? I require sorting based on multiple columns. If this issue is related I could PR perhaps.

**Comment by jayarjo** [comment]
@FroggDev ok from what I see sorting based on multiple columns is not supported at the moment: https://github.com/mbrn/material-table/issues/541

**Comment by omritelem** [comment]
Is there any update regards to getting the order type inside the customSort function?
Is there a possibility to get Inside the customSort function (we get the 2 current objects), but not the sort type itself - 'asc' or 'desc'.
