### ISSUE TITLE
Documentation error for Action icon section

### ISSUE THREAD

**Issue by FroggDev** [mbrn/material-table#877]
Hi,

In the documentation action field https://material-table.com/#/docs/features/actions :

> icon | string or ReactElement|   | Icon of button from material icons or custom component

When i try to put a react component i get the error

> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Error example :
```
              actions={[
                  rowData => ({
                  icon: <edit/>,
                  tooltip: 'Edit',
                  onClick: (event, rowData) => { console.log('CLICK') },
                }),
]} 
```
this works 
```
              actions={[
                  rowData => ({
                  icon: () => { return <Edit/> },
                  tooltip: 'Edit',
                  onClick: (event, rowData) => { console.log('CLICK') },
                }),
]} 
```

So maybe the documentation should be changed with :

> icon | string or **function**   | Icon of button from material icons or **custom rendering function**

Thanks

**Comment by Domino987** [comment]
The documentation has been updated.
