### ISSUE TITLE
Overriding toolbar (removing selection count)

### ISSUE THREAD

**Issue by nikhilwbhatia** [mbrn/material-table#879]
How would I go about overriding the toolbar to remove the selection count overlay (while still retaining search, etc)

Was referring to this: https://material-table.com/#/docs/features/component-overriding, but unsure how to selectively override the selection count functionality.

**Comment by nataliepatton13** [comment]
Within options in the table set the showTextRowsSelected attribute to false, like this...      `<MaterialTable options={{ toolbar: true, selection: true, showTextRowsSelected: false }}/>`

**Comment by nikhilwbhatia** [comment]
Thanks!
