### ISSUE TITLE
Material Table desktop view - overflow scroll

### ISSUE THREAD

**Issue by SilviaJoyceBalraj** [mbrn/material-table#88]
When the table has more number of columns, it is not adding a scrollbar in desktop view. Instead it just overflows outside the container. Could you please check on this.

Thanks,
Silvia

**Comment by mbrn** [comment]
Hi @SilviaJoyceBalraj,

Can you check it again. Because i added more than 40 columns and it works properly. 

![image](https://user-images.githubusercontent.com/7895451/49732438-c88ce580-fc8f-11e8-8920-b1979b62e28b.png)
