### ISSUE TITLE
Enable selection on row click

### ISSUE THREAD

**Issue by nikhilwbhatia** [mbrn/material-table#884]
How can I select a row on row click (rather than having to press the selection checkbox). I did something like this:

onRowClick={(event, rowData) => {
                        let versions = this.state.versions
                        const index = versions.indexOf(rowData)
                        versions[index].tableData.checked = true
                        this.setState({versions: versions})
}}

This checks the box but does not call any of the onSelectionChange logic that is important in my use case. Is there an easy way to enable this?

**Comment by oze4** [comment]
Why not just call it manually?

[![Edit react-material-table-onSelectionChange-via-onRowClick](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-material-table-start-on-page-6fr1q?fontsize=14&module=%2Fsrc%2FAppTable.js)

**Comment by nikhilwbhatia** [comment]
Aha, did not think of that. Thank you again for your help!

**Comment by oze4** [comment]
@nikhilwbhatia no problem! As far as the double click is concerned I believe we just added a prop for that (I would need to dig more to give you specifics though, so let me know if you need any help finding it).
