### ISSUE TITLE
Programmatically Change Page

### ISSUE THREAD

**Issue by oze4** [mbrn/material-table#885]
Is there any way to programmatically change the page, or set the current page asynchronously? When I programmatically set `initialPage`, MaterialTable does not react to these changes.

[![Edit react-material-table-start-on-page](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-material-table-start-on-page-vzmv8?fontsize=14&module=%2Fsrc%2FAppTable.js)

***EDIT:*** I have updated the Sandbox above to show how I was able to get around this.  Essentially, I load a 'placeholder' table until my API data arrives.. This is giving me what I need, albeit a bit hacky, but its working for now..

**Comment by oze4** [comment]
I am closing this out due to the 'hack' above. Although, this feature should most likely be implemented.

**Comment by fastaburuaga2** [comment]
> I am closing this out due to the 'hack' above. Although, this feature should most likely be implemented.

Any news on this implementation?

**Comment by oze4** [comment]
> Any news on this implementation?

@fastaburuaga2 unfortunately, no.  They are not very responsive in this repo (just look at how many open issues/pull requests there are).. I once opened a pull request to fix a minor bug, and it took them like nearly 2 months to merge it.  We're talking a minor bug.. very minor... like a handful of lines of code.

I would consider this repo dead - may want to fork it and just update your own version - I wouldn't look for anything more from this repo, sadly.

**Comment by joshuaheslin** [comment]
Managed to find a hack - hope it helps someone.

```
const MyComponent = () => {
  const tableRef = React.useRef();

  const handlePageChange = () => {
    // here is where we invoke the onChangePage function
    // note: we are setting page = 0
    tableRef.current.onChangePage({}, 0);
  }

  return (
    <>
    <button onClick={handlePageChange}>Click</button>
      <MaterialTable
        tableRef={tableRef}
        columns={columns}
        data={dataSource}
        components={{
          Pagination: PatchedPagination
        }}
        options={{
          ...materialTableOptions,
          sorting: true,
          pageSizeOptions: [10, 20, 50],
          pageSize: 10,
          paging: true,
        }}
      />
    </>
  )
}

```

Should also note I'm using another patch at the same time PatchedPagination. It might be required or maybe not.
https://github.com/mbrn/material-table/pull/2937
