### ISSUE TITLE
Centering action button

### ISSUE THREAD

**Issue by FroggDev** [mbrn/material-table#888]
Hi,

The property **actionsCellStyle** apply to the **action <td>**
If i want to center the custom action button in the TD, I  need to access to the properties of the extra **<div style="display: flex;">** container added from the code.

BTW, i don't know what is the utility of this div.

When the div **<div style="display: flex;">** is removed ( using the browser console for example) I can correctly align action button using 
`actionsCellStyle:{justifyContent:'center'}`

Thanks.

**Comment by pak11273** [comment]
It's hard to read what you wrote.  You can center an action button like this:

````javascript
options={{actionsCellStyle: {display:"flex", justifyContent: "center"}}}
````

**Comment by FroggDev** [comment]
![2019-08-06 11_23_02-Window](https://user-images.githubusercontent.com/3765812/62528117-9e9abb80-b83c-11e9-8b79-375cfcd6b27a.png)

Thanks, but as you can see the bottom line isn't aligned with your code

**Comment by FroggDev** [comment]
finally i got it:

`actionsCellStyle:{justifyContent: "center"},`

**Comment by chitgoks** [comment]
that is actually what i did. but no, it does not work

```
actionsCellStyle: {
            justifyContent: 'center'
          },
```
Even adding display: 'flex' or textAlign: 'center'

Please see image. the css instead gets applied to the cell but it does not center it because the buttons have a <div style="display: flex"> container.
![cellstyle](https://user-images.githubusercontent.com/3955470/74503084-c45ef680-4f2a-11ea-89b4-57fdff33ff77.png)

**Comment by trianta2** [comment]
The solutions above don't work, this issue should be reopened

**Comment by FroggDev** [comment]
You can try something tricky like

> actionsCellStyle:{justifyContent: "center",maxWidth: 90,width: 90}

**Comment by lucacattide** [comment]
In waiting for the official fix, set it like this:
```
actionsCellStyle: {
  display: 'flex',
  justifyContent: 'center',
  padding: 16,
  width: '100%'
}
```

**Comment by arbaz1006** [comment]
Thanks @lucacattide, works fine for me.

**Comment by JeffEmery** [comment]
I had to add a bit more padding and push the bottom margin...

    actionsCellStyle: {
        display: 'flex',
        justifyContent: 'center',
        padding: '24px',
        width: '100%',
        marginBottom: '-1px',
    },

**Comment by chitgoks** [comment]
in my case, i actually have 1 custom action button (search) while the other 2 are edit and delete. tried to place that in the search action button, didnt work.[
![action](https://user-images.githubusercontent.com/3955470/78954720-8ee01f00-7b0f-11ea-974a-f3886568a9b5.png)
](url)

**Comment by chitgoks** [comment]
seems we all have to wait for this fix.

**Comment by FroggDev** [comment]
As i said in the first post, the problem come from the **DIV which contains the buttons**.
When **actionsCellStyle is set, it is applied to the TD**, so it does not change the DIV behavior.

If you want to CENTER the BUTTONS you have to apply a style to the DIV which contains the BUTTONS instead of the TD

You can do it in multiple ways.

Here an exemple using external style

for exemple:
```
.MuiTable-root tr td:last-child div {
  justify-content: center;
}
```
 
Result:

![centered](https://user-images.githubusercontent.com/3765812/78993221-830b5180-7b3d-11ea-9309-14899bc7a6e9.png)

You can see a working demo at:
https://codesandbox.io/s/pedantic-villani-xl7nf?file=/src/styles.css:59-126


Anyway, there should be an option for that in material-table, and for now it is missing.

But if you want to contribute you can try to do a PR with an option that apply "justify-content: center;" to the action DIV container.

**Comment by FroggDev** [comment]
@JeffEmery Thanks.

**Comment by royliu007** [comment]
> finally i got it:
> 
> `actionsCellStyle:{justifyContent: "center"},`

I tried the justifyContent prop. but it is not working, I don't know why, 
I used paddingLeft instead to move the icon to the center of the cell.
```
actionsCellStyle: {
    paddingLeft: '2rem',
}
```

**Comment by FroggDev** [comment]
> > finally i got it:
> > `actionsCellStyle:{justifyContent: "center"},`
> 
> I tried the justifyContent prop. but it is not working, I don't know why,
> I used paddingLeft instead to move the icon to the center of the cell.
> 
> ```
> actionsCellStyle: {
>     paddingLeft: '2rem',
> }
> ```

Read the post of the 10 Apr then check JeffEmery commit

**Comment by zhushenhang** [comment]
@FroggDev .MuiTable-root tr td:last-child div {
  justify-content: center;
}
thanks,it works for me 
but at present, the acticon title is centered by default, how to change it to left, I tried the headerStyle, but it does not work.

**Comment by sebaranowski** [comment]
> [...] but at present, the acticon title is centered by default, how to change it to left, I tried the headerStyle, but it does not work.

Try:
```
const useStyles = makeStyles((theme: Theme) =>
  createStyles({
    root: {
      '& .MuiTable-root tr th:last-child': {
        textAlign: 'right !important',
        paddingRight: theme.spacing(3),
      }
    },
  }),
);
```

**Comment by abhi-dasgupta** [comment]
`actionsCellStyle: {
                margin: "0 auto",
                display: "flex",
                flexGrow: "1",
                justifyContent: "center",
                // border: "3px solid black",
              },`
in options worked for me

**Comment by chitgoks** [comment]
wow ... 2 years and still hasnt been fixed? pretty hard bug. hope this can be given more attention. none of the ones mentioned above worked for me.

**Comment by FroggDev** [comment]
> `actionsCellStyle: { margin: "0 auto", display: "flex", flexGrow: "1", justifyContent: "center", // border: "3px solid black", },`
> in options worked for me

It has been fixed there:
https://github.com/ChrisHampu/material-table/commit/0177d77a7bd2cd9902760a0c8760500f620edb3a
