### ISSUE TITLE
Extremly slow perfomance while expanding grouped field with many results.

### ISSUE THREAD

**Issue by NicoEspositoARG** [mbrn/material-table#889]
First of all... Thank you for this excellent component! i found it very useful!

Bug report:
When expanding a grouped field, that contains many results, total rows count of the table only considers the first level of agrupation. So when you try to expand this first level, the totaly of the results are rendered at once. In my case I have "categories" containing over 5k rows each, so when i try to expand it, it takes more than 30 seconds to render the data.

I tried with 7000 rows of data, 4 columns, zero actions on each row, and defining grouping: true as the only Option for the MaterialTable Component.  Im using built-in data handling, not the remote data functionality.

**To Reproduce**
1. Set: data={this.props.dataArray},  options={{ grouping:true }}
2. Drag and drop column header in order to group by.
3. Expand one of the grouped values.
4. When there is a significant amount of results it takes to long to render the rows, doesn't responds normally (the cursor gets buggy and no response browser warning is showned).

**Expected behavior**
It would be great to have the pagination on the amount of expanded rows, and not only on the first level of aggrupation.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.4
 - Browser [Chrome]
 - Version [75.0.3770 64bits]

Thx!

**Comment by oliviertassinari** [comment]
@NicoEspositoARG I think that the root of the issues comes from our API. We are paying the cost of React abstraction. Basically, having an intermediary component for each table elements has a cost. Compare with 100 rows:
- https://material-ui.com/performance/table-raw/
![Capture d’écran 2019-08-13 à 10 58 21](https://user-images.githubusercontent.com/3165635/62928707-58ec6e80-bdb9-11e9-9c2a-3ddeec1600f3.png)
- https://material-ui.com/performance/table-component/
![Capture d’écran 2019-08-13 à 10 58 27](https://user-images.githubusercontent.com/3165635/62928708-58ec6e80-bdb9-11e9-91b2-600186bc8839.png)
- https://material-ui.com/performance/table-mui/
![Capture d’écran 2019-08-13 à 11 01 38](https://user-images.githubusercontent.com/3165635/62928937-bf718c80-bdb9-11e9-8478-c8f2e0cc3f04.png)

An alternative would be:
```jsx
import React from 'react';
import { Table } from '@material-ui/core';

// ...

      <Table>
        <thead>
          <tr>
            <th>#</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Username</th>
          </tr>
        </thead>
        <tbody>
```

but we would lose style capabilities at the cell level. Can React handle 28k cells in the first place? If not, then virtualization is our best option.

**Comment by NicoEspositoARG** [comment]
Hi @oliviertassinari maybe I wasn't  clear in my original post, but i think the issue here is that the pagination doesn't work over the amount of expanded rows, it only takes to account the first level of aggrupation.

For example in the screenshot below, notice that the pagination is based in 2 items (rows) corresponding to the results of the first level of grouping ("state"). The results shown when expanding one of this levels are not been counted to the pagination logic.

![image](https://user-images.githubusercontent.com/46970426/63040543-0afc6700-be9c-11e9-81b1-d56df87ab185.png)

Withouth grouping the pagination works as expected:

![image](https://user-images.githubusercontent.com/46970426/63040648-41d27d00-be9c-11e9-98c4-00d544226a4c.png)

**Comment by gabrieldaghetti** [comment]
HI, I have the same problem!

**Comment by sanders-vag** [comment]
This is happening to me too, any workaround?

**Comment by NicoEspositoARG** [comment]
Any chance we can get an alternative to this issue? Thx

**Comment by avizaviz** [comment]
+1

**Comment by mackankowski** [comment]
Let's my previous post about virtualization (as a way of performance improvement) where I share some sample code: https://github.com/mbrn/material-table/issues/891#issuecomment-681986647

**Comment by androidemil** [comment]
+1

**Comment by germiy** [comment]
the issue is still there...
