### ISSUE TITLE
Apollo Graphql and Material Table

### ISSUE THREAD

**Issue by cardimajs** [mbrn/material-table#890]
Nice project, tks.

Is possible to use this project as remote data with Apollo Grapql?

any example?

Tank you.

**Comment by natac13** [comment]
I am attempting this right now. Not going so well when trying to implement pagination with Apollo's `fetchMore` function. When it gets called in the function passed to `data` ( like the remote data example ) it fetches and updated the data as expected. However it causes a  re-render of the whole page which sets `query.page` back to 0. Therefore when the refresh is done it is still on page 1. 

If I get it working :crossed_fingers: Ill post it here...

**Comment by cardimajs** [comment]
i'm trying using apollo client :

import { useApolloClient } from '@apollo/react-hooks';


let result = await client.query(
              {query: GET_ACCOUNTS, 
                variables: {
                  pagination: {
                    page: query.page, 
                    rowsPerPage: query.pageSize,
                    sortField: orderBy,
                    sortDirection: query.orderDirection,
                    searchText: query.search
                  }
                }
              }
            );

**Comment by kaienbcjdoapwkfldue** [comment]
I'm also using apllo client instance as @cardimajs suggested. However, `client.query` apparently only lets you fire one-shot queries and you don't reap the benefits of automatic table updates when the cache changes (as it is the case with the `useQuery` hook or the `Query` HOC). I tried to play around with `client.watchQuery` with little success. The best way would be to have `MaterialTable` to be fully controlled and use a parent component to manage data fetching with filtering, pagination, sorting, searching etc. However, the current API does not seems to allow for `MaterialTable` to be fully controlled.

**Comment by lookfirst** [comment]
Yep, the interaction is a train wreck. Trying to figure this out myself. Tried lazy queries as well, but everything I do sends things into a render loop. I'm sure there is some convoluted magic that makes all this work right, but have yet to discover it. =(

**Comment by lookfirst** [comment]
Here is a relatively simple (ahahahah) example that I just figured out. It uses typescript, graphql and latest react methodology (hooks).

`usePaginatedLazyQuery` is an auto generated method using [graphql-code-generator](https://graphql-code-generator.com/). It is basically a wrapper around `useLazyQuery` from Apollo.

I use lazy because I want the rendering to happen in a controlled way. The controlled way is by using `setPaginated` and `useEffect`.

The idea is that when this component first loads, nothing really happens. An 'empty' table is rendered with `isLoading: true`. This gives the user the nice effect that something is happening.

`useEffect()` is then fired automatically, which first calls `getData()` which makes the query and returns an updated data object. Then because `data` is watched in the `useEffect` dependency array, `useEffect` is called again, which calls `setPaginated()`.

This forces another render loop, which then returns a table with `loading` being false. Now the issue I noticed was that the newly updated `data` object wasn't firing its function. There is probably some smart way to do this, but I punted and added a line below `setPaginated()` which calls `tableRef.current.onQueryChange();` and forces the `data` function to get called. I had to add some magic to the `useRef()` initial default value to make typescript happy.

For refreshing the table, the 'trick' here is to pass my made up variable `{refetch: true}` into `onQueryChange`. This becomes available above in the the MT `data` function, which I then use to call the `refetch` function from the lazy query.

Feedback welcome.

```
function Rigs() {
	const [getData, {loading, data, refetch}] = usePaginatedLazyQuery({
		variables: {
			edge: 'Rig',
			after: '',
			first: 10,
		}
	} as QueryHookOptions<any, PaginatedQueryVariables>);

	const [paginated, setPaginated] = useState<ResultCursor | undefined>(undefined);
	const tableRef = useRef({
		onQueryChange: () => {
		}
	});

	useEffect(() => {
		if (!loading) {
			if (data && data.Paginated) {
				setPaginated(data.Paginated as any);
				tableRef.current.onQueryChange();
			} else {
				getData();
			}
		}
	}, [data, loading, getData]);

	const dataProp = async (query: any) => {
		if (query.refetch) {
			await refetch();
		}

		if (paginated) {
			const formattedData = formatData(paginated);
			return {
				data: formattedData,
				page: 0,
				totalCount: paginated.totalCount,
			}
		} else {
			return {
				data: [{}],
				page: 0,
				totalCount: 0,
			}
		}
	};

	const props = {
		title: 'Rigs',
		tableRef: tableRef,
		isLoading: true,
		columns: [
			{title: 'Rig Id', field: 'rigId'},
		],
		actions: [
			makeRefreshAction(tableRef),
		],
	} as MaterialTableProps<any>;

	if (loading) {
		return makeTable({
			...props,
			data: [{}],
		});
	} else {
		return makeTable({
			...props,
			isLoading: false,
			data: dataProp,
		});
	}
}
```

```
export function makeTable(props: MaterialTableProps<any>) {
	return (
		<div style={{maxWidth: "100%"}}>
			<MaterialTable {...props} icons={tableIcons}/>
		</div>
	);
}

export function makeRefreshAction(ref: RefObject<any>) {
	return {
		icon: () => <Refresh/>,
		tooltip: 'Refresh Data',
		isFreeAction: true,
		onClick: () => {
			ref.current && ref.current.onQueryChange({refetch: true});
		},
	} as Action<any>;
}
```

**Comment by lookfirst** [comment]
I have a feeling that this fix would fix the workaround for updating the data. https://github.com/mbrn/material-table/pull/974/files

**Comment by lookfirst** [comment]
```
	useEffect(() => {
		tableRef.current.onQueryChange();
	}, [data]);
```

**Comment by pttse** [comment]
Thanks @lookfirst and your code is better as it is using fewer Http requests. 

In addition, as to fulfill the sorting, searching, and filtering functions, I have updated the dataFunc function based on your code. 

Given that the database is large and dynamic, the data is instantly retrieved from the server. 

```javascript
let currentQuery = null;
  const dataFunc = async (query) => {

    //Check conditions before refetch 
    const isRequiredRefresh = await requireRefresh(query);
    if (isRequiredRefresh) {
      //Patch the query page with the existing graphQL
      const currentPage = query.page >= 0 ? query.page + 1 : 1;
      let variables = await {
        name: query.search, size: query.pageSize, page: currentPage,
        orderByField: _.get(query, "orderBy.field", DEFAULT_ORDER_FIELD), 
        order: query.orderDirection !== "" ? query.orderDirection : `asc`
      };

      //Refetch with the latest variables
      refetch(variables).finally(() => {
        delete query.refetch;
        setReload(true);
      });
    }

    return await getTableData();
  };

  //Determine whether to refetch 
  const requireRefresh = async (query) => {

    //Condition 1: Force refresh
    if (query.refetch) {
      return true;
    }

    //Condition 2: no previous query, check if there is any existing cache/ data
    if (!currentQuery) {
      currentQuery = query;
      return data? false : true;

    //Condition 3: compare with current and new queries. Only update if the new query is different 
    } else {
      const isSame = await _.isEqual(currentQuery, query);
      if (isSame && data) {
        return false;
      }
    }

    return true;
  }

  const getTableData = async () => {
    const resultPage = await _.get(data, "users.query_metadata.total_page", 0);
    const resultPageCount = await _.get(data, "users.query_metadata.total", 0)

    return await {
      data: _.get(data, "users.result", []),
      page: resultPage - 1, //the material-table page is starting from zero
      totalCount: resultPageCount
    }
  }
`

**Comment by pttse** [comment]
Thanks @lookfirst and your code is better as it is using fewer Http requests. 

In addition, as to fulfill the sorting, searching, and filtering functions, I have updated the dataFunc function based on your code. 

Given that the database is large and dynamic, the data is instantly retrieved from the server. 

```javascript
let currentQuery = null;
  const dataFunc = async (query) => {

    //Check conditions before refetch 
    const isRequiredRefresh = await requireRefresh(query);
    if (isRequiredRefresh) {
      //Patch the query page with the existing graphQL
      const currentPage = query.page >= 0 ? query.page + 1 : 1;
      let variables = await {
        name: query.search, size: query.pageSize, page: currentPage,
        orderByField: _.get(query, "orderBy.field", DEFAULT_ORDER_FIELD), 
        order: query.orderDirection !== "" ? query.orderDirection : `asc`
      };

      //Refetch with the latest variables
      refetch(variables).finally(() => {
        delete query.refetch;
        setReload(true);
      });
    }

    return await getTableData();
  };

  //Determine whether to refetch 
  const requireRefresh = async (query) => {

    //Condition 1: Force refresh
    if (query.refetch) {
      return true;
    }

    //Condition 2: no previous query, check if there is any existing cache/ data
    if (!currentQuery) {
      currentQuery = query;
      return data? false : true;

    //Condition 3: compare with current and new queries. Only update if the new query is different 
    } else {
      const isSame = await _.isEqual(currentQuery, query);
      if (isSame && data) {
        return false;
      }
    }

    return true;
  }

  const getTableData = async () => {
    const resultPage = await _.get(data, "users.query_metadata.total_page", 0);
    const resultPageCount = await _.get(data, "users.query_metadata.total", 0)

    return await {
      data: _.get(data, "users.result", []),
      page: resultPage - 1, //the material-table page is starting from zero
      totalCount: resultPageCount
    }
  }
```

Please feel free to comment the code, thanks!

**Comment by lookfirst** [comment]
Not sure why you'd add the query caching (condition 3). Just let apollo cache for you.

**Comment by lookfirst** [comment]
I will add, after my last code bit, I've quit material-table. I got to the point where it felt like I was adding too many workarounds for the weird logic with loading remote data. This library just wasn't designed to deal with remote data properly.

I picked up what I should have done from the start, the first suggested library from the material-ui suggestions for datagrids. It isn't 'free', but it is open source. It is also excellent. I'm actually a little surprised at how good it is. Totally worth the price if you're doing a commercial app, as these developers have really put the effort into it. I am not naming names to respect the author here, who has done a lot of great work as well... I appreciate the effort... this stuff isn't easy.

**Comment by natac13** [comment]
And here I though it was just me having an issue with this library and fetching data from Apollo.

For me I abandoned using the remote data version of Material Tabla and changed the source code to be able to set a [`totalCount`](https://github.com/mbrn/material-table/compare/master...natac13:feature/props-totalCount-n-pageSize-onChangePage). What this allows me to do is have a `onPageChange` function that uses Apollo's `refetchQuery` to update the data, and give that updated data to Material Table. I am paginating via `skip` & `limit` instead of `cursors`.  
For the most part it works. **However** there still are glitches, like when I delete an entry the page refreshes and I lose all data but the first time fetch. 
I will look into this [React Grid](https://devexpress.github.io/devextreme-reactive/react/grid/) thing however I was wondering if anyone has looked into or has use [React-Virtualized](https://github.com/bvaughn/react-virtualized) with Apollo. I think I will give it a try.

**Comment by lookfirst** [comment]
That might be a caching issue with apollo or your component isn't getting re-rendered. I had similar glitches, which is why I gave up on it. I'm also now paginating with skip/limit after switching to postgres.

**Comment by dragonfriend0013** [comment]
For apollo client, useQuery is desiner to only be called once.  There is another export called useLazyQuery that can be called any time you want.  You must explicitly call it.

**Comment by pixelass** [comment]
We are using material-table with Apollo (v3 BETA) without any issues. It was a really straight forward implementation. It's also SSR ready (which we do not need ATM so it wasn't added)

We use sorting and paging (both via graphql) and we refetch data when items are added to the list or removed (this is a builtin mechanism `client.reFetchObservableQueries()`). It also uses i18next for localization. The project is currently in a private repository but I might be able to provide the code in a public repo somewhen next week. 

The project/repo also has a fully mocked graphql service, so it's a pretty complete implementation that could be adjusted to your needs. I might have to use different data and queries/mutations.
I'll have to ask if I can just fork it to my private github and open-source it.

**Comment by pixelass** [comment]
I went ahead and added an example to a library I'm currently working on. "Phony" helps mock the graphql service. 

The example uses:

* ssr over next.js
* graphql over apollo
* paging over graphql/phony
* i18next for translations (german/english enabled)
* material-table to display entries

I added a button to create new rows. The paging logic provided by "Phony" is integrated with material-table. I hope this helps understands how to implement something similar.

https://github.com/pixelass/phony/tree/master/examples/apollo

While the example is a rather complete setup including ssr and translation the main logic can be found here: https://github.com/pixelass/phony/blob/master/examples/apollo/pages/index.tsx
It should be fairly easy to understand since it only relies on a few local `react.useHooks`

**Comment by eminioloro** [comment]
@pixelass Hello. In your example, how do you get the currentPage. Line 63.

**Comment by pixelass** [comment]
@eminioloro see here: 

https://github.com/pixelass/phony/blob/master/examples/apollo/pages/index.tsx#L43

It defaults to `0` and is then set via the pageHandlers: 

https://github.com/pixelass/phony/blob/master/examples/apollo/pages/index.tsx#L159-L165

**Comment by eminioloro** [comment]
Thank you for your quick reply.

**Comment by hatchli** [comment]
@pixelass Thank you so much for sharing! Can I ask why you don't make use of useLazyQuery?

**Comment by pixelass** [comment]
> @pixelass Thank you so much for sharing!
> 
> Since implementing succesfully in my own project thanks to you, I have one question! I need to manipulate the data coming in before it is rendered. I'm not sure how to to handle that, given the function you wrote for grabbing it:
> 
> `return data.getItems.map(({ __typename, ...item}) => item);`
> 
> For example, a simple thing is that I need to change my created_at column values from ISO to normal readable dates. But I'm not sure how to "intercept" it based on the code you used above to get the data in to the table! Any direction would be appreciated!

I am just removing the property `__typename` from the object. It would cause an error in material-table.

I'm not sure if this is what you were asking but it's just simple javascript.

```js
const mycopy = data.getItems.map(
    ({ __typename, created_at, ...item}) => 
        ({
            ...item, 
            created_at: someDateFormatter(created_at)
        }
    )
);
```

You can also use the `render` method of the columns though https://material-table.com/#/docs/features/custom-column-rendering

```jsx
<MaterialTable
    // other props
    columns={[
      {
        field: 'created_at',
        title: 'Created At',
        render: ({created_at}) => someDateFormatter(created_at)
      }
    ]}
/>
```

**Comment by bryancolin** [comment]
Does anyone knows how to work on useQuery graphql?
`
interface Row {
  id: string;
  username: string;
  email: string;
  password: string;
}

interface StaffData {
  allStaff: Row[];
}

interface TableState {
  columns: Array<Column<Row>>;
  datas: Row[];
}

const GET_STAFF = gql`
query getStaff{
  allStaff{
    id
    username
    email
    password
  }
}`;


export default function Customer() {

  const [state, setState] = React.useState<TableState>({
    columns:
      [
        { title: 'Id', field: 'id', type: 'numeric' },
        { title: 'Name', field: 'name' },
        { title: 'Email', field: 'email' },
        { title: 'Password', field: 'password' }
      ],
    datas:
      [
        { id: "1", username: 'Bryan', email: "bryan@yahoo.com", password: "123" },
        { id: "2", username: 'Colin', email: "colin@yahoo.com", password: "123" }
      ]
  });

  const { /* loading, error, */ data } = useQuery<StaffData>(GET_STAFF);

  useEffect(() => {
    console.log("useEffect hook is called");
    setState((prevState) => {
      const current = [...prevState.datas];
      current.push();
      return { ...prevState, current };
    });
  }, [data]);

  return (
    <div>
      <MaterialTable
        title="Customer List"
        columns={state.columns}
        data={state.datas}

        editable={{

          onRowAdd: (newData) =>
            new Promise((resolve) => {
              setTimeout(() => {
                resolve();
                setState((prevState) => {
                  const data = [...prevState.datas];
                  data.push(newData);
                  return { ...prevState, data };
                });
              }, 600);
            }),

          onRowUpdate: (newData, oldData) =>
            new Promise((resolve) => {
              setTimeout(() => {
                resolve();
                if (oldData) {
                  setState((prevState) => {
                    const data = [...prevState.datas];
                    data[data.indexOf(oldData)] = newData;
                    return { ...prevState, data };
                  });
                }
              }, 600);
            }),

          onRowDelete: (oldData) =>
            new Promise((resolve) => {
              setTimeout(() => {
                resolve();
                setState((prevState) => {
                  const data = [...prevState.datas];
                  data.splice(data.indexOf(oldData), 1);
                  return { ...prevState, data };
                });
              }, 600);
            }),
        }}
      />
    </div>
  );
}
`

**Comment by pixelass** [comment]
@bryancolin your code-formatting is messed up so it's really hard to analyze the code. Also try to include a codesandbox example. One thing I can tell you for sure is that the following part makes no sense:

```js
useEffect(() => {
    console.log("useEffect hook is called");
    setState((prevState) => {
        const current = [...prevState.datas];
        current.push();
        return { ...prevState, current };
    });
}, [data]);
```

You might want to look into how react hooks work especially setState and useEffect. The snippet above does nothing except for setting an absolutely invalid model. 

As mentioned, without a codesandbox or reproduction example nobody will be able to help you. 
You might want to look into the example app I mentioned above. It uses `useQuery`.

**Comment by bryancolin** [comment]
Here is my code
```
interface Row {
id: string;
username: string;
email: string;
password: string;
}

interface StaffData {
allStaff: Row[];
}

interface TableState {
columns: Array<Column>;
datas: Row[];
}

const GET_STAFF = gql query getStaff{ allStaff{ id username email password } };

export default function Customer() {

const [state, setState] = React.useState({
columns:
[
{ title: 'Id', field: 'id', type: 'numeric' },
{ title: 'Name', field: 'name' },
{ title: 'Email', field: 'email' },
{ title: 'Password', field: 'password' }
],
datas:
[
{ id: "1", username: 'Bryan', email: "bryan@yahoo.com", password: "123" },
{ id: "2", username: 'Colin', email: "colin@yahoo.com", password: "123" }
]
});

const { /* loading, error, */ data } = useQuery(GET_STAFF);

useEffect(() => {
console.log("useEffect hook is called");
setState((prevState) => {
const current = [...prevState.datas];
current.push();
return { ...prevState, current };
});
}, [data]);

return (


<MaterialTable
title="Customer List"
columns={state.columns}
data={state.datas}
    editable={{

      onRowAdd: (newData) =>
        new Promise((resolve) => {
          setTimeout(() => {
            resolve();
            setState((prevState) => {
              const data = [...prevState.datas];
              data.push(newData);
              return { ...prevState, data };
            });
          }, 600);
        }),

      onRowUpdate: (newData, oldData) =>
        new Promise((resolve) => {
          setTimeout(() => {
            resolve();
            if (oldData) {
              setState((prevState) => {
                const data = [...prevState.datas];
                data[data.indexOf(oldData)] = newData;
                return { ...prevState, data };
              });
            }
          }, 600);
        }),

      onRowDelete: (oldData) =>
        new Promise((resolve) => {
          setTimeout(() => {
            resolve();
            setState((prevState) => {
              const data = [...prevState.datas];
              data.splice(data.indexOf(oldData), 1);
              return { ...prevState, data };
            });
          }, 600);
        }),
    }}
  />
</div>
);
}
`````

**Comment by bryancolin** [comment]
I'm trying to display the data from the backend using graphql useQuery but i'm not sure how to set the State on the useEffect
`import React, { useState, useEffect } from 'react';
import MaterialTable, { Column } from 'material-table';
import gql from 'graphql-tag';
import { useQuery, useLazyQuery } from '@apollo/react-hooks';
import { MyTable } from './Table'
// import { Query } from 'react-apollo';
// import { Card, CardBody, CardHeader, CardSubtitle, Spinner } from 'reactstrap';
// import ReactTable from 'react-table'

interface Row {
  id: string;
  username: string;
  email: string;
  password: string;
}

interface Staff {
  id: string;
  username: string;
  email: string;
  password: string;
}

interface StaffData {
  allStaff: Row[];
}

interface TableState {
  columns: Array<Column<Row>>;
  datas: Row[];
}

const GET_STAFF = gql`
query getStaff{
  allStaff{
    id
    username
    email
    password
  }
}`;

export default function Customer() {

  const [state, setState] = React.useState<TableState>({
    columns:
      [
        { title: 'Id', field: 'id', type: 'numeric' },
        { title: 'Name', field: 'name' },
        { title: 'Email', field: 'email' },
        { title: 'Password', field: 'password' }
      ],
    datas:
      [

      ]
  });

  //const { error, data } = useQuery<StaffData>(GET_STAFF);
  const { error, data } = useQuery<Row>(GET_STAFF);

  useEffect(() => {
    console.log("useEffect hook is called");


      setState((prevState) => {
        const current = [...prevState.datas];
        current.push(data);
        return { ...prevState, current };
      });

  }, [data]);


  return (
    <div>
      <MaterialTable
        title="Customer List"
        columns={state.columns}
        data={state.datas}

        editable={{

          onRowAdd: (newData) =>
            new Promise((resolve) => {
              setTimeout(() => {
                resolve();
                setState((prevState) => {
                  const data = [...prevState.datas];
                  data.push(newData);
                  return { ...prevState, data };
                });
              }, 600);
            }),

          onRowUpdate: (newData, oldData) =>
            new Promise((resolve) => {
              setTimeout(() => {
                resolve();
                if (oldData) {
                  setState((prevState) => {
                    const data = [...prevState.datas];
                    data[data.indexOf(oldData)] = newData;
                    return { ...prevState, data };
                  });
                }
              }, 600);
            }),

          onRowDelete: (oldData) =>
            new Promise((resolve) => {
              setTimeout(() => {
                resolve();
                setState((prevState) => {
                  const data = [...prevState.datas];
                  data.splice(data.indexOf(oldData), 1);
                  return { ...prevState, data };
                });
              }, 600);
            }),
        }}
      />
    </div>
  );
}`

**Comment by pixelass** [comment]
As mentioned please look into your `setState` usage.  
_Sidenote: Why are you using a `setTimeout`?_

**I think the main problem is that your code does not make sense.**

```js
const current = [...prevState.datas];
current.push(data); // ? why
// use this instead
const current = [...prevState.datas, data];
```

the result of your logic would be something like:

```js
{
    columns: [/*...*/],
    datas: [],
    current: [/*...*/]
}
// or the below (depending on where/when it is updated)
{
    columns: [/*...*/],
    datas: [],
    data: [/*...*/]
}
```

I have the feeling that your question is not related to the original topic of this question. Maybe you're better off on Stackoverflow or another community that offers help. You are really just asking how to use React hooks.

**Comment by ambuznego** [comment]
Thanks for sharing @pixelass - I was able to easily make this work by following your example. Here's what worked for me:

```
const [currentPage, setCurrentPage] = React.useState(0);
const [currentPageSize, setCurrentPageSize] = React.useState(100);

const variables = { page: currentPage, pageLength: currentPageSize };
const { loading, error, data, refetch } = useQuery(SOME_GQL_DEFINED_QUERY, { variables });

React.useEffect(() => {
        refetch();
    }, [currentPage, currentPageSize]);

<MaterialTable
        // all other props
        onChangePage={nextPage => {
                setCurrentPage(nextPage);
        }
        onChangeRowsPerPage={nextPerPage => {
                setCurrentPageSize(nextPerPage);
                setCurrentPage(0);
        }}
        options={{
		pageSize: currentPageSize
	}}
/>
```

**Comment by ifndefdeadmau5** [comment]
@pixelass you saved my ass
