### ISSUE TITLE
Center align in column

### ISSUE THREAD

**Issue by nikhilwbhatia** [mbrn/material-table#896]
How would I center align a button/custom rendered object in a column. Opting to custom render the column value forces left alignment, but is there an easy way to center the contents of the column?

**Comment by pak11273** [comment]
@nikhilwbhatia can you provide some minimal code to reproduce your issue?

**Comment by pak11273** [comment]
You can inline style any component like this:

````
columns={[
  {
    title: "Avatar",
    field: "avatar",
    render: rowData => (
      <button
        style={{ height: 36, borderRadius: "50%", margin: "0 auto" }}
        src={rowData.avatar}
      >test</button>
    )
  }
]}
````

**Comment by emrekara37** [comment]
i close this issue. reopen if you needed please

**Comment by nikhilwbhatia** [comment]
Worked for me, thank you
