### ISSUE TITLE
Add print feature

### ISSUE THREAD

**Issue by mbrn** [mbrn/material-table#9]
Users can print table data

**Comment by mbrn** [comment]
no need for now.

**Comment by Bulletninja** [comment]
Are there any plans to add this feature?

**Comment by mbrn** [comment]
@Bulletninja i may add this feature. But currently i need to work on more important issues.

**Comment by aramkoukia** [comment]
why do you close the issue? shouldn't it be open to be addressed?

**Comment by mbrn** [comment]
Hi @aramkoukia ,

Because it has a export feature. Users could use export feature for printing.

**Comment by Flash619** [comment]
I would also be interested in this functionality for a few apps I'm working on. Users don't always like an extra step. 😊

**Comment by dmetzler2012** [comment]
I would also like this feature.

**Comment by NickAlvesX** [comment]
+1

**Comment by therohitjha** [comment]
its very easy to add print option just install below package.
https://www.npmjs.com/package/react-to-print

then follow below image
<img width="323" alt="Capture1" src="https://user-images.githubusercontent.com/45750703/73139149-082fb000-4091-11ea-8a1c-24af953a6b61.PNG">
<img width="397" alt="Capture2" src="https://user-images.githubusercontent.com/45750703/73139151-09f97380-4091-11ea-9eed-a474a044722e.PNG">

**Comment by xStorm111** [comment]
@therohitjha it's not that simple, the way you're showing only prints the data that's your screen is showing, imagine that you have more than 100 rows and you need to print the all the data, do you have a solution for that?
i left a issue with this scenario on react-to-print with this situation:
https://github.com/gregnb/react-to-print/issues/206

**Comment by rizabek-mukanov** [comment]
> @therohitjha it's not that simple, the way you're showing only prints the data that's your screen is showing, imagine that you have more than 100 rows and you need to print all the data, do you have a solution for that?
> i left a issue with this scenario on react-to-print with this situation:
> [gregnb/react-to-print#206](https://github.com/gregnb/react-to-print/issues/206)

were you able to find solution for this issue?

**Comment by usahai** [comment]
> > @therohitjha it's not that simple, the way you're showing only prints the data that's your screen is showing, imagine that you have more than 100 rows and you need to print all the data, do you have a solution for that?
> > i left a issue with this scenario on react-to-print with this situation:
> > [gregnb/react-to-print#206](https://github.com/gregnb/react-to-print/issues/206)
> 
> were you able to find solution for this issue?

I'm also kinda looking for something similar, although my use case is a little different. I am adding as a column, and would like to pass specific data into the content prop. Any ideas?

**Comment by xStorm111** [comment]
@rizabek-mukanov Sorry for late response, i only saw this now
Yes i did, i found out that my problem was the maxBodyHeight, if i remove it, react-to-print was able to print all data
