### ISSUE TITLE
Setting detailPanelColumnAlignment to right misaligns row while editing

### ISSUE THREAD

**Issue by Jim-Gambit** [mbrn/material-table#900]
**Describe the bug**
First of all great work! Material Table has made my work a lot easier. I am trying to create a table with multiple detail panels. I want the icon column of the panels on the right hand side and I am using detailPanelColumnAlignment props with value 'right' in option. This works fine but when I try to edit a row, column misaligns with the header i.e. it shifts right by one column.

**To Reproduce**
1. Make the table rows editable
2. Create a multiple details panel
3. In options, set detailPanelColumnAlignment: 'right'
4. Try editing any row

**Expected behavior**
Rows should not shift or misalign from headers while editing even if detailPanel column is right align.

**Desktop (please complete the following information):**
 - OS:  Ubuntu 16.04
 - Browser: Chrome
 - Version: 75.0.3770.142

**Comment by mbrn** [comment]
Hi @Jim-Gambit ,

We will resolve this bug asap.
