### ISSUE TITLE
Draggable option doesn't work

### ISSUE THREAD

**Issue by hrafaelveloso** [mbrn/material-table#901]
**Describe the bug**
In this new 1.41.0 version it was introduce one `draggable` option that could opt-out the draggable feature of the header columns (#779). I wanted that feature but it isn't working in the moment...

**To Reproduce**
https://codesandbox.io/s/affectionate-nightingale-6x3xn

**Expected behavior**
Disable header draggable feature.

**Desktop:**
 - OS: Linux
 - Browser: Chrome
 - Version: 75.0.3770.142

**Comment by emrekara37** [comment]
Hi @hrafaelveloso 

Are you sure it doesn't work in version 1.41.0 ?
works at me version `1.41.0`
Check your sandbox version
<img width="276" alt="Screenshot_3" src="https://user-images.githubusercontent.com/17519791/62203371-b208db00-b393-11e9-994e-417a4ed0fe78.png">

**Comment by hrafaelveloso** [comment]
I changed the version in `package.json` and it works in sandbox now. However my `npm ls material-table` returns `material-table@1.41.0` and still doesn't work.

My options:
```
options={{
    draggable: false,
    grouping: false,
    toolbar: false,
    showTitle: false,
}}
```

**Comment by hrafaelveloso** [comment]
I stoped my dev server and started again. It's working now, sorry for the problem....
