### ISSUE TITLE
A table that is both "Editable" and uses "Remote Data"

### ISSUE THREAD

**Issue by msb** [mbrn/material-table#904]
The "Editable" examples all use table `data` managed in the state, whereas the "Remote Data" examples manage the  `data` internally. What approach should I take if I want to do both?

**Comment by kaienbcjdoapwkfldue** [comment]
You can use a function as the `data` prop where you make your API call to get your remote data. Then, supply functions to `onRowAdd`, `onRowUpdate` and `onRowDelete` of the `editable` prop where you make the appropriate API calls for mutating your data.

**Comment by pak11273** [comment]
I personally use the react state approach.  You're not as coupled to material-table that way.

**Comment by jakecinco** [comment]
> You can use a function as the `data` prop where you make your API call to get your remote data. Then, supply functions to `onRowAdd`, `onRowUpdate` and `onRowDelete` of the `editable` prop where you make the appropriate API calls for mutating your data.

Hi, can you show us an example code please?  I'm also trying to understand how to do this. Thanks.

**Comment by ROSHANDBIT** [comment]
here is the sample code snippet:
`  const fetchRemoteDataFunc = async (query) => {
    try {
      // network call here
      // then 
      resolve({
        data: 
        ....
      })
    } catch (err) {
      console.log(err)
    }
  }`



`            <MaterialTable
              columns={columns}
              data={fetchRemoteDataFunc} 
              tableRef={tableRef}
              ....
              title=''
              editable={{
                onRowUpdate: fetchRemoteDataFunc
              }}
            />`
