### ISSUE TITLE
Tooltip will be positioned wrong on free action buttons

### ISSUE THREAD

**Issue by efkan** [mbrn/material-table#910]
Hello,

When a free action button is created, the tooltip text that assigned to the button is shown different position than built-in buttons' tooltips.

For instance:
![image](https://user-images.githubusercontent.com/6974198/62285039-84886400-b45d-11e9-8aca-b38293ff14ac.png)

**Comment by emrekara37** [comment]
Hi, Fixed

**Comment by efkan** [comment]
Hello Emre,

Sorry for late. 

I couldn't close the issue because I didn't get a chance to check it yet.

It's nice to hear that the issue has been resolved.

Keep your great works up!

**Comment by emrekara37** [comment]
First of all thanks
@efkan please wait the next release  :)
