### ISSUE TITLE
duplicated data

### ISSUE THREAD

**Issue by axle21** [mbrn/material-table#914]
after i pagination some of my data being duplicated,

![Capture](https://user-images.githubusercontent.com/43855639/62353074-1622cf00-b54d-11e9-8476-dc3cb93f5ffe.PNG)

**Comment by emrekara37** [comment]
Hi @axle21 ,
duplicate #893 
and i fixed https://github.com/mbrn/material-table/pull/911,
will probably be in the next release

**Comment by axle21** [comment]
is there any update with this?

**Comment by SpearThruster** [comment]
I am still having this issue -> what's the status of this?

**Comment by Domino987** [comment]
Can you reproduce that in a sandbox?

**Comment by spaceneurocruzz** [comment]
same issue! there will be multiple duplicated row. When I use the filter, the duplicated data will show even if they doesn't meet the filter criteria...

**Comment by freddymercury** [comment]
I am getting the same buggy behavior.  This is on version: 1.52.0

When using the search filter, duplicated data shows up in the table and persists across pagination (every page has the same repeating 3 rows and then the page rows show up below)

![Screen Shot 2020-10-13 at 2 20 23 PM](https://user-images.githubusercontent.com/22851546/95917527-407e3800-0d5f-11eb-9de7-54393a19984d.png)

**Comment by Domino987** [comment]
Hi can you verify that in a version after 1.6x maybe 1.68, which is not broken and create a Sandbox so I can take a look at it?

**Comment by freddymercury** [comment]
It looks like there was a memory leak in the data.  So after addressing those (via deep clone) I am no longer having the issue.  Thanks!

**Comment by Domino987** [comment]
@axle21 is this still present in the current version?

**Comment by axle21** [comment]
@Domino , last time i check yes, but as of now not using it anymore on my
current projects. I created my own table component for this one.
