### ISSUE TITLE
Transparent background for the whole table

### ISSUE THREAD

**Issue by ysmike** [mbrn/material-table#920]
**Is your feature request related to a problem? Please describe.**
I'd like to have an image as a background of the website but noticed that the table covers over the image due to its assigned colors.

**Describe the solution you'd like**
Would it be possible to have an option prop that toggles transparency or controls color/opacity of the entire table?

**Describe alternatives you've considered**
I've tried setting the backgroundColor to "transparent" and rgb(0, 0, 0, 0.5) to test the toolbar but the color remains as white. Even if this were possible, custom-changing the color for each component may be a hassle vs. one option prop for all.

**Additional context**
Probably not something you should look into urgently but would be a neat feature to have IMHO! By the way, material-table == my favorite table out there atm!

**Comment by pak11273** [comment]
I don't think this should be a feature because I see rare cases where anybody wants to use images for backgrounds on tables.

**Comment by usamamoinakhter** [comment]
Just add the following code and you are done
`   style={{ boxShadow: '0px 0px 0px rgba(0,0,0,0.0)',backgroundColor:'transparent' }}`
