### ISSUE TITLE
Why is pagination caption display set to 'none'

### ISSUE THREAD

**Issue by sjovanelly** [mbrn/material-table#921]
I can't get the pagination caption to show up.  Doesn't matter what I set for pagination. labelRowsPerPage.

Seems that in src/index.js there is this following code always making that display to none
  paginationCaption: {
    display: 'none'
  }

I can't find the setting to turn on other than setting 
    MuiTablePagination: {
      caption: {
        display: 'block !important',
      },
  }
 in my theme.

Is this a bug or am I missing a setting?  That was changed back when this code was in material-table.js with commit 929f0fef1b03d40ba912f3f190a5e13d2be6f921.  Mobile fix.

**Comment by sjovanelly** [comment]
Update, looks like because of the override of the actions to include to, from, etc.  That does hide the labelRowsPerPage too, unfortunately.

**Comment by sjovanelly** [comment]
My fix above doesn't fix it.

**Comment by sjovanelly** [comment]
the fix above with the !important shows double n-nn of nnn.  If you also add pagination override below to your material-table, it hides the unneeded one.
<TablePagination
  {...props}
  labelDisplayedRows={row => <div/>}
/>

**Comment by AsheKR** [comment]
has any update?
