### ISSUE TITLE
Items within filtering row are not on the same line

### ISSUE THREAD

**Issue by tbilek** [mbrn/material-table#929]
Hey :)

I came across a problem with filtering row. I have select field and also input field at one filtering row. The problem is that they are not on the same line. I can see that problem itself is empty label element which is within select field but missing within input field.

Is it a bug or I missed something?

Thank you :)

![issue](https://user-images.githubusercontent.com/49515764/62471060-1b298d80-b79c-11e9-9bf2-fa0d1dea4180.png)

**Comment by emrekara37** [comment]
the reason of this [Material Select](https://material-ui.com/components/selects/#selects) Placeholder,
i will ask that
