### ISSUE TITLE
Do not require material icons to be imported from remote

### ISSUE THREAD

**Issue by bgits** [mbrn/material-table#93]
**Is your feature request related to a problem? Please describe.**
Often a project already has material-ui/icons in node_modules, so there is no need to load it from a remote resource and as pollute the global space.

**Describe the solution you'd like**
The required icons should already either be part of the library or can be imported directly where material-table is being used.

example:
```
import React, { Fragment, memo } from 'react'
import MaterialTable from 'material-table'
import Icons from '@material-ui/icons'

const myTable = ({ data }) => (
  <Fragment>
    <MaterialTable
      Icons={Icons}
      columns={[
        { title: 'Profile Id', field: 'idGiver', type: 'numeric' },
        { title: 'Name', field: 'name' },
        { title: 'Url', field: 'url' },
        { title: 'Commit Time', field: 'commitTime', type: 'numeric' },
        { title: 'cancel', field: 'canceled' }
      ]}
      data={data}
      title="Funding Profiles"
    />
  </Fragment>
)

export default memo(myTable)
```

**Describe alternatives you've considered**

**Additional context**

**Comment by mbrn** [comment]
Very clear alternative to cdn import. I will try and do this. Thank @bgits

**Comment by michaeljtobias** [comment]
im having issues doing this/it's not working as advertised.  I used the code above (except the property icons needs to be lower case). But then it gives this error:

TS2739: Type 'typeof import("/Users/michael/path/to/projecti/node_modules/@material-ui/icons/index")' is missing the following properties from type 'Icons': DetailPanel, Export, NextPage, PreviousPage, ThirdStateCheck

So then I do something like:

import {
    Search,
    ViewColumn,
    SaveAlt,
    ChevronLeft,
    ChevronRight,
    FirstPage,
    LastPage,
    Add,
    Check,
    FilterList,
    Remove,
} from '@material-ui/icons'
...
icons={ 
    Check: Check,
    DetailPanel: ChevronRight,
    Export: SaveAlt,
    Filter: FilterList,
    FirstPage: FirstPage,
    LastPage: LastPage,
    NextPage: ChevronRight,
    PreviousPage: ChevronLeft,
    Search: Search,
    ThirdStateCheck: Remove,
}

That fails with:

TS2322: Type '{ Check: ComponentType<SvgIconProps>; DetailPanel: ComponentType<SvgIconProps>; Export: ComponentType<SvgIconProps>; Filter: ComponentType<SvgIconProps>; FirstPage: ComponentType<SvgIconProps>; ... 5 more ...; ViewColumn: ComponentType<...>; }' is not assignable to type 'Icons'.
Types of property 'Check' are incompatible.
Type 'ComponentType<SvgIconProps>' is not assignable to type '() => ReactElement<any>'.        
Type 'ComponentClass<SvgIconProps, any>' is not assignable to type '() => ReactElement<any>'.
Type 'ComponentClass<SvgIconProps, any>' provides no match for the signature '(): ReactElement<any>'.

How does one use this feature? Thanks much for you response.

**Comment by michaeljtobias** [comment]
this worked:

import { SvgIconProps } from '@material-ui/core/SvgIcon'

import Search from '@material-ui/icons/Search'
import ViewColumn from '@material-ui/icons/ViewColumn'
import SaveAlt from '@material-ui/icons/SaveAlt'
import ChevronLeft from '@material-ui/icons/ChevronLeft'
import ChevronRight from '@material-ui/icons/ChevronRight'
import FirstPage from '@material-ui/icons/FirstPage'
import LastPage from '@material-ui/icons/LastPage'
import Add from '@material-ui/icons/Add'
import Check from '@material-ui/icons/Check'
import FilterList from '@material-ui/icons/FilterList'
import Remove from '@material-ui/icons/Remove'

import MaterialTable from 'material-table';


let searchIcon: React.ReactElement<SvgIconProps> = <Search />; 
            let viewColumnIcon: React.ReactElement<SvgIconProps> = <ViewColumn />; 
            let saveAltIcon: React.ReactElement<SvgIconProps> = <SaveAlt />; 
            let chevronLeftIcon: React.ReactElement<SvgIconProps> = <ChevronLeft />; 
            let chevronRightIcon: React.ReactElement<SvgIconProps> = <ChevronRight />; 
            let firstPageIcon: React.ReactElement<SvgIconProps> = <FirstPage />; 
            let lastPageIcon: React.ReactElement<SvgIconProps> = <LastPage />; 
            let checkIcon: React.ReactElement<SvgIconProps> = <Check />; 
            let filterListIcon: React.ReactElement<SvgIconProps> = <FilterList />; 
            let removeIcon: React.ReactElement<SvgIconProps> = <Remove />; 


icons={{ 
                        Check: () => { return checkIcon },
                        Export: () => { return saveAltIcon },
                        Filter: () => { return filterListIcon },
                        FirstPage: () => { return firstPageIcon },
                        LastPage: () => { return lastPageIcon },
                        NextPage: () => { return chevronRightIcon },
                        PreviousPage: () => { return chevronLeftIcon },
                        Search: () => { return searchIcon},
                        ThirdStateCheck: () => { return removeIcon },
                        ViewColumn: () => { return viewColumnIcon },
                        DetailPanel: () => { return chevronRightIcon },
                      }}

**Comment by sfDev001** [comment]
Thank you! It worked
```
import Search from '@material-ui/icons/Search'
import ViewColumn from '@material-ui/icons/ViewColumn'
import SaveAlt from '@material-ui/icons/SaveAlt'
import ChevronLeft from '@material-ui/icons/ChevronLeft'
import ChevronRight from '@material-ui/icons/ChevronRight'
import FirstPage from '@material-ui/icons/FirstPage'
import LastPage from '@material-ui/icons/LastPage'
import Add from '@material-ui/icons/Add'
import Check from '@material-ui/icons/Check'
import FilterList from '@material-ui/icons/FilterList'
import Remove from '@material-ui/icons/Remove'

import MaterialTable from 'material-table';
...
<MaterialTable
          icons={{ 
            Check: Check,
            DetailPanel: ChevronRight,
            Export: SaveAlt,
            Filter: FilterList,
            FirstPage: FirstPage,
            LastPage: LastPage,
            NextPage: ChevronRight,
            PreviousPage: ChevronLeft,
            Search: Search,
            ThirdStateCheck: Remove,
          }}
```

**Comment by sfDev001** [comment]
Specifying icons and using Editable together will result in an error. Is there a way to use it together?
https://mbrn.github.io/material-table/#/docz-examples-15-example-editable
<img width="824" alt="img" src="https://user-images.githubusercontent.com/6834723/56253252-8b7da780-60f6-11e9-849c-c3cd8d3c7bdc.png">

**Comment by mbrn** [comment]
It should be resolved with latest versions.

**Comment by bhavna-it-talents** [comment]
i need diffrent icon on each filter.

**Comment by Sphinxs** [comment]
A complete version:

```js
import Search from "@material-ui/icons/Search";

import ViewColumn from "@material-ui/icons/ViewColumn";

import SaveAlt from "@material-ui/icons/SaveAlt";

import ChevronLeft from "@material-ui/icons/ChevronLeft";

import ChevronRight from "@material-ui/icons/ChevronRight";

import FirstPage from "@material-ui/icons/FirstPage";

import LastPage from "@material-ui/icons/LastPage";

import Add from "@material-ui/icons/Add";

import Check from "@material-ui/icons/Check";

import FilterList from "@material-ui/icons/FilterList";

import Remove from "@material-ui/icons/Remove";

import ArrowDownward from "@material-ui/icons/ArrowDownward";

import Clear from "@material-ui/icons/Clear";

import DeleteOutline from "@material-ui/icons/DeleteOutline";

import Edit from "@material-ui/icons/Edit";

export default {
  Check: Check,
  DetailPanel: ChevronRight,
  Delete: DeleteOutline,
  Export: SaveAlt,
  Filter: FilterList,
  FirstPage: FirstPage,
  LastPage: LastPage,
  NextPage: ChevronRight,
  PreviousPage: ChevronLeft,
  Search: Search,
  ThirdStateCheck: Remove,
  Add: Add,
  SortArrow: ArrowDownward,
  Clear: Clear,
  Edit: Edit,
  ViewColumn: ViewColumn
};
```

**Comment by CristianaYasuda** [comment]
My icon Clear does not render, How do I do? My version:
	"@material-ui/core": "^4.9.5",
    "@material-ui/icons": "^4.9.1",
    "@material-ui/styles": "^4.9.0",
	"material-table": "^1.57.2",

**Comment by Sphinxs** [comment]
@CristianaYasuda check the way you're [importing](https://material-ui.com/components/icons/#usage) the icons and the version, in my project I'm using the same version for the Material Table and the version 4.5.1 for the Material UI Icons

**Comment by blumk** [comment]
@CristianaYasuda Follow the instructions described in the `README.md`, they are more up-to-date than the comments in this thread.
https://github.com/mbrn/material-table#installation

**Comment by matthewcoding0** [comment]
Is it completely necessary to import the icons? Why cant the icons just be used by default? It's kind of annoying to have to specify these icons whenever i make a table.

**Comment by PeaceS** [comment]
@matthewcoding0 agree!
