### ISSUE TITLE
Many, many, many instances in Redux

### ISSUE THREAD

**Issue by oze4** [mbrn/material-table#930]
**Describe the bug**
Material Table is creating many Redux instances of my app - not sure why this is happening but I have pin pointed it to be a Material Table issue. I don't even use Redux in my app.

**To Reproduce**
1. Go here: https://codesandbox.io/s/react-material-table-start-on-page-vzmv8
2. Open URL in a new page, so you can view data in Redux DevTools (see screenshot below)
3. Open Redux DevTools

**Expected behavior**
Only one instance of the app should show up in devtools

**Screenshots**
![image](https://user-images.githubusercontent.com/21092343/62476676-1ac5ce00-b76d-11e9-8414-190eb969ff59.png)

**Comment by oze4** [comment]
@emrekara37 - it looks like `redux` and `react-redux` are dependencies of `react-beautiful-dnd` - not sure if this is a `material-table` issue (meaning, how `material-table` is using `react-beautiful-dnd`) or a `react-beautiful-dnd` issue (meaning, a bug within their code).

FYI.

**Comment by oze4** [comment]
It looks like this is an issue with `react-beautiful-dnd` - this happens in the examples they provide on their repo...

https://ql08j35j3q.csb.app/

The 'Simple Vertical List` example: https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/about/examples.md#basic-samples

**Comment by log901108** [comment]
same issue. does it fix or any solution?

**Comment by log901108** [comment]
I checked react-beutiful-dnd example you mentioned(https://ql08j35j3q.csb.app/), however there is no redux instance creation. Did they fixed this issue at newer version?

**Comment by jayarjo** [comment]
@log901108 try to update `react-beautiful-dnd` dependency to the latest version and let us know if it will resolve the problem for you.

**Comment by oze4** [comment]
@log901108 @jayarjo `react-beautiful-dnd` may have resolved this issue.. As, log901108 said, the example which I provided no longer causes multiple Redux instances.

**Comment by log901108** [comment]
I updated react-beautiful-dnd in 11.0.5 which is latest version, however the issue is happened. 
Then I just tried replacing exact folder of react-beautiful-dnd from node_module in material-table(which is ../react_project/node_module/material-table/node_module/react-beautiful-dnd). Unfortunately, it doesn't fix at all.  :-(

**Comment by oze4** [comment]
@log901108 seems to be an issue with `Material-Table` then..?

**Comment by log901108** [comment]
I tried test with delete every react-beautiful-dnd in my project, however it still gives many redux instance creation(it is not make sense). I think I could make mistake on my test condition, since I am sort of newbie in React. Anybody test with the latest version of react-beutiful-dnd?

**Comment by kyle-mccarthy** [comment]
As of 1.54.2, [material-table locks the react-beautiful-dnd dependency to 11.0.3](https://github.com/mbrn/material-table/blob/master/package.json#L83), so installing your own version won't resolve the issue (assuming that updating react-beautiful-dnd would resolve the problem)

**Comment by Jsalvat** [comment]
Bummp

**Comment by AntOliRsn** [comment]
Still facing this issue, any news on this ?

**Comment by LoicHa** [comment]
Same issue here :/

**Comment by Praveen-Aanand** [comment]
same here ☹

**Comment by madly0894** [comment]
Has anyone else solved the problem?

**Comment by nivranaitsirhc** [comment]
Sigh.. this is a bummer

**Comment by yasdev8** [comment]
Hi, I have the latest version of material-table (1.69.3) and I still have this issue. Someone else have also this issue?
