### ISSUE TITLE
Sort columns by drag & drop with hidden column

### ISSUE THREAD

**Issue by juldrixx** [mbrn/material-table#932]
**Describe the bug**
When one column has the hidden feature to true the feature to order columns by dragging them doesn't work properly.

**Comment by Tibblist** [comment]
I am also experiencing this issue when using the columnsButton option and toggling 1 or more columns to be hidden

**Comment by mieber** [comment]
The same here. A fix would be highly appreciated.

**Comment by ryanintulsa** [comment]
> I am also experiencing this issue when using the columnsButton option and toggling 1 or more columns to be hidden

@Tibblist I saw this issue as well, but I think it is unrelated to this drag & drop bug. Please create another issue. I'll take a look at this one and then that one if someone doesn't beat me to it, because both of these are must fix issues for my project.

**Comment by ryanintulsa** [comment]
My PR to fix this is here: https://github.com/mbrn/material-table/pull/1228
