### ISSUE TITLE
TS2322 Type 'string' is not assignable to type 

### ISSUE THREAD

**Issue by govi74** [mbrn/material-table#933]
After updating to the latest version, getting the typescript errors.

TypeScript error in myfile.tsx:
Type 'string' is not assignable to type '"state" | "region" | "id" | "shape" | "ad" | "timeRequestReceived" | "estimatedEndTime" | "wrstate" | "workflowSurrogateKey" | undefined'.  TS2322

    139 |         {
    140 |           title: "",
  > 141 |           field: "state",
        |           ^
    142 |           render: rowdata => (
    143 |             <Avatar
    144 |               style={{

**Comment by govi74** [comment]
Looks like the issue was I had a nested object and for one of the field i was assigning the nested objects.

Like 

        {
          title: "Workflow Name",
          field: "workflowDefinition.name",
          ...
        }

field?: keyOf Rowdata;

Is that supported?  With the addition of typescript support with "keyOf Rowdata", the above is broken I believe.

**Comment by madflanderz** [comment]
You get this error if you misspelled a property name (like in your case). Typescript doesn't know that you have nested data. In this case you can use u custom render function:

`{
  title: "Workflow Name",
  render: rowData => rowData.workflowDefinition.name
}`
