### ISSUE TITLE
How do i add page link to field.

### ISSUE THREAD

**Issue by sunithakk** [mbrn/material-table#935]
How do i add page link to field.

**Comment by hrafaelveloso** [comment]
You can use custom render:

```javascript
columns={[
    {
        field: 'name',
        title: 'Name',
        render: rowData => <a href=`/profile/${rowData.name}`>{rowData.name}</a>
    }
]}

```

**Comment by sunithakk** [comment]
I need to pass query params to link but i m not able to ,
const columns = [
{
title: "Theme Name",
field: "theme_name",
render: rowData => <Link to="scene/" + `${rowData.id}`
state={{id:rowData.id}}>{rowData.theme_name}</Link>
},

{
title: "Batch",
field: "batch_id",
lookup: this.state.batches
},
{
title: "Class",
field: "class_id",
lookup: this.state.classes
}
];

**Comment by hrafaelveloso** [comment]
Can you show some codesandbox with that problem?
Why are you using two string literals:
```jsx
to="scene/" + `${rowData.id}`
``` 

and not 
```jsx
to=`scene/${rowData.id}`
```

**Comment by emrekara37** [comment]
i close this issue. reopen if you needed please

**Comment by sunithakk** [comment]
I found the solution yeah pls close.
