### ISSUE TITLE
import failed in electron

### ISSUE THREAD

**Issue by bohrsty** [mbrn/material-table#94]
I'd like to use your data table component with electron and electron-forge, but the import failed with the following error message:  
`Uncaught SyntaxError: Unexpected identifier`.

Searching the internet points to issues with css, but neither importing the icon css from i.e. `material-design-icon-fonts` nor loading it in HTML file (local and remote from i.e. google) let me use it...

Is there any known problem using it with electron?

**Comment by mbrn** [comment]
Hi @bohrsty ,

You may the first person who want to use material-table in electron. I don't know how it works and how to help you? 

@luizbaldi do you have any experience with electron?

If no one helps you, i will install elecktron and try material-table:)

**Comment by luizbaldi** [comment]
I'll take a look at this, seems like a really interesting problem to solve :)

**Comment by bohrsty** [comment]
this has been fixed in current version (maybe through [pull request 111](https://github.com/mbrn/material-table/pull/111) by @codebutler... so it wasn't css but babel/env preset...
