### ISSUE TITLE
makeStyles was not found in @material/core

### ISSUE THREAD

**Issue by benjaminsuch** [mbrn/material-table#942]
**Describe the bug**
Installing the newest version 1.45 and then running "yarn watch" (from create-react-app) leads to a warning:

>  warning  in ./node_modules/material-table/node_modules/@material-ui/pickers/dist/material-ui-pickers.esm.js
> 
> "export 'makeStyles' (imported as 'makeStyles$1') was not found in '@material-ui/core'

**To Reproduce**
1. Go to favorite react project
2. Install version 1.45 of material-table
3. Run yarn watch

**Expected behavior**
I expect no warning.

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu
 - Browser: Chrome

**Comment by emrekara37** [comment]
Hi , i tried in`1.45.0` but i am not saw error.
