### ISSUE TITLE
components.Pagination labelRowsPerPage overwritten by localization

### ISSUE THREAD

**Issue by y3sh** [mbrn/material-table#943]
**Describe the bug**

This problem came up for me when following the advice from https://github.com/mbrn/material-table/issues/148#issuecomment-452984812, referencing this line [material-table.js:449](https://github.com/mbrn/material-table/blob/37fc73876c799eb6604b9c7b4eba1da51581848a/src/material-table.js#L449). LabelDisplayedRows and labelRowsPerPage don't work anymore.

For example:
```jsx
// import { TablePagination } from '@material-ui/core';

<MaterialTable
  columns={[]}
  data={this.state.data}
  title='Demo Title'

  // ******** Some workarounds can happen out here now *******
  localization={{
    pagination: {
      labelDisplayedRows: 'string here'
      labelRowsPerPage: 'another string here'
    }
  }}
  // ********

  components={{
    Pagination: props => (
        <TablePagination
            {...props}

            // ******* These don't work anymore, because overwritten ********
            labelRowsPerPage={<div style={{fontSize: 14}}>{props.labelRowsPerPage}</div>}
            labelDisplayedRows={row => <div style={{fontSize: 14}}>{props.labelDisplayedRows(row)}</div>}
            // ******* 
        />
    )
  }}
/>;
```

Related issues: https://github.com/mbrn/material-table/issues/148, https://github.com/mbrn/material-table/issues/226

**Comment by cristiangabor** [comment]
I have the same issue ...At least I saw `labelDisplayedRows={row => <div style={{fontSize: 14}}>{props.labelDisplayedRows(row)}</div>}` does not change the table rendering. Could this still be an ongoing issue?

**Comment by bargar** [comment]
I have the same issue. My function is being invoked and is returning the desired text, but not showing up in the rendered component.
