### ISSUE TITLE
Overriding MTableHeader (how to add button to header)

### ISSUE THREAD

**Issue by nikhilwbhatia** [mbrn/material-table#944]
How would I go about overriding MTableHeader to add a button directly to the right of the search bar in the table header. Thank you!

**Comment by pendrive148** [comment]
You can add a button with the 'actions' prop and set 'isFreeAction' to true.
Exemple:
```
actions={[
            {
              icon: () => <FilterlistIcon />,
              tooltip: 'Filter',
              onClick: (event, rowData) =>  alert("Alert"),
              isFreeAction: true
            },
          ]}
```

![image](https://user-images.githubusercontent.com/4793775/62711471-7d1e0900-b9cf-11e9-8604-353b672932ef.png)
