### ISSUE TITLE
TypeScript types for custom actions are wrong

### ISSUE THREAD

**Issue by vinterdo** [mbrn/material-table#948]
I have custom action on table. Typescript requires function to have signature:
`public customAction(event: any, rowData: IRowData[])`
It is ok when selection is enabled, but when selection is disabled and action is executed on single row, rowData is just object of this row (not an array). So now i need to do @ts-ignore or my code dont work.

**Comment by gianlucamateo** [comment]
The type for parentChildData is also wrong, as the function returns a single dataset and not an array.

**Comment by adamTarr** [comment]
Also running into this issue. In a `action`, the `onClick` function is typed as 
`Action<RowData>.onClick: (event: any, data: RowData | RowData[]) => void`
This makes custom actions unusable in a TypeScript project unless the error is ignored with `//@ts-ignore`
