### ISSUE TITLE
Resizing of columns

### ISSUE THREAD

**Issue by Dwight-D** [mbrn/material-table#950]
An option for resizable columns would be great, in a similar vein as the draggable columns. Maybe such functionality is already possible but I didn't see any straight forward way to do it or find anything when searching.

Thanks for your work!

**Comment by jakeleventhal** [comment]
The following are good examples of what could work well:
https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/tree-data/
https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/column-resizing

**Comment by LChris94** [comment]
Some notice from this topic?

**Comment by scscgit** [comment]
I'm also voting for this to be added - and I'm curious, are there any reference requirements of UX guidelines that this project is trying to fulfill? For example, I found it's as high as # 2 here:
> https://www.mobilespoon.net/2019/11/design-ui-tables-20-rules-guide.html

Also as a reference, there seems to be a similar paid product called DevExtreme out there which already supports this, as seen in their React Grid Tree Data example, so it may be useful as an inspiration:
> https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/tree-data/

**Comment by iamsaurabhgupt** [comment]
@mbrn please prioritise the resizing of columns. It is essential when the contents are not uniform. 
It makes the table look ugly. See image attached.
If the user could resize the column and the width adjusts properly, it would be wonderful.

![image](https://user-images.githubusercontent.com/43205009/86085628-33458200-babd-11ea-87f0-0951a9979593.png)

**Comment by iamsaurabhgupt** [comment]
@mbrn please prioritise the resizing of columns. It is essential when the contents are not uniform.
It makes the table look ugly. See image attached.
If the user could resize the column and the width adjusts properly, it would be wonderful.
![image](https://user-images.githubusercontent.com/43205009/86085723-7b64a480-babd-11ea-9894-db4405a724c4.png)

**Comment by priyanshu-intellemo** [comment]
In some cases, this could be handy! I need this in my project too.

**Comment by Shivam-Intellemo** [comment]
can we have resize feature of columns in this table in priority?

**Comment by mbrn** [comment]
I started to work on this :)

**Comment by jakeleventhal** [comment]
not stale

**Comment by rikr2sanchez** [comment]
any progress on this ?

**Comment by jakeleventhal** [comment]
not stale

**Comment by mayank-mundhra-2012** [comment]
Any progress on this?

**Comment by scscgit** [comment]
@mbrn can you please [label this issue](https://github.com/mbrn/material-table/blob/master/.github/stale.yml#L7) to make the `stale` bot shut up?

**Comment by rikr2sanchez** [comment]
not stale

**Comment by scscgit** [comment]
still not stale ✨

**Comment by scscgit** [comment]
and yet it's not stale

**Comment by rikr2sanchez** [comment]
@mbrn any update on this or insights on how to implement ?
