### ISSUE TITLE
CSS off , supported with screenshot from matrial-ui website

### ISSUE THREAD

**Issue by GESTIFANOS** [mbrn/material-table#953]
![bug_display_maerial_ui](https://user-images.githubusercontent.com/787384/62662083-b307b280-b927-11e9-807b-cf995d45be46.png)
I have similar issue in my dev environment as well.

**Comment by GESTIFANOS** [comment]
Look at the search & pagination part at a minimum.

**Comment by emrekara37** [comment]
<img width="894" alt="Screenshot_2" src="https://user-images.githubusercontent.com/17519791/62686988-8195f200-b9ce-11e9-9db5-28d33e05ee99.png">

On my pc

**Comment by GESTIFANOS** [comment]
I noticed that material-ui site don't show the issue any more. I still have it in my pc. 
Any pointer is appreciated. 
Chrome
![image](https://user-images.githubusercontent.com/787384/62731781-d0945500-b9d7-11e9-9ec7-9172eae5ff2c.png)

Issue is both in  Chrome & Firefox
![image](https://user-images.githubusercontent.com/787384/62732007-3f71ae00-b9d8-11e9-8de1-237aeba7b1c4.png)

![image](https://user-images.githubusercontent.com/787384/62732029-4993ac80-b9d8-11e9-8f4d-fdc7a7863dc9.png)

**Comment by emrekara37** [comment]
Hi @GESTIFANOS ,
could you share console output screenshot
Thanks

**Comment by GESTIFANOS** [comment]
Just created clean demo, attached is the screenshot on debug mode.

![image](https://user-images.githubusercontent.com/787384/62739326-64225180-b9e9-11e9-939d-844c9378f0ef.png)

Here are the dependency from package.json 
![image](https://user-images.githubusercontent.com/787384/62739452-a51a6600-b9e9-11e9-935c-08efa7134e46.png)

**Comment by GESTIFANOS** [comment]
{
  "name": "fleet_ui",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@material-ui/core": "^4.3.1",
    "@material-ui/icons": "^4.2.1",
    "@material-ui/styles": "^4.3.0",
    "axios": "^0.18.0",
    "bootstrap": "^4.3.1",
    "html2canvas": "^1.0.0-rc.3",
    "i18next": "^15.1.0",
    "i18next-browser-languagedetector": "^3.0.1",
    "jspdf": "^1.5.3",
    "jspdf-autotable": "^3.1.1",
    "material-table": "^1.47.0",
    "muicss": "^0.9.41",
    "react": "^16.8.4",
    "react-dom": "^16.8.4",
    "react-i18next": "^10.9.0",
    "react-redux": "^7.0.0-beta.0",
    "react-router-dom": "^5.0.0",
    "react-scripts": "2.1.8",
    "recharts": "^1.5.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ]
}

**Comment by cbio-thomas** [comment]
It's not finding the icons it uses for pagination, sort, etc. features; you can resolve by manually passing an icon prop object to the table, as described [here](https://github.com/mbrn/material-table#2add-material-icons).

**Comment by GESTIFANOS** [comment]
I see, Thanks I will check it out.

**Comment by emrekara37** [comment]
I am closing this issue. You can reopen if you need.

**Comment by GESTIFANOS** [comment]
Thanks, linking in my inde.html worked.
