### ISSUE TITLE
Table Body not updating after onChangeRowsPerPage

### ISSUE THREAD

**Issue by msb** [mbrn/material-table#957]
I have an application with table data managed outside material table in state - this is because my table is editable (as per your examples). I had overridden onChangePage and onChangeRowsPerPage and my table was paging correctly in version 1.40.1. However, when I upgraded, to 1.46.0, the table body stopped resizing after onChangeRowsPerPage is handled. I have added a cut-down example of how I am using material-table:

```tsx
import React from 'react';
import MaterialTable from "material-table";
import {TablePagination} from "@material-ui/core";

export interface IQuery {
    page: number
    pageSize: number
}

export interface IState {
    query: IQuery
    data: any[]
    totalCount: number
    pageChanged: boolean
}

class App extends React.Component<object, IState> {

  public state = {
    query: {
      page: 1,
      pageSize: 5,
    },
    data: [],
    totalCount: 0,
    pageChanged: true
  }

  public fetchData(additionalState?: object) {
    const { query } = this.state
    const url = `https://reqres.in/api/users?per_page=${query.pageSize}&page=${query.page}`
    fetch(url)
      .then(response => response.json())
      .then(result => {
        this.setState({
            ...additionalState,
            data: result.data,
            totalCount: result.total
        })
      })
  }

  public componentDidMount() {
    this.fetchData()
  }

  render() {
    const { totalCount, query, data, pageChanged } = this.state

    return (
      <MaterialTable
        title="Illustrates Page Size Changing Problem"
        columns={[
          {
            title: 'Avatar',
            field: 'avatar',
            render: (rowData: any) => (
              <img
                style={{ height: 36, borderRadius: '50%' }}
                src={rowData.avatar}
                alt={rowData.first_name}
              />
            ),
          },
          { title: 'Id', field: 'id' },
          { title: 'First Name', field: 'first_name' },
          { title: 'Last Name', field: 'last_name' },
        ]}
        data={data}
        components={{
          Pagination: (props: any) => (
            <TablePagination {...props} count={totalCount} page={query.page - 1} rowsPerPage={query.pageSize}/>
          ),
        }}
        onChangePage={(page: number) => {
          // this is a work-around, as I received two onChangePage event, the 2nd resetting the page number
          if (pageChanged) {
            this.setState(
              {query: {...query, page: page + 1}, pageChanged: false}, () => this.fetchData({pageChanged: true})
            );
          }
        }}
        onChangeRowsPerPage={(pageSize: number) => {
          this.setState({query: {...query, pageSize}}, this.fetchData);
        }}
      />
    )
  }
}

export default App;
```
I have pin-pointed [the change request that breaks my code](https://github.com/mbrn/material-table/pull/848). It's clearly meant to fix something around page size changing but I don't understand exactly what. So my question is, was this CR incorrect or is there something wrong with my approach - in which case, what should I do instead?

Any help gratefully received.

**Comment by dmyalik** [comment]
Try to add this in your table options:
`options={{
                        pageSize: this.query.pageSize
                    }}`

**Comment by msb** [comment]
Thanks @dmyalik, that worked perfectly.
:)

**Comment by sureshtidbit** [comment]
this does not work when value coming from props not from state. @dmyalik

**Comment by dimabitsorchestra** [comment]
> this does not work when value coming from props not from state. @dmyalik

As a solution, you can use componentDidUpdate() hook and set state there.

`componentDidUpdate(prevProps) {
  if (this.props.pageSize!== prevProps.pageSize) {
    this.setState({pageSize: this.props.pageSize});
  }
}
`
and then use it in table options 
`options={{ pageSize: this.state.pageSize }}`

And again to avoid other issues it is better to use a material-table approach with remote data like [here](https://material-table.com/#/docs/features/remote-data).

**Comment by alam7860** [comment]
pegination with firebase database (remote data)

**Comment by naikvaibhav** [comment]
> I have an application with table data managed outside material table in state - this is because my table is editable (as per your examples). I had overridden onChangePage and onChangeRowsPerPage and my table was paging correctly in version 1.40.1. However, when I upgraded, to 1.46.0, the table body stopped resizing after onChangeRowsPerPage is handled. I have added a cut-down example of how I am using material-table:
> 
> ```tsx
> import React from 'react';
> import MaterialTable from "material-table";
> import {TablePagination} from "@material-ui/core";
> 
> export interface IQuery {
>     page: number
>     pageSize: number
> }
> 
> export interface IState {
>     query: IQuery
>     data: any[]
>     totalCount: number
>     pageChanged: boolean
> }
> 
> class App extends React.Component<object, IState> {
> 
>   public state = {
>     query: {
>       page: 1,
>       pageSize: 5,
>     },
>     data: [],
>     totalCount: 0,
>     pageChanged: true
>   }
> 
>   public fetchData(additionalState?: object) {
>     const { query } = this.state
>     const url = `https://reqres.in/api/users?per_page=${query.pageSize}&page=${query.page}`
>     fetch(url)
>       .then(response => response.json())
>       .then(result => {
>         this.setState({
>             ...additionalState,
>             data: result.data,
>             totalCount: result.total
>         })
>       })
>   }
> 
>   public componentDidMount() {
>     this.fetchData()
>   }
> 
>   render() {
>     const { totalCount, query, data, pageChanged } = this.state
> 
>     return (
>       <MaterialTable
>         title="Illustrates Page Size Changing Problem"
>         columns={[
>           {
>             title: 'Avatar',
>             field: 'avatar',
>             render: (rowData: any) => (
>               <img
>                 style={{ height: 36, borderRadius: '50%' }}
>                 src={rowData.avatar}
>                 alt={rowData.first_name}
>               />
>             ),
>           },
>           { title: 'Id', field: 'id' },
>           { title: 'First Name', field: 'first_name' },
>           { title: 'Last Name', field: 'last_name' },
>         ]}
>         data={data}
>         components={{
>           Pagination: (props: any) => (
>             <TablePagination {...props} count={totalCount} page={query.page - 1} rowsPerPage={query.pageSize}/>
>           ),
>         }}
>         onChangePage={(page: number) => {
>           // this is a work-around, as I received two onChangePage event, the 2nd resetting the page number
>           if (pageChanged) {
>             this.setState(
>               {query: {...query, page: page + 1}, pageChanged: false}, () => this.fetchData({pageChanged: true})
>             );
>           }
>         }}
>         onChangeRowsPerPage={(pageSize: number) => {
>           this.setState({query: {...query, pageSize}}, this.fetchData);
>         }}
>       />
>     )
>   }
> }
> 
> export default App;
> ```
> 
> I have pin-pointed [the change request that breaks my code](https://github.com/mbrn/material-table/pull/848). It's clearly meant to fix something around page size changing but I don't understand exactly what. So my question is, was this CR incorrect or is there something wrong with my approach - in which case, what should I do instead?
> 
> Any help gratefully received.

@msb thanks for your example really helped in achieving server side pagination

**Comment by Kamranshahid243** [comment]
> Try to add this in your table options:
> `options={{ pageSize: this.state.query.pageSize }}`
> 
> And to avoid other issues it is better to use material-table approach with remote data like [here.](https://material-table.com/#/docs/features/remote-data).

Thanks buddy! saved my 3 days' work.

**Comment by jaythakur** [comment]
I have a similar issue. tried everything but did not work.

**Comment by sktanwar2014** [comment]
watch below link to learn sorting, selection, searching and pagination for table. easily can write a custom hook to manage table in react.

https://www.youtube.com/watch?v=jUwgi_bBtWI

**Comment by basitHussain1998** [comment]
> 

This code is not working on React18

Anyone can guide me how to use with functional component.
