### ISSUE TITLE
Enhancement: Init already checked row

### ISSUE THREAD

**Issue by balibou** [mbrn/material-table#96]
**Is your feature request related to a problem? Please describe.**
I would like to be able to load data with already checked rows

**Describe the solution you'd like**
Implement it 😄 (can try the ticket)

**Comment by mbrn** [comment]
You can send already init checked row with adding tableData:{checked: true} to your row-data. 

```javascript
 data: [
      { name: 'Mehmet', surname: 'Baran', birthYear: 1987, birthCity: 63, tableData: { checked: true } },
      { name: 'Mehmet', surname: 'Baran', birthYear: 1987, birthCity: 63 },
      { name: 'Mehmet', surname: 'Baran', birthYear: 1987, birthCity: 63 },
    ]
```

**Comment by sshanzel** [comment]
Is it working now? Cause i am implementing the tableData with checked property but it is not being checked.
