### ISSUE TITLE
Make fields editable in custom action.

### ISSUE THREAD

**Issue by AngelesBernardez** [mbrn/material-table#960]
I'm adding a custom action in the `actions` prop array, and I need it to edit only one of the fields. Right now I can't find the way to do this, not even making `editable` the column.
Is this possible or I'm asking for something crazy?

**Comment by raza2022** [comment]
@TheWoodStudio I am just want the same case, How did you achieve it?

**Comment by raza2022** [comment]
@TheWoodStudio I see there is a fields named `readonly` [here ](https://material-table.com/#/docs/all-props) but it's not working despite I am given it value true
