### ISSUE TITLE
warning div cannot appear as a child of tr when customising pagination component

### ISSUE THREAD

**Issue by EbenZhang** [mbrn/material-table#966]
**Describe the bug**
There is warning in the browser console when pagination component customised

```
Warning: validateDOMNesting(...): <div> cannot appear as a child of <tr>.
```

**To Reproduce**
1. Customise the pagination component with a Grid
```
<MaterialTable
    title="Multiple Detail Panels Preview"
    components={
     {Pagination: props => <Grid><Typography>Pagination Placeholder</Typography></Grid>} 
    }
...
/>
```
2. Open chrome debug console
3. Load the table
4. Notice the warning in the debug console

**Expected behavior**
No warning

**Desktop (please complete the following information):**
 - OS: Windows10 64bit 
 - Browser Chrome
 - Version 76.0.3809.100

**Additional context**
Looks like caused by the code here: https://github.com/mbrn/material-table/blob/196ef89ffd501319f160fd253e7e7758ea124f59/src/material-table.js#L428
The pagination component is inside a TableRow

**Comment by number133** [comment]
Had the same issue rewriting Pagination. 
I tried to replace it use customized `MTablePagination`.
Saw the answer [here](https://github.com/mbrn/material-table/issues/148) 
Had to use `TablePagination` from `'@material-ui/core'`
```
Pagination: props => (
                        <TablePagination className={classes.root}
                            {...props}
                        />
                    )
```

In your case I think you have to wrap it with `TableCell`
`Pagination: props => <TableCell><Grid><Typography>Pagination Placeholder</Typography></Grid></TableCell>`

**Comment by Arithmetics** [comment]
reopen please
