### ISSUE TITLE
Material-table components are unmounting and mounting after action

### ISSUE THREAD

**Issue by czaplej** [mbrn/material-table#969]
**Describe the bug**
Example: I override Toolbar component and i wanna add filter column. After i send back props to main component it's unmounting whole toolbar component and immediately mount again

**Expected behavior**
It's not suppose to unmounting component after sending back props to main component

**Screenshots**
![image](https://user-images.githubusercontent.com/29889157/62762956-9c2da100-ba8a-11e9-9362-bf3c96bad3bf.png)

**Comment by uccio83** [comment]
Any news about this issue?
I may have found the same problem adding a TextField inside the toolbar. It looses the focus on every change, hence it is unusable. 

Here it is a live example:
https://codesandbox.io/embed/materialuiexample-vokpn

**Comment by fmorgens** [comment]
I can confirm this issue the toolbar is unmounted every time the state of the main component changes

**Comment by ksuraj112** [comment]
This unmount and remount is also happening with the detailPanel component

**Comment by GabeMeister** [comment]
This is also happening for me as well! Someone halp
