### ISSUE TITLE
Handle page and rowsPerPage changes

### ISSUE THREAD

**Issue by alexxbull** [mbrn/material-table#97]
**Is your feature request related to a problem? Please describe.**
The default material-ui table pagination gives control over handling events when the page and/or rowsPerPage changes. I would like these options exposed/available in material-table as well 

**Describe the solution you'd like**
Expose page and rowsPerPage event handling as implemented by material-ui table pagination.

**Additional context**
Material-UI Table Pagination:
https://material-ui.com/api/table-pagination/

**Comment by mbrn** [comment]
Hi @alexxbull,

Why not. This is very easy and useful feature. We will implement this asap.

**Comment by chris-stormideas** [comment]
@yildirims @mbrn I have had a quick crack at this as I need these features just now

**Comment by mbrn** [comment]
> @yildirims @mbrn I have had a quick crack at this as I need these features just now

And you did :). I will check it and publish new release today.
