### ISSUE TITLE
Tooltip doesn't disappear for icon on table scroll

### ISSUE THREAD

**Issue by amit1910** [mbrn/material-table#972]
The Bug is:
when you have an list if icons in material-table and the material table maxBosyHeight is 500 or less, the tooltip wrappeed to that icon does not dissappear.

**To Reproduce**
1. Go to 'https://codesandbox.io/s/material-demo-51qgm'
2. Hover the mouse on the delete icon and start scrolling downwards or upwards
3. the tooltip goes up and down with the scroll, but the pointer has to be in the same place where the icon is

**Expected behavior**
The tooltip should disappear

**Screenshots**
![image](https://user-images.githubusercontent.com/34508451/62776886-d04c9600-ba79-11e9-88cc-296819fe3785.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version: 76.0.3809.100 (Official Build) (64-bit)

**Comment by FroggDev** [comment]
Hi, i don't know if it can help someone, but i use on some events the code

> document.activeElement.blur();

to prevent tooltip to stay visible.
