### ISSUE TITLE
How to set type Date output format?

### ISSUE THREAD

**Issue by matiasthompson** [mbrn/material-table#973]
I need to config output format, to edit some fields defined as type Date.

**Comment by kostadriano** [comment]
I don't know if it is the case, but you can make a custom output using render attribute on the header prop, like this: 

```jsx
  <Table
    headers={[
        { field: 'date', title: 'Date', render: rowData => new Date(rowData.date).toLocaleDateString() }
    ]}
  >
```

On render, you need to return a function that receives the object in that row, that function need to return a string, or a jsx attribute.

**Comment by oze4** [comment]
I am not sure if this is what you're looking for, but you can specify `date`, `datetime`, or `time` as the `type` property within `columns`:

<img width="972" alt="image" src="https://user-images.githubusercontent.com/21092343/63307715-f3b2e480-c2b4-11e9-9b5a-e3e698318a66.png">

This is the code that builds my `data`:

<img width="401" alt="image" src="https://user-images.githubusercontent.com/21092343/63307772-3a084380-c2b5-11e9-8334-2a0c0a432dba.png">

The `columns` object:

<img width="197" alt="image" src="https://user-images.githubusercontent.com/21092343/63307794-4b515000-c2b5-11e9-889a-b0587eb7421d.png">

Rendered:

<img width="588" alt="image" src="https://user-images.githubusercontent.com/21092343/63307800-55734e80-c2b5-11e9-9aaa-97ab686ba914.png">
