### ISSUE TITLE
multiple data in one field

### ISSUE THREAD

**Issue by axle21** [mbrn/material-table#977]
is there a way like i can use 2 data in one field? like i can concat datestart and dateend?

**Comment by madflanderz** [comment]
You can use custom column rendering. 
https://material-table.com/#/docs/features/custom-column-rendering

In your case something like this:
`
{title: 'Column with 2 values', render: (rowData) => rowData.firstname + " " + rowData.lastname}
`

**Comment by axle21** [comment]
Aww thanks you so much about this will try it

**Comment by thidasapankaja** [comment]
@madflanderz is there a way to render data conditionally in a column ?

**Comment by Fallen-6121995** [comment]
Hi is there a way I can add a value received from API and have a button in front of it to toggle some additional data on that button click?? Basically I want to be able to add some html code before my data in the column
