### ISSUE TITLE
Should be a option to filter on hidden fields

### ISSUE THREAD

**Issue by netbrain** [mbrn/material-table#98]
The following line:
https://github.com/mbrn/material-table/blob/master/src/material-table.js#L150

There should be a option to filter on hidden fields. Now the search functionality excludes fields that are hidden. But I would like ti include them in search, but not display them.

Should be simple enough to add a flag for this.

**Comment by mbrn** [comment]
Hi @netbrain. 

We can add this option easily. We will do it. But why you dont contribute project with this :)
