### ISSUE TITLE
Selecting row hides toolbar action menu

### ISSUE THREAD

**Issue by Dwight-D** [mbrn/material-table#980]
**Describe the bug**
When rows are selected, the toolbar.nRowsSelected message blocks the toolbar action menu. Even when options.showTextRowsSelected is false the toolbar menu still disappears, even though no message blocks it.

**To Reproduce**
1. Enable selection and disable selection text in options prop:
```
const options = {
      selection: true,
      showTextRowsSelected: false,
...
```

2. Notice that toolbar action menu is shown
3. Select one or more rows
4. Notice how toolbar menu disappears 

**Expected behavior**
Toolbar should stay regardless of row selection.
Possibly add additional option to force toolbar to stay on top, even if selection message is present (show both message and toolbar if there is space in the header).

**Screenshots**
No selection:
<img width="1626" alt="image" src="https://user-images.githubusercontent.com/25592807/62941987-9cee6c00-bdd7-11e9-9fd5-d76afb4eb3c2.png">

With selection and no selection message:
<img width="1627" alt="image" src="https://user-images.githubusercontent.com/25592807/62942012-aaa3f180-bdd7-11e9-8e8f-3ab6fc8c1e0e.png">

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Firefox Developer Edition, version 69.0b11 (64-bit)

**Comment by bableves** [comment]
Any update on this? It's a pretty annoying bug

**Comment by pixelass** [comment]
@mbrn can you please take a look at this? 

* Is this a bug or does it work as designed?
* Any suggestion how to make actions work with selections would be helpful

**Comment by mbrn** [comment]
It seems like a bug. I will take a look it. But I prioritize the issues according to their reaction count. Please take a look at readme

**Comment by pixelass** [comment]
Thank you for the fast reply. 
I need this feature but can use something custom until it's fixed.
I might look into it and try to open a PR if I can get it to work.

**Comment by pixelass** [comment]
I'm not sure if this helps the other reporters. In my case I was able to find some undocumented  feature (I might also be blind) to support my desired behavior. 

```
actions={[{
    icon: 'edit',
    tooltip: 'Edit',
    position: "toolbarOnSelect",
    onClick: (event) => {
        console.log('Clicked edit action')
    }
}]}
```

This will show the action in the toolbar only if one or more rows are selected which is exactly what I was trying to achieve.

![material-table](https://user-images.githubusercontent.com/1148334/73921817-5e3df800-48c8-11ea-9156-87e4f2290819.gif)

**Comment by corneliushka** [comment]
Up. 
After some searching and overrides attemps, I still cannot figure how change the "showTextRowSelected"... we can only set the prop true/false

**Comment by pixelass** [comment]
@corneliushka `showTextRowsSelected` is a boolean option. I'm not sure how your question relates to this issue.

You can set `showTextRowsSelected ` to false if you want to disable the text "[n] rows selected" which works as designed

**notice how the title stays in place compared to the gif I posted earlier**

![material-table_2](https://user-images.githubusercontent.com/1148334/73935029-f4314d00-48df-11ea-85b5-c4b5b09e6f14.gif)

**Comment by corneliushka** [comment]
Sorry I wrongly explained myself; I want to change color (pink to grey) & the text _x row(s) selected_, but I don't know how. showTextRowsSelected is the only prop I found that's related to this...

**Comment by pixelass** [comment]
@corneliushka This is absolutely unrelated to this issue. Please make sure you don't spam other issues. If you notice a bug, please open an issue (look for existing issues) if you need help please consider other platforms like Stackoverflow which (has more activity and faster replies).

You can find examples on styling here: https://material-table.com/#/docs/features/styling

**Comment by EdwinCloud101** [comment]
2021 and we still have this bug, did anyone get this working?

By working I mean setting the showTextRowsSelected to false and the toolbar buttons would still be visible regardless if there are checkboxes selected or not.

Thanks

**Comment by sr2399** [comment]
@pixelass  Thanks a lot. It worked But still i want show an action button only all the rows have been selected. 
Can you tell me how to do that.. Thanks in advance.

**Comment by EdwinCloud101** [comment]
@sr2399  I identified the issue, I consider that a bug  and sent a PR to the material-table repo. You might want to take a look, hoping it gets approved soon.

https://github.com/mbrn/material-table/pull/2809
