### ISSUE TITLE
Error when using Fragment for container

### ISSUE THREAD

**Issue by oscar-b** [mbrn/material-table#981]
**Describe the bug**
Specifying `React.fragment` as `Container` component fails with error: `Failed prop type: Invalid prop `components.Container` supplied to `MaterialTable`.`

**To Reproduce**
```
components={{ Container: React.Fragment }}
```
as per #119 

**Expected behavior**
Table to be wrapped in nothingness.

**Additional context**

Regression introduced here: https://github.com/mbrn/material-table/commit/8e73b1f7b0e925116f4c1b905c232f752318da1a#diff-2d70362469a78d83972d4a85388d6e70R299

**Comment by canMaih** [comment]
Try:
`Container: props => <Fragment>{props.children}</Fragment>,`

**Comment by oscar-b** [comment]
Will try tomorrow, but there’s an additional error about style being applied to React.Fragment, which isn’t allowed either.
