### ISSUE TITLE
Replace the lookup component

### ISSUE THREAD

**Issue by sajadghawami** [mbrn/material-table#983]
Hey,

is it currently possible to replace the lookup component?

thanks!

Cheers.

**Comment by ImOnMars** [comment]
Are you referring to the search component? If so, there doesn't seem to be a way to replace it, which is pretty absurd as seemingly all other components can be overriden, and it would be a possible alternative to the search callback feature request: #982, though obviously the search callback should be implemented as well.

**Comment by sajadghawami** [comment]
yeah i am! Hmm... that is unfortunate... :O

**Comment by jayarjo** [comment]
Maybe we should start making PRs. Owner seems busy, don't think it will get implemented any time soon.
