### ISSUE TITLE
Removing overflow-y: auto wrapper around table.

### ISSUE THREAD

**Issue by Flash619** [mbrn/material-table#990]
It seems like every instance of material-table is wrapped with three div's, one of which has the style `overflow-y: auto;`. I can understand how this would be desirable in the event that the content cannot fit on the page, however, its causing an issue when a field uses [react-select](https://react-select.com/home) for editing. The select drop down will bleed off the end of the table, and because the position of the drop-down box is absolute, a scroll bar will never appear and the content will be hidden from sight due to the `overflow-y: auto` style. 

![image](https://user-images.githubusercontent.com/1608113/63100739-4f8c0f00-bf3d-11e9-912d-4dea41718466.png)

For now, I must apply an ugly fix of making the drop-down be `position: fixed` which expands the row vertically so it appears within the containing divs.

Is it possible to remove the `overflow-y: auto` surrounding the table, or would anyone be able to provide a better alternative fix for this?

**Comment by Flash619** [comment]
I was able to fix this by adding the following properties to my react-select.

```javascript
menuPosition={'fixed'}
menuPlacement={'auto'}
```

I think it would still be nice to give the user control over the style of the table wrapper, though I'm not sure how much benefit their would be.

**Comment by mebuckler** [comment]
I could also really use to remove the overflow-y, when removed I can more properly handle the over flow at a higher div level so that my column headers can stay as you scroll. Is there any plan to fix this?
