### ISSUE TITLE
Attempted import error: 'makeStyles' is not exported from '@material-ui/core'

### ISSUE THREAD

**Issue by suleka96** [mbrn/material-table#991]
I am getting an error saying: 
**Attempted import error: 'makeStyles' is not exported from '@material-ui/core'** 
when I try importing material-table as:
`import MaterialTable from "material-table";
`

Shown below are the versions I am using:
"@material-ui/core": "^3.9.3",
 "@material-ui/icons": "^3.0.2",
 "@material-ui/styles": "^4.2.1",
"react": "^16.8.6",
"material-table": "^1.49.0",

**Comment by LeonKarabchevsky** [comment]
Try:

`npm install @material-ui/core@4.0.1 --save`

**Comment by DhayalanP** [comment]
It's still occuring in the latest version also

**Comment by brentN5** [comment]
That is true I am also getting this error in the latest version.

**Comment by Cipher-08** [comment]
@brentN5  it's 'makeStyles'

**Comment by Cipher-08** [comment]
I was actually declaring useStyles twice to import 'makestyles' , converting that to useStyle and 
import {makeStyles} from '@material-ui/core/styles'
helped me !!
Hope it will help someone else toooo!

**Comment by Q-dimi** [comment]
i could not find an answer for version 5 beta... looked at the documentation and still no solution.

**Comment by emrekutuker** [comment]
Try this: `import { createTheme } from '@material-ui/core/styles';`

**Comment by danielsheh02** [comment]
> Try this: `import { createTheme } from '@material-ui/core/styles';`

Just looking for a solution for "createTheme". The problem is identical. Do you know how to solve?

"Attempted import error: 'createTheme' is not exported from '@material-ui/core/styles'."

**Comment by lead123** [comment]
I'm facing the same issue in 'ToolBar'
