### ISSUE TITLE
How to style the 'No records to display'?

### ISSUE THREAD

**Issue by Jak3b0** [mbrn/material-table#992]
Hi,

is there a way to style the 'No records to display' element? I would like to change the font size and weight on it.

Thank you!

**Comment by adahmeda** [comment]
Here's how I did it:

 ` <MaterialTable        
          localization={{
                  body:{
                    emptyDataSourceMessage:<h1style={{marginTop:'6%', position:'absolute', top:'16%',  marginLeft:'-70px', textAlign:'center'}}>No records to display</h1>
                  }
                }}/>_`

**Comment by Jak3b0** [comment]
Thanks for the workaround @adahmeda! I'm wondering if there is a more official way to do it :)

**Comment by jahangirhussain** [comment]
> Here's how I did it:
> 
> ` <MaterialTable localization={{ body:{ emptyDataSourceMessage:<h1 style={{marginTop:'6%', position:'absolute', top:'16%', marginLeft:'-70px', textAlign:'center'}}>No records to display</h1> } }}/>_`
emptyDataSourceMessage only supports string type
