### ISSUE TITLE
Width of actions column

### ISSUE THREAD

**Issue by ronald-chun** [mbrn/material-table#995]
I have a problem when I have multiple actions
The width of actions column will not expand to contain all the icons
May I ask is there any props for setting this?

![Screenshot 2019-08-16 at 11 13 26](https://user-images.githubusercontent.com/6634823/63141145-35befa80-c017-11e9-94ad-d0bec669022c.png)

**Comment by emrekara37** [comment]
Hi @ronald-chun ,
Can you share codesandbox ? 
Which version of MT do you use?
Thanks

**Comment by ronald-chun** [comment]
@emrekara37 Thanks for your reply
I cant reproduce in codesandbox ([https://codesandbox.io/s/material-demo-3j2vd](https://codesandbox.io/s/material-demo-3j2vd))

But I found that the width of header of the actions column are difference in my project and codesandbox

On codesandbox:
<img width="1895" alt="Screenshot 2019-08-16 at 18 18 51" src="https://user-images.githubusercontent.com/6634823/63161476-c36c0b80-c052-11e9-93ed-c59338e7a582.png">

On my machine:
<img width="1883" alt="Screenshot 2019-08-16 at 18 20 00" src="https://user-images.githubusercontent.com/6634823/63161477-c36c0b80-c052-11e9-8bc2-c4b79702a901.png">

**Comment by ronald-chun** [comment]
Sorry is my problem.
I found that I have the style `table-layout: fixed` in my _reset.scss
It's working now after I removed this style
