### ISSUE TITLE
There is a console warning when using 'stepped' paginationType

### ISSUE THREAD

**Issue by jakeleventhal** [mbrn/material-table#999]
**Describe the bug**
When pagination type is set to `stepped`, there is a console error
<img width="1001" alt="Screen Shot 2019-08-17 at 8 50 02 PM" src="https://user-images.githubusercontent.com/15133828/63219904-d1905980-c130-11e9-9c17-4a7f97acfde7.png">

**To Reproduce**
1. Set `paginationType: 'stepped'` in options
2. See error in console

**Comment by Domino987** [comment]
Fixed with #1180

**Comment by jakeleventhal** [comment]
Closing
